### ISSUE TITLE
only rename anime episodes

### ISSUE THREAD

**Issue by networkpadawan** [SickChill/SickChill#3691]
regular shows I don´t want to rename because of getting the best subtitles according with the uploader group, but anime eps come hardcoded, so i would like to rename those for kodi to find.

**Comment by sharkykh** [comment]
Maybe if you set the custom naming pattern (for regular shows) to `%RN` - that should use the original release name.
Then just set the custom **anime naming** pattern to whatever you like/need.

**Comment by networkpadawan** [comment]
That helps and i´ve tried it but sometime (subscene/opensubtitles plugins) can´t find because it´s not in the same order the file name (pattern matching issues i think). But if I can go to the anime show and select preview rename > rename, its not possible to automate/schedule this for all anime shows?

**Comment by sharkykh** [comment]
@networkpadawan 
Like I said, you need to set a custom naming pattern for anime. That option is available from the **Post-Processing Config**, at the bottom of the **Episode naming** tab.

If you mean you want to rename all of the episodes in all of the anime shows at once,
you can do that using **Manage > Mass Update**, but I think it's quite risky...
Filter only the anime shows by typing <kbd>y</kbd> in the box under the "Anime" column header, then check the box under "Rename" and click "Submit"
## -- Do this at your own risk. --

Personally,
I'd suggest you rename each show individually using "Preview Rename"...

**Comment by networkpadawan** [comment]
I have the custom pattern for anime, but i don´t want to rename the tv shows. that is my problem:) if I enable "rename" in post processing options I rename everything (tv + anime) and I don´t want this. the other way (which is what i´ve been doing) is going to each anime show, or mass update the rename.

what I would like is way (api/script if it can´t be done in sickrage itself) to automate this everytime a new episode is downloaded.

**Comment by sharkykh** [comment]
Oh, okay. It's not currently possible to only rename anime (and not tv).
Don't know about an external script that providers episode naming options similar to SR.

**Comment by sharkykh** [comment]
For future reference:
This can be modified to be able to select which types of releases would get renamed.
Options should include: [multi-select]
* All releases [selects all - overrides selection]
* Mainstream? / Normal? / Regular? TV
* Air-By-Date
* Sports
* Anime
![image](https://cloud.githubusercontent.com/assets/10238474/25558666/0b821798-2d34-11e7-8bb5-962eb79f6db0.png)

**Comment by networkpadawan** [comment]
okay, thanks for the feedback!

**Comment by h3llrais3r** [comment]
Another option could also be adding 'Original...' option next to the 'Custom...' option in the dropdown on the 'Post processing - Episode naming' configuration page.

**Comment by sharkykh** [comment]
> Another option could also be adding 'Original...' option next to the 'Custom...' pattern in the dropdown on the 'Post processing - Episode naming' configuration page for all types.
> So even when renaming is enabled, you can still keep the original name for certain types.
> 
> Or perhaps even better: add a checkbox for the regular tv shows like there is a checkbox for all other types.
> So we can skip the regular tv shows and rename only anime.

@h3llrais3r 
In my mind, the checkboxes and select-boxes are for the **custom** naming patterns,
so that's not the right place for this option, as that would be a bit confusing.

I think my idea is clearer for the end user.
"Do you want to rename episodes?" -Yes
"Okay, episodes of which type(s)?" -[All/Normal/ABD/Sports/Anime]

**Comment by h3llrais3r** [comment]
I think there can still be some confusion...
If I take your example, I can still say: only rename Anime, but still have the custom options for the other and for anime? Or do you have a complete rework of the episode naming page in mind?

Perhaps another way is to keep it like it is now, but add a custom option for the regular shows?
So 1 general renaming pattern (like it is now which impacts everyting unless a custom one is selected) and add 1 custom option for regular shows?

**Comment by sharkykh** [comment]
@h3llrais3r Maybe a rework is a good idea, but I can't guarantee that I'll be able to actually do this. I'm very rusty

**Comment by networkpadawan** [comment]
its not possible to create a flag on pp settings?? just rename if episode has anime flag on the show?

**Comment by sharkykh** [comment]
@networkpadawan We were discussing about how the setting for it should look like. We don't want it to be confusing for users.

**Comment by networkpadawan** [comment]
@sharkykh imo, a flag/tick below the option:

> Rename Episodes? - rename episode using the Episode Naming  settings?

with the option:

> Only rename Anime episodes? - Just rename Anime episodes, keep TV episodes with original names

does not seem confusing. the under the hood work should be the more complicated part i think

**Comment by sharkykh** [comment]
@networkpadawan We want to support every type of episode.
That means Air-By-Date and Sports as well.

**Comment by networkpadawan** [comment]
@sharkykh could it be a tick per category?
