### ISSUE TITLE
Windows character encoding

### ISSUE THREAD

**Issue by chwynn** [SickChill/SickChill#3696]
### Before submitting your issue:

Branch/Commit: Master/Don't know where to find this
OS: Windows 7
What you did: Anything involving any character past ASCII-128
What happened: Sickrage behaves weirdly. Inserts about 10-20 characters in the ASCII-218-256 range, in place of the original character, and also prints the erroneous string over the close button for the view, and all buttons fail to work.
What you expected: It to work like a normal application since Extended ASCII was introduced about when the big bang happened and recognise that there are more than 128 characters.

Other Crap:
Clicking shutdown displays a message that it will shutdown, then seconds later it restarts. Had to force a shutdown with process explorer, by ending the Non-sucking service manager. Ironic name, cause It manages that service so hard you cant shut it down when you want to.
Registered with your forums a day ago. Still no email from them.
Webpage fails to load when adding more than 10 shows, after the 10th show is added.
I installed this to replace sickbeard, which has been working fine, but after a temporary hard drive failure it marked all downloaded shows as ignored, which would be a hassle to fix. I came to sickrage to fix this, and it turns out that it has the same behaviour. 
Refuses to actually queue anything in SABnzbd, says it can't find any results. Has the same search providers ticked as sickbeard does, plus a bunch of torrent ones Never added a torrent either. I swapped it for sickbeard, within 5 mins, the 12 missing episodes were in my SAB queue.

I presume that sickrage is just for people that have about 15 TV shows they want to download. Light users that want a pretty interface before any other considerations, because throwing 500 shows and 50,000 media files at it totally broke it. Sickbeard was fine.

I'm going back to sickbeard. I don't care that it hasn't been updated in years, it hasn't been updated with flashy do-nothing features that make for a pretty interface but make the application experience slow and suck. sickrage is just bloated. Mayby it would be better if I was part of the Linux master race.
Logs:
```
2017-05-01 10:59:09 DEBUG Thread-28 :: git ls-remote --heads origin : returned successful
2017-05-01 10:59:07 DEBUG Thread-28 :: Executing git ls-remote --heads origin with your shell in C:\SickRage\SickRage
2017-05-01 10:59:07 DEBUG Thread-28 :: git symbolic-ref -q HEAD : returned successful
2017-05-01 10:59:07 DEBUG Thread-28 :: Executing git symbolic-ref -q HEAD with your shell in C:\SickRage\SickRage
2017-05-01 10:59:07 DEBUG Thread-28 :: git config remote.origin.url https://github.com/SickRage/SickRage.git : returned successful
2017-05-01 10:59:07 DEBUG Thread-28 :: Executing git config remote.origin.url https://github.com/SickRage/SickRage.git with your shell in C:\SickRage\SickRage
2017-05-01 10:54:48 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
```

**Comment by sharkykh** [comment]
>Clicking shutdown displays a message that it will shutdown, then seconds later it restarts. Had to force a shutdown with process explorer, by ending the Non-sucking service manager. Ironic name, cause It manages that service so hard you cant shut it down when you want to.

This is a known issue when running as a service.
You can shutdown/start SickRage using [these links in your start menu](https://cloud.githubusercontent.com/assets/10238474/25532744/0ad8b3f4-2c37-11e7-84c0-5d682840f48e.png)

>Registered with your forums a day ago. Still no email from them.

We don't have any forums. The forums you found are related to another fork of SickRage.
