### ISSUE TITLE
Sickrage QNAP + rTorrent Unable to connect

### ISSUE THREAD

**Issue by MSBIZ** [SickChill/SickChill#3702]
Hi,

I'm install Sickrage on my QNAP TVS 471, and rTorrent but i have this message when i try to config rTorrent on sickrage. when i click on test connection i have this message : Error: Unable to connect to rTorrent

My rtorrent is install 6009 port

http://LOCALIP:6009/
i try whit https but same problem

i try whit scgi  : 
scgi://localhost:6009 not working.

What is the problem ?

Thank you

**Comment by sharkykh** [comment]
@MSBIZ 
**I don't use rTorrent, but I'll try to assist**

1. Enable debug logs
> 1. Open SR interface
> 2. Menu General Settings > Advanced Settings
> 3. Enable 'Enable debug'

2. Test the connection again.

3. Go to http://LOCALIP:8081/errorlogs/viewlog/?min_level=10

4. Copy and post the logs here between two ` ``` ` tags
**(DO NOT POST ANYTHING THAT CONTAINS YOUR LOGIN INFORMATION OR API KEY)**
