### ISSUE TITLE
Sms Free Mobile

### ISSUE THREAD

**Issue by Denaz** [SickChill/SickChill#3709]
Branch: master
Commit: 53474edc0c971aa678bbbe0e925744963c8f47e7
Version: v2017.05.02-1
Database Version: 44.0

First im sorry for my english, ive an issue, ive put the good seetings in "Free Mobile" and when i send a test , i have it.
But when a download is ending, i dont receive any notifications.

**Comment by sharkykh** [comment]
@Denaz

When you click test, you get an SMS on your phone?
Just not when you download?
Just to make sure, check that the option for it is selected, then click **Save Changes**:
![image](https://cloud.githubusercontent.com/assets/10238474/25783294/756c5798-3362-11e7-8877-fdb797852b93.png)

If you're still not getting messages, do the following steps:
1. Enable debug logs
> 1. Open SR interface
> 2. Menu General Settings > Advanced Settings
> 3. Enable 'Enable debug'

2. Wait for a download to finish

3. Go to http://localhost:8081/errorlogs/viewlog/?min_level=10

4. Look for logs about `Free Mobile` (try searching for it if you don't see it right away)
