### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-298305 :: [Usenet-Crawler] :: [53474ed] Unable to load url https://www.usenet-crawler.com/getnzb/32f3e87e7c4905321342c12610de9a7f.nzb&i=175534&r=99745873e8a52acdded839c09a63d984, can't download season NZB

### ISSUE THREAD

**Issue by gkeen316** [SickChill/SickChill#3715]
### INFO
Python Version: **2.7.7 (default, Jun  1 2014, 14:17:13) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@53474edc0c971aa678bbbe0e925744963c8f47e7
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-298305 :: [Usenet-Crawler] :: [53474ed] Unable to load url https://www.usenet-crawler.com/getnzb/32f3e87e7c4905321342c12610de9a7f.nzb&i=175534&r=99745873e8a52acdded839c09a63d984, can't download season NZB
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Gitarski** [comment]
I don't believe this is an issue with SickRage.

Did you try the URL yourself?  Has this been retried again later?  If possible, retry it on the same machine where SickRage is running.  Maybe the nzb provider was having an issue at the time.  FYI, I tried to do the same thing and then deleted it...it worked properly.

**Comment by gkeen316** [comment]
Yes I believe it was a Usenet crawler issue. It works fine now.

**Comment by WebSpider** [comment]
If you feel the issue has been solved, please feel free to close it in github :)
