### ISSUE TITLE
Quality pill not rendering correctly with propers

### ISSUE THREAD

**Issue by psylenced** [SickChill/SickChill#3746]
**Branch/Commit:** master
**OS:** win 10
**What happened:** proper gets pill style, quality doesn't
**What you expected:** both to get pill style

![quality-pill](https://cloud.githubusercontent.com/assets/1967906/25930614/7c1b5e78-364a-11e7-9b77-8c8d37f94c16.png)

**Comment by sharkykh** [comment]
Maybe that only happens with Snatched status? It renders well when it's in Downloaded status.
