### ISSUE TITLE
defunct python?

### ISSUE THREAD

**Issue by mgaulton** [SickChill/SickChill#3750]
I was using an init script and tried a couple variations so i don't know if that has anything to do with this but...

I keep noticing that my web UI stalls, its responding, says the ports in use if i restart SB etc but its not responding with full web request results, just spins.
checking processes, I can see defunct python processes. This seems to be the culprit but i can't explain why this is happening. it didn't happen in the past. I moved to new hardware about 2 months ago.
reboot and it works again but some random time later, it happens again.

2 core, 16 gig ram, SSD boot / 7200rpm data disk, running Opensuse 42.2 
Running lasted git pull.
Using nzbToMedia with SABnbd and utorrent.

**Comment by sharkykh** [comment]
Anything in the logs? Don't forget to enable debug logs and http server logs in the config first

**Comment by mgaulton** [comment]
I've been monitoring and have not yet been able to find anything in the logs that is meaningful. I do notice that if i run some python code to do API calls, the UI becomes unresponsive to the browser, but once the APIs stop, it recovers after a small period. I don't know if this would be related or not.
I haven't been able to get a cause > effect scenario pinned down.

**Comment by mgaulton** [comment]
I'm still experiencing this but have yet to find something in the logs. I was thinking it might be some python api stuff i do so that was all disabled. Its getting frustrating now as nzbToMedia is failing. Everything works except the web ui when this happens.

**Comment by mgaulton** [comment]
@sharkykh Python 2.7.13 running latest git pull on opensuse 42.2

**Comment by sharkykh** [comment]
Have you tried running it without the init script? If it works well, that means your init script configuration might be incorrect.

**Comment by mgaulton** [comment]
Yes, i removed the init and have a bash script to call the comment to start it. I've noticed no difference
I rebooted about an hour ago and within an hour, it went dead again.

**Comment by sharkykh** [comment]
@mgaulton Maybe try running this not as a daemon?

**Comment by mgaulton** [comment]
so I've tried the following:
rebooted (multiple)
removed the init script and replaced with a shell
shell runs basically : cd /opt/SIckBeard-tvrage ; /opt/SickBeard-tvrage/SickBeard.py 
I'm now trying to pipe this to a file seperate from the logs themselves which aren't enlightening
did a backup ini/db > reclone > restore

so i'll review the piped file when i notice it hang again, see if that gives me anything more.

**Comment by mgaulton** [comment]
randomly, i see this, but piping to a file doesn't seem to have worked, its 0 byte
017-06-28 20:59:26 DEBUG    TORNADO :: API :: show: cur_kwargs {'tvdbid': '113131'}
2017-06-28 20:59:26 DEBUG    TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
2017-06-28 20:59:26 DEBUG    TORNADO :: API :: all args: '()'
2017-06-28 20:59:26 DEBUG    TORNADO :: API :: all kwargs: '{'cmd': 'show', 'tvdbid': '79228'}'
2017-06-28 20:59:26 DEBUG    TORNADO :: API :: show: cur_kwargs {'tvdbid': '79228'}
2017-06-28 20:59:26 ERROR    TORNADO :: [96b53de] API :: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 129, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 201, in call_dispatcher
    cur_out_dict = to_call.run()  # call function and get response
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 1864, in run
    "season_list": CMDShowSeasonList((), {"indexerid": self.indexerid}).run()["data"],
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 2456, in run
    season_list.append(int(row[b"season"]))
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by sharkykh** [comment]
>shell runs basically : cd /opt/SIckBeard-tvrage ; /opt/SickBeard-tvrage/SickBeard.py
...
piping to a file doesn't seem to have worked, its 0 byte

Do you run it with any arguments?

Also, `cd` to the SickRage folder isn't necessary, so you don't need a bash script, just run it directly from shell and pipe to `> ~/sickrage.log` for example.

**Comment by mgaulton** [comment]
No arguments no. the cd is just my paranioia method of making sure apps don't start in folders and leave litter behind, so i make sure they start in their install directory.

I'll try running it naked, see what happens.

I've been playing a bit and the UI definitely spins and spins, not really timing out in the browser / nzbToMedia for some reason but some little python scripts i run to make quicky api calls are working. Which i find interesting.

**Comment by mgaulton** [comment]
seems like running just the py isn't working either but > /tmp/sickrage.txt is still creating a 0 byte, not sure why.
i rebooted, ran the commandline, a while later my monitor said it was down.
rebooted, ran command again, a while later, it happened again.
Not sure where to go now.

**Comment by sharkykh** [comment]
@mgaulton **Sorry**, I didn't check before telling you to do that. It doesn't work for me either.
You could just run it (without piping the output) and leave the shell window open, then review the console logs after.

**Comment by mgaulton** [comment]
trying this https://linux-tips.com/t/how-to-record-a-linux-session/145

**Comment by mgaulton** [comment]
So script worked and I know have a session log which is a dump of the console but i'm not seeing anything different than what I've been seeing in the SR logs themselves. 
Grepping "error" and "failed" in the logs isn't showing anything new. Manual browse of it, didn't see anything that jumped out either.

I intermittently see Trakt error, which i didn't think was related.
15:11:13 DEBUG::TRAKTCHECKER :: Could not connect to Trakt. Error: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=30)

Lots of these too
16:04:55 ERROR::TORNADO :: [96b53de] API :: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 129, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 201, in call_dispatcher
    cur_out_dict = to_call.run()  # call function and get response
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 1864, in run
    "season_list": CMDShowSeasonList((), {"indexerid": self.indexerid}).run()["data"],
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 2456, in run
    season_list.append(int(row[b"season"]))
TypeError: int() argument must be a string or a number, not 'NoneType'

server6:~ # ps -efl | grep defunct
0 Z root     20544 20456  6  80   0 -     0 task_d 15:05 pts/1    00:05:24 [python2.7] <defunct>
1 Z root     29680  1988  5  80   0 -     0 task_d 16:23 ?        00:00:00 [/usr/libexec/we] <defunct>
0 S root     29939  5969  0  80   0 -  2833 pipe_w 16:23 pts/3    00:00:00 grep --color=auto defunct
server6:~ # pstree -s -p 20544
systemd(1)───sshd(1671)───sshd(3553)───bash(3568)───script(20454)───bash(20456)───python2.7(20544)───{python2.7}(15476)
server6:~ # pstree -s -p 20456
systemd(1)───sshd(1671)───sshd(3553)───bash(3568)───script(20454)───bash(20456)───python2.7(20544)───{python2.7}(15476)

**Comment by mgaulton** [comment]
ok so i've been watching this closely and its still early but i may have narrowed down something.
I use utserver linux (its old but does exactly what i want, i have api scripts built around it that I haven't found for other clients) and it seems THAT may be causing a defunct python, which for some reason, takes out JUST the SR web UI (this also seems to stop most scheduled tasks)
I tried turning off the nzbToMedia call in uTorrent and that seem to not always make a difference.
I tried running SickGear just to play devils advocate, same issue.
renamed utserver to disable, and so far, the web UI seems stable where before it was dead within an hour.
Not sure why this is only starting recently, i've been running this same config for years on the utserver side. I'm stumped.
for the day, i'm not going to run utserver, see how that goes over. 
Sab + nzbToMedia is working fine from what i can see.

**Comment by OmgImAlexis** [comment]
Do you use anything that hits the Sickrage API? If you're using something like ShowsRage it may be crashing the web API somehow which could be stalling Python.

**Comment by mgaulton** [comment]
And the UI died out again, with no utserver running. so i think that's not it.

I had some python stuff hitting the API, but nothing else should be. nzbToMedia calls in to process, my pythons are renamed, i even removed the Chrome extension i was using, to be on the safe side. I was thinking the same thing but i can't pin down what it is.

**Comment by OmgImAlexis** [comment]
I noticed the `SIckBeard-tvrage` are you running this on a fresh install or an old install that's been updated? Maybe try backing up your install, installing a new copy and then importing your backup file.

**Comment by OmgImAlexis** [comment]
@sharkykh could you have a look at https://github.com/SickRage/SickRage/issues/3750#issuecomment-311833013. It seems like @mgaulton may have a broken show in their DB.

**Comment by mgaulton** [comment]
@OmgImAlexis  on and old updated folder then to troubleshoot, i backed up the .db and .ini, deleted the git and repulled fresh master, then restored dbs. Problem has persisted throughout.

**Comment by mgaulton** [comment]
@OmgImAlexis I'm trying a sqlite dump to a new db file, i know that's fixed some issues in the past.

**Comment by mgaulton** [comment]
nope, doesn't appear that solved it by dumping to a new sqlite file. its hung again.

**Comment by OmgImAlexis** [comment]
Can you put your whole log file into a [gist](https://gist.github.com/) and post it here?

Also can you try running it for a while without anything connecting to it over the API.

**Comment by mgaulton** [comment]
i can run it as the only active process easily enough. To my knownledge, nothing else API beyond nzbtomedia should be active.
Log files coming up.

**Comment by mgaulton** [comment]
I'm still monitoring but i noticed that even though only nzbtomedia should be running (cron is stopped, only downloader tasks running etc) that a bunch of the below showed up. nTM is using user/pass so its not that. i renamed the folder my python scripts were in. 
My thought now is that I have a flexget config that will scrape for missing episodes. I've now disabled that as well. hopefully the localhost stuff is related to that.

15:09:18 DEBUG::TORNADO :: API :: all kwargs: '{'cmd': 'show', 'tvdbid': '73739'}'
15:09:18 DEBUG::TORNADO :: API :: show: cur_kwargs {'tvdbid': '73739'}
15:09:18 DEBUG::TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
15:09:18 DEBUG::TORNADO :: API :: all args: '()'
15:09:18 DEBUG::TORNADO :: API :: all kwargs: '{'cmd': 'show', 'tvdbid': '295684'}'
15:09:18 DEBUG::TORNADO :: API :: show: cur_kwargs {'tvdbid': '295684'}
15:09:18 DEBUG::TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
15:09:18 DEBUG::TORNADO :: API :: all args: '()'
15:09:18 DEBUG::TORNADO :: API :: all kwargs: '{'cmd': 'show', 'tvdbid': '113131'}'
15:09:18 DEBUG::TORNADO :: API :: show: cur_kwargs {'tvdbid': '113131'}
15:09:18 DEBUG::TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
15:09:18 DEBUG::TORNADO :: API :: all args: '()'
15:09:18 DEBUG::TORNADO :: API :: all kwargs: '{'cmd': 'show', 'tvdbid': '79228'}'
15:09:18 DEBUG::TORNADO :: API :: show: cur_kwargs {'tvdbid': '79228'}
15:09:18 ERROR::TORNADO :: [96b53de] API :: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 129, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 201, in call_dispatcher
    cur_out_dict = to_call.run()  # call function and get response
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 1864, in run
    "season_list": CMDShowSeasonList((), {"indexerid": self.indexerid}).run()["data"],
  File "/opt/SickBeard-tvrage/sickbeard/webapi.py", line 2456, in run
    season_list.append(int(row[b"season"]))
TypeError: int() argument must be a string or a number, not 'NoneType'
15:09:18 DEBUG::TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
15:09:18 DEBUG::TORNADO :: API :: all args: '()'
15:09:18 DEBUG::TORNADO :: API :: all kwargs: '{'cmd': 'show', 'tvdbid': '81466'}'
15:09:18 DEBUG::TORNADO :: API :: show: cur_kwargs {'tvdbid': '81466'}
15:09:18 DEBUG::TORNADO :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED
15:09:18 DEBUG::TORNADO :: API :: all args: '()'
15:09:18 DEBUG::TORNADO :: API :: all kwargs: '{'cmd': 'show', 'tvdbid': '92171'}'
15:09:18 DEBUG::TORNADO :: API :: show: cur_kwargs {'tvdbid': '92171'}

**Comment by mgaulton** [comment]
I just noticed it bombed again. No Flexget, no python scripts, only nzbTM.

https://gist.github.com/mgaulton/cc6fb92a299150b4ce3915ae020e74af/raw/d7c7ed9f1ad2c00f53e37b7347604a9f7c5409fa/sickrage.log

**Comment by mgaulton** [comment]
Oh and for good measure, i had changed the API key to prevent API access prior to this run.

**Comment by mgaulton** [comment]
hmmm and it recovered after the Trakt check queued new shows to add. I'll leave it longer.

**Comment by OmgImAlexis** [comment]
Ah, any chance you're adding a show without any seasons?

**Comment by mgaulton** [comment]
hmm, well I use the trakt integration. I've been having issues adding certain shows. Perhaps that's it? Marvel's the Punisher for example is on Trakt but apparently nothing on thetvdb so SR rejects it and it gets removed through the integration. I can turn off the trakt integ and see what happens. It went for a couple hours last night but was down when i got into the office this morning.

**Comment by mgaulton** [comment]
OK, trakt disabled, monitoring.

Is there a limit to how many things can be doing api at the same time? i have 2 instances of nTM, one for utorrent and one for SAB because they download to different locations. Any chance its getting clobbered?

**Comment by OmgImAlexis** [comment]
The API should be fine as it's non-blocking. I think the problem is there's a bug in the API and it's locking up the web thread which handles the API and web view.

I'll see if I can get to fixing this tomorrow.

**Comment by mgaulton** [comment]
so with Trakt and Subtitles disabled, seems to have done it again.

**Comment by mgaulton** [comment]
I've turned off anidb checking. I noted it was timing out but the recovered after. Eliminating stuff :)

**Comment by mgaulton** [comment]
so I don't actually have the browser open or anything, would this be nTM accessing it using user/pass instead of API?
2017-07-05 14:12:50 INFO     TORNADO :: User logged into the SickRage web interface

**Comment by mgaulton** [comment]
nope, still happens, nothing really seems consistently to be causing it.

**Comment by mgaulton** [comment]
So currently i'm in test cycle 2 for my current config as below. First run this morning died out as well. 
no Trakt
no anidb
no Emby
No AutoProc
no subs
disable service check bash that attempts a sb.ping periodically
changed API key so nothing can connect other than nzbToMedia with username/password

**Comment by mgaulton** [comment]
and it seems to have done it again :(

**Comment by mgaulton** [comment]
So i'm wondering now, having noticed that it seems to lose the UI after a Move operation, would a slow network operation cause the UI to stall? I have the one NAS that for some reason takes longer than the others for transfers (never noticed it before, but i've been paying more attention).

**Comment by mgaulton** [comment]
NAS is resolved (WDSAFE mount to other NAS, not sure wtf that was about was causing high load ~12), monitoring now.

**Comment by OmgImAlexis** [comment]
I don't think anything should be causing Python to die because of a slow network connection but I could be wrong. @miigotu any ideas on this?

**Comment by mgaulton** [comment]
So my server decided to eat itself (i think i had a runaway proc and nuked a number of important files :( )
I rebuild it the other night and noted that SR seemed more stable *crosses fingers*
i then installed a few python modules and it became unstable again.
I removed those modules last night, and its still running this morning from what I can tell. Any way to get an uptime on SR?

I'm not sure which module it might have been, but this is the list i removed. bs4 i ended up having to reinstall later as it broke my flexget :)
python-pyinotify python-beautifulsoup4 python-PySocks python-M2Crypto

**Comment by mgaulton** [comment]
And just to update you on the platform
  SickRage Info:
Branch: master
Commit: 832ccb445f8eaadef783eddb51880d67d1a77b3d
Database Version: 44.0
  Python Version: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
  SSL Version: OpenSSL 1.0.2j-fips 26 Sep 2016
  OS: Linux-4.4.79-19-default-x86_64-with-SuSE-42.3-x86_64
  Locale: None.None
