### ISSUE TITLE
Don't delete root folder

### ISSUE THREAD

**Issue by FernandoMiguel** [SickChill/SickChill#3757]
Branch/Commit: v2017.05.10-1
OS: linux
What you did:
manually run post process

What happened:
since there was a tv show file in the root folder, the root folder was deleted after being empty.
this folder is used to process finished downloads

What you expected:
for subfolders to be deleted, but the root one to be kept.

**Comment by sharkykh** [comment]
Did you set this folder as the post-processing folder in the post-processing config?

**Comment by FernandoMiguel** [comment]
@sharkykh yes.

**Comment by sharkykh** [comment]
Could you post the debug logs please? Most of the answers are in there.

**Comment by FernandoMiguel** [comment]
I'll try to reproduce and gather the logs.
thanks for the quick reply

**Comment by Yaruru** [comment]
It just happened to me, all my series went to neverland... I checked "delete files and folders" but it's the first time it deletes the root folder
