### ISSUE TITLE
[APP SUBMITTED]: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by MarioCaires** [SickChill/SickChill#3768]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@c56813972dbd79b774fab271b990881af464aa7a
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [c568139] [Errno 22] Invalid argument
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by sharkykh** [comment]
@MarioCaires  Please provide logs of the error.

**Comment by cepelkey** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/2fa6f6dbfa28b786cd2014ff1f276ae4
### ERROR
```
POSTPROCESSOR-AUTO :: [807c5ae] [Errno 22] Invalid argument
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/7a99cf5cdb9205c5f4e06cf32b127318
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] [Errno 22] Invalid argument
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
Link to Log: https://gist.github.com/ba2ae5eddc3120503cdf666ee6a1919f
### ERROR
```
POSTPROCESSOR-AUTO :: [51328d1] [Errno 22] Invalid argument
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
Link to Log: https://gist.github.com/ee4b84cbbbc928f74932078f498b9d95
### ERROR
```
POSTPROCESSOR-AUTO :: [51328d1] [Errno 22] Invalid argument
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
[Errno 22] Invalid argument
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Unable to copy file from C:\Users\snapp\Completed\Marvel.Studios.Assembled.S01E05.The.Making.of.What.If.720p.WEB.h264-KOGi[rarbg]\Marvel.Studios.Assembled.S01E05.The.Making.of.What.If.720p.WEB.h264-KOGi.mkv to \\storage\storage\Television\ASSEMBLED\Season 01\Marvel.Studios.Assembled.S01E05.720p.WEB.DL-.mkv: [Errno 22] Invalid argument
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
