### ISSUE TITLE
SickRage forgetting custom NZB provider

### ISSUE THREAD

**Issue by jangrewe** [SickChill/SickChill#3772]
Branch/Commit: master/c56813972dbd79b774fab271b990881af464aa7a (v2017.05.10-1)
OS: Linux
What you did: nothing
What happened: Custom NZB provider disappeared
What you expected: Custom NZB provider still there
Logs:
```
<nothing that would indicate any config change, then suddenly:>
2017-05-19 22:49:53 INFO     SEARCHQUEUE-MANUAL-248841 :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
```
This already happened to me yesterday, and i added my custom NZB provider again. Now today it's gone, again!

**Comment by sharkykh** [comment]
* **Make sure you click "Add" then "Save Changes".**
* After you save, go to http://local:8081/config/providers/ and select the new provider, then click "Save Changes".

**Comment by jangrewe** [comment]
@sharkykh Okay, my fault for not being more explicit, i had something like your comment coming ;-)

So: I've been running SickRage for years, starting with SickBeard, and do know how a "Save" button works. After adding my Custom NZB Provider, SickRage uses it for its searches and successfully find and downloads NZBs, but then at some point it forgets about it again. There is nothing happening on filesystem-level, i rarely login on my box (which is dedicated and runs 24/7).

Again, to be explicit: This is not a user error. SickRage "forgets" the Custom NZB Provider after successfully using it for some time.

**Comment by sharkykh** [comment]
Do you have debug logging enabled in the configuration?
Maybe something is logged but SickRage is filtering it based on that config var?

**Comment by jangrewe** [comment]
I've switched it on now, but i was hoping that maybe there was a recent commit affecting this that would spring to mind...

**Comment by sharkykh** [comment]
@jangrewe Last one was about a month-and-a-half ago
https://github.com/SickRage/SickRage/commits/master/sickbeard/providers/newznab.py
