### ISSUE TITLE
New Provider: privatehd.to

### ISSUE THREAD

**Issue by MoltenTesseract** [SickChill/SickChill#3773]
With the death of Freshon.TV (TVTorrents), people have been flooding to other trackers that have opened their doors. One of these is: privatehd.to

Can we please get support added for this?

**Comment by sharkykh** [comment]
This is a private tracker, invite only. Can't add support without an account.

If you have an account, check if they have an API with documentation? If so, post the information here.

**Comment by beschoenen** [comment]
https://github.com/Jackett/Jackett/blob/f2def1f615a2df8cb929860992c22aec95906c4f/src/Jackett/Indexers/Abstract/AvistazTracker.cs

This is the implementation of Jackett for Avistaz family, which PrivateHD is part of.
Looks like they are just scraping the HTML.

AFAIK  they don't have an API, but the support custom rss feeds with filters.
