### ISSUE TITLE
Network location based post-processing not working properly? (Windows/UNC)

### ISSUE THREAD

**Issue by xhorntail** [SickChill/SickChill#3802]
Debugging was enabled during the log clips posted below.
**Branch/Commit:** master/10a0c3012e600ed61cdff6a6108b2bb55062907b
**OS:** Windows 10
**What you did:** Tried to manual post-process with network location. Of note, the service is being ran as a local user with access to the share. This worked fine prior to an update ~20-30 commits back.
**What happened:** Received error `Unable to figure out what folder to process. If your downloader and SickRage aren't on the same PC make sure you fill out your TV download dir in the config.` This happens regardless of Move/Copy.
**What you expected:** Usual post processing.
**Logs:**

**sickrage.log:**
```
2017-05-24 16:06:06 INFO     Thread-27 :: Beginning manual post processing task: \\TS5400DB22\Share\Torrents - Downloaded\SickRage
2017-05-24 16:06:06 DEBUG    Thread-27 :: Unable to figure out what folder to process. If your downloader and SickRage aren't on the same PC make sure you fill out your TV download dir in the config.
2017-05-24 16:06:06 INFO     Thread-27 :: Manual post processing task for \\TS5400DB22\Share\Torrents - Downloaded\SickRage completed
```

**General Configuration -> Show root directories:**
![screenshot_3](https://cloud.githubusercontent.com/assets/20708358/26429249/2212edde-40a3-11e7-82b6-6c3a1019362f.png)

**Manual post processing settings:**
![screenshot_2](https://cloud.githubusercontent.com/assets/20708358/26429190/c8c3ca8c-40a2-11e7-8924-847ffae95711.png)

**Manual post processing results:**
![screenshot_3](https://cloud.githubusercontent.com/assets/20708358/26429224/f18a634a-40a2-11e7-8083-6774010ff235.png)

**Comment by sharkykh** [comment]
Try using your IP instead of computer names.

**Comment by xhorntail** [comment]
Ok, so this seemed to have resolved itself for a while.
However, I had the issue pop again today during regular use, all of a sudden it wouldn't auto-populate my NAS directories while typing them in.
Service is ran as local user, I even restarted it.
Drive is mounted local, and the UNC path works fine in explorer as well.

For some reason, using the IP of the drive does work. No idea why it loses the ability to resolve UNC for days at a time.

**Comment by sharkykh** [comment]
>```2017-06-28 16:44:20 WARNING POSTPROCESSOR-MANUAL :: A path is required for the destination. Check the root dir and show locations are correct for Home of the Brave (I got '\\TS5\Share\Media\Plex\TV\Walker, Texas Ranger')
>```

The TS5 comes from the TV root dir (General Config or show-specific config for "Walker, Texas Ranger")

**Comment by xhorntail** [comment]
You're entirely correct. I didn't realize that the shows each retain their original path.
After going to the show, and updating the directory to the IP based location, it updated quite dandy. Thank you so much for a solution to that!

I still think this is a bug however, the UNC paths shouldn't lose resolution randomly, especially when the host OS resolves it just fine. Users should be forced to, or at least heavily prompted to, us the IP based location on Windows based installs. Otherwise object permanence is lost. This could be a Python issue, a hostname/local DNS issue, or what have you, but until it's resolved I feel like named named UNC paths should be resolved to the correlating IP at the time of entry, or simply not be accepted at all when operating on Windows.

Thanks again for the interim solution though!
Also of note, I'm running a Cisco 2504 with 3 AP's on FlexConnect, and at the same time this hit a fault my three Chromecasts refused to show up through the Android Cast API on any apps. I still haven't resolved that and can't say that it's causation over correlation, it's worth noting however.
