### ISSUE TITLE
[Feature Request] Episode gaps screen

### ISSUE THREAD

**Issue by psylenced** [SickChill/SickChill#3810]
Sometimes for some reason episodes get missed and lost when managing large collections and there are a few seasons that have episodes that have been gaps of un-downloaded episodes with future episodes downloading after it.

What I suggest is a new screen called "episode gaps" which shows any show/season that has a gap in one of the episode downloads.

I wrote the following query:
```
select distinct t1.*
from tv_episodes t1
inner join tv_episodes t2 on t1.showid = t2.showid and t1.season = t2.season and t1.episode < t2.episode and t1.location = '' and t2.location <> '' 
where t1.season <> 0
order by t1.showid, t1.season desc, t1.episode desc 
```

What this does is finds any season that has a location (ie. filename) that has an earlier episode that is missing a location. This then returns "gaps" of missing downloads.

It works on a season basis, so wont return gaps for earlier seasons, unless an episode has been downloaded in that season.

Not sure what the screen layout should be, whether it models off schedule screen or backlog overview. If it was backlog, it'd need clicks through to the show and possibly a search column, so the schedule screen is probably the best fit.

**Comment by miigotu** [comment]
If you have the skill, you are welcome to add this if you want.

**Comment by psylenced** [comment]
Is someone able to look at this on my behalf? My python is limited to small changes and not larger features.
