### ISSUE TITLE
Download Station error

### ISSUE THREAD

**Issue by Ombouwleusden** [SickChill/SickChill#3817]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: MASTER
OS: SYNOLOGY
What you did: NOTHING IT WAS A SICKRAGE UPDATE
What happened: DOWNLOAD STATION FAILED TO CATCH TORRENTS, i cant test anymore too
What you expected: THAT DS STATION DOWNLOAD THE TORRENTS

SickRage Info:
Branch: master
Commit: 10a0c3012e600ed61cdff6a6108b2bb55062907b
Version: v2017.05.23-1
Database Version: 44.0
  Python Versie: 2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]
  SSL Versie: OpenSSL 1.0.2j 26 Sep 2016
  OS: Linux-3.10.35-x86_64-with-glibc2.2.5
  Taal: en_US.UTF-8

Logs:
```
2017-05-31 17:30:45 WARNING SEARCHQUEUE-DAILY-SEARCH :: DownloadStation: Authentication Failed
```

**Comment by sharkykh** [comment]
I don't use DS, but it says "Authentication Failed". Make sure the client username & password you entered in the settings are correct. Check against your DS configuration. Try re-entering them and saving.

**Comment by sharkykh** [comment]
Also, after reading a little into an issue with the same error message (#1257)...
**Have you recently started using _second factor authentication_?**

**Comment by sharkykh** [comment]
@Ombouwleusden Waiting for your response.
