### ISSUE TITLE
Episodes naming from file system

### ISSUE THREAD

**Issue by doodyd** [SickChill/SickChill#3821]
I have searched on this in help and found nothing useful (please point me at anything I may have missed), and have also searched on here for other similar issues but found only closed ones.

So...

Is there any way I can fix this episode naming problem (see image) without having to rename all my files?  I want a human readable file naming system (without SxxEyy names, that are not very friendly), plus this schema I am using is already working with Plex and the TV-Series plugin of Mediaportal.

This occurs with any series and with every episode name that begins with a number.
![image](https://cloud.githubusercontent.com/assets/29137584/26711796/1f6fb0a2-47a2-11e7-83c1-e367df846918.png)

I realise this is not the recommended file naming schema, but it is one I have used for many, many years, and is not one I wish to abandon.  Again, the fact it works perfectly well with other media software suggests I should not need to change my system.

Any thoughts are appreciated.

**Comment by skalvaro** [comment]
@doodyd I'm not sure but my guess is you can change it in the Post Processing settings.
On the Episode Naming tab Select 'Custom...' for the naming pattern and then fill in something like this:
`Season %0S/%0E %EN`
That should do the trick.
