### ISSUE TITLE
qbittorrent: Unable to send Torrent 

### ISSUE THREAD

**Issue by ragtag-fleet** [SickChill/SickChill#3832]
Hi,

Since updating to qbittorrent v3.3.13, I am unable to send to webui. I think something has changed in webui. Authentication is fine i have tested it, changed it and verified it by logging into the webui. 

Branch/Commit: master/10a0c3012e600ed61cdff6a6108b2bb55062907b
OS: Windows 10
What you did: Manual search eposide to transfer via webui to qbitorrent
What happened: torrent not send to qbitorrent webui
What you expected: torrent send to qbitorrent webui
Logs: https://pastebin.com/pJUPeimj

**Comment by sharkykh** [comment]
https://github.com/qbittorrent/qBittorrent/commit/087856d3d8d6d77881c3d8378a95d80d693af2dd
This was implemented around that version.

We need to account for that change... I look into that, but I don't use qBT.

**Comment by jabbink** [comment]
Tested, and the fix works.

**Comment by ragtag-fleet** [comment]
Could you please push this fix to master branch, I am awaiting for this fix...

**Comment by jabbink** [comment]
In the meantime you can switch to the `develop` branch in the advanced settings.

on `/config/general/`

![image](https://user-images.githubusercontent.com/2461972/26927311-a3d566ee-4c51-11e7-89a1-3969892af89d.png)

Downside: you get this warning on all pages for the time being

![image](https://user-images.githubusercontent.com/2461972/26927333-bc192330-4c51-11e7-858d-5cd423268e0b.png)

**Comment by ragtag-fleet** [comment]
@jabbink This fix has not been pushed to the develop branch either! Did you test on the devlop branch?

**Comment by jabbink** [comment]
It has been on `develop` since 4 days ago: https://github.com/SickRage/SickRage/commit/be0c5eaac12d5736c49e9a54edb4b4cd5b260720

![image](https://user-images.githubusercontent.com/2461972/26973828-8fc4605c-4d18-11e7-8dad-821c8b59f7d8.png)

**Comment by procdaddy11** [comment]
Issue is with qBitTorrent 3.3.13, downgrading to .12 fixed the issue

https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-3.3.12/

.14 is in the works to resolve this issue.

**Comment by Ambilinc** [comment]
downgrading from 3.3.13 to 3.3.12 did it for me.. now my downloads are once again working

**Comment by jabbink** [comment]
Again, upgrading SickRage would also work, which was the easier method for me as it's a matter of switching the branch/commithash of sickrage and restarting, instead of downgrading qBittorrent which requires more work.

**Comment by sharkykh** [comment]
@jabbink While I agree,
I guess some people find it easier than changing the branch on SickRage (you need to login with your Github credentials in SR)

**Comment by jabbink** [comment]
Hmm, I never logged into either SickRage with my GH credentials, nor would you need credentials to clone a repository (specific branch/commit hash/anything public) when you chose https as protocol.

**Comment by sharkykh** [comment]
You can do whatever you like with the git cli, but to checkout a different branch from within SickRage, you need to set your GH credentials (to get develop branch) or enable developer in config.ini (to get all branches).
REF: https://github.com/SickRage/SickRage/blob/96b53dee713dc35ebf295d0f37a67b2a36fb4ea3/gui/slick/views/config_general.mako#L1089-L1102

**Comment by sharkykh** [comment]
You can do whatever you like with the git cli, but to checkout a different branch from within SickRage, you need to set your GH credentials (to get develop branch) or enable developer in config.ini (to get all branches).
REF: https://github.com/SickRage/SickRage/blob/96b53dee713dc35ebf295d0f37a67b2a36fb4ea3/gui/slick/views/config_general.mako#L1089-L1102

**Comment by Raze42** [comment]
Any update on when this will make it to master?

much thanks,

~Raze42

**Comment by Firedrake1** [comment]
I would also like to know. I would love to switch back to the master branch.

**Comment by sharkykh** [comment]
@miigotu Maybe you should just hotfix/cherry-pick it into master.

**Comment by mickloud** [comment]
@Raze42 @Firedrake1 Also waiting on this to make it to master. 

I've been using develop, but now downloaded episodes aren't showing anymore under develop. 

Guess I'm forced to downgrade QBT at this point in order to be able to see my dl'ed episode and have auto-snatching work.
 
Master:
![image](https://user-images.githubusercontent.com/29279909/28216634-60afbf72-6880-11e7-8d27-6ac86493e08b.png)
Develop:
![image](https://user-images.githubusercontent.com/29279909/28216900-3c97a874-6881-11e7-9cf4-9208d03e48f5.png)

**Comment by sharkykh** [comment]
@mickloud This has nothing to do with qBT. It's probably something we did in the last few days. Thanks for posting this, I'll look into it.

**Comment by procdaddy11** [comment]
It's 100% qBT's issue. https://github.com/qbittorrent/qBittorrent/pull/6887

**Comment by sharkykh** [comment]
@procdaddy11 I was referring to the issue that downloaded episodes are no longer visible in SickRage. This has nothing to do with qBT.
The original issue discussed here was definitely caused by qBT.
