### ISSUE TITLE
Add requirements.txt and read it into setup.py

### ISSUE THREAD

**Issue by miigotu** [SickChill/SickChill#3834]
@sharkykh

 The list of libs we use you could go ahead and add to a new requirements.txt file, with version numbers or git commits as necessary.  I would like to get away from requiring the use of the lib folder, and the stuff that is in libs that cannot be sourced we could move them into the sickrage module. The list does not need to be complete to add it, we can update it over time as we figure out what libs came from where.
- [x] Create requirements.txt with current versions of libs => [Table+File](https://gist.github.com/sharkykh/2f6aa19befbb8a503f8e335e54565046) | [Branch](https://github.com/SickRage/SickRage/tree/feature/requirements/requirements)
- [x] Read requirements.txt into setup.py install_requires => 2a8e275abee7282ae20ff9a8843d3c36dea63861
- [ ] Leave libs as-is for now

**Comment by sharkykh** [comment]
How would that work?
Installation-wise... We'd just run `python setup.py install`?

> Create requirements.txt with current versions of libs

Already did a base list a month ago, and it's mostly updated.
It's not completely ready but it's close...
https://github.com/sharkykh/SickRage/blob/list-py-dependencies/lib/list.txt

**Comment by miigotu** [comment]
Eventually, you could clone and python setup.py install, or just `pip install sickrage-ng`... But we need a step-by-step approach that does not adversely affect end users in the process. Some users do not have access to pip, ditutils, or setuptools.  BUT we can use the requirements.txt/setup.py to automate keeping the libs dir up to date (for old style installs) and also make installing via pip and setup.py possible, so that new installs will be easier for the majority.  I'd like to keep the old libs folder approach for awhile, possibly even checking if we are installed a conventional way or the old broken SR way and avoiding the sys.path.insert if we can

**Comment by miigotu** [comment]
`Already did a base list a month ago, and it's mostly updated.` <-- This is why I pinged you, I knew you had a list =P

**Comment by sharkykh** [comment]
I feel like we should install them to a virtual environment. It's way too many packages.
Can it be done programmatically? So we'll install them in a `.venv` folder?

**Comment by miigotu** [comment]
For now we just need to get the full dependancies list into requirements.txt, we can go from there then.

**Comment by sharkykh** [comment]
@miigotu Should I list the dependencies of the packages?
Like, for Mako -> MarkupSafe

**Comment by sharkykh** [comment]
Okay... I finished updating the list.
Had so much new information that I also created a table to make it a little easier to read.
https://gist.github.com/sharkykh/2f6aa19befbb8a503f8e335e54565046

This should contain every folder or python file in the `lib` folder.
