### ISSUE TITLE
Replace bower with yarn

### ISSUE THREAD

**Issue by miigotu** [SickChill/SickChill#3835]
```
npm WARN deprecated bower@1.8.0: ..psst!
While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects!
Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects.
Currently there's no migration path but we hope you'll help us figure out one.
```

**Comment by miigotu** [comment]
@sharkykh I should have listened to you before to use yarn =P

**Comment by sharkykh** [comment]
@miigotu My brother, actually :stuck_out_tongue:

**Comment by OmgImAlexis** [comment]
If you'd like I can convert it all over?

**Comment by miigotu** [comment]
It would be helpful @OmgImAlexis thanks

**Comment by OmgImAlexis** [comment]
If you two are okay with this I'll also switch over to ava for js testing and xo for js linting. I've been using yarn, xo and ava together on all my projects lately and it's helped keep my code a LOT cleaner than bower/npm, jshint and mocha.

**Comment by OmgImAlexis** [comment]
Looks like we'll need to find replacements for these as they're not on the npmjs registry.

```
{
    "jqueryui-touch-punch": "*",
    "bootstrap-formhelpers": "~2.3.0",
    "openSans": "https://google-fonts.azurewebsites.net/googleFonts/openSans?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic",
    "jsgettext": "~0.8.1",
    "jquery.redirect": "^1.0.4"
}
```

**Comment by OmgImAlexis** [comment]
Started on this https://github.com/SickRage/SickRage/pull/3840

**Comment by sharkykh** [comment]
> Looks like we'll need to find replacements for these as they're not on the npmjs registry.
@OmgImAlexis 

Has to be registered? Is there an option for git sources?

**Comment by OmgImAlexis** [comment]
Git sources should be fine but there is still a bug open about a post install hook not being run for some packages so I'll check and see if I can get those last few installed that way if not we'll have to find alternatives.

**Comment by miigotu** [comment]
This is becoming much more of a priority now guys, if anyone is interested.
