### ISSUE TITLE
Requesting for files when series page loads

### ISSUE THREAD

**Issue by burzka** [SickChill/SickChill#3844]
I set up series location on mounted GoogleDrive. Mounted drive has many limitations (for example checking if file exists takes much longer than on local drive). Now, even when series is fully cached in SickRage database, files are requested everytime I load episodes list. There is no info on DEBUG log. I see it on GoogleDrive mounting software log. It causing EXTREMELY lag. Waiting time strictly depends of number of episodes inside series.

Is there any reason for requesting files from disc, when specific episodes list page is loading?

**Comment by miigotu** [comment]
probably checking file sizes

**Comment by Gitarski** [comment]
Isn't it checking to see if files have been removed or added or changed?

So, there is nothing wrong except for it taking an extremely long time?  That would be the network delays, wouldn't it?

So, I guess this isn't an "issue" but would be a feature request to modify the normal processing of series, right?
