### ISSUE TITLE
SickRage keeps unpacking already processed rars

### ISSUE THREAD

**Issue by agentq15** [SickChill/SickChill#3845]
Branch: master
Commit: 96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
Version: v2017.06.05-1
Database Version: 44.0
OS:Linux-4.4.6-grsec-x86_64-with-Ubuntu-14.04-trusty

What you did: Auto unpacked content on my seedbox to a "ready to download" folder and then downloading the content and removing the unpacked content from the server but keeping the source files in another folder.

What happened: Sickrage keeps unpacking the content every night so I download the same content again.

What you expected: Sickrage to only unpack once and the ignore the folders that has already been unpacked.

Logs:
I get these every night but it stills processes and unpacks the folders again.
```
2017-06-07 17:28:20 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 17:28:20 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 17:28:20 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 17:28:20 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 17:28:20 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 17:28:20 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 17:28:20 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 17:28:20 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 17:28:20 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 03:58:02 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 03:58:02 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 03:58:02 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 03:58:02 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 03:58:02 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
2017-06-07 03:58:02 POSTPROCESSOR-AUTO :: Cannot process an episode that's already been moved to its show dir, skipping /home/disk10/...REMOVED...
```

**Comment by sharkykh** [comment]
Is the "Delete RAR contents" option in the PP settings selected? If so, try again after de-selecting it.

**Comment by agentq15** [comment]
But isn't it supposed to delete the content? Otherwise wouldn't I get the unpacked content left in the source folder?

**Comment by miigotu** [comment]
force post process them once. likely you deleted cache.db at some point and these files were processed before that deletion, so SR doesnt know that they were already processed but it also cannot finish processing them.  @sharkykh probably should mark them as processed in the cache when `Cannot process an episode that's already been moved to its show dir`

**Comment by agentq15** [comment]
@miigotu Okay done that now. Have not deleted that file on purpose though. Should I do what sharkykh said? I have it now as method Copy and delete contents.

Sorry about the title. Didn't mean to sound offensive. Had a hard time thinking of what to call the problem.

**Comment by miigotu** [comment]
"SickRage keeps unpacking already processed rars" seems simple enough.  Sure, try what @sharkykh suggests, I have not been as active as he has lately, so he might be able to help better.

**Comment by agentq15** [comment]
Now it still does the same but more often. I have deleted the content in the download folder manually and it just keeps unpacking it there again. Is there something else I can try?

**Comment by agentq15** [comment]
I haven't find any solution to this yet. Anything else I can try? It just keeps unpacking.

**Comment by sharkykh** [comment]
@miigotu 
Well, of course it unpacks it every time.
Don't know how I missed this before.
[`validate_dir`](https://github.com/SickRage/SickRage/blob/96b53dee713dc35ebf295d0f37a67b2a36fb4ea3/sickbeard/processTV.py#L193) is called after the unrar.
I'll try and make a separate function to validate the contents of a rar like a folder.
I think I saw that rarfile has a list function. Hopefully :crossed_fingers:

**Comment by sharkykh** [comment]
Wait a second... @agentq15 
Please list your directories:
TV Root Dir
Post Processing Dir

I have a feeling they're the same or one inside the other.

**Comment by agentq15** [comment]
They get downloaded to one folder and then unpacked to another one. 
Root dir: /home/disk10/user/torrents/Sickrage_download
Post Proc: /home/disk10/user/torrents/Sickrage_download

On all shows I have /home/disk10/user/torrents/unpacked_series

This is all on a seedbox and the unpacked content is downloaded from the unpacked_series folder and then removed.

**Comment by sharkykh** [comment]
According to what you're saying, your config is incorrect.
You can't have the TV root dir the same as the post processing dir.
Tv root dir is where processed shows go into.

**Comment by agentq15** [comment]
Is "Show root directories" the same as TV root dir? 
Am I supposed to have that as where I unpack the stuff?
Everything gets removed from that folder when it's downloaded so it feels wrong. All show files are at /home/disk10/user/torrents/Sickrage_download

**Comment by sharkykh** [comment]
The workflow show be like that:
Transmission download to /downloads/completed
SickRage watches the download dir (Post Processing Dir)
Unpacking dir is optional, if you do use it, it should be something different, not in the postprocessing dir
The post processor moves video files to the show's location = a subdirectory of the show's root directory.
You set TV root directories in the general config, 
They must be a different folder and not a subfolder of the postprocessing dir or unpack dir.
Every show you add to that root dir creates a sub directory with the show's name and everything gets transfered there.
The shows you already have, you can change their root dir using Manage -> Mass Update from the menu.

**Comment by miigotu** [comment]
TV root dir is something like `/Videos/Shows`. When you add a show to SR it will create a folder in there for that show, `/Videos/Shows/Arrow` for example.
Then you have a post processing folder/download folder, such as `/Downloads/SickRage/` where your torrent client should put downloads once they have completed.
SickRage then looks in that postprocessing folder for new downloads, processes them and moves them into the correct place in the show folder which is in the tv show root, such as `/Videos/Shows/Arrow/Season 01/S01E01.mkv`

**Comment by miigotu** [comment]
your post processing/download folder and your tv root should be on the same device

**Comment by agentq15** [comment]
Everything is on the same device. It's a seedbox

**Comment by sharkykh** [comment]
@agentq15 

1. http://localhost:8081/config/search/#torrent-search
Set `Downloaded files location` to `/torrents/downloads/`
2. **If you mean using SickRage and not an external tool...**
http://localhost:8081/config/postProcessing/#unpack
Set `Unpack` to `Unpack (process contents)`
Set `Unpack Directory` to `/torrents/finished/`
3. 
> There it will be downloaded to a local server and the file will be removed from /torrents/finished/ when finished

I don't understand what you mean.
Again, if you want SickRage to do it all for you -- 
it will extract to `/torrents/finished/`, process the video files, then **remove the extracted folder**.
4. As long as you don't use the 'Move' as the post-processing method, the original files stay.

Go into a show in SickRage, one that its downloaded files get unpacked again every time.
**What is the location?**
![image](https://user-images.githubusercontent.com/10238474/27361275-e640ef9e-562e-11e7-9599-da116a293539.png)

**Comment by agentq15** [comment]
> I don't understand what you mean.
> Again, if you want SickRage to do it all for you --
> it will extract to /torrents/finished/, process the video files, then remove the extracted folder.
Because this is all on a seedbox. I just want the seedbox to unpack the content and then I can download it to my local storage using FTP. When that is done I don't need the extracted content to take space on the seedbox. I just need the original files for seeding.

The location right now on all the shows is `/torrents/finished/` because that is where I want it to put the show. They don't have its own folder on the seedbox. I solve that locally later.

**Comment by sharkykh** [comment]
Okay, that's an unusual setup.
But SickRage can't really work like that. Its purpose is to **completely automate** the process of searching for shows / managing RSS feeds / tracking shows and episodes / managing a TV library)
It needs to a location to process episodes to, and it needs to be different.

The easiest solution I can think of for you, is to open Post-processing settings,
* **Clear the "Unpack dir"** option (empty text box)
You don't need it. It unpacks in the download folder and then deletes the extracted folder if post-processing was successful.
* Enable "Add shows without directory".
This will tell SickRage to simply add everything it post-processes to the root folder without creating show-specific folders.
I've never used it, so I don't know how it works exactly (it does say it's not recommended)
If you're using the Rename episodes option, make sure you set the custom naming to have all the basic information needed in the filename (Show name, season number, episode number, quality)
