### ISSUE TITLE
episodes stay's wanted

### ISSUE THREAD

**Issue by ypehille** [SickChill/SickChill#3867]
Why is sickrage leaving a lot of episodes Wanted while they can be found manually

### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by sharkykh** [comment]
We can't possibly know what the issue is without debug logs.
