### ISSUE TITLE
Postprocessor random file copy problem

### ISSUE THREAD

**Issue by phild9** [SickChill/SickChill#3869]
Raspian Issue

Sickrage uses Transmission to download and completed files are copied by the post processor from the completed torrents folder to a dedicated TV catalogue folder.
When this happens, sometimes Sickrage complains of a permissions issue and creates a 0 byte file in the destination location with the correct name,
ie the post processor attempts to copy `/mnt/downloads/torrents/completed/TVShow.S01E01.webrip.x265.720p.blah.mkv` to
`/mnt/TV catalogue/TV Show/TV Show Season 1/TV Show.S01E01.The First Episode.mkv`
and creates a 0 byte file with that filename instead.

Sickrage and Transmission both run as the same user and the permissions are correct, when I change the status of the episode to wanted and the post processor runs again it copies the file correctly from completed download to the destination. So this issue occurs seemingly randomly.

The log says:
```
2017-01-07 21:02:30 DEBUG SHOWQUEUE-REFRESH :: Setter sets location to [DESTINATION]
2017-01-05 23:17:06 DEBUG POSTPROCESSER :: Copying file from [SOURCE] to [DESTINATION]
2017-01-05 23:17:06 ERROR POSTPROCESSER :: [ee7f95b] [Errno 13] Permission denied: [DESTINATION]
IOError: [Errno 13] Permission denied: [DESTINATION]
2017-01-05 23:17:06 DEBUG POSTPROCESSER :: Not running as root or owner of [DESTINATION], not trying to set permissions
```

Sickrage IS (definitely, 100%) running as the owner of the DESTINATION parent folder and as I said when I run the post processor again it nearly always copies the file correctly. This doesn't happen for all files downloaded initially, or all files belonging to a single TV show - one episode will copy correctly but the next one for the same show won't. This behaviour appears to be random. 

Is this a known issue?

Raspbian / RPI3 - Linux 4.9.24-v7+

SickRage Info:
Branch: master
Commit: 96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
Version: v2017.06.05-1
Database Version: 44.0
  Python Version: 2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]
  SSL Version: OpenSSL 1.0.1t 3 May 2016
  OS: Linux-4.9.24-v7+-armv7l-with-debian-8.0

**Comment by sharkykh** [comment]
@phild9 
Operating systems usually don't lie.
`[Errno 13] Permission denied` is the response SickRage got from your OS, so it's probably true in some way or another, but continue reading.

[This StackOverflow answer](https://stackoverflow.com/a/39879794/7597273) suggests...
> This only happens when shutil.copy(), copy2(), copyfile() does NOT have "clean" access to the file.
> **in most cases this is because you have not closed the file before trying to copy it. Not having read permissions on the first file could cause this too.**
> 
> I just had this problem because I had **the same program scheduled twice at the same time. Stepping all over each other.**

I'm trying to remember what I did exactly when this happened to me (Windows 7 / uTorrent),
**I think** I was trying to move a file that was being used by uTorrent (seeding),
or it might be something else...

Nonetheless, I'd suggest:
* Making sure you're not running SickRage as root / `sudo` mode.
  I assume you're using a service to start SickRage on boot, so maybe check the init script for it.
  Or check processes using `ps -a | grep python`?
* Making sure parent directories have their ownership and permissions set correctly.
  Do it again even if you're sure, just to be "double-sure".
* Go over Transmission's settings.
  Maybe something there locks the file(s)? (so only it can use them while locked)
