### ISSUE TITLE
bad str/unicode comparison

### ISSUE THREAD

**Issue by lootr** [SickChill/SickChill#3891]
**Context**
Branch/Commit: master (96b53dee713dc35ebf295d0f37a67b2a36fb4ea3)
OS: Ubuntu 16.04.2
What you did: mass replacing root directory
What happened: none was replaced
What you expected: some concerned would be replaced
Logs:
Nothing

Note:
Some of my FS entries are UTF-8 encoded, this is the root cause of this issue.

I tried to log ``cur_root_dir`` and ``cut_show_dir`` to see why nothing occurs (see https://github.com/SickRage/SickRage/blob/96b53dee713dc35ebf295d0f37a67b2a36fb4ea3/sickbeard/webserve.py#L3459):
* ``cur_root_dir`` is a unicode value
* ``cur_show_dir`` is a str-encoded value

Even if their value are similar (excepting locale issue), the mapping is never found.

**Way to solve:**
Make both variable type-compatible, in one way or the other

**Comment by sharkykh** [comment]
I'll just say, unicode is what we aim for.
