### ISSUE TITLE
Series search badly broken, need to upgrade to TVDB v2 API

### ISSUE THREAD

**Issue by arana-krypteia** [SickChill/SickChill#3893]
This issue is the same as #3222 

Searches will not find many relevant results. For example, searching for "Frontier" will not find "Frontier (2016)". 

Basically, the TVDB search functionality is badly broken in the v1 API and will not be fixed. Sickrage needs to move to the [v2 API](https://api.thetvdb.com/swagger).

Confirmation from tvdb devs that this is an old API issue and will not be fixed: https://forums.thetvdb.com/viewtopic.php?f=17&t=35772&hilit=sickrage

SickRage Info: 
Branch: master
Commit:
Database Version: 44.0
Python Version: 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
SSL Version: OpenSSL 1.1.0e 16 Feb 2017
OS: Linux-4.9.30-unRAID-x86_64-with-glibc2.2.5
Locale: en_GB.UTF-8

**Comment by moosedookie** [comment]
It appears that development is already under way for this.
https://github.com/SickRage/SickRage/projects/1
