### ISSUE TITLE
[Feature Request] Improve integrity of POSTPROCESSER file moving/deleting

### ISSUE THREAD

**Issue by jamver** [SickChill/SickChill#3895]
**Branch/Commit**: master/96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
**OS**: Linux-4.4.68.x86_64.1-x86_64-with-debian-8.8 (Netgear ReadyNAS 6.7.4)

**What you did**:

- Copied (multi-gigabyte) files to the _Post Processing Dir_ from a remote network client.

Note: On the NAS, the _Post Processing Dir_ and the _Show root directories_ are on **_different_** file systems, and the _Processing Method_ is _Move_.

**What happened**:

The _Post Processing_ **_Move_** function only transferred partial files to the _Show root directories_
- _Post Processing_ began while files were still in transit (i.e. partially copied) and still being written to the NAS (AFP share via netatalk-3.1.11-netgear1) into the _Post Processing Dir_.
- _Post Processing_ _**Moved**_ the partially transferred files into the _Show root directories_.
- The _Post Processing Move_ completed before the remote network client, and only transferred partial files, leaving the truncated versions in the _Show root directories_.
- The original file (inode) was deleted after _Post Processing_ finished _Moving_ the files.
- The remote network client continued to write to the original inode and (correctly) believed it had completed the file transfer, however, as the _Processing Method_ was _Move_, and this was across filesystem boundaries, the completed/non-truncated version of the file was lost.

**What you expected**:

Some form of _File Integrity Checking_, especially during a risky operations such as a **_move across filesystem boundaries_**
- Check for file lock status (statuses of files within a sub-directory) before attempting to process the file/directory
- If the source and target directories do not share a mountpoint or for some other reason it is not possible to perform an atomic move operation (e.g. inode relocation is not possible), ensure higher file transfer integrity processes are performed, such as an explicit copy>check integrity>delete process
- If using a copy>check integrity>delete
  - The check function should (at a minimum) confirm that no attributes (ctime, mtime, size, permissions, checksum if requested) have been modified between the beginning and end of the copy process.
  - If file changes are detected (ctime, mtime, size, permissions, checksum if requested), then,
    1. delete the transferred file
    1. and either
      - perform a test>sleep>test cycle until no changes are detected, or
      - record the anomaly in the Logs and leave until next time the Postprocessor executes.

**Current workaround**:

Copy files to a different directory in the _same filesystem_ as the _Post Processing Dir_, then manually perform an atomic move into the _Post Processing Dir_.

**Comment by jamver** [comment]
It’s a bit rude closing a clearlubidentified big that has not been fixed!

**Comment by miigotu** [comment]
It is a bit rude to make a snarky comment rather tna read the tag and just comment if it needed to still be open. There were hundred of stale issues that WERE NOT bugs that needed to be closed.

**Comment by miigotu** [comment]
Regardless, what you are asking for is a FEATURE, there is no bug there. You are welcome to PR a fix.

**Comment by jamver** [comment]
Apologies if it seemed snarky, but I didn’t see a reason to close it with a descriptive tag to reopen. This is likely to never see it revisited and more likely for an identical issue to be filed by someone else experiencing the same issue in the future. 

I would have suggested you ower it’s priority, if that is the intention.

**Comment by miigotu** [comment]
Actually in over 4 years nobody else has had such an issue

**Comment by miigotu** [comment]
We already have things like .syncthing files and others that prevent PP from happening before files are finished being copied.
