### ISSUE TITLE
Backlog will not clear

### ISSUE THREAD

**Issue by Fetchered** [SickChill/SickChill#3896]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
OS: QNAP QTS 4.3.3.0210
What you did: Marked all 'backlogged' shows/episodes as ignore
What happened: The backlog was cleared for a short while, then they all came back
What you expected: That the backlog for shows already downloaded and of acceptable quality would not continually keep backlogging.
Logs:
```
https://pastebin.com/U3M8q3g2
```
Several shows have dozens of entries which say the Airdate was never and the episode listed is WAY beyond what the show has aired (S01E223, S01E222). Most commonly happens for Doctor Who (2005), Family Guy, and Hawaii Five-O, all showing as Season 1.
Shows will not change quality from Downloaded Unknown to Downloaded SDTV.

This is annoying because these shows keep looking for old episodes I no longer want them to look for, they keep putting them in the backlog, and end up using up too many of my NZB requests!

**Comment by sharkykh** [comment]
I would suggest removing the shows from the database and re-adding them. Something isn't right.
I have Doctor Who 2005 and Family Guy and I never had this issue.
