### ISSUE TITLE
insserv: script sickrage is not an executable regular file, skipped!

### ISSUE THREAD

**Issue by chrism2015** [SickChill/SickChill#3905]
Branch/Commit: Unknown trying to install
OS: Ubuntu 16.04 lts
What you did: tried to install sickrage
What happened: failed with error insserv: script sickrage is not an executable regular file, skipped!
Logs: no logs available

whilst trying to install the most recent version the install using both the scrip and manually fails at the step, sudo update-rc.d sickrage defaults from the page https://github.com/SickRage/SickRage/wiki/Sickrage-installation-Debian-Ubuntu-14-15-16 with the error insserv: script sickrage is not an executable regular file, skipped! this error is also displayed when trying to start the sickrage service.

**Comment by sharkykh** [comment]
try `chmod +x /etc/init.d/sickrage` and then do the step again?

**Comment by FGOD1983** [comment]
Having the same issue. Install script didn't work (fail on python, unrar-free and libssl) so i am doing a manual install. But the chmod +x /etc/init.d/sickrage didn't solve this problem

**Comment by FGOD1983** [comment]
Same Ubuntu version too btw

**Comment by OmgImAlexis** [comment]
If you can provide the logs for the install we can help otherwise we're just blindly guessing at what's not working.

**Comment by DropdeadFredd** [comment]
Had the same issue, used: chmod +x /etc/init.d/sickchill and now it works.
