### ISSUE TITLE
Add paging for shows with lots of episodes

### ISSUE THREAD

**Issue by rlambert27** [SickChill/SickChill#3924]
Branch/Commit
Branch: master
Commit: 96b53dee713dc35ebf295d0f37a67b2a36fb4ea3
Version: v2017.06.05-1
Database Version: 44.0
OS: Linux-4.4.0-83-generic-x86_64-with-Ubuntu-16.04-xenial 
What you did: Added Jeopardy
What happened: Page won't load, script takes too long warning in FF
What you expected: When shows has X amount of season or X amount episodes that some type of paging would occur. Otherwise the page is way too big, Jeopardy has 7509 epidoes.
Logs: N/A

Also since sooo many episodes show up i'm unable to switch them from "Skipped" to "Wanted", the page reloads but nothing happens.

What do you think about adding some type of paging when shows are too big?

**Comment by sharkykh** [comment]
> What do you think about adding some type of paging when shows are too big?

I don't believe this is an easy feature to implement. I wouldn't count on that in the near future...
About changing episode status, just select less, and it _should_ work... I think.

**Comment by rlambert27** [comment]
It doesn't work, if I select less episodes and switch them to wanted, it reloads the page but i'm thinking it takes soo much time to load that it doesn't execute the code to put switch the status.

**Comment by sharkykh** [comment]
It sends the status update request before it reloads the page. I just checked the code.
If you allow the page to load you should see the updated status.

**Comment by rlambert27** [comment]
Well I guess the issue is that I need to wait for the page to load completely before I can change the status. If I hit stop on the script it won't let me change the status. But If I let the script continue it crashes the browser.

I'm surprised no one else has run into this issue with other big shows, maybe like "The Simpsons" (28 seasons). I guess Jeopardy might be unique in the fact that it has 7509 episodes.

**Comment by rlambert27** [comment]
Is it possible to leave this open? I still don't add Jeopardy because it crashes the script.

**Comment by miigotu** [comment]
Sure, just tagged and closed all issues older than 6 months, so people would comment and let me know which are still issues =P

**Comment by leipert** [comment]
@miigotu This is especially a problem on slower hosts, like a NAS. Please compare for example [The Daily Show](https://www.thetvdb.com/series/the-daily-show) and [The Handmaid's Tale](https://www.thetvdb.com/series/the-handmaids-tale)

The Daily Shown takes ~25 seconds to load (TTFB), so it takes a lot of time to render the data in the backend:
<img width="437" alt="screenshot 2018-11-24 at 11 46 22" src="https://user-images.githubusercontent.com/2906107/48967332-fa8b2000-efde-11e8-8b34-d7d881c0a65d.png">
After the thing is generated, we have around 520000 DOM Elements and 18000 event listeners.

Compare that to the Handmaid's Tale, which takes just ~700 milliseconds to load, and just has 9200 DOM Elements and 414 Event listeners:

<img width="436" alt="screenshot 2018-11-24 at 11 51 05" src="https://user-images.githubusercontent.com/2906107/48967367-63729800-efdf-11e8-826f-6fe1e89b0366.png">

I think the best compromise would be to just render the last X seasons, let's say 3 (maybe configurable), per default and have a button to load the rest of the seasons. We don't have to get crazy with AJAX, we could also add a URI parameter e.g.:

- /displayShow?show=321239&seasons=full -> all seasons
- /displayShow?show=321239&seasons=3 -> last 3 seasons

**Comment by miigotu** [comment]
Feel free to make a PR ;) bit I have tons of other stuff I need to do first if I have to do it myself.

**Comment by rlambert27** [comment]
Leave open, if I get a chance i'll try to work on a PR.

**Comment by rlambert27** [comment]
Same leave open please, thanks!
