### ISSUE TITLE
bad anime metadata

### ISSUE THREAD

**Issue by ArGaMer** [SickChill/SickChill#3952]
the anime Fairy tale has 7 seasons in sickrage but in animedb it has 175 episodes in the first series and 102 episodes in the second so when i set season 7 ( latest season ) to wanted, it downloads season two episode 1 to 102 which is correct but it names it s02e01-e102 and i have the older episodes downloaded as well, and it names them s07e01-175 so when i look at it and when plex does it reades that season 2 is older than season 7 and puts them in the same anime folder which is incorrect.

since sickrage reads anime as seasons same as IMDb it thinks the second series is the second season from the first series so when it downloads the second series ( 7 season overall in sickrage ) it PP them as second season

**Comment by beschoenen** [comment]
SickRage reads its metadata from [TheTVDB](http://thetvdb.com/?tab=series&id=114801&lid=7). SickRage it's perfect and in cases like this, you'll have to rename the episodes yourself.

Try this program for windows: http://www.bulkrenameutility.co.uk/Main_Intro.php
