### ISSUE TITLE
Downloaded subtitles not approriate for the downloaded TV show

### ISSUE THREAD

**Issue by jgrossrieder** [SickChill/SickChill#3958]
### Before submitting your issue:

Branch: master
Commit: 832ccb445f8eaadef783eddb51880d67d1a77b3d
Version: v2017.06.05-1
Database Version: 44.0
OS: Linux-4.8.0-30-generic-x86_64-with-Ubuntu-16.10-yakkety

What you did:
1. Configure a TV show to download, with some subtitles(in my case french).
2. Configure the post processing episode naming to include the Release Group. In my case, I selected the last proposal: Season 02/Show.Name.S02.E03.720p.HDTV-RLSGROUP
3. Wait to have one episode downloaded.

What happened:
subtitles have been downloaded, by they are not synchronized at all with the tv show. So at the end I've to search myself for which file has been downloaded, search for the correct release and download myself.

What you expected:
Properly take in account the release group to download the file.

I've a concrete case:
I added a famous TV shows with blonde and dragons in 1080p.
I got one episode downloaded:

> TV.SHOW.S07E03.The.Episode.Name.1080p.AMZN.WEB-DL.DDP5.1.H.264-GoT[ettv]

It has been remaned to

> TV.SHOW.S07E03.1080p.WEB.DL-GoT.mkv

 Please notice that it did loose the AMZN part

It then downloaded the **1080p WEB-DL** subtitle for this show from OpenSubtitles.
The best alternative I found was the **720p.AMZN.WEB-DL** from addicted(my understanding is that between 720p and 1080p, subitles are interchangeable?).

I looked a little bit, and it seems that AMZN is one of the release group, and it should be included in the name of the file(since at my knowledge it's used to determine which subtitle should be downloaded).

I don't really have logs, and there is no "errors", just some part of the file that are not included in the file.

**Comment by BenjV** [comment]
AMZN is not a releasegroup.
This is a amazon webrip, which is falsely named a web-dl but it is a webrip.
So a sub made for a web-dl won't be in sync.

Web-dl's are coming from iTunes and not from Amazon.

**Comment by jgrossrieder** [comment]
@BenjV Sorry, I didn't know, thank you for the precision. But still, it means then that the kind of the tv-show is incorrectly read, right?

**Comment by BenjV** [comment]
No this means that the person who uploaded the video gave it the wrong name.
A AMZN cannot be a WEB-DL at the same time

It would be nice if Sickrage had such rules aboard to prevent wrong downloads.

**Comment by jgrossrieder** [comment]
@benjV I don't agree, I've seen it on multiple torrent websites, also on subtitles providers, so if they both support it, the only one that doesn't is SR?

**Comment by BenjV** [comment]
I don't understand what you disagree with?

The fact that AMZN is not an web-dl?
or
That Sickrage does not have rules to not download those wrongly named video's?

**Comment by jgrossrieder** [comment]
@BenjV That we can just say "Ok, it seems that this file is poorly named, so no matters it's still recognized elsewhere, even if it's ourself that have choosen to download that specific file, I still want to get a subtitle that doesn't match the content".

My point of view is that even this file is maybe(I've no idea if this is the case, but I trust you on this one) poorly named, I can still exactly match which subtitle file should have been downloaded(at least from the first subtitle website that I found), so why not SR? I've checked on addic7ed by example, and there is some subtitles versions named "AMZN.WEB-DL", so what is missing except recognizing this?

For what I see, the two main provider(cpasbien and yggtorrent)(for french content at least) seems to be proposing the episodes with this format.

**Comment by BenjV** [comment]
Ok I understand your issue now.
I agree that Sickrage should make this match even although they are wrongly named.

I also know that sublimaal (which is used by Sickrage) is not up to par on matching sub with video's.
I wrote myself a better application (autosub) but that is only doing Dutch and English subtitles, so no luck for French subs.
