### ISSUE TITLE
from Today's news - Tried entering the steps and fails at git branch -u origin/master

### ISSUE THREAD

**Issue by PipingR** [SickChill/SickChill#3961]
Branch/Commit: latest
OS: ubuntu 12.04.5 LTS
What you did: 
git remote set-url origin https://github.com/SickRage/SickRage.git
git fetch origin
git checkout master
git branch -u origin/master
git reset --hard origin/master
git pull

What happened:
git branch -u origin/master
error: unknown switch -u

so continued with final command (above) and started back up.
What you expected:
Newer version?

Logs:
```
sysadmin@TretflixVM:~$ sudo service sickrage start
Starting SickRage
ERROR:root:Could not find any typelib for Notify
DEBUG:sickrage:MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
DEBUG:sickrage:MAIN :: Found codec for 'Show Name: Ep Name'.
DEBUG:sickrage:MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
DEBUG:sickrage:MAIN :: formatting pattern: %SN - S%0SE%0E - %EN - %Q.N -> Show Name - S02E03 - Ep Name - 720p.HDTV
DEBUG:sickrage:MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
DEBUG:sickrage:MAIN :: Found codec for 'Show Name: Ep Name'.
DEBUG:sickrage:MAIN :: formatting pattern: Season %0S -> Season 02
DEBUG:sickrage:MAIN :: Trying to parse Show Name - S02E03 - Ep Name - 720p.HDTV.ext
DEBUG:sickrage:MAIN :: Parsed Show Name - S02E03 - Ep Name - 720p.HDTV.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
DEBUG:sickrage:MAIN :: The name Show Name - S02E03 - Ep Name - 720p.HDTV.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
DEBUG:sickrage:MAIN :: Checking database structure...sickbeard.db
DEBUG:sickrage:MAIN :: Database upgrade required: Reset Version
DEBUG:sickrage:MAIN :: ResetDBVersion upgrade completed
DEBUG:sickrage:MAIN :: Checking database structure...cache.db
DEBUG:sickrage:MAIN :: Checking database structure...failed.db
INFO:sickrage:MAIN :: Fixing unaired episode status for episode_id: 143572
DEBUG:sickrage:MAIN :: Checking for shows with tvrage id's, since tvrage is gone
DEBUG:sickrage:MAIN :: Checking for archived episodes not qualified
DEBUG:sickrage:MAIN :: Checking if we can use git commands: git version
DEBUG:sickrage:MAIN :: Executing git version with your shell in /opt/tretflix/appdata/sickrage
DEBUG:sickrage:MAIN :: git version : returned successful
DEBUG:sickrage:MAIN :: Using: git
DEBUG:sickrage:MAIN :: Executing git symbolic-ref -q HEAD with your shell in /opt/tretflix/appdata/sickrage
DEBUG:sickrage:MAIN :: git symbolic-ref -q HEAD : returned successful
DEBUG:sickrage:MAIN :: Retrieving the last check time from the DB
sysadmin@TretflixVM:~$ INFO:sickrage:MAIN :: Writing PID: 52126 to /home/sysadmin/.sickrage.pid


```

**Comment by PipingR** [comment]
So now at each restart it shows this:
 Loading /opt/tretflix/appdata/sabnzbdplus/admin/future/SABnzbd_nzo_OXYJYr failed

Time to revert to prior image? Not sure.

**Comment by pigsyn** [comment]
You're using an obsolete distro and outdated git version, so this won't work.
I believe -u was added in git 1.8, but --set-upstream exists from 1.7
Maybe try `git branch --set-upstream master origin/master `

**Comment by PipingR** [comment]
Thank you. 
Running git version 1.7.9.5 so will try that suggestion and report back only if it does not work for my distro.

**Comment by PipingR** [comment]
Still stuck on old distro. 

sysadmin@TretflixVM:~$ cd /opt/tretflix/appdata/sickrage/
sysadmin@TretflixVM:/opt/tretflix/appdata/sickrage$ sudo service sickrage stop
Stopping SickRage
sysadmin@TretflixVM:/opt/tretflix/appdata/sickrage$ git remote set-url origin https://github.com/SickRage/SickRage.git
sysadmin@TretflixVM:/opt/tretflix/appdata/sickrage$ git fetch origin
sysadmin@TretflixVM:/opt/tretflix/appdata/sickrage$ git checkout master
Already on 'master'
Your branch and 'origin/master' have diverged,
and have 3707 and 2953 different commits each, respectively.
sysadmin@TretflixVM:/opt/tretflix/appdata/sickrage$ git branch --set-upstream master origin/master
Branch master set up to track remote branch master from origin.
sysadmin@TretflixVM:/opt/tretflix/appdata/sickrage$ git reset --hard origin/master
Checking out files: 100% (6786/6786), done.
HEAD is now at dcb10ca Merge branch 'release/9.4.4'
sysadmin@TretflixVM:/opt/tretflix/appdata/sickrage$ git pull
Already up-to-date.
sysadmin@TretflixVM:/opt/tretflix/appdata/sickrage$ sudo service sickrage start
Starting SickRage
/usr/bin/python2.7: can't open file 'SickBeard.py': [Errno 2] No such file or directory
sysadmin@TretflixVM:/opt/tretflix/appdata/sickrage$ sudo service sickrage stop
Stopping SickRage
No process in pidfile '/home/sysadmin/.sickrage.pid' found running; none killed.
sysadmin@TretflixVM:/opt/tretflix/appdata/sickrage$ sudo service sickrage stop
Stopping SickRage
No process in pidfile '/home/sysadmin/.sickrage.pid' found running; none killed.
sysadmin@TretflixVM:/opt/tretflix/appdata/sickrage$ sudo service sickrage start
Starting SickRage
/usr/bin/python2.7: can't open file 'SickBeard.py': [Errno 2] No such file or directory
