### ISSUE TITLE
Auto delete show from Kodi library

### ISSUE THREAD

**Issue by RebelDesigner** [SickChill/SickChill#3964]
It would be nice if SickRage is able to automatically delete a show from the Kodi library when one deletes it from SickRage/the filesystem.

**Comment by p0psicles** [comment]
Sure you want that? As that can be tricky. What happens if a user, uses a remote share. And it loses connection? You'll have to take into account all kind of exceptions.

**Comment by RebelDesigner** [comment]
That is not what I am talking about. (my original sentence could be read the wrong way, I see)
The DELETE button in SickRage could also trigger a call to Kodi to delete the show from the lib.
Has nothing to do with connection or exceptions.
Could be designed similar to the question dialog that asks to just delete from SickRage or also from the file system.

**Comment by beschoenen** [comment]
For reference: http://kodi.wiki/view/JSON-RPC_API/v6#VideoLibrary.RemoveTVShow

**Comment by RebelDesigner** [comment]
Does anyone know if SickRage currently saves the Kodi `tvshowid`?
Maybe I have some time later today to extend the Kodi service provider with a test setup for such a feature.

**Comment by beschoenen** [comment]
Yep, it does, the number comes from the indexer you pick when adding a show, this indexer you use should be the same in KODI for this to work.

**Comment by RebelDesigner** [comment]
Cool. That should make stuff easier.
