### ISSUE TITLE
 WARNING::MAIN :: Updating network timezones failed

### ISSUE THREAD

**Issue by ovsleep** [SickChill/SickChill#3972]
Branch/Commit: master
OS: **docker in QNAP**
What you did: Try to open main page
What happened: got a ERR_EMPTY_RESPONSE response
What you expected: see main page
Logs:
```
23:27:46 WARNING::MAIN :: Updating network timezones failed, this can happen from time to time. URL: https://sickrage.github.io/sb_network_timezones/network_timezones.txt
23:27:46 DEBUG::MAIN :: Request failed: ("bad handshake: Error([('', 'osrandom_rand_bytes', 'getrandom() initialization failed.')],)",)
23:27:46 DEBUG::MAIN :: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/helpers.py", line 1511, in handle_requests_exception
    raise requests_exception
SSLError: ("bad handshake: Error([('', 'osrandom_rand_bytes', 'getrandom() initialization failed.')],)",)
```

This issue prevents me to open any sickrage page, so any change in the config should be done from the config.ini file. I set the enable_https: 0 (read somewhere this could be the issue) but the error persist.

**Comment by p0psicles** [comment]
@sharkykh i'm going to help you a little here.
There are two issues here.

1. Somehow this use has issues getting the network timezones. And yes it looks like an SSL thing.
2. (And this is something you should do something about). Your making the request to get the timezones part of your webserves Home route. You should not do that as for 1. it can slow down the loading of the page and 2. any exception like this user is experiencing, will result in the page not loading.

This is your entry point: https://github.com/SickRage/SickRage/blob/master/sickbeard/webserve.py#L545

You can drill that down to: https://github.com/SickRage/SickRage/blob/master/sickbeard/network_timezones.py#L144
and https://github.com/SickRage/SickRage/blob/master/sickbeard/network_timezones.py#L100.

What you want is a background process, that will update the timezones on a periodic base. Like once a night. And remove all the references from the routes. At least that is how we did it. If that fails for some reason, user can get a warning or error. And report it.
