### ISSUE TITLE
Please add 1337x.to Provider

### ISSUE THREAD

**Issue by DDA78** [SickChill/SickChill#3974]
Can you add https://1337x.to

**Comment by ward0** [comment]
they don't provide RSS to work with. Its not possible.

contact 1337 and ask them to make RSS available.

**Comment by DDA78** [comment]
thanks... have written them, let's see if they reply.

**Comment by ward0** [comment]
I did the same like 10 times already :) never got an reply :(

**Comment by pigsyn** [comment]
Well after looking at some sickbeard/providers code, I wonder what is considered "RSS".

**Comment by ward0** [comment]
@pigsyn  the dev's need some materials to work with, RSS or API from the provider so send requests to get data back.

If you want to scrape the website, you use jackett to do it for you and you get a RSS back from Jackett.

**Comment by Kwintspiracy** [comment]
How come Download Station is able to search L337
![screen shot 2018-03-16 at 4 26 53 pm](https://user-images.githubusercontent.com/18689967/37510652-dd551fdc-2936-11e8-8d0d-fc7ee7b7b3b9.png)
x then ?

**Comment by ward0** [comment]
@Kwintspiracy Just use Jackett!
