### ISSUE TITLE
Thread-21 :: Unable to create directory 

### ISSUE THREAD

**Issue by digitalgp** [SickChill/SickChill#3976]
SickRage Info:
Branch: master
Commit: 832ccb445f8eaadef783eddb51880d67d1a77b3d
Version: v2017.06.05-1
Database Version: 44.0,   Python versjon:
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL versjon:
OpenSSL 1.0.2j 26 Sep 2016
OS: Windows-10-10.0.14393
Språk: nb_NO.cp1252

What you did: used \\192.168.10.77\media\bittorrent\downloaded as folder for post processing (tv download folder from torrent client)
What happened: first the post processing got a error Unable to create directory \\192.168.10.77\media\bittorrent\downloaded, dir not changed.
Then the setting in post processing for folder is now blank and i get an error Auto post-processing attempted but directory is not set:

192.168.10.77 is a readynas with smb share, the sicrage is a new install on a new win10 pc. If i have problems with right on the folder the setting should not have been blank when going back to the setting after the first error. 

Logs:
```
2017-08-11 02:08:27 Thread-21 :: Unable to create directory \\192.168.10.77\media\bittorrent\downloaded, dir not changed.

Auto post-processing attempted but directory is not set:

**Comment by Tankyspanky** [comment]
I have exactly the same error, i cant give in the folder /mnt/Storage/Downloads 
Then i get a "unable to create directory" error, logical because there are all torents what are downloaded placed.

Any way to fix this??
I hate copying all files by hand and then ned to rescan all files and updates etc
