### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/331608/en.xml

### ISSUE THREAD

**Issue by SteveBeauchemin** [SickChill/SickChill#3977]
### INFO
Python Version: **2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]**
Operating System: **Linux-4.12.3-1.el7.elrepo.x86_64-x86_64-with-centos-7.3.1611-Core**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@91809083cb82732908357e184acd477138277ef5
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [9180908] Unable to connect to theTVDB while creating meta files - skipping - error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/331608/en.xml
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SteveBeauchemin** [comment]
### INFO
Python Version: **2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]**
Operating System: **Linux-4.12.3-1.el7.elrepo.x86_64-x86_64-with-centos-7.3.1611-Core**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@91809083cb82732908357e184acd477138277ef5
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [9180908] Unable to connect to theTVDB while creating meta files - skipping - error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/331608/en.xml
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SteveBeauchemin** [comment]
### INFO
Python Version: **2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]**
Operating System: **Linux-4.12.3-1.el7.elrepo.x86_64-x86_64-with-centos-7.3.1611-Core**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@91809083cb82732908357e184acd477138277ef5
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [9180908] Unable to connect to theTVDB while creating meta files - skipping - error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/331608/en.xml
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SteveBeauchemin** [comment]
### INFO
Python Version: **2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]**
Operating System: **Linux-4.12.3-1.el7.elrepo.x86_64-x86_64-with-centos-7.3.1611-Core**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@91809083cb82732908357e184acd477138277ef5
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [9180908] Unable to connect to theTVDB while creating meta files - skipping - error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/331608/en.xml
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by p0psicles** [comment]
I don't think they already have pulled the plug out of the tvdb api v1, but else it won't take long. I think they will first start shifting resources to be use by the apiv2. And thats partly the reason why these errors occur. To make a long story short. Sickrage should start moving to api v2 real fast.
