### ISSUE TITLE
Incorrect renaming of Anime specials

### ISSUE THREAD

**Issue by plato79** [SickChill/SickChill#3990]
Branch/Commit: master/832ccb445f8eaadef783eddb51880d67d1a77b3d
OS: FreeBSD-11.0-RELEASE-amd64-64bit-ELF
What you did: Put a special episode ( 6.5 ) in process directory with episode 6
What happened: It first got episode 6 and parsed correctly. After that it saw episode 6.5 and assumed it's episode 6 and when it detected it's bigger than original episode 6 it overwrite it with episode 6.5 assuming quality is better than the other file while not detecting that it's not actually episode 6.
What you expected: It should parse it like special episode, or there should be episodes with decimals for anime to correctly parse this file.

I see this a lot when downloading anime titles.
For example in a 12 episode title there is an episode at the half of the series, and in AniDB, they're not numbered as S1 or S2 ( which Sickrage also doesn't understand ) but as 6.5..
Well, as I check my log file, it downloads 1-12 and 6.5.. If it didn't parse episode 6.5 then it should have been ok for me. Unfortunately episode 6.5 is longer than episode 6 by a few kilobytes... So Sickrage assumes this is a better quality, and replaces episode 6 with episode 6.5.. What happened is now you have episode 6 overwritten and episode 6.5 parsed as episode 6, and it shows as there are no specials downloaded... Could somebody fix this problem? Also it would be perfect if other specials are also parsed as in AniDB. Like OP1, ED1, S1, S2 etc.. Instead of S00E01, S00E02 etc..

**Comment by beschoenen** [comment]
AFAIK indexer like TheTVDB don't support episodes with a decimal number, your episode 6.5 might just be something like S0E13. Which show is this?

**Comment by plato79** [comment]
I'm talking about animes.. So, yes, tvdb doesn't support them. In AniDB, they're tagged as S1 or S2..

But when downloading the scene releases from torrent they are not tagged as S1 but tagged as 6.5 or 12.5

One example is Durarara!! episode 12.5 from [Exiled-Destiny] scene group, which is actually episode S1 for that season:

`[Exiled-Destiny]_Durarara!!_Ep01_[BD_1080p_8bit]_(D72DBB49).mkv`
`[Exiled-Destiny]_Durarara!!_Ep02_[BD_1080p_8bit]_(1A831199).mkv`
`[Exiled-Destiny]_Durarara!!_Ep03_[BD_1080p_8bit]_(D3E57817).mkv`
`[Exiled-Destiny]_Durarara!!_Ep04_[BD_1080p_8bit]_(7946AE61).mkv`
`[Exiled-Destiny]_Durarara!!_Ep05_[BD_1080p_8bit]_(EB10AABD).mkv`
`[Exiled-Destiny]_Durarara!!_Ep06_[BD_1080p_8bit]_(D362A5FF).mkv`
`[Exiled-Destiny]_Durarara!!_Ep07_[BD_1080p_8bit]_(B337F55A).mkv`
`[Exiled-Destiny]_Durarara!!_Ep08_[BD_1080p_8bit]_(542FDDFF).mkv`
`[Exiled-Destiny]_Durarara!!_Ep09_[BD_1080p_8bit]_(1B3DB668).mkv`
`[Exiled-Destiny]_Durarara!!_Ep10_[BD_1080p_8bit]_(4403750B).mkv`
`[Exiled-Destiny]_Durarara!!_Ep11_[BD_1080p_8bit]_(20981852).mkv`
`[Exiled-Destiny]_Durarara!!_Ep12.5_[BD_1080p_8bit]_(2FB5E9E3).mkv`
`[Exiled-Destiny]_Durarara!!_Ep12_[BD_1080p_8bit]_(746EC0EC).mkv`
`[Exiled-Destiny]_Durarara!!_Ep13_[BD_1080p_8bit]_(7A58133B).mkv`
`[Exiled-Destiny]_Durarara!!_Ep14_[BD_1080p_8bit]_(6F727F90).mkv`
`[Exiled-Destiny]_Durarara!!_Ep15_[BD_1080p_8bit]_(8F0533AD).mkv`
`[Exiled-Destiny]_Durarara!!_Ep16_[BD_1080p_8bit]_(0DD8DF8B).mkv`
`[Exiled-Destiny]_Durarara!!_Ep17_[BD_1080p_8bit]_(84E2D3B7).mkv`
`[Exiled-Destiny]_Durarara!!_Ep18_[BD_1080p_8bit]_(3F7700A2).mkv`
`[Exiled-Destiny]_Durarara!!_Ep19_[BD_1080p_8bit]_(F30EC15D).mkv`
`[Exiled-Destiny]_Durarara!!_Ep20_[BD_1080p_8bit]_(EC24CCB1).mkv`
`[Exiled-Destiny]_Durarara!!_Ep21_[BD_1080p_8bit]_(5203669D).mkv`
`[Exiled-Destiny]_Durarara!!_Ep22_[BD_1080p_8bit]_(D79E747A).mkv`
`[Exiled-Destiny]_Durarara!!_Ep23_[BD_1080p_8bit]_(CE229CD2).mkv`
`[Exiled-Destiny]_Durarara!!_Ep24_[BD_1080p_8bit]_(14D9077C).mkv`
`[Exiled-Destiny]_Durarara!!_Ep25_[BD_1080p_8bit]_(E2AF9FB3).mkv`

I'm not sure if it's actually possible but comparing the CRC32 could solve the problem. I think you need to dig into AniDB's API though. Checking the file name for CRC32 would be another problem altogether and not all downloads contain CRC32 in the filename.

**Comment by plato79** [comment]
I think the problem lies with anime titles parsed with thetvdb.. If anidb is used instead the problem would be solved altogether. But AFAIK, using direct access to API is restricted to a few clients ( AoM, WebAoM.. ).. Other clients use UDP api and there's a restriction for access per minute.

**Comment by beschoenen** [comment]
We indeed only support episode numbering from thetvdb. So you'll have to follow that if you want to work with anime in sickrage.

**Comment by plato79** [comment]
Is it possible to incorporate https://github.com/xyzz/pyanidb to Sickrage? This was from a very old tool ( 7 years ) but it still works. I understand it would be a lot of work but it would actually make Sickrage better for animes. 

BTW, I checked UDP API restriction. There is a flood protection explained like this:

**Flood Protection**

To prevent high server load the UDP API server enforces a strict flood protection policy.

Short Term:
- A Client MUST NOT send more than 0.5 packets per second (that's one packet every two seconds, not two packets a second!)
- The server will start to enforce the limit after the first 5 packets have been received.

**Long Term:**
- A Client MUST NOT send more than one packet every four seconds over an extended amount of time.
- An extended amount of time is not defined. Use common sense.

Once a client exceeds a rate limit all further UDP packets from that client will be dropped without feedback until the client's packet rate is back down to acceptable levels.

---
Everything available explained here: https://wiki.anidb.net/w/UDP_API_Definition

**Comment by plato79** [comment]
I tried with episode 12.5 I posted here.

Here is the output:
`% anidb -u <anidb_user> -p <anidb_password> -i \[Exiled-Destiny]_Durarara\!\!_Ep12.5_\[BD_1080p_8bit]_\(2FB5E9E3\).mkv
No xattr, caching disabled.`
`Logged in as user: <anidb_user>`
`Hashed: ed2k://|file|[Exiled-Destiny]_Durarara!!_Ep12.5_[BD_1080p_8bit]_(2FB5E9E3).mkv|712673346|16d3a795a46eeefb34a0598a5e11ace9|`
`Identified: [E-D] Durarara!! - S1 - Tenmoukaikai`
`Hashed 1 files.
`

**Comment by beschoenen** [comment]
I can't speak for everyone but I know that the main dev, @miigotu, doesn't really care for anime. So I don't really see it happening.

**Comment by beschoenen** [comment]
You're better off just following TheTVDB and naming your episodes `S00E01`

**Comment by miigotu** [comment]
If someone with the skills to do it properly feels so inclined to improve anime in SickRage I'm not against it, but I lack the time and interest to bother with anime myself.

**Comment by plato79** [comment]
While I'm also a programmer, I am new to python.. If there is no one who could do this I'll try to improve myself enough to contribute to this project.

**Comment by p0psicles** [comment]
I've looked quite a bit into anidb and the possibility of adding it as an indexer. But in the end they make it really impossible to utilize their api's on a large scale. The information offered by their different api's (udp, http, tcp) is very fragmented. To name a few of the issues I had:
1. Searching shows could be done using the xml dumpts. There is also a public http rest api put online. But it's missing show dates.
2. To get detailed show info, you can use the http api. But it's heavy rate limited.
3. The other api's are also rate limited.

Also if you go over the limits you get banned for a duration of time. That alone was very annoying when developing for it.

In the end using some rate limit decorators, and finding a nice workaround for getting the show start dates, you could get something working. But you would have to do allot of exception handling around it. And still it would be nowhere the level of quality as the tvdb indexer. So I doubt it would be accepted into develop.

**Comment by plato79** [comment]
Just started examining the code for post processing. There should be a manual to explain workflow of this much code though. 

I found out that adba library is used for anidb integration and it's at least possible to find out information about episode by checking its' ed2k hash. So if for example an episode is titled like "Fairy.Tail.001.mkv", after finding out it's an anime we wanted ( from DB, checking show's anime flag ) we could run hashing algorithm to calculate ed2k hash and get file information ( release name, episode name, group name, resolution etc.. ).. So there is actually no need to separate anime processing directory, because we could easily find out information about episode if it's in anidb this way.

That's not what I wanted but it's a step closer to identify an episode correctly if the anime name is a match in DB at least. Of course releases outside of AniDB should be processed as before...

The rate limiting is not a problem and it's already integrated in the code. Every time an api call is made if previous call was too close there's a delay added to prevent consecutive calls to the api. I don't think it'll be a problem to call api functions which causes permanent or temporary bans. Also I don't know if it's used in code or not yet but there's a method to keep the connection to AniDB to prevent multiple logins.

But all this information we get belongs to AniDB and I still think I should find out a way to integrate it as an indexer like TheTVDB. As far as I see SickRage is deeply integrated with TVDB and it's too hard to integrate AniDB as an additional indexer... Actually I think while at first the thought was there about multiple indexers, now it's just assumed the indexer we are using is TVDB all the time.
