### ISSUE TITLE
Feature Request: Auto prune functionality

### ISSUE THREAD

**Issue by trideout** [SickChill/SickChill#4001]
There are a number of daily shows which I only want to keep for a number of days. Things like The Late Show, or Jeopardy. A feature which tracks when files were added and keeps them for x period of time would be really nice to keep down HDD space issues and reduce the amount of time spent on managing my library.

**Comment by OldskoolOrion** [comment]
Just keeping last season would already help, for the likes of The Daily Show etc. indeed :-)
