### ISSUE TITLE
Regional airdates

### ISSUE THREAD

**Issue by fallenturtle** [SickChill/SickChill#4003]
I'm following a show that is currently airing on the BBC and will later be airing on an American station. The airdates in Sickrage are showing the future American airdates but since the show is currently airing in the UK the episodes are being posted now. Is there a way to get Sickrage to look for the new episiodes based on the UK airdates or do I have to do it manually?

**Comment by bobbysteel** [comment]
you probably want to look on theTVDB to find the appropriate listing on the BBC network, then re-add the show to your Sickrage library ensuring that same tvdb ID is referenced.
