### ISSUE TITLE
multiple episodes at once = rtorrent Error while sending torrent: Magnet failed to resolve

### ISSUE THREAD

**Issue by chienb** [SickChill/SickChill#4005]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/832ccb445f8eaadef783eddb51880d67d1a77b3d
OS: u14.04
What you did: added whole seasons for different shows
What happened: some episodes were added in paused state and not labeled when whole seasons are grabbed, single torrent works fine
What you expected: episodes should auto start download and labeled when magnet is sent to rtorrent
Logs:
```
2017-08-26 22:32:36 SEARCHQUEUE-BACKLOG-296762 :: Error while sending torrent: Magnet failed to resolve after 10 seconds (load_magnet).
2017-08-26 22:32:36 SEARCHQUEUE-BACKLOG-296762 :: rTorrent: Unable to send Torrent
```

**Comment by pnoeric** [comment]
Ditto, same problem here.

**Comment by chienb** [comment]
I switched over to using blackhole mode with a watch folder in rt
