### ISSUE TITLE
Marvel's Avengers Assemble

### ISSUE THREAD

**Issue by RodriguesGabriel** [SickChill/SickChill#4007]
The show Marvel's Avengers Assemble changes name based on which season it is and torrent site use that last name and SickRage can't download because it doesn't search by that name (this season it's Avengers Secret Wars). Any simple way to fix this or it needs some coding?
(Not saying OS and wtv because that info isn't needed)

**Comment by OldskoolOrion** [comment]
@RodriguesGabriel 

from the top of my head : add additional search terms on advanced tab when editting the show.. its the option at the bottom of the page.. not sure how its exactly called (cant check at the moment) but has the word "scene" in it..

add as many terms u need to catch the releases..
works fine.. for instance i collected the show Les Revenants.. first season I had and was named as such.. s2 was released with dutch subs in 1080p with the english showtitle.. The Returned..

adding The Returned S02 1080p as extra term gave me the wanted eps no matter what the momemt they came out. Guess u can use that :-)

**Comment by RodriguesGabriel** [comment]
tyvm  I'll try that and later update you ;)
