### ISSUE TITLE
SkyTorrents does not work as search provider

### ISSUE THREAD

**Issue by rmbleeker** [SickChill/SickChill#4009]
Branch: master
Commit: 832ccb445f8eaadef783eddb51880d67d1a77b3d
Version: v2017.06.05-1
Database Version: 44.0
OS: Ubuntu 14.04.5 LTS with kernel 4.4.0-92-generic
What you did: Added SkyTorrents.in as a search provider, which seems to not function
Logs:
```
2017-08-29 10:29:28 SEARCHQUEUE-BACKLOG-72449 :: [SkyTorrents] :: [832ccb4] Exception while searching SkyTorrents. Error: IndexError('list index out of range',)
```

**Comment by norey** [comment]
I'm having the same issue. The error specifically is [https://bpaste.net/show/3e211ba38707](url)
