### ISSUE TITLE
Update via Synology package center broke install

### ISSUE THREAD

**Issue by simonwicks** [SickChill/SickChill#4010]
Branch/Commit: Master - Was up to date this morning
OS: Synology DSM6
What you did: Update via package center
What happened: Now it doesn't start
What you expected: It to start :( 
Logs:
```
Not sure how, or can't get to logs
```

Hey guys, usually I just see updates at the top of SR itself and do them manually that way, but today package center was telling me there was an update so I went ahead with that. It took a while, then said it was repairing, now it just wont start at all. I've restarted the NAS and tried installing the app from the community section, but it's still broken. 

Here's a screenshot of the version it's installed. If you need logs or anything and can help me get to them I'll be glad to supply. Gutted, not done a backup since Jan.

http://i.imgur.com/MWWDSbu.png

**Comment by simonwicks** [comment]
After some digging, I'm confused. There's 2 different SR's. I remember something went on a while back, but don't know all the details. I just want one that works and is kept up to date. The one I was using (this one I thought) was being kept up to date, but now it seems to have been overwritten (and broken completely now, cant even install this one from github now) by the other :/

**Comment by simonwicks** [comment]
Ok, managed to install it a fresh now, after a few reboots etc. Bad news, it wouldn't find my backup so having to redo everything from scratch, hopefully i can remember all the settings I had. 

Not sure if I went wrong somewhere which made the package center tell me to update, or something else has gone wrong. 

If I can help out in anyway, let me know. Otherwise, issue over I guess.

**Comment by Taifu02** [comment]
Hey !
Looks like to be the same thing for me. After downloading and installing 20170829-04 on my Syno, I got a 'repairing' status for a while then... impossible to start it again :(
Where did you find you 2nd SR instance ? Don't want to loose all my settings after a new fresh install :/

**Comment by simonwicks** [comment]
@Taifu02 I didn't have two versions installed, I was just saying there's 2 different version of SR on github, different devs. 
If you were on the same build as me, this one, and installed by the syno repo, it seems the other version has since taken over it, which in turn broke this one when we updated. 

You may well be out of luck in terms of getting your settings back, I'm having to go through all of mine again.

**Comment by Taifu02** [comment]
OK :/ thanks for the links
I'll go through a fresh install process, probably the best thing to do
Thanks

**Comment by neoatomic** [comment]
@simonwicks @Taifu02 Looks like the synocommunity approving process is a mess, they updated the package with the old SRTV that is pretty broken. And as a result corrupted your installs. Just use the manual SPK installer, and you are up and running again with the correct version. :+1: 

https://github.com/BenjV/SYNO-packages/raw/master/SickRage%20DSM%206%20noarch%20V1.0.spk

@miigotu This is confusing users, might be a good idea to look into this and inform users about whats happening at the synocommunity repo.

**Comment by simonwicks** [comment]
@neoatomic I tried BenjV's installer thing, downloaded it, but it wouldn't install, it just kept saying 'not available'. I got mine back up running eventually (after a few restarts) via a manual install of the master branch using the 'custom' option in the syno package center, and have spent the afternoon/evening setting everything back up again, so mines all good again now for the most part, just a bit of an inconvenience.

**Comment by neoatomic** [comment]
@simonwicks Apologies about that, but glad you have it up and running again. 
Alternatively you can indeed use the sickbeard-custom method and manually entering the URL. 

Just stair clear of anything with the name `echel0n` `sickrage.tv` or `sickrage.ca` and you should be fine. :+1:

**Comment by simonwicks** [comment]
@neoatomic Not your fault, just a weird hiccup, hope it manages to get rectified. I should be good from now as it's using that other method and pointing direct to the master branch of this version :)

**Comment by kareljan** [comment]
Hey 

I'm having the same problem. I've tried everything and the sickbeard-custom, gives me the same problem. Can you guys give a more detailed explanation of how you solved it?

thanx

**Comment by simonwicks** [comment]
@kareljan I ended up deleting it completely from my Synology, restarting it, then it let me install from the community section using sickbeard custom. You have to change the address it points to, use this guide - https://github.com/SickRage/SickRage/wiki/Switching-your-Synology's-Sickrage-to-the-new-repository#install-sickrage
Then I had to set up from scratch, import all my all shows, let it repopulate etc, and go through adjusting settings for my shows.

**Comment by Taifu02** [comment]
Hey !
I firstly removed echel0n sickrage package.
Then I reinstalled using sickbeard-custom with the correct sickrage git repo (git://github.com/SickRage/SickRage.git) but unchecking the little box that is saying 'starting the package after install' (or something like that, I don't have the exact english translation). Then I rebooted my Synology and started the sickbeard-custom package ans it worked !

**Comment by miigotu** [comment]
I'd like to help, but the synocommunity maintainers are a little bullheaded about the forks. Nothing I can do to make it better.  Someone could of course, create a repo with a good package and we can fork it into here, and maintain it ouselves.

**Comment by BenjV** [comment]
Everybody can use my Sickrage package that is working for DSM 6 as well.
Download it an do a manual install.
It is working perfectly, but if there is a problem, most likely is that due to not removing the old package.

It is to be found here:
https://github.com/BenjV/SYNO-packages/blob/master/SickRage%20DSM%206%20noarch%20V1.0.spk

I have changed the version number of the package to 99999999 so the Echel0n version is lower and you don't get the update request anymore.

**Comment by kareljan** [comment]
Ok finally is working.
I've tried a thousand things, so I don't really know how I did it ;-)
But I guess the sickbeard-cusom with the sickrage git is working (git://
github.com/SickRage/SickRage.git) like Taifu02 said. And enough of
rebooting.

**Comment by z4pst4r** [comment]
Fuck fuck fuck, I did the same thing, update, repair and now it won't start :-(

Is there an update with coming sometime with a fix or do I need to start all over again?? 
I'm terrible at this, took me forever the first time :-(

**Comment by BenjV** [comment]
It is not difficult to start from scratch.
First do an update to the latest version from within SickRage.
Set the path for you serie location correct, and let SickRage scanit.
It will create a new database for you with all yyour series in the.

Just let SickRage scan your folder and it will create a new database with all your

**Comment by Adelscott** [comment]
I managed to get it running with BenjV version. Then I loaded an old backup (may 2017). For some reason I ignore, I couldn't browse to the folder volume1 to find the backup. I had to change permissions on this folder and subfolders, don't know which account it's used by SickRage I gave permissions for anyone until I find it.
Could Echlel0n's version mess up with permissions ?

**Comment by BenjV** [comment]
No the permissions are changed in DSM 6 and so a package that is made for DSM 6 has different setting.
It is never a good idea to give permissions to everybody if not needed.
Permissions can be granted via the group "sc-media", which is created during package installation.

If you had installed the Echel0n version that restoring the backup only work when you are sure it is a version from before that mistake.

**Comment by Adelscott** [comment]
Thanks BenjV, I granted the group sc-media Read and Write. I can't see any user in this group but it seems to work.

BTW, was Echel0n's release a takeover to move everybody from https://github.com/SickRage  to https://git.sickrage.ca ? His setup doesn't seem to ask git repository, so I assume it uses his own.

**Comment by BenjV** [comment]
I added the hidden user in that group but of course it stays hidden, you have to take my word for it.

And yes it uses Echle0n's GitHub, that's why it does not work anymore because the database and the config is not compatible anymore.
Also the old version that the SynoCommunity made was asking for the GitHub, but Echel0n took that out and the core people on the SynoCommunity seems to be absent lately.
Also his version does not work on DSM 6 like a lot of packages on the SynoCommunity site.

I also added a very high version number so you don't get an update anymore, because such an update would get you the Echel0n version again and that's the latest you want.
Updates of the package you don't need, SickRage can update itself.

**Comment by Adelscott** [comment]
The user is sc-sickrage ? That's the one I see on symlinks sickrage creates after moving files from transmission folder.
So your package, the one with version 999999999, uses https://github.com/SickRage ? Where can I check this ? Doesn't seem to appear on UI. I guess I have to use a git command ?

**Comment by BenjV** [comment]
Sorry my mistake, the user is "sc-sickrage" and the group you need for setting access right is "sc-media".
The files created by SickRage are no longer part of the group "users", so you have to give rights via the group "sc-media".

About the GitHub source you have again to take my word for it, but you can check it in SickRage itself after you have installed it.

**Comment by avillegasn** [comment]
I followed the steps and SickRage icon disappeared from Synology UI. How can I get it back? Not sure if that's related to the permissions issue.

**Comment by BenjV** [comment]
No that happens sometimes.
Sometimes logging out and back in will fix this.
If not most of the times a reboot will fix this.

**Comment by avillegasn** [comment]
That's not the case. I logged out and reboot several times. The point is that SickRage is running and if I enter through the URL it works, but the app does not appear in the list of apps of my Synology nor can I create a shortcut in the Synology Desktop.

**Comment by BenjV** [comment]
The default port is 8081.
So http//:<ipadress NAS>:8081 in the browser should work.
Je can also look in the package centre. 
Installed packages.
Click on Sickrage and look at "URL"

**Comment by avillegasn** [comment]
I know that. Maybe I didn't explain it properly (sorry). SickRage does appear in installed packages inside package center. But it does not appear as an app when I click on the start button (the one that seems like the start button in a Windows OS). Therefore, I cannot create a shortcut of SickRage in my Synology Desktop UI, which was something I liked to have.

**Comment by SteveW25561** [comment]
I'm trying to reinstall Sickrage on my new Syno DS918+.  Note I have manually installed "Git Server" (I don't see just "git") and "Python Module" and "Python3."  In my original system I had packages that were called "Git" and "Python".  I can't see these exact names anymore.

When I install via Package manager with the Synocommunity repo, I get this error: 
The following packages are missing in the package server. Please contact the Synology support team for help. **git, python**
When I install using the manually downloaded .spk, I get this error:
**Please install git, python (any version later than 2.7.10)**

What am I missing now?  SR was running great on my original DSM before it died.

**Comment by BenjV** [comment]
The DS918+ has not yet been added to the Synology toolchain and so there are no packages available from the SynoCommunity.

**Comment by Arckain33** [comment]
Hi everyone, 
I managed to get the old sickrage installation i had (Echel0n) working after this update.
At least i can now screenshot every tab and some day i'll install again the "main" version.
The problem was the package tries to launch "SiCKRAGE.py" while the program "main" is SickBeard.py.
I created a symbolic link to make it work.

Here are the steps : 

ssh to your synology and type the following 2 lines :
cd /usr/local/sickrage/var/SickRage
ln -s SickBeard.py SiCKRAGE.py

You should now be able to start the package normally.

**Comment by BenjV** [comment]
Just get rid of the Echel0n bullshit version.
Even if you get it to work it will be broken by the next update Ehel0n puts out.

**Comment by rob006** [comment]
If you want to just ignore this update you can edit `/var/packages/sickrage/INFO` and replace line with
```
version="20150526-1"
```
by
```
version="20170829-4"
```

**Comment by BenjV** [comment]
Replace it with 9999999999 then you never get the update question.
Updaten is done from within Sickrage.

**Comment by Arckain33** [comment]
I'm just trying to help, maybe some people would like to be able to see and screenshot their configuration before "gettind rid of the bullshit version" (whick works perfectly for me, but that's another debate).
I don't know what is your relation with echelon are and i honestly don't care, i created a github account specially to post my solution people because i was happy to make it works and though i could help others.
No need to be agressive about it.

As for your statement that the next update will break it, i highly doubt that as i just created a symbolic link, i don't think any future update will remove it (but i might be wrong, i'm not familiar with the exact update process).

**Comment by BenjV** [comment]
I am not aggressive at all.
I just speak of experience that in the time I used Echl0n's version any update I got had a 80% chance it would break the functionality and just wouldn't run anymore.

And this is the GitHub that Echel0n tried to shutdown with its false accusations, so it is a little strange that you would advertise his version over here.

**Comment by aditvalue** [comment]
Hi

Today i bought my brand new DS218+ and i am currently busy setting things up. I also have my previous synology nas, where sickbeard,NZBGET and couchpotato run like a purring kitten. Now that i'm trying to install sickbeard and couchpotato i get the error:
The following packages are missing in the package server. Please contact the Synology support team for help. git, python
I tried installing git and python, yet i keep on getting this error message.

Also i don't see nzbget anymore.

It's been a VERY long time since i last set this up (i would say about 3/4 years ago) so i'm very rusty. Can anyone please help me?

**Comment by BenjV** [comment]
Packages for a Synology must be compiled with the toolchain from Synology.
The SynoCommunity does not have packages released yet for DSM 6.
For the new DS models Synology only releases a DSM 6.1 toolchain, so until the SynoCommunity figures out how to build packages for DSM 6 there will be no packages for the new DS models.

**Comment by aditvalue** [comment]
I see, thank you so much!

So i got a great superfast synology beast which can't do what i want it to
do 😂
Cheers

Al

Op 10 okt. 2017 20:20 schreef "BenjV" <notifications@github.com>:

**Comment by klue-zz** [comment]
Hi @BenjV 

I'm not able to save any configuration changes since re-installation of your release (nor SickRage-custom or Echel0n versions..) 
SickRage used to give me a pop-up confirming any saved changes, but nothing happens now. Could you please offer any advise? I have cleared browser cache, but no help.

Cheers

**Comment by BenjV** [comment]
Probably a access rights problem.
By using different installation the ownership of the folders is most likely screwed up.
Set the installation folder and its subfolders to the correct owner (e.g. sickrage).
Best to do that with winscp or else via putty.

**Comment by klue-zz** [comment]
Thanks for the reply. It's all good now after a number of uninstall/reinstall with restarts etc. 

Cheers

**Comment by jpmurray** [comment]
Is there anyway to disable the update of Echel0n's version!? It keeps installing it every now and then even if auto update is disabled in DSM...

**Comment by BenjV** [comment]
Read the whole thread I already explained it.
Install my package and this issue is gone forever.
Be sure to uninstall the old package first.

https://github.com/BenjV/SYNO-packages/raw/master/SickRage%20DSM%206%20noarch%20V1.0.spk

**Comment by jpmurray** [comment]
@BenjV this is _exactly_ what I've done at the start of october... Then at the start of November, then yesterday. To be honsest thought, I didn't knew it was supposed to solve the problem.

That being said, it does not. At least not on my end. Would there be anything I could provide or do to try and debug this? I guess some logs the next time would be in order...

**Comment by jpmurray** [comment]
Welp, it just reverted again! I don't want to feel like I'm pushing of anything, but @BenjV, any input on the mechanics of _what_ could cause it to still update/revert to Echel0n's?

- [X] Auto-updated is off.
- [X] I uninstalled.
- [X] Reinstalled using your package. 

I'm honestly out of my league on Synology's flavor of linux systems, so I'm really not sure where I can find anything else of any uses to help here.

**Comment by BenjV** [comment]
The package with the version 99999999 is not Echel0n's version at all.
That is the correct version.
If you take al look at the "Help & info" page you should see that the source is from "https://github.com/SickRage/SickRage/" and that is the correct GitHub.

The package I created has gotten the 99999999 version number to be sure that it is always higher then Echel0n's version to prevent een auto update for silly people who let thing do an auto update.

**Comment by miigotu** [comment]
@jpmurray check your config.ini and make sure the remote is not echel0ns

**Comment by jpmurray** [comment]
@miigotu good call, but it was the good one! :)

@BenjV Then it _has_ to be something else. Sorry for the disturbance!

**Comment by Adelscott** [comment]
@BenjV please could you give me some hints to resolve that https://github.com/SickRage/SickRage/issues/4159 ?

**Comment by ronrosenfeld** [comment]
@BenjV  I have a DS718+ on order. What else do I need to install in order that your SickRage package will work?  I recall that the older package required Python 2.7, but I only see Python 3 being available from Synology.  I don't know if there are any other requirements.  Thanks.

**Comment by BenjV** [comment]
There is not yet a python 2.7 package for the DS718+ and SickRage does not work witj python 3.
You have to wait until the SynoCommunity releases python for this Nas.

**Comment by ronrosenfeld** [comment]
That’s unfortunate.

 

I don’t suppose your source will work with DSM 4.  I have a DS209 that is presently running SickRage.

 

*	The 209 DSM cannot be upgraded past 4 and is currently running the latest version.
*	Sickrage says “no updates required”, but the last update was last June and I am clearly behind
*	For some reason, cannot use `git` on my Synology.

*	If I SSH as root --> git:  not found
*	Assuming it was a previously documented problem with sinology 4 updates, I used the full path and tried to update sickrage manually, but get an error message with any options:

*	DiskStation> /var/packages/git/target/bin/git remote rm origin
fatal: Not a git repository (or any parent up to mount point /volume2)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
*	I really have no idea what to do next.

 

Any thoughts?

 

Ron

**Comment by BenjV** [comment]
Nothing wrong there.
The last update if from June.

**Comment by ronrosenfeld** [comment]
Hmmm.

I thought there was an update in August.

 

Six months seems a long time to go with no updates – on the Windows version (running on a different machine), there have been updates in the interim.

 

Ron

**Comment by BenjV** [comment]
Here you can see an overview op the updates.
https://github.com/SickRage/SickRage/graphs/commit-activity

**Comment by ronrosenfeld** [comment]
Hmm.

 

I can see commits in July and August (8/27), and I think that was what was probably downloaded on my Windows version.

But at this link:  https://github.com/SickRage/SickRage/releases it does show that the latest release was June 5.

Not all that familiar with github, but I guess the Synology version is only getting the releases.  I’ll need to check the actual version number on my windows version when I am back at that computer in a few weeks.

 

Thanks for taking the time to clarify things for me.

 

Now if only someone will do whatever needs to be done so I can get this running on my DS718  (Python issue).

 

Ron
