### ISSUE TITLE
Mako Error opening show with Umlaut characters (äöü)

### ISSUE THREAD

**Issue by Mettbrot** [SickChill/SickChill#4030]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Linux Docker
What you did: click on show containing Umlaut characters ("Tatort Faber & Bönisch & Kossik & Dalay")
What happened: Mako Error appeared
What you expected: the show to open
Logs:
```
Mako Error

A mako error has occured.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

                File /opt/sickrage/gui/slick/views/displayShow.mako:141, in render_content:
                                                            ${show.imdb_info['runtimes']} ${_('minutes')}
                    KeyError: 'runtimes'
```

The (debug) log shows nothing.

**Comment by Mettbrot** [comment]
If I try to edit the show it gives me this error: 

> Error
> 
> near "WHERE": syntax error
> Traceback
> 
> Traceback (most recent call last):
> File "/opt/sickrage/lib/tornado/web.py", line 1511, in _execute result = yield result
> File "/opt/sickrage/lib/tornado/gen.py", line 1055, in run value = future.result()
> File "/opt/sickrage/lib/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info)
> File "/opt/sickrage/lib/tornado/gen.py", line 1063, in run yielded = self.gen.throw(*exc_info)
> File "/opt/sickrage/sickbeard/webserve.py", line 257, in get results = yield self.async_call(method)
> File "/opt/sickrage/lib/tornado/gen.py", line 1055, in run value = future.result()
> File "/opt/sickrage/lib/concurrent/futures/_base.py", line 422, in result return self.__get_result()
> File "/opt/sickrage/lib/concurrent/futures/thread.py", line 62, in run result = self.fn(*self.args, **self.kwargs)
> File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call result = function(**kwargs)
> File "/opt/sickrage/sickbeard/webserve.py", line 1674, in editShow show_obj.saveToDB()
> File "/opt/sickrage/sickbeard/tv.py", line 1165, in saveToDB main_db_con.upsert("imdb_info", newValueDict, controlValueDict)
> File "/opt/sickrage/sickbeard/db.py", line 329, in upsert self.action(query, list(valueDict.values()) + keyDict.values())
> File "/opt/sickrage/sickbeard/db.py", line 260, in action sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
> File "/opt/sickrage/sickbeard/db.py", line 111, in _execute sql_results = self.connection.cursor().execute(query, args)
> OperationalError: near "WHERE": syntax error
> Request Info
> 
> body: show=262997&location=%2Fmnt%2Fuser%2FFilme%2FTatort%2FDortmund&quality_preset=164&anyQualities=4&anyQualities=32&anyQualities=128&defaultEpStatus=5&indexerLang=de&paused=on&season_folders=on&rls_ignore_words=&rls_require_words=
> files: {}
> protocol: http
> connection:
> body_arguments: {'rls_ignore_words': [''], 'defaultEpStatus': ['5'], 'rls_require_words': [''], 'show': ['262997'], 'anyQualities': ['4', '32', '128'], 'indexerLang': ['de'], 'season_folders': ['on'], 'paused': ['on'], 'location': ['/mnt/user/Filme/Tatort/Dortmund'], 'quality_preset': ['164']}
> uri: /home/editShow
> query_arguments: {}
> _start_time: 1506591610.78
> headers: Content-Length: 227 Accept-Language: de,en-US;q=0.7,en;q=0.3 Accept-Encoding: gzip, deflate Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0 Dnt: 1 Host: server:8082 Referer: http://server:8082/home/editShow?show=262997 Cookie: login_cookie=23b17f1e5bd2c599f82bea7725f80dc56c14f850; login_salt=38 Upgrade-Insecure-Requests: 1 Content-Type: application/x-www-form-urlencoded
> host: server:8082
> version: HTTP/1.1
> server_connection:
> host_name: server
> _finish_time: None
> query:
> arguments: {'rls_ignore_words': '', 'defaultEpStatus': '5', 'rls_require_words': '', 'show': '262997', 'anyQualities': ['4', '32', '128'], 'indexerLang': 'de', 'season_folders': 'on', 'paused': 'on', 'location': '/mnt/user/Filme/Tatort/Dortmund', 'quality_preset': '164'}
> path: /home/editShow
> method: POST
> remote_ip: 192.168.178.30

with the following log:

> 2017-09-28 11:40:10 Thread-15 :: [75b6d2f] DB error: near "WHERE": syntax error
>                         2017-09-28 11:40:10 Thread-15 :: [75b6d2f] Failed doing webui callback: Traceback (most recent call last):
>   File "/opt/sickrage/sickbeard/webserve.py", line 273, in async_call
>     result = function(**kwargs)
>   File "/opt/sickrage/sickbeard/webserve.py", line 1674, in editShow
>     show_obj.saveToDB()
>   File "/opt/sickrage/sickbeard/tv.py", line 1165, in saveToDB
>     main_db_con.upsert("imdb_info", newValueDict, controlValueDict)
>   File "/opt/sickrage/sickbeard/db.py", line 329, in upsert
>     self.action(query, list(valueDict.values()) + keyDict.values())
>   File "/opt/sickrage/sickbeard/db.py", line 260, in action
>     sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
>   File "/opt/sickrage/sickbeard/db.py", line 111, in _execute
>     sql_results = self.connection.cursor().execute(query, args)
> OperationalError: near "WHERE": syntax error

**Comment by lejudoka13** [comment]
same things +1

**Comment by Mettbrot** [comment]
I decided to take things into my own hands and repair the database on my own using http://sqlitebrowser.org/
There was an entry missing in imdb_info which I added. I suspect it had nothing to do with the umlauts. Strange how this can happen though.. Is there a "maintenance mode" in sichbeard or something which repairs these kind of DB faults?
