### ISSUE TITLE
Missing Icon for CBS All Access

### ISSUE THREAD

**Issue by 03397** [SickChill/SickChill#4047]
There is an icon missing for specific show namely CBS All Access.
The snow is named  Star Trek: Discovery http://www.imdb.com/title/tt5171438/.

### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by JayTurnr** [comment]
The icon is available in the Public Domain here: https://en.wikipedia.org/wiki/CBS_All_Access#/media/File:CBS_All_Access.png

**Comment by 03397** [comment]
In which folder should I put the file?
Which resolution should I download.
I have insert it to  /share/MD0_DATA/.qpkg/SickRage/SickRage/gui/slick/images/network/ with no effect.

**Comment by 03397** [comment]
I have managed to make SIckrage to recognize the png picture but it looks very blurry.
I have tried different resolutions but it seems that  Sickrage is shrinking the size length.
![image](https://user-images.githubusercontent.com/6150853/30631356-9c921f0c-9dec-11e7-8c3b-dd4ce3fad839.png)

**Comment by JayTurnr** [comment]
How did you make it recognize? What did you have to name it? 
I am going to refactor the logo a little so it fits the box

**Comment by 03397** [comment]
The problem is it is case sensitive. I have rename it to cbs all access.png. After this it was recognized just fine, 
Problem is the resolution.

**Comment by JayTurnr** [comment]
See pull request #4053

**Comment by JayTurnr** [comment]
@03397 For clarification, I looked at the files in the folder and found that they are all 64x32, which is super small. As the CBS All Access logo is mostly text with a fancy A in a box at the right side, I submitted the A as the logo, at the right dimensions.

**Comment by 03397** [comment]
@JayTurnr 
Thanks. I confirmed that. The logos are 64x32. I have tried to transform one of the CBS logs to 64x32 but this still creates the blurry image.

**Comment by 03397** [comment]
@JayTurnr 
Hey there. How am I going to get the updated icon?
Is it going to be included in one of the future releases?
