### ISSUE TITLE
Feature Request: YouTube series

### ISSUE THREAD

**Issue by JayTurnr** [SickChill/SickChill#4048]
An ability to subscribe to download items in a YouTube playlist - could hook into the YouTube [PlaylistItems ](https://developers.google.com/youtube/v3/docs/playlistItems) and [Playlists](https://developers.google.com/youtube/v3/docs/playlists) API calls.

Edit: YouTube Red too, apparently people use that.

**Comment by LeePorte** [comment]
I'd add to this the ability to search against Youtube Red series.

**Comment by JayTurnr** [comment]
Oh, yes, definitely!
