### ISSUE TITLE
Sports indexers

### ISSUE THREAD

**Issue by smorison** [SickChill/SickChill#4052]
Hey team,
There have been a few requests over the years since sports got booted from other indexers... any chance of looking into adding a sports indexer? 

Thesportsdb seems to be pretty mature with its API, if i could code i’d give it a go. 

Thanks for considering!!!

**Comment by joeportela** [comment]
@miigotu I'm interested in getting support for sports indexers, namely TheSportsDB.  I can build it if there would be interest in getting it eventually merged on your end.

**Comment by miigotu** [comment]
It's a possibility, we can add it after I get movies working using the new db format (sqlalchemy)

I'm currently working on it in the develop branch.

Indexers need to be reworked again, I'm not happy with my last rewrite of them.
