### ISSUE TITLE
Missing TV networks for Turkey

### ISSUE THREAD

**Issue by mzeyrek** [SickChill/SickChill#4056]
Is it possible to add below missing networks  ?

TRT 1 : https://en.wikipedia.org/wiki/TRT_1
Kanal D : https://tr.wikipedia.org/wiki/Kanal_D
ATV : https://en.wikipedia.org/wiki/ATV_(Turkey) 
PuhuTv : https://tr.wikipedia.org/wiki/Puhutv

Thanks

**Comment by bobbysteel** [comment]
why don't you make the commits and file a PR? quite easy :)

**Comment by mzeyrek** [comment]
I did a commit yesterday but due skytorrents issue it can't pass tests. Failing with  The Travis CI build failed.
Therefore it would be much easier for the OP to commit directly as there is no clear guideline about dimensions.

**Comment by JayTurnr** [comment]
I second this... mine has entered some kind of hell and been flagged 'Do Not Merge' and all sorts of stuff
