### ISSUE TITLE
Seeding stop aumatically

### ISSUE THREAD

**Issue by Adelscott** [SickChill/SickChill#4059]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Synology DSM 6
What you did: Torrent snatched
What happened: Torrent stops seeding after completion (don't know when exactly) marked as completed
What you expected: Torrent seed forever (seed ratio at -1 for the providers)
Logs:
```
PASTE LOGS HERE
```
I''ve seen this in error log, seems related :
2017-09-24 02:49:03 MANUAL :: [d8c2613] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/sickbeard/webserve.py", line 4877, in saveProviders
    sickbeard.save_config()
  File "/volume1/@appstore/sickrage/var/sickbeard/__init__.py", line 2063, in save_config
    'torrent_seed_time': int(TORRENT_SEED_TIME),
ValueError: invalid literal for int() with base 10: ''

**Comment by plato79** [comment]
As far as I know Sickrage is not responsible of client's seeding rules. So configure your seed rules in the client.

**Comment by Adelscott** [comment]
As far as I know, you're wrong. There's a seed setting in SickRage for each torrent provider. If you had read my post carefully you would have seen "Torrent seed forever (seed ratio at -1 for the providers)"

**Comment by plato79** [comment]
So how did you configure your torrent client? Maybe it's related to that.
