### ISSUE TITLE
Issue submitter doesn't submit issues. Fav bug ever.

### ISSUE THREAD

**Issue by JayTurnr** [SickChill/SickChill#4061]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master d8c2613583ce8b321a5adc9ff70c52e830f224a8
OS: Arch Linux
What you did: Hit Submit Errors
What happened: It errored
What you expected: Not more errors...
Logs:
```
2017-09-26 00:43:58 Thread-19 :: [d8c2613] Traceback (most recent call last):
File "/opt/sickrage/app/sickbeard/logger.py", line 325, in submit_errors
regex = r'^({0})\s+([A-Z]+)\s+[A-Za-z0-9\-\[\] :]+::\s(?:\[[\w]{7}\]).*$'.format(re.escape(cur_error.time))
IndexError: tuple index out of range

2017-09-26 00:42:38 SEARCHQUEUE-BACKLOG-72218 :: [SkyTorrents] :: [d8c2613] Exception while searching SkyTorrents. Error: IndexError('list index out of range',)
```

**Comment by mzeyrek** [comment]
I can confirm this bug and looks like affecting all pull requests. I tried to merge some translation text but failed due same error.

======================================================================
143) ERROR: Check that SkyTorrents returns results in proper format
----------------------------------------------------------------------
   Traceback (most recent call last):
    sickrage_tests/providers/torrent/parsing_tests.py line 172 in test_result_values
      results = self.provider.search(self.search_strings('Episode'))
    /home/travis/build/SickRage/SickRage/sickbeard/providers/skytorrents.py line 117 in search
      info_hash = download_url.rsplit('/', 2)[1]
   IndexError: list index out of range
