### ISSUE TITLE
Download Subtitle Only for HDTV Version 

### ISSUE THREAD

**Issue by Rakan-10** [SickChill/SickChill#4062]
Hi ...

Is there a way to make SickRage download subtitle only for HDTV version? The WEB-DL version (AMZN, NF) is already embedded with eng sub

**Comment by rmbleeker** [comment]
I believe that when you leave the checkbox for the option **Embedded Subtitles** OFF it will check the downloaded MKV file for embedded subtitles and not download them if subs in your preferred language(s) are found inside. If you turn that option ON it will ignore embedded subs and download them anyway.

**Comment by Rakan-10** [comment]
So did I, but it doesn't solve the issue. It still downloads srt files for AMZN version which it's already has an end sub.
