### ISSUE TITLE
Unknown status (Unknown)

### ISSUE THREAD

**Issue by MrNightRyder** [SickChill/SickChill#4085]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master Commit: d8c2613583ce8b321a5adc9ff70c52e830f224a8
OS: Server 2k12 R2
What you did: absolutely nothing....
What happened: For several versions of the software I've had this happen where it shows up as status unknown and i find myself missing episodes of tv shows.  What causes this and how do you fix?  It's super annoying because i find myself having to go back and restatus everything i haven't gotten as "Wanted"  see screenshot: https://imgur.com/a/Tf0ez
What you expected: the software to work.
Logs: Unknown when it's happening so hard to show you logs
```
PASTE LOGS HERE
```
Unknown when it's happening hard to show you logs.

**Comment by MrNightRyder** [comment]
Anyone?  As mentioned this has been happening for several releases and i have no easy way to fix them I have to go through every single series by hand... i really prefer to use your platform but if i can't find a solution I'll have to move to sonarr.

**Comment by walterhpdx** [comment]
I've been having this same exact issue, and it's been going on for at least early September.

**Comment by Falconne** [comment]
I've had this issue for a long time. It's difficult to debug because you never know when the software decides it's going to mess up the status. It may take one or two weeks for the problem to happen. Would keeping a debug log going for a few weeks be practical? I don't want to run out of disk space.

**Comment by loryans** [comment]
I've also had this issue for a long time. I just make it a point every few days to go through and look for any shows where it says "Continuing" and double-check for any air episodes.
Setting Unknown to Wanted generally makes it go away, but I have had it come back a few times for the same show over a long period.

**Comment by Falconne** [comment]
@miigotu This problem still exists. It's just that no one's had the time to debug it.

**Comment by Deepcuts** [comment]
Having the same problem.
If I do a manual search, it will find and download the episode.

**Comment by miigotu** [comment]
I think you need to go in and set default episode status to wanted:

go to `/manage/` and click the check box to edit all shows you want updated, click `edit selected`, change `default episode status` to `wanted`, and click `save changes`

**Comment by Deepcuts** [comment]
> I think you need to go in and set default episode status to wanted:
> 
> go to `/manage/` and click the check box to edit all shows you want updated, click `edit selected`, change `default episode status` to `wanted`, and click `save changes`

Did that several times. No luck.
Many episodes from various shows will be listed as "Unknown Unknown"
For some shows, two weeks can pass by until I realize I get no new episodes. I have to go to that show and manually search the "Unknown" episodes.

**Comment by miigotu** [comment]
This has never happened to me, and I am unable to reproduce.

**Comment by Deepcuts** [comment]
I had to backup, completely remove SickChill, install the latest version and import the back.
Then, I did as you suggested, updating all shows default episode status to wanted and only then the problem went away.
Thank you.

**Comment by Deepcuts** [comment]
Sorry to reopen this, but after couple of days working OK, this problem came back.
Several shows have their status for already aired episodes as Unknown.
If I click on Manual Search, it will find the episode and download just fine.
Setting Default Episode Status to Wanted via mass edit does nothing for already aired episodes with unknown status.

**Comment by miigotu** [comment]
If they are already aired you need to set them all from unknown to wanted. Your db got messed up when using some other fork it seems.

**Comment by Deepcuts** [comment]
Edited the sqlite db, selected all episodes with the status value of -1 (unknown) and set them to 3 (wanted)
Will see how it goes.
Indeed, this install went through all that sickrage->sickchill move.
