### ISSUE TITLE
Manually added subtitles not detected

### ISSUE THREAD

**Issue by rmbleeker** [SickChill/SickChill#4086]
Branch: master
Commit: d8c2613583ce8b321a5adc9ff70c52e830f224a8
Version: v2017.06.05-1
Database Version: 44.0

OS: Linux
What you did: Manually added subtitles that SickRage couldn't find, then did a full update on the shows
What happened: SickRage doesn't see the subtitles and still lists them under "Missed Subtitle Management". They're also not showing on the shows page
What you expected: SickRage to detect the subtitles and acknowledge that they're present

I sometimes manually add subtitle files that SickRage was unable to find. Even with the proper file naming scheme SickRage never detects these subtitles and acts as if they're not there. I hope some functionality can be added so when SickRage performs a full update of a show, it also checks for subtitle files and shows them as available if they weren't before.

**Comment by rmbleeker** [comment]
Is this a "won't fix" or was this closed for some other reason?

**Comment by rmbleeker** [comment]
Can feature requests become stale? Should I perhaps make the feature request somewhere else? I seem to remember there used to be a thing for that.

**Comment by WebSpider** [comment]
They shouldn't.

**Comment by miigotu** [comment]
Stalebot might have to go, it seems broken
