### ISSUE TITLE
Find a use for the sickrage.tv domain

### ISSUE THREAD

**Issue by WebSpider** [SickChill/SickChill#4089]
For historic reasons, I am the owner of the sickrage.tv domain.

I have put my active days within the sickrage community behind me, and would like to donate the domain, if you have any use for it.

If not, it goes up for auction, proceeds will go to EFF.

**Comment by abetancort** [comment]
Sell it.

**Comment by OmgImAlexis** [comment]
@WebSpider I'd be more than happy to setup a redirect from that domain to this repo if that's good with you; Otherwise I'll be watching for the auction as I'd like to grab it.
