### ISSUE TITLE
Request: TuSubtitulo

### ISSUE THREAD

**Issue by ajtudela** [SickChill/SickChill#4096]
It would be great uif I could add tusubtitulos.com provider.

There are some apis  for kodi like this:
https://github.com/ldotlopez/tusubtitulo

https://github.com/josecurioso2/service.subtitles.tusubtitulo

**Comment by daniesteban** [comment]
It seems the owner of tusubtitulo.es isn't/wasn't very "collaborative" with people who want to get subtitles from the web trough scripts: https://github.com/Diaoul/subliminal/issues/460
