### ISSUE TITLE
Anonymous redirect keeps getting filled in to default

### ISSUE THREAD

**Issue by Rouzax** [SickChill/SickChill#4104]
Not a big issue but since a few versions the anonymous redirect keeps getting filled out even when I remove it myself. It seems that each updates restores the default value of `http://dereferer.org/?`
![image](https://user-images.githubusercontent.com/4103090/32017044-d2325416-b9c5-11e7-946c-cc157d7df3ea.png)

**Comment by Rouzax** [comment]
Am I the only one with this issue?

**Comment by Halvhjearne** [comment]
this is getting quite annoying ... 
i have also had this problem for a while now, but was expecting it to be a minor error or whatever and expected it to be fixed quickly, but now its becomming a real pia every time i go to a link in sickrage after an update.
will you please stop resetting this link on every update?

**Comment by MilhouseVH** [comment]
http://dereferer.org appears to have dropped off line (at least in the UK) - it no longer has a DNS entry.

As per the OP it's not possible to set a blank `Anonymous redirect` field as each time SickChill is restarted the field is reset back to `http://dereferer.org/?` which is preventing access to external sites.

Testing with master branch, commit f42794fb5d8746eeb7fa7462fd3aead87a2b780b (latest at time of writing)

**Comment by MilhouseVH** [comment]
Thanks for the fixes.

I can also confirm that changing http://dereferer.org to https://dereferer.me/? is working in the current release (f42794fb5d8746eeb7fa7462fd3aead87a2b780b) and the setting survives a restart. :+1:

**Comment by twinden** [comment]
Thanks ! 
Changing the url in Settings / General / Advanced to https://dereferer.me/ ? worked !
