### ISSUE TITLE
Link in wiki

### ISSUE THREAD

**Issue by ghost** [SickChill/SickChill#4109]
The [wiki here](https://github.com/SickRage/SickRage/wiki/Installation-&-Configuration-Guides) links to this page for installatino instructions on CentOS7.
http://deviantengineer.com/2015/06/usenet-centos7/

But this page now shows how **NOT** to use SickRage and move to Sonarr... you may want to change this! :D

**Comment by abetancort** [comment]
SickRage is being deprecated by most due to the lack of active development. I can’t blame them.

**Comment by OmgImAlexis** [comment]
@abetancort no it's not.. if I have to I'll start removing comments like that.

**Comment by OmgImAlexis** [comment]
@Thijxx that page is from 2015 and offsite. We'll update the wiki to link to a new guide when we can.
