### ISSUE TITLE
Cannot point to directories on NAS

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#4117]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Windows 10
What you did: Tried browsing to my network share both as the local mount point and UNC path.
What happened: Sickrage will only let me browse to local folders
What you expected: I was hoping to continue using my NAS
Logs: [not applicable]
```
PASTE LOGS HERE
```

**Comment by Tiwas** [comment]
Ok. This was because I ran it as a service, so my fault. Would be nice to be able to add username and password for a UNC path, though.

**Comment by bobbysteel** [comment]
You should be able to include a username and password in a UNC path though

**Comment by Tiwas** [comment]
@bobbysteel How would you do this in SickRage? The UNC paths are formatted \\host\share\folder, right? I guess smb://username:password@host/share/folder would be the right way to do it from a shell, but will that work with SR? Sorry if I'm being a noob here, but...I'm a windows person. That's my only excuse :p

**Comment by bobbysteel** [comment]
The easiest would be to mount as drive using these credentials and something like ``` net use Z: \\server\path /user:name password ```

**Comment by Tiwas** [comment]
That's what I'm doing now, but that prevents me from running it as a service. The optimal solution would be to run as much as possible as services in case there's a reboot or something.
