### ISSUE TITLE
Sickrage doesn't pick Amazon rips?

### ISSUE THREAD

**Issue by plato79** [SickChill/SickChill#4127]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/d8c2613583ce8b321a5adc9ff70c52e830f224a8
OS: FreeBSD-11.0-STABLE-amd64-64bit-ELF
What you did: Search for episode S04E06 of How to Get Away with Murder
What happened: It found in RARBG but ignored it
What you expected: I expected it to download 1080p Amazon WEBRip ( = WEB-DL ) 
Logs:
```
2017-11-08 08:26:05 DEBUG    SEARCHQUEUE-BACKLOG-281620 :: [Rarbg] :: Using cached parse result for: How.to.Get.Away.with.Murder.S04E02.Im.Not.Her.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv]
2017-11-08 08:26:05 DEBUG    SEARCHQUEUE-BACKLOG-281620 :: [Rarbg] :: Any,Best = [ 1080p WEB-DL, 1080p BluRay ] [ None ] Found = [ 1080p WEB-DL ]
2017-11-08 08:26:05 DEBUG    SEARCHQUEUE-BACKLOG-281620 :: [Rarbg] :: Episode already exists with quality 720p HDTV and the found result has same/lower quality, ignoring found result for How to Get Away with Murder S04E02 with quality 1080p WEB-DL
2017-11-08 08:26:05 DEBUG    SEARCHQUEUE-BACKLOG-281620 :: [Rarbg] :: Ignoring How.to.Get.Away.with.Murder.S04E02.Im.Not.Her.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv]
```

~~I am not sure but does Sickrage know that WEBRIP = WEB-DL? Because some scene releases tagged with WEBRIP instead of WEB-DL but they're same thing.~~ 

Edit: Ok, it seems it detects it's 1080p WEB-DL but why doesn't download it?

**Comment by Wally73** [comment]
it doesn't download as you have your pref and archived quality settings not
set up right

Episode already exists with quality 720p HDTV and the found result has
same/lower quality, ignoring found result for How to Get Away with
Murder S04E02 with quality 1080p WEB-DL


pref is 720p HDTV, archived should be 1080p web-dl and then it should pick up

**Comment by plato79** [comment]
But I set it as allowed 1080p web-dl and 1080p blu-ray. I downloaded in the past as 720p HDTV but now it is in yellow as it is not in allowed range. I think it should get 1080p web-dl as it is now in the allowed

**Comment by plato79** [comment]
I set the preferred to the same values as in allowed ( 1080p WEB-DL, 1080p Bluray ). Now it should work. But I think it should work when I set them only in Allowed and not in the Preferred.

If you select set qualities like HD1080p, it sets only allowed part as 1080p HDTV, 1080p WEB-DL and 1080p Bluray.

The only difference is I don't prefer to download 1080p HDTV, so that's why I use custom.

**Comment by didyouexpectthat** [comment]
I think you should allow 1080p HDTV and prefer 1080p WEB-DL/Bluray.  It will get a 1080p HDTV if no 1080p WEB-DL/Bluray is available, but replace later.  
Correct me if I'm wrong, but prefer is also an allowed rule, but allowed says that you find that the quality is allowable to not need to update it to a better quality.

**Comment by plato79** [comment]
First, as you can see from the log the quality I have ( not actually as I'll explain later ) is 720p HDTV and it's not in Allowed or Preferred. So it should replace that quality.

I was using the configuration like that though.. HDTV, WEB-DL, Bluray as allowed, WEB-DL and Bluray as preferred. But I saw that I download both HDTV and WEB-DL version a few days apart and realized that I really don't use HDTV release at all.. So I only selected WEB-DL and Bluray as Allowed and no preferred selection thinking that should be enough.

BTW, I realized that the episode I mentioned had 720P HDTV as snatched not as downloaded. So actually there was no file but a file in torrent client queue was 720P HDTV.. When the BACKLOG checked it again, and found 1080P WEB-DL, it doesn't get that and wait for 720P HDTV release first it seems.

When the file is downloaded as 720P HDTV it'll probably replace it with 1080P WEB-DL.
