### ISSUE TITLE
Feature Request: Set API Limits for Search Providers

### ISSUE THREAD

**Issue by LeeThompson** [SickChill/SickChill#4136]
A useful addition would be to specify how many API calls per day each search provider allows (with 0 being unlimited).

I use several, and some are unlimited and some are not.    I try to move the limited ones to the lower part of the list.

**Comment by Kramasz** [comment]
I have a question on this topic-- if you receive this message
"2017-11-16 08:07:47 INFO SEARCHQUEUE-BACKLOG-330151 :: [NZb.su] :: Request failed: 429 Client Error: Too Many Requests for url: "

What happens with that searched item that returns request failed? Does it show up as a failed download and mark the NZB as such, or does SR know that that NZB download wasn't successful and return it to backlog?

I've been trying to mitigate this by pausing a bunch of my shows, but I've gotten a bit out of hand with my amount of shows that are in the search queues.

**Comment by LeeThompson** [comment]
I should update on this a bit more, there seems to be an issue with Sickrage (design or bug I'm not sure) where the provider order really doesn't seem to make any difference since Sickrage appears to search all providers. 

The way it appears to search is it creates searches for each provider, in the order given, but does them as a group.  As results/errors return they come back from all the enabled providers regardless of order (of course the order of results is typically simliar to the provider order depending on speed/timeouts etc).


The way I (and probably others) expected the search provider order to work is:
Provider "A" is searched first, if a suitable release is _not_ found, search Provider "B", if a suitable release is _not_ found, search Provider "C", etc.

Currently the provider search order really doesn't make any difference.

**Comment by brianjmurrell** [comment]
I think this would be useful.  Can it be reopened or should I create a duplicate issue?

**Comment by offbyone** [comment]
I have persistent issues with this as well with one of my providers, to the point where I need to disable backlog searches entirely.
