### ISSUE TITLE
Some API Feature Requests

### ISSUE THREAD

**Issue by LeeThompson** [SickChill/SickChill#4141]
**sb.startdailysearch**
Manually trigger the daily search function

**sb.stopdailysearch**
Abort the daily search function (if it's in progress, otherwise, ignored)

**sb.startsubtitlesearch**
Manually trigger search for subtitles (if enabled)

**sb.startpropersearch**
Manually trigger search for propers.

Basically this would be an API interface for the functions on the "manage searches" page.

**Comment by HappyTreeBeard** [comment]
It would be easy to add startdailysearch, startsubtitlesearch, and startpropersearch. I'm not sure if there is an easy way to implement any sort of stop action function, e.g. stopdailysearch. 

sickbeard.scheduler.Scheduler has a stop event but this would kill the entire Scheduler object and only after the current action is complete. Pausing a queue also would not stop a search in progress.
