### ISSUE TITLE
column sort doesn't work while new show is being added

### ISSUE THREAD

**Issue by lewis269** [SickChill/SickChill#4146]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: QNAP linux x86_64

What you did: attempted to sort columns by episodes / alphabetically etc... on main shows page whilst a new show is attempting to be added.(as per screenshot)

What happened: nothing

What you expected: the sort to still work whilst "Loading...(New show name)" appears at the top of the list. have tested this on chrome / IE / firefox all with the same result.

Logs: nothing appeared in the logs as i think this is a GUI issue.

not fussed if this gets fixed or not, but it is annoying when adding multiple shows

thanks

![image](https://user-images.githubusercontent.com/27728386/32989513-9af6048e-cd52-11e7-92ef-bd19b755d32e.png)

**Comment by zflash** [comment]
Same thing happens to me
