### ISSUE TITLE
Sickrage doesn't update on Synology

### ISSUE THREAD

**Issue by Vilscon** [SickChill/SickChill#4158]
I noticed Sickrage hasn't updated in months. After checking, the last update was since June. I checked the branche, but that one does correctly directs to to here. Can't find a 'Check for update' icon/button either. How do I update Sickrage on my Synology?

Branch/Commit: Master / d8c2613583ce8b321a5adc9ff70c52e830f224a8
OS: Synology
What you did: Nothing
What happened: Well.. actually nothing as well
What you expected: An update button to appear or be available

// There are no logs that are related to updates.

Update: I found the (obvious located) update button. When clicking on 'check for update' it says "no update needed".

**Comment by bobbysteel** [comment]
Easier to run via Docker. There was a big issue with a takedown request and another version has tried to hijack this version

**Comment by repulse** [comment]
Unfortunately, not all Synology can run Docker...

**Comment by Vilscon** [comment]
I've currently disabled Sickrage and trying Sonarr.
Not seeing any major differences in function, but trying another jacket every now and then can be fun.

My DS216+ can run Docker without a problem, btw.

**Comment by repulse** [comment]
Tried Sonarr too, but it's unable to get all my tv shows, when Sickrage can. There is always some show that can't be found for whatever reason...
So, running Sickrage on Docker is more up to date than Synology app that is actually on v2017.06.05-1 ?

**Comment by Vilscon** [comment]
I do wonder why Docker can run a more up to date version instead of the Synology package, while they both relate and update from the same Github branche?

**Comment by bobbysteel** [comment]
You're looking at the wrong package then. It should be using the Sickrage
version here: https://github.com/SickRage/SickRage which has last update on
August 31st.

Follow directions here:
https://github.com/SickRage/Sickrage/wiki/Sickrage-installation-packages

**Comment by bobbysteel** [comment]
yeah follow that wiki link and use the other synology package linked there

**Comment by bobbysteel** [comment]
actually that link seems outdated - here's the fresh one
https://github.com/BenjV/SYNO-packages/blob/master/SickRage%20DSM%206%20noarch%20V1.0.spk?raw=true

**Comment by repulse** [comment]
How is this version different ?

**Comment by bobbysteel** [comment]
there is a whole lot of drama but in short, there is SickRageTV and
SickRage. SickRage is a fork off SickRageTV. SickRageTV then filed a
takedown for SickRage and took over that Synology package source it seems
and points it to his code which seems to be only maintained by him.
SickRage is a fork that has most of the other developers working on it, so
it seems more maintained and robust.

**Comment by repulse** [comment]
Is it really different than this method, which still work on DSM 6 ?
https://github.com/SickRage/SickRage/wiki/Switching-your-Synology's-Sickrage-to-the-new-repository#install-sickrage

**Comment by bobbysteel** [comment]
That should work the same if you use that url

**Comment by BenjV** [comment]
No that is not the same.
The package from the SynoCommunity are not working correct on DSM 6 (they are working on it).
So in the meantime I advice to use the package I created.

**Comment by repulse** [comment]
What is not working with SynoCommunity package ?
I'm using it since long time ago now, and almost never experienced problem or strange behavior.

**Comment by BenjV** [comment]
That's because you had it already installed when you upgraded from DSM 5 to DSM 6.
A new install does not functionate, the package will not start then.

**Comment by ediazrod** [comment]
What is the final status of the SickRage? have time with out maintenance?, is stopped?.

**Comment by solipsist01** [comment]
use the sickbeard-custom package, and point it to the right fork URL.
trust me, it works.

**Comment by ronrosenfeld** [comment]
Actually, Sickrage (Sickbeard-custom fork) just updated a few days ago. v2017.12.19-1 is the version now showing.  That was on my old DS209 and the update showed up in the web GUI.  This was the first update since last June.  Unfortunately, I have not been able to run Sickrage on my new DS718+, since Python2.7 and Git have not yet been available from Synocommunity.

**Comment by bobbysteel** [comment]
If you have a plus run docker on it and add sickrage that way

**Comment by ronrosenfeld** [comment]
Isn't the version of sickrage on docker the one supported by echel0n?

**Comment by bobbysteel** [comment]
There are lots of versions on docker. Linuxserver/sickrage is the best

**Comment by ronrosenfeld** [comment]
Do you know who is supporting that version?

**Comment by bobbysteel** [comment]
Linuxserver. They've got docs on that page how they build it. Google it. I
also maintain a medusa one at bobbysteel/medusa

**Comment by ronrosenfeld** [comment]
Thanks.  I will look it over.

**Comment by ronrosenfeld** [comment]
OK, I've downloaded Docker and installed it.  And then installed the Linux/sickrage (which does seem to be the same version that I wanted to use).  And I am working my way through the binding and permission issues Binding seems relatively straightforward but tedious.  Permissions not so much, but since this is a home unit, I don't have to really be concerned about privacy.  However, it does seem to work quite well.  Thank you for your pointer to that resource.

**Comment by llonca13** [comment]
If it works dont fix (update) it :D
