### ISSUE TITLE
Daily search only searches for better quality if Custom quality is selected

### ISSUE THREAD

**Issue by PancakeZik** [SickChill/SickChill#4171]
Branch/Commit: master
OS: Windows
What you did: 
1. Set TV Show preferred quality to HD1080p
2. Snatched a 720p Episode manually (its status turned yellow (Allowed))
3. Forced daily search to grab 1080p that's in the feed.

What happened:
Daily search didn't try to find the episode. Backlog search did, but that's not the point.

What you expected:
Daily search should check if better quality if available.

Workaround:
1. Changed the TV Show preferred quality to Custom (Allowed: 720p, Preferred 1080p)
2. Ran daily search again
3. It worked,, snatching the 1080p version from the db.

**Comment by herbi3** [comment]
Same problem here,

switched to the repo at git.sickrage.ca/sickrage (https://github.com/SiCKRAGETV/SiCKRAGE)

the support is far more responsive, and the issues are actually fixed promptly
