### ISSUE TITLE
Browser notifications broken (Chrome/Edge)

### ISSUE THREAD

**Issue by Pbroc** [SickChill/SickChill#4172]
Branch: master
Commit: d8c2613583ce8b321a5adc9ff70c52e830f224a8
OS: Linux-4.4.24-x86_64-with-glibc2.2.5
What you did: Tried to save changes 
What happened: No notifications showing to confirm the saving.
What you expected: A notification to confirm any changes
Logs: no particular logs in debug mode

It still works with Firefox Quantum.

**Comment by DDA78** [comment]
+1

developer tools in chrome shows below info

[Deprecation] The Notification API may no longer be used from insecure origins. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
permission @ vender.min.js:1
