### ISSUE TITLE
Sickrage wont find any subs to download

### ISSUE THREAD

**Issue by AlexGr3** [SickChill/SickChill#4184]
Branch/Commit:master/d8c2613583ce8b321a5adc9ff70c52e830f224a8
OS: Linux-4.9.59-v7+-armv7l-with-debian-9.1
What you did: I enabled subtitles searching.
What happened: Sickrage wont find any subs whatsoever.
What you expected: To find subs.
![screenshot_23](https://user-images.githubusercontent.com/34418662/33805849-c05a58a8-ddc7-11e7-9f90-c260b8cb4b5f.png)
![screenshot_22](https://user-images.githubusercontent.com/34418662/33805850-c07d0ce0-ddc7-11e7-9b50-2b912e963a05.png)
![screenshot_21](https://user-images.githubusercontent.com/34418662/33805851-c09d9a96-ddc7-11e7-8403-4503044b4dbf.png)

Logs:
```
PASTE LOGS HERE2017-12-10 14:29:16 INFO FINDSUBTITLES :: No subtitles to download
2017-12-10 14:29:16 INFO FINDSUBTITLES :: Checking for missed subtitles
2017-12-10 14:29:15 INFO Thread-1116 :: Subtitle search forced
```

**Comment by bobbysteel** [comment]
enable debug logs and then repost w/ that

**Comment by AlexGr3** [comment]
Hmmm where do I do that? I believe I already have but not sure.

**Comment by bobbysteel** [comment]
there's a setting for Enable Debug
https://github.com/SickRage/SickRage/wiki/Settings-explained
if you've already enabled, in the Logs view, change the dropdown from INFO
to DEBUG and it will show the debug logs to see what's really wrong

**Comment by AlexGr3** [comment]
![image](https://user-images.githubusercontent.com/34418662/34445793-d24b990c-ecde-11e7-82ef-2e07727b1ec4.png)
Thats the only thing that showed up when I forced a subtitle search.

**Comment by SeeDborg** [comment]
I have the same problem : no subtitles are downloading since more than a month (on Synology NAS)
