### ISSUE TITLE
NewzNab using Spotweb times out

### ISSUE THREAD

**Issue by wijmaar** [SickChill/SickChill#4189]
Branch/Commit: Master
OS: Synology, Unix (DS214Play)
What you did: I added Spotweb as a NewzNab provider. 
What happened: The API calls to the from SickRage to Spotweb time out if I do a search
What you expected: To successfully receive the NZB from Spotweb, as the episode I am using to test is available in Spotweb. 

Logs:
SEARCHQUEUE-MANUAL-121361 :: [Spotweb] :: Request failed: HTTPConnectionPool(host='localhost', port=80): Read timed out. (read timeout=30)

I have adapted newznab.py to log the search attributes, and recreated the API call that is done by SickRage to Spotweb. Which is something like:

http://localhost/spotweb/api?t=tvsearch&apikey=...&season=6&maxage=3350&cat=5000%2C5030%2C5040%2C5050&q=ShowTitle&limit=100&offset=0&ep=5

If I complete this request manually it takes up to 5 minutes to process. If I remove the season and the ep attribute it completes within seconds. 

As a temporary fix I have commented out the part where the season and ep tag are added in newznab.py, but that doesn't seem like an ideal solution to me.

**Comment by mesa57** [comment]
Spotweb issue resolved in develop branch https://github.com/spotweb/spotweb/issues/346
