### ISSUE TITLE
Scheduler - Cycle time

### ISSUE THREAD

**Issue by emil31** [SickChill/SickChill#4195]
Branch/Commit: master/1d28b358576b35b101bb0f662858ae5296d2ef8b
OS:Xpenology

Hello,

I see that sickrage is taking a lot of memory on my NAS and that it is increasing with time.

I think that the scheduler may cause this issue, indeed, the scheduler for "Search Queue" and "Show Queue" have a cycle time of 5s. I didn't find the parameter to change the time.

Can somebody help me ?

Thanks

**Comment by miigotu** [comment]
that 5s only starts the scheduler for a second to check if there is a search task or show task to be done and then it stops right away. It has nothing to do with your issue
