### ISSUE TITLE
Post Processing: Not deleting content of RAR files

### ISSUE THREAD

**Issue by bolhaskutya** [SickChill/SickChill#4205]
No matter what I try, the option:
"delete content of RAR files, even if Process Method not set to move?"

- Isn't working.
- Doesn't matter if I set unpack dir or not. 
- Doesn't matter if I use manual post processing or auto.
- The unpacked folders containing the unpacked files aren't deleted.

I'm using COPY method.
On latest version.

**Comment by OlympicLarry** [comment]
I have had the same problem since April, 2017.  I decided to debug the code in VS this weekend and I'm seeing that the delete_files call is never being hit.

The following code is copied from line 221 of processTV.py

```python
# auto post-processing deletes rar content by default if method is 'move',
# sickbeard.DELRARCONTENTS allows to override even if method is NOT 'move'
# manual post-processing will only delete when prompted by delete_on
delete_rar_contents = any([sickbeard.DELRARCONTENTS and mode != 'manual',
                           not sickbeard.DELRARCONTENTS and mode == 'auto' and method_fallback == 'move',
                           mode == 'manual' and delete_on])

for directory_from_rar in directories_from_rars:
    process_dir(
        process_path=directory_from_rar,
        release_name=ek(os.path.basename, directory_from_rar),
        process_method=method_fallback,
        force=force,
        is_priority=is_priority,
        delete_on=delete_rar_contents,
        failed=failed,
        mode=mode
    )

    # Delete rar file only if the extracted dir was successfully processed
    if mode == 'auto' and method_fallback == 'move' or mode == 'manual' and delete_on:
        this_rar = [rar_file for rar_file in rar_files if os.path.basename(directory_from_rar) == rar_file.rpartition('.')[0]]
        delete_files(current_directory, this_rar, result) # Deletes only if result.result == True

```
The following are the values of the variables

sickbeard.DELRARCONTENTS = true
mode = 'auto'`
delete_rar_contents = true
method_fallback = 'copy'

Line 241 has the the bad logic. It only lets you delete if mode == 'auto' and method_fallback == 'move' or mode == 'manual' and delete_on

**Shouldn't it just be looking at the value of delete_rar_contents?**

```python
if delete_rar_contents:
    this_rar = [rar_file for rar_file in rar_files if os.path.basename(directory_from_rar) == rar_file.rpartition('.')[0]]
    delete_files(current_directory, this_rar, result) # Deletes only if result.result == True
```

**Comment by bolhaskutya** [comment]
Any chance this will be fixed?

**Comment by OlympicLarry** [comment]
@bolhaskutya I'm not sure how active this project is anymore. But here is what I did to help delete the files.

I changed my settings to use a specific folder to unrar so now all the files that need to be deleted are in 1 folder. This makes it easier to manually delete them.

**Comment by bolhaskutya** [comment]
@OlympicLarry 
I'm still hoping it will be fixed though. The last commit was a month ago...
Meanwhile thanks for the tip, I'll use the unpack dir. Good idea.

**Comment by bolhaskutya** [comment]
Still nothing? Could someone make a pull request?

**Comment by herbi3** [comment]
Same problem here,

switched to the repo at git.sickrage.ca/sickrage (https://github.com/SiCKRAGETV/SiCKRAGE)

the support is far more responsive, and the issues are actually fixed promptly

**Comment by WebSpider** [comment]
I have this issue as well, and i am getting fed up with deleting my processed series by hand :) i will see if i can find some time to PR this.

**Comment by bolhaskutya** [comment]
git.sickrage.ca/sickrage had tons of warnings for me and it was 10 times slower than this repo.

**Comment by heyimawesome** [comment]
From what I've seen, it looks like Sickrage is extracting the RAR to a sub folder within the specified Unpack Directory. It will then process that sub folder only for RAR deletion. I changed a line of code to have it not extract to this sub folder, and it seems to be working now.

**Comment by mystycs** [comment]
Fixed in my latest PR. [https://github.com/SickChill/SickChill/pull/5448](url)

**Comment by mystycs** [comment]
Fixed here: https://github.com/SickChill/SickChill/pull/5449
