### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-DAILY-SEARCH :: [4b69468] qbittorrent: Unable to set priority for Torrent

### ISSUE THREAD

**Issue by Kalagg** [SickChill/SickChill#4230]
### INFO
Python Version: **2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-101-generic-x86_64-with-LinuxMint-18-sarah**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [4b69468] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Kalagg** [comment]
### INFO
Python Version: **2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-101-generic-x86_64-with-LinuxMint-18-sarah**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [4b69468] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Kalagg** [comment]
### INFO
Python Version: **2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-101-generic-x86_64-with-LinuxMint-18-sarah**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [4b69468] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Kalagg** [comment]
### INFO
Python Version: **2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-101-generic-x86_64-with-LinuxMint-18-sarah**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-312141 :: [4b69468] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MotleyC** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [4b69468] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MotleyC** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [4b69468] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MotleyC** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [4b69468] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
One of the solutions mentioned in the duplicates is installing node.js, does that solve the issue for you too?
