### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by baronebirra82** [SickChill/SickChill#4244]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master - 4b69468cc1ea330f598364718068352a54b0eb92
OS: Windows 10
What you did: tried to update
What happened: update failed
What you expected: update succesfull and restart
Logs:
```
PASTE LOGS HERE
No logs created, how do i manually update?

**Comment by WebSpider** [comment]
You can always go to the SickChill directory and on the command line perform a 'net stop SickChill', followed by a 'git pull origin master' and then 'net start SickChill'
