### ISSUE TITLE
set unaired to skipped

### ISSUE THREAD

**Issue by brianjmurrell** [SickChill/SickChill#4249]
Branch: master
Commit: 4b69468cc1ea330f598364718068352a54b0eb92
Version: v2017.12.19-1
Database Version: 44.0

OS: Linux

I have a show that has some past missing episode air dates on thetvdb.com.  I don't really want to download any of those past episodes even if their airdates get added to thetvdb.com at some point.  But _Unaired_ episodes are not selectable so that I can set them to _Skipped_.  I do want to download future episodes though, so setting _Default Episode Status_ to _Skipped_ is not an option.

It really ought to be possible to set the status of _Unaired_ episodes.

**Comment by brianjmurrell** [comment]
There has been no further activity because nobody has even triaged this yet.  Just because it has not been triaged doesn't make it invalid or stale.

**Comment by WebSpider** [comment]
At this point you can only achieve this by editing the database by hand. I will turn this into a feature request.

**Comment by brianjmurrell** [comment]
Cool.  Thanks!

**Comment by brianjmurrell** [comment]
Again, it's NOT stale.  How do we get this stale-bot to stop marking issues as stale just because no work has been done on them yet?

**Comment by brianjmurrell** [comment]
And ONCE AGAIN, it's NOT stale. How do we get this stale-bot to stop marking issues as stale just because no work has been done on them yet?

**Comment by brianjmurrell** [comment]
Why close?  It's still an issue isn't it?
