### ISSUE TITLE
Selecting Backlog Overview: Mako Error

### ISSUE THREAD

**Issue by iculookn** [SickChill/SickChill#4252]
When I select Backlog Overview, I get a Mako Error

```
File /opt/sickrage/sickbeard/sbdatetime.py:239, in sbfdatetime:
strd = dt.strftime(sickbeard.DATE_PRESET)
ValueError: year=218 is before 1900; the datetime strftime() methods require year >= 1900

```
Seems like it doesn't like the date of some file/show? should be 2018, but see's it as 218

I looked through the shows, but could not see any funny dates

Branch/Commit:
Branch: master
Commit: 4b69468cc1ea330f598364718068352a54b0eb92
Version: v2017.12.19-1
Database Version: 44.0

OS: UBUNTU 16.04
What you did: Click on Backlog Overview
What happened: 
A mako error has occured. 

 File /opt/sickrage/sickbeard/sbdatetime.py:239, in sbfdatetime:
strd = dt.strftime(sickbeard.DATE_PRESET)
ValueError: year=218 is before 1900; the datetime strftime() methods require year >= 1900

What you expected:
Logs:
```
Nothing in main log or debug log 
```

**Comment by iculookn** [comment]
Thanks, that helped.

As for logs, I turned on debug, checked the logs, clicked the button, got error, checked logs again and nothing was added to the log file

**Comment by itsme9x** [comment]
I got the same issue today when going to the backlog page:

File /SickRage/sickbeard/sbdatetime.py:239, in sbfdatetime:
strd = dt.strftime(sickbeard.DATE_PRESET)
ValueError: year=208 is before 1900; the datetime strftime() methods require year >= 1900

Version v2018.02.26-2

Noting in logss

**Comment by clawoflight** [comment]
This still occurs with some shows, I presume having invalid year data?
