### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/76666/actors.xml

### ISSUE THREAD

**Issue by jcarlos001** [SickChill/SickChill#4258]
### INFO
Python Version: **2.7.13 (default, Aug 15 2017, 13:52:27) [GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)]**
Operating System: **FreeBSD-11.1-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@4b69468cc1ea330f598364718068352a54b0eb92
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [4b69468] Unable to connect to theTVDB while creating meta files - skipping - error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/76666/actors.xml
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by XxUnkn0wnxX** [comment]
tvdb is getting unstable it constantly very slow or going down, why cant SR adopt https://trakt.tv as an alternative?

**Comment by gurmukhp** [comment]
I can't seem to add any new shows as it always returns 'not found' even common shows like Friends.
