### ISSUE TITLE
Submit Errors Broken

### ISSUE THREAD

**Issue by HPMSGEN8** [SickChill/SickChill#4267]
Branch/Commit:
OS: Branch: master
Commit: 5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
Version: v2018.01.24-1
Database Version: 44.0
What you did: Try to submit and error
What happened: Got an error
What you expected: Submit To GitHub
Logs:
```
2018-01-24 16:21:59 Thread-14 :: [5bc5c3a] Traceback (most recent call last):
File "/volume5/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 332, in submit_errors
if LOGGING_LEVELS[level] == ERROR:
KeyError: u'2018-01-24 16:12:40'

```

**Comment by XxUnkn0wnxX** [comment]
yep broken 4 me 2 

OS: macOS High Sierra 10.13.3
Branch: master
Commit: 5bc5c3a
Version: v2018.01.24-1
What you did: Try to submit and error
What happened: Got an error
What you expected: Submit To GitHub
Logs: https://gist.github.com/XxUnkn0wnxX/e5fa797740a675dab791cb578a733ab9

**Comment by WebSpider** [comment]
Are you still seeing this?
