### ISSUE TITLE
CHECKVERSION :: Unable to contact github, can't check for update: gaierror(-2, 'Name or service not known')

### ISSUE THREAD

**Issue by marcusstock** [SickChill/SickChill#4278]
Branch/Commit: Master 5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
OS:QNAP 
What you did: tried to update from github
What happened: did not update
What you expected: it to updarte

  SickRage Info:
Branch: master
Commit: 5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
Database Version: 44.0
  Python Version: 2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]
  SSL Version: OpenSSL 1.0.2h 3 May 2016
  OS: Linux-4.2.8-x86_64-with-glibc2.2.5
  Locale: en_US.UTF-8

  User: admin
  Program Folder: /share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master
  Config File: /share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/config.ini
  Database File: /share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/sickbeard.db
  Cache Folder: /share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/cache
  Log Folder: /share/CACHEDEV1_DATA/.qpkg/QSickRage/SickRage-master/Logs
  Arguments: ['-p', '29989', '--daemon', '--nolaunch']

  Website: http://sickrage.github.io/
  Wiki: https://github.com/SickRage/SickRage/wiki
  Source: https://github.com/SickRage/SickRage/
  IRC Chat: #sickrage-issues on irc.freenode.net

The main screen shows
Unknown current version number: If you've never used the SickRage upgrade system before then current version is not set. — Update Now
so i try to update and i get 

Update Failed
Update wasn't successful, not restarting. Check your log for more information ( i enabled debug)

Logs:
```
2018-01-29 21:22:16 WARNING Thread-15 :: Unable to contact github, can't check for update: gaierror(-2, 'Name or service not known')
2018-01-29 21:21:48 DEBUG Thread-14 :: cur_commit = 5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37, newest_commit = 5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37, num_commits_behind = 0
2018-01-29 21:21:44 INFO Thread-14 :: Config backup successful, updating...
2018-01-29 21:21:42 INFO Thread-14 :: Config backup in progress...
```

So it appears that the version is uptodate but im getting the error

I am a bit of a novice on command line on the qnap so please bare with me if you need things changed,,

**Comment by marcusstock** [comment]
captured from Advanced settings...
GitHub
Options for github related features.
Branch version master
Authorization Type - Username and password
GitHub username - mxxxxxxxxk
GitHub password - ••••••••
GitHub remote for branch - origin
Git executable path (blank)

**Comment by redvers76** [comment]
Are you on SKY BROADBAND in the UK? I am, and have had a few weeks of not being able to connect to GitHub at all - not just for SickRage but for anything (e.g. HomeBrew also failing)

This seems to have been resolved in the past couple of days...

**Comment by redvers76** [comment]
And now it seems to have broken again!

**Comment by WebSpider** [comment]
Name or service not known usually points to a DNS issue. Please see if you still have this issue when using any of the known public DNS's, such as 8.8.8.8, 1.1.1.1, etc, if so, please open a new issue.
