### ISSUE TITLE
Blank search provider page

### ISSUE THREAD

**Issue by danyboy666** [SickChill/SickChill#4290]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
OS: Linux-4.4.0-109-generic-x86_64-with-Ubuntu-16.04-xenial
What you did: Added some providers
What happened: After I adding some providers and saving to my already populated list the provider page turned blank. Same with the torrent providers page.
What you expected: ...
Logs: na
```
PASTE LOGS HERE
```
![sans titre](https://user-images.githubusercontent.com/8345498/35715896-4f432d24-07a3-11e8-9ce0-856cb0d452e7.jpg)

**Comment by danyboy666** [comment]
I still have this issue.

**Comment by WebSpider** [comment]
- Is there anything in the logs regarding newznab?
- Can you try and disable newznab completely in Search settings, re-enable this and see if it makes any difference?

**Comment by danyboy666** [comment]
You can close this. I completely forgot about this. The problem went away with a fresh install. It was some how related to jackett i think I had two identical labels in the providers page, it caused the page to return empty providers strings even though everything apparently worked fine.
