### ISSUE TITLE
Sickrage broken after update 

### ISSUE THREAD

**Issue by Hansie5381** [SickChill/SickChill#4291]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed) can't enable because sick rage won't run anymore

Branch/Commit: 20171129-4
OS:DSM 6.1.5-15254
What you did: Updated tot latest version 
What happened: Sickrage will not start anymore
What you expected: that it would run
Logs: no logs can't enable debug logging. 
```
PASTE LOGS HERE
```

Since Synology messed up ROOT i can't acces the root folder of my synology this blocks me to backup system files., can you help me, to recover settings, and Database and whatever i need tot re-install sick rage again and restore it to last know working config.

**Comment by WebSpider** [comment]
You need to grab sick*.db and config.ini from your old install and move it over to the new install. Then stop SickChill, put these files in place and restart SickChill
