### ISSUE TITLE
Error when searching spotweb for files with date

### ISSUE THREAD

**Issue by heula** [SickChill/SickChill#4307]
Branch/Commit: Master / 5bc5c3aa7b0007ee3c69e7cacfb975af597f8f37
[sickrage.log](https://github.com/SickRage/SickRage/files/1714183/sickrage.log)

OS: Windows 10
What you did: Sickrage searched for an episode but could not find it
What happened: The episode does exist on Spotweb but is not snatched because of another date format used I think. Dutch format is dd.mm.yy
What you expected:That Sickrage snatched this file or give me the option the set a date format to search for.
Logs:  018-02-10 07:37:33 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Spotweb] :: Unable to find episode with date 2018-09-02 for show Voetbal Inside, skipping
2018-02-10 07:37:33 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Spotweb] :: Parsed Voetbal.Inside.09-02-2018.x264.HQTV.720p into Voetbal Inside - 2018-09-02 [ABD: True] [ANIME: False] [whichReg: [u'scene_date_format']]
2018-02-10 07:37:33 DEBUG

I hope Sickrage can search for files like these two examples.

"Unable to find episode with date 2018-09-02 for show Voetbal Inside, skipping"
Voetbal Inside 09-02-2018 x264 HQTV 720p is on Spotweb

And for files called like this 

"This is Us SE.2 afl.12 Clooney" 
Se. stands for Seizoen (Season) and afl. stands for Aflevering (episode)

Not just like this "This is Us S02E012 or 2x12"

Thanks

**Comment by heula** [comment]
Sickrage keeps given me this search error. Evenwhen the show is already set as archived.

2018-03-12 07:37:40 SEARCHQUEUE-DAILY-SEARCH :: [Spotweb] :: Unable to find episode with date 2018-09-03 for show Voetbal Inside, skipping

[sickrage.log](https://github.com/SickRage/SickRage/files/1801764/sickrage.log)

**Comment by heula** [comment]
2018-03-14 09:16:18 SEARCHQUEUE-DAILY-SEARCH :: [Spotweb] :: Unable to find episode with date 2018-03-13 for show Voetbal Inside, skipping

2018-03-13 is not a date this show is on. The show was on 2018-03-12. Sickrage shows that date in the show list so why searching for a different date? That's why it can't find any.

[https://i.imgur.com/eF1yycu.jpg](url)

[sickrage.log](https://github.com/SickRage/SickRage/files/1810167/sickrage.log)

**Comment by heula** [comment]
This is still an issue for me. So if this can be done or fixed, it would be really helpfull.
Perhaps someone can at least comment to this?

Thanks.

**Comment by WebSpider** [comment]
Looking at your questions:

- SC tries to adhere to the scene naming rules as much as possible, so anyone using non-English abbreviations to indicate episodes (such as afl, abl, seq, etc) will not likely be added by the devs. Feel free to contribute this yourself by sending in a PR.
- Dates being off by one can be either one of two things: Timezone settings are off in either your local install or in the network's timezone definition, or the indexer told SC this episode exists.

Let me check into the pausing. Also, how did you add spotweb into SC?
