### ISSUE TITLE
Suggestion: Add support for alternative TV API's

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SickChill/SickChill#4308]
tvdb, has become somewhat unreliable its constantly down and is struggling to stay up these days, would it kill you guys to Add support for alternative API's rather then sourcing all your information from tvdb?

trakt.tv has a accurate database and the API is built well, and what about tvmaze.com? 

this is starting to become a nuisance from shows not updating properly due to tvdb's downtime of late...

**Comment by OmgImAlexis** [comment]
trakt.tv is tvdb under the hood.

tvmaze and others could be added but we're all busy so maybe open a PR?

**Comment by chrillep** [comment]
maybe merge from https://github.com/pymedusa/Medusa ?
* Supports TVMaze and TMDB indexers

https://github.com/pymedusa/Medusa/tree/master/medusa/indexers

**Comment by dirkr07** [comment]
@miigotu Since the tvdb seems to be lacking updates recently, any chance this can be revisited?

**Comment by dirkr07** [comment]
@miigotu are there any plans to re-visit this?
You reopened this yourself but it has been marked stale again..

Would love to know if this is on the roadmap

**Comment by miigotu** [comment]
It has been on the roadmap for like 4 years ;)

**Comment by stevegilbert23** [comment]
+1 for this.
The thetvdb.com is having issues today:

An unexpected error occurred.
SQLSTATE[08004] [1040] Too many connections

Is there a branch/fork/project where this work has started?
Seems daunting to start from scratch, if any of us out here wanted to contribute.

If thetvdb.com goes away, would sickchill be effectively dead?

**Comment by jaxjexjox** [comment]
Recent issues with TVDB means it might be nice to consider adding another source, if it's not a huge amount of work.

**Comment by Zw3rv3r** [comment]
Perhaps some inspiration can be found on https://github.com/pymedusa/Medusa/tree/master/lib/pytvmaze if both Sickbeard forks aren't too far apart?

**Comment by brianjmurrell** [comment]
I'm starting to find things on my search-engine-of-choice that have only tvmaze indexing and not thetvdb, so I am missing things because of it.

Apparently SickGear and Sonarr support this multiple database searching.  I'd really rather stick with SickChill than have to migrate somewhere else.
