### ISSUE TITLE
[APP SUBMITTED]: u'2018-02-19 07:51:02'

### ISSUE THREAD

**Issue by m184711** [SickChill/SickChill#4319]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5066fab234dc43e24648601b932523d87d9bac6c
No Log available with ERRORS:
### ERROR
```
Thread-16 :: [5066fab] Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 332, in submit_errors
    if LOGGING_LEVELS[level] == ERROR:
KeyError: u'2018-02-19 07:51:02'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
Please provide more debug logging when this is happening
