### ISSUE TITLE
https://iptorrents.eu is no longer active please switch to .com to save me custom config :D

### ISSUE THREAD

**Issue by zarboz** [SickChill/SickChill#4324]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by zarboz** [comment]
diff --git a/sickbeard/providers/iptorrents.py b/sickbeard/providers/iptorrents.py
index 927ecf2c1..19ece3d6c 100644
--- a/sickbeard/providers/iptorrents.py
+++ b/sickbeard/providers/iptorrents.py
@@ -49,9 +49,9 @@ class IPTorrentsProvider(TorrentProvider):  # pylint: disable=too-many-instance-
 
         self.cache = tvcache.TVCache(self, min_time=10)  # Only poll IPTorrents every 10 minutes max
 
-        self.urls = {'base_url': 'https://iptorrents.eu',
-                     'login': 'https://iptorrents.eu/take_login.php',
-                     'search': 'https://iptorrents.eu/t?%s%s&q=%s&qf=#torrents'}
+        self.urls = {'base_url': 'https://iptorrents.com',
+                     'login': 'https://iptorrents.com/take_login.php',
+                     'search': 'https://iptorrents.com/t?%s%s&q=%s&qf=#torrents'}
 
         self.url = self.urls['base_url']

**Comment by miigotu** [comment]
both iptorrents.eu and iptorrents.com work fine, its your network provider blocking it. Try a custom dns
