### ISSUE TITLE
Sickrage can't send torrents to Deluge 

### ISSUE THREAD

**Issue by Danelem** [SickChill/SickChill#4331]
Hey,

When finding a show, Sickrage encounters an error while reading/sending the torrent to Deluge. I tried with multiple trackers.

What is more surprising, is that if I restart Sickrage, it then works (not sure for how long, maybe a day). I tried a few times.

Branch/Commit: master
OS: inux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
What you did: Manual Backlog search
What happened: Error: "not a valid bencoded string" and "Unable to bdecode torrent"
What you expected: The torrent to be sent over to Deluge
Logs:
```
`AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/home/hd1/*******/apps/sickrage/sickbeard/helpers.py", line 1932, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/home/hd1/*******/apps/sickrage/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA result = self._get_torrent_hash(result)
AA File "/home/hd1/*******/apps/sickrage/sickbeard/clients/generic.py", line 259, in sendTORRENT
AA Traceback (most recent call last):
2018-02-25 06:56:55 ERROR SEARCHQUEUE-MANUAL-337514 :: [5066fab] Deluge: Failed Sending Torrent
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/home/hd1/*******/apps/sickrage/sickbeard/helpers.py", line 1932, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/home/hd1/*******/apps/sickrage/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA Traceback (most recent call last):
2018-02-25 06:56:55 ERROR SEARCHQUEUE-MANUAL-337514 :: [5066fab] Unable to bdecode torrent
2018-02-25 06:56:55 INFO SEARCHQUEUE-MANUAL-337514 :: Downloading Wilder.S01E06.FiNAL.FRENCH.720p.HDTV.x264-SH0W from YggTorrent
2018-02-25 06:56:55 INFO SEARCHQUEUE-MANUAL-337514 :: [YggTorrent] :: Quality of Wilder.S01E06.FiNAL.FRENCH.720p.HDTV.x264-SH0W is 720p HDTV
2018-02-25 06:56:55 INFO SEARCHQUEUE-MANUAL-337514 :: [YggTorrent] :: Performing episode search for Wilder
2018-02-25 06:56:54 INFO SEARCHQUEUE-MANUAL-337514 :: Beginning manual search for: [Wilder - S01E06 - L'abîme]`
```

**Comment by oasisck** [comment]
I have exactly same issue but different downloader : transmission
Sickrage in jail (official plugin from FreeNAS)
Anyone ?

**Comment by Danelem** [comment]
Right, the problem is that Sickrage is fetching something that doesn't look like a torrent file.

**Comment by Danelem** [comment]
@oasisck does it work for you after restarting? And for how long?

**Comment by oasisck** [comment]
Actually it works without restarting, SR send torrents to transmission but with errors

**Comment by antipiot** [comment]
i have the same error since may; have to reboot for sickrage to download torrent from yggtorrent but it does not work at all with Yggtorrent.
Do you guys have solved this?

**Comment by neo62248** [comment]
Hello, 

same issue, not with Deluge client but with Download Station. Yggtorrent / Torrent9 tested and always the same problem... any ideas?

**Comment by Anatharias** [comment]
Actually, Medusa doesn't help with YGGtorrent.is
it has the same bdecode issue.
Been using Medusa for a while now, but I think that this error has to do with the way the .torrent is downloaded from ygg.

**Comment by neo62248** [comment]
The url change does not change anything about this problem. Problem seems to be relative to the torrents files downloading from YggTorrent. Maybe the stream received is not "understood" by Sickrage system.

I need a dev to seeing what can cause this problem in code.
