### ISSUE TITLE
Usenet-Crawler URL/API is not editable and does not currently work

### ISSUE THREAD

**Issue by jeronymite** [SickChill/SickChill#4334]
SickRage Info:
Branch: master
Commit: 5066fab
Version: v2018.02.17-1
Database Version: 44.0
Python Version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version: OpenSSL 1.0.2j 26 Sep 2016
OS: Windows-10-10.0.16299
Locale: en_AU.cp1252

What you did:
I discovered that Usenet-Crawler has changed its method of  connecting to its API: _"26 January 2018
I have separated the api and website. This should lower the amount of open connections a lot, hopefully making the site more snappy. New url https://api.usenet-crawler.com "_.

I attempted to update this information in SickRage Search Providers. I tried both Configure Custom Newznab Providers and Provider Options.

What happened:
Neither allowed me to edit the site URL or anything that is part of the URL except the actual API Key.

What you expected:
I expected to be able to edit this information and also be able to provide a full URL as recommended by the Provider, including options other than just the API Key. For example: https://www.usenet-crawler.com/rss lists a variety of options that can/should be included in the URL.

Logs:
```
2018-02-26 11:57:37 WARNING SEARCHQUEUE-MANUAL-76119 :: [Usenet-Crawler] :: Error getting caps xml for [Usenet-Crawler]
2018-02-26 11:57:37 INFO SEARCHQUEUE-MANUAL-76119 :: [Usenet-Crawler] :: Request failed: 403 Client Error: Forbidden for url: https://www.usenet-crawler.com/api?apikey=**********&t=caps
```

Thanks for your investigation and advice/rectification.

**Comment by EqUaTe** [comment]
@jeronymite FYI, RSS and API are not the same, so the options here really aren't relevant. You'd use the RSS if you put it directly into nzbget/sabnzbd/usenet client of choice. My PR above should fix this issue for you

**Comment by jeronymite** [comment]
Many thanks for your advice and the fix. Much appreciated.

**Comment by itsme9x** [comment]
Double with https://github.com/SickRage/SickRage/issues/4293
