### ISSUE TITLE
Newest release forgets Sort Order on Shows screen

### ISSUE THREAD

**Issue by kailia** [SickChill/SickChill#4340]
Branch: master
Commit: 6e3a1dccd94857fc381c9a246b903904eca424e1
Version: v2018.02.26-2
Database Version: 44.0

Python Version:
2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]

SSL Version:
OpenSSL 1.0.2d 9 Jul 2015
OS:
Windows-10-10.0.17074

Hi Devs,

using the latest update, SickRage always returns to the default sorting order (Sort by Show) in the main Shows screen, e.g. after clicking the SickRage logo on the top left.
Previously, it would always remember the last sort order set by the user.
E.g. I always have this sorted by Downloads, so I can see which shows have missing or recently Snatched episodes.

**Comment by OblivionSA** [comment]
Branch: master
Commit:  6e3a1dccd94857fc381c9a246b903904eca424e1
Version: v2018.02.26-2
Database Version: 44.0
Python Version: 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] 
SSL Version: OpenSSL 1.0.2d 9 Jul 2015
OS: Windows-7-6.1.7601-SP1

Same here, the Show List returns to being sorted first by 'Active' and then by 'Name'.
Experiencing the same issue on the Schedule page, where it used to remain sorted how it was last left, but now always returns to being sorted by show 'Name'.
Clearing Filter(s) and Restarting hasn't resolved.

**Comment by rutskiuk** [comment]
I noticed in the changelog there was something about the sort order that was changed. 

"Remove saveSort, it's irritating"

Ever since the update I get the sort by show name rather than my chosen field (downloads). Personally, I find it far more irritating having to manually re-sort the page each time I load it.

**Comment by JeeWee** [comment]
SickRage Info:
Branch: master
Commit: 6e3a1dccd94857fc381c9a246b903904eca424e1
Version: v2018.02.26-2
Database Version: 44.0
Python Version: 2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]
SSL Version: OpenSSL 1.0.1t 3 May 2016
OS: Linux-4.9.26v7-aufs-armv7l-with-debian-8.0 (raspbian jessy)

Have exactly the same problem on all browsers.

**Comment by briped** [comment]
Adding my voice to bring back saving the sorting preference.

SickRage Info:
Branch: master
Commit: 6e3a1dccd94857fc381c9a246b903904eca424e1
Version: v2018.02.26-2
Database Version: 44.0
  Python Version: 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
  SSL Version: OpenSSL 1.0.2g 1 Mar 2016
  OS: Linux-4.13.0-32-generic-x86_64-with-Ubuntu-17.10-artful
  Locale: en_US.UTF-8

**Comment by Sithlord82** [comment]
Add my voice to this as well. Very irritating having it forget the sort order each time :(
