### ISSUE TITLE
Request: Add Notify when postprocessing is done

### ISSUE THREAD

**Issue by CoRpO** [SickChill/SickChill#4348]
Simple feature request

Add the ability to notify when post processing is done (actually you can choose between download started or download finished only)

Thank you, keep up the good work

(I have a rather slow post processing, I'm recoding the files when needed)

**Comment by CoRpO** [comment]
Nobody needs this ??

**Comment by CoRpO** [comment]
I've made a patch to implement this

**Comment by WebSpider** [comment]
Please make a PR for the patch, thanks!
