### ISSUE TITLE
Ignore releases with no .par and no archive types

### ISSUE THREAD

**Issue by clinton-hall** [SickChill/SickChill#4379]
Branch: master
Commit: 7a26059801aed3e1aa4994663b0c68ee13fb3d56
Version: v2018.03.11-1
Database Version: 44.0
OS: Linux (Asustor)

What you did: 
Downloading releases for recent shows. SickRage is snatching releases from USENET that don't have any archive (rar) for par files. i.e. these are just .mkv files.

If any articles are missing these result in a file that is playable, but has skips/pauses.
Status in NZBGet is failed (but nzbToMedia scans file with ffprobe and finds a playable video so therefore processes anyway.

Just curious to know if it is possible to filter and ignore these releases so as not to snatch first time? 

e.g. https://dognzb.cr/details/bcc0e81189ceecc251f818de41d562a1

**Comment by WebSpider** [comment]
Possible .. yes. Easy, no. 

SickRage currently does not take the extension of the file downloaded into consideration when determining the validity/quality of a file.

**Comment by clinton-hall** [comment]
fair call... have asked at NZBget, should be possible with a queue script to identify no-par, no archive downloads.

In sickrage I have added some "group" names to ignore words in search settings. This helps somewhat. `xpost` seemed to be a common one for me.
