### ISSUE TITLE
qbittorrent: Unable to send Torrent

### ISSUE THREAD

**Issue by KenjiAU** [SickChill/SickChill#4385]
Branch/Commit: Master
OS: Windows 10
What you did: Manual Search for show
What happened: Error message, show still wanted. Torrent appears but no category, and paused
What you expected: Torrent to be added to QBitorrent with a category and started
Logs:
```
2018-03-13 13:58:10 WARNING SEARCHQUEUE-MANUAL-75692 :: qbittorrent: Unable to send Torrent
2018-03-13 13:57:49 INFO SEARCHQUEUE-MANUAL-75692 :: Downloading Law.and.Order.SVU.S19E14.720p.HDTV.x264-AVS[ettv] from ThePirateBay
2018-03-13 13:57:49 INFO SEARCHQUEUE-MANUAL-75692 :: [ThePirateBay] :: Quality of Law.and.Order.SVU.S19E14.720p.HDTV.x264-AVS[N1C] is 720p HDTV
2018-03-13 13:57:49 INFO SEARCHQUEUE-MANUAL-75692 :: [ThePirateBay] :: Quality of Law.and.Order.SVU.S19E14.720p.HDTV.x264-AVS[ettv] is 720p HDTV
2018-03-13 13:57:45 INFO SEARCHQUEUE-MANUAL-75692 :: [ThePirateBay] :: Performing episode search for Law & Order: Special Victims Unit
2018-03-13 13:57:45 INFO SEARCHQUEUE-MANUAL-75692 :: Beginning manual search for: [Law & Order Special Victims Unit - S19E14 - Chasing Demons]
```
I updated qBittorrent and Sickrage and now I can't get shows to downloaded as they come now. I checked the webui settings and it works on Radarr fine.

Torrent still goes into qBittorrent, but still wanted on Sickrage. So it keeps adding the same torrent.  

Also saw this in logs, not sure if it is relevant.
AA ValueError: No JSON object could be decoded
AA File "d:\SickRage\lib\simplejson\decoder.py", line 353, in raw_decode
AA File "d:\SickRage\lib\simplejson\decoder.py", line 335, in decode
AA File "d:\SickRage\lib\simplejson\__init__.py", line 307, in loads
AA return complexjson.loads(self.text, **kwargs)
AA File "D:\SickRage\lib\requests\models.py", line 894, in json
AA if self.response.json()['piece_size'] != -1:
AA File "D:\SickRage\sickbeard\clients\qbittorrent_client.py", line 138, in _verify_added
AA return self._verify_added(result.hash)
AA File "D:\SickRage\sickbeard\clients\qbittorrent_client.py", line 87, in _add_torrent_uri
AA r_code = self._add_torrent_uri(result)
AA File "D:\SickRage\sickbeard\clients\generic.py", line 262, in sendTORRENT
AA Traceback (most recent call last):

**Comment by ukharley** [comment]
For me was failing with magnet links. Qbittorrent can take a while to give the response SickRage wants. I changed the following in qbittorent_clint.py
From:
    def _verify_added(self, torrent_hash, attempts=5):
        self.url = urljoin(self.host, 'query/propertiesGeneral/{}'.format(torrent_hash.lower()))
        for i in range(attempts):
            if self._request(method='get', cookies=self.session.cookies):
                if self.response.json()['piece_size'] != -1:
                    return True
            sleep(2)
        return False

To:
    def _verify_added(self, torrent_hash, attempts=20):
        self.url = urljoin(self.host, 'query/propertiesGeneral/{}'.format(torrent_hash.lower()))
        for i in range(attempts):
            if self._request(method='get', cookies=self.session.cookies):
                if self.response.json()['piece_size'] != -1:
                    return True
            sleep(1)
        return False

On average it takes about 10 to 15 seconds to reply with piece_size != -1

**Comment by KenjiAU** [comment]
My code matches yours now. Still doesn't work. Log below


AA Release Group: CROOKS
AA Size: 652161843
AA Name: Last.Week.Tonight.With.John.Oliver.S05E03.720p.HDTV.x264-CROOKS
AA Quality: 720p HDTV
AA status: 5
AA hastbn: False
AA hasnfo: False
AA airdate: 736757 (datetime.date(2018, 3, 4))
AA subtitles_lastsearch: '0001-01-01 00:00:00'
AA subtitles_searchcount: 0
AA subtitles: u''
AA description: u"This week John Oliver takes a look at NRA TV and it's various show's message and sometimes bizarre content."
AA location: u''
AA u'Last Week Tonight with John Oliver' - S5E3 - u'Episode 122'
AA Episodes:
AA Extra Info:
AA ValueError: No JSON object could be decoded
AA File "d:\SickRage\lib\simplejson\decoder.py", line 353, in raw_decode
AA File "d:\SickRage\lib\simplejson\decoder.py", line 335, in decode
AA File "d:\SickRage\lib\simplejson\__init__.py", line 307, in loads
AA return complexjson.loads(self.text, **kwargs)
AA File "D:\SickRage\lib\requests\models.py", line 892, in json
AA if self.response.json()['piece_size'] != -1:
AA File "D:\SickRage\sickbeard\clients\qbittorrent_client.py", line 138, in _verify_added
AA return self._verify_added(result.hash)
AA File "D:\SickRage\sickbeard\clients\qbittorrent_client.py", line 87, in _add_torrent_uri
AA r_code = self._add_torrent_uri(result)
AA File "D:\SickRage\sickbeard\clients\generic.py", line 262, in sendTORRENT
AA Traceback (most recent call last):
2018-03-23 20:54:55 ERROR SEARCHQUEUE-MANUAL-278518 :: [5af6c53] qbittorrent: Failed Sending Torrent
2018-03-23 20:54:20 INFO SEARCHQUEUE-MANUAL-278518 :: Downloading Last.Week.Tonight.With.John.Oliver.S05E03.720p.HDTV.x264-CROOKS from ThePirateBay

**Comment by KenjiAU** [comment]
My code now matches yours, and it still doesn't work for me. Log below

AA . Error No JSON object could be decoded
AA Release Group: CROOKS
AA Size: 652161843
AA Name: Last.Week.Tonight.With.John.Oliver.S05E03.720p.HDTV.x264-CROOKS
AA Quality: 720p HDTV
AA status: 5
AA hastbn: False
AA hasnfo: False
AA airdate: 736757 (datetime.date(2018, 3, 4))
AA subtitles_lastsearch: '0001-01-01 00:00:00'
AA subtitles_searchcount: 0
AA subtitles: u''
AA description: u"This week John Oliver takes a look at NRA TV and it's various show's message and sometimes bizarre content."
AA location: u''
AA u'Last Week Tonight with John Oliver' - S5E3 - u'Episode 122'
AA Episodes:
AA Extra Info:
AA ValueError: No JSON object could be decoded
AA File "d:\SickRage\lib\simplejson\decoder.py", line 353, in raw_decode
AA File "d:\SickRage\lib\simplejson\decoder.py", line 335, in decode
AA File "d:\SickRage\lib\simplejson\__init__.py", line 307, in loads
AA return complexjson.loads(self.text, **kwargs)
AA File "D:\SickRage\lib\requests\models.py", line 892, in json
AA if self.response.json()['piece_size'] != -1:
AA File "D:\SickRage\sickbeard\clients\qbittorrent_client.py", line 138, in _verify_added
AA return self._verify_added(result.hash)
AA File "D:\SickRage\sickbeard\clients\qbittorrent_client.py", line 87, in _add_torrent_uri
AA r_code = self._add_torrent_uri(result)
AA File "D:\SickRage\sickbeard\clients\generic.py", line 262, in sendTORRENT
AA Traceback (most recent call last):
2018-03-23 20:54:55 ERROR SEARCHQUEUE-MANUAL-278518 :: [5af6c53] qbittorrent: Failed Sending Torrent
2018-03-23 20:54:20 INFO SEARCHQUEUE-MANUAL-278518 :: Downloading Last.Week.Tonight.With.John.Oliver.S05E03.720p.HDTV.x264-CROOKS from ThePirateBay
