### ISSUE TITLE
Wrong search pattern

### ISSUE THREAD

**Issue by robot110011** [SickChill/SickChill#4396]
Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Linux Ubuntu
What you did: Basic config
What happened: Sickrage is search torrent with the wrong pattern (eg Unable to find a download for: [GameOfThrones - S03E029 - Chapter Tweny-Nine]
What you expected: I'd expect Sickrage search using: [title S00E00]
Logs:
2018-03-17 00:14:08 INFO SEARCHQUEUE-MANUAL-281621 :: Unable to find a download for: [GameOfThrones - S03E029 - Chapter Tweny-Nine]

**Comment by miigotu** [comment]
I'd expect you to not have Game of Thrones set as an anime also.

**Comment by robotlovefarm** [comment]
@miigotu ?

**Comment by miigotu** [comment]
You have it set as an anime I think. Regardless that log string is now how it searches the providers, the episode name is never passed to the provider. Check the debug log
