### ISSUE TITLE
Re Design!

### ISSUE THREAD

**Issue by Kwintspiracy** [SickChill/SickChill#4411]
To all developers around:
Who would be up to the task of giving this project an overall redesign lift ?

I'd be happy to work on something, as a designer.

**Comment by WebSpider** [comment]
Are you talking about the UI?

**Comment by Kwintspiracy** [comment]
Yeah

**Comment by WebSpider** [comment]
@omgimalexis is this you these days?

**Comment by OmgImAlexis** [comment]
@WebSpider nope, working on Medusa mainly.
