### ISSUE TITLE
Error while trying to update: CRC check failed 0xc6640640L != 0x8f0e252L

### ISSUE THREAD

**Issue by itsme9x** [SickChill/SickChill#4415]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
- Branch: master
- Commit: 53e6cc50c086757c31fc518b550d7681c61649e6
- Database Version: 44.0
OS: Debian
What you did: trying to update
What happened: trying to update
What you expected: successfull update
Logs:
```
2018-03-19 22:05:37 Thread-14 :: [53e6cc5] Error while trying to update: CRC check failed 0xc6640640L != 0x8f0e252L
```

**Comment by WebSpider** [comment]
Please provide some more debug logging so we can see when this is occurring
