### ISSUE TITLE
Feature Request - Truncate long episode Names

### ISSUE THREAD

**Issue by crowaust** [SickChill/SickChill#4545]
### INFO
Python Version: **2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2008ServerR2-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5066fab234dc43e24648601b932523d87d9bac6c
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [5066fab] Unable to move file U:\DCC\TV\Ben-To\[MK] Ben-To - 10 [BD 720p][Hi10][Dual][440D3854].mkv to W:\Anime\Ben-To\Season 01\Ben-To - S01E10 ( 010 ) - It was a Warm Gentle Flavor that Reminded Me of my Grandmother. A Japanese Dish that was Kind to Both Body and Soul. Plum and Dried Baby Sardines over Rice with Plenty of Seasonal Vegetables Stewed Bento 480kcal - 720p BluRay - MK.mkv: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by crowaust** [comment]
After checking on this, it appears to be hitting the maximum Character Count, is there a way to limit the character count on the Episode Name?
I currently have a Custom naming on all shows Standard and Anime of:

> Season %0S/%SN - S%0SE%0E ( %AB ) - %EN - %QN - %RG

Most of the other items are Fixed or at least fairly regular in length, the only Field that Radically changes in length is Episode Name. Maybe we can give people a way to select which field to Truncate by adding a T to the code? like %ENT ?

**Comment by crowaust** [comment]
I still think that a truncate option for the episode name would be a good idea.

**Comment by WebSpider** [comment]
Unstale
