### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/320724/actors.xml

### ISSUE THREAD

**Issue by statik1983** [SickChill/SickChill#4561]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1d34bcb48c1e03d568a8fdc08f60df8fa7f2d5d4
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [1d34bcb] Unable to connect to theTVDB while creating meta files - skipping - error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/320724/actors.xml
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
This happens when thetvdb has intermittent failures.
