### ISSUE TITLE
[APP SUBMITTED]: near "s": syntax error

### ISSUE THREAD

**Issue by AubreyKloppers** [SickChill/SickChill#4594]
### INFO
Python Version: **2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.11**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [a760263] DB error: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.14 (default, Mar 14 2018, 20:37:29) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: None
Branch: **develop**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
Link to Log: https://gist.github.com/ddca3d2155eb131eb62a9492d566d70c
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [a760263] DB error: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
Link to Log: https://gist.github.com/f2efe4543b6d074b1aa64b8ec6a31b5c
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [a760263] DB error: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by AurimasNav** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
Link to Log: https://gist.github.com/a848b4d48d77111adfe25e81405cee65
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [a760263] DB error: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by rishitank** [comment]
### INFO
Python Version: **2.7.10 (default, Oct 26 2015, 22:15:29) [GCC 4.2.3]**
Operating System: **Linux-3.4.6-armv5tel-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
Link to Log: https://gist.github.com/da7fea2e897a10297d94a5a9d3b7d154
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [5a9a634] Fatal error executing query with db.action in database /share/MD0_DATA/.qpkg/SickBeard-TVRage/config/sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Darnel-K** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.1-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
Link to Log: https://gist.github.com/6d017718c663ab6174a67bdde1e712e9
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [5a9a634] Fatal error executing query with db.action in database /var/db/sickrage/sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fopaldir** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.8.0-51-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
Link to Log: https://gist.github.com/01d90195d1d726c0a243f3350c468f53
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [5a9a634] Fatal error executing query with db.action in database /opt/sickrage/sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by statik1983** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/881bf498a282658ae35a456528dba243
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [807c5ae] Fatal error executing query with db.action in database /var/db/sickrage/sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by jeronymite** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/348fb02adf6708e4e99eb78cdc678706
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [807c5ae] Fatal error executing query with db.action in database C:\SickRage\Data\sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by statik1983** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/5d0042ad9979350859f9dd03d358ddfc
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [807c5ae] Fatal error executing query with db.action in database /var/db/sickrage/sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fopaldir** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.8.0-51-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/7237a85de9e0b6704ae965b27f4f4c94
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [807c5ae] Fatal error executing query with db.action in database /opt/sickrage/sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by grandboricua** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/61e2b7dd1ea4aee9fbb037c1ec12ac2d
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [0e72764] Fatal error executing query with db.action in database C:\SickRage\Data\sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Jelmerb** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 15:25:50) [GCC 4.8.3 20140106 (prerelease)]**
Operating System: **Linux-3.10.105-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/946a12ddea81b5bb1a13cfec492bdf2e
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [0e72764] Fatal error executing query with db.action in database /volume1/@appstore/sickbeard-custom/var/sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fopaldir** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.8.0-51-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/3439bc9a5bfea604050bea37ac0ef93d
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [0e72764] Fatal error executing query with db.action in database /opt/sickrage/sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by TiagoDM** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/e8e34623269b3a1707024094e10a49b9
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [0e72764] Fatal error executing query with db.action in database C:\SickRage\Data\sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17751**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/c4f6014f2adf192d26675ebe4bd867ba
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [0e72764] Fatal error executing query with db.action in database C:\SickRage\sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by dirkr07** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 15:26:34) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [51328d1] Fatal error executing query with db.action in database /volume1/@appstore/sickbeard-custom/var/sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by edwinroos** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
Link to Log: https://gist.github.com/1d4bb8f63f2c5632603e87b79e8d583f
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [51328d1] Fatal fout opgetreden bij query met db.action in database C:\SickRage\SickRage\sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by RustyHoff** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
Link to Log: https://gist.github.com/69324ad0535bf5879b31deb3a8d04a1c
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [51328d1] Fatal error executing query with db.action in database C:\SickRage\Data\sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SimonHova** [comment]
### INFO
Python Version: **2.7.15 (default, Sep  1 2018, 13:12:31) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.9.0-7-amd64-x86_64-with-debian-9.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@2a781a0356e952c3e25890286aade058083bd0c1
Link to Log: https://gist.github.com/d4d604c69e64d217a594818aae23cc6c
### ERROR
```
SHOWQUEUE-REMOVE-SHOW :: [2a781a0] Fatal error executing query with db.action in database /opt/SickRage/sickbeard.db: near "s": syntax error
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by OneCDOnly** [comment]
same config as @SimonHova, and I agree with his assessment:
```
2018-10-24 07:41:26 INFO     SHOWQUEUE-REMOVE-SHOW :: Removing Marvel's Luke Cage
2018-10-24 07:41:27 INFO     SHOWQUEUE-REMOVE-SHOW :: Attempt to delete cache file /home/me/.sickchill/cache/images/304219.banner.jpg
2018-10-24 07:41:27 INFO     SHOWQUEUE-REMOVE-SHOW :: Attempt to delete cache file /home/me/.sickchill/cache/images/304219.poster.jpg
2018-10-24 07:41:27 INFO     SHOWQUEUE-REMOVE-SHOW :: Attempt to delete cache file /home/me/.sickchill/cache/images/304219.fanart.jpg
2018-10-24 07:41:27 INFO     SHOWQUEUE-REMOVE-SHOW :: Attempt to delete show folder /share/tv/action/Marvel's Luke Cage
2018-10-24 07:41:27 ERROR    SHOWQUEUE-REMOVE-SHOW :: [2a781a0] Fatal error executing query with db.action in database /home/me/.sickchill/sickbeard.db: near "s": syntax error
Traceback (most recent call last):
  File "/opt/SickChill/sickbeard/db.py", line 283, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/SickChill/sickbeard/db.py", line 141, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: near "s": syntax error
2018-10-24 07:41:27 INFO     SHOWQUEUE-REMOVE-SHOW :: If this happened in cache.db, you can safely stop SickChill, and delete the cache.db file without losing any data
2018-10-24 07:41:27 INFO     SHOWQUEUE-REMOVE-SHOW :: Here is the arguments that were passed to this function (This is what the developers need to know): {'fetchall': True, 'attempt': 0, 'severity': 40, 'self': <sickbeard.db.DBConnection object at 0x7f2099152050>, 'args': [304219], 'sql_results': [], 'query': u"SELECT location from tv_shows WHERE location LIKE '/share/tv/action/Marvel's Luke Cage%' AND indexer_id != ?", 'e': OperationalError('near "s": syntax error',), 'fetchone': False}
```
