### ISSUE TITLE
Qualities - create custom quality by size

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#4595]
Would it be possible to create an option to limit snatched episodes by size and not quality - or maybe both? Also, it would be great if it was possible to somehow rank allowed qualities?

**Comment by lejudoka13** [comment]
That's a good idea +1

**Comment by nekkidtruth** [comment]
It was requested something like 2 years ago. It was hinted that it was "coming soon". It's really obnoxious to be forced to manually select files by size when I have a perfectly good automated ecosystem going on. Not sure why the dragging of feet for this feature.

https://feathub.com/SickRage/SickRage/+77

**Comment by Tiwas** [comment]
If nothing else, this could be done in increments.

1. Make it so that you can tell it in which order you prefer qualities, not assuming higher qualities are more interesting for the user.
2. Make it so that you can make a check for "stop processing" if you have one of the qualities in the allowed list. It bugs me when I have a perfectly fine SD that SR will proceed to download a worse quality 720p just because it's in the allowed list.
3. Open up for custom qualities.

I believe 1 and 2 would be pretty easy to implement, and they would solve 90% of my issue :)

**Comment by nekkidtruth** [comment]
For anyone wanting to follow along: https://github.com/SickRage/SickRage/pull/3655

The feature has been worked on, it just isn't done and hasn't been merged yet. I'm a little disappointed to see it fall to the side as I think it's an extremely important addition.

**Comment by Nosirus** [comment]
no news ?

**Comment by miigotu** [comment]
It's already being worked on

**Comment by mystery76** [comment]
That's great news - any idea of timelines?

**Comment by pjrettin** [comment]
It seems this feature is wanted very badly, and I concurr.  This is probably the #1 update to SickChill that I would find MOST useful... it's funny how it's never been implemented.

**Comment by optio50** [comment]
1.5 Gig episodes are bumming me out.
I would be grateful for some kind of a selection for x265 720p and max file size

**Comment by tchirou** [comment]
Hi 
Is it still possible to consider this ?
Thanks

**Comment by Tiwas** [comment]
@optio50 That would be awesome - I, too, would like to limit downloads to x265 files. As a matter of fact I'm now mainly using SC to tell me when episodes are airing som I can manually find the x265 downloads.

**Comment by tchirou** [comment]
As a matter of fact, there already is the setting to download x265 files.
Check in config/search settings. If you want only x265, also put x265 in
the required words in each show setting.

Personally, I only want 1080p x264 files over 2GB and there is not solution
to do that currently

Le 23 déc. 2019 à 12:59, Tiwas <notifications@github.com> a écrit :

﻿

@optio50 <https://github.com/optio50> That would be awesome - I, too, would
like to limit downloads to x265 files. As a matter of fact I'm now mainly
using SC to tell me when episodes are airing som I can manually find the
x265 downloads.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/SickChill/SickChill/issues/4595?email_source=notifications&email_token=ABTPZ3AMZRI6ITKZ5HSMF6TQ2CR3TA5CNFSM4E2B7NTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHQ7HJQ#issuecomment-568456102>,
or unsubscribe

**Comment by tchirou** [comment]
Actually, you can set x265 in the global required word settings in config/search

**Comment by optio50** [comment]
I have it downloading x265 but I want to limit the file size.

I get bummed when I see that the download was 1.5 Gig for  1/2 hour TV show.

The ones as of lately are fine for me at 250 MB 720p

 
 

Sent: Monday, December 23, 2019 at 3:18 AM

**Comment by miigotu** [comment]
It's on the list. I literally just got internet in my new house again just recently. I'm doing TVDB2/2 first and that job is huge. If I get irritated with it, maybe I'll throw this together in the middle.

**Comment by tchirou** [comment]
👍🏻🎉

**Comment by JDubbedN** [comment]
@miigotu Thanks man for your hard efforts. I just started using SickChill andI know you're busy with python3 but I wanted to see if you could chime in for this feature and see if by you getting python3 setup for SickChill that this feature would gain more headway. Thanks.

**Comment by miigotu** [comment]
I have this one on my mind, don't worry. This has been requested for almost 10 years.

**Comment by DravenSA** [comment]
I too have been looking for this feature for a long time. I have noticed that there are more 300mb files that say HD because of the x265, but because i have set my shows to SD, my nzb's never catch them and i have to go do it manually or risk a torrent days later.
So file size max would be great because i could then set it to HD and not worry about a 3GB file downloading. 
Life happens and we appreciate all the work you are doing, but it is scary when you say its been a request for 10 years, please dont be saying 20 years in 10 years time PLEASE!

**Comment by JDubbedN** [comment]
@DravenSA I completely agree with this. SickChill is invaluable and I can tell there is years of sweat and blood in it. I just started using it a week ago and am finally getting it setup to my specific needs thanks to @miigotu help. The only caveat is that I've noticed for example 1080p downloads selected by SickChill range from a small 1gb file to upwards of 5gb file. That is some serious hog on storage. I am trying my best to put into place specific words to be filtered to help SickChill filter out large files but in the end it won't work unless SickChill checks the actual file size before download and allow us to set a file size range for each quality. I just tested a new TV series for the first season that had 12 episodes and I set it to 1080p quality allowed only with x265 allowed, which for some reason it didn't take advantage of even though it was available. It snatched all 12 episodes but they varied in size greatly. A 12 episode season turned into a 50GB memory hog. When I compared it to 1080p files I would have downloaded manually, I would have been able to download each file for about 1-1.5gb each resulting in about a 15GB season. That's about a 35GB storage savings.

I will be very excited when @miigotu adds this feature. As soon as it is added I plan to redo all TV shows. It'll save me so much storage.

**Comment by miigotu** [comment]
The internal debate I'm having right now is whether it's just setting boundaries for each individual quality, or setting a default and per show size range regardless of quality.

**Comment by nekkidtruth** [comment]
Personally, I'd prefer default size range regardless of quality.

**Comment by JDubbedN** [comment]
Yes a default size range for each quality. But add the ability for user customization either per global settings or per each tv series. Or both. Making per tv series settings priority over global.

For example. 1080p default 1gb - 2.5gb. And make both 1gb and 2.5gb input fields so user can change them as desired. Or make a slide bar if you want to go fancy. So I could change 1gb to 500mb and 2.5gb to 2gb. Making it 1080p 500mb - 2gb. And maybe add the option to enforce HVEC x265 for those who have power servers or want to save as much disk drive space as possible.

**Comment by miigotu** [comment]
I'm working on something much bigger than this also, so I'm not sure which will come first. But the other one will decimate all ("possibly even overnight parts from Japan")

**Comment by neo-neo1** [comment]
Any updates? Been a few months, this is the only feature that Sonarr has over SickChill and I've love for that to change. Thanks for your work

**Comment by miigotu** [comment]
Bud, we have been inundated with issues since the switch to python3, mostly issues which were not related to the python3 switch. Be patient.

**Comment by ghenry22** [comment]
Just moved over to sickchill from an old sickbeard install, really liking it and wanted to add my request for this feature.  The same as we have allowed and preferred quality for a series could we have an allowed and preferred size for each quality?

This keeps it fairly consistent in the way it's implemented, would be super useful as I have been getting some ridiculously sized episodes.

**Comment by ghenry22** [comment]
@miigotu could this issue be set back to open state as it seems to still be in progress, also any update would be brilliant, thanks
