### ISSUE TITLE
Replaces "'" to "&#39;" in file path

### ISSUE THREAD

**Issue by pax0707** [SickChill/SickChill#4601]
Branch: master
Commit: a7602639bd525f27475f1eeb2fc504111a14b51c
Version: v2018.04.08-1
Database Version: 44.0
  Python Version: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
  SSL Version: OpenSSL 1.0.2k 26 Jan 2017
  OS: Windows-10-10.0.16299
  Locale: hr_HR.cp1250

When adding series it changes ' to &#39;.

```
DC's Legends of Tomorrow - DC&#39;s Legends of Tomorrow
Marvel's Agents of S.H.I.E.L.D - Marvel&#39;s Agents of S.H.I.E.L.D
Bob's Burgers - Bob&#39;s Burgers
```

**Comment by zarboz** [comment]
#4588

**Comment by nFec** [comment]
#4445
