### ISSUE TITLE
RARBG: Request failed: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by kailia** [SickChill/SickChill#4604]
Hi,

it's been impossible to snatch anything through RARBG for a few days.

SickRage Info:
Branch: master
Commit: a7602639bd525f27475f1eeb2fc504111a14b51c
Version: v2018.04.08-1
Database Version: 44.0

  Python Version:
2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]

  SSL Version:
OpenSSL 1.0.2d 9 Jul 2015

  OS:
Windows-10-10.0.17133

```

11:29:27 INFO::SEARCHQUEUE-BACKLOG-77398 :: [Rarbg] :: **Request failed: 403 Client Error: Forbidden for url:** http://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=sickrage2&format=json
11:29:27 WARNING::SEARCHQUEUE-BACKLOG-77398 :: [Rarbg] :: Unable to connect to provider

**Comment by Jamyz** [comment]
Same problem....... Cloudflare maybe change
