### ISSUE TITLE
sickbeard.py opens up winrar everytime it runs

### ISSUE THREAD

**Issue by dozza07** [SickChill/SickChill#4614]
Hi there,

I have created an auto start of sickrage whenever windows boots. its been working fine now when it runs sickbeard.py it opens winrar to extract to c:\\sickrage. i click on cancel and then it loads up sickrage how do i get to stop doing this?

website where it helped me create the vbs sometime back,
https://www.htpcguides.com/install-sickrage-windows-usenet-torrent-tv/

**Comment by VietTPham** [comment]
Does not sound like it is problem with sickrage, but a setup on your side.
use a batch script as your auto start 'python sickbeard.py <your argument here>'
