### ISSUE TITLE
Apostrophe in show name directory not working

### ISSUE THREAD

**Issue by xorinzor** [SickChill/SickChill#4638]
Branch/Commit: a7602639bd525f27475f1eeb2fc504111a14b51c
OS: Ubuntu 16.04
Browser: Chrome

**What you did:** I added shows to my NAS with directory name "Bob's Burgers", then I added the show in SickRage

**What happened:** it created a directory in my NAS named "Bob#39;s Burgers", when I removed that directory and tried to select the proper directory I could click on it all I wanted, but the web interface didn't do anything. It additionally said that the "Bob's Burgers" directory was missing after I deleted the incorrect directory.

**What you expected:** For it to select the directory "Bob's Burgers"

Logs:
```
INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /mnt/MediaStorage/Series/Bob's Burgers
```

I guess some htmlentities issue is going on here, since the log looks fine

**Comment by nstead** [comment]
I just discovered the same problem.
I'm using Branch v2018.04.08-1

In my case the show is "Marvel's Runaways".  When Sickrage tries to post-process an episode in a folder such as "Marvel's.Runaways.S01E04.Fifteen.1080p", it fails, reporting "Unable to figure out what folder to process".  If I try to manually post-process the folder, the web interface won't let me select the folder.

Renaming the folder to remove the apostrophe fixes the problem, and the post-processor has no problem with the apostrophe in the video file itself - this is purely a problem with the apostrophe in the folder name.

**Comment by zarboz** [comment]
#4588

**Comment by zarboz** [comment]
#4445

**Comment by zarboz** [comment]
#4601

**Comment by zarboz** [comment]
p/utils.py:481: UserWarning: unable to use "lxml": dlopen(/Users/zarboz/Downloads/SickRage/lib/lxml/etree.so, 2): no suitable image found.  Did find:
	/Users/zarboz/Downloads/SickRage/lib/lxml/etree.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/zarboz/Downloads/SickRage/lib/lxml/etree.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
  warnings.warn('unable to use "%s": %s' % (mod, str(e)))
/Users/zarboz/Downloads/SickRage/lib/imdb/parser/http/utils.py:472: UserWarning: falling back to "beautifulsoup"
  warnings.warn('falling back to "%s"' % mod)


guessing it has something to do with lxml

**Comment by Lucidi0us** [comment]
I am seeing this issue.  I also noticed that, when attempting to rename the folders and edit the locations for each show; I see it tell me that \quote\/media... does not contain a valid tvshow.nfo.  I.e. it can't read any special characters correctly, even when editing the show location it will convert whatever you type.
