### ISSUE TITLE
Shows reset, marked as downloaded and always have 7 seasons

### ISSUE THREAD

**Issue by HazMatt69** [SickChill/SickChill#4643]
SickRage Info:
Branch: master
Commit: a7602639bd525f27475f1eeb2fc504111a14b51c
Version: v2018.04.08-1
Database Version: 44.0
Python Version: 2.7.14 (default, Mar 03 2018, 11:05:58) [GCC 7.3.0]
SSL Version: OpenSSL 1.0.2n 7 Dec 2017
OS: Linux-3.4.6-x86_64-with-glibc2.2.5 (QNAP v4.3.4 Build 20180419)
Locale: en_US.UTF-8

I've been having a painful bug, as almost every show gets reset (and marked as downloaded) and counts 7 seasons, although there are not as many
<img width="1804" alt="screen shot 2018-04-30 at 10 09 47" src="https://user-images.githubusercontent.com/18046509/39419194-12574b10-4c5f-11e8-9b97-44fe6dd667e9.png">
<img width="1918" alt="screen shot 2018-04-30 at 10 10 20" src="https://user-images.githubusercontent.com/18046509/39419195-126c8250-4c5f-11e8-8185-bf43ca8bf53b.png">

 as seen in the attached screenshots.

**Comment by matthewjoliver** [comment]
Doing a "force full update" works and removes non existing seasons. I just wish I didn't have to do that each time the NAS reboots...

**Comment by matthewjoliver** [comment]
Hi,

I still have this issue and now "force full update" does not work anymore...
Any idea what I can do to correct this behaviour?
