### ISSUE TITLE
node.js

### ISSUE THREAD

**Issue by ajmm25** [SickChill/SickChill#4647]
Request failed: Missing Node.js runtime. Node is required and must be in the PATH (check with `node -v`). Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install nodejs-legacy` on some Debian-based systems. (Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.

I have been getting this message, I have installed node-v again bug it keeps happening anyone can help?

**Comment by Zjaaspoer** [comment]
I've got the same issue. Anyone?

**Comment by ajmm25** [comment]
yeah its not been working for a few weeks for me now.
Anyone knows what to do?

regards

**Comment by oAo-COBA** [comment]
Same problem

**Comment by lookatitude** [comment]
Same problem here and i have both node -v and nodejs -v working on MAC.

**Comment by alienx2** [comment]
Same here problem.. gave me error like this:

> Request failed: Missing Node.js runtime. Node is required and must be in the PATH (check with `node -v`). Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install nodejs-legacy` on some Debian-based systems. (Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.

**Comment by Dannejaha** [comment]
Same here, been broken for several weeks now. Been trying to update everything and installing nodejs according to instructions/hompag (Mac)

**Comment by busemann** [comment]
https://github.com/SickRage/SickRage/issues/4628#issuecomment-410257773 - This is how I solved it on Windows 10
