### ISSUE TITLE
[APP SUBMITTED]: not well-formed (invalid token): line 1, column 19

### ISSUE THREAD

**Issue by 00mpy** [SickChill/SickChill#4651]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
Link to Log: https://gist.github.com/41b5fef792026f38641064f8a383510b
### ERROR
```
SEARCHQUEUE-BACKLOG-326490 :: [Jackett - Torrent Day] :: [a760263] Unable to parse the XML of Marvel's.The.Defenders.S01.720p.Netflix.WEBRip.DD5.1.x264-PSYPHER, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by 00mpy** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-128-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-95441 :: [Jackett - IP Torrents] :: [807c5ae] Unable to parse the XML of NCIS.Los.Angeles.S01-S06.720p.WEB-DL.DD5.1.H.264-Mixed, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by 00mpy** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-128-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311945 :: [Jackett - TorrentDay] :: [807c5ae] Unable to parse the XML of Bull.2016.S01.720p.AMZN.WEBRip.DD5.1.x264-BTN, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by 00mpy** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-128-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311945 :: [Jackett - IP Torrents] :: [807c5ae] Unable to parse the XML of Bull.2016.S01-S02.720p.HDTV.X264-Scene.[NO.RAR], not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by 00mpy** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-128-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-176941 :: [Jackett - TorrentDay] :: [807c5ae] Unable to parse the XML of Sherlock.S01-S02-S03-S04.720p.BluRay.WEB.DL.x264-ITSat, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by 00mpy** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-128-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-176941 :: [Jackett - IP Torrents] :: [807c5ae] Unable to parse the XML of Sherlock.S01-S02-S03-S04.720p.BluRay.WEB.DL.x264-ITSat, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-266631 :: [PrivateHD] :: [0e72764] Unable to parse the XML of Thunderbirds.Are.Go!.S01.720p.AMZN.WEB-DL.DD+.5.1.H.264-SiGMA, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-253323 :: [PrivateHD] :: [0e72764] Unable to parse the XML of LEGO.Ninjago:.Masters.of.Spinjitzu.S06.720p.AMZN.WEB-DL.DD+.2.0.H.264-SiGMA, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-253323 :: [PrivateHD] :: [0e72764] Unable to parse the XML of LEGO.Ninjago:.Masters.of.Spinjitzu.S05.720p.AMZN.WEB-DL.DD+.2.0.H.264-SiGMA, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-253323 :: [PrivateHD] :: [0e72764] Unable to parse the XML of LEGO.Ninjago:.Masters.of.Spinjitzu.S04.720p.AMZN.WEB-DL.DD+.2.0.H.264-SiGMA, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-253323 :: [PrivateHD] :: [0e72764] Unable to parse the XML of LEGO.Ninjago:.Masters.of.Spinjitzu.S03.720p.AMZN.WEB-DL.DD+.2.0.H.264-SiGMA, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-253323 :: [PrivateHD] :: [0e72764] Unable to parse the XML of LEGO.Ninjago:.Masters.of.Spinjitzu.S02.720p.AMZN.WEB-DL.DD+.2.0.H.264-SiGMA, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahummaida** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-264365 :: [PrivateHD] :: [0e72764] Unable to parse the XML of Sofia.the.First.S01.720p.WEB-DL.AAC.2.0.H.264-NOGROUP, not splitting it
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by doreybenjamin** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 25 2018, 20:42:16) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-7-amd64-x86_64-with-debian-8.11**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-350665 :: [Jackett Ygg] :: [f7a113a] Unable to parse the XML of The.Rookie.:.le.flic.de.Los.Angeles.S01E04-09.HDTV.VOSTFR, not splitting it
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doreybenjamin** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 25 2018, 20:42:16) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-7-amd64-x86_64-with-debian-8.11**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
Link to Log: https://gist.github.com/5618a593accba7990f3d4191cb29301c
### ERROR
```
SEARCHQUEUE-BACKLOG-350665 :: [Jackett Ygg] :: [b3da866] Unable to parse the XML of The.Rookie.:.le.flic.de.Los.Angeles.S01E04-09.HDTV.VOSTFR, not splitting it
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:35:26) [GCC 8.3.0]**
Operating System: **Linux-4.19.56-Unraid-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
MANUAL :: [1ed3156] Unable to connect to theTVDB while creating meta files - skipping - error not well-formed (invalid token): line 19409, column 12
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:35:26) [GCC 8.3.0]**
Operating System: **Linux-4.19.56-Unraid-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [1ed3156] Unable to connect to theTVDB while creating meta files - skipping - error not well-formed (invalid token): line 19409, column 12
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:35:26) [GCC 8.3.0]**
Operating System: **Linux-4.19.56-Unraid-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
MANUAL :: [1ed3156] Unable to connect to theTVDB while creating meta files - skipping - error not well-formed (invalid token): line 19409, column 12
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:35:26) [GCC 8.3.0]**
Operating System: **Linux-4.19.56-Unraid-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [1ed3156] Unable to connect to theTVDB while creating meta files - skipping - error not well-formed (invalid token): line 19409, column 12
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:35:26) [GCC 8.3.0]**
Operating System: **Linux-4.19.56-Unraid-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [e094759] Unable to connect to theTVDB while creating meta files - skipping - error not well-formed (invalid token): line 19409, column 12
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by thenamelessthing** [comment]
### INFO
Python Version: **2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.15.0-88-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f9161da71a75dbabf83fd862bc4e46a0b4391352
Link to Log: https://gist.github.com/40a74d178053c5ac102b0838e24e5566
### ERROR
```
SEARCHQUEUE-BACKLOG-295068 :: [Ygg] :: [f9161da] Unable to parse the XML of Dragon.Ball.Super.S05.Multi.BluRay.1080p.x264.-.Chris44, not splitting it
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
@thenamelessthing I need the xml for `Dragon.Ball.Super.S05.Multi.BluRay.1080p.x264.-.Chris44` nzb from jackett.

**Comment by thenamelessthing** [comment]
@miigotu excuse me but can you give me where to retrieve it?

**Comment by miigotu** [comment]
@thenamelessthing search for it in your jackett UI, and download the nzb file from there.

**Comment by thenamelessthing** [comment]
@miigotu ,can you put a screenshot of the place where I can get them?  I doesn't found anywhere,,,

**Comment by wsbraun** [comment]
### INFO
Python Version: **2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@882758f0a88be7a48228e25e95c506fad926335a
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [882758f] Unable to write file to /mnt/series/Greek/Season 02/Greek - 2x06 - See You Next Time, Sisters! - 720p HDTV.nfo - are you sure the folder is writable? not well-formed (invalid token): line 1, column 0
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by wsbraun** [comment]
### INFO
Python Version: **2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@882758f0a88be7a48228e25e95c506fad926335a
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [882758f] Unable to write file to /mnt/series/The Crown/Season 01/The Crown - 1x03 - Windsor - 720p WEB-DL.nfo - are you sure the folder is writable? not well-formed (invalid token): line 1, column 0
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by wsbraun** [comment]
### INFO
Python Version: **2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@882758f0a88be7a48228e25e95c506fad926335a
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [882758f] Unable to write file to /mnt/series/Fargo/Season 01/Fargo - 1x07 - Who Shaves the Barber - SD DVD.nfo - are you sure the folder is writable? not well-formed (invalid token): line 48, column 15
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by wsbraun** [comment]
### INFO
Python Version: **2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@882758f0a88be7a48228e25e95c506fad926335a
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [882758f] Unable to write file to /mnt/series/Bones/Season 02/Bones - 2x20 - The Glowing Bones in the Old Stone House - SDTV.nfo - are you sure the folder is writable? not well-formed (invalid token): line 1, column 0
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by wsbraun** [comment]
### INFO
Python Version: **2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@882758f0a88be7a48228e25e95c506fad926335a
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [882758f] Unable to write file to /mnt/series/NCIS/Season 02/NCIS - 2x23 - Twilight - SDTV.nfo - are you sure the folder is writable? not well-formed (invalid token): line 2, column 2
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by wsbraun** [comment]
### INFO
Python Version: **2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@882758f0a88be7a48228e25e95c506fad926335a
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [882758f] Unable to write file to /mnt/series/Long Way Round/Season 01/Long Way Round - 1x03 - Kazakhstan - SD DVD.nfo - are you sure the folder is writable? not well-formed (invalid token): line 1, column 0
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
