### ISSUE TITLE
post processing folder permission error

### ISSUE THREAD

**Issue by Fafa24** [SickChill/SickChill#4653]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Linux-3.10.102-x86_64-with-glibc2.2.5 / Synology DSM DSM 6.1.6-15266 Update 1
Browser: Firefox
What you did: I didn't change anything so far as I know
What happened: Sickrage cannot acccess the post processing folder which resided on the same Synology box. It appears there is a permission issue. When I look at the server status info. It says disk space for TV download directory "missing"
What you expected: Sickrage no longer post process files
Logs:
2018-05-07 20:19:59 ThreadPoolExecutor-0_0 :: Unable to open /volume1/download: OSError(13, 'Permission denied') / [Errno 13] Permission denied: '/volume1/download

Under the folder /volume1/download there a subfolders. Sickrage cannot access them. 

How can I resolve the permission error. 

Thanks
Fafa24

**Comment by xorinzor** [comment]
As you replied on #4633 opening this issue is basically a duplicate.
Since you apparently also have a synology NAS I'd recommend asking on their forums if  you dont get a reply from the other guy, since this is not a sickrage issue, but rather an issue with the NAS in the way it handles its permissions

**Comment by Fafa24** [comment]
Thanks - I saw the other topic later. Yes it is basically a Synology permission issue I think.
