### ISSUE TITLE
TNTVillage Italian Provider

### ISSUE THREAD

**Issue by Danny89530** [SickChill/SickChill#4659]
Hi,
Because of the provider changed his policy, the old webpage is accessible only if anyone has a paid account but, otherwise, they expose another light version for anyone other.
So I've rewrited the script <[tntvillage.py.txt](https://github.com/SickRage/SickRage/files/1983729/tntvillage.py.txt)> and is actually in use in my environment, feel free to modify it for a perfect integration with SR!

Regards.

**Comment by TEO984** [comment]
Scusa l'ignoranza ma come faccio ad usare il tuo script? e mille grazie per il lavoro che hai fatto.

**Comment by TEO984** [comment]
Fatto grazie
