### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-DAILY-SEARCH :: [5a9a634] qbittorrent: Unable to set the pause for Torrent

### ISSUE THREAD

**Issue by gatamah** [SickChill/SickChill#4697]
### INFO
Python Version: **2.7.13 |Continuum Analytics, Inc.| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
Link to Log: https://gist.github.com/ef0991ca16e550c9ff8ea1401ddd8443
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [5a9a634] qbittorrent: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by andystevens91** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.13.0-41-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
Link to Log: https://gist.github.com/d614e6434ac5a8e0b31c534599443dd9
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [5a9a634] qbittorrent: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gatamah** [comment]
### INFO
Python Version: **2.7.13 |Continuum Analytics, Inc.| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
Link to Log: https://gist.github.com/3c170cd9664969f6b2cead8c0dcf9df6
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [5a9a634] qbittorrent: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Zabanya** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.9.87-linuxkit-aufs-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
Link to Log: https://gist.github.com/2698df4231f09642e32a96f78d457268
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [5a9a634] qbittorrent: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by procdaddy11** [comment]
Same issue here

**Comment by POgli** [comment]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-296762 :: [5a9a634] qbittorrent: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by POgli** [comment]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-279121 :: [5a9a634] qbittorrent: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by POgli** [comment]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295685 :: [5a9a634] qbittorrent: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by POgli** [comment]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-280619 :: [5a9a634] qbittorrent: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
