### ISSUE TITLE
HEVC Support!

### ISSUE THREAD

**Issue by herbi3** [SickChill/SickChill#4707]
Having the show settings on HD where the required naming structure of a file has to contain hdtv etc. episodes with the hevc codec are ignored by sick rage completely.

How about adding an or function to the required file names which includes hevc?

If I go the long way about it, i.e setting the required words, ignore words etc. and quality set to custom (Because HEVC comes up as 'Unknown' quality....) I've noticed shows don't get snatched until I force the backlog again.

**Comment by herbi3** [comment]
Still no HEVC support???

**Comment by miigotu** [comment]
Stalebot might have to go...

**Comment by herbi3** [comment]
Instead of setting the quality as unknown and getting either 1080 OR 720 etc, I still have the required words x265, hevc, and ignored x264

I stopped auto updates, and edited common.py at line 387 from

"return Quality.UNKNOWN if result is None else result"
to
"return Quality.HDTV if result is None else result"

**Comment by miigotu** [comment]
@herbi3 this has been added already in the develop branch, you just have to enable the "allow hevc" option in search settings.

**Comment by herbi3** [comment]
👍🏼 following the other post, thanks for the reminder
