### ISSUE TITLE
New Installation (From SickBeard) - Shows with Apostrophe's gets processed with &#39

### ISSUE THREAD

**Issue by whiteazn** [SickChill/SickChill#4708]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 0.5.3
OS: Windows
Browser: Chrome

What you did: Shutdown SickBeard, Installed SickRage. Add Show > Add Existing Shows > Added locations for TV Shows > Checked Setting to check each show

What happened: As I was going through the shows, it crashed.  It was after about 10 shows in.  It crashed when I just finished checking the settings for a show, clicked add, and was trying to load the next show.  It was trying to load a show that had an apostrophe.  It had weird characters in the search text field.  I then happened to check the location of the TV Shows in windows explorer, and noticed all the shows that were added that had an apostrophe in it, had the folders renamed.  All apostrophes went from ' to & #39;  (without the space, so AmpersandPound39Semicolon)

I checked the folders themselves, and all the files were gone.  Not in the Recycle Bin.  Just, gone. Logs don't seem to show anything. **EDIT: FILES NOT DELETED?**

**EDIT:  Looks like the new folders were created, but the old folders were still there.**  But seems to be an issue with shows with Apostrophe's?  I mean, do I have to name my folders with "Whiteazn&#39's Show"?  It is throwing my Plex off (having to manually match the shows where before it would match it just fine)

I also notice that in the individual show page, if I edit and try and change show location, i cannot click on the show folder.  Trying to click on Chef's Table does nothing.  (If I add the folder Chef&#39s Table, it is able to traverse to the folder fine)

What you expected: Added Show

Logs: (of one of the shows affected)
```
2018-05-16 22:38:40 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: L:\Videos\TV Shows\Chef's Table France
2018-05-16 22:38:36 INFO SHOWQUEUE-ADD :: Done cache check
2018-05-16 22:38:35 INFO SHOWQUEUE-ADD :: 268972: Updating NFOs for show with new indexer info
2018-05-16 22:38:30 INFO SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2018-05-16 22:38:30 INFO SHOWQUEUE-ADD :: 268972: Unable to find the show in the database
2018-05-16 22:38:30 INFO SHOWQUEUE-ADD :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', u'cache': u'D:\\Apps\\Media\\SickRage\\Data\\cache\\indexers\\theTVDB', u'language': 'en'}
2018-05-16 22:38:30 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: L:\Videos\TV Shows\Chef's Table
2018-05-16 22:38:29 INFO SHOWQUEUE-ADD :: Done cache check
2018-05-16 22:38:21 INFO SHOWQUEUE-ADD :: 81903: Updating NFOs for show with new indexer info
```

Edit:  I forced restart of Sickrage.

**Comment by zarboz** [comment]
#4588

**Comment by zarboz** [comment]
#4445

**Comment by zarboz** [comment]
#4638

**Comment by whiteazn** [comment]
>#4445

which referenced this pull https://github.com/SickRage/SickRage/pull/4702 by @Fiat2LTC

Doesn't fix it.  While it does let me browse WebFileBrowser, it still does not fix the issue.  It still tries to save to the FilePath with the escaped Html Characters, and even if you change the path by editing to the correct folder, it still does not refresh the episodes correctly.

**Comment by Fiat2LTC** [comment]
Try the latest develop brsnch

**Comment by whiteazn** [comment]
Tried it.  Still isn't completely working.  When adding the show, it is able to find the show automatically now.  But the show page, still shows location missing, and re-scanning files doesn't seem to find it.

**Comment by Fiat2LTC** [comment]
Yes unfortunately not easy to fix the entries that were added while it was broken, no worries! Glad it's sorted

**Comment by Fiat2LTC** [comment]
Found some more lines to fix! PR submitted #4753

**Comment by HPMSGEN8** [comment]
So it works and does not add this wired #xxx BUT if i try and edit my shows it does not work as it cannot find the folder of the show.

**Comment by Fiat2LTC** [comment]
HPMSGEN8 latest develop branch is working fine for me now, please try it and maybe try removing the show and re-adding.

**Comment by Fiat2LTC** [comment]
If you're still having issues include a screenshot of the exact bit it's failing on so I can debug

**Comment by Lucidi0us** [comment]
Still having issues where editing the show path declares that the tvshow.nfo is missing and aborts.  Using develop branch.
![image](https://user-images.githubusercontent.com/2955403/41072159-603ff5c6-69b9-11e8-8b91-40917c9c03d2.png)
![image](https://user-images.githubusercontent.com/2955403/41072167-72ea1f44-69b9-11e8-9d7e-0926b1d49dac.png)

**Comment by Fiat2LTC** [comment]
@Lucidi0us new PR submitted to fix this, please try develop branch once merged

**Comment by HPMSGEN8** [comment]
I have stated this now on the new master and it is working for me at least. Changed 2 shows where the was an 's and so far all good :)  Now i only have a few more issues to get fix :D

**Comment by whiteazn** [comment]
Make sure you are on the latest branch and updated?  

Jack Ryan is working fine for me

**Comment by gerbil42** [comment]
I "think" so.

Branch: master
Commit: 0e727649748ec38c5bba69f3f97c9e7b794d56df
Version: v2018.07.21-1

My issue isn't with the folders, but with the file names after rename, and the display in the Shows drop-down menu.

![image](https://user-images.githubusercontent.com/8066781/45013211-26de6400-afcf-11e8-9131-1110810daa59.png)

I can rename them manually with bulk tools and they're fine after, but this seems like it should be fixed, based on these threads, but isn't working right for me.

**Comment by TheHolyRoger** [comment]
@gerbil42, to quote @Fiat2LTC twice above...

> latest develop branch is working fine for me

:) You're on master branch @gerbil42

**Comment by gerbil42** [comment]
I also tried the Develop branch. It made no difference, so I switched back.
I'll try it again.

**Comment by gerbil42** [comment]
No change with Develop.  Still have the same issues with the &#39; display and file, but not folder, names.

I also tried removing the show and re-adding it, then re-processing a few of the files I had already manually renamed.

They came out with the &#39; where the apostrophe, or nothing, should be.

**Comment by TheHolyRoger** [comment]
@gerbil42 are you using latest develop? Can you paste the commit ID?

Also screenshots of where it goes wrong starting with adding a **fresh** show with apostrophes

**Comment by gerbil42** [comment]
Commit: 7702fd81b8732b8f9f03c17bc80141bb6a7f4a57

Nothing goes wrong with adding the show.  That works fine.  The folders are created properly, the show appears correctly in the table list view.

My issues seem to be related to the same handling of apostrophes, but in other processes.  Namely the screenshot I posted above about the Shows drop-down and in post-process rename.

I didn't realize when I replied to the post that this was only about the process of adding shows.  Should I open a new issue?  The issue tracker looked incredibly cluttered so I felt lucky to find a thread that seemed to describe the issue I was having.

**Comment by whiteazn** [comment]
Weird.  For me, in the dropdown, one works, others don't.

Tom's Clancy Jack Ryan, Let's Eat Dinner Together ... those 2 work and show up fine.

Chef's Table shows up like yours.

Probably just another place where the apostophe fix needs to be implemented in to
