### ISSUE TITLE
BTFailure from torrent9 when trying to download torrents.

### ISSUE THREAD

**Issue by czotti** [SickChill/SickChill#4716]
Hi, 
Yesterday, I was trying to check why my torrents were not downloading anymore from torrent9.
In fact it's due to torrent9 that change the url to get their torrents.
The `http://torrent9.red/get_torrent/blabla.html` is not working anymore and redirect to a page with non related torrent.

I have a made a quick fix in my fork: https://github.com/czotti/SickRage/tree/fix/torrent9
The fix is in the file `sickbread/providers/torrent9.py`
On my side the fix seems to work, the torrent is added to my transmission downloader.

It's my first time trying to contribute, can I make a PR with my fix ?

Branch/Commit:
OS: Freenas 11.1, Archlinux
Browser: Firefox.
What you did: Searching for torrent on torrent9 tracker.
What happened: Nothing is download due to a change in the torrent9 torrent download.
What you expected: The torrent to e downloaded.
Logs:
```
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA result = self._get_torrent_hash(result)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/clients/generic.py", line 259, in sendTORRENT
AA Traceback (most recent call last):
2018-05-20 09:30:20 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [5a9a634] Transmission: Failed Sending Torrent
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA Traceback (most recent call last):
2018-05-20 09:30:20 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [5a9a634] Unable to bdecode torrent
2018-05-20 09:30:20 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading iZombie.S04E11.VOSTFR.HDTV.x264-Torrent9 from Torrent9
2018-05-20 09:30:20 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: Quality of iZombie.S04E11.VOSTFR.HDTV.x264-Torrent9 is SDTV
2018-05-20 09:30:20 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: Found result iZombie.S04E11.VOSTFR.HDTV.x264-Torrent9 at http://www.torrent9.red/get_torrent/izombie-s04e11-vostfr-hdtv.torrent
```

**Comment by jlejeune** [comment]
I have also errors with your dev branch I have fixed on this PR : https://github.com/czotti/SickRage/pull/1

You can test it and create a PR on official sickrage repository after that. Maybe @Arm-ageddon can validate it too.

**Comment by Arm-ageddon** [comment]
It's ok for me too. Nice !
Thank you ! not good enough in python to fix it by myself :)

**Comment by lagaisse** [comment]
Hello,

I would iterate on each row in line 86 instead of iterating (once?) on the table

Proposal (tested &working on Synology) :

```
                with BS4Parser(data, 'html5lib') as html:
                    torrent_table = html.find('div', {'class': 'table-responsive'})
                    if torrent_table is not None:
                        torrent_rows = torrent_table.findAll('tr')
                    if not torrent_rows:
                        continue

                    for result in torrent_rows:
```

**Comment by lagaisse** [comment]
Hello,
I would iterate on each row on line 86 instead of iterating (once?) on the table 

Proposal for your PR (tested on synology) :
```
                with BS4Parser(data, 'html5lib') as html:
                    torrent_table = html.find('div', {'class': 'table-responsive'})
                    if torrent_table is not None:
                        torrent_rows = torrent_table.findAll('tr')
                    if not torrent_rows:
                        continue

                    for result in torrent_rows:
```

**Comment by rdehouss** [comment]
#4719 works for me, thx!

**Comment by dubazar** [comment]
Hello,
The fix was not pushed, right?
How can I use it on my own?
Thanks

**Comment by Jamyz** [comment]
Latest commit 9392379 online but not pushed... Why ?
