### ISSUE TITLE
Quote mark cannot be used in the file path of "Edit Show/Main/Show Location" field

### ISSUE THREAD

**Issue by janusn** [SickChill/SickChill#4720]
## Branch:
master
## Commit:
5a9a634bc8af642c13a41b01affabbe96d9564dd
## Database Version:
44.0
## Python Version:
2.7.9 (default, Sep 9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]
## OS:
FreeNAS v11.1-U4
## Browser:
Google Chrome

## What you did: 
Shows->Show List
Click on a Show (like "Handmaid's Tale")
Click on Edit Button
On "Main"->"Show Location" type:
/path/to/Handmaid's Tale
Click On "Save Changes" Button

## What happened:
It redirected back to the show information page without the change on "Show Location" made.
It kept the old value

## What you expected:
It redirected back to the show information page with the "Show Location" changed as new value.

## Additional information:
After clicking on the Browse Button on the right of the Edit/Main/Show Location Field, click on the destination folder with a quote on the folder name does not change the directory to there either.

**Comment by AzureCerulean** [comment]
SickRage Info:
Branch: master
Commit: 5a9a634bc8af642c13a41b01affabbe96d9564dd
Version: v2018.05.11-1
Database Version: 44.0
  Python Version: 2.7.13 (default, Dec 4 2017, 14:53:22) [GCC 6.3.0 20170406]
  SSL Version: OpenSSL 1.0.2g 1 Mar 2016
  OS: Linux-4.10.0-43-generic-x86_64-with-Ubuntu-17.04-zesty
  Locale: en_US.UTF-8

CONFIRMED:  you cannot add/use/enter directories or file names with  string related characters.

**Comment by Fiat2LTC** [comment]
See #4708 and try the latest develop branch
