### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-FORCE-UPDATE :: [5a9a634] No data returned from theTVDB, unable to update this show.

### ISSUE THREAD

**Issue by noodles101** [SickChill/SickChill#4723]
### INFO
Python Version: **2.7.13 (default, Dec 19 2016, 01:28:10) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [5a9a634] No data returned from theTVDB, unable to update this show.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by muchall** [comment]
### INFO
Python Version: **2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-121-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [5a9a634] No data returned from theTVDB, unable to update this show.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
