### ISSUE TITLE
[APP SUBMITTED]: Invalid folder for the show!

### ISSUE THREAD

**Issue by ahyear** [SickChill/SickChill#4725]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-132-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-ADD :: [5a9a634] Error trying to add show: Invalid folder for the show!
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-132-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-ADD :: [5a9a634] Error trying to add show: Invalid folder for the show!
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by HPMSGEN8** [comment]
What are you trying to add ? Or is this for all

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-132-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-ADD :: [5a9a634] Error trying to add show: Invalid folder for the show!
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-151-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@93923792e8908427344d6e01de968656cf096626
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-ADD :: [9392379] Error trying to add show: Invalid folder for the show!
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-151-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-ADD :: [0e72764] Error trying to add show: Invalid folder for the show!
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-3.13.0-151-generic-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-ADD :: [0e72764] Error trying to add show: Invalid folder for the show!
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
