### ISSUE TITLE
Need to reboot Sickrage for downloading files

### ISSUE THREAD

**Issue by stephane-r** [SickChill/SickChill#4734]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit**: master
**OS**: OSMC
**Browser**: Mozilla
**What you did**: Search file
**What happened**: Error from logs : `BTFailure: not a valid bencoded string`. If i restart Sickrage, all download is succes. After 24h (why 24h ?), i've this error. I need to restart :/
**What you expected**: Downloading file :)
**Logs**:
![image](https://user-images.githubusercontent.com/4712791/40588094-a10b0a2a-61d8-11e8-97ba-873fa8a7ed48.png)

**Comment by HPMSGEN8** [comment]
Did u upgrade to the Last Version before this started or it was always there ? The last option is the backup SickRage copy the config files - The Wiki states what needs to get backed up and start on an clean install and see if this works.
