### ISSUE TITLE
Passwords with special characters

### ISSUE THREAD

**Issue by Lucidi0us** [SickChill/SickChill#4738]
After the last update, SickRage stopped accepting my password.  After clearing the ini and trying variations, it appears the issue was having "!" in my password.  The password was working until the latest update.

My issue is resolved as I chose a new password.

**Comment by Fiat2LTC** [comment]
sounds like password just needs to be unescaped in webserve.py
Will have a look when I have a moment

**Comment by dcrdev** [comment]
Yeah this is now affecting the mail notifications and github credentials too.
