### ISSUE TITLE
[BUG] Required Words Override Not Working

### ISSUE THREAD

**Issue by HPMSGEN8** [SickChill/SickChill#4740]
Hi,

So there seems to be an issue with the Required Words. If you exclude something on the Global Settings. Required Words overwrite this as.

I have WEBRIP excluded and then enabled for this show but it does not take the settings.

I did create an folder called The Handmaids Tale and used this as the 's still an issue.

Branch/Commit:
Branch: master
Commit: 5a9a634bc8af642c13a41b01affabbe96d9564dd
Version: v2018.05.11-1
Database Version: 44.0
What you did: Add Required Words
What happened: Did Not Snatch
What you expected: Show To Snatch
Logs:
```
Scene Name:	The Handmaid's Tale | The Handmaids Tale
Required Words:	WEBRIP,x264,HDTV,TBS,-TBS

Release: The.Handmaids.Tale.S02E07.WEBRip.x264-TBS contains webrip, ignoring it
Quality of The.Handmaids.Tale.S02E07.WEBRip.x264-TBS is SDTV
 Performing episode search for The Handmaid's Tale

```

Any help at all please.

Thanks

**Comment by HPMSGEN8** [comment]
My Global Ignore Words have WEBRIP Listed and the Shows Required Words Have WEBRIP so the Show should Override the Global Settings but it is not.

**Comment by HPMSGEN8** [comment]
@sharkykh If you have time can you help me out on this as you seem to know all the tricks of the trade :)

**Comment by HPMSGEN8** [comment]
I have tried on another show and this is still broken after the new update.

**Comment by HPMSGEN8** [comment]
Can someone please fix this bug

**Comment by miigotu** [comment]
make the required word `webrip` and not `WEBRIP` and it will override `webrip` in the ignored words list.
