### ISSUE TITLE
SceneTime provider is no longer working

### ISSUE THREAD

**Issue by abright52** [SickChill/SickChill#4755]
Branch: master
Commit: 5a9a634bc8af642c13a41b01affabbe96d9564dd
Version: v2018.05.11-1
OS: Windows-7-6.1.7601-SP1
Browser: Chrome
What you did: Search
What happened: No results
What you expected: Snatched!
Logs:
```
SEARCHQUEUE-BACKLOG-290498 :: [SceneTime] :: Request failed: 404 Client Error: Not Found for url: https://www.scenetime.com/browse_API.php
```

**Comment by papaxris** [comment]
I too am experiencing the same as abright52 has mentioned.

Branch: master
Commit: 5a9a634bc8af642c13a41b01affabbe96d9564dd
Version: v2018.05.11-1
 OS: Linux-4.4.0-127-generic-x86_64-with-Ubuntu-16.04-xenial
Browser: Chromium
What you did: Search
What happened: No results
What you expected: Snatched!

[SceneTime] :: Request failed: 404 Client Error: Not Found for url: https://www.scenetime.com/browse_API.php

**Comment by goomercampbell** [comment]
Has anyone managed to fix this yet as I to am having the same issue

**Comment by papaxris** [comment]
Hey goomercampbell,

Its still unresolved.  Help out the Dev Team by posting the information related to you SickRage Install.

This should help them identify where the issue started.

Prior to updating SickRage, SceneTime was working.  At the time I was 46 commits behind; now I'm on Version: v2018.05.11-1 where we have confirmed SceneTime is broken.

**Comment by abright52** [comment]
I don't think anything was broken in SickRage, it looks like Scenetime made a change on their end.  That is why Browse_API.php is returning a 404.

**Comment by abright52** [comment]
I moved over to using Jackett to query Scenetime.  It had the same problem, but their devs were able to get it fixed already.
Maybe this will help get SickRage fixed, as well:
https://github.com/Jackett/Jackett/issues/3199

**Comment by papaxris** [comment]
Hey xchewtoyx,

Confirmed Working.

Many Thanks for turning this around so quickly!
