### ISSUE TITLE
[APP SUBMITTED]: can't start new thread

### ISSUE THREAD

**Issue by prantzos** [SickChill/SickChill#4757]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [5a9a634] Exception generated in thread SHOWQUEUE-REFRESH: can't start new thread
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [5a9a634] Exception generated in thread POSTPROCESSOR-AUTO: can't start new thread
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [5a9a634] 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
CHECKVERSION :: [5a9a634] Exception generated in thread CHECKVERSION: can't start new thread
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by j0n0russo** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.19.8-ckt22-custom-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/89df4bf3d546c23faf111c6e73361559
### ERROR
```
SHOWQUEUE-REFRESH :: [0e72764] Exception generated in thread SHOWQUEUE-REFRESH: can't start new thread
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by j0n0russo** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.19.8-ckt22-custom-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/5b0eb4ff083022ae04771d7a0a190d7d
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [0e72764] Exception generated in thread SEARCHQUEUE-DAILY-SEARCH: can't start new thread
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by j0n0russo** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.19.8-ckt22-custom-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/ae25615ff63eb085e86ddcb3544e20d7
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] Exception generated in thread POSTPROCESSOR-AUTO: can't start new thread
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by j0n0russo** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.19.8-ckt22-custom-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9862786ccee1054cdcac409ef27abe5a63af5936
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [9862786] Exception generated in thread SHOWQUEUE-REFRESH: can't start new thread
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by dporem** [comment]
### INFO
Python Version: **3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]**
Operating System: **Linux-4.19.66-v7+-armv7l-with-debian-10.0**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@54162dfb5f95c68f8da55bbfd9efa97e1f1a7caa
Link to Log: https://gist.github.com/5caacc5ae45ac718b1528ca9927d6260
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-5.10.60-v7+-armv7l-with-debian-10.10**
Locale: UTF-8
Branch: **pip**
Commit: SickChill/SickChill@1ab5cd772328140c49813ca683de00f5bfa2997f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-5.10.60-v7+-armv7l-with-debian-10.10**
Locale: UTF-8
Branch: **pip**
Commit: SickChill/SickChill@1ab5cd772328140c49813ca683de00f5bfa2997f
No Log available with ERRORS:
### ERROR
```
Exception generated in thread POSTPROCESSOR-AUTO: can't start new thread
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-5.10.60-v7+-armv7l-with-debian-10.10**
Locale: UTF-8
Branch: **pip**
Commit: SickChill/SickChill@1ab5cd772328140c49813ca683de00f5bfa2997f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-5.10.60-v7+-armv7l-with-debian-10.10**
Locale: UTF-8
Branch: **pip**
Commit: SickChill/SickChill@1ab5cd772328140c49813ca683de00f5bfa2997f
No Log available with ERRORS:
### ERROR
```
Exception generated in thread SHOWQUEUE-REFRESH: can't start new thread
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
