### ISSUE TITLE
Seeing unusual amount of traffic

### ISSUE THREAD

**Issue by supersonical** [SickChill/SickChill#4759]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master, 5a9a634bc8af642c13a41b01affabbe96d9564dd
OS: Linux-4.4.0-124-generic-x86_64-with-Ubuntu-16.04-xenial
Browser: Chrome
What you did: Seeing big amount of network traffic
What happened: Network traffic is excess of 250mbit/s constantly
What you expected: not that much traffic. 
Logs:
```
PASTE LOGS HERE
```

**Comment by HPMSGEN8** [comment]
I take it if you stop SickRage the issue stops ?

**Comment by supersonical** [comment]
Correct, i can see thet it has generated around 5.5TB traffic during a 14 day period.

**Comment by HPMSGEN8** [comment]
I am not an expert here but have you tried to install an clean setup on another different OS or the same and see if that works or solve the issue.

99% of the time for me when i have issues i re-install and it works. 

The DEV's will need to answer this one.

**Comment by HPMSGEN8** [comment]
Did it work ?

**Comment by supersonical** [comment]
I actually found that if i had stuff in the "download" folder it generated alot of data transfer. It stopped when i removed everything from the folder the data transfer stopped. My first thought was that i have been hacked... but than i saw that the data only transferred between my subnets. Question is what has changed in the latest update which creates this behavior. 

Sorry for my bad english!
