### ISSUE TITLE
Wrong Folder Path

### ISSUE THREAD

**Issue by greentrancer** [SickChill/SickChill#4760]
Branch/Commit: master latest
OS: Qnap OS
Browser: Mozilla Firefox
What you did: added 'Marvel's Agents of S.H.I.E.L.D. (2013)' folder
What happened: creates 'Marvel&#39;s Agents of S.H.I.E.L.D. (2013)' empty folder on the NAS and shows that I have 0 episodes
What you expected: get 'Marvel's Agents of S.H.I.E.L.D. (2013)' folder and list the episodes

I even restarted SickRage, added the folder again and it always happens the same.

**Comment by HPMSGEN8** [comment]
Try this.

1. Delete the show from SickRage and not the Data.
2. Delete the .nfo from the main folder
3. Then re-name the main folder to Marvel's Agents of S.H.I.E.L.D.
4. Once done add an exciting show and select Marvel's Agents of S.H.I.E.L.D.
5. Let it add it back

This should work with no issues BUT remember there is an issue with 's shows so once you have added it you cannot modify it again until the issues are solved in the master branch.

**Comment by greentrancer** [comment]
Thank you for your suggestion. Unfortunately I was away over the weekend and did not get time to do anything.

I just updated to the latest version and the issue seems to be fixed.

I was partly incorrect above, the folder that was getting created was by SickRage was 'Marvel&#39;s Agents of S.H.I.E.L.D. (2013)' or something very similar. My main folder is 'Marvel's Agents of S.H.I.E.L.D. (2013)' and it always stayed the same, only SickRage was creating an additional one and reading (obviously) 0 files from it.

Thanks again for trying!
