### ISSUE TITLE
Chome on MacOS gets ERR_CERT_INVALID error.

### ISSUE THREAD

**Issue by ogg1e** [SickChill/SickChill#4763]
Ever since I updated, I can no longer connect via chrome on MacOS.

It used to be fine, but it now gives me the error NET::ERR_CERT_INVALID and does not have the proceed link like it used to. 

Strange thing is that it still works as before on linux using chrome

**Comment by WebSpider** [comment]
Chrome is working on being more strict about security aspects, such as SSL checks. Possibly you have an expired or self-signed SSL certificate?
