### ISSUE TITLE
[APP SUBMITTED]: Found 294176, but attribute 'seriesname' was empty.

### ISSUE THREAD

**Issue by monipeni** [SickChill/SickChill#4764]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
Link to Log: https://gist.github.com/4fc2741cab0672d3a31df1c1fbf4dfe6
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [5a9a634] Data retrieved from theTVDB was incomplete, aborting: Found 294176, but attribute 'seriesname' was empty.
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
the tvdb has been having some issues.
If this is still a problem, please force-update the show
