### ISSUE TITLE
Probleme with yggtorrent

### ISSUE THREAD

**Issue by Hydro8** [SickChill/SickChill#4770]
Hi

I add yggtorrent as search provider. Search is ok (founds some results on log) but I've got error for creditentials :

Invalid username or password. Check your settings. 

I check more than once and I change my password for something easier but nothing work. 

Maybe it's because I've got a number on my login name ?

Thank

**Comment by neodavid13fr** [comment]
hello, you must change the url in yggtorrent.py file. http:\\yggtorrent.is must be change in http:\\ww1.yggtorrent.is

**Comment by Hydro8** [comment]
Thank it works !

**Comment by LaurentDes** [comment]
Hi 
on synology how can I modify the files?
thks

**Comment by Oz246** [comment]
Thank it works !
