### ISSUE TITLE
SickRage pulling old TV Show Details - TVDB2 problem?

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#4779]
I've noticed that one of my shows has started pulling through incorrect information.

Branch/Commit: master Commit: 93923792e8908427344d6e01de968656cf096626 
OS: Windows
Browser: 60.0.2 (64-bit)
What you did: Noticed Taz-Mania shows two seasons, checked TVDB and it only shows one. Force update made no difference, deleted and readded the show made no difference
What happened: Taz-Mania still shows two seasons
What you expected: Taz-Mania should show one season

https://www.thetvdb.com/series/taz-mania
I have checked the show ID matches (76989) and I presume that the old version of the site had two seasons but the new version of the site has one

**Comment by rutskiuk** [comment]
Are you referring to nfo, tbn and tvshow.info in the Taz-Mania folder? If so, there aren't any.
I tried looking for 76989 and taz-mania as the prefix but couldn't see anything other than the cache images.

**Comment by HPMSGEN8** [comment]
Ok so i just added this to my setup - displayShow?show=76989

There is 2 Sessions and i have all the pics, Poster, backdrop etc.... and all showing

am i missing something ?

**Comment by rutskiuk** [comment]
There aren't two seasons, just one:
https://www.thetvdb.com/series/taz-mania

**Comment by HPMSGEN8** [comment]
I see what you mean i went to go take an look.  Seems there is an issue but the @admins @devs will need to help here.

**Comment by rutskiuk** [comment]
I can no longer replicate the problem, the show in question now shows one season.
