### ISSUE TITLE
DownloadStation: Failed Sending Torrent (work before)

### ISSUE THREAD

**Issue by LaurentDes** [SickChill/SickChill#4780]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:SickRage/SickRage i
**OS:** synology
Browser:
**What you did**: nothing new
**What happened:**
Many Week, Download failed
2018-06-16 07:31:16 SEARCHQUEUE-BACKLOG-311892 :: [5a9a634] Unable to bdecode torrent
2018-06-16 07:31:16 SEARCHQUEUE-BACKLOG-311892 :: [5a9a634] DownloadStation: Failed Sending Torrent
**What you expected:** download again

Logs:
```
PASTE LOGS HERE
```

thanks for your help

**Comment by neo62248** [comment]
Hello, 

what provider do you use?

**Comment by LaurentDes** [comment]
torrent9 an ygg

**Comment by LaurentDes** [comment]
more log detail


AA Extra Info:
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/volume1/@appstore/****beard-custom/var/SickBeard/****beard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/volume1/@appstore/****beard-custom/var/SickBeard/****beard/clients/generic.py", line 216, in _get_torrent_hash
AA result = self._get_torrent_hash(result)
AA File "/volume1/@appstore/****beard-custom/var/SickBeard/****beard/clients/generic.py", line 259, in sendTORRENT
AA Traceback (most recent call last):
2018-06-17 13:39:22 ERROR SEARCHQUEUE-DAILY-SEARCH :: [5a9a634] DownloadStation: Failed Sending Torrent
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/volume1/@appstore/****beard-custom/var/SickBeard/****beard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/volume1/@appstore/****beard-custom/var/SickBeard/****beard/clients/generic.py", line 216, in _get_torrent_hash
AA Traceback (most recent call last):
2018-06-17 13:39:22 ERROR SEARCHQUEUE-DAILY-SEARCH :: [5a9a634] Unable to bdecode torrent

**Comment by LaurentDes** [comment]
any news ?

**Comment by miigotu** [comment]
Usually this happens when you have too low of a seed ratio or too many hit and runs.
