### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'findAll'

### ISSUE THREAD

**Issue by proctophage** [SickChill/SickChill#4784]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/d9bde97a9c0cfdac32807703a6664a35
### ERROR
```
SEARCHQUEUE-BACKLOG-269653 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/02d7c14b1e1921fa5afe927fbaf3078c
### ERROR
```
SEARCHQUEUE-BACKLOG-239851 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/6f82883eb5e04de705ad277434d39252
### ERROR
```
SEARCHQUEUE-BACKLOG-72885 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/2b79351119aa16981cb96db63a3122f4
### ERROR
```
SEARCHQUEUE-BACKLOG-77398 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/0183262dfde6ad58265eed90be466c12
### ERROR
```
SEARCHQUEUE-BACKLOG-262754 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/48f9784e84b17be4da025eb0e9fc6f00
### ERROR
```
SEARCHQUEUE-BACKLOG-81751 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/a407efce91111562edaae26583e7c34f
### ERROR
```
SEARCHQUEUE-BACKLOG-85249 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/80ec7c80128425fba1532f976bf596ab
### ERROR
```
SEARCHQUEUE-BACKLOG-279659 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/e61bf97701477004032c0e9d12114315
### ERROR
```
SEARCHQUEUE-BACKLOG-302938 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/0e70aa06d83bd1b8f07f518259f2d8d3
### ERROR
```
SEARCHQUEUE-BACKLOG-270408 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/15a1c77bc2e30690bb6464680ca7294f
### ERROR
```
SEARCHQUEUE-BACKLOG-270633 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/b468ca7c14b3e364aa2f25ac200fb224
### ERROR
```
SEARCHQUEUE-BACKLOG-78901 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/37d7f833d49b4ab2b9afcad30331cc03
### ERROR
```
SEARCHQUEUE-BACKLOG-260449 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by xchewtoyx** [comment]
Looks like the PR I submitted was incomplete.  I can see where the problem is, when there are no search results, the html returned is invalid (torrenttable div is not closed).  I will raise a new PR that checks for this and treats it as no result rather than raising an exception

**Comment by papaxris** [comment]
**INFO**

Python Version: 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
Operating System: Linux-4.4.0-127-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: en_US.UTF-8
Branch: master
Commit: 807c5ae37ecd5af7483f06459c94788ee9db483d
Version: v2018.06.15-1

**ERROR**

`SEARCHQUEUE-BACKLOG-110381 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)`


I too am experiencing the same issue.  Details listed above.

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/b86a29b3c28b9428b775a1f2286d10af
### ERROR
```
SEARCHQUEUE-BACKLOG-347953 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/af3fa74fc04e200280bd9e9b2efee65d
### ERROR
```
SEARCHQUEUE-BACKLOG-269653 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/7be34f869ae20f06fe8741639e8b68c4
### ERROR
```
SEARCHQUEUE-BACKLOG-239851 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/bf70ceeeb763b3fde0650eedee978a62
### ERROR
```
SEARCHQUEUE-BACKLOG-72885 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/8d3023d9f467cb4271a4b64e608e2dab
### ERROR
```
SEARCHQUEUE-BACKLOG-77398 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/dc2ba2bf91f43ff1b4bc447b3e04cb7a
### ERROR
```
SEARCHQUEUE-BACKLOG-262754 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/3c9d4eaed9e348320e640b12acfe51c8
### ERROR
```
SEARCHQUEUE-BACKLOG-81751 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/4ce0ea52a24e0391fc3cd9ed7334a13d
### ERROR
```
SEARCHQUEUE-BACKLOG-85249 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/9e049ce63ef2dcbb7635bd4e11d6ac45
### ERROR
```
SEARCHQUEUE-BACKLOG-279659 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/69414bd26c7681abcab13c55d27d266e
### ERROR
```
SEARCHQUEUE-BACKLOG-302938 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/eeaa451408e764d55f3b7ee8dc9549af
### ERROR
```
SEARCHQUEUE-BACKLOG-270408 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/ab54a6b3fe1745313bc8cffe65b2ffa3
### ERROR
```
SEARCHQUEUE-BACKLOG-270633 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/61268c105826250d952263acd4ca906e
### ERROR
```
SEARCHQUEUE-BACKLOG-78901 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by proctophage** [comment]
### INFO
Python Version: **2.7.10 (default, Nov 16 2015, 02:48:48) [GCC 4.9.3]**
Operating System: **Linux-3.10.75-84-armv7l-with-debian-jessie-sid**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
Link to Log: https://gist.github.com/c510d4a056c90b40665d0698fd1b08be
### ERROR
```
SEARCHQUEUE-BACKLOG-260449 :: [SceneTime] :: [807c5ae] Exception while searching SceneTime. Error: AttributeError("'NoneType' object has no attribute 'findAll'",)
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
