### ISSUE TITLE
Search Providers Page not Working

### ISSUE THREAD

**Issue by fidofido300** [SickChill/SickChill#4794]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

SickRage Info:
Branch: master
Commit: 807c5ae37ecd5af7483f06459c94788ee9db483d
Version: v2018.06.15-1
Database Version: 44.0
  Python Version: 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
  SSL Version: OpenSSL 1.0.2a 19 Mar 2015
  OS: Windows-7-6.1.7601-SP1
  Locale: en_GB.cp1252

Browser:Chrome
What you did:
Try To access Search providers Page
What happened:
Mako Error with the Following Error

File C:/SickRage/SickRage/gui/slick/views/config_providers.mako:183, in render_pages:
${('', 'checked="checked"')[curNewznabProvider.enable_daily]}

TypeError: tuple indices must be integers, not unicode

What you expected:
Page To be working :)

Logs:
```
PASTE LOGS HERE
```

**Comment by boredsysadmin** [comment]
same issue as https://github.com/SickRage/SickRage/issues/4817

**Comment by ravensorb** [comment]
is this a duplicate of #4721
