### ISSUE TITLE
Constant errors from Tornado/SSL module

### ISSUE THREAD

**Issue by zhimsel** [SickChill/SickChill#4796]
Branch/Commit: master, 807c5ae37ecd5af7483f06459c94788ee9db483d
OS: Archlinux
Browser: N/A
What you did: Use Sickrage normally
Logs:
```
2018-06-20 14:07:42 ERROR    Exception in callback None
Traceback (most recent call last):
  File "/opt/sickrage/lib/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/opt/sickrage/lib/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/sickrage/lib/tornado/iostream.py", line 519, in _handle_events
    self._handle_read()
  File "/opt/sickrage/lib/tornado/iostream.py", line 1390, in _handle_read
    self._do_ssl_handshake()
  File "/opt/sickrage/lib/tornado/iostream.py", line 1310, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error
```

I've been getting a constant stream of exceptions from the `ssl` module (via Sickrage's included `tornado` module) for as long as I've been running Sickrage.

Versions of some possibly related pip packages:
```
cryptography==2.2.2
pycrypto==2.6.1
pyOpenSSL==18.0.0
requests==2.18.4
urllib3==1.23
```

Python Version: 2.7.15 (default, May 1 2018, 20:16:04) [GCC 7.3.1 20180406]
SSL Version: OpenSSL 1.1.0h 27 Mar 2018

**Comment by meyersbs** [comment]
In my experience, Tornado constantly throwing errors is expected behavior, regardless of the application using it. It's an incredibly difficult library to work with, and it's poorly documented. Obviously I don't speak for the SickRage developers, but I wouldn't count on those errors going away any time soon.

**Comment by zhimsel** [comment]
Hm. I wonder if there's a way to silence those errors, at least. Maybe whatever call Sickrage uses to it can catch any Exceptions and either:
- produce a neat error
- ignore it

Obviously, this can/should be configurable.

**Comment by Itsmmai** [comment]
Since a couple of days (maybe 2 weeks or so) I've the same.. very annoying.

**Comment by WebSpider** [comment]
This would most likely be from a webbrowser trying an ssl version that tornado doesn't support. Think very recent clients trying TLS1.3, or very old clients trying something unsupported.

**Comment by Itsmmai** [comment]
ok, thank you WebSpider, but how can I change it then. I just use a browser to connect.

**Comment by Itsmmai** [comment]
But it still occurs ?

**Comment by WebSpider** [comment]
Try forcing your browser to use TLS1.2. How to do this, depends on the browser you use.
