### ISSUE TITLE
Add Existing Shows does not use predetermined path

### ISSUE THREAD

**Issue by Scythe42** [SickChill/SickChill#4799]
Branch/Commit: 807c5ae37ecd5af7483f06459c94788ee9db483d

When you try to add an existing show, the name of the show you select from the indexer gets added the the predetermined path. This is also visible in the WebUI at the bottom. As a result the show will not be added as the path cannot be found as it doesn't exist. Sickrage should use the predertermined path and not alter it when adding an existing show. This defect came up recently and was not present the last time I added an existing show, which was at the end of 2017.

**Comment by below9k** [comment]
I've seen this bug, but it doesn't affect the actual path. The name is appended to the end only in the UI. If you're seeing this on actual folders perhaps it's file system dependent or you're not on master.
