### ISSUE TITLE
Update Wiki: (Launch Sickrage On Boot & Via App) [macOS]

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SickChill/SickChill#4801]
@neoatomic @miigotu

[SickRage LaunchAgent macOS [Runs On Boot]](https://gist.github.com/XxUnkn0wnxX/9f260a476472b9cb43afecc30f0c2a93)

I've made a more effective way or running SR & I've been using this for a long time.
I use the built in launchd on macOS to Daemonize SR.

I would highly recommend the [Wiki](https://github.com/SickRage/SickRage/wiki/Installation-&-Configuration-Guides#mac) to be updated with new ver of method - Simpler to setup & use. [More permanent & probably wont change.]

**Comment by WebSpider** [comment]
Feel free to PR the wiki with changes!
