### ISSUE TITLE
In light of recent broken builds, can we please get an easy "revert" button to revert to a prior build, maybe under Changelog pulldown?

### ISSUE THREAD

**Issue by ctrlbrk42** [SickChill/SickChill#4802]
Hi guys,

In light of the recent problem with the broken builds (no SAB shows being processed since June 15 build), it would be really great if you added a GUI button to help us "revert" the build to a prior build, like maybe in the Changelog section.

I would love to revert to a working build, but I don't know how on my Synology server running SickRage.  It's a bit complicated with that install, so a GUI option would be super welcome.

**Comment by HPMSGEN8** [comment]
@ctrlbrk42 

I have a Synology and my shows are getting process with the nzbtomedia scripts.

**Comment by Fiat2LTC** [comment]
Fixed the postprocess issue in: https://github.com/SickRage/SickRage/pull/4803
