### ISSUE TITLE
Search Providers page Blank/Not Working

### ISSUE THREAD

**Issue by notna314** [SickChill/SickChill#4806]
Branch: master
Commit: 807c5ae37ecd5af7483f06459c94788ee9db483d
Version: v2018.06.15-1
Database Version: 44.0
Python Version: 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
SSL Version: OpenSSL 1.0.2g 1 Mar 2016
OS: Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
Browser: Chrome & Safari
What you did: Fresh/New install, opened up SickRage
What happened: gave me a warning "No NZB/Torrent providers found or enabled for daily searches and backlog searches.
Please check your settings."
Went to settings, to set-up some providers, however the Search Providers page doesn't show any.
What you expected:  Expected to see a list of Providers that I could configure
Logs(enabled DEBUG / nothing out of the ordinary:
```
2018-06-30 11:44:56 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2018-06-30 11:44:56 INFO SEARCHQUEUE-DAILY-SEARCH :: No episodes needed.
2018-06-30 11:44:56 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2018-06-30 11:44:51 INFO DAILYSEARCHER :: No new released episodes found ...
2018-06-30 11:44:51 INFO DAILYSEARCHER :: Searching for new released episodes ...
2018-06-30 11:38:52 INFO ThreadPoolExecutor-0_3 :: No update needed
2018-06-30 11:38:51 INFO ThreadPoolExecutor-0_3 :: Checking for updates using GIT
2018-06-30 11:34:51 INFO CHECKVERSION :: Checking for updates using GIT
2018-06-30 11:34:50 INFO TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2018-06-30 11:34:50 INFO MAIN :: Starting SickRage [master] using '/opt/sickrage/config.ini'
```

**Comment by Zensai89** [comment]
Exactly the same here. 

Running via Entware on a Zyxel NAS 542

SickRage Configuration
SickRage Info:
Branch: master
Commit: 0e727649748ec38c5bba69f3f97c9e7b794d56df
Version: v2018.07.21-1
Database Version: 44.0
  Python Version: 2.7.15 (default, May 12 2018, 06:33:51) [GCC 7.3.0]
  SSL Version: OpenSSL 1.0.2o 27 Mar 2018
  OS: Linux-3.2.54-armv7l-with-glibc2.4

Logs: https://pastebin.com/rdNs9wSi

Steps used for entware: https://github.com/Entware/Entware/wiki/Install-on-Zyxel-NAS542
Steps used for CP, SickRage, NZBGet: http://forum.nas-central.org/viewtopic.php?f=249&t=18383

**Comment by SPDurkee** [comment]
Same issue. Brand new install. 
[sickrage.log](https://github.com/SickRage/SickRage/files/2264470/sickrage.log)

Branch: master
Commit: 0e727649748ec38c5bba69f3f97c9e7b794d56df
Version: v2018.07.21-1
Database Version: 44.0
Python Version: 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
SSL Version: OpenSSL 1.1.0f 25 May 2017
OS: Linux-4.16.14-feral-x86_64-with-debian-9.4

![screenshot](https://user-images.githubusercontent.com/2486134/43746327-ab5eb768-99b1-11e8-8569-e10167d1200f.jpg)

**Comment by SPDurkee** [comment]
Tried 2018.03.25-2 and it works correctly, so the issue must be sometime after that version.
If I manually edit the config.ini file and enable a provider, the list of providers will appear correctly.

**Comment by mszczepanczyk** [comment]
Stumbled upon this thread while looking for a solution. It seems you need to enable torrent/nzb providers first:

![image](https://user-images.githubusercontent.com/286129/54641556-c0b0be80-4a92-11e9-9067-48999228c993.png)
