### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/344714/de.xml

### ISSUE THREAD

**Issue by hawkeye73** [SickChill/SickChill#4808]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [807c5ae] Unable to connect to theTVDB while creating meta files - skipping - error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/344714/de.xml
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by hawkeye73** [comment]
Can I do something so the error will not appear anymore? I can't find which series this is otherwise I could maybe manually edit and correct this.

**Comment by WebSpider** [comment]
In some way a series got into your series database with an invalid tvdb id. 
If you have a sqlite3 client, open up your .db file (when sickchill is not running!) and look for the indexer ID.

A query such as this should get you the offending series:

```sql
SELECT *
FROM tv_shows
WHERE indexer_id = '344714'```
