### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_0 :: [807c5ae] Unable to create the folder /volume1/TV Shows/Shooter, can't add the show

### ISSUE THREAD

**Issue by amagill79** [SickChill/SickChill#4824]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:12) [GCC 4.6.4]**
Operating System: **Linux-2.6.32.12-armv5tel-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [807c5ae] Unable to create the folder /volume1/TV Shows/Shooter, can't add the show
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
SickChill cannot access the required directory. Make sure parent dirs exist, and SickChill has sufficient permissions
