### ISSUE TITLE
Status of episode not being updated correctly by post processor

### ISSUE THREAD

**Issue by jrucker2004** [SickChill/SickChill#4828]
Branch/Commit: master v2018.06.15-1
OS: Server: FreeNas jail, client: Windows
Browser: Chrome
What you did: Downloaded two versions of the same episode
What happened: The status of the episode wasn't updated correctly
What you expected: The status of the episode should reflect what was actually downloaded.

Steps to reproduce:
1.  Add a show, and set an episode to "Wanted"
2.  Let SickRage snatch an HD version of that episode
3.  Outside of SickRage, pause or cancel the download of that HD version
4.  Manually download an SD version of the same episode, and place it in the directory being processed by SickRage's post processor
5.  Let SickRage process the SD version
6.  See that the status of the episode is listed in SickRage as "Downloaded HD" when it should be "Downloaded SD"

The post processor should update the status of episode with the correct information, and not just assume that the previous status should be trusted.

**Comment by miigotu** [comment]
Next time, mark the episode as failed in SC before you trick it into processing a file.
