### ISSUE TITLE
Unknown current version number

### ISSUE THREAD

**Issue by raitono** [SickChill/SickChill#4832]
Branch/Commit: 272348118e78057cb230138aa09c82452b9e0ef3
OS: FreeBSD-11.0-RELEASE-amd64-64bit-ELF (Running FreeNAS 11 Plugin)
Browser: Chrome 67.0.3396.99 64 bit
What you did: Update to latest commit
What happened: Updated to latest commit, but now I receive this message:

> Unknown current version number: If you've never used the SickRage upgrade system before then current version is not set. — Update Now

What you expected: Not receiving the above message
Logs: Not really a way to reproduce it unless I downgrade somehow. When I click the Update Now button in the message, this is what I get:
```
2018-07-20 14:15:45 DEBUG ThreadPoolExecutor-0_2 :: cur_commit = 272348118e78057cb230138aa09c82452b9e0ef3, newest_commit = 272348118e78057cb230138aa09c82452b9e0ef3, num_commits_behind = 0
```

**Comment by WebSpider** [comment]
Is happens when you cannot contact github right after updating, and should disappear once the version checker has ran, by default once every 12h

**Comment by ronrosenfeld** [comment]
I am having the same problem since the last update dtd around 28 jun 2019
   Branch: master 
   Commit: 1ed315660d99f6673a3bb53363fdff6902b89429 

and the version checker has successfully run several times since then.
