### ISSUE TITLE
[APP SUBMITTED]: Hell on Wheels is already queued to be removed

### ISSUE THREAD

**Issue by furafollas** [SickChill/SickChill#4851]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **develop**
Commit: SickRage/SickRage@06aeb2f24994df9b4e3f32adeda5b32f405d36ed
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [06aeb2f] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/sickbeard/webserve.py", line 3617, in massUpdate
    sickbeard.showQueueScheduler.action.remove_show(show_obj)
  File "/volume1/@appstore/sickrage/var/sickbeard/show_queue.py", line 178, in remove_show
    raise CantRemoveShowException('{0} is already queued to be removed'.format(show.name))
CantRemoveShowException: Hell on Wheels is already queued to be removed

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
This happens when a show is being deleted, but SickChill hasn't gotten around to it yet, because it was busy doing other, more important, stuff, such as sending more snatches :)
