### ISSUE TITLE
[APP SUBMITTED]: Frequency is already queued to be removed

### ISSUE THREAD

**Issue by furafollas** [SickChill/SickChill#4852]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **develop**
Commit: SickRage/SickRage@06aeb2f24994df9b4e3f32adeda5b32f405d36ed
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [06aeb2f] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/sickbeard/webserve.py", line 3617, in massUpdate
    sickbeard.showQueueScheduler.action.remove_show(show_obj)
  File "/volume1/@appstore/sickrage/var/sickbeard/show_queue.py", line 178, in remove_show
    raise CantRemoveShowException('{0} is already queued to be removed'.format(show.name))
CantRemoveShowException: Frequency is already queued to be removed

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by prantzos** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/ed534d3afa731af8b55eeffa3d28d7bd
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] 
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
This happens when you are deleting a show, but SickChill hasn't gotten around to actually removing it (for instance because it is post-processing and searching a lot of items at the same time)
