### ISSUE TITLE
Schedule - Netflix Shows

### ISSUE THREAD

**Issue by RodriguesGabriel** [SickChill/SickChill#4859]
Since Netflix shows' episodes are released at the same time, schedule list always gets very long. Maybe it would be better if Netflix shows' episodes were announced only as one (maybe the first one or smt)

**Comment by shawnhicks** [comment]
Many shows distributed through non-traditional services (cable/satellite) allow access to an entire season of a series at the same time (not only Netflix). SickRage gets a shows's metadata from thetvdb.com which requires people (unafilliated with SickRage) to enter the schedule. The volunteers that manage the data on thetvdb.com aim for the most accurate information about a show's air dates.  The issue you present sounds like a convenient aesthetic that would cause more confusion than it would be worth. Please consider the complication surrounding even a "double time-slot episode" or two episodes aired back to back. How would you propose identifying a qualifying simplification of the schedule? Is it when greater than two episodes air on the same date, or three, or four? How should a marathon be presented?

**Comment by RodriguesGabriel** [comment]
Yeah it's pure aesthetics. Maybe when more than idk 2 or 3 episodes premiere at the same time (maybe even day), a dropdown is presented.
