### ISSUE TITLE
Feature request: Add mirror url text field for torrent providers

### ISSUE THREAD

**Issue by Pauligrinder** [SickChill/SickChill#4861]
I noticed a while ago that my ISP had blocked rarbg, and therefore SickRage was constantly complaining about not being able to connect. I got around it by modifiying sickbeard/providers/rarbg.py with the url to a rarbg-mirror that isn't blocked, then removed the .pyc -file and restarted SickRage. 

That got me thinking - couldn't all providers have custom url fields for these cases? At least in the case of rarbg, adding a custom provider for it didn't work (it doesn't find the torrent link from the RSS element, I'm guessing because the link on those links to torrent details instead of the actual torrent/magnet).

**Comment by JoshuaArus** [comment]
Another thought : most ISP only block DNS resolution.

So if you add an entry in your windows hosts file (rarbg' IP should not change often), or change your network DNS server (like openDNS), maybe you could avoid this kind of troubles ?

**Comment by Pauligrinder** [comment]
I guess that's a better idea, I guess I might do that...
