### ISSUE TITLE
How to work post process with networked storage drives?

### ISSUE THREAD

**Issue by Drigoo** [SickChill/SickChill#4864]
Hello people,

I have a problem: I have Sickrage installed on a Raspberry Pi with Raspbian, but my storage unit is on router (Xiaomi Mi Router 3, firmware Padavan, storage plugged into the usb).
The downloaod is done by the Transmission of the router.
What happened is that I can not make the post process work, even with the storage drive being mapped and mounted on Raspbian, I tried several paths and I could not.

Some information:

- My transmission downloads go to //192.168.1.1/media/files/Downloads (I select downloads to default folder in sickrage, leaving the place unfilled)

- in raspbian, I mounted the storage unit of the HD in the network smb server by this way: / mnt / HD / HD / ... this way, I can see all the folders in the network by sickrage.

Does anyone use something similar so can you help me?
*excuse me,  my english is bad.

[img] https://i.imgur.com/1lt0BKY.png [/ img]

**Comment by WebSpider** [comment]
Can you provide postprocessor debug logs?
