### ISSUE TITLE
Sickrage does not recognise mapped drive

### ISSUE THREAD

**Issue by sleggate** [SickChill/SickChill#4866]
Hi,

I'm new to all this so wonder if I could get some help please.  Someone set up my HTPC running Win10 Home with Kodi, SAB NZB, Sickrage, CP.  I had an external HDD attached via USB on my HTPC which contained all my media, this was mapped as follows:
Show root directories: D:\Videos\TV Series
Post Processing Dir: D:\Downloads\complete

I decided to purchase a WD MyCloud NAS and attached the external HDD into the USB port on the back of it.  I disconnected the old D:\ mapping on the HTPC and mapped the D:\ to the new UNC location for the HDD, so it is mapped exactly the same as previously
Show root directories: D:\Videos\TV Series
Post Processing Dir: D:\Downloads\complete

I can access the D:\ fine on the HTPC, SAB NZB can see it and can download to it, but Sickrage can no longer see my D:\ and therefore cannot do any post processing.

I read somewhere that this maybe a permissions thing, so I created an admin account called sickrage and assigned this to the sickrage service in windows, but still no joy.  I've also tried eidting the config.ini with the full UNC address but no joy either.  Please help, I'm not very technical, so out of ideas.

Thanks in advance.....

SickRage Configuration
  SickRage Info:
Branch: master
Commit: 0e727649748ec38c5bba69f3f97c9e7b794d56df
Version: v2018.07.21-1
Database Version: 44.0
  Python Version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
  SSL Version: OpenSSL 1.0.2j 26 Sep 2016
  OS: Windows-10-10.0.17134
  Locale: en_GB.cp1252

  User: Sickrage
  Program Folder: C:\SickRage\SickRage
  Config File: C:\SickRage\Data\config.ini
  Database File: C:\SickRage\Data\sickbeard.db
  Cache Folder: C:\SickRage\Data\cache
  Log Folder: C:\SickRage\Data\Logs
  Arguments: ['--nolaunch', '--port=8081', '--datadir=C:\\SickRage\\Data']
```

**Comment by shawnhicks** [comment]
Did you use the hostname/computername or "." in the unc path example \\.\share ? The "." denotes the current computer irrespective of naming, it eliminates name resolution issues.
