### ISSUE TITLE
Emby update

### ISSUE THREAD

**Issue by battamo** [SickChill/SickChill#4867]
It would be great if there was a setting for sickrage to auto update Emby during post processing.

**Comment by mgaulton** [comment]
Just curious, if you look under notifications, it has Emby with the option "send updates to emby".
I might be wrong, but that implied to me that SB will do what you're asking for already.

**Comment by WebSpider** [comment]
@battamo there is an emby section in notifications. If this does not do what you need, please open a new issue explaining in more detail.
