### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/volume1/Media/shared/Animes/TV Shows/Gantz/Season 01/Gantz - S01E10 - Yuuzou-kun - SD_DVD.en.srt'

### ISSUE THREAD

**Issue by janusn** [SickChill/SickChill#4892]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/d71b947d8d7cc037be9aa8766ffd36c0
### ERROR
```
FINDSUBTITLES :: [0e72764] Unable to find subtitles for Gantz S01E10. Error: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/db6b4a2fa813290d3d786cf96a4932ed
### ERROR
```
FINDSUBTITLES :: [0e72764] Unable to find subtitles for Gantz S01E10. Error: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/8fc80d4e31b68debe51983c62c19ac62
### ERROR
```
FINDSUBTITLES :: [0e72764] Unable to find subtitles for Gantz S01E10. Error: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by BenjV** [comment]
Why are you spamming this issue tracker with all this issue's don't you see you messing up the issue system or are you a deliberate spammer?

**Comment by janusn** [comment]
Dear BenjV,

Maybe it was sent alone with other errors on the SickRage error log pages
when I hit the submit button. I have should have fixed that myself.

Sorry for the annoyance caused.  Is there a way to submit a single error
from the error log page? Or I have to submit by logging into the github
directly in order to do so?

Cheers,
Janus

**Comment by janusn** [comment]
Dear BenjV,

Sorry about the spamming. I was just hitting the "Submit Errors" button on
the Error page of SickRage as illustrated in the attachment. I will submit
to the github individually instead.

Cheers,
Janus

[image: Screen Shot 2018-08-22 at 10.03.16 PM.png]

**Comment by janusn** [comment]
Dear BenjV,

I have installed from
https://github.com/BenjV/SYNO-packages/raw/master/SickRage%20DSM%206%20noarch%20V1.0.spk

Which I found on this page as ready made for DSM6:
https://github.com/SickRage/Sickrage/wiki/Sickrage-installation-packages

Cheers,
Janus

**Comment by BenjV** [comment]
Ok that's is correct.
But I am still confused about the submit button, because I don't have such a button.

Besides that, if that button submit all occurrences of an error then it is a very bad idea to use it.
