### ISSUE TITLE
Failed downloads keep status "Snatched"

### ISSUE THREAD

**Issue by heula** [SickChill/SickChill#4912]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:Branch: master
Commit: 0e727649748ec38c5bba69f3f97c9e7b794d56df
Database Version: 44.0
OS: Synology DS418 NAS 
Browser:-
What you did:
What happened:
What you expected:

```
When episodes are set to snatched and the download fails within SAbnzbd the status of the episode is not set back to wanted. The status stays at snatched.

When I set episodes to skipped or ignored so they will not be downloaded anymore, the next day the status of those episode is set bak to whatever it was and are being picked up again. I set those episodes manually to skipped or ignored because there are no better versions available anymore for example.

What can I do to get the status set back to wanted when downloads have failed.
And why is my manually set status to ignored or skipped being ignored by Sickrage.?

Thanks

[Sickrage.log](https://github.com/SickRage/SickRage/files/2289850/Sickrage.log)

**Comment by WebSpider** [comment]
We do not have reporting from sabnzbd back to sickrage. What you can do is set the episode status to 'FAILED' by hand, and it will try to snatch a different source.
