### ISSUE TITLE
SickRage Kills Its Self After Time

### ISSUE THREAD

**Issue by HPMSGEN8** [SickChill/SickChill#4916]
Hi Team

Please see the below. This has happened more then once and starting to be an issue as everything hangs.

Branch/Commit: master / 0e727649748ec38c5bba69f3f97c9e7b794d56df
OS: Synology
Browser: Chrome 68.0.3440.84 (Official Build) (64-bit) (cohort: 68_84_win)
What you did: SickRage Was Running
What happened: SickRage Died
What you expected: SicKRage To Not Die
Logs:
```
Cannot Find Anything In Debug Logs

```
https://imgur.com/a/vItQEFL

I need to do a Full Shutdown via the App Manager and start again. Restarting SickRage does not fix this

Thanks

**Comment by WebSpider** [comment]
Is this still happening?
