### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: [0e72764] git config remote.origin.url https://github.com/SickRage/SickRage.git returned code -11, treating as error : None

### ISSUE THREAD

**Issue by Impulse1337** [SickChill/SickChill#4928]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-4.14.49-unRAID-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/f2ebe89b0697ca926571ff0e70216531
### ERROR
```
CHECKVERSION :: [0e72764] git config remote.origin.url https://github.com/SickRage/SickRage.git returned code -11, treating as error : None
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
CHECKVERSION :: [0e72764] git config remote.origin.url https://github.com/SickRage/SickRage.git returned code -11, treating as error : None
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
Please make sure you use the new URL, https://github.com/SickChill/SickChill.git
