### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/downloads/uTorrent/Ready/Doctor.Who.2005.S05E07.1080p.BluRay.x264-BiA-Scrambled/0a7f32299394439784bd5f80f954bdf9.mkv'

### ISSUE THREAD

**Issue by Impulse1337** [SickChill/SickChill#4929]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-4.14.49-unRAID-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/77ccff8d03bd219c88a7136a17fee6fc
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] [Errno 2] No such file or directory: '/downloads/uTorrent/Ready/Doctor.Who.2005.S05E07.1080p.BluRay.x264-BiA-Scrambled/0a7f32299394439784bd5f80f954bdf9.mkv'
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Impulse1337** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-4.14.49-unRAID-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
Link to Log: https://gist.github.com/9d1541603e3de256c0a05ca5d6028193
### ERROR
```
POSTPROCESSOR-AUTO :: [0e72764] Unable to move file /downloads/uTorrent/Ready/Doctor.Who.2005.S05E07.1080p.BluRay.x264-BiA-Scrambled/0a7f32299394439784bd5f80f954bdf9.mkv to /tv/Doctor Who (2005)/Season 05/Doctor Who (2005) - S05E07 - Amy's Choice.mkv: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
Please explain what you did which led to this error?

**Comment by Impulse1337** [comment]
Honestly, i do not know what actually happened here.. this is an error from 4 months ago. I fixed the issue by deleting it and redownloading the files.

**Comment by WebSpider** [comment]
Yeah, I'm going through old issues to clean them up a bit. Glad you solved it!
