### ISSUE TITLE
Unknown current version number, Upgrade as suggested failed

### ISSUE THREAD

**Issue by janusn** [SickChill/SickChill#4932]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/0e727649748ec38c5bba69f3f97c9e7b794d56df
OS: DSM 6.2-23739 Update 2
Browser: Chrome on Mac Version 68.0.3440.106 (Official Build) (64-bit)
What you did: Click on the Update Now link on the SickRage page as shown below
<img width="648" alt="screen shot 2018-08-28 at 4 23 50 pm" src="https://user-images.githubusercontent.com/21253783/44711181-56c5cd00-aae0-11e8-9823-639f1ebd2796.png">

What happened: update failed as show below
<img width="648" alt="screen shot 2018-08-28 at 4 28 03 pm" src="https://user-images.githubusercontent.com/21253783/44711225-6e9d5100-aae0-11e8-8355-da1e83c70241.png">

Nothing is shown on the log of the WebUI
<img width="648" alt="screen shot 2018-08-28 at 4 30 30 pm" src="https://user-images.githubusercontent.com/21253783/44711268-8bd21f80-aae0-11e8-9fbe-e86af247917d.png">

What you expected: Update successfully with version listed.

Logs:
```
2018-08-28 16:10:03 INFO ThreadPoolExecutor-0_3 :: Config backup successful, updating...
2018-08-28 16:09:50 INFO ThreadPoolExecutor-0_3 :: Config backup in progress...
```

**Comment by WebSpider** [comment]
Please retry with a more current release of SickChill, thank you!
