### ISSUE TITLE
Error on mail notifications

### ISSUE THREAD

**Issue by NilsNojje** [SickChill/SickChill#4943]
Branch/Commit: Master/0e727649748ec38c5bba69f3f97c9e7b794d56df
OS: Ubuntu 18.04 amd64
Browser: Chrome
What you did: Tested mail notification / saved and tested again
What happened: Success in sending / ERROR: (535, '5.7.8 Authentication failed')
What you expected: Success
Logs:
```
2018-09-05 20:22:25 DEBUG ThreadPoolExecutor-0_0 :: Sending LOGIN command!
2018-09-05 20:22:25 DEBUG ThreadPoolExecutor-0_0 :: Sending STARTTLS command!
2018-09-05 20:22:25 DEBUG ThreadPoolExecutor-0_0 :: Sending initial EHLO command!
2018-09-05 20:22:24 DEBUG ThreadPoolExecutor-0_0 :: HOST: xxxx.yyyy.zz; PORT: 587; FROM: *****************, TLS: 1, USER: *****************, PWD: hidden_value, TO: ['xxxx@gmail.com']
```

Entering the values for email notification, server, port, user etc ... and then test manual works.
But when saving and leaving the page to return later and test without changing any values, result in an AUTH error. (shown above).

I tested with a temporary mail user and a simple password (alfa chars only) but that didn't work either and the correct password is actually shown in the config.ini file.

**Comment by J-Hutt** [comment]
Confirmed this bug

**Comment by WebSpider** [comment]
What mailserver are you using to send mail through?

**Comment by J-Hutt** [comment]
I tried gmail using an app password. Also using my ISP email server. Both times, works first time, then when I navigate away from the page and back, it fails.

**Comment by J-Hutt** [comment]
So specifically smtp.gmail.com. Also smtp.telstra.com

**Comment by J-Hutt** [comment]
Actually I see now that (for me anyway) its only the email test that is failing (after the first attempt succeeds, navigate away and back, then try again).

The actual notifications per show get sent ok.
