### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-71814 :: [ilCorsaroNero] :: [51328d1] Could not find table of torrents

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#4971]
### INFO
Python Version: **2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-71814 :: [ilCorsaroNero] :: [51328d1] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MACE-Zer0** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-3.10.105-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [ilCorsaroNero] :: [51328d1] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MACE-Zer0** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-3.10.105-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-263365 :: [ilCorsaroNero] :: [51328d1] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MACE-Zer0** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-3.10.105-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@51328d1fb61ebc9704934e3cf14425453196790d
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-79545 :: [ilCorsaroNero] :: [51328d1] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
This would seem to be a temporary problem with the site being unavailable
