### ISSUE TITLE
Enhancement; Option to "touch" the show folder during post processing

### ISSUE THREAD

**Issue by lakeman** [SickChill/SickChill#4973]
In a large library, if the modified timestamp of a show folder was updated every time a new episode was added, this would allow users to identify new content quickly using their favourite file browser.

**Comment by mgaulton** [comment]
I actually wrote a batch script to do something like this. It marks metafiles as super old (windows doesn't even show the timestamps) and sets the mtime on the folder to the most recent media file. Which is dated as air date. Not fast, but it runs low pri in the background periodically.
I like your idea though. Mine gets munged when the oldest file is really old lol
