### ISSUE TITLE
Can't find episodes on HorribleSubs for anime

### ISSUE THREAD

**Issue by WiseMMO** [SickChill/SickChill#4974]
Branch/Commit: master / 51328d1fb61ebc9704934e3cf14425453196790d
OS: Windows 10
Browser: Opera
What you did: Searched for episode of My Hero Academia
What happened: Did not find the episode
What you expected: To find the episode on HorribleSubs at least, considering it's there and available
Logs: There is no error or apparent help on the logs, it just says it was unable to find episodes on all anime trackers.

![opera_2018-09-28_15-10-09](https://user-images.githubusercontent.com/33370380/46210299-9b879280-c330-11e8-88c0-333975e55a3c.png)

Is HorribleSubs still supported?

**Comment by WiseMMO** [comment]
![opera_2018-09-28_15-11-37](https://user-images.githubusercontent.com/33370380/46210363-cf62b800-c330-11e8-8519-f7701a0e805d.png)

**Comment by VietTPham** [comment]
Horriblesubs works for me. I found that it has problem getting certain shows from it. This show is one of the one it has problems with.

```2018-10-09 04:36:25 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HorribleSubs] :: Found result: [HorribleSubs] some show here```

**Comment by spudsrus** [comment]
I have also had problems with it, does it work for shows without scene names? both of the shows that didn't work for me used scene names.

**Comment by Trical** [comment]
I seem to have the same issue.

**Comment by chronicrebellion** [comment]
It appears that the search is only trying the scene exceptions for the Season only.
In the case of My Hero Academia, Season 4 exceptions do not contain "Boku no Hero Academia" although the show exception does have it.

As a work around you can add the correct japanese title for season and it should start working

**Comment by spudsrus** [comment]
The workaround chronicrebellion suggested worked for me.

**Comment by miigotu** [comment]
Sounds like a bug. I'll see if I can find a fix.

**Comment by miigotu** [comment]
![image](https://user-images.githubusercontent.com/390379/72775279-bf34b300-3bdb-11ea-91d5-82d724e72ee3.png)
