### ISSUE TITLE
[Feature request] Add possibility to add commands to run when episodes are aired

### ISSUE THREAD

**Issue by Pauligrinder** [SickChill/SickChill#4979]
Hey! I had this idea, that it would be great to be able to set commands to download episodes when they are aired, instead of triggering torrent/usenet searches for shows that never get uploaded to those. For example, I'm watching a couple of shows on Yle Areena and now I have to manually download the episodes using yle-dl - that could be automated quite easily.

**Comment by WebSpider** [comment]
You may want to have a look at https://github.com/SickChill/SickChill/wiki/NZBtoMedia
