### ISSUE TITLE
Possible hacking from Sickrage.ca

### ISSUE THREAD

**Issue by Issam2204** [SickChill/SickChill#5020]
Drammatic title, but your website downloads (and ready installers) redirects to https://github.com/SickRage/SickRage.

Moreover, using the following command (which I always used successfully) downloads their repo instead of this one:

`git clone https://github.com/SickRage/SickRage.git`

Is this normal?

**Comment by WebSpider** [comment]
Please see #4984

**Comment by AubreyKloppers** [comment]
WTF - I just switched to Medusa to get myself (3 cliets) out of this mess!  This is the second time and I refuse to get bunt again!

**Comment by Eagllus** [comment]
Funny think to note.

Me and a few other have referenced to this Repo from git.sickrage.ca and the owner there was so kind to remove our posts. 😆

**Comment by miigotu** [comment]
@AubreyKloppers don't advertise. While we aren't necessarily actively competing, we avoid posting about each other's forks on the other's tracker (even though we share a few devs)

**Comment by vkbo** [comment]
It is very concerning that GitHub would allow someone to replace a repository like this. Especially one with this many forks and clones. I use GitHub a lot for work, and it didn't take me long to figure out what happened, but I'm surprised that this is even possible.

**Comment by miigotu** [comment]
Microsoft owns github now so.....

**Comment by vkbo** [comment]
Yeah, that was a sad day for open source.
