### ISSUE TITLE
Is SickChill (new repo) also hacked now? SickRage "S" logo showing in Wiki

### ISSUE THREAD

**Issue by SteveW25561** [SickChill/SickChill#5028]
I'm paranoid, but looking on this newly named SickChill/SickChill github page: https://github.com/SickChill/SickChill/wiki (on the Wiki Home link)

I see the echelon "S" logo, not the shark logo.  Is everything OK on this Repo now?

**Comment by rcross** [comment]
wondering myself... its also odd that there isn't much in the way of any annoucement on the websites about the new name.

**Comment by Arcanemagus** [comment]
"That" logo was introduced to the wiki back in 2005 [here](https://github.com/SickChill/SickChill/wiki/Home/f42d6f3ab0d39307ee96d192f04f00426e8eb1e0), so definitely not related to the current mess. It's likely just pointing to something that has since changed.

**Comment by rcross** [comment]
at this point, i'm feeling fairly confident this is the right repo/etc. Will just wait for more announcements and other levels of name-change adoption to take place.

**Comment by SteveW25561** [comment]
@arcanemagus thanks for the quick reply. Sorry for the noob question but is my install ok to be configured like that (pointing  to the head instead of the master branch)?  If not, how should I fix it?

I should mention I’m running this on my Synology via a docker image called linuxserver-sickrage

**Comment by phaseburn** [comment]
The icon in the wiki was a URL to the avatar of the SickRage org. It was hard coded into the Wiki, and when it was forked over here, the URL was never updated. Then echel0n updated the logo on the original user which changed the logo on our Wiki. I've corrected that. There's going to be a tremendous rebranding effort to catch those little details. But rest assured you're in the right place, and that there's no issues here.

**Comment by phaseburn** [comment]
@SteveW25561 I can't close this issue, but, I've at least resolved it. Can you please validate it yourself if you want, and close this out to keep things clean and tidy?

**Comment by Arcanemagus** [comment]
`HEAD` is just the git term for the current pointer to a commit of a branch. Again, from what you show there it is correct 😉.
