### ISSUE TITLE
Deluge 2.0 Support

### ISSUE THREAD

**Issue by iced** [SickChill/SickChill#5030]
Deluge 1.x can't do proper pre-alloc (only sparse) which leads to epic fragmentation, but 2.0 changed rpc api and can't be used from sick... ehm... chill.

**Comment by miigotu** [comment]
Link to api change?

**Comment by mgaulton** [comment]
Personal observation, I've been running 2.0dev since the 40ish build number  (up near 200 now) and its had no issues that i've noticed.

**Comment by iced** [comment]
Sorry, guys, I just fixed file alloc for deluge 1.x and forgot about the issue. Hopefully will get some time soon and provide more info about 2.x - for me it was unable to set labels and move dir.

**Comment by WebSpider** [comment]
Since the issue with 1.x has been resolved, this is now a FR to support 2.x

**Comment by nicoschl** [comment]
Any progress on support for deluge 2? 

I found these, hopefully it could help:
https://deluge.readthedocs.io/en/latest/reference/index.html
