### ISSUE TITLE
Cannot add existing shows with accented characters in title

### ISSUE THREAD

**Issue by bartolomesoriano** [SickChill/SickChill#5031]
Branch: master
Commit: 6d04e48280212de63227c7fb16145c3be9678dbe
Version: v2018.10.10-2
Database Version: 44.0
Python Version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
SSL Version: OpenSSL 1.0.2o 27 Mar 2018
OS: Windows-10-10.0.18252
What you did: Tried to add an existing show with accented characters in title (and folder name)
What happened: GUI showed folder name with garbled characters, could not add show
What you expected: show to be added

I did not attach a log in case this is just a configuration issue that you can tell me how to fix easily.  Examples of shows I tried to add (deleting the old nfo I had, and changing the search language to Spanish are Élite, Llámame Francisco, El Día de Mañana.

Please let me know what additional information is requried.  Thanks.

EDIT: The issue has somewhat self-corrected.  I tried again, and with one exception, I could add the shows.  For some of them, SickChill is trying to create directories with garbled characters for the show, but it adds the show.  I can then edit each show and point it to the correct directory, and SickChill will pick up all of my existing episodes.

Is this a locale problem or a code problem?

Here is a link to the log that hopefully shows the problems, including the one show I could not add, Sr. Ávila.  https://1drv.ms/u/s!AlII29kkG6TFiLJVwcAwWF5WxeoW1Q

**Comment by miigotu** [comment]
Its just titles on tvdb with windows characters that are not utf8, they all get fixed eventually
