### ISSUE TITLE
non-bitcoin donations

### ISSUE THREAD

**Issue by andreas-globi** [SickChill/SickChill#5032]
Why do you only accept donations via bitcoin? Many people don't have this. Can't you accept PayPal etc?

**Comment by herbi3** [comment]
Because echelon is has fraudulently stopped this. refer to https://github.com/SickChill/SickChill/issues/4984#issuecomment-429080381

**Comment by miigotu** [comment]
I think if you copy the url from here it might work lol, just make sure you get the full pp url
https://github.com/SickChill/SickChill/wiki/Donations/_compare/1d93844b86bd180d58d6bace4a9c85216238772c
