### ISSUE TITLE
sickchill.png file is missing

### ISSUE THREAD

**Issue by dieselVtwin** [SickChill/SickChill#5035]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master Latest commit 42048ad
OS: Windows 1-
Browser: MS Edge
What you did: Opened browser console (After reinstall due to Sick-Rage repo hijack event)
What happened: Console opened but with missing logo in top left corner
What you expected: Console to have logo in top left corner
Logs:
```
00:10:44 ERROR::Could not open static file u'C:\\SickRage-master\\gui\\slick\\images\\sickchill.png'
00:13:33 ERROR::Could not open static file u'C:\\SickRage-master\\gui\\slick\\images\\sickchill.png'```

Temporary workaround is to copy …\gui\slick\images\sickrage.png to …\gui\slick\images\sickchill.png

Cheers,
DVT

**Comment by Tiwas** [comment]
Thanks. The devs should make note of this and force the new image with a future update.
