### ISSUE TITLE
Error getting caps xml for

### ISSUE THREAD

**Issue by digrouz** [SickChill/SickChill#5036]
Hello,

I'm receiving this from time to time, is it something related to my config ?

```
2018-10-12 13:38:22 SEARCHQUEUE-DAILY-SEARCH :: [nzbid] :: Error getting caps xml for [nzbid]
2018-10-12 13:37:57 SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Error getting caps xml for [Usenet-Crawler]
```

**Comment by tchirou** [comment]
I do too
I think this is more related to usenet-crawler itself

**Comment by samnjugu** [comment]
The domain name being hit for api calls for usenet-crawler has changed. Sickchill is trying to get caps using https://api.usenet-crawler.com which results in an error you can manually update the url to https://usenet-crawler.com and api calls to usenet-crawler will work.
I tried to do a pull request for this but I ran into git auth errors so hopefully some one with a proper setup will update the domain name soon.

**Comment by miigotu** [comment]
Stop SR, and edit the url in your config.ini
I changed the default one in code, but you have to change your ini either way

**Comment by digrouz** [comment]
I guess the case for nzbid is because they are down ?

**Comment by miigotu** [comment]
If the site is offline of course you will get an error ...

**Comment by markdegrootnl** [comment]
> Stop SR, and edit the url in your config.ini
> I changed the default one in code, but you have to change your ini either way

Seems that it is still at api.usenet-crawler.com: https://github.com/SickChill/SickChill/blob/514d19f9d7e7b1731c40b9250eb9e3f9d0f362a2/sickbeard/providers/newznab.py#L207
