### ISSUE TITLE
Switch from Echel0n's SickRage to SickChill

### ISSUE THREAD

**Issue by krugster** [SickChill/SickChill#5037]
I was ignorant to all the goings on but have come across them now and wish to migrate to SickChill.

I did a fresh install but would like to import settings and DB if possible.  I tried a simple restore from backup which didn't get my anywhere, any suggestions?

**Comment by krugster** [comment]
config.ini is still there but it looks like the rest of the database structures have changed pretty significantly in the latest version

**Comment by krugster** [comment]
and the config version is too far ahead it seems

**Comment by Zabanya** [comment]
don't forget change git url, seems sick-rage.github.io needs to be changed too but not sure where

**Comment by Tiwas** [comment]
Did you change the git remote, as per https://github.com/SickChill/SickChill/issues/5022 ?

**Comment by miigotu** [comment]
You might have to restore an older database and config file unfortunately, since echelon forced users onto his code and changed their databases and config so they are not compatible with SickChill.
Closing this because Im trying to keep the issues with important info at the top of the tracker.
