### ISSUE TITLE
Getting a notifce for new version - comparison points to old site, some other errors after upgrading

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#5038]
Clicked the "new version" link to see changelog, but it points here: https://github.com/SickRage/SickRage/compare/6d04e48280212de63227c7fb16145c3be9678dbe...42048adc775140a99dbc348c6ea66b0d63643b7e

After upgrading, the logs are riddled with "AA **18-10-** 21:26:50 ERROR Could not open static file u'C:\\SickRage\\gui\\slick\\images\\sickchill.png'"

I also get this error: "AA **18-10-** 21:29:56 INFO ThreadPoolExecutor-0_1 :: Request failed: 404 Client Error: Not Found for url: http://sick-rage.github.io/sickchill-news/news.md"

I'm on commit 4**48adc775140a99dbc348c6ea66b0d63643b7e.

Checking the changelog from the menu presents this error: "The was a problem connecting to github, please refresh and try again"

I hope this has some value. Thanks for all the work you guys put in. You're awesome!

**Comment by jkervevan** [comment]
Hello,
For the static png file, Take a look at the issue [#5035](https://github.com/SickChill/SickChill/issues/5035).

**Comment by Tiwas** [comment]
> Hello,
> For the static png file, Take a look at the issue [#5035](https://github.com/SickChill/SickChill/issues/5035).

Thanks. Already did that, but the devs should make note of this workaround and force the new image out with a future update.

**Comment by miigotu** [comment]
If you knew how much work has gone into all of this rename, you would be patient.

Just update again, its already fixed.
