### ISSUE TITLE
Request Failed 404 Client Error

### ISSUE THREAD

**Issue by CAVACO-PT** [SickChill/SickChill#5041]
Hello , since the website changed , been getting this error on Sickchill , needs to be changed to the new one

![image](https://user-images.githubusercontent.com/9946471/46893177-01fbcd00-ce68-11e8-8c57-f5003429efc7.png)

**Comment by ronrosenfeld** [comment]
MACE-Zer0:  Can you please give a fuller path to INIT.py
I have a docker installation and there are a number of **___init___.py** files but I didn't find an **INIT.py**

**Comment by MACE-Zer0** [comment]
@ronrosenfeld   hope this helps , sorry forgot to put the whole path

![image](https://user-images.githubusercontent.com/9946471/46902957-035be280-cec6-11e8-84c5-f338a41676c8.png)

**Comment by ronrosenfeld** [comment]
Thanks. That does it.  And I don't know if the latest has fixed it yet, but on the Help & Info page near the bottom, there is also:  `Website: http://sick-rage.github.io/ `  which is also incorrect.
