### ISSUE TITLE
No Search Providers All Missing

### ISSUE THREAD

**Issue by optio50** [SickChill/SickChill#5050]
Error:
No NZB/Torrent providers found or enabled for daily searches and backlog searches

Search provider screen has no table or options for providers

**Comment by mmhere** [comment]
please provide more info.  what does the tail end of the logfile say?

**Comment by optio50** [comment]
Dont know why but a new clone of the repository seems to have resolved the issue

**Comment by smilerz** [comment]
I ran into this problem as well.  For anyone that stumbles here looking for a fix this is what I did.
Before correcting "local ahead of master issue" use built-in Backup feature and backup your config.
Update config.ini to point to new git location (SickChill/SickChill.git)
Restart SickChill
Get 'No NZB/Torrent Error'
Restore backup
Restart...viola!

**Comment by robrossuk** [comment]
Hi everyone. I've got this same issue. I've just completed a fresh install and when I go to search providers they are completely empty.

**Comment by robrossuk** [comment]
There is no longer an option to add customs search provider either. I'm trying to add showrss feed but there is no custom torrent providers tab.

**Comment by Cypher87** [comment]
I'm running into the same issue, No providers, nothing useful in the logs either (debug enabled). No errors in the browser console except a message "This function need to be filled with ConfigProviders.js but can't be as we've got scope issues currently."

Any help is appreciated

**Comment by Woutifier** [comment]
In my case the solution was to manually enable one of the providers in the config.ini

- Stop SickBeard
- Modify config.ini (e.g. set "btn = 0" to "btn = 1")
- Start SickBeard
- Also make sure "Enable torrent search providers" is checked in "Search settings"

Hope this helps for you as well

**Comment by Cypher87** [comment]
This worked indeed! Thank you @Woutifier
