### ISSUE TITLE
No longer automatically updating

### ISSUE THREAD

**Issue by procdaddy11** [SickChill/SickChill#5055]
I switched repos from SR to SC and ever since then I’ve had to manually update my SC. Windows 10 x64

**Comment by miigotu** [comment]
Stop SC
Backup your config.ini and sickbeard.db
Uninstall and delete the C:\SickRage folder
Install with the SC installer (Its updated)
Stop SC
Restore your config.ini and DB, BUT edit the config.ini and search for "Rage", make sure you aren't using Sick-Rage or SickRage in the git url, and make sure auto_update = 1 in the ini.
Start SC

**Comment by procdaddy11** [comment]
I followed your instructions a few hours ago and I’m still seeing the same behavior.

**Comment by miigotu** [comment]
A few hours ago? It only auto updates once a day.

**Comment by procdaddy11** [comment]
018-10-17 07:48:24 WARNING CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version. Error: AssertionError(u'Empty response from http://cdn.rawgit.com/SickChill/SickChill/2a781a0356e952c3e25890286aade058083bd0c1/sickbeard/databases/mainDB.py',)
2018-10-17 07:48:24 INFO CHECKVERSION :: Request failed: 403 Client Error: Forbidden for url: https://cdn.rawgit.com/SickChill/SickChill/2a781a0356e952c3e25890286aade058083bd0c1/sickbeard/databases/mainDB.py

**Comment by miigotu** [comment]
Update it manually one time, that error has been fixed. RawGit is shut down
