### ISSUE TITLE
RarBG and PirateBay Errors

### ISSUE THREAD

**Issue by CAVACO-PT** [SickChill/SickChill#5056]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:Chrome
What you did: Sickchill tried to do Hourly search ,
What happened: PirateBay and RarBG have this errors , this is happening for some days now , anyone having the same ??
What you expected: no errors in acessing
Logs:

**Comment by CAVACO-PT** [comment]
![image](https://user-images.githubusercontent.com/9946471/46916882-95441800-cfb8-11e8-89d3-2067dfd727c6.png)

**Comment by miigotu** [comment]
TPB was down, and you got throttled on rarbg. They both work.
