### ISSUE TITLE
Suddenly decided it needed nodejs which cannot be installed.

### ISSUE THREAD

**Issue by giantpune** [SickChill/SickChill#5057]
```sh
SickChill Info:
Branch: master
Commit: e3525d78aee855db8e02769f5d782d91cf54b6ef
Version: v2018.10.13-6
Database Version: 44.0
  Python Version: 2.7.3 (default, Nov 24 2017, 18:50:14) [GCC 4.6.3]
  SSL Version: OpenSSL 1.0.1t 3 May 2016
  OS: Linux-3.10.82+-armv7l-with-debian-7.11
  Locale: en_US.UTF-8
```
```sh
2018-10-14 09:58:41 SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] :: [e3525d7] Request failed: Missing Node.js runtime. Node is required and must be in the PATH (check with `node -v`). Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install nodejs-legacy` on some Debian-based systems. (Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.
```

Apparently nodejs won't play nicely on dinosaur computer.   Its not available in the package manager and trying to install it directly from their website gives 
```sh
## Confirming "wheezy" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/wheezy/Release'

## Your distribution, identified as "wheezy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
```

Please reconsider depending on the cancer that is nodejs as its not able to be installed on many embedded systems.  :(

FWIW pukpy is a python package that can interpret javascript and doesn't rely on nodejs.

**Comment by miigotu** [comment]
We dont require nodejs, but the lib we use to automatically solve captchas does. It has been this way for like 2 years lol... Worst case scenario you just dont get the results for that search on that site.
Likely you forgot some cookies, or need to log into the site from that machine to get past the captcha once and it will be fine.

**Comment by abetancort** [comment]
You can use [**Jacket**](url
https://github.com/Jackett/Jackett) which is multi-site platform independent searcher that is supported natively by SickChill, Sonarr, Radarr, CouchPotato, Mylar, DuckieTV, and other. 

Its current (and previous) releases are actually really stable and the addition of new sources it is quite active right now. Nowadays it supports well over 100 sources, private and public, not just for TV Seies but almost anything else. 

Doesn’t have any external dependencies, like nodejs, other than .net 4.6.1 on Windows PC and Mono 5.8 part of Microsoft .net open source foundation to port its  .NET Framework to Linux and macOS .

**Comment by miigotu** [comment]
@abetancort it has to solve captchas somehow. If you want to contribute that is ok, but we arent advertising alternatives here.
