### ISSUE TITLE
Changing drives

### ISSUE THREAD

**Issue by roscopwnz** [SickChill/SickChill#5059]
Hey,

Not a bug, but looking for some advice,

I had all my shows split across 2 drives, lets call them B and T drives,

I then *had* to move everything from the B drive to the T drive,
Now I'm looking for a quick and easy way to relist all the shows in SickChill to tell it not to look at B but look for everything on T,

Only way I found so far is to manually edit each show individually and reselect

**Comment by miigotu** [comment]
Using sqlite to modify the db would be the quickest route if you know your way around sql

**Comment by miigotu** [comment]
install sqlite3
stop SR, and make a backup copy of sickbeard.db to sickbeard.db.bak
sqlite3 sickbeard.db
```sql
UPDATE tv_episodes SET location = replace( field, 'C:\afolder\', 'C:\anewfolder\' ) WHERE field LIKE 'C:\afolder\%';
UPDATE tv_shows SET location = replace( field, 'C:\afolder\', 'C:\anewfolder\' ) WHERE field LIKE 'C:\afolder\%';
commit;
.quit
```
delete cache.db, and start SickRage
