### ISSUE TITLE
Transmission connection error

### ISSUE THREAD

**Issue by fantasio31** [SickChill/SickChill#5060]
**Branch**: master
**Commit**: 65254bfa4d580a883a46d5a99b93e599e42f2959
**Version**: v2018.10.14-1
**Database Version**: 44.0
**OS**: Raspbian Wheezy (7)
**Browser**: Firefox

**What you did:** let SickChill work and try to send torrent to Transmission
**What happened:** [Errno 404] Not Found (while testing connection) / Authentication failed (while sending download)

**What you expected:** Sending successful to transmission. My transmission client is configured with no authentication. It works fine two days ago, but it is no more working while transmission is correctly available through its web interface and working. Tried with other transmissions installations, same behavior

**Logs:**
2018-10-14 21:25:15 WARNING  SEARCHQUEUE-BACKLOG-80379 :: Transmission: Authentication Failed
2018-10-14 21:25:14 DEBUG    SEARCHQUEUE-BACKLOG-80379 :: Calling Transmission Client

**Comment by miigotu** [comment]
![screenshot from 2018-10-14 21-05-12](https://user-images.githubusercontent.com/390379/46929717-ea524f00-cff5-11e8-8e9e-4c1a5a7d67f5.png)

**Comment by miigotu** [comment]
![screenshot from 2018-10-14 21-13-58](https://user-images.githubusercontent.com/390379/46929747-166dd000-cff6-11e8-8924-81adb2553e0f.png)

**Comment by fantasio31** [comment]
Found the issue using Apache2 logs to check URL.

Transmission URL RPC was not ok : i used "transmission/web" as defined some days ago in my raspbian.

For some kind of reason (maybe update ?), url has changed to "transmission".
