### ISSUE TITLE
Blank Star Rating Shown in All Shows

### ISSUE THREAD

**Issue by abetancort** [SickChill/SickChill#5061]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/65254bfa4d580a883a46d5a99b93e599e42f2959
OS: Synology
Browser: Safari Mobile 
What you did: Enter a multiple shows 
What happened: **There are no stars (or any other rating) showed. The stars remain grey for every show.**
What you expected: **To see the ratings from IMDb or Tratk or RottenTomatoes...**
Logs: None
PASTE LOGS HERE:
N/A

**Comment by miigotu** [comment]
I had to revert this fix for now... it breaks stuff for some people -.-
