### ISSUE TITLE
Error Updating existent show , error After latest update

### ISSUE THREAD

**Issue by CAVACO-PT** [SickChill/SickChill#5064]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did: updated to latest version 
What happened: Show Disapeared from List , error in logs , cannot re add show , does not apear in list.
What you expected: updated sucessfully

After restart i have an error each time 

![image](https://user-images.githubusercontent.com/9946471/46939995-967c5000-d05f-11e8-82b4-85ef67efcbda.png)

**Comment by CAVACO-PT** [comment]
![image](https://user-images.githubusercontent.com/9946471/46939596-962f8500-d05e-11e8-99db-c54beac50cb1.png)

**Comment by CAVACO-PT** [comment]
![image](https://user-images.githubusercontent.com/9946471/46939961-7cdb0880-d05f-11e8-90f6-5fffddaf1b01.png)

**Comment by miigotu** [comment]
Try the develop branch please

**Comment by CAVACO-PT** [comment]
@miigotu  , when i try the Develop branch i get this error

![image](https://user-images.githubusercontent.com/9946471/46947809-f41a9780-d073-11e8-860f-149c8b167fde.png)

**Comment by CAVACO-PT** [comment]
![image](https://user-images.githubusercontent.com/9946471/46948442-0564a380-d076-11e8-9437-ca010abc3875.png)

**Comment by miigotu** [comment]
pull again and try. I just tried another fix

**Comment by miigotu** [comment]
```bash
git fetch origin
git checkout -b develop origin/develop
```

**Comment by CAVACO-PT** [comment]
@miigotu  not yet :(

![image](https://user-images.githubusercontent.com/9946471/46948823-3abdc100-d077-11e8-9483-20186221eaef.png)

**Comment by miigotu** [comment]
```bash
git branch
git checkout -b develop --track origin/develop
```

**Comment by CAVACO-PT** [comment]
git branch shows this 

![image](https://user-images.githubusercontent.com/9946471/46949228-9ccaf600-d078-11e8-87af-c1976f55bcc7.png)

**Comment by CAVACO-PT** [comment]
![image](https://user-images.githubusercontent.com/9946471/46949260-b5d3a700-d078-11e8-8e0d-ba4cc413f82c.png)

**Comment by miigotu** [comment]
Your git repo is fucled....

**Comment by CAVACO-PT** [comment]
@miigotu can i delete it . or have to reinstall ???

**Comment by miigotu** [comment]
Just stay on master, im reverting the new imdbpy commit - I think we can live with no star ratings on displayShow for awhile. Its better than this

**Comment by CAVACO-PT** [comment]
@miigotu did a brand new docker from linux  , and the change to develop gives the exact same error , just so u know ...
