### ISSUE TITLE
[APP SUBMITTED]: Error relocating /app/sickrage/lib/lxml/etree.so: __sprintf_chk: symbol not found

### ISSUE THREAD

**Issue by CAVACO-PT** [SickChill/SickChill#5065]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-3.10.105-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@d019c5454643153e16b48de740c7a02558139207
Link to Log: https://gist.github.com/de6ccc84f5af8db7bba14bb46a58ee2c
### ERROR
```
MAIN :: [d019c54] There was an error creating the show in /volume2/Media/Series/Property Brothers Buying and Selling: Error Error relocating /app/sickrage/lib/lxml/etree.so: __sprintf_chk: symbol not found
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Try the develop branch please

**Comment by kyuuk** [comment]
Tested on master, it's working, thank you.
