### ISSUE TITLE
[APP SUBMITTED]: Error loading shared library /SickRage/lib/lxml/etree.so: Exec format error

### ISSUE THREAD

**Issue by bepece1** [SickChill/SickChill#5066]
### INFO
Python Version: **2.7.14 (default, Feb 22 2018, 21:59:41) [GCC 6.3.0]**
Operating System: **Linux-4.14.70-v7+-armv7l-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@d019c5454643153e16b48de740c7a02558139207
Link to Log: https://gist.github.com/17bb913d970cf65f212e4c94d4075a27
### ERROR
```
SHOWQUEUE-ADD :: [d019c54] Error loading IMDb info: Error loading shared library /SickRage/lib/lxml/etree.so: Exec format error
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by bepece1** [comment]
### INFO
Python Version: **2.7.14 (default, Feb 22 2018, 21:59:41) [GCC 6.3.0]**
Operating System: **Linux-4.14.70-v7+-armv7l-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@d019c5454643153e16b48de740c7a02558139207
Link to Log: https://gist.github.com/5ac58ea00e09e5d9f227fcf8cc757f26
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [d019c54] Error loading IMDb info: Error loading shared library /SickRage/lib/lxml/etree.so: Exec format error
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Try the develop branch please

**Comment by bepece1** [comment]
Works ok now, thanks
