### ISSUE TITLE
[APP SUBMITTED]: /volume1/@appstore/sickbeard-custom/var/SickBeard/lib/lxml/etree.so: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by Mickroz** [SickChill/SickChill#5068]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 15:06:18) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-3.10.105-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@d019c5454643153e16b48de740c7a02558139207
Link to Log: https://gist.github.com/7792cb4bc47fe1e5943a2ac7555afaa8
### ERROR
```
SHOWQUEUE-ADD :: [d019c54] Error trying to add show: /volume1/@appstore/sickbeard-custom/var/SickBeard/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Try the develop branch please

**Comment by Mickroz** [comment]
can i change that in the config.ini @miigotu ?

**Comment by miigotu** [comment]
stop SR, edit ini and change gh_branch to develop, then do an update

**Comment by Mickroz** [comment]
thanks will try.

**Comment by Mickroz** [comment]
It is called just "branch" if anyone is also having this.
after updating a few times it worked !

**Comment by miigotu** [comment]
@Mickroz because I reverted the commit that broke it haha... star ratings on displayShow don't work right now, but thats better than actual functionality not working.
