### ISSUE TITLE
Request to change restore behavior to get ride of the wrong github location

### ISSUE THREAD

**Issue by BenjV** [SickChill/SickChill#5071]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```
Maybe it is a good idea to change the restore functionality a little bit to get ride of the wrong github in old backups.
When restoring a old backup SickChill will also restore the wrong setting for "git_remote_url".
Maybe it is an good idea to changes that into the correct github location so people can use old backups.

**Comment by miigotu** [comment]
It already does ^

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/blob/master/sickbeard/__init__.py#L801
