### ISSUE TITLE
No Providers? 

### ISSUE THREAD

**Issue by xDowwdeen** [SickChill/SickChill#5073]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: dietPi (Raspberry Pi)
Browser: Chrome
What you did: Fresh install of SickRage.
What happened: I am not getting any of the search providers to show up when i go to configure them 

LOGS: https://pastebin.com/YMxWFMCq

http://prntscr.com/l6aeen

**Comment by CAVACO-PT** [comment]
@xDowwdeen  go enable them on the providers area , then they will apear

**Comment by xDowwdeen** [comment]
> @xDowwdeen go enable them on the providers area , then they will apear

I would but none are showing up ?

http://prntscr.com/l6akdb
