### ISSUE TITLE
When Adding Existing Shows with 4-digit Season numbers, episodes are ignored

### ISSUE THREAD

**Issue by bartolomesoriano** [SickChill/SickChill#5075]
Branch: master
Commit: 13bbd46fc7b59190c0507ec0d2d601d77c947106
Version: v2018.10.15-3
Database Version: 44.0
Python Version: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
OS: Windows-10-10.0.18252
Locale: en_US.cp1252
Browser: Chrome
What you did: Rescan files on show with seasons with 4-digits
What happened: All episodes for seasons other than Season 0 were ignored
What you expected: All existing episodes to be picked up.

Logs: https://1drv.ms/u/s!AlII29kkG6TFiLJglGLd3E9xLesK0A

The Sky At Night (tvdb id 80428) has season numbers with 4 digits, since the season number is the year of airing of the episodes.  This is not an air-by-date show, it has seasons in thetvdb, numbered 1960, 1984, 2018, etc.  When re-scanning files after I saw that none of my existing episodes except for Season 0 are showing in SickChill, I tried re-scanning the files.  The result is the same, none of my episodes except for Season 0 are being picked up.

I provided the link to my log with debug turned on from when I tried again to re-scan the files.

**Comment by miigotu** [comment]
We dont support 4 digit season numbers.

**Comment by miigotu** [comment]
A new regex would have to be added to add them from existing files. It may have worked to download them before they were renamed to SR naming style you have set.

**Comment by WebSpider** [comment]
Unstale

**Comment by WebSpider** [comment]
We need to teach the bot to also ignore enhancement and feature requests

**Comment by oraclesod** [comment]
I saw above that this is not supported ? why not ? its now heavily used by TheTVDB

Without this ability we are forced to use Aired Date, however there is another bug in that where it displays a day ahead of the actual date when comparing the gui to the downloaded zip file from TheTVDB...

Two examples where the year is the season:
https://www.thetvdb.com/series/eurovision-song-contest
https://www.thetvdb.com/series/pixar-shorts

**Comment by oraclesod** [comment]
How do we reopen this ?
