### ISSUE TITLE
Calling the ALL CLEAR on SickChill rename?

### ISSUE THREAD

**Issue by mmhere** [SickChill/SickChill#5081]
Given all of the great work in implementing the name change, could someone in the know please call an **ALL CLEAR** once it is thought that *Master* is good to do a clean `git clone` in order to start a (*) fresh install?

It would be good to do this in a clearly visible location.  (Maybe readme.md?  It gets displayed at the top level github page.)

---

I'm planning to shutdown, backup all of the critical data in my installation:

- *.db files
- config.ini
- whatever else I usually forget

then `git clone` a fresh blob, and restart with the data and configs put back in place.

(*) That'll be a "partially fresh" install I guess given that old data and settings will come along for the ride.

As my existing pre-shenanigans installation continues to chug along with some minor fixes hacked in place as below, an All Clear isn't necessary now but would be nice to know about when those in the know think it has been achieved.

These critical fixes to my local pre-shenanigans install (otherwise unchanged) allow it to keep
pumping along right now:

- ./sickbeard/network_timezones.py
`url = 'http://sickchill.github.io/sb_network_timezones/network_timezones.txt'`

- ./sickbeard/indexers/indexer_config.py
`'scene_loc': 'http://sickchill.github.io/scene_exceptions/scene_exceptions.json',`

I.e., I'm still running OK with an old tweaked install but it would be nice to grab a brand spanking clean new installation once we think all the corners have had the light shone in.

---

I pose the question at the top because I notice stuff like the following is still present in *Master*:

`$ ls -oh ./gui/slick/images/sickrage-shark-mascot.png`
`-rw-r--r-- 1 mmhere 11K Oct 15 13:58 ./gui/slick/images/sickrage-shark-mascot.png`

I know it takes along time to ferret out all the niggly little details with a major rename like this.

**Comment by miigotu** [comment]
All Clear. It has been safe to use this for over a week.
