### ISSUE TITLE
Sickchill cant open safari-pinned-tab.svg

### ISSUE THREAD

**Issue by Jamyz** [SickChill/SickChill#5086]
Branch/Commit: 42ebd2241c841f3339ad0a80411277487345a005
OS:Linux-3.10.105-x86_64-with-glibc2.2.5
Browser: Chrome
What you did: Update
What happened: Sickchill cant open safari-pinned-tab.svg
What you expected: Sickchill maybe need png format and not svg ?
Logs:
```
AA 2018-10-16 08:41:11 ERROR Could not open static file u'/volume1/@appstore/sickbeard-custom/var/SickBeard/gui/slick/images/ico/safari-pinned-tab.svg" color="#5bbad5'
```
I think safari-pinned-tab.svg need to convert to safari-pinned-tab.png

**Comment by nicke736** [comment]
I getting same here. The log is getting spammed with this message.

**Comment by Jamyz** [comment]
Yes. But i cant upload the file converted in png in the repo.........

**Comment by CAVACO-PT** [comment]
same here 

![image](https://user-images.githubusercontent.com/9946471/46998927-f5070400-d11b-11e8-94af-fc572c81c60b.png)

**Comment by jpdyno** [comment]
Looks like a fix is in the wings, just waiting on approval.
[https://github.com/SickChill/SickChill/issues/5083](url)
[https://github.com/SickChill/SickChill/pull/5085](url)

**Comment by Jamyz** [comment]
![safari-pinned-tab](https://user-images.githubusercontent.com/6177824/47000169-fa6a4b80-d127-11e8-9aca-8a99cdcb0e90.png)

**Comment by jpdyno** [comment]
See issue 5083, looks like the same thing, Apparently a typo in the code?
someones submitted a fix already waiting on approval.
