### ISSUE TITLE
Image Error

### ISSUE THREAD

**Issue by fookhk** [SickChill/SickChill#5088]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
Branch: master
Commit: 42ebd2241c841f3339ad0a80411277487345a005
Version: v2018.10.15-4
Database Version: 44.0

OS: aspbian GNU/Linux 9 (stretch)
Browser: Firefox 62.0.3
What you did:
What happened: error in logs
What you expected:
Logs:
```
PASTE LOGS HERE
```
ERROR    Could not open static file u'/opt/sickrage/gui/slick/images/ico/safari-pinned-tab.svg" color="#5bbad5'

**Comment by jeffjoker** [comment]
Same here
