### ISSUE TITLE
We can't proceed with the update. Unable to check remote DB version. RawGit has reached the end of its useful life.

### ISSUE THREAD

**Issue by Mickroz** [SickChill/SickChill#5090]
```
2018-10-16 13:57:57 CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version. Error: AssertionError(u'Empty response from http://cdn.rawgit.com/SickChill/SickChill/42ebd2241c841f3339ad0a80411277487345a005/sickbeard/databases/mainDB.py',)
```
RawGit has reached the end of its useful life
October 8, 2018
RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.

GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.

If you're currently using RawGit, please stop using it as soon as you can.

**Comment by CAVACO-PT** [comment]
I have the exact same error when i try to swith from Master to develop branch... cannot do it ... gives that error , and tried a fresh installed with nothing on it .. and doesnt work .. only can be in the branch that i set on the install then cannot change .... @miigotu  already saw this as well

**Comment by Mickroz** [comment]
Im already on develop branch, but if he knows it will be fixed soon, no doubt ;)

**Comment by miigotu** [comment]
Fixed in develop and master. Update.
