### ISSUE TITLE
Network folder

### ISSUE THREAD

**Issue by ortga10** [SickChill/SickChill#5091]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:  Windows
Browser: Chrom
What you did: update
What happened: can't open map drive the log below [ Z network folder ] it was working fine yesterday 
What you expected: update issue
Logs:
```
2018-10-16 22:06:15 ThreadPoolExecutor-0_3 :: [fa36303] Unable to create the folder Z:\Media\tv show\Boardwalk Empire, can't add the show
```

**Comment by miigotu** [comment]
It is not an update issue, nothing related to that has changed. Check your setup.
