### ISSUE TITLE
Ubuntu installation instructions

### ISSUE THREAD

**Issue by Zw3rv3r** [SickChill/SickChill#5093]
Because of the name change to SickChill the Ubuntu installation instructions (https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15) do not work correctly.

The daemon script references to the group/user/folder have changed but the documentation for creating group/user/folder required for the script to run hasn't changed yet.

**Comment by NeoMod** [comment]
I have edited the Wiki page in order to reflect the changes and - hopefully - avoid problems for other users.

If it's fine, I think this might be marked as closed.

**Comment by miigotu** [comment]
I mass edited wiki pages right now, hopefully it is good now.
If you find broken links/info please let me know.

**Comment by sinterlkaas** [comment]
This link still has the issue with adding new user to linux 
https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15

as reported by https://github.com/SickChill/SickChill/issues/5093#issuecomment-430467004

**Comment by miigotu** [comment]
Fixed
