### ISSUE TITLE
Docker: which image to use?

### ISSUE THREAD

**Issue by SteveW25561** [SickChill/SickChill#5094]
@miigotu 
So glad to see you're finally digging out of the whole echel0n fiasco.

I see a few new docker images with the name sickchill, and 2 look to be the most 'official': one owned by sickchill and the other by miigotu.  Do you officially endorse these ones (or both)?  The wiki still points to linuxserver/sickrage.  After being stung I want to be sure we're not being fooled again, so which one of these so you recommend:

https://hub.docker.com/r/sickchill/sickchill/ --> looks new and current
https://hub.docker.com/r/miigotu/sickchill/ --> looks new and current
https://hub.docker.com/r/linuxserver/sickrage/ --> last updated 09.08.18 thus might still be compromised

Thanks!

**Comment by jasker5183** [comment]
Personally I'm still using the linuxserver/sickrage container hoping that they change the name soon but if you want to compare here is the [linuxserver/sickrage dockerfile](https://github.com/linuxserver/docker-sickrage/blob/master/Dockerfile), here is the [linuxserver/sickchill dockerfile](https://github.com/linuxserver/docker-sickchill/blob/master/Dockerfile) from their github repo (still not up on docker hub yet though). Both of those should be the exact same. Should be noted that linuxserver/sickrage was changed to the new github repo but the readme still links to the sickrage.ca and it hasn't been updated that the repo changed again. I think it's also not being updated any further.

Here is the [sickchill/sickchill dockerfile](https://github.com/SickChill/SickChill/blob/master/Dockerfile) so you tell me which one is better if at all? It's just if you were running the linuxserver version you need to change /config to /data, so should be an easy change.

**Comment by miigotu** [comment]
miigotu/sickchill and sickchill/sickchill are identical and always current (by build automation) with the master branch.
linuxserver/sickrage is ours, and so will be linuxserver/sickchill ... Im not sure where they are with the progress, but it helps that they keep it updated.

**Comment by SteveW25561** [comment]
That’s terrific. I just installed the docker for Synology using sickchill/sickchill and its working great! It’s nice to have docker images to avoid incompatiblity issues when there’s an update to Synology DSM & native/community packages, etc.
