### ISSUE TITLE
SickChill Failing to add Torrent Category to some downloads (qBittorent)?

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SickChill/SickChill#5095]
Branch/Commit: 2a781a0356e952c3e25890286aade058083bd0c1
Was: fa36303a1f48e9862729b0f1a74f83de81bc2522
OS: MacOS Mojave 10.14
Browser: Safari 12
What you did: nothing on my own
What happened: SickChill falling to add category to some torrents to qBittorent Properly
What you expected: TorrentToMedia.py to process torrent properly but I believe SC is stripping out the category of some downloads which is odd.
Logs: 
[SC CAT issue.zip](https://github.com/SickChill/SickChill/files/2486053/SC.CAT.issue.zip)

Notes: did not use gist this time as the issue seems to be widespread & I'm having trouble isolating why this is happening. these are raw logs for SC, nzbtomedia & qbittorrent (unedited this time)

@miigotu @clinton-hall 

for torrent hash `25288643e7be48131c1aaf8a7b2617688521dd1e` SC fails to properly apply category for some reason sickchill.log.5 & hash `2a991ed1b58a011c314fe9f3d1b4ef046f091b31` sickchill.log.6

you can trace the issue between the SC, nzbtomedia & qbittorrent logs. I believe SC is having issues with some torrents. because most torrents successfully process expect for a couple and this has been happening for couple days not. I though it was nothing while I was testing api features and other stuff with nzbtomedia. but this is starting to concern me now.

manually running script with sickchill CAT is no issues so repeating this issue is going to be hard as SC or QB makes this issues automatically time to time & the real reason is unknown to why this is happening.

**Comment by XxUnkn0wnxX** [comment]
so SC to Balme? not sending the torrents properly? but I cannot understand why this only happens to some but not all torrents. something is a miss here....

**Comment by miigotu** [comment]
It happens when qB takes to long to gather metadata. When the torrent isnt finished loading the set label call fails

**Comment by clinton-hall** [comment]
not saying SC to blame.... somewhere the hand-shake between SC and QB is failing.

**Comment by XxUnkn0wnxX** [comment]
@miigotu is there a way to mitigate this? like put in a timer somewhere to give qB time to load/gather the metadata?

**Comment by miigotu** [comment]
I didnt look at the logs yet, but I bet its only on magnets ^ with slow trackers.

**Comment by XxUnkn0wnxX** [comment]
onto of my previous post my current setup in SC + qB for trackers are I have Trackers list in SC configured + qB: 
![screen shot 2018-10-17 at 7 39 15 pm](https://user-images.githubusercontent.com/2242880/47073601-5b874180-d244-11e8-860a-741aa6291410.jpg)

I'm probably doubling up on the amount of trackers. I could probably remove from SC and just let qB do it. but still won't complete solve the issue for any other torrents added which contains slow trackers.

a more elegant solution would be for either SC or qB to run a script (if possible) before any torrent is added to strip trackers out of the magnets (a check is run identifying slow trackers from a approved list of trackers which are not slow or having downtime issues). EG from https://github.com/ngosang/trackerslist/blob/master/trackers_best.txt which is updated daily or https://newtrackon.com.

**Comment by miigotu** [comment]
There is your problem, you are using TOO MANY trackers, and qB has to go through every one of them, even if they take forever to respond if at all.

**Comment by below9k** [comment]
I have this problem and I am just using the magnet's (or whatever torrent meta SC gets) trackers. I ended up removing the categories in SC myself just to get rid of the warnings.
Side note: I've had to up the attempt count on verifying torrents as well see #5016 qbittorrent is slow about things I suppose..

**Comment by XxUnkn0wnxX** [comment]
> You could just let the magnets use the trackers they came with, js.

well it doest always mean those trackers included will also have issues as well. + generally I need extra trackers in qB as I only DL other media torrents via the hash which doesnt include the trackers with them.

**Comment by XxUnkn0wnxX** [comment]
FYI, still having same issues @miigotu I disabled all tracker adding in SC & QB and only stuck with original trackers that came with magnet. and only 4 trackers this one had and it still failed to stick label. however out of those 4 trackers only 2 where working. so simply sticking with Original trackers wont fix this. when the author who posts magnets with improper trackers still causes this.... simply put 

> You could just let the magnets use the trackers they came with, js.

wont solve this 👎

**Comment by miigotu** [comment]
How many seeds does the torrent have and do you have DHT enabled?

**Comment by XxUnkn0wnxX** [comment]
ok I've set to qbittorrent-labels

but 'I'm getting `you're using the qbittorrent-labels branch. Please use 'master' unless specifically asked` annoying notification on SC now. is there a way I disable this? even if its for a couple of days...

**Comment by miigotu** [comment]
stop sc and edit the config.ini and set developer=1 and the irritating popup goes away
It doesnt matter how many trackers you use now, because the label and path (if set) get set on the torrent when it is added now instead of a different call.

**Comment by XxUnkn0wnxX** [comment]
@miigotu well I think it safe to commit the changes into master branch. I've had no issues.

**Comment by WebSpider** [comment]
This has been in master a while now, closing issue
