### ISSUE TITLE
post-processing problem

### ISSUE THREAD

**Issue by bepece1** [SickChill/SickChill#5096]
I have post-processing problems with some files.

Example:
Directory: The Walking Dead - Temporada 9 Capitulo 2 [HDTV 720p][AC3 5.1 Castellano]
File: th.wkd.9x02.m720p.[es].mkv

Why not post-processing??? No errors but not work.

SickChill Info:
Branch: master
Commit: 2a781a0356e952c3e25890286aade058083bd0c1
Version: v2018.10.16-3
Database Version: 44.0
Versión de Python: 2.7.14 (default, Feb 22 2018, 21:59:41) [GCC 6.3.0]
Versión SSL: LibreSSL 2.5.5
OS: Linux-4.14.70-v7+-armv7l-with

**Comment by Tiwas** [comment]
Seems like a naming issue to me. Tried renaming the file to the same name as the directory?

**Comment by DasGreff** [comment]
Yeah, bad file naming, either rename your file or add a scene exception (the.wkd)

**Comment by bepece1** [comment]
> Yeah, bad file naming, either rename your file or add a scene exception (the.wkd)

Works, thank you  ;-)
