### ISSUE TITLE
git checkout -f master returned : error: pathspec 'master' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by CAVACO-PT** [SickChill/SickChill#5097]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:master
OS:
Browser:
What you did: Tried to go to switch the repos either from develop to master , or master to develop 
What happened: the error in the logs
What you expected: changed branch 
Logs:
```
it checkout -f master returned : error: pathspec 'master' did not match any file(s) known to git.
```
Already tried with a new instalation without docker ... and its the same ... will only stay in the branch that is put during instalation , cannot change .... found a thread maybe can ohelp

https://stackoverflow.com/questions/30800454/error-pathspec-test-branch-did-not-match-any-files-known-to-git/37981441

Anyone else has this error ???

**Comment by miigotu** [comment]
Try this:
```
rm -r master
rm -r origin/master
git fetch origin
git branch -r
git checkout master
```
If that doesnt work, update git.
