### ISSUE TITLE
torrent - Sent to Download Station

### ISSUE THREAD

**Issue by 03397** [SickChill/SickChill#5099]
Suggestion - Request

Is there a possibility to add an option to SickChill to send the torrents to Download Station of QNAP.
It is like the option you have to sent it to  Synology.

Thanks

**Comment by 03397** [comment]
@WebSpider 
You mean  that QNAP should create create an API so that SickChill can interface with it?
Who is Lenny?????:)

**Comment by WebSpider** [comment]
Well, I am under the assumption that qnap already has an api allowing for just that. I am assuming the qnap packager has more intimate knowledge (and a qnap to test with? ), which would greatly speed up development time

**Comment by 03397** [comment]
Happy new year to everyone  Are there any news on that?
