### ISSUE TITLE
Shows with parenthesis in name get double-encoded when doing RSS search on torrentday, possible other providers

### ISSUE THREAD

**Issue by AubreyKilian** [SickChill/SickChill#5110]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
master/2a781a0356e952c3e25890286aade058083bd0c1
(And others before this...)

OS:
Ubuntu 18.04.1 LTS

Browser:
Chrome Mac - but this isn't relevant

What you did:
Daily searches not picking up shows with brackets/parenthesis in their name, when searching against torrentday's RSS GET method (maybe others...)

What happened:
Specifically, showname "The Flash (2014)" ends up getting double-encoded on the GET params when calling torrentday:
https://www.torrentday.com/t.json?24=1&26=1&34=1&q=The%2BFlash%2B%25282014%2529%2BS05E02&2=1&7=1
Notice the q=The%2BFlash%2B%25282014%2529%2BS05E02
That decodes to: q=The+Flash+%282014%29+S05E02
Due to this error, the search results in zero torrents being returned.

One work-around was to add "The Flash 2014" as a showname alternative.

What you expected:
The showname shouldn't be encoded twice, so should come through on the GET params line as:
The%20Flash%20%282014%29%20S05E02 or some such

Logs:
```
2018-10-22 13:23:18 INFO     SEARCHQUEUE-MANUAL-279121 :: [TorrentDay] :: Performing episode search for The Flash (2014)
2018-10-22 13:23:18 DEBUG    SEARCHQUEUE-MANUAL-279121 :: [TorrentDay] :: Search Mode: Episode
2018-10-22 13:23:18 DEBUG    SEARCHQUEUE-MANUAL-279121 :: [TorrentDay] :: Search string: The Flash (2014) S05E02
2018-10-22 13:23:19 DEBUG    SEARCHQUEUE-MANUAL-279121 :: [TorrentDay] :: GET URL: https://www.torrentday.com/t.json?24=1&26=1&34=1&q=The%2BFlash%2B%25282014%2529%2BS05E02&2=1&7=1 [Status: 200]
2018-10-22 13:23:19 DEBUG    SEARCHQUEUE-MANUAL-279121 :: [TorrentDay] :: Data returned from provider does not contain any torrents
```

**Comment by AubreyKilian** [comment]
Diff of the above-mentioned change:

diff --git a/sickbeard/providers/torrentday.py b/sickbeard/providers/torrentday.py
index b286e1d90..c4493049d 100644
--- a/sickbeard/providers/torrentday.py
+++ b/sickbeard/providers/torrentday.py
@@ -132,7 +132,7 @@ class TorrentDayProvider(TorrentProvider):  # pylint: disable=too-many-instance-

                 get_params = {}
                 get_params.update(self.categories[mode])
-                get_params["q"] = quote_plus(search_string.decode('utf-8', 'ignore'))
+                get_params["q"] = quote_plus(search_string.decode('utf-8', 'ignore'), '()')

                 try:
                     torrents = self.get_url(search_url, params=get_params, returns='json')

**Comment by miigotu** [comment]
requests calls quote_plus internally when you pass a string in a dict value for params/data/payload.
```python
>>> quote_plus(quote_plus('Help (2018)'))
'Help%2B%25282018%2529'
>>> quote_plus('Help (2018)')
'Help+%282018%29'
```
