### ISSUE TITLE
[Feature Request] Cross-Seeding the same file

### ISSUE THREAD

**Issue by doopeldedoo** [SickChill/SickChill#5112]
Sickchill only downloads one torrent of a specific episode.

If the episode is available on **multiple** trackers, can Sickchill **download them all** to cross-seed?
Cross-seeding is when the same torrent is on two different trackers, you can download it from one, then seed to both.
This makes it possible to achieve a better ratio at multiple trackers.

**Comment by WebSpider** [comment]
This doesn't look like a task for SC to do, since SC offload the actual downloading of the media to various clients, such as jacket, usenet clients, torrent clients, etc.

You should implement this in your torrent software, which SC is not.
