### ISSUE TITLE
thetvdb is down maybe api fault?

### ISSUE THREAD

**Issue by movfan** [SickChill/SickChill#5113]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:Search new series
What happened: connection fault
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by vanbrabant** [comment]
No logs because all we get is a time-out.

**Comment by mgaulton** [comment]
I noticed that a tvdb api I use broke when urllib / requests was updated recently. Perhaps related?

**Comment by miigotu** [comment]
Likely the api was just down. It works fine here.
