### ISSUE TITLE
rTorrent: Unable to send Torrent

### ISSUE THREAD

**Issue by JohnMaguire** [SickChill/SickChill#5118]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
```
Branch: master
Commit: 6e3a1dccd94857fc381c9a246b903904eca424e1
Database Version: 44.0
```
OS: `Linux-4.14.35-1-lts-x86_64-with` (in Docker)
Browser: Google Chrome
What you did: Forced a backlog search
What happened: Torrents found, but failed to send to rTorrent
What you expected: Torrents downloading in rTorrent
Logs:
```
2018-10-24 10:07:39 WARNING SEARCHQUEUE-BACKLOG-194031 :: rTorrent: Unable to send Torrent
2018-10-24 10:07:39 WARNING SEARCHQUEUE-BACKLOG-194031 :: Error while sending torrent:
2018-10-24 10:07:39 DEBUG SEARCHQUEUE-BACKLOG-194031 :: Result Hash is XXX
2018-10-24 10:07:39 DEBUG SEARCHQUEUE-BACKLOG-194031 :: Calling rTorrent Client
2018-10-24 10:07:39 DEBUG SEARCHQUEUE-BACKLOG-194031 :: GET URL: https://XXX [Status: 200]
```

(URL and hash removed.)

From rTorrent xmlrpc.log:

```
---
<?xml version='2.0'?>
<methodCall>
<methodName>load_raw</methodName>
<params>
<param>
<value><base64>
(snip)
</base64></value>
</param>
</params>
</methodCall>

---
Status: 200 OK
Content-Type: text/xml
Content-Length: 309

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<fault>
<value><struct>
<member><name>faultCode</name>
<value><i4>-506</i4></value></member>
<member><name>faultString</name>
<value><string>Method 'load_raw' not defined</string></value></member>
</struct></value>
</fault>
</methodResponse>

---
```

(Removed base64'd value)

**Comment by JohnMaguire** [comment]
FWIW, this looks similar to this issue: https://github.com/pymedusa/Medusa/issues/3223

**Comment by JohnMaguire** [comment]
It looks like `load_raw` was renamed to `load.raw`, along with a bunch of other changes... https://github.com/pymedusa/Medusa/pull/3333/files#diff-33878acf9434aa074045d228eade8661

**Comment by mr-orange** [comment]
@Miigotu  Could you give some of your love to this issue. 
Thanks.

**Comment by bolhaskutya** [comment]
I have the same issue. Torrents are not sent to rTorrent. Please fix, thanks :)

I use the url: http://localhost:2020/plugins/httprpc/action.php in SickShill settings.

**Comment by bolhaskutya** [comment]
I can confirm the load_raw renaming to load.raw and such.

In **rutorrent/php/methods-0.9.4.php** we now have:
```
"load_raw"		=>	array( "name"=>"load.raw", "prm"=>1 ),
"load_raw_start"	=>	array( "name"=>"load.raw_start", "prm"=>1 ),
"load_raw_verbose"	=>	array( "name"=>"load.raw_verbose", "prm"=>1 ),
"load_start"		=>	array( "name"=>"load.start", "prm"=>1 ),
"load_start_verbose"	=>	array( "name"=>"load.start_verbose", "prm"=>1 ),
"load_verbose"		=>	array( "name"=>"load.verbose", "prm"=>1 ),
```

But in **sickbeard\lib\rtorrent\__init__.py** we still have:
```
if start and verbose:
    func_name = "load_start_verbose"
elif start:
    func_name = "load_start"
elif verbose:
    func_name = "load_verbose"
else:
    func_name = "load"
elif file_type in ["file", "raw"]:
    if start and verbose:
        func_name = "load_raw_start_verbose"
elif start:
    func_name = "load_raw_start"
elif verbose:
    func_name = "load_raw_verbose"
else:
    func_name = "load_raw"
```

Underscores after raw changed to dots.

_I can't comment on the other changes._

**Comment by miigotu** [comment]
Feel free to PR ;)

**Comment by defhead** [comment]
@miigotu Since this issue is still, does this mean that the current version of sickchill doesn't support rTorrent 0.9.4, 0.9.5, 0.9.6, 0.97, etc... ? (as it was also pointed here #2578 )

**Comment by mr-orange** [comment]
Because of this issue I have Switched to medusa.


________________________________
Da: DefHead <notifications@github.com>
Inviato: domenica, agosto 18, 2019 5:15 PM
A: SickChill/SickChill
Cc: Mr_Orange; Comment
Oggetto: Re: [SickChill/SickChill] rTorrent: Unable to send Torrent (#5118)


@miigotu<https://github.com/miigotu> Since this issue is still, does this mean that the current version of sickchill doesn't support rTorrent 0.9.4, 0.9.5, 0.9.6, 0.97, etc... ? (as it was also pointed here #2578<https://github.com/SickChill/SickChill/issues/2578> )

**Comment by JohnMaguire** [comment]
Same
