### ISSUE TITLE
network_timezones still missing DC Universe and others

### ISSUE THREAD

**Issue by mmhere** [SickChill/SickChill#5119]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:  Master
OS:  Linux/Debian
Browser:  Chrome
What you did:  Restart SickChill
What happened:  Error log grows the familiar complaint about "DC Universe" and others having no timezones
What you expected:  Lack of said error
Logs:
```
2018-10-24 20:42:40 ERROR    Thread-15 :: [a71302b] Missing time zone for network: DC Universe. Check valid network is set in indexer (theTVDB) before filing issue
```
I am only opening this issue anew as many previous reports of it have had their related issues closed, but this URL still returns a time zones list that does not include "DC Universe"

http://sickchill.github.io/sb_network_timezones/network_timezones.txt

**Comment by miigotu** [comment]
I dont know the timezone for it. Anyways it is added with a blank timezone for now.

**Comment by mmhere** [comment]
That's a bit better, but:

```
2018-10-26 16:16:24 ERROR    Thread-14 :: [a71302b] Missing time zone for network: DC Universe. Check valid network is set in indexer (theTVDB) before filing issue.
2018-10-26 16:16:24 ERROR    Thread-14 :: [a71302b] Missing time zone for network: European Broadcasting Union (EBU). Check valid network is set in indexer (theTVDB) before filing issue.
2018-10-26 16:20:36 ERROR    Thread-15 :: [a71302b] Missing time zone for network: Fox España. Check valid network is set in indexer (theTVDB) before filing issue.
```

The three above still complain either about missing entries entirely (the last two), or about the fact that the timezone pair (name plus zone) is missing for the [thankfully] newly added "DC Universe".  So more or less the same startup error is still happening.

https://sickchill.github.io/sb_network_timezones/network_timezones.txt
does show the "DC Universe" entry but as mentioned the above error still occurs.

I also just noted that someone's app posted the following automatically, so that is a dupe w.r.t. the issue open here:
https://github.com/SickChill/SickChill/issues/5121

-----

Let's just pick a timezone for DC Universe.  I propose East Coast US to mimic other streaming services such as CBS All Access or Netflix.  Those look like this:

```
CBS All Access:US/Eastern
Netflix:US/Eastern
```

So why don't we set the result to:

```
DC Universe:US/Eastern
```

**Comment by mmhere** [comment]
How about this to resolve all present timezone errors at startup.  DC Universe as Eastern US as proposed above.  EBU is already present as "EBU (EU)" but some forms apparently want to use the string "European Broadcasting Union (EBU)".  This is based in Geneva so is Central European Time.  Fox España is based in Spain so is also Central European Time.  If these three lines are made to be present in https://sickchill.github.io/sb_network_timezones/network_timezones.txt I think we would be all set:

```
DC Universe:US/Eastern
European Broadcasting Union (EBU):CET
Fox España:CET
```

**Comment by WebSpider** [comment]
Using CET is non-summertime aware, causing time shifts. Please use summertime aware timezones.

And yay, I **finally** figured out what causes these annoying timeshifts!

**Comment by mmhere** [comment]
What is the proper timezone string then?

You can check other examples in the raw text here:
https://sickchill.github.io/sb_network_timezones/network_timezones.txt

**Comment by WebSpider** [comment]
So this should be:
```
DC Universe:US/Eastern
European Broadcasting Union (EBU):Europe/Zurich
Fox España:Europe/Madrid
```

**Comment by mmhere** [comment]
Excellent!  Thanks.  So perhaps miigotu can stick those in next time he pops in here.  Then this issue could be closed.  I'd put them in but I'm not sure how to check in a change for the sickchill.github.io URL referenced above.

**Comment by WebSpider** [comment]
This PR should fix this once it's merged.

**Comment by mmhere** [comment]
Just a note, that version on your pull request still has the "DC Universe:" entry further up the file.  That was where miigotu had added the network string with a blank time zone.  Not sure if the cache.db loader will error out when it comes across the first entry or whether it will keep going through the text file to find the correct entry that you just added.  Perhaps you could delete the redundant one?

**Comment by WebSpider** [comment]
Good one. Fixed.

**Comment by mmhere** [comment]
Cool.  When your two pull requests are merged to main, it'll include the proper time zones for DCU, the two variants of EBU, and the one for Fox España.  Muchos Gracias.  No more startup errors!

**Comment by mmhere** [comment]
Woo-hey!  Startup is once again error free.  Cool.
