### ISSUE TITLE
Req: list of available files under show

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#5124]
First of all - love what you've done, and as soon as you accept anything other than bitcoin I'll contribute with some money. 

I was hoping to be able to get something like in Radarr (and other apps) where you can click on the "Search" tab to see available downloads. This will to a certain degree limit the need for manual searching in nzbhydra and stuff.

Example: I usually specify SD for my shows as I watch them on my computer or pad. Some shows either don't come as SD, other qualities are released before or I would like a higher quality. To save space, I like to go for x265. Now, if I could check some sort of search tab, see which are marked as failed, size and qualities for other files etc that would be an awesome addition.

**Comment by miigotu** [comment]
Ill think about that once some other issues are ironed out. PP donation is added back btw, =P

**Comment by Tiwas** [comment]
Cheers! Made a donation - will donate more once I get my job situation sorted. Keep up the good work :)

**Comment by miigotu** [comment]
Thanks!
This feature might be a bit easier after the DB changes im working on =P

**Comment by miigotu** [comment]
Holding
