### ISSUE TITLE
poster.png and banner.png still showing old name

### ISSUE THREAD

**Issue by si458** [SickChill/SickChill#5126]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: ANY
Browser: ANY
What you did: setup from fresh repo
What happened: after adding shows, the banner.jpg is showing the old name 
What you expected: if should show the new name
Logs:
```
SickChill/gui/slick/images/poster.png
SickChill/gui/slick/images/banner.png
```

**Comment by miigotu** [comment]
feel free to pr some new images lol.

**Comment by BenjV** [comment]
Feel free to use the images I created for the Synology package.
You can find them here.
https://github.com/BenjV/SYNO-packages/tree/master/SickChill_Images

**Comment by miigotu** [comment]
These look ok for now?

https://github.com/SickChill/SickChill/blob/d478f73d1cdd90070b6cce2ee1935eb54016a3d8/gui/slick/images/banner.png
https://github.com/SickChill/SickChill/blob/d478f73d1cdd90070b6cce2ee1935eb54016a3d8/gui/slick/images/poster.png

**Comment by si458** [comment]
brillant!

looks perfect :)

**Comment by miigotu** [comment]
It is seriously ridiculous how much I lack in the artistic department but can still make a half decent logo/image lol....
