### ISSUE TITLE
Attent Devs -- TPB Fix?

### ISSUE THREAD

**Issue by mrmovie89** [SickChill/SickChill#5136]
So this is more of a help getting thepiratebay up and running using one of their valid proxies...

is there a way this can be fixed so tpb can work again? I modified the providers folder in the sickbeard portion, but it didn't seem to do anything.

Thanks in advance for response.

**Comment by miigotu** [comment]
TPB works when it isnt offline.

**Comment by mrmovie89** [comment]
yes but it's been offline for months now. I believe SickChill still uses thepiratebay.org and now it requires the number 3... thepiratebay3.org.

It'd be cool though if there was a way we could just edit this and use any TPB proxy that is live...

**Comment by miigotu** [comment]
You can set the custom url right in the settings page for tpb in SC

**Comment by mrmovie89** [comment]
unless I'm doing it wrong it's not working. How I tested it:

1) Updated URL on SC for TPB
2) Turned off all other providers
3) Force Searched for a file I didn't have yet

Nothing ever snatched...

**Comment by miigotu** [comment]
Use a different provider. Tpb is unreliable because it is always going down. The mirrors only cache older information, they don't get the daily stuff right away.
