### ISSUE TITLE
Rarbg - invalid token

### ISSUE THREAD

**Issue by tapessur** [SickChill/SickChill#5137]
search provider Rarbg spewing following error when doing a manual search. Only start happening today.

SEARCHQUEUE-MANUAL-161511 :: [Rarbg] :: Invalid token. Use get_token for a new one!

**Comment by miigotu** [comment]
Have you tried turning it off and back on again?

**Comment by tapessur** [comment]
It just started working again... prob issue @rarbg.. thanks!!
