### ISSUE TITLE
TODO: Mirrors

### ISSUE THREAD

**Issue by miigotu** [SickChill/SickChill#5139]
Mirror to gitlab and bitbucket automagically, and check those git remotes in case of failures.

**Comment by WebSpider** [comment]
I can help with this

**Comment by miigotu** [comment]
Send me usernames for bitbucket, gitlab, codeplex, etc and I will add you to the teams

**Comment by miigotu** [comment]
Gitlab is already done, need to create teams there

**Comment by WebSpider** [comment]
@miigotu dropped you a mail.

**Comment by WebSpider** [comment]
Destale

**Comment by WebSpider** [comment]
Unstale.

**Comment by WebSpider** [comment]
Unstale

**Comment by miigotu** [comment]
I need to check for that mail, not sure if I did what I was supposed to do here.
