### ISSUE TITLE
from requests.compat quote = SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jangrewe** [SickChill/SickChill#5141]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Debian
Browser: -
What you did: -
What happened: SickChill updated and failed to restart
What you expected: SickChill updated and restarts successfully
Logs:
```
Oct 30 15:29:29 hades systemd[1]: Starting SickChill Daemon...
Oct 30 15:29:29 hades python2.7[25597]: Traceback (most recent call last):
Oct 30 15:29:29 hades python2.7[25597]:   File "/opt/sickchill/SickBeard.py", line 69, in <module>
Oct 30 15:29:29 hades python2.7[25597]:     import sickbeard
Oct 30 15:29:29 hades python2.7[25597]:   File "/opt/sickchill/sickbeard/__init__.py", line 46, in <module>
Oct 30 15:29:29 hades python2.7[25597]:     from sickbeard import (auto_postprocessor, dailysearcher, db, helpers, logger, metadata, naming, post_processing_queue, properFinder, providers, scheduler,
Oct 30 15:29:29 hades python2.7[25597]:   File "/opt/sickchill/sickbeard/dailysearcher.py", line 27, in <module>
Oct 30 15:29:29 hades python2.7[25597]:     from sickbeard import common, db, logger, network_timezones
Oct 30 15:29:29 hades python2.7[25597]:   File "/opt/sickchill/sickbeard/db.py", line 34, in <module>
Oct 30 15:29:29 hades python2.7[25597]:     from sickbeard import logger
Oct 30 15:29:29 hades python2.7[25597]:   File "/opt/sickchill/sickbeard/logger.py", line 43
Oct 30 15:29:29 hades python2.7[25597]:     from requests.compat quote
Oct 30 15:29:29 hades python2.7[25597]:                              ^
Oct 30 15:29:29 hades python2.7[25597]: SyntaxError: invalid syntax
```
Probably caused by https://github.com/SickChill/SickChill/commit/7d88939667bd53d793b3bc766c17f2fe52bfe96a

**Comment by jangrewe** [comment]
Yep, somebody did a search & replace for `six.moves.urllib.parse import`, but also removed all the `import`.

**Comment by AraneaDev** [comment]
Having the same issue ... rolling back to 350635cdf82efcfb7720efd79bb7d66090428096 fixed it

**Comment by dirkr07** [comment]
Sadly on Synology I rely on the internal git mechanism to do updates/rollbacks.. guess I'll go through each file manually ?

**Comment by jangrewe** [comment]
There's already a newer commit that fixes all but 1 file, `sickbeard/webserve.py` line 49. I'm guessing that will follow soon. Right, @miigotu ? ;-)

**Comment by AraneaDev** [comment]
> Sadly on Synology I rely on the internal git mechanism to do updates/rollbacks.. guess I'll go through each file manually ?

Ouch ... no command line ? Otherwise it should just be a matter of running: 
`git reset --hard 350635cdf82efcfb7720efd79bb7d66090428096`  in ur SickChill folder

Otherwise wait patiently ;)

**Comment by jangrewe** [comment]
Yeah, but if you do that, SC may update to the currently broken commit again. ;-)

**Comment by dirkr07** [comment]
> > Sadly on Synology I rely on the internal git mechanism to do updates/rollbacks.. guess I'll go through each file manually ?
> 
> Ouch ... no command line ? Otherwise it should just be a matter of running:
> `git reset --hard 350635cdf82efcfb7720efd79bb7d66090428096` in ur SickChill folder
> 
> Otherwise wait patiently ;)

well yeah commandline but no git package afaik :)
Was able to go through the files manually though (only a few) so up and running again!

I'll wait for the commit now with the webserve.py included before I update again 😃

**Comment by miigotu** [comment]
Fixed, stupid for me to release that so fast even though it was a trivial change I just fucked it up. lol sorry.

**Comment by jangrewe** [comment]
@miigotu not quite, there's still `sickbeard/webserve.py` line 49 :-)

**Comment by miigotu** [comment]
@jangrewe nope, I fixed that before I made that comment ^

**Comment by jangrewe** [comment]
Ah, now the commits show up and can be pulled. Looks like Github had a bit of lag... Thanks! :-)

**Comment by miigotu** [comment]
NP, my machine might have lagged on the push =P
