### ISSUE TITLE
Unable to start after update

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#5143]
Updated to the latest version today. After the update SickChill won't start. Trying to start from the command line gives to following output.

Traceback (most recent call last):
  File "C:\SickRage\SickBeard.py", line 72, in <module>
    from sickbeard.webserveInit import SRWebServer
  File "C:\SickRage\sickbeard\webserveInit.py", line 17, in <module>
    from sickbeard.webserve import CalendarHandler, KeyHandler, LoginHandler, LogoutHandler
  File "C:\SickRage\sickbeard\webserve.py", line 49
    from requests.compat unquote_plus
                                    ^
SyntaxError: invalid syntax

Any tips on how to fix it?

**Comment by Tiwas** [comment]
Ok. Must have been a partial update or something. Did a new "git pull" and it seems to have fixed it.

**Comment by flyescke** [comment]
Same for the installation on my synology nas.

`Traceback (most recent call last):
  File "./SickBeard.py", line 72, in <module>
    from sickbeard.webserveInit import SRWebServer
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserveInit.py", line 17, in <module>
    from sickbeard.webserve import CalendarHandler, KeyHandler, LoginHandler, LogoutHandler
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 49
    from requests.compat unquote_plus
                                    ^
SyntaxError: invalid syntax
`

**Comment by Tiwas** [comment]
> Same for the installation on my synology nas.
> 
> `Traceback (most recent call last): File "./SickBeard.py", line 72, in <module> from sickbeard.webserveInit import SRWebServer File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserveInit.py", line 17, in <module> from sickbeard.webserve import CalendarHandler, KeyHandler, LoginHandler, LogoutHandler File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 49 from requests.compat unquote_plus ^ SyntaxError: invalid syntax `

Did you try a manual pull? That fixed thing for me.

**Comment by TimKras** [comment]
> ou try a manual pull? That fixed thing for me.

Can you give the commands you need to execute?

**Comment by miigotu** [comment]
Just git pull...
iirc on windows git is at C:\SickRage\git\bin\git.exe and the code is at C:\SickRage\SickRage I think
```bash
cd C:\SickRage\SickRage
C:\SickRage\git\bin]git pull
```

**Comment by miigotu** [comment]
This works on windows also:
`net stop sickchill && cd c:\SickChill\SickChill && c:\SickChill\Git\bin\git fetch origin && c:\SickChill\Git\bin\git reset --hard origin/master && net start sickchill`

**Comment by Tiwas** [comment]
net stop and net start will only work if sickchill is running as a service.

**Comment by miigotu** [comment]
net stop and net start work if it is installed with our installer, which is 99.9% of people who have it installed in windows.
