### ISSUE TITLE
I cant update on my synology

### ISSUE THREAD

**Issue by Kubilai12** [SickChill/SickChill#5147]
### Before submitting your issue:

Branch: master
Commit: 2a781a0356e952c3e25890286aade058083bd0c1
Version: v2018.10.16-3
Database Version: 44.0

2018-10-30 17:45:19 ThreadPoolExecutor-0_0 :: [2a781a0] git pull -f origin master returned : From https://github.com/SickChill/SickChill
 * branch                master     -> FETCH_HEAD
error: The following untracked working tree files would be overwritten by merge:
	contrib/images/background.jpg
	contrib/images/banner.xcf
	contrib/images/icon.png
	contrib/images/icon.xcf
	contrib/images/logo.xcf
	contrib/images/poster.xcf
	contrib/images/vector.bmp
	contrib/images/vector.svg
	contrib/images/vector.xcf
	contrib/images/vector2.bmp
	gui/slick/images/subtitles/subtitulamos.png
	gui/slick/images/subtitles/tusubtitulo.png
	lib/certifi-2018.10.15.dist-info/DESCRIPTION.rst
	lib/certifi-2018.10.15.dist-info/INSTALLER
	lib/certifi-2018.10.15.dist-info/LICENSE.txt
	lib/certifi-2018.10.15.dist-info/METADATA
	lib/certifi-2018.10.15.dist-info/RECORD
	lib/certifi-2018.10.15.dist-info/WHEEL
	lib/certifi-2018.10.15.dist-info/metadata.json
	lib/certifi-2018.10.15.dist-info/top_level.txt
	lib/cfscrape-1.9.5.dist-info/INSTALLER
	lib/cfscrape-1.9.5.dist-info/LICENSE
	lib/cfscrape-1.9.5.dist-info/METADATA
	lib/cfscrape-1.9.5.dist-info/RECORD
	lib/cfscrape-1.9.5.dist-info/WHEEL
	lib/cfscrape-1.9.5.dist-info/top_level.txt
	lib/chardet-3.0.4.dist-info/DESCRIPTION.rst
	lib/chardet-3.0.4.dist-info/INSTALLER
	lib/chardet-3.0.4.dist-info/METADATA
	lib/chardet-3.0.4.dist-info/RECORD
	lib/chardet-3.0.4.dist-info/WHEEL
	lib/chardet-3.0.4.dist-info/entry_points.txt
	lib/chardet-3.0.4.dist-info/metadata.json
	lib/chardet-3.0.4.dist-info/top_level.txt
	lib/enzyme-0.4.1.dist-info/INSTALLER
	lib/enzyme-0.4.1.dist-info/METADATA
	lib/enzyme-0.4.1.dist-info/RECORD
	lib/enzyme-0.4.1.dist-info/WHEEL
	lib/enzyme-0.4.1.dist-info/top_level.txt
	lib/idna-2.7.dist-info/INSTALLER
	lib/idna-2.7.dist-info/LICENSE.txt
	lib/idna-2.7.dist-info/METADATA
	lib/idna-2.7.dist-info/RECORD
	lib/idna-2.7.dist-info/WHEEL
	lib/idna-2.7.dist-info/top_level.txt
	lib/rarfile-3.0.dist-info/INSTALLER
	lib/rarfile-3.0.dist-info/METADATA
	lib/rarfile-3.0.dist-info/RECORD
	lib/rarfile-3.0.dist-info/WHEEL
	lib/rarfile-3.0.dist-info/top_level.txt
	lib/requests-2.20.0.dist-info/DESCRIPTION.rst
	lib/requests-2.20.0.dist-info/INSTALLER
	lib/requests-2.20.0.dist-info/LICENSE.txt
	lib/requests-2.20.0.dist-info/METADATA
	lib/requests-2.20.0.dist-info/RECORD
	lib/requests-2.20.0.dist-info/WHEEL
	lib/requests-2.20.0.dist-info/metadata.json
	lib/requests-2.20.0.dist-info/top_level.txt
	lib/urllib3/contrib/_appengine_environ.py
	lib/urllib3/util/queue.py
	lib/urllib3-1.24.dist-info/INSTALLER
	lib/urllib3-1.24.dist-info/LICENSE.txt
	lib/urllib3-1.24.dist-info/METADATA
	lib/urllib3-1.24.dist-info/RECORD
	lib/urllib3-1.24.dist-info/WHEEL
	lib/urllib3-1.24.dist-info/top_level.txt
Please move or remove them before you merge.
Aborting
Updating 2a781a035..c03f7cfdf

**Comment by miigotu** [comment]
cd to the folder, git reset --hard, git pull

**Comment by Kubilai12** [comment]
Sorry im newbie wich folder  ? cause git command not found

**Comment by miigotu** [comment]
@Kubilai12 in that folder you just did that command....  `/volume1/@appstore/git/bin/git fetch origin && /volume1/@appstore/git/bin/git reset --hard origin/master` and then restart the sickrage service

**Comment by miigotu** [comment]
#5146

**Comment by Kubilai12** [comment]
Thanks so much it s ok now

**Comment by Kubilai12** [comment]
I have same error for doing the new last commit update i try to do same command, but now i have this message :

 Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by miigotu** [comment]
You have to be in the SickChill dir.... same dir as SickBeard.py

**Comment by Kubilai12** [comment]
Ok sorry 

Thanks it s ok now
