### ISSUE TITLE
Failed to start, invalid syntax, after update?

### ISSUE THREAD

**Issue by risticsasa011** [SickChill/SickChill#5148]
Hello, 

after today's update my setup failed. When trying to start I get the following:

```
"Starting SickRage
Traceback (most recent call last):
  File "SickBeard.py", line 72, in <module>
    from sickbeard.webserveInit import SRWebServer
  File "/opt/sickrage/sickbeard/webserveInit.py", line 17, in <module>
    from sickbeard.webserve import CalendarHandler, KeyHandler, LoginHandler, LogoutHandler
  File "/opt/sickrage/sickbeard/webserve.py", line 49
    from requests.compat unquote_plus
                                    ^
SyntaxError: invalid syntax"
```

**Comment by mikemor22** [comment]
I've got a very similar issue, although I'm running on Windows:
![image](https://user-images.githubusercontent.com/30507142/47750877-47056900-dc88-11e8-93ff-3c5c6d99c0e8.png)

**Comment by risticsasa011** [comment]
I backed up my config.ini and sickbeard.db, bit the bullet, renamed /opt/sickrage to /opt/sickrage-old, ran **git clone https://github.com/SickChill/SickChill.git /opt/sickrage**, copied back the backed-up files, and started SickChill... Everything is working again... I don't know what happened...

**Comment by belinux** [comment]
Fixed on 67f13cf4c4c9f65df24c0bafc82dde927f71ab6a
Pull and restart service.

**Comment by mikemor22** [comment]
Thanks guys.  I also backed up data and reinstalled.  I don't really know what 'pull' means (git is still a bit of a dark art to me, as yet)
All's well that ends well though, I'm back on.  Now to try and work out how to get a new copy without reinstalling from scratch next time.

**Comment by whytewolf** [comment]
Pull means to run the command `git pull` while in the directory that is a git repo. This way you don't need to backup and reinstall to get a fresh copy you just pull the most recent version down from git. Which is what the update script is doing anyway with a little more panache.
