### ISSUE TITLE
SickChill vs SickRage

### ISSUE THREAD

**Issue by Nickduino** [SickChill/SickChill#5151]
I have an old installation of SickRage and now, my "Local branch is ahead of master. Automatic update not possible." Should I upgrade to SickChill ? Keep the old SickRage? What happened anyway?

**Comment by smilerz** [comment]
an old Dev trademarked SickRage and hijacked the github repository.  This is essentially SickRage renamed with the same dev team.

You can fix your install by:
1. Backup config using built in backup tool
2. Edit config.ini from https://github.com/SickRage/SickRage to https://github.com/SickChill/SickChill.git
3. Restart SickRage
4. If you get an error stating "No NZB/Torrent providers found or enabled for daily searches and backlog searches" restore the backup completed in Step 1.
5. Restart SickChill

**Comment by miigotu** [comment]
#4984 #5022 #5026

**Comment by Nickduino** [comment]
Thanks for the kind replies

> * Edit config.ini from https://github.com/SickRage/SickRage to https://github.com/SickChill/SickChill.git
> * Restart SickRage

Maybe I misunderstood...
I changed the line _git_remote_url = https://github.com/SickRage/SickRage.git_ to _git_remote_url = https://github.com/SickChill/SickChill.git_, in \SickRage\Data\config.ini and saved it, then restarted Sickrage. At startup, I still have the issue and the config.ini is back to its old form. It happened four times so I figure it's not user error (I mean I didn't forget to save the file four times in a row) but that SickRage was rewriting config.ini when restarting. So I tried to shutdown SickRage before modifying the config.ini but it wouldn't let me: it kept rebooting afterwards.

But i found a working solution in my case: I kept saving (like twice per second) the config.ini with the new address while SickRage was rebooting....and it finally asked me if I wanted to update. I now have a SickChill install :-)

**Comment by miigotu** [comment]
App has to be stopped before editing the ini

**Comment by Nickduino** [comment]
> You stop the service on windows

'thought about that but I didn't know the name of the service (it doesn't start with SickRage nor with Python). Still, I don't get why "shut off" only reboots the thing.


All in all, everything is well now :-)

**Comment by Nickduino** [comment]
Is it useful to have the shutdown option in the menu, then?

**Comment by miigotu** [comment]
I think its trivial and not hurting anyone to be there. If their service is not set to automatically restart then shutdown works just fine.

**Comment by Nickduino** [comment]
How can I configure the service not to restart, then?

**Comment by miigotu** [comment]
Edit it in windows, services.msc
It isnt part of SC

**Comment by Nickduino** [comment]
Thanks
