### ISSUE TITLE
Synology dsm 6 no install documentation

### ISSUE THREAD

**Issue by Trical** [SickChill/SickChill#5156]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:DMS 6
Browser:
What you did: trying to install
What happened: installation guide
What you expected: there is no guide provided and the custom package 404's for synology
Logs:
```
PASTE LOGS HERE
```

**Comment by BenjV** [comment]
Which package did you use and what did you expect as guide?
404 is a html page not found code, so I am missing any clue what you have done.

**Comment by Trical** [comment]
hello,
on this page: https://www.synology-forum.nl/sickbeard/working-forks-sickbeard-sickrage/105/

there is listed following info:
Synology:
(DSM 5) Add the Synocommunity Repo to your Synology, then follow : Installing --> this link doesn't have any info
(DSM 5 & 6) Or use BenjV's .SPK SickChill package --> this is a 404 

also I would add somewhere that if you install with dsm the default port is apparently 8083

**Comment by BenjV** [comment]
Use this link to download the package and do a manual install from the package center on your Nas.
The used port will be explained to you during installation.
https://github.com/BenjV/SYNO-packages/blob/master/SickChill%20noarch%20V1.1.spk

**Comment by miigotu** [comment]
@BenjV I've created a repo "sickchill-synology"
If you accept your invite you can work on the Synology package there, and update the wiki to the location and install guide, so you don't have to keep repeating yourself 😂

**Comment by miigotu** [comment]
He was using a full path in the "Share name" field in SC rather than the share name.
