### ISSUE TITLE
Feature proposal: Monitor downloads

### ISSUE THREAD

**Issue by mihaiblaga89** [SickChill/SickChill#5158]
Hey guys,

A quick thought: can we monitor a triggered download in utorrent/transmission? I know they have apis and it's doable, but is there anything that I haven't thought of stopping us for achieving this?

Not only display the progress / download instead of "Snatched", but also redownload with a different torrent. Example: I've started downloading a new series and about 40% of the episodes are missing due to low seeds and they are stuck in utorrent. My idea is to delete them in utorrent, Sickchill will periodically check for the progress and if it's missing it will trigger another search for a different torrent .

I'm down to work on this feature and submit a pull request if you don't have anything against it.

**Comment by WebSpider** [comment]
This seems useful to me!

**Comment by miigotu** [comment]
@mihaiblaga89 it has been a dream of ours for a long time to do this, including deleting the files after they have been post processed and reached the seeding target for that provider as well.  If you have the skill to do this, we would love if you could do it! Warning, it is quite a bit of work or I would have done it already. I'd say start with one client and then extend to all of our supported clients.

**Comment by mihaiblaga89** [comment]
@miigotu Just started working on it. I have a new task scheduled only if torrents are enabled and it's configured to use a "supported" client. Any slack channel or something to quickly ask questions if I have any?

**Comment by miigotu** [comment]
Only me on slack and im not always around: https://join.slack.com/t/sickchill/shared_invite/enQtNDcxMjU3NTYwODIwLTFmYTdkMWQ5MDQwNzFhY2E2YzdkNTk0OWVkNTFkNzk4ZDBmMzMxYWI0OGZmZjRjMmU0YzdiNzZlYTM4NTdmY2U

We also have IRC on freenode #sickchill, also SickChill on gitter, telegram, and discord

**Comment by mihaiblaga89** [comment]
Perfect. Will let you know once it's ready. I'll be working on utorrent and transmission.

**Comment by WebSpider** [comment]
You might need db changes to be able to track per file download progress / seed ratio etc. If so, please check out #5167 so this can be added into schema version 45.

**Comment by miigotu** [comment]
@mihaiblaga89 I am adding the torrent hash to the sickbeard.tv_episodes, sickbeard.history, cache.<provider>, failed.failed, and failed.history tables so you can match the hash from snatched episodes in the client. It will also support more than one client, because I am also adding .client to the tables so that you know whether the torrent with that hash or nzb with that guid is in one client or nzb downloader or another. Once it is removed from the client the client is removed from the db, so you can filter the sql based on that `client` column and only check for downloads that are actually in a client.

**Comment by mihaiblaga89** [comment]
@miigotu that would be awesome, because most of my problems lie on matching the episode with the torrent. Any ETA on that? Or a branch that has these changes already?

**Comment by miigotu** [comment]
#5167

**Comment by miigotu** [comment]
I only added the columns in sickbeard.db so far, and havent pulled them into the show or episode objects yet

**Comment by roopesh** [comment]
Is there a framework?  I'd love to include SABnzbd.
