### ISSUE TITLE
[Question] Python 2.7 EOL

### ISSUE THREAD

**Issue by belinux** [SickChill/SickChill#5160]
Considering the The End Of Life date (EOL, sunset date) for Python 2.7 [(pep-0373)](https://legacy.python.org/dev/peps/pep-0373/)
Is there any plan on moving to Python 3?

Branch/Commit: Master
OS: archlinux

**Comment by WebSpider** [comment]
Given that we use encodingkludges in very many places, bringing this to Python3 will most likely require some pretty big rewrites, with no current plan in place.

Personally, I am in favor of redoing the core of the app completely, getting rid of the legacy code we have laying around from being a SickBeard fork. 

It would be cool to have this finished in 2 years indeed ;)

**Comment by belinux** [comment]
I agree on your personal opinion, it would be great to redo the core.

**Comment by miigotu** [comment]
Definitely a more robust rewrite in the works, which has made it past the idea stage and into a skeleton.
