### ISSUE TITLE
Feature Request: add plex url scheme on ios

### ISSUE THREAD

**Issue by chrillep** [SickChill/SickChill#5164]
Feature Request: add plex url scheme on to ios

Add ability to tap on items to either view or play in plexapp for ios.
could be added if Plex notifications are enabled.
would have to talk to plex web api to get metadata for the item.

resource for api-request -> https://support.plex.tv/articles/201638786-plex-media-server-url-commands/
resource for url-scheme on IOS -> https://forums.plex.tv/t/deep-links/205583

**Comment by mihaiblaga89** [comment]
I don't think this will be added but I stand to be corrected. Sickchill is for downloading and managing, not playing. Had the same idea a couple of years or so ago but to send it to Chromecast but it was dismissed.

**Comment by miigotu** [comment]
Sending to chromecast is a little different, you have to serve the file from SC then. For plex, you need to either add a row to the db to store the plex path or query it dynamically when the link is clicked. Not a super hard feature tbh

**Comment by miigotu** [comment]
Unstale

**Comment by chrillep** [comment]
Does the plex notification get any data in the callback?
