### ISSUE TITLE
transmission RPC URL

### ISSUE THREAD

**Issue by buccinator** [SickChill/SickChill#5166]
using latest stable git sickchill. since the whole sickrage switch over to sickchill, it wont connect to transmission. Errno 404 not found. looks like the RPC param is being ignored or clobbered by some default etc

it passes /transmission/web/rpc regardless of what is set when it should default to /transmission/rpc

$ nc -l 127.0.0.1 9091
GET /transmission/web/rpc HTTP/1.1
Host: 127.0.0.1:9091
Connection: keep-alive
Accept-Encoding: gzip,deflate
Accept: */*
User-Agent: SickChill.CE.1/(Windows; 10; 43c6631e-e084-11e8-b427-68a3c44a0c3c)
Authorization: Basic ************

------------

$ nc 127.0.0.1 9091
GET /transmission/web/rpc HTTP/1.1
Host: 127.0.0.1:9091
Connection: keep-alive
Accept-Encoding: gzip,deflate
Accept: */*
User-Agent: SickChill.CE.1/(Windows; 10; 43c6631e-e084-11e8-b427-68a3c44a0c3c)
Authorization: Basic ************

HTTP/1.1 404 Not Found
Server: Transmission
Date: Sun, 04 Nov 2018 23:14:42 GMT
Content-Length: 88
Content-Type: text/html; charset=ISO-8859-1

<h1>404: Not Found</h1>C:\Program Files\Transmission/web/rpc (No such file or directory)

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by buccinator** [comment]
bizzare, because ive had this issue since the change over, i decided to edit transmissions settings.json to rpc-url to be /transmission/web/rpc, which gave an authentication error. i then reverted back and removed rpc-url and put the RPC URL param back into sickrage with transmission/rpc and it started working again. nfi.

**Comment by miigotu** [comment]
It works and has always worked for me. The one save button on that page doesn't work is the issue
