### ISSUE TITLE
DB Changes

### ISSUE THREAD

**Issue by miigotu** [SickChill/SickChill#5167]
Torrent hash / NZB Guid - To keep track of torrents added to clients and remove them after they have completed seeding, to correctly handle failed downloads and not snatch them again, and enable min/max sizes for a download, and scene names for seasons

~~sickbeard.tv_episodes.hash~~
~~sickbeatrd.tv_episodes.url~~
~~sickbeard.tv_episodes.client (client name, if empty already removed from client)~~
~~sickbeard.tv_shows.min_size~~
~~sickbeard.tv_shows.max_size~~
~~sickbeard.tv_shows.size~~
sickbeard.movies (TBD layout - title, size, min_size, max_size, quality, allowed_quality, preferred_quality, location, client, provider, snatch_date, release_date, +)
sickbeard.qualities - (combined_quality, min_size, max_size) - For global setting size limits for qualities
~~sickbeard.history.type (movie/episode/etc)~~
~~sickbeard.history.hash~~
~~sickbeard.history.url~~
failed.history.hash
failed.history.url
failed.history.type (movie/episode/etc )
failed.failed.hash
failed.failed.url
failed.failed.type (movie/episode/etc )
cache.\<provider\>.hash
cache.\<provider\>.type (movie/episode/etc )

**Comment by miigotu** [comment]
@mihaiblaga89  Lets do all of the DB upgrades necessary for this and all other db change dependant features in one shot. LMK if I missed any that I should add to the list
@SickChill/collaborators @SickChill/moderators

**Comment by mihaiblaga89** [comment]
@miigotu sorry, missed that comment. Quick question, I see that in your commit you changed the queries from `MainSanityCheck`. When I was experimenting with this I just created another class as you did with `BigDBUpdate` with a `test` of `.hasColumn()`and that was it. It worked perfectly without needing to change `MainSanityCheck `. Am I missing something? I'll make another branch and start helping you on this one because it's useless to work on mine before you finish this.

**Comment by miigotu** [comment]
MainSanityCheck is done when creating a new database, and there are a few more mods I should make up there. In essence, that method shows us a complete schema in one place if nothing else.

**Comment by WebSpider** [comment]
It may make sense to fix https://github.com/SickChill/SickChill/blob/master/sickbeard/tv.py#L1173 as well

**Comment by miigotu** [comment]
Ill add that later, as well as implementing the use of some of these new columns if I can awhile.

**Comment by WebSpider** [comment]
U stale.
