### ISSUE TITLE
Link to Asustor APK on Dropbox is dead

### ISSUE THREAD

**Issue by brendanheyu** [SickChill/SickChill#5169]
Hi Folks,

Very much like to get my asustor NAS up and running.

Any chance to get a working URL to the APK?

Thanks!

**Comment by miigotu** [comment]
I will see about adding an asustor pkg, I have added a repository to start this in. If you can find a skeleton of a source package that would help.

Do you happen to have the old package?

**Comment by brendanheyu** [comment]
I wish I did!

I'm looking at my sickrage install currently warming me that: "Local branch is ahead of master. Automatic update not possible."

If I had that SickChill build I'd be much happier :)

Thanks!

**Comment by Se7enSyns** [comment]
Where can I find instructions to change the git remote and git fetch and git reset.  I want to get away from sickrage as soon as possible, but thought I was having to wait until an asustor build was ready before I could get on sickchill.
