### ISSUE TITLE
Feature Request : ability to enable/disable daily search by series

### ISSUE THREAD

**Issue by pipopop** [SickChill/SickChill#5170]
I think this option can be appreciate only by non-English user.
Today, we can modify the options of backlog search and daily search in the "general search settings". Daily search isn't very useful for people who wants episode in another language because most of time, the translation is release 6 or 12 months after the original release (except for Netflix).
So it could be more efficient if we can modify the daily search by series or by Network.

Thanks for all !

**Comment by miigotu** [comment]
This isnt possible. Daily searcher does not search for specific shows or episodes, and does not send a search string to a provider. It simply hits each provider that is enabled for daily searches and asks "what new downloads do you have"
