### ISSUE TITLE
fix for failed downloads being treated as completed.

### ISSUE THREAD

**Issue by battamo** [SickChill/SickChill#5174]
Hi,

I just realized why failed downloads are often being treated as completed.

When a download from Sabnzbd fails, sabnzbd , passes the path to the temporary folder instead of the path to the folder with completed downloads. The temporary folder contains the left over files, that couldn't be completed, which are then post processed. It would be simple to check if the path being passed is within the download folder or the temp folder and fail the download accordingly.

I just posted it on nzbToMedia as well.
https://github.com/clinton-hall/nzbToMedia/issues/1091

**Comment by miigotu** [comment]
This is solely an nzbtomedia issue, because SickChill does not use any temp folders.
