### ISSUE TITLE
DB ravaged by Sickrage, can it be fixed?

### ISSUE THREAD

**Issue by tommitytom** [SickChill/SickChill#5175]
I upgraded "SiCKRAGE" not knowing that the whole git history had been rewritten.  I didn't realise until my database had been changed and the login screen appeared.  I have switched my docker containers to SickChill but now I get this error:
```
sickchill_1     | 13:01:27 INFO::MAIN :: Backing up database before upgrade
sickchill_1     | 13:01:27 INFO::MAIN :: Proceeding with upgrade
sickchill_1     | 13:01:27 INFO::MAIN :: Add minor version numbers to database
sickchill_1     | 13:01:27 INFO::MAIN :: Updated to: 43.1
sickchill_1     | 13:01:27 INFO::MAIN :: Backing up database before upgrade
sickchill_1     | 13:01:27 INFO::MAIN :: Proceeding with upgrade
sickchill_1     | 13:01:28 ERROR::MAIN :: Your config version (11) has been incremented past what this version of SickChill supports (8).
sickchill_1     |                 If you have used other forks or a newer version of SickChill, your config file may be unusable due to their modifications.
```

I didn't think to backup before I upgraded - are automatic updates kept anywhere?  Can I fix this mess?!

**Comment by miigotu** [comment]
back up your whole data folder someplace safe.
Then in the original location, make sure sickrage is stopped and rename config.ini.v8 to config.ini (config.ini.v7 if v8 doesn't exist) and start the app again.

**Comment by tommitytom** [comment]
So it now seems to load just fine, but none of my shows are in there.  Does the new sickrage change the actual database?

**Comment by tommitytom** [comment]
Looks like all database backups were actually deleted in the upgrade.  Man that guy is an arsehole.  Also I'm pretty disappointed in GitHub, the security implications of switching out a repo like that without warning are numerous!

**Comment by WebSpider** [comment]
We are working on mechanisms where we no longer rely on a single repository, but need a majority vote of a list of known mirrors.

We never thought this would be needed to ensure the existence of open source software :D
