### ISSUE TITLE
Trakt sync watchlist - All shows are added to watchlist in trakt

### ISSUE THREAD

**Issue by Jelmerb** [SickChill/SickChill#5179]
Branch/Commit: master/61e699ea0a706d453437cc5650fdc201e3188d65
OS: MacOS 10.14.1
Browser: Safari 
What you did:
I enabled Trakt sync watchlist option
What happened:
All my shows are added to Trakt watchlist
What you expected:
I expected only the shows with wanted or snatched episodes would be added to the watchlist. This is I think the expected behaviour. For instance, I have every downloaded and watched every episode from Silicon Valley. Still it is added to the watchlist. 

Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
I think the opposite is actually the intended behavior, to add every episode you actually have downloaded in the watchlist.
However, the trakt watchlist/collections are being used for a totally unintended purpose by SC.  If anything, you should be using plex or kodi or whatever to use watchlists for items you have watched or not watched.

This feature may be totally removed, and if anything it should be removed and rewritten by someone who understands the watchlists on trakt better.

**Comment by Jelmerb** [comment]
Thank you for your quick response :) 

No, I disagree. The watchlist is intended for keeping track of shows you are planning to watch. This is from the official Trakt blog. [link](https://blog.trakt.tv/manage-your-watchlist-personal-lists-9e4fdc521e3d)

> Your watchlist is built in list to keep track of everything you want to watch. Once you watch an item from your watchlist, it automatically gets removed. Watching 1 episode of a show or season will remove that item as well. Your calendars and progress are automatically kept up to date with what you’re watching, no need to keep it on your watchlist.

The watched status of shows and episodes is something different in Trakt and is indeed handled by something like Kodi or Plex. This is also what I use Kodi for like you said. Most of the downloaded episodes I have already watched so there is no need for them to be in my watchlist.

It almost works perfectly, the only thing is that whenever a show gets removed from my Trakt watchlist by SickChill because an episode is downloaded (like it should) it gets added back later by SickChill somehow. I think that behaviour is incorrect. I wish I could help you with it, but I don't have any experience in Python. I'll just ignore it for now :) 

Thank you for all your hard work on this amazing piece of software. Have a nice weekend.

**Comment by miigotu** [comment]
I think that the behavior SHOULD be this:
Add everything to your collection, and then when a file is post-processed it should be added to your watchlist (aka a new episode is ready to be watched)
If you delete a show from SC, it should be removed from your collection, and all episodes for that show should be removed from your watch list.

The biggest problem with SC, is that there is a feature that allows you to add a show to your watchlist, and then SC will add the show and try to download it. This causes a terrible situation where you cannot delete a show in SC because it keeps being added back from the watchlist.

**Comment by Jelmerb** [comment]
I think the Trakt collection is where al the downloaded episodes are 'collected'. This list is meant for people to see which episodes they can actually watch because they have the file on their system. The watchlist is just for future planning. If I have the file on my system or not is besides the point. 

> Once you watch an item from your watchlist, it automatically gets removed. Watching 1 episode of a show or season will remove that item as well.

SickRage doesn't know if I have watched an episode or not. So even though Trakt removes a show because I have watched 1 episode of that show Sickrage will automatically add the show to my watchlist again which I think is wrong.

That terrible situation I encountered one time. I think it could be avoided by just importing a show from the Trakt watchlist to SickChill (and setting no episodes to wanted, only the first episode or all episodes) and removing the show immediately from the Trakt watchlist. If the user then decides to delete the show, the show won't get picked up from the watchlist next time SickRage checks Trakt. I forgot this problem existed. I think I'll stop using the watchlist in SickRage altogether. 

I understand if this is not priority, especially when the code is old and bad. I thought, I'll just give my two cents on the matter.

**Comment by Jelmerb** [comment]
In my opinion, this is how you could look at it. Trakt watchlist and SickChill show list are one and the same. They are both a list of shows that you are planning to watch, the difference being that SickChill can actually download the shows. When I am on holiday for example and someone tells me to watch a show I add it to my Trakt watchlist, because I either I can't reach SickChill at home or it is just faster. Now when I am back at home, I can go to SickChill and add the shows from my Trakt watchlist I am planning to watch, or (what I think the behaviour should be) SickChill can move the show from my Trakt watchlist to my Sickchill show list. Because now the show is in SickChill (and will be downloaded) I have no use for it to be in my Trakt watchlist. I hope this makes sense.

**Comment by miigotu** [comment]
Like I said, everyone has a different idea of how it should work with SC, and most of them are incorrect. The code is broken and because it is so ambiguous and difficult to understand it is very unlikely to be fixed.  If it were a clear idea it might be different, but it isnt. Too many people confuse the watchlist with a personal list and use it for more than one purpose.
There is no reason to use trakt with SC, send yourself a note and add it in SC when you get home, and let your media player use trakt by itself.
