### ISSUE TITLE
[Request] opt-out/Disable "Trackers list" Function

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [SickChill/SickChill#5186]
Branch/Commit: 61e699ea0a706d453437cc5650fdc201e3188d65

Hi, Since I use qB it auto adds trackers for me. And every time I delete the Trackers from Trackers list in SC it keeps coming back with trackers. is there a way to stop it from doing this? as I don't want to double up on trackers...

**Comment by miigotu** [comment]
Use the other save button, they should stay set at empty
