### ISSUE TITLE
Packfile does not match index

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#5187]
[SickChill Problem.zip](https://github.com/SickChill/SickChill/files/2584936/SickChill.Problem.zip)

Initially updated to SickChill without a problem.  But lately have been seeing error messages in the log of the above type.

On the "Info" page I see:
`Branch: master 

Commit: 61e699ea0a706d453437cc5650fdc201e3188d65 

Version: error: packfile .git/objects/pack/pack-648ad4002d7816c4c8c0d701da00d3546116bfef.pack does not match index error: packfile .git/objects/pack/pack-648ad4002d7816c4c8c0d701da00d3546116bfef.pack does not match index error: packfile .git/objects/pack/pack-648ad4002d7816c4c8c0d701da00d3546116bfef.pack does not match index error: packfile .git/objects/pack/pack-648ad4002d7816c4c8c0d701da00d3546116bfef.pack does not match index error: inflate: data stream error (invalid distance too far back) error: failed to read object 7d88939667bd53d793b3bc766c17f2fe52bfe96a at offset 3915 from .git/objects/pack/pack-74a95651ee04a4b07e0c867b0e9d65cfcf61dc48.pack fatal: packed object 7d88939667bd53d793b3bc766c17f2fe52bfe96a (stored in .git/objects/pack/pack-74a95651ee04a4b07e0c867b0e9d65cfcf61dc48.pack) is corrupt 
Database Version: 44.0 `

And when I try to do a "manual" update, the attached text file shows the output.

In config.ini, I have: `git_remote_url = https://github.com/SickChill/SickChill.git`

Please help.

**Comment by miigotu** [comment]
Looks like you have bad data in the git dir from the bad version. Try a fresh clone.

**Comment by miigotu** [comment]
If you have it installed using SickChill installer, then you should open an elevated command prompt and do this:
```
net stop sickchill
cd C:\SickChill
del /f /s /q SickChill
C:\SickChill\Git\bin\git clone https://github.com/SickChill/SickChill.git SickChill
net start sickchill
```

If you had installed with SickRage installer, you should do a backup, uninstall the whole app, and use our installer and then restore your backup.
Or, you could manually do it (even though backup, uninstall SickRage, install SickChill, restore is the best way)

```
net stop sickrage
cd C:\SickRage
del /f /s /q SickRage
C:\SickChill\Git\bin\git clone https://github.com/SickChill/SickChill.git SickRage
net start sickrage
```

Editing your config.ini does nothing.

**Comment by ronrosenfeld** [comment]
**Thank you**,  miigotu.

I used your recommended method to use your installer.  Everything worked ok but in the process of uninstalling SickRage, I managed to also uninstall my backup :-(   *Don't ask*

But, fortunately, I remembered most of my settings and was able to use the "add existing shows" option to restore the database.

All seems well now, with none of those errors in the log.

Ron
