### ISSUE TITLE
Anime - Show tagged as Anime but search still uses SxxExx instead of absolute number

### ISSUE THREAD

**Issue by dirkr07** [SickChill/SickChill#5188]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Synology DS
Browser: Chrome
What you did: Searched for an episode from an anime show
What happened: The episode searched based on the SxxExx format
What you expected: that the episode would be searched based on the aboslute number
Logs:

Either I'm missing an option that I need to enable but even though i have the show marked as anime it still searches on the Season/Episode naming

**Comment by miigotu** [comment]
Logs...
