### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: u'C:\\SickRage\\Data\\Logs\\sickchill.log'

### ISSUE THREAD

**Issue by CrazySwed** [SickChill/SickChill#5189]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@61e699ea0a706d453437cc5650fdc201e3188d65
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [61e699e] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 5283, in viewlog
    data = sickbeard.logger.log_data(min_level, log_filter, log_search, max_lines)
  File "C:\SickRage\SickRage\sickbeard\logger.py", line 519, in log_data
    with io.open(_log_file, 'r', encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: u'C:\\SickRage\\Data\\Logs\\sickchill.log'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment]
Can you please let us know what the history of this install is, and what you did that led to this error?
Thanks!
