### ISSUE TITLE
Torrent9 new address

### ISSUE THREAD

**Issue by Kubilai12** [SickChill/SickChill#5190]
I don t know what happens but i think Torrent9 change again adresse, but i can t dowload on it ?

Did domeone find a way ?

**Comment by pluzun** [comment]
Hi @Kubilai12, as I can see on Twitter, torrent9.ch don't seem to be the real one. (e.g. The search engine is not the same as before)
I'm looking for the new one before editing the provider address.

**Comment by Kubilai12** [comment]
the tracker is different right ? cause i can download on this site

**Comment by Kubilai12** [comment]
it s seems torrent9 change again i have this one now : https://www.torrents9.pw/

**Comment by sizzlingkenny** [comment]
while searching on google I have found the working torrent9 link https://www.torrent9.icu/ 
it was taken from here https://postfreelinks.xyz/Torrents/torrent9-cz-ne-fonctionne-pas-torrent9-alternatives-mirror-and-proxy-6 
it has almost all the torrents which was wiped out from torrent9.cz recently.
It works good for me lets see if it works good for you.
