### ISSUE TITLE
Posters Not in Alphabetical Order

### ISSUE THREAD

**Issue by amandalfrench** [SickChill/SickChill#5198]
Hello,
I added some shows to sickchill and they are not in alphabetical order despite having it sort by name. Is there anyway I can fix this?
![help](https://user-images.githubusercontent.com/35348868/48867830-59a52680-ed8c-11e8-8860-2a0fed63d74a.JPG)

**Comment by miigotu** [comment]
Those are in alphabetical order, left to right row by row. If you want things like `the` to be in the T's, disable the setting sort articles

**Comment by amandalfrench** [comment]
How would turning that setting off affect Altered Carbon from being after American Dad?

**Comment by miigotu** [comment]
Ha, I didn't notice that one. Idk why it is doing that I can look later

**Comment by miigotu** [comment]
I think you need to force a refresh on Altered Carbon maybe, this issue doesnt happen here:
![image](https://user-images.githubusercontent.com/390379/48924028-b118c480-ee68-11e8-9a99-15b72f2f3395.png)

**Comment by miigotu** [comment]
I wonder if the js flow means to put altered carbon before american dad there, and it is treating american dad as if it were in the next (3rd row) row because it is pushed down due to the missing poster for the abc murders??

**Comment by amandalfrench** [comment]
Sorry, Thanksgiving has been crazy. I tried refreshing and updating Altered Carbon and American Dad and that didn't work. Where would i check the js?

**Comment by miigotu** [comment]
You won't see the issue in the js, it's in a 3rd party boostrap lib. I'll try to get the poster size corrected, bit this is a minor issue

**Comment by miigotu** [comment]
I cannot find why it is making the generic sickchill poster the wrong size when a show is missing a poster. That is when the ordering gets messed up because it confuses the JavaScript "flow" positioning. If and when we get another js guru or @OmgImAlexis can look we will address it, but this is such low priority that I am going to close this.
