### ISSUE TITLE
Searching for Specials

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#5200]
Would it be possible to enhance the search for specials?

There isn't any standardised naming for specials among the release groups so I was wondering if the search could be enhanced to include:

S(xx)E00 (episode name)
S(xx)X00 (episode name)

where xx is a wildcard.
Would that be possible? I know searching by episode name may miss a few releases but currently searching by S00E(xx) hardly returns any results and this should improve matters.

Many thanks :)

**Comment by mgaulton** [comment]
I'd also like to see a "when adding show, mark special as wanted if default status is wanted" sort of thing.

**Comment by ConfusedTA** [comment]
I've found that Specials are often indexed by name, so using the name as an additional search parameter may improve success rate of acquiring.
