### ISSUE TITLE
requirewords

### ISSUE THREAD

**Issue by ConnectOL** [SickChill/SickChill#5211]
Hello,
sorry, but since the version (v2018.11.07-1), the "keywords" do not work as before!
I have a lot of problems on several series since (before all worked without problem, more than 2 years of use).
The specific words **for a series**, are no longer used.
Are used those in the general settings.

here I ask THAT `French` for the **Camping** series and it does not do it (unlike previous versions) :
```
SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Release: Camping.US.S01E06.Carleen.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv] doesn't contain any of multi, vfi, vf, vff, truefrench, french, francais, vostfr, vostf, subfrench, ignoring it
2018-11-19 18:43:21 INFO     SEARCHQUEUE-DAILY-SEARCH :: [ArcheTorrent] :: Found result Camping.US.S01E06.VOSTFR.WEB.H264-TAT at https://www.archetorrent.com/download.php?id=115829&name=Camping.US.S01E06.VOSTFR.WEB.H264-TAT
2018-11-19 18:43:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [ArcheTorrent] :: Quality of Camping.US.S01E06.VOSTFR.WEB.H264-TAT is SDTV
2018-11-19 18:43:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Camping.US.S01E06.VOSTFR.WEB.H264-TAT from ArcheTorrent
2018-11-19 18:43:23 INFO     SEARCHQUEUE-DAILY-SEARCH :: Executing command [u'/usr/syno/bin/synodsmnotify', u'@*****istrators', u'Started Download', u'Camping (US) - 1x06 - Carleen! - SDTV from ArcheTorrent']
```
**Search parameters (configuration)**
![image](https://user-images.githubusercontent.com/44948834/49096637-405c1880-f26b-11e8-9788-150ee9f723c4.png)

**Edit Series (Advanced Settings)**
![image](https://user-images.githubusercontent.com/44948834/49096835-b496bc00-f26b-11e8-89c4-4ea01ef2ec31.png)
_note: this option replaces the mandatory words globally ignored!_

**Comment by WebSpider** [comment]
Possibly related to #5153 (0d4863918a8bda7dc1724f3a2ae884b6ed37d197)

**Comment by miigotu** [comment]
Please don't open duplicates. We already discussed this in another issue.

**Comment by miigotu** [comment]
You can comment on existing issues and add information, just like you did there with your bold lettering.

**Comment by ConnectOL** [comment]
I'm already struggling enough with English, why do not you just answer this question :
why now he gets a file with the word `vostfr` (present in the global list)
`Downloading Camping.US.S01E06.VOSTFR.WEB.H264-TAT from ArcheTorrent`
while I ask EXCLUSIVELY the word `french` and nothing else (specifically for this series)

**Comment by miigotu** [comment]
Bud, please don't use language as an excuse to not use common sense. I have commented in the other thread, and asked for more information from you and your friend. Unless I am missing something the code does exactly the same thing as it did before, and until I can reproduce the problem in programmers terms it doesnt exist
