### ISSUE TITLE
Formula 1

### ISSUE THREAD

**Issue by Nickduino** [SickChill/SickChill#5217]
Since both sites reference it, I was expecting to be able to add it to my SickChill shows but I only get a "** 403: Series Not Permitted **" result
IMDb: https://www.imdb.com/title/tt8945320/releaseinfo?ref_=tt_dt_dt
TheTVDB: https://www.thetvdb.com/series/formula-1

Alternatively, would it be possible to manually add a series? i.e. create a list of all episodes I want to download

**Comment by WebSpider** [comment]
Adding Formula 1 to SC is not just adding the show, the issue with sports in general is that the scene naming is poorly implemented at best. Or at least, it was 2 years ago, when I looked at implementing sports handling in SC.

Thanks for the reminder tho, need to look into that again to see if the scene has improved.

**Comment by WebSpider** [comment]
I'm not in favor of handling sports on a one-by-one basis, it would simply be (over) chaotic and error-prone.

The idea of having a show that uses no indexer for episode information, but uses user input for this seems more feasible to me

**Comment by Nickduino** [comment]
> The idea of having a show that uses no indexer for episode information, but uses user input for this seems more feasible to me

Cool :-)

**Comment by Nickduino** [comment]
Hum...have you guys given it some more thought?

**Comment by Nickduino** [comment]
The Formula 1 season has started again,  I'd love to get the feature

**Comment by knockreff** [comment]
the sports DB is a possible API to use to pull the data

**Comment by Nickduino** [comment]
Good suggestion

**Comment by psyciknz** [comment]
Actually I notices the thetvdb has formula 1 in it.  I see a sports scene regex in the code.  But this works better:
```
^(?P<series_name>.*?(UEFA|MLB|ESPN|WWE|MMA|UFC|TNA|EPL|NASCAR|NBA|NFL|NHL|NRL|PGA|SUPER LEAGUE|FORMULA1|FIFA|NETBALL|MOTOGP).*?)[. _-]+
((?P<series_num>\d{1,4})[. _-]+)?
     ((?P<air_date>(\d+[. _-]\d+[. _-]\d+)|(\d+\w+[. _-]\w+[. _-]\d+))[. _-]+)?
     ((?P<extra_info>.+?)((?<![. _-])
     (?<!WEB)-(?P<release_group>[^ -]+([. _-]\[.*\])?))?)?$
```

What is also missing, that I notice with formula 1, is that they dont tend to post episode numbers (that the tvbd lists). But the name of the event eg: Formula1.2020.Bahrain.Grand.Prix.Qualifying.720p50.HDTV.DD2.0.x264-wAm
"Bahrain.Grand.Prix.Qualifying would appear in extra info. And this coul dbe used for matching the the tvdb for episode naming.

The only other request I'd want for this case is to only choose "episodes' of a certain type, eg, Race and Qualifying.  But if I had to a manuals change from wanted to skipped would work.

**Comment by Nickduino** [comment]
> What is also missing, that I notice with formula 1, is that they dont tend to post episode numbers (that the tvbd lists). But the name of the event eg: Formula1.2020.Bahrain.Grand.Prix.Qualifying.720p50.HDTV.DD2.0.x264-wAm
> "Bahrain.Grand.Prix.Qualifying would appear in extra info. And this coul dbe used for matching the the tvdb for episode naming.

It depends on who uploaded it. Fairly often you see which round it is (eg 2020x14, 2020x15, ...) Example : https://www.ettvcentral.com/torrents-search.php?search=formula


> The only other request I'd want for this case is to only choose "episodes' of a certain type, eg, Race and Qualifying. But if I had to a manuals change from wanted to skipped would work.

True

**Comment by psyciknz** [comment]
Ok.   On nzd they don’t.    Releases just tend to be
Formula1.2020.Bahrain.grand.prix.race.1080-wam
Or
Formula1.2020.Sakir.practice.1.1080-wam

**Comment by Nickduino** [comment]
> If someone was torrent based

Yeah, that's me :-)
