### ISSUE TITLE
Sickrage removed sickchill installed but has wrong port

### ISSUE THREAD

**Issue by m3rbmw** [SickChill/SickChill#5220]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
The port is set with the settings, and possibly by the installer? Idk if it's exposed in the installer but just change the port to whatever you want in general settings.

**Comment by m3rbmw** [comment]
I am not a computer person and I have no idea how to follow any of the instructions that I have been able to find because I am a "dummy".

I update Sickrage on my Synology device using the update offered and the discovered I had been hijacked. Soooo Angry. I then removed sickrage and managed to install SickChill but it attempt to run on the SickRage port.

I am completely at a loss as to how to fix this.

Can someone please provide some instructions in dummy speak?

The file I downloaded and installed is: SickChill noarch V1.1.spk as per the instructions I have been able to find and I have had it suggested I edit the install to see if the port is specified but I do not even know how to do this.

Any assistance will be greatly appreciated.
