### ISSUE TITLE
Not finding show

### ISSUE THREAD

**Issue by FlyingPersian** [SickChill/SickChill#5222]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master/c0e676570fbffe964c57e8e089b8cab7b4b2f668 
OS: FreeNAS (iocage jail)
Browser: Firefox 63.0.3 (64 Bit)
What you did: Search to add existing show Travelers (https://www.thetvdb.com/series/travelers-2016)
What happened: Three shows returned for Travelers, neither is the correct one. Tried using the ID on thetvdb, didn't help. Same result if I use "Add Show" instead of "Add existing show".
What you expected: To find the correct show. 
Logs: Doesn't really state anything except that it searched. Debug is on:

2018-12-01 17:46:15 DEBUG    ThreadPoolExecutor-0_1 :: Searching for Show with searchterm(s): ['travelers'] on Indexer: theTVDB

**Comment by miigotu** [comment]
You have to search `Travelers (2016)`

**Comment by FlyingPersian** [comment]
I'll be damned! Never been help so quickly, let alone on github :D Thanks!!
