### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/304219/actors.xml

### ISSUE THREAD

**Issue by cadatoiva** [SickChill/SickChill#5224]
### INFO
Python Version: **2.7.15 (default, May 18 2018, 10:49:46) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]**
Operating System: **FreeBSD-11.2-RELEASE-p4-amd64-64bit-ELF**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@c0e676570fbffe964c57e8e089b8cab7b4b2f668
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [c0e6765] Unable to connect to theTVDB while creating meta files - skipping - error HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/304219/actors.xml
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment]
Thetvdb is currently not available. Please try again later :wink:
