### ISSUE TITLE
Magnum P.I. not loading

### ISSUE THREAD

**Issue by MSP85D** [SickChill/SickChill#5230]
I don't know if this is the correct place to raise this but the new Magnum P.I. series is not loading into the show. I have both the old Magnum, P.I. and the new Magnum P.I. shows listed in Sickchill.

2018-12-04 10:56:19 INFO POSTPROCESSOR-MANUAL :: This show isn't in your list, you need to add it to SR before post-processing an episode
2018-12-04 10:56:07 INFO POSTPROCESSOR-MANUAL :: Processing /volume1/Video Files/Downloads/Magnum.P.I.2018.S01E01.720p.HDTV.x264-AVS.mkv (None)

If I try it without the 2018 it loads into the old Magnum, P.I. series.

**Comment by miigotu** [comment]
Add "Magnum P.I. (2018)" as a scene exception for the right show.

@WebSpider want to add that scene exception? I'm on my phone

**Comment by MSP85D** [comment]
You are a Legend. Thanks.

I did not know what that was for so at least I will not need to ask this sort of question again.

**Comment by kcwebby** [comment]
I dont think this ever got added to the base code.   I reinstalled, and forgot about this for a few days.  Finally remembered.
