### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_1 :: [c0e6765] git config remote.origin.url https://github.com/SickChill/SickChill.git returned code 255, treating as error : error: could not lock config file .git/config: No space left on device

### ISSUE THREAD

**Issue by Vorsayo** [SickChill/SickChill#5233]
### INFO
Python Version: **2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]**
Operating System: **Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.5.1804-Core**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@c0e676570fbffe964c57e8e089b8cab7b4b2f668
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [c0e6765] git config remote.origin.url https://github.com/SickChill/SickChill.git returned code 255, treating as error : error: could not lock config file .git/config: No space left on device
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment]
The disk SickChill is installed on is full. Please clean house.
