### ISSUE TITLE
Add new Show from TVDB Indexer not working on some shows

### ISSUE THREAD

**Issue by loungebob** [SickChill/SickChill#5236]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/c0e676570fbffe964c57e8e089b8cab7b4b2f668 
OS: Windows-10-10.0.17763 
Browser: IE11
What you did: Add new Show
What happened: Show not listed
What you expected: Show to be listed
Logs: Nothing in the logs
```
PASTE LOGS HERE
```

Trying to add shows

- Forever (2018)
- Wanderlust (2018)
- The Fam (2019)

Forever and Wanderlust are listed on TVDB, as far as I can see with all necessary information. The Fam isn't so that one's not really a surprise not being found.

Tried Forever, Forever 2018, Forever (2018), nothing.

**Comment by WebSpider** [comment]
Both Forever and Wanderlust work for me when I search:

forever 2018
wanderlust 2018

**Comment by loungebob** [comment]
They work for me too, now. This was not working in any combination of date, name and brackets the last couple of weeks. Well, solved for now.
