### ISSUE TITLE
Keep torrent info (feature request)

### ISSUE THREAD

**Issue by syco** [SickChill/SickChill#5237]
Hi,
would be nice to know, after a download has finished, where it was downloaded from and the full url used to retrieve the magnet/torrent file.
I use jackett and sometimes I get a file in russian, but I can't find any way to know what indexer I have to disable to avoid this, or what keyword I have to add to the sickchill ignored words.
Thanks

**Comment by WebSpider** [comment]
This will become possible to add after our db changes as mentioned in #5167

**Comment by miigotu** [comment]
The provider and release name are already stored on the history page

**Comment by syco** [comment]
Thanks, but the provider (in my case) is simply jackett, I don't add individual providers, that's why the torrent/magnet url would be more useful to me.
