### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_0 :: [9862786] Missing time zone for network: TNT Brasil. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by j0n0russo** [SickChill/SickChill#5242]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.19.8-ckt22-custom-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9862786ccee1054cdcac409ef27abe5a63af5936
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [9862786] Missing time zone for network: TNT Brasil. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by tvann2182** [comment]
go to settings then general and where you see the following "Use initial indexer set to" set the drop down to TVDB and this should take care of the problem.

**Comment by j0n0russo** [comment]
### INFO
Python Version: **2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]**
Operating System: **Linux-3.19.8-ckt22-custom-x86_64-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9862786ccee1054cdcac409ef27abe5a63af5936
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_15 :: [9862786] Missing time zone for network: TNT Brasil. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
