### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-DAILY-SEARCH :: [c0e6765] DelugeD: Unable to set the label for Torrent

### ISSUE THREAD

**Issue by Adarack** [SickChill/SickChill#5247]
### INFO
Python Version: **2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@c0e676570fbffe964c57e8e089b8cab7b4b2f668
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [c0e6765] DelugeD: Unable to set the label for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment]
Please add debug logging illustrating the issue.
