### ISSUE TITLE
Missing Artwork

### ISSUE THREAD

**Issue by CryofMankind** [SickChill/SickChill#5252]
Branch/Commit:  master / 020e76222c851074fe22b76ada95d31697091a91
OS: Synology 
Browser: Chrome
What you did: Switched from the SickRage package to SickChill
What happened: All the artwork is missing. 
I restarted, cleared the history, cleared the browser cache, performed a mass update, no change.
There are no errors in the logs even with debug enabled. There are also no permission errors on the Synology.

**Comment by miigotu** [comment]
Mass update, check all for rescan, submit

**Comment by miigotu** [comment]
Please let me know if that fixes it

**Comment by CryofMankind** [comment]
Sorry, since the update the UI has been running so slowly. After I hit Submit, nothing happens. Nothing shows in the log. I tried doing a rescan on a few individual shows but it didn't have any impact.

**Comment by WebSpider** [comment]
Please check the logfiles to see what is going on

**Comment by miigotu** [comment]
@CryofMankind are you sure you successfully made the switch? Does it say sickchill instead of sickrage on the home page???
