### ISSUE TITLE
[APP SUBMITTED]: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by lenaertst89** [SickChill/SickChill#5259]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@abc6aab554715e57cf1668627a1f57f5b1ed4588
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [abc6aab] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4470, in savePostProcessing
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1971, in save_config
    'torrent_seed_time': int(TORRENT_SEED_TIME),
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by lenaertst89** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@abc6aab554715e57cf1668627a1f57f5b1ed4588
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [abc6aab] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 4337, in saveSearch
    sickbeard.save_config()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 1971, in save_config
    'torrent_seed_time': int(TORRENT_SEED_TIME),
ValueError: invalid literal for int() with base 10: ''

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by krangas** [comment]
### INFO
Python Version: **2.7.16 (default, May 23 2019, 05:34:26) [GCC 7.4.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7f1edd5394aff690feccf43f1e0e1ea31b0500e7
Link to Log: https://gist.github.com/2dab3f12f6392dacb55dc5318776e0b7
### ERROR
```
SHOWQUEUE-ADD :: [7f1edd5] Unable to add show due to an error with theTVDB: invalid literal for int() with base 10: ''
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by krangas** [comment]
### INFO
Python Version: **2.7.16 (default, May 23 2019, 05:34:26) [GCC 7.4.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7f1edd5394aff690feccf43f1e0e1ea31b0500e7
Link to Log: https://gist.github.com/a031ba69f704ca08c19f614a27e486b2
### ERROR
```
SHOWQUEUE-ADD :: [7f1edd5] Error trying to add show: invalid literal for int() with base 10: ''
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
