### ISSUE TITLE
"Looks like we do not have enough disk space to render the page! {error}"

### ISSUE THREAD

**Issue by jtgd** [SickChill/SickChill#5260]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 2018.12.24-1
OS: Arch Linux 4.19.12
Browser: opera, qutebrowser, eolie, chromium
What you did: tried to load localhost:8081
What happened: I got the error message on the web page "Looks like we do not have enough disk space to render the page! {error}"  There is plenty of disk space available on all drives.
What you expected: normal operation
Logs:
```
I cannot reach the settings to enable logging.
```
One thing I've done is change the username in the systemd sickchill.service from sickchill to my own username, but it's been working for weeks that way.

This problem started after the latest update (a couple days ago). It's been working great for months before this.

**Comment by miigotu** [comment]
The cache dir needs permissions changed recursively to the user running SC. You changed the user and nothing needed written in the cache until an update changed a template file, and now it cannot write there.

**Comment by jtgd** [comment]
Fixed, thank you. I might suggest a different error message regarding permissions instead of disk space.
