### ISSUE TITLE
No results found on DOGnzb but are definitely there

### ISSUE THREAD

**Issue by gchaimovitz** [SickChill/SickChill#5261]
Branch: master
Commit: abc6aab554715e57cf1668627a1f57f5b1ed4588
Version: v2018.12.24-1
Database Version: 44.0
OS: Windows 10
Browser: Chrome
What you did: Backlog search & tried manual search after noticing episodes not downloading
What happened: No episodes found during search
What you expected: Find correct nzb and push to sabnzb

Using the DOGnzb webui I could find and push the episodes manually.  This just started happening recently and I hadn't changed anything.  I updated a few days ago hoping that would fix it but it didn't.

Tested with Torrentday and NZB.su and worked fine.

Logs:
```
2018-12-28 10:02:44 INFO SEARCHQUEUE-BACKLOG-259866 :: No needed episodes found during backlog search for: [Ray Donovan]
2018-12-28 10:02:42 INFO SEARCHQUEUE-BACKLOG-259866 :: [DOGnzb] :: Performing episode search for Ray Donovan
2018-12-28 10:02:31 INFO SEARCHQUEUE-BACKLOG-259866 :: Beginning backlog search for: [Ray Donovan]
```

**Comment by gchaimovitz** [comment]
Thanks, I’ll keep an eye on the forum.

**Comment by mannibis** [comment]
Hey guys, dognzb staff member. The admin fixed the t=tvsearch&tvdbid issue.

TVDB ID searches should work now via the API. I just did a bunch of tests in my browser with the t=tvsearch and tvdbid parameters with 100% success on every call

**Comment by gchaimovitz** [comment]
Confirmed working, thanks so much!

**Comment by vergessen** [comment]
Should probably close the issue.  This was never on sick chills side.
