### ISSUE TITLE
Manual Force Full Update failed

### ISSUE THREAD

**Issue by hjacquemin** [SickChill/SickChill#5287]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: v2019.01.06-1
OS: Synology DSM 6.2
Browser: Firefox
What you did: Force Full update for a show
What happened: update failed and refresh stays in queue and block all other action.
What you expected: a refresh of the show
Logs:
```
https://pastebin.com/7Xa34ULT

```

I saw in the log that SickChill failled to fetch an image, the the link is working:

2019-01-14 21:36:11 SHOWQUEUE-REFRESH :: There was an error trying to retrieve the image, aborting

http://thetvdb.com/banners/episodes/250487/6850876.jpg

![sickchill](https://user-images.githubusercontent.com/15141309/51139971-99950100-1845-11e9-84ed-1417df5c283a.PNG)

**Comment by WebSpider** [comment]
From your logs, it would seem the update is still running, and it has moved from an episode for which it could not fetch a thumbnail from IMDB to the next one. Full updates can take a while, since it checks each episode sequentially to see if something can be refreshed.

**Comment by hjacquemin** [comment]
Hello,

We are 9 hours later and the update is not finished... I don't think it's normal...

![sickchill2](https://user-images.githubusercontent.com/15141309/51161964-b9074a80-1894-11e9-919d-c3c9a178ba7b.PNG)

**Comment by hjacquemin** [comment]
As we don't have control on jobs, the only way is to restart SickChill
