### ISSUE TITLE
Feature Request: Post Processing in Show Order

### ISSUE THREAD

**Issue by jpenberthy** [SickChill/SickChill#5289]
It would be great when (Ombi or) I add a new show to SickChill to auto download all the episodes with SABnzbd, it doesn't auto-move them out of order. As in if S01E01 hasn't been moved to the directory, it doesn't copy anything after that until that episode has moved.

This way I can go full automated, as sometimes new requested shows wont download everything the first time. Of course maybe I'm missing something in the setting that may already do this.

**Comment by jpenberthy** [comment]
Just thought as well, maybe just have an option for a show not to be post processed as well when building up the content.

**Comment by WebSpider** [comment]
A few thoughts on this:

1. I am missing the point of post processing what you have when it's complete, even if it's out of order. SC still knows the other episodes are pending / snatched, right? What would be the use of this feature?
2. For shows not to be postprocessed when building up the content we have lock files in place, if your downloading application places a lock file, the postprocessor will skip the directory.
