### ISSUE TITLE
Feature Request: Add YouTube Option

### ISSUE THREAD

**Issue by lmao32895** [SickChill/SickChill#5291]
I also watch a lot of YouTube channels and as YouTube like to delete things I started downloading my watched channels. it would be nice to add this to SickChill to automate the process like it does for TV Shows.

**Comment by WebSpider** [comment]
Interesting request.
Please note SC doesn't download anything by itself, it uses clients for that, which are seperate software.

If there would be any clients available that could download YouTube contents and are available noninteractively.

Now do note that shows you watch still need to be added to an indexing service that we use, or we won't be able to find out which episodes exist, etc.

**Comment by lmao32895** [comment]
what is the indexing service you use? thetvdb? and ill do some research into a separate client that can do the download. I would also be happy to colab/test on this if you like!

**Comment by mgaulton** [comment]
FYI, if you pass the channel URL to youtube-dl on linux, it grabs everything.

**Comment by lmao32895** [comment]
no i didn't! thank you
