### ISSUE TITLE
[APP SUBMITTED]: 'Host'

### ISSUE THREAD

**Issue by MarcoPires** [SickChill/SickChill#5298]
### INFO
Python Version: **2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.14.52-v7+-armv7l-with-debian-9.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [f7a113a] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 717, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "/opt/sickrage/sickbeard/webserve.py", line 126, in __init__
    if rh.request.headers['Host'][0] == '[':
  File "/opt/sickrage/lib/tornado/httputil.py", line 217, in __getitem__
    return self._dict[_normalized_headers[name]]
KeyError: 'Host'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.20206-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f8f5e604429802b21b6e6364f60e17619d84a253
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]**
Operating System: **Linux-5.4.51-v7+-armv7l-with-debian-10.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7d8f93f66958e42e740f2326f5ea048a4c44f562
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by risticsasa011** [comment]
### INFO
Python Version: **3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]**
Operating System: **Linux-5.4.0-47-generic-x86_64-with-glibc2.29**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@37657586de6ed01fbc3fddad92ede679aa44209f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Blinkz** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Yoshi900** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]**
Operating System: **Linux-5.4.51-v7+-armv7l-with-debian-10.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.20226-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.20226-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
Link to Log: https://gist.github.com/84d557688834f44b796a14723cfe8bde
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Blinkz** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by risticsasa011** [comment]
### INFO
Python Version: **3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]**
Operating System: **Linux-5.4.0-47-generic-x86_64-with-glibc2.29**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Blinkz** [comment]
Lots of people seem to be having the same issue. Any chance a mod can un-stale this so we can try and get it sorted?

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.20231-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
Link to Log: https://gist.github.com/1984cd56d5ab80a7938960987a7fc50e
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.20231-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by jaxdomino** [comment]
### INFO
Python Version: **3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) [Clang 6.0 (clang-600.0.57)]**
Operating System: **macOS-10.15.7-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]**
Operating System: **Linux-5.4.51-v7+-armv7l-with-debian-10.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cadmuslabslex** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
