### ISSUE TITLE
[APP SUBMITTED]: [Errno 22] invalid mode ('wb') or filename: u'M:\\series\\Mysteries at the Museum (2010)\\Season 13\\Mysteries at the Museum (S13E03) (2016-12-01) (1080p WEB-DL) The Man Who Sold a Million Rocks, a Party That Started a War and the Umbrella Man.mkv'

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#5301]
### INFO
Python Version: **2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [f7a113a] Unable to move file T:\completedDownload\SR\Mysteries.at.the.Museum.S13.1080p.TRAVEL.WEBRip.AAC2.0.x264-Absinth[rartv]\Mysteries.at.the.Museum.S13E03.A.Party.That.Started.a.War.1080p.Travel.WEB-DL.AAC2.0.H.264-Absinth.mkv to M:\series\Mysteries at the Museum (2010)\Season 13\Mysteries at the Museum (S13E03) (2016-12-01) (1080p WEB-DL) The Man Who Sold a Million Rocks, a Party That Started a War and the Umbrella Man.mkv: error 22 : invalid mode ('wb') or filename
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment]
The complete length of path and filename is too long for windows to be able to handle. Try something shorter :)

**Comment by crowaust** [comment]
Maybe adding an option to truncate long episode names would help things like this

https://github.com/SickChill/SickChill/issues/4545
