### ISSUE TITLE
SickRage to SickChill using backup of sickbeard-custom directory

### ISSUE THREAD

**Issue by ccwillia** [SickChill/SickChill#5307]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Synology
Browser: Safari
What you did: Backed up sickbeard-custom folder and tried to uninstall/reinstall do to "local ahead of master error".  
What happened: Discovered that sickrage had moved to sickchill so i reinstalled with sickchiil repo and copied cache.db, config.ini, sickbeard.db, failed.db, and cache directory from backup
What you expected: All settings to be restored, however all banner and poster images are missing from the user interface.  However i can see all the files in /volume1/@appstore/sickbeard-custom/var/cache/images
Logs:
```
PASTE LOGS HERE
```
I did not find any errors in the sickchill.log

**Comment by WebSpider** [comment]
Do a full refresh of all shows, it will refetch the artwork

**Comment by ccwillia** [comment]
I tried the to select all shows on mass update screen then select update option, but that didn't appear to do anything.  I moved the cache.db and cache directory which I pulled from my backup to a different name and restarted SickChill.  Now all the banners say SickChill

**Comment by ccwillia** [comment]
Update:  When I click into a show I do see a blue banner that says "This show is queued to be refreshed."
