### ISSUE TITLE
Issues with requirements.txt

### ISSUE THREAD

**Issue by skipmeister123** [SickChill/SickChill#5316]
Branch/Commit: master/f7a113a
OS: Ubuntu 18.04.1 LTS
Browser: n/a
What you did:
    - Upgraded from sickrage to sickchill following these instructions: https://www.reddit.com/r/sickchill/comments/9o8jpa/could_we_have_a_sticky_post_on_the_best_way_to/e7t65cm/
    - sudo -H pip install --upgrade requirements/requirements.txt
What happened: All sorts of errors with dependencies.
What you expected: No dependency issues; able to start sickrage

I found a few conflicts and remedied it.  [You can't have both dogpile.cache and dogpile.core](https://github.com/Diaoul/subliminal/issues/721#issuecomment-273458081).

pyasn1 and pyasn1-modules were upset.  I changed `pyasn1 == 0.1.7` to `pyasn1 >= 0.1.7`, and that helped.

My system is up and running, but I'd recommend revisiting these requirements on a fresh OS.

**Comment by miigotu** [comment]
@skipmeister123 requirements.txt isnt required at all in SickChill right now, that file is just there to baseline as we move towards being able to be packaged. I will update it though, thanks
