### ISSUE TITLE
Feature request: Placeholder for tvshow's folder name in torrent download location

### ISSUE THREAD

**Issue by zimme** [SickChill/SickChill#5317]
I would be nice to have a placeholder for the tvshow's folder name in torrent download location config.

e.g.

Downloaded files location: `/mnt/tvshows/<tvshow>`

This would set the download path in the torrent client (transmission) to `/mnt/tvshows/Suits/` for the tvshow `Suits`.

This way I can skip post processing all together as the torrent client would download to the correct location directly.

**Comment by zimme** [comment]
I looked into doing a PR for this but I'm a but out of my element but maybe the placeholder could be processed in the generic torrent client code, but I'm not sure if the tvshow's folder name is available there?

**Comment by BenjV** [comment]
Seems to me a very redundant functionality.
This functionality is done in the Postprocessor.

Normally nobody wants the keep the downloaded files in the folder owned by the downloader (e.g. Transmission in your case)

**Comment by BenjV** [comment]
So you want something which is usefull only for your special needs.
PostProcessing kan do it for you.

**Comment by zimme** [comment]
It might be for my needs but I do believe others will find it usefull if they download rared releases and want to keep them as is.

The reason I opened this issue is because post-processing can't do this. Post-processing can't move/symlink rar files properly it will only move/symlink the `.rar` file and not all the "part" files i.e. `r00` etc. and post-processing will completely ignore the original folder name of a tv show.

**Comment by zimme** [comment]
I'm also willing to help with this when we figure out the best way to do it.

**Comment by zimme** [comment]
The reason i asked for this and not a fix for the post processing is that there has already been an issue for fixing the post processings support for rar files and that had a fix, which didn't work or wasn't correct and the entire issue was closed. That lead me to look at this in a different way that might be implementable.

Yes, that's the best solution today and why I'm asking to see what can be done to change that as unpacking my rared downloads and use double the space as i need to seed the rared files isn't an option for me.

**Comment by WebSpider** [comment]
Please bot, don't close FRs

**Comment by cewood** [comment]
+1 this makes a lot of sense when dealing with Torrents, would love to see this implemented.
