### ISSUE TITLE
tvshow.nfo meta data not scrapping year 

### ISSUE THREAD

**Issue by papampi** [SickChill/SickChill#5345]
Post process not scrapping year for new tv shows.
Kodi shows year for all the new shows as 1969

If possible extract year from first aired date and add for kodi tvshow.nfo

**Comment by WebSpider** [comment]
Unidle

**Comment by papampi** [comment]
This is not fixed.
kodi shows year 1969 

Please fix it.

**Comment by sarsipius** [comment]
I'm having this issue with sickchill's metadata not scraping the year correctly and kodi showing the year as 1969 as well
