### ISSUE TITLE
Search linked to Jackett delivers empty results

### ISSUE THREAD

**Issue by littlejeem** [SickChill/SickChill#5346]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Linux-4.14.92-v7+-armv7l-with-debian-9.6
Browser: Chrome
What you did: Linked Sickchill to Jackett
What happened: Search returns results but doesn't grab downloads
What you expected: Prior behavior has been that search results are grabbed and sent a blackhole and picked up by download client
Logs:
```
PASTE LOGS HERE
```
Sickchill Warning Log
https://pastebin.com/sq39K5dB

Sickchill Debug Log
https://pastebin.com/uPXwPBaw

I'm not sure yet is the error is with Sickchill or Jackett and not sure where to start

**Comment by miigotu** [comment]
SC searches and finds the result with no issue, jackett delivers an empty torrent file

**Comment by littlejeem** [comment]
thanks @miigotu , posted over at Jackett and this has now been resolved through issue tracker #4584 for anyone that comes along after me
