### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_3 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by DasGreff** [SickChill/SickChill#5351]
### INFO
Python Version: **2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by larstomas** [comment]
I have the same problem.

**Comment by Zetsuo** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 26 2018, 05:58:52) [GCC 4.9.2]**
Operating System: **Linux-4.9.35-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doreybenjamin** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 25 2018, 20:42:16) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-7-amd64-x86_64-with-debian-8.11**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DravenSA** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by benjired** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Snowaks** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_19 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kcwebby** [comment]
I also am having the same issue -- commenting to get notifications.

**Comment by DravenSA** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by bepece1** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:35) [GCC 6.4.0]**
Operating System: **Linux-4.14.98-v7+-armv7l-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Snowaks** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doreybenjamin** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 25 2018, 20:42:16) [GCC 4.9.2]**
Operating System: **Linux-3.16.0-7-amd64-x86_64-with-debian-8.11**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ming1981** [comment]
### INFO
Python Version: **2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [f7a113a] Missing time zone for network: YouTube Premium. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by explor202** [comment]
Same issue here.

**Comment by miigotu** [comment]
I updated network timezones when I closed this. Its there. https://github.com/SickChill/sickchill.github.io/blob/master/sb_network_timezones/network_timezones.txt#L2414

**Comment by explor202** [comment]
Great, thanks!
