### ISSUE TITLE
ERR_CONNECTION_RESET after power outage

### ISSUE THREAD

**Issue by mathsteck** [SickChill/SickChill#5354]
It's the third or fourth time that this problem occurs to me: I'm running the service on a raspberry pi 2 and, at this time of year, raining and thunderstorms are pretty common... As power outages. The problem is that every time that the energy goes off (or the service is suddenly interrupted for any external factor) only the WEB CLIENT stop working... The server side still running and working as it should but I can't access the client and I can't find any error log that can tell me what kind of problem is happening. I'm getting tired of reinstalling the service every time I have this error. Is there a way to reset the configurations without reinstalling, check the web client log, fix the database or something?

Thanks.

Branch/Commit: master
OS: raspbian
Browser: Google Chrome

**Comment by miigotu** [comment]
Usually stopping the SC service and deleting everything in the cache folder except the images folder works.

**Comment by mathsteck** [comment]
I've tried that but It's still not working. Is there any log that I can check for further information so I can post here?

**Comment by miigotu** [comment]
seems more like a networking issue then. I would manually rboot everything to get it to work. If the server is working, the web is actually working.
