### ISSUE TITLE
poster.png has incorrect size

### ISSUE THREAD

**Issue by skalvaro** [SickChill/SickChill#5355]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: f7a113a737654a91076bb42221e119db6258a276
Version: v2019.01.06-1
Database Version: 44.0
OS: Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Browser: Any
What you did: Added shows with no poster available
What happened: On Shows page the default poster is higher than other show poster.
What you expected: All posters are same size.
Logs: No logs, this is a visual issue.

The default poster used for shows that have no poster availble has a size of 640x1000 while other show posters have a size of 680x1000. This results on the Shows page in different display sizes as the width of the default poster is adjusted from 640 to 680 but it seems with respecting the width-heigth ratio and as such the heigth becomes 1062. This leads to the posters not being aligned anymore and the Shows page gives a cluttered view.

`poster.png 680x1000 (adjusted)`
![poster](https://user-images.githubusercontent.com/10258537/53373113-e7c51600-3954-11e9-8270-29194c66b469.png)
`poster.png 640x1000 (original)`
![poster orig](https://user-images.githubusercontent.com/10258537/53373260-37a3dd00-3955-11e9-9978-b7e02cc69469.png)
`how the original poster.png (640x1000) brakes the alignement`
![afbeelding](https://user-images.githubusercontent.com/10258537/53373628-4d65d200-3956-11e9-9207-31eeddced9dd.png)
`alignement back ok with adjusted poster.png (680x1000)`
![afbeelding](https://user-images.githubusercontent.com/10258537/53373777-b6e5e080-3956-11e9-9121-6acdea305636.png)

**Comment by miigotu** [comment]
Please make a PR with the corrected poster if you know how. This fixes a few issues, thanks.

**Comment by skalvaro** [comment]
@miigotu Hope I created the PR correctly.
