### ISSUE TITLE
Create ARM build of Docker image

### ISSUE THREAD

**Issue by giggio** [SickChill/SickChill#5359]
As #5258 was closed, reopening.

Right now you have an x64 build, it would be nice to publish an ARM one. If possible, use the same tags, and publish it as a different architecture.

**Comment by viraptor** [comment]
Step away from that button, bot.

**Comment by WebSpider** [comment]
I've never actually created an arm docker image, but this looks like an easy fix so I'll dive into it

**Comment by giggio** [comment]
Why was this closed?

**Comment by miigotu** [comment]
![image](https://user-images.githubusercontent.com/390379/76156642-41653200-60cb-11ea-8c1a-0859583d80c9.png)
![image](https://user-images.githubusercontent.com/390379/76156667-8f7a3580-60cb-11ea-9ba8-eaf3eced83b0.png)

**Comment by miigotu** [comment]
Also, https://github.com/docker/hub-feedback/issues/1779#issuecomment-478100972
