### ISSUE TITLE
Typo: it's != its

### ISSUE THREAD

**Issue by Nickduino** [SickChill/SickChill#5365]
_it's_ should be _its_

![image](https://user-images.githubusercontent.com/9784237/53822128-6fbba900-3f6f-11e9-81e2-a84458bf3af7.png)

There (I think): https://github.com/SickChill/SickChill/blob/42048adc775140a99dbc348c6ea66b0d63643b7e/gui/slick/views/addShows.mako#L19

By the way, years ago, sickrage wasn't able to recreate a deleted directory when it didn't find it, has this been fixed?

**Comment by WebSpider** [comment]
This has been fixed long ago
