### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_0 :: [f7a113a] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by bwguy** [SickChill/SickChill#5369]
### INFO
Python Version: **2.7.14 (default, Mar 03 2018, 11:05:58) [GCC 7.3.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [f7a113a] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Ulroy** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [f7a113a] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
