### ISSUE TITLE
cloudflare ygg

### ISSUE THREAD

**Issue by skillfr** [SickChill/SickChill#5372]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: f7a113a737654a91076bb42221e119db6258a276
Version: v2019.01.06-1

Logs:
```
2019-03-14 00:30:14 SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: [f7a113a] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." ()
2019-03-14 00:30:14 SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: [f7a113a] Failed parsing provider YggTorrent.
```

**Comment by Jamyz** [comment]
Look [#5373](https://github.com/SickChill/SickChill/pull/5374) 
Edit you're file or wait update.

**Comment by skillfr** [comment]
Nice thank you

**Comment by shimmerdark** [comment]
It's been like 5 months since the last update. Should we plan to update files day by day? I see patches and changes are being submitted but just not committed and new versions released. I have edited my /sickchill/lib/cfscraper/___ini___.py file twice now as my searching stopped working twice. I am not involved with development but the updates scheduled seems very delayed currently. Is this project dead ending? Should folks start looking for another fork?

**Comment by ovsleep** [comment]
I'm having the same issue. I tried to manually edit the mentioned file, but now it get stuck at downloading the torrent file, no log or anything else
`39 INFO SEARCHQUEUE-MANUAL-296830 :: Downloading a result from Torrentz at http://XXXXXXXX/torrent/F2B1FD02A0454EFF6E52DD083D09FE395315469D.torrent`
Anyway to apply the fix using git? or should I just manually replace the file? 
I'm running SickChill in a docker on my NAS, so I just have access from the terminal.

**Comment by shimmerdark** [comment]
Ok here is my __init__.py. I also renamed the __init__.pyc that was in the
directory. I am not that familiar with python but I think that it is like a
runtime compile. It was auto recreated(__init__.pyc) when I restarted
sickchill.

the directory was sickchill/lib/cfscrape/

I wasn't using Torrentz though I was using iptorrents.

I am running my sickchill on Debian 8 atm about to move up to 9. It's just
bare metal install, also serves as my plex server.

Good luck I hope they start taking better care of this project and
releasing more consistent updates. I mean the got people fixing the stuff,
they just aren't releasing it via their updater.

**Comment by Jamyz** [comment]
> Ok here is my __init__.py. I also renamed the __init__.pyc that was in the directory. I am not that familiar with python but I think that it is like a runtime compile. It was auto recreated(__init__.pyc) when I restarted sickchill. the directory was sickchill/lib/cfscrape/ I wasn't using Torrentz though I was using iptorrents. I am running my sickchill on Debian 8 atm about to move up to 9. It's just bare metal install, also serves as my plex server. Good luck I hope they start taking better care of this project and releasing more consistent updates. I mean there are people fixing the stuff, they just aren't releasing it via the updater. I know I am just arm chair quarterbacking, my extensive knowledge of python is clearly shown above.

Where is the link?

**Comment by WebSpider** [comment]
cfscrape component ahs been worked on and should now be fixed
