### ISSUE TITLE
DSM 6.2.1-23824 Update 6 (DS1511+) + Reverse Proxy

### ISSUE THREAD

**Issue by Jamyz** [SickChill/SickChill#5375]
Branch/Commit: master/f7a113a737654a91076bb42221e119db6258a276
OS: Linux-3.10.105-x86_64-with (Docker)
Browser: Chrome Version 72.0.3626.121 (Build officiel) (64 bits)
What you did: Use Reverse Proxy on DSM Synology
What happened: When HDD works more than 20% can't find the page
What you expected: Any fix ?
Logs:
No Logs about this.

Hi everybody.
At first i use Sickchill with Docker on Synology and too with sickbeard-custom package.
This month i trying using the reverse proxy from synology on DSM. All works very good when the volume of my NAS is not working. But when the Volume works a little, the reverse proxy can't reach the pages of sickchill web.
Example, when sickchill download 1Go with DSDownload. I can't reach the sickchill webpages.
Any one have this issue ?
What i can do ?
Thanks.

**Comment by WebSpider** [comment]
When you use a reverse proxy, make sure you have the webroot settings correct.

**Comment by Jamyz** [comment]
> When you use a reverse proxy, make sure you have the webroot settings correct.

On DSM is pretty easy.
It's https://sickchill.mydomain.com -> https://localhost:8083
Only fail when HDD workings. The other like router.domin.com or others not on the localhost fails.
Maybe is only synology bug and not sickrage.

**Comment by WebSpider** [comment]
In that case, please add some logfiles from SickChill indicating the error :-)
