### ISSUE TITLE
Error parsing Cloudflare IUAM Javascript challenge

### ISSUE THREAD

**Issue by rsarkhani** [SickChill/SickChill#5380]
Hi,

Im getting this error when i do manual search

`2019-03-21 12:11:10 SEARCHQUEUE-DAILY-SEARCH :: [f7a113a] Request failed: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." ()`

Branch/Commit: master/ f7a113a737654a91076bb42221e119db6258a276
OS: Windows 10
Browser: Chrome 
What you did: Manual search on episode
What happened: Got this error complaining about parsing
What you expected: snatch torrent like how it was couple of weeks ago
Logs:
```
https://pastebin.com/3E1EPri4
```
More log: https://pastebin.com/3E1EPri4 

![image](https://user-images.githubusercontent.com/48775468/54729358-070d3700-4bd3-11e9-9766-6eb507d75fd7.png)

**Comment by Jamyz** [comment]
Try https://github.com/SickChill/SickChill/pull/5374

**Comment by Jamyz** [comment]
I see my logs and i have maybe the same issue.
Do you see the logs in debug and check if you have similar like me.
`2019-03-21 10:59:43 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: GET URL: https://www2.yggtorrent.gg/cdn-cgi/l/chk_jschl?category=2145&do=search&sub_category=all&jschl_vc=87796e6aa73000e656df6479107dfe6b&jschl_answer=17.0297812237&pass=1553162379.107-UxuHC6RF9G&name= [Status: 302]
2019-03-21 10:59:51 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: [f7a113a] Request failed: maximum recursion depth exceeded (<type 'str'>)
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1526, in handle_requests_exception
    raise requests_exception
RuntimeError: maximum recursion depth exceeded
2019-03-21 10:59:51 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1526, in handle_requests_exception
    raise requests_exception
RuntimeError: maximum recursion depth exceeded
`
#5379

**Comment by Jamyz** [comment]
Update __init__.py file in /lib/cfscrape folder or wait update

**Comment by JetLimits** [comment]
And with what do you need to update it?

**Comment by davebooi** [comment]
With this commit: https://github.com/SickChill/SickChill/pull/5381/commits/8c1a9f9f557f59e0d7fd458fd85259ecbc3e00ff

**Comment by Jamyz** [comment]
> With this commit: [8c1a9f9](https://github.com/SickChill/SickChill/commit/8c1a9f9f557f59e0d7fd458fd85259ecbc3e00ff)

Sorry for not reply before.
Yes. But i trying with few providers, for ones are good for others not.
Because i try change` js = re.sub(r"a\.value = (.+ \+ t\.length(\).toFixed\(10\))?).+", r"\1", js)`
in line 128 but not works correctly. Try with your providers....

**Comment by davebooi** [comment]
using cardigann as search provider, it works ok with TorNZAB feed from Cardigann

**Comment by JetLimits** [comment]
Seems I do not have this file in my docker under that location.
I do have /app/sickrage/sickbeard/__init__.py

Worst case I'll wait for the update and process my DLs manually for the time being. Is their an ETA on the next update?

Thx!

**Comment by Starbuck1991** [comment]
Same problem here.

This is the log:
https://pastebin.com/rc4aHKbF

**Comment by lounsberry** [comment]
I believe this is a problem with CloudFlare updating their service and the CloudFlare Scraper ([cfscrape](https://github.com/Anorov/cloudflare-scrape)) hasn't been updated to counter it yet.

**Comment by Jamyz** [comment]
Now i use jackett.....!!!!! Works again and better.

**Comment by WebSpider** [comment]
cfscrape has been worked on and should now be fixed
