### ISSUE TITLE
How to create a torrent provider

### ISSUE THREAD

**Issue by Jamyz** [SickChill/SickChill#5382]
Hi !
I want to create my own providers.
How can i proceed ?

I think there are 2 files to create/modify.

1st - in the providers directory add `mytorrentprovider.py`
2nd - and add mytorrentprovider in `__init__.py` in directory providers.

Anything else ?

**Comment by WebSpider** [comment]
The provider would need to be added to the GUI as well, so you can configure it.

**Comment by Jamyz** [comment]
> The provider would need to be added to the GUI as well, so you can configure it.

That is for webs with RSS. I want without RSS. It's correct ?

**Comment by WebSpider** [comment]
If there is no configuration needed for the provider, all you should create more is a test to automatically test functionality

**Comment by Jamyz** [comment]
I don't understand.....
I have the follow screen.
![Sans titre-1](https://user-images.githubusercontent.com/6177824/54817485-62086200-4c97-11e9-925d-8d0931f84c76.jpg)

So what i use for exemple oxtorrent.com ?
URL RSS ?
Cookies ? How i use uid=xx;pass=yy
Title ?

A How to is available ? Where ?

**Comment by miigotu** [comment]
If you use another provider as a template, most of the settings will be automatically added to the gui if it uses the same class variable names.

Search for `rarbg` in the source and you will see all the places you need to add the import

**Comment by Jamyz** [comment]
> If you use another provider as a template, most of the settings will be automatically added to the gui if it uses the same class variable names.
> 
> Search for `rarbg` in the source and you will see all the places you need to add the import

Thanks @miigotu , now how i do to upload a png for the provider ? I cant upload in github

**Comment by Jamyz** [comment]
@WebSpider , sorry i see today we can change the url for the custom 👍 .
Thanks
