### ISSUE TITLE
[APP SUBMITTED]: u'Seeders' is not in list

### ISSUE THREAD

**Issue by Toolazy2work** [SickChill/SickChill#5387]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Nebulance] :: [f7a113a] Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/providers/nebulance.py", line 164, in search
    seeders = try_int(cells[labels.index('Seeders')].text.strip())
ValueError: u'Seeders' is not in list

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment]
If this happens once in a while, most likely the provider was having troubles. Is this once, or does it happen all the time?

**Comment by chompspace** [comment]
Can confirm this issue. I spoke with the staff of nebulance a week+ ago and they confirmed the site was changed. I resolved the issue myself by changing the file nebulance.py file on lines 164 & 165 with the following:
**Note**: these are NOT the caret and letter v, but instead are the characters [Wedge](https://en.wikipedia.org/wiki/Wedge_(symbol)) and [Vel](https://en.wikipedia.org/wiki/Vel_(symbol))

```
seeders = try_int(cells[labels.index('∧')].text.strip())
leechers = try_int(cells[labels.index('∨')].get_text(strip=True))
```

**Comment by Torhal** [comment]
@miigotu Any chance on this being fixed soonish? I've been waiting for three months and I'd prefer not manually editing the code to avoid Git update drama. :D

**Comment by miigotu** [comment]
idk how I closed this before the PR, but its fixed anyways :) Thanks @fbossy

**Comment by fbossy** [comment]
No pb! :) Glad I could help with this small change.
