### ISSUE TITLE
[Feature request] Aria2

### ISSUE THREAD

**Issue by Ulrar** [SickChill/SickChill#5402]
Hi,

It would be great to have support for aria2, which like deluge has an RPC API that could be used for that. Is there by any chance anyone working on this ?
If not, is there any docs on how to add new torrent clients correctly ?

Thanks

**Comment by wahyd4** [comment]
+1 here, [Aria2](https://aria2.github.io/) is actually a quite popular file downloading tool which supports  `HTTP/HTTPS`,`FTP`, `SFTP`, `BitTorrent` and `Metalink`.
