### ISSUE TITLE
Configure custom Torrent providers

### ISSUE THREAD

**Issue by simon25608** [SickChill/SickChill#5413]
I have configured two private torrents and both appear as not supporting delayed or manual searches, however they do accept them.
If for example I configure them in znab with jackett the error is not shown.

![img-2](https://user-images.githubusercontent.com/18722357/55842868-a61fb180-5b35-11e9-8742-a9d667bbd57b.png)
![2019-04-10_020812](https://user-images.githubusercontent.com/18722357/55842869-a61fb180-5b35-11e9-814d-bba3a79d17a1.png)

**Comment by miigotu** [comment]
In SC only rss torrent providers are supported. If they are not rss providers, configure them in jackett and add jackett as the provider in SC.

**Comment by simon25608** [comment]
Both are RSS providers and I have tried to configure them with jackett and the error is the same

![2019-04-10_082120](https://user-images.githubusercontent.com/18722357/55856273-1d6f3880-5b6a-11e9-9843-9f19bab5c12d.png)

![2019-04-10_082042](https://user-images.githubusercontent.com/18722357/55856275-1d6f3880-5b6a-11e9-8fed-0d86539bed1b.png)
