### ISSUE TITLE
Windows 10 mako issue

### ISSUE THREAD

**Issue by mbnoimi** [SickChill/SickChill#5414]
**Branch/Commit**: master
**Commit**: b3da866cadff70973fabdbb3ffbe8ad0dd208c49
**Version**: v2019.04.07-1
**Database Version**: 44.0
**Python Version**: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
**OS**: Windows-10-10.0.17763
**Browser**: Firefox / Microsoft Edge
**What I did**: Add existing TV Shows
**What happened**: Doesn't add the TV Shows and shows Mako error (doesn't appear in the log although I already enabled debug mode so I took a screenshot for it)
BTW, this issue occurs for dding new TV Shows
**What I expected:** Adding TV Shows
**Logs**:
![Capture](https://user-images.githubusercontent.com/284547/55866101-54ecdd80-5b88-11e9-8e36-43280d678950.PNG)

[sickchill.log](https://github.com/SickChill/SickChill/files/3062943/sickchill.log)

**Comment by mbnoimi** [comment]
I dropped Windows machine for good.

**Comment by miigotu** [comment]
I fixed an error like this in the new tvdb API branch, hopefully it can be released soon.
