### ISSUE TITLE
Ignored episodes are still downloading randomly

### ISSUE THREAD

**Issue by ErenPhayte** [SickChill/SickChill#5417]
I have a persisting issue, I have had to set all my downloaded episodes to ignore, as it was randomly just downloading new files. Even when they are ignored it still picking up episodes and downloading them.

my settings are as followed if that even helps

![Capture](https://user-images.githubusercontent.com/1400967/55990027-ed797f80-5ca6-11e9-83ac-ad32b2bbb99d.PNG)

**Comment by WebSpider** [comment]
One explanation for this would be that you have season packs enabled, and the unwanted eps are bundled with wanted eps in a season pack.

Does that make sense for your case?

**Comment by ErenPhayte** [comment]
Makes sense. Let me check that out when I get home later today.

**Comment by ErenPhayte** [comment]
So I had a look at all the settings. Season packs is not enabled, so this
is a strange one.

**Comment by neomvll** [comment]
Same issue here. Epsodes only is enabled.
Eps ignored, downloaded or archived are downloading randomly

**Comment by WebSpider** [comment]
Please add some logs, where things are snatched that are not supposed to be
