### ISSUE TITLE
editing "api."usenet-crawler.com out of config.ini and when restart sickchill config.ini reverts to include api.

### ISSUE THREAD

**Issue by sempisan** [SickChill/SickChill#5419]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master  b3da866cadff70973fabdbb3ffbe8ad0dd208c49
OS: ReadyNAS Debian 8.2.0-12
Browser: Chrome
What you did:  Followed instructions on https://github.com/SickChill/SickChill/issues/5036  I shutdown the sickchill service.  Went to apps/sickchill/app-config and edited config.ini to remove "api." from usenet-crawler.com from the [Newznab] section.  Verified I edited it correctly.  Restarted sickchill and got the error below
What happened:  config.ini reverted back to include the "api."usenset-crawler.com 
What you expected: config.ini would not revert back to before it was edited
Logs:
```
2019-04-11 22:08:06 WARNING ThreadPoolExecutor-0_2 :: Error getting caps xml for [Usenet-Crawler]
2019-04-11 22:08:06 INFO ThreadPoolExecutor-0_2 :: Request failed: 404 Client Error: Not Found for url: https://api.usenet-crawler.com/api?apikey=**********&t=caps ()
```

**Comment by miigotu** [comment]
You cannot edit the ini while SR is running, or it gets overwritten on shudown.

**Comment by markdegrootnl** [comment]
It also gets overwritten when SR is not running. After starting SR the url reverts back to api.usenet-crawler.com.

**Comment by sempisan** [comment]
Like mark said, it also gets overwritten when sickchill is not running

**Comment by miigotu** [comment]
Not on the develop branch it doesn't. The python was already changed.

**Comment by markdegrootnl** [comment]
Ah I see. When will the master be updated?

**Comment by ChuckyNorris** [comment]
Why would this be hard-coded instead of configurable?

**Comment by miigotu** [comment]
It isnt hard coded, its only defaults in the code.

**Comment by ChuckyNorris** [comment]
When the default in the code cannot be edited by users, it's the definition of hard-coded!
Anyway, nzbfinder.ws is also going to change their URL soon... users need to be able to change the URLs themselves...

**Comment by miigotu** [comment]
No, it is able to be edited. The defaults just populate the list when the config entry is empty.
You can PR or ask for us to change the URL for nzbfinder when that happens (or just add it as an extra newznab entry)

But otherwise, you can take that hard exclamation point somewhere else, because I don't appreciate being shouted at.
