### ISSUE TITLE
Pirate Bay uses wrong search url

### ISSUE THREAD

**Issue by Linden-Ryuujin** [SickChill/SickChill#5425]
Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:  master/ b3da866cadff70973fabdbb3ffbe8ad0dd208c49 
OS: Arch Linux
Browser: Firefox
What you did: Search for a new episode on the pirate bay
What happened: results with least seeders were returned
What you expected: results with the most seeder should be returned
Logs:
```
2019-04-15 21:33:37 INFO     SEARCHQUEUE-MANUAL-121361 :: [ThePirateBay] :: Performing episode search for test
2019-04-15 21:33:37 DEBUG    SEARCHQUEUE-MANUAL-121361 :: [ThePirateBay] :: Search Mode: Episode
2019-04-15 21:33:37 DEBUG    SEARCHQUEUE-MANUAL-121361 :: [ThePirateBay] :: Search string: test S01E01
2019-04-15 21:33:38 DEBUG    SEARCHQUEUE-MANUAL-121361 :: [ThePirateBay] :: GET URL: https://thepiratebay.org/search/test%20S01E01/0/8/200 [Status: 200]
```

You can see the search url uses `/0/8/200` as its categories. If you click the link it generates for something new (e.g. https://thepiratebay.org/search/Game%20of%20Thrones%20S08E01/0/8/200) you can see it is ordered with least seeders first. I think it should be using `/0/7/200`  instead (e.g. https://thepiratebay.org/search/Game%20of%20Thrones%20S08E01/0/7/200 )

There's a comment in the provider python saying:
># oder_by is 7 in browse for seeders, but 8 in search!
Not sure if this is just out of date, but certainly in my browser 7 seems to be the right value. I wonder if at one point the browse and search urls were different and they have since been brought in line with each other - the last change to that area was a few years ago.

**Comment by ninovanhooff** [comment]
I suggest that you create a pull request for this, since the fix should be simply changing that number in the url

**Comment by Linden-Ryuujin** [comment]
I'm happy to do that, I've fixed it locally on my machine and have a branch read to go, but I guess I need adding the to repo as I don't have permission to push it or create a pull request.

**Comment by ninovanhooff** [comment]
The idea of a pull request is that you create a fork first, which copies
everything to your own repo. You can push to a branch there and then create
a pull required. Github will understand that you want it to be pulled into
the original sickchill repo
