### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_0 :: [b3da866] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by r5464y75** [SickChill/SickChill#5426]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [b3da866] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by r5464y75** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_11 :: [b3da866] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Spanjoekel** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [b3da866] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by r5464y75** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [b3da866] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
