### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_3 :: [b3da866] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by frank3427** [SickChill/SickChill#5428]
### INFO
Python Version: **2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.14.98-v7+-armv7l-with-debian-9.8**
Locale: ISO8859-1
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [b3da866] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment]
Please use the master branch, not the develop branch.
