### ISSUE TITLE
[APP SUBMITTED]: CHECKVERSION :: [b3da866] git rev-parse --verify --quiet "@{upstream}" returned code -11, treating as error : None

### ISSUE THREAD

**Issue by freeextreme** [SickChill/SickChill#5431]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
No Log available with ERRORS:
### ERROR
```
CHECKVERSION :: [b3da866] git rev-parse --verify --quiet "@{upstream}" returned code -11, treating as error : None
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment]
You had a problem connecting to github.com. Please let us know if this was a one-time error, or if this is recurrinf
