### ISSUE TITLE
[Jackett] :: Request failed: HTTPConnectionPool(host='192.168.1.##', port=####): Read timed out. (read timeout=30) ()

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#5432]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```
looks like it takes Jackett longer then 30 second to respond from the search request.
Jackett processes the request through all providers before responding, 
I've done manual searches that seem to take in excess of 45 seconds to respond (i'm guessing since I didn't time it), other times it's quicker.  I think being able to adjust the timeout limit should be adjustable with a max limit.

**Comment by nydave69** [comment]
any progress on this...  I'm manually having to download episodes that keep getting missed...

**Comment by miigotu** [comment]
Disable whichever provider is locking up jackett, or add the individual provider urls from jackett into SC instead of the catchall
