### ISSUE TITLE
Unable to find episode with date 2001-09-01 for show 9-1-1, skipping

### ISSUE THREAD

**Issue by Senate9690** [SickChill/SickChill#5436]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / b3da866cadff70973fabdbb3ffbe8ad0dd208c49
OS: Linux-4.15.0-47-generic-x86_64-with-Ubuntu-16.04-xenial
Browser: Chrome 73.0.3683.103 (Official Build) (64-bit)
What you did: Forced Full Update
What happened: I get this warning often.
What you expected: To not get this warning.
Logs:
```
2019-04-23 03:56:35 SHOWQUEUE-REFRESH :: Unable to find episode with date 2001-09-01 for show 9-1-1, skipping
```
Not sure if this is a scraper issue or SickChill but I get this warning weekly (atleast). There is not an episode listed for that date in the Show either.

**Comment by ncl2fth** [comment]
> ### Before submitting your issue:
> Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)
> 
> Branch/Commit: master / [b3da866](https://github.com/SickChill/SickChill/commit/b3da866cadff70973fabdbb3ffbe8ad0dd208c49)
> OS: Linux-4.15.0-47-generic-x86_64-with-Ubuntu-16.04-xenial
> Browser: Chrome 73.0.3683.103 (Official Build) (64-bit)
> What you did: Forced Full Update
> What happened: I get this warning often.
> What you expected: To not get this warning.
> Logs:
> 
> ```
> 2019-04-23 03:56:35 SHOWQUEUE-REFRESH :: Unable to find episode with date 2001-09-01 for show 9-1-1, skipping
> ```
> 
> Not sure if this is a scraper issue or SickChill but I get this warning weekly (atleast). There is not an episode listed for that date in the Show either.

I have this too... odd.

**Comment by bluezed** [comment]
Same issue here... The warning is in the logs every day after the general refresh runs.
Looks like somehow the show name 9-1-1 gets interpreted as a date maybe!?

**Comment by rd1** [comment]
bug is still happening:

2022-01-23 02:19:56 Unable to find episode with date 2005-10-03 for show The Neighborhood, skipping
