### ISSUE TITLE
Extremely long show page load times on Android Chrome

### ISSUE THREAD

**Issue by danepowell** [SickChill/SickChill#5437]
Branch/Commit: master / b3da866
OS: Ubuntu 18.04
Browser: Android on Chrome
What you did: Load a show page (This Old House and House Hunters consistently have this problem)
What happened: Took 1-5 minutes to load the show page
What you expected: Page should load in a reasonable time (<5 s)
Logs: Sickchill does not appear to generate any server-side logs with page requests. However you can see in Chrome Inspector the evidence of what's happening here:
![networklog](https://user-images.githubusercontent.com/1984514/56597062-8f05a880-65a6-11e9-83fc-8391df7aeb60.png)

You can see that there's almost a minute between the fanart loading and the next get_messages call. What this looks like in practice is that page is totally unresponsive and the fanart is missing, then after a minute the fanart snaps in and everything starts working.

Also what's odd is that if I look at the Apache logs, I see a ton of GET requests to get_messages even while the fanart is still loading, even though that's not really reflected in the inspector logs. It's like they are all stacking up or something and overloading the client/server.

I can't reproduce this in Firefox on Android, only Chrome

**Comment by WebSpider** [comment]
Try clearning logfile notifications, or shorten logfiles. Does that help?

**Comment by danepowell** [comment]
I assume you mean the server-side logs. Thanks for the suggestion, but no, clearing those doesn't seem to make a difference. I already have them set to a pretty minimal 500Kb max.

Originally I said this doesn't happen on Firefox mobile, but in fact it is somewhat of an issue there too, just not as bad as Chrome. Interestingly, Firefox throws a warning about the vender.min.js script being unresponsive.
