### ISSUE TITLE
IPTorrents. Error: TypeError('tuple indices must be integers, not str',) on any search

### ISSUE THREAD

**Issue by chris023** [SickChill/SickChill#5451]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: b3da866cadff70973fabdbb3ffbe8ad0dd208c49
Version: v2019.04.07-1
Database Version: 44.0

OS: Windows
Browser: Firefox
What you did: Search for torrent on IPT.  IPT is configured even though the logs think it isnt
What happened: IPTorrents. Error: TypeError('tuple indices must be integers, not str',)
What you expected: Not this error
Logs:
2019-05-01 16:35:09 INFO     SEARCHQUEUE-MANUAL-121361 :: Unable to find a download for: [Game of Thrones - S08E01 - Winterfell]
2019-05-01 16:35:09 INFO     SEARCHQUEUE-MANUAL-121361 :: [IPTorrents] :: No NZB/Torrent providers found or enabled in the sickchill config for backlog searches. Please check your settings.
AA TypeError: tuple indices must be integers, not str
AA return (logger.ERROR, logger.WARNING)[exception.message and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception.message]
AA File "D:\SickChill\SickChill\sickbeard\helpers.py", line 1522, in get_level
AA logger.log(default.format(error, type(error.__class__.__name__)), get_level(error))
AA File "D:\SickChill\SickChill\sickbeard\helpers.py", line 1578, in handle_requests_exception
AA handle_requests_exception(error)
AA File "D:\SickChill\SickChill\sickbeard\helpers.py", line 1465, in getURL
AA return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs)
AA File "D:\SickChill\SickChill\sickchill\providers\GenericProvider.py", line 372, in get_url
AA self.get_url(login_url, returns='text')
AA File "D:\SickChill\SickChill\sickbeard\providers\iptorrents.py", line 83, in login
AA if not self.login():
AA File "D:\SickChill\SickChill\sickbeard\providers\iptorrents.py", line 108, in search
AA items_list += self.search(search_string, ep_obj=episode)
AA File "D:\SickChill\SickChill\sickchill\providers\GenericProvider.py", line 170, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "D:\SickChill\SickChill\sickbeard\search.py", line 474, in searchProviders
AA TypeError: tuple indices must be integers, not str
AA return (logger.ERROR, logger.WARNING)[exception.message and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception.message]
AA File "D:\SickChill\SickChill\sickbeard\helpers.py", line 1522, in get_level
AA logger.log(default.format(error, type(error.__class__.__name__)), get_level(error))
AA File "D:\SickChill\SickChill\sickbeard\helpers.py", line 1578, in handle_requests_exception
AA handle_requests_exception(error)
AA File "D:\SickChill\SickChill\sickbeard\helpers.py", line 1465, in getURL
AA return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs)
AA File "D:\SickChill\SickChill\sickchill\providers\GenericProvider.py", line 372, in get_url
AA self.get_url(login_url, returns='text')
AA File "D:\SickChill\SickChill\sickbeard\providers\iptorrents.py", line 83, in login
AA if not self.login():
AA File "D:\SickChill\SickChill\sickbeard\providers\iptorrents.py", line 108, in search
AA items_list += self.search(search_string, ep_obj=episode)
AA File "D:\SickChill\SickChill\sickchill\providers\GenericProvider.py", line 170, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "D:\SickChill\SickChill\sickbeard\search.py", line 474, in searchProviders

**Comment by pcmerc** [comment]
Try this, in your Seach Provider configuration, remove the username/password & fill in the cookie options instead. Example __cfduid=L3EbngcbyVwcSSK6oqdJA6u83cmQed6UcdFmDzdLsQKv;uid=3368768;pass=pbpjsfb6r6oba7gtxjki2a2evq8wm8mr

This appears to have corrected the issue for me.
