### ISSUE TITLE
[FEATURE REQUEST] - Parse a per-torrent download folder

### ISSUE THREAD

**Issue by dejh0n** [SickChill/SickChill#5454]
So I currently have SickChill setup to scan my download folder and then once Transmission has finished downloading the torrent, SC moves it to the correct folder for me Eg.- /TV Shows/[Show Name]/[Season #].

Can we have it so that SC parses this 'final' location to Transmission BEFORE download? On a per torrent basis? (like we have currently, but its only a single location).

AKA when you download Game.of.Thrones.S08E04.1080p it sends the torrent to Transmission with the folder /TV Shows/Game of Thrones/S 08 or if The.Simpsons.S26E13.720p it sends it with /TV Shows/The Simpsons/S 26 as the folder

Hopefully this makes sense

**Comment by WebSpider** [comment]
This would only work when the content downloaded requires no post-processing, which usually is not the case.

**Comment by dejh0n** [comment]
That’s strange. Other than moving my files my content requires 0 post-processing..

**Comment by WebSpider** [comment]
So your content doesn't :

- require to be unrared
- require series information, such as episode descriptions, poster info, etc to be written
- subtitles to be downloaded
.....

?

**Comment by dejh0n** [comment]
Nope, none of those.

 

1.	I stopped using Usenet – no more RAR
2.	All of that information is handled by Plex
3.	All files are English which is my primary language

**Comment by miigotu** [comment]
This might be a possibility. Plex and some other clients don't require renaming or metadata handed to it.

**Comment by miigotu** [comment]
We would use curly brace tags like the renamer to say what to send to the client, and if they are present in the download location disable the post processor? I am not sure how we would mark them from snatched to downloaded though.
