### ISSUE TITLE
Deluge: download path is not passed

### ISSUE THREAD

**Issue by doucheymcdoucherson** [SickChill/SickChill#5476]
Branch/Commit: 175df89cabf295358b8caa2d96dafadb2347622d 
Deluge: 1.3.15
OS: Synology 

I've set a directory in "Downloaded files location" in Search Settings -> Torrent Search. Torrent gets passed to Deluge without the configured path. The Deluge default download directory is used instead. Expectation is for SickChill to pass the directory specified in  "Downloaded files location" to Deluge, overriding the default directory. 

Nothing relevant in the debug logs about the "Downloaded files location" directory when a torrent is sent from SickChill to Deluge. 

Looks like this was previously filed in #3082 but not fixed. The workaround mentioned does not work for my particular needs. I have SickChill set to download to a particular directory and then a label in Deluge applied which will move it from that directory to a different one when the download is complete. The Deluge default directory is on a different volume, so hardlinking between the two is not possible.

**Comment by doucheymcdoucherson** [comment]
So it looks like SickChill is using this path as a "move when completed" directory, although that's not clear from the wording in the UI. Reference: https://github.com/SickChill/SickChill/blob/master/sickbeard/clients/deluged_client.py

Couchpotato allows configuration for both "directory" and "completed directory" for Deluge. Perhaps "Downloaded files location" can be kept and renamed/reworded in the UI and the directory option be added as well? Couchpotato reference: https://github.com/CouchPotato/CouchPotatoServer/blob/master/couchpotato/core/downloaders/deluge.py

**Comment by WebSpider** [comment]
Hey! Your PR seems to cause some issues for people. I referenced the issues to your PR.

Could you have a look what's going on?

**Comment by doucheymcdoucherson** [comment]
feature added in #5495 - closing
