### ISSUE TITLE
Import existing shows - display shows duplicated folder name

### ISSUE THREAD

**Issue by marka65** [SickChill/SickChill#5478]
Branch/Commit: master/75df89cabf295358b8caa2d96dafadb2347622d
OS: Linux-3.13.0-132-generic-x86_64-with-Ubuntu-14.04-trusty
Browser: Doesn't matter
What you did: Try to import existing shows from directory
What happened: The shows imported all ok, but display name for directory in "#5 Verify Your Input" duplicates the folder name. This happens every single one imported.
What you expected: Not to display duplicate folder name

![Sickchill version](https://user-images.githubusercontent.com/16505919/57903351-0205f480-78b1-11e9-9b91-cd5c0394d287.png)

![Sickchill import existing show](https://user-images.githubusercontent.com/16505919/57903356-06321200-78b1-11e9-9c51-995d9c12cdb7.png)

**Comment by albeec13** [comment]
I've run into this and at the moment it makes it impossible to import a show.

**Comment by jiska78** [comment]
I've got this issue too
