### ISSUE TITLE
Mako error prevents Server Status page from opening

### ISSUE THREAD

**Issue by rEes9P** [SickChill/SickChill#5483]
**Branch/Commit:** master/175df89cabf295358b8caa2d96dafadb2347622d

**OS:** macOS High Sierra (10.13.6)

**Browser:** Safari

**What you did:** Tried to access the Server Status page

**What happened:** The page couldn't open because of a Mako Error with the following error message

**What you expected:** The page to open

**Logs:**
```
File /Applications/SickChill/gui/slick/views/status.mako:112, in render_content: ${service.lastRun.strftime(dateTimeFormat)} ValueError: year=1819 is before 1900; the datetime strftime() methods require year >= 1900
```

**Comment by miigotu** [comment]
Set the year correctly on the server?

**Comment by rEes9P** [comment]
Sorry, I didn't get that that was a question directed at me. How do I set the year correctly on the server?

**Comment by WebSpider** [comment]
That would depend on the server.

**Comment by rEes9P** [comment]
I'm running SC on a Mac. How would I go about doing this?

**Comment by miigotu** [comment]
Open a terminal and type date and tell me what it says

**Comment by rEes9P** [comment]
Tue Jun  4 00:47:47 IST 2019

**Comment by miigotu** [comment]
The only thing I can think might have happened is if you set way too high of a cycleTime for a thread
