### ISSUE TITLE
[APP SUBMITTED]: DAILYSEARCHER :: [175df89] Missing time zone for network: Spectrum. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by divx-guy** [SickChill/SickChill#5485]
### INFO
Python Version: **2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@175df89cabf295358b8caa2d96dafadb2347622d
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [175df89] Missing time zone for network: Spectrum. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by javelin4effect** [comment]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@175df89cabf295358b8caa2d96dafadb2347622d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [175df89] Missing time zone for network: Spectrum. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
