### ISSUE TITLE
Git Reset Option Absent

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#5494]
Branch/Commit: Any/All
Branch: master
Commit: 9ae2c845db7315015ae07f3f486661a62947a288
Version: v2019.05.20-1

OS: Windows 10
Browser: Firefox
What you did: Followed the instructions to go to Settings > General > Advanced
(As a workaround I went to config.ini and set to 1 manually)
What happened: No Git Reset option
What you expected: To see Git Reset as an option

Not a major issue, I managed to fix the update problems by using the standard steps but for a long time the interface has been pointing to a missing option to fix the problem, could the text be replaced with the standard steps to fix update problems or just include the option in the interface?

**Comment by WebSpider** [comment]
Git reset is not to be found in the SC interface. Could you let me know which piece of documentation let you to believe this?

**Comment by rutskiuk** [comment]
Here are a couple of areas of documentation that refer to it in the settings:

The section called "I have problems updating or my installation got corrupt. What now?"
https://github.com/SickChill/SickChill/wiki/FAQ%27s-and-Fixes

The section Github > Git Reset
https://github.com/SickChill/SickChill/wiki/Settings-explained

**Comment by rutskiuk** [comment]
Not forgetting after a failed update the error message in the log that says to please enable Git Reset in the settings

**Comment by miigotu** [comment]
Git reset is forced in code to True currently. The text in the error message is just not changed since git reset might not always be forced.
