### ISSUE TITLE
Can't use simple name pattern only containing episode number in filename

### ISSUE THREAD

**Issue by Programie** [SickChill/SickChill#5504]
Branch/Commit: master/b3da866cadff70973fabdbb3ffbe8ad0dd208c49
OS: Ubuntu 18.10 (linuxserver/sickchill Docker Image)
Browser: Chrome 75.0.3770.51 (Beta)
What you did: Trying to use "S%0S/E%0E" as name pattern for the episode naming
What happened: SickChill shows an error "This pattern is invalid"
What you expected: The pattern should just work.

Why can't I use simple filenames like E01.mkv for my episodes? They are already unique based on the parent folders (Showname/S<season number>)...

**Comment by miigotu** [comment]
Because it will confuse media player scanners, must have Season and Episode in the file name.
