### ISSUE TITLE
Network drives not recognized

### ISSUE THREAD

**Issue by fleinbach** [SickChill/SickChill#5510]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by fleinbach** [comment]
Cannot access network drive. All my programming is on 2 other computers on network drive. I have used Sickrage for several years but thought I would try Sickchill. Network drives worked fine in Sickrage on another computer. I installed Sickchill on a different computer so I could keep using Sickrage until I get Sickchill running. I have tried several things from previous posts but still cannot get it to work.

**Comment by WebSpider** [comment]
What have you tried?
What worked with SR?
Please add logs?

**Comment by fleinbach** [comment]
What have you tried? I tried to access network drives using Sickchill but cannot. 
What worked with SR? Network Drives worked with SR
Please add logs? Added
[sickchill.log](https://github.com/SickChill/SickChill/files/3230248/sickchill.log)

**Comment by fleinbach** [comment]
SickRage had no issue with network drives so Why does Sick Chill?

**Comment by pro-src** [comment]
<details><summary>Hmm...</summary>

I'd imagine this to be a Windows only problem that has something to do with `os.path.isdir`?
https://github.com/SickChill/SickChill/blob/86207e9e728f4685e5b92a14674d2ae4e6e1279b/sickbeard/tv.py#L1712-L1714

https://github.com/SickChill/SickChill/blob/86207e9e728f4685e5b92a14674d2ae4e6e1279b/sickchill/helper/encoding.py#L41-L42
So the `ek` isn't doing anything special on Windows, it becomes:
```py
os.path.isdir(self.show._location)
```

I'm not really sure at the moment but a quick search: https://www.google.com/search?q=os.path.isdir+windows+network+drive

If the drive is accessible but `sickbeard.CREATE_MISSING_SHOW_DIRS` isn't true, you'll see the same. I'd have to trace that back unless somebody else already knows.
</details>

Do the show directories already exist? i.e. Q:\TV4
If you created the directories that are mentioned in the logs to see if the problem persists, It'd probably help narrow it down.

Also, It'd be better if you could remove the old log first. It's already huge. lol

**Comment by fleinbach** [comment]
Yes I have 485 TV shows totaling 23,876 episodes on 4 6TB drives. I had acquired most using sickbeard then Sickrage. I never had a problem for years with SickRage but now it is doing some strange things that is why I decided to try installing SickChill. SickRage is still running and keeping most shows up to date and all on the 4 network drives. It started cycling through numerous shows re-downloading them and won't stop. That is why I thought I should start with a new install.

**Comment by pro-src** [comment]
That's quite a collection!
Could you execute the following snippet using the same python interpreter that you use to run SickChill?

Original snippet from https://stackoverflow.com/a/34809340
<details><summary>Code snippet</summary>

```py
import os
import ctypes
from ctypes import wintypes

mpr = ctypes.WinDLL('mpr')

ERROR_SUCCESS   = 0x0000
ERROR_MORE_DATA = 0x00EA

wintypes.LPDWORD = ctypes.POINTER(wintypes.DWORD)
mpr.WNetGetConnectionW.restype = wintypes.DWORD
mpr.WNetGetConnectionW.argtypes = (wintypes.LPCWSTR,
                                   wintypes.LPWSTR,
                                   wintypes.LPDWORD)

def get_connection(local_name):
    length = (wintypes.DWORD * 1)()
    result = mpr.WNetGetConnectionW(local_name, None, length)
    if result != ERROR_MORE_DATA:
        raise ctypes.WinError(result)
    remote_name = (wintypes.WCHAR * length[0])()
    result = mpr.WNetGetConnectionW(local_name, remote_name, length)
    if result != ERROR_SUCCESS:
        raise ctypes.WinError(result)
    return remote_name.value

full_unc_path = get_connection('Q:')
print(os.path.isdir('Q:\'))
print(os.path.isdir('Q:\TV4'))
print(os.path.isdir(full_unc_path))
print(os.path.isdir(r'{}\{}'.format(full_unc_path)))
```
</details>

**Comment by fleinbach** [comment]
Sorry I do not know what you mean. I just start SickChill using the executable file. I did start a new log file though.
[sickchill.log](https://github.com/SickChill/SickChill/files/3235110/sickchill.log)

**Comment by pro-src** [comment]
:thinking: No, it's my fault. I'm making too many assumptions there. I'll have to get back to you on this because I'm not sure how best to instruct you on running the snippet. If you had already had a python installation then, you'd be good 2 go.

**Comment by fleinbach** [comment]
Ok thanks, going to bed now.

**Comment by pro-src** [comment]
Ok so AFAIK, SickChill uses setup.py to install which requires a python installation. You should be able to open a shell `cmd.exe` on windows. If python is in your system path, execute python by typing `python.exe` and press the return key [Enter]. This should start the interactive python interpreter. Copy and paste the code snippet followed by the return key again.

Sorry, if I confused you. Let me know if this doesn't make sense.

**Comment by fleinbach** [comment]
Ok, I actually  already did that I think. I executed python from within the SickChill directory and pasted the code.

**Comment by fleinbach** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: tuple index out of range

**Comment by pro-src** [comment]
Great. Unfortunately, something seems to be wrong with that snippet so...

Try this instead:
```py
import os
print(os.path.isdir('Q:\'))
print(os.path.isdir('Q:\TV4'))
```
And if you know the full UNC path:
```py
import os
print(os.path.isdir(full_unc_path))
```

**Comment by fleinbach** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'full_unc_path' is not defined

**Comment by fleinbach** [comment]
Sorry I did that wrong. will try again

**Comment by pro-src** [comment]
That is to be expected, I meant for you to define `full_unc_path` if you know it. You could just run the other and paste the results?

**Comment by pro-src** [comment]
> Sorry I did that wrong. will try again

Thanks

**Comment by fleinbach** [comment]
SyntaxError: EOL while scanning string literal
>>> print(os.path.isdir('Q:\TV4'))
True
>>> And if you know the full UNC path:
  File "<stdin>", line 1
    And if you know the full UNC path:
                  ^
SyntaxError: invalid syntax
>>>
>>> import os
>>> print(os.path.isdir(full_unc_path))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'full_unc_path' is not defined
>>> mport os
  File "<stdin>", line 1
    mport os
           ^
SyntaxError: invalid syntax
>>> print(os.path.isdir('Q:\'))
  File "<stdin>", line 1
    print(os.path.isdir('Q:\'))

**Comment by pro-src** [comment]
Sorry for being unclear. The python interpreter only understand python code. You have to copy the following exactly without my comments:
```py
import os
print(os.path.isdir('Q:\'))
print(os.path.isdir('Q:\TV4'))
```

**Comment by fleinbach** [comment]
UNC is \\Primary\tv4 but I keep getting errors

**Comment by pro-src** [comment]
Actually, I think there is enough information there already.
```py
print(os.path.isdir('Q:\TV4'))
True
```

It means that I'm wrong about `os.path.isdir`. At least something was ruled out!
I'm sure @WebSpider or somebody more experienced will get back to you on this.
Sorry, I can't be of more help at the moment. :(

**Comment by fleinbach** [comment]
Thanks for you help.

**Comment by fleinbach** [comment]
I'm wondering if this has anything to do with Microsoft updating windows 10 earlier this year. They screwed up networking terribly for a few months. I have been using network drives for over 20 years and I had all kind of problems back in January and from what I read Microsoft was aware of it and said it would be fixed. Well for the past month or so it seemed to be working properly.

**Comment by BenjV** [comment]
Your question "Cannot use network drive" is a little vage.
Please specify where and how you want to use network drives.
Tell us in which field of SickChill you put what.
Do you use UNC of do you use a drive mapping?
Can you access those share with the explorer?
Did you adjust the firewall to allow SickChill to access those shares?

And by the way the Microsoft issue was with smb2 shares, so only when you use smb2 (which you should not do, smb3 was released in 2011)

**Comment by fleinbach** [comment]
Do you use UNC of do you use a drive mapping? I use windows 
drive mapping but I tried UNC which also does not work.
Can you access those share with the explorer? Yes all my network drives work fine using explorer.

Did you adjust the firewall to allow SickChill to access those shares? My firewall allows Sickchill

The Microsoft issue I was speaking of had to do with shared computers not appearing in Explorer. It also had something to do with dropping Homegroups.

**Comment by BenjV** [comment]
Show de input you used in SickChill.
And the windows firewall on both machines must be set to allow SickChill not only the one on the machine witch is running SickChill.
I use remote shares all the time with SickChill so it has to be something in your configuration or environment..

**Comment by fleinbach** [comment]
I did not know I had to setup Sickchill in the firewall on the other computer. I will do it and let you know. Thganks

**Comment by fleinbach** [comment]
I cannot find the SickChill executable on the computer it is installed on.

**Comment by BenjV** [comment]
you need to allow sm access from the SickChill computer.

**Comment by fleinbach** [comment]
I am sorry for my ignorance but after working with computers for over 30 years I never even heard of SMB. After reading about it I still have no idea how to activate it. Under windows features there are 4 choices for SMB. Which one is the correct one?

**Comment by BenjV** [comment]
SMB is the protocol used for accesssing shares.
It is standard installed on every Windows computer.
But if you can access the shares from the windows explorer the firewall is not the problem unless you are running SickChill under a different users then the explorer.

As I asked before please tell us where in SicKChill you defined that it must use the share en show here what the exact input is that you put into that field.

**Comment by fleinbach** [comment]
I chose one of the 485 tv shows I already have (This is what I see  N:\TV2\24 Legacy (Missing) and tried to edit the drive it is on. 
Since the edit window only shows access to the local drives I tried to type the UNC  like this \\Plexpc\tv1. When I hit enter it disappears but if I hit the ok button it shows up but when I hit save it reverts back to the network drive.

**Comment by fleinbach** [comment]
I am using different logins on the 2 computers involved but did not think that was the issue since I use SickRage on 2 computers with different logins but it works. That is why I am so confused. Why does SickRage work fine but SickChill doesn't.

**Comment by fleinbach** [comment]
Ok, I made both computer use the same login but still same problem.

**Comment by BenjV** [comment]
An unc has a form of:
//<share>/<folder>
Still not clear what jou are trying to change inwhich field

**Comment by fleinbach** [comment]
Here is screen shot

![Capture](https://user-images.githubusercontent.com/22884563/58752037-11bb3680-8476-11e9-92c4-2eb63faca90e.PNG)

**Comment by BenjV** [comment]
If you have created a share called Plecpc and you have a show called tv1 then this is correct.
Buit seems to me this is a level to high because I don't think you have a show called tv1?

You said you have created a drive mapping so can you browse see that drive letter and browse it in SickChill?

**Comment by fleinbach** [comment]
TV1 is the folder where the shows are. 

My drives are all mapped. I have tried my best to say this since I started.

**Comment by BenjV** [comment]
This screen jou are showing is a per show setting.
I red that but I asked if jou should browse them

**Comment by fleinbach** [comment]
Yes it is a Per show screen but it is where I tried to put in the UNC since the network shares are not seen by SickChill. You wanted to see how I typed the UNC. 
Yes I can browse all my 485 tv shows with Explorer.

**Comment by fleinbach** [comment]
Ok, I installed SickRage on the computer I have been having a problem with SickChill and it sees network drives fine. I suppose I will have to stick with it until maybe someone figures out what is wrong with SickChill. 
SIckRage has some other issues but at least it works properly 90 % of the time.

**Comment by fleinbach** [comment]
SickChill Shows network drive but cannot see the content. There are over 100 shows in each drive. 

![Capture2](https://user-images.githubusercontent.com/22884563/58760705-a1f68b80-8509-11e9-95d0-3ca1ec77db32.PNG)

**Comment by fleinbach** [comment]
Same screen as above but from SickRage. You can see the programs from Q drive that cannot be seen from SickChill.

![Capture3](https://user-images.githubusercontent.com/22884563/58760804-e2a2d480-850a-11e9-911b-0b8e954d6877.JPG)

**Comment by BenjV** [comment]
So the problem is that he SickChill user who is running the program does not have enough access rights to that share.

**Comment by fleinbach** [comment]
I don't understand. Both SR and SC are on the same computer. How does SR work but SC doesn't?

**Comment by WebSpider** [comment]
Network drive mappings are specific to the executing user. Do both SickChill and SickRage run under the same user account?

**Comment by fleinbach** [comment]
Yes they do. I am the only user for all my networked computers. 6 total

**Comment by WebSpider** [comment]
Both run as a Service on your computer, usually with an account that is not equal to your own user account.

This account needs to have the same permissions as the account that SR runs as.

**Comment by fleinbach** [comment]
Also I might mention. SickRage has been running for over a year on a computer that has a different user name then the computer where the network files are. The reason is I setup that computer with a setup image I use when building a new computer fro friends.

**Comment by fleinbach** [comment]
Under services this is where SC says it is located.  C:\SickChill\Installer\nssm.exe  Does that look right?

**Comment by fleinbach** [comment]
I see nothing in services that says what the user account is.

**Comment by fleinbach** [comment]
I just realized SR is not running under services. It says Automatic and when I hit start it says it cannot be found. I moved SR over a year ago to a newly built computer. I just copied the solder over to the new computer and it has been working ever since.

**Comment by fleinbach** [comment]
Any other idea's? Still does not work.

**Comment by itsme9x** [comment]
> Any other idea's? Still does not work.

https://www.reddit.com/r/sickchill/comments/cn0yj8/tutorial_fix_unrecognized_shared_network_drives/

**Comment by nydave69** [comment]
did you use the windows installation for sickchill...  and did it create a service for you?

**Comment by itsme9x** [comment]
yes and yes

**Comment by rtrive** [comment]
for me this "fix" didn't work. I'm not able to access to shared volume even if sickchill service is setup with right user

**Comment by nydave69** [comment]
> for me this "fix" didn't work. I'm not able to access to shared volume even if sickchill service is setup with right user

I had the same problem under Windows 7...
No mater what I did with the SC service I just couldn't get it to work..

What I did was;
Stop and disable the service
Locate SC where it was installed (this depends on the version that was installed)
in my case it is c:\sickchill
I then run it from a command window (cmd.exe) it needs to remain running all the time.
In my case;
C:\SickChill\Python3\tools\python.exe C:\SickChill\Python3\tools\Scripts\SickChill.py --nolaunch --port 8085 --datadir C:\\SickChill\\Data
I also changed the Web port access to 8085 since I have another app that uses the 8081 port
I created a desktop short cut to start SC when I need to.
Since your actually starting it it inherits that users permissions.

This may not be ideal but if it does run this way than you know it's something with SC permissions messing things up.
I also create drives that point to the media folders and have SC use the drive letters.

**Comment by rtrive** [comment]
> 
> I had the same problem under Windows 7... No mater what I did with the SC service I just couldn't get it to work..
> 
> What I did was; Stop and disable the service Locate SC where it was installed (this depends on the version that was installed) in my case it is c:\sickchill I then run it from a command window (cmd.exe) it needs to remain running all the time. In my case; C:\SickChill\Python3\tools\python.exe C:\SickChill\Python3\tools\Scripts\SickChill.py --nolaunch --port 8085 --datadir C:\SickChill\Data I also changed the Web port access to 8085 since I have another app that uses the 8081 port I created a desktop short cut to start SC when I need to. Since your actually starting it it inherits that users permissions.
> 
> This may not be ideal but if it does run this way than you know it's something with SC permissions messing things up. I also create drives that point to the media folders and have SC use the drive letters.

I tried this way right now and works. So something is wrong with SC service
