### ISSUE TITLE
Renaming shows skips .srt .nfo and .tbn files

### ISSUE THREAD

**Issue by marcofranssen** [SickChill/SickChill#5511]
When renaming shows it only renames the video file.

All other files like the following are always skipped.

- .srt
- .nfo
- .tbn

In my case the orginal files have file names identical to the .mp4 or the .mkv files. After the rename is done the .mkv / .mp4 gets the new filename as expected, but the others don't change.

It seems this issue has been in there before #1332. This issue was specifically for subs, but in this case it goes basically for any files related the the video file that is not renamed, also not the subs.

I did check things like file permissions and file owners. Even when these are same as the video the rename does not pick the .srt .nfo and .tbn file.

As far it might make a difference I can also mention my shows are renamed using the following pattern.

`Season %0S/%SN - S%0SE%0E - %EN` meaning they end up in a folder per season.

Would be great if someone known to the codebase could resolve this as it takes me tons of manual work getting those filed renamed now.

**Comment by optio50** [comment]
I am also affected

Branch/Commit: Master 6bfdb2236003331e639a1845f765ee0462ae8a5d 
OS: Linux
Browser: Firefox
What you did: Renamed selected files after preview rename clicked
What happened: Video files renamed but not associated files (tbn nfo srt)
What you expected: All files to be renamed

**Comment by marcofranssen** [comment]
This is already since the SickRage repository since a couple of months ago. I'm not deeply enough in the code to fix this myself. Would really be great if a core contributor could fix this.

**Comment by John-Gee** [comment]
Same here, but with some tutoring I'd be happy to try and create a patch for this.

**Comment by marcofranssen** [comment]
Anyone in here who knows where to start to resolve this? I'm happy to assist if someone can guide.

**Comment by John-Gee** [comment]
I'm guessing it's something to do in the "doRename" function in home.py.

Maybe it just loops on the files for the episodes and does not probe for more. It should not be too hard to verify that I suppose.

**Comment by John-Gee** [comment]
@marcofranssen: Well I think it's just some sort of cached data bug, but this seems to work for me:

In Post Processing options, uncheck "Move associated files", save settings, recheck "Move associated files", save settings. And that's it.

I thought "Associated file extensions" mattered but no, the renamer picked a file with ".test" extension just fine without putting it in that list.

Same for "Rename .nfo file" it does not seem related.

Does that work for you too or am I just getting crazy, looking at this so late?

**Comment by marcofranssen** [comment]
@John-Gee you are right. Once the checkbox is enabled and I add the tbn extension in the list all works.

Maybe still it makes sense to enable this setting by default as it seems many people are struggling with this. 

I never enabled the autoprocessing option and therefore assumed the other settings would not apply to anything. Seems some of these settings are used in the manual rename functionality as well.

**Comment by John-Gee** [comment]
Yeah it's a bit strange. I would not have thought of looking in that tab without debugging the code.

Maybe that setting is enabled by default, but only for new users. It was checked for me, but didn't do anything... I have not found any other PP setting used in renaming though, but truthfully I only tested 3.
