### ISSUE TITLE
2019-05-30 19:28:28 ThreadPoolExecutor-0_2 :: [86207e9] Missing time zone for network: TV2 (NZ). Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by mosscow** [SickChill/SickChill#5517]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```
2019-05-30 19:28:28 ThreadPoolExecutor-0_2 :: [86207e9] Missing time zone for network: TV2 (NZ). Check valid network is set in indexer (theTVDB) before filing issue.

**Comment by naydichev** [comment]
This is still happening for me.
