### ISSUE TITLE
Req: New show status

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#5521]
Is it possible to get a new status like "Waiting for new season" or "Between seasons"? Maybe changing the status of shows in season to "Airing" or "In season"? Right now shows that are airing or the season has ended but there are new seasons coming will show as "Continuing". The new status would be awesome for sorting when you want to binge seasons.

**Comment by miigotu** [comment]
Those statuses come from thetvdb. We dont create those from thin air =P.
You could always ask them on their site.
