### ISSUE TITLE
[APP SUBMITTED]: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python.

### ISSUE THREAD

**Issue by psa99** [SickChill/SickChill#5522]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [0fd732b] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-321285 :: [Torrent9] :: [0fd732b] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311714 :: [Torrent9] :: [0fd732b] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-269586 :: [Torrent9] :: [0fd732b] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-281470 :: [Torrent9] :: [0fd732b] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-330525 :: [Torrent9] :: [0fd732b] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295648 :: [Torrent9] :: [0fd732b] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295647 :: [Torrent9] :: [0fd732b] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [0fd732b] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-95011 :: [Torrent9] :: [0fd732b] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by informagenie** [comment]
May be because Torrent9 is now available now to [torrent9.cz](https://site-de-streaming.com/torrent9-change-dadresse/) ?

**Comment by Varashi** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-81797 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar 11 2019, 18:59:25) [GCC 8.2.1 20181127]**
Operating System: **Linux-5.2.11-1-MANJARO-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by psa99** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/fc1d76fb55a89c5e72b7fff213574fc1
### ERROR
```
SEARCHQUEUE-BACKLOG-321670 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by studio-es-lee** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by studio-es-lee** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by studio-es-lee** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-247808 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by studio-es-lee** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-266189 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [TorrentDay] :: [TorrentDay] :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-361315 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-328634 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-164541 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295760 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-79619 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295759 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-73762 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-289590 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-257655 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-328724 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by doncoque** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-5.0.0-32-generic-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-114801 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-363714 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-305719 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-279121 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar 11 2019, 18:59:25) [GCC 8.2.1 20181127]**
Operating System: **Linux-5.3.6-1-MANJARO-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-293088 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar 11 2019, 18:59:25) [GCC 8.2.1 20181127]**
Operating System: **Linux-5.3.6-1-MANJARO-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-250487 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar 11 2019, 18:59:25) [GCC 8.2.1 20181127]**
Operating System: **Linux-5.3.6-1-MANJARO-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-260449 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar 11 2019, 18:59:25) [GCC 8.2.1 20181127]**
Operating System: **Linux-5.3.6-1-MANJARO-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-80379 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar 11 2019, 18:59:25) [GCC 8.2.1 20181127]**
Operating System: **Linux-5.3.6-1-MANJARO-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-262980 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar 11 2019, 18:59:25) [GCC 8.2.1 20181127]**
Operating System: **Linux-5.3.6-1-MANJARO-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-153021 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar 11 2019, 18:59:25) [GCC 8.2.1 20181127]**
Operating System: **Linux-5.3.6-1-MANJARO-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-257655 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar 11 2019, 18:59:25) [GCC 8.2.1 20181127]**
Operating System: **Linux-5.3.6-1-MANJARO-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar 11 2019, 18:59:25) [GCC 8.2.1 20181127]**
Operating System: **Linux-5.3.6-1-MANJARO-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-263365 :: [Torrent9] :: [e094759] Request failed: Cloudflare captcha challenge presented for ww1.torrent9.nz (cfscrape cannot solve captchas) (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
