### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_0 :: [0fd732b] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by r5464y75** [SickChill/SickChill#5523]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [0fd732b] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Luismcplopes** [comment]
Hi have the same problem.

 ### INFO

**SickChill Info:**
Branch: master
Commit: 0fd732bfc1ced5ff95a27cea6d2d7d93f3e71d8f
Version: v2019.05.31-1
Database Version: 44.0
Python Version: 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
SSL Version: OpenSSL 1.1.0j 20 Nov 2018
OS: Linux-4.14.78-4-osmc-armv7l-with-debian-9.8
Locale: None.None


 ### ERROR
```
2019-06-03 23:43:27 ThreadPoolExecutor-0_2 :: [0fd732b] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
