### ISSUE TITLE
Sorting issue with high number of downloads

### ISSUE THREAD

**Issue by akselfoley** [SickChill/SickChill#5524]
Hi, 
If I sort the shows on downloads the shows with alot of files that misses some episodes is not shown on top as the rest of the shows with missing episodes. They're in the middle with shows where all the episodes are downloaded. The color is light green ofc. But when you got 500+ shows you have to scroll alot to find the shows that are missing episodes.

**Comment by miigotu** [comment]
You can also see what is missing episodes with the dropdown `manage->backlog overview` or `manage->episode status management` and selecting `wanted` status
If you have 500+ __shows__ that's ridic

**Comment by akselfoley** [comment]
Yes, I could use the backlog overview or the episode status management, but I prefer to use the homepage for status overview. Yes, got some show. 
567 Shows (146 Active)  | 34902 / 34970 Episodes Downloaded (99.8%)
