### ISSUE TITLE
[APP SUBMITTED]: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."

### ISSUE THREAD

**Issue by ctrlbrk42** [SickChill/SickChill#5527]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
Link to Log: https://gist.github.com/9bfca8f2b7fc7490e9a5cd300cf3333d
### ERROR
```
SEARCHQUEUE-BACKLOG-72218 :: [HDTorrents] :: [6bfdb22] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ctrlbrk42** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
Link to Log: https://gist.github.com/b86797b19c781441b551e3e48c3cb4e8
### ERROR
```
SEARCHQUEUE-BACKLOG-72218 :: [IPTorrents] :: [6bfdb22] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by pro-src** [comment]
Hi @ctrlbrk42,

I think this error is due to using a very old version of Node.js. Please ensure that you have a currently supported version of Node.js installed. For further instructions related to the Node.js dependency: https://github.com/Anorov/cloudflare-scrape#nodejs-dependency

**Comment by acataldi** [comment]
### INFO
Python Version: **2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-150-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
Link to Log: https://gist.github.com/a7f0ad267cdd0daa75593ecdc0d9d1e9
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] :: [6bfdb22] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by acataldi** [comment]
### INFO
Python Version: **2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-150-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
Link to Log: https://gist.github.com/1a9fc4fac85a13f0f25715dfb970c00a
### ERROR
```
SEARCHQUEUE-BACKLOG-311713 :: [Torrentz] :: [6bfdb22] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by papaxris** [comment]
> Hi @ctrlbrk42,
> 
> I think this error is due to using a very old version of Node.js. Please ensure that you have a currently supported version of Node.js installed. For further instructions related to the Node.js dependency: https://github.com/Anorov/cloudflare-scrape#nodejs-dependency

Hi @pro-src 

Thank you for providing the information.  Upgrading from node.js 4.2 to 8.16 resolved the issue for me.

The Ubuntu repositories have old stable releases.  Had to perform the install from nodesource repo.

**Comment by WebSpider** [comment]
A possible fix for this has been added to the develop branch. Please test and see if this solves your issue.

**Comment by angeloschat** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-365722 :: [TorrentLeech] :: [e094759] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by angeloschat** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-328686 :: [TorrentLeech] :: [e094759] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by angeloschat** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-78957 :: [TorrentLeech] :: [e094759] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by angeloschat** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentLeech] :: [e094759] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by angeloschat** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-258541 :: [TorrentLeech] :: [e094759] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by angeloschat** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [e094759] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ariscottle** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-164-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@17e379df7dadc7711db1c76695411267f245a961
Link to Log: https://gist.github.com/4cdee484778f5c13dc0974827b66ece5
### ERROR
```
SEARCHQUEUE-MANUAL-78804 :: [IPTorrents] :: [17e379d] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ariscottle** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-164-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@17e379df7dadc7711db1c76695411267f245a961
Link to Log: https://gist.github.com/139ed8e596458ccae6b45425158d9215
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [17e379d] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ariscottle** [comment]
### INFO
Python Version: **2.7.12 (default, Aug 22 2019, 16:36:40) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-164-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@17e379df7dadc7711db1c76695411267f245a961
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-MANUAL-78804 :: [IPTorrents] :: [17e379d] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ariscottle** [comment]
### INFO
Python Version: **2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-171-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@17e379df7dadc7711db1c76695411267f245a961
Link to Log: https://gist.github.com/1e7e2334ed79b1dee0bc8f7e089d2f5b
### ERROR
```
SEARCHQUEUE-MANUAL-71663 :: [IPTorrents] :: [17e379d] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ProBator** [comment]
### INFO
Python Version: **2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-171-generic-i686-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@1fc03b73354be2653c4ad5f1e0c7d44c5ea6c5d3
Link to Log: https://gist.github.com/2f01b2a27ea9538b42f4b361f869adcd
### ERROR
```
SEARCHQUEUE-MANUAL-368126 :: [1fc03b7] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ariscottle** [comment]
### INFO
Python Version: **2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-171-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@4dedd01fc6d57622442113f66d180c21f4eaff8c
Link to Log: https://gist.github.com/3b4138c0a5ccb98eaa5d8fc5a4b06e4f
### ERROR
```
SEARCHQUEUE-MANUAL-296830 :: [IPTorrents] :: [4dedd01] Request failed: Cloudflare IUAM challenge returned unexpected answer. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
