### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_0 :: [6bfdb22] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by tfraiseo** [SickChill/SickChill#5528]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [6bfdb22] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by tfraiseo** [comment]
Didn't notice this had already been opened as an issue.  I'm closing this one

**Comment by Snowaks** [comment]
### INFO
Python Version: **2.7.16 (default, May 16 2019, 01:14:27) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)]**
Operating System: **FreeBSD-11.2-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [6bfdb22] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Snowaks** [comment]
### INFO
Python Version: **2.7.16 (default, May 16 2019, 01:14:27) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)]**
Operating System: **FreeBSD-11.2-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [6bfdb22] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Snowaks** [comment]
### INFO
Python Version: **2.7.16 (default, May 16 2019, 01:14:27) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)]**
Operating System: **FreeBSD-11.2-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [6bfdb22] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by millzee69** [comment]
### INFO
Python Version: **2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [6bfdb22] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar  7 2019, 23:06:01) [GCC 8.2.0]**
Operating System: **Linux-3.10.105-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [6bfdb22] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **2.7.16 (default, Mar  7 2019, 23:06:01) [GCC 8.2.0]**
Operating System: **Linux-3.10.105-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [6bfdb22] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
