### ISSUE TITLE
rTorrent connection failing, unable to debug

### ISSUE THREAD

**Issue by dirkr07** [SickChill/SickChill#5530]
So more of a troubleshooting question than a bug.
I'm trying to connect Sickchill to a seedbox with rTorrent on it.

No matter what settings I use i just get "failed to connect to rTorrent" in the test.
Now my question: are there any logs/debug information as to what the test is returning?
I enabled debug logs and also checked the log but don't see anything..

**Comment by dirkr07** [comment]
nvm. the logs didn't say anything but I found the issue.
I switched from Synlogy DS to rTorrent and strangely I had to save the settings of rTorrent before the test would take.

After rTorrent is saved it works and changing things gives a proper test.
Seems that somehow the switch didn't take in runtime and it was doing the test incorrectly.

**Comment by rasmusbe** [comment]
I had the same problem now so thank you for the info about saving.
I see two problems in the rtorrent integration:
1. "Test Connection" doesn't give any output in the debug log.
2. "Test Connection" doesn't work without saving the settings first.

**Comment by rasmusbe** [comment]
Still a problem

**Comment by Tsaukpaetra** [comment]
Yep, really bas-ackwards. Spent two hours trying to figure out how to troubleshoot, despite that the Test Connection *very clearly* sends the connection information, it's apparently not actually used whatsoever. Quite insane.
