### ISSUE TITLE
[Feature request] Play on Kodi

### ISSUE THREAD

**Issue by shtrom** [SickChill/SickChill#5548]
With notifications enabled for Kodi, there should be sufficient information to also add some ability to “Play on Kodi”. The first place where that could be done is in the `displayShow` view, alongside the download link.

There may be some difficulty in handling multiple Kodi hosts, but perhaps either only handling the first one, or a rough drop-down list of available hosts would be a good first cut.

**Comment by miigotu** [comment]
Have an icon that would be good for this? I just rewrote the Kodi notifier and can play episodes from it now xD
