### ISSUE TITLE
[Feature request] Batch email notifications

### ISSUE THREAD

**Issue by shtrom** [SickChill/SickChill#5549]
Currently, SickChill notifies by email separately on every new episode.

This can lead to a bit of noise when, say, a whole season is available at once, or just if a few episodes of various series have been finished getting acquired more or less at the same time.

It would be good to be able to batch those notifications by, say half-an-hour to an hour (up to, maybe, a day, perhaps with a configurable time of notification), so that a single email is sent with a list of the recently finished series/seasons/episodes (and a link to play them in Kodi #5548 :trollface: )

**Comment by RB14060** [comment]
Adding my support of this. I use Pushover notifications so it's quite annoying to get 10s-100s of notifications at once especially when I'm loading a new show for the first time. I also have Plex notifications enabled and it causes my Plex to get a large amount of library update requests all at once which causes it to not properly load metadata for a while until it updates in the background.
