### ISSUE TITLE
General config menu 

### ISSUE THREAD

**Issue by pigsyn** [SickChill/SickChill#5551]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: release v2019.06.27-1
OS: Linux
Browser: All
What you did: access config->general menu
What happened: Oops: 404 Not Found
What you expected: Accessing general configuration menu
Logs:
```
2019-06-27 12:26:21 DEBUG    TORNADO :: Failed doing ***** request "general": Traceback (most recent call last):
  File "/opt/sickrage/sickchill/views/index.py", line 156, in get
    method = getattr(self, route)
AttributeError: 'Config' object has no attribute 'general'
```

**Comment by Wally73** [comment]
happens on windows too

AA AttributeError: 'Config' object has no attribute 'general'
AA method = getattr(self, route)
AA File "G:\SR1\sickchill\views\index.py", line 156, in get
2019-06-27 13:01:22 DEBUG TORNADO :: Failed doing webui request
"general": Traceback (most recent call last):
AA None

**Comment by skillfr** [comment]
idem

**Comment by miigotu** [comment]
Thanks for the PR
