### ISSUE TITLE
Issue browsing directories

### ISSUE THREAD

**Issue by NunoHiggs** [SickChill/SickChill#5553]
Branch/Commit: Master
OS: Linux Centos 7.6
Browser: Any
What you did: Tried to change a show dir
What happened: Nothing. Browser just sat there.
What you expected: To see the directories of show or server.
Logs:
```

Inside the sickchill.log i found this error. 

2019-06-27 16:21:34 DEBUG    TORNADO :: Failed doing webui request "browser": Traceback (most recent call last):
  File "/opt/SickRage/sickchill/views/index.py", line 156, in get
    method = getattr(self, route)
AttributeError: 'WebRoot' object has no attribute 'browser'
```
Also i've tried to do a fresh install and the issue is the same.

**Comment by thenamelessthing** [comment]
I have the same behavior. I'm under Ubuntu 16.04

**Comment by miigotu** [comment]
Fixed, please update
