### ISSUE TITLE
[Feature Request] Utilize "open directories" for downloads

### ISSUE THREAD

**Issue by Castrol69** [SickChill/SickChill#5554]
Is it possible to use "Open Directories" with WGET to download episodes.
Similar to the search tool filepursuit.com does but automated?
If not possible is it possible for the user to manually add web directories that they find to include in search?

Great work guys

**Comment by WebSpider** [comment]
[Disclaimer: All i know about filepursuit is a 10sec Google] 

SickChill does not do it's downloads itself, it hands this over to another piece of software (we call them clients) to do this.

If there is a sufficiently advanced client available that can grab stuff from filepursuit, we could consider integrating this.

For searches, we use a concept called providers. If filepursuit has a search API we can connect to, we could consider integrating filepursuit as a searchprovider.
