### ISSUE TITLE
WebRoot object has no attribute browser

### ISSUE THREAD

**Issue by egrueda** [SickChill/SickChill#5558]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 6d86b33618952100cafd6b322bc295246a228c00
Version: v2019.06.27-2
OS: Linux-4.19.50-v7l+-armv7l-with-debian-10.0
Browser: Chrome
What you did: Click on any "Browse" buttons to select a path
What happened: error 404
What you expected: modal file browse should show
Logs:
```
2019-06-28 18:09:24 DEBUG    TORNADO :: Failed doing webui request "browser": Traceback (most recent call last):
  File "/opt/sickchill/sickchill/views/index.py", line 156, in get
    method = getattr(self, route)
AttributeError: 'WebRoot' object has no attribute 'browser'
```

Devtools show the 404 error for the URL:

```
http://192.168.0.100:8081/browser/?path=&includeFiles=0&fileTypes=
```

Any help?

**Comment by pigsyn** [comment]
see #5553

**Comment by egrueda** [comment]
> see #5553

You're right, same issue.
Sorry

**Comment by miigotu** [comment]
@pigsyn, thanks again!
