### ISSUE TITLE
[Feature request] schedule: display past shows

### ISSUE THREAD

**Issue by Celforyon** [SickChill/SickChill#5565]
It would be nice to be able to choose a time range of past shows to be kept in the schedule.
Currently, a show disappear as soon as its airdate is reached, meaning that if a show airs at 3am, when looking in the schedule, it will not be shown for most of the day it airs. One must look the day before.

I propose a time range to let people keep the current behaviour by setting 0, but this can be achieved by adding a checkbox enabling a pre-defined time range, should it be simpler.

**Comment by Viss** [comment]
+1 this.
I'd like to be able to tell sickchill how far into the future the schedule should see.
