### ISSUE TITLE
Shows in Archived status after hard drive swap

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#5569]
Branch: master
Commit: 1ed315660d99f6673a3bb53363fdff6902b89429
Version: v2019.06.28-1
Database Version: 44.0
OS: Windows 10
Browser: Firefox 67.0.4

What you did: Updated hard drive (backed up all content to another larger drive then changed that drive letter to the original drive letter)
What happened: shows went to archived status
What you expected: shows to be recognised if a hard drive is replaced, drive letter swapped to match the original location and the same files are in the same location/path with the same name. Especially after a full show re-scan, I shouldn't have to delete all the shows and start again.

Logs:
```
https://ufile.io/dqpvr0vq
https://ufile.io/nie0d6ts

Here's an example of a file that is showing archived:
D:\TV\Almost Human\Season 01\Almost Human - S01E13 - Straw Man.mp4
The same file in what was the D drive but now K after the transition:
K:\TV\Almost Human\Season 01\Almost Human - S01E13 - Straw Man.mp4

If I'm missing something obvious please let me know!
```

**Comment by rob006** [comment]
`D:\TV\Almost Human\Season 01\Almost Human - S01E13 - Straw Man.mp4` and `K:\TV\Almost Human\Season 01\Almost Human - S01E13 - Straw Man.mp4` are two different paths, why you're expecting that they will be treated as one?

**Comment by rutskiuk** [comment]
I'm not expecting them to be treated as one path.

The problem I have is that the drive that is now K was D, I copied the contents to the new drive D with the exact same folder structure and file name. What I am trying to show is evidence that the naming and location is identical but the file is now showing as archived. I'm not expecting a file in the K drive to be located, I'm expecting the file in the same D location with the same file name to be located.

**Comment by rob006** [comment]
Path of the file is treated as its identifier, so different drives -> different paths -> different files. If you move `D:\TV\Almost Human\Season 01\Almost Human - S01E13 - Straw Man.mp4` into `K:\TV\Almost Human\Season 01\Almost Human - S01E13 - Straw Man.mp4`, then `D:\TV\Almost Human\Season 01\Almost Human - S01E13 - Straw Man.mp4` is treated as deleted, because there is no file under that path.

**Comment by rutskiuk** [comment]
I did not move the file, I copied it. The original file never left its location. Once the copy process completed I changed the drive I copied to to drive D and the original drive D to drive K.

**Comment by WebSpider** [comment]
Does SC have permissions on the file system of the new drive to access the files?

**Comment by rutskiuk** [comment]
I've now manually removed the shows and re-added them. The extent of the problem wasn't the hundreds of shows I first thought, it was only a dozen. I've come to the conclusion that in the few seconds it took for me to reallocate the drive letter a show re-scan was either triggered or in progress and that's what put shows into an archived status. It would be nice if the presence of the file could take an episode out of archived status but I'm just glad that I don't have to recreate the entire library. Having to re-add 834 shows and making sure the quality matches the download for each would take a long time to fix and the prospect of that was intimidating.
