### ISSUE TITLE
REQ: More/better caching of data/images

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#5572]
First of all - hope the move went fine and without issues. After all, we need you more than your family :p 

This is not an urgent request, but as there's already quite a bit of caching going on I was hoping it's possible to extend this a bit. The way I use SC is that I delete the directory once I've watched the contents. This makes it easier to see which shows have unwatched episodes. When a new episode is downloaded, SC will have to redownload a lot of information. Let's use The Simpsons as an example, where 30 seasons worth is checked. Would it be possible to have most of this in a db or a compressed folder or something for quick and easy extraction? Might make the whole process a bit quicker, too.

Thanks, and thanks for your invaluable work.

**Comment by BenjV** [comment]
What information are you talking about?
The only things in the data folders (besides the video's) are the  metadata of the video's, so there is nothing to cache.
And metadata caching in the database seems to me a useless idea.
Also metadata from a video file you have deleted is pointless.

**Comment by Tiwas** [comment]
Agreed to not store it in the db, but some of it would be quicker to retrieve from a local dir than the internet (if available). Maybe softlink (if that's the one where you delete the link without deleting the file) things like tvshow.nfo, seasonxx.tbn, fanart.jpg, folder.jpg and stuff like that? I agree it's not a *big* thing, but could make for a quicker post processing. But if the idea is stupid, just delete it. I'm on a 1Gb line anyway, so it's more my NAS limiting me than anything else :)

**Comment by BenjV** [comment]
Things like banner, fanart and poster are already cached in the cache folder.
Only the metadata for the serie, folder and video are in the video directories.
And if you would just delete just the video's and not the complete folder it would not be needed to retrieve again so it is your own choice.

Beside, compared to searching and retrieving video's this metadata retrieving is peanuts.

**Comment by miigotu** [comment]
Only made it to Georgia so far ;) Should be in SC tonight, but won't be set up for maybe a few weeks for much coding.
