### ISSUE TITLE
[Feature Request] Force show name in search

### ISSUE THREAD

**Issue by jbu92** [SickChill/SickChill#5573]
This may be able to be implemented in a fix for [5536](https://github.com/SickChill/SickChill/issues/5536). I would like the ability to customize/force the show name being searched. For example, a show named "Bob & Joe" is being uploaded as "Bob and Joe", currently there is no mechanism to have this show properly tracked, and I have to manually fetch new episodes.

**Comment by Wally73** [comment]
edit show -> advanced -> under Scene Exception set Bob and Joe as show ->press add and press save changes

**Comment by jbu92** [comment]
Aha. Clearly my google searches were not quite properly tailored to have that functionality come up as a solution to the issue I was having. Thank you.
