### ISSUE TITLE
Feature Request: Notes

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#5578]
Hi,

I was wondering if it were possible to add notes to a TV show

I have been manually re-checking my library and I've found a number of issues with my media that I need to sort out. These include the wide range of qualities that classify as SD - VHSrip/TVrip/WebRip. Finding TVDB entry is incorrect and need to submit an update (checking sources first, obviously). Finding files that have the wrong audio or has hardcoded subs. 

I think it would really help if I were able to add a note to a TV show so that I can come back and manage it at a later stage. It would help if it were implemented to have a notes overview in the Manage section.

This could have the potential to link to Ombi so that when someone reports an issue with your media it could be applied directly to the notes.

**Comment by miigotu** [comment]
Im not sure how Ombi works, i'll look into it, but maybe another service will work as well
