### ISSUE TITLE
Jackett integration request

### ISSUE THREAD

**Issue by TiagoDM** [SickChill/SickChill#5585]
Hi,

I was wondering if would be possible to have a jackett provider in sickchill.. I use it in couchpotato and it works really well, even with tpb (Which is always changing the addresses) and eztv and others that sickchill doesn't support (yet). 

So, in my humble opinion, would be great for maybe some people to have a way to integrate torrents with jackett. Torrents are tending to fade with the ISP blocks and it's getting harder to mantain addresses updated .. jackett does that very well, so it would help you (coders) too, I think, in a long run.

Please consider this.

Best regards,

Tiago Marques

**Comment by miigotu** [comment]
Already implemted. Add it as a custom newznab provider and it just works.
