### ISSUE TITLE
Show Updater not running automatically

### ISSUE THREAD

**Issue by rEes9P** [SickChill/SickChill#5590]
**Branch/Commit:** master/1ed315660d99f6673a3bb53363fdff6902b89429

**OS:** macOS High Sierra (10.13.6)

**Browser:** Safari

**What you did:** Noticed that all shows need to be updated manually from time to time in order to get new season and episode information. This has been the case for me for many months now.

**What happened:** The _General Configuration>Misc>Choose hour to update shows_ is set to 11. SickChill was running at 11 am today. The Server Status shows the Show Update to have last run at 13:22 (it is 13:24 as I am typing this). The Show Updater section in the logs is blank and has no information at all.

**What you expected:** For the shows to get updated automatically and this to get reflected in the Show Updater section in the logs

**Comment by miigotu** [comment]
The show updater is working, but if the series you have had not had any updates on thetvdb since the last update, they don't update anything, just a refresh.
