### ISSUE TITLE
[APP SUBMITTED]: Cloudflare captcha challenge presented for torrentz2.eu (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python.

### ISSUE THREAD

**Issue by jerkmaniac** [SickChill/SickChill#5598]
### INFO
Python Version: **2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.14.98-v7+-armv7l-with-debian-9.9**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] :: [1ed3156] Request failed: Cloudflare captcha challenge presented for torrentz2.eu (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by jerkmaniac** [comment]
### INFO
Python Version: **2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.14.98-v7+-armv7l-with-debian-9.9**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-355567 :: [Torrentz] :: [1ed3156] Request failed: Cloudflare captcha challenge presented for torrentz2.eu (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment]
A possible fix for this has been added to the develop branch. Please test and see if this solves your issue.
