### ISSUE TITLE
Move torrent providers to cookie based authentication 

### ISSUE THREAD

**Issue by WebSpider** [SickChill/SickChill#5602]
A few torrent sites are using Cloud flare to protect themselves.

This protection is sometimes triggered by installs that have many items that needs to be searched for.

Looking at other solutions, cookie based authentication seems to be a solution there. Therefore we should move the sites that are causing Cloudflare problems to cookie auth.

**Comment by miigotu** [comment]
We already do this on the providers that need it :+1:
