### ISSUE TITLE
[APP SUBMITTED]: Could not find a suitable TLS CA certificate bundle, invalid path: /volume2/@appstore/sickbeard-custom/var/SickBeard/lib/certifi/cacert.pem

### ISSUE THREAD

**Issue by janusn** [SickChill/SickChill#5603]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [TokyoToshokan] :: [1ed3156] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: /volume2/@appstore/sickbeard-custom/var/SickBeard/lib/certifi/cacert.pem (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [LimeTorrents] :: [1ed3156] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: /volume2/@appstore/sickbeard-custom/var/SickBeard/lib/certifi/cacert.pem (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: [1ed3156] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: /volume2/@appstore/sickbeard-custom/var/SickBeard/lib/certifi/cacert.pem (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrent9] :: [1ed3156] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: /volume2/@appstore/sickbeard-custom/var/SickBeard/lib/certifi/cacert.pem (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] :: [1ed3156] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: /volume2/@appstore/sickbeard-custom/var/SickBeard/lib/certifi/cacert.pem (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [SkyTorrents] :: [1ed3156] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: /volume2/@appstore/sickbeard-custom/var/SickBeard/lib/certifi/cacert.pem (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by janusn** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-72877 :: [TorrentProject] :: [1ed3156] Request failed: Could not find a suitable TLS CA certificate bundle, invalid path: /volume2/@appstore/sickbeard-custom/var/SickBeard/lib/certifi/cacert.pem (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by pro-src** [comment]
Certifi and the certificate have been updated on the develop: https://github.com/SickChill/SickChill/commit/a47992e1e2ce9177c118c62f1e12af5a8158b2a1

Give that go.
