### ISSUE TITLE
ORganizr + Auth + Sickchill

### ISSUE THREAD

**Issue by stanthewizzard** [SickChill/SickChill#5611]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 1ed315660d99f6673a3bb53363fdff6902b89429
Version: v2019.06.28-1
Database Version: 44.0
Debian

What you did:
With nginx
I have a reverse proxy with Organizr

##  Organizr auth direct
	location ~ /auth-(.*) {
		internal;
		rewrite ^/auth-(.*) /api/?v1/auth&group=$1;
	}

##  Organizr auth sub	
   location ~ ^/auth-(.*) {
    	## Has to be local ip or local DNS name
    	proxy_pass https://grabbing2.xxxxx.com:9955/api/?v1/auth&group=$1;
    	proxy_pass_request_body off;
    	proxy_set_header Content-Length "";
	}
location ^~ /sickrage {
      	include /etc/nginx/global.d/proxy.conf;	
		proxy_pass http://127.0.0.1:8081;  
	    auth_request /auth-0;
    	add_header X-Frame-Options "SAMEORIGIN";
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
    	proxy_set_header Host $host;
    	proxy_set_header X-Real-IP $remote_addr;
    	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  
   	}

What happened:
When not logged into Organizr, I'm unable to access directly sickrage
When logged into Organizr, I'm able to access directly sickrage or in iframe inside Organizr
Sickrage behave correctly

Issue:
Adding a new show leads to a nginx's error 500

Thanks for help

**Comment by WebSpider** [comment]
Make sure you set the web_root correctly in your config.

**Comment by stanthewizzard** [comment]
Yes it is
https://grabbing2.xxxxx.com:9955/sickrage 
sorry for the rage ;)

**Comment by WebSpider** [comment]
This component is new to me, I will spend some time over the coming weekend to play with it myself

**Comment by stanthewizzard** [comment]
Organizr is really an awesome portal

**Comment by stanthewizzard** [comment]
no news :(
Thanks

**Comment by WebSpider** [comment]
Sorry bud, preparations for my wedding take up all my time atm

**Comment by stanthewizzard** [comment]
Don't be
Wedding comes first ! Congrats
next step ... childrens (and then you will have no time at all believe me lol)

**Comment by WebSpider** [comment]
OK, married, let's pick this up

**Comment by stanthewizzard** [comment]
CONGRATS !!! :)

**Comment by Xenocell12** [comment]
Hey folks! I have an issue related to this on a Sickbeard fork. Curious of your results? Any updates?

**Comment by Xenocell12** [comment]
Hi @stanthewizzard 

Hope this message gets to ya!

*copied from Org Github issue*

You'll need to auth exclude URL starting at /addshows

Example below. However, this is for subfolder configuration. The key is to exclude addShows. This will also allow you to add existing.

location /medusarage/addShows { auth_request off;
proxy_pass http://192.168.1.79:5050/medusarage/addShows;
}

Being as I was concerned about security as long as you don't exclude beyond addshows it will be basically broken to outsiders as everything to make this menu work get's 401'ed to death. You will see in your console.

The reason why this doesn't work from my understanding is the Python Web Server is doing many internal redirects and with the auth block in the proxy the app doesn't behave well. This affects all "sickrage" forks.

**Comment by Xenocell12** [comment]
Oh! And side note, by design due to auth. If you try to access the /sickrage site without logging into the Org first you will get a blank page. You'll have to access it via local address to bypass nginx and reach the apps web server directly
