### ISSUE TITLE
Feature Request: Support more Indexers

### ISSUE THREAD

**Issue by LeeThompson** [SickChill/SickChill#5616]
Right now SickChill only supports thetvdb which, unfortunately, has become rather unreliable this year.   It would be nice to have some more options to use.    (I know that would also create a massive database headache especially if different indexers didn't match episode orders etc.)

**Comment by deepseth** [comment]
What other indexers are there that have the same depth of information as thetvdb, for TV shows?

**Comment by WebSpider** [comment]
Tvmaze?

**Comment by knockreff** [comment]
the sports DB (thesportsdb.com)

**Comment by downloadtheworld** [comment]
Given thetvdb.com's recent announcement that they'll be charging for API calls, could this be thought about again? I'm not going to be paying them.
