### ISSUE TITLE
start using StaticFileHandler from tornado

### ISSUE THREAD

**Issue by chrillep** [SickChill/SickChill#5623]
### Before submitting your issue:
start using StaticFileHandler instead of own built code

https://www.tornadoweb.org/en/stable/web.html?highlight=StaticFileHandler#tornado.web.StaticFileHandler

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
It already does...
