### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-DAILY-SEARCH :: [1ed3156] DelugeD: Unable to set the pause for Torrent

### ISSUE THREAD

**Issue by chrillep** [SickChill/SickChill#5624]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-328724 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-281470 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-357105 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-368298 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-340666 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-357907 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-332525 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-328577 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-332858 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-322191 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311714 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-333644 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-330997 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-271910 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-269689 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-332127 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-296295 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-284210 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@1ed315660d99f6673a3bb53363fdff6902b89429
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-289096 :: [1ed3156] DelugeD: Unable to set the pause for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chrillep** [comment]
Sickchill is generating an error even when it is adding the torrent correctly paused in DelugeD

**Comment by maxxxxpower** [comment]
I see the same error when I have deluge configured to start all torrents as paused. So it;s almost like sickchill is telling deluge to pause, but the torrent has already been paused by deluge itself.

If I turn off the deluge option to pause all new torrents, the sickchill error goes away.
