### ISSUE TITLE
Long load times

### ISSUE THREAD

**Issue by dporem** [SickChill/SickChill#5626]
Branch/Commit: Master
OS: Raspbian
Browser: Chrome
What you did: Tried to open several pages
What happened: The load of them takes a long time (when finishes). From all, the one that seems to take the longest is the schedule page
What you expected: To be much quicker
Logs: What logs do you want? info and debug level don't show nothing relevant. Warning and error debug have nothing there.

**Comment by WebSpider** [comment]
We have resolved an issue with high cpu usage last week, are you completely up to date?

**Comment by dporem** [comment]
Thanks for your reply.

I cloned sickchill yesterday. When was this commit done?

A sábado, 7/09/2019, 12:43, WebSpider <notifications@github.com> escreveu:

**Comment by dporem** [comment]
Just checked, my copy is up to date.

**Comment by WebSpider** [comment]
Please post the statistics line at the bottom of the overview page, the one including memory usage and load times

**Comment by dporem** [comment]
132 Shows (106 Active)  | 3020 +87  Snatched / 6256 Episodes Downloaded (48.2%)  | Daily Search: 0:09:29 | Backlog Search: 10:18:06
Memory used: 327.54 KB | Load time: 0.5844s | Mako: 0.2826s | Branch: master | Now: 08/09/19 11:52

But right now is going good. I think the issue only happens when sickchill is processing the results of the RSS feed (that was what I could see in the debug log yesterday when I couldn't open schedule)

**Comment by dporem** [comment]
it happened again (in a smaller case, normally takes much longer)

132 Shows (106 Active)  | 3021 +87  Snatched / 6256 Episodes Downloaded (48.2%)  | Daily Search: 0:05:07 | Backlog Search: 10:13:43
Memory used: 327.54 KB | Load time: 68.6162s | Mako: 0.2044s | Branch: master | Now: 08/09/19 11:56
