### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_1 :: [e094759] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by dporem** [SickChill/SickChill#5627]
### INFO
Python Version: **2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.2.0]**
Operating System: **Linux-4.19.66-v7+-armv7l-with-debian-10.0**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [e094759] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cbinder4** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_7 :: [e094759] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by jarble7** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [e094759] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.14 (default, Mar 03 2018, 11:05:58) [GCC 7.3.0]**
Operating System: **Linux-4.14.24-qnap-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [e094759] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mitch71h** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
DAILYSEARCHER :: [e094759] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.14 (default, Mar 03 2018, 11:05:58) [GCC 7.3.0]**
Operating System: **Linux-4.14.24-qnap-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [e094759] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by dporem** [comment]
### INFO
Python Version: **2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.2.0]**
Operating System: **Linux-4.19.66-v7+-armv7l-with-debian-10.0**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [e094759] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
