### ISSUE TITLE
can't reach github repo for sickchill

### ISSUE THREAD

**Issue by asiajason** [SickChill/SickChill#5630]
Is the get repo working anymore?

git clone https:/github.com/sickchill/sickchill
Cloning into 'sickchill'...
ssh: Could not resolve hostname https: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

but I can go to github / sickschill in a browser.....

**Comment by BenjV** [comment]
Try a double / after https:
So git clone https://github.com/SickChill/SickChill
