### ISSUE TITLE
Torrent not snatched - unable to send torrent - Add notification

### ISSUE THREAD

**Issue by rhyssman** [SickChill/SickChill#5632]
Branch/Commit: master/1ed315660d99f6673a3bb53363fdff6902b89429
OS: Docker
Browser: Chrome
What you did: Deluge updated to new version resulting in authentication issue for Sickchill
What happened: Torrents not snatched as unable to send via Deluge Daemon
What you expected: Only logged as warning. Suggest this should be loggged at a higher level. Feature request to push failed to send error to notification agents to user. Possibly other critical errors restricting Sickchill from searching/sending
Logs:
```
Warning
2019-09-15 16:15:47 SEARCHQUEUE-DAILY-SEARCH :: DelugeD: Unable to send Torrent
```
To rectifiy the authentication issues I switched to send torrents via Deluge WebUI to fix sending issue. Authentication not Sickchill issue.

What confused me was torrents were not snatching so I thought I had a search provider issue not a sending issue.

**Comment by miigotu** [comment]
warnings are for the end user (you), errors are for us. I'm not ok with making this spam the issue tracker every time a torrent fails to send to a person's client.
