### ISSUE TITLE
Image Caches Never Update

### ISSUE THREAD

**Issue by Torhal** [SickChill/SickChill#5636]
Every so often, fanart for "boxes" and banners is updated, which I frequently see reflected in my Plex server. For SickChill, however, I had years-old artwork until I manually deleted the cached images and allowed SickChill to re-populate them. This can be very disconcerting since, in many cases, the artwork depicts scenes/story-arcs which are several years old unless you manually purge.

Branch/Commit: master
OS: macOS Mojave (version 10.14.6)
Browser: N/A
What you did: Manually deleted cache folder.
What happened: Images re-populated with updates.
What you expected: Automatic image refershes.
Logs: N/A

**Comment by miigotu** [comment]
The way we currently do this, is if we have an image of a specific type, we dont update it. With thousands of users with hundreds of shows, and hundreds of images per series, it would not be a good idea to automatically update everyone's images and practically bring down the indexers, let alone cost them all that bandwidth.

**Comment by Torhal** [comment]
@miigotu  Oh, dear no - I didn't mean on every update. A timed interval, say 90 days, to mark images as stale after being set on a per-show basis. This is similar to what Plex does from my observations, and would prevent mass spam updates via the API.
