### ISSUE TITLE
No info found for show in Thetvdb

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#5644]
Wanted to add "Watchmen", but it's not found by sickchill. All I get is the following in the logs

> AA **19-10-03 08:21:50 DEBUG ThreadPoolExecutor-0_2 :: Searching for Show with searchterm(s): ['watchmen'] on Indexer: theTVDB

The only show found is "Watchmen: The Motion Comic" from 2008.

Watchmen is found on thetvdb and has episode information, as far as I can see. https://www.thetvdb.com/series/watchmen

**Comment by Tiwas** [comment]
Ok, so I found a non-ideal way of adding the show, but also verifying that it is in fact a bug - I added it from a trakt list, which worked like a charm.

**Comment by oxivanisher** [comment]
The same here. Also others have reported the same issue #5646

**Comment by Tiwas** [comment]
@oxivanisher Is there a way for me to merge these?

**Comment by oxivanisher** [comment]
@Tiwas AFAIK not, but since I mentioned the other issue, they are already linked. You can probably just close yours, the history will show that they are linked.

**Comment by Tiwas** [comment]
Closed. Duplicate.
