### ISSUE TITLE
Unable to Find Show - No Results

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#5646]
Branch: master
Commit: e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Version: v2019.06.28-1
Database Version: 44.0

OS: Win 10
Browser: Firefox
What you did: Searched for a show
What happened: Show was not returned in the results
What you expected: To locate the show in the results

I frequently have issues with SickChill where a show that can be located in TheTVDB.com and does come up with air dates cannot be added to the TV show list. This happens regularly but sometimes if I misspell the name or partially enter it I can work around the problem but today I was unable to locate Watchmen. I tried searching using Watchmen, Watchman, Watchmen 2019, The Watchmen, Watch Men, tt7049682, 360733 and the only result I can find is Watchmen: The Motion Comic. Each of these searches were run with all indexers selected.
 I worked around the problem by adding the show using Add From IMDB's Popular Shows but I would really expect to be able to locate the show when searching by using the correct name.

**Comment by ogg1e** [comment]
I'm seeing the same issue as well for watchmen

**Comment by rutskiuk** [comment]
I had a go at recreating my SickChill database on another machine and found a few shows that could not be identified (the correct show was not listed among the results) but could be after minor changes to the naming:

Mork and Mindy - No results
Mork & Mindy - Located
Life of Birds - The Secret Life of Birds / Iolo's Secret Life of Birds (neither the correct show)
The Life of Birds - Located
Stephen King's The Stand (1994) - No Results
The Stand (1994) - Located
Stephen King's The Shining (1997) - No Results
The Shining (1997) - Located
Ronia the Robber's Daughter - No results
Ronja the Robber's Daughter - Located
World War 1 In Colour - No Results
World War I In Colour - Located
World War 2 The Complete History - No Results 
WWII The Complete History - Located
Sarah Silverman - Sarah Silverman / I Love You, America (neither the correct show)
The Sarah Silverman Program - Located
Dr Snuggles - No Results
Doctor Snuggles - Located
Clive Barker's A - Z Of Horror - No Results
Clive Barker's A-Z Of Horror - Located
The Sarah Jane Smith Adventures - No results
The Sarah Jane Adventures - Located
Not The 9 O'Clock News - No Results
Not The Nine O'Clock News - Located

I am still left with a few shows that are not found by SickChill even though the spelling of the name matches TheTVDB:

Broken (2017) - can locate it by adding 2017 into the name again
**Cracker - no results, not even Cracker (US)**
Legend of the Dragon Kings (1994) - can locate it by just using Dragon Kings
The Fear (2015) - can locate it by adding 2015 into the name again

Interestingly, I am now able to add Watchmen however I am still having problems adding correctly named TV shows or getting results for shows very closely matching TheTVDB and indeed searchable in TheTVDB.

**Comment by rutskiuk** [comment]
In addition:

Dynasties - One result: Dynasties
Dynasties 2018 - located

**Comment by rutskiuk** [comment]
Just updating this one after a prompt from a competitor that they cannot replicate this issue on their platform. I'm glad to say most of these shows can now be found with the exception of:

Dr Snuggles (because the show is called Doctor Snuggles)
Not The 9 O'Clock News (this one should still come up in the results as it is the spelling of the show although is found with Nine rather than 9)
Stephen King's The Stand (1994) (because the show is called The Stand)
The Sarah Jane Smith Adventures (because the show is called The Sarah Jane Adventures)
World War 2 The Complete History (this one should still come up in the results as World War II The Complete History is listed in TheTVDB.com)

All in all it seems to be largely sorted but there are a couple I think should still come up in the results.

**Comment by miigotu** [comment]
@rutskiuk that was mostly due to the old api, which is no longer being used in develop. I have completely changed over to api v2/3 for tvdb

**Comment by rutskiuk** [comment]
Oh right, I just did a search for devs and couldn't find that but a search for dev allowed me to pick it from the list. So am I just waiting for the API to be rolled out to the master now?

**Comment by rutskiuk** [comment]
Great, now able to add shows first time round.

Since updating completely downloaded shows are now in my shows list as 0/0 downloaded
Just not been running it long but I'm already seeing this with 8 shows... 9 shows..

I thought SC had started failing to get the airdate info from TVDB, I checked one show where I only have a few episodes and the only episodes listed now are the ones I downloaded, forcing a full update fixes the problem fortunately.
