### ISSUE TITLE
REQ: Set show as "full season only"

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#5647]
The other day I was thinking how some shows are much better when binged and that I regularly save up episodes for this purpose. Would it be possible to set a switch so that the show only registers as wanted when the last episode has aired?

**Comment by Tiwas** [comment]
Any interest in this?

**Comment by miigotu** [comment]
I think this is not a great idea, because by the time the last episode hits the early episodes will not have many seeds. Maybe just don't watch them until the season is ending?

**Comment by chris41g** [comment]
couldnt you just set that show to only download season packs and achieve similar results?
