### ISSUE TITLE
Episodes Downloading Without Detecting Quality (Quality N/A)

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#5649]
Branch: master
Commit: e094759
Version: v2019.06.28-1
Database Version: 44.0

OS: Win 10
Browser: Firefox
What you did: Downloaded an episode
What happened: Postprocessed into the correct show on the correct episode and says downloaded but the status field indicating the quality is blank
What you expected: To show Downloaded [unknown/720p HDTV/SDTV/720p BluRay/1080p]

When I look at my history I can see the quality is listed as not applicable.
I can see the quality in the file name and if I open the file the resolution is 1280x720

Episode in the show
![image](https://user-images.githubusercontent.com/25068977/66434757-2064bc00-ea1b-11e9-951a-461e2e06571f.png)

Episode in the history
![image](https://user-images.githubusercontent.com/25068977/66434788-307c9b80-ea1b-11e9-85f7-7b442ac9fe7c.png)

Episode in VLC
![image](https://user-images.githubusercontent.com/25068977/66434971-a5e86c00-ea1b-11e9-82ca-c1971bd8a59b.png)

The outcome of this is an episode without a profile so I cannot filter by it in episode status management and have to manually trawl through recent downloads applying a quality profile to them.

**Comment by BenjV** [comment]
Analyzing of video's is done via the information in the filename.
Your filename does not contain any such information.
It only states the seriename, the season and episode information and the title.
So no resolution codec, releasegroup etc. is available.

**Comment by rutskiuk** [comment]
The file in the screenshot is postprocessed, the original file showed like this:

![image](https://user-images.githubusercontent.com/25068977/66588633-d1d33100-eb84-11e9-9daf-ca5cd60ed6b3.png)

The original filename (more accurately, the folder the file was enclosed in) does include the quality and the release group but the point I am trying to make is that the quality is being listed as n/a rather than unknown/sd/720p etc. If the file quality cannot be determined I would expect the quality to be listed as unknown rather than n/a. Listing without a quality rather than saying unknown stops me from filtering episodes by downloaded (unknown) to manage them manually and adding correctly downloaded episodes to a backlog.

**Comment by BenjV** [comment]
The folder name is not processed only the filename.
So if you have an obfuscated folder then the filename will have no information to process.

**Comment by rutskiuk** [comment]
That's not my experience with other downloads: 

![image](https://user-images.githubusercontent.com/25068977/66597723-79f1f580-eb97-11e9-853b-99189febe094.png)

![image](https://user-images.githubusercontent.com/25068977/66597763-89713e80-eb97-11e9-8903-1bd9766b3ce0.png)

![image](https://user-images.githubusercontent.com/25068977/66597807-9aba4b00-eb97-11e9-8db4-fb80a165e0ab.png)

Even if that is the case the file should not be identified as n/a, it should be at least processed as unknown.

**Comment by Tiwas** [comment]
This is similar to my problems, also. Seems to be the x265 as x264 will be correctly displayed given the same filename.

![image](https://user-images.githubusercontent.com/17053402/67840165-83ff7800-faf5-11e9-8e50-5d07535c2091.png)

I've mentioned the same in #5648 and #5650

**Comment by Tiwas** [comment]
For debug log, see #5650

**Comment by rutskiuk** [comment]
Is there any chance of an update on this one? 

I understand the point about file quality being detected by file name (or folder name for obfuscated downloads) and if the file only says 720p/1080p rather than 720p/1080pHDTV/WebRip/BluRay it cannot be determined automatically. 
I'm fine with that. The problem I have is that these files are just marked as quality n/a rather than unknown. This stops users from filtering shows in Episode Status Management. I know this problem is caused by the release group, however I only started having this problem with not being able to manage the episodes recently.

Please can SickChill either identify these as unknown or 720p/1080p HDTV (presumably the lowest quality 720p/1080p variant)?

**Comment by miigotu** [comment]
If you just enable hevc support in the settings they aren't Unknown quality. It's like this because most people still don't want hevc files.

**Comment by rutskiuk** [comment]
Thank you for the update

I'm not sure why this is closed. A file should never have no quality associated with it, even with hevc support not selected the quality should never be blank. If the quality is left blank users have to go through all shows manually to select each episode that has downloaded and assign them manually, they should at least be able to do this through episode status management but leaving the quality blank stops this from working breaks that process.
I've been able to find hevc support and selected it so hopefully things will start working but without it selected SC should still not leave the quality as blank, at the very least set as unknown.

**Comment by miigotu** [comment]
It's closed because it isn't a bug. There are only so many qualities we can assign without completely reworking how qualities work in SC. It's set to Quality.NONE on purpose, because hevc could be accidentally accepted if someone allows ANY quality when they aren't expecting that to even be a possibility.

**Comment by rutskiuk** [comment]
I totally see why you wouldn't want to multiply the number of quality profiles, I'd never think that would be a good idea. I guess if I had a system that didn't work with hevc files I would add hevc and x265 to the ignore words list.
I still consider episode status management broken while SC prevents a portion of the episodes from being managed. Yes, people can manage episodes individually but you could be talking about a collection with thousands of episodes and that isn't feasible. Also, who is going to intuitively know to go to Settings > Search Settings > Allow downloading HEVC x265 releases to work around the problem? Most people would just look at the behaviour and consider it broken.
Sorry if it seems like I'm causing hassle, I don't mean to.

**Comment by miigotu** [comment]
If they didn't have hevc enabled in the first place then SC wouldn't download them, and they wouldn't be set as None. Trying to process files that SC didn't download is probably how this happened. It isn't going to change, and it isn't about multiplying qualities. There's no space left in the width of a uint_32t to fit more qualities, so we literally can't add any more.

**Comment by rutskiuk** [comment]
Forgot to say thank you. SC is working perfectly now I have that option switched on.
