### ISSUE TITLE
Not post processing after updating to mac os catalina

### ISSUE THREAD

**Issue by moexpa** [SickChill/SickChill#5652]
After updating mac os to mac os catalina, sickchill no longer moves watched folder videos to their correct folder on my qnap nas

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by tastycorn** [comment]
Same here.

**Comment by tastycorn** [comment]
I got this sorted.
I ended up adding Python to the Full Disk Access group:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/23389178/66654823-44c9bf80-ebf8-11e9-9524-37fec9ceb552.png">

My Python executable was at:
/Library/Frameworks/Python.framework/Versions/2.7/Python

Then when starting SickChill, run it as sudo. For me this was:
`sudo python /Applications/SickChill/SickBeard.py`

I start SickChill with an Apple Script, so if you do the same, you will need to add sudo to that.

**Comment by lookatitude** [comment]
I have the exact same problem tried to add python like @tastycorn mentioned but still get the same error:
`2019-10-12 03:05:31 ThreadPoolExecutor-0_3 :: Unable to open /Volumes/Downloads: OSError(1, 'Operation not permitted') / [Errno 1] Operation not permitted: '/Volumes/Downloads'`

I may have a difference the /Volumes directly is where I mount my NAS folders on to.
I've also added Python3 to the full Disk Access apps but still the same error.

**Comment by rr0ss0rr** [comment]
Also having this issue .. I'm not getting an error about needing full disk access .. actually, not getting any errors at all.  Also, there should be no need to run SickChill through sudo.  I also opened a problem with NZBtoMedia.

**Comment by tastycorn** [comment]
I wasn’t getting any errors. It just wasn’t working and doing this (including sudo) fixed it for me.

**Comment by rr0ss0rr** [comment]
Thanks .. but running SickChill under sudo opens too many security exposures for my liking.

**Comment by rr0ss0rr** [comment]
ok .. I thought this was a NZBGet issue (in part it was) since it's only happening on NZB prost processing and working fine on Torrent Post Processing (Both are using NZBtoMedia for post processing), but now I'm seeing the following on SickChill but only on files that were obtained through a NZB file.  files downloaded via torrents use the same directories and files via NZB (Which is the real confusing part of this)

2019-10-23 10:30:26 ThreadPoolExecutor-0_2 :: Unable to open /Users/richard/Downloads: OSError(1, 'Operation not permitted') / [Errno 1] Operation not permitted: '/Users/richard/Downloads'

I gave python full disk access

**Comment by rr0ss0rr** [comment]
@tastycorn , Are using NZBGet for the downloader?  The thing is, SickChill works fine when a Torrent is used (downloaded by Transmission), but SickChill Fails on the NZBGet files unless SickChill is run under sudo.  So, Is this a permissions issue with NZBGet?  Both NZBGet and Transmission requested and authorized to access the "Downloads"  folder via SysPrefs->Security&Privacy, so I'm thinking this is not a SickChill issue, but NZBGet and the new Catalina Folder Access lockdown (I don't even know how to test for this new lockdown).  What do you guys think?

**Comment by tastycorn** [comment]
I am using SABnzbd as my downloader. I did not have to do anything with the permissions for SABnzbd.

**Comment by rr0ss0rr** [comment]
Thanks .. I switched over to SABnzbd today.  Fingers crossed.

**Comment by rr0ss0rr** [comment]
OK .. With SABnzbd, nzbToMedia and SickChill did not require sudo and had no problems with permissions.  Thanks

**Comment by rr0ss0rr** [comment]
Just a follow up, I removed Full Disk Access for Python2.7 (SickChill) and everything still works fine

**Comment by XxUnkn0wnxX** [comment]
doesnt work for me cannot even do full disk access python completely
![Screen Shot 2019-11-03 at 8 16 58 am](https://user-images.githubusercontent.com/2242880/68077121-6d696180-fe12-11e9-8592-d7ec10e0a287.jpg)
 greyed out for me.

everytime one of my scripts go off i have to manually approve gatekeeper when it pops up for me when it wants disk access 

i'm on macOS Catalina 10.15.1

**Comment by rr0ss0rr** [comment]
Mac 10.15 already has python 2.7 installed.
/usr/bin/python links to the following:
/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7

**Comment by XxUnkn0wnxX** [comment]
the one found in /System/Library/Frameworks is the one installed by the user using the package installer

as for the one i have installed i have custom python modules i use for other applets that require it.

i also have /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 but that one is greyed out as well.

i noticed that python doesnt have the 
![Screen Shot 2019-11-03 at 12 05 01 pm](https://user-images.githubusercontent.com/2242880/68078805-3a36ca80-fe32-11e9-9d61-201e1fbd2bb3.jpg)
tag. thats why it wont let me select it.
