### ISSUE TITLE
[APP SUBMITTED]: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/316059/en.xml

### ISSUE THREAD

**Issue by janusn** [SickChill/SickChill#5657]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /volume2/Media/shared/TV Shows/The Watchman on theTVDB using ID 316059, not using the NFO. Delete .nfo and try adding manually again.: HTTP error None while loading URL http://thetvdb.com/api/F9C450E78D99172E/series/316059/en.xml
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by gadgetusaf** [comment]
Seeing a similar issue here as well

**Comment by rehova** [comment]
ditto, exact same issue here, I've been unable to add shows for a few days now

**Comment by relay7565** [comment]
I'm seeing the same thing.  Here is a log excerpt:

AA tvdb_error: "There is no item named 'en.xml' in the archive"
AA raise tvdb_error(e)
AA File "/app/sickchill/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
AA epsEt = self._getetsrc(url, language=language)
AA File "/app/sickchill/lib/tvdb_api/tvdb_api.py", line 874, in _getShowData
AA self._getShowData(key, self.config['language'], True)
AA File "/app/sickchill/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
AA s = t[self.indexer_id]
AA File "/app/sickchill/sickbeard/show_queue.py", line 324, in run
AA Traceback (most recent call last):
2019-11-18 21:07:38 ERROR SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /tv/TVShows/The Mandalorian on theTVDB using ID 361753, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.xml' in the archive"

**Comment by Mysteres** [comment]
Same problem

**Comment by miigotu** [comment]
#5789 fixes, is in develop branch. Will be on master after more testing.
