### ISSUE TITLE
Incompatibility of generated nfo files with new Kodi 18 unique IDs

### ISSUE THREAD

**Issue by modem** [SickChill/SickChill#5660]
Kodi 18 has introduced unique IDs in NFO files.
Some plugins such as trakt.tv fails to syncronize kodi library with trakt.tv collection, including watched status.
https://kodi.wiki/view/NFO_files/Movies
https://kodi.wiki/view/NFO_files/TV_shows

This makes the generated NFO files incompatible with some plugins like the trakt.tv plugin.

I'm currently relying on MediaElch (https://github.com/Komet/MediaElch) to create the NFO files with the uniqueid tags.

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: all
Browser: all
What you did: added a new TV Show
What happened: the generated NFO file does not have the uniqueid introduced by Kodi in the v18 version
What you expected: the generated NFO file to have the uniqueid
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Fixed in develop
