### ISSUE TITLE
REQ: Information in notifications

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#5669]
Would it be possible to select more information for notifications? I have some public and some private trackers. I would love to know which tracker a show was downloaded from. I'm sure other people would like to get more information, too - like size, codec etc.

**Comment by WebSpider** [comment]
What is shown in notifications greatly depends on the exact notifier. Which notifier do you use?

**Comment by Tiwas** [comment]
@WebSpider Mostly email, but having the option to send whatever information you think is relevant would be cool no matter which notifier people use.

**Comment by procdaddy11** [comment]
Bump. I’ve seen this integration in Medusa. In no way do I recommend switching projects, but it would be a welcome enhancement.
