### ISSUE TITLE
Feature Request: Set Indexer Data Cache Age

### ISSUE THREAD

**Issue by LeeThompson** [SickChill/SickChill#5670]
It would be nice for certain situations to be able to control the maximum indexer data cache age.

`2019-10-30 20:54:24 DEBUG    SEARCHQUEUE-MANUAL-267951 :: [INDEXER] :: Last update was too soon, using old cache: 2019-10-30 20:47:34. Updated less then 30 minutes ago
`
Perhaps even have a 'clear cache' button/option on each indexer's configuration page to force a new search or perhaps clear incorrect data.

**Comment by papampi** [comment]
+1

**Comment by miigotu** [comment]
These cannot be lowered. We have meticulously went through and made them as low as possible while still not angering providers by spamming their sites with requests. This cache is only for rss/daily updates, not actual searches.

**Comment by LeeThompson** [comment]
That's not how it works in practice, just FYI. It blocks manual searches as well.

**Comment by miigotu** [comment]
@LeeThompson no, it doesn't. When you manual search it hits the rss/daily first, invade it's found without doing an actual search. Then it's followed with an actual string search which does not have a cache.

**Comment by LeeThompson** [comment]
Not going to argue with you, but you should check it.  I don't think it works like you think it does.

**Comment by miigotu** [comment]
I know exactly how it works. I wrote the code. It updates the cache (and gives a cache log if it's too soon) and then continues with the string search. Enable debug logging and check back.
