### ISSUE TITLE
Feature Request:  Plex Token retriever.

### ISSUE THREAD

**Issue by kcwebby** [SickChill/SickChill#5673]
Would really like to see a method to login via plex and grab an application auth token.

Retrieving manually now is only effective temporarilly.
I would rather not have SickChill login via username / password, but instead a token.

See this post for details on the changes:
https://forums.plex.tv/t/how-to-request-a-x-plex-token-token-for-your-app/84551

**Comment by miigotu** [comment]
It does use token based auth, through OAUTH.

**Comment by kcwebby** [comment]
Sorry I left out some info -- I'd like to see it be able to auto-complete the auth token under the notifications. 
I'm also not aware of OAUTH usage for sickchill, but I'll look into that further, I'm assuming that's for user login?
snip of where I was referring,  
![image](https://user-images.githubusercontent.com/10803458/68127403-71ad8180-fedb-11e9-8c27-933caf25186a.png)

**Comment by miigotu** [comment]
Going to be redoing the plex notifiers soon, and adding the ability to click play for a file right from displayshow and select which destination ^

**Comment by miigotu** [comment]
@kcwebby you do know you only need to put the username and password right? Token is only for if you don't have a free plex account

**Comment by kcwebby** [comment]
I'm not sure why this mention didn't hit my mailbox, but yes, I know I only need user/pass.  I have PlexPass, which requires the Token, correct?

**Comment by miigotu** [comment]
@kcwebby no, token is only required to use a local server when you have no plex account at all (PlexPass or Plex Free). Username and password is enough.
