### ISSUE TITLE
Episodes showing as "Unaired" long after air date.

### ISSUE THREAD

**Issue by Behanji** [SickChill/SickChill#5675]
Branch/Commit: Latest?
OS: Linux
Browser: Chrome
What you did: Checked for latest episodes downloaded
What happened: Episodes from yesterday were showing as Unaired despite being past the date and the time on my machine was correct.
What you expected: I expected the latest episodes to be downloaded overnight as I am in the EU.
Logs: There was nothing in the logs for me regarding this. I cleared them last night and there were no new entries for me?

Apologies for the lack of information, I am new to SickChill. I am wondering if people have encountered this before, and if there is any way to fix it?

**Comment by miigotu** [comment]
What show? Daily search needs to be enabled to update statuses.

**Comment by Behanji** [comment]
@miigotu it's all shows that I have added. I thought Daily Search was enabled by default? It certainly was on SickRage and Medusa. How do I enable it?

**Comment by miigotu** [comment]
If it's all shows you need to check your logs for errors contacting tvdb. Just have at least one provider enabled for daily search.

**Comment by Behanji** [comment]
No errors relating to TvDB at the moment. There are 3 errors right now:

2019-11-08 09:30:06 ThreadPoolExecutor-0_1 :: [e094759] Missing time zone for network: Peacock. Check valid network is set in indexer (theTVDB) before filing issue.
2019-11-08 09:27:09 ThreadPoolExecutor-0_0 :: [e094759] Missing time zone for network: Apple TV+. Check valid network is set in indexer (theTVDB) before filing issue.
2019-11-08 09:27:09 ThreadPoolExecutor-0_0 :: [e094759] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.

I have been able to get the status to change to Wanted by doing "Force Full Update"  on the individual show. 

Is there a way to do a "Force Full Update" operation on all shows at once? Or a way to make it automatically do it?

**Comment by miigotu** [comment]
#5789 fixes, is in develop branch. Will be on master after more testing.
