### ISSUE TITLE
Multi Episode Naming Problems

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#5677]
I have noticed with my latest SickChill install that multi episode files that were identified previously are no longer being recognised.

Branch: master
Commit: e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Database Version: 44.0
Browser: Firefox
What you did: Added a show with multiple episodes
What happened: Files were not identified
What you expected: Files to be identified (they were previously)
Logs:
```
PASTE LOGS HERE
```
2019-11-06 21:09:37 INFO     SHOWQUEUE-REFRESH :: 73871: No episode number found in /tv/Futurama/Season 02/Futurama - S02E04E08 - Fry & The Slurm Factory & Xmas Story.avi, ignoring it

Proof that this naming structure worked previously:
![image](https://user-images.githubusercontent.com/25068977/68338811-34174700-00db-11ea-9a0c-7cb34f62fa0e.png)

![image](https://user-images.githubusercontent.com/25068977/68338844-42fdf980-00db-11ea-922d-11302c54f921.png)

Has something changed?

**Comment by miigotu** [comment]
Nothing has changed in like a year related to naming or parsing. Maybe it was matched before it was renamed.

**Comment by rutskiuk** [comment]
I'm puzzled then, I installed SickChill on a mini PC in January and it identified these files/episodes without any difficulty at the time:

![image](https://user-images.githubusercontent.com/25068977/68414843-df320a00-0188-11ea-9395-90d03b011342.png)

![image](https://user-images.githubusercontent.com/25068977/68414890-f5d86100-0188-11ea-8909-2b0908d3aa10.png)
(screenshots of the same file on the mini PC)

The files are the same and were on the same raid array I am currently using so SickChill did identify them after their initial naming.

**Comment by rutskiuk** [comment]
Is there anything that can be done about non-contiguous episode identification?

**Comment by miigotu** [comment]
I think if it's named S02E04.S02E10 it might work, but it's not a normal scenario. Usually releases are episode 4-10, not episode 4 and 10 only, because that makes no sense.
