### ISSUE TITLE
Update notification | Not shown anymore 

### ISSUE THREAD

**Issue by marflao** [SickChill/SickChill#5679]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/e094759640ca61c5c033bf1ff9d33bc7fc1ba857
OS: Linux-2.6.32.12-armv5tel-with-glibc2.4
Browser: Chrome Version 78.0.3904.87 (Offizieller Build) (64-Bit)

What you did: Looking for possible available Sickchill updates
What happened: I don't recall when this "issue" has occured for the first time but currently I don't see any "available" update notification whenever I start the sickchill GUI. 
In addtion to that when I click on "Check for new updates" I'll be redirected directly to /home screen (the overview with all the shows). 
What you expected: to see if available updates are available

Just curious if this is a normal behaviour or if there is some issue in my settings?!
Thanks in advance.

**Comment by WebSpider** [comment]
Update checks are ran periodically, so not instantly. Your SC may simply not have checked for updates yet.

**Comment by marflao** [comment]
Thanks for getting back to me, WebSpider.

Hmm...what shall I expect "to see" in case I would click on "Check For Updates" in the SC GUI?

Cheers,
marflao

**Comment by miigotu** [comment]
It just shows up with a pink box at the top of the home page telling you there is an update. If you disable auto update checks it won't do it on it's own
