### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG-348851 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents

### ISSUE THREAD

**Issue by ahyear** [SickChill/SickChill#5683]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-348851 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-325303 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-341663 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-323168 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-73762 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-266967 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-281621 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311711 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295777 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-321239 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-321285 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311714 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-284190 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-279121 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-330525 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295648 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-349317 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-295647 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-320724 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-311954 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-289855 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-328724 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-247808 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-95011 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-264586 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-328577 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-114801 :: [ilCorsaroNero] :: [e094759] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
This site is down, returning a 500 error
