### ISSUE TITLE
Please add rarbgmirror.org

### ISSUE THREAD

**Issue by rd1** [SickChill/SickChill#5685]
Thanks a lot :)

**Comment by papampi** [comment]
Why mirror when main is working properly?
There are too many mirrors to have them all. 
rarbgaccess.org, rarbgmirror.org, rarbg.to, rarbgto.org, rarbgunblock.com, rarbgproxy.org, rarbg.is, rarbgprx.org, ....

**Comment by miigotu** [comment]
What about the api authentication? does that work on a mirror?

**Comment by miigotu** [comment]
I changed it from rarbg.com to rarbg.to, hopefully that fixes the issue?
