### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_14 :: [5aad224] Missing time zone for network: Apple TV+. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by Snowaks** [SickChill/SickChill#5688]
### INFO
Python Version: **2.7.16 (default, Jul  6 2019, 11:29:19) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)]**
Operating System: **FreeBSD-11.2-STABLE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@5aad224493c6eacbbc6b59793a55994915331032
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_14 :: [5aad224] Missing time zone for network: Apple TV+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by steveschow** [comment]
The new "Disney+" streaming channel is also missing

**Comment by steveschow** [comment]
AppleTV+ is on thetvdb:  https://www.themoviedb.org/network/2552-apple-tv?language=en-US

Disney+ is on thetvdb:  https://www.themoviedb.org/network/2739?language=en-US

**Comment by Snowaks** [comment]
This could also be a TVDB Problem.

**Comment by mmhere** [comment]
I submitted a pull request for this [here](https://github.com/SickChill/sickchill.github.io/pull/22) two weeks ago but it hasn't been picked up.  Same needs done for Disney+

**Comment by oookamiii** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-0.bpo.6-amd64-x86_64-with**
Locale: None
Branch: **develop**
Commit: SickChill/SickChill@5aad224493c6eacbbc6b59793a55994915331032
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [5aad224] Missing time zone for network: Apple TV+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mmhere** [comment]
The `Apple TV+` item has been added so this could be resolved.  `Disney+` still needs added.

**Comment by WebSpider** [comment]
Someone provided a pull request for Apple TV+, that speeds things up =)

Closing this as this issue is solved.
