### ISSUE TITLE
Can't auto-update Sickchill on QNAP NAS. Manual update works.

### ISSUE THREAD

**Issue by baronebirra82** [SickChill/SickChill#5697]
Branch/Commit:  e094759
OS: Win 10 / QNAP 4.3.3
Browser: Chrome
What you did: I manually updated sickchill via Putty console. Also disabled certificate check.
What happened: Update worked, but i still get this error when it tries it auto-checks for new updates: _git fetch origin --prune returned : (128) fatal: unable to access 'https://github.com/sickchill/sickchill.git/': error setting certificate verify locations: cafile: /etc/ssl/certs/ca-certificates.crt_

**Comment by miigotu** [comment]
This is a configuration issue on your nas, not SC related.
Either fix the cert location:
https://github.com/scalingexcellence/scrapybook/issues/36#issuecomment-528681936
Or disable ssl verification globally either with a git config command or a systemwide environment variable.

**Comment by miigotu** [comment]
Idk what that means, this has nothing to do with python. It calls the git installed on the system.
