### ISSUE TITLE
Way to prefer Multi/Dual Audio

### ISSUE THREAD

**Issue by Extarys** [SickChill/SickChill#5700]
I'm looking for a way to prefer dual audio (English/French) downloads. The main reason is that I watch everything in english, but most of my friends and family prefer French.

Right now I get the file in the two languages, extract the audio of one and merge it with the other. Which takes a lot of time, manual work and more disk space.

I'm not sure if there is a way to do this simpler or something. I thought I would post this here. Please feel free to redirect me if it was inappropriate.

**Comment by mmhere** [comment]
It would also be nice to be able to specify audio encoding.  Some releases are stereo while others are marked DDP5.1, and come along later.  It'd be nice to be able to set the latter as a preference.

**Comment by Extarys** [comment]
I didn't even think of that. Good idea.

I appreciate uploaders, but it's a shame many of them do not specify some details or are too vague in the title/description and make it a trial and error thing which turns out to be time consuming.
