### ISSUE TITLE
Unable to write file to D:\TV\Show Name Here\series.xml - are you sure the folder is writable? error 13 : Permission denied

### ISSUE THREAD

**Issue by cadmuslabslex** [SickChill/SickChill#5702]
I am getting this on every show. I can write to the folder with no issue. The folder has EVERYONE for security permissions. Is there some other user / name I need to add for the program to be able to write the .xml file to the folder?

**Comment by WebSpider** [comment]
Please provide more information about the version you are running, the OS you are running it on, etc.

**Comment by cadmuslabslex** [comment]
Version: v2019.06.28-1
Database Version: 44.0

  Python Version:
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]

  SSL Version:
OpenSSL 1.0.2j 26 Sep 2016

  OS:
Windows-7-6.1.7601-SP1

  Locale:
en_US.cp1252

**Comment by cadmuslabslex** [comment]
> 
> 
> Please provide more information about the version you are running, the OS you are running it on, etc.

The thing that doesnt make any sense at all is that it downloads the banner.jpg and folder.jpg to the same directory with no problem only the .xml is failing to write.

**Comment by miigotu** [comment]
Check permission on D:\TV (and then fix it on the show for also)
