### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_1 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by psa99** [SickChill/SickChill#5706]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by adelatour11** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by lofteddwarf** [comment]
I have the same issue. Not found a way to fix it.

**Comment by adelatour11** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by maxfield07** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_7 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by maxfield07** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_5 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by maxfield07** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by maxfield07** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by daleadae** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:46:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sho0ok** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 15:28:11) [GCC 4.9.4 20150629 (prerelease)]**
Operating System: **Linux-4.4.59+-aarch64-with-glibc2.17**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sho0ok** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 15:28:11) [GCC 4.9.4 20150629 (prerelease)]**
Operating System: **Linux-4.4.59+-aarch64-with-glibc2.17**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sho0ok** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 15:28:11) [GCC 4.9.4 20150629 (prerelease)]**
Operating System: **Linux-4.4.59+-aarch64-with-glibc2.17**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [e094759] git checkout -f develop returned : error: pathspec 'develop' did not match any file(s) known to git.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
