### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_0 :: [e9a82d9] Unable to create the folder \\ds1817-01\tv\The Science of Star Wars, can't add the show

### ISSUE THREAD

**Issue by knapekt** [SickChill/SickChill#5707]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **develop**
Commit: SickChill/SickChill@e9a82d932c30f9614bc4658fba03a745afc705ef
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [e9a82d9] Unable to create the folder \\ds1817-01\tv\The Science of Star Wars, can't add the show
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by didyouexpectthat** [comment]
This looks like a permission issue.

**Comment by knapekt** [comment]
You’re right – I guess windows updated and blew out an account or some permissions.  Sorry to bother you.

Todd Knapek
858.822.8451
todd@toddknapek.com<mailto:todd@toddknapek.com>
