### ISSUE TITLE
Can't add any new shows

### ISSUE THREAD

**Issue by lmao32895** [SickChill/SickChill#5711]
2019-11-19 22:54:18 SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /home/iadmin/DRIVE/Who Are You School 2015 on theTVDB using ID 294815, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.xml' in the archive"

never had a problem till 3 days ago. now i cant add anything

**Comment by LeeThompson** [comment]
Read #5686 for reasons and workarounds.

**Comment by mmhere** [comment]
[#5686](https://github.com/SickChill/SickChill/issues/5686) is really long, too(*), so you might want to search for "TL;DR version A" in there, or use the `develop` branch that has a temporary fix.

(*) partially my fault!

**Comment by lmao32895** [comment]
thank you both! i was able to add my new shows and then set it back to master for now

**Comment by QuentinJ54** [comment]
Hello,

I can not use the develop branch.
he says to me:
"The update failed
The update was not applied, there was no reboot. Check your event log for more information.

error code:
[e094759] git checkout -f develop returned: error: pathspec 'develop' did not match any file (s) known to git.

Can you help me?

Thank you

**Comment by mikektyler** [comment]
Just wondering whats the timeline for a final fix/update?
Thanks so much.
