### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_5 :: [e9a82d9] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by the-davidtran** [SickChill/SickChill#5714]
### INFO
Python Version: **2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]**
Operating System: **Darwin-18.7.0-x86_64-i386-64bit**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@e9a82d932c30f9614bc4658fba03a745afc705ef
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_5 :: [e9a82d9] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by vbigchris** [comment]
### INFO
Python Version: **2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-169-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@e9a82d932c30f9614bc4658fba03a745afc705ef
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [e9a82d9] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by huush** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **develop**
Commit: SickChill/SickChill@e9a82d932c30f9614bc4658fba03a745afc705ef
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [e9a82d9] Missing time zone for network: Disney+. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
