### ISSUE TITLE
[APP SUBMITTED]: "There is no item named 'nl.xml' in the archive"

### ISSUE THREAD

**Issue by PeterHubert** [SickChill/SickChill#5718]
### INFO
Python Version: **2.7.14 (default, Jan  8 2018, 16:10:56) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/3e4910a51c3004ec643f33d28e0b69b5
### ERROR
```
SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /volume1/TV Series_new/NCIS on theTVDB using ID 72108, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'nl.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fl1ck3r** [comment]
This issue is repeated, see original for updates : [https://github.com/SickChill/SickChill/issues/5686](url)

**Comment by miigotu** [comment]
Completely fixed in develop branch. ;)
