### ISSUE TITLE
SickChill cannot see Shared Folders on QNAP

### ISSUE THREAD

**Issue by Systemcrash74** [SickChill/SickChill#5721]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: MAC OSX
Browser: Safari
What you did: Tried to add Post Processing settings, but cannot browse to Shared Folders on QNAP.  Also cannot manually add the path /share/Downloads (error about cannot access)
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by BenjV** [comment]
SickChill does not have the correct privileges, you have to correct that on your Qnap.

**Comment by Systemcrash74** [comment]
Yes, I kinda assumed that’s what was wrong.  Do you know how I got about fixing the permissions?  What account is Sickchill using?  Where do I fix the permissions?  In Container Station?  In the Container?  In Users/Access Permissions?

Scott

**Comment by papampi** [comment]
Is it installed on container?
Why not directly install it from qnapclub.eu repo from app center?
I have it on TVS-863 with no problems at all
