### ISSUE TITLE
[APP SUBMITTED]: "There is no item named 'en.zip.xml' in the archive"

### ISSUE THREAD

**Issue by meks007** [SickChill/SickChill#5722]
### INFO
Python Version: **2.7.12 (default, Aug 20 2016, 20:35:21) [GCC 5.2.0]**
Operating System: **Linux-4.14.24-qnap-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@e9a82d932c30f9614bc4658fba03a745afc705ef
Link to Log: https://gist.github.com/91e2ca5f84437ca2a819a14b92d38616
### ERROR
```
SHOWQUEUE-ADD :: [e9a82d9] Unable to look up the show in /share/Multimedia/Serien/The Boys on theTVDB using ID 355567, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.zip.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by gielie** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:46:53) [GCC 4.6.3]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: None
Branch: **develop**
Commit: SickChill/SickChill@e9a82d932c30f9614bc4658fba03a745afc705ef
Link to Log: https://gist.github.com/a30a59f79ac3c31380344f1eea68a20f
### ERROR
```
SHOWQUEUE-ADD :: [e9a82d9] Unable to look up the show in /volume1/TVseries/The Feed (2019) on theTVDB using ID 361038, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.zip.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by maxfield07** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@e9a82d932c30f9614bc4658fba03a745afc705ef
Link to Log: https://gist.github.com/3c331061f688a10a29251154eed3c172
### ERROR
```
SHOWQUEUE-ADD :: [e9a82d9] Unable to look up the show in /media/diskstation/media/TV Series/The Morning Show on theTVDB using ID 361563, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.zip.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by maxfield07** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@e9a82d932c30f9614bc4658fba03a745afc705ef
Link to Log: https://gist.github.com/29c2a2cf4878741d958dcf1b6785e439
### ERROR
```
SHOWQUEUE-ADD :: [e9a82d9] Unable to look up the show in /media/diskstation/media/TV Series/Evil on theTVDB using ID 363955, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.zip.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by maxfield07** [comment]
### INFO
Python Version: **2.7.15+ (default, Oct  7 2019, 17:39:04) [GCC 7.4.0]**
Operating System: **Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@e9a82d932c30f9614bc4658fba03a745afc705ef
Link to Log: https://gist.github.com/974662e6ffa9e8c81de1046838ce8c4f
### ERROR
```
SHOWQUEUE-ADD :: [e9a82d9] Unable to look up the show in /media/diskstation/media/TV Series/Star Trek Picard on theTVDB using ID 364093, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.zip.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by meks007** [comment]
for the record i have removed the zip-part from the filename and its working now ... it appears as if tvdb have fixed the naming issue in their api

return xmltodict.parse(myzipfile.read('%s.xml' % language), postprocessor=process)

**Comment by mmhere** [comment]
Yup, thetvdb switched back to the original way prior to their problems that began ~2wks ago.  Nightly updates still broken.

**Comment by PILO7980** [comment]
They fixed the naming issue, but still have a lot of problems. I've tried to add The Mandalorian and got "The Mandaloriano con las tetas en la mano" instead.

**Comment by mesa57** [comment]
Last 2 commits on the tvdb-api.py should be reverted on the develop branch to follow the back- and forth of tvbd :confused:

**Comment by pipopop** [comment]
Hello, I use the master branch Version v2019.06.28-1.
Last week, I modified the the tvdb_api.py as it is mentioned here : [https://github.com/SickChill/SickChill/issues/5686#issuecomment-554764119](https://github.com/SickChill/SickChill/issues/5686#issuecomment-554764119)
It works until the TVDB API change again.
I tried to use the original tvdb_api.py. But it doesn't work too.
Do you know if there is a solution to solve this problem ?

**Comment by Wally73** [comment]
https://github.com/SickChill/SickChill/pull/5731/files

**Comment by pipopop** [comment]
@Wally73 I think I already use this version of code (it's the same as master branch).

**Comment by jamieewart** [comment]
### INFO
Python Version: **2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **develop**
Commit: SickChill/SickChill@e9a82d932c30f9614bc4658fba03a745afc705ef
Link to Log: https://gist.github.com/f68f032a595d3880a81abb0e38a19092
### ERROR
```
SHOWQUEUE-ADD :: [e9a82d9] Unable to look up the show in C:\tv\Ray Donovan on theTVDB using ID 259866, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.zip.xml' in the archive"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
#5789 fixes, is in develop branch. Will be on master after more testing.
