### ISSUE TITLE
Empty space on poster listing

### ISSUE THREAD

**Issue by jamesmck** [SickChill/SickChill#5724]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/e094759640ca61c5c033bf1ff9d33bc7fc1ba857
OS: Linux-4.15.0-70-generic-x86_64-with-Ubuntu-18.04-bionic
Browser: Brave (latest)
What you did: Added a new show
What happened: Show was not added due to an error but worked fine when I retried. But now I have an empty space in the show listings that I cannot click on or delete.
What you expected: To be able to delete the empty placeholder.
![Screenshot_2019_11_25 10_32_53](https://user-images.githubusercontent.com/9306482/69529142-f9812b80-0f6f-11ea-89fa-2a2e46f8b032.png)

Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Seems there is an error in your db. You should be able to view the source of the page and find the Id of the show and use another show to go to the display show page and change the Id in the url, then click remove

**Comment by MrHappy** [comment]
I've got the same issue. Looking at the source of the page (or inspect elements) there is nothing there to show. It goes (in the example like above) from Sherlock to Star Trek.
When I change the poster size to smaller at some point it is okay, but smaller of bigger and it's wrong again.
Any other ideas?

**Comment by miigotu** [comment]
Then it's the bug in isotope from way back. There is no fix for it yet.

**Comment by miigotu** [comment]
I cannot reproduce this, have you tried ctrl+f5?

**Comment by ddease2** [comment]
This is still an issue for me. Reading above, I guess its a bug with isotope so it probably won't be fixed?
