### ISSUE TITLE
Access Denied: https://artworks.thetvdb.com/banners/_cache/posters/5d74e59889b16.jpg

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#5725]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:Branch: master / Commit: e094759640ca61c5c033bf1ff9d33bc7fc1ba857 
OS: Docker
Browser:
What you did: Downloaded new show
What happened: Show downloaded but image on Show List page shows only the generic sickchill image
What you expected: An image with artwork from the show on the Show List page
Logs:
```
PASTE LOGS HERE
```

Is this something that still needs to be fixed by TVDB? or is there some setting I'm missing in the master branch (I've been doing some manual editing, but thought I had reverted everything).

If I enter the URL manually into a browser, it returns an "AccessDenied" code.

Since I'm using docker, with the image from linuxserver, they don't include the dev branch, and I'd rather not go through the agony of switching if not necessary.

Thanks.

**Comment by mesa57** [comment]
It is also a problem on the develop branch. Even adding a show via the theTVDB api does again not work any more on that branch (think theTVDB reverted some changes again),

**Comment by ronrosenfeld** [comment]
Well, for the most part, my main branch seems to be working.  At least, I can add new shows and get the artwork.  I'm not sure about old show updates, but I don't seem to be missing any.  The problem with a missing poster seems to have to do with one particular show, as I just added a different show, and the artwork appeared.

**Comment by mesa57** [comment]
Please reopen this issue as the given url still give this problem.
https://artworks.thetvdb.com/banners/_cache/posters/5d74e59889b16.jpg
