### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'whitelist'

### ISSUE THREAD

**Issue by psa99** [SickChill/SickChill#5728]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [e094759] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickchill/views/index.py", line 180, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickchill/views/home.py", line 987, in editShow
    whitelist = show_obj.release_groups.whitelist
AttributeError: 'NoneType' object has no attribute 'whitelist'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by psa99** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [e094759] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickchill/views/index.py", line 180, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickchill/views/home.py", line 987, in editShow
    whitelist = show_obj.release_groups.whitelist
AttributeError: 'NoneType' object has no attribute 'whitelist'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Does this happen on latest develop branch?
