### ISSUE TITLE
[Feature Request] changing show name

### ISSUE THREAD

**Issue by ahyear** [SickChill/SickChill#5730]
Hello 
Some time the show name is followed by a sub title. 
It would be nice to be able to remove it from the show name (for list and post process) or edit the name to remove "the" in the beginning of we want to.

**Comment by defhead** [comment]
What about adding a scene exception name: "Edit" (from the show page) => "Advanced" => Enter a scene exception => "Add" => "Save Changes". It will match your show with the search results.

Does it solve your problem?

**Comment by ahyear** [comment]
no I still have the original name in the post process show title.
the issue is note finding episodes but naming them...
![image](https://user-images.githubusercontent.com/8113672/69961255-c90b3580-150b-11ea-8d44-9c5becce707f.png)

**Comment by nydave69** [comment]
Add... So many shows are remakes or copies of shows from other countries,  would be nice to be able to add to the title (US)  or (1969) whatever you want to separate them out.  Don't even suggest going to the TVDB and trying anything.
