### ISSUE TITLE
[APP SUBMITTED]: Found 73871, but attribute 'seriesname' was empty.

### ISSUE THREAD

**Issue by StanESmith** [SickChill/SickChill#5735]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-5.0.21-5-pve-x86_64-with-debian-10.2**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@2404f197697602a2bbfa8e6b39207229a94d37bb
Link to Log: https://gist.github.com/280359c139adc78ef232833d5fb38c53
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [2404f19] Data retrieved from theTVDB was incomplete, aborting: Found 73871, but attribute 'seriesname' was empty.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
#5789 fixes, is in develop branch. Will be on master after more testing.
