### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/downloads/_UNPACK_The Blacklist S02E12 NORDiC 720p WEB-DL DD5 1 H 264-GREYHOUNDS/TB_2_2/The.Blacklist.S02E12.NORDiC.720p.WEB-DL.DD5.1.H.264-GREYHOUNDS.mkv'

### ISSUE THREAD

**Issue by glancy** [SickChill/SickChill#5741]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.19.56-Unraid-x86_64-with**
Locale: None
Branch: **develop**
Commit: SickChill/SickChill@2404f197697602a2bbfa8e6b39207229a94d37bb
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [2404f19] [Errno 2] No such file or directory: '/downloads/_UNPACK_The Blacklist S02E12 NORDiC 720p WEB-DL DD5 1 H 264-GREYHOUNDS/TB_2_2/The.Blacklist.S02E12.NORDiC.720p.WEB-DL.DD5.1.H.264-GREYHOUNDS.mkv'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by glancy** [comment]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-4.19.56-Unraid-x86_64-with**
Locale: None
Branch: **develop**
Commit: SickChill/SickChill@2404f197697602a2bbfa8e6b39207229a94d37bb
No Log available with ERRORS:
### ERROR
```
POSTPROCESSOR-AUTO :: [2404f19] Unable to move file /downloads/_UNPACK_The Blacklist S02E12 NORDiC 720p WEB-DL DD5 1 H 264-GREYHOUNDS/TB_2_2/The.Blacklist.S02E12.NORDiC.720p.WEB-DL.DD5.1.H.264-GREYHOUNDS.mkv to /tv/The Blacklist/Season 02/The Blacklist - S02E12 - The Kenyon Family.mkv: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by embii74** [comment]
Same issue has already been reported quite some time ago:
#5318

**Comment by kretzu77** [comment]
### INFO
Python Version: **2.7.16 (default, Mar  7 2019, 23:06:01) [GCC 8.2.0]**
Operating System: **Linux-3.10.105-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@1f124b31b16303a511c86717f11dd28b9cbf7b46
Link to Log: https://gist.github.com/3dcff3a4736e7661a817016869b5a538
### ERROR
```
WEBSERVER-ADDSHOWS :: [1f124b3] Unable to run synoindex: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kretzu77** [comment]
### INFO
Python Version: **2.7.16 (default, Mar  7 2019, 23:06:01) [GCC 8.2.0]**
Operating System: **Linux-3.10.105-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@1f124b31b16303a511c86717f11dd28b9cbf7b46
Link to Log: https://gist.github.com/3c0e867a8515692ab93a77fe32e53b3c
### ERROR
```
POSTPROCESSOR-AUTO :: [1f124b3] Unable to run synoindex: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kretzu77** [comment]
### INFO
Python Version: **2.7.16 (default, Mar  7 2019, 23:06:01) [GCC 8.2.0]**
Operating System: **Linux-3.10.105-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@4a38d31d5c0f5e30d9f8181f03b3ff85c6f51e3e
Link to Log: https://gist.github.com/1c6110a07ea455afa4c4b0b2e7189a5f
### ERROR
```
POSTPROCESSOR-AUTO :: [4a38d31] Unable to run synoindex: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
