### ISSUE TITLE
Newly updated poster not updated in browser due to browser cache

### ISSUE THREAD

**Issue by cgatesman** [SickChill/SickChill#5742]
If a poster is missing then updated using a full refresh, the poster continues to be shown as the default poster.  The `Last-Modified` response header is showing an old date, instead of today which is when the poster was updated.  I believe this is why the browser continues to use the browser cached version.  Of course, clearing browser cache fixes the problem, but you shouldn't have to do that.

```
GET https://localhost:8081/showPoster/?show=332858&which=poster_thumb
HTTP/1.1 200 OK
Content-Length: 748493
Accept-Ranges: bytes
Vary: Accept-Encoding
Server: TornadoServer/4.5
Last-Modified: Thu, 14 Nov 2019 21:58:39 GMT
Etag: "3c140a15945fd13c322b2815e0a0448ae3fc7347"
Cache-Control: public, max-age=86400
Date: Sun, 01 Dec 2019 13:28:13 GMT
Content-Type: image/png
```

**Comment by Wally73** [comment]
a force refresh page mostly works too (ctrl+f5 in chrome)

**Comment by cgatesman** [comment]
Of course.  Same difference.  You shouldn't have to do that.

**Comment by miigotu** [comment]
This is quite complicated because we can only have 1 staticfiles dir. It would force us to store posters in the same folder as the gui source files

**Comment by miigotu** [comment]
Ive made a change for it, but it will require moving your cache dir inside `gui/slick/` so its like `gui/slick/cache/images` and setting cache_dir in config.ini to `gui/slick/cache`

**Comment by miigotu** [comment]
I will get it into production as soo as I do more testing.

**Comment by cgatesman** [comment]
Thanks, @miigotu!
