### ISSUE TITLE
[APP SUBMITTED]: Found 269586, but attribute 'seriesname' was empty.

### ISSUE THREAD

**Issue by lsducati** [SickChill/SickChill#5744]
### INFO
Python Version: **2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.15.18-seedhost-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@2404f197697602a2bbfa8e6b39207229a94d37bb
Link to Log: https://gist.github.com/c67a5158070cc763ec19965c9d77e09c
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [2404f19] Data retrieved from theTVDB was incomplete, aborting: Found 269586, but attribute 'seriesname' was empty.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
#5789 fixes, is in develop branch. Will be on master after more testing.

**Comment by adrienvia** [comment]
### INFO
Python Version: **2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.14.58v7-aufs-armv7l-with-debian-9.11**
Locale: ISO8859-1
Branch: **master**
Commit: SickChill/SickChill@6d86b33618952100cafd6b322bc295246a228c00
Link to Log: https://gist.github.com/6e98f6f7b0e88fd9abedb960da26e9dd
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [6d86b33] Data retrieved from theTVDB was incomplete, aborting: Found 269586, but attribute 'seriesname' was empty.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
@adrienvia you need to update, bad lol
