### ISSUE TITLE
[Q] Set default quality/All shows quality

### ISSUE THREAD

**Issue by Extarys** [SickChill/SickChill#5746]
### Before submitting your issue:

Branch/Commit:  master  /  2404f197697602a2bbfa8e6b39207229a94d37bb 
OS: Synology
Browser: Firefox
What you did: I imported all shows with 1080p preferred quality and saved as default
What happened: All shows are marked for SD quality
What you expected: All shows imported as 1080p preferred

How can I set the quality of all shows that are already imported?
I'd prefer BD RIP 1080p and 720p before 1080p HDTV for example. Would that be possible?

**Comment by miigotu** [comment]
Mass edit, select the quality column, submit
