### ISSUE TITLE
IPTorrents sometimes give me na error

### ISSUE THREAD

**Issue by MastaG** [SickChill/SickChill#5748]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop latest commit
OS: Fedora 31
Browser: Firefox
What you did:
Configured IPTorrrents as search provider
What happened:
It works but sometimes gives me a warning and error
What you expected:
No warning and error
Logs:
```
2019-12-06 11:01:29 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Unable to connect to provider
AA KeyError: 'location'
AA raise requests_exception
AA File "/opt/sickchill/sickbeard/helpers.py", line 1527, in handle_requests_exception
AA Traceback (most recent call last):
2019-12-06 11:01:29 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [2404f19] Request failed: 'location' ()
```

**Comment by cb1ocker** [comment]
I'm getting the same errors running latest master branch on Windows. Everything appears to be working fine, but those 2 messages are a daily occurrence.

**Comment by silencer727** [comment]
Same here. for me doesn't work at all any more. exact same error

**Comment by Vanguard4893** [comment]
Also having this issue. Not working at all here.

**Comment by tobias-urdin** [comment]
See https://github.com/SickChill/SickChill/issues/5737#issuecomment-567677430

**Comment by miigotu** [comment]
If any of you can, please try the cfscrape branch and let me know. Thanks
