### ISSUE TITLE
[Feature Request] Option not to update ended shows.

### ISSUE THREAD

**Issue by papampi** [SickChill/SickChill#5749]
Please add an option not to update ended shows.
Most of us have many ended shows in our libraries so checking and updating them every night is a waste of resource.

Please consider it.

**Comment by Dekkerjj** [comment]
Is the 'pause' option not doing just that?
![image](https://user-images.githubusercontent.com/29119422/70334351-992e9b80-1845-11ea-9b94-e4c26bd117ff.png)

**Comment by papampi** [comment]
Pause do that manually, so you should check and pause ended shows.
What I suggest will pause them automatically when they ended.

Sickchll job is to make things happens automatically.
We can manually download shows, rename them, move them and ....and don't use Sickchill, but we use it so we don't do stuff manually.

**Comment by consenti** [comment]
Use mass update.  
![Screen Shot 2019-12-12 at 11 01 24 AM](https://user-images.githubusercontent.com/10899191/70740814-da53ff00-1cce-11ea-8439-56b47862daa2.png)

**Comment by papampi** [comment]
I know mass update can do it too, But that is also is doing it manually.

**Comment by Dekkerjj** [comment]
@papampi: So you want to automate everything, but it should not waste resources.. That's a difficult tradeoff :-)
f.e. : 
If a show is automatically stopped in Sick Chill after an announced show-end and a reboot follows the new episodes would not be downloaded unless Sickchill checks the status and unpauses again. But in that case pausing is pointless as it has to check status whether it is paused or not.
So I'm still in favour of current mechanism as quite some shows (24, Prison Break, Will&Grace) have rebooted after a couple of years.

**Comment by papampi** [comment]
@Dekkerjj, That's a good point, then it's best to put ended shows to some kind of a semi-pause state, so sickrage update ended shows at longer intervals like every 30 days instead of every day.

**Comment by miigotu** [comment]
It's pretty easy to add this feature. I will do it after the fallout from the tvdb3 PR is handled once it is released.

**Comment by nydave69** [comment]
I have a lot of shows that are ended.... but missing some episodes so I have them NOT paused so it can capture them if it finds them.  Auto pausing them would keep me from finding those episodes.
I can't believe that it's that hard to click pause once, for the show you do not wish any more downloads.

**Comment by miigotu** [comment]
@papampi is the reason you want this because master is currently updating every show in your showlist every time?
@nydave69 It would absolutely be configurable, and defaulting to off

**Comment by papampi** [comment]
Yes, I see them in show update queue when it's not needed at all, they are ended and fully downloaded.
SC can have an option to auto pause or delay update ended fully downloaded shows if user wanted, else it update them like all the rest.

**Comment by miigotu** [comment]
@papampi there is a bug in master right now that updates all shows even if there are no updates. We will be only updating shows that actually changed, and updating shows is not really much work in the background.

I could go and add this, but I'm concerned for when something is fixed on tvdb that makes a missed episode get downloaded correctly or it changes from ended to continuing.

**Comment by papampi** [comment]
If only updated shows in indexer gets the update then I think it won't be needed at all.
But if not that's why I suggested delay updates, so ended shows with no wanted episodes get updated every week/month/10 days or whatever you think is best or as user sets.

**Comment by nydave69** [comment]
OK I found the setting, It's defaulted to 7
How do I disable it..  set it to -1 , 0 , 1  doesn't say...

**Comment by miigotu** [comment]
-1 is never update them (infinity days), 0 is 0 days so 0 days have to pass since the last update so....

**Comment by nydave69** [comment]
thanks,  zero it is.....   
Should see if you can add that to the settings screen..
