### ISSUE TITLE
Episode number limit?

### ISSUE THREAD

**Issue by Dekkerjj** [SickChill/SickChill#5752]
I have a couple of DVD copies that have one file for multiple episodes.
With two episodes in one file everything works fine, but larger numbers gives an interesting error:

 --Snip of logfile--- 
No episode number found in /....../Series/New kids/Season 1/New Kids.S01E01E02E03E04E05E06E07E08E09.VOB, ignoring it
No episode number found in /volume1/Video/Series/Bumba/Season 10/Bumba.S10E01E02E03E04E05E06E07E08E09E10E11E12 - In Azie.mp4, ignoring it
No episode number found in /........../Series/Bumba/Season 05/Bumba.S05E01E02E03E04E05E06E07E08E09E10E11E12 - Kiwi.mp4, ignoring it
------

Is there a limit to the number of episodes allowed in one file?

**Comment by miigotu** [comment]
I think we allow 4 in one file, because the naming usually ends up exceeding file path limits otherwise.
