### ISSUE TITLE
Github api usage deprecation

### ISSUE THREAD

**Issue by mesa57** [SickChill/SickChill#5757]
>You recently used a password to access an endpoint through the GitHub API using SickChill. We  will deprecate basic authentication using password to this endpoint soon:

https://api.github.com/organizations/44020801

> We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

> Thanks,
> The GitHub Team

Branch : Master

**Comment by Wally73** [comment]
create a token ;)

**Comment by Wally73** [comment]
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/
