### ISSUE TITLE
Episode Order Change on TheTVDB doesn't reflect in SickChill

### ISSUE THREAD

**Issue by whiteazn** [SickChill/SickChill#5764]
Recently, the Episode Order of a Show was recently updated in TheTVDB.  But The change does not reflect in SickChill.

https://thetvdb.com/series/peytons-places/seasons/official/1

Correct Order (as is current on TheTVDB):
Ep2: Greatest Catch
Ep3: History of the QB

Episodes 2 and 3 were reversed (Early on, Ep2 was listed as History of the QB, while Ep3 was Greatest Catch).  This was fixed later on, in the old version of thetvdb, then again recently, in the new version.  

I have tried removing the show and re-adding it.  But SickChill still lists it under the old order

https://i.imgur.com/peLR1X4.png

I have the files named correctly manually (and Plex finds it fine)

**Comment by ronrosenfeld** [comment]
Did you delete and re-download the files also?

**Comment by whiteazn** [comment]
Yes, but the files I download have the correct order, and would thus be named incorrectly

**Comment by ronrosenfeld** [comment]
In your screenshot, it appears there is a mismatch between "Name"  (correct) and "File Name" (incorrect).  When I'm at a location with a faster internet, I'll see what happens with a fresh download.

**Comment by whiteazn** [comment]
That's cause in the end I manually renamed the files to be correct for Plex/TheTVDB

**Comment by ronrosenfeld** [comment]
Something funny with this show.  Although Sickchill found the show, it could not find any of the episodes on my NZB provider even though the episodes and shows were present if I did a manual search!

 > INFO     SEARCHQUEUE-MANUAL-362863 :: Beginning manual search for: [Peyton's Places - S01E01 - The Hupmobile]
 > INFO     SEARCHQUEUE-MANUAL-362863 :: [NZBGeek] :: Performing episode search for Peyton's Places
 > INFO     SEARCHQUEUE-MANUAL-362863 :: Unable to find a download for: [Peyton's Places - S01E01 - The Hupmobile]

**Comment by whiteazn** [comment]
for me, I am downloading it via Torrents, then manually post-processing it.

Wonder if maybe the apostrophe is throwing it off during the search?  

Torrent files have it as Peytons.Places.S01E01....

**Comment by ronrosenfeld** [comment]
I tried adding "Peytons Places" to the scene exception list, but the results were the same.

**Comment by miigotu** [comment]
Sometimes there is a discrepancy between what tvdb shows on the interface and what data they give to us in the update file. When SC searches for a show, it doesnt search with the episode name. My guess is this will clear up on its own eventually.

**Comment by miigotu** [comment]
Issue resolved?

**Comment by whiteazn** [comment]
Sorry.  Yeah, I did recently update SickChill, but I haven't checked until now, so not sure if they were related or not.  

Thank you
