### ISSUE TITLE
UI User "appears" in log with stars

### ISSUE THREAD

**Issue by Pastagazok** [SickChill/SickChill#5766]
Hello,

Firstable, excuse me for my english, wich is not perfect (I know that. :) )

My context :

Branch: master
Commit: 2404f197697602a2bbfa8e6b39207229a94d37bb
Version: v2019.11.28-1
Database Version: 44.0

My problem :

In the log screen, I can see some "well known" words with some stars in the middle of them.
These stars are hidding the letters of my UI password, in the words containing them.

So, in some case, it is very easy to find the UI password.

One example : My ta**or is rich ! :)
We understand easily that the stars are hidding the letters "il".

It's a little security problem, no ?

Have a nice day.
Thx,
Guillaume.

**Comment by WebSpider** [comment]
Can you please provide some examples of these logs, so we can find the corresponding code, and see where to fix this?

Just replace your actual password with MYPASSWORDWASFOUNDHEREOMG or something similar ;)

**Comment by Pastagazok** [comment]
Hi,

I've tried to imagine for you one example up above.
I'm affraid that if I show you my log, even if I use "MYPASSWORDWASFOUNDHEREOMG" to replace it, you will find my password. Right ? :)
There are 2 types of sentences that show the problem, actually.
How can I do to give you these informations... privately ?

Thx.

**Comment by dirkr07** [comment]
You could always change your password for real to something, get the logs and switch back..?

**Comment by Pastagazok** [comment]
OK. :)
For test, I've installed a temporary SickChill with a user "pi", and it appears that it's not the UI password, but the UI user (I apologize...).
So, it's not as bad, but there's no reason for this string to "appear" (hidden) in the log with stars.

See below what appened in my log (search "**" please):

...
2019-12-12 09:04:06 INFO DAILYSEARCHER :: Searching for new released e**sodes ...
2019-12-12 09:03:19 INFO FINDPROPERS :: Completed the search for new propers, next check in approx. 14m, 59s
2019-12-12 09:03:19 INFO FINDPROPERS :: [Rarbg] :: Searching for any new PROPER releases from Rarbg
2019-12-12 09:03:19 INFO FINDPROPERS :: Beginning the search for new propers
2019-12-12 09:03:16 INFO CHECKVERSION :: Checking for updates using GIT
2019-12-12 09:03:15 INFO SHOWUPDATER :: Could not get the recently updated show data from theTVDB. Retrying later. Url was: http://thetvdb.com/a**/Updates.php?type=series&time=978303600
2019-12-12 09:03:15 INFO SHOWUPDATER :: Request failed: 500 Server Error: Internal Server Error for url: https://thetvdb.com/a**/Updates.php?type=series&time=978303600 ()
...

Thx, Guillaume.

**Comment by BenjV** [comment]
Why would the username be a security risc?
Of course access to the logfile should be restricted to the same user and so I don't see any security risc

**Comment by Pastagazok** [comment]
Hello,
Because first I thought it was the password, not the username (I've changed the title).
As I said, there's no reason for this string to "appear" (hidden) in the log with stars.
It’s a strange behavior of the application.

**Comment by Pastagazok** [comment]
I haven't said that yet, so... I am a super-fan of this application. Go on ! :)

**Comment by Pastagazok** [comment]
Hello, do you need more information ?

**Comment by Pastagazok** [comment]
Hi and happy new year,
I can give you more information if you want.
This thread is marked "Need More Info", so I asked...

**Comment by Pastagazok** [comment]
Hi miigotu,
Thank you for your work.
Have a nice day.
