### ISSUE TITLE
Github deprecation of basic authentication via password?

### ISSUE THREAD

**Issue by famewolf** [SickChill/SickChill#5769]
I received this.   Is this something I need to take action on?

Hi @famewolf,

You recently used a password to access an endpoint through the GitHub API using SickChill. We will deprecate basic authentication using password to this endpoint soon:

https://api.github.com/organizations/44020801

We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

Thanks,
The GitHub Team

**Comment by augur42** [comment]
I got that too, and yes you should take action on it. Simply go to Config>General>Advanced Settings, scroll down to GitHub>Authorization Type, change it to Personal access token and follow the prompts to generate one for SickChill. It took me all of five minutes from seeing the email to inputting the token.

**Comment by famewolf** [comment]
Thanks for the info! Should be useful to others who get the email.   Done.

**Comment by asibat** [comment]
does this also affect git clone command using username and password authentication ?
