### ISSUE TITLE
Facing an issue with Scene Exception

### ISSUE THREAD

**Issue by mbuyukkalender** [SickChill/SickChill#5771]
### Before submitting your issue:

Branch/Commit: Master
OS: Asustor ADM
Browser: Chrome
What you did: I tried to add a scene exception for the show "Paw Patrol" but it doesn't work.

Currently, the torrent provider uses name like "PAW PATROL, LA PAT'PATROUILLE S06.E11.TRUE.FRENCH.1080P.WEB-DL.X264-AC3.-B.M.A'.

So I added, "PAW PATROL, LA PAT'PATROUILLE" as an exception for the whole show... But it seems also that the season / episod format causes trouble because SickChill is looking for something with "S06E11" but torrent provider pushed something like "S06.E11"

Is there a way to modify season / episod format for a specific show ? 

Thanks in advance for your feedback

**Comment by miigotu** [comment]
The code would need to be modified to support that episode format, but we would have to worry about it breaking other releases.
