### ISSUE TITLE
Missing files status not changing to Archived

### ISSUE THREAD

**Issue by G33K** [SickChill/SickChill#5772]
Branch/Commit: master/2404f197697602a2bbfa8e6b39207229a94d37bb
OS: Linux-4.9.0-9-amd64-x86_64-with-debian-9.9
Browser:Chrome
What you did: Already ran "Force Full update" and "Re-Scan Files"
What happened: Episode status not changing to Archived
What you expected: Episode status to change to Archived
Logs:
```
2019-12-18 13:44:36 DEBUG SHOWQUEUE-REFRESH :: Unable to find a file path to use for this thumbnail, not generating it
2019-12-18 13:44:36 DEBUG SHOWQUEUE-REFRESH :: Metadata provider KODI 12+ creating episode thumbnail for House of Cards (US) - S01E07 - Chapter 7
2019-12-18 13:44:36 DEBUG SHOWQUEUE-REFRESH :: formatting pattern: %SN - S%0SE%0E - %EN -> House of Cards (US) - S01E07 - Chapter 7
2019-12-18 13:44:36 DEBUG SHOWQUEUE-REFRESH :: Parsed /path/House of Cards (US)/Season 1 - 1080p BluRay/1x07 - Chapter 7 - House of Cards (US) (1080p BluRay) into S01E07 [ABD: False] [ANIME: False] [whichReg: [u'fov', u'season_only']]
2019-12-18 13:44:36 DEBUG SHOWQUEUE-REFRESH :: Checking if /path/House of Cards (US)/Season 1 - 1080p BluRay/1x07 - Chapter 7 - House of Cards (US) (1080p BluRay).nfo exists: True
2019-12-18 13:44:36 DEBUG SHOWQUEUE-REFRESH :: 262980: Retrieving/creating episode S01E07
```

Some files got accidentally deleted. The video files are not there but the nfos are there. Tried running a "full update", "re-scan files" so that I can quickly see which files are missing by the archived status but the status does not change from "Downloaded". Deleted the nfo and re-ran scan to only have the nfo recreated but still say downloaded.

**Comment by miigotu** [comment]
TVDB had some issues. Should work fine now.

**Comment by G33K** [comment]
This is still not working as intended.
Updated to 2c72459ddfd209106d1eb76677b2016f4bcecd74 and still the same.

With video files not present the status should change from Downloaded to Archived, this is not happening.

**Comment by miigotu** [comment]
Make sure you do not have `Skip Remove Detection` checked in `Config->General->Advanced` and your `Default deleted episode status` is set on the same page

**Comment by G33K** [comment]
Thanks. I completely overlooked that option! 

It now correctly switched the status to Archived.

However this now brought up another issue, the previous quality was "Downloaded (1080p Bluray)" but after update the status now changed to "Archived" and not "Archived (1080p Bluray)" and since there is no quality attached I can't bring them up in the Episode Status Management page.

**Comment by miigotu** [comment]
If it's deleted, it has no quality, because there is no file...

**Comment by G33K** [comment]
With that logic then it will always just say Archived and never have any quality info because the video file is never there when it is changing to Archived. I would assume that it would use the previous status which in this case was Downloaded 1080p Bluray?

**Comment by miigotu** [comment]
There is no reason for it to have a quality if there is no file.

**Comment by G33K** [comment]
1. Thats contradictory to the note on the Advanced Settings page under "Default deleted episode status" option which reads:
"define the status to be set for media file that has been deleted.
note: Archived option will keep previous downloaded quality
example: Downloaded (1080p WEB-DL) ==> Archived (1080p WEB-DL)"

2. Assuming that the quality is not carried over, how then can I pull up all the archived episodes that don't have any quality attached on the Manage>Episode Status Management page since there is no option for Archived without any quality?

**Comment by miigotu** [comment]
Your 2nd question is a bug, but it isnt a priority right now.
It will eventually set them all to Archived and only show the Archived option in ep status management. I assume, for the time being you know which episodes you have deleted manually.
