### ISSUE TITLE
Show unable to add - search unable to find as "singletown", but insists it is "singletown" after being found as "single town".

### ISSUE THREAD

**Issue by quickdry** [SickChill/SickChill#5778]
Trying to add show "Singletown", is reported as not found but has very strange results (it exists in TVDB)

[Screenshot 1 - search for one word](https://i.imgur.com/stiMuhI.png)

Searching for "single town" (two words) _is_ found, but returned as the single word "singletown"

[Screenshot 2 - search two words, returned as one word](https://i.imgur.com/F92iMzT.png)

Adding this returns the error

SHOWQUEUE-ADD :: Show in E:\TV Shows\Singletown has no name on theTVDB, probably searched with the wrong language. Delete .nfo and add manually in the correct language.

[Screenshot 3 - error finding as one word](https://i.imgur.com/KznLXV5.png)

Branch/Commit: master
OS: Windows-2012Server-6.2.9200

**Comment by quickdry** [comment]
changing the directory to be two words "single town", adding as existing show, results in the same as screenshot 2, and a slightly different error message:

SHOWQUEUE-ADD :: Show in E:\TV Shows\Single town has no name on theTVDB, probably searched with the wrong language. Delete .nfo and add manually in the correct language.

**Comment by asbestinuS** [comment]
Hi,
I'd like to add that I have the same issue, with Doctor Who:

WARNING  SHOWQUEUE-ADD :: Show in F:\Series\Doctor Who (2005) has no name on theTVDB, probably searched with the wrong language. Delete .nfo and add manually in the correct language.

Not sure which .nfo I'm supposed to delete or manually add another language.
Thanks!
