### ISSUE TITLE
Airdates Lost After Shows Update

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#5782]
In my latest update of existing shows I have lost the airdates for a number of shows which has resulted in them showing in the show list as downloaded 0/0

![image](https://user-images.githubusercontent.com/25068977/71307676-69f16000-23e9-11ea-9e57-3ec2489f5674.png)

Branch: master
Commit: d468bee
Version: v2019.12.20-1
Database Version: 44.1
OS: Windows 10
Browser: Firefox
What you did: SickChill ran the scheduled show update
What happened: Multiple shows now show Never in the airdate
What you expected: TV Shows to update with airdate information from TheTVDB

I have gone to each show to force an update but that hasn't returned the airdates, there are a large number of entries in the log reflecting that episodes cannot be found.

Logs:
```
2019-12-21 10:59:44 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 75682: Could not find season 2 (unaired/deleted) in the indexer theTVDB for Bones. Removing existing records from database

```
Just to add, even without airdates, surely if you have every show downloaded then the download list should show x / x rather than 0 / 0?

**Comment by Xx-Ness-xX** [comment]
I had the similar issue, but I think it's a hiccup from TheTVDB's end
