### ISSUE TITLE
Shudder network icon misspelled as "shutter.png"

### ISSUE THREAD

**Issue by Teamshake** [SickChill/SickChill#5790]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened: file is named shutter.png instead of shudder.png
What you expected:
Logs:
```
PASTE LOGS HERE
```
Thanks

**Comment by miigotu** [comment]
I will fix this later

**Comment by Teamshake** [comment]
thank you
