### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_1 :: [2c72459] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by Teamshake** [SickChill/SickChill#5792]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@2c72459ddfd209106d1eb76677b2016f4bcecd74
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [2c72459] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by scopuli2x** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@2c72459ddfd209106d1eb76677b2016f4bcecd74
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_7 :: [2c72459] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by bwguy** [comment]
### INFO
Python Version: **2.7.14 (default, Mar 03 2018, 11:05:58) [GCC 7.3.0]**
Operating System: **Linux-4.14.24-qnap-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@2c72459ddfd209106d1eb76677b2016f4bcecd74
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [2c72459] Missing time zone for network: Shudder. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
