### ISSUE TITLE
Alternative indexer

### ISSUE THREAD

**Issue by Nickduino** [SickChill/SickChill#5797]
I never understood why the indexer was theTVDB while the popular shows came from IMDB.

I'd like to add Vacations of the Brave, which is referenced on IMDB (https://www.imdb.com/title/tt9055320/) and not www.thetvdb.com: what's the easiest solution for me?

**Comment by BenjV** [comment]
IMDB is owned by Amazon and does not have an API so it is impossible to use IMDB as an indexer.

If some obscure Serie does not exists on TheTvdb, then the only solution is that you login on TheTvdb and create that serie there yourself.
All the data on TheTvdb is created by users and if this serie does not exists there, nobody else bothered to create it.

**Comment by miigotu** [comment]
I'm actually working on adding some other indexers. Please search next time before opening an issue.
