### ISSUE TITLE
Sickchill timeout during startup

### ISSUE THREAD

**Issue by thu3n** [SickChill/SickChill#5807]
OS:Ubuntu 16.4
Browser: -
What you did: Restart ubuntu
What happened: Gets timeout when trying start systemctl start sickchill
What you expected: - 
sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Sat 2019-12-28 18:15:05 CET; 6min ago
  Process: 970 ExecStart=/usr/bin/python2.7 /opt/sickchill/SickBeard.py -q --daemon --nolaunch --datadir=/opt/si
    Tasks: 0
   Memory: 35.1M
      CPU: 793ms

Dec 28 18:13:35 sickchill systemd[1]: Starting SickChill Daemon...
Dec 28 18:15:05 sickchill systemd[1]: sickchill.service: Start operation timed out. Terminating.
Dec 28 18:15:05 sickchill systemd[1]: Failed to start SickChill Daemon.
Dec 28 18:15:05 sickchill systemd[1]: sickchill.service: Unit entered failed state.
Dec 28 18:15:05 sickchill systemd[1]: sickchill.service: Failed with result 'timeout'.

```

**Comment by thu3n** [comment]
This is really f.ck.ng wierd....... I have now solved the issue, it appeard during my LAB period, where i installed Bittorrent on the same computer i have utorrent, only difference is the portnumber here.. As soon as i removed the bittorrent APPDATA folder, eveyrthing start to working again.... It's wierd that sickchill stopped working only because of the appdata folder, i promise you that this was the only thing i did. Removed the APPDATA off bittorrent(didn't use bittorrent, only for LAB purpose.)

**Comment by miigotu** [comment]
Likely both were using the same port?
