### ISSUE TITLE
sick* drama v2

### ISSUE THREAD

**Issue by OmgImAlexis** [SickChill/SickChill#5815]
For those who don't know we now have issues with yet another person... yay.

https://github.com/jackdandy/SickGear/issues/9

Ref: @miigotu @SickChill/collaborators @SickChill/moderators

**Comment by OmgImAlexis** [comment]
Just more crap like https://github.com/SickChill/SickChill/issues/4984

Honestly thought after all these years we'd be over this whole stealing users crap but no...

**Comment by p0psicles** [comment]
You should link to his issue # 11 now

**Comment by BenjV** [comment]
Judging tot his tone and comment in that issue, mister JackDandy and mister Echel0n are one and the same person.
He first copied all the work of MrOrange, renamed it to SickRage and announced he owned it and now he is doing the same to SickGear I guess and still hold a grundge to SickChill.

I would say, ignore him, he will run SickGear into the ground soon with his attitude and lousy coding quality.

**Comment by p0psicles** [comment]
No that's not the case. It's still mister jack over there. Else we'd have seen a takedown somewhere.

**Comment by BenjV** [comment]
In that case I don't understand his ranting about SickChill.
SickGear is also a fork from the copy Echel0n made from the SickBeard fork of MrOrange (called SickBeard the Piratebay).
So they did the same as SickChill did.

**Comment by p0psicles** [comment]
He didn't continue using the sickrage name. He renamed his from the start. He's highlighting the kinda hostile takeover that took place in the past.

**Comment by miigotu** [comment]
I could care less what they have to say. Everyone knows I didn't hold the name for 3 years, and I wasn't "forced" to change it.  I just wanted to be done with their bullshit. I did accomplish showing the world how shitty of a person ech is and how he destroyed development teams all 3 times he was involved. Users will see through this petty attempt at a power grab, and all of those issues he noted aren't even issues in sc right now.

**Comment by miigotu** [comment]
I closed this because I don't think it's worth highlighting it to users this time at this stage. We can still talk about it of course.

**Comment by miigotu** [comment]
I think he just saw I was away for 4 months while we moved across the country and are getting settled in our new house and figured it was his best opportunity.

From here on out I'm not that concerned with winning over users from another project. I just want to make good software that people want to use. The code and functionality will speak for itself.
