### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-FORCE-UPDATE :: [17e379d] No data returned from theTVDB, unable to update this show.

### ISSUE THREAD

**Issue by nickybol** [SickChill/SickChill#5823]
### INFO
Python Version: **2.7.14 (default, Jan 15 2018, 20:23:21) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@17e379df7dadc7711db1c76695411267f245a961
Link to Log: https://gist.github.com/51c162b6d9dac5847149399b67207ae1
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [17e379d] No data returned from theTVDB, unable to update this show.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by jangrewe** [comment]
https://github.com/SickChill/SickChill/pull/5789

**Comment by DravenSA** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@17e379df7dadc7711db1c76695411267f245a961
Link to Log: https://gist.github.com/bf024030d6a713253c0897dc057f2d4c
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [17e379d] No data returned from theTVDB, unable to update this show.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by jangrewe** [comment]
Fixed in develop branch, as mentioned above.

**Comment by HazMatt69** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 02 2019, 11:13:20) [GCC 7.4.0]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@17e379df7dadc7711db1c76695411267f245a961
Link to Log: https://gist.github.com/5ff84ecb7dd9b305ce91284715e7c482
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [17e379d] No data returned from theTVDB, unable to update this show.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by midnightx12** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@17e379df7dadc7711db1c76695411267f245a961
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [17e379d] No data returned from theTVDB, unable to update this show.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
