### ISSUE TITLE
theTVDB complained about wrong language

### ISSUE THREAD

**Issue by jraydoran** [SickChill/SickChill#5826]
### Before submitting your issue:

2020-01-07 21:48:32 SHOWQUEUE-ADD :: Show in /mnt/synologynetworkmediashare/TVShows/Mr. Robot has no name on theTVDB, probably searched with the wrong language. Delete .nfo and add manually in the correct language.

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Error:
2020-01-07 21:48:32 SHOWQUEUE-ADD :: Show in /mnt/synologynetworkmediashare/TVShows/Mr. Robot has no name on theTVDB, probably searched with the wrong language. Delete .nfo and add manually in the correct language.

Branch: master
Commit: 17e379df7dadc7711db1c76695411267f245a961
Version: v2020.01.03-1
Database Version: 44.4
OS: Raspbian Buster
Browser:Safari from macOS
What you did: Added an existing Show.  Selected the directory where show was located.
What happened is It momentary adds the show but disappears nearly immediately
What you expected: Expected the show add

What is also alarming that the final location where it wants to save the show. Mr.RobotMr.Robot.

written twice

<img width="812" alt="Screenshot 2020-01-07 at 22 00 11" src="https://user-images.githubusercontent.com/17763657/71925170-2775a480-3199-11ea-9de8-547d581efaad.png">
<img width="760" alt="Screenshot 2020-01-07 at 21 59 35" src="https://user-images.githubusercontent.com/17763657/71925171-2775a480-3199-11ea-9800-4d05b9528d30.png">
<img width="893" alt="Screenshot 2020-01-07 at 21 59 25" src="https://user-images.githubusercontent.com/17763657/71925174-280e3b00-3199-11ea-8572-b577d88eaa5f.png">
<img width="734" alt="Screenshot 2020-01-07 at 21 58 49" src="https://user-images.githubusercontent.com/17763657/71925176-280e3b00-3199-11ea-97ac-73f74e253b0f.png">

Thank you in advance. Appreciate the effort

I have tried other shows and it works as expected. I think the "." in the name is confusing it.

**Comment by miigotu** [comment]
This should already be fixed on the develop branch

**Comment by jraydoran** [comment]
> This should already be fixed on the develop branch

That is great news. Not sure how long before is goes to the “live” branch. Not serious at all, will wait.

Really appreciate your response and effort!!

**Comment by miigotu** [comment]
Definitely fixed in develop. Will be released to master as soon as more people test it on develop.
