### ISSUE TITLE
unable to start sickchill after update to https://github.com/SickChill/SickChill/commit/6aa548f90be370020a444336a1bf679ad0f0bf5f

### ISSUE THREAD

**Issue by Wally73** [SickChill/SickChill#5829]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop https://github.com/SickChill/SickChill/commit/6aa548f90be370020a444336a1bf679ad0f0bf5f
OS: Windows 
Browser: chrome
What you did: autoupdate
What happened: sickchill doesn't start anymore 
What you expected: to start
Logs:
```
PASTE LOGS HERE
```
https://pastebin.com/nxNgXycP

**Comment by miigotu** [comment]
```DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.1h 5 Jun
 the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3```

**Comment by miigotu** [comment]
Also, what version is your python?

**Comment by Wally73** [comment]
Python Version:2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
  SSL Version:OpenSSL 1.0.1h 5 Jun 2014
  OS:Windows-2008ServerR2-6.1.7601-SP1
  Locale:en_US.cp1252

that ssl thingy is a warning, there are errors in inits

**Comment by miigotu** [comment]
Are you using the SickChill installer? create_default_context was introduced in Python 2.7.9, installer gives 2.7.11 I think.

**Comment by miigotu** [comment]
6 year old Python and openssl aren't very secure

**Comment by Wally73** [comment]
pretty sure i installed it ages ago manually 
latest python 2.7.17 has openssl 1.0.2s i see  so also not good enough

**Comment by miigotu** [comment]
@Wally73 the openssl is fine, you need to update the python. ssl.create_default_context is part of the standard lib in python and it didnt exist until 2.7.9

**Comment by Wally73** [comment]
will try to upgrade python to 2.7.17 and see if that works

**Comment by miigotu** [comment]
Thanks for posting though, I will make it error and close gracefully so its easier to determine the problem.

**Comment by miigotu** [comment]
Let me know if that fix works please, I don't want to get surprised when I release it to master 1000 people post new issues lol

**Comment by Wally73** [comment]
SickChill Info:
Branch: develop
Commit: cea5113e79ca11d588303fe670c21028ae2c5588
Version: v2020.01.03-1
Database Version: 44.1
  Python Version:2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]
  SSL Version:OpenSSL 1.0.2t 10 Sep 2019
  OS:Windows-2008ServerR2-6.1.7601-SP1
  Locale:en_US.cp1252

ok that works (ok that warning about ssl version is still there but at least SickChill works again)
