### ISSUE TITLE
Update docker image with Python 2.7.9

### ISSUE THREAD

**Issue by kretzu77** [SickChill/SickChill#5831]
Hi,

Can you update docker image with Python 2.7.9 please?

Last update (2020-01-08) needs Python 2.7.9 and last docker image has 2.7.16 (default, Mar 7 2019, 23:06:01) [GCC 8.2.0] - 9 months old.

Respect,
Kretzu

**Comment by miigotu** [comment]
2.7.16 is newer than 2.7.9, 2 7 16 vs 2 7 9

**Comment by kretzu77** [comment]
Stupid me :)
Sorry for bother.
