### ISSUE TITLE
[APP SUBMITTED]: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by stuartcastle** [SickChill/SickChill#5832]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@17e379df7dadc7711db1c76695411267f245a961
Link to Log: https://gist.github.com/a07a9820b8b89727ec84757f1f6b3a29
### ERROR
```
CHECKVERSION :: [17e379d] Exception generated in thread CHECKVERSION: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kachikulu** [comment]
### INFO
Python Version: **2.7.18 (default, Aug  3 2020, 18:28:08) [GCC 4.9.4 20150629 (prerelease)]**
Operating System: **Linux-4.4.59+-aarch64-with-glibc2.17**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@99336df163c7e776c7931d864e84d1f0f83afe4d
Link to Log: https://gist.github.com/80adf70149d3e633261bf3ad4e62a994
### ERROR
```
CHECKVERSION :: [99336df] Exception generated in thread CHECKVERSION: argument of type 'NoneType' is not iterable
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by retsu8** [comment]
### INFO
Python Version: **3.7.9 (default, Jan  3 2021, 07:11:34) [GCC 5.5.0]**
Operating System: **Linux-4.19.123-feral-x86_64-with-debian-9.13**
Locale: UTF-8
Branch: **pip**
Commit: SickChill/SickChill@99336df163c7e776c7931d864e84d1f0f83afe4d
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hubdows** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
Link to Log: https://gist.github.com/4f8032a1215bf86695b35dd6eb9e4dd3
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
