### ISSUE TITLE
Jacket error

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#5834]
### Before submitting your issue:

SickChill Info:
Branch: master
Commit: 17e379df7dadc7711db1c76695411267f245a961
Database Version: 44.1
  Python Version:
2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
  SSL Version:
OpenSSL 1.0.2o 27 Mar 2018
  OS:
Windows-7-6.1.7601-SP1
  Locale:
en_US.cp1252

What you did: 
  Let SickChill do it's thing
What happened: 
  It keeps failing as below, I have to manually download the missing episodes that SickChill can't seem to find.

What you expected:  
  That is would work like before

```
08:16:30 INFO::SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
08:19:20 INFO::SEARCHQUEUE-DAILY-SEARCH :: [Jackett] :: Request failed: HTTPConnectionPool(host='192.168.10.75', port=9117): Read timed out. (read timeout=30) (<type 'str'>)
08:19:26 INFO::SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found

```

**Comment by miigotu** [comment]
Looks like your jackett is failing to respond in a full 3 minutes....

**Comment by kretzu77** [comment]
Jackett and Sickchill are on the same machine?
Enter in Jackett and see result of the test button.
If you reinstalled jackett, change API/link in sickchill.

**Comment by miigotu** [comment]
Im not sure if jackett uses tvdb api, but if so that could be the reason. tvdb api is borked atm
