### ISSUE TITLE
Show not found, but exists in thetvdb

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#5841]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Windows 10
Browser: Chrome
What you did: Search for new show (Locke & Key)
What happened: Nothing found
What you expected: Show found ;)
Logs:
```
AA ****-01-10 22:52:15 DEBUG ThreadPoolExecutor-0_3 :: Searching for Show with searchterm(s): ['Locke & Key'] on Indexer: theTVDB
```
The show is here: https://www.thetvdb.com/series/locke-and-key

Tried searching both with "&" and "and". Nothing found. 

Also tried searching for https://www.thetvdb.com/series/ragnarok, but got the same result. Restarted sickchill. Same thing happened. Searched for "Devs" and found it, so it can at least find some of the shows.

Also tried manually adding the directories and search for existing shows.

Tried adding from trakt.tv without any luck.

**Comment by dracupg** [comment]
I have the same issues in the Master branch looking for the show Glee. It works fine in the current Development branch though.
![Screenshot from 2020-01-11 11-12-18](https://user-images.githubusercontent.com/11346330/72194867-a6056700-3463-11ea-89db-1dcadf56c705.png)

**Comment by Tiwas** [comment]
Thanks, @dracupg . Switching branches helped on these two. However, I also searched for some other shows I've had problems with and they came up with "null" as air date. These were not possible to add.

These are the shows I'm still unable to add:
* House of the Dragon
* Kevin Can F--- Himself
* Marvel's Falcon & Winter Soldier
* Snowpiercer
* The Continental

**Comment by m1ckyb** [comment]
Tried searching for Battlestar Galactica, got No results found, try a different search.

Searched with quotes "Battlestar Galactica" it found it, but got this in the log

2020-01-11 12:14:55 SHOWQUEUE-ADD :: Show in /nfs/media/TVEps/Battlestar Galactica (2003) has no name on theTVDB, probably searched with the wrong language. Delete .nfo and add manually in the correct language.

**Comment by Tiwas** [comment]
Just a note if other people switch brances - I got a *lot* of errors, and the log page barely worked. Shut SC down, deleted the logs, and things started working properly again.

**Comment by didyouexpectthat** [comment]
I have a similar issue but with loading content from theTVDB.
```
AA tvdb_attributenotfound: Found 360504, but attribute 'seriesname' was empty.
AA "Found {0}, but attribute 'seriesname' was empty.".format(self.indexerid))
AA File "/apps/sickrage/sickbeard/tv.py", line 856, in loadFromIndexer
AA self.show.loadFromIndexer(cache=not self.force)
AA File "/apps/sickrage/sickbeard/show_queue.py", line 651, in run
AA Traceback (most recent call last):
2020-01-10 20:19:12 ERROR SHOWQUEUE-FORCE-UPDATE :: [17e379d] Data retrieved from theTVDB was incomplete, aborting: Found 360504, but attribute 'seriesname' 
```
I did a full update on show ID 360504; theTVDB has new information and graphics and SickChill is unable to pull them. I am going to wait for the pending code from develop branch to go to master (as per the announcement) and then hopefully all these issues will be fixed.

**Comment by Scythe42** [comment]
Searching when adding news shows currently only work when putting the search term in "", but when adding the show I'll get "Show in XXX has no name on theTVDB, probably searched with the wrong language. Delete .nfo and add manually in the correct language.". I searched in English.

Guess the v1 API is screwed up again on the TVDB side. Tried to switch to develop, which seams to have v3 API support now, but running into timeouts on all searches or even on refreshing existing shows, which works on master.

**Comment by Jelly-Flinger** [comment]
I basically have the same problem for a couple of days now. Unable to add shows, same error messages but I cannot use the existing folder as a work around by treating it as an existing show. 

I don't know how to switch from master to development branch  and see if it resolves. I am running wndows 10. There is an option in the setting to choose a new branch but the drop down only has master branch listed.

**Comment by miigotu** [comment]
Thetvdb is going through big changes, they have gone down and broken different parts of the api manyu times over the past few weeks. For about 24 hours, the api didnt work at all. It just got fixed a few hours ago.

**Comment by whiteazn** [comment]
Woke up this morning to this issue.

Any show I search, comes back with 0 results.  

No matter what I search, no results.

Debug Log doesn't show much, just:
2021-03-01 10:27:06 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with searchterm(s): ['Person of Interest'] on Indexer: theTVDB

I updated to the most recent version:
http://dereferer.org/?https://github.com/SickChill/SickChill/commit/34112a6279de83bb8671246dbf1b1f942d10915b

But updating didn't fix it.  

Windows, Master Branch, DB Version 44.2, Python 3.8.5

**Comment by miigotu** [comment]
https://twitter.com/thetvdb/status/1366428411304939523?s=19

**Comment by brettvitaz** [comment]
I am experiencing this issue. I noticed that if I search for the title lowercased, it has better luck.
