### ISSUE TITLE
INFO SEARCHQUEUE-BACKLOG-77419 :: [NZBGeek] :: Request failed: 500 Server Error: Internal Server Error for url: https://api.nzbgeek.info/api?apikey=**********&tvdbid=77419&season=2&maxage=2500&cat=5030%2C5040&limit=100&t=tvsearch&offset=0&ep=8 ()

### ISSUE THREAD

**Issue by cbinder4** [SickChill/SickChill#5857]
I guess this message is just informational and not an error?  Why is it being generated over and over in my log and how can I fix it?

**Comment by miigotu** [comment]
The error is on nzbgeek, you aren't gonna get any results from them until they fix their api.

**Comment by Wally73** [comment]
disable backlog search on that provider
