### ISSUE TITLE
[APP SUBMITTED]: 'ShowIndexer' object has no attribute 'series_poster_by_id'

### ISSUE THREAD

**Issue by fantastrick** [SickChill/SickChill#5858]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b6fe632f4de93df057e04f2773dfc007574c8f0f
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [b6fe632] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickchill\views\index.py", line 182, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickchill\views\manage\add_shows.py", line 345, in getTrendingShowImage
    image_url = sickchill.indexer.series_poster_by_id(indexerId)
AttributeError: 'ShowIndexer' object has no attribute 'series_poster_by_id'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fantastrick** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b6fe632f4de93df057e04f2773dfc007574c8f0f
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [b6fe632] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickchill\views\index.py", line 182, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickchill\views\manage\add_shows.py", line 345, in getTrendingShowImage
    image_url = sickchill.indexer.series_poster_by_id(indexerId)
AttributeError: 'ShowIndexer' object has no attribute 'series_poster_by_id'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fantastrick** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b6fe632f4de93df057e04f2773dfc007574c8f0f
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [b6fe632] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickchill\views\index.py", line 182, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickchill\views\manage\add_shows.py", line 345, in getTrendingShowImage
    image_url = sickchill.indexer.series_poster_by_id(indexerId)
AttributeError: 'ShowIndexer' object has no attribute 'series_poster_by_id'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fantastrick** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b6fe632f4de93df057e04f2773dfc007574c8f0f
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [b6fe632] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickchill\views\index.py", line 182, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickchill\views\manage\add_shows.py", line 345, in getTrendingShowImage
    image_url = sickchill.indexer.series_poster_by_id(indexerId)
AttributeError: 'ShowIndexer' object has no attribute 'series_poster_by_id'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
You did restart SC after the update right?

**Comment by fantastrick** [comment]
Yes I did!

Rick


________________________________
Van: miigotu <notifications@github.com>
Verzonden: zondag, januari 12, 2020 11:10 AM
Aan: SickChill/SickChill
CC: fantastrick; Author
Onderwerp: Re: [SickChill/SickChill] [APP SUBMITTED]: 'ShowIndexer' object has no attribute 'series_poster_by_id' (#5858)


You did restart SC after the update right?
