### ISSUE TITLE
[APP SUBMITTED]: 'Series' object has no attribute 'title'

### ISSUE THREAD

**Issue by fantastrick** [SickChill/SickChill#5859]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b6fe632f4de93df057e04f2773dfc007574c8f0f
Link to Log: https://gist.github.com/d5421c8c8de8134ad437f021483d75b1
### ERROR
```
SHOWQUEUE-ADD :: [b6fe632] Unable to look up the show in None on theTVDB using ID 360733, not using the NFO. Delete .nfo and try adding manually again.: 'Series' object has no attribute 'title'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fantastrick** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b6fe632f4de93df057e04f2773dfc007574c8f0f
Link to Log: https://gist.github.com/1680714821f4a8eb2e01836c3c1be899
### ERROR
```
SHOWQUEUE-ADD :: [b6fe632] Unable to look up the show in None on theTVDB using ID 362496, not using the NFO. Delete .nfo and try adding manually again.: 'Series' object has no attribute 'title'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
I'll fix the one later, it's on trending shows page right?

**Comment by HazMatt69** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 02 2019, 11:13:20) [GCC 7.4.0]**
Operating System: **Linux-3.4.6-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@b6fe632f4de93df057e04f2773dfc007574c8f0f
Link to Log: https://gist.github.com/168a66636069cc21f2edb5b55d4e77e7
### ERROR
```
SHOWQUEUE-ADD :: [b6fe632] Unable to look up the show in None on theTVDB using ID 361563, not using the NFO. Delete .nfo and try adding manually again.: 'Series' object has no attribute 'title'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
