### ISSUE TITLE
Retrieving poster_thumb seems to fail

### ISSUE THREAD

**Issue by MrHappy** [SickChill/SickChill#5865]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/d195d3ab25ee4525faecba2b2064eaa28b3648b2 
OS: Windows 2019
Browser: Firefox
What you did: force full update
What happened: poster-thumb was not retrieved (tried with both  'Rick and Morty' and 'Giri'Haji'. They both don't update, other images of these series are pulled fine.
What you expected: to see the thumb
Logs:
```
020-01-13 11:50:35 INFO     SHOWQUEUE-REFRESH :: Done cache check
2020-01-13 11:50:35 DEBUG    SHOWQUEUE-REFRESH :: Seeing if we still need an image of type 5: False
2020-01-13 11:50:35 DEBUG    SHOWQUEUE-REFRESH :: Unable to retrieve image to save in e:\_data\sickchill\cache\images\thumbnails\275274.banner.jpg, skipping
2020-01-13 11:50:35 DEBUG    SHOWQUEUE-REFRESH :: Seeing if we still need an image of type 3: True
2020-01-13 11:50:35 DEBUG    SHOWQUEUE-REFRESH :: Unable to retrieve image to save in e:\_data\sickchill\cache\images\thumbnails\275274.poster.jpg, skipping
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Seeing if we still need an image of type 4: True
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Unable to retrieve image to save in e:\_data\sickchill\cache\images\275274.banner.jpg, skipping
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Seeing if we still need an image of type 1: True
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Seeing if we still need an image of type 2: False
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if we can use the show image from the Sony PS3 metadata
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if we can use the show image from the Mede8er metadata
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if we can use the show image from the TIVO metadata
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if we can use the show image from the KODI metadata
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if we can use the show image from the WDTV metadata
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if we can use the show image from the MediaBrowser metadata
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if we can use the show image from the KODI 12+ metadata
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if file e:\_data\sickchill\cache\images\275274.fanart.jpg exists
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if file e:\_data\sickchill\cache\images\thumbnails\275274.banner.jpg exists
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if file e:\_data\sickchill\cache\images\thumbnails\275274.poster.jpg exists
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if file e:\_data\sickchill\cache\images\275274.banner.jpg exists
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if file e:\_data\sickchill\cache\images\275274.poster.jpg exists
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking if we need any cache images for show 275274
2020-01-13 11:50:34 DEBUG    SHOWQUEUE-REFRESH :: Checking & filling cache for show Rick and Morty
2020-01-13 11:50:34 INFO     SHOWQUEUE-REFRESH :: 275274: Updating NFOs for show with new indexer info
```

**Comment by MrHappy** [comment]
Tried to add an other series (Hoogvliegers) and this one works.
Has this got something to do with tvdb or my database?

**Comment by Wally73** [comment]
there is prob not a thumb image on tvdb at the moment so no wonder it fails

**Comment by MrHappy** [comment]
The posters are visible on tvdb, but the links to the posters are different.
I 've tested three, the first one does show a thumb in SickChill the next 2 do not:
https://artworks.thetvdb.com/banners/series/365302/posters/62046632.jpg
https://artworks.thetvdb.com/banners/posters/275274-2.jpg
https://artworks.thetvdb.com/banners/posters/5d74e34f4ed48.jpg

**Comment by BenjV** [comment]
The problem is the Tvdb Api.
At the moment it does not return the banner for any serie via the "image/query "api, but the others (posters and small posters) are available.

@miigotu 
I don't know how you implemented the banner, but the swagger API states that the banner is available via the key the "image/query" api using the subkey "graphical" but in practice that is not the case.
The banner is only available directly from the "search/serie" api in the json (called "banner").

**Comment by miigotu** [comment]
@BenjV the banner is available on the series/image api endpoint:
This show doesnt have one on tvdb:
```python
>>> import tvdbsimple
>>> tvdbsimple.keys.API_KEY = 'F9C450E78D99172E'
>>> si = tvdbsimple.Series_Images
>>> i = si('365302', 'en', keyType='series')
>>> im = i.all()
HTTPError: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/365302/images/query?keyType=series

>>> s = tvdbsimple.Series('365302', 'en')
>>> s.info()['banner']
u''
```
This one does:
```python

>>> i = si('257655', 'en', keyType='series')
>>> im = i.all()
>>> im[0]['fileName']
u'graphical/257655-g2.jpg'
>>> im[0]['thumbnail']
u'graphical/257655-g2_t.jpg'
>>> s = tvdbsimple.Series('257655', 'en')
>>> s.info()['banner']
u'graphical/257655-g.jpg
```

Poster and Poster Thumb for Arrow:
```
>>> i = si('257655', 'en', keyType='poster')
>>> im = i.all()
>>> im[0]['thumbnail']
u'posters/257655-2_t.jpg'
>>> im[0]['fileName']
u'posters/257655-2.jpg'
```

The hoogliegers that was asked above:
```
>>> i = si('365302', 'en', keyType='poster')
>>> im = i.all()
>>> im[0]['fileName']
u'series/365302/posters/62036307.jpg'
>>> im[0]['thumbnail']
u'series/365302/posters/62036307_t.jpg'
```

**Comment by miigotu** [comment]
@MrHappy Im not sure why you are getting errors unless the fixed something in the api between your post and now:
```python
>>> i = si('275274', 'en', keyType='poster')
>>> im = i.all()[0]
>>> im['fileName']
u'posters/275274-1.jpg'
>>> im['thumbnail']
u'posters/275274-1_t.jpg'
>>> i = si('275274', 'en', keyType='series')
>>> im = i.all()[0]
>>> im['thumbnail']
u'graphical/275274-g_t.jpg'
>>> im['fileName']
u'graphical/275274-g.jpg
```

**Comment by miigotu** [comment]
The only thing missing for that show is the season banners

**Comment by miigotu** [comment]
Just gonna put this here, I've tested the code for all possible images I need. Soon I will add unittests to verify that it doesnt get broken later

```python
>>> arrow = Show(257655)
>>> arrow
<Show object at 0x7f3852141750>
>>> arrow.indexerid
257655
>>> arrow.lang
'en'
>>> api[1].season_poster_url(arrow, 2)
u'https://artworks.thetvdb.com/banners/seasons/257655-2-3.jpg'
>>> api[1].season_poster_url(arrow, 2, True)
u'https://artworks.thetvdb.com/banners/seasons/257655-2-3_t.jpg'
>>> api[1].season_banner_url(arrow, 2, True)
u'https://artworks.thetvdb.com/banners/seasonswide/257655-2_t.jpg'
>>> api[1].season_banner_url(arrow, 2, False)
u'https://artworks.thetvdb.com/banners/seasonswide/257655-2.jpg'
>>> api[1].series_fanart_url(arrow, False)
u'https://artworks.thetvdb.com/banners/fanart/original/257655-3.jpg'
>>> api[1].series_fanart_url(arrow, True)
u'https://artworks.thetvdb.com/banners/fanart/original/257655-3_t.jpg'
>>> api[1].series_banner_url(arrow, True)
u'https://artworks.thetvdb.com/banners/graphical/257655-g2_t.jpg'
>>> api[1].series_banner_url(arrow, False)
u'https://artworks.thetvdb.com/banners/graphical/257655-g2.jpg'
>>> api[1].series_poster_url(arrow, False)
u'https://artworks.thetvdb.com/banners/posters/257655-2.jpg'
>>> api[1].series_poster_url(arrow, True)
u'https://artworks.thetvdb.com/banners/posters/257655-2_t.jpg'
>>> arrow.dvdorder = False
>>> e = api[1].episode(arrow, 1, 1)
>>> e['filename']
u'episodes/257655/4325893.jpg'
>>> api[1].complete_image_url(e['filename'])
u'https://artworks.thetvdb.com/banners/episodes/257655/4325893.jpg'
>>> e.keys()
[u'seriesId', u'airsAfterSeason', u'dvdEpisodeNumber', u'productionCode', u'overview', u'airedSeasonID', u'thumbAdded', u'episodeName', u'airedSeason', u'airsBeforeSeason', u'showUrl', u'id', u'dvdDiscid', u'contentRating', u'filename', u'dvdSeason', u'writers', u'airedEpisodeNumber', u'absoluteNumber', u'thumbHeight', u'isMovie', u'imdbId', u'lastUpdated', u'airsBeforeEpisode', u'lastUpdatedBy', u'dvdChapter', u'language', u'thumbAuthor', u'siteRatingCount', u'directors', u'firstAired', u'guestStars', u'siteRating', u'thumbWidth']
>>> arrow.dvdorder = True
>>> e = api[1].episode(arrow, 1, 1)
>>> api[1].complete_image_url(e['filename'])
u'https://artworks.thetvdb.com/banners/episodes/257655/4325893.jpg'
```

**Comment by MrHappy** [comment]
If I select debuglogging I get the following messages when I do a full update of a serie:

> 2020-01-13 11:34:44 DEBUG    SHOWQUEUE-REFRESH :: Unable to retrieve image to save in e:\_data\sickchill\cache\images\thumbnails\364388.banner.jpg, skipping
> 2020-01-13 11:34:43 DEBUG    SHOWQUEUE-REFRESH :: Unable to retrieve image to save in e:\_data\sickchill\cache\images\thumbnails\364388.poster.jpg, skipping
> 2020-01-13 11:34:43 DEBUG    SHOWQUEUE-REFRESH :: Unable to retrieve image to save in e:\_data\sickchill\cache\images\364388.banner.jpg, skipping
> 2020-01-13 11:34:42 DEBUG    SHOWQUEUE-REFRESH :: Unable to retrieve image to save in e:\_data\sickchill\cache\images\364388.poster.jpg, skipping
> 2020-01-13 11:34:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if file e:\_data\sickchill\cache\images\364388.fanart.jpg exists
> 2020-01-13 11:34:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if file e:\_data\sickchill\cache\images\thumbnails\364388.banner.jpg exists
> 2020-01-13 11:34:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if file e:\_data\sickchill\cache\images\thumbnails\364388.poster.jpg exists
> 2020-01-13 11:34:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if file e:\_data\sickchill\cache\images\364388.banner.jpg exists
> 2020-01-13 11:34:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if file e:\_data\sickchill\cache\images\364388.poster.jpg exists
> 2020-01-13 11:34:42 DEBUG    SHOWQUEUE-REFRESH :: Checking if we need any cache images for show 364388
> 2020-01-13 11:34:42 INFO     SHOWQUEUE-REFRESH :: 364388: Updating NFOs for show with new indexer info
> 2020-01-13 11:34:42 DEBUG    SHOWQUEUE-REFRESH :: 364388: Writing NFOs for all episodes
> 2020-01-13 11:34:42 DEBUG    SHOWQUEUE-REFRESH :: 364388: Writing NFOs for show
> 2020-01-13 11:34:42 DEBUG    SHOWQUEUE-REFRESH :: 364388: Loading all episodes with a location from the database
It doesn't say why it can't retrieve...

**Comment by miigotu** [comment]
Some images are missing for some shows. The code is working, sometimes either tvdb doesn't have one, or isn't retuning it via API. I'm sure if you look at your shows you have them.
