### ISSUE TITLE
Show has no name on theTVDB, searched wrong language?

### ISSUE THREAD

**Issue by cbinder4** [SickChill/SickChill#5868]
Seeing this warning on couple of shows as well.  I don't have an .NFO file in the folders to delete so didn't know if this is possibly something with the API still not working right or not?

> WARNING SHOWQUEUE-ADD :: Show in E:\Valhalla has no name on theTVDB, probably searched with the wrong language. Delete .nfo and add manually in the correct language.

**Comment by BenjV** [comment]
I tried the Api directly and it found the serie just fine.
In SickChill I got the same error as you did.
To get around this you can choose "Nederlands" in the "Add Show" page for this serie.

**Comment by ethoscraig** [comment]
Getting the same issue, although with a slightly different message in logs for about a dozen shows at the moment. If you check TVDB the episodes do have titles, but sickchill is not able to retrieve them.

Here is an example of the log - 
2020-01-16 20:32:13 INFO SHOWQUEUE-FORCE-UPDATE :: This episode Natsunagu! - S01E02 has no name on theTVDB. Setting to an empty string

**Comment by miigotu** [comment]
It finds the series fine, but the `seriesName` attribute is empty. Using nederlands returns a title for the show
