### ISSUE TITLE
Episode name not being retrieved from TVDB

### ISSUE THREAD

**Issue by ethoscraig** [SickChill/SickChill#5873]
On latest version from git v2020.01.14-2, this issue has been happening for the past week and I have been keeping on the lastest version from the master branch, to see if this issue resolves. 

Episode names are not being retrieved for around a dozen shows currently. The episode names are just set to "None" in the webui. 

The file names for the downloaded shows don't have anything either. 
For example: Rebirth - 001 -.mkv which should for example be Rebirth - 001 - Episode 1.mkv
This is also causing the shows not to show up in Kodi

I have checked TVDB and the episodes do have titles, but sickchill is not able to retrieve them.

Here is an example of the log -
2020-01-16 20:32:13 INFO SHOWQUEUE-FORCE-UPDATE :: This episode Natsunagu! - S01E02 has no name on theTVDB. Setting to an empty string

Another strange factor to this is that for some shows it has came across this error, and the next day the episode name information has retrieved correctly. When on TVDB the information has been there the entire time.

**Comment by miigotu** [comment]
We use their new api, and they have some bugs to work out. It has been working off and on because they keep changing it and breaking it, I have no control over that. I'm sure their api will stop being broken eventually 🙏
