### ISSUE TITLE
Request failed: 403 Client Error: Forbidden for url: https://iptorrents.eu/t

### ISSUE THREAD

**Issue by hooligeek** [SickChill/SickChill#5875]
### Before submitting your issue:

Branch/Commit: Master/4dedd01fc6d57622442113f66d180c21f4eaff8c
OS: Windows Server 2012 R2
Browser: Chrome
What you did: I manually browsed to iptorrents.eu and grabbed the cookie from there but the issue remains.  Also the fact that I'm even able to browse the site suggests this is not and ISP related issue.
What happened: Since the last update iptorrents.eu is unreachable
What you expected: I guess I though sickchill would use .com based on my locale
Logs:
```
2020-01-16 07:02:10 INFO SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Request failed: 403 Client Error: Forbidden for url: https://iptorrents.eu/t?73=&60=&q=&qf=#torrents ()
```

Thanks

**Comment by miigotu** [comment]
You need the cookie and the username/password

**Comment by hooligeek** [comment]
Ok I'll double check that.  Is that new? This was working previously.

I'll update when this is resolved.

**Comment by hooligeek** [comment]
I updated the username/password for the provider but it still fails.

Do I need the whole cookie header or just 'uid=1234;pass=567845439634987'?

**Comment by hooligeek** [comment]
proxying through Jacket works with the cookie header from ipt.

**Comment by hooligeek** [comment]
alright.  grabbed the cookie again from the .eu site, restarted sickchill and forced a backlog search.  This appears be resolved but will monitor it for the day.  thanks for assist.
