### ISSUE TITLE
Install SickChill on a raspberry

### ISSUE THREAD

**Issue by etienne954** [SickChill/SickChill#5877]
Hi everyone,

Does anyone knows why the links for SickChill's installation guide dedicated to Raspberry pi brings us to SickRage installation guide ? I'm talking about those two links in SickChill's Wiki :
    http://www.htpcguides.com/install-sickrage-raspberry-pi-usenet-torrent-tv/
    http://www.algissalys.com/how-to/sickrage-sabnzbd-raspberry-pi-tvpi-part-2
Do we have to install Sickrage to actually install SickChill ? Is there a specific procedure available to install SickChill on a raspberry pi ?

Thank you very much in advance for your answer and your support.

**Comment by miigotu** [comment]
They just haven't updated their guide. Replace SickRage with SickChill everywhere in that guide

**Comment by miigotu** [comment]
I sent an email to both site admins, to see if they can update the guides and/or send me a new link.

**Comment by etienne954** [comment]
> 
> 
> They just haven't updated their guide. Replace SickRage with SickChill everywhere in that guide

Hi @miigotu ,

Thank you very much for your answer. Do we have to replace SickRage with SickChill in the command line ?
Like `sudo git clone https://github.com/SickRage/SickRage.git /opt/sickrage`becomes `sudo git clone https://github.com/SickChill/SickChill.git /opt/sickchill` and `python /opt/sickrage/SickBeard.py` becomes `python /opt/sickchill/SickBeard.py`?

I'm gonna try and give my feedback.
Thanks again

**Comment by miigotu** [comment]
@etienne954 absolutely everywhere you see SickRage->SickChill and sickrage->sickchill, even the commands

**Comment by etienne954** [comment]
I followed this procedure :
https://www.htpcguides.com/install-sickrage-raspberry-pi-usenet-torrent-tv/

As well as replacing all sickrage with sickchill, I've replaced user `pi `by my user name which is ... `xbian`

At the very end, I get this
```
xbian@xbian ~ $ sudo service sickchill start
Starting SickBeard
start-stop-daemon: user 'sickbeard' not found
```
Nothing is available on port 8081 yet. Would you know where this user `sickbeard` is defined ?
I thought maybe replacing `xbian` with `sickbeard `in sickchill default file could solve this issue but no. 

```
SR_USER=**xbian**
SR_HOME=/opt/sickchill
SR_DATA=/opt/sickchill
SR_PIDFILE=/home/xbian/.sickchill.pid
```

**Comment by miigotu** [comment]
@etienne954 looks like your service scripts are still messed up. `sudo cp /opt/sickchill/runscripts/init.ubuntu /etc/init.d/sickchill`

**Comment by etienne954** [comment]
Yep, everything is ok now. Thank you very much miigotu for your support. Really appreciated :)

**Comment by etienne954** [comment]
Updated procedure to install Sickchill on a raspberry Pi 4 with OSMC, available here : [https://github.com/SickChill/sickchill/discussions/8171#discussioncomment-3755877]
