### ISSUE TITLE
Error with theTVDB, not creating episode list: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/...

### ISSUE THREAD

**Issue by cbinder4** [SickChill/SickChill#5879]
Don't think the fix for shows with no episodes is working because now I'm getting this -

2020-01-16 12:35:12 INFO SHOWQUEUE-ADD :: 356422: Updating NFOs for show with new indexer info
AA HTTPError: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/356422/episodes?page=1
AA raise HTTPError(http_error_msg, response=self)
AA File "C:\SickRage\SickRage\lib\requests\models.py", line 940, in raise_for_status
AA response.raise_for_status()
AA File "C:\SickRage\SickRage\lib\tvdbsimple\base.py", line 146, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "C:\SickRage\SickRage\lib\tvdbsimple\base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "C:\SickRage\SickRage\lib\tvdbsimple\base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "C:\SickRage\SickRage\lib\tvdbsimple\series.py", line 244, in page
AA self.page(1)
AA File "C:\SickRage\SickRage\lib\tvdbsimple\series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "C:\SickRage\SickRage\lib\tvdbsimple\series.py", line 222, in all
AA for series_episode in showObj.Episodes.all():
AA File "C:\SickRage\SickRage\sickbeard\tv.py", line 527, in loadEpisodesFromIndexer
AA self.show.loadEpisodesFromIndexer()
AA File "C:\SickRage\SickRage\sickbeard\show_queue.py", line 477, in run
AA HTTPError: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/356422/episodes?page=1
AA raise HTTPError(http_error_msg, response=self)
AA File "C:\SickRage\SickRage\lib\requests\models.py", line 940, in raise_for_status
AA response.raise_for_status()
AA File "C:\SickRage\SickRage\lib\tvdbsimple\base.py", line 146, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "C:\SickRage\SickRage\lib\tvdbsimple\base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "C:\SickRage\SickRage\lib\tvdbsimple\base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "C:\SickRage\SickRage\lib\tvdbsimple\series.py", line 244, in page
AA self.page(1)
AA File "C:\SickRage\SickRage\lib\tvdbsimple\series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "C:\SickRage\SickRage\lib\tvdbsimple\series.py", line 222, in all
AA for series_episode in showObj.Episodes.all():
AA File "C:\SickRage\SickRage\sickbeard\tv.py", line 527, in loadEpisodesFromIndexer
AA self.show.loadEpisodesFromIndexer()
AA File "C:\SickRage\SickRage\sickbeard\show_queue.py", line 477, in run
AA Traceback (most recent call last):
2020-01-16 12:35:11 ERROR SHOWQUEUE-ADD :: [4dedd01] Error with theTVDB, not creating episode list: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/356422/episodes?page=1
2020-01-16 12:35:09 INFO SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2020-01-16 12:35:09 INFO SHOWQUEUE-ADD :: 356422: Unable to find the show in the database
2020-01-16 12:35:08 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: E:\Dark Cargo

SickChill Info:
Branch: master
Commit: 4dedd01fc6d57622442113f66d180c21f4eaff8c
Version: v2020.01.14-2
Database Version: 44.1
  Python Version:2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
  SSL Version:OpenSSL 1.0.2a 19 Mar 2015
  OS:Windows-8-6.2.9200
  Locale:en_US.cp1252

**Comment by miigotu** [comment]
Tvdb screwing up their api again ^

**Comment by miigotu** [comment]
This is another place it hit an error, ill see if I can fix it

**Comment by cbinder4** [comment]
Thank you!
