### ISSUE TITLE
[Feature Request] qBittorrent "snatched" status improvement

### ISSUE THREAD

**Issue by sumarimike** [SickChill/SickChill#5881]
I've been playing around with the way SickChill reports a torrent as "snatched" with qBittorrent, and have a potential improvement for consideration.

Currently in SickChill\sickbeard\clients\qbittorrent.py, there's a line (163 in the _verify_added function):
`if self.response.json()['piece_size'] != -1:`

This looks for pieces of a torrent to be in qBittorrent so SickChill can report it as "snatched". What I am finding is that qBittorrent can be lazy in actually downloading content, so after a few tries (specified as 10 in the same code), SickChill sees it as not snatched. However, the torrent usually HAS been caught by qBittorrent but is in a "downloading metadata" state with 0 pieces. So, eventually it starts to download the original file. However, Sick Chill later on will attempt to search for the torrent again because it thinks it was never snatched in the first place. And the cycle continues - with 'piece_size' you can end up with numerous downloads of the same or similar torrents and it's never quite "snatched" right unless you get lucky.

I found that changing that line to this:
`if self.response.json()['addition_date'] != -1:`
seems to work every time. Using the property "addition_date" seems more accurate because for qBittorrent, the torrent is added immediately before it starts the process of finding pieces of the torrent. SickChill then sees it as received by the client and marks it as Snatched. it's worked very well so far for me. Naturally you may still have a dead torrent, but at least you don't have multitudes of them over time.

So I recommend and request changing that line in qbittorrent.py to use the 'addition_date' property instead of 'piece_size'.

Kind regards,
Michael 
Ref: #5016 #4385

**Comment by miigotu** [comment]
To preserve credit for the change, you could create a pull request to the develop branch with this change in both qbittorrent clients. Otherwise, I will make the PR later.

**Comment by sumarimike** [comment]
I've got several hours before I can do this and it'd be my first PR. I'll come back here and comment if I get to do it, but if you have the opportunity before that, go for it. I'm glad to have contributed improvement regardless of who posts it.
