### ISSUE TITLE
Episodes marked as skipped are marked as wanted after a full force update (or auto update of sickchill)

### ISSUE THREAD

**Issue by Ventje23** [SickChill/SickChill#5882]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / a39f879895fcfffd97951a5be6ed256949fd5275
OS: Synology DSM
Browser: Chrome
What you did: Sickchill automatically updated some series and they are now marked as wanted. Before they were marked e.g. as skipped or snatched. Also after a full force update the status is updated [wrongly] (i.e. from skipped / snatched etc. switched to status wanted)/
What happened: episodes marked as skipped/snatched are now marked as wanted. More series have this issue after an automotic update by Sickchill
What you expected: episodes marked as for instance snatched or skipped stay marked as snatched or skipped after a automatic update by Sickchill or a full force update by the user.
Logs:
```
PASTE LOGS HERE
```

**Comment by inamak** [comment]
I am also having this issue - lots of old episodes being changed to wanted

**Comment by miigotu** [comment]
This happens when tvdb is breaking their api, SC deletes the episodes from the db, then adds them back

**Comment by Numiah** [comment]
I ran into the same thing resulting in a massive (really massive) download. 
Not quite wanted.

**Comment by miigotu** [comment]
@Numiah it shouldn't be doing it anymore with the latest update. If your episode exists it won't delete itself when tvdb fails.

**Comment by Numiah** [comment]
Today it happened again :/
100Gb of data down the drain 💯 
Not sure why this happened though since I am not behind on commits.

**Comment by miigotu** [comment]
If SC deletes something from the DB, it doesn't delete it from disk...
