### ISSUE TITLE
Found issue in the logs

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#5888]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

 SickChill Info:
Branch: master
Commit: a39f879895fcfffd97951a5be6ed256949fd5275
Database Version: 44.1
  Python Version:
2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
  SSL Version:
OpenSSL 1.0.2o 27 Mar 2018
  OS:
Windows-7-6.1.7601-SP1
  Locale:
en_US.cp1252

What you did:   nothing
What happened:  it's doing a show queue refresh
What you expected:  not what is in the logs,  been working for a very long time, first time I've seen that message.  check the dates.....

Logs:
```
2020-01-17 03:40:19 SHOWQUEUE-REFRESH :: Unable to find episode with date 2069-01-17 for show Looney Tunes, skipping
```

**Comment by miigotu** [comment]
@nydave69 ill have to think about how to handle this. I'm pretty sure the date was provided in the file as `01-17-69` and it is assuming that means 2069 rather than 1969.

**Comment by nydave69** [comment]
Yep...  most likely..  since it didn't specify what episode...
