### ISSUE TITLE
Question:  Time to update yet, or wait a bit still

### ISSUE THREAD

**Issue by ulrick65** [SickChill/SickChill#5892]
Just curious @miigotu , you mentioned a few days ago to maybe wait and see how the update to master goes...I took that advice and have been waiting.  I am not adding new shows and things see to be going OK at the moment, but I am 34 commits behind.  With all the issues I see being listed here, just want some input from you (or anyone for that matter).  OK to update now, or wait a bit longer for other fixes?

Thanks for all the hard work...very much appreciated.

**Comment by miigotu** [comment]
It should be fine to update. Occasionally we have small issues reported for the new api that are not harmful, but most are still `seriesname` ones from the old API.

**Comment by BenjV** [comment]
I am running the version with the new tvbd api from the beginning and so far no serious problem occurs.
A few issues with the api not returning the correct info but that can only to be fixed at tvdb site and the same but worse is happening with the old tvdb api.

**Comment by miigotu** [comment]
I just wish tvdb would stop editing their api in production, without peer testing 🤔 At least that's what it seems like.

Hopefully the kinks get worked out without much more hiccups

**Comment by BenjV** [comment]
Did you see any change in their api interface?

I think it is more the case that their database en their internal connection from the api to the database is not stable anymore
This started when they upgraded their site and migrated internally to api v3.
And I guess that their V1 api is implemented internally using the V2/V3 api so the problem with the V1 api are doubled.

**Comment by ulrick65** [comment]
Thanks...updating now.  Appreciate it!
