### ISSUE TITLE
No connection between SickChill and Transmission 

### ISSUE THREAD

**Issue by etienne954** [SickChill/SickChill#5893]
Hi everyone

I'm facing a strange behaviour with SickChill.
I just install SickChill and the connection between SickChill and Transmission is not working.
I don't thing the issue comes from Transmission because the same connection is up and running with couchpotato. Also, Transmission is accessible through my web browser.

localhost:9091/, user name and password are correctly set in SickChill.
I'm on a Raspberry Pi 2, running the latest Xbian Stretch.

When a click on "Test Connection" button, SickChill gives this message : **[Errno 404] Not Found**

Is there any port to activate or something like this ?

Many thanks in advance for your support.

**Comment by miigotu** [comment]
Try adding the http://

Transmission works fine here

**Comment by miigotu** [comment]
![Screenshot_20200118-072420](https://user-images.githubusercontent.com/390379/72663721-a8b40f00-39c3-11ea-8d0b-51ae5c70ad35.png)

**Comment by BenjV** [comment]
Do you have a firewall active that is preventing Sickchill to reach transmission?

**Comment by etienne954** [comment]
Hi guys,

Sorry for the delay. No, no firewall, and I tried HTTP:// but same result.
I continue the investigation but I don't know what's wrong so far.

Thank you all for your answers.

**Comment by etienne954** [comment]
I've everything configured as on the screenshot with my Localhost:9091. What is strange is that the connection is working on couchpotato. 
![SickChill](https://user-images.githubusercontent.com/59967365/72910739-42b7e680-3d39-11ea-94b5-2afdffc090da.jpg)
![Couchpotato](https://user-images.githubusercontent.com/59967365/72910740-42b7e680-3d39-11ea-811e-7de6029b5920.jpg)

**Comment by etienne954** [comment]
Same kind of issue occured in the past.
https://github.com/SickChill/SickChill/issues/5166
But no solution found at that time either.
Anyone with has an idea ?

**Comment by miigotu** [comment]
`transmission` in the rpc url box?

**Comment by miigotu** [comment]
In couchpotato, enable advanced toggle and see the full settings there ^

**Comment by etienne954** [comment]
> 
> 
> `transmission` in the rpc url box?

Yes. On base configuration, I just have `transmission` in this section. I tried to modify has indicated in #5166 but it doesn't make sense because I don't have /transmission/web/rpc directory.



> 
> 
> In couchpotato, enable advanced toggle and see the full settings there ^

Advanced Toggle is enable in couchpotato : 
![couchpotato](https://user-images.githubusercontent.com/59967365/72913672-ca9fef80-3d3d-11ea-96e2-38ab86511b9f.png)

**Comment by miigotu** [comment]
Try the local ip, instead of localhost

**Comment by miigotu** [comment]
`transmission/web/rpc` isn't a directory, it's an endpoint.

**Comment by BenjV** [comment]
I don't know if it is just a typo on this forum but localhost cannot be written with a capital L it should be localhost

**Comment by miigotu** [comment]
If anything, you can download transmission remote on your phone and check the connection to transmissionwith that, we connect the same way. Also, I hope this is transmission daemon and not the standalone because I think we only support the daemon

**Comment by etienne954** [comment]
Thank you very much.
I've tried with the real IP@ and localhost is not written with capital L in SickChill.
It is transmission deamon, running on the latest xbian stretch.
![xbian](https://user-images.githubusercontent.com/59967365/72987388-96363d00-3dea-11ea-8ca6-6ba9e162360a.png)
I can access to transmission through my phone is well, I've checked it.
I'll try to reinstall everything from scratch and see what happen. I don't see any other way to solve this for now.

**Comment by BenjV** [comment]
Is the user under which SickChill is installed and runs the same as under which the Transmission deamon is running.
Because it must be a right issue if you can cannot with your browser to Transmission and SickChill cannot.

**Comment by miigotu** [comment]
Maybe you are using a VPN that is setting firewall rules to block from localhost? VPN made my life hell when I set it up, but I have it working good now after tons of custom tweaking

**Comment by etienne954** [comment]
Reinstallation did solve the issue.
Thank you very much @miigotu and @BenjV for your support. 👍
