### ISSUE TITLE
Sorry, requires Python at least 2.7.9 but less than 3

### ISSUE THREAD

**Issue by binbashblog** [SickChill/SickChill#5894]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: latest
OS: centos 7
Browser:
What you did: update sickchill
What happened: sickchill won't start
What you expected: sickchil to start
Logs:
```
PASTE LOGS HERE
```
Manually running sickbeard.py gives the following error:

```
# ./SickBeard.py
Sorry, requires Python at least 2.7.9 but less than 3
```

```
# python --version
Python 2.7.5
```

Sickchill has been working well for a long time before I applied the recent update. There isn't a newer python in centos7. Touching python in centos7 will break centos as it depends on python.

**Comment by Wally73** [comment]
you need to upgrade your python version to 2.7.17
https://www.python.org/downloads/release/python-2717/

**Comment by BenjV** [comment]
https://tecadmin.net/install-python-2-7-on-centos-rhel/

**Comment by miigotu** [comment]
Really would recommend updating to new python, but it isnt 100% necessary if I change the code a bit more. I want to try and improve it some.

**Comment by identd113** [comment]
Use virtual environment if you worried that a newer version will break the OS

**Comment by BenjV** [comment]
Every python 2 version is backwards compatible, so an upgrade from 2.7.5 to 2.7.16 won't break anything.
No need to spend time on it in my opinion.

**Comment by binbashblog** [comment]
It will and does break on Centos 7 and Python2.7 is EOL as of 1st Jan 2020, so Python3 should probably be used instead in future anyway as most distro's have it.

Anyway this is how I resolved it for anyone else experiencing this:

`yum install wget sqlite-devel gcc openssl-devel bzip2-devel -y`
`cd /usr/src && wget https://www.python.org/ftp/python/2.7.17/Python-2.7.17.tgz && tar xzf Python-2.7.17.tgz && cd Python-2.7.16`
`./configure --enable-optimizations --enable-loadable-sqlite-extensions && make altinstall` < This is the important bit as by default sqlite isn't compiled and altinstall will not touch the existing python
`python2.7 -m ensurepip`

Runs fine for now.

**Comment by miigotu** [comment]
There is no functional difference between 2.7.5 and 2.7.16, it wouldnt break anything, but glad you got it working. I did allow lower versions of python, but 2.7.9 is required for ssl to work correctly.
