### ISSUE TITLE
SSL Error when trying to add a Show

### ISSUE THREAD

**Issue by pjrettin** [SickChill/SickChill#5895]
What you did:
1. Upgraded Sickchill to latest version (that required newer version of Python)
2. Compiled from source python 2.7.9
3. Started Sickchill.
4.  Went to add a show and see these errors in log:

Logs:
```
SSLError: HTTPSConnectionPool(host='api.thetvdb.com', port=443): Max retries exceeded with url: /login (Caused by SSLError(CertificateError("hostname 'api.thetvdb.com' doesn't match either of 'ssl418142.cloudflaressl.com', '*.ccccareers.com', 'ccccareers.com'",),))
```

**Comment by ThrustVector** [comment]
Got the same issue.
Latest Sickchill version (v2020.01.17-1)
Python 2.7.13
OpenSSL 1.10l

**Comment by miigotu** [comment]
lol idk what they are doing that their certs are matching a carpentry site, but this was on thetvdb's end.
