### ISSUE TITLE
Feature request: Free unrar alternative Unarchiver (unar, lsar)

### ISSUE THREAD

**Issue by CYBERDEViLNL** [SickChill/SickChill#5897]
It would be nice to have a alternative to the non-free unrar solution. I've been working on a simple Python wrapper for the tools unar and lsar. I haven't looked at the SickChill code yet, so I don't know how to implement this (yet). Maybe someone that does would like to help? Else I will do it myself over-time, but this can take a while since I have more projects to work on :-)

pyUnarchiver code: https://notabug.org/cyberdevil/pyUnarchiver

**Comment by Wally73** [comment]
the unrar part from rarlabs is freeware (both the windows dll and the unrar binary for deb/ubuntu)

**Comment by miigotu** [comment]
Yeah, I'm not sure what is important about this other than not supporting software that isn't open source. It doesn't cost anything to use non-free

**Comment by CYBERDEViLNL** [comment]
Yeah for me it's exactly that; I don't want to run any proprietary software. I have chosen my hardware for that. In the current situation I will have to enable the non-free repo of the distro I'm using if I want to extract archives; don't want to do that.

**Comment by miigotu** [comment]
I'll take a look at it, but it needs to be completely compatible with the non-free archives, and split rars.

**Comment by BenjV** [comment]
This is just nonsense.

Unrar is completely free to be used and even bundled with most Linux distributions.
The public license permits its use to produce software capable of unpacking, but not creating, RAR archives, without having to pay a fee.
So for compressing you must pay a fee but uncompressing is free.

Unrar is as free as pyUnarchiever (just like programs as 7Zip, RarZilla, PeaZip etc etc)

**Comment by nhorvath** [comment]
> This is just nonsense.
> 
> Unrar is completely free to be used and even bundled with most Linux distributions.
> The public license permits its use to produce software capable of unpacking, but not creating, RAR archives, without having to pay a fee.
> So for compressing you must pay a fee but uncompressing is free.
> 
> Unrar is as free as pyUnarchiever (just like programs as 7Zip, RarZilla, PeaZip etc etc)

He means that unrar is not free (libre) it's only free (beer). He has made a personal choice to only run free (libre) software. 

That said, you'd probably do better to just use a shell script wrapper to accomplish this since the command line arguments are not likely to match up even if it's feature compatible.

**Comment by miigotu** [comment]
Unarchiver isn't libre either.

**Comment by nhorvath** [comment]
> Unarchiver isn't libre either.

You appear to be correct. While the premise makes sense, it appears his proposed alternative doesn't fit it. And I'm not sure if anything does.

**Comment by miigotu** [comment]
The only solution I think is debian unrar (the free/libre) version. It just doesn't work with the unrar lib we use and a working one is not available.

We try to use libraries for as many functionalities as we can.

**Comment by nhorvath** [comment]
Oh that explains why sickchill can never unrar things for me. (I use
debian). I just have a cron job that unrars all the directories in my
torrent folder then drops a file there so I know it's done..

**Comment by CYBERDEViLNL** [comment]
Thanks to everyone that took/takes this seriously! :-)

____

@nhorvath

> He means that unrar is not free (libre) it's only free (beer). He has made a personal choice to only run free (libre) software.

Yes that's right!

> That said, you'd probably do better to just use a shell script wrapper to accomplish this since the command line arguments are not likely to match up even if it's feature compatible.

You mean create a shell script that matches the cli arguments of the non-free unrar? That actually isn't a bad idea.

___

@miigotu

> Unarchiver isn't libre either.

Hmm well I think it is: https://github.com/incbee/Unarchiver/blob/master/License.txt

Very libre strict distro's like Trisquel and Parabola also have the `unarchiver` package which provide `unar` and `lsar`.

> The only solution I think is debian unrar (the free/libre) version. It just doesn't work with the unrar lib we use and a working one is not available.

Yeah the `unrar-free` from Debian isn't maintained anymore as far as I know; that's why I looked into a alternative.

**Comment by nhorvath** [comment]
That license you linked is definitely LGPL so it's free/libre. When @miigotu said it wasn't I also googled it and found some thing that agreed with him. I think maybe there's two software products called the Unarchiver maybe? Regardless, I think an adapter shell script is the most expediant way to get this done.

Perhaps @miigotu could add a config that defaults to the path of unrar so it can be configured to point to a replacement.
