### ISSUE TITLE
Issue with the icon size of the Trakt link on the show page

### ISSUE THREAD

**Issue by defhead** [SickChill/SickChill#5899]
@miigotu You merged my PR #5896 after you updated the CSS file.

I applied on my SickChill your modification and here is what it's showing:
![image](https://user-images.githubusercontent.com/24367728/72680834-b7332100-3abe-11ea-9173-eaf121192eac.png)

It's because the file you're using has icons of 32x32px (-ish) while the others icons (imdb, tvdb) come from 16px_sprite_colored_show.png file.

What do you think? Should it's be left as it (personally I don't mind) or should it be fixed?

**Comment by miigotu** [comment]
That icon is 16x16, the css sizes it

**Comment by defhead** [comment]
Wait... :) Which icon you're talking about?

I know that the CSS set every "displayshow-icon-*" class to 16x16, but the image file you're using is a 200x32px (and it's cut -38px to start on the trakt icon).

Right now what it's doing, it's showing a quarter of the trakt icon (top left corner of the icon).
Can we fix it so it show the whole icon?

**Comment by miigotu** [comment]
ahaha i see what you mean now, ill see if i can scale it
