### ISSUE TITLE
[APP SUBMITTED]: global name 'indqexer_id' is not defined

### ISSUE THREAD

**Issue by kentromox** [SickChill/SickChill#5900]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.94-Unraid-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@a6400cf7d8c459d64bfa73dad082241f39a381a8
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [a6400cf] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickchill/sickchill/views/index.py", line 182, in async_call
    result = function(**kwargs)
  File "/app/sickchill/sickchill/views/manage/add_shows.py", line 187, in massAddTable
    cur_dir['existing_info'] = (indqexer_id, show_name, indexer)
NameError: global name 'indqexer_id' is not defined

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by shawnd1965** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@a6400cf7d8c459d64bfa73dad082241f39a381a8
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [a6400cf] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickchill\views\index.py", line 182, in async_call
    result = function(**kwargs)
  File "C:\SickChill\SickChill\sickchill\views\manage\add_shows.py", line 187, in massAddTable
    cur_dir['existing_info'] = (indqexer_id, show_name, indexer)
NameError: global name 'indqexer_id' is not defined

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by shawnd1965** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@a6400cf7d8c459d64bfa73dad082241f39a381a8
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [a6400cf] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickchill\views\index.py", line 182, in async_call
    result = function(**kwargs)
  File "C:\SickChill\SickChill\sickchill\views\manage\add_shows.py", line 187, in massAddTable
    cur_dir['existing_info'] = (indqexer_id, show_name, indexer)
NameError: global name 'indqexer_id' is not defined

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by shawnd1965** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@a6400cf7d8c459d64bfa73dad082241f39a381a8
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [a6400cf] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickchill\views\index.py", line 182, in async_call
    result = function(**kwargs)
  File "C:\SickChill\SickChill\sickchill\views\manage\add_shows.py", line 187, in massAddTable
    cur_dir['existing_info'] = (indqexer_id, show_name, indexer)
NameError: global name 'indqexer_id' is not defined

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by adriansnyman** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-5.4.0-0.bpo.2-amd64-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@a6400cf7d8c459d64bfa73dad082241f39a381a8
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [a6400cf] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickchill/sickchill/views/index.py", line 182, in async_call
    result = function(**kwargs)
  File "/app/sickchill/sickchill/views/manage/add_shows.py", line 187, in massAddTable
    cur_dir['existing_info'] = (indqexer_id, show_name, indexer)
NameError: global name 'indqexer_id' is not defined

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
