### ISSUE TITLE
TheTVDB authentication error while trying to update a series.

### ISSUE THREAD

**Issue by GeckoOBac** [SickChill/SickChill#5904]
Branch: master
Commit: e67ce46328a255be9173d59db93794db097ef522
Version: v2020.01.20-3
Database Version: 44.1

After attempting to force update a series I've got the following error:

> 2020-01-20 19:18:57 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: Unknown error while authenticating. Check your api key or your user/userkey

Trying to update other series produces the same error ouput and doesn't actually update the series.

**Comment by miigotu** [comment]
It's tvdb, we don't control their api failing. Have to wait until it's up again.
