### ISSUE TITLE
Seasons for Scene Exceptions are not up to date with The TVDB

### ISSUE THREAD

**Issue by GeckoOBac** [SickChill/SickChill#5905]
Branch: master
Commit: e67ce46328a255be9173d59db93794db097ef522
Version: v2020.01.20-3
Database Version: 44.1

Some shows don't seem to have the season numbers for their scene exceptions up to date with the seasons available on the TheTVDB. I have at least two cases where it's possible to add Scene Exceptions just for Season 1, while the show is currently on Season 2 (and being Anime has a slightly different name for the season),

I'm not sure whether this is a bug or a feature request. The "override" file on the other repo doesn't seem to be actively worked on (IE: [this issue](https://github.com/SickChill/sickchill.github.io/issues/27) has been open and ignored for a while, even though sickchill says to open issues there for problems relating to scene exceptions), which makes it so unless there is a way to manually add exceptions for new seasons, certain shows have to be downloaded by hand.

**Comment by miigotu** [comment]
6 days isn't a long time in the open source world.
You can make a PR to that repo, and I will check about the tvdb thing.

**Comment by GeckoOBac** [comment]
> 6 days isn't a long time in the open source world.
> You can make a PR to that repo, and I will check about the tvdb thing.

Yeah ofc and that's fair, but I think there shouldn't be a NEED for the exception to be committed just so you can have availability for "Season 2" in the dropdown and the ability to actually add those manually. The information is already available through the show metadata.

**Comment by miigotu** [comment]
It was a bug, calm down bud
