### ISSUE TITLE
Unable to contact theTVDB, aborting: Unknown error while authenticating. Check your api key or your user/userkey

### ISSUE THREAD

**Issue by Matthewserta** [SickChill/SickChill#5906]
Branch/Commit: Master Version: v2020.01.20-4 Commit: be4c371b727438cf2efedf3cdd0d7e58d5887da3 
OS: Windows 10 Pro
Browser: Firefox
What you did: Tried to force update a show, to get the default picture replaced with the actual show picture.
What happened:
2020-01-20 18:53:02 SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: Unknown error while authenticating. Check your api key or your user/userkey
What you expected: Show to update and new poster to download

**Comment by Matthewserta** [comment]
Also under General Settings i get this error:
Mako Error

A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

**Comment by miigotu** [comment]
The apikey error is thetvdb's API not working well, on their end. It will resolve on its own when they fix that.

The other comment I can't help you with because I need the traceback info and I cannot reproduce it. If you get the traceback for it, post it here and I'll check it out.
