### ISSUE TITLE
Feature Request:   video container preference (mp4 vs mkv)

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#5910]
Some of the players I use work better with one format vs the other..
Would be nice download to be able to preference one over the other if both are offered.
Or if its going to replace an existing video..

Also as a side note: I'm interested in the Video format and audio format, (1080p-h264 AAC-2ch)
The WebDL or Blue-ray, DVD-rip is really meaningless.. Since any movie of any format or type could be placed on any of those media's...  So I have to use another program to rename them. 

What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
We cannot filter by containers because most release names are folder names when we get results, not file names.

We also do not scan files to determine audio codecs. If it isn't in the original file name to start with, we don't call mediainfo on it for example because audio codec really serves us no purpose.

A scene name consists of show name, SxxExx, resolution, source, compression codec, and release group. ie: `Show.Name.S00E00.1080p.HDTV.x264-SiCKCHiLL`

If you want to keep the original names, thats fine, or use the post processing hook to call an external tool to rename the files such as nzbtomedia or others.

**Comment by nydave69** [comment]
OK,  that then explains why sometime I have low quality (480 vs 1080) media downloads since it just uses the filename. The rename I use then uses the MediaInfo to process the file. That how I find out that they weren't really 1080..

**Comment by miigotu** [comment]
If you are getting files that aren't the size they are advertised as I wouldn't be using that provider.

**Comment by nydave69** [comment]
> If you are getting files that aren't the size they are advertised as I wouldn't be using that provider.

Futurama Season 1-7 S01-S07-Movies DVDRip-1080p BluRay x264-MiXED

This is currently being offered by most of the providers on SickChill and was selected by SickChill for download.  It's thinking that the BluRay is better then what I have I assume..
I already have these;
Season 7\Futurama (1999) (S07E26) (2013-09-04) (1080p-h264 AC3-6ch) Meanwhile.mkv

My point being that your statement would exclude most of the providers that SickChill uses and the others just dont offer what I am looking for. 
In this case it replaced all 7 episodes of 1080p  with 
Futurama.S01E07.My.Three.Suns.DVDRip.x264.
That turns out to be..
Futurama Season 1 7 S01 S07 Movies (S01E07) (480p-h264 AAC-2ch) Futurama My Three..

In your defense I will say that there is no way to know that that file contained 480P format video files till you download them..  That being said I do think that the post processing process / rename should look at the file its self and decide if the new file is actually a better quality, then decide if it should be moved and replace the existing.  
Now I catch these by not letting the files on the downloader remove them from the down load list. Lots get past me if they are just single episodes. But I always check season packs  And all deleted files go to the recycling bin so that I can restore them.  That's what I did here.  So I am asking; it would be nice if the files were checked (media-info) before moving them.

This mainly happens with older shows.....

Thanks   great program.....

**Comment by miigotu** [comment]
If you process the files yourself to rename them and scan the actual quality, you can have your script also call the API to set the quality of the file in SC. But for sure we won't be rewriting the processor right now, it has been working well off of file names for a decade
