### ISSUE TITLE
Show database entries lost

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#5914]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop
OS: Windows 10
Browser: Chrome
What you did: Nothing (I swear!)
What happened: Several shows show no entries - no episodes listed except ones with files on disk, where date is displayed as 'never'. Newer episodes not listed and not snatched
What you expected: Old episoded to be listed as archived and new episodes snatched
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Tvdb API having issues on their end still. Nothing we can do here.

**Comment by Tiwas** [comment]
@miigotu Ok. Understandable - but is it possible to make it so old entries don't disappear when things like this happens? Having 30 seasons of Simpsons suddenly flooding in is...not ideal ;)

**Comment by miigotu** [comment]
Yeah I know, I'm just not quite sure what to do about it right now because I never get the API to fail so I can't debug a way to avoid it

**Comment by Tiwas** [comment]
I now have at few shows that are like this. Is there a way for me to open the db and have a look? It wouldn't surprise me if the entries are still there, but somehow don't show up with the call from sickchill.

**Comment by Tiwas** [comment]
I've made a note to look at the db with the sqlite db browser tonight. Will share if I find anything, but I guess it would be interesting if the entries are still there. That would mean the select statement is faulty - or the code handling the data afterwards.

**Comment by miigotu** [comment]
They aren't in the DB or they would show up in SC. The problem is when tvdb doesn't return the data correctlyduring a show update, it deletes the episodes from the DB and re-adds them with the incomplete data from tvdb.
