### ISSUE TITLE
Post processing not working

### ISSUE THREAD

**Issue by potestus** [SickChill/SickChill#5916]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)
![Screenshot_20200122-184006_Chrome](https://user-images.githubusercontent.com/2980512/72923726-8ade0580-3d47-11ea-8730-9c8c4d48cfbd.jpg)

Branch/Commit:main latest
OS:android to qnap
Browser:chrome
What you did:latest updates yesterday
What happened:post processing not working and can't enter post processing config page. I reinstalled using sherpa script. Seems to be in a loop.

![Screenshot_20200122-184006_Chrome](https://user-images.githubusercontent.com/2980512/72923971-f58f4100-3d47-11ea-92e3-4424d37fb63e.jpg)

What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by potestus** [comment]
![Screenshot_20200122-191508_Chrome](https://user-images.githubusercontent.com/2980512/72926015-97fcf380-3d4b-11ea-941d-98113d576f49.jpg)

**Comment by potestus** [comment]
Ok I fixed it..found lots of issues.
I'll try to explain.
Because SABnzbd script isn't working because of python 3 I decided to let sickchill do the unpacking and turned off unRAR in SAB .. it unpacked into a folder with the same name as the first RAR file..  so no use to anyone.. each 15 mins sickchill unpacks the now increasing number of grabbed releases hence the loop..
I had set sickchill to unpack as I didn't understand the 3rd option (treat like a video)?.

Any help on how to do this properly greatly appreciated..

**Comment by miigotu** [comment]
Treat like a video is if you want to keep the release packed, since some players can play files right from the archive.

I suggest https://github.com/clinton-hall/nzbToMedia

**Comment by miigotu** [comment]
If you want to use SR alone, make the unpack dir somewhere outside of the post processing path

**Comment by potestus** [comment]
Nzbtomedia isn't  working at the moment python 2.7 expired.. If I use SR it also handles problem downloads... so I put the unpack in a new folder say SRTV..How does it get named appropriately and how does SR  handle it!?

**Comment by miigotu** [comment]
Python2.7 is still safe to use. We don't even work with python3 yet....

Putting the unpack folder outside if the postprocessing sir SC will unpack the archive there and process the files from that dir and copy them to your show folder. Make sure to check the delete rar contents option to clear that folder out after it is processed.

Also, nzbtomedia works with marking stuff failed in SC, but if you can get it working great with just SC that's less to worry about and configure.

**Comment by potestus** [comment]
It's not working..I thought this would happen
![Screenshot_20200124-212425_Chrome](https://user-images.githubusercontent.com/2980512/73105441-ef889400-3ef0-11ea-9eaf-bb8611f0d611.jpg)
![Screenshot_20200124-212502_Chrome](https://user-images.githubusercontent.com/2980512/73105453-f57e7500-3ef0-11ea-9da0-598ee4dc7bb6.jpg)

**Comment by potestus** [comment]
![Screenshot_20200124-212746_Qfile](https://user-images.githubusercontent.com/2980512/73105461-fdd6b000-3ef0-11ea-8b28-377aa33821ba.jpg)

**Comment by miigotu** [comment]
Why is there a rar inside the unpack dir? The ear should be downloaded to the normal postprocess dir, rar will unpack it to the unpack dir and process the VIDEO file there.

**Comment by miigotu** [comment]
Also, it doesnt look like its failing or looping, its just re-running every time your post processor runs
