### ISSUE TITLE
When adding a new show, sort search results

### ISSUE THREAD

**Issue by cbinder4** [SickChill/SickChill#5917]
Feature Request -

When adding a new TV Show, sometimes the list of results is very long.  It may be nice to have the list able to be sorted.  For example, if my search results return 50 shows, I could click on Premiered and the results would be sorted by date making it easy to find the one I'm looking for because I know it is from year XXXX.

![SickChill - New Show - Google Chrome](https://user-images.githubusercontent.com/22643599/72928399-eb5c4b00-3d25-11ea-877d-0dded6119b0e.jpg)

**Comment by BenjV** [comment]
I am not sure how SickChill implemented the list for the gui but the result from the api is sorted in the most likely match from the tvdb query.
So the first result has the best match to your input according to Tvdb.

But what you want is a list of all shows sorted by release year.
The tvdb api does not support this.

To my honest opinion that is such a extreem nice request that nobody else would want/use this and spending time to develop it a waste of effort.

If you looking for that show try the TVDB or IMDB websites to find it.

**Comment by cbinder4** [comment]
It's just a request.  Whether it gets implemented or not is up to the Dev Team, of course.

When theTVDB API returns a list of shows I have to scroll three pages through and a show with an exact name match is in the middle of the results, I wouldn't say their API is returning the results in the  most relevant order.  I realize this is an API issue and not a SickChill issue, but having such a sort option could make SickChill a little more easy to use when the APIs are perhaps not performing their best.

**Comment by BenjV** [comment]
Relevant is what Tvdb implemented not what you find relevant.
That's the problem of every developer, what is the most common denominator.

But what you want is just not available in the API.
It is only possible to search for shows based on a Show Name or on ImdbId.
The api will accept a name and does some fuzzy logic search with that name to retrieve a list of relevant shows which are presented by SickChill to the user to choose from.

Api search with an ImdbId will result in just one show.

**Comment by nydave69** [comment]
Is that the IMDB.id or the TVDB.id...  since the request goes to the TVDB..
If the first works good to know but I don't find a lot of shows in the IMDB..

**Comment by BenjV** [comment]
Not sure what you mean.
The request from ChickChill only works with Show Name as input and nothing else.

The underlying TVDB Api can search series with one of the following search parameters.
- name
- imdbId
- zaptoItId
- slug

**Comment by nydave69** [comment]
> Api search with an ImdbId will result in just one show.

You referenced ImdbId...
Just was looking for clarification..

**Comment by BenjV** [comment]
To add a search with ImdbId as parameter would be a simple change is what I meant.
A search based on release date's (what the topic starter wants), is not possible because this is not in the Tvdb api available.

**Comment by miigotu** [comment]
@BenjV Im pretty sure he means to add a tablesorter to that table, so you can click the headers to sort it. imdbid should already work i think

**Comment by cbinder4** [comment]
> Im pretty sure he means to add a tablesorter to that table, so you can click the headers to sort it searching by imdbid or tvdbid should already work i think

Yes, this is what I meant.  I don't expect the API to do something it doesn't but if you are presenting a table of results from the API, I would think it could be made possible to sort the table by various manners in the interface.

**Comment by BenjV** [comment]
@miigotu 
I am sorry but you cannot use ImdbId or TvdbId in the "add show" from SickChill.
And TvdbId is not even an option in the search api.

Also there is no tablesorter there.
You just can select an item by bullet selection.

**Comment by miigotu** [comment]
@benjv try entering a tvdbid in the search field. Imdbid change isn't on the repo yet, but soon.

The tablesorter is what he is asking to be added, and if I was better at JavaScript it would be done already

**Comment by BenjV** [comment]
Cool, TvdbId does work!
I tried Imdbid but that did not work of course because that search works via the other api parameter.

By the way I hate javascripts too.

**Comment by miigotu** [comment]
Searching by tvdb or imdbid is done, and sorting search results by clicking the table headers is done. enjoy

**Comment by cbinder4** [comment]
Wow, that's awesome on all aspects!  Thank you!
