### ISSUE TITLE
Reverse symlink in post-processing not working

### ISSUE THREAD

**Issue by vlastaw** [SickChill/SickChill#5918]
Hi, I would say SickChill on Windows doesn't access files right. I used SR/SC on ReadyNAS for a long time, but that version is not maintained and cannot be updated, so I decided to purchase low-power PC with Windows and use it for SC/qBT. I installed SC with the Windows installer, everything seems to be working fine - it even updates, which is cool. With one exception:

File handling (in postprocessing) seems to be broken. Same as on ReadyNAS I would like to postprocess using Reversed symlinks, because I don't want to waste disk space holding two copies of the same file while seeding. Postprocessing however has difficulties finding the files on the disk, assigning them to the show - and even if this happens, ultimately, there's no symlink created.

What I do is I delete the show from the old SC incl. the files (actually symlinks), create the show in the new SC and force postprocess. My expectation is it will find the downloaded files in the post-processing directory (the one where qBT puts downloaded files), add it to the show and re-create symlinks. But none of it happens. No files detected, no added, no symlinks. Tried setting up episodes wanted and downloaded. No change.

Log states Processing failed - This show isn't in your list, you need to add it to SR before post-processing an episode.

Branch/Commit: master, 855f1372e4a868fb27e8202a51dbfcebb9c0701f (actual)
OS: Windows 10
Browser: MS Edge Chromium
Logs: Guess it's for no use. No error logged.

**Comment by vlastaw** [comment]
By setting downloaded episodes to Wanted and forcing already processed files I was able to make SC find most files, but for one show it still doesn't work. Is it possible to paste here log secretly? For obvious reasons I don't want to paste filenames.

However symlinks creation still does not work (networked drive connected via net use). T: is post-process dir, X: is root dir:

LOG (part):
Processing T:\<file>.mkv (None)
Retrieving episode object for 7x10
Snatch history had a quality in it, using that: 1080p WEB-DL
Is ep a priority download: False
File X:\<showname>\<file>.mkv doesn't exist so there's no worries about replacing it
No associated files for X:\<showname>\<file>.mkv were found during this pass
Found release name <file>
Destination folder for this episode: X:\<showname>
Creating then symbolic linking file from X:\<showname>\<file>.mkv to T:\<file>.mkv
Processing succeeded for T:\<file>.mkv

**Comment by miigotu** [comment]
This isn't a symbolic link issue, it's a permissions issue. The service on Windows is ran as your user and unless you are logged in the share doesn't exist. Also, your share needs mounted as a folder, not a drive.

**Comment by vlastaw** [comment]
I have some experience with Windows Servers, so my service runs under Local SYSTEM account, which has unrestricted access to all resources. My network drives are connected on system level via scheduled task on computer startup using persistent net use also under SYSTEM account, which also means these are available to all user accounts and always connected. To compare my qBT service runs under a limited user account (default user account + logonasaservice right + write permission to qBT folder, nothing more) and has access to the same network drives (it downloads to my T: drive). So this should be OK.

Will try the folder-not-a-drive-approach however. Even though I don't know why should there be a difference between mounted drive and folder.

**Comment by miigotu** [comment]
Update?
