### ISSUE TITLE
SSLError TheTVDB (Max retries exceeded with url: /login)

### ISSUE THREAD

**Issue by ThrustVector** [SickChill/SickChill#5920]
Branch/Commit: master/855f1372e4a868fb27e8202a51dbfcebb9c0701f
OS:
----Client -> Windows 10 Pro x64 (accessing sickchill)
----Server -> Debian 9.11 (serving sickchill)
Browser: Chrome 79.0.3945.130
What you did: Tried to add new show.
What happened: Search returned: No results found, try a different search.
What you expected: The show to appear in the search so I could add it.
Logs:
```
AA SSLError: HTTPSConnectionPool(host='api.thetvdb.com', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

**Comment by miigotu** [comment]
Cannot control when tvdb breaks their api. They are in a development frenzy in live code ...
