### ISSUE TITLE
2160p not detected as 4K

### ISSUE THREAD

**Issue by hapklaar** [SickChill/SickChill#5924]
Can anyone explain why this is happening? I don't understand why SickChill doesn't detect this as 4k and skips the episode. Isn't 2160p indicative for this?

`2020-01-25 22:04:50 DEBUG SEARCHQUEUE-BACKLOG-359251 :: [NZBGeek] :: Ignoring result Seven.Worlds.One.Planet.S01E02.Asia.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-FraMeSToR-Scrambled.

2020-01-25 22:04:50 DEBUG SEARCHQUEUE-BACKLOG-359251 :: [NZBGeek] :: Don't want this quality, ignoring found result for Seven Worlds, One Planet S01E02 with quality Unknown

2020-01-25 22:04:50 DEBUG SEARCHQUEUE-BACKLOG-359251 :: [NZBGeek] :: Any,Best = [ 4K UHD TV, 4K UHD WEB-DL, 4K UHD BluRay ] [ None ] Found = [ Unknown ]

2020-01-25 22:04:50 DEBUG SEARCHQUEUE-BACKLOG-359251 :: [NZBGeek] :: Parsed 
Seven.Worlds.One.Planet.S01E02.Asia.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-FraMeSToR-Scrambled into Seven Worlds One Planet - S01E02 [GROUP: Scrambled] [ABD: False] [ANIME: False] [whichReg: [u'standard']]`

**Comment by hapklaar** [comment]
Funny thing is, when I download those eps manually SickChill does see them as '4K UHD TV'

**Comment by miigotu** [comment]
Enable HEVC support in `settings->search settings` by checking `Allow downloading HEVC x265 releases`

**Comment by Tiwas** [comment]
I just found this today. My SC gives me the same message when looking for 4K material. If I download manually, the 2160 episodes will be marked as 4K, but are ignored when searching. I've checked allow downloading HEVC x265 releases.

Any other tips?

**Comment by miigotu** [comment]
I added a commit to the history branch that makes the above releases work. They are missing the codec in the release name, but I worked around it by allowing the HEVC tag to mean x265 and TrueHD to be allowed as the source (usually a web source)
