### ISSUE TITLE
Trakt integration doing too much things

### ISSUE THREAD

**Issue by defhead** [SickChill/SickChill#5926]
Branch/Commit: 097c67d9998e549f6cab0dae0e511f3a0dfa68e4
OS: Linux-4.15.0-74-generic-x86_64-with

I know the issue title is weird, it's not often it's possible to complain about too many "features" :)
Currently, if you enable Trakt integration in SickChill and toggle "Sync watchlist" it will mark each "Wanted" episode on SickChill as "Watchlisted" in Trakt.

My usage of Trakt is much more simplier. I'm using the watchlist at the highter level, meaning I add a show to the watchlist and once I watched at least one of its episodes, the whole show gets removed from that list (default Trakt functioning), at no point the episodes or seasons are added to this list. My "watched" and "collected" status in Trakt are handled by my Plex. 

**So my question is :** Is it really possible to configure Trakt in SickChill to only grab the new shows added on my default watchlist, add them in SickChill, and let the removal from watchlist be handled by Trakt itself. I don't want SickChill to mark any individual season or episode as neither "watchlisted" nor "collected".

If not, could you give me a start point in SickChill codes (which files are handling this feature) so maybe I could make a PR to allow this very simple and basic functioning of Trakt in SickChill?

**Comment by miigotu** [comment]
sickbeard/traktchecker.py

**Comment by defhead** [comment]
Ok thank you. But I assume it means my use cas is not possible ?

**Comment by miigotu** [comment]
Everything is possible, but for your use case you dont need to use trakt inside SC at all. Your plex or kodi can add your collection and watchlist on its own

**Comment by defhead** [comment]
Well Plex and Plex-trakt-plugin don't allow to handle a list of the wanted, future, not aired yet tv shows (at least not in my knowledge) .

If you are suggesting that I should manually add the future tv shows I want to watch in SC, without using Trakt watchlist, it would not be a good solution for me. I would like Trakt to stay my entry point for each DVR (SC, CP, etc.)

**Comment by miigotu** [comment]
I just dont see the point of trakt, Pex's on-deck and recently-added is plenty enough for me to keep track of what to watch. If you would like it to work a different way, you are welcome to mess with it, but I just can't make sense of how it should work enough to even bother spending my time on it personally.

**Comment by defhead** [comment]
Plex's on deck and recently added are based on the files/tv shows **you already have**.

Let's forget Plex for a minute.

I'm talking about something way more basic: I would like SC to automatically add new shows by getting them from my Trakt watchlist. Does the current implementation of Trakt integration within SC allow that, **without tagging each "Wanted" episode from SC as "Watchlisted" in Trakt**?

**Comment by miigotu** [comment]
Like I said, I do not know much about how it works or how it should work, but it does need to have episodes marked as watched in trakt in order for automatically removing shows from SC once you have watched them 100%.

I imagine you can get the behavior you want by commenting out lines 246 and 247 of sickbeard/traktChecker.py

**Comment by miigotu** [comment]
The way I __think__ it should work is that all the previous shows you had and currently have in SC should be in your collection.
The watchlist should never have shows or episodes added to it by SC, it should grab items FROM the watchlist, add the show to SC, check the collection for what you have already watched from that series and mark it as ignored/skipped, download the new ones you havent watched yet, and remove it from the watchlist.

**Comment by defhead** [comment]
When you say "collection", I imagine you mean "Trakt collection", right (just to be sure)? I think that relying on Trakt Collection to check what was watched or not could be problematic. A Trakt user may have an episoded tagged as "Watched" on Trakt, but not have it in his collection (still trakt collection). 

I see what is your idea, but how would it handle a show that was ended but rebooted many years later?

**Comment by miigotu** [comment]
If an episode is marked as Watched, it should always be in the trakt collection imho, but you can just mark the episode watched and not add it to the watchlist. An ended show rebooted later would still behave the way it is now, you would have to either still have the show in SC, or add it back manually

So Im gathering you mean Collection is just the shows you currently have in SC?
Watched are episodes you previously watched (obviously)
And watchlist is stuff you have manually added to your watchlist and SC picks that up and adds the show to SC and removes it from the watchlist?

**Comment by defhead** [comment]
> Watched are episodes you previously watched (obviously)

Yes

> So Im gathering you mean Collection is just the shows you currently have in SC?
> And watchlist is stuff you have manually added to your watchlist and SC picks that up and adds the show to SC and removes it from the watchlist?

Not really, I think each user can have its own "notion" of what should be considered as "collected". For instance if you take my example:
- My Trakt profile is my central and most important thing to "trakt" what, when (and even how, with Trakt collections being able to contain information like BluRay, 1080p, etc) I watched something
- My Plex server is not on the same "environment" than SC, so the folders and files are not shared between them.
- So, in my case an episode or a movie is tagged "**Watched**" on Trakt once I watched it on Plex and "**Collected**" if I have the file(s) on my Plex server (they are deleted from my Trakt Collection if I delete the files from my Plex server) . My trakt "**Watchlist**" contains only movies and tv shows (not its episodes/seasons, even if technically Trakt allows it) I didn't watch yet. So in some cases an episode will be "collected" and, at the same time, the show will still be on the "Watchlist". But in each case, a show will be deleted from my trakt "Watchlist" when at least one of its episodes is tagged as "Watched" (still on Trakt). It's the default behavior on Trakt when an element is tagged as "Watched", I don't have to do it myself.
- For now, I disabled Trakt on SC, so when I want to watch a show that will air in 2 months I have to add it twice, once to my Trakt watchlist and a second time to my SC (I anticipate a suggestion right away : I cannot add it _just_ to SC, because anything could happen to my SC installation, I could lost the data, etc., whilst Trakt has more guarantees for data integrity and preservation). And I don't need SC to handle my "watched" or "collected" status on Trakt.

But some other user will have another "setup". For instance he will not have a Plex server, so he'd like an episode on its Trakt be tagged as "Collected" once SC downloads it.

That's way I suggest that SC should let the user enable or disable some configuration parameters, allowing him to control which actions should be trigged on specific "events".

You probably won't have much time or "reasons" to change all that right now, but if you're open to these suggestions, I'm really motivated to contribute and make some PR, but I would have to get your approve on the "functional side" of things. We could collect some "setup" scanarios from other users using SC and Trakt "together".

**Comment by miigotu** [comment]
I'm all for it being rewritten, and highly configurable. Honestly, I hate how it's done right now and it's unreliable. I'll try to help where I can, but I don't use trakt. SC processes my files and Plex picks up the changes to the show for and keeps track of my watched status. When I want a show i add it to SC and that's that.
