### ISSUE TITLE
Last update caused an unusuall result

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#5927]
SickChill Info:
Branch: master
Commit: 097c67d9998e549f6cab0dae0e511f3a0dfa68e4
Database Version: 44.1
  Python Version:
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
  SSL Version:
OpenSSL 1.0.2t 10 Sep 2019
  OS:
Windows-7-6.1.7601-SP1
  Locale:
en_US.cp1252

What you did: refreshed show
What happened: got whats pictured bellow, new season in wrong language
What you expected: the updated season 8 in English
also not sure why one episode is in white listed, does this have a new meaning?
Logs:
```
PASTE LOGS HERE
```
![image](https://user-images.githubusercontent.com/14140816/73135439-0376e780-4010-11ea-8949-6a0e9c57106e.png)

**Comment by miigotu** [comment]
Their api... Nothing has changed on our end in the past week related to this

**Comment by miigotu** [comment]
Has it resolved? force an update on it again

**Comment by nydave69** [comment]
No it's still wrong,  but it's correct on the TVDB...

**Comment by nydave69** [comment]
SC also shows that episode 3 never aired but the TVDB has an air date

**Comment by miigotu** [comment]
Click the manual search magnifying glass for that episode
