### ISSUE TITLE
[Feature]Refresh Poster

### ISSUE THREAD

**Issue by Mickroz** [SickChill/SickChill#5943]
Since i cannot get some posters to update when refreshing a show(with different browsers, so no cache issue), anyway we can get a refresh poster only button instead of refreshing the whole show?
And with that, maybe choose between a tvdb or fanart poster?

I know that tvdb api has some issues, but some shows refuse to update the posters, even after recreating a show, where some newly added shows do update the poster image.

**Comment by Nyaran** [comment]
I'm working on this right now, I will upload a first version to my fork soon and if is stable enough I will made a PR

@miigotu Anything I need to know? My branch will be based on "develop" branch, to use Python 3

**Comment by miigotu** [comment]
Have at it bud =P

**Comment by Nyaran** [comment]
First version is ready: https://github.com/Nyaran/SickChill/tree/feature/customize_show

Features:

On edit show, a new tab was added, "Customize", where you can:
 - Change Show name: #5730 
 - Edit images (poster/banner/fanart): Get the image from the show indexer or from fanart.tv. Also allows to upload from computer

I will use it for a while to detect issues and also have to write the tests. Meanwhile... some screenshots =)

![img0](https://user-images.githubusercontent.com/1042532/90312371-3f1dc400-df04-11ea-940d-7da200ad9054.png)
![img_1](https://user-images.githubusercontent.com/1042532/90312373-3fb65a80-df04-11ea-95be-c6f8d5151544.png)
![img2](https://user-images.githubusercontent.com/1042532/90312372-3fb65a80-df04-11ea-8668-1b6716caf9a5.png)
