### ISSUE TITLE
Sorting by Next Episode doesn't always work

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#5944]
Branch: master 
Commit: 097c67d9998e549f6cab0dae0e511f3a0dfa68e4 
Version: v2020.01.25-1 
Database Version: 44.1 
OS: Windows-10-10.0.18362 
Browser: Edge
What you did: Select to display **Show List / Poster / Sort by Next Episode**
What happened:  Sort results show Next Episodes mixed with Continuing and Continuing mixed with Ended
What you expected:  First see **Next Episodes**, then **Continuing**, then **Ended**
Logs:
```
No relevant entries
```
I don't recall having noticed this in the past, but I'm not sure when it started.

The issue seems to be when displaying by **Poster**
The other display options (which I don't use) show the **Next Episode** in proper order, but **Continuing** and **Ended** are still interleaved.

The sorting order in **Poster** also seems to vary with the size of the window.
With the window narrow enough to show just one or two columns of Posters, the sorting is as expected. As I widen the window, the sorting becomes increasingly incorrect.

Similar problems occur in Chrome.

**Comment by ronrosenfeld** [comment]
Just updated to the latest version
```
Commit: 248db26e9962bb83163194a269f26497551511b4 
Version: v2020.01.29-1 
```
And the problem persists

**Comment by ronrosenfeld** [comment]
To further clarify, since I can't open a duplicate issue, the sorting order goes as follows, with Poster view and a window that is showing Six panels across; Layout: Poster; SortBy: Next Episode Ascending

```
1/29/2020     1/30/2020     1/30/2020     1/31/2020     1/31/2020     2/1/2020
2/3/2020      Continuing    2/9/2020      2/9/2020      6/6/2020      Continuing
Continuing    Continuing    Continuing    Continuing    Continuing    Continuing
Continuing    Continuing    Continuing    Continuing    Continuing    Continuing
Continuing    Ended        Continuing    Continuing    Continuing    Continuing
Ended        Ended        Ended        Ended        Ended        Ended
```

**Comment by miigotu** [comment]
Need a screenshot and page source while problem is present. This is a pretty minor issue and I cannot reproduce it, so I'm gonna need as much help as possible to narrow it down. Most likely this is the isotope flow bug, and might not get fixed.

**Comment by ronrosenfeld** [comment]
On the first screenshot, you can see how American Gods (Continuing) is listed in between Manifest and Power which have upcoming dates.

Of interest is that if I change the zoom of the browser -- say to 75% -- the "Next Episodes" are sorted correctly, but there is still some intermixing of Continuing and Ending.

The second screenshot demonstrates mixing of Continuing and Ending.

To me it seems like something in how Sickchill is interacting with Windows and/or the browsers


![sick1](https://user-images.githubusercontent.com/18516066/73393542-d34a7580-42a9-11ea-968a-6ed45c47aaf0.PNG)

![sick2](https://user-images.githubusercontent.com/18516066/73393850-62578d80-42aa-11ea-944a-8a99c90f5058.PNG)

**Comment by miigotu** [comment]
First, I think you are confusing status and next (or most recent) air date.

Continuing, Ended, etc are the status of the show, next air date (or most recent) is the air date.

A show can be marked ended and still have a newer episode than one who is continuing.

This is why you can sort by status in other modes.

**Comment by miigotu** [comment]
By page source I mean right click the page while the problem is showing and Vue source, copy the HTML, and paste it to a gist.

Also, what browser are you using?

**Comment by ronrosenfeld** [comment]
I would think there is a difference between "next" and "most recent" in the sorting, and that the latter should be ignored if sorting by most recent. But even if it is not, in the second screenshot above, the "Ended" has a "most recent date" that is earlier than the "most recent" dates of the "Continuing" series on either side.

I've seen the problem with both Edge and Chrome.

Here is the Source from Edge:

[SickSrc.txt](https://github.com/SickChill/SickChill/files/4131584/SickSrc.txt)

**Comment by miigotu** [comment]
Because poster view uses the JavaScript isotope library, the others use jQuery.tablesorter.... there is a sorting/layout bug in isotope, and there is no fix for it and there is no good alternative.

**Comment by ronrosenfeld** [comment]
Thanks for the explanation. I appreciate your taking the time to follow up with me on this.

**Comment by miigotu** [comment]
Also, make sure the new javascript is loaded, ctrl+f5

**Comment by ronrosenfeld** [comment]
Will do. I usually update Java when prompted, but I'll double check that I haven't missed one.

**Comment by miigotu** [comment]
@ronrosenfeld if you click the dropdown and switch from next episode to name, and then back to next episode, is it correct then?

**Comment by miigotu** [comment]
Try updating to v2020.01.29-2 and see if that works

**Comment by ronrosenfeld** [comment]
Hmmm.  Seems I missed v2020.01.29-2.  I just updated and now see:

```
Commit: 54aaf19ff076d5591c60e757135cdaf58d6cc31d 
Version: v2020.01.29-4 
```

And I am pleased to say that this version seems to display the shows in the desired order!!
Thank you so much, for this and for all your work in keeping this running.

I wish I knew enough to help with the project.

Ron

**Comment by ronrosenfeld** [comment]
With regard to Java version, I can't seem to verify it in Edge, Chrome or IE.  Ctrl-F5 doesn't seem to do anything except maybe reload the page. And the [verify Java page](https://www.java.com/en/download/installed.jsp) tells me it won't work in Edge or Chrome. In IE nothing appears when I click it. But Sickchill in Poster mode seems to work OK with this latest update. I'll keep an eye on it.

The sorting used to be OK.  It seems it was broken for a few weeks, but now is again working.

**Comment by miigotu** [comment]
@ronrosenfeld Java and JavaScript aren't the same thing. Ctrl+f5 clears the browser cache and forces it to reload the source files is all. Anyway, glad it's working.

**Comment by ronrosenfeld** [comment]
Unfortunately, the problem has recurred.  Again, just in the large poster view with a full window browser.  With a browser showing just four posters in a row, or even with it full screen but set to 75% zoom level, the sorting will be OK.  (Similar behavior with Chrome, Edge and IE).

I've tried the ctrl-F5; switching between different sorts and display types, and restarting Sickchill to no avail.

**Comment by ronrosenfeld** [comment]
And, with the latest update, the problem seems to have again resolved.  I guess it is just going to be an intermittent thing.

**Comment by glenviewjeff** [comment]
Happening for me as of that recent major update where we had to manually re-install Sickchill.

**Comment by glenviewjeff** [comment]
Broken again. "Next episode" is blank for many shows in the show list, regardless of what format you're viewing, for shows that have airdates scheduled in the future. For example, right now Star Trek Discovery shows up for me as a blank "next episode," although there's one scheduled for October 29th.

**Comment by ronrosenfeld** [comment]
@glenviewjeff  Jeff, I think your issue is different from the issue I reported in this thread. The problem I was having had to do with sorting.  I never had any blank dates for shows with scheduled future air dates.  You may want to search to see if that particular problem has been reported; and either add something to that issue; or report a new issue with all the relevant information.

**Comment by glenviewjeff** [comment]
@ronrosenfeld I'm not sure if it's different, it may just be my description of the bug that's unique. When I look at the poster view, I see the same order as the other views when sorting by next episode. The only four shows with a "next episode" listed are Last Week Tonight, Nova, SNL, and Doctor Who. Everything else shows "continuing," even shows which have ended, such as Beavis and Butt-Head. Many shows which have upcoming episodes even within the next week (both in reality and within the show page detail) are randomly sorted among those. 

Looking at the details on the simple layout reveals the episode data is totally screwed up, and there must not be error checking within the code about this. For instance SNL shows a previous episode of 11/7/20, with a next episode of 10/31/20. Then as another example, Star Trek Discovery has a previous episode of 1/7/21, but no next episode in the simple list. Everything's correct on the individual show pages. Oops!

> @glenviewjeff Jeff, I think your issue is different from the issue I reported in this thread. The problem I was having had to do with sorting. I never had any blank dates for shows with scheduled future air dates. You may want to search to see if that particular problem has been reported; and either add something to that issue; or report a new issue with all the relevant information.

**Comment by ronrosenfeld** [comment]
@glenviewjeff  In my issue the **dates listed were always correct**. The order of the posters was incorrect and somehow related to the size of the poster, zoom level of the browser, etc. Migiiotu thought it was related to a sorter in the browser, not in Sickchill.

**Comment by glenviewjeff** [comment]
I actually think my issue may be stemming from a Windows permissions problem. Working on it now, thanks.
