### ISSUE TITLE
Sorting by Next Episode doesn't always work

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#5946]
I posted this yesterday  [Sorting by Next Episode doesn't always work](https://github.com/SickChill/SickChill/issues/5944) and it was closed indicating a recent commit fixed the problem.

However, today I downloaded the most recent update

```
Commit: 248db26e9962bb83163194a269f26497551511b4 
Version: v2020.01.29-1 
```
and the same issue persists

**Comment by miigotu** [comment]
Don't open duplicate issues. It sorts based on shows who have a new episode set in tvdb. Ended shows and paused shows are after the continuing list. Update the original issue with more information otherwise.
