### ISSUE TITLE
[APP SUBMITTED]: 429 Client Error: TOO MANY REQUESTS for url: https://discordapp.com/api/webhooks/512556869173248011/dsrPzvQFqnjPYmS20xOa7F8pJy7Ms6H7SJZfuUDIxgRPyjZyAp3M8QRT5hlFlF6WtAcb

### ISSUE THREAD

**Issue by szum1k** [SickChill/SickChill#5949]
### INFO
Python Version: **2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]**
Operating System: **Linux-5.0.0-37-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@54aaf19ff076d5591c60e757135cdaf58d6cc31d
Link to Log: https://gist.github.com/76a44ee4492ffcfd57677b8abc2b1e0a
### ERROR
```
SEARCHQUEUE-BACKLOG- :: [54aaf19] Error Sending Discord message: 429 Client Error: TOO MANY REQUESTS for url: https://discordapp.com/api/webhooks/512556869173248011/dsrPzvQFqnjPYmS20xOa7F8pJy7Ms6H7SJZfuUDIxgRPyjZyAp3M8QRT5hlFlF6WtAcb
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
xD
