### ISSUE TITLE
Show List Not Sorted Properly

### ISSUE THREAD

**Issue by cbinder4** [SickChill/SickChill#5954]
I know this was supposed to be recently fixed, but when viewing by Poster, the Show List order is still majorly messed up for me.  I have a bunch of shows listed by date as they should be, then the Continuing shows, then Ended shows... but under the ended shows I have another set of shows that are active and have air dates on them such that they should be at the top of the list with the other air date shows and then I have more Continuing shows under them.

**Comment by miigotu** [comment]
Please search issues first next time. The is fixed as best it can get, there is a bug in a 3rd party lib we use and it's not gonna get any better than it is now. If sorting by next episode is a major need, switch to another view type and sort the table.
