### ISSUE TITLE
[e388002] Unable to write file to D:\TV\ShowName\series.xml - are you sure the folder is writable? error 13 : Permission denied

### ISSUE THREAD

**Issue by cadmuslabslex** [SickChill/SickChill#5955]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: MASTER
OS: Win7x64
Browser: Chrome
What you did: Show Update
What happened: Failure
What you expected: Show to update 

I keep randomly getting this error on shows inside a folder that I know has full read / write and proper permissions. Everyone and Users as well as my account have full permissions and the folder is NOT set to read only. If I delete the folder and re-create it I do not get the error.

Any Ideas?

**Comment by BenjV** [comment]
Possible a problem with the user which is running ChickChill or with the parent folder.

ChickChill creates the folder and at that moment the privileges are set.
I am not very familiar with the windows privileges but on Linux when you create a folder or file it inherit the privileges of its parent folder.
So if the parent has no write privileges then ChickChill create a folder with the same privileges and cannot put a file there.

**Comment by miigotu** [comment]
@BenjV wtf is ChickChill lol

**Comment by BenjV** [comment]
It is SickChill for Chicklet tv series lol.
