### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by XanderStrike** [SickChill/SickChill#5957]
There's an api key in the settings, and there's [this file](https://github.com/SickChill/SickChill/blob/master/sickchill/views/api/webapi.py) which seems to define an API, but neither the wiki nor the readme seem to reference any kind of specific API documentation.

Googling for "sickchill api documentation" or "sickrage api documentation" returns no results.

The methods seem to contain help information, but I'm wary of the accuracy of them and the comments. For example the URL format [in this comment](https://github.com/SickChill/SickChill/blob/master/sickchill/views/api/webapi.py#L243) is not correct (it's actually `/api/apikey?cmd=...`) and at least one [isn't documented](https://github.com/SickChill/SickChill/blob/master/sickchill/views/api/webapi.py#L267). 

Given the `_help` variables I would guess at some point there was automatically generated documentation, but I'm not familiar with how Python does this. I just wanted to bring it to your attention that this could be helpful to others because I've spent a bunch of time reverse-enginering this.

**Comment by miigotu** [comment]
`ip:port/apibuilder`

**Comment by XanderStrike** [comment]
Cool, thank you! Would you be open to a PR that links to that from the settings page like CouchPotato and others do?

**Comment by miigotu** [comment]
You can certainly make any PR that's useful 😉
