### ISSUE TITLE
Dates are changing for exsisting shows

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#5959]
Checking through some on my archived shows I noticed lots of changes, The air date now mostly shows never aired.. or Some date.. and usually at 12:00

![image](https://user-images.githubusercontent.com/14140816/73847319-059d2b00-47f4-11ea-8999-31e050eab325.png)

If you look at the dates for the shows in the same season, the file name contains the actual show date.

What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
SickChill simply uses the dates provided by tvdb.
You will have to fix it there.
https://thetvdb.com/series/ancient-megastructures/episodes/669901
