### ISSUE TITLE
This isnt really an issue, more of a request but Not sure..... please read regarding modifying the manual post processing default options.

### ISSUE THREAD

**Issue by cadmuslabslex** [SickChill/SickChill#5960]
This isn't really an issue, more of a request but Not sure..... please read

Under manual post processing section you are given 4 options:

Force already Post Processed Dir/Files
Mark Dir/Files as priority download
 (Check it to replace the file even if it exists at higher quality)
Delete files and folders
 (Check it to delete files and folders like auto processing)
Don't use processing queue
(If checked this will return the result of the process here, but may be slow!)

Is there anyway to code SickChill to have these options be checked "ON/Enabled" by default on  my build. I do not use the auto processor because my Downloads folder and my storage directory are on separate discs and when it auto processes it slows the pc down really badly. So i have a manual path entered here and every time I open it I have to check off those 4 boxes again. I want to have it so that by default all 4 options are checked off and if I need to change the settings then I simply uncheck.

1), Can anyone tell me if this is possible?
2). If it is possible what file needs to be edited to make it possible.
3). which line / lines of code need to be modified
4). What needs to be added to / removed from those lines.

Thank You

**Comment by BenjV** [comment]
All settings are to be found in the config.ini.
So I assume you could add the settings you want to the condig.ini before you install SickChill.

Not sure why you woud need this, because you only have to do this settings once, so why the need for this default?

**Comment by miigotu** [comment]
@cadmuslabslex I would suggest using a script to make a call to the api manually
`ip:port/apibuilder` and type postprocess into the command box. It will show you the url and params to hit, and you can even get response data and print it out with your script.

**Comment by miigotu** [comment]
`ip:port/<web root>/api/<apikey>/?cmd=postprocess&failed=1&force_next=1&force_replace=1&is_priority=1&path=<process dir>&return_data=1&process_method=copy&type=manual&delete=1`
