### ISSUE TITLE
mako error on show list, schedule

### ISSUE THREAD

**Issue by Wally73** [SickChill/SickChill#5964]
File G:\SR1\sickbeard\image_cache.py:159, in image_url:
return 'cache' + path.split(sickbeard.CACHE_DIR)[1].replace('\\', '/')
IndexError: list index out of range

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop/0bfff36c51e058e0539007b271fb93d5666dcd29
OS: win2008R2
Browser: chrome

**Comment by miigotu** [comment]
whats your cache dir?

**Comment by Wally73** [comment]
standard windows install (i haven't changed dir order)

**Comment by miigotu** [comment]
I don't use windows so I'll need a bit of help here...

**Comment by Wally73** [comment]
cache seems now moved from sickchill root to under gui/slick/cache

**Comment by miigotu** [comment]
Yes it's supposed to be moved

**Comment by miigotu** [comment]
click update again for now, it might not show posters but it wont error for now while i figure it out

**Comment by Wally73** [comment]
> click update again for now, it might not show posters but it wont error for now while i figure it out

show list and schedule show up now again (and yes the images are missing)

**Comment by miigotu** [comment]
stop SC, edit config.ini, change cache_dir to `gui\slick\cache`, path separator is bad

**Comment by Wally73** [comment]
that did the trick ;) thx
