### ISSUE TITLE
image_url issue after tonights commit

### ISSUE THREAD

**Issue by riddlenl** [SickChill/SickChill#5965]
After tonights update at around 20:30, the following error occurs on the homepage /home/

File C:\SickChill\SickChill\sickbeard\image_cache.py:159, in image_url:
return 'cache' + path.split(sickbeard.CACHE_DIR)[1].replace('\\', '/')
IndexError: list index out of range

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/issues/5964
