### ISSUE TITLE
Sort by Next Episode

### ISSUE THREAD

**Issue by krash1220** [SickChill/SickChill#5966]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Windows 10
Browser: Chrome
What you did: Chose Sort by Next Episode
What happened: Shows are not sorted correctly
What you expected:
Logs:
```
PASTE LOGS HERE
```
When choosing Sort by Next Episode I'm getting the wrong sort dates. Some of the dates are right 2/9 - 2/22 but then there are two continuing and then two at the end are 2/13.

**Comment by miigotu** [comment]
Sure those aren't paused or aren't continuing?...

**Comment by krash1220** [comment]
No. I removed the continuing ones but there are still two at the end that list as 2/13. Briarpatch is listed as Show status: upcoming and so is High Fidelity. The ones that are in the right order list all as Show Status: continuing. Could that be it? I don't understand why Briarpatch is listed as upcoming but High Fidelity hasn't started yet. But I've never had this problem before.

**Comment by krash1220** [comment]
They all sort correctly when on everything but Poster. Small poster, Banner, and Simple sort correctly.

**Comment by deepseth** [comment]
Can you post a screenshot? I'm intrigued, as I use this sort method but haven't noticed this happening to me.

**Comment by ronrosenfeld** [comment]
I have intermittently had this problem, although not since the last update
```
Commit: 1f124b31b16303a511c86717f11dd28b9cbf7b46 
Version: v2020.02.15-3 
```

For me, it has been present on both Chrome and Edge browsers, and seems to relate to both the size of the browser window, and also the size of the Poster (as adjusted from within the SickChill UI).

This has been mentioned multiple times in the past, and is due to a bug in a 3rd party application.
