### ISSUE TITLE
[request] gathering issue information.

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#5969]
when creating an issue report some information from SickChill is useful for those trying to fix the issue.
could a click here type button be created that copies the information to the clipboard.
That way it could be pasted here or where it would be useful.
Coping the information to the clipboard gives the user control.
 I know I would use it, since I manually do that myself but I'm sure there is other information that not on the Help & Info that would also be helpful.
A user could remove any information when they paste it since its just text, that they don't want shown.

```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
If a person is making so many issue reports that they need buttons to make it easier to spam issues I don't see that as a good thing. Most actual issues are reported by the app just by clicking one button, the manually reported ones should be few and far between.
