### ISSUE TITLE
Cache rebuild after last update

### ISSUE THREAD

**Issue by cmdzod** [SickChill/SickChill#5970]
Branch/Commit: last
OS: CentOS 7.7
Browser: firefox
What you did: update

I noticed that after last update the cache directory for posters/fanarts/banners was recreated and sickchill start to download new files from provider (thetvdb.com). On my system, sickchill is installed in /opt/sickchill and the full path to the cache dir for images is /opt/sickchill/gui/slick/cache/images. After update, a new directory was created and the full path is "/opt/sickchill/gui\slick\cache/images". So, in linux, instead of three recursive directories (gui, slick and cache) a new one was created called "gui\slick\cache" and sickchill cannot find anymore the already existing jpg files in images directory.

Also I see that sickchill automatically start refresh to all shows at each start. In my case this feature is not a good thing, because I have a lot of shows and I don't keep server running all the time, just 1-2 hours/day. If I want to add a new show I must wait until all shows are refreshed before the new show appear in list. Basically on the last 3-4 days my sickchill server is doing refresh all the time. Maybe a option for enable/disable this can be added in config section ?

**Comment by miigotu** [comment]
This was already fixed in the very next commit, just stop SC and fix the path in config.ini if it hasn't fixed itself yet.
