### ISSUE TITLE
Error in File Path?

### ISSUE THREAD

**Issue by kcwebby** [SickChill/SickChill#5973]
Running the origin branch, through linuxserver.io's docker, I noticed unhandled errors were causing my instance to reboot.   I am unable to figure out what part of the UI is triggering this, but I think it is somewhere around the /errorlog as that's where it happens most often.

Apologies in advance I am unable to recreate, so some of the information is missing.

AA IOError: [Errno 2] No such file or directory: u'/config/gui\\slick\\cache/mako/layouts/main.mako.py'
AA fp = open(path, "rb")
AA File "/app/sickchill/lib/mako/util.py", line 391, in read_python_file
AA return util.read_python_file(self.module_filename)
AA File "/app/sickchill/lib/mako/template.py", line 679, in code
AA module_source = info.code
AA File "/app/sickchill/lib/mako/exceptions.py", line 166, in _init
AA self.records = self._init(traceback)
AA File "/app/sickchill/lib/mako/exceptions.py", line 93, in __init__
AA kwargs['backtrace'] = RichTraceback()
AA File "/app/sickchill/sickchill/views/common.py", line 116, in render
AA 0], max_download_count=stats[1], controller="home", action="index", selected_root=selected_root or '-1')
AA File "/app/sickchill/sickchill/views/home.py", line 142, in index
AA result = function(**kwargs)
AA File "/app/sickchill/sickchill/views/index.py", line 178, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "/app/sickchill/lib/concurrent/futures/thread.py", line 63, in run
AA return self.__get_result()
AA File "/app/sickchill/lib/concurrent/futures/_base.py", line 455, in result
AA value = future.result()
AA File "/app/sickchill/lib/tornado/gen.py", line 1055, in run
AA results = yield self.async_call(method)
AA File "/app/sickchill/sickchill/views/index.py", line 156, in get
AA yielded = self.gen.throw(*exc_info)
AA File "/app/sickchill/lib/tornado/gen.py", line 1063, in run
AA raise_exc_info(self._exc_info)
AA File "/app/sickchill/lib/tornado/concurrent.py", line 238, in result
AA value = future.result()
AA File "/app/sickchill/lib/tornado/gen.py", line 1055, in run
AA result = yield result
AA File "/app/sickchill/lib/tornado/web.py", line 1511, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='https', host='rage:443', method='GET', uri='/home/', version='HTTP/1.1', remote_ip='136.35.218.92', headers={'Sec-Fetch-User': '?1', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'X-Forwarded-Host': 'rage', 'X-Forwarded-Ssl': 'on', 'Sec-Fetch-Site': 'same-origin', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'Upgrade-Insecure-Requests': '1', 'Host': 'rage:443', 'X-Forwarded-Proto': 'https', 'Referer': 'https://rage/errorlogs/?level=30', 'Sec-Fetch-Mode': 'navigate', 'If-None-Match': '"468ee05d114662a820cfdbeb6eeb0caf347de769"', 'X-Real-Ip': '136.35.218.92', 'Cookie': '_ga=GA1.2.1911477551.1556070295; sickchill_user="2|1:0|10:1580177682|14:sickchill_user|44:NjA2MjVkZGM0MzQ3MWMzZDJkYTIyY2RlMWM4ZDM0M2U=|dc4220e699dfb92b6b5e775a21b8cf90e14d6fcff5e2d38b153a639b31e9d039"; _policy=%7B%22restricted_market%22:true,%22tracking_market%22:%22explicit%22%7D; visitor=vid=5c053c17-9329-5f68-b166-27a9543fe9f5; _gid=GA1.2.1400518334.1581386990', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36', 'X-Forwarded-For': '136.35.218.92'})
AA 2020-02-11 18:41:33 ERROR Uncaught exception GET /home/ (136.XX.XX.XX)

**Comment by miigotu** [comment]
Stop SC, git pull, edit `cache_dir` in the config.ini to `gui/slick/cache`, start SC. There was a mistake in how I moved the cache dir. It should fix the cache dir when you start SC up with the new version, but edit the ini just in case it doesn't
