### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-BACKLOG- :: [09207fe] qbittorrent: Unable to set priority for Torrent

### ISSUE THREAD

**Issue by GabhanOLoughlin** [SickChill/SickChill#5980]
### INFO
Python Version: **2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]**
Operating System: **Linux-3.10.70-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@09207fe0680c8a8fd7b9b93127f28b62b6de3732
Link to Log: https://gist.github.com/1aa5af58e260c83ddc712c22fad409d2
### ERROR
```
SEARCHQUEUE-BACKLOG- :: [09207fe] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by GabhanOLoughlin** [comment]
### INFO
Python Version: **2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]**
Operating System: **Linux-3.10.70-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@09207fe0680c8a8fd7b9b93127f28b62b6de3732
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [09207fe] qbittorrent: Unable to set priority for Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Make sure your using the correct qbittorrent client in SC, there are 2 of them.

**Comment by GabhanOLoughlin** [comment]
The other qBitTorrent (ApiV2) in SC doesn't connect at all to my qBitTorrent - it's running on an Asustor NAS (as is SC). Claims to be qBitTorrent v 4.0.4. But gives a _[Errno 404] Not Found_ when testing connection.

**Comment by miigotu** [comment]
what version does it show when you hit `host:ip/api/v2/app/webapiVersion` ?

**Comment by miigotu** [comment]
Actually, 4.0.4 is supposed to be the old client, but that client is a little buggy and is deprecated. Is there a way for you to update to at least qBittorrent v4.2.0?

**Comment by GabhanOLoughlin** [comment]
I've been using the stock qBitTorrent from Asustor App Central - and this is the last update. I'll try to update by SSHing into the box. Cheers.

**Comment by GabhanOLoughlin** [comment]
Updated to the latest version that I can find support for 4.1.8.r0 and ApiV2 seems to be working correctly now - cheers

**Comment by quentinwolf** [comment]
I too have this issue with SickChill.

2020-03-01 19:17:51 INFO SEARCHQUEUE-DAILY-SEARCH :: Telegram message sent successfully.
AA None
2020-03-01 19:17:51 ERROR SEARCHQUEUE-DAILY-SEARCH :: [4d0657e] qBittorrent APIv2: Unable to set priority for Torrent
2020-03-01 19:17:51 INFO SEARCHQUEUE-DAILY-SEARCH :: Request failed: 409 Client Error: Conflict for url: http://192.168.1.12:8080/api/v2/torrents/increasePrio?hashes=%3Cbuilt-in%20method%20lower%20of%20str%20object%20at%200x7f55dcb47b20%3E ()
2020-03-01 19:17:50 INFO SEARCHQUEUE-DAILY-SEARCH :: Downloading TVSHOWNAME from PRIVATETRACKER
2020-03-01 19:17:50 INFO SEARCHQUEUE-DAILY-SEARCH :: [PRIVATETRACKER] :: Quality of TVSHOWNAME is 720p WEB-DL

-----

qBittorrent version: 4.2.1 in Linux
http://192.168.1.12:8080/api/v2/app/webapiVersion shows: 2.4
