### ISSUE TITLE
Two TV shows with Seasons ending too soon

### ISSUE THREAD

**Issue by RetroDriven** [SickChill/SickChill#5985]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/1f124b31b16303a511c86717f11dd28b9cbf7b46
OS: Linux-3.10.102-x86_64-with-glibc2.2.5
Browser: Chrome
What you did: 
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```
--
The Curse of Oak Island is reporting that Season 7 only has 9 episodes and a Status of  Continuing. This show is currently on Episode 13.

Harley Quinn is also reporting that the eason ended with episode 9 as well.

**Comment by miigotu** [comment]
We don't control that, we just use the data from thetvdb.com, you will need to edit the seasons there.

**Comment by RetroDriven** [comment]
The information appears to be correct on thetvdb.com for both shows mentioned above.

**Comment by miigotu** [comment]
force an update on the shows
