### ISSUE TITLE
Question about Use SR Metadata for subtitle download

### ISSUE THREAD

**Issue by ulrick65** [SickChill/SickChill#5989]
I am never quite sure if this the right place to ask questions, if not please let me know the best way to do that.

I was wondering what the setting:

Use SR Metadata:  use SickChill metadata when searching for subtitles, this will override the autodiscovered metadata

actually does and whether I should enable it or not.  I am just now starting to use SC to download subtitles as my hearing has gotten to the point where I need them more and more.

As a side note, I did notice that the setting says "SR" when it probably should say "SC". Not a big deal of course, but the more we get rid of references to SickRage the better in my opinion! 

Thanks.

**Comment by miigotu** [comment]
I'm not sure that setting even does anything haha, I'd have to look at code and I can't right now. Iirc it used to check if the user changed the title and other info in the tvshow.nfo and used that for the search.

**Comment by ulrick65** [comment]
@miigotu  Ok, thanks.  Either way, I assume it uses the release name for an exact match of the subtitles (assuming the setting in subtitles for "exact match" is enabled, which mine is) so it has the best chance of getting subtitles that are not out of sync.

Thanks.
