### ISSUE TITLE
Mako Error

### ISSUE THREAD

**Issue by chris41g** [SickChill/SickChill#5990]
Branch: master
Commit: 1f124b31b16303a511c86717f11dd28b9cbf7b46
Version: v2020.02.15-3
Database Version: 44.1
OS: Linux-5.3.0-28-generic-x86_64-with-Ubuntu-18.04-bionic 
Browser: firefox 73.0 64bit
What you did: click on any tv show from main page
What happened: Mako error
                    File /opt/sickchill/lib/beekeeper/comms.py:99, in send:
                    raise ResponseException(self.action.format(), err)
                    ResponseException: Error message: 404/Not Found
What you expected: to go to tv show page
I completely re-cloned the repo, then just added my config.ini and my db file and I still get the same error. I can't find anything relevant in the logs, so I've attached a complete log from the new cloning.

Logs:
[sickchill.zip](https://github.com/SickChill/SickChill/files/4216451/sickchill.zip)

**Comment by miigotu** [comment]
Post the log file, not a zip

**Comment by chris41g** [comment]
[sickchill.log](https://github.com/SickChill/SickChill/files/4216969/sickchill.log)

**Comment by miigotu** [comment]
What does the mako error say?

**Comment by chris41g** [comment]
From the original report

`File /opt/sickchill/lib/beekeeper/comms.py:99, in send:
raise ResponseException(self.action.format(), err)
ResponseException: Error message: 404/Not Found`

**Comment by davidcastellani** [comment]
> From the original report
> 
> `File /opt/sickchill/lib/beekeeper/comms.py:99, in send: raise ResponseException(self.action.format(), err) ResponseException: Error message: 404/Not Found`

This is the same error output I get whenever I click on any one of my shows from within the Sickchill web interface.

**Comment by miigotu** [comment]
Can you access thetvdb from that machine?

**Comment by chris41g** [comment]
> 
> 
> Can you access thetvdb from that machine?

yes no issues there

**Comment by davidcastellani** [comment]
```
root@f8e279e5c0b9:/$ curl -i --head https://api.thetvdb.com
HTTP/2 401
content-type: application/json; charset=utf-8
content-length: 26
date: Tue, 18 Feb 2020 23:45:02 GMT
cache-control: private, max-age=86400
www-authenticate: JWT realm=jwt auth
x-powered-by: Thundar!
x-thetvdb-api-version: 3.0.0
vary: Accept-Language
x-cache: Error from cloudfront
via: 1.1 e89d95d090c0c86ecc7b8930e434625d.cloudfront.net (CloudFront)
x-amz-cf-pop: IAD89-C3
x-amz-cf-id: 2BWZPjrklXgZZbhJcNy2RIrvRItX-GIOdkQ90OYVp4VI7m2wXdb6nA==
```

From within the sickchill container, failed to authenticate.

**Comment by Gemni69** [comment]
I am having same issue and getting mako error. I cannot view the show content page for any show listed. It is running on Synology device.

**Comment by derkens** [comment]
I'm having exactly the same issue,

**Comment by SirYaro** [comment]
Same problem here.

**Comment by wickerwaka** [comment]
The issue (at least my version of it) is caused by KODI notifications, even if you don't have KODI enabled. Go to settings -> Notifications -> KODI. Enable it and delete the `localhost:80` in the KODI IP:Port settings and then save settings.

**Comment by wickerwaka** [comment]
Not directly caused by, but https://github.com/SickChill/SickChill/commit/23f0d808a622009e7f4591f36a1177cb30111f72 exposed the issue.

**Comment by furgussen** [comment]
Same issue.  I was using Kodi notifications before, but I disabled it months ago.  I went in tonight, enabled Kodi notifications, deleted the Kodi IP:Port User/Pass settings and saved it.  Now I can view shows again.

**Comment by derkens** [comment]
> Same issue. I was using Kodi notifications before, but I disabled it months ago. I went in tonight, enabled Kodi notifications, deleted the Kodi IP:Port User/Pass settings and saved it. Now I can view shows again.

Yes, this works, disabled Kodi notifications moths ago, deleting all kodi information solved the problem.
