### ISSUE TITLE
Latest Image Cache Changes Docker Support

### ISSUE THREAD

**Issue by jesdevs** [SickChill/SickChill#5991]
Related to the latest image cache changes which are now only stored in the application directory, this is somewhat breaking Docker support where the image cache has to be rebuild each time the container is created. Why not create a symlink pointing `${PROG_DIR}/gui/slick/cache` to `${DATA_DIR}/cache` instead?

Additionally, I noticed that the images pulled from TVDB are no longer the main ones for a given show, based on favorite rating, but the oldest ones uploaded. In order to reintroduce the previous behavior, I am suggesting the below change sorting the images based on rating average information.

```diff
--- /app/sickchill/sickchill/show/indexers/tvdb.py.orig
+++ /app/sickchill/sickchill/show/indexers/tvdb.py
@@ -182,8 +182,9 @@

     @ExceptionDecorator(default_return='', catch=(HTTPError, KeyError), image_api=True)
     def __call_images_api(self, show, thumb, keyType, subKey=None, lang=None):
-        images = self.series_images(show.indexerid, lang or show.lang, keyType=keyType, subKey=subKey)
-        return self.complete_image_url(images.all()[0][('fileName', 'thumbnail')[thumb]])
+        images = sorted(self.series_images(show.indexerid, lang or show.lang, keyType=keyType, subKey=subKey).all(),
+                        key=lambda img: img['ratingsInfo']['average'], reverse=True)
+        return self.complete_image_url(images[0][('fileName', 'thumbnail')[thumb]])

     @staticmethod
     @ExceptionDecorator()
```

As a side note, the log directory part of the same change is capitalized (`${DATA_DIR}/Logs`). Was this intended to be that way? It used to be lowered cased prior to that on Linux systems based on my usage.

**Comment by jesdevs** [comment]
Related to #6010

**Comment by miigotu** [comment]
@jesdevs the docker container needs an update, mind helping with that? It should be a new volume mount I think

**Comment by jesdevs** [comment]
@miigotu why not just have the symlink be handled by the application? You just recommended this on #6010. What about my other points?

**Comment by miigotu** [comment]
@jesdevs I added code that does what your patch does already, but I dont see it as necessary to add code that creates a symlink for 1 person who has code on a read-only file system. The dockerfile can be updated for docker and it solves the entire issue.

**Comment by jesdevs** [comment]
@miigotu it's up to you but the same argument could be made from the user's perspective. Having persistent cache data part of the application directory when there is a dedicated data directory available for that purpose isn't optimal architecture-wise.

What is your concern for having the symlink handled by the application?

**Comment by miigotu** [comment]
It isn't even really cache data, it's static files.

**Comment by jesdevs** [comment]
If these were static files, then they would already be committed into repository. Wasn't the cache directory change put in place to mitigate a caching issue in the first place? #5742 

Oh well, it doesn't seem you want to make this reasonable change. I have my workaround so I am not too concern about my usage. I am fairly certain more users will complain about this change once they update their setup. Hopefully, you will reconsider once more folks question this.

**Comment by miigotu** [comment]
This fixes #5742 and others.

Doesn't change the fact that adding a line to the dockerfile makes this change mean nothing to your setup, and actually will keep the cache folder in the data_dir.

I understand, something has changed, as is how the software world goes, you don't like change maybe?

**Comment by jesdevs** [comment]
> something has changed, as is how the software world goes

Agreed but there are different ways to introduce a change especially when it's breaking previous setup. Anyway, I raised a concern and we can't seem to agree on the outcome. Like I mentioned above, I am not gonna try to convince you otherwise at this point. I am just gonna wait and see if other users complain about this or not. If not, then it's on me.

In regards to updating the dockerfile suggestion, I am using the [LinuxServer.io](https://github.com/linuxserver/docker-sickchill) image which I believe is used by a lot of users (10M+ pulls so far). So this is not a simple change for end users as you might think.

**Comment by miigotu** [comment]
The linuxserver.io image will be updated, as well as our own docker image on dockerhub.

**Comment by miigotu** [comment]
Seems it is complicated to mount over mounts in docker, so I added a method on startup that moves the cache folder from gui/slick/cache to DATA_DIR/cache and creates a symlink to it . I really hope it doesn't cause any issues, because there are some big issues I need to focus on for a bit.

**Comment by jesdevs** [comment]
Thanks for making the change. It looks good from my testing using a Docker container.

PR #6014
