### ISSUE TITLE
$ in show name causes search and post processing to fail

### ISSUE THREAD

**Issue by hooligeek** [SickChill/SickChill#5992]
Admittedly this is an assumption.

the show McMillions is listed as McMillion$ in tvbd.

https://thetvdb.com/series/mcmillions

I believe the $ in he name is causing the IPT search to return zero results and the SC postprosessing to be ignored when I manually down the the IPt torrent what does not contain the $.

**Comment by hooligeek** [comment]
Actually is the renaming that fails.  the unrar works.

**Comment by miigotu** [comment]
You need to show logs, and add McMillions as a scene exception for that show.

**Comment by hooligeek** [comment]
Thanks.  I added the scene exception.
