### ISSUE TITLE
Bug with ignored status

### ISSUE THREAD

**Issue by Navino16** [SickChill/SickChill#5994]
### Before submitting your issue:

Branch/Commit: master / last update
OS: Linux / LinuxServer Docker version
Browser: Chrome
What you did: Setting some episode to Ignored
What happened: After some time (max 24 hours, probably during daily update) ignored episodes are marked as Wanted

I experiment this issue with La Casa De Papel (https://thetvdb.com/series/la-casa-de-papel). I set Episodes 14/15 to ignored because the show doesn't match the Netflix format. After Daily update, episodes 14/15 are not marked as ignored but as Wanted.

Thanks in advance for your help.

**Comment by miigotu** [comment]
Do you use trakt? And do you have a log line like `Setting episode {show} {ep} to wanted` ? It could be trakt changing the status to wanted. If you set it to skipped instead of ignored it wont do that.
