### ISSUE TITLE
Error getting caps xml for disabled usenet provider

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#5995]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master 
Commit: 1f124b31b16303a511c86717f11dd28b9cbf7b46 
Version: v2020.02.15-3 
Database Version: 44.1 
OS: W10 Pro
Browser: Edge
What you did: Reviewed Warnings
What happened: see log
What you expected: Did not expect this since that provider has been disabled
Logs:
```
	Line 3345: 2020-02-16 20:33:00 WARNING  WEBSERVER-CONFIGPROVIDERS :: Error getting caps xml for [Usenet-Crawler]
	Line 3489: 2020-02-17 08:32:53 INFO     WEBSERVER-CONFIGPROVIDERS :: SSL Error requesting url: 'https://api.usenet-crawler.com/api?apikey=**********&t=caps' Try disabling Cert Verification on the advanced tab of /config/general
	Line 3490: 2020-02-17 08:32:53 WARNING  WEBSERVER-CONFIGPROVIDERS :: Error getting caps xml for [Usenet-Crawler]
	Line 3862: 2020-02-18 10:15:44 INFO     WEBSERVER-CONFIGPROVIDERS :: SSL Error requesting url: 'https://api.usenet-crawler.com/api?apikey=**********&t=caps' Try disabling Cert Verification on the advanced tab of /config/general
	Line 3863: 2020-02-18 10:15:44 WARNING  WEBSERVER-CONFIGPROVIDERS :: Error getting caps xml for [Usenet-Crawler]
```
I frequently have this warning when I open Sickchill in the morning.
But I have **disabled** this provider in the UI, so why does it even bother to check?

![image](https://user-images.githubusercontent.com/18516066/74750001-017ffd00-5239-11ea-9278-5c801a388fcc.png)

Not a deal breaker, but it is an annoyance.

Is there some other place to disable the checking for this provider?  The provider has closed shop and does not look as if will be re-opening.

Thanks.

Ron

**Comment by miigotu** [comment]
It happens when you open the providers settings, because you have previously used it and it needs to know what to do if it were to be enabled. You shouldn't need to open that page everyday.

**Comment by ronrosenfeld** [comment]
@miigotu So if I don't open the Providers Settings page, the error will not recur?  (I can live with that).

**Comment by miigotu** [comment]
Exactly
