### ISSUE TITLE
Github personal token problem

### ISSUE THREAD

**Issue by thenamelessthing** [SickChill/SickChill#5999]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Ubuntu 16.04.3
Browser: at least Firefox or Google Chrome
What you did: setup github personal token
What happened:  In the branch version is always stuck with Loading spinning wheel...it is normal??
What you expected:

![image](https://user-images.githubusercontent.com/10235448/74861914-2186ed80-5319-11ea-89ef-42f6dd449ba3.png)

**Comment by miigotu** [comment]
Save and reload the page? Did you give the token the correct permissions?

**Comment by thenamelessthing** [comment]
I already check permission twice and reload the page. I also set token
directly in the conf file.

Le mer. 19 févr. 2020 4:19 p.m., miigotu <notifications@github.com> a
écrit :

**Comment by miigotu** [comment]
@thenamelessthing you cannot set it directly in the config file, because it gets encrypted before it is saved in the config.
