### ISSUE TITLE
Language problems?

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#6000]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop (tried to switch back, but it times out looking for other branches)
OS: windows 10
Browser: chrome
What you did: Opened the schedule
What happened: The schedule opened :p But tomorrow's split between "torsdag" and "thursday". "Torsdag" is the Norwegian name for "thursday" (Thor's day! Yay!)
What you expected: Only "thursday" :)

![image](https://user-images.githubusercontent.com/17053402/74873257-2cfd0780-535f-11ea-9e4e-a9fe3875a4a2.png)

**Comment by Tiwas** [comment]
Both my media center pc (hosting SC) and my regular PC have US English versions of Windows 10, btw

**Comment by Tiwas** [comment]
Oh, and this just goes on and on, so I don't know how to revert to 'master'

![image](https://user-images.githubusercontent.com/17053402/74873821-2de26900-5360-11ea-977e-2a7b3360211e.png)

**Comment by miigotu** [comment]
Has the translation issue cleared up after a mass update?
The git branch issue is separate, its a problem Im working on.

**Comment by Tiwas** [comment]
@miigotu Sorry. Forgot to update. Yeah, it disappeared. Thought it was relevant, though. I'll just chill about the branch issue.

Great work, though. SC is getting better and better :D
