### ISSUE TITLE
Player other than Kodi

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6003]
The play column only shows Kodi that I do not have..
Was looking for a way to define it to default player or to specify a player..
could not find a setting for it.
All I want to do is click on it to play that episode.

If I click on Kodi I get a box with no choices and a Play button or cancel.
If I click play it causes a few errors,

```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
It takes a lot of code to make it work for even 1 player. If you don't have Kodi enabled it shouldn't be showing a button at all. Other players will come gradually, it's a new feature, but many players do not support this way of playing a file. Be patient.
