### ISSUE TITLE
refresh of shows on startup causing issues..

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6005]
SickChill Info:
Branch: master
Commit: 1f124b31b16303a511c86717f11dd28b9cbf7b46
Database Version: 44.1
  Python Version:
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
  SSL Version:
OpenSSL 1.0.2t 10 Sep 2019
  OS:
Windows-7-6.1.7601-SP1
  Locale:
en_US.cp1252

What you did:  nothing started SickChill
What happened: it does a refresh of all shows
What you expected: refresh current shows

![image](https://user-images.githubusercontent.com/14140816/75068204-b8d87600-54bc-11ea-821f-4b4538829a33.png)

This show is no longer running..

![image](https://user-images.githubusercontent.com/14140816/75068277-e1f90680-54bc-11ea-95e1-0a8908b37f6d.png)

I have it paused..

![image](https://user-images.githubusercontent.com/14140816/75068365-081ea680-54bd-11ea-9d3b-d4446c53ecad.png)
![image](https://user-images.githubusercontent.com/14140816/75068512-4ae07e80-54bd-11ea-9e84-8809f174ea68.png)

It decided to download a few more;

In other cases information has also changed including air dates..
It's downloaded whole seasons that were already archived..

It's hard to keep up with what it's changing.. I have close to 400 downloads;
![image](https://user-images.githubusercontent.com/14140816/75068808-e8d44900-54bd-11ea-8290-da9d6fc3a0e0.png)

I don't know what is real or just another re-download
In one case it replace 2 seasons of one show with the seasons of another...

I have to keep stopping SickChill to cleanup...
Don't think it would be so bad if it was just doing the currently active shows.

Logs:
```
PASTE LOGS HERE
```

**Comment by nydave69** [comment]
Is there a way to turn this off...
I see there is an update but I'm holding off because it will cause another refresh of all shows.

**Comment by nydave69** [comment]
anything on this?

**Comment by miigotu** [comment]
6d44c2165685286a985cec69ad132fd4c20a0ba3
