### ISSUE TITLE
Python ssl errors in logs

### ISSUE THREAD

**Issue by rvhav** [SickChill/SickChill#6006]
Branch: master
Commit: 1f124b31b16303a511c86717f11dd28b9cbf7b46
Version: v2020.02.15-3
Database Version: 44.1

FreeBSD-12.0-RELEASE-p13-amd64-64bit-ELF 
Python Version:
2.7.17 (default, Jan 2 2020, 01:19:19) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.1 (tags/RELEASE_601/final 335540)] 
OpenSSL 1.1.1a-freebsd 20 Nov 2018 

Browser: FireFox 73

Many shows did not seem to get an updated air schedule. After doing mass-update on all shows they all got an up to date schedule. Not shure if was the trick to get everything running again, but the log still shows some python errors couple of times per day.

AA error: [Errno 0] Error
AA self._sslobj.do_handshake()
AA File "/usr/local/lib/python2.7/ssl.py", line 828, in do_handshake
AA self.socket.do_handshake()
AA File "/usr/local/sickbeard/lib/tornado/iostream.py", line 1310, in _do_ssl_handshake
AA self._do_ssl_handshake()
AA File "/usr/local/sickbeard/lib/tornado/iostream.py", line 1390, in _handle_read
AA self._handle_read()
AA File "/usr/local/sickbeard/lib/tornado/iostream.py", line 519, in _handle_events
AA return fn(*args, **kwargs)
AA File "/usr/local/sickbeard/lib/tornado/stack_context.py", line 277, in null_wrapper
AA handler_func(fd_obj, events)
AA File "/usr/local/sickbeard/lib/tornado/ioloop.py", line 888, in start
AA Traceback (most recent call last):
AA 2020-02-22 10:04:31 ERROR    Exception in callback None
AA error: [Errno 0] Error
AA self._sslobj.do_handshake()
AA File "/usr/local/lib/python2.7/ssl.py", line 828, in do_handshake
AA self.socket.do_handshake()
AA File "/usr/local/sickbeard/lib/tornado/iostream.py", line 1310, in _do_ssl_handshake
AA self._do_ssl_handshake()
AA File "/usr/local/sickbeard/lib/tornado/iostream.py", line 1390, in _handle_read
AA self._handle_read()
AA File "/usr/local/sickbeard/lib/tornado/iostream.py", line 519, in _handle_events
AA Traceback (most recent call last):
AA 2020-02-22 10:04:31 ERROR    Uncaught exception, closing connection.
AA 2020-02-22 10:04:30 ERROR    Could not open static file u'/usr/local/sickbeard/gui/slick/images/network/sony crackle.png'
AA 2020-02-22 10:04:30 ERROR    Could not open static file u'/usr/local/sickbeard/gui/slick/images/network/telemundo.png'

When i look at the installed python version on the FreeBSD it shows multiple versions.
py27-asn1crypto-0.24.0
python27-2.7.17_1
python36-3.6.9_3
python37-3.7.6
py27-openssl-19.0.0
sabnzbdplus-2.3.9

Are the 3.6/3.7 versions causing this the errors and is this the cause for not auto refreshing the schedules?

Thanks!

**Comment by miigotu** [comment]
Has nothing to do with python version. SC runs on python 2.7 (python27-2.7.17_1 in your case)

This is just a missing network image in that path and you using ssl

**Comment by rvhav** [comment]
thanks for the response
