### ISSUE TITLE
RFE: No update all showns from console

### ISSUE THREAD

**Issue by NunoHiggs** [SickChill/SickChill#6007]
Hello all,

Is there a cli or way to force an "Force full update" on a show form the console, without going into the webgui? 
I have done a script that forces the full scan form the id shows pulled form the API cmd's show, and then doing a curl in a for loop but it does seem a un-elegant approach to the problem.

I have looked in the API and found this:

{"data": {"api_commands": ["backlog", "episode", "episode.search", "episode.setstatus", "episode.subtitlesearch", "exceptions", "failed", "future", "help", "history", "history.clear", "history.trim", "logs", "logs.clear", "postprocess", "sb", "sb.addrootdir", "sb.checkscheduler", "sb.checkversion", "sb.dailysearch", "sb.deleterootdir", "sb.getdefaults", "sb.getmessages", "sb.getrootdirs", "sb.pausebacklog", "sb.ping", "sb.propersearch", "sb.restart", "sb.searchindexers", "sb.searchtvdb", "sb.searchtvrage", "sb.setdefaults", "sb.shutdown", "sb.subtitlesearch", "sb.update", "show", "show.addexisting", "show.addnew", "show.cache", "show.delete", "show.getbanner", "show.getfanart", "show.getnetworklogo", "show.getposter", "show.getquality", "show.pause", "show.refresh", "show.seasonlist", "show.seasons", "show.setquality", "show.stats", "show.update", "shows", "shows.stats"], "api_version": 5, "sr_version": "master"}, "message": "", "result": "success"}

If it was similar to the sickbeard API, it gather it should be sb.forcesearch, but no such command exists.
Is it possible to implement such a thing?

Thanks,
Nuno

**Comment by miigotu** [comment]
I think you no longer need this because i update every show now in the show updater until tvdb's updates api is fixed. Anyway, ip:port/api_builder will show you the api and docs for it. This one updates a show:
![image](https://user-images.githubusercontent.com/390379/75503226-1b40e300-59a3-11ea-9dba-7a0a1152ef9b.png)

**Comment by miigotu** [comment]
![image](https://user-images.githubusercontent.com/390379/75503271-3b70a200-59a3-11ea-96ff-af3d54e3bbed.png)
You shouldnt need to do this anymore because I changed the show updater to update every show each night, until tvdb fixes their updates api.
