### ISSUE TITLE
Error on read-only FS after updating

### ISSUE THREAD

**Issue by arantes555** [SickChill/SickChill#6010]
#### Branch/Commit: 
`v2020.02.15-1`

#### OS: 
Linux

#### What you did:
After updating from `v2020.02.11-3` to `v2020.02.15-1`, I cannot access the web interface anymore : I get `Looks like we do not have enough disk space to render the page! {error}`

I have to point out that on my installation, the sickrage code is on a Read-Only FS, and the data directory & config are on a writable FS.

#### What happened:
I believe I have tracked the issue to this commit and line : https://github.com/SickChill/SickChill/commit/a1e4590cc2ce24f985edf87241234ac435399dc7#diff-ca8b2565f5e99e9c38ee2c2a4a56b64fR841

I believe this line that just got changed :
```python
CACHE_DIR = ek(os.path.normpath, ek(os.path.join, PROG_DIR, "gui", GUI_NAME, "cache"))
```
should instead read:
```python
CACHE_DIR = ek(os.path.normpath, ek(os.path.join, DATA_DIR, "gui", GUI_NAME, "cache"))
```

#### What you expected:

The interface to work :)

#### Logs:

I cannot access the web interface to enable debug

**Comment by miigotu** [comment]
Create a symlink link from gui/slick/cache to a writable location, or mount a writable location to that directory. There is no other way for me to make the static file handler work without it being alongside the other static files.

**Comment by arantes555** [comment]
@miigotu The symlink trick worked, thank you.

However, I do consider this to be a trick. Having a cache directory in the middle of the code seems ... really ugly.

**Comment by miigotu** [comment]
It is, but I have no choice. Currently I have the code auto creating a symlink there (if it can write to that location ;)
