### ISSUE TITLE
New "exposed to the internet" feature doesn't work

### ISSUE THREAD

**Issue by identd113** [SickChill/SickChill#6013]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: d8032fa19c84e5b63c9cb2b4a6c053a07b253a7b
Version: v2020.02.24-2
Database Version: 44.1

OS: Darwin-19.3.0-x86_64-i386-64bit
Browser: Safari
What you did: Attempting to login, at home, using a publicly accessible hostname
What happened: I was presented with the "server has no password, so no access hacker" type message
What you expected: Be able to login as expected
Logs: Doesn't show anything, or at least not that I could find, as it SC was running a refresh

**Comment by drdelaney** [comment]
Same issue here. No visible entry in the log for any problem. Can gain access through the local network, just not public. Even when a username/password is set via the webui on the local network.

**Comment by sagig76** [comment]
Same issue here. latest update broke access. I work on a remote headless server and lost access to web interface although user/pass are set in config.ini

**Comment by miigotu** [comment]
Try updating again

**Comment by miigotu** [comment]
a5fb0066fd9125e94e8f6e903a84ab2fafba077e

**Comment by drdelaney** [comment]
> Try updating again

Negative. Updated and still getting the text saying I need to set up a username/password.

**Comment by miigotu** [comment]
@drdelaney I have to be cautious here, any person complaining about this could be the attacker that gained access to one of our user's system.

I will do some testing and verify my changes

**Comment by miigotu** [comment]
Anyone see a problem here? this is the current check:
```python
% if not (is_ip_private(remote_ip) or (sickbeard.WEB_PASSWORD and sickbeard.WEB_USERNAME)):
```

**Comment by drdelaney** [comment]
> @drdelaney I have to be cautious here, any person complaining about this could be the attacker that gained access to one of our user's system.
> 
> I will do some testing and verify my changes

Do what you need to do. I was passwordless because I run behind ombi. Had to ssh in to get local access to add the password. Also, how can I force an update from the "You are locked out, add a password" screen? Either way, thanks for looking into this.

**Comment by miigotu** [comment]
When you SSH'd in, did you stop SC first before editing the ini? It needs both the username and the password set.
You can update by stopping SC, cd to the dir, git pull, start SC

```python
>>> from sickbeard.helpers import is_ip_private
>>> sickbeard.WEB_USERNAME = '1'
>>> sickbeard.WEB_PASSWORD = sickbeard.WEB_USERNAME = '1'
>>> remote_ip = '212.222.222.222'
>>> not (is_ip_private(remote_ip) or (sickbeard.WEB_PASSWORD and sickbeard.WEB_USERNAME))
False
>>> sickbeard.WEB_PASSWORD = sickbeard.WEB_USERNAME = ''
>>> not (is_ip_private(remote_ip) or (sickbeard.WEB_PASSWORD and sickbeard.WEB_USERNAME))
True
>>> sickbeard.WEB_PASSWORD = sickbeard.WEB_USERNAME = '1'
>>> not (is_ip_private(remote_ip) or (sickbeard.WEB_PASSWORD and sickbeard.WEB_USERNAME))
False
>>> remote_ip = '127.0.0.1'
>>> not (is_ip_private(remote_ip) or (sickbeard.WEB_PASSWORD and sickbeard.WEB_USERNAME))
False
>>> sickbeard.WEB_PASSWORD = sickbeard.WEB_USERNAME = ''
>>> not (is_ip_private(remote_ip) or (sickbeard.WEB_PASSWORD and sickbeard.WEB_USERNAME))
False
>>> remote_ip = '192.168.99.1'
>>> not (is_ip_private(remote_ip) or (sickbeard.WEB_PASSWORD and sickbeard.WEB_USERNAME))
False
>>> sickbeard.WEB_PASSWORD = sickbeard.WEB_USERNAME = '1'
>>> not (is_ip_private(remote_ip) or (sickbeard.WEB_PASSWORD and sickbeard.WEB_USERNAME))
False
```

**Comment by drdelaney** [comment]
> When you SSH'd in, did you stop SC first before editing the ini? It needs both the username and the password set.
I added the user/pass from the webui on the local net (ssh port forwarding)


> You can update by stopping SC, cd to the dir, git pull, start SC
> 
Running in a docker instance. I was able to force the update via the localnet webui

**Comment by miigotu** [comment]
@drdelaney does it work ok now?

**Comment by drdelaney** [comment]
> @drdelaney does it work ok now?

Seeing no new updates. I think the confusion is when I asked how to update from the 'you need to access from a local network ip'. 

I am on the most current master checkout and it is not asking for a username and password, which was previously set up via the webui on localnet. I also cleared cache and refreshed a few times. Still not working.

**Comment by drdelaney** [comment]
Just enabled debug in the log. But it's going to take a few minutes for the "let's update all shows including paused ones" spam to clear.

**Comment by drdelaney** [comment]
> Just enabled debug in the log. But it's going to take a few minutes for the "let's update all shows including paused ones" spam to clear.

And naturally, debug doesn't seem to record access requests.

**Comment by miigotu** [comment]
Check that both the username and password are set in the ini:
`grep -P 'web_user|web_pass' config.ini`

**Comment by drdelaney** [comment]
They are:
`grep -P 'web_user|web_pass' config.ini
web_password = sickchill
web_username = sickchill`

**Comment by miigotu** [comment]
Dont post them here....

**Comment by drdelaney** [comment]
I just wanted something simple for testing... it will be changed when it's working. Not like it's super secure anyways.

**Comment by miigotu** [comment]
Seems I didnt publish it to master, should be there for you to update now

**Comment by drdelaney** [comment]
> Seems I didnt publish it to master, should be there for you to update now

Seems to be working now. Getting the login prompt and able to authenticate from my public IP.
