### ISSUE TITLE
Ssl error in log since last update

### ISSUE THREAD

**Issue by MartinHaimberger** [SickChill/SickChill#6015]
Branch/Commit: master
OS: windows
Browser: chrome

Since last update i get a lot of ssl eooros in the log

AA 2020-02-25 09:33:55 WARNING SSL Error on 21296 ('192.168.0.1', 61366): [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:590)

ssl cert verification is disabled in advanced settings.

Thx in advance

**Comment by miigotu** [comment]
There is more to that error, but it looks like you have an expired certificate for your SC. This has nothing to do with outgoing cert verification, this is for oncoming connections.

**Comment by MartinHaimberger** [comment]
hmmm the certificate will end 2026 so its not expired ... maybe generate a new one ?
But how ?

**Comment by miigotu** [comment]
I really don't know anything about your cert or setup, if it's a self generated cert, or even the whole traceback or surrounding log. Im not sure.

**Comment by miigotu** [comment]
I'll need more information, the lines starting with AA surrounding that log line and a few lines before and after the traceback

**Comment by MartinHaimberger** [comment]
Hi,

 looks like it has nothing to do with sickchill, it seems to be the actual chrome browser. With Firefox and Safari all is fine.

Thx so far
