### ISSUE TITLE
Cant open SickChill anymore on Synology NAS!

### ISSUE THREAD

**Issue by nadimalam** [SickChill/SickChill#6017]
Im trying to open SickChill on my Synology NAS, however I can't seem to open it anymore?!

Im constantly getting the following error message displayed on the SickChill URL:

> SickChill
> If you are the owner of this server, your SickChill installation is exposed to the internet without a password. You will need access to the local network where this machine is to set the password through the interface. Otherwise, you will need to stop SickChill and edit the config.ini manually before starting SickChill back up. This may seem like an inconvenience, but your logins and file system being exposed is much more inconvenient.

Does anyone have any idea why this is happening and how I can fix it?

Thanks

**Comment by thelan** [comment]
related to commit : https://github.com/SickChill/SickChill/commit/5d2611781e28a869d2049f9ea19bcccc42249780

**Comment by nadimalam** [comment]
> related to commit : [5d26117](https://github.com/SickChill/SickChill/commit/5d2611781e28a869d2049f9ea19bcccc42249780)

thank you for your quick response, I appreciate it. But I don't really have a clue how too apply the commit to my application? Im running SickChill through Synology Community Packages by adding the SickChill GitHub URL in the SickBeard Custom App.

Do I need to uninstall the current app and then reinstall it and add in the url again? If I did this would I loose all my setup in SickChill?

**Comment by BenjV** [comment]
Seems very obvious to me you exposed SickChill directly to the internet without setting a username/password for SickChill (very foolish I must add).

Solution is simple.
Don't expose SickChill to the internet directly.

**Comment by nadimalam** [comment]
> Seems very obvious to me you exposed SickChill directly to the internet without setting a username/password for SickChill (very foolish I must add).
> 
> Solution is simple.
> Don't expose SickChill to the internet directly.

Oh I see, yes I can access my NAS through the Synology.me URL, and also access the SickChill through that URL so that I can open it when I'm at work etc.. and don't have to be reliant to be at home to open it. How can I add a SickChill username and password? As I can't seem to open the webpage at all now to go to settings etc... Or would it open as normal when I go home and try to access it on my local network?

**Comment by thelan** [comment]
By reading the added code in this commit, it seems if the application see your are coming from an local network (RFC1918 ips) it will allow you to access it.

I think the idea behind this is to go from your local network then add a login / password in the settings > General Configuration > Interface. then add a pasword

**Comment by nadimalam** [comment]
> By reading the added code in this commit, it seems if the application see your are coming from an local network (RFC1918 ips) it will allow you to access it.
> 
> I think the idea behind this is to go from your local network then add a login / password in the settings > General Configuration > Interface. then add a pasword

Thanks so much, I will try this from my local network then when I go home tonight!!

**Comment by bogorad** [comment]
This is ridiculous and typical disregard for users! Those running Sickchill under Docker are left with a non-working system and no obvious way of fixing it. 

What I did to fix it: 

1. added 'network: host' to Sickchill entry in docker-compose.yml
2. restarted the container
3. connected to xxx:8081
4. set login/password
5. removed 'network: host'
6. restarted the container

Why did they have to put a lot (10+ million downloads on docker hub) of people through this misery is beyond me.

**Comment by miigotu** [comment]
Or just shut it down, edit the config.ini like the page says, and start it again. I think the clear instructions on the notice are very "obvious"

**Comment by bogorad** [comment]
> Or just shut it down, edit the config.ini like the page says, and start it again. I think the clear instructions on the notice are very "obvious"

Yeah, spent like half an hour trying to figure out what to edit in the config.ini - no luck, hence the docker trick. 

Maybe - just maybe - the message should include some details on what entries to edit?

**Comment by miigotu** [comment]
web_pass and web_user are fairly self explanatory.

**Comment by bogorad** [comment]
> web_pass and web_user are fairly self explanatory.

Let's agree to disagree. In any case, could you please add this info to the error page for the next person who suddenly stumbles into this?

**Comment by cherjr** [comment]
> web_pass and web_user are fairly self explanatory.

well, yes, but it didn't work for me, I tried.

**Comment by fatgeek** [comment]
I'm having the same issue. Running in Docker (linuxserver.io) on Unraid. Looks like I got an automatic update last night. My instance is in no way exposed to the internet. The error message says to manually edit the config.ini, bur doesn't offer any actual explanation on the error. The inplementation of this "feature" seems to have a pretty narrow view of how people use SickChill. I have no desire to need a user/pass for something only accessible from within my home network. At least allow the option of setting trusted subnets, or a switch to turn the check off completely.

**Comment by miigotu** [comment]
#6531
