### ISSUE TITLE
Backup fails 

### ISSUE THREAD

**Issue by MrHappy** [SickChill/SickChill#6019]
Backup fails and thereby also the update..

Branch/Commit: Master/55c97c3 (but had it with previous too, until recently this worked...)
OS: Windows 2019
Browser: not relevant
What you did: tried to update and tried manual backup
What happened: backup was not created
What you expected: a backup
Logs:
```
2020-02-25 18:23:43 INFO     WEBSERVER-HOME :: Config backup in progress...
2020-02-25 18:23:45 WARNING  WEBSERVER-HOME :: Zip creation error: path is on drive C:, start on drive e: 
2020-02-25 18:23:45 ERROR    WEBSERVER-HOME :: [9ce7837] Config backup failed, aborting update

2020-02-25 18:37:16 WARNING  WEBSERVER-CONFIGBACKUPRESTORE :: Zip creation error: path is on drive C:, start on drive e: 
```

**Comment by miigotu** [comment]
Your backup dir is a UNC path? you need to provide a drive letter for config backups to a different drive with how it currently works.

**Comment by miigotu** [comment]
Could you try changing sickbeard/helpers.py line 1198 to `a.write(f, ek(os.path.realpath, f))` please? And see if the backup works then manually.

**Comment by miigotu** [comment]
Actually that wont work. I need to backup cache and config/db separately I think

**Comment by MrHappy** [comment]
> 
> 
> Your backup dir is a UNC path? you need to provide a drive letter for config backups to a different drive with how it currently works.

If I do a manual backup and enter a path (e:\backup i.e.) it gives the same error as above
`2020-02-26 07:52:09 WARNING  WEBSERVER-CONFIGBACKUPRESTORE :: Zip creation error: path is on drive C:, start on drive e:`

**Comment by miigotu** [comment]
Not currently no.
