### ISSUE TITLE
Option to disable password check when "exposed to the internet"

### ISSUE THREAD

**Issue by tmcarr** [SickChill/SickChill#6020]
I recently started recieving the error about my install being open to the internet. While it might appear so the way the app is configured, I'm actually using Cloudflare Access to reach my installation and all other IPs are firewalled off... I would like an option to disable this check, even if its a hidden setting in config.ini.

I think this is the commit relevant to my issue: https://github.com/SickChill/SickChill/commit/1e67c6d063fe1cbcff6e58f3030b4d44b6737e7f

**Comment by miigotu** [comment]
How does authentication work with cloudflare? You can add basic auth headers to the request from the proxy

**Comment by tmcarr** [comment]
It handles OAuth on their end with whichever provider you choose, there are never credentials sent to me. (I'm using Google Auth in my setup...)

**Comment by tmcarr** [comment]
I guess another solution here is to be able to give Sickrage a list of trusted IPs... Cloudflare publishes their list on their site.

**Comment by miigotu** [comment]
Surely cloudflare has a way to pass an authentication token to the local service? I cannot imagine cloudflare requiring open authentication and only relying on spoofable remote up in a firewall?

**Comment by miigotu** [comment]
#6018

**Comment by tmcarr** [comment]
They offer no way to send credentials on based on the docs I'm reading. They offer JSON Web tokens to authenticate requests to services that implement it, but otherwise nothing else. FWIW SSL wont work without their cert(s) anyways. 

On another note, I dont really see the value in having my local reverse proxy inject basic auth credentials since any attacker will pass through said proxy anyways getting auth for free...

**Comment by tmcarr** [comment]
https://community.cloudflare.com/t/how-to-connect-with-basic-auth/61022

**Comment by miigotu** [comment]
@tmcarr Im interested in implementing jwt or another method, but not allowing an override to allow unprotected access to people who by and large are most likely to be either not sysadmins or are not very good ones.

**Comment by tmcarr** [comment]
Thats why I suggested an ini-only option... most folks wont read that much. Sadly, I'll likely be forced to just do the dumb basic auth hack in my reverse proxy for this which is just as bad.

**Comment by miigotu** [comment]
If you have a reverse proxy, just limit it to only localhost requests for that endpoint and add the basic auth. basic auth is perfectly fine on a local network.

If there is a way to implement jwt that helps, point me to some docs and ill get on it.

**Comment by tmcarr** [comment]
I dont understand? If the claim is that you're afraid someone can spoof cloudflare... having the proxy inject basic auth headers at any point does literally nothing other than let anyone through.

**Comment by tmcarr** [comment]
JWT docs are here: https://developers.cloudflare.com/access/setting-up-access/validate-jwt-tokens/

**Comment by miigotu** [comment]
very easy implementation xD, im nearly done. You will just need to provide the AUD and auth domain in settings =P

**Comment by miigotu** [comment]
@tmcarr could you try the cloudflare_jwt_login branch and configure it with your CFAccess? I need to know if it works without paying cloudflare lol.
The new settings are to be in the config.ini like this:
```
[Cloudflare]
auth_domain = ""
audience_policy ""
```

**Comment by naydichev** [comment]
I would also like to disable this option, I have sickchill behind an nginx proxy server that requires SSLMA to access.

**Comment by miigotu** [comment]
@naydichev you can pass basic auth headers in your nginx config.

I will not be putting an option to just disable authentication outright. There is always a way to pass a header or token

**Comment by naydichev** [comment]
@miigotu yes, I can do that and it does solve my particular issue. 

I still believe that you should allow people to opt out of this. It would be safer to allow them to disable it themselves, then for them to find other workarounds.

**Comment by miigotu** [comment]
In no world is it safer to allow them to disable it than to force them to enable SOME type of authentication.

I will add authentication methods as necessary, maybe even oauth using GitHub/Facebook/Google, but I won't add a feature to just expose themselves to the wolves.

In the software world you almost need to treat users like small children. If there's a knife on the floor that they can hurt themselves on they will.

**Comment by MasterCtrl** [comment]
i have sickchill installed and my synology and after updating today i am constantly met with this password check. i have reinstalled sickchill both through the synocommunity package and BenjV's package. I have no way to access the interface to setup the password, i have ssh'd into the nas and tried to set the username and password in the config.ini but with no success. What settings should i be looking for in the config? any help would be appreciated.

**Comment by miigotu** [comment]
@MasterCtrl stop SC before you edit the config.ini or the settings wont stick. Then edit web_username and web_password in config.ini and start it back up.

**Comment by MasterCtrl** [comment]
@miigotu I now have the web-username and web_password fields populated in the config.ini but i am still met with the same webpage telling me i need to set it up. is there something else i need to turn on?

**Comment by miigotu** [comment]
@MasterCtrl you must be editing the wrong config.ini, because the page never comes up of a username and password is set.

**Comment by tmcarr** [comment]
@miigotu I'll get to testing this tonight...
