### ISSUE TITLE
My SickChill is not exposed to the Internet but says it is, even over localhost

### ISSUE THREAD

**Issue by brianjmurrell** [SickChill/SickChill#6023]
Branch/Commit: master as of right now
OS: Linux
Browser: Chrome
What you did:
Opened a browser tab to http://localhost:8081/
What happened:
### SickChill
If you are the owner of this server, your SickChill installation is exposed to the internet without a password. You will need access to the local network where this machine is to set the password through the interface. Otherwise, you will need to stop SickChill and edit the config.ini manually before starting SickChill back up. This may seem like an inconvenience, but your logins and file system being exposed is much more inconvenient.

Your IP: ::1

If you are an attacker, the party is over.
What you expected:
The SickChill main page

This installation is (a) behind a firewall and (b) being accessed on the same machine as the browser via `localhost`.  It does NOT need a password.

**Comment by miigotu** [comment]
I didn't account for ip6. I will later

**Comment by brianjmurrell** [comment]
I just did.  For loopback, at least.
