### ISSUE TITLE
Unable to contact github, can't check for update

### ISSUE THREAD

**Issue by vitinhosessa** [SickChill/SickChill#6025]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Version: v2019.06.28-1
Database Version: 44.0
OS: Windows-10-10.0.18362
Browser: Chrome
What you did: checked for update
What happened: errors
What you expected: no errors, and update
Logs:
```
2020-02-26 22:46:37 ThreadPoolExecutor-0_0 :: git fetch origin --prune returned : (128) fatal: pack has 2 unresolved deltas fatal: index-pack failed
2020-02-26 22:46:37 ThreadPoolExecutor-0_0 :: Unable to contact github, can't check for update
```

I had already opened this issue:  https://github.com/SickChill/SickChill/issues/5813

I cannot solve it. Someone could help me with a step by step to solve this pls.

**Comment by miigotu** [comment]
Go to thre directory and do `git fsck --full && git fetch origin --prune && git pull`
If that succeeds all is fixed.

**Comment by miigotu** [comment]
Also, next time please reuse the existing issue. If you tag me anywhere on github I will see it, even on closed issues.
