### ISSUE TITLE
Can no longer connect to SickChill

### ISSUE THREAD

**Issue by TimSomers420** [SickChill/SickChill#6027]
I would have posted error logs, but I can't connect to SickChill to do that.

Running Windows 10
Python 2.7.13 and 3.5.2
Most recent (per the update feature) of SickChill

Last worked: 8am this morning
First noticed issue: 11:30pm this evening
Have rebooted machine with not improvement

Not familiar enough with the inner-workings of Python or SickChill core files to make educated guesses as to what's causing the issue.  Any help would be appreciated.

Thank you.

**Comment by knapekt** [comment]
I'm having the same issue, was working a couple of hours ago, and now cannot connect.  Re-starting the service and the VM it is hosted on has no effect.  All other stuff on that machine is working.

**Comment by huynguyen** [comment]
Might be related to this https://github.com/SickChill/SickChill/commit/3c4a005b20b7a7ef7be0e1ea3bb17e39f5461edb.

If you run the service manually and get the following error:
```
PS C:\SickRage> .\Python\python.exe .\SickRage\SickBeard.py --nolaunch --port=8081 --datadir=C:\\SickRage\\Data
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2a 19 Mar 2015) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File ".\SickRage\SickBeard.py", line 70, in <module>
    from .authentication import LoginHandler, LogoutHandler
  File "C:\SickRage\SickRage\sickchill\views\authentication.py", line 35, in <module>
    from .index import BaseHandler
  File "C:\SickRage\SickRage\sickchill\views\index.py", line 34, in <module>
    from jwt.algorithms import RSAAlgorithm as jwt_algorithms_RSAAlgorithm
ImportError: cannot import name RSAAlgorithm
```
You'll have to update manually with a `git pull` from within the `C:\SickRage\SickRage\`.

**Comment by miigotu** [comment]
```
cd path-to-sickchill
git pull
```

**Comment by labbean** [comment]
C:\SickChill\SickChill\sickchill>git pull
remote: Enumerating objects: 346, done.
remote: Counting objects: 100% (346/346), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 510 (delta 222), reused 345 (delta 222), pack-reused 164
Receiving objects: 100% (510/510), 2.67 MiB | 2.25 MiB/s, done.
Resolving deltas: 100% (222/222), completed with 39 local objects.
From https://github.com/SickChill/SickChill
   b375a7dbc..4d0657e88  master     -> origin/master
   b375a7dbc..4d0657e88  develop    -> origin/develop
 * [new tag]             v2020.02.26-2 -> v2020.02.26-2
 * [new tag]             v2020.02.26-3 -> v2020.02.26-3
 * [new tag]             v2020.02.27-1 -> v2020.02.27-1
 * [new tag]             v2020.02.27-2 -> v2020.02.27-2
error: Your local changes to the following files would be overwritten by merge:
        sickbeard/helpers.py
Please commit your changes or stash them before you merge.
Aborting
Updating b375a7dbc..4d0657e88

**Comment by miigotu** [comment]
@labbean you dont need to comment in more than one place, it just makes this harder.
![image](https://user-images.githubusercontent.com/390379/75474975-e9f5f200-5965-11ea-9a6e-e7c2e284ad5c.png)

**Comment by labbean** [comment]
Sorry... was searching and went and threw a paste in the wrong window, could not undo!

    On Thursday, February 27, 2020, 1:34:48 PM EST, miigotu <notifications@github.com> wrote:  
 
 
@labbean you dont need to comment in more than one place, it just makes this harder.
