### ISSUE TITLE
[SOLVED] ImportError: cannot import name RSAAlgorithm

### ISSUE THREAD

**Issue by NunoHiggs** [SickChill/SickChill#6028]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: linux, centos 7
Browser: any
What you did: nothing - auto update
What happened: sickchill did not start
What you expected: sickchill to start

Logs:
```

On startup, the sysctl daemon would report:  **ImportError: cannot import name RSAAlgorithm**
```
Solution:

yum -y install python-crypto python-jwcrypto.noarch 

After installing this packages sickchill started ok

**Comment by miigotu** [comment]
Or just update and it would start also. I wrapped the import in a try block.
