### ISSUE TITLE
"Server is exposed to the internet"-warning with reverse proxy/HTTP Auth

### ISSUE THREAD

**Issue by darkguy-git** [SickChill/SickChill#6034]
Branch/Commit: master
OS: Unraid 6.8.2/linuxserver Docker
Browser: Vivaldi 2.11.1811.33 (Windows 10 Pro, x64) [also tried various others under Windows 10 and Android with various IP adresses/connections)
What you did: Tried accessing Sickchill over the WebUI over the internet
What happened: Got the message that the server was reachable over the internet without authentication
What you expected: SickChill to work, as it sits behind a reverse proxy (nginx 1.16) with HTTP-Auth protection
Logs:
```
2020-02-27 19:25:35 WARNING  WEBSERVER :: Remote access was attempted by xx.xxx.xxx.xx
2020-02-27 19:26:48 WARNING  WEBSERVER :: Remote access was attempted by xx.xxx.xx.xxx
2020-02-27 19:26:55 WARNING  WEBSERVER :: Remote access was attempted by xx.xxx.xx.xxx
2020-02-27 19:27:28 WARNING  WEBSERVER :: Remote access was attempted by xx.xxx.xx.xxx
2020-02-27 19:32:00 WARNING  WEBSERVER :: Remote access was attempted by xx.xxx.xx.xxx
2020-02-27 19:48:50 WARNING  WEBSERVER :: Remote access was attempted by xx.xxx.xx.xxx
2020-02-27 19:51:44 WARNING  WEBSERVER :: Remote access was attempted by xx.xxx.xx.xxx

```

I run SickChill as a **Docker container** on an **Unraid** server (using **linuxserver's** Docker). I also run linuxserver's letsencrypt Docker, which provides an **nginx**-Webserver. I configured nginx as a remote proxy and use **Basic HTTP Authentication** to access various web services behind it.

The **reverse proxy** is configued to ask for a username and password, unless the accessing IP is my own static IP address at home; when accessing anything behind nginx remotely, I type in the username/password or use VPN to access my network (and using my home IP in the process) to bypass authentication. Both methods worked with SickChill up to the v2020.02.24-2  release of SickChill. I also tried removing my static IP to be allowed access, but that also chaned nothing.

Now SickChill always displays the "your server is accessible over the internet" message, unless I access it from the local network; I briefly looked at the code and it looks like it either checks if a password is set in the config or if the accessing IP address is a private one. This of course, does not consider my use case.

There already is an option to accept proxy headers, so maybe add another one to check is a "Authorization: Basic" header is being sent with the request, as defined in [RFC 7617](https://tools.ietf.org/html/rfc7617) as another valid options to access SickChill over the web? (the way I understand it, the authentication has to succeed in order to access SickChill, at which point the check could be made).

**Comment by miigotu** [comment]
You will need to set a username and password in SC, and then add a basic auth header in your nginx config in the sickchill route.
This is how you create the token:
https://github.com/SickChill/SickChill/issues/6018#issuecomment-591069959
and the comment after that shows how to set the header in apache. I think you should be able to figure out how to add the header in nginx fairly easy, so please post it back here (with a dummy token) after you do please.

**Comment by darkguy-git** [comment]
Seems using the same username/password in SickChill that gets used with HTTP Basic Auth bypasses the message.
