### ISSUE TITLE
[APP SUBMITTED]: Cloudflare has blocked this request (Code 1020 Detected).

### ISSUE THREAD

**Issue by sanomi78** [SickChill/SickChill#6037]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@4d0657e881dbd773d3b2326933c52e6501345fad
Link to Log: https://gist.github.com/0f41fc12d7791fff749a39af0f844e08
### ERROR
```
SEARCHQUEUE-BACKLOG-373992 :: [LimeTorrents] :: [4d0657e] Request failed: Cloudflare has blocked this request (Code 1020 Detected). (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by JonathanLydall** [comment]
I noticed this evening that my SickChill wasn't starting up on Windows, when trying from a console I get the following error:
```
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2t  10 Sep 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "..\SickRage\SickBeard.py", line 70, in <module>
    from sickchill.views.server_settings import SRWebServer
  File "C:\SickRage\SickRage\sickchill\views\__init__.py", line 23, in <module>
    from .authentication import LoginHandler, LogoutHandler
  File "C:\SickRage\SickRage\sickchill\views\authentication.py", line 35, in <module>
    from .index import BaseHandler
  File "C:\SickRage\SickRage\sickchill\views\index.py", line 34, in <module>
    from jwt.algorithms import RSAAlgorithm as jwt_algorithms_RSAAlgorithm
ImportError: cannot import name RSAAlgorithm
```

I downloaded the latest 2.7 version, but still the same error. I'm not familiar with Python, but if it's possible to update OpenSSL in the Python install, then that may fix the issue.

I don't know if Python 3 would work with SickChill.

**Comment by JonathanLydall** [comment]
A `git pull` allowed SickChill to start up again, but the warning still remains:

`DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2t  10 Sep 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.`

**Comment by riddlenl** [comment]
Same here, SC does not want to start.

**Comment by sanomi78** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@4d0657e881dbd773d3b2326933c52e6501345fad
Link to Log: https://gist.github.com/0956d58d8b4ac3b4c1e60a77958de5d7
### ERROR
```
SEARCHQUEUE-BACKLOG-373992 :: [LimeTorrents] :: [4d0657e] Request failed: Cloudflare has blocked this request (Code 1020 Detected). (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sanomi78** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@4d0657e881dbd773d3b2326933c52e6501345fad
Link to Log: https://gist.github.com/8163a094e63236622769aa8d11f56d56
### ERROR
```
SEARCHQUEUE-BACKLOG-278125 :: [LimeTorrents] :: [4d0657e] Request failed: Cloudflare has blocked this request (Code 1020 Detected). (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sanomi78** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@4d0657e881dbd773d3b2326933c52e6501345fad
Link to Log: https://gist.github.com/38d1b8c0c78d87d9aa335e5f71830748
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [LimeTorrents] :: [4d0657e] Request failed: Cloudflare has blocked this request (Code 1020 Detected). (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sanomi78** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@4d0657e881dbd773d3b2326933c52e6501345fad
Link to Log: https://gist.github.com/50f4678ccb4e15863db8ecdba961d421
### ERROR
```
SEARCHQUEUE-BACKLOG-146651 :: [LimeTorrents] :: [4d0657e] Request failed: Cloudflare has blocked this request (Code 1020 Detected). (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sanomi78** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@4d0657e881dbd773d3b2326933c52e6501345fad
Link to Log: https://gist.github.com/4dbdccd57bdb7bddc76b84d8f5d47417
### ERROR
```
SEARCHQUEUE-BACKLOG-80522 :: [LimeTorrents] :: [4d0657e] Request failed: Cloudflare has blocked this request (Code 1020 Detected). (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sanomi78** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@4d0657e881dbd773d3b2326933c52e6501345fad
Link to Log: https://gist.github.com/0b9991352f50e38159a7f74ed57badfa
### ERROR
```
SEARCHQUEUE-BACKLOG-271671 :: [LimeTorrents] :: [4d0657e] Request failed: Cloudflare has blocked this request (Code 1020 Detected). (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sanomi78** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@4d0657e881dbd773d3b2326933c52e6501345fad
Link to Log: https://gist.github.com/769d846bdb9a6ad513c432901fee1af7
### ERROR
```
SEARCHQUEUE-BACKLOG-311902 :: [LimeTorrents] :: [4d0657e] Request failed: Cloudflare has blocked this request (Code 1020 Detected). (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sanomi78** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@4d0657e881dbd773d3b2326933c52e6501345fad
Link to Log: https://gist.github.com/f9318f21a0e433ae49d8678776be80ae
### ERROR
```
SEARCHQUEUE-BACKLOG-269641 :: [LimeTorrents] :: [4d0657e] Request failed: Cloudflare has blocked this request (Code 1020 Detected). (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sanomi78** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@4d0657e881dbd773d3b2326933c52e6501345fad
Link to Log: https://gist.github.com/5ae5a981aca458c6799818cfd2b0207c
### ERROR
```
SEARCHQUEUE-BACKLOG-75692 :: [LimeTorrents] :: [4d0657e] Request failed: Cloudflare has blocked this request (Code 1020 Detected). (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by sanomi78** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@efafac2893be1b91a8adbe3c0a1ae0eb60a7f511
Link to Log: https://gist.github.com/504e404d2ec3cb0feda06aa44ab941ab
### ERROR
```
SEARCHQUEUE-MANUAL-364093 :: [LimeTorrents] :: [efafac2] Request failed: Cloudflare has blocked this request (Code 1020 Detected). (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
