### ISSUE TITLE
Can't access /home, instantly redirect to /login

### ISSUE THREAD

**Issue by Silentbob1402** [SickChill/SickChill#6038]
![Capture d’écran 2020-02-29 à 16 03 21](https://user-images.githubusercontent.com/2717141/75609958-6414ab00-5b0d-11ea-98e3-57b81bc8fec8.png)
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/4d0657e881dbd773d3b2326933c52e6501345fad
OS: MacOs Sierra 10.12.6
Browser: Chrome / 80.0.3987.122
What you did: I entered my login and password on the login page
What happened: Despite typing the good login/password, I "stayed" on the login page, without any error message. After investitation in the network tab, I realise I got sent to the home page and had a 302 redirect that send me back to the login page
What you expected: I expected to get to the homepage
Logs:
2020-02-29 16:00:13 INFO     WEBSERVER :: User logged into the SickChill web interface
2020-02-29 16:00:39 INFO     WEBSERVER :: User logged into the SickChill web interface

**Comment by hey101** [comment]
I am also currently having this same issue. I tried clearing browser cache, using a different device, restarting SickChill, and doing a manual update. It still runs fine in the background as new shows get added to my download queue and then processed, but the login page just redirects back to the login page with no errors in the log or on the page itself.

**Comment by miigotu** [comment]
@Silentbob1402 if you set your username/password manually in the config, check that `encryption_version = 0` otherwise the config is supposed to have encrypted passwords.

Otherwise, using a reverse proxy does require to pass basic auth headers or work in jwt auth.

**Comment by hey101** [comment]
I just got mine finally fixed. 
If you use Nginx for a reverse proxy you have to edit `/etc/nginx/sites-available/reverse`
and add under SickChill `proxy_set_header Authorization "Basic dXNlcm5hbWU6cGFzc3dvcmQ=";`

`dXNlcm5hbWU6cGFzc3dvcmQ=` is the base64 encoded `username:password`. Use the same credentials that you use to login into SickChill
