### ISSUE TITLE
TheTVDB show info missing.

### ISSUE THREAD

**Issue by pejub** [SickChill/SickChill#6040]
Hi,

I have Star Wars: The Clone Wars configured, The ID is 83268. Searching for that ID at the TheTVDB site give me the correct show, but my SickChill don't show the same information.

I see nothing in the log related to this, hence no log attached.

How do I fix this? I have obviously removed and re-added the show several times.

/Per

**Comment by BenjV** [comment]
Ask tvdb to fix it.
Their Api is not always returning all the information they have available on there webite.
