### ISSUE TITLE
Push notification enhancement for updates

### ISSUE THREAD

**Issue by procdaddy11** [SickChill/SickChill#6041]
Please include the commit url when update happens so that we can see what’s changed.

**Comment by miigotu** [comment]
On which notifier...

**Comment by procdaddy11** [comment]
When SickChill updates

**Comment by miigotu** [comment]
You need to be more specific. We have like 15 notifiers. I don't mind updating one notifier.
But we already show the diff url in the UI before an update, log the diff url, and sent the commit in push notifications.

**Comment by procdaddy11** [comment]
![A963D81D-50FB-44F8-A6F9-6D96CEC47B0E](https://user-images.githubusercontent.com/1616899/79802048-e60e9c80-8324-11ea-825c-76b104891165.jpeg)

**Comment by miigotu** [comment]
What notification provider. Where is that being sent.

**Comment by procdaddy11** [comment]
Pushover

**Comment by miigotu** [comment]
This isnt an option, because we don't know your previous commit by the time this notification is sent. Very easy to come to this page and see though, or disable auto update and a link is shown that takes you to the diff before you click update.
