### ISSUE TITLE
Massive Git Objects/Pack folder

### ISSUE THREAD

**Issue by simonhepworth69** [SickChill/SickChill#6044]
I can't enable debugging because sickchill won't run.

My Raspberry Pi is totally out of space and it's because of the sickrage/git/objects/pack folder which has ballooned to 23Gb - any idea what to do?

**Comment by simonhepworth69** [comment]
I fixed it, removed 20gb worth of tmp_ files. 

Any idea why this happened?

**Comment by miigotu** [comment]
Try
```
git gc --prune=now
git remote prune
git gc --aggressive
```

**Comment by simonhepworth69** [comment]
Thanks!
