### ISSUE TITLE
mass remove

### ISSUE THREAD

**Issue by brianjmurrell** [SickChill/SickChill#6072]
The mass editing feature of SickChill is pretty sick.  :-)

What I really miss though is a mass _remove_ function in that feature.

Let's say I filter the list of shows by _status_ **Ended** and then just want to remove all of those shows.  I don't see any way to do that.  Having to remove them individually can be pretty tedious.

**Comment by miigotu** [comment]
This is already there in mass update:
![image](https://user-images.githubusercontent.com/390379/76146877-f4e70b80-6064-11ea-8158-c642fa462401.png)

**Comment by miigotu** [comment]
If you dont see it, scroll the table to the right or increase your window size.

**Comment by brianjmurrell** [comment]
Ah, yes, it was hiding off on the right and I had to utilise the widget scrollbar to see it.

One interesting enhancement might be something between _Remove_ and _Delete_ where shows with no episodes still present are deleted, but any shows with episodes still present are just removed.

In any case, thanks for the pointer on the scrollbar.  I didn't notice it before.
