### ISSUE TITLE
Has anyone figured this out yet its been a week - Branch version hung (spinning) on Branch Version

### ISSUE THREAD

**Issue by cadmuslabslex** [SickChill/SickChill#6073]
Branch/Commit: Master "LATEST"
OS: Windows
Browser: SAFARI
What you did: Everything correctly, this may not be a token problem, I have see this before. Token successfully generated with all specified permissions, I have also generated a token with all permissions which gave the same result.
What happened: Branch Version stuck on loading
What you expected: To see a list of branches, and to be able to checkout branches via the UI.

Has anyone figured this out yet its been a week

**Comment by miigotu** [comment]
I dont care if its a year, don't create duplicate issues. This was such a minor thing to be upset about.
