### ISSUE TITLE
containsAtLeastOneWord function could return unexpected results due to regexp being too specific

### ISSUE THREAD

**Issue by markprins** [SickChill/SickChill#6075]
Probably since containsAtLeastOneWord (https://github.com/SickChill/SickChill/blob/master/sickbeard/show_name_helpers.py#L68 ) has been made, it seems to me that it will misbehave in certain conditions.

The logic of the function specifies that it has to be preceded and/or followed by a word, but it is not allowed to be _part of a word_

So when wanting to require (or ignore) words it won't allow partial words.

For example:

ignore word: "Bar"
name: "Seriesname.Foo.Bar.mkv"

It matches and ignores the release

ignore word: "Bar"
name: "Seriesname.FooBar.mkv"

It won't match the release as "Bar" is not a word.

When testing using:
```
print(containsAtLeastOneWord('Seriesname.Foo.Bar.mkv', ['Bar']))
print(containsAtLeastOneWord('Seriesname.FooBar.mkv', ['Foo']))
print(containsAtLeastOneWord('Seriesname.FooBar.mkv', ['Bar']))
print(containsAtLeastOneWord('Seriesname.FooBar.mkv', ['FooBar']))
print(containsAtLeastOneWord('Seriesname.FooBar.mkv', ['foobar']))
```

It results in:

```
Debug:
containing words entered:Seriesname.Foo.Bar.mkv:['Bar']
iterating:Bar:(^|[\W_])Bar($|[\W_]):Seriesname.Foo.Bar.mkv
(^|[\W_])Bar($|[\W_]):Seriesname.Foo.Bar.mkv
Result:
Bar

Debug:
containing words entered:Seriesname.FooBar.mkv:['Foo']
iterating:Foo:(^|[\W_])Foo($|[\W_]):Seriesname.FooBar.mkv
(^|[\W_])Foo($|[\W_]):Seriesname.FooBar.mkv
Result:
False

Debug:
containing words entered:Seriesname.FooBar.mkv:['Bar']
iterating:Bar:(^|[\W_])Bar($|[\W_]):Seriesname.FooBar.mkv
(^|[\W_])Bar($|[\W_]):Seriesname.FooBar.mkv
Result:
False

Debug:
containing words entered:Seriesname.FooBar.mkv:['FooBar']
iterating:FooBar:(^|[\W_])FooBar($|[\W_]):Seriesname.FooBar.mkv
(^|[\W_])FooBar($|[\W_]):Seriesname.FooBar.mkv
Result:
FooBar

Debug:
containing words entered:Seriesname.FooBar.mkv:['foobar']
iterating:foobar:(^|[\W_])foobar($|[\W_]):Seriesname.FooBar.mkv
(^|[\W_])foobar($|[\W_]):Seriesname.FooBar.mkv
Result:
foobar
```

An easy fix would be to just match everything and modify the regexp to something like:
`^.*{0}.*$`

When running the same as before, but now with the "fix" it results in:

```
Debug:
containing words entered:Seriesname.Foo.Bar.mkv:['Bar']
iterating:Bar:(^.*)Bar(.*$):Seriesname.Foo.Bar.mkv
(^.*)Bar(.*$):Seriesname.Foo.Bar.mkv
Result:
Bar

Debug:
containing words entered:Seriesname.FooBar.mkv:['Foo']
iterating:Foo:(^.*)Foo(.*$):Seriesname.FooBar.mkv
(^.*)Foo(.*$):Seriesname.FooBar.mkv
Result:
Foo

Debug:
containing words entered:Seriesname.FooBar.mkv:['Bar']
iterating:Bar:(^.*)Bar(.*$):Seriesname.FooBar.mkv
(^.*)Bar(.*$):Seriesname.FooBar.mkv
Result:
Bar

Debug:
containing words entered:Seriesname.FooBar.mkv:['FooBar']
iterating:FooBar:(^.*)FooBar(.*$):Seriesname.FooBar.mkv
(^.*)FooBar(.*$):Seriesname.FooBar.mkv
Result:
FooBar

Debug:
containing words entered:Seriesname.FooBar.mkv:['foobar']
iterating:foobar:(^.*)foobar(.*$):Seriesname.FooBar.mkv
(^.*)foobar(.*$):Seriesname.FooBar.mkv
Result:
foobar

```

However someone has probably thought the reg-exp through so I wouldn't want to just change it.

**Comment by miigotu** [comment]
It isnt unexpected behavior, its supposed to be that way. If you want to require/ignore Foobar you add Foobar. Thats why its called containsAtLeatsOne__Word__

**Comment by markprins** [comment]
Yeah, I guessed as much. Then it's probably best to disregard and close the issue :)

I've modified my local checkout to let the regexp be a bit more greedy. It's probably an edge case situatie and not what everybody else wants/expects.

Thanks for taking the time to reply!

**Comment by miigotu** [comment]
I guess it could be made to allow a regex or wildcard in the word and match that way but it would open a whole other can of worms
