### ISSUE TITLE
Change AIR DATES DB to Glotz after commit 06.01.2020

### ISSUE THREAD

**Issue by hyperbit00** [SickChill/SickChill#6076]
### Before submitting your issue:
After the Commit at 06.01.2020 the tvdb was changed and some sources was changed.

How can we use now Glotz.info for the airdates?

Before we had to made some changes in indexers/indexer_config.py , but this file is gone

**Comment by BenjV** [comment]
That's the problem with hacking the sources.
Just don't do that would be my advise.

**Comment by miigotu** [comment]
Rewrite the patch you used to do it before.
