### ISSUE TITLE
Q - How to getrid of unwanted stings in the filename

### ISSUE THREAD

**Issue by fadern** [SickChill/SickChill#6079]
Hi,
Im just wondering how or if sickchill supports removing unwanted additions to the original filenames. Some indexers/uploaders add their own tags like 4P, asrequested, request, rakuvfinhel, xpost. These extra tags makes sickchill confused and it makes sickchill rename the files incorrectly.
example
Tom.Clancys.Jack.Ryan.S02E07.Dios.y.Federación.1080p.WEB.DL-xpost

**Comment by miigotu** [comment]
xpost isnt an added string, and does not confuse SC. xpost is what we call the "release group" and belongs there.

I imagine it is failed to match because it does not say x264 or x265 or divx or xvid or whatever compression it uses.

**Comment by fadern** [comment]
So do these have two releasegroups?

 RBG.2018.720p.BluRay.DTS.x264-FuzerHD-xpost
Narcos.S03E01.1080p.BluRay.x264-SHORTBREHD-xpost

**Comment by fadern** [comment]
And Sonarr sees these as none legit groups

https://github.com/Sonarr/Sonarr/pull/2984
https://github.com/Sonarr/Sonarr/commit/9744873e7a305c1d6606f773f55f84b30ba0c776

**Comment by miigotu** [comment]
Those 2 release names those are not release groups. I will add xpost to our sanitizer.
