### ISSUE TITLE
qbittorrent: Unable to send torrent; 404 for http://localhost:8081/command/download

### ISSUE THREAD

**Issue by morphine00** [SickChill/SickChill#6080]
**Branch/Commit:** master  c31c4f89d3cd0ca841c604d034cb371251684572
**OS:** Windows 10 Professional
**Browser:** Chrome
**What you did:** Searched for a show episode.
**What happened:** Episode back to "Wanted," log shows the torrent didn't get into qBitTorrent
**What you expected:** Torrent would be added to qBitTorrent
**Logs:**
```
2020-03-10 00:34:41 WARNING SEARCHQUEUE-MANUAL- :: qbittorrent: Unable to send Torrent
2020-03-10 00:34:41 INFO SEARCHQUEUE-MANUAL- :: Request failed: 404 Client Error: Not Found for url: http://localhost:8081/command/download ()
```

**Comment by miigotu** [comment]
Start qbittorrent....

**Comment by morphine00** [comment]
- qBittorrent 4.2.1 is running, and its execution log doesn't show anything.
- The "Test Connection" button in SickChill brings up "Success: Connected and Authenticated."
- Going to http://localhost:8081 brings up the qBitTorrent web UI working okay.
- Trying to manually go to /command/download goes to a 404.

Maybe something changed in a recent version of qBitTorrent?

**Comment by miigotu** [comment]
There are 2 different clients for qbittorent in SC, make sure you are selecting "New qBittorent" in the client config.

**Comment by morphine00** [comment]
And there we go, "qBitTorrent APIv2" and it works. Sorry, this is an old install of SickChill/Rage and I wasn't even aware that there had been an API change for qBitorrent.

**Comment by morphine00** [comment]
Thanks!
