### ISSUE TITLE
The Late Show with Stephen Colbert

### ISSUE THREAD

**Issue by marcb1387** [SickChill/SickChill#6090]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: efafac2893be1b91a8adbe3c0a1ae0eb60a7f511
OS: Linux-4.4.0-133-generic-x86_64-with-Ubuntu-16.04-xenial
Browser: Chrome
What you did: Tried to add The Late Show with Stephen Colbert
What happened: the connection to the TVDB timed out 
What you expected: the show to be added 

I have been having trouble for quite some time getting The Late Show with Stephen Colbert to update for new episodes. I usually can manually force a full update but since the latest commit that has not worked. it would not load any episode information or update. I delete the show out of sickchill but now im unable to re-add it due to TVDB timing out and not finding new shows. i have also made an API key and added it into coinfig.ini but it continues to timeout and not get added via new or by selecting the existing folder. It has the correct series ID 289574 but will not add. 

Logs:
```
2020-03-12 22:37:59 INFO SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2020-03-12 22:37:59 INFO SHOWQUEUE-ADD :: 289574: Unable to find the show in the database
2020-03-12 22:37:49 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /media/Shows/TV Shows/The Late Show with Stephen Colbert
```

**Comment by miigotu** [comment]
This is an issue on thetvdb, they are working on it but there is nothing we can do on this end.
