### ISSUE TITLE
Re-downloading everything!

### ISSUE THREAD

**Issue by utdrmac** [SickChill/SickChill#6092]
What happened with the latest update? Been using SickChill for 2+ years. Never had this happen. Seems that since the most recent update, SC has decided for unknown reasons to REDOWNLOAD everything in my library. Episodes that were already downloaded (been downloaded for years) have started to download again. I have not changed anything in my setup in the past 3 months. SC does auto-updates. This is crazy! What setting got enabled that is causing this? How do I make it stop? Is there a patch/fix for this coming soon?

**Comment by jura4** [comment]
I confirm this issue. _Ignored_ episodes changed to _wanted_ without user action. 
Does not happen on all shows, only 2 out of 50.

**Comment by wallacebrf** [comment]
i am getting this, and before it happens, the entire show's episode content gets deleted. then it re-syncs with TVDB and BAM it has all of the episodes marked as "wanted" and proceeds with re downloading the entire damn show. the log file simply shows it is permanently deleting the episode.

**Comment by miigotu** [comment]
TVDB causing this with their broken api.

**Comment by miigotu** [comment]
I'll be adding a new indexer over the next few days.

**Comment by utdrmac** [comment]
@miigotu Can we please leave this open until it's fixed?
This will make it auto-close when you create/merge the PR which fixes the issue: https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#closing-an-issue-in-the-same-repository

**Comment by miigotu** [comment]
You expect me to leave 50 duplicates open and tag them all with a commit? Lol no thanks.

**Comment by utdrmac** [comment]
Tag with the PR with the issue # and  the issue auto-closes when the PR merges. No need to tag each issue, that's nuts. Just tag the PR. One-n-done.

**Comment by miigotu** [comment]
You're missing the point. If you have 50 open issues for 1 problem, you have 50 issue numbers to put into the commit. Just use the same issue, ill tag that issue, and auto close it with one issue. If its 2 or 3 ill usually do that, but im not gonna be blasted with spam from dozens of duplicate issues.

If you want to make a PR and tag dozens of issues in the commit message, have at it, otherwise you manage your projects your way, ill manage mine my way.
