### ISSUE TITLE
Trying to add a show twice

### ISSUE THREAD

**Issue by krash1220** [SickChill/SickChill#6093]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:Master
OS:Windows 10 
Browser:Chrome
What you did:Tried adding Fear The Walking Dead
What happened: 2020-03-13 21:47:38 SHOWQUEUE-ADD :: [b2d7ac1] Error with theTVDB, not creating episode list: Unknown error while authenticating. Check your api key or your user/userkey
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by jellobello** [comment]
I'm having the same issue when adding a new show. On the first force refresh it failed and the second attempt to refresh about 10 minutes later worked.

Branch: master
Commit: b2d7ac109604ed7585ba0b56c53fcf93e4f2fadd
Version: v2020.03.13-6
Database Version: 44.1
Python Version: 2.7.9 (default, Sep 9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]
SSL Version: OpenSSL 1.0.2d 9 Jul 2015
OS: FreeBSD-11.0-RELEASE-amd64-64bit-ELF
Locale: en_US.UTF-8

LOG (debug):
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, language=show.lang).all()
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickchill/show/indexers/tvdb.py", line 94, in episodes
AA result = target(*args, **kwargs)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA for series_episode in self.idxr.episodes(self):
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 526, in loadEpisodesFromIndexer
AA self.show.loadEpisodesFromIndexer()
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/show_queue.py", line 491, in run
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, language=show.lang).all()
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickchill/show/indexers/tvdb.py", line 94, in episodes
AA result = target(*args, **kwargs)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA for series_episode in self.idxr.episodes(self):
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 526, in loadEpisodesFromIndexer
AA self.show.loadEpisodesFromIndexer()
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/show_queue.py", line 491, in run
AA Traceback (most recent call last):
2020-03-14 10:41:14 ERROR SHOWQUEUE-ADD :: [b2d7ac1] Error with theTVDB, not creating episode list: Unknown error while authenticating. Check your api key or your user/userkey

**Comment by cgatesman** [comment]
I created a new issue on this (#6095), because the title of this issue is very poor and misleading.
