### ISSUE TITLE
Problem with adding new show

### ISSUE THREAD

**Issue by 03397** [SickChill/SickChill#6096]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Branch: master
Commit: b2d7ac109604ed7585ba0b56c53fcf93e4f2fadd
Version: v2020.03.13-6
Database Version: 44.1
OS: Linux-3.4.6-x86_64-with-glibc2.2.5
Browser: Chrome

```
2020-03-14 21:38:09 WEBSERVER-ADDSHOWS :: [b2d7ac1] Failed doing webui callback: Traceback (most recent call last):
File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/views/index.py", line 215, in async_call
result = function(**kwargs)
File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/views/manage/add_shows.py", line 526, in addNewShow
s = sickchill.indexer.series_by_id(indexerid=indexer_id, indexer=indexer, language=indexerLang)
File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/handler.py", line 156, in series_by_id
series = self.indexers[indexer].series(id=indexerid, language=language)
File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/wrappers.py", line 44, in wrapper
result = target(*args, **kwargs)
File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/tvdb.py", line 59, in series
result.info(language=kwargs.get('language'))
File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/series.py", line 64, in info
response = self._GET(path)
File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 149, in _GET
return self._request('GET', path, params=params, cleanJson=cleanJson)
File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 142, in _request
return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 126, in _request
self._set_token_header(forceNewToken)
File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 91, in _set_token_header
self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 122, in get_token
raise AuthenticationError(error)
AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
```
When I try to add a new show a get an error
search timed out, try again or try another indexer

I can log in to tvdb.com just fine and I do not have any kind of issue with my connection

**Comment by 03397** [comment]
In addtion, If I try several times then it continues to the next screen but when I Add Show it never ends

**Comment by 03397** [comment]
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/series.py", line 64, in info
AA result.info(language=kwargs.get('language'))
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/tvdb.py", line 59, in series
AA result = target(*args, **kwargs)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA series = self.indexers[indexer].series(id=indexerid, language=language)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/handler.py", line 156, in series_by_id
AA s = sickchill.indexer.series_by_id(indexerid=indexer_id, indexer=indexer, language=indexerLang)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/views/manage/add_shows.py", line 526, in addNewShow
AA result = function(**kwargs)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/views/index.py", line 215, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/concurrent/futures/thread.py", line 63, in run
AA return self.__get_result()
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/concurrent/futures/_base.py", line 455, in result
AA value = future.result()
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tornado/gen.py", line 1055, in run
AA results = yield self.async_call(method)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/views/index.py", line 193, in get
AA yielded = self.gen.throw(*exc_info)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tornado/gen.py", line 1063, in run
AA raise_exc_info(self._exc_info)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tornado/concurrent.py", line 238, in result
AA value = future.result()
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tornado/gen.py", line 1055, in run
AA result = yield result
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tornado/web.py", line 1511, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol=u'http', host='192.168.10.105:7073', method='POST', uri='/addShows/addNewShow', version='HTTP/1.1', remote_ip='192.168.10.23', headers={'Origin': 'http://192.168.10.105:7073', 'Content-Length': '373', 'Accept-Language': 'en-US,en;q=0.9,el;q=0.8', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.10.105:7073', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'Upgrade-Insecure-Requests': '1', 'Connection': 'keep-alive', 'Referer': 'http://192.168.10.105:7073/addShows/newShow/', 'Cache-Control': 'max-age=0', 'Cookie': 'remeber=1; qtoken=75d556218004fd654148df7999acd1e5; qtoken_account=YWRtaW4=; nas_lang=ENG; sickchill_user="2|1:0|10:1583322256|14:sickchill_user|44:ZDQ4Y2E5OWEwNTdkYzZiMTQwODQ2ODg0MjJjZWIzMTc=|35ac92176af5ba855a31e370b30bccd96638e0fc622f6d225050a0a9e1e1a967"; nas_1_u=YWRtaW4=; login_cookie=41d5a63e6fd90d5da3d31de642f129c0689128ab; login_salt=635; showAllAp=true; QT=1584213610475', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'})
AA 2020-03-14 21:38:09 ERROR Uncaught exception POST /addShows/addNewShow (192.168.10.23)
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/series.py", line 64, in info
AA result.info(language=kwargs.get('language'))
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/tvdb.py", line 59, in series
AA result = target(*args, **kwargs)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA series = self.indexers[indexer].series(id=indexerid, language=language)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/handler.py", line 156, in series_by_id
AA s = sickchill.indexer.series_by_id(indexerid=indexer_id, indexer=indexer, language=indexerLang)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/views/manage/add_shows.py", line 526, in addNewShow
AA result = function(**kwargs)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/views/index.py", line 215, in async_call
AA Traceback (most recent call last):
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdbsimple/series.py", line 64, in info
AA result.info(language=kwargs.get('language'))
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/tvdb.py", line 59, in series
AA result = target(*args, **kwargs)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA series = self.indexers[indexer].series(id=indexerid, language=language)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/show/indexers/handler.py", line 156, in series_by_id
AA s = sickchill.indexer.series_by_id(indexerid=indexer_id, indexer=indexer, language=indexerLang)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/views/manage/add_shows.py", line 526, in addNewShow
AA result = function(**kwargs)
AA File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickchill/views/index.py", line 215, in async_call

**Comment by krash1220** [comment]
I did a fresh install and now I don't get an error but:
 search timed out, try again or try another indexer

**Comment by 03397** [comment]
Problem is with the tvdb, most probably with their API.

I think you guys need to add an alternative index.

**Comment by krash1220** [comment]
I totally agree. I am so tired of the problems with tvdb.

**Comment by dracupg** [comment]
Same issue here

**Comment by marcb1387** [comment]
yeah tvdb is having all kinda issues, im also having trouble with plex for something and other with kodi too. https://forums.thetvdb.com/viewtopic.php?f=122&t=63148

**Comment by miigotu** [comment]
Already working on another indexer, tvdb has been great for years but i think its time.
