### ISSUE TITLE
Commit 5d261 breaks my installation

### ISSUE THREAD

**Issue by arantes555** [SickChill/SickChill#6099]
Branch/Commit: https://github.com/SickChill/SickChill/commit/5d2611781e28a869d2049f9ea19bcccc42249780
OS: Linux
Browser: Any
What you did: Updated
What happened: My SickChill instance displays a "helpful" message that my "SickChill installation is exposed to the internet without a password", and that I need to set one.
What you expected: Actually, my installation is behind a reverse-proxy, that already checks for auth, so there IS an authentication, just not SickChill's one. I would *really* appreciate an option to disable this kind of paternalistic behaviour. Yes, this feature is probably helpful for 99% of users. Yes, it is a good idea to implement this kind of checks. However, it also is a good idea to think about the advanced users and allow a sickchill option to disable this behaviour *without requiring some reverse-proxy config shenanigans*. (What I am asking for is a file-only option, so it would not be "throwing users to the wolves" or anything like that, because people who do not know what they are doing would never go editing config files manually. And I do know that this is similar to issues #6018 & #6020, but you talked about an ini override, and never followed through with it as far as I can see.)

**Comment by arantes555** [comment]
(btw, unrelated but i just received an error message regarding my posting of this issue :
```
Run failed for develop (b2d7ac1)
Repository: SickChill/SickChill
Workflow: Greetings
Duration: 1.0 second
Finished: 2020-03-15 01:51:49 UTC

View results

Jobs:
.github/workflows/greetings.yml failed (0 annotations)
```
)

**Comment by miigotu** [comment]
If you are using basic auth for your reverse proxy, set the same username/password in SC and it will passthru.
If not, you can set a basic auth header in your reverse proxy that will authenticate SC, or add jwt auth.

This isnt paternalistic, a user was found to have been attacked and ended up with the attacker having complete control of his machine. The application the attacker used was examined and found to target dozens of forks and all it takes is a user who did not set up auth.

**Comment by arantes555** [comment]
I am actually packaging the app for cloudron.io. As such, I cannot automatically update the config files of the users of my package to add the user/password in it without some very impractical awk and sed magic.

Instead i just setteled for
```
            proxy_set_header X-Real-Ip "";
            proxy_set_header X-Forwarded-For "";
```

So SickChill thinks it's a local network. I really do not like breaking the logging like this, but this really leaves me no choice.

**Comment by arantes555** [comment]
On a side note, I think a lot of users would really appreciate a proper CHANGELOG.md and versionning, so we do not get caught by this kind of things by surprise.

**Comment by miigotu** [comment]
There is a proper changelog and versioning. You mean to tell me you are profiting from my and other's work and you can't handle a change you dont like?
