### ISSUE TITLE
OpenSSL version required by Cloudflare

### ISSUE THREAD

**Issue by dieselVtwin** [SickChill/SickChill#6100]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master e4f2fadd
OS: Win10
Browser: Edge
What you did: launched SickChill
What happened: SickChill Python window bannered error message "DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2t  10 Sep 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1030 blocks."

What you expected: the error message to not be displayed and for Cloudflare sites to not fail on reCaptcha.

Logs (aka Please Read Me:
Expect that developers already know about this issue so not attaching logs, but will if requested.

Tried uninstalling Python and reinstalling python-2.7.17.amd64.msi from www.python.org, but didn't fix the OpenSSL version issue.

Wanted:  A cardboard cutout for dummies of how to fix the OpenSSL version issue.

Thanks heaps for all your work!

**Comment by miigotu** [comment]
There is no fix for it, because the final version of python2.7 on windows has an old version of openssl. Live with it or use docker or linux until we convert to use py3

**Comment by dieselVtwin** [comment]
Bugger.  Not the response I was hoping for, but I understand now.
Thanks again for your work!
Cheers,
Alan
