### ISSUE TITLE
SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] Failure

### ISSUE THREAD

**Issue by adit-s** [SickChill/SickChill#6109]
Hello. I recently noticed the message below in the logs indicating that searches on torrentz2.eu are failing. I think all of the necessary information is below. Can you take a look and let me know if you need anything else. Also, if there's a setting or something else I may have missed/misconfigured to resolve the issue. Thanks in advance.

SickChill Info:
Branch: master
Commit: b3da866cadff70973fabdbb3ffbe8ad0dd208c49
Database Version: 44.0

  Python Version:
2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]

  SSL Version:
OpenSSL 1.1.1d 10 Sep 2019

  OS:
Linux-4.15.0-88-generic-x86_64-with

  Locale:
None.None

```
PASTE LOGS HERE
2020-03-15 23:29:55 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] :: Request failed: 403 Client Error: Forbidden for url: https://torrentz2.eu/feed?f= ()

**Comment by miigotu** [comment]
Torrentz is broken, it will be disabled. It was a clone and not the real one anyways ;(
