### ISSUE TITLE
SC not updating/downloading shows

### ISSUE THREAD

**Issue by loungebob** [SickChill/SickChill#6115]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master f9161da71a75dbabf83fd862bc4e46a0b4391352 
OS: Windows-10-10.0.18362 
Browser: Chrome
What you did: Nothing
What happened: It seems like most of my shows didn't get updated/downloaded since before christmas, probably around the thanksgiving break. I noticed fewer incoming but since I was traveling and working a lot I didn't pay too much attention to it. Also, I have stuff coming in from other sources so this explains why I let it go until this morning.
I don't know what triggered it but today I was looking at like 600 new episodes, all the backlog was worked off. But, those never showed as backlog episodes. This I checked every now and then. So SR must have gotten stuck somewhere thinking - like me - those shows were not missing because there was no new episodes scheduled. 
It's nothing severe. I didnt have time for those anyway but I'm curious. What would make something like this happen? Where would I look in the logs, what for? Since SR just downloaded that many eps, looking for anything in the logs seems difficult. Any pointers? 
What you expected: For SR to download episodes as they get released/aired.
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Tvdb updates api is buggy, force update all your shows and hopefully it's working now for future episodes. Just check back on it in a week or two to see that new episodes got added to the shows

**Comment by loungebob** [comment]
okidoki
