### ISSUE TITLE
mulit-tenancy / multi-user

### ISSUE THREAD

**Issue by brianjmurrell** [SickChill/SickChill#6121]
This is probably a stretch goal, but multi-tenanted SC would be interesting.

That is, a single SC process that searches for shows for multiple users, each with their own grabber (i.e. sabnzb, etc.) running on a different machine/IP/port.

This way, any overlap in searches can easily be leveraged between the two users instead of each user having their own SC doing their own (duplicate) searches, etc.

**Comment by miigotu** [comment]
What you are looking for is out of scope, but will be handled if I ever get the miix project off the ground.
