### ISSUE TITLE
Status unaired after airdate

### ISSUE THREAD

**Issue by egrueda** [SickChill/SickChill#6132]
Hi! I'm having a problem with unaired shows, I cannot mark them as wanted 'cause their still "unaired" but it is not right.
I have a current sample, but happened before with other shows:
![unaired](https://user-images.githubusercontent.com/358397/77178464-655f4500-6ac7-11ea-951c-08b1253dcfad.png)
(Local time is 16.26h)

Why is it happening? Am I doing something wrong?

SickChill Info:
```
Branch: master
Commit: f9161da71a75dbabf83fd862bc4e46a0b4391352
Version: v2020.03.15-1
Database Version: 44.1
  Python Version:2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
  SSL Version:OpenSSL 1.1.1d 10 Sep 2019
  OS:Linux-4.19.97-v7l+-armv7l-with-debian-10.3
  Locale:en_US.UTF-8
```

**Comment by miigotu** [comment]
They just aired about 9 hours ago, 5 hours after this issue was opened?

**Comment by egrueda** [comment]
Acording to the screenshot thei aired at 15h and it was 16.26h when I opened the issue, so for me they aired more than 1 hour ago

**Comment by miigotu** [comment]
Likely the network they are linked to has no timezone linked to it or the wrong timezone, which will cause it to display unaired for a few extra hours. Unless it is more than 24 hours and still unaired, this isnt a bug.
