### ISSUE TITLE
DAILY Xthor Anti-Spam Protection: A.P.I limited to 1 request every 2 seconds

### ISSUE THREAD

**Issue by vlsoft** [SickChill/SickChill#6134]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master / f9161da71a75dbabf83fd862bc4e46a0b4391352
Version: v2020.03.15-1
Database Version: 44.1

OS:Debian 9 Linux-4.9.0-11-amd64-x86_64-with-debian-9.12
Browser: Chrome
What you did:
What happened: problem when looking for episodes. Only DAILY  
What you expected:
Logs:
SEARCHQUEUE-DAILY-SEARCH :: [XThor] :: Protection Anti-Spam: A.P.I limitee a 1 requete toutes les 2 secondes. 

Info :

SEARCHQUEUE-BACKLOG- OK Works after fixed Fixes #6107  but New bug SEARCHQUEUE-DAILY-SEARCH

**Comment by miigotu** [comment]
Logs, because unless there is an error I sleep 3 seconds after every single request to xthor.
