### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-FORCE-UPDATE :: [f9161da] theTVDB timed out, unable to create the episode

### ISSUE THREAD

**Issue by sp8ced21** [SickChill/SickChill#6136]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@f9161da71a75dbabf83fd862bc4e46a0b4391352
Link to Log: https://gist.github.com/b52e6ec170a116aa0263f17099d31eb7
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [f9161da] theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by zimbomb** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f9161da71a75dbabf83fd862bc4e46a0b4391352
Link to Log: https://gist.github.com/0aa67e301f9c824d1b81174c8b8f065b
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [f9161da] theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
