### ISSUE TITLE
qBittorrent does not support old API used by SickChill

### ISSUE THREAD

**Issue by Victorvdc** [SickChill/SickChill#6137]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:  Master/f9161da71a75dbabf83fd862bc4e46a0b4391352
OS:Windows 10
Browser: Chrome
What you did: Request Down load for show using qBittorrent
What happened: Download failed , Old API command
What you expected: Can you update SickChill to new API
Logs:
```
Request failed: 404 Client Error: Not Found for url: http://192.168.1.9:8090/command/download()

Response from qBittorrent developers when I enquired...

Not Found for url: http://192.168.1.9:8090/command/download()
You trying to access qBittorrent via old WebAPI that aren't supported now in version 4.2.0 and up. See
https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation


```

**Comment by Wally73** [comment]
go to your sc install/config/search/ and under torrent search select qbittorrent apiV2

**Comment by Victorvdc** [comment]
Thanks 
You probably can delete the old qBittorrent format from the  pull down since it is no longer supported by qBittorrent last 2 stable releases. (or rename it OLD)
