### ISSUE TITLE
TheTVDb   has series with both Season 1 and Season 2004

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6144]
SickChill is loading all the season that theTVDb has for a series but since theTVDb
has both the Season 1 and Season 2004 it loads both and is searching for both.

([https://thetvdb.com/series/megastructures](https://thetvdb.com/series/megastructures)) is just one that I have found..

not sure how this should be taken care of,  

you can't remove the seasons you don't want because a refresh brings them back..

What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
The data is incorrect on tvdb, get it fixed there
