### ISSUE TITLE
year=202 is before 1900; the datetime strftime() methods require year >= 1900 = MAKO error

### ISSUE THREAD

**Issue by Ventje23** [SickChill/SickChill#6155]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master  / f9161da71a75dbabf83fd862bc4e46a0b4391352
OS: Linux-3.10.35-x86_64-with-glibc2.2.5
Browser: Chrome
What you did: Tried to access backlog overview
What happened: a Mako error
What you expected: a backlog. 
After I submitted this error I found out that option episode status management allows me to access the episodes with status wanted. Again for quite some series episodes that were downloaded were set to wanted. By changed the status I encountered a problem with the show Tacoma FD. When I tried to access that show I got the same MAKO error. After I deleted the show the MAKO error is gone. RE-adding the show again generates the MAKO error. So hopefully you can use this info to find out what's wrong with the data of this show.
```
File /volume1/@appstore/sickchill/var/SickBeard/sickbeard/sbdatetime.py:243, in sbfdatetime:
strd = dt.strftime(sickbeard.DATE_PRESET)
ValueError: year=202 is before 1900; the datetime strftime() methods require year >= 1900
```

**Comment by miigotu** [comment]
Looks like this should already be fixed. Someone entered 202 as the year for an episode or the show, it is no longer 202 (typo for 2020)

**Comment by Ventje23** [comment]
Ok thank you, will try again.
thanks for all you work on SC.
Be careful and stay safe.

**Comment by offbyone** [comment]
This has come up on another show; is it possible to add logic to protect against this? 

```
File /opt/sickchill/sickbeard/sbdatetime.py:243, in sbfdatetime:
strd = dt.strftime(sickbeard.DATE_PRESET)
ValueError: year=17 is before 1900; the datetime strftime() methods require year >= 1900
```

This is happening in the display for [this show](https://thetvdb.com/series/full-frontal-with-samantha-bee)

**Comment by offbyone** [comment]
Oh, I don't deny that there is a bug in the show data :)

What I think is reasonable is for SickChill not to be vulnerable to bad data like that, even if all you can display is "Show active from WTF to 2017" :D
