### ISSUE TITLE
When an episode is cancelled and airdate removed from tvdb SickChill does not mirror the change.

### ISSUE THREAD

**Issue by augur42** [SickChill/SickChill#6156]
When performing Mass Update or Force Full Update on a show any episodes which have been removed from the schedule due to coronavirus aren't having their airdate updated from their current date to Never to reflect they no longer have a known airdate. By removing the show entirely and readding it the Never status is correct.

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Win7
Browser: Firefox 74.0
What you did: Tried to update a few shows airdate to Never with cancelled episode before testing with debug enabled for The Flash (2014) using Mass Update and when that failed Force Full Update
What happened: The airdate for the unaired episode(s) wasn't removed
What you expected: The airdate would be updated to reflect it will no longer air.

This is a snippet from the debug log, the rest is just repetitions for other episodes of The Flash (2014), episode S06E16 was scheduled to air 2020-04-08 but has been removed from schedule due to coronavirus affecting post production.
Logs:
```
23:44:46 DEBUG::SHOWQUEUE-FORCE-UPDATE :: 279121: The absolute number for S06E16
 is: 130
23:44:46 DEBUG::SHOWQUEUE-FORCE-UPDATE :: 279121: Episode airs in the future or
has no airdate, marking it Unaired
23:44:46 DEBUG::SHOWQUEUE-FORCE-UPDATE :: 279121: Not creating SQL queue - recor
d is not dirty
```

**Comment by potestus** [comment]
Got the same problem where shows have had a date removed. Sickchill doesn't set it to "never" on a refresh.

**Comment by miigotu** [comment]
Would you rather.... SC remove your entire library when tvdb fails or deal with some episodes not having the correct airdate yet?

**Comment by augur42** [comment]
I don't like this binary choice, both suck, although one sucks a lot more than the other. Looks like I'm going to fix them manually then, one at a time, it might be a 2 beer job. 

I demand perfection, fix tvdb /sarcasm

**Comment by potestus** [comment]
How do I fix this manually? Just on show DC legends of tomorrow.

**Comment by augur42** [comment]
Remove show, this removes all info from the database. Then readd it as an existing show, you'll have to set any non default quality and reset the status for existing episodes e.g 1080p WEB-DL and archived episodes.

A bit fiddly, and if you have a lot of shows it could take a little time hence a 2 beer job. If you wait long enough they will likely fix themselves when they either do get an airdate or get removed from the tvdb database, but that could be months.

**Comment by miigotu** [comment]
They will fix themselves, it hurts nothing for them to be incorrect until then.
