### ISSUE TITLE
Images missing if sickchill is behind nginx reverse proxy

### ISSUE THREAD

**Issue by MennoBroxterman** [SickChill/SickChill#6160]
![Screenshot 2020-04-01 at 16 39 19](https://user-images.githubusercontent.com/18718607/78151150-8e24fa00-7438-11ea-8cce-9225b8472b2b.png)
        location /sickchill {
                proxy_pass http://<serverip>:8081;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Protocol $scheme;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

		error_page 502 /502sickb.html;
		error_page 401 /401.html;
}

SickChill works fine directly without using NGinx as reverse proxy, also tried sickchill with https, works fine without nginx, with nginx no images.

**Comment by miigotu** [comment]
Mine works just fine here.

```
    location / {
        try_files $uri $uri/ =404;
    }

    location /sickchill {
        proxy_pass http://192.168.1.222:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        client_max_body_size 0;
        proxy_read_timeout 36000s;
        proxy_redirect off;
    }
```

**Comment by MennoBroxterman** [comment]
Thanks, you helped me out. The sickchill settings were fine, but the nginx config file also contained this 

location ~ /(\.git|cache|bin|logs|backup|tests)/.*$ { return 403; }

Removed it and now i have images again. Thx.

**Comment by miigotu** [comment]
You can add that back and just take out the `|cache` part

**Comment by MennoBroxterman** [comment]
Yeah i did allready, thanks for mentioning it.
