### ISSUE TITLE
Save Me (2013) and Save Me (2018) using the same name

### ISSUE THREAD

**Issue by MSP85D** [SickChill/SickChill#6162]
Hi,

Please understand that I am only a user and have no technical knowledge so I may be asking something that can be worked around.

I already have Save Me (2013) loaded into Sickchill and is stored as just "Save Me".

When I try and add Save Me (2018) it tells me the folder already exists by asking which unallocated folder to use..

Can either the 2013 or the 2018 be modified to use the year so they load to different locations? Or do I just create a folder manually and point the series top it?

**Comment by miigotu** [comment]
The title of `Save Me (2018)` needs to be set to `Save Me (2018)` on tvdb. Point this out to them that there are 2 versions and they will fix it there.
