### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by dmbymdt** [SickChill/SickChill#6164]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

**Info**
SickChill Info:
Branch: master
Commit: 50a2b16835064938d2a99129fca8744edcfb18a2
Version: v2020.04.01-2
Database Version: 44.1
  Python Version:2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
  SSL Version:OpenSSL 1.1.1d 10 Sep 2019
  OS:Linux-4.19.97-v7+-armv7l-with-debian-10.3
  Locale:en_US.UTF-8

**What you did:**
Updated sickchill to newest version

**What happened:**
Have not been able to add new shows. Keep getting handshake errors.

**What you expected:**
Expected to be able to add new shows. Is this a python 2.7 error that needs to be updated to python3? 

**Related**
Attached are related issues

#5948
#5920
#5895
#5756

Logs:
```
2020-04-01 17:49:25 DEBUG WEBSERVER-ADDSHOWS :: Could not find item on the indexer: (Indexer probably doesn't have this item) [error HTTPSConnectionPool(host='api.thetvdb.com', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",),))]
```

**Comment by miigotu** [comment]
No. It is an error on TVDB's end. Also, check your system time/date/timezone

**Comment by dmbymdt** [comment]
Thanks! I ended up getting it to work after fixing `cryptography` to be higher than version 1.7.1.

Ultimately the code that seemed to help the most was also very simple:
`sudo apt-get remove cryptography`

This removed the cryptography 1.7.1 version and 2.6.1 was already there.

Your Wiki was helpful
https://github.com/SickChill/SickChill/wiki/SSL-Errors

Also the following website explained the issue well
https://www.raspberrypi.org/forums/viewtopic.php?t=204149
