### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-FORCE-UPDATE :: [50a2b16] theTVDB timed out, unable to create the episode

### ISSUE THREAD

**Issue by Ichikafka** [SickChill/SickChill#6168]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@50a2b16835064938d2a99129fca8744edcfb18a2
Link to Log: https://gist.github.com/5a94b13da915865d6ea2c5d5a1effc4a
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [50a2b16] theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@50a2b16835064938d2a99129fca8744edcfb18a2
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [50a2b16] theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by zimbomb** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@50a2b16835064938d2a99129fca8744edcfb18a2
Link to Log: https://gist.github.com/288f641b1610bf43ef7988aeadcfb763
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [50a2b16] theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
