### ISSUE TITLE
[APP SUBMITTED]: WEBSERVER-HOME :: Missing time zone for network: Sky Crime (UK). Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by swhgraham** [SickChill/SickChill#6178]
### INFO
Python Version: **2.7.9 (default, Sep 14 2019, 20:00:08) [GCC 4.9.2]**
Operating System: **Linux-4.4.190.x86_64.1-x86_64-with-debian-8.11**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@50a2b16835064938d2a99129fca8744edcfb18a2
No Log available with ERRORS:
### ERROR
```
WEBSERVER-HOME :: Missing time zone for network: Sky Crime (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
This should be fixed
