### ISSUE TITLE
Extremely large shows hang in the browser (hundreds+ episodes)

### ISSUE THREAD

**Issue by iguyking** [SickChill/SickChill#6179]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:  Master
OS:   Centos/Windows 10
Browser:  Chrome 80
What you did:  Load episodes from Jeopardy with 8k + episodes
What happened:

The browser can take over 30 minutes to load and is very difficult to do anything in there.  

What you expected:

Potentially a paging method, only load 10 seasons at a time, something to be able to load and change the status to wanted for episodes.  

Logs:
```
PASTE LOGS HERE
```

**Comment by GregSawin** [comment]
Have you tried unchecking the "Show all seasons" option on the General Config / Interface page? I had a similar problem and this fixed it for me.  It'll now only show/expand the latest season by default, though you can easily click to see any other season.

**Comment by iguyking** [comment]
That does help.  Don't suppose we can shift this to be a setting per series?   

Thanks.
