### ISSUE TITLE
Added episodes stay in Snatched status even after re-scan/full update

### ISSUE THREAD

**Issue by Belokan** [SickChill/SickChill#6182]
Hello,

I've just migrated from SickBeard to SickChill because after upgrading my VM from Jessie to Buster I was not able to restart SB.
My configuration is as follow (maybe not the simplest but it works for years ...):

1.- SickChill sends episodes to SABnzbd thru API
2.- Once processed by SABnzbd, I have a filebot script that renames episodes, retrieves subtitles and move the files to the definitive location for TV shows.

This definitive location is the one defined in SickChill for the "Show root directories".

I've not migrated from SB to SC so I've reconfigured everything and add all existing shows. SC has been been able to re-scan my library without issue and discovered all the episodes (renamed by filebot before when using SB).

My problem is that all new episodes are not discovered by SC when filebot move them in my TV shows location. Even if I re-scan files or force full update. The files are present, with the correct naming but they stay in "snatched" status.
More curious, if I delete the show and add it as existing show again, SC correctly find the new episodes and they all appear as Downloaded with the correct resolution.

Any idea ? Of course SC is up to date.

Thanks a lot in advance,

Belokan

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Debian 10 Buster
Browser: Firefox 74.0.1
What you did: Add newly downloaded episodes 
What happened: Episodes stay in Snatched status
What you expected: Episodes to appear as Downloaded
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Snatched status is only meant for SC internally. When the episode is in snatched status it is expecting to find a new file with post processor and process it. As far as it knows, a file was in the location before and it was marked failed or manually searched on the show page and it is waiting to replace it with the newly downloaded file. Set the episode to skipped or wanted and rescan the folder then.

**Comment by Belokan** [comment]
Hi miigotu,

Thanks for your answer. But I don't really see the point here. Why SC does not recognized a newly downloaded episode during the scheduled or forced re-scan but recognizes it when I add the show (after delete) ?
SB was dealing fine with the same configuration, I'm just wondering what is the problem here.

My TV Shows "repository"  is NFS mounted if it has some impact on how SC detects new added files ...
omv1:/export/download on /volume1/Download type nfs (rw,relatime,vers=3,rsize=262144,wsize=262144,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.1.102,mountvers=3,mountport=42603,mountproto=udp,local_lock=none,addr=192.168.1.102)

Regards

**Comment by miigotu** [comment]
You are not supposed to add files directly to the show folder that SC snatched. Use the post processor or nzbtomedia.

It would also be better to just run SC on the omv machine, and save a ton of time with transfers.

**Comment by Belokan** [comment]
OK I see how it's supposed/designed to work, I was confused because SB worked for years in this configuration.
Regarding the infrastructure, I have a 3 nodes Proxmox cluster @_home. My OMV instances are also VMs bound to a node using pass-through physical disks. I have a rule that makes the VM running SC (and TM, SAB, CP, ...) on the same node than OMV1 if possible, so transfers are done using the internal bridge, close to if it was on the same host. And I prefer, personal choice, to keep my VM as "clean as possible" and avoiding plugins ...

**Comment by Belokan** [comment]
Hello,

I dropped my filebot scripts and let SC doing post-processing. It works correctly now. Just have some issues with subtitles but I'll deal with it ;-)
