### ISSUE TITLE
Error in french translation for anime edition #5218 is closed but not corrected

### ISSUE THREAD

**Issue by lobofoots** [SickChill/SickChill#6189]
Hello @miigotu 

I think you overlooked this one, please check
Error in french translation for anime edition #5218

**Comment by miigotu** [comment]
Translation is not done on GitHub. It is done on crowdin. Follow the link on the other issue.

**Comment by EZ-nanoCloud** [comment]
@miigotu 
Sorry if I don't understand this, how can I have in my sickchill directory the good translation that is on the Crowdin site instead of the bad that is on github?
I'm at Version: v2020.04.22-1 and the error is still there.

**Comment by miigotu** [comment]
@EZ-nanoCloud it is updated and pulled from crowdin for every push to master

**Comment by miigotu** [comment]
@EZ-nanoCloud sadly, we dont have a maintainer for french on crowdin anymore, so I had to manually go in and approve the translations just now on crowdin.

**Comment by EZ-nanoCloud** [comment]
@miigotu 
I volunteer, if you need someone.

**Comment by miigotu** [comment]
@EZ-nanoCloud are you lobofoots?

**Comment by EZ-nanoCloud** [comment]
@miigotu 
Yes, sorry I have multiple accounts on github

**Comment by miigotu** [comment]
I have given you proofreader rights for french on crowdin, you can approve translations for it now.

**Comment by EZ-nanoCloud** [comment]
Thanks
