### ISSUE TITLE
manual initiation of series updates and daily searches

### ISSUE THREAD

**Issue by D3ltorohd** [SickChill/SickChill#6198]
Hello,
because my runtimes, i have a problem, that SC updates automaticly series data, like Broadcast date or the daily search for episodes. So often im not in the timerange it was set in the settings. So when it runs nothing happens. Is there a way, when the system wakesup, that i can trigger something to start initial series data and daily search ?

**Comment by miigotu** [comment]
SC needs to be ran on a server that is always on.

**Comment by D3ltorohd** [comment]
hm ok. Then i have to look how i do that.
