### ISSUE TITLE
Cannot load SickChill pages from bonded NIC with IPv6 address in remote_url

### ISSUE THREAD

**Issue by jamver** [SickChill/SickChill#6199]
SickChill no longer correctly parses the IPv6 remote_ip addresses when the server is presented on a bonded interface.  Everything works fine using an IPv4 address in the URL.

**Branch/Commit**: master/50a2b16835064938d2a99129fca8744edcfb18a2

**Database Version**: 44.1
**OS**: Macintosh; Intel Mac OS X 10_13_6
**Browser**: Version/13.1 Safari/605.1.15

**What you did**: Loaded page using mDNS hostname in URL
**What happened**: Empty response, error in logs
**What you expected**: SickChill interface appear

**Logs**:
```
2020-04-14 16:18:16 ERROR    Uncaught exception GET / (fe80::cf70%bond0)
HTTPServerRequest(protocol=u'https', host='sickrage.local:8081', method='GET', uri='/', version='HTTP/1.1', remote_ip='fe80::cf70%bond0', headers={'Accept-Language': 'en-au', 'Accept-Encoding': 'br, gzip, deflate', 'Host': 'sickrage.local:8081', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15', 'Connection': 'keep-alive', 'Cookie': 'plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; plushQueuePerPage=20; sn=3C913601013DD; _ga=GA1.2.202148725.1583028868; plushHistPerPage=9999999'})
Traceback (most recent call last):
  File "/apps/sickchill/lib/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/apps/sickchill/lib/tornado/web.py", line 2884, in wrapper
    if not self.current_user:
  File "/apps/sickchill/lib/tornado/web.py", line 1157, in current_user
    self._current_user = self.get_current_user()
  File "/apps/sickchill/sickchill/views/index.py", line 172, in get_current_user
    return helpers.is_ip_private(self.request.remote_ip)
  File "/apps/sickchill/sickbeard/helpers.py", line 1718, in is_ip_private
    return ipaddress.ip_address(ip.decode()).is_private
  File "/apps/sickchill/lib/ipaddress.py", line 168, in ip_address
    address)
ValueError: u'fe80::cf70%bond0' does not appear to be an IPv4 or IPv6 address
```

**Comment by miigotu** [comment]
I'm probably not up to snuff about bonds, but why is %bond0 being passed in the remote_ip?

**Comment by jamver** [comment]
'%bond0' is being passed into remote_ip because it is the scope/zone component of the (scoped literal) IPv6 addresses (see [RFC 4007 — IPv6 Scoped Address Architecture](https://tools.ietf.org/html/rfc4007.html)).

Submitted #6201 as a temporary workaround.

The issue is that the embedded library phihag/ipaddress@d8aef06 (Python 3.3+'s ipaddress for older Python versions) does not correctly handle scoped literal IPv6 addresses, which are returned under Python 2.7+ (at least).  IPv6 scoped literal addresses support has recently been added to Python 3.9a5 python/cpython@21da76d1f1b527d62b2e9ef79dd9aa514d996341 (to handle IPv6 addresses containing '%' followed by a scope or zone id value — typically a number on Windows and an interface name on Unix-based systems).

The [IPv6 address Wikipedia article](https://en.wikipedia.org/wiki/IPv6_address) has a good description of [scoped literal IPv6 addresses](https://wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses).

(For background, this is normal behaviour for Python's [socket.socket.accept()](https://docs.python.org/2/library/socket.html#socket.socket.accept), which is a transliteration of the underlying system call.  On Unix-based systems (such as Linux), sockaddr_storage (sockaddr_in6 from [ip6(7)](http://man7.org/linux/man-pages/man7/ipv6.7.html)) includes sin6_scope_id (ifr_ifindex from [netdevice(7)](http://man7.org/linux/man-pages/man7/netdevice.7.html)), and is returned as the interface name (represented as %ifr_ifname) when being returned as a string by the Python2.7 sockets library (python/cpython@7a41638b5b183d0b9b27449d502d0a15001134ee [2.7.18rc1/Modules/socketmodule.c#L1366](https://github.com/python/cpython/blob/7a41638b5b183d0b9b27449d502d0a15001134ee/Modules/socketmodule.c#L1366)).

Also, while debugging, I tested tornadoweb/tornado@8e9e755(2018-01-07, latest/final v4.5 branch release) and confirmed that it appears to functional correctly without changes (but still fails to handle IPv6 scoped address).

I also tested tornadoweb/tornado@a99f147(2019-03-02, latest/final version supporting Python2.7) with no obvious errors, however, SickChill hangs when attempting to serve client HTTP/S requests (suggesting configuration or changes are required in SickChill).

**Comment by jamver** [comment]
Opened issue phihag/ipaddress#54 requesting upstream support.
