### ISSUE TITLE
Shows managed by sickchill dont get imported in kodi 18.6 (OSMC)

### ISSUE THREAD

**Issue by fadern** [SickChill/SickChill#6200]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 50a2b16835064938d2a99129fca8744edcfb18a2
Version: v2020.04.01-2
Database Version: 44.1
Python Version: 2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]
SSL Version: OpenSSL 1.0.2n 7 Dec 2017
OS: Linux-3.10.105-x86_64-with-glibc2.2.5 (Synology)
Browser: FF 75
OSMC: KODI 18.6

Hi,

I've been using SickChill and OSMC for some years now with no bigger issues.
Lately OSMC dont import new shows that SickChill are managing. Ive been in contact with OSMC devs and they say that there might be some problem with the nfos that SickChill are creating. I can get the shows imported into OSMC if I manually update the show info from OSMC.
Do I need to change any settings to get sickchill compatible with OSMC?

**Comment by miigotu** [comment]
There were some bugs with the episodeguide url used in nfo files previously. Either sed the episodeguide urls out of the nfos or delete the nfos

**Comment by fadern** [comment]
Ok, I'll try delete the nfos. I will report back to you.
Thank you

**Comment by fadern** [comment]
OSMC imported the shows correctly when i deleted the nfos. But then i tried to add a new show (from sickchill) and OSMC did not import that one. 
I reported that to OSMC and they looked at the nfo that sickchill had generated. They say that it looks like there might be a issue with the url tag.

`darwindesign
9h

I never looked into how using login works with scraping but you have an issue with the url tag as what you posted does not work, but if I replace it by itself with what would be stock without a logon…

  <episodeguide>
        <url cache="377269-en.xml">http://thetvdb.com/api/439DFEBA9D3059C6/series/377269/all/en.zip</url>
  </episodeguide>

then it scrapes mostly okay. The “mostly” is that the nfo file is a bit thin and it lacks a lot of common tags such as rating, runtime, all the artwork, etc. You might be better off just turning off nfo generation in sickchill and let Kodi sort it out on its own. Otherwise this is a Sickchill issue and not an OSMC or Kodi one and so you need to work it out with their people.`

https://discourse.osmc.tv/t/osmc-stopped-adding-new-shows/85202/8

**Comment by miigotu** [comment]
@fadern that person is mistaken.
The episodeguideurl should look like this: ` <url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:80379}|Content-Type=application/json</url>`

__BUT__ nfo files aren't even needed by kodi anymore, you can safely turn that off.

https://forum.kodi.tv/showthread.php?tid=323588
![image](https://user-images.githubusercontent.com/390379/79629829-8a70c300-811a-11ea-9c74-b20527f6283c.png)

**Comment by miigotu** [comment]
The problem is that thetvdb api is buggy and sometimes it doesnt work ^

**Comment by fadern** [comment]
ok, thank you!
:-)
