### ISSUE TITLE
[APP SUBMITTED]: /opt/sickrage/lib/lxml/etree.so: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by mortael** [SickChill/SickChill#6204]
### INFO
Python Version: **2.7.9 (default, Sep 16 2019, 18:29:54) [GCC 4.9.2]**
Operating System: **Linux-4.14.29-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@09d8e853be6fc3d67862d6b1305fda26a2a8209c
Link to Log: https://gist.github.com/2535affd4b86ec8a16cfacd89a1dd6a1
### ERROR
```
SHOWQUEUE-ADD :: [09d8e85] Unable to add show due to an error with theTVDB: /opt/sickrage/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mortael** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 16 2019, 18:29:54) [GCC 4.9.2]**
Operating System: **Linux-4.14.29-v7+-armv7l-with-debian-8.0**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@09d8e853be6fc3d67862d6b1305fda26a2a8209c
Link to Log: https://gist.github.com/1208df19e1e1b8ca309d4a6e575b189a
### ERROR
```
SHOWQUEUE-ADD :: [09d8e85] Error trying to add show: /opt/sickrage/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
```
sudo apt install build-essential python2-pip
cd path/to/sickchill
pip install -Ut lib -r requirements/requirements.txt
```

**Comment by ddf2k2** [comment]
> ```
> sudo apt install build-essential python2-pip
> cd path/to/sickchill
> pip install -Ut lib --force-reinstall -r requirements/requirements.txt
> ```

Hi Miigotu 
Doesnt fix the issue for me.

`pi@raspberrypi:~ $ sudo apt install build-essential python2-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python2-pip`

`pi@raspberrypi:/opt/sickrage $ pip install -Ut lib --force-reinstall -r requirements/requirements.txt
Ignoring win-inet-pton: markers 'os_name == "nt" and python_version < "3.0"' don't match your environment
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting babelfish==0.5.5 (from -r requirements/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/34/b7/b36c651a9136990060ab4d6c9a32de81752123105b940b2f3b958e5c6cd0/babelfish-0.5.5.tar.gz (90kB)
    100% |████████████████████████████████| 92kB 1.8MB/s 
Collecting backports_abc==0.5 (from -r requirements/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/7d/56/6f3ac1b816d0cd8994e83d0c4e55bc64567532f7dc543378bd87f81cebc7/backports_abc-0.5-py2.py3-none-any.whl
Collecting backports.ssl-match-hostname==3.7.0.1 (from -r requirements/requirements.txt (line 4))
  Downloading https://www.piwheels.org/simple/backports-ssl-match-hostname/backports.ssl_match_hostname-3.7.0.1-py2.py3-none-any.whl
Collecting beautifulsoup4==4.9.0 (from -r requirements/requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/2d/3e/8b2fc5d3c31c84d7209313f4059858f502f2e4a9d986693eca03fe325565/beautifulsoup4-4.9.0-py2-none-any.whl (109kB)
    100% |████████████████████████████████| 112kB 2.2MB/s 
Collecting bencode==1.0 (from -r requirements/requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/ee/e8/a525446e3868f820f7f94787ca9277cc7ed005923672a986e6448fb04f1f/bencode-1.0.tar.gz
Collecting cachecontrol==0.12.6 (from -r requirements/requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/18/71/0a9df4206a5dc5ae7609c41efddab2270a2c1ff61d39de7591dc7302ef89/CacheControl-0.12.6-py2.py3-none-any.whl
Collecting certifi==2020.4.5.1 (from -r requirements/requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl (157kB)
    100% |████████████████████████████████| 163kB 1.9MB/s 
Collecting cfscrape>=1.9.5 (from -r requirements/requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/a6/3d/12044a9a927559b2fe09d60b1cd6cd4ed1e062b7a28f15c91367b9ec78f1/cfscrape-2.1.1.tar.gz
Collecting chardet==3.0.4 (from -r requirements/requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting cloudscraper from git+https://github.com/VeNoMouS/cloudscraper.git@dev#egg=cloudscraper (from -r requirements/requirements.txt (line 12))
  Cloning https://github.com/VeNoMouS/cloudscraper.git (to revision dev) to /tmp/pip-install-fYYC1T/cloudscraper
Branch 'dev' set up to track remote branch 'dev' from 'origin'.
Switched to a new branch 'dev'
Collecting configobj==5.0.6 (from -r requirements/requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
Collecting decorator==4.4.2 (from -r requirements/requirements.txt (line 14))
  Downloading https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting dogpile.cache (from -r requirements/requirements.txt (line 16))
  Downloading https://www.piwheels.org/simple/dogpile-cache/dogpile.cache-0.9.0-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 1.7MB/s 
Collecting enum34==1.1.10 (from -r requirements/requirements.txt (line 17))
  Downloading https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
Collecting enzyme==0.4.1 (from -r requirements/requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/dd/99/e4eee822d9390ebf1f63a7a67e8351c09fb7cd75262e5bb1a5256898def9/enzyme-0.4.1.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 2.2MB/s 
Collecting fake-useragent==0.1.11 (from -r requirements/requirements.txt (line 19))
  Downloading https://files.pythonhosted.org/packages/d1/79/af647635d6968e2deb57a208d309f6069d31cb138066d7e821e575112a80/fake-useragent-0.1.11.tar.gz
Collecting feedparser from git+https://github.com/kurtmckee/feedparser.git@f1dd1bb923ebfe6482fc2521c1f150b4032289ec#egg=feedparser (from -r requirements/requirements.txt (line 20))
  Cloning https://github.com/kurtmckee/feedparser.git (to revision f1dd1bb923ebfe6482fc2521c1f150b4032289ec) to /tmp/pip-install-fYYC1T/feedparser
Collecting futures==3.3.0 (from -r requirements/requirements.txt (line 21))
  Downloading https://files.pythonhosted.org/packages/d8/a6/f46ae3f1da0cd4361c344888f59ec2f5785e69c872e175a748ef6071cdb5/futures-3.3.0-py2-none-any.whl
Collecting guessit==3.1.0 (from -r requirements/requirements.txt (line 22))
  Downloading https://files.pythonhosted.org/packages/3e/4d/0f3c55ff4fbef55e6e1086e9f273cef4f70d8aa1b975f2a4d9821e0fdc34/guessit-3.1.0.tar.gz (144kB)
    100% |████████████████████████████████| 153kB 1.3MB/s 
Collecting html5lib==1.0.1 (from -r requirements/requirements.txt (line 27))
  Downloading https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl (117kB)
    100% |████████████████████████████████| 122kB 2.5MB/s 
Collecting httplib2==0.17.2 (from -r requirements/requirements.txt (line 28))
  Downloading https://files.pythonhosted.org/packages/1b/f0/a35a448afea308aeb6a1430dbcfb46f4cef11360cbc18f22af6e567bb847/httplib2-0.17.2.tar.gz (220kB)
    100% |████████████████████████████████| 225kB 1.1MB/s 
Collecting idna==2.9 (from -r requirements/requirements.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
Collecting IMDbPY==6.8 (from -r requirements/requirements.txt (line 31))
  Downloading https://files.pythonhosted.org/packages/a9/0e/06116cc20b7a9ad31578aac40afde7f64b02c417afc81473702279242b0e/IMDbPY-6.8.tar.gz (305kB)
    100% |████████████████████████████████| 307kB 1.2MB/s 
Collecting js2py from git+https://github.com/PiotrDabkowski/Js2Py.git@05e77f0d4ffe91ef418a93860e666962cfd193b8#egg=js2py (from -r requirements/requirements.txt (line 32))
  Cloning https://github.com/PiotrDabkowski/Js2Py.git (to revision 05e77f0d4ffe91ef418a93860e666962cfd193b8) to /tmp/pip-install-fYYC1T/js2py
Collecting jsonrpclib from git+https://github.com/joshmarshall/jsonrpclib.git@e3a3cdedc9577b25b91274815b38ba7f3bc43c68#egg=jsonrpclib (from -r requirements/requirements.txt (line 33))
  Cloning https://github.com/joshmarshall/jsonrpclib.git (to revision e3a3cdedc9577b25b91274815b38ba7f3bc43c68) to /tmp/pip-install-fYYC1T/jsonrpclib
Collecting lockfile (from -r requirements/requirements.txt (line 36))
  Downloading https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting mock (from -r requirements/requirements.txt (line 37))
  Downloading https://www.piwheels.org/simple/mock/mock-4.0.0-py2.py3-none-any.whl
mock requires Python '>=3.6' but the running Python is 2.7.16`

**Comment by ddf2k2** [comment]
Still get the same errors in Sickchill

`2020-04-18 13:30:20 SHOWQUEUE-ADD :: [460ab74] Unable to add show due to an error with theTVDB: /opt/sickrage/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
2020-04-18 13:30:20 SHOWQUEUE-ADD :: [460ab74] Error trying to add show: /opt/sickrage/lib/lxml/etree.so: wrong ELF class: ELFCLASS64`

**Comment by ddf2k2** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@460ab7407e0856a03ae2728878e1256e252f2239
Link to Log: https://gist.github.com/a70e843a1e56ce6986f86a45307d10aa
### ERROR
```
SHOWQUEUE-ADD :: [460ab74] Unable to add show due to an error with theTVDB: /opt/sickrage/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ddf2k2** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@460ab7407e0856a03ae2728878e1256e252f2239
Link to Log: https://gist.github.com/5da50259ecec1fa0cfd88bff7e8ecf2a
### ERROR
```
SHOWQUEUE-ADD :: [460ab74] Error trying to add show: /opt/sickrage/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hooligeek** [comment]
> ```
> sudo apt install build-essential python2-pip
> cd path/to/sickchill
> pip install -Ut lib --force-reinstall -r requirements/requirements.txt
> ```

This worked on my Windows Server 2012 R2 build.  Minus the apt install portion obviously.
