### ISSUE TITLE
[APP SUBMITTED]: SHOWQUEUE-REFRESH :: [50a2b16] Multiple entries for absolute number: 1 in show: La Pat'Patrouille found 

### ISSUE THREAD

**Issue by tunisiano187** [SickChill/SickChill#6205]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@50a2b16835064938d2a99129fca8744edcfb18a2
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [50a2b16] Multiple entries for absolute number: 1 in show: La Pat'Patrouille found 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Fix it on thetvdb
