### ISSUE TITLE
[APP SUBMITTED]: Shared object "libm.so.6" not found, required by "etree.so"

### ISSUE THREAD

**Issue by GeckoOBac** [SickChill/SickChill#6207]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@460ab7407e0856a03ae2728878e1256e252f2239
Link to Log: https://gist.github.com/3ca8900ffb7231f200ba0c4b3a6d97f2
### ERROR
```
MAIN :: [460ab74] There was an error creating the show in /media/series/Dances with the Dragons: Error Shared object "libm.so.6" not found, required by "etree.so"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by GeckoOBac** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@460ab7407e0856a03ae2728878e1256e252f2239
Link to Log: https://gist.github.com/f5dd4bee7a2f8c58d46fd06e7a636617
### ERROR
```
MAIN :: [460ab74] There was an error creating the show in /media/series/Kenja no Mago: Error Shared object "libm.so.6" not found, required by "etree.so"
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by quickdry** [comment]
Same/related error on Windows:

Python Version:2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
  SSL Version:OpenSSL 1.0.2a 19 Mar 2015
  OS:Windows-2012Server-6.2.9200

Branch: master
Commit: 460ab7407e0856a03ae2728878e1256e252f2239
Version: v2020.04.18-1
Database Version: 44.1


2020-04-18 20:38:34 SHOWQUEUE-ADD :: [460ab74] Error loading IMDb info: cannot import name etree
2020-04-18 19:28:18 MAIN :: [460ab74] There was an error creating the show in E:\TV Shows\Temptation Island (AU): Error cannot import name etree

**Comment by BenjV** [comment]
On Linux you need libm.so.6 to be present in /lib
This is normally part of the Linux distribution and should standard be available
If it is missing on your system you could use pip to install lxml with this command.
### sudo pip install lxml
This should add this binary to  /lib

On Windows you need libxmk2.dll and libxslt.dll

See:
### https://lxml.de/installation.html

**Comment by miigotu** [comment]
This will fix it on linux, not sure about windows yet. I have a dependency issue in libs right now because of someone insisting I update every lib -.-

```bash
cd path/to/sickchill
sudo apt install -f build-essential
pip install -Ut lib --force-reinstall --no-compile -r requirements/requirements.txt
```
