### ISSUE TITLE
SickChill won't run after update..

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6209]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: current
OS: Windows 7
Browser: firefox
What you did: Selected update on the screen
What happened: Went through a process and then stopped
What you expected: To restart 

I tried to get it to start manually but the command window open and closes too fast to read anything.  Opened a command window and started SickBeard.py got some errors..

Downloaded the ZIP file and extracted to the same directory and replace all files.

Started setup.py;
That didn't work...
Started SickBeard.py
That didn't work...
Logs:
```


C:\SickChil>SickBeard.py
Traceback (most recent call last):
  File "C:\SickChil\SickBeard.py", line 67, in <module>
    import sickbeard
  File "C:\SickChil\sickbeard\__init__.py", line 41, in <module>
    import sickchill
  File "C:\SickChil\sickchill\__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "C:\SickChil\sickchill\show\indexers\__init__.py", line 22, in <module>
    from .handler import ShowIndexer
  File "C:\SickChil\sickchill\show\indexers\handler.py", line 31, in <module>
    from sickbeard.tv import Show
  File "C:\SickChil\sickbeard\tv.py", line 48, in <module>
    from . import db, helpers, logger, network_timezones, notifiers, postProcessor, subtitles
  File "C:\SickChil\sickbeard\helpers.py", line 55, in <module>
    import cloudscraper
  File "C:\SickChil\lib\cloudscraper\__init__.py", line 27, in <module>
    from .exceptions import (
ImportError: cannot import name CloudflareLoopProtection

C:\SickChil>
```

Hope to get this running soon...

**Comment by scottfreeze** [comment]
Seeing the same thing.  Updated with the latest 17 commits, Sickchill won't start.  Ubuntu 16.04.

**Comment by foot-gloves** [comment]
see the temporary workaround in issue 6208:

> Temporary workaround until a fix is made:
> 
> --- lib/cloudscraper/__init__-orig.py   2020-04-18 22:10:01.829854203 +1000
> +++ lib/cloudscraper/__init__.py        2020-04-18 22:10:10.048853841 +1000
> @@ -24,14 +24,6 @@
>  from requests.sessions import Session
>  from requests.adapters import HTTPAdapter
>  
> -from .exceptions import (
> -    CloudflareLoopProtection,
> -    CloudflareCode1020,
> -    CloudflareIUAMError,
> -    CloudflareReCaptchaError,
> -    CloudflareReCaptchaProvider
> -)
> -
>  from .interpreters import JavaScriptInterpreter
>  from .reCaptcha import reCaptcha
>  from .user_agent import User_Agent
>

**Comment by armontero** [comment]
I have the same issue

Branch/Commit: current
OS: FreeBSD 11.3-RELEASE-p6 (FreeNAS.amd64)
Browser: Chrome
What you did: Noticed Sickchill was down.  Went to jail and tried to start service.
What happened: Startup failed with error
What you expected: Sickchill to start

This is what I get:

root@sickchill:~ # service sickchill start
Starting sickchill.
Traceback (most recent call last):
  File "/usr/local/sickchill/SickBeard.py", line 67, in <module>
    import sickbeard
  File "/usr/local/sickchill/sickbeard/__init__.py", line 41, in <module>
    import sickchill
  File "/usr/local/sickchill/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/usr/local/sickchill/sickchill/show/indexers/__init__.py", line 22, in <module>
    from .handler import ShowIndexer
  File "/usr/local/sickchill/sickchill/show/indexers/handler.py", line 31, in <module>
    from sickbeard.tv import Show
  File "/usr/local/sickchill/sickbeard/tv.py", line 48, in <module>
    from . import db, helpers, logger, network_timezones, notifiers, postProcessor, subtitles
  File "/usr/local/sickchill/sickbeard/helpers.py", line 55, in <module>
    import cloudscraper
  File "/usr/local/sickchill/lib/cloudscraper/__init__.py", line 27, in <module>
    from .exceptions import (
ImportError: cannot import name CloudflareLoopProtection
/usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill
root@sickchill:~ #

**Comment by foot-gloves** [comment]
> I have the same issue
> 
> Branch/Commit: current
> OS: FreeBSD 11.3-RELEASE-p6 (FreeNAS.amd64)
> Browser: Chrome
> What you did: Noticed Sickchill was down. Went to jail and tried to start service.
> What happened: Startup failed with error
> What you expected: Sickchill to start
> 
> This is what I get:
> 
> `root@sickchill:~ # service sickchill start Starting sickchill. Traceback (most recent call last): File "/usr/local/sickchill/SickBeard.py", line 67, in <module> import sickbeard File "/usr/local/sickchill/sickbeard/__init__.py", line 41, in <module> import sickchill File "/usr/local/sickchill/sickchill/__init__.py", line 5, in <module> from .show.indexers import indexer, ShowIndexer File "/usr/local/sickchill/sickchill/show/indexers/__init__.py", line 22, in <module> from .handler import ShowIndexer File "/usr/local/sickchill/sickchill/show/indexers/handler.py", line 31, in <module> from sickbeard.tv import Show File "/usr/local/sickchill/sickbeard/tv.py", line 48, in <module> from . import db, helpers, logger, network_timezones, notifiers, postProcessor, subtitles File "/usr/local/sickchill/sickbeard/helpers.py", line 55, in <module> import cloudscraper File "/usr/local/sickchill/lib/cloudscraper/__init__.py", line 27, in <module> from .exceptions import ( ImportError: cannot import name CloudflareLoopProtection /usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill root@sickchill:~ # `

see my comment above or issue 6208

**Comment by armontero** [comment]
> > I have the same issue
> > Branch/Commit: current
> > OS: FreeBSD 11.3-RELEASE-p6 (FreeNAS.amd64)
> > Browser: Chrome
> > What you did: Noticed Sickchill was down. Went to jail and tried to start service.
> > What happened: Startup failed with error
> > What you expected: Sickchill to start
> > This is what I get:
> > `root@sickchill:~ # service sickchill start Starting sickchill. Traceback (most recent call last): File "/usr/local/sickchill/SickBeard.py", line 67, in <module> import sickbeard File "/usr/local/sickchill/sickbeard/__init__.py", line 41, in <module> import sickchill File "/usr/local/sickchill/sickchill/__init__.py", line 5, in <module> from .show.indexers import indexer, ShowIndexer File "/usr/local/sickchill/sickchill/show/indexers/__init__.py", line 22, in <module> from .handler import ShowIndexer File "/usr/local/sickchill/sickchill/show/indexers/handler.py", line 31, in <module> from sickbeard.tv import Show File "/usr/local/sickchill/sickbeard/tv.py", line 48, in <module> from . import db, helpers, logger, network_timezones, notifiers, postProcessor, subtitles File "/usr/local/sickchill/sickbeard/helpers.py", line 55, in <module> import cloudscraper File "/usr/local/sickchill/lib/cloudscraper/__init__.py", line 27, in <module> from .exceptions import ( ImportError: cannot import name CloudflareLoopProtection /usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill root@sickchill:~ # `
> 
> see my comment above or issue 6208

Thank you - I commented that section out and it started.  Will this impact the next update in any way, or will the next update just overwrite my change?

**Comment by nydave69** [comment]
Well I did as suggested...  comment out those lines...   started...
got a rash of errors, (15+)
2020-04-18 09:24:38 MAIN :: [460ab74] There was an error creating the show in M:\series\The Curse of Oak Island Behind the Dig (2018): Error cannot import name etree

this show and all the other has been there for years..  this is a current running show..
