### ISSUE TITLE
[APP SUBMITTED]: /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by djtazie** [SickChill/SickChill#6211]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/06dfc60e809cac72cf6eccc7d7878b4b
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/The British Tribe Next Door: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/6c4b475345a795bc0e77cfffab9fc517
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Treasure Island with Bear Grylls: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/6a9fcbba5a0ad0afc1ebb1d2fcc202fd
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Unsellable Houses: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/92610e59a3d61ae7e8eee1363cf7a3bb
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Celebrity IOU: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/b8feffdaf75a18e9e834f73ee0d0058d
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Outer Banks: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/fec6011acab7528140b99148f0babd96
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/90 Day Fiance Just Landed: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/4dd2c3bf1647f20d3c42777fcda69bd5
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Jungle Life: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/607347ef589345c25542c7e3f5a337f9
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Cop Car Workshop: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/1aa48d47b032d1ccb32b2b51a7648ef0
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Girls On Girls: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/d5cd8138c246cb2822dd1b765a131c1a
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Off The Grid On The Beach: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/59718ab780aec90958405e530fe8bef9
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Opening Night: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/4d99dd1650c39a73b59db128be45dc02
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/90 Day Fiance Just Landed: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/128fd2b88f3507b94ca58cd49db55116
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Jungle Life: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/24b68ed8818bb7c7b5316b8dbcfe27ee
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Cop Car Workshop: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/6fed1fc07397a007773b95025561a530
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Girls On Girls: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/822c5da6c5a2449c354fbe1a4169a72d
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Off The Grid On The Beach: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/95ba3b54cd5db292e9361c14332d7dcd
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Opening Night: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/f181383558f447da9d5e5a383a15472d
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/The British Tribe Next Door: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/a131a3ce5c1f851cfd3052f2d3f9a820
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Treasure Island with Bear Grylls: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/dffe02369aa75983f0dd5083909671d3
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Unsellable Houses: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/28699879acbab7ba6e129946d6bda98e
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Celebrity IOU: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by djtazie** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/3cbe82b935b9e1447d03cf078de9d87b
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /mnt/shows/Outer Banks: Error /opt/sickchill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by phirestalker** [comment]
Having the same problem on macOS with up to date Sickchill.

**Comment by Wensh** [comment]
**INFO**

Python Version: 2.7.14 (default, May 28 2018, 15:05:24) [GCC 4.6.4]
Operating System: Linux-3.2.40-armv7l-with-glibc2.4 (DSM 6.2.2-24922 Update 4)
Locale: UTF-8
Branch: master
Commit: 9aa8ab5

**ERROR**

`MAIN :: [9aa8ab5] There was an error creating the show in /volume1/downloads/Show: Error /volume1/@appstore/sickbeard-custom/var/SickBeard/lib/lxml/etree.so: wrong ELF class: ELFCLASS64`

**Comment by miigotu** [comment]
Update, if you have issues you will have to pip install lxml manually.
