### ISSUE TITLE
Unable to get SickChill to add show on Raspberry Pi 4 - Can't add shows/wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by sunrisepi** [SickChill/SickChill#6212]
I've used Sickchill on a Raspberry Pi 3b with no issues.  Trying to install now on Raspberry Pi 4b and it's not letting me add a show, complains of a wrong ELF class: ELFCLASS64.

Tried to install by following steps here: https://www.htpcguides.com/install-sickrage-raspberry-pi-usenet-torrent-tv/

**Installed dependencies
sudo apt-get install python-pip python-dev git libssl-dev libxslt1-dev libxslt1.1 libxml2-dev libxml2 libssl-dev libffi-dev build-essential -y

sudo pip install pyopenssl

**Also installed unrar.

**Then ran git clone
git clone https://github.com/SickChill/SickChill.git

Now I am running via "python SickBeard.py" and it runs but when adding a show I get the error about ELFCLASS64.

I tried following steps here:  https://github.com/SickChill/SickChill/issues/6204.  Specifically these steps:

##
sudo apt install build-essential python2-pip
cd path/to/sickchill
pip install -Ut lib --force-reinstall -r requirements/requirements.txt
##

Get same error reported from  ddf2k2 (python2-pip not found and then below error):
##
Collecting mock (from -r requirements/requirements.txt (line 37)) Downloading https://www.piwheels.org/simple/mock/mock-4.0.0-py2.py3-none-any.whl mock requires Python '>=3.6' but the running Python is 2.7.16
##

So the pip install doesn't finish completely.

Would appreciate suggestions on how to get this working.  Thanks.

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:  Latest
OS: Raspberry Pi 4, 
Browser:  Firefox 
What you did: Tried to add a show
What happened: got ELFCLASS64 error
What you expected: Show to be added
Logs:
```
AA ImportError: /home/pi/SickChill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
AA from lxml import etree as ElementTree
AA File "/home/pi/SickChill/lib/imdb/parser/http/piculet.py", line 263, in 
AA from .piculet import Path, Rule, Rules
AA File "/home/pi/SickChill/lib/imdb/parser/http/companyParser.py", line 32, in 
AA from . import (
AA File "/home/pi/SickChill/lib/imdb/parser/http/__init__.py", line 40, in 
AA from .parser.http import IMDbHTTPAccessSystem
AA File "/home/pi/SickChill/lib/imdb/__init__.py", line 195, in IMDb
AA i = imdb.IMDb()
AA File "/home/pi/SickChill/sickbeard/tv.py", line 851, in loadIMDbInfo
AA self.show.loadIMDbInfo()
AA File "/home/pi/SickChill/sickbeard/show_queue.py", line 472, in run
AA Traceback (most recent call last):
2020-04-18 11:22:08 ERROR    SHOWQUEUE-ADD :: [9aa8ab5] Error loading IMDb info: /home/pi/SickChill/lib/lxml/etree.so: wrong ELF class: ELFCLASS64
2020-04-18 11:22:08 INFO     SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2020-04-18 11:22:06 INFO     SHOWQUEUE-ADD :: 75117: Unable to find the show in the database
2020-04-18 11:22:05 INFO     SHOWQUEUE-ADD :: Starting to add show by ShowDir: /media/USBHDD1/shares/TVShows/Antiques Roadshow (US)

```

**Comment by miigotu** [comment]
Update and sudo pip install lxml

**Comment by ddf2k2** [comment]
HI doing the above fixes the issue of not being able to add shows, However I am still getting an error for all the shows I tried to add earlier. I cant Add them. I have submitted a new error
