### ISSUE TITLE
[APP SUBMITTED]: dlopen(/Applications/SickChill/lib/lxml/etree.so, 2): no suitable image found.  Did find:
	/Applications/SickChill/lib/lxml/etree.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Applications/SickChill/lib/lxml/etree.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

### ISSUE THREAD

**Issue by jaxdomino** [SickChill/SickChill#6214]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 16:07:15) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]**
Operating System: **Darwin-19.4.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/956cd82b069b7ebba9eeb70698c6e98d
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /Volumes/Share/tv/Marvel's Hawkeye: Error dlopen(/Applications/SickChill/lib/lxml/etree.so, 2): no suitable image found.  Did find:
	/Applications/SickChill/lib/lxml/etree.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Applications/SickChill/lib/lxml/etree.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by jaxdomino** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 16:07:15) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]**
Operating System: **Darwin-19.4.0-x86_64-i386-64bit**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@9aa8ab5cbd57972ceeacc3411a8c04fa17597f88
Link to Log: https://gist.github.com/cb62075cc3817557881fedbec6878a13
### ERROR
```
MAIN :: [9aa8ab5] There was an error creating the show in /Volumes/Share/tv/Intruders (2014): Error dlopen(/Applications/SickChill/lib/lxml/etree.so, 2): no suitable image found.  Did find:
	/Applications/SickChill/lib/lxml/etree.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Applications/SickChill/lib/lxml/etree.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Update. Install lxml manually if you run into issues.
