### ISSUE TITLE
Mako Error for Search Settings after latest update

### ISSUE THREAD

**Issue by kesawi** [SickChill/SickChill#6219]
Branch/Commit: Master
OS: CentOS 7 docker linuxserver/sickchill
Browser: Windows 10 Firefox 75.0 64-bit & Internet Explorer V11.778.18362.0

Updated from `9c4c5c5af34af9bb95f958c7463b4afbfdf98918` to `4d23d38d26058711c3227f3329f988db2b3348d7` by downloading updated docker image and replacing existing container.

Selected `Search Settings` from menu and received the following Mako Error:
```
File /app/sickchill/sickbeard/clients/deluged.py:14, in :
from synchronousdeluge import DelugeClient
ImportError: No module named synchronousdeluge
```

Enabled debugging but logs show no error. Tried deleting `config.ini` and restarted container, but error still present. Have tried to access with both Firefox and Internet Explorer.

Reverted to previous build and used previous `config.ini` file and no error present.

**Comment by miigotu** [comment]
Should be fixed

**Comment by kesawi** [comment]
> 
> 
> Should be fixed

Confirmed it has resolved the issue for me. Thanks.
