### ISSUE TITLE
After update sickchill broken ??

### ISSUE THREAD

**Issue by Tankyspanky** [SickChill/SickChill#6221]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: latest update
OS: Debian Buster
Browser: Chrome
What you did: click update on the popup from sickchill 
What happened: he started to update and after "restart" nothing
What you expected: a newer version 

When i wanna start it this is what happens

aad@Plexi:/opt/sickchill$ python SickBeard.py 
Traceback (most recent call last):
  File "SickBeard.py", line 67, in <module>
    import sickbeard
  File "/opt/sickchill/sickbeard/__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "/opt/sickchill/sickbeard/providers/__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "/opt/sickchill/sickbeard/providers/abnormal.py", line 34, in <module>
    from sickchill.providers.torrent.TorrentProvider import TorrentProvider
  File "/opt/sickchill/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>
    from feedparser import FeedParserDict
ImportError: cannot import name FeedParserDict

**Comment by DasGreff** [comment]
I got it fixed following some instructions on #6214 

First of all, stop your sickchill instance ("systemctl stop sickchill")

1. Backup your sickchill directory (just to be safe) 
2. Run "git clean -df" in your sickchill directory
3. Remove all pyc file (ex: "find -name '*.pyc' -exec rm {} \;")
4. Start your sickchill instance ("systemctl start sickchill")

That dit the trick for me

**Comment by jangrewe** [comment]
For me it was sufficient to:
```
cd /path/to/sickchill
git pull
find -name '*.pyc' -delete
```
and then restart SickChill.

**Comment by Tankyspanky** [comment]
Its working again now ,
thanx

**Comment by djtazie** [comment]
> find -name '*.pyc' -delete

this worked for me as well , thanks , it took a small bit to start but all working again now
