### ISSUE TITLE
New install and database restore....  errors

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6223]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Windows 7
Browser: NA
What you did: Installed new copy of SickChill ...  not a problem at this point other then it gave version error (didn't have one)
Went to restore and restored the backup..  went ok..  Did a restart as suggested..
See errors below..  Log has 13 of these errors in it....
UI shows  There is a newer version available (you're 9 commit behind) — Update Now
I'm going to wait before doing anything else...
Suggestions welcome...

What happened:
What you expected:
Logs:
```
Restore: restoring DB and config.ini SUCCESSFUL!
07:48:50 WARNING::MAIN :: Restore: Unable to remove the cache/mako directory: error 3 : The system cannot find the path specified
07:48:54 ERROR::MAIN :: [290b22c] There was an error creating the show in N:\series\Looney Tunes (1929): Error DLL load failed: %1 is not a valid Win32 application.
Traceback (most recent call last):
  File "C:\SickChill\SickBeard.py", line 416, in load_shows_from_db
    cur_show = TVShow(sql_show[b'indexer'], sql_show[b'indexer_id'])
  File "C:\SickChill\sickbeard\tv.py", line 120, in __init__
    self.loadFromDB()
  File "C:\SickChill\sickbeard\tv.py", line 785, in loadFromDB
    self.loadIMDbInfo()
  File "C:\SickChill\sickbeard\tv.py", line 851, in loadIMDbInfo
    i = imdb.IMDb()
  File "C:\SickChill\lib\imdb\__init__.py", line 195, in IMDb
    from .parser.http import IMDbHTTPAccessSystem
  File "C:\SickChill\lib\imdb\parser\http\__init__.py", line 40, in <module>
    from . import (
  File "C:\SickChill\lib\imdb\parser\http\companyParser.py", line 32, in <module>
    from .piculet import Path, Rule, Rules
  File "C:\SickChill\lib\imdb\parser\http\piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: DLL load failed: %1 is not a valid Win32 application.
07:48:55 ERROR::MAIN :: [290b22c] There was an error creating the show in N:\series\Discovery Understanding (1994): Error DLL load failed: %1 is not a valid Win32 application.
Traceback (most recent call last):
  File "C:\SickChill\SickBeard.py", line 416, in load_shows_from_db
```

**Comment by nydave69** [comment]
Found this in the logs...
Restore: Unable to remove the cache/mako directory: error 3 : The system cannot find the path specified..

**Comment by hanshendrix** [comment]
I installed the update this morning en now i can't open SickChill anymore on my Synology.
What can i do. Sorry for my bad English.

![SickChill](https://user-images.githubusercontent.com/60215088/79687507-f866d880-8247-11ea-91b6-c3f7689eea6b.JPG)

**Comment by rmagasi** [comment]
Same issue here at my DS918+ and one another NAS.

**Comment by P-Verbrugge** [comment]
> I installed the update this morning en now i can't open SickChill anymore on my Synology DS918+.
> What can i do. Sorry for my bad English.
> 
> ![SickChill](https://user-images.githubusercontent.com/60215088/79687507-f866d880-8247-11ea-91b6-c3f7689eea6b.JPG)

You can always login with SSH and checkout an older working version, until this issue is fixed.

**Comment by hanshendrix** [comment]
> I installed the update this morning en now i can't open SickChill anymore on my Synology DS918+.
> What can i do. Sorry for my bad English.
> 
> 
> You can always login with SSH and checkout an older working version, until this issue is fixed.

That's fine, but I don't now how too work with SSH, I'll wait until the issue is fixed.

**Comment by miigotu** [comment]
Current version is not broken, the residual files from the old version are. Check the pinned issue.
