### ISSUE TITLE
SickChill not starting after last update

### ISSUE THREAD

**Issue by rmagasi** [SickChill/SickChill#6224]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 289e0795cc3c1a579595aae5a3e60a75764382cf
OS: Synology DSM 6.2.2-24922 Update 6
Browser: Edge Chromium but doesnt matter
What you did: Update to latest commit
What happened: Sickchill is not starting
What you expected: to start
Logs:
```
cant find logs
```
![image](https://user-images.githubusercontent.com/24958713/79688089-1cc4b400-824c-11ea-8706-088d927ce62e.png)

**Comment by P-Verbrugge** [comment]
You can login via SSH and checkout an older version until it's fixed. Did the same just now.

**Comment by MrHappy** [comment]
It doesn't start on Windows either. Starting it from command prompt throws me this error:
`ImportError: cannot import name FeedParserDict`

**Comment by mbnoimi** [comment]
Same bug under Linux Mint 19.3

```
$ python ~/SickRage/SickBeard.py --daemon
Traceback (most recent call last):
  File "/home/media-servers/SickRage/SickBeard.py", line 67, in <module>
    import sickbeard
  File "/home/media-servers/SickRage/sickbeard/__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "/home/media-servers/SickRage/sickbeard/providers/__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "/home/media-servers/SickRage/sickbeard/providers/abnormal.py", line 34, in <module>
    from sickchill.providers.torrent.TorrentProvider import TorrentProvider
  File "/home/media-servers/SickRage/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>
    from feedparser import FeedParserDict
ImportError: cannot import name FeedParserDict
```

**Comment by kainhofer** [comment]
Seems to be the same issue as #6225. On my synology diskstation, I get the same traceback as @mbnoimi on Linux.

**Comment by rmagasi** [comment]
> You can login via SSH and checkout an older version until it's fixed. Did the same just now.

Thanks! Could you please share the commands to do it?

**Comment by vkbo** [comment]
Same here on Debian 10.
You can run `git reset --hard HEAD^1` in the folder to step backwards in history. I had to do it 8 times before it started. That puts you "8 commits behind" in the update box, and just leave that for now.

**Comment by mbnoimi** [comment]
I could fix this issue as following:
1. Backed up `config.ini` and `sickbeard.db`
2. Deleted `SickChill` folder
3. Cloned `SickChill` from the scratch
4. Run `SickChill` then shurdown it
5. Restored `config.ini` and `sickbeard.db` to the new folder
6. Run `SickChill` then run a `Mass Update` for `Rescan` and `Update` for the whole TV Shows I've.

**Comment by rmagasi** [comment]
> Same here on Debian 10.
> 
> You can run `git reset --hard HEAD^1` in the folder to step backwards in history. I had to do it 8 times before it started. That puts you "8 commits behind" in the update box, and just leave that for now.
> 
> Note: Checking out an older commit puts you in detached mode, which means you're no longer on the master branch. It's not a big issue, but generates a few errors.

Thank you, that worked for me as well!

**Comment by vkbo** [comment]
Just make sure you don't have automatic updates on, or it will revert whenever that runs.

**Comment by gdeans** [comment]
Same on Debian 10 and I did the reinstall route mentioned by @mbnoimi but it took a few manual starts before the service would run.  Now I get the error about local being ahead of master.  WTF guys?  Why does this always happen?  At least I don't seem to be getting that stupid recaptcha error.

`2020-04-19 10:41:00 CHECKVERSION :: git pull -f origin master returned : (128) From https://github.com/SickChill/SickChill
 * branch                  master     -> FETCH_HEAD
error: The following untracked working tree files would be overwritten by merge:
  [... file list]
2020-04-19 10:40:53 CHECKVERSION :: Local branch is ahead of master. Automatic update not possible.
`

**Comment by mbnoimi** [comment]
> Same on Debian 10 and I did the reinstall route mentioned by @mbnoimi but it took a few manual starts before the service would run. Now I get the error about local being ahead of master. WTF guys? Why does this always happen? At least I don't seem to be getting that stupid recaptcha error.

Hmm, It works fine for me but I suspect you didn't delete the old folder completely. Try to use `rm -fr SickChill` then run `python SickChill/SickBeard.py --daemon`

**Comment by BenjV** [comment]
The latest source of SickChill has a problem with importing 'feedparserdict'
To fix this you must change the python source so this object can be correctly imported.

Locate this file:
### /volume1/@appstore/sickchill/var/SickBeard/sickchill/providers/torrent/TorrentProvider.py
and change
### from feedparser import FeedParserDict
into
### from feedparser.util import FeedParserDict

After that SickChill will start again.

**Comment by meyersbs** [comment]
> Same here on Debian 10.
> 
> You can run `git reset --hard HEAD^1` in the folder to step backwards in history. I had to do it 8 times before it started. That puts you "8 commits behind" in the update box, and just leave that for now.
> 
> Note: Checking out an older commit puts you in detached mode, which means you're no longer on the master branch. It's not a big issue, but generates a few errors.

Confirmed: 8 commits back did the trick on Ubuntu 18.04

**Comment by jaharkema** [comment]
> The latest source of SickChill has a problem with importing 'feedparserdict'
> To fix this you must change the python source so this object can be correctly imported.
> 
> Locate this file:
> 
> ### /volume1/@appstore/sickchill/var/SickBeard/sickchill/providers/torrent/TorrentProvider.py
> and change
> 
> ### from feedparser import FeedParserDict
> into
> 
> ### from feedparser.util import FeedParserDict
> After that SickChill will start again.
> 
> Of course on other platforms then Synology the location of SickChiil will be below /volume1/@appstore but on the normal installation folder for your system

What I don't get is why it takes 4+ hours and no response from the developers. It's a fairly easy fix, by the looks of it. Why hasn't an update been shipped yet? Why was the bug released in the first place? Are there no tests being done?

I read a lot of people turned off automatic updates. Which is a really worrying trend for a package which master branch is supposed to be stable.

**Comment by gdeans** [comment]
@mbnoimi I did remove the entire folder and it is working now.  It just took a few starts for it to work right.  The big problem is this isn’t the first time they’ve hosed up the branches.

**Comment by knelmes** [comment]
> What I don't get is why it takes 4+ hours and no response from the developers. It's a fairly easy fix, by the looks of it. Why hasn't an update been shipped yet? 

Probably because it looks like there is only one active developer, who may be blissfully unaware of this, having a quiet Sunday.

**Comment by miigotu** [comment]
@jaharkema fuck off with your ignorance. That isn't the fix and if you checked the pinned issue you would see the solution. I was up over 20 hours working on 600,000 changes. Some people actually have to fucking sleep.

**Comment by rmagasi** [comment]
> The latest source of SickChill has a problem with importing 'feedparserdict'
> To fix this you must change the python source so this object can be correctly imported.
> 
> Locate this file:
> 
> ### /volume1/@appstore/sickchill/var/SickBeard/sickchill/providers/torrent/TorrentProvider.py
> and change
> 
> ### from feedparser import FeedParserDict
> into
> 
> ### from feedparser.util import FeedParserDict
> After that SickChill will start again.
> 
> Of course on other platforms then Synology the location of SickChiil will be below /volume1/@appstore but on the normal installation folder for your system

Thank you BenjV! This fixed it!

**Comment by miigotu** [comment]
There is nothing wrong with the feedparser import. You are actually breaking it by doing that.

Check. The. Pinned. Issue.

**Comment by gdeans** [comment]
Well, I guess I spoke too soon.  The recaptcha error is back.

**Comment by miigotu** [comment]
> @mbnoimi I did remove the entire folder and it is working now. It just took a few starts for it to work right. The big problem is this isn’t the first time they’ve hosed up the branches.
Idk wtf you mean by "hosed up the branches" but the code isn't broken, its residual files left behind by git and python. So if you want to be a dick to someone direct it to another *free software you didn't fucking pay for*

Also, cloudflare recaptcha error has nothing to do with this issue OR SC code.

**Comment by gdeans** [comment]
Damn, didn't know this would make you so touchy but I'm just chiming in on the same error other people are having.  Calling out a problem is not being a dick, it's part of what open source is all about.
Local branch is ahead of master isn't the fault of the update process.  If it is, then fix the update script.  If I have this automatically updating and it ends up with a problem, then it was a problem with the underlying files or the update process.  I'm just trying to get some help, not a bunch of undeserved attitude.
As for the recaptcha issue, I never said it was related.  If there's a fix for it I haven't found it yet.
If you're sore about supporting free software, then don't release it as free.  I'm just commenting on a bug, so if you can't handle that, maybe you're too thin skinned to do this

**Comment by miigotu** [comment]
@gdeans your bullshit comments `The big problem is this isn’t the first time they’ve hosed up the branches.` are simply bullshit. Local branch ahead of master is by your dumb ass thinking you know something and modifying the repository, and checking out incorrect revisions. If you wanna make some PR's go for it. I'm not too thin skinned, I just absolutely will not sit here and be bad mouthed by a self righteous, arrogant and entitled prick who thinks people who do shit for free owe them something.

**Comment by v0d0r** [comment]
lol I cant believe the nerve of some folk. the responses was quite a good laugh thanks for that miigotu.  thats for your hours of time giving us stuff for free.
Anyway so I run Sickchill on qnap and ran into the same issue after updating trying to fix the IMDB offline issue.
For now I rolled back versions to the below version. After this it seems this new issue was introduced.

[/opt/SickChill/SickChill] # git reset --hard HEAD^1
Checking out files: 100% (2055/2055), done.
HEAD is now at 77822cbf3 Fix adding from imdbpopular

**Comment by miigotu** [comment]
There are like 50 commits after imdbpopular. See #6230

**Comment by DamienBraillard** [comment]
> The latest source of SickChill has a problem with importing 'feedparserdict'
> To fix this you must change the python source so this object can be correctly imported.
> 
> Locate this file:
> ### /volume1/@appstore/sickchill/var/SickBeard/sickchill/providers/torrent/TorrentProvider.py
> 
> and change
> ### from feedparser import FeedParserDict
> 
> into
> ### from feedparser.util import FeedParserDict
> 
> After that SickChill will start again.
> 
> Of course on other platforms then Synology the location of SickChiil will be below /volume1/@appstore but on the normal installation folder for your system
> 
> #######################################################################
> **EDIT:**
> Although this fix worked it is not the correct solution and will create problems with futher upgrades.
> This solution is posted by @miigotu in #6214:
> 
> remove "D:<snip>\SickRage\lib\feedparser" directory not the feedparser.py
> remove "D:<snip>\SickRage\lib\cloudscraper\exceptions" directory not the exceptions.py
> remove ``"D:\SickRage\lib\lxml"`

For those wou did not find the solution right away, this is the one
