### ISSUE TITLE
Sickchill not starting after latest update on Windows.

### ISSUE THREAD

**Issue by mwbinkley** [SickChill/SickChill#6225]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by ejc1967** [comment]
Same here on a Synology.

**Comment by freeextreme** [comment]
Same issue here on Synology. Went back to latest image and now 317 commits behind.

**Comment by kainhofer** [comment]
Same here on Synology. I manually made sure I'm up to latest origin/master in git.

The relevant log file on the diskstation is:

Full log: /volume1/@appstore/sickbeard-custom/var/sickbeard-custom.log
Sun Apr 19 15:21:33 CEST 2020
```
Starting sickbeard-custom command /volume1/@appstore/sickbeard-custom/env/bin/python /volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py --daemon --pidfile /volume1/@appstore/sickbeard-custom/var/sickbeard-custom.pid --
config /volume1/@appstore/sickbeard-custom/var/config.ini --datadir /volume1/@appstore/sickbeard-custom/var/
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2n  7 Dec 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpe
cted reCaptcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py", line 67, in <module>
    import sickbeard
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/abnormal.py", line 34, in <module>
    from sickchill.providers.torrent.TorrentProvider import TorrentProvider
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>
    from feedparser import FeedParserDict
ImportError: cannot import name FeedParserDict
```

**Comment by skydiverscott** [comment]
Same thing here... Running on window  via git:
`d:\SickChill>python d:\SickChill\SickBeard.py
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2q  20 Nov 2018) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "d:\SickChill\SickBeard.py", line 67, in <module>
    import sickbeard
  File "d:\SickChill\sickbeard\__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "d:\SickChill\sickbeard\providers\__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "d:\SickChill\sickbeard\providers\abnormal.py", line 34, in <module>
    from sickchill.providers.torrent.TorrentProvider import TorrentProvider
  File "d:\SickChill\sickchill\providers\torrent\TorrentProvider.py", line 25, in <module>
    from feedparser import FeedParserDict
ImportError: cannot import name FeedParserDict`

What is the command to roll back the version via git?

**Comment by ryandanger** [comment]
https://github.com/SickChill/SickChill/wiki/FAQ's-and-Fixes#how-to-switch-to-an-older-sickchill-version

run `git checkout v2020.04.18-1` to roll back. This version confirmed working on my Windows 10 environment.

**Comment by p88h** [comment]
Actually a bit later than that still works, you can go to v2020.04.18-3 + 1 commit, and the better way than checkout would be:

`git reset --hard 77822cbf3640030f875077f052117f209abe6bf2`
goes back to the last working commit. 

BTWt There is one other import error in bf9dd8a7676a2065f53d4abd13e1ac3ecf81068c beyond the FeedParserDict one, after fixing TorrentProvider you would get:
`
Traceback (most recent call last):
  File "./SickBeard.py", line 67, in <module>
    import sickbeard
  File "/home/usenet/sickrage/sickbeard/__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "/home/usenet/sickrage/sickbeard/providers/__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "/home/usenet/sickrage/sickbeard/providers/thepiratebay.py", line 28, in <module>
    import js2py
  File "/home/usenet/sickrage/lib/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
  File "/home/usenet/sickrage/lib/js2py/base.py", line 5, in <module>
    from .translators.friendly_nodes import REGEXP_CONVERTER
  File "/home/usenet/sickrage/lib/js2py/translators/__init__.py", line 28, in <module>
    from .translator import translate_js, trasnlate, syntax_tree_translate, DEFAULT_HEADER
  File "/home/usenet/sickrage/lib/js2py/translators/translator.py", line 2, in <module>
    import pyjsparser.parser
ImportError: No module named parser
`
which is a bit less obvious, and there are more pyjsparser issues later on.

**Comment by labbean** [comment]
git reset --hard 77822cbf3640030f875077f052117f209abe6bf2 got me back nto GUI (Win10)

**Comment by BKSteve** [comment]
Thanks @p88h works with Synology too.

**Comment by BenjV** [comment]
The latest source of SickChill has a problem with importing 'feedparserdict'
To fix this you must change the python source so this object can be correctly imported.
Locate this file:

SickBeard/sickchill/providers/torrent/TorrentProvider.py
On Synology you can find this below /volume1/@appstore/sickchill/var/

and change
from feedparser import FeedParserDict
into
from feedparser.util import FeedParserDict
After that SickChill will start again.

**Comment by miigotu** [comment]
Downgrading isn't the fix. The current head is not broken, it's the install that breaks on update. Check the pinned post.
