### ISSUE TITLE
Add Show - Mako Error

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#6227]
I have had a problem with the show Supernatural for a few weeks, if I try to force update nothing changes however on TheTVDB the airdates have been updated and I couldn't get that to pull through. I removed and re-added the show and now if I try to open it I get Mako errors

A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes. 

Commit: 83e43932e0cbbf200472bb1a96f0580cddaf0e4c
OS: Windows
Browser: Chrome/Firefox
Version: v2020.04.18-1
Database Version: 44.1

What you did: Ran the update to the latest version, that wouldn't even run on W10 so I rolled back to v2020.04.18-1. I retried forcing a refresh on Supernatural but again nothing changed so I removed and re-added the show and get Mako errors
What happened: I got Mako errors instead of the show entry in the show list, the best I can say is it now has the correct count of episodes.
What you expected: To be able to re-add the show and get correct listing details
Logs:
```
File C:/SickChill/SickChill/gui/slick/views/displayShow.mako:140, in render_content:
                                                                ${show.imdb_info['runtimes']} ${_('minutes')}

                    KeyError: 'runtimes'

I cannot see any errors in the logs, even if I select debug
```

**Comment by miigotu** [comment]
Rolling back isnt the solution, see the pinned issue.

**Comment by rutskiuk** [comment]
Rolling back really wasn't!
Sadly the fix didn't work for me because I installed using Git for windows meaning I didn't have a git folder. Fortunately I found a git folder on another installation and copied that over and got it working again.
