### ISSUE TITLE
Feedparser Exit Error, SickChill Not Starting

### ISSUE THREAD

**Issue by overloadsix** [SickChill/SickChill#6229]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 
OS: Linux 18.04
Browser: Brave
What you did: stopped the service, started the service, ran the .py in the opt folder, also checked UFW to ensure 8081 is open
What happened: All attempts show failed to start Sickchill.
What you expected: I went to the tab I have set for Sickchill and I got a refused connection when I reloaded the page for Sickchill. I have not changed anything to the program EXCEPT added a customized search provider, RARBG from Jackett. I can't imagine adding a customized search provider would cause the package to crash entirely. I can send any other logs if needed.
Logs:
```
PASTE LOGS HERE
```
-- Unit sickchill.service has begun starting up.
Apr 19 15:47:42 anthem python2.7[25119]: Traceback (most recent call last):
Apr 19 15:47:42 anthem python2.7[25119]:   File "/opt/sickchill/SickBeard.py", line 67, in <module>
Apr 19 15:47:42 anthem python2.7[25119]:     import sickbeard
Apr 19 15:47:42 anthem python2.7[25119]:   File "/opt/sickchill/sickbeard/__init__.py", line 49, in <module>
Apr 19 15:47:42 anthem python2.7[25119]:     from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
Apr 19 15:47:42 anthem python2.7[25119]:   File "/opt/sickchill/sickbeard/providers/__init__.py", line 29, in <module>
Apr 19 15:47:42 anthem python2.7[25119]:     from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
Apr 19 15:47:42 anthem python2.7[25119]:   File "/opt/sickchill/sickbeard/providers/abnormal.py", line 34, in <module>
Apr 19 15:47:42 anthem python2.7[25119]:     from sickchill.providers.torrent.TorrentProvider import TorrentProvider
Apr 19 15:47:42 anthem python2.7[25119]:   File "/opt/sickchill/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>
Apr 19 15:47:42 anthem python2.7[25119]:     from feedparser import FeedParserDict
Apr 19 15:47:42 anthem python2.7[25119]: ImportError: cannot import name FeedParserDict
Apr 19 15:47:42 anthem systemd[1]: sickchill.service: Control process exited, code=exited status=1
Apr 19 15:47:42 anthem systemd[1]: sickchill.service: Failed with result 'exit-code'.
Apr 19 15:47:42 anthem systemd[1]: Failed to start SickChill Daemon.
-- Subject: Unit sickchill.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support

**Comment by miigotu** [comment]
```
rm -r /opt/sickchill/lib/feedparser /opt/sickchill/lib/lxml /opt/sickchill/cloudscraper/exceptions
```

**Comment by miigotu** [comment]
#6230
