### ISSUE TITLE
Sickchill Timezone Not correct

### ISSUE THREAD

**Issue by ebaydan777** [SickChill/SickChill#6233]
I understand you stated timezone is not set, however it is set to local both on sickchill and synology is reading proper time locally.

Yet the downloads are set for 1 day in advance. Please advise how to fix this before deleting. Thank you

**Comment by miigotu** [comment]
If you keep opening a new issue every time you have something to say imma have to block you. Everyone gets notifications if they are participating in an issue whether it is closed or not.

**Comment by miigotu** [comment]
Your downloads btw are like 3 hours off. After midnight it becomes another day. So an episode that airs at 10pm on the west coast, downloads in SC at 1am+runtime the next day because of the 3 hour time difference.
