### ISSUE TITLE
Failed to start sick chill

### ISSUE THREAD

**Issue by armontero** [SickChill/SickChill#6235]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/current
OS: FreeNAS 11.3-U2
Browser: Chrome
What you did: Noticed sickchill wasn't up, logged into jail to start
What happened: sickchill fails to start with the error below
What you expected: sickchill should start
Logs:
`root@sickchill:/usr/local/sickchill # service sickchill start
Starting sickchill.
Traceback (most recent call last):
  File "/usr/local/sickchill/SickBeard.py", line 67, in <module>
    import sickbeard
  File "/usr/local/sickchill/sickbeard/__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "/usr/local/sickchill/sickbeard/providers/__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "/usr/local/sickchill/sickbeard/providers/abnormal.py", line 34, in <module>
    from sickchill.providers.torrent.TorrentProvider import TorrentProvider
  File "/usr/local/sickchill/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>
    from feedparser import FeedParserDict
ImportError: cannot import name FeedParserDict
/usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill
root@sickchill:/usr/local/sickchill #`

**Comment by rschitz** [comment]
same here after auto-update SickChill Updated : SickChill Updated To Commit#: f9f74d973779a2e29ed60d0cb42216079854aed5

Apr 19 23:08:43 vmk-vcr-01 python2.7[706]:     from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien…t, filelist,
Apr 19 23:08:43 vmk-vcr-01 python2.7[706]:   File "/opt/sickchill/sickbeard/providers/abnormal.py", line 34, in <module>
Apr 19 23:08:43 vmk-vcr-01 python2.7[706]:     from sickchill.providers.torrent.TorrentProvider import TorrentProvider
Apr 19 23:08:43 vmk-vcr-01 python2.7[706]:   File "/opt/sickchill/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>
Apr 19 23:08:43 vmk-vcr-01 python2.7[706]:     from feedparser import FeedParserDict
Apr 19 23:08:43 vmk-vcr-01 python2.7[706]: ImportError: cannot import name FeedParserDict
Apr 19 23:08:43 vmk-vcr-01 systemd[1]: sickchill.service: Control process exited, code=exited status=1
Apr 19 23:08:43 vmk-vcr-01 systemd[1]: Failed to start SickChill Daemon.
Apr 19 23:08:43 vmk-vcr-01 systemd[1]: sickchill.service: Unit entered failed state.
Apr 19 23:08:43 vmk-vcr-01 systemd[1]: sickchill.service: Failed with result 'exit-code'.


tried a git pull but no luck

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/issues/6230

**Comment by rschitz** [comment]
> #6230

worked, thanks a lot
