### ISSUE TITLE
Unable to start SickChill since updating to Master today - errors with js2py

### ISSUE THREAD

**Issue by bigwavedave42** [SickChill/SickChill#6236]
My specific errors:
```bash
$ python SickBeard.py
Traceback (most recent call last):
  File "SickBeard.py", line 67, in <module>
    import sickbeard
  File "/home/user42/SickRage/sickbeard/__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_                     processing_queue, properFinder, providers,
  File "/home/user42/SickRage/sickbeard/providers/__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "/home/user42/SickRage/sickbeard/providers/thepiratebay.py", line 28, in <module>
    import js2py
  File "/home/user42/SickRage/lib/js2py/__init__.py", line 73, in <module>
    from .evaljs import *
  File "/home/user42/SickRage/lib/js2py/evaljs.py", line 155
    exec (DEFAULT_HEADER, self._context)
SyntaxError: unqualified exec is not allowed in function '__init__' it contains a nested function with free variables
```
_Originally posted by @bigwavedave42 in https://github.com/SickChill/SickChill/issues/6217#issuecomment-616231452_

**Comment by miigotu** [comment]
https://github.com/PiotrDabkowski/Js2Py/issues/193
What version is your python?

**Comment by bigwavedave42** [comment]
$ python --version
Python 2.7.5

If I try with Python 3:
$ python3 --version
Python 3.6.8

$ python3 SickBeard.py
Sorry, requires Python at least 2.7 but less than 3

**Comment by bigwavedave42** [comment]
OK, just did ANOTHER git pull (20th+ of the day) and got some more updates:

$git pull
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 11 (delta 5), reused 11 (delta 5), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://github.com/SickChill/SickChill
   ddeceaa..f397a0d  master     -> origin/master
   a258157..f397a0d  develop    -> origin/develop
 * [new tag]         v2020.04.19-9 -> v2020.04.19-9
From https://github.com/SickChill/SickChill
 * [new tag]         v2020.04.19-8 -> v2020.04.19-8
Updating ddeceaa..f397a0d
Fast-forward
 sickbeard/providers/thepiratebay.py | 19 ++++++++++++++++++-
 sickbeard/tv.py                     | 43 +++++++++++++++++++++----------------------
 sickbeard/versionChecker.py         | 46 +++++++++++++++++++++++++++++++++++++++++++++-
 sickchill/show/indexers/handler.py  |  5 +----
 4 files changed, 85 insertions(+), 28 deletions(-)



It is working again!  So, one of the updates above seems to have fixed it.  I'm still using Python 2.7.5 for this success.

Since the errors had been pointing to thepiratebay.py (among others) and the file was pulled in with updates... 
Looking at 21fded0e2da4f59a42daf4de80edbbb439e4ac3c it seems you found it (and now I'm seeing you referenced it above).

Confirming that it is now working as desired/expected.
