### ISSUE TITLE
Missing provider : YggTorrent

### ISSUE THREAD

**Issue by mohegan** [SickChill/SickChill#6241]
After a new installation from git, the YggTorrent is missing in Search Providers List. 
The files (/opt/sickchill/sickbeard/providers/yggtorrent.py and /opt/sickchill/sickbeard/providers/yggtorrent.pyc) are presents but it is missing. 

I test also the devolop branch and it is the same.

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Ubuntu 18.04.4 Server
Browser: 
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Because that provider is not working, hasnt been for a long time due to cloudflare. It is disabled.

**Comment by elgofo** [comment]
been banging my head on this for like 1hour....should have rtfm. thanks !!
