### ISSUE TITLE
[APP SUBMITTED]: str() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by vroemraw** [SickChill/SickChill#6244]
### INFO
Python Version: **2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.15.18-seedhost-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@518e33e628df975eb178c2a6b8541066818a2359
Link to Log: https://gist.github.com/e558bf910c37420e10259b306e2ba1b6
### ERROR
```
WEBSERVER-HOME :: [518e33e] Failed doing webui callback: Traceback (most recent call last):
  File "/home14/vroemraw/software/SickRage/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
  File "/home14/vroemraw/software/SickRage/sickchill/views/home.py", line 1842, in fetch_releasegroups
    groups = anime.get_groups()
  File "/home14/vroemraw/software/SickRage/adba/aniDBAbstracter.py", line 174, in get_groups
    self.release_groups.append({"name": str(line["name"], "utf-8"),
TypeError: str() takes at most 1 argument (2 given)

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Zetsuo** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@518e33e628df975eb178c2a6b8541066818a2359
Link to Log: https://gist.github.com/bc37ade547f42fcc5351f0f96eb5f5b7
### ERROR
```
WEBSERVER-HOME :: [518e33e] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickchill/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
  File "/opt/sickchill/sickchill/views/home.py", line 1842, in fetch_releasegroups
    groups = anime.get_groups()
  File "/opt/sickchill/adba/aniDBAbstracter.py", line 174, in get_groups
    self.release_groups.append({"name": str(line["name"], "utf-8"),
TypeError: str() takes at most 1 argument (2 given)

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
