### ISSUE TITLE
Scheduled automatic backups

### ISSUE THREAD

**Issue by tinyhands01** [SickChill/SickChill#6247]
Feature Request:
Because it's a manual process, the last backup I was able to find was over a year old.  When a recent update caused SickChill not to run, I wasn't able to use the webgui to make a backup package, but I was able to SSH in and backup the .ini and .db files myself and get back to where I was after fixing the latest update.

My suggestion is to, in the gui, schedule backups to happen automatically.  Allow the user to set a schedule of hours/days/weeks months, number of backups to retain, and a backup folder outside the installation.  For example, I would probably set mine for weekly backups and retain the last 6 to a subdirectory of my /home. 

(sorry, I don't see how to add labels such as feature request - maybe I don't have permission)

**Comment by miigotu** [comment]
This already happens on every update.

**Comment by tinyhands01** [comment]
Only in the install var directory, correct?  I can't reinstall and restore those backups without SSH into the box.  If a backup is stored elsewhere, as it is when I manually use the gui backup, then I can use that to restore.

**Comment by miigotu** [comment]
In the data dir in a folder called backups. It always keeps the latest version. Your data dir yould not be inside the SC source directory.
