### ISSUE TITLE
Wrong path when changing location on mass update

### ISSUE THREAD

**Issue by vitinhosessa** [SickChill/SickChill#6249]
Branch/Commit: master / 6ca4546faa2c23f2f6e87e7f93f5a587b26b1633
OS: ubuntu server 18.04.4
Browser: chrome
What you did: tried to change location of some series
What happened: the last path was added with the new path
What you expected: the location changes to the new path
Logs:
```
2020-04-21 04:56:12 WEBSERVER-MANAGE :: [6ca4546] Errors: [u'New location /hds/hd2/Seriados/X:\\Seriados\\American Gods does not exist']
2020-04-21 04:56:10 WEBSERVER-MANAGE :: [6ca4546] Errors: [u'New location /hds/hd2/Seriados/X:\\Seriados\\The 100 does not exist']
2020-04-21 04:56:08 WEBSERVER-MANAGE :: [6ca4546] Errors: [u'New location /hds/hd2/Seriados/X:\\Seriados\\24 does not exist']
```

The old path: `X:\Seriados\24`
The new path `/hds/hd2/Seriados/24`

But when i try to change, both are combined and i cant change. I have to change one by one.

**Comment by miigotu** [comment]
This is due to switching from Windows to Linux. Normally this wouldn't be an issue, but since the path separator is different it is confused. 

I will see if I can come up with something but if you can't wait:

You can edit them manually, or with something like this:
(Off the top of my head, typed on a phone)
```bash
sqlite3 sickbeard.db
```
```sql
UPDATE tv_episodes WHERE location LIKE "X:\Seriados\%" SET location=REPLACE(location, "X:\Seriados\", "/hds/hd2/Seriados/") WHERE location LIKE "X:\Seriados\%";

UPDATE tv_episodes SET location=REPLACE(location, "/hds/hd2/Seriados/X:\Seriados\", "/hds/hd2/Seriados/") WHERE location LIKE "/hds/hd2/Seriados/X:\Seriados\"
```

**Comment by miigotu** [comment]
Update and try again =P
