### ISSUE TITLE
No refresh possible for ended or pauzed shows after restore

### ISSUE THREAD

**Issue by Ventje23** [SickChill/SickChill#6250]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master /  518e33e628df975eb178c2a6b8541066818a2359
OS: Linux-3.10.35-x86_64-with-glibc2.2.5
Browser: Chrome
What you did: due to the startup error(s) earlier this week wih Sickchill after the latest updates I had to do a reinstall of Sickchill. So I removed Sickchill from my Synology, installed it again with BenjiV app and restored the database and did a mass update with option re-scan files. All the shows that are ended or paused aren't updating, so no backgrounds, banners, posters etc.
Only a force full update works in case of paused or ended show.
I have no idea if this is intend by design.

What happened: All the shows that were not ended or paused were updated. The rest not, so no posters, banners etc. for those shows.
What you expected: That after a restore with a mass update + resacen files also rescans the stopped and paused shows so that posters, banners etc. are "restored" too.
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
This is intended, because paused shows are paused to prevent from being changed.
Ended shows only update every 7 days by default, to avoid spam to tvdb as much as possible.

I will make it so the button on the show page works to refresh, but thats all I can do.

**Comment by miigotu** [comment]
5a9ea4b464ff8564a93f0b10ac6a35737d8d83dd

**Comment by Ventje23** [comment]
Hi,

thanks for super fast reply. sounds like a good workaround. 
Isn't there an option to force a rescan for shows during a restore if e.g. the folder with the banners, posters etc. doesn't exist (e.g. in case of a remove +reinstall +restore db of Sickchill)?
