### ISSUE TITLE
Add Exisiting Shows not working as expected/intended

### ISSUE THREAD

**Issue by zeveroare** [SickChill/SickChill#6251]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/6ca4546faa2c23f2f6e87e7f93f5a587b26b1633
OS: QNAP
Browser: Firefox/chrome
What you did: Add shows - Add existing shows
What happened: It shows -all- of them instead of just those that are not already added
What you expected: Just the shows that are not already in the database
Logs: Nothing relevant shown in logs 
```
I tried with and without debugging logs, it doesn't show anything about my action.
```

**Comment by miigotu** [comment]
Not here it doesnt

**Comment by zeveroare** [comment]
Is there a way for me to see what happens somewhere? Or to log what is happening on my end?

**Comment by miigotu** [comment]
@zeveroare that is not the add existing shows page...

**Comment by miigotu** [comment]
![image](https://user-images.githubusercontent.com/390379/79868112-6ed11b00-83ad-11ea-883a-da521d9bfd6c.png)
![image](https://user-images.githubusercontent.com/390379/79868224-9aec9c00-83ad-11ea-8688-4eecc097a533.png)

**Comment by zeveroare** [comment]
That is true, that's one step further. Here a screenshot with part of the list of the "add existing shows" and a screenshot of the show in the "shows" list.

![this is](https://user-images.githubusercontent.com/15368257/79869487-bbcee480-83e1-11ea-9f77-d729688957f2.png)
![show list](https://user-images.githubusercontent.com/15368257/79869490-bd001180-83e1-11ea-8c99-d05f90fd1adb.png)

**Comment by miigotu** [comment]
And I bet if you click into those shows, the location is red at the top because it isnt set right.

**Comment by zeveroare** [comment]
No, but I agree I was stupid and I could have looked better.
I'm sorry.
There are two ways to get to the qnap repository, with the "cachedev" and without. I should have used the "without" for this installation.

Mea culpa. You can close this :/

**Comment by miigotu** [comment]
No worries
