### ISSUE TITLE
ReadyNAS Update Hack in #6230 forgets SSL certificates and does not restore SickChill-master/.[a-z]*

### ISSUE THREAD

**Issue by jamver** [SickChill/SickChill#6255]
Per the title, the hack in #6230 to fix Netgear ReadyNAS installations does not backup and restore any locally generated SSL certificates and does not restore the dot-files from `SickChill-master/`

```
-rw-rw-r--+ 1 root root 2.6K Apr 22 11:17 .appveyor.yml
-rw-rw-r--+ 1 root root   38 Apr 22 11:17 .bowerrc
-rw-rw-r--+ 1 root root   25 Apr 22 11:17 .checkignore
-rw-rw-r--+ 1 root root 4.1K Apr 22 11:17 .codecov.yml
-rw-rw-r--+ 1 root root   13 Apr 22 11:17 .dockerignore
-rw-rw-r--+ 1 root root  490 Apr 22 11:17 .editorconfig
-rw-rw-r--+ 1 root root 1.6K Apr 22 11:17 .gitattributes
drwxrwxrwx+ 1 root root  210 Apr 22 11:17 .github
-rw-rw-r--+ 1 root root 1.1K Apr 22 11:17 .gitignore
-rw-rw-r--+ 1 root root  203 Apr 22 11:17 .lgtm.yml
-rw-rw-r--+ 1 root root  441 Apr 22 11:17 .snyk
-rw-rw-r--+ 1 root root 1.6K Apr 22 11:17 .travis.yml
```

**Comment by miigotu** [comment]
Those dotfiles are not used for SC to run, they are for testing and development only
I will update it to include cert/key

Please use the discussion issue, don't open extra issues for related issues.

**Comment by jamver** [comment]
Apologies for opening a new issue — comments were closed on the pinned issue with the recommended fix.

**Comment by miigotu** [comment]
Should be updated well enough. I rewrote the instructions to include the cache also.

**Comment by jamver** [comment]
Also, given `/` is only 4GB on a ReadyNAS, you probably want to use '/apps' or '/data' for temporary storage during the data migration and recovery (due to likely cache and log sizes).

**Comment by miigotu** [comment]
@jamver It is like 100MB total

**Comment by jamver** [comment]
FYI, my `app-config/` totalled `~1.1GB`, including:
```
452M    backup
231M    cache
228M    gui
115M    Logs
```
