### ISSUE TITLE
error in piratebay search provider

### ISSUE THREAD

**Issue by vicks619** [SickChill/SickChill#6256]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 8b28909
OS: Ready NA
Browser:chrome
What you did: added show ghostwriter (2019)
What happened: gave error while searching piratebay for episodes
What you expected: search without error
Logs:
`2020-04-22 11:15:45 SEARCHQUEUE-BACKLOG-369490 :: [ThePirateBay] :: [8b28909] Exception while searching ThePirateBay. Error: TypeError("'int' object is not iterable",)`

Also the 8th episode with air date 1st may 2020 is showing status as snatched

**Comment by miigotu** [comment]
#2614

**Comment by vicks619** [comment]
@miigotu i understand this is duplicate but what about the fix or is it just intermittent thing. also the it is showing snatched for un-aired episodes when it snatched the season 1 but episode 8 is not a part of it.
here is the screenshot
https://i.imgur.com/TXERO1Z.png
