### ISSUE TITLE
YGGTorrent provider is not available anymore

### ISSUE THREAD

**Issue by dokho1984** [SickChill/SickChill#6257]
Hi,

Since I upgraded to the latest version YGGTorrent provider is not available anymore.

Thanks in advance for your help.

Julien

__________________________________________________

SickChill Info:
Branch: master
Commit: db5bd92e4ff65108c395dcf87d0ed9195b6fde73
Version: v2020.04.22-1
Database Version: 44.1
  Version de Python:2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
  Version SSL:OpenSSL 1.1.1d 10 Sep 2019
  OS:Linux-4.19.0-8-amd64-x86_64-with-debian-10.3
  Local:en_US.UTF-8

**Comment by miigotu** [comment]
Because we cannot get past cloudflare on it yet, it will be reenabled when it isnt broken anymore.
