### ISSUE TITLE
ALL seasons selected (hidden seasons) when filtering episodes

### ISSUE THREAD

**Issue by optio50** [SickChill/SickChill#6259]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master 3a1f59212c9d43fc37f39c886f6fe70e417236b7 
OS: Ubuntu 19
Browser: Firefox
What you did: Selected filtered episodes
What happened: ALL seasons selected
What you expected: Only filtered episodes selected, I cant see the selected episodes because they are hidden.
Logs:
```
PASTE LOGS HERE
```
BTW not a fan of the hiding of seasons unless its selectable per show. Its VERY annoying with shows that have many seasons and I want to look at all the episodes. Please make it selectable.

**Comment by miigotu** [comment]
Not everyone can be a fan of everything. There are hundred of other people not a fan of their show page taking over a minute to load on large shows.

**Comment by optio50** [comment]
indeed I sympathize with that. Can we have it be selectable on a per episode basis?

**Comment by miigotu** [comment]
Negative, because that requires a database upgrade.
