### ISSUE TITLE
Unaired episode showing as snatched

### ISSUE THREAD

**Issue by vicks619** [SickChill/SickChill#6261]
showing snatched for un-aired episodes when it snatched the season 1 but episode 8 is not a part of it as it isnlbunaired. It should be disabled as it is upcoming
here is the screenshot
https://i.imgur.com/TXERO1Z.png

_Originally posted by @vicks619 in https://github.com/SickChill/SickChill/issues/6256#issuecomment-617594855_

**Comment by miigotu** [comment]
Set it to wanted and do a show update.
