### ISSUE TITLE
[APP SUBMITTED]: /media/sdao/josh-gaby/.local/lib/python2.7/site-packages/lxml/etree.so: undefined symbol: PyUnicodeUCS4_DecodeLatin1

### ISSUE THREAD

**Issue by joshgaby** [SickChill/SickChill#6264]
### INFO
Python Version: **2.7.17 (default, Apr 20 2020, 01:55:07) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.19.0-0.bpo.5-amd64-x86_64-with-debian-9.11**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@0018d0847e9e2371501e63727b756218096d665b
Link to Log: https://gist.github.com/5fabe06f3db1c0db185507051a13dc0f
### ERROR
```
MAIN :: [0018d08] There was an error creating the show in /media/sdao/josh-gaby/.sickrage.tv.shows/How to Get Away with Murder: Error /media/sdao/josh-gaby/.local/lib/python2.7/site-packages/lxml/etree.so: undefined symbol: PyUnicodeUCS4_DecodeLatin1
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by joshgaby** [comment]
### INFO
Python Version: **2.7.17 (default, Apr 20 2020, 01:55:07) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.19.0-0.bpo.5-amd64-x86_64-with-debian-9.11**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@0018d0847e9e2371501e63727b756218096d665b
Link to Log: https://gist.github.com/83be7e677b167c9da125c48fd33e2ce2
### ERROR
```
MAIN :: [0018d08] There was an error creating the show in /media/sdao/josh-gaby/.sickrage.tv.shows/Vampirina: Error /media/sdao/josh-gaby/.local/lib/python2.7/site-packages/lxml/etree.so: undefined symbol: PyUnicodeUCS4_DecodeLatin1
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
#6320
