### ISSUE TITLE
When adding existing show, target folder is displayed incorrectly

### ISSUE THREAD

**Issue by benyjr** [SickChill/SickChill#6265]
Branch: master
Commit: 8b28909b502f3d8e75d8808ff8d17420c039aa75
Version: v2020.04.21-4
Database Version: 44.1

OS: Windows, Android, Ubuntu 18.04
Browser: Chrome

What you did: Added an existing show, selected the show title from the search list

What happened: The target folder is displayed incorrectly: ie. changes from /path/to/showtitle to /path/to/showtitleshowtitle (see attached images)

What you expected: Target folder should not change.  

It appears that this bug is purely aesthetic, as editing the show after the fact displays the /path/to/showtitle. Also, when shows are added to the target folder, showtitleshowtitle folder is not created.  This would just create confusion, but still functions as intended.

![Before-SickChill - New Show](https://user-images.githubusercontent.com/14084052/79989061-69430600-847d-11ea-9a0a-a5d59d96f868.png)
![After-SickChill - New Show](https://user-images.githubusercontent.com/14084052/79989571-043be000-847e-11ea-9b6c-fee9b309ebec.png)

**Comment by miigotu** [comment]
I cannot reproduce this
![image](https://user-images.githubusercontent.com/390379/80033853-6a932380-84bb-11ea-8595-82ec89febdac.png)

**Comment by miigotu** [comment]
Aha, its when you click the button on `#2 Pick a Show` that i changes it

**Comment by benyjr** [comment]
Glad you were able to reproduce it after all!
