### ISSUE TITLE
Only download new episodes

### ISSUE THREAD

**Issue by theskillwithin** [SickChill/SickChill#6294]
for an existing show in your library how do you tell it to only download new episodes?  It seems like even things with a status of skipped are downloading and I thought skipped meant it won't search & download.

Sorry this is a question not a bug

**Comment by didyouexpectthat** [comment]
I haven't had this happen before myself. I use Ombi which sometimes adds shows to SickChill with "SKIPPED" on all historical episodes and only grabs new episodes, even though my default setting is set to "WANTED". Those episodes _never_ downloaded... 
You should provide some logs where it shows this happening.

**Comment by miigotu** [comment]
Im guessing you have season pack download enabled.

If you have set the provider to allow downloading season packs, and a couple of episodes in a season are wanted it will download a season pack.
When the season pack is processed, it will mark even skipped episodes as downloaded, even though SC did not go out and specifically DL this file on purpose.

If you don't want to allow it to keep the file that it downloaded anyways, set the episodes to ignored, or you could set the provider to episode only downloading.
