### ISSUE TITLE
version checking is disabled 

### ISSUE THREAD

**Issue by vicks619** [SickChill/SickChill#6298]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: ReadyNAS
Browser: chrome
What you did: check for updated 
What happened: version checking is disabled 
What you expected: check for update successful
Logs:
```
2020-04-23 11:59:55 INFO     WEBSERVER-HOME :: Version checking is disabled, not checking for the newest version

**Comment by didyouexpectthat** [comment]
What does your /config/general/ show for Updates?
![image](https://user-images.githubusercontent.com/1329077/80067022-ef992f80-84f1-11ea-97ab-1a64156608a6.png)

**Comment by vicks619** [comment]
@didyouexpectthat everything is same except auto update is unchecked. Restart seems to correct the issue. closing it
