### ISSUE TITLE
Manual post processing fails after fresh adding of new show (Requires Restart)

### ISSUE THREAD

**Issue by optio50** [SickChill/SickChill#6301]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master  757fa1f130e39bef50b35941364d64ac10bfe3f3
OS: Ubuntu
Browser: Firefox
What you did: Add new show. 15 min later init manual  post process
What happened: Failed to add episodes
What you expected: Episodes added
Logs: Below is the reoccurring for all episodes. Some named slightly different (but still acceptable) and None were detected or added. After restarting sickchill and attempting another manual post process it works fine. This is repeatable several times with new shows.
```
2020-04-22 23:08:47 INFO     POSTPROCESSOR-MANUAL :: /media/POOL/Temp/Complete/TV/qw/Boston Legal - 201 - The Black Widow.avi : Processing failed:
2020-04-22 23:08:03 INFO     POSTPROCESSOR-MANUAL :: Processing /media/POOL/Temp/Complete/TV/qw/Boston Legal - 201 - The Black Widow.avi (None)

```

**Comment by miigotu** [comment]
You will need to use the latest version and provide a debug log.
