### ISSUE TITLE
Round 2, Electric Boogaloo: Clicking on specific show in Show List produces Mako error

### ISSUE THREAD

**Issue by smbrannon** [SickChill/SickChill#6304]
**This on the same show as submitted in #6262** 

Branch/Commit:

Branch: master
Commit: 0306ded8f236585531276bc4cc1db9303f26bfce
Version: v2020.04.23-6
Database Version: 44.1

OS:    **Windows-10-10.0.18362
More commonly referred to as: Win 10 v1909 32-bit**

Python Version:  **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)**

Browser: **Chrome 81.0.4044.92**

What you did: Clicked on show "The Late Show with Stephen Colbert" in the Show List. I didn't click on all 57 shows I have, but I clicked on 10 random ones and they work as expected.

What happened: Browser threw a 500 error? Tab changed to "SickChill - 500". Then "Mako Error" was displayed, along with the following text:

"A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes."

Clicking on the "Show/Hide Error" button resulted in the following text:

```
File W:/SickChill/gui/slick/views/displayShow.mako:469, in render_content:
${(

TypeError: tuple indices must be integers, not NoneType
```

There is a strange icon before the ${(, so I've included a screen capture of the error.

What you expected: I expected SickChill to display the info about the show I clicked on.

Logs:

I've included a log file snippet. My clicking on the show and producing the Mako error occured around 2020-04-23 05:20:00, but I don't think it matters because this is a Mako file, and as I said in my last submission #6262, I don't know where Mako stores its logs.

Attached.

[sickchill.log](https://github.com/SickChill/SickChill/files/4522437/sickchill.log)
![SickChill - Mako Error2](https://user-images.githubusercontent.com/6511963/80099207-f42a0c00-8522-11ea-82dd-839fa5bc5aab.png)

**Comment by miigotu** [comment]
Next time, just re-use the existing issue you created. It makes it easier to maintain context and it keeps my issue tracker not being cluttered.

Your log does not contain the error, I need that please.

**Comment by smbrannon** [comment]
Sorry, I waffled on creating a new issue or not, and erred.

As before, there isn't an error thrown that I could see in the sickchill.log. The only error info I could find is in the code block in the submission body. I wasn't able to find where Mako stores its logs.

**Comment by miigotu** [comment]
Yes, only the sickchill.log. We use tornado server with mako template engine ^

Anyway, that should be fixed now. Comment in this issue if it is not once you update.

**Comment by smbrannon** [comment]
Branch: master
Commit: a2dc606824280455182dd7806fe070be7cfe0930
Version: v2020.04.24-3
Database Version: 44.1

I'm beginning to think either SickChill or Mako hates Stephen Colbert.   :-)

Error on displaying same show, The Late Show with Stephen Colbert (289574), by clicking on tile in home screen/Show List around 2020-04-24 19:35:00. Get a Mako Error, but nothing appears in sickchill.log.

```
Mako Error

A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

File W:/SickChill/gui/slick/views/displayShow.mako:527, in render_content:
<% airDate = datetime.datetime.fromordinal(epResult[b'airdate']) %>

ValueError: ordinal must be >= 1

```

I don't understand why this is happening to only this show. What is specific to this show that is throwing successive Mako errors? Anything else I can give you to help?

sickchill.log attached.


[sickchill.200424-0.log](https://github.com/SickChill/SickChill/files/4532239/sickchill.200424-0.log)

**Comment by miigotu** [comment]
Looks more like that show needs a full update from tvdb

**Comment by miigotu** [comment]
I'll make a change for it though 😉

**Comment by smbrannon** [comment]
Thanks for the quick answer. Yeah, I didn't go to TVDB. I was relying on SickChill to see if there were new shows, but I couldn't get that far as I kept getting errors.  :-) But, there is a upside to all this. I guess I helped improve SickChill's error handling. Which, as far as I am concerned, is one of the most important parts of code.    ;-)))  It also forced me to understand a little better how SickChill is put together. Thank you for SickChill and all the work you put into it!

**Comment by smbrannon** [comment]
Branch: master
Commit: fff4560fbd4bee1a7192670b36addbbbf6f38620
Version: v2020.04.25-5
Database Version: 44.1


**OK. It's official. SickChill does indeed hate Stephen Colbert, or myself.** 

Proof that SickChill hates either Stephen Colbert or myself:

Error on displaying same show, The Late Show with Stephen Colbert (289574), by clicking on tile in home screen/Show List around 2020-04-25 02:41:00. Get a Mako Error, but nothing appears in sickchill.log.

```
Mako Error

A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.


File W:/SickChill/gui/slick/views/displayShow.mako:568, in render_content:
<% curStatus, curQuality = Quality.splitCompositeStatus(int(epResult[b"status"])) %>

TypeError: int() argument must be a string or a number, not 'NoneType'
```

sickchill.log attached.




[sickchill.200425-0.log](https://github.com/SickChill/SickChill/files/4532736/sickchill.200425-0.log)

**Comment by miigotu** [comment]
Go to the mass update page, check update for that show, and click submit. That show is broken in your db

**Comment by miigotu** [comment]
This show works fine here:
![image](https://user-images.githubusercontent.com/390379/80277722-f923c280-86be-11ea-9f25-223c4889ad2b.png)

**Comment by smbrannon** [comment]
Branch: master
Commit: 42a2ae4d5c043b8a938fde1999bc4da30ff32d6a
Version: v2020.04.25-9
Database Version: 44.1

**All my issues seem to stem from a corrupt sickbeard.db. I was in the process of making this comment when I think I have discovered the root of the problem. Skip to the last three paragraphs to get the punchline.**

I performed an 'Update' with 'Mass Update' as you suggested. Nice that the feature is there, because I couldn't get into the show to modify it. :-)   Anyway, that failed with the following error:

```
Mako Error

A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.


File W:/SickChill/gui/slick/views/displayShow.mako:568, in render_content:
<% curStatus, curQuality = Quality.splitCompositeStatus(int(epResult[b"status"])) %>

TypeError: int() argument must be a string or a number, not 'NoneType'

```

So, I 'Removed' the show via the 'Mass Update' screen. I then used the 'Add Existing Show' to add the show, and pointed to the root of the directory where my shows get stored. I then waited for the show's data to update. When it had finished updating, I got a partial display of the shows I had in the only directory I had, Season 5. It wasn't complete:

![Partial of Season 5](https://user-images.githubusercontent.com/6511963/80355509-0ced3700-882d-11ea-91c3-096f359d0a08.jpg)

It jumps from S05E34 to S05E100, when I have S05E01 to S05E108.

Out of curiosity, I clicked the "Preview Rename" on the show page, and I got a 500 error:

```
File W:/SickChill/gui/slick/views/testRename.mako:82, in render_content:
if not ep_obj._location:

AttributeError: 'NoneType' object has no attribute '_location'

```

I then proceeded to open a new browser tab and attempt to load SickChill's home page, and I got another 500 error a standard browser localhost is currently unable to handle the request HTTP ERROR 500. At the same point, the sickchill.log contains an error, I could see it scrolling in the terminal windows. Subsequent attempts to open the home page also failed with the same error. Upon examining the sickchill.log file, it appears that there is database corruption. The first instance of this is noted at 2020-04-26 23:28:21.

So, I think all of the problems I've been having are due to a corrupt database. What's interesting is that I haven't noticed any other shows having problems, and it's only Late Show with Stephen Colbert that is having a problem. When I performed the 'Remove' via the 'Mass Update' page, does SickChill prune the database at that point in time? I'm asking because I'm trying to figure out why after 'Removing' the show and re-adding it via 'Add Existing Show' it is still having problems. 

I've got backups from 0408, 0419, and 0422. I have the most faith in 0408, as there was an update on or around 0419 that caused me some grief and caused me to do a clean install and restore. Is it safe to restore from a 19 day-old backup, and what are the ramifications?

**Thank you very much for your help!**

**Comment by miigotu** [comment]
Yes stopping SC and moving the backed up sickbeard.db into position is fine. Keep the one you are replacing though just in case.

**Comment by smbrannon** [comment]
Branch: master
Commit: 42a2ae4d5c043b8a938fde1999bc4da30ff32d6a
Version: v2020.04.25-9
Database Version: 44.1


Restored sickbeard.db from 0408 and still get Mako error, so the database must have become corrupt before then. So, I then restored with the next most recent backup I had, from 0113 and clicked on Late Show with Stephen Colbert, and it showed the expected page with info up to 0113. If I go to 'Mass Update' and select all shows and the 'Update' selection, will this perform a 'Full Update' and bring all my shows up to date, including already downloaded shows, etc.?



```
File W:/SickChill/gui/slick/views/displayShow.mako:568, in render_content:
<% curStatus, curQuality = Quality.splitCompositeStatus(int(epResult[b"status"])) %>

TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by miigotu** [comment]
I personally would edit the db manually, but that is beyond scope for most people's skill level.

**Comment by smbrannon** [comment]
Manually edit the damaged/corrupt db manually? I did database programming for about 2 years 34 years ago. I guess I could look into that if it's the shortest route to getting my SC back up.

**Comment by miigotu** [comment]
You might be able to accomplish it with mass update-> check remove for that show, click submit. Then try re-adding it?

**Comment by smbrannon** [comment]
I already tried that. In my post from 2020-04-27 03:23 PDT I discuss it starting from "So, I 'Removed' the show ." It didn't go well. When I added the show back I was back to where I started from with Mako errors.

I've been browsing sickbeard.db files from a few backups I have, starting with 0422 when this started, and back to the earliest I have which is 0113 (Before that I was using the last version of the old SickRage, before Echel0n fucked us all over, on the principal "If it ain't broke, don't fix it." Then it broke around the beginning of December 2019.). Not that I know the structure of sickbeard.db, but I thought I might be able to spot garbage as it only contains 11 tables. Here's something interesting I found. In the tv_episodes table, starting with record 11190 (episode_id 16823) there five records with non-sequitur data. Meaning not garbage, but data in the wrong place. Looks like something happened around 2020-01-23.  



![tv_episodes error](https://user-images.githubusercontent.com/6511963/80563756-d46e6a00-89a0-11ea-9cf9-65af29999411.jpg)


I've included a backup of the sickbeard.db I made the day I opened #6262 in case you want to look at the database. Right now I'm working off of the most recent good database I have, from 2020-01-13, and using 'Mass Update' to 'Update' and 'Rescan' my shows in conjunction with 'Add Existing Shows' to try and get my stuff up to date. 

Thank you for your help with this.

[sickbeard.db-20200422184556.zip](https://github.com/SickChill/SickChill/files/4549938/sickbeard.db-20200422184556.zip)

**Comment by miigotu** [comment]
You can delete any record that has indexer != 1, or status is null to start off
You want to check the history, tv_episodes, and tv_shows tables

**Comment by miigotu** [comment]
BTW, does the dir `V:\Shows\Last Week Tonight` exist?

**Comment by smbrannon** [comment]
> You can delete any record that has indexer != 1, or status is null to start off
> You want to check the history, tv_episodes, and tv_shows tables

Thank you for the pointer. I started with tv_shows and then went to tv_episodes.

> BTW, does the dir `V:\Shows\Last Week Tonight` exist?

Yes. Why do you ask?

**Comment by miigotu** [comment]
Ahaha yes I conflated the two shows. I will look again xD

**Comment by miigotu** [comment]
This is a very strange thing. I think the db file is corrupted beyond normal repair methods.
```sql
SELECT * FROM tv_episodes WHERE status ISNULL;
```
returns 0 rows

One of the records the show fails on is:
```sql
SELECT * FROM tv_episodes WHERE episode = "W:\Completed\NCIS.S17E13.iNTERNAL.1080p.WEB.x264-TRUMP[rarbg]\ncis.s17e13.internal.1080p.web.x264-trump.mkv"

episode_id | showid | indexerid | indexer | name | season | episode | description | airdate | hasnfo | hastbn | status | location | file_size | release_name | subtitles | subtitles_searchcount | subtitles_lastsearch | is_proper | scene_season | scene_episode | absolute_number | scene_absolute_number | version | release_group
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
16824 | 20200124000852 | 72108 | 17 | 13 | 64 | W:\Completed\NCIS.S17E13.iNTERNAL.1080p.WEB.x264-TRUMP[rarbg]\ncis.s17e13.internal.1080p.web.x264-trump.mkv | trump | -1 | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | NULL | -1 | NULL

														-1	
```

But select by that show id:
```sql
SELECT * FROM tv_episodes WHERE showid = 20200124000852
```
returns nothing

**Comment by miigotu** [comment]
```
integrity_check
--
*** in database main ***On tree page 8262 cell 49: Rowid 20225 out of orderOn tree page 7953 cell 4: 2nd reference to page 8286
row 11190 missing from index idx_tv_episodes_showid_airdate
row 11190 missing from index idx_status
row 11190 missing from index idx_sta_epi_sta_air
row 11190 missing from index idx_sta_epi_air
row 11190 missing from index idx_showid
row 11191 missing from index idx_tv_episodes_showid_airdate
row 11191 missing from index idx_status
row 11191 missing from index idx_sta_epi_sta_air
row 11191 missing from index idx_sta_epi_air
row 11191 missing from index idx_showid
row 11192 missing from index idx_tv_episodes_showid_airdate
row 11192 missing from index idx_status
row 11192 missing from index idx_sta_epi_sta_air
row 11192 missing from index idx_sta_epi_air
row 11192 missing from index idx_showid
row 11193 missing from index idx_tv_episodes_showid_airdate
row 11193 missing from index idx_status
row 11193 missing from index idx_sta_epi_sta_air
row 11193 missing from index idx_sta_epi_air
row 11193 missing from index idx_showid
row 11194 missing from index idx_tv_episodes_showid_airdate
row 11194 missing from index idx_status
row 11194 missing from index idx_sta_epi_sta_air
row 11194 missing from index idx_sta_epi_air
row 11194 missing from index idx_showid
wrong # of entries in index idx_tv_episodes_showid_airdate
wrong # of entries in index idx_status
wrong # of entries in index idx_sta_epi_sta_air
wrong # of entries in index idx_sta_epi_air
wrong # of entries in index idx_showid

```

**Comment by miigotu** [comment]
I ran this
```bash
sqlite3 broken.sickbeard.db ".recover" | sqlite3 sickbeard.db
```
Some info was removed, but it seems to boot up and the show loads now. I do not know how much info was lost.
[sickbeard.db.zip](https://github.com/SickChill/SickChill/files/4550674/sickbeard.db.zip)

**Comment by smbrannon** [comment]
Dude!! That was way more than I imagined you'd do! It looks like you spent 30 minutes on this.    :scream:   I just thought you might be interested in the how the database was corrupted, in that the reason might have been programmatic, rather than due to diskissue/cosmic ray strike. :smiley: 


I really, really appreciate the ton of time you spent on this. 

BTW, not looking for thanks, but I'll tell you, early on this interaction with you made me want to donate on a monthly basis. You're a really nice guy.    :hug:

Keep yourself safe.   :mask:
