### ISSUE TITLE
Yggtorrent broken?

### ISSUE THREAD

**Issue by fly320** [SickChill/SickChill#6308]
Hi everyone,

Yggtorrent is not available anymore. Do you have the same issue?

Thanks

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
It's broken, so it is disabled and hidden
