### ISSUE TITLE
Hidden Season Episodes

### ISSUE THREAD

**Issue by Keith-H99** [SickChill/SickChill#6309]
Just a quick question, my sickchill now opens with just the 3 most recent seasons of each show visible, the older seasons are hidden and I have to click "Show Episodes" to view them, is there a setting I can change to make them all visible as default?

**Comment by miigotu** [comment]
No.

**Comment by miigotu** [comment]
Maybe you just need to see the seasons that have snatched or wanted episodes in them to also be expanded?

**Comment by Keith-H99** [comment]
The shows have downloaded and are in the correct structure within the correct show but if there are 9 seasons then seasons 1 to 6 just show the season header and to see the episodes I have to expand each one individually but it used to have them all expanded as default, I have looked through settings and in the config.ini but can’t find a way to change it

**Comment by miigotu** [comment]
There is no way to change it. People were having more than 1 minute to display a show for the page to load.
