### ISSUE TITLE
rTorrent connection stopped working after latest updates : Error: Unable to connect to rTorrent

### ISSUE THREAD

**Issue by wokka1** [SickChill/SickChill#6313]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Linux
Browser: Chrome / Firefox
What you did: updated to latest sickchill
What happened: rtorrent stopped working / test connection fails
What you expected: send torrents over to rtorrent
Logs:
```
https://gist.github.com/wokka1/ab56dbef80ef6f417f57df578bedf4e8
```
I had responded to https://github.com/SickChill/SickChill/issues/6217 and a couple of people tried to help, but even after todays update, I'm still getting failures, so wanted to start it's own issue related to rTorrent.

I had the same issue that others did related to that thread, but clearing out the directories and pyc files allowed me to get sickchill to launch and web page works, it can find things via tvdb as expected, but when it finds a torrent, it doesn't send the file over to rtorrent to start the download.  I made no config changes and this setup has been working for months.

Enabling debug logs, going in and testing the connection gave nothing indicative in the logs, just get the same Error: Unable to connect to rTorrent

What I'm using for the connection is : scgi:///home/wokka/.config/rtorrent/socket which is a valid file, and again, this config has been working for months.

Thanks for your help, please let me know if you need further info

**Comment by miigotu** [comment]
Are you using rtorrent or rtorrent9 in SC settings?

**Comment by miigotu** [comment]
I just went through setting this up and matching your use case (using a socket) and it works

![image](https://user-images.githubusercontent.com/390379/80172494-21c29400-85bb-11ea-899a-20929f58bd3f.png)
Notice I have selected rtorrentv9+, not rtorrent as the client:
![image](https://user-images.githubusercontent.com/390379/80172512-3010b000-85bb-11ea-91d1-de4f69f15b21.png)

**Comment by wokka1** [comment]
Thanks, changing to rTorrent v9 resolved the issue.
