### ISSUE TITLE
[APP SUBMITTED]: WEBSERVER-HOME :: Missing time zone for network:  Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by itsme9x** [SickChill/SickChill#6319]
### INFO
Python Version: **2.7.14 (default, Dec 20 2018, 09:19:48) [GCC 4.9.4 20150629 (prerelease)]**
Operating System: **Linux-4.4.59+-aarch64-with-glibc2.17**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@a2dc606824280455182dd7806fe070be7cfe0930
Link to Log: https://gist.github.com/5995fc6f83293984bc7b3abfa5a17fff
### ERROR
```
WEBSERVER-HOME :: Missing time zone for network:  Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Not sure what show that is, but it seems to have been changed on tvdb (I just updated the network lists and it did not add this network)

**Comment by itsme9x** [comment]
For example Dream School is from this network 

https://thetvdb.com/series/dreamschool-nl

The network is called NPO 1, but the full name is Nederlandse Publieke Omroep 1

https://thetvdb.com/networks/NPO1

**Comment by itsme9x** [comment]
> Not sure what show that is, but it seems to have been changed on tvdb (I just updated the network lists and it did not add this network)

For example Dream School is from this network

https://thetvdb.com/series/dreamschool-nl

The network is called NPO 1, but the full name is Nederlandse Publieke Omroep 1

https://thetvdb.com/networks/NPO1

**Comment by miigotu** [comment]
It isnt coming back with data from their api yet. Maybe in a few days it will

**Comment by glancy** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@0306ded8f236585531276bc4cc1db9303f26bfce
Link to Log: https://gist.github.com/eba305975046142f1ecc521b0b4e75a1
### ERROR
```
WEBSERVER-HOME :: Missing time zone for network:  Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by glancy** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@0306ded8f236585531276bc4cc1db9303f26bfce
Link to Log: https://gist.github.com/c0ee20703607f1d9345751d3b74595d1
### ERROR
```
WEBSERVER-HOME :: Missing time zone for network:  Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 20 2018, 09:19:48) [GCC 4.9.4 20150629 (prerelease)]**
Operating System: **Linux-4.4.59+-aarch64-with-glibc2.17**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/2251639a01d648b9b9d24e45f2c6cab5
### ERROR
```
WEBSERVER-HOME :: Missing time zone for network:  Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 20 2018, 09:19:48) [GCC 4.9.4 20150629 (prerelease)]**
Operating System: **Linux-4.4.59+-aarch64-with-glibc2.17**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@ebcb4d616200cde7fba8e5b5f4601ecbcd402c1d
Link to Log: https://gist.github.com/24e7241996269294e0c8041c45a8a40f
### ERROR
```
WEBSERVER-HOME :: Missing time zone for network:  Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **2.7.14 (default, Dec 20 2018, 09:19:48) [GCC 4.9.4 20150629 (prerelease)]**
Operating System: **Linux-4.4.59+-aarch64-with-glibc2.17**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
Link to Log: https://gist.github.com/9578c06bcfe859caa70e678b5b5cf6cf
### ERROR
```
WEBSERVER-HOME :: Missing time zone for network:  Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
