### ISSUE TITLE
Unable to Update 

### ISSUE THREAD

**Issue by overloadsix** [SickChill/SickChill#6320]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Origin Master
OS: Linux 18.04
Browser: Brave
What you did: Green bar at top of SickChill alerted me I was 11 commits behind, clicked on the update now link
What happened: Update failed. Update wasn't successful, not restarting. Check your log for more information.

What you expected: to be 11 commits current. 
Logs:
```
2020-04-24 17:48:08 WEBSERVER-HOME :: [96cd069] git pull -f origin master returned : From https://github.com/SickChill/SickChill
* branch master -> FETCH_HEAD
error: The following untracked working tree files would be overwritten by merge:
lib/IMDbPY-6.9.dev20200423.dist-info/DESCRIPTION.rst
lib/IMDbPY-6.9.dev20200423.dist-info/INSTALLER
lib/IMDbPY-6.9.dev20200423.dist-info/METADATA
lib/IMDbPY-6.9.dev20200423.dist-info/RECORD
lib/IMDbPY-6.9.dev20200423.dist-info/WHEEL
lib/IMDbPY-6.9.dev20200423.dist-info/entry_points.txt
lib/IMDbPY-6.9.dev20200423.dist-info/metadata.json
lib/IMDbPY-6.9.dev20200423.dist-info/top_level.txt
lib/cloudscraper/help.py
lib/cloudscraper-1.2.34.dist-info/INSTALLER
lib/cloudscraper-1.2.34.dist-info/LICENSE
lib/cloudscraper-1.2.34.dist-info/METADATA
lib/cloudscraper-1.2.34.dist-info/RECORD
lib/cloudscraper-1.2.34.dist-info/WHEEL
lib/cloudscraper-1.2.34.dist-info/top_level.txt
lib/cryptography-2.9.2.dist-info/AUTHORS.rst
lib/cryptography-2.9.2.dist-info/INSTALLER
lib/cryptography-2.9.2.dist-info/LICENSE
lib/cryptography-2.9.2.dist-info/LICENSE.APACHE
lib/cryptography-2.9.2.dist-info/LICENSE.BSD
lib/cryptography-2.9.2.dist-info/LICENSE.PSF
lib/cryptography-2.9.2.dist-info/METADATA
lib/cryptography-2.9.2.dist-info/RECORD
lib/cryptography-2.9.2.dist-info/WHEEL
lib/cryptography-2.9.2.dist-info/top_level.txt
lib/httplib2-0.17.3.dist-info/DESCRIPTION.rst
lib/httplib2-0.17.3.dist-info/INSTALLER
lib/httplib2-0.17.3.dist-info/METADATA
lib/httplib2-0.17.3.dist-info/RECORD
lib/httplib2-0.17.3.dist-info/WHEEL
lib/httplib2-0.17.3.dist-info/metadata.json
lib/httplib2-0.17.3.dist-info/top_level.txt
Please move or remove them before you merge.
Aborting
Updating 96cd06961..a2dc60682
```

**Comment by miigotu** [comment]
Not sure how you got untracked files, but following #6230 again will fix that.

**Comment by overloadsix** [comment]
I did, and I got an error:

lib/IMDbPY-6.9.dev20200423.dist-info/DESCRIPTION.rst
lib/IMDbPY-6.9.dev20200423.dist-info/INSTALLER
lib/IMDbPY-6.9.dev20200423.dist-info/METADATA
lib/IMDbPY-6.9.dev20200423.dist-info/RECORD
lib/IMDbPY-6.9.dev20200423.dist-info/WHEEL
lib/IMDbPY-6.9.dev20200423.dist-info/entry_points.txt
lib/IMDbPY-6.9.dev20200423.dist-info/metadata.json
lib/IMDbPY-6.9.dev20200423.dist-info/top_level.txt
lib/cloudscraper/help.py
lib/cloudscraper-1.2.34.dist-info/INSTALLER
lib/cloudscraper-1.2.34.dist-info/LICENSE
lib/cloudscraper-1.2.34.dist-info/METADATA
lib/cloudscraper-1.2.34.dist-info/RECORD
lib/cloudscraper-1.2.34.dist-info/WHEEL
lib/cloudscraper-1.2.34.dist-info/top_level.txt
lib/cryptography-2.9.2.dist-info/AUTHORS.rst
lib/cryptography-2.9.2.dist-info/INSTALLER
lib/cryptography-2.9.2.dist-info/LICENSE
lib/cryptography-2.9.2.dist-info/LICENSE.APACHE
lib/cryptography-2.9.2.dist-info/LICENSE.BSD
lib/cryptography-2.9.2.dist-info/LICENSE.PSF
lib/cryptography-2.9.2.dist-info/METADATA
lib/cryptography-2.9.2.dist-info/RECORD
lib/cryptography-2.9.2.dist-info/WHEEL
lib/cryptography-2.9.2.dist-info/top_level.txt
lib/httplib2-0.17.3.dist-info/DESCRIPTION.rst
lib/httplib2-0.17.3.dist-info/INSTALLER
lib/httplib2-0.17.3.dist-info/METADATA
lib/httplib2-0.17.3.dist-info/RECORD
lib/httplib2-0.17.3.dist-info/WHEEL
lib/httplib2-0.17.3.dist-info/metadata.json
lib/httplib2-0.17.3.dist-info/top_level.txt
Please move or remove them before you merge.

-however I kinda messed up, and did not run git pull again, after the sudo git clean -dfq lib command, which showed that error message above.
But to top it off, I keep getting unit sickrage.service not found, which means I am missing my sickchill autostart systemd file

**Comment by miigotu** [comment]
`system to start sickchill`
Not
`systemctl start sickrage`

And if git clean isn't removing untracked files, do `git reset --hard`.

**Comment by overloadsix** [comment]
thanks!
