### ISSUE TITLE
Episode lists Hidden... Need to hit "Show Episodes" to view them now.

### ISSUE THREAD

**Issue by mikey0613** [SickChill/SickChill#6321]
This may be minor, but ever since the last update all my show seasons are collapsed..  I have to keep hitting "Show Episodes" which for a show like NCIS with 17 seasons can get tedious.. Plus when I do hit "Show Episodes" it doesn't save that for next time, and I have to hit it all over again.

Is this a "Feature" now, and can there be options to enable/disable it, or make it remember the setting?

~Michael McPeters.
(I didn't attach logs, as I don't believe they apply to this)

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master - v2020.04.24-3
OS: Win7 x64
Browser: Firefox

**Comment by miigotu** [comment]
Too many people were having shows take over a minute to load. It isn't configurable right now. But it isn't a bug.

**Comment by mikey0613** [comment]
Is there an eta on when this is configurable, or some way to override it?

**Comment by miigotu** [comment]
No
