### ISSUE TITLE
[APP SUBMITTED]: Set changed size during iteration

### ISSUE THREAD

**Issue by midnightx12** [SickChill/SickChill#6325]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@a2dc606824280455182dd7806fe070be7cfe0930
Link to Log: https://gist.github.com/0e80a61ea3754015798a6aa477eb877a
### ERROR
```
SEARCHQUEUE-BACKLOG-294417 :: [ThePirateBay] :: [a2dc606] Exception while searching ThePirateBay. Error: RuntimeError('Set changed size during iteration',)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Fixed
