### ISSUE TITLE
Unable to add a show

### ISSUE THREAD

**Issue by superboy1950** [SickChill/SickChill#6329]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master/ the latest (I've done a fresh update and updated but not sure how to find this)
OS: Win 10 64bit
Browser: Chrome
What you did: Tried to add the show 'Dragon Ball Super'. I've done this on two systems, two fresh installs and got the same result
What happened: got an error as shown
What you expected: The show to add as straight after I added the Witcher and it worked
Logs:
```
2020-04-25 09:03:13 INFO SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2020-04-25 09:03:13 INFO SHOWQUEUE-ADD :: 295068: Unable to find the show in the database
2020-04-25 09:03:13 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /media/sdai1/********/.sickrage.tv.shows/Dragon Ball Super
```

**Comment by 03397** [comment]
I have the exact same issue. I have tried  two different shows After Trek and Sons of Anarchy.
The first one is added correctly but the second one is not. Getting the following and the show is never added

2020-04-25 12:39:27 INFO SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2020-04-25 12:39:26 INFO SHOWQUEUE-ADD :: 82696: Unable to find the show in the database
2020-04-25 12:39:26 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /share/Multimedia/Video/Series/Sons of Anarchy

**Comment by miigotu** [comment]
`82696: Unable to find the show in the database` is not an error, it is just checking if the show is already added before it adds it. Notice it says `INFO` not `ERROR`
However, there was an issue for imdb info that is gathered right after that log line. It might help whatever problem you are having (not seeing one here)

```bash
06:40:21 INFO::SHOWQUEUE-ADD :: Starting to add show by ShowDir: /home/dusted/Projects/SCVideos/Fleabag
06:40:21 INFO::SHOWQUEUE-ADD :: 314614: Unable to find the show in the database
06:40:21 DEBUG::SHOWQUEUE-ADD :: 314614: Loading show info from theTVDB
06:40:21 DEBUG::SHOWQUEUE-ADD :: Setter sets location to /home/dusted/Projects/SCVideos/Fleabag
06:40:21 INFO::SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
06:40:21 DEBUG::SHOWQUEUE-ADD :: 314614: Loading show info from IMDb
06:40:26 DEBUG::SHOWQUEUE-ADD :: 314614: Obtained info from IMDb ->{u'rating': '8.7', u'votes': 69768, u'runtimes': 27, u'year': 2016, u'imdb_id': u'tt5687612', u'akas': u'\u0424\u043b\u0456\u0431\u0435\u0433 (Ukraine)|\u908b\u9062\u5973\u90ce (Taiwan, Province Of China)|Wsp\xf3\u0142czesna dziewczyna (Poland)|Potvora (Czech Republic)|\u0411\u0443\u0432\u0430\u0440\u0430 (Serbia)|\u0414\u0440\u044f\u043d\u044c (Russian Federation)|Lun Dun Sheng Huo (China)|Potvora (Slovakia)', u'indexer_id': 314614, u'genres': u'comedy|drama', u'countries': u'United Kingdom', u'title': u'Fleabag', u'last_update': 737540, u'country_codes': u'gb', u'certificates': u'TV-MA'}
06:40:26 DEBUG::SHOWQUEUE-ADD :: 314614: Saving to database: Fleabag
06:40:26 DEBUG::SHOWQUEUE-ADD :: 314614: Loading all episodes from theTVDB...
```

**Comment by 03397** [comment]
@miigotu 
I still cannot add Sons Of Anachy. I am @ Commit: b75f47bba3df545f117f28a76c7d923f947ab157
No error message
You can try it your self if you want

**Comment by miigotu** [comment]
There is an error in the log:
```
07:13:32 INFO::SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
07:13:32 DEBUG::SHOWQUEUE-ADD :: 82696: Loading show info from IMDb
Exception in thread SHOWQUEUE-ADD:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/dusted/Projects/SickChill/sickbeard/show_queue.py", line 469, in run
    self.show.loadIMDbInfo()
  File "/home/dusted/Projects/SickChill/sickbeard/tv.py", line 887, in loadIMDbInfo
    for alternate in title_versions['alternateTitles']
  File "/home/dusted/Projects/SickChill/sickbeard/tv.py", line 888, in <genexpr>
    if 'region' in alternate and 'title' in alternate and alternate['title'] != imdb_title.title)
KeyError: u'XWW'

```

**Comment by 03397** [comment]
What does this mean?

**Comment by superboy1950** [comment]
> `82696: Unable to find the show in the database` is not an error, it is just checking if the show is already added before it adds it. Notice it says `INFO` not `ERROR`
> However, there was an issue for imdb info that is gathered right after that log line. It might help whatever problem you are having (not seeing one here)
> 
> ```shell
> 06:40:21 INFO::SHOWQUEUE-ADD :: Starting to add show by ShowDir: /home/dusted/Projects/SCVideos/Fleabag
> 06:40:21 INFO::SHOWQUEUE-ADD :: 314614: Unable to find the show in the database
> 06:40:21 DEBUG::SHOWQUEUE-ADD :: 314614: Loading show info from theTVDB
> 06:40:21 DEBUG::SHOWQUEUE-ADD :: Setter sets location to /home/dusted/Projects/SCVideos/Fleabag
> 06:40:21 INFO::SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
> 06:40:21 DEBUG::SHOWQUEUE-ADD :: 314614: Loading show info from IMDb
> 06:40:26 DEBUG::SHOWQUEUE-ADD :: 314614: Obtained info from IMDb ->{u'rating': '8.7', u'votes': 69768, u'runtimes': 27, u'year': 2016, u'imdb_id': u'tt5687612', u'akas': u'\u0424\u043b\u0456\u0431\u0435\u0433 (Ukraine)|\u908b\u9062\u5973\u90ce (Taiwan, Province Of China)|Wsp\xf3\u0142czesna dziewczyna (Poland)|Potvora (Czech Republic)|\u0411\u0443\u0432\u0430\u0440\u0430 (Serbia)|\u0414\u0440\u044f\u043d\u044c (Russian Federation)|Lun Dun Sheng Huo (China)|Potvora (Slovakia)', u'indexer_id': 314614, u'genres': u'comedy|drama', u'countries': u'United Kingdom', u'title': u'Fleabag', u'last_update': 737540, u'country_codes': u'gb', u'certificates': u'TV-MA'}
> 06:40:26 DEBUG::SHOWQUEUE-ADD :: 314614: Saving to database: Fleabag
> 06:40:26 DEBUG::SHOWQUEUE-ADD :: 314614: Loading all episodes from theTVDB...
> ```

Thanks for the sarcasm and general being a d!ck, it really helped. The specific log entry may not be an error but when I am asking to add a show which has be added with no issues on previous installations and it doesn't that seems like an error or issue. 

Is there a resolution for this? Other than being sarcastic?

**Comment by miigotu** [comment]
@superboy1950 nobody was being sarcastic so you can go ahead and fuc right the hell off.

@03397 The problem with sons is fixed.

**Comment by 03397** [comment]
@miigotu 
Not it not fixed.
Show cannot be added yet.

**Comment by miigotu** [comment]
@03397 I added it here, did you pull the update again?

```bash
07:48:03 DEBUG::WEBSERVER-ADDSHOWS :: Searching for Show with searchterm(s): ['sons of anarchy'] on Indexer: theTVDB
07:48:10 INFO::SHOWQUEUE-ADD :: Starting to add show by ShowDir: /home/dusted/Projects/SCVideos/Sons of Anarchy
07:48:10 INFO::SHOWQUEUE-ADD :: 82696: Unable to find the show in the database
07:48:10 DEBUG::SHOWQUEUE-ADD :: 82696: Loading show info from theTVDB
07:48:11 DEBUG::SHOWQUEUE-ADD :: Setter sets location to /home/dusted/Projects/SCVideos/Sons of Anarchy
07:48:11 INFO::SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
07:48:11 DEBUG::SHOWQUEUE-ADD :: 82696: Loading show info from IMDb
07:48:17 DEBUG::SHOWQUEUE-ADD :: 82696: Obtained info from IMDb ->{u'rating': '8.6', u'votes': 242548, u'runtimes': 45, u'year': 2008, u'imdb_id': u'tt1124373', u'akas': u'Sinovi anarhije (Slovenia)|Sinovi anarhije (Croatia)|Synowie anarchii (Poland)|Hijos de la anarqu\xeda (Spain)|\u0421\u0438\u043d\u043e\u0432\u0435 \u043d\u0430 \u0430\u043d\u0430\u0440\u0445\u0438\u044f\u0442\u0430 (Bulgaria)|Sinovi anarhije (Serbia)|Fiii anarhiei (Romania)|Filhos da Anarquia (Brazil)|Sons of anarchy (Romania)|Anar\u015finin Evlatlar\u0131 (Turkey)|Sons (World Wide)|Forever Sam Crow (United States)|\u0421\u044b\u043d\u044b \u0430\u043d\u0430\u0440\u0445\u0438\u0438 (Russian Federation)|Giang H\u1ed3 \u0110\u1eabm M\xe1u (Viet Nam)|Los indomables (Mexico)|Anarchijos vaikai (Lithuania)|\u30b5\u30f3\u30fb\u30aa\u30d6\u30fb\u30a2\u30ca\u30fc\u30ad\u30fc (Japan)|Kem\xe9ny motorosok (Hungary)', u'indexer_id': 82696, u'genres': u'crime|drama|thriller', u'countries': u'United States', u'title': u'Sons of Anarchy', u'last_update': 737540, u'country_codes': u'us', u'certificates': u'TV-MA'}
07:48:17 DEBUG::SHOWQUEUE-ADD :: 82696: Saving to database: Sons of Anarchy
07:48:17 DEBUG::SHOWQUEUE-ADD :: 82696: Loading all episodes from theTVDB...
07:48:17 DEBUG::SHOWQUEUE-ADD :: 82696: Episode S01E01 not found in the database
07:48:17 DEBUG::SHOWQUEUE-ADD :: 82696: The absolute number for S01E01 is: 1 
07:48:17 DEBUG::SHOWQUEUE-ADD :: Looking up XEM scene mapping for show 82696 on theTVDB
07:48:17 DEBUG::SHOWQUEUE-ADD :: Episode has already aired, marking it Skipped
```

**Comment by 03397** [comment]
Yes I am at the latest 4cd83736f6c4fe9eba49cb4d2c7bbf6b6ff183a7

**Comment by 03397** [comment]
@miigotu 
Now it is ok. It took a whille to add.
Thanks.
