### ISSUE TITLE
Torrent file content is empty

### ISSUE THREAD

**Issue by roscopwnz** [SickChill/SickChill#6331]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 42a2ae4d5c043b8a938fde1999bc4da30ff32d6a
Version: v2020.04.25-9
Database Version: 44.4
OS: Windows 10
Browser: Chrome
What you did: Add new show , try to download new episode
What happened: error in log
What you expected: torrent to get downloaded, added to deluge and so on 
Additional comment : 
Been using sickchill for months, one update broke it, and I think I botched the fix
So this is a brand new fresh install and adding 1 show to test but same issue as before
Hopefully it's unrelated so and I can restore database instead of adding all shows again :D
Logs:
```
PASTE LOGS HERE
```
19:13:25 INFO::SEARCHQUEUE-BACKLOG- :: Beginning backlog search for: [Superstore]
19:13:38 INFO::SEARCHQUEUE-BACKLOG-295648 :: [IPTorrents] :: Performing episode search for Superstore
19:13:39 INFO::SEARCHQUEUE-BACKLOG-295648 :: [IPTorrents] :: Quality of Superstore.S05E21.iNTERNAL.720p.WEB.h264-TRUMP is 720p WEB-DL
19:13:39 INFO::SEARCHQUEUE-BACKLOG-295648 :: [IPTorrents] :: Quality of Superstore.S05E21.CALIFORNIA.PART.1.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb is 720p WEB-DL
19:13:39 INFO::SEARCHQUEUE-BACKLOG-295648 :: [IPTorrents] :: Preferring Superstore.S05E21.CALIFORNIA.PART.1.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb (normal instead of internal)
19:13:39 INFO::SEARCHQUEUE-BACKLOG-295648 :: [IPTorrents] :: Quality of Superstore.S05E21.720p.HDTV.x264-AVS is 720p HDTV
19:13:39 INFO::SEARCHQUEUE-BACKLOG-295648 :: [IPTorrents] :: Quality of Superstore.S05E21.720p.HEVC.x265-MeGusta is 720p HDTV
19:13:39 INFO::SEARCHQUEUE-BACKLOG- :: Downloading Superstore.S05E21.CALIFORNIA.PART.1.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb from IPTorrents
19:13:39 INFO::SEARCHQUEUE-BACKLOG- :: Request failed: 404 Client Error: Not Found for url: https://iptorrents.com/download.php/3866707/Superstore.S05E21.CALIFORNIA.PART.1.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb.torrent (<type 'str'>)
19:13:39 WARNING::SEARCHQUEUE-BACKLOG- :: Torrent file content is empty

**Comment by BenjV** [comment]
This has nothing to do with SickChill but is an IPtorrent issue.

In this case the IPtorrent announce it has this torrent but when SickSchill tries to download it IPtorrent answers with a 404 error, in other word it does not have the actual torrentfile.

**Comment by roscopwnz** [comment]
Hmm, very strange,

If I click on the link it does download the torrent though, and if I add it to deluge it does download it, so seems torrent is fine but maybe sickchill is having issues grabbing it, also there are many shows with this same issue, 

I'll accept it's not sickchills fault, and issue is coming from iptorrents side, but is there anything I can do, I will try using different urls available for iptorrents, and see if they work instead

**Comment by miigotu** [comment]
The torrent download site is protected by cloudflare, the new version which is not broke yet. You can try to add the cloudflare cookies in your settings, along with the uid and pass ones, but idk if it will work.

**Comment by miigotu** [comment]
Also, I get this when I click that link (404)
```
Not Found

Sorry pal :(

```
