### ISSUE TITLE
docker update fails and won't restart

### ISSUE THREAD

**Issue by phoniclynx** [SickChill/SickChill#6332]
### Before submitting your issue:

Branch/Commit: Branch: master Commit: 4cd83736f6c4fe9eba49cb4d2c7bbf6b6ff183a7
OS: Docker
Browser: Vivaldi
What you did: SC had an update and selected to update to the latest version as it was 33 commits behind
What happened: SC didn't start up again properly
What you expected: SC to start
Logs: Error logged over and over again:
```
Traceback (most recent call last):                                                           File "/app/sickchill/SickBeard.py", line 67, in <module>                                     import sickbeard                                                                         File "/app/sickchill/sickbeard/__init__.py", line 49, in <module>                            from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_proces
sing_queue, properFinder, providers,                                                         File "/app/sickchill/sickbeard/providers/__init__.py", line 29, in <module>                  from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishb
its, demonoid, elitetorrent, filelist,                                                       File "/app/sickchill/sickbeard/providers/abnormal.py", line 34, in <module>                  from sickchill.providers.torrent.TorrentProvider import TorrentProvider                File "/app/sickchill/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>  from feedparser import FeedParserDict                                                 ImportError: cannot import name FeedParserDict    
```

**Comment by dkgs** [comment]
Check https://github.com/SickChill/SickChill/issues/6230#issue-602814841

**Comment by phoniclynx** [comment]
I checked that.. but I couldn't get it to work.. the instructions for linux.. well. idk

**Comment by miigotu** [comment]
docker run --rm \ -v /var/run/docker.sock:/var/run/docker.sock \ containrrr/watchtower \ --run-once sickchill

**Comment by phoniclynx** [comment]
That didn't change anything for me.. This is running on a Synology NAS. When I run it I get the error ```
"docker: invalid reference format.
See 'docker run --help'.
```
I am also running linuxserver/sickchill:latest if that helps

**Comment by miigotu** [comment]
Then remake your container. That command is supposed to pull a new base image and remake your container with the variables you had when you made it.
