### ISSUE TITLE
TV Shows Hiding Seasons

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#6333]
A recent change to SickChill has greatly affected the ability to manage TV shows.
I appreciate that this is an intentional change to improve responsiveness however the knock on effect is that it makes it much harder to manage TV show episodes.

For example, where a show is changed it flags in the shows list as missing an episode and previously I would click on the shows from the shows list and see the missing episode straight away. Now if this were to happen with a show like Horizon I would have to click expand up to 55 times so this would multiply the amount of time it takes to get an overview of a show. If I then force an update of the show I would need to repeat that entire process.

Not only this but it also renders filters useless. If I were to filter a show by 'allowed' I only have visibility of the seasons that are expanded rather than the episodes I have elected to filter by. Users need to be able to see the episodes they have filtered by otherwise they may accidentally make the wrong selection.

I can see someone has requested an option to allow the default view of a show to expand all seasons and that was declined but I thought it would be useful to take on board the scale of the problem this change creates.

Branch: master
Commit: 757fa1f130e39bef50b35941364d64ac10bfe3f3
Version: v2020.04.22-4
Database Version: 44.1
OS: Windows
Browser: Firefox
What you did: Clicked on a show from the shows list
What happened: Only a portion of the seasons show are visible
What you expected: To see the episodes of the selected show

**Comment by ulrick65** [comment]
I am having similar issues.  Is there a way (or could one be added please) to turn this feature off?
