### ISSUE TITLE
[REQUEST FEATURE] Add series from favorites from TVDB

### ISSUE THREAD

**Issue by ciltocruz** [SickChill/SickChill#6334]
Hello!

I am trying SickChill and I found it interesting to ask for this.
I have +100 series added to favorites on tvdb. Transferring these favorites to SickChill would be a hard job.

Could you add the option to connect with API token to TVDB (of each user) and retrieve by API the favorites list to import it into SickChill?

Thank you!

**Comment by miigotu** [comment]
This is quite a bit of work honestly. I could make it so you can select the shows from a list and click to add them all using default settings pretty easily, or have to click through the settings for each show. I think both extremes are not what you are looking for.

While feature requests arent really being accepted without an associated path right now, I might consider it. Please elaborate on your idea.

**Comment by ciltocruz** [comment]
Good Morning.

I will try to explain myself well. The operation, without knowing the source code, should not be very difficult.

I imagine you know that TVDB has a fantastic data request API. I think they use it to get series information.

From the TVDB user area, you can create API KEYS associated with the user who is logged in.

![image](https://user-images.githubusercontent.com/19903919/80356327-9a567880-8879-11ea-90e9-012b0e2d8044.png)


What could be good is having, within the Sickchill options, a section to enter 3 data to login and be able to retrieve the tvdb token:

username
apikey
apisecret.

![image](https://user-images.githubusercontent.com/19903919/80356422-be19be80-8879-11ea-90f1-9470276e8912.png)


With these data entered (and not before) in the ADD SERIES section, a new section could appear that would be:
ADD FROM TVDB FAVORITES.
(sorry, mi UI is in SPANISH and this is make for me in HTML... :p )

![image](https://user-images.githubusercontent.com/19903919/80359707-83feeb80-887e-11ea-81a6-d7c763d19a10.png)


When clicked, a request is made via api from the favorites of the user who has entered their apikey / apisecret / username in the configuration section. The request, obviously, is made with the JWT token that is obtained with the 3 parameters saved in the configuration.

![image](https://user-images.githubusercontent.com/19903919/80356731-29fc2700-887a-11ea-81e7-60d1a2ad61a1.png)

Retrieving the favorites from TVDB gives the tvdb_id.

Then you would have to make a call to / series / {id} to obtain the information of the favorite series and, this I leave to your discretion,
a) add all series.
b) allow the user to choose the series he wants to add.

This last screen is very similar to that of adding SERIES FROM TRAK.TV LISTS.

![image](https://user-images.githubusercontent.com/19903919/80359980-f1128100-887e-11ea-8b07-243035684793.png)


What you think?

A greeting!

**Comment by miigotu** [comment]
I know how to get the favorites, and where to put the option, but it is once we have the list that is up for debate.

Do I just add the show with the default options? Add one at a time like imdbpopular? Add all with defaults?

**Comment by ciltocruz** [comment]
Ok. I understand you now. 
I would set the default options as the "checked" option. 

But if the user wants to choose the "tvshow by tvshow" options he chooses the option "one by one" and then it would happen in the same way as now with the option that "import tvshows from the hard drive".

We can keep debating if you don't see it right

A hug!

**Comment by ciltocruz** [comment]
This is maximum efficiency and the rest is nonsense.
👍 💯 

I've been testing the implementation and I think something is wrong. Or it could be my system.

I have entered the user and the APIKEY and I have given "Submit" but nothing happened there.

Also, I would like to help translate the new literals, at least in Spanish. Can I send the text strings here?

Thanks!

**Comment by ciltocruz** [comment]
Sorry. Let me ask...

"Basic implementation" does not make it clear to me that the implementation is finished. Maybe I went too fast in my previous comment.

Let me know if it is and if it is, I apologize!

**Comment by ciltocruz** [comment]
Hello again @miigotu.

Seeing that there were problems obtaining favorites I decided to download the code and stick with it until I found the error.

I had never worked with Python and debugging but I have managed to find it.

When you click "Add Series" and then "Add from TVDB Favorites", before the interface loads, an API call is made to generate a token. That call is made with this API_KEY

PHOTO 1.
![image](https://user-images.githubusercontent.com/19903919/80503604-63b05900-8972-11ea-962a-52d850ff5647.png)


A token is generated for that APIKEY which is the one used in all calls.
Then there is a getFavorites call from the user who has retrieved that token.

(The first time the page is loaded, the line is called in yellow. That line (only the first time) is the one that generates the api token.

![image](https://user-images.githubusercontent.com/19903919/80503430-2055ea80-8972-11ea-84e1-d16d1ab890b6.png)

And this is the result ALWAYS, it doesn't matter what data is stored in tvdb_user and tvdb_user_key.

When tvdb_user and tvdb_user_key are introduced I have seen that the function "test_user_key" is called. This, with the api token generated before, always returns the same user: P

Who is "alexpablo"? hahaha

![image](https://user-images.githubusercontent.com/19903919/80504437-6790ab00-8973-11ea-9bae-4d370846d3b1.png)


Therefore, I think that the best way to solve it is to leave that parameter, as up to now, in the code, but enter in the Configuration -> General -> Advanced a section where you can "overwrite" the API-KEY.

With this, I think that the form of tvdb_user and tvdb_user_key would no longer be necessary because the call to "user" of TVDB is going to be done with the token obtained in the first call. And that token is generated with the API_KEY.

Let me know if you understood.

BTW, I have put my API_KEY in my code and the app has returned 106 favorites. That works great. And they have been added well. Directly, without problems.

![image](https://user-images.githubusercontent.com/19903919/80503069-aaea1a00-8971-11ea-9de8-bc84ac591716.png)

A greeting.

**Comment by miigotu** [comment]
You are confusing API key and User Key. On tvdb, go to your dashboard and edit info. The key is labeled "unique user key"

The API key is separate, and that is application wide already set by SC.

alexpablo is a stupid default user that tvdb returns when your info is wrong.

**Comment by ciltocruz** [comment]
Hello! 

No, I'm not confusing both keys. I know what everyone is. 

I'm just telling you the flow that follows SC. Because the favorites of the users that have been entered in the cells of the form are not being retrieved. 

Any API key is used to retrieve data from the series, but retrieving user data requires a tvdb jwt token generated exclusively with an API key of the user in question. 

Best regards!

**Comment by miigotu** [comment]
You do not need to worry about the API key, or the token. That is handled by SC as it always has been.

**Comment by ciltocruz** [comment]
Ok, so it seems that a user section, like /user/favorites/, cannot be retrieved without an own API-KEY for each user.

**Comment by ciltocruz** [comment]
Look at this.

I have continued to emulate what SC does but in the TVDB API.
I have made a first call (with SC's APIKEY) to obtain a Token. This is my token:

{
  "Token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODg3MTg5MTksImlkIjoic2lja2NoaWxsIiwib3JpZ19pYXQiOjE1ODgxMTQxMTl9.edFWUfCcuHyA-LUXIQRVuFb9xpPYnBd8iGFAM9cqPx571d7xsgaW2TcnMLzevzFQBxoD_7L92IMdJQgLnx9v7dpLGui0DB5YigxlgaL5pFrGGGevqDlggBmp0ESJw9iGbDXutCAa4MUNupQpXOPUbWFTPeJo7hh13NzyrsV-qvIY_nh4t7R5lu48BL9BpxxO2cAxzsuvIh7hfYjdNEGjqf29_rrwNixAlCHYerwYQ-C8K_nTD7Hu-em0e3S3i5fWqFLMb8-g4T5OGjZv_F5YQrU9n5zgLKvIiFw156dAYMYk_X0zh2gUPVI3cXqa3PEj17MBSGHEq-mwgjxJhaJJIg"
}

I have debugged in SC to know the call that was made:

![image](https://user-images.githubusercontent.com/19903919/80545457-a8101900-89b3-11ea-8b81-f63ae3283d74.png)

And on TVDB the same:

![image](https://user-images.githubusercontent.com/19903919/80545492-be1dd980-89b3-11ea-8351-11b6b31c41ca.png)

I have added the token.
![image](https://user-images.githubusercontent.com/19903919/80545636-2a004200-89b4-11ea-81af-1f0bef3b7bed.png)

Now I do a get /user/favorites with that token.

![image](https://user-images.githubusercontent.com/19903919/80545724-5451ff80-89b4-11ea-87c6-3a90aed805f3.png)

There is only one favorite. It is normal that it is not mine. I have not yet input my user_tvdb and my user_key.

I'm going to see what user it is. I find alexpablo. Okay, don't worry. The user can't be me yet.

Now I come to this window and the favorite collected from the previous query appears. Okay.

![image](https://user-images.githubusercontent.com/19903919/80546265-81eb7880-89b5-11ea-8958-5421e6dcc3a7.png)


I put my username and my User Key and a test_user is done.
I hope, seeing the code, that it returns the info of MY USER, since I have entered my username and my api_key. But... NOT.

![image](https://user-images.githubusercontent.com/19903919/80546583-4f8e4b00-89b6-11ea-89ff-74788d7c83f3.png)

Why?

By the token. The token is associated with a user's API-KEY.

We might think ... Ok, when we introduce the tvdb_user and the tvdb_user_key we renew the token, but we continue making the call to /login/ with the API-KEY of SC.

What is the result of the operation?

```
curl -X POST --header 'Content-Type: application / json' --header 'Accept: application / json' -d '{
  "apikey": "6aa6e4ecae5b56e9644f6a303c0739b6",
  "userkey": "USER_API_KEY",
  "username": "ciltocruz"
} '' https://api.thetvdb.com/login '
```

It has generated a token for me!

I add the token in the api and quickly go make a call to /user.

![image](https://user-images.githubusercontent.com/19903919/80546981-5b2e4180-89b7-11ea-8e9f-d9f46b94509f.png)

I'm not alexpablo.

------

Trust me. It is necessary, to obtain user data in TVDB, an APIKEY different from the one SC has by default. Be careful, this APIKEY (by default SC) is perfect for obtaining information about series, actors, posters ... but not for obtaining user data.

This message is a little confusing.
![image](https://user-images.githubusercontent.com/19903919/80547156-c4ae5000-89b7-11ea-896d-c8b062b5c889.png)

Indeed, you can obtain a token without a user and without a userkey to obtain series information. SC does it and does it great!
But if you want to obtain user information, you must enter these values. And you will think ... Then everything is correct, because we do it!

The problem, and that does not appear in that text, is that I am convinced that for user to work, the APIKEY must belong to the user "username".

What do you think of this?

**Comment by miigotu** [comment]
I got this, I just had a typo in my code. Be patient.

**Comment by miigotu** [comment]
The API key is application specific, not user specific.

**Comment by miigotu** [comment]
Update and try it again

**Comment by ciltocruz** [comment]
First of all, thanks for the answers and the speed in the operation.

Second, my apologies because it seems that all my reasoning was wrong. (half). Now it works: when the page loads for the first time there is no token previously loaded with user "null".

The third. Works! It's great!

Thanks for everything.

If I find any error I inform you.
Now I would like to be able to help in the translation of the text strings.

A greeting!

**Comment by miigotu** [comment]
Translation is done on https://crowdin.com/project/sickchill

**Comment by ciltocruz** [comment]
Thanks!
