### ISSUE TITLE
Custom URL option removed from ThePirateBay search providers

### ISSUE THREAD

**Issue by ziplock9000** [SickChill/SickChill#6338]
Branch/Commit:
OS: Windows 10
Browser: Chrome
What you did: Tried to enter a new custom URL for ThePirateBay search provider in "Provider Options"
What happened: The option to enter a custom one has been removed in the last month or so, which makes the search provider useless in some regions and even sickchill as a whole.
What you expected: To be able to enter a custom URL which has been a feature for years
Logs: Not relevant

**Comment by miigotu** [comment]
They all use apibay now, there are no mirrors of apibay.
