### ISSUE TITLE
Add Show from existing folders defaults to the 'default folder' and not the folder in which the existing show has been found

### ISSUE THREAD

**Issue by crzed1** [SickChill/SickChill#6339]
Branch/Commit: v2020.04.27-1
OS: Synology NAS and Windows 10 (laptop)
Browser: Firefox

**What you did:** used "Add Existing Shows", which shows the folders configured in SickChill - Config - General - Misc - Show root directories|where the files of shows are located

**What happened:** I selected to add a show from a connected USB drive "/volumeUSB2/usbshare/Series2". After going through the process SickChill used the default folder (marked with a *) from the list and announced the show would be added to SickChill **to** that location. Which would require a copy action from the folder in which the show was found to the as default marked folder.

**What you expected:** I expected SickChill to honor the folder in which it actually found the show (the list in SickChill - Config - General - Misc - Show root directories|where the files of shows are located) and use that one to add the show to the database. No copy required.

**Logs:** my bad, haven't made debug logs

**Possible solutions?** 
1) rename the wording into "**Import** Existing Show" instead of "Add Existing Show" 
2) use the folder in which the shows are found (preferable)
3) make the show folder on the add show page editable

**Comment by crzed1** [comment]
Ah, have found #6265 which looks remarkably the same.

**Comment by miigotu** [comment]
This is unrelated to the issue you linked, but I think you misunderstand what is supposed to happen.

Adding an existing show is adding a show folder that you already have. If you have that root dir in your root dirs, it will add the show as it sits.
If not, I think it will try to copy it to the default root dir.

SC cannot read your mind, so if the root isnt in your root dir settings it makes a best guess.
