### ISSUE TITLE
Do not download subtitles with Addic7ed

### ISSUE THREAD

**Issue by C0rwen** [SickChill/SickChill#6341]
Good morning all,

I use the addic7ed provider for the subtitles.
However, the latter does not download any subtitles yet present on the site.
I did a test with opensubtitle and it works.

I only want to use addic7ed

Thank you all

**Comment by C0rwen** [comment]
hi, I have already done a research and I have not found anything that solves my problem ....

**Comment by miigotu** [comment]
You will have to try with the subliminal cli version, because we do not maintain the subtitles providers. We simply import subliminal and search with that.

**Comment by C0rwen** [comment]
How can I install this ?

**Comment by VGBenjamin** [comment]
Apparently Addic7ed have added a repatcha and it is not possible to grab the subtitles anymore.
Here is the issue: https://github.com/Diaoul/subliminal/issues/1005
