### ISSUE TITLE
Problem with searching for files in a series

### ISSUE THREAD

**Issue by C0rwen** [SickChill/SickChill#6342]
Good morning all,

In some of my series, there are multiple episodes.
In the series tab, I put episode 2 ignored.
However with each new download, sickchill skips this episode in download and asks me to download the subtitles

 How to get past this?

Thank you all

**Comment by miigotu** [comment]
Huh?

**Comment by C0rwen** [comment]
I put the episode in ignored status so that it doesn't search for subtitles.
But regularly, it returns to download status

**Comment by miigotu** [comment]
Episode status has nothing to do with subtitles though
