### ISSUE TITLE
Multiple disk extents under windows/vmware

### ISSUE THREAD

**Issue by Jonnehs** [SickChill/SickChill#6344]
Hey,

Couldn't find the info I wanted in the help or settings descriptions. How does Sickchill handle multiple root directories in terms of using the space or transferring between multiple root directories on multiple disk drives?

Mine runs in a VMWare hosted windows environment and I've been burned by an (unrelated) hardware/esx issue which has meant I've had to recover and copy the 10TB virtual disk a few times to recover. Once this is finished it'd probably be better and more scalable to use mutiple virtual disk extents instead, so the question is really how well SickChill handles that, does it move series etc around and keep them on the same disk with sister episodes, or is the functionality not there or very basic?

Would I be better off having multiple disks but mounting them into the same root drive with NTFS? This kinda defeats the purpose so it'd be much better if SC handled multiple disks elegantly I guess, but it'd be good to know what to expect before I start shifting the data around.

**Comment by miigotu** [comment]
It won't magically select a different root, you select the root when you add the show. If you want to put the show on a different root you can move it from one drive to another, make sure the root is added on SC, and edit the show and select the new root. Or in the case of many shows move them all to a new root and mass update -> edit -> select a new root.

My advice if you have more than one drive is to use a raid1/raid5 etc, for redundancy.

**Comment by Jonnehs** [comment]
ah ok, so you just assign the root manually? That can work I guess. I think I remember where you select that now that you say it.

It was in a raid, just a random fluke issue meant the hypervisor cant read the array anymore
