### ISSUE TITLE
Several network icons are missing

### ISSUE THREAD

**Issue by Ventje23** [SickChill/SickChill#6346]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 731ed8515721409268876f307d4972635a8f6b7b
OS: Linux-3.10.35-x86_64-with-glibc2.2.5
Browser: Chrome
What you did: updated to latest Sickchill
What happened: noticed that several network icons are missing (like in issue #6337 the BCC iplayer):

- uk tv drama
- sony crackle
- spectrum
- pop
- fox channel (uk)
- facebook watch
- quibi
- acorn tv
- stan

What you expected:
Logs:

```
AA 2020-04-28 09:23:44 ERROR     not open static file /volume1/@appstore/sickchill/var/SickBeard/gui/slick/images/network/uktv drama.png
etc...
```

**Comment by miigotu** [comment]
You can make a pull request with the images you want added, sized 64x32

**Comment by Ventje23** [comment]
I have (found) a couple of logo's but some of them are on a black background is that a problem?

**Comment by miigotu** [comment]
I usually find them on the website for the network. Sometimes I use the favicon. The color of the images don't matter as long as they have transparent edges.

**Comment by Ventje23** [comment]
So here are some logo's

for Spectrum TV there is a blue and a white version. Personally I like the blue one better, but maybe the white one works better.

Hope you can use them.


![UK TV Drama](https://user-images.githubusercontent.com/59983825/80920853-cb034a00-8d72-11ea-81b9-a81b3e2e312b.png)
![Stan](https://user-images.githubusercontent.com/59983825/80920854-cccd0d80-8d72-11ea-9870-f9b3bcd34c59.png)
![Facebook Watch](https://user-images.githubusercontent.com/59983825/80920857-ce96d100-8d72-11ea-9a6b-1fe4631fa98c.png)
![SpectrumTV - Blue Logo](https://user-images.githubusercontent.com/59983825/80920859-d22a5800-8d72-11ea-99fc-036bfa7371ab.png)
![Pop](https://user-images.githubusercontent.com/59983825/80920861-d3f41b80-8d72-11ea-8fc6-ff7f36aa952d.png)
![Quibi](https://user-images.githubusercontent.com/59983825/80920863-d5bddf00-8d72-11ea-8ffe-0cc6092e7298.png)
![Acorn TV](https://user-images.githubusercontent.com/59983825/80920864-d787a280-8d72-11ea-87ba-6e2c2e962d8c.png)
![Crackle](https://user-images.githubusercontent.com/59983825/80920868-da829300-8d72-11ea-8637-46ee1c76f941.png)
![SpectumTV - White Logo](https://user-images.githubusercontent.com/59983825/80920884-ef5f2680-8d72-11ea-9811-8f96bb73ef39.png)

**Comment by miigotu** [comment]
Can you make the pull request? Thanks.

**Comment by Ventje23** [comment]
unable to create branch and pull request,
Thank you
