### ISSUE TITLE
Can I remove sickrage now?

### ISSUE THREAD

**Issue by damagu** [SickChill/SickChill#6348]
This is just a question not so much an issue...

I shifted to Sickchill from Sickrage. I now have these directories `/opt/sickrage` and `/opt/sickchill`. Can I remove `/opt/sickrage` and its contents or does sickchill need it to remain in place? 

If I can remove it, is there a particular way I should  go about it or would be `rm -rf /opt/sickrage` be suitable?

**Comment by miigotu** [comment]
Make sure there isn't anything you need in /opt/sickrage like databases or media files. Then rename the folder and reboot the machine and test SC

**Comment by damagu** [comment]
Okay I actually did that already - I changed the name of the directory to /opt/sickrage_bak but when I saw [a recent post of yours](https://github.com/SickChill/SickChill/issues/6230) where you said:

> Linux with Git

```
cd path/to/sickchill
systemctl stop sickrage
find . -name "*.pyc" -delete
find lib -empty -type d -delete
git pull
git clean -dfq lib
systemctl start sickrage
```
... and I saw that you were saying to stop sick**rage**, deal with files in the sick**chill** directory and then start sick**rage** again, and I started thinking maybe I needed sickrage to stay where it was. But, I'll be the first to admit, I was probably just missing something about the context.

Anyway... I've moved the sickrage directory, rebooted and tested, assuming everything is running correctly, do I then just rm the sickrage directory?

**Comment by miigotu** [comment]
That user's service was still named sickrage that's all

**Comment by damagu** [comment]
Okay thanks. And what about this:

> Anyway... I've moved the sickrage directory, rebooted and tested, assuming everything is running correctly, do I then just rm the sickrage directory?

**Comment by miigotu** [comment]
As long as you don't need anything from there yes. Old db backups or anything?

**Comment by damagu** [comment]
Thanks
