### ISSUE TITLE
Error adding new shows

### ISSUE THREAD

**Issue by mountwc** [SickChill/SickChill#6350]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master/3e12397aa1e0e125752e46a629fba4f56dcdc1ab 
OS: Centos
Browser: firefox
What you did: Attempted to add a new show to SickChill
What happened:  Show never appears in show list.
What you expected:  new show in the list.
Logs:
```
2020-04-29 07:35:04 ERROR    MAIN :: [3e12397] There was an error creating the show in /home/kpood/SickChill/shows/Devil Docs: Error attempt to write a readonly database
Traceback (most recent call last):
  File "/home/kpood/SickChill/SickBeard.py", line 416, in load_shows_from_db
    cur_show = TVShow(sql_show[b'indexer'], sql_show[b'indexer_id'])
  File "/home/kpood/SickChill/sickbeard/tv.py", line 121, in __init__
    self.loadFromDB()
  File "/home/kpood/SickChill/sickbeard/tv.py", line 797, in loadFromDB
    self.loadIMDbInfo()
  File "/home/kpood/SickChill/sickbeard/tv.py", line 856, in loadIMDbInfo
    results = filter(lambda x: x.type == 'TV series' and x.title == attempt, i.search_for_title(attempt))
  File "/home/kpood/SickChill/lib/imdbpie/facade.py", line 87, in search_for_title
    for result in self._client.search_for_title(query):
  File "/home/kpood/SickChill/lib/imdbpie/imdbpie.py", line 182, in search_for_title
    search_results = self._suggest_search(title)
  File "/home/kpood/SickChill/lib/imdbpie/imdbpie.py", line 160, in _suggest_search
    search_results = self._get(url=url, query=query_encoded)
  File "/home/kpood/SickChill/lib/imdbpie/imdbpie.py", line 307, in _get
    headers.update(self.get_auth_headers(full_url))
  File "/home/kpood/SickChill/lib/imdbpie/auth.py", line 112, in get_auth_headers
    creds, soon_expires = self._creds_soon_expiring()
  File "/home/kpood/SickChill/lib/imdbpie/auth.py", line 97, in _creds_soon_expiring
    creds = self._get_creds()
  File "/home/kpood/SickChill/lib/imdbpie/auth.py", line 84, in _get_creds
    with diskcache.Cache(directory=self._cachedir) as cache:
  File "/home/kpood/SickChill/lib/diskcache/core.py", line 408, in __init__
    sql(query, (key, value))
OperationalError: attempt to write a readonly database

```

**Comment by miigotu** [comment]
Permissions.

**Comment by mountwc** [comment]
I've checked the sickbeard.db file and the permissions are correct.  This started happening on 3 different instances of SickChill after I did an update a day or 2 ago.

**Comment by CrimeClown** [comment]
I am having the same issue.

**Comment by mountwc** [comment]
It's definitely a permissions issue, but i can't find it.  I've chmod and chowned the entire SickChill directoy down, that didn't fix anything.  If I restart the instance as root, it works just fine.

**Comment by miigotu** [comment]
Docker?

**Comment by mountwc** [comment]
no.   3 installs running as 3 different users.

**Comment by ljw1** [comment]
I am also having the same issue. It is for a show I previously tried to add but there was a bug preventing it. Now it detects the folder and won't add it.

**Comment by fonzy69** [comment]
problem of the same type in windows, show appear a short time  in webui and disappear. empty folder with show name is create

**Comment by jayhowell** [comment]
yeah these seem like permissions Issues. I just installed fresh from master and I didn't have the problem.  @mountwc did you also check the file permissions not just of the file itself, but the directory the db is hosted in? https://stackoverflow.com/questions/40703228/python-sqlite3-operationalerror-attempt-to-write-a-readonly-database

Other things that would help
* You're on centos, can you do a ls -l  on the directory that contains the db and the db itself and upload the output?
* Are you running the service?  
    * If you are, what user are you running it as?
* Can you run sickchill as root from the command line(does it work when you do that?) - that will verify it's a permissions issue with the user you're running as.
    * `sudo python2.7 sickbeard.py`

**Comment by miigotu** [comment]
```bash
sudo chown -R username:username sickchilldatadir
```

The other guy with issues on Windows, set the time on the machine.

**Comment by fonzy69** [comment]
the time is already ok

**Comment by asbestinuS** [comment]
Hi,
I was just adding a few existing shows and I can say that I have the same problem. Adding an existing show shows "Loading...(Series Name)". Adding a show using the imdb thing it shows "Loading... (Loading)" and no error in the debug log. Checked my time, it's fine. Running under Windows Server 2019 with Version: v2020.04.28-3. Not sure how permissions would be a problem, it's a normal folder under C root with all normal permissions (that came with the installer). Anything else I can provide to help?
Thanks

**Comment by gdeans** [comment]
I’m seeing the same thing on 7 Little Johnstons.  I had it in a previous SC install, but I changed to use a fresh install to fix other issues.  The only thing I get in my logs is about a wrong or missing ID in tvshow.nfo but I’ve triple checked the nfo and it’s correct and valid.  This new install had no problem with the other 60+ shows so it’s not permissions; however, I also have Media Center Master on a Windows box that hangs when trying to fetch that same show for a missing episodes report.  I’m not sure, but maybe it’s some trash data or no response from TVDB?  Is it possible to modify the script to add either the returned data or query timeout in the logs?

**Comment by CrimeClown** [comment]
I've not been able to fix this using the current version. I downgraded to an old version from 2 weeks ago and now it's fine.

**Comment by miigotu** [comment]
This is failure to write to a temp dir. Im going to try and push a fix using CACHE_DIR for it (which SC should be able to write to)

**Comment by miigotu** [comment]
Should be fixed

**Comment by gdeans** [comment]
Yes!  After the update I see the IMDb processing in the logs and it’s keeping the show.  What temp folder was it looking for or having problems with?  I want to fix it so there aren’t other issues (w/SC or something else)

**Comment by mountwc** [comment]
Thank you.  confirmed issue is resolved.
