### ISSUE TITLE
Emby notifications for an https server

### ISSUE THREAD

**Issue by mabelisle** [SickChill/SickChill#6351]
Branch/Commit: v2020.04.28-3
OS: OSX
Browser: Firefox
What you did: I updated my emby server to https
What happened: Notifications don't work anymore
What you expected: N/A
Logs:
```
2020-04-29 09:46:39 WARNING  WEBSERVER-HOME :: EMBY: Warning: Couldn't contact Emby at http://xxxx.xxxxx.com/emby/Notifications/Admin
```

"http" is hard coded in the link.

https://github.com/SickChill/SickChill/blob/3e12397aa1e0e125752e46a629fba4f56dcdc1ab/sickbeard/notifiers/emby.py#L55

**Comment by miigotu** [comment]
Are they all https now?

**Comment by mabelisle** [comment]
By default both are enabled on 2 different ports 8096&8020 but since I started using a reverse proxy, http is not accessible anymore. So it's a choice to use one or the other or both.
