### ISSUE TITLE
Hard link falls back to copy with no ability to stop it

### ISSUE THREAD

**Issue by Joshfindit** [SickChill/SickChill#6352]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 731ed8515721409268876f307d4972635a8f6b7b
Version: v2020.04.27-2
Database Version: 44.0

OS: Docker
Browser: Firefox
What you did: During hardlink troubleshooting, I processed some files with "Manual Post Processing"
What happened: hardlink failed and it copied instead
What you expected: hardlink to fail and log the error
Logs:
```
2020-04-29 12:53:43 WARNING  POSTPROCESSOR-MANUAL :: Failed to create hardlink of /media/Replaceable/Torrents/Sick/SHOW.S03.720p.WEB-DL.H264/SHOW S03E19 720p h264-CtrlHD.mkv at /media/Replaceable/Video/Movies, Cartoons, and TV - PG - PG13 rated/Keep/TV/SHOW/Season 03/SHOW - S03E19 - .mkv. Error: [Errno 1] Operation not permitted. Copying instead
```

For my setup, I don't ever want a copy made: hardlink or nothing.
I understand that it's a sane default for people, but a checkbox in Settings > Post Processing, as well as one in Shows > Manual Post Processing would be a big help

**Comment by miigotu** [comment]
Try using reverse symlink method instead. Hard link only works when the source and destination are on the same file system partition.

If you want to hard link, out your downloads folder on the same drive as the shows folder.

I'm not going to add more options to the already confusing enough post processor.

**Comment by Joshfindit** [comment]
Sorry, I think you’ve assumed a lack of knowledge on my part.

The downloads folder and the shows folder are on the same drive, and symlinks are not at all desired.

What keeps happening is things will change with the Docker image, or there will be a permissions problem with the underlying system (maybe I manually make a folder through smb). Point being there will be something subtle and seemingly innocent that changes that causes all files to be duplicated where they should not be.

And, since this is only a warning, it can go unnoticed for a while causing dozens or hundreds of GB in wasted space. Because of this I’m now in the process of creating a script to de-duplicate by going through all the episodes and hard-linking.

**Comment by Joshfindit** [comment]
Circling back on this as it's hitting me again during an import through the Docker container.

As there's no documentation on https://github.com/SickChill/SickChill/wiki/Post-Processing that says that copying is the fallback, I'm going to suggest simply changing the default behavior:

When a hard link can't be made, fail.

This will force people to see the issue and correct it themselves before space is doubled.

**Comment by miigotu** [comment]
Negative. Just `delete files and data` when you remove a torrent from your client, and the copy is removed. We arent going to fail every time and break current functionality for one person who apparently cant grasp this. If you need an option for it, make a PR that doesnt change current functionaily.
