### ISSUE TITLE
Shows don't update automatically from Disk

### ISSUE THREAD

**Issue by JeeWee** [SickChill/SickChill#6355]
Branch: master
Commit: 3e12397aa1e0e125752e46a629fba4f56dcdc1ab
Version: v2020.04.28-3
Database Version: 44.1

After I watched an episode I usually delete the episode from the hard drive. Before, SickChill would every night automatically update the episode status from Downloaded to Archived. 
This is no longer happening. I have to manually click on the Re-scan files button.

**Comment by fadern** [comment]
@miigotu Hi,
Ive now updated SC but the episodes are still marked as downloaded but the actual files are deleted.  Have you change the way it supposed to work?

**Comment by JeeWee** [comment]
I believe the process that marks them automaticlly archived once they're deleted only runs at night.

**Comment by fadern** [comment]
ok, ill wait...

thank you
