### ISSUE TITLE
SC on Windows constantly makes noise

### ISSUE THREAD

**Issue by proctophage** [SickChill/SickChill#6359]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: main/v2020.04.28-3
OS: Windows 10
Browser: N/A
What you did: Any error. Fail processing, fail to connect to provider, timeouts, etc.
What happened: Plays windows background notification.wav
What you expected: record in logs only
Logs:
I could post the process monitor log but it wouldn't really help. I can't run sickchill as a service account (and I would want to anyway) since system doesn't path network drives, so I run it as the normal user account. Running it as a user using NSSM and I see that every time conhost fails to do anything over the network it plays the sound. There's no way to turn off this functionality in windows. You can change the system sound but that's it. If you remove the critical stop sound altogether it just plays the default notification noise. It's driving me crazy because there's no way to turn it off.

**Comment by miigotu** [comment]
Not sure if you used the SC installer or not (you should have, and then just changed the user the service runs as or used \\Machine\share type path instead of a mapped drive) but switching from pythonw-python or vice versa fixes your issue.

**Comment by proctophage** [comment]
Oh my gosh I'm an idiot. I had to redo the NSSM and you're right I used python and not pythonw. thank you!
