### ISSUE TITLE
Mako Error on renaming

### ISSUE THREAD

**Issue by asbestinuS** [SickChill/SickChill#6364]
Branch: master
Commit: 3e12397aa1e0e125752e46a629fba4f56dcdc1ab
Version: v2020.04.28-3
Database Version: 44.4
What you did: Selecting a manual added episode to use the renaming mechanism from SickChill (clicking "Preview rename" on the top right of the show)
What happened: after about 1 minute a new site openend and I got a "Mako Error" with a 500 error code in the tab name
What you expected: the rename to work
Logs: couldn't find any entries?
```
File C:/Program Files/SickChill/SickChill/gui/slick/views/testRename.mako:82, in render_content:
if not ep_obj._location:

AttributeError: 'NoneType' object has no attribute '_location'
```
SickChill is installed on a virtual Windows Server 2019 and I'm using "Waterfox" to access sickchill in my internal network.

Thanks in advance!

**Comment by miigotu** [comment]
Cannot reproduce this currently

**Comment by BurakNeu** [comment]
Branch: master
Commit: e9ccfe43f7515ddcacb872f3dc679694ad707481
Version: v2020.05.08-4
Database Version: 44.4
Experienced the same issue.
Forcing full update is fixes the issue for that specific show.
Restarting SickChill fixes the issue for all shows that are added.
But issue persist when new (never before added) shows are added via 'Add existing show'

**Comment by asbestinuS** [comment]
Well, with v2020.05.08-4 it's working now. I noticed a bunch of shows where queued for "mass update". Maybe the renaming wasn't working because I might have chosen a show thats currently updating?

**Comment by miigotu** [comment]
Yes, you have to wait until the show is done being loaded from the indexer before you can rename the files.

Needless to say, you shouldn't need to use the renamer page, almost never.
