### ISSUE TITLE
[APP SUBMITTED]: WEBSERVER-ERRORLOGS :: [c5ed827] git symbolic-ref -q HEAD returned : 

### ISSUE THREAD

**Issue by klainn** [SickChill/SickChill#6366]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/bcd1e9f91e007372337366fc41987843
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by klainn** [comment]
Error as shown in log:

`2020-05-03 08:40:02 WEBSERVER-HOME :: [c5ed827] git symbolic-ref -q HEAD returned :
2020-05-03 08:40:01 WEBSERVER-HOME :: [c5ed827] git config remote.origin.url https://github.com/SickChill/SickChill.git returned code 255, treating as error : error: could not lock config file .git/config: Permission denied
2020-05-03 08:39:17 WEBSERVER-HOME :: [c5ed827] git fetch origin --prune returned code 255, treating as error : error: cannot open .git/FETCH_HEAD: Permission denied`

This is on the linuxserver/sickchill docker container.

**Comment by klainn** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/9e529253f46d8d43d536bf4ea8460984
### ERROR
```
WEBSERVER-HOME :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by klainn** [comment]
This double posed from the app, I'm not sure why that would happen.

**Comment by ronrosenfeld** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/f5ee2cb6b9a24459869799bc1b9325cb
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ronrosenfeld** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/f345293c00994e2ae6f6db2d6f106459
### ERROR
```
WEBSERVER-HOME :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by tardfree** [comment]
I have the same issue, also with the linuxserverio/sickchill container.
The issue is permissions inside their container, and was noticed in the PR which caused it. https://github.com/linuxserver/docker-sickchill/pull/17#issuecomment-622462827
The git clone runs as root (in the Dockerfile), but the app runs as a user, so the permissions don't allow the running process to write to the git location, so you get permission denied.

**Comment by ronrosenfeld** [comment]
@tardfree  Is there a fix?  Or a temporary workaround?

**Comment by tardfree** [comment]
Following their instructions for updating would be the workaround to update. [Readme file, updating info section](https://github.com/linuxserver/docker-sickchill). That redeploys the container from the latest version.
Doing that mine checked out the latest git tag [v2020.05.03-1](https://github.com/SickChill/SickChill/releases/tag/v2020.05.03-1) (released 2 days ago)
The issue would still remain where it can't check what the latest is. Most of the linuxserverio containers state 

> Most of our images are static, versioned, and require an image update and container recreation to update the app inside.


I'm testing chowning the files under /app inside the container to see what happens - the update check succeeded and stated I'm on the latest version. I'm wondering if this fixes up the other issues I've been having (which I'm still tracking down to log an issue/fix). Doing anything inside the container like this would get blown away when it updates next time.

Previously I've used the new update banner notification as a prompt to update the container - not to update inside the container.

**Comment by ronrosenfeld** [comment]
@tardfree  Hmm. I've done that and still have the problem.  Inspecting the image I get:

` "build_version": "Linuxserver.io version:- v2020.05.03-1-ls37 Build-date:- 2020-05-03T03:50:20-04:00",`

Any other thoughts?

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/315e87f8e09ae3fa0a47a518c21d71c0
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
No Log available with ERRORS:
### ERROR
```
CHECKVERSION :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ronrosenfeld** [comment]
@fatgeek:  Are you also running in Docker? That seems to be a common denominator so far.

**Comment by fatgeek** [comment]
Yes. Linuxserver.io docker running on Unraid.

**Comment by ronrosenfeld** [comment]
Turns out this issue is a side-effect of the LSIO version now putting the correct Commit/Version on the SickChill Info page.  Before, that would be blank or out of date.  See [Sickchill Permission Errors](https://discourse.linuxserver.io/t/sickchill-permission-errors/1452)

**Comment by DasKaktus** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:45:25) [GCC 9.2.0]**
Operating System: **Linux-4.19.93-v7l+-armv7l-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/2b6a9425a1a76f37eb25e68715a5bd42
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DasKaktus** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:45:25) [GCC 9.2.0]**
Operating System: **Linux-4.19.93-v7l+-armv7l-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/1abdc28a8c5f336c49e6128accc2a985
### ERROR
```
WEBSERVER-HOME :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DasKaktus** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:45:25) [GCC 9.2.0]**
Operating System: **Linux-4.19.93-v7l+-armv7l-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/c6ced20507696a45f79e2426439c0167
### ERROR
```
WEBSERVER-CONFIG :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DasKaktus** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:45:25) [GCC 9.2.0]**
Operating System: **Linux-4.19.93-v7l+-armv7l-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/5fd088dffdef5ab2d65f98e4daf9fc02
### ERROR
```
CHECKVERSION :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DasKaktus** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:45:25) [GCC 9.2.0]**
Operating System: **Linux-4.19.93-v7l+-armv7l-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/4faf0f8075043e988659b6436f7c4ff9
### ERROR
```
MAIN :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DasKaktus** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:45:25) [GCC 9.2.0]**
Operating System: **Linux-4.19.93-v7l+-armv7l-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/9ce76addc013f411533449ce25dcad90
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Reverted a change to the docker image, I will merge it to master soon as I get to a PC.

**Comment by DasKaktus** [comment]
I solved it by going into the docker and set the git to master

>docker exec -it sickchill /bin/bash
cd /app/sickchill
git checkout master

**Comment by ronrosenfeld** [comment]
@DasKaktus Tried that -- didn't work for me. Still got the error messages when trying to "Check for Updates" either manually or automatically.

**Comment by ronrosenfeld** [comment]
Tried that.
It worked **until** I restarted sickchill. Then the error messages returned.

**Comment by DasKaktus** [comment]
> 
> 
> @DasKaktus
> 
> Tried that.
> It worked **until** I restarted sickchill. Then the error messages returned.

Weird. Maybe not exact problem then. Because it didnt work until i restarted sickchill.

I remember now that I also changed owner on all git folders to abc:abc also

**Comment by miigotu** [comment]
```bash
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once sickchill
```

**Comment by ronrosenfeld** [comment]
@miigotu  What problem is that code line supposed to fix?  Isn't it just another method of updating SickChill to the latest version?  It doesn't seem to do anything about the error being returned when checking for an update within the GUI, which seems to be an issue with LSIO having

> "switched to `git clone` to get all the other info that sickchill uses to determine version. But since we do versioned releases, we can’t just `git clone` and leave it at that, so we then do `git checkout <tag>` which sets it to the tagged release that is also in the docker image tag.
It seems the update checker needs to know which branch it is currently on to figure out updates. Since we checkout the specific tag, we’re no longer on the master branch, hence the error."

**Comment by miigotu** [comment]
You are confusing the sickchill/sickchill image with the linuxserver/sickchill one.

Ours was broken due to permissions. The linuxserver one is a different story.

**Comment by ronrosenfeld** [comment]
@miigotu  OK. But I think the others in this thread are also using the linuxserver/sickchill image.  I didn't realize your code line applied to the sickchill/sickchill image.

**Comment by miigotu** [comment]
Linuxserver could either clone the whole repo, or ask for a flag that disables the updater. They will need to coordinate

**Comment by ronrosenfeld** [comment]
I've disabled the automatic updater on my SC installation. That works for me, for now, except I have to manually check (either by coming here or doing a docker pull) to see if there are updates.

**Comment by miigotu** [comment]
> ```shell
> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once sickchill
> ```

This will automatically update the docker instance, regardless if where it comes from.

**Comment by ronrosenfeld** [comment]
> You could even put that in a Cron job

I will give that some consideration.  Thanks.  And quicker than going through the `docker create` process.
