### ISSUE TITLE
[APP SUBMITTED]: WEBSERVER-ERRORLOGS :: [c5ed827] git config remote.origin.url https://github.com/SickChill/SickChill.git returned code 255, treating as error : error: could not lock config file .git/config: Permission denied

### ISSUE THREAD

**Issue by klainn** [SickChill/SickChill#6367]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/13b9ddf2b229d2d9ab80e3782fe89f9e
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] git config remote.origin.url https://github.com/SickChill/SickChill.git returned code 255, treating as error : error: could not lock config file .git/config: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by klainn** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/4b58decf001a174753950425f4192f28
### ERROR
```
WEBSERVER-HOME :: [c5ed827] git config remote.origin.url https://github.com/SickChill/SickChill.git returned code 255, treating as error : error: could not lock config file .git/config: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by klainn** [comment]
Sorry for the triple post. Maybe that's another issue. It took it about 5 minutes to actually post this issue and I only clicked submit once.

**Comment by ronrosenfeld** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/a3868fd63b6c485ff261ffeafd454063
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] git config remote.origin.url https://github.com/SickChill/SickChill.git returned code 255, treating as error : error: could not lock config file .git/config: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ronrosenfeld** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/3b7cdb8a65a9b809d4d441e33ba04260
### ERROR
```
WEBSERVER-HOME :: [c5ed827] git config remote.origin.url https://github.com/SickChill/SickChill.git returned code 255, treating as error : error: could not lock config file .git/config: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by didyouexpectthat** [comment]
Your permissions need to be reset.  "could not lock config file .git/config: Permission denied"
Check that your user who runs SickChill has r/w permissions on files.

**Comment by ronrosenfeld** [comment]
It just started happening after years of no problems with permissions.
Sickchill is running in a Docker container.  Permissions are `777` (`rwxrwxrwx`)
What to change?

**Comment by ronrosenfeld** [comment]
Another item I've noticed, possibly related:

Under **General Configuration --> Advanced Settings --> GitHub** , the Branch Version is set to "Develop"

And, although I can try to change it to Master, when I restart Sickchill, it switches back to Develop.

![image](https://user-images.githubusercontent.com/18516066/80963022-2ae20b00-8ddc-11ea-88c0-ec8595582db0.png)

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/d994d51f261e1df76526cb83a7055261
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] git config remote.origin.url https://github.com/SickChill/SickChill.git returned code 255, treating as error : error: could not lock config file .git/config: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
No Log available with ERRORS:
### ERROR
```
CHECKVERSION :: [c5ed827] git config remote.origin.url https://github.com/SickChill/SickChill.git returned code 255, treating as error : error: could not lock config file .git/config: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Reverted a change to the docker image, I will merge it to master soon as I get to a PC.
