### ISSUE TITLE
[APP SUBMITTED]: WEBSERVER-ERRORLOGS :: [c5ed827] git fetch origin --prune returned code 255, treating as error : error: cannot open .git/FETCH_HEAD: Permission denied

### ISSUE THREAD

**Issue by klainn** [SickChill/SickChill#6368]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/d8e9d15fcb33db9ed1d41b9ca3f6a8ca
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] git fetch origin --prune returned code 255, treating as error : error: cannot open .git/FETCH_HEAD: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by klainn** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/9d7f75ebb4c7364d82033560f11a1fab
### ERROR
```
WEBSERVER-HOME :: [c5ed827] git fetch origin --prune returned code 255, treating as error : error: cannot open .git/FETCH_HEAD: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by klainn** [comment]
Sorry for the triple post. Maybe that's another issue. It took it about 5 minutes to actually post this issue and I only clicked submit once.

**Comment by ronrosenfeld** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/e420510b023ca47f6dfa79e707b63dec
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] git fetch origin --prune returned code 255, treating as error : error: cannot open .git/FETCH_HEAD: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ronrosenfeld** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/423bdfb48391904c67fef5ec5cf37237
### ERROR
```
WEBSERVER-HOME :: [c5ed827] git fetch origin --prune returned code 255, treating as error : error: cannot open .git/FETCH_HEAD: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/f64cb2762c15689442dfd08f01f438f0
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] git fetch origin --prune returned code 255, treating as error : error: cannot open .git/FETCH_HEAD: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by fatgeek** [comment]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-4.19.107-Unraid-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
No Log available with ERRORS:
### ERROR
```
CHECKVERSION :: [c5ed827] git fetch origin --prune returned code 255, treating as error : error: cannot open .git/FETCH_HEAD: Permission denied
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
If this is docker, Reverted a change to the docker image, I will merge it to master soon as I get to a PC..
Otherwise fix permissions
