### ISSUE TITLE
Airdate is never

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6369]
I have a number of shows, and episodes in other shows that have an airdate of never.
Great Expectations (1981) is one....
The TVDB list the airdate as BBC without any date.

  SickChill Info:
Branch: master
Commit: c5ed827b40693bd481417845e37ff2622cd6ab8a
Database Version: 44.1
  Python Version:
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
  SSL Version:
OpenSSL 1.0.2t 10 Sep 2019
  OS:
Windows-7-6.1.7601-SP1
  Locale:
en_US.cp1252

What you did: Added the Shows..
What happened: Nothing.... SickChill will not do anything with these episodes, or shows
What you expected:  Search for and download these episodes
Logs:
```
PASTE LOGS HERE
```
![image](https://user-images.githubusercontent.com/14140816/80915203-c614ab00-8d1e-11ea-9857-d31dbc566420.png)

**Comment by miigotu** [comment]
If tvdb shows no airdate, where do you think we get that data? Fix it on tvdb.

**Comment by nydave69** [comment]
couldn't we just search for it anyway?
