### ISSUE TITLE
[APP SUBMITTED]: WEBSERVER-ERRORLOGS :: [3e12397] "/usr/bin/git" symbolic-ref -q HEAD returned : 

### ISSUE THREAD

**Issue by psyciknz** [SickChill/SickChill#6376]
### INFO
Python Version: **2.7.16 (default, Nov 15 2019, 19:32:34) [GCC 9.2.0]**
Operating System: **Linux-5.3.0-51-generic-x86_64-with**
Locale: None
Branch: ****
Commit: SickChill/SickChill@3e12397aa1e0e125752e46a629fba4f56dcdc1ab
Link to Log: https://gist.github.com/8e02d0f05922d2bc53a32e00ed9c500f
### ERROR
```
WEBSERVER-ERRORLOGS :: [3e12397] "/usr/bin/git" symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ronrosenfeld** [comment]
Are you running Docker using the Linuxserver/sickchill image?

**Comment by miigotu** [comment]
If this is docker, Reverted a change to the docker image, I will merge it to master soon as I get to a PC.

**Comment by psyciknz** [comment]
Yes it was the linuxserver docker image I eas getting this on.  I've since turned off check for updates on their advice.
