### ISSUE TITLE
DelugeD: Deluge 2.0+ rpc connection fails

### ISSUE THREAD

**Issue by nopoz** [SickChill/SickChill#6377]
Connecting to the Deluge 2.0.3-2-201906121747 using the "DelugeD" option in SickChill and clicking the "Test Connection" button generates this error:

```
Error: Unable to Authenticate! Please check your config!
```

Checking the deluge logs these log lines are produced:

```
20:45:35 [INFO    ][deluge.core.rpcserver         :171 ] Deluge Client connection made from: 127.0.0.1:54826
20:45:35 [WARNING ][deluge.transfer               :114 ] Error occurred when parsing message header: Received invalid protocol version: 120. PROTOCOL_VERSION is 1..
20:45:35 [WARNING ][deluge.transfer               :116 ] This version of Deluge cannot communicate with the sender of this data.
20:45:35 [WARNING ][deluge.transfer               :136 ] Failed to decompress (0 bytes) and load serialized data with rencode: Error -5 while decompressing data: incomplete or truncated stream
20:46:05 [INFO    ][deluge.core.rpcserver         :197 ] Deluge client disconnected: Connection to the other side was lost in a non-clean fashion: Connection lost.
```

The same error is produced every time SickChill tries to send a torrent to Deluge. 

Checking other projects, it looks like the transfer protocol changed in Deluge 2.0 - so others have come up with solutions for detecting the protocol version. For example this issue reported at https://github.com/Flexget/Flexget/issues/2287 and the fix https://github.com/JohnDoee/deluge-client/pull/29

**Comment by nopoz** [comment]
The other "Deluge" connection method still works. I've created a push request in #6378 which gives "Deluge" feature parity with "DelugeD".  

I assume the connection library for DelugeD needs to be updated in order for it to work again with Deluge 2.0+

**Comment by miigotu** [comment]
Merged, it will be in master later tonight.

**Comment by nopoz** [comment]
@miigotu Just to be clear, #6378 updates "Deluge" to give it feature parity with "DelugeD". This makes it a workable alternative, but "DelugeD" is still broken. In order to fix it, the deluge client submodule the deluged.py file uses would need to be updated to use deluge-client instead of synchronousdeluge.

**Comment by miigotu** [comment]
Interested in doing that?

**Comment by miigotu** [comment]
I rewrote the deluged client to use deluge-client, seems to work nice.

**Comment by nopoz** [comment]
> 
> 
> I rewrote the deluged client to use deluge-client, seems to work nice.
> (also fixed tpb)

Thanks!
