### ISSUE TITLE
Docker: PUID no longer setting sickchill user uid in container. Breaks media access. 

### ISSUE THREAD

**Issue by cloudynetwork** [SickChill/SickChill#6380]
Latest docker image, upon recreation could no longer access media drives. I set sickchill PID to 1000 via Docker ENV PUID. Now sickchill launches with PID 317 breaking many things. 

PUID is working fine on other containers recreated today as expected. 
```

**Comment by miigotu** [comment]
Reverted a change to the docker image, I will merge it to master soon as I get to a PC.

**Comment by cloudynetwork** [comment]
Confirmed all fixed now. Thanks.
