### ISSUE TITLE
Episodes won't update when using episode status management 

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6407]
Episodes won't update when using episode status management 
I have a lot of older shows that are Archive SDTV and I want to change it to Downloaded SDTV

Branch/Commit: current
OS: windows 7
Browser:
What you did: episode status management, selected Archive SDTV change to Downloaded SDTV
What happened: lots of errors
What you expected: status to be changed
Logs:
```
12:47:31 WARNING::WEBSERVER-MANAGE :: Refusing to change status of 2x7 to DOWNLOADED because it's not SNATCHED/DOWNLOADED
12:47:31 WARNING::WEBSERVER-MANAGE :: Refusing to change status of 2x8 to DOWNLOADED because it's not SNATCHED/DOWNLOADED
12:47:31 WARNING::WEBSERVER-MANAGE :: Refusing to change status of 2x9 to DOWNLOADED because it's not SNATCHED/DOWNLOADED
12:47:31 WARNING::WEBSERVER-MANAGE :: Refusing to change status of 2x10 to DOWNLOADED because it's not SNATCHED/DOWNLOADED
12:47:31 WARNING::WEBSERVER-MANAGE :: Refusing to change status of 2x11 to DOWNLOADED because it's not SNATCHED/DOWNLOADED
12:47:31 WARNING::WEBSERVER-MANAGE :: Refusing to change status of 2x12 to DOWNLOADED because it's not SNATCHED/DOWNLOADED
12:47:31 WARNING::WEBSERVER-MANAGE :: Refusing to change status of 2x13 to DOWNLOADED because it's not SNATCHED/DOWNLOADED
```

**Comment by miigotu** [comment]
Change them to skipped and refresh the show. They won't have the quality of it isn't in the file name but they will be marked as downloaded

**Comment by nydave69** [comment]
Why can't we just change the status...

I have episodes that are skipped      This is going to be a lot of work..

I was looking at changing 800+ episodes..

**Comment by miigotu** [comment]
Because it has no file location for the episode, so we can't just change the status.
