### ISSUE TITLE
Deleted episodes are still marked as downloaded

### ISSUE THREAD

**Issue by fadern** [SickChill/SickChill#6408]
SickChill Info:
Branch: master
Commit: ebcb4d616200cde7fba8e5b5f4601ecbcd402c1d
Version: v2020.05.07-3
Database Version: 44.1

Python Version:
2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]

SSL Version:
OpenSSL 1.0.2n 7 Dec 2017

OS:
Linux-3.10.105-x86_64-with-glibc2.2.5 / Synology

  Locale:
None.None

Browser: FF
What you did: Deleted some episodes.
What happened: SC didnt change status for the deleted episodes.
What you expected: In earlier version of SC it updated the status of deleted episodes to archived. Now they stays at downloaded. I expect the status to change to Archived.

Is this a new "by design" behavior?

**Comment by miigotu** [comment]
#6355
