### ISSUE TITLE
Can't launch SickChill anymore

### ISSUE THREAD

**Issue by Nickduino** [SickChill/SickChill#6409]
On my Windows PC, I can't access http://localhost:8081/ anymore (website is anavailable).

I haven't manually updated or changed a setting for well over a year and I don't remember what's what...

In the startup menu, I have stop & start sickrage (first install was made many years ago, although I updated the repo to SickChill's), which don't magically make it work.

I see two backups in _C:\SickRage\Data\backup_, should I try restoring the latest one? I wouldn't mind reinstalling everything but what files do I need to keep my configuration?

**Comment by Wally73** [comment]
https://github.com/SickChill/SickChill/issues/6230
try that first

config.ini and sickbeard.db are the files to keep

**Comment by BenjV** [comment]
If you want a to do a freh install act as follow.

Save the following files to a save place
sickbeard.db
config.ini

You could also save the complete folder C:\SickRage\cache\images but they can be recreated by SickChill if they are missing

I am not a windows user but I think they are located in the C:\SickRage folder.

Then uninstall SickRage.
Do a fresh install of SickChill, don't start SickChill yet.
Copy the saved files to the SickChill folder.
If you saved the cache\images then copy those too.
Start SickChill

**Comment by Nickduino** [comment]
> #6230
> try that first

Not sure about _for /f "usebackq delims=" %d in (`"dir /ad/b/s lib | sort /R"`) do rd "%d"_
It tells me (dozens of times) the folder is not empty.

I do the rest nonetheless, to no avail
