### ISSUE TITLE
Add Custom Group not handling space character

### ISSUE THREAD

**Issue by lobofoots** [SickChill/SickChill#6411]
Branch: master
Commit: e9ccfe43f7515ddcacb872f3dc679694ad707481
OS: Darwin 19.4.0
Browser: Firefox 76

What you did: 
Add a TVSHOW, set it as Anime, add a custom group named Kgk, save it.
Edit this show, go to Format, type a custom group for an anime containing a space character (like: EXEM PLE). 
Click Add to whitelist, it goes to the Whitelist box. 
Then click the save changes button.

I tried with 'EXEM PLE' and "EXEM PLE" too

What happened: 
Kgk is still the only group in the list, the EXEM PLE group is not saved 

What you expected: 
for sickchill to save it in the custom group list.

**Comment by miigotu** [comment]
The group has to exist on anidb for that show to be able to add it.

**Comment by lobofoots** [comment]
I don't understand why you made a "custom group" then.

Can you modify this feature so that we can add groups that are not known on anidb.
There are a lot of one time release group and ill-named torrents on nyaa that would match but aren't processed because of that.

ex: https://nyaa.si/view/1171637
release is named [Xspitfire911], I can't add it

**Comment by miigotu** [comment]
![image](https://user-images.githubusercontent.com/390379/81655454-3fd62400-9404-11ea-8d7a-7211790d99fe.png)
