### ISSUE TITLE
POSTPROCESSOR 

### ISSUE THREAD

**Issue by lobofoots** [SickChill/SickChill#6412]
Branch: master
Commit: e9ccfe4
OS: Darwin 19.4.0
Browser: Firefox 76
Postprocessor won't recognise some Anime show files. The numbering is, as usual, not following SxxExx conventions.

Please fix it so that it can better recognize Anime content.

Logs:
```
```

**Comment by miigotu** [comment]
Those files are not from a scene release. SC only works with scene names, because there are rules to the naming convention for scene releases and we can predict what they should look like.

If those were 001 instead of 01 I imagine they would match, but they should also have a quality and language.

**Comment by lobofoots** [comment]
Anime scene releases conventions are different from tvshow conventions.
Even for big release group like https://horriblesubs.info/ use this naming convention:

[ReleaseGroup] ShowName - XX [QualityTags].mkv
 The only exception is when this anime reach 100 episodes, they obviously use XXX numbering
They hardly ever use SxxExx, this is not the norm in this scene.

Can you apply different rules while processing Anime? This would make a great step forward for supporting this content.

**Comment by miigotu** [comment]
I know that if I keep waking up to multiple duplicate issues from you I'm gonna block you. Anime has scene rules too. We follow scene rules as do reputable anime groups. We aren't going to change that. Anime is a secondary feature, and we do it pretty well.
