### ISSUE TITLE
[APP SUBMITTED]: Detected the new Cloudflare challenge.

### ISSUE THREAD

**Issue by beironjohn** [SickChill/SickChill#6413]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
Link to Log: https://gist.github.com/79916c4d7062456bf702ee9cf03d3a82
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
Link to Log: https://gist.github.com/b13ec523c62f8e342388e30a772b3c66
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-78901 :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by shimmerdark** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-8-amd64-x86_64-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by shimmerdark** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-8-amd64-x86_64-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
Link to Log: https://gist.github.com/7ddefe0bcce6de821a972ab8c0606f44
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-266189 :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-110381 :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75897 :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-110381 :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
Link to Log: https://gist.github.com/fe38c26327ae282596b84098b18a9fb7
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-110381 :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e9ccfe43f7515ddcacb872f3dc679694ad707481
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-75897 :: [IPTorrents] :: [e9ccfe4] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by shimmerdark** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-8-amd64-x86_64-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@95dba6e0b3329852909bd361b4f8abac366e15d3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [95dba6e] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by shimmerdark** [comment]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-8-amd64-x86_64-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@95dba6e0b3329852909bd361b4f8abac366e15d3
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [95dba6e] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by beironjohn** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@95dba6e0b3329852909bd361b4f8abac366e15d3
Link to Log: https://gist.github.com/c308e05dc83116bb07b4d285d0cf22ac
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [95dba6e] Request failed: Detected the new Cloudflare challenge. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
