### ISSUE TITLE
Issue with show not being post-processed

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#6416]
No logs to post, I'm afraid.

Magnum P.I. (2018) isn't recognized. I've tried adding "Magnum P I", "Magnum P I 2018" and "Magnum P I (2018)" as scene exceptions, but it still doesn't work. If I manually copy them into the directory and then click "re-scan files" they're identified correctly. Other shows post-process just fine from the same location.

Example filename: Magnum.P.I.2018.S02E20.720p.HDTV.x265-MiNX[TGx]/Magnum.P.I.2018.S02E20.720p.HDTV.x265-MiNX.mkv

Thanks for making a product so good that this seems like an issue worth mentioning :D

**Comment by Wally73** [comment]
I have Magnum P.I and Magnum P.I 2018 as scene exceptions for that show, work fine

**Comment by Tiwas** [comment]
@Wally73 Thanks. Adding the period between P and I seems to solve the problem.
