### ISSUE TITLE
Shows still don't update after episodes are deleted from disk

### ISSUE THREAD

**Issue by JeeWee** [SickChill/SickChill#6417]
SickChill Info:
Branch: master
Commit: e9ccfe43f7515ddcacb872f3dc679694ad707481
Version: v2020.05.08-4
Database Version: 44.1

  Python Version:
2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]

  SSL Version:
OpenSSL 1.1.1d 10 Sep 2019

  OS:
Linux-4.19.97-v7l+-armv7l-with-debian-10.3

  Locale:
en_GB.UTF-8

Browser: Firefox
What you did: deleted episodes from disk
What happened: Episodes aren't updates to Archived
What you expected:Episodes should have been updated from Downloaded to Archived
Logs:

This is a follow up from https://github.com/SickChill/SickChill/issues/6355 and from https://github.com/SickChill/SickChill/issues/6408

This was resolved in https://github.com/SickChill/SickChill/commit/e9ccfe43f7515ddcacb872f3dc679694ad707481 but it didn't. From what I read it's the "don't skip refresh on ended shows".
However the episodes I deleted (after watching) are from shows that are still Continuing

**Comment by JeeWee** [comment]
As extra information: I haven't enabled the option Skip Remove Detection under General > Advanced Settings

**Comment by JeeWee** [comment]
The show Space Command has status Ended, so I'm thinking the Refresh process stops once it finds a show that has status Ended.

**Comment by Torhal** [comment]
I'm seeing the same issue, but none of my shows are Ended. Picking a random show, if I go to view its details I'll see episode file data for files that no longer exist until I click the "Re-scan files" button.

**Comment by JeeWee** [comment]
I'm glad I'm not the only one with this problem. I deleted the series that were ended, and still the same problem. It's not refreshing all series

**Comment by fadern** [comment]
I have the same issue.

**Comment by miigotu** [comment]
Are these shows paused by chance? Check your debug logs when the show updater runs, it should tell you why it didnt change status now

**Comment by rob006** [comment]
Neither paused nor ended in my case. If I use "Re-scan files" button it works fine.

**Comment by JeeWee** [comment]
> 
> 
> Are these shows paused by chance? Check your debug logs when the show updater runs, it should tell you why it didnt change status now

Nope, none of my shows are paused. Logs don't show any errors. It just doens't go through all the shows. Manual update (mass or per show) works fine.

I've just enabled debug, so i'll know more tomorrow after the scheduled update has run

**Comment by Torhal** [comment]
Same here; none of the shows are paused, and manually clicking "Re-scan files" updates the episodes to Archived. Interestingly, the file size properly shows 0 when the episodes have been deleted so that codepath is working as expected.

**Comment by JeeWee** [comment]
Today around 15.40 I deleted all the episodes of The Blacklist season 7. I let the updater run at hour 16.

The log says:
2020-05-16 16:38:25 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 266189: Not creating SQL queue - record is not dirty
2020-05-16 16:38:25 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 266189: Setting status for S07E19 based on status Downloaded (720p HDTV) and location /media/tvshows/The Blacklist/The Blacklist - 7x19 - The Kazanjian Brothers.mkv

Somehow sickchill still thinks the episode is at the location, but it isn't

The full debug log for this show can be found at: https://pastebin.com/TwkB0MnE

**Comment by miigotu** [comment]
`SHOWQUEUE-FORCE-UPDATE` is not where the status gets changed from downloaded to archived, it happens after that in `SHOWQUEUE-REFRESH` or `SHOWQUEUE-FORCE-REFRESH`

The logs you are sharing are not the full process for the show. It does the update, then QUEUES the refresh for awhile later.

**Comment by rob006** [comment]
@miigotu I have over 20 tracked shows, but this night `SHOWQUEUE-REFRESH` task run only for 7 of them. Two of them had removed episodes in last \~2 days, and this is now properly detected - status of episodes was refreshed and removed episodes are marked as archived. In the same time I have show with episodes removed 3 weeks ago, which are still not refreshed and shows as downloaded (the `SHOWQUEUE-REFRESH` task did not start for this show). 

Is there any algorithm to pick which shows should be refreshed?

**Comment by miigotu** [comment]
Shows are only skipped based on settings when they are paused or ended.

**Comment by miigotu** [comment]
Or if the entire show directory does not exist.

**Comment by Torhal** [comment]
> Or if the entire show directory does not exist.

That's strange, because I've only noticed this happening recently and having the show directory not exist has been a default for me for years now; when I delete episodes from within Plex after they've been watched, Plex will auto-delete the containing folder if it was the last episode in the folder.

I'm definitely not going to start deleting episodes directly from the filesystem where my Plex Media Server is running when I can easily do so with the remote control I have in my hand after watching said episode, so I guess this is something I'll need to ignore and simply rely on the Size in the top card saying 0.00 B.

**Comment by tardfree** [comment]
> Shows are only skipped based on settings when they are paused or ended.

Thats good to know. I've been trying to troubleshoot the same issue myself.

I have a show that is continuing(not ended), not paused and has new episode status set to skipped. It seems to never get scanned. I've paused the vast majority of shows I have configured to try to reduce the log volume on this and see if that makes any difference. Curiously the footer still says "50 Active". (my issue is with all shows not picking up new files, not just one show)

Is there any way to run the scanner manually (command line), perhaps in verbose/debug mode? this might make it easier to spot any broken filenames or similar issues.

**Comment by miigotu** [comment]
@Torhal there is a setting `create shows without show dir` that allows it to refresh shows that have no show dir if you have it enabled. None of this has changed for at least 5 years.

**Comment by Torhal** [comment]
@miigotu I actually have that setting checked, and have for as long as I can remember. It does, indeed, recreate the directory/folder during post-processing after a new episode has downloaded.

What hasn't been happening, though, is deleted episodes being converted to Archived in the episode listing. For example: I only have the latest episode for one of my shows and the Size in the top card says 2.39 GB (which matches what the size column in the episode list says). The episode listing shows the previous four episodes as Downloaded, though, instead of Archived.

If nothing has changed in five years, I'm going to go out on a limb here and guess that since I've been watching way more TV lately that I'm watching/deleting the episodes on the night they air - which causes Plex to delete the directory for the show itself - before the show update process runs; when it does so, the directory doesn't exist, so my shows' episode statuses aren't updating as they had previously. That would make my "This has only been happening lately" simultaneously true and anecdotal. :)

**Comment by JeeWee** [comment]
> 
> 
> `SHOWQUEUE-FORCE-UPDATE` is not where the status gets changed from downloaded to archived, it happens after that in `SHOWQUEUE-REFRESH` or `SHOWQUEUE-FORCE-REFRESH`
> 
> The logs you are sharing are not the full process for the show. It does the update, then QUEUES the refresh for awhile later.

Sorry, my brain was clearly not working at the moment.

- I have 54 shows, 53 are active, one is upcoming. None are paused
- I don't delete the show folders, only the episode files
- Under General Configuration > Misc the option "Choose hour to update shows" is set to 6
- Debug logs are enabled.

Last night I finished watching Nancy Drew (id: 363673). I've only deleted the 18 episodes. 
- The directory is still present as can be seen in the screenshot https://i.imgur.com/OiJjC9H.png ("Deze map is leeg."="This folder is empty".
- The show isn't paused in SickChill nor does it give an error on the folder: https://i.imgur.com/brjXcu5.png
- It's now 10:55 AM, several hours after the updates have run. The episodes still show as downloaded and home still display the show with several gigabytes of data: https://i.imgur.com/0r93Sm2.png
- I can't find an option 'SHOWQUEUE-REFRESH' in the filter pulldown menu in the logs. When I search for the show ID (363673) I only get 'SHOWQUEUE-FORCE-UPDATE' entries for level Debug. 
-If i search for 'SHOWQUEUE-REFRESH' the show isn't in the logs: https://pastebin.com/pgiu0x2R

I did a quick count: the refresh only shows 13 different ID's/Shows instead of the 54 I had expected

**Comment by miigotu** [comment]
You need to check the log file itself, not just from the UI.

**Comment by JeeWee** [comment]
> 
> 
> You need to check the log file itself, not just from the UI.

Same issue, not all shows are being refreshed. 
[sickchill.log](https://github.com/SickChill/SickChill/files/4657653/sickchill.log)

**Comment by miigotu** [comment]
@JeeWee thanks for a full log finally.
Pushing a fix

**Comment by JeeWee** [comment]
Awesome. Did a quick test and it works perfectly fine now. Thanks a bundel!
