### ISSUE TITLE
Not finding episodes for newly added show

### ISSUE THREAD

**Issue by dracupg** [SickChill/SickChill#6420]
![Screenshot from 2020-05-10 12-16-59](https://user-images.githubusercontent.com/11346330/81489403-448dc180-92b8-11ea-8e69-fac08bfee9e9.png)
### Before submitting your issue:

Branch: master
Commit: e9ccfe43f7515ddcacb872f3dc679694ad707481
Version: v2020.05.08-4
Database Version: 44.0
OS: Ubuntu 18.04.4
Browser: Firefox 76.0
What you did: Added new show Unorthodox a 4 part series aired on 26-Mar-20
What happened: Series added and episodes marked as wanted, but no episodes were found although there are episodes available on the NZB indexer. Also an error log entry saying "no absolute number on TVdb".
What you expected: Expected 4 episodes to be found and passed to my downloader
Logs:
```
![Screenshot from 2020-05-10 11-36-15](https://user-images.githubusercontent.com/11346330/81489000-db0bb400-92b3-11ea-8575-4c44539ee2fd.png)
![Screenshot from 2020-05-10 11-37-02](https://user-images.githubusercontent.com/11346330/81489001-dcd57780-92b3-11ea-8dfd-ec3c45804216.png)
![Screenshot from 2020-05-10 11-40-21](https://user-images.githubusercontent.com/11346330/81489002-dd6e0e00-92b3-11ea-84dd-1f06309024de.png)



PASTE LOGS HERE
```

**Comment by dracupg** [comment]
![Screenshot from 2020-05-10 11-36-15](https://user-images.githubusercontent.com/11346330/81489425-97677900-92b8-11ea-8b69-6921dd2d124d.png)

**Comment by dracupg** [comment]
![Screenshot from 2020-05-10 11-37-02](https://user-images.githubusercontent.com/11346330/81489439-bebe4600-92b8-11ea-9765-38b04893da3e.png)

**Comment by BenjV** [comment]
The problem is on Tvdb.
Their database record record is incomplete and is missing the absolute number for this serie.

@miigotu 
Maybe you could change the API call to use "airedSeason" and "airedEpisode" instead of "absoluteNumber".
This will always produce a correct record instead of an error for some series.

**Comment by miigotu** [comment]
We do use airedSeason and airedEpisode. The absolute number log line is a debug line.

It isn't finding it on your nzb indexer probably because they do not have the tvdbid marked in the database on the indexer for that show.

**Comment by dracupg** [comment]
Can you help me narrow this issue down further? Should I raise the issue with Nzbplanet and what info should I give them as the logs seem a little vague? Many thanks.

**Comment by miigotu** [comment]
Yes, you need to contact nzbplanet, give them the line your log shows for the api call
![image](https://user-images.githubusercontent.com/390379/81660208-7615a280-9408-11ea-9c86-4dc896059130.png)
(But the one for episode 1 that you know is there)
