### ISSUE TITLE
Updated Borked via GUI for ReadyNas 0S6 X86

### ISSUE THREAD

**Issue by r3dn1nja75** [SickChill/SickChill#6422]
Fails to update to e9ccfe4

I followed your method in #6230, which updates fine via that method to e9ccfe4 though still showing as 50a2b16 which was MHYNLO last release for RN OS6 X86 (I had to do a complete reinstall)

Update again to 'fix' this through the GUI just Borks it.. ..  I noticed app-config and gui cache goes for a wonder after the update to e9ccfe4, hence your script for it to manually update..

**Comment by miigotu** [comment]
https://github.com/SickChill/readynas-sickchill/releases/tag/0b79cc3
