### ISSUE TITLE
Which docker?

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#6428]
I have been using Linuxserver/Sickchill which allows SC to function for the most part, but is missing the ability to

 - figure out the running commit/version from within the UI
 - Check for updates
 - update from within the UI

If the Sickchill/Sickchill version does not have those limitations, I'd like to try it.  But I can't find online information as to how to set it up.

Any guidance?

**Comment by miigotu** [comment]
Both images work, but you shouldn't be updating with the built in updater.

You update the whole image, which is built every time I push.

```bash
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once sickchill
```

**Comment by miigotu** [comment]
Sickchill/sickchill will update from the UI (even though it shouldn't), and show commit version, but the permissions are handled differently so currently the linuxserver image is better imho.

**Comment by ronrosenfeld** [comment]
OK Thanks. I'll follow your advice and stick with linuxserver.  

It would be make things simpler if, when opening the sickchill UI, the program could check what version it is running, and give a pop-up if it is not the most recent. (Like it does on non-docker versions).

Of course, since (at least with linuxserver) the current version is not being written to config.ini, I imagine doing something like that would be non-trivial,  So it's just a passing thought -- nice to have, but certainly not essential.

**Comment by miigotu** [comment]
The issue is because linuxserver only checks out the current commit, with depth=1. Cant run git commands to check if there are updates because of that.

**Comment by heymoe** [comment]
If you want to be crazy, you could log into the linuxserver SC docker shell and ("docker exec -it <sc container name> /bin/bash" - replace "<sc container name>" with what you named yours), cd to /app rename the sickchill dir to something else (mv sickchill sickchill.org", do a normal git clone ("git clone https://github.com/SickChill/SickChill.git ./sickchill"), exit shell, stop SC docker container and start it back up.

When you do an update of SC via the SC interface, you need to stop and re-start the docker container. If you don't you might end up with SC trying to run twice. This method isn't recommend.

As @miigotu noted, with docker it's best if you just update the whole docker container when updates come out. You can use a tool called watchtower that will monitor docker containers and auto update them when there is an update for you.

**Comment by miigotu** [comment]
Updating inside a docker container works only until the container is restarted, because changes aren't persistent unless you docker commit.

**Comment by heymoe** [comment]
If you do a docker create to create a docker container (vs docker run), that container will be persistent between restarts until you delete it.

**Comment by ronrosenfeld** [comment]
@heymoe  LSIO recommends against using Watchtower (or anything) for automated updates

**Comment by heymoe** [comment]
@ronrosenfeld Huh.. Never saw anything saying that. I've been using watchtower to update one of LSIO's images for a while (not SC) and never had an issue with it doing auto updates. I get that in general auto updates could break things if an update rolls out that has a bug and the auto update process installs the bugged version before it's fixed but that could happen if you manually did the update before the bug was discovered and a fix pushed out too. Any ways, like most things, run at your own risk.

**Comment by miigotu** [comment]
The page for docker-sickchill specifically recommends watchtower.

If it fails, as soon as a fixed image is up just run watchtower again...
