### ISSUE TITLE
deluge and deluged can't add a torrent

### ISSUE THREAD

**Issue by nopoz** [SickChill/SickChill#6438]
Using latest commit 9f3b9e22b8d6e3d28351439f3da06c7fd83f4c68 deluge and deluged do not work when trying to add a torrent. 

using deluge:
```
18:33:35 WARNING::SEARCHQUEUE-MANUAL- :: Deluge: Unable to send Torrent
```

using deluged:
```
18:35:38 ERROR::SEARCHQUEUE-MANUAL- :: [9f3b9e2] DelugeD: Failed Sending Torrent
Traceback (most recent call last):
  File "/app/sickchill/sickbeard/clients/generic.py", line 268, in sendTORRENT
    r_code = self._add_torrent_file(result)
  File "/app/sickchill/sickbeard/clients/deluged.py", line 87, in _add_torrent_file
    remote_torrent = self.client.core.add_torrent_file(result.name + '.torrent', b64encode(result.content), self.make_options(result))
  File "/app/sickchill/lib/deluge_client/client.py", line 283, in __call__
    return self.caller(self.method, *args, **kwargs)
  File "/app/sickchill/lib/deluge_client/client.py", line 247, in call
    return self._receive_response(self.deluge_version, self.deluge_protocol_version)
  File "/app/sickchill/lib/deluge_client/client.py", line 226, in _receive_response
    raise exception(exception_msg)
AddTorrentError: Unable to add torrent to session: torrent already exists in session
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/torrentmanager.py", line 545, in add
    handle = self.session.add_torrent(add_torrent_params)
RuntimeError: torrent already exists in session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 483, in add_torrent_file
    filedump=filedump, options=options, filename=filename
  File "/usr/lib/python3/dist-packages/deluge/core/torrentmanager.py", line 550, in add
    raise AddTorrentError('Unable to add torrent to session: %s' % ex)
deluge.error.AddTorrentError: Unable to add torrent to session: torrent already exists in session
```

I rolled back to e9ccfe43f7515ddcacb872f3dc679694ad707481 and deluge option works as expected. I assume this issue occured due to the changes in 040d7d8c966680010eb45dcbc13b0996e06ba066 and 80aee2739462941c7bfbe5e4227132eea54ab9f9

Deluge version: 2.0.3-2-201906121747-ubuntu18.04.1

**Comment by chris41g** [comment]
can confirm, using deluge 1.3.15 on windows. same error on deluge web and deluged

**Comment by miigotu** [comment]
"torrent already exists in session"... is it in the client with the same torrent hash?

**Comment by Mercono** [comment]
> "torrent already exists in session"... is it in the client with the same torrent hash?

Can't speak for others, but the torrent isn't showing in the client for me

**Comment by nopoz** [comment]
> 
> 
> "torrent already exists in session"... is it in the client with the same torrent hash?

The torrent hash didn't already exist in the client. Rolling back to the older commit and re-trying the same torrent, it was added successfully - no deluge client changes necessary.

**Comment by FGOD1983** [comment]
having the same issue on Ubuntu between sickchill and deluge. Torrent isn't showing up and testing the connection gives me ```[Errno 404] Not Found```. Tried restarting both sickchill and Deluge but with no success

**Comment by miigotu** [comment]
Strange, this is working for me here using linuxserver/deluge

**Comment by PaulW** [comment]
I've started to get this now too, I manually cleared the `state/torrents.fastresume` file as there was a reference in there which seemed to not exist in the `state/torrents.state` file (unsure why) but now when trying to add a torrent, I'm seeing the following within the deluge-daemon logs:

```[INFO    ] 10:09:49 rpcserver:206 Deluge Client connection made from: 127.0.0.1:58990
[ERROR   ] 10:09:49 core:253 There was an error adding the torrent file somethingsomething.torrent
[ERROR   ] 10:09:49 core:254 object of type 'int' has no len()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/core/core.py", line 251, in add_torrent_file
    torrent_id = self.torrentmanager.add(filedump=filedump, options=options, filename=filename)
  File "/usr/lib/python2.7/dist-packages/deluge/core/torrentmanager.py", line 491, in add
    torrent = Torrent(handle, options, state, filename, magnet)
  File "/usr/lib/python2.7/dist-packages/deluge/core/torrent.py", line 198, in __init__
    self.set_options(self.options)
  File "/usr/lib/python2.7/dist-packages/deluge/core/torrent.py", line 234, in set_options
    OPTIONS_FUNCS[key](value)
  File "/usr/lib/python2.7/dist-packages/deluge/core/torrent.py", line 312, in set_file_priorities
    file_priorities and len(file_priorities) == len(self.get_files())):
TypeError: object of type 'int' has no len()```

**Comment by cyphher** [comment]
Same issue here (Linux raspberrypi 4.19.114-v7l+ #1303 + deluge 1.3.15)
Reverted back to an older version an no more problems.

**Comment by FGOD1983** [comment]
@cyphher how did you revert and to which version? because then at least it is downloading the series automaticly again

**Comment by cyphher** [comment]
> 
> 
> @cyphher how did you revert and to which version? because then at least it is downloading the series automaticly again
- Stopped the sickchill service
I have an old version backuped from 20200413.
- Moved the current version to /opt/sickchill.20200515.
- Copied the /opt/sickchill.20200413 to /opt/sickchill
- Copied the //opt/sickchill.20200515/config.ini and /opt/sickchill.20200515/sickbeard.db to /opt sickchill so that config and database are still up-to-date
-Started sickchill service and all was fine again.
Though I'm 135 commits behind now, but I'll sit this one out untill the cause is known or a fix is available.

**Comment by FGOD1983** [comment]
hmmm I don't have a backup, but there must be a way to revert through git right? (never had to do this, so never looked into it). 

Although I noticed that the last couple of days my deluge was finally picking up on the label rules and moving my downloaded files to the correct folder so sickchill could pick this up. (probably also a change from the last couple days in sickchill?)

**Comment by miigotu** [comment]
If you go to config/search and disable the option `set downloads of recently aired episodes to high priority` does it work again?

**Comment by miigotu** [comment]
Ping me here if that doesnt fix it

**Comment by cyphher** [comment]
> 
> 
> Ping me here if that doesnt fix it

Didn't work. Updated to the last commit, changed the setting in search. Sickchill still isn't able to connect to deluge
![deluge error](https://user-images.githubusercontent.com/44112500/82048524-23144780-96b5-11ea-8f12-31340f17d234.PNG)

**Comment by FGOD1983** [comment]
it did download the series for me at 3pm. but the test connection is still giving a connection error.

**Comment by cyphher** [comment]
> 
> 
> it did download the series for me at 3pm. but the test connection is still giving a connection error.

You're wright, although the connection test is giving an error Sickhill did snatch an epidode and Deluge is downloading.

**Comment by FGOD1983** [comment]
so basicly the only problem left is the test connection button that fails although sickchill seems to be able to connect to Deluge

**Comment by Mercono** [comment]
Same experience as you guys. I followed the suggestion by miigotu, and it downloads as expected now. [Errno 404] Not Found when using the "Test Connection" button though.

**Comment by miigotu** [comment]
What does your connection url look like?

**Comment by Mercono** [comment]
> What does your connection url look like?

For me it's 

http://10.10.0.2:8112/

**Comment by FGOD1983** [comment]
For me it was the same format as @Mercono but even changing it to the DNS I use to access Deluge (instead of the IP) still gives me the same problem on test

**Comment by miigotu** [comment]
I didn't change the way deluge logs in, only deluged.

I will try mine logging in over webapi shortly.

**Comment by FGOD1983** [comment]
well, my Deluge is a Ubuntu install of Deluge-web/deluged, so could be that this is the reason it still is giving errors. But then again, I always had it set up as Deluge and not Deluged

**Comment by miigotu** [comment]
I got it fixed, pushing soon as i fix a few other things too

**Comment by FGOD1983** [comment]
now i can't even open the search options :/

```
Mako Error
A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

File /opt/sickchill/sickbeard/clients/deluge.py:40, in __init__:
if not host.startswith('http'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by miigotu** [comment]
Fixing now

**Comment by miigotu** [comment]
pushed

**Comment by miigotu** [comment]
When people revert immediately without helping me debug the issue and testing the fixes, it just takes me longer to fix it...

**Comment by FGOD1983** [comment]
`Success: Connected and Authenticated` :)

**Comment by FGOD1983** [comment]
thx for fixing it this fast :) seems it is now working again like it should :)

**Comment by Mercono** [comment]
> When people revert immediately without helping me debug the issue and testing the fixes, it just takes me longer to fix it...

Agreed, reverting is a bandaid anyway, not a real solution.

Everything is working as expected now. Thanks for the quick fix.

**Comment by cyphher** [comment]
> 
> 
> When people revert immediately without helping me debug the issue and testing the fixes, it just takes me longer to fix it...

Agreed, that's hy I keep several versions and backups so I can toggle around for testing. Thanx for the fixes! Have a nice weekend.
