### ISSUE TITLE
Show Airdates are now fuzzy

### ISSUE THREAD

**Issue by thargan81** [SickChill/SickChill#6440]
Branch/Commit: master/515676fb6
OS: Debian
Browser: Firefox
What you did: Went to the displayShow for any show in library
What happened: Airdates are now listed using the fuzzy option rather than the absolute date
What you expected: Shows to be listed in the absolute format.
Logs:
```
Even with debug enabled, there are no log entries generated when moving between show list pages.
```
This happened today, after one of the updates committed in the past 24 hours. 

SC had a full restart as part of attempting to resolve this, along with turning on fuzzy dates and then turning them back off again to ensure that it wasn't something odd with the option being inverted.

**Comment by mikemor22** [comment]
Branch: master
Commit: 515676fb69b3036c58425425d3471a8abb68b3ff
Version: v2020.05.15-3
Database Version: 44.1
OS: Windows Windows-10-10.0.18362 
Browser: Firefox 76.0.1 (64-bit)

I too am seeing fuzzy values in any date on lists (show list last / next ep, individual show airdates,  history list) despite having the setting disabled.  Have restarted SC, as well as turning fuzzy dates settings on and off.

The schedule is in banner format and shows proper dates - it won't actually change to a list view though, so I don't know if that view has a similar problem to other lists.

**Comment by vkbo** [comment]
The settings for fuzzy date as well as fanart on the show pages are now both being ignored. I have both features disabled, but they're both there anyway.

**Comment by miigotu** [comment]
I'll take a look later. Probably a mistake in the mass changes I made.

**Comment by miigotu** [comment]
> Edit: I received 12 commits today from the pull, and it happened within those.

In this case that doesn't help much because each of those commits is hundreds of changes each haha
