### ISSUE TITLE
SC never fetches any REPACK

### ISSUE THREAD

**Issue by loungebob** [SickChill/SickChill#6442]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / f9161da71a75dbabf83fd862bc4e46a0b4391352 
OS: Win10
Browser: FF
What you did: normal stuff
What happened: REPACK not downloaded
What you expected: REPACKs to be downloaded
Logs:
```
PASTE LOGS HERE
```
Sorry, dont quite know how to put it above. I only realize that REPACK episodes are not fetched by SC now that whole season packs come out (since the seasons finales aired) and I verify against what SC downloaded. Not a single REPACK of the last 10 shows I checked had been downloaded by SC.
I dont know how to/or what to run now to see in the logs what the issue is since those REPACK eps have been out for weeks/months.

The settings in SC are correct I suppose. Replace is ticked, every 4 hours and backlog search is at 14 days.

I checked my sources and most of the REPACKS are listed as released within max 24 hours. So that should be covered.

What do I do manually to figure out where this goes wrong?

**Comment by miigotu** [comment]
Repack is gotten during proper search

**Comment by miigotu** [comment]
Do those shows happen to be paused?

**Comment by loungebob** [comment]
No. They're downloaded normally and are not paused. E.g. "How to get away with murder" just finished the normal download for the last ep and the Full Season Pack (with the repacks) came in just a few hours later. The Season Pack contains 4 REPACKS that never got downloaded by my SC instance.

That happend to at least  10 shows I checked the last couple of days. None of them hat the REPACK downloaded and replaced.

If I trigger one of the HTGAWM that have a REPACK now manually (set it to wanted) it would most certainly download the REPACK. That way I cant figure out why the REPACKs dont get downloaded.

Any other idea how to find out whats wrong?

**Comment by miigotu** [comment]
Do you have proper search enabled?
![image](https://user-images.githubusercontent.com/390379/82089616-f0248080-96c1-11ea-9496-8393b75711ea.png)

**Comment by loungebob** [comment]
Yes it's ticked. Even unticked and ticked and saved it about a week ago.

**Comment by miigotu** [comment]
Then it might be whichever provider you are using. Some cannot do proper searches.

**Comment by loungebob** [comment]
This is a special search? I thought it's a normal query looking for the word REPACK or PROPER in the release name...

I mostly use rarbg for current tv releases.

**Comment by miigotu** [comment]
well its technically amost identical to a backlog `string` search. If the provider only works with daily search (rss, latest, etc) it is unlikely to pick up propers.
We have 3 searches, daily, backlog, and proper. Proper just happens to do the same thing as a backlog search with the added words to the search string.
