### ISSUE TITLE
INFO WEBSERVER-HOME :: Request failed: [Errno 404] Not Found ()

### ISSUE THREAD

**Issue by PixLzzz** [SickChill/SickChill#6443]
Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

What you did: Nothing (same config as before)
What happened: as episodes were snatched but not downloaded via transmission, i  tried to "test connection" on transmission and got "[Errno 404] Not Found". I have exactly the same parameters on couchpotato and the test works perfectly. Is that coming from sickchill ? 

Logs:
```
2020-05-15 22:55:15 INFO WEBSERVER-HOME :: Request failed: [Errno 404] Not Found ()
```
![image](https://user-images.githubusercontent.com/36031553/82095512-6eebde80-96ff-11ea-8658-ded775fb91c0.png)

**Comment by miigotu** [comment]
working on it now, idk why other providers were effected

**Comment by mbravorus** [comment]
Having exactly the same problem on both master and develop docker images.

Error in the log looks like: `Request failed: [Errno 404] Not Found (<class 'str'>)

in the latest stable Firefox

**Comment by jagauthier** [comment]
I just put SickChill in a docker and I'm getting this error when testing the connection to transmissions as well.

**Comment by cionz0** [comment]
same here

2022-03-07 20:41:17 INFO :: WEBSERVER-HOME_0 :: Request failed: [Errno 404] Not Found (HTTPError)

I've recently updated to MacOS Monterey, don't know whether it matters.

**Comment by miigotu** [comment]
Use the IP of the transmission container, likely the library doesn't understand named routes.

**Comment by jagauthier** [comment]
Docker containers can potentially have a different IP address every time they start.

Docker is excellent at name resolution. However, you must first create a network and then assign all your containers to that network. Their respective names will be available among all the containers in that network. 100% of the time, works perfectly.

Using containers by IP is a recipe for disaster.

**Comment by miigotu** [comment]
> Docker containers can potentially have a different IP address every time they start.
> 
> Docker is excellent at name resolution. However, you must first create a network and then assign all your containers to that network. Their respective names will be available among all the containers in that network. 100% of the time, works perfectly.
> 
> Using containers by IP is a recipe for disaster.

"potentially", you should be setting the IP when you create the container or when you write the docker-compose. Beyond that, it is likely which network_mode you select that will determine if SC and transmission are on the same host or even the same network. I would suggest using something like transmission-ovpn and then attaching sickchill to the network it creates. 

```
network_mode: "container:[container name/id]"
```
Or
```
network_mode: "service:[service name]"
```

You would then make sure you set things like container_name, host_name, etc on both containers and possibly use the "links" configuration.

Point being there are a hundred ways to make the connection with multiple docker containers, and sickchill has no control over how you do that as it is outside our scope and control.

**Comment by miigotu** [comment]
And no, using IP is not a recipe for disaster. We aren't scaling to hundreds of nodes with SC. I'd be surprised if anyone has more than like 10-15 machines in the same compose stack. If they do, they should split that up to what needs to talk to each other.

**Comment by jagauthier** [comment]
Well, docker handles naming perfectly. So that and not worry about IPs. My sick chill just references the host name and it works flawlessly.  In a world of IPs it is nice to not have to worry about them.

**Comment by miigotu** [comment]
> Well, docker handles naming perfectly. So that and not worry about IPs. My sick chill just references the host name and it works flawlessly. In a world of IPs it is nice to not have to worry about them.

> I just put SickChill in a docker and I'm getting this error when testing the connection to transmissions as well.


Which is it? Put them in the same network and network mode, or use links, or use IPs. What is there to argue about?

**Comment by jagauthier** [comment]
The only one here who appears to be arguing is you.
