### ISSUE TITLE
SC not retrieving TheTVDB favorites

### ISSUE THREAD

**Issue by bobvmierlo** [SickChill/SickChill#6446]
Branch: master
Commit: 0e9751432b43aa5f9bcb066c2bb976098e9f157b
Version: v2020.05.17-1
Database Version: 44.1
Browser: Chrome 81.0.4044.138
What you did: Try to retrieve TheTVDB favorites using my username and the 'Unique User Key' from the dashboard.
What happened: No results (only the default "Six feat under")
What you expected: To see my TheTVDB favorites
Logs:
```
SC does not seem to log anything regarding this funtionality, not even in debug mode.
```

**Comment by angeloschat** [comment]
same here. Is it an issue or is not fully implemented yet?

**Comment by miigotu** [comment]
It is buggy, set the right user and key and restart SC. Something with requests caching in the library.
