### ISSUE TITLE
SC Update on Readynas faulty

### ISSUE THREAD

**Issue by christiaanw1** [SickChill/SickChill#6448]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 146 behind
OS: 6.10.3 readynas
Browser:
What you did: Tried to update
What happened: SC shuts down but doesn't start up again
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
So enable the package so it auto starts...

**Comment by christiaanw1** [comment]
Auto start is enabled and also show enabled on the Nas Apps page. When I try to open the page it does not connect. Tested with 2 different ready Nas devices.

**Comment by miigotu** [comment]
Im not sure which readynas package you are even using, there are multiple.

**Comment by christiaanw1** [comment]
![2020-05-23_14h00_33](https://user-images.githubusercontent.com/52601131/82730151-f2a85b00-9cfd-11ea-959f-a22c1f3146ae.png)

**Comment by miigotu** [comment]
#6230

**Comment by christiaanw1** [comment]
Thank you for the link. This is the errors I get by following the ReadyNas Scripts.




Kind Regard/Vriendlike Groete Christiaan Willemse
 

    On Saturday, 23 May 2020, 20:12:09 SAST, miigotu <notifications@github.com> wrote:  
 
 


#6230
