### ISSUE TITLE
 Snatching but not changing status or sending notification

### ISSUE THREAD

**Issue by adambra** [SickChill/SickChill#6450]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 
Branch: master
Commit: 0e9751432b43aa5f9bcb066c2bb976098e9f157b
OS: Windows 10
Browser: Chrome
What you did:
Snatch an episode via daily searcher or forced manual.
What happened:
When a show snatches torrent downloads as expected but status won't change. It then keeps snatching and adding more torrents to the black hole each search. Forcing a manual search does the same thing. Snatched but does not register a snatch (no notification, no change in episode status, no log under History). 
What you expected: 
Episode status should change to snatched, be logged under History and send notification.
Checked logs and this started happening after update on 10 May
`2020-05-11 00:14:52 INFO CHECKVERSION :: New update found for SickChill, starting auto-updater `...
Logs:
```
AA AttributeError: 'unicode' object has no attribute 'hasattr'
AA elif self.input.hasattr("read"):
AA File "C:\SickChill\SickChill\lib\rtorrent9\lib\torrentparser.py", line 138, in __init__
AA NewTorrentParser(file_name)
AA File "C:\SickChill\SickChill\sickchill\providers\torrent\TorrentProvider.py", line 134, in _verify_download
AA if self._verify_download(downloaded_filename):
AA File "C:\SickChill\SickChill\sickchill\providers\GenericProvider.py", line 128, in download_result
AA newResult = resProvider.download_result(result)
AA File "C:\SickChill\SickChill\sickbeard\search.py", line 58, in _downloadResult
AA dlResult = _downloadResult(result)
AA File "C:\SickChill\SickChill\sickbeard\search.py", line 135, in snatchEpisode
AA self.success = search.snatchEpisode(searchResult[0])
AA File "C:\SickChill\SickChill\sickbeard\search_queue.py", line 186, in run
2020-05-18 21:40:11 INFO SEARCHQUEUE-MANUAL- :: Downloading a result from TorrentLeech at https://www.torrentleech.org/download/_torrent_name_here_.torrent
2020-05-18 21:40:11 INFO SEARCHQUEUE-MANUAL- :: Downloading /_torrent_name_here_ from TorrentLeech
```

**Comment by wallowinthemire** [comment]
was JUST going to post my own issue about this same problem. I also can't manually change any 
episode statuses, don't know if you're seeing that problem as well.
