### ISSUE TITLE
phantom show entry?

### ISSUE THREAD

**Issue by OneCDOnly** [SickChill/SickChill#6451]
Hello,

using SickChill from GitHub source on a Debian 10.4 server and accessed via FireFox 73.0.1 on a Debian 10.4 workstation. 

```
Branch: master
Commit: 95dba6e0b3329852909bd361b4f8abac366e15d3
Version: v2020.05.19-1
Database Version: 44.1
```

Just noticed a phantom TV show entry in my list. Hovering the mouse over it doesn't show a name, but it appears as the last item in a name sort. It isn't listed in any of the drop-down show lists. 

![](https://i.imgur.com/tyhiWFK.png)

It is also ignoring my column layout. 

I'm unable to select it. :(

Any thoughts?

**Comment by miigotu** [comment]
Corrupt database

**Comment by OneCDOnly** [comment]
Ah, so how should I fix it?

**Comment by OneCDOnly** [comment]
update: the problem seems to have fixed itself. :confused: 

So I checked the SickChill logs - there's nothing there to indicate a problem was found or fixed. Oh well. 

Thank you. :grin:

**Comment by miigotu** [comment]
Probably was a show in the process of being added?

**Comment by OneCDOnly** [comment]
Nope. I only occasionally add a new show, and I always wait to check that it adds correctly. 

I also don't use any automation for show adding. 

Hopefully, it was just a once-off glitch. :grin:
