### ISSUE TITLE
IPT unable to find torrents

### ISSUE THREAD

**Issue by Senate9690** [SickChill/SickChill#6457]
### INFO
Python Version: **2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]**
Operating System: **Linux-4.15.0-101-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@95dba6e0b3329852909bd361b4f8abac366e15d3
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [IPTorrents] :: [95dba6e] Request failed: Unable to parse Cloudflare anti-bots page: Error trying to solve Cloudflare IUAM Javascript, they may have changed their technique. (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

_Originally posted by @Senate9690 in https://github.com/SickChill/SickChill/issues/6317#issuecomment-631479541_

**Comment by miigotu** [comment]
Not fixable unless we can get a new cloudscraper. Please use search next time.

**Comment by Senate9690** [comment]
I searched and found #6372 which appeared to be unrelated... that is to my limited knowledge. 

> @icepicknz You need to be using python 2.7.9+ (but less than python3) to use cloudscraper. Please fix your log line endings next time x.X

Using 2.7.17 of python.

Would VeNoMouS's bypass work?

**Comment by miigotu** [comment]
We already use everything available, venemous library does not pass cloudflare on ipt currently.
