### ISSUE TITLE
Discord notifications no longer contain relevant information

### ISSUE THREAD

**Issue by jacobcooper** [SickChill/SickChill#6464]
As a byproduct of moving to queues to fix #6444, https://github.com/SickChill/SickChill/commit/f74aea2efcf3509c71da40d4a6d43259026e8b47 has changed the author and title of Discord notifications to "SickChill"

Desktop/Push Notifications from the Desktop and iOS Discord apps only display the author and title of an incoming discord notification. They don't display the [now queued] fields ("Notification": $message), which makes the notifications less useful (see screenshots). Additionally, the author and title are now both set to SickChill which is redundant.

I propose that we make the title more meaningful. I would open a PR but wanted to start the discussion here. Cheers!

Before:
![Screen Shot 2020-05-22 at 12 06 45 AM](https://user-images.githubusercontent.com/6813027/82641998-0e0e4b80-9bc2-11ea-9667-45e361e2cd3c.png)

After:
![Screen Shot 2020-05-22 at 12 07 12 AM](https://user-images.githubusercontent.com/6813027/82642062-2bdbb080-9bc2-11ea-8d29-271823c7ed8b.png)

![IMG_7739](https://user-images.githubusercontent.com/6813027/82642072-3138fb00-9bc2-11ea-93e2-0b8ef0fd9eb3.jpg)

![Annotation 2020-05-22 001817](https://user-images.githubusercontent.com/6813027/82641950-fe8f0280-9bc1-11ea-88f8-49489be5072b.png)

**Comment by miigotu** [comment]
I'm all for you opening a PR, because I personally could care less about discord notifications lol. Just be aware that different fields have different character limits, so you cant add multiple notifications into the title field.

**Comment by miigotu** [comment]
Heck, if you can just tell me a good format for the messages that will work, I can probably work with that.
