### ISSUE TITLE
Addic7ed pluging broken

### ISSUE THREAD

**Issue by aarnaud** [SickChill/SickChill#6467]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: https://github.com/SickChill/SickChill/blame/82c9f0b0ca8ecabee8565c9e8bc72d87a44524f7/lib/subliminal/providers/addic7ed.py#L234 by @miigotu 
OS: Ubuntu 18.04
Browser: Mozilla firefox
What you did: update sickchill
What happened: Addic7ed pluging is missing
What you expected: Addic7ed still working
Logs: not logs because catch by something. 

```
  File "lib/subliminal/providers/addic7ed.py", line 234
    r = self.session.get(self.server_url + 'show/%d' % show_id, params={'season': season}, timeout=10)
    ^
```

**Comment by miigotu** [comment]
That isn't the whole error...
