### ISSUE TITLE
file rename not changing episode name inside of .NFO

### ISSUE THREAD

**Issue by Teamshake** [SickChill/SickChill#6468]
On a rename, it used to just rename the main video I think.  I'm not sure about the TBN, but I know  the NFO did not get renamed.  It made you do a re-scan then it would make a new NFO.  now it is renaming the NFO, but it keeps the same info inside of the NFO.  Is there a way to make it so during a file rename, it also updates the episode name inside of the NFO?  Of just have it go back to the old way where doesn't rename the NFO file?  This way you don't have to go through the folders to find the NFO to delete or edit it.

thanks

**Comment by miigotu** [comment]
The episode name doesnt change just because you did a rename. Am i missing something here?

**Comment by Teamshake** [comment]
sometimes on the tvdb, the episode name will be a place holder like "episode 11".  these are normally fixed after air.  if you go back and do a rename, to update it with the correct info after the file is already present, it changes the file names for the video file, screen shot, and NFO.  it only renames the nfo file so the old episode title is still inside of the nfo file.
it used to only rename the video file and if you did a re-scan, it would make a new nfo with the updated info.  this happened semi recently, but i'm not sure what exact version it was.

**Comment by miigotu** [comment]
When the show update is done, that is when the name in the nfo is updated.

**Comment by Teamshake** [comment]
I had tried a force full update but it did not update the nfo files.  No big deal, i will just go into the folder and delete them like i have been doing.  thanks.

**Comment by miigotu** [comment]
Seems only the show nfo is updated, i'll try and find a way to update episode nfos.
BTW, you know that nfo files are almost never needed anymore right?

**Comment by Teamshake** [comment]
thanks.  i know kodi and probably others get the info, but i like to keep the info local as some things don't match up to the tvbd.
