### ISSUE TITLE
Update Fails

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6470]
SickChill Info: Branch: master
Commit: 82c9f0b0ca8ecabee8565c9e8bc72d87a44524f7
Database Version: 44.1
  Python Version:
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
  SSL Version: OpenSSL 1.0.2t 10 Sep 2019
  OS: Windows-7-6.1.7601-SP1
  Locale: en_US.cp1252

What you did: click update
What happened: update process started then failed
What you expected: that it would update
Logs:
```
08:10:44 INFO::WEBSERVER-HOME :: Config backup successful, updating...
08:10:45 INFO::WEBSERVER-HOME :: Creating update folder C:\SickChill\sr-update before extracting
08:10:45 INFO::WEBSERVER-HOME :: Downloading update from http://github.com/SickChill/SickChill/tarball/master
08:10:52 INFO::WEBSERVER-HOME :: Extracting file C:\SickChill\sr-update\sr-update.tar
08:11:12 INFO::WEBSERVER-HOME :: Deleting file C:\SickChill\sr-update\sr-update.tar
08:11:12 INFO::WEBSERVER-HOME :: Moving files from C:\SickChill\sr-update\SickChill-SickChill-2d23c10 to C:\SickChill
08:11:12 ERROR::WEBSERVER-HOME :: [82c9f0b] Error while trying to update: error 32 : The process cannot access the file because it is being used by another process
Traceback (most recent call last):
  File "C:\SickChill\sickbeard\versionChecker.py", line 865, in update
    ek(os.remove, new_path)
  File "C:\SickChill\sickchill\helper\encoding.py", line 44, in ek
    result = function(*args, **kwargs)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\SickChill\\gui\\slick\\css\\style.css'
```

This has been failing for the last month...
It always fails in the same folder but different files,

**Comment by nydave69** [comment]
Also I tried the suggestions in the FAQ, none worked..
I used to be able to delete the sr-update  folder and try again, but that hasn't worked in a long time.

**Comment by miigotu** [comment]
Check permissions of that file/folder...

**Comment by burtal** [comment]
i have this warrning when sickchill starts or hit the check updates option 

Unable to contact github, can't check for update


2020-05-25 17:13:50 DEBUG    WEBSERVER-HOME :: check_for_new_news: Checking GitHub for latest news.
2020-05-25 17:13:50 INFO     WEBSERVER-HOME :: No update needed
2020-05-25 17:13:50 WARNING  WEBSERVER-HOME :: Unable to contact github, can't check for update
2020-05-25 17:13:50 DEBUG    WEBSERVER-HOME :: Executing git fetch origin --prune with your shell in /app/sickchill
2020-05-25 17:13:50 DEBUG    WEBSERVER-HOME :: Executing git config remote.origin.url https://github.com/SickChill/SickChill with your shell in /app/sickchill
2020-05-25 17:13:50 DEBUG    WEBSERVER-HOME :: git rev-parse HEAD : returned successful
2020-05-25 17:13:50 DEBUG    WEBSERVER-HOME :: Executing git rev-parse HEAD with your shell in /app/sickchill
2020-05-25 17:13:50 DEBUG    WEBSERVER-HOME :: Executing git symbolic-ref -q HEAD with your shell in /app/sickchill
2020-05-25 17:13:50 INFO     WEBSERVER-HOME :: Checking for updates using GIT

**Comment by nydave69** [comment]
Checked the permissions and they are as the root sickchill

10:46:45 INFO::WEBSERVER-HOME :: Config backup in progress...
10:48:16 INFO::WEBSERVER-HOME :: Config backup successful, updating...
10:48:17 INFO::WEBSERVER-HOME :: Creating update folder C:\SickChill\sr-update before extracting
10:48:17 INFO::WEBSERVER-HOME :: Downloading update from http://github.com/SickChill/SickChill/tarball/master
10:48:22 INFO::WEBSERVER-HOME :: Extracting file C:\SickChill\sr-update\sr-update.tar
10:48:48 INFO::WEBSERVER-HOME :: Deleting file C:\SickChill\sr-update\sr-update.tar
10:48:48 INFO::WEBSERVER-HOME :: Moving files from C:\SickChill\sr-update\SickChill-SickChill-f9e54fd to C:\SickChill
10:48:49 ERROR::WEBSERVER-HOME :: [82c9f0b] Error while trying to update: error 32 : The process cannot access the file because it is being used by another process
Traceback (most recent call last):
  File "C:\SickChill\sickbeard\versionChecker.py", line 865, in update
    ek(os.remove, new_path)
  File "C:\SickChill\sickchill\helper\encoding.py", line 44, in ek
    result = function(*args, **kwargs)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\SickChill\\gui\\slick\\css\\style.css'

**Comment by miigotu** [comment]
On Windows it shouldn't be doing a source update. Use the installer.

**Comment by nydave69** [comment]
> 
> 
> On Windows it shouldn't be doing a source update. Use the installer.

I'm not...  just click the update on the browser page.

Anyway...   
I did some trouble shooting and found that the process that has the file open is SickChill

what I did whether right or wrong is;
stopped SickChill
copied the extracted update to the folders over writing existing files..
restarted SickChill
got the update banner again, click update
update ran clean this time..
all looks good

will wait and see what happens with the next update..

**Comment by miigotu** [comment]
You need to back up, uninstall, and reinstall using the installer. SC has two different methods to do updates. Either using git or using a source zip. Apparently it isn't using git on yours, and it should always be using git on Windows.

**Comment by burtal** [comment]
@miigotu  so if i update via synology docker  i will no longer be able to update via check updates option?

**Comment by miigotu** [comment]
@burtal Synology, and docker, are totally different than windows.

For docker you use linuxserver/docker-sickchill and cannot update using the UI because they only checkout the latest commit. You use watchtower to update the image like it says in their readme.

**Comment by burtal** [comment]
@miigotu  update  via UI worked till last couple of builds on syno docker ... i was getting the notification that i am behind commits and update worked. 
Is true that last 2 updates i made them by puuling the docker image from linuxserver and that is the time when i started to get the "Unable to contact github, can't check for update"  error
