### ISSUE TITLE
Deluge - doesnt download to correct directory

### ISSUE THREAD

**Issue by Raiu** [SickChill/SickChill#6474]
SickChill: Master v2020.05.26-2 in official docker container
Deluge version: 1.3.15 in a docker container

SickChill doesnt set the correct download directory when using Deluge.
The problem started when i updated sickchill 14days ago, before that i had no issues.
Directory that should be used is _/media/torrent/pvr_ , but for some reason when a torrent is added, the directory is instead deluge's default directory, _/media/torrent/downloads_ .
SickChill and Deluge has the same directory structure

I have tested these steps:

- Update SickChill 
- Update SickChill docker container and pull fresh image from :latest
- Test both Deluge Daemon and Web interface
- Manually add torrent in deluge with the path, successfully.
- Deleted all files in _states_ directory and restarted sickchill

Settings page:
![sickchill_search_settings](https://user-images.githubusercontent.com/1299835/83061516-6c717900-a05d-11ea-898f-a22d0d9b70eb.PNG)

**Comment by Raiu** [comment]
With some further testing, it seems like sickchill set deluges "Incomplete" directory to the "Downloaded files location" directory and just leaves the "Complete" to the default.

Maybe there has been an update to Sickchills Deluge client and that has caused some issues with my version of deluge server.

**Comment by Raiu** [comment]
The bug is only partly fixed.

Now if you dont set the "Incomplete directory" in SickChill and you want it to default to Deluges set directory, it will instead use the "Download" directory for the "Incomplete" location.

**Comment by miigotu** [comment]
882758f0a88be7a48228e25e95c506fad926335a should fix it
