### ISSUE TITLE
Method to query API remotely

### ISSUE THREAD

**Issue by gaetan-petit** [SickChill/SickChill#6475]
Hi, I'd like to build a cross platform application using React Native.

Because of how CORS are configured in SickChill I'm unable to make queries to the API. Jsonp is not an option in native application. Setting a proxy is a bit out of the scope for this kind of use case.

From #3466 I understand that forbidding CORS was done for security reasons. Is there any chance this behavior could be changed for the API routes?

**Comment by miigotu** [comment]
You can make API calls all you want. Cors doesn't stop that. Also, if you were making an app that works for your own SC install, they would be on the same host. So nope.

**Comment by gaetan-petit** [comment]
Well @miigotu if you think of an mobile application you definitely won't be on the same host (also you have to live on the same port and scheme).

What's the reason for blocking external requests anyway? You have to provide your API token or the request is rejected. I can't think of many API that are limited to localhost consumption.

Maybe it could exists as a configuration in SickChill if you really don't want to expose API by default. What do you think?

**Comment by miigotu** [comment]
We don't block external requests. There are apps that use the api, even a few mobile applications such as showsRage (which needs renamed and updated).

Cors doesn't prevent someone from using the API, it prevents SICKCHILL from hitting something external.

**Comment by gaetan-petit** [comment]
Hi @miigotu maybe I'm wrong but you said yourself that you have to be on the same host to perform querie to the api, then the opposite.

Look from this console, I'm trying to use the browrer Fetch API from another port of the same host.

![cors2](https://user-images.githubusercontent.com/851486/83283084-e713d300-a1da-11ea-88fc-f0ebf050e733.png)

You can see that the request get denied (of course it works from the same address and port).

In the meantime I found that native app don't mind CORS, but I won't be able to make a web version and the debuging is a PITA.

**Comment by miigotu** [comment]
Done. Please share the source code of the app you are making, I don't want to be opening up our free software for people to make profits from.

**Comment by gaetan-petit** [comment]
Thanks @miigotu, I'll check this ASAP.

As for my application I'm not working on a commercial project and even if it will become one I would release the source under free licence.
Anyway Sickchill project licence is GPLv3 and I have no intension to violate it's terms.
