### ISSUE TITLE
[APP SUBMITTED]: API Key Required

### ISSUE THREAD

**Issue by bwguy** [SickChill/SickChill#6480]
### INFO
Python Version: **2.7.14 (default, Mar 03 2018, 11:05:58) [GCC 7.3.0]**
Operating System: **Linux-4.14.24-qnap-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@9d460f97f2c3ac8f6d075ea33267f1de6bb959db
Link to Log: https://gist.github.com/e4300d4bbe51630c198626306395abbd
### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [9d460f9] Unable to get info from theTVDB, the show info will not be refreshed: API Key Required
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by nydave69** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.2.20
No Log available with ERRORS:
### ERROR
```
Unable to get info from theTVDB, the show info will not be refreshed: API Key Required
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
