### ISSUE TITLE
Shows Disappearing from Shows List - Errno 1101 there was an error creating the show

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#6481]
In the last day I have noticed shows dropping off my shows list, I went from 912 shows to 887.
Looking in the logs each missing show has Errno 1101
I have checked the files still exist, I have tried to add the shows again but they are not detected as new shows and was only able to re-add one show by renaming the folder so it could be detected again. 

Branch: master
Commit: f9e54fd4521a32963ca23458617f29be1a85ccfb
Database Version: 44.1
OS: Windows 10 64bit
Browser: Firefox
What you did: Opened the shows list
What happened: Fewer shows appeared
What you expected: To see all previously added shows

Logs:
```
2020-05-28 02:17:56 MAIN :: [f9e54fd] There was an error creating the show in D:\TV\She and Her Cat -Everything Flows-: Error HTTPSConnectionPool(host='v2.sg.media-imdb.com', port=443): Max retries exceeded with url: /suggests/s/She_and_Her_Cat_Everything_Flows.json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
```

**Comment by miigotu** [comment]
https://v2.sg.media-imdb.com/suggests/s/She_and_Her_Cat_Everything_Flows.json

Make sure you can access the url. It isnt deleting the show from your DB, it just cant load your show from the db because you dont have the imdb info for it.

**Comment by miigotu** [comment]
Pushing a fix to prevent imdb from lstopping a show from loading.

**Comment by rutskiuk** [comment]
Thank you, the link is accessible (it probably wasn't at the time). 
I appreciate the quick fix!
