### ISSUE TITLE
Corrupt nfo causes show refresh to fail to complete

### ISSUE THREAD

**Issue by Peanut-Afl** [SickChill/SickChill#6484]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/d2c60105671645c41cb27e1909254370d1ebd839
OS: Win 10 (1909)
Browser: Firefox 76.0.1
What you did: Added a show I already had on disk
What happened: The show never updated. It is showing that I have only one episode (The very first one) and no others.
What you expected: I expected it to show that I have all the episodes on disk.
Logs:
```
22:16:28 DEBUG::WEBSERVER-HOME :: Queueing show refresh for The Big Bang Theory
22:16:30 INFO::SHOWQUEUE-REFRESH :: Performing refresh on The Big Bang Theory
22:16:30 DEBUG::SHOWQUEUE-REFRESH :: 80379: Loading all episodes from the show directory E:\Series\The Big Bang Theory
22:16:30 DEBUG::SHOWQUEUE-REFRESH :: 80379: Creating episode from S01E01 - Pilot - SDTV.avi
22:16:30 DEBUG::SHOWQUEUE-REFRESH :: 80379: Creating episode object from E:\Series\The Big Bang Theory\Season 01\S01E01 - Pilot - SDTV.avi
22:16:30 DEBUG::SHOWQUEUE-REFRESH :: Using cached parse result for: E:\Series\The Big Bang Theory\Season 01\S01E01 - Pilot - SDTV.avi
22:16:30 DEBUG::SHOWQUEUE-REFRESH :: 80379: E:\Series\The Big Bang Theory\Season 01\S01E01 - Pilot - SDTV.avi parsed to The Big Bang Theory S01E01
22:16:30 DEBUG::SHOWQUEUE-REFRESH :: Setter sets location to E:\Series\The Big Bang Theory\Season 01\S01E01 - Pilot - SDTV.avi
22:16:30 DEBUG::SHOWQUEUE-REFRESH :: Checking if E:\Series\The Big Bang Theory\Season 01\.meta\S01E01 - Pilot - SDTV.avi.txt exists: True
22:16:30 DEBUG::SHOWQUEUE-REFRESH :: Checking if E:\Series\The Big Bang Theory\Season 01\S01E01 - Pilot - SDTV.xml exists: True
22:16:30 DEBUG::SHOWQUEUE-REFRESH :: Checking if E:\Series\The Big Bang Theory\Season 01\S01E01 - Pilot - SDTV.jpg exists: True
22:16:30 DEBUG::SHOWQUEUE-REFRESH :: Checking if E:\Series\The Big Bang Theory\Season 01\.meta\S01E01 - Pilot - SDTV.avi.txt exists: True
22:16:30 DEBUG::SHOWQUEUE-REFRESH :: Checking if E:\Series\The Big Bang Theory\Season 01\.meta\S01E01 - Pilot - SDTV.avi.txt exists: True
22:16:31 DEBUG::SHOWQUEUE-REFRESH :: Parsed E:\Series\The Big Bang Theory\Season 01\S01E01 - Pilot - SDTV into S01E01 [ABD: False] [ANIME: False] [whichReg: [u'standard', u'season_only']]
22:16:31 DEBUG::SHOWQUEUE-REFRESH :: formatting pattern: %SN - S%0SE%0E - %EN -> The Big Bang Theory - S01E01 - Pilot
22:16:31 DEBUG::SHOWQUEUE-REFRESH :: Metadata provider TIVO updating episode indexer info metadata file for The Big Bang Theory - S01E01 - Pilot
Exception in thread SHOWQUEUE-REFRESH:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\SickRage\sickbeard\show_queue.py", line 558, in run
    self.show.refreshDir()
  File "C:\SickRage\sickbeard\tv.py", line 1015, in refreshDir
    self.loadEpisodesFromDir()
  File "C:\SickRage\sickbeard\tv.py", line 445, in loadEpisodesFromDir
    curEpisode = self.makeEpFromFile(media_file)
  File "C:\SickRage\sickbeard\tv.py", line 718, in makeEpFromFile
    rootEp.createMetaFiles()
  File "C:\SickRage\sickbeard\tv.py", line 1770, in createMetaFiles
    self.createNFO()
  File "C:\SickRage\sickbeard\tv.py", line 1782, in createNFO
    result = cur_provider.update_episode_metadata(self) or result
  File "C:\SickRage\sickbeard\metadata\generic.py", line 318, in update_episode_metadata
    episodeXML = etree.ElementTree(file=xmlFileObj)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 611, in __init__
    self.parse(file)
  File "<string>", line 38, in parse
ParseError: syntax error: line 1, column 0

22:16:46 DEBUG::WEBSERVER-HOME :: Executing git config remote.origin.url https://github.com/SickChill/SickChill.git with your shell in C:\SickRage
22:16:46 DEBUG::WEBSERVER-HOME :: git config remote.origin.url https://github.com/SickChill/SickChill.git : returned successful
22:16:46 DEBUG::WEBSERVER-HOME :: Executing git symbolic-ref -q HEAD with your shell in C:\SickRage
22:16:46 DEBUG::WEBSERVER-HOME :: git symbolic-ref -q HEAD : returned successful
22:16:46 DEBUG::WEBSERVER-HOME :: Executing git ls-remote --heads origin with your shell in C:\SickRage
22:16:48 DEBUG::WEBSERVER-HOME :: git ls-remote --heads origin : returned successful
```

**Comment by miigotu** [comment]
Looks like it errors when creating the show nfo/xml, and the process of adding the show is stopped because that thread dies.

I'll add some exception handling around it in a bit so we can try to see why it errors.

You can disable nfo/xml creating and it will succeed in the meantime.

**Comment by miigotu** [comment]
Actually, your existing nfo file for that episode is corrupt. Can you paste the contents of it here? I don't have a computer right now so I'll try to help as best I can.

**Comment by Peanut-Afl** [comment]
Below is the xml file for S01E01

<?xml version='1.0' encoding='utf-8'?>
<details>
  <movie isExtra="false" isSet="false" isTV="true">
    <title>Pilot</title>
    <season>1</season>
    <episode>1</episode>
    <year>2007</year>
    <plot>A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.</plot>
    <episodeplot>Brilliant physicist roommates Leonard and Sheldon meet their new neighbor Penny, who begins showing them that as much as they know about science, they know little about actual living.</episodeplot>
    <mpaa>TV-14</mpaa>
    <rating>77</rating>
    <credits>|Bill Prady|Chuck Lorre|</credits>
    <cast>
      <actor>Brian Patrick Wade</actor>
      <actor>Vernee Watson-Johnson</actor>
    </cast>
  </movie>
</details>

Below is the metadata for the TIVO. (file is a .txt file)

title : The Big Bang Theory
seriesTitle : The Big Bang Theory
episodeTitle : 1x01 Pilot
episodeNumber : 1
isEpisode : true
description : Brilliant physicist roommates Leonard and Sheldon meet their new neighbor Penny, who begins showing them that as much as they know about science, they know little about actual living.
seriesId : EP00931182
callsign : CBS
originalAirDate : 2007-09-24T00:00:00Z
vActor : Jim Parsons
vActor : Johnny Galecki
vActor : Kaley Cuoco
vActor : Kunal Nayyar
vActor : Simon Helberg
vActor : Melissa Rauch
vActor : Mayim Bialik
vActor : Laura Spencer
vActor : Sara Gilbert
vActor : Kevin Sussman
vActor : John Ross Bowie
vActor : Carol Ann Susi
starRating : 3.0
tvRating : TV-14
vProgramGenre : Comedy

**Comment by miigotu** [comment]
I see, for some reason it is trying to update a TiVo file as an nfo.

Temporarily disabling the TiVo metadata will allow your show to refresh for now.
