### ISSUE TITLE
[APP SUBMITTED]: SEARCHQUEUE-MANUAL-340959 :: [ilCorsaroNero] :: [d2c6010] Could not find table of torrents

### ISSUE THREAD

**Issue by djtazie** [SickChill/SickChill#6485]
### INFO
Python Version: **2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]**
Operating System: **Linux-4.19.97-v7l+-armv7l-with-debian-10.3**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@d2c60105671645c41cb27e1909254370d1ebd839
Link to Log: https://gist.github.com/e95f888e2de9a67e1aa9205066bb8a03
### ERROR
```
SEARCHQUEUE-MANUAL-340959 :: [ilCorsaroNero] :: [d2c6010] Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
There is a site issue with ilcorsaronero right now, search isn't working on the site only latest/rss
