### ISSUE TITLE
Subtitles downloader not working

### ISSUE THREAD

**Issue by waltermaldonado** [SickChill/SickChill#6498]
SickChill will not download subtitles

Branch/Commit: Latest
OS: Windows
Browser: Chrome
What you did: Tried to download subtitles
What happened: No subtitle dowloaded
What you expected: My subtitles downloaded
Logs:
```
AA ValueError: Path does not exist
AA raise ValueError('Path does not exist')
AA File "C:\SickChill\SickChill\lib\subliminal\core.py", line 362, in scan_video
AA video = subliminal.scan_video(video_path)
AA File "C:\SickChill\SickChill\sickbeard\subtitles.py", line 350, in get_video
```

**Comment by miigotu** [comment]
The video has to be there for it to scan it...

**Comment by waltermaldonado** [comment]
It happens for a downloaded video file that already is in place (post-processed and inside the right folder) when I click to manually dowload subtitle. Actually, SickChill is not downloading any subtitile...

**Comment by miigotu** [comment]
What is the path to the video?
