### ISSUE TITLE
Mako Error after update

### ISSUE THREAD

**Issue by jotapejota** [SickChill/SickChill#6500]
Hi, I know nothing about programm, 
So, I was trying to update the sickchill  two days ago and unfortunately have had some problem that I don´t know to fix.

I´m using raspberry pi 3 and Kodi.

Thank you so much

Mako Error
A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

```
PASTE LOGS HERE
```
File/storage/.kodi/addons/service.downloadmanager.SickPotatoHead/resources/SickBeard/gui/slick/views/inc_home_showList.mako:352, in render_body:

![error_sickchill](https://user-images.githubusercontent.com/66326175/83578403-15f8b480-a50d-11ea-8c3a-dd490a927614.jpg)

**Comment by miigotu** [comment]
I can't check if there is a problem right now, hoping I have a working pc soon.

**Comment by jotapejota** [comment]
> I can't check if there is a problem right now, hoping I have a working pc soon.

I can´t do nothing. I can´t access my shows, my shows list...

**Comment by jotapejota** [comment]
I'll install again because I didn't understand anything. This problem occurred after an update
