### ISSUE TITLE
Cant enable https with letsencrypt certs

### ISSUE THREAD

**Issue by alexsalex** [SickChill/SickChill#6501]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/Commit: d21a4fceaa4933e4d8ebc71cd0238d181988aebe 
OS: Ubuntu 18.04
Browser: Firefox
What you did: install letsencrypt and sickchill
What happened: 
What you expected: enabled https
Logs:
```
2020-06-03 08:16:13 MAIN :: pyopenssl module missing, please install for https access
2020-06-03 08:16:13 MAIN :: Disabled HTTPS because of missing CERT and KEY files


2020-06-03 08:16:13 INFO     CHECKVERSION :: Checking for updates using GIT
2020-06-03 08:16:13 INFO     WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2020-06-03 08:16:13 WARNING  MAIN :: Disabled HTTPS because of missing CERT and KEY files
2020-06-03 08:16:13 INFO     MAIN :: Unable to create CERT/KEY files, disabling HTTPS
2020-06-03 08:16:13 WARNING  MAIN :: pyopenssl module missing, please install for https access
2020-06-03 08:16:13 INFO     MAIN :: Starting SickChill [master] using '/opt/SickChillServer/config.ini'
```

**Comment by miigotu** [comment]
`2020-06-03 08:16:13 MAIN :: pyopenssl module missing, please install for https access`

**Comment by alexsalex** [comment]
This module installed fo python 2 and 3

**Comment by miigotu** [comment]
@alexsalex try this from the cli:
python2 -c "from OpenSSL import crypto, __version__; print(__version__)"

**Comment by alexsalex** [comment]
```
root@p:~# python2 -c "from OpenSSL import crypto, __version__; print(__version__)"
0.14
root@p:~# cd /opt/SickChillServer/
root@p:/opt/SickChillServer# python2 -c "from certgen import createKeyPair, createCertRequest, createCertificate, TYPE_RSA"
root@p:/opt/SickChillServer#
```

**Comment by miigotu** [comment]
```
    try:
        # noinspection PyUnresolvedReferences
        from OpenSSL import crypto
        from certgen import createKeyPair, createCertRequest, createCertificate, TYPE_RSA
    except Exception:
        logger.log(_("pyopenssl module missing, please install for https access"), logger.WARNING)
        return False
```

If you are using a virtual environment you need to install it in the virtual environment. Looks like your install isn't using the regular python2 install or you would have gotten an error with those commands.

**Comment by alexsalex** [comment]
Use physical machine, no VM.
`root@p:/opt/SickChillServer# ps aux | grep Sick
user      31920  4.2  3.3 1385320 267864 ?      Sl   08:16  40:01 /usr/bin/python2.7 /opt/SickChillServer/SickBeard.py -q --daemon --nolaunch --datadir=/opt/SickChillServer`

**Comment by miigotu** [comment]
Maybe you have old dirs in your SC install. Change to the dir and do `git clean -dfq lib`

**Comment by alexsalex** [comment]
Same:
`2020-06-04 01:20:48 MAIN :: pyopenssl module missing, please install for https access
                        2020-06-04 01:20:48 MAIN :: Disabled HTTPS because of missing CERT and KEY files`

**Comment by miigotu** [comment]
I'll add some logging around it and see what is happening.

**Comment by miigotu** [comment]
Is the cert inside the SC dir? you need to make a link to the letsencrypt cert and key inside the SC dir and use that path for the cert and key

**Comment by miigotu** [comment]
Don't ask why it is this way, lol, it should be allowed to use an external key directly

**Comment by alexsalex** [comment]
```
user@p:/opt/SickChillServer$ ll | grep ".key\|.cert"
-rw-rw-rw-   1 veo  users    2740 Jun  4 01:18 certgen.py
-rw-r--r--   1 root root     3075 Jun  3 21:48 certgen.pyc
lrwxrwxrwx   1 root root       48 Jun  3 08:05 fullchain.cert -> /etc/letsencrypt/live/p.dazab.club/fullchain.pem
lrwxrwxrwx   1 root root       46 Jun  3 08:04 privkey.key -> /etc/letsencrypt/live/p.dazab.club/privkey.pem
user@p:/opt/SickChillServer$ ll /etc/letsencrypt/live/dom/privkey.pem
lrwxrwxrwx 1 root root 39 Jun  3 00:02 /etc/letsencrypt/live/dom/privkey.pem -> ../../archive/dom/privkey1.pem
user@p:/opt/SickChillServer$ ll /etc/letsencrypt/live/dom/privkey.pem
lrwxrwxrwx 1 root root 39 Jun  3 00:02 /etc/letsencrypt/live/dom/privkey.pem -> ../../archive/dom/privkey1.pem
user@p:/opt/SickChillServer$ ll /etc/letsencrypt/archive/dom/privkey1.pem
-rw-r----- 1 root veo 1704 Jun  3 00:02 /etc/letsencrypt/archive/dom/privkey1.pem
user@p:/opt/SickChillServer$
```

**Comment by miigotu** [comment]
With it in the SC for, you just put the relative path, in your case just the filename in SC settings.

**Comment by miigotu** [comment]
Let me know if this doesn't solve your issue and I will re-open this and make some code changes.

**Comment by alexsalex** [comment]
Like I sad before... it’s not working.

**Comment by miigotu** [comment]
Just put "fullchain.cert" and "privkey.pem" in SC settings, no path. SC concats the directory, so your path needs to be relative to the SC dir.

**Comment by alexsalex** [comment]
Again, if you read correctly my post #15 I already try it. Got the same error.

**Comment by miigotu** [comment]
Maybe it's that it's a link to a link?

Try copying `/etc/letsencrypt/archive/dom/privkey1.pem`
And 
`/etc/letsencrypt/archive/dom/fullchain.pem`
Directly in the SC folder

I will do some tests with it in the next few days also.

**Comment by miigotu** [comment]
I just created cert and key with minica, created a soft link from the created cert and key into SC source dir, set them in the gui, enabled https, and restart SC. Works.

There is something in your process you arent doing right.

**Comment by gonijn** [comment]
@alexsalex Put the CERT and KEY in the ...var/ directory, 0777 them, point to the CRT and KEY with only their filenames, no path. Somehow after an SC update the path changed. After moving the files to var (instead of ...var/SickBeard/) https worked fine for me.
