### ISSUE TITLE
Unable to remove the cache/mako directory!

### ISSUE THREAD

**Issue by Tonkapug** [SickChill/SickChill#6502]
Receiving a continuous stream of the below in Sickchill log. I'm running SickChill on a Raspberry Pi.

2020-05-29 09:14:40 WARNING  MAIN :: Unable to remove the cache/mako directory!
2020-05-29 09:14:40 INFO     WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2020-05-29 09:14:40 INFO     WEBSERVER :: Could not start webserver on port 8081: already in use!
2020-05-29 09:15:05 INFO     MAIN :: Starting SickChill [master] using '/opt/sickrage/config.ini'

Also, I get this shown when trying to access the GUI. A reboot fixes it for a short while

"Looks like we do not have enough disk space to render the page! {error}"

I've searched and found a couple of similar posts with this issue. The comments said to enable permissions for the cache directory for that user. So, I navigated to /opt/sickrage and chmod 755 cache but it doesn't appear to have sorted it. My Linux skills are minimal. I have been using this setup for years now with very few issues. Now all of a sudden the permissions are incorrect. Something must have changed in an update I'd assume.

Sorry, I don't have a debug log as I am currently out of the country and noticed this when logging in.

SickChill info:
Branch: master
Commit: d21a4fceaa4933e4d8ebc71cd0238d181988aebe
Version: v2020.05.30-1
Database Version: 44.1

I would appreciate some guidance.

Thanks

**Comment by miigotu** [comment]
`Could not start webserver on port 8081: already in use!`
Looks like you have the service set to auto-restart, and it restarts before it can remove the gui/slick/cache/mako dir

**Comment by Tonkapug** [comment]
Thanks for the quick response. I just dug this up from the install guide I used a few years back. At that time it was Sickrage and not SickChill. Below are the sickrage default file and the startup script. I'm thinking i possibly need to increase the sleep 2? Maybe? lol. As I said, my knowledge is pretty basic.

https://www.htpcguides.com/install-sickrage-raspberry-pi-usenet-torrent-tv/

nano /etc/default/sickrage

SR_USER=pi
SR_HOME=/opt/sickrage
SR_DATA=/opt/sickrage
SR_PIDFILE=/home/pi/.sickrage.pid

nano /etc/init.d/sickrage

[Script.txt](https://github.com/SickChill/SickChill/files/4726000/Script.txt)

Thanks for your assistance

**Comment by miigotu** [comment]
Yes maybe, try sleep 5. I'm sure there are better scripts around =P

**Comment by Tonkapug** [comment]
Thanks...I will give it a try. I'm always open to something 'better' ;) lol. I do need to upgrade this setup in the near future. It's been on my list of things to do. Any decent guides you recommend for the Raspberry Pi?

**Comment by miigotu** [comment]
Raspberry pi is no different than any other Linux install using sysvinit
