### ISSUE TITLE
Can not update SickChill

### ISSUE THREAD

**Issue by PhilJen153** [SickChill/SickChill#6504]
Hi,

I have a NAS Asustor, which hosts SickChill.
I have a very old version of SickChill, but I can not figure out how to update it.
You will find every necessary information below.
Thanks for your help.

Branch: master
Commit: 1ed315660d99f6673a3bb53363fdff6902b89429
Version: v2019.06.28-1
Database Version: 44.0

OS: Linux-4.14.x-x86_64-with-glibc2.2.5 
Browser: Firefox (last version)
What you did: Nothing in fact...The automatic updates stopped one day, and I did not pay attention. 
What happened: SickChill did not update itself automatically. It worked well until this version. Nothing new since this one...
What you expected: What can I do to activate automatic updates again ?
Logs:
```
2020-06-04 02:49:06 CHECKVERSION :: git fetch origin --prune returned : (128) fatal: unable to access 'https://github.com/SickChill/SickChill.git/': Couldn't resolve host 'github.com'
2020-06-04 02:49:06 CHECKVERSION :: Unable to contact github, can't check for update
```

**Comment by miigotu** [comment]
Well first, it needs to be able to access GitHub.com from the device and it cannot. Second, the remote url for that git repo has a trailing slash that doesn't belong there.

**Comment by PhilJen153** [comment]
Thanks for your help @miigotu 

For the first part, is there a way to check if SickChill can access github.com ?
For information, SickChill can get tv shows information (search tvdb, get thumbnails, ...), so I think it can access pages through internet. Maybe there is something special with connection to github.com ?

For the second part, I tried to update the remote URL in "General->Advanced parameters", filling the field "Git executable path" with this value : https://github.com/SickChill/SickChill.git
But when I try to update SickChill manually, i get this message : 
"Can not find git executable. Stop SickChill and add git_path ton config.ini or delete your .git directory and execute from sources to update".
(Sorry for the approximative translation, my SickChill version is in French language)

I don't know if I did the right actions to fix my problem.
If not, could you please explain how I can check SickChill can access github.com, and how I can modify the git repo URL ?

Sorry for my "newby" questions, I am not really familiar with advanced parameters in SickChill, or in looking for configuration information on Linux system.

Thanks again for your help.

**Comment by miigotu** [comment]
No, remove that git path, that is for when the git executable is not in the path.

Now cd to

**Comment by miigotu** [comment]
That is the preferred way to fix things when they stop worrking ;) good work.
