### ISSUE TITLE
SC inseting tvshow-trailer.mp4 as an episode

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6513]
Just found another show where the show trailer located in the show folder
has been inserted as an episode over writing an existing show.
It just changes the entry in the database, the actually show is still in the episode folder
this time it's season one episode 13 of "13 Reasons Why" that has it the trailer.
![13 reasons why trailer season 1 episode 13](https://user-images.githubusercontent.com/14140816/83981917-4915bc00-a8f0-11ea-835d-8885041ebb82.JPG)

found it earlier in Avenue 5 season 1 episode 5...
![avenue 5 trailer in season 1](https://user-images.githubusercontent.com/14140816/83981883-fd631280-a8ef-11ea-9060-7001a90a1d3a.JPG)

Tried a rescan but that had no effect.
Any suggestions
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
You will need to to a forced full update to fix after you update. I think it will be fixed now.
