### ISSUE TITLE
Search with special characters !': in the title but not on indexers + search modifiers

### ISSUE THREAD

**Issue by ShrekIsLoveLife** [SickChill/SickChill#6514]
**Branch/Commit:** Latest
**OS:** Linux
**Browser:** N/A
**What you did:** Add show _"RuPaul's Drag Race All Stars: Untucked!"_ and have it search NZB indexes for it 
**What happened:** Nothing found
**What you expected:** Results found
**Notes:**
If you search the indexes without special characters "RuPauls Drag Race All Stars Untucked" instead of "RuPaul's Drag Race All Stars: Untucked!" they will return results.
Even adding a scene exception title will not find it as it's just adding information instead of replacing the title.
Generally ! is an "exclude this" search modifier and quotes ' " are exact match operators, they should be stripped
The : generally isn't hurting, but why keep special characters when they are generally not included in file names.
There are many other search modifiers like _ - | << ! ' " ^ $ * ()
**Fixes:**
Search with the special characters information stripped if the search with them fail
Allow complete name replace for search instead of appending the search so we can manually fix outliers, like kei$ha junk

**Comment by miigotu** [comment]
A scene exception does work, it will search with the original title, and then search with the scene exception. It will match results that match the scene exception also. Just make sure it is a show exception and not a season exception.
