### ISSUE TITLE
is-alive callback returns 400 Bad Request

### ISSUE THREAD

**Issue by egrueda** [SickChill/SickChill#6523]
When I restart sickchill from web gui, manually of after an update, it waits with the "Waiting for SickChill to start again: " forever

I can see it's sending POST requests to:
`http://ip-of-my-sickchill:8081/home/is-alive/?callback=jQuery224032145131241444744_1521685641890`
It returns "`400Bad Request`" even when the servers has restarted and is accesible.
Tested in two different installations, same result.

It's not a real problem cause you can F5, but anyway there's something wrong.
Best regards.

**Comment by miigotu** [comment]
This is already fixed, not sure if it is in master yet.
