### ISSUE TITLE
Cannot select new show from TheTVDB list

### ISSUE THREAD

**Issue by mesa57** [SickChill/SickChill#6525]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Latest
OS: Arm/Linux
Browser:Firefox
What you did:Add new show
What happened:Show is not on list
What you expected:Show should be on the returned list
Logs:
2020-06-11 18:32:26 DEBUG    WEBSERVER-ADDSHOWS :: Searching for Show with searchterm(s): ['Curon'] on Indexer: theTVDB

```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Put the tvdbid in the search box: 361739
