### ISSUE TITLE
[APP SUBMITTED]: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues."

### ISSUE THREAD

**Issue by LaurentDes** [SickChill/SickChill#6529]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
Link to Log: https://gist.github.com/82fb62074be4d2eb257ce28360b5af2b
### ERROR
```
SEARCHQUEUE-BACKLOG-353412 :: [Torrent9] :: [020e762] Request failed: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LaurentDes** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
Link to Log: https://gist.github.com/c32e5a163602c837e08f7eee0f39bc0e
### ERROR
```
SEARCHQUEUE-BACKLOG-353412 :: [Torrentz] :: [020e762] Request failed: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LaurentDes** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
Link to Log: https://gist.github.com/f0a77e31ae550c8a826078fe3e7621af
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [Torrentz] :: [020e762] Request failed: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LaurentDes** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
Link to Log: https://gist.github.com/a6294221482c0957a2e1c5ad60df079f
### ERROR
```
SEARCHQUEUE-BACKLOG-351958 :: [Torrentz] :: [020e762] Request failed: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LaurentDes** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
Link to Log: https://gist.github.com/33145a1575d325320efe355f2f7f48e2
### ERROR
```
SEARCHQUEUE-BACKLOG-361585 :: [Torrentz] :: [020e762] Request failed: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LaurentDes** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
Link to Log: https://gist.github.com/7c9d2eb5d916d09cb88702a24165a7e3
### ERROR
```
SEARCHQUEUE-BACKLOG-351291 :: [Torrentz] :: [020e762] Request failed: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LaurentDes** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
Link to Log: https://gist.github.com/9f9597d589285a28c0a3586ede515ed6
### ERROR
```
SEARCHQUEUE-BACKLOG-338936 :: [Torrentz] :: [020e762] Request failed: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LaurentDes** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
Link to Log: https://gist.github.com/16e087361a0c05e7973f334b4ee675b0
### ERROR
```
SEARCHQUEUE-BACKLOG-305288 :: [Torrentz] :: [020e762] Request failed: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LaurentDes** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
Link to Log: https://gist.github.com/5fa5dd087a7f87c79e7fb848bc48b985
### ERROR
```
SEARCHQUEUE-BACKLOG-260449 :: [Torrentz] :: [020e762] Request failed: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LaurentDes** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
Link to Log: https://gist.github.com/ad5a5f9c41d47cdda2fe0498ae40511a
### ERROR
```
SEARCHQUEUE-BACKLOG-73762 :: [Torrentz] :: [020e762] Request failed: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LaurentDes** [comment]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@020e76222c851074fe22b76ada95d31697091a91
Link to Log: https://gist.github.com/417de53c6d7e7b78b5d25a06d08e2728
### ERROR
```
SEARCHQUEUE-BACKLOG-295685 :: [Torrentz] :: [020e762] Request failed: Unable to parse Cloudflare anti-bots page: 'NoneType' object has no attribute 'group' Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues." (<type 'str'>)
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
![2018](https://user-images.githubusercontent.com/390379/84583738-052c2680-adca-11ea-86d3-e2fa6122905b.png)

**Comment by miigotu** [comment]
Update, you are using code from 2018
