### ISSUE TITLE
Sickchill incorrectly reports exposed to internet while running in docker

### ISSUE THREAD

**Issue by utdrmac** [SickChill/SickChill#6533]
Branch/Commit: Digest: sha256:2840c40984f51df922763e917579141a65189cc799d1332c30827fcb94673857
OS: Docker/Ubuntu 18
Browser: n/a
What you did: tried to load sickchill GUI
What happened: Said my install was exposed to internet
What you expected: To be able to access my sickchill from the same network I'm already on.

My sickchill is located at 10.10.10.203 and my laptop IP is 10.10.10.75. See screenshot. Yet, sickchill seems to think that somehow, my setup is accessible from the public internet. I guarantee it is not. How do I get around this? The error message does not tell you what to do other than "edit the config". Edit it how? What setting do I need to change to disable this "feature"?

![image](https://user-images.githubusercontent.com/4413670/84613426-c5784400-ae88-11ea-8509-00c93beebf54.png)

**Comment by miigotu** [comment]
#6531 6531
