### ISSUE TITLE
Sickchill for Docker wrong volume?

### ISSUE THREAD

**Issue by Ventje23** [SickChill/SickChill#6536]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Hi, I tried to setup Sickchill in a Docker container and I thank that mayby there is a typo in the setup description, which says:
volumes:
      - /path/to/data:/config
      - /path/to/data:/downloads
      - /path/to/data:/tv

But when I check the settings of Sickchill after the setup (Help & Info):

  User:root
  Program Folder:/app/sickchill
  Config File:/data/config.ini
  Database File:/data/sickbeard.db
  Cache Folder:/app/sickchill/gui/slick/cache
  Log Folder:/data/Logs

So it seems to me that "/path/to/data:/config" must be:

"/path/to/data:/data"

If I do that then the settings are persistent while updating the docker-image.

**Comment by miigotu** [comment]
Where are you seeing this description?

![image](https://user-images.githubusercontent.com/390379/84691767-ad4d0700-af12-11ea-9776-6f560f7d0ad5.png)

**Comment by Ventje23** [comment]
hi miigotu,

shoot! I'm so sorry but it looks like things got mixed up on my side. Looks like I mixed up settings of the linuxserver/sickchill image with the sickchill/sickchill image. Probaly because I was looking for settings and on the hub.docker.com for sickchill/sickchill where there's no description.
I am aiming on using the sickchill/sickchill image.

**Question though...**
DownloadPath:/DownloadPath: the first DowlloadPath is the (users) path to where downloads are stored? Same for ShowPath?
And both /DownloadPath and /ShowPath just as is in the Docker image?

FYI: I am trying this on a Synology using the Synology Docker app (not the CLI).

**Comment by miigotu** [comment]
The show path you can create as whatever you want inside/outside the image. You just need to be able to set the path inside SC for your show root and your downloads/postprocessor location.

Honestly, I'm personally currently using the linuxserver version, and I do 2 commands to fix updates:
```bash
docker exec -it sickchill /bin/bash 'cd /app/sickchill && git checkout master && chown -R $PUID:$PGID /app/sickchill'
docker restart sickchill
```

**Comment by miigotu** [comment]
Closing this. If you have more questions you can still ask right here in this issue even though it is closed.
