### ISSUE TITLE
Request failed: Detected the new Cloudflare challenge. ()

### ISSUE THREAD

**Issue by quickdry** [SickChill/SickChill#6539]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/95dba6e0b3329852909bd361b4f8abac366e15d3 
OS: Windows Server 2012
Browser: N/A
What you did: any torrent search
What happened:
What you expected:
Logs:
```
2020-06-16 17:56:51 FINDPROPERS :: [Torrent9] :: [95dba6e] Request failed: Detected the new Cloudflare challenge. ()
                        2020-06-16 17:51:34 SEARCHQUEUE-BACKLOG-75382 :: [Torrent9] :: [95dba6e] Request failed: Detected the new Cloudflare challenge. ()
```

Received about 206 of these errors today, so far I'm only getting it on this provider, not sure if these sorts of errors increase the urgency for a Python 3 switch so we can use the newer OpenSSL versions.

**Comment by miigotu** [comment]
@quickdry the best way right now is to use docker on windows, because for some reason they never updated the openssl for python2.7 on windows.
