### ISSUE TITLE
Post processed shows won’t be processed by PLEX

### ISSUE THREAD

**Issue by philippebezoteaux** [SickChill/SickChill#6544]
Hi,

Been using sickchill for months and it is from far the best service I run on my Synology.
For about 10 days now, my post processed shows won’t be detected by Plex as it used to whereas they are detected fine when adding them manually into their folder (created by Sickchill).

Any clues on what is happening ?

Thanks a lot for your help and keep up the great job !

**Comment by burtal** [comment]
i noticed that also .... lastest couple of episodes are not displayed in plex although they are in the proper folder 
i verified R/W permi PER FILE and the new ones that were downloaded  and they were different from the rest .... 
The admin user had rights to the new files at that was all ....the old ones had admin, users, everyone 

old files permisions  
![image](https://user-images.githubusercontent.com/65765790/85050854-69226680-b19f-11ea-846e-27db279fd73d.png)

The new files have only admin rights if give the rights to plex or everyone, the episode will appear in plex

So: the download and post processing works ....but the permissions are messed up 

@miigotu  
i made the change from linuxserver docker to your docker by this steps. 
1. make a backup from sickchill
2. export docker settings 
3. edit the json with the new image name 
4.start running your docker 
5. import what i backed up 

Can this affect the rights perimissons ?

**Comment by philippebezoteaux** [comment]
Just to complete my post, I’m using the Sickchill package version for DSM 6.

**Comment by BenjV** [comment]
Permissions are never inherited.

Files and folders get their permissions from the folder they are created in when the postprocessor move them to that folder.
In case of Synology you have to make sure that folder is given read/write access for the group "**sc-download**".

If you already have existing folders and/or files in that folder then changing the permissions for that top folder does not change the existing subfolders and files so you have to expliciete give them read/write permission (can be done with FileStation).

**Comment by philippebezoteaux** [comment]
So my point remains...
Permissions are set correctly for both Plex and SickChill and been working perfectly for the last 24 months and works while manually moving files.

As Burtal mentioned, the issue only comes up while using SickChill to post process files and these do not get any permissions at all.

**Comment by BenjV** [comment]
I installed plex to see what is does and is does not follow the normal rules of Synology so the group settings do not work.
Instead it runs the plex media server as the user 'plex'
So the folder you choose in the SickChill in the postprocessings tab (e.g. Post Processing Dir) has to be created with read/write privileges for the user "plex".

This has to be created and given this privileges before any postprocessings in SickChill starts.
If already for example a season folder is created then it won't work because at the moment of creating a folder it inherite the privileges from the parent folder.

**Comment by philippebezoteaux** [comment]
Plex is working differently but the issue remains on SickChill side, how come that moved files won’t get the permissions from the folder their moved in as you mentioned earlier ?
My Marvel Agents of Shield example is the perfect example of permissions getting messed up while SickChill moves a file.

My SYNOLOGY share is set with correct permissions (including Plex) which means that when Sickchill creates folders for TV Shows or seasons, these should get the same permissions as the share folder, then files should get their permissions from the season folder. This should all work nicely as it has been working for the last few years.

**Comment by BenjV** [comment]
Over here it still is working ok.

**Comment by miigotu** [comment]
There is a method in SC synonotifier or something like that, which tells Synology fs that we have added a file and it is supposed to put the proper permissions afaik. Maybe our call to that is no longer correct.

**Comment by philippebezoteaux** [comment]
@miigotu I believe that something is no longer working as usual... just moved to Medusa which is working just fine as Sickchill used to while post processing files.

**Comment by miigotu** [comment]
Actually I just looked. That is for the synoindex script.

Here is where we make the folders for episodes:
https://github.com/SickChill/SickChill/blob/b6fe632f4de93df057e04f2773dfc007574c8f0f/sickbeard/postProcessor.py#L1145

Inside that method, we chmod as the parent folder:
https://github.com/SickChill/SickChill/blob/3484b32552b388617d53101b6ebdce3b0a1c76f5/sickbeard/helpers.py#L458
https://github.com/SickChill/SickChill/blob/3484b32552b388617d53101b6ebdce3b0a1c76f5/sickbeard/helpers.py#L493

If SC does not own the parent folder, or have rwx permissions on that folder, it cannot change the mode of the folder.

**Comment by pnsbttl** [comment]
Hi everyone,
I have the same issue, all new files have only admin permission, blocking Plex to see them in library.
Reading your comments, I'm not sure to understand how to solve situation.
Is somebody would explain how to solve this permission situation once for good?
Thank you everyone for your answer!

**Comment by BKSteve** [comment]
Set the permissions of the parent folder and force inherit permissions on all unfolded. This should resolve

**Comment by pnsbttl** [comment]
Hello BKSteve,
I am unfortunately in the same situation than philippebezoteaux,..
forcing inherit permissions on all subfolders solves situation only temporarily until next post-processing.


> So my point remains... Permissions are set correctly for both Plex and SickChill and been working perfectly for the last 24 months and works while manually moving files.
> 
> As Burtal mentioned, the issue only comes up while using SickChill to post process files and these do not get any permissions at all.
> 
> Here is an example that I recreated with Marvel Agents of Shield last episode... 1st screenshot is Season 07 folder permissions ![CaptureA](https://user-images.githubusercontent.com/37223962/85128784-45f4c700-b232-11ea-8af6-efc1e1f18ade.PNG) 2nd screenshot is the SickChill post processed episode's permissions ![CaptureB](https://user-images.githubusercontent.com/37223962/85128822-586f0080-b232-11ea-8f16-c3c77bcb2f60.PNG)
> 
> Also look at Condor tv show... seems that the issue is the same with SickChill created folders... 1st screenshot is 2 years ago Condor folder permissions created by SickChill ![Capture](https://user-images.githubusercontent.com/37223962/85128991-a97ef480-b232-11ea-84a8-2b9f1bf19b5f.PNG) Season 2 folder permissions created by SickChill last week ![Capture2](https://user-images.githubusercontent.com/37223962/85129021-b6034d00-b232-11ea-8e06-25c59c4273b2.PNG) Last post processed episode permissions ![Capture3](https://user-images.githubusercontent.com/37223962/85129062-c9161d00-b232-11ea-9e9d-67940568b4eb.PNG)

**Comment by BKSteve** [comment]
I will assume you are on DSM 6 as you have `sc-download` as a group.
The key with the permissions is the `system internal users` and this is `sc-sickchill` if you've installed with the `sc-` synocommunity spk.
The permissions and inherit must be set at the superior level. You've given screen shots of show folders and episodes but you need to set at the higher level. Not at Condor or Marvel... but the `TVSeries` folder level, the one/s in the `Settings>General>Show root directories` box.

See
https://github.com/SynoCommunity/spksrc/wiki/Permission-Management
and coming soon the updated wiki
https://github.com/SickChill/SickChill.WikiTemp/blob/main/Synology-install.md#synology-sickchill-permissions
