### ISSUE TITLE
motortrendondemand logo missing

### ISSUE THREAD

**Issue by GamerGun** [SickChill/SickChill#6553]
AA 2020-06-30 15:36:03 ERROR Could not open static file u'/volume2/@appstore/sickbeard-custom/var/SickBeard/gui/slick/images/network/motortrendondemand.png'

e.g. the show "Ant Anstead Master Mechanic" uses this

**Comment by miigotu** [comment]
Looks like that network was fixed on thetvdb.

**Comment by GamerGun** [comment]
Hmm still shows no image for me though

**Comment by miigotu** [comment]
Sickbeard-custom doesn't work for SC anymore though, maybe your show isn't updating.

**Comment by GamerGun** [comment]
Right, gotcha.
I removed the package from my Synology and installed the one from here https://github.com/SynoCommunity/spksrc/pull/4161 (as mentioned in https://github.com/SickChill/SickChill/wiki/Synology) but that didn't seem to help. Should i remove the show and re-add it?
