### ISSUE TITLE
unrar-free silently fail

### ISSUE THREAD

**Issue by dkgs** [SickChill/SickChill#6556]
Branch/Commit: master
OS: Armbian Focal #20.05.4

I followed the following instructions to set up SickChill after a a new os install : https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15

Then I tried to manual post process some shows, but the processing was failing silently, and the log was displaying as if it was extracting something, but it was really fast and nothing was done.

I then remove unrar-free to install unrar, then everything works as expected. As I found in the FAQ.

Hence, whether unrar-free is unsupported ? or is the documentation not updated ?

i propose to switch from unrar-free to unrar in the installation script:  #6556 

The wiki should also be updated : https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15

Thanks :)

**Comment by miigotu** [comment]
New version will be using new rarfile which supports unrar, unrar-free, unar, lsar, bsdtar
Closing this since it is already fixed in the py3 branches.
