### ISSUE TITLE
Cannot Preview Rename - keep getting "Mako error"

### ISSUE THREAD

**Issue by JasonLoKiSmith** [SickChill/SickChill#6560]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: The latest as of 05 July 2020
OS: Win 10
Browser: Chrome
What you did:  Click on Preview Rename after I just added a new show
What happened: Keep getting a "Mako Error" 
File D:/SickChill/SickChill/gui/slick/views/testRename.mako:82, in render_content:
if not ep_obj._location:

AttributeError: 'NoneType' object has no attribute '_location'

What you expected: The Preview Rename screen
![Untitled](https://user-images.githubusercontent.com/32739724/86539809-e2d88500-beff-11ea-977f-1a8f1a47f106.jpg)

Logs:
```
PASTE LOGS HERE
```

**Comment by drdelaney** [comment]
I get this same exact error message.  
Running in the most recent docker image.
Been happening "for a while"  (I cannot give a proper time estimate as I do not rename things that often.  At least 2 months)
I can temporarily fix the error by restarting sickchill (at least the docker image).  But it will eventually come back after a short while.  Ran into this problem 3 times today.

**Comment by miigotu** [comment]
If you wait until the show is done loading into the database this doesn't happen. Anyway, pushed a commit it will just skip episodes that arent loaded yet.
