### ISSUE TITLE
[Speed] :: Unable to connect to provider / [ST] :: Unable to connect to provider

### ISSUE THREAD

**Issue by papaxris** [SickChill/SickChill#6562]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

  SickChill Info:
Branch: master
Commit: 815795107af24f5381b8a6c4d41c7cced297b3f4
Version: v2020.06.20-2
Database Version: 44.1
  Python Version:2.7.12 (default, Apr 15 2020, 17:07:12) [GCC 5.4.0 20160609]
  SSL Version:OpenSSL 1.0.2g 1 Mar 2016
  OS:Linux-4.4.0-184-generic-x86_64-with-Ubuntu-16.04-xenial

What you did: Automated Daily Search
What happened:Request Failed
What you expected: Daily Search to succeed
Logs: Below
```
INFO SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: Request failed: 404 Client Error: Not Found for url: https://speed.cd/browse.php?c55=1&c52=1&c50=1&search=&c49=1&c30=1&c41=1 ()


INFO SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: Request failed: Detected the new Cloudflare challenge. ()

```

**Comment by miigotu** [comment]
speed.cd needs rewritten, they rebuilt the site.
Anything using cloudflare needs a newer openssl, which isnt available on windows. Switch to a docker image or a linux install or VM.

**Comment by papaxris** [comment]
Thanks for the response.  The OS being used is as follows:

OS:Linux-4.4.0-184-generic-x86_64-with-Ubuntu-16.04-xenial

Is there a particular version of openssl that needs to be installed on Linux?

**Comment by papaxris** [comment]
@miigotu Please disregard the previous message.  Found the information.

https://github.com/SickChill/SickChill/wiki/SSL-Errors

**Comment by miigotu** [comment]
That doesn't meet the minimum requirements for cloudflarescrape though.

It works for SC, but not all providers. Cloudflare is constantly changing their techniques.

**Comment by papaxris** [comment]
Hi @miigotu 

SickChill Info:
Branch: master
Commit: cddc3c8c60f3f588ea56326a42727ffb12149428
Database Version: 44.1
Python Version:2.7.18rc1 (default, Apr 7 2020, 12:05:55) [GCC 9.3.0]
SSL Version:OpenSSL 1.1.1f 31 Mar 2020
OS:Linux-5.4.0-40-generic-x86_64-with-Ubuntu-20.04-focal

I went ahead and update the SC install to investigate the Cloudflare error within the logs.  I'm utilizing the following version of OpenSSL:
OpenSSL 1.1.1f 31 Mar 2020

SC is behaving as expected, but the following entries are still being displayed within the logs:

INFO SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: Request failed: Detected the new Cloudflare challenge. ()

Let me know if there is any other info I can pull to help with the resolution.

**Comment by miigotu** [comment]
Cloudflare is constantly changing their methods. I am not working on the python2 base much anymore, just the python3 branch. Python3 has the newer ciphers bro help with cloudflare.

**Comment by papaxris** [comment]
Understood.  Thanks for the response and the link to the Python 3 Thread.

**Comment by AlanKellyEire** [comment]
There was changes recently made the the speed.CD site and now I am getting the same error.

`2020-09-04 08:12:48 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: Request failed: 404 Client Error: Not Found for url: https://speed.cd/browse.php?c55=1&c52=1&c50=1&search=&c49=1&c30=1&c41=1 ()`

The actual format of the URL for these categories is  
`https://speed.cd/browse/30/52/2/49/55/41/50`

They have also added a new section for SD episodes of series from any source called Episodes and the category number of that is 2. They have also added a section for there internal release group DiVERSiTY. Below is the category IDs

            '30',  # Anime
            '41',  # TV/Packs
            '49',  # TV/HD
            '50',  # TV/Sports
            '52',  # TV/B-Ray
            '55',  # TV/Kids
            '2',   # TV/Episodes
            '57',  # TV/DiVERSiTY


URL with a the search string "test"

`https://speed.cd/browse/57/30/52/2/49/55/41/50/q/test`

Let me know if you need access.

**Comment by miigotu** [comment]
Fixed in develop, requires adding cookies to provider settings. (Develop is python3 ONLY)

**Comment by papaxris** [comment]
Hi @miigotu,

I had forgotten that this issue was previously created.  I also recently made mention here:
Cloudflare IUAM error #7049


I can confirm that both SPEED and ST are experiencing this issue. I'd like to re-open #6562 to help troubleshoot and work with you to test/resolve.

SickChill Info:
Branch: master
Commit: 34112a6
Version: v2021.02.17-1
Database Version: 44.5
Python Version:3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

Error:
Request failed: Cloudflare IUAM possibility malformed, issue extracing delay value. ()

Also, the user and pass cookie info has been applied to the Provider Options

**Comment by miigotu** [comment]
You are more than a month out of date with your updates

**Comment by papaxris** [comment]
@miigotu 

SC was updated and the test was run again for SPEED.  Same issue as before.

SickChill Info:
Branch: master
Commit: 771ea729fdae8606b6d41e3e66bb583323398014
Version: v2021.03.10-1
Database Version: 44.5
Python Version:3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
SSL Version:OpenSSL 1.1.1f 31 Mar 2020
OS:Linux-5.4.0-65-generic-x86_64-with-glibc2.29

Error:
Request failed: Cloudflare IUAM possibility malformed, issue extracing delay value. ()

**Comment by miigotu** [comment]
Try develop, I just updated cloudscraper there

**Comment by papaxris** [comment]
Hi @miigotu,

Thanks for providing the update an the feedback.  I had an opportunity today to test with the latest master branch release.  The log now shows a different message than what it was previously capturing.

Log:
SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: Request failed: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version. () 

SickChill Info:
Branch: master
Commit: a16038636bfa9fe747f9ef50c785b3b223213122
Version: v2021.03.18-1
Database Version: 44.5
  Python Version:3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
  SSL Version:OpenSSL 1.1.1f 31 Mar 2020
  OS:Linux-5.4.0-65-generic-x86_64-with-glibc2.29
  Locale:en_US.UTF-8

**Comment by miigotu** [comment]
Yes, which means there is nothing I can do about it.

**Comment by papaxris** [comment]
Understood.  At least you were able to confirm the root cause of the issue.

Hopefully the cloudflare bypass gets updated soon and we can test again and confirm functionality.

Thanks for your help/update and communication.

**Comment by papaxris** [comment]
SickChill Info:
Branch: master
Commit: d76229cd404a162a707d189302990d8911ffe77e
Version: v2021.04.10-1
Database Version: 44.5
Python Version:3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
SSL Version:OpenSSL 1.1.1f 31 Mar 2020
OS:Linux-5.4.0-65-generic-x86_64-with-glibc2.29

With the current cloudscraper update the following was collected from the logs:

SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: Request failed: Unable to parse Cloudflare anti-bots page: Error trying to solve

@miigotu If you would like to check a different way to test, I'd be open to help.

**Comment by miigotu** [comment]
Cloudscraper is not a part of SC.

**Comment by papaxris** [comment]
I totally understand that.

I'm referring to release 2021.4.10 where the following was included:
Bump cloudscraper from 1.2.56 to 1.2.58

I figured this was done in an effort to resolve the issues on this thread.

**Comment by miigotu** [comment]
Nope, it just keeps the requirements.txt, poetry.lock, yarn.lock, and lib folder up to date.
