### ISSUE TITLE
Import error : cannot import name FeedParserDict

### ISSUE THREAD

**Issue by titofffffff** [SickChill/SickChill#6571]
hello,

since latest update I have an issue to run SickChill on docker.

Here below the detail of the issue.

Thanks in avance for your help :)

**Branch/Commit:** master/lastest
**OS:** Linux (docker container linuxserver/sickrage:latest from Docker hub registry)
**Browser:** n/a
**What you did:** update from master and restart docker container
**What happened:t**he following error at sickchill starting : 
![image](https://user-images.githubusercontent.com/5903546/87223775-f496ae00-c37f-11ea-8098-91994035bf6d.png)

**What you expected:**
clean start of SickChill

**Comment by miigotu** [comment]
#6230
