### ISSUE TITLE
[FEATURE REQUEST] add new episode status: "snatched manually" or similar

### ISSUE THREAD

**Issue by OneCDOnly** [SickChill/SickChill#6576]
For as long as I've been using SickBeard (and its later forks), I've wanted to be able to set episode statuses to `manually snatched`, `snatched manually` or something like it. This is for episodes that were not found using the "usual" methods, and have already been placed in a download queue. 

At present, I set these to `skipped` to prevent SickChill from searching for them and potentially adding them again as new downloadable items. 

Or, maybe we could make the current `snatched` status selectable by the user?

Thank you.

**Comment by miigotu** [comment]
I will close this for now since we are not doing feature requests currently, especially since porting to py3 is the priority now
I can look back over the features requested at a later date.
