### ISSUE TITLE
SickChill Configuration/SickChill Info - No longer displays version

### ISSUE THREAD

**Issue by papaxris** [SickChill/SickChill#6580]
SickChill Info:
Branch: master
Commit: cddc3c8c60f3f588ea56326a42727ffb12149428
Database Version: 44.1
Python Version:2.7.18rc1 (default, Apr 7 2020, 12:05:55) [GCC 9.3.0]
SSL Version:OpenSSL 1.1.1f 31 Mar 2020
OS:Linux-5.4.0-40-generic-x86_64-with-Ubuntu-20.04-focal

What was expected:
Under Sickchill Configuration => SickChill Info
http://server:8081/config/

For the current version of SickChill to be displayed generally under the Commit string.

Currently SickChill Info displays the following (no version):

SickChill Info:
Branch: master
Commit: cddc3c8c60f3f588ea56326a42727ffb12149428
Database Version: 44.1

**Comment by miigotu** [comment]
Possibly something with your git clone on your end, but even if not I am not working on python2.7 version anymore, just the python3 branch for now (which will soon replace the python2 master)

![image](https://user-images.githubusercontent.com/390379/88455937-a9809e80-ce47-11ea-9358-0f2bea081ecb.png)
