### ISSUE TITLE
SickChill on Synology will not start/run 

### ISSUE THREAD

**Issue by Fraggle72** [SickChill/SickChill#6585]
Branch/Commit: sickchill_noarch-all_20200603-1.spk (https://github.com/SickChill/synology-sickchill/releases/download/20200603-1/sickchill_noarch-all_20200603-1.spk)
OS: Synology
Browser: Chrome
What you did: 
I have tried the update from [BenjV](https://github.com/BenjV/SYNO-packages) following a restart when this also did not work I tried installing sickchill_noarch-all_20200603-1.spk referenced in the issues, however this also failed to run.

What happened:  
Package installs however does not run.  The new error appears to be a path issue (can't open file '/volume1/@appstore/sickchill/SickChill/SickBeard.py': [Errno 2] No such file or directory), the file is actually located '/var/packages/sickchill/target/var/SickBeard/'

I was also unable to reinstall the BenjV package as synology saw it as an earlier version.  

Logs:
```
Wed Jul 22 14:27:35 AWST 2020
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python /volume1/@appstore/sickchill/SickChill/SickBeard.py --daemon --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/config.ini --datadir /volume1/@appstore/sickchill/var 
/volume1/@appstore/sickchill/env/bin/python: can't open file '/volume1/@appstore/sickchill/SickChill/SickBeard.py': [Errno 2] No such file or directory

```

Thanks in advance

**Comment by Fraggle72** [comment]
Hi @miigotu, 

I appear to have fixed the path issue by updating the service-setup file with the following:

SICKCHILL="${SYNOPKG_PKGDEST}/var/SickBeard/SickBeard.py"
#SICKCHILL="${SYNOPKG_PKGDEST}/SickChill/SickBeard.py"

However I am now getting the following in the error log:

Thu Jul 23 11:37:27 AWST 2020
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python /volume1/@appstore/sickchill/var/SickBeard/SickBeard.py --daemon --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/config.ini --datadir /volume1/@appstore/sickchill/var 
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2n  7 Dec 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/var/SickBeard/SickBeard.py", line 520, in <module>
    SickChill().start()
  File "/volume1/@appstore/sickchill/var/SickBeard/SickBeard.py", line 242, in start
    sickbeard.CFG = ConfigObj(sickbeard.CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/volume1/@appstore/sickchill/var/SickBeard/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/volume1/@appstore/sickchill/var/SickBeard/lib/configobj.py", line 1318, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 1056.

Any assistance would be appreciated as I really like using SickChill would prefer to not have to revert to other apps.

Cheers,

**Comment by miigotu** [comment]
Your config.ini is damaged

**Comment by Fraggle72** [comment]
Hi @miigotu,

Thanks for getting back to me.  
I can open the config.ini without an issue and it looks okay.

Should I just copy in a version from the backup folder?

**Comment by Fraggle72** [comment]
Thanks, I wrote the contents of an older backup over the current file and it is now working.

Thanks again for the guidance.
