### ISSUE TITLE
Error parsing existing nfo file 

### ISSUE THREAD

**Issue by jclemens78** [SickChill/SickChill#6590]
I've been getting a warning for the last few months that I can't comprehend.  I had had a few drives on my server get bad sectors.  When I first searched on the issues here found that you said a few NFO's were blank and I had some junk files at 0 bytes that I deleted and then had Sickchill do a full update on that show and get new NFO's.  I still got the errors and also tried to have Ember Media Manager get new ones as well with the same warnings pop up.  It shows I have 3,300 warnings because it flags every ep.  All the NFO's work fine in Kodi and Plex, so I'm a little at a loss on what the flag is and why it keep popping up and how I can fix it.  

Thanks for your help!

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master/c67114a85c9d911697376acec2d4c6dd9c902e54
OS: Windows 10
Browser: Chrome
What you did: Tried to delete the NFO files and had Sickchill do a full update to re-download the NFO's.  Also used Ember Media Manager to re-scrape NFO's as well. 
What happened: No change
What you expected: Not to keep getting the error messages
Logs:
```
2020-07-25 07:39:01 SHOWQUEUE-FORCE-UPDATE :: Error parsing existing nfo file at F:\Clemens Home Server\Recorded TV\TV Shows\Star Wars The Clone Wars\Season 1\Star Wars The Clone Wars s01e10.nfo - no element found: line 1, column 0
2020-07-25 07:39:00 SHOWQUEUE-FORCE-UPDATE :: Error parsing existing nfo file at F:\Clemens Home Server\Recorded TV\TV Shows\Star Wars The Clone Wars\Season 1\Star Wars The Clone Wars s01e02.nfo - no element found: line 1, column 0
2020-07-25 07:39:00 SHOWQUEUE-FORCE-UPDATE :: Error parsing existing nfo file at F:\Clemens Home Server\Recorded TV\TV Shows\Star Wars The Clone Wars\Season 1\Star Wars The Clone Wars s01e05.nfo - no element found: line 1, column 0

```

**Comment by miigotu** [comment]
Post contents of one of the nfo's it errors on.

I can try to help but there won't be code changes to the python2 branch, I'm working on the python3 branch

**Comment by jclemens78** [comment]
When I went to look at the first file I posted, it showed a file size of 0.  And I blew out all the zeros a month ago when this happened a fourth time.  Testing deleting all the duplicated versions of these files from DriveBender and re-updating again.  If it pops up again then it's something goofy with my Sickchill updating it's NFO's.  I'll follow back up as soon as this is complete.  

Is there a way to not have Sickchill do Daily Searches for shows that I'm done and complete on?  It seems like it does extra processing and spinning up of the hard drives when I really only need it to search for new shows instead of older stuff.

**Comment by miigotu** [comment]
Pause the complete shows

**Comment by hairyhippy** [comment]
Hi
I'm getting a similar error parsing existing nfo message, except mine says junk after document element, mainly line 34 but a couple line 37.  Should I delete the existing and force a full update to resolve?

**Comment by jclemens78** [comment]
I deleted all the bad nfo's in question and it seemed to fix it for me after updating each show.  It happened a couple of times and what @miigotu suggested helped fix it.
