### ISSUE TITLE
Sickchill HTTP Error 409 adding label to qbittorrent

### ISSUE THREAD

**Issue by GeekItTillItMhz** [SickChill/SickChill#6600]
### Before submitting your issue:

~~Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)~~ Done!

**Branch/Commit:**
linuxserver / sickchill |   | v2020.07.18-1-ls39 (Commit: c67114a85c9d911697376acec2d4c6dd9c902e54 | Database Version: 44.4)
linuxserver / qbittorrent |   | 14.2.5.99202004250119-7015-2c65b79ubuntu18.04.1-ls86 (qBittorrent v4.2.5 (64-bit)

**OS:** VERSION_ID="20200727" "openSUSE Tumbleweed" Sickchill sees it as (Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with)
**Browser:** Firefox
**What you did:** Started both docker containers, Authed qbittorrent in Sickchill sucessfully, Test in menu runs without error.
**What happened:** Torrent gets added to qbittorrent but SickChill cannot add the label due to error.
**What you expected:** Torrent is added to client with specified label.
**Logs:**
```
2020-07-31 00:02:15 INFO     SEARCHQUEUE-BACKLOG- :: Beginning backlog search for: [XXXXXX]
AA None
2020-07-31 00:02:12 ERROR    SEARCHQUEUE-BACKLOG- :: [c67114a] qBittorrent APIv2: Unable to set the label for Torrent
2020-07-31 00:02:12 INFO     SEARCHQUEUE-BACKLOG- :: Request failed: 409 Client Error: Conflict for url: http://qbittorrent:8080/api/v2/torrents/setCategory ()
```
Any insight is appreciated.

**Comment by miigotu** [comment]
Use the other qbittorrent client in SC (there are 2 versions)

**Comment by GeekItTillItMhz** [comment]
So the above is using the qbittorrent API V2. When I switch to just qbittorrent the below happens:

> 2020-08-04 00:11:27 DEBUG    SEARCHQUEUE-BACKLOG- :: qbittorrent: Requested a POST connection to url http://qBittorrent:8080/command/download and data: {u'urls': 'magnet:?xt=urn:btih:986d010aa420bc7f43de5d6db3e4debbc442df65&dn=&tr=udp%3A%2F%2Ftracker....
> 2020-08-04 00:11:27 INFO     SEARCHQUEUE-BACKLOG- :: Request failed: 404 Client Error: Not Found for url: http://qbittorrent:8080/command/download (<type 'str'>)
> 2020-08-04 00:11:27 WARNING  SEARCHQUEUE-BACKLOG- :: qbittorrent: Unable to send Torrent

Other than changing qbittorrent in the drop down. The URL has not changed, username and password have not changed.

**Comment by miigotu** [comment]
I have updated to a new qbittorrent client library in the py3 branch. it will be fixed there.
