### ISSUE TITLE
Twilio Notifications Fail

### ISSUE THREAD

**Issue by hooper303** [SickChill/SickChill#6603]
I am going to preface this with Twilio was working prior to doing a restore on a new install of sickchill. My hunch is that something got carried over in the restore causing Twilio to stop working. If you look at the remote_ip it is referencing 192.168.10.150. The server is at 192.168.10.200. I have no idea where the .150 address is coming from or how to change it. 

Branch: master
Commit: c67114a85c9d911697376acec2d4c6dd9c902e54
OS: Linux-4.14.24-qnap-x86_64-with
Browser: n/a
What you did: Enabled Twilio Notifications, Pressed Test Twilio button 
What happened: Twilio Test Fails (actually no change to UI)
What you expected: Twilio test to succeed
Logs:

AA NameError: global name 'twilio' is not defined
AA File "", line 3, in raise_exc_info
AA raise_exc_info(self._exc_info)
AA File "/app/sickchill/lib/tornado/concurrent.py", line 261, in result
AA value = future.result()
AA File "/app/sickchill/lib/tornado/gen.py", line 1133, in run
AA results = yield self.async_call(method)
AA File "/app/sickchill/sickchill/views/index.py", line 192, in get
AA yielded = self.gen.throw(*exc_info)
AA File "/app/sickchill/lib/tornado/gen.py", line 1141, in run
AA raise_exc_info(self._exc_info)
AA File "/app/sickchill/lib/tornado/concurrent.py", line 261, in result
AA value = future.result()
AA File "/app/sickchill/lib/tornado/gen.py", line 1133, in run
AA result = yield result
AA File "/app/sickchill/lib/tornado/web.py", line 1592, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol=u'http', host='192.168.10.200:8082', method='POST', uri='/home/testTwilio', version='HTTP/1.1', remote_ip='192.168.10.150')
AA 2020-07-31 15:27:10 ERROR Uncaught exception POST /home/testTwilio (192.168.10.150)
AA NameError: global name 'twilio' is not defined
AA except twilio.TwilioRestException:
AA File "/app/sickchill/sickbeard/notifiers/twilio_notify.py", line 72, in test_notify
AA result = notifiers.twilio_notifier.test_notify()
AA File "/app/sickchill/sickchill/views/home.py", line 365, in testTwilio
AA return function(**kwargs)
AA File "/app/sickchill/sickchill/views/index.py", line 215, in async_call
AA Traceback (most recent call last):
AA NameError: global name 'twilio' is not defined
AA except twilio.TwilioRestException:
AA File "/app/sickchill/sickbeard/notifiers/twilio_notify.py", line 72, in test_notify
AA result = notifiers.twilio_notifier.test_notify()
AA File "/app/sickchill/sickchill/views/home.py", line 365, in testTwilio
AA return function(**kwargs)
AA File "/app/sickchill/sickchill/views/index.py", line 215, in async_call

**Comment by miigotu** [comment]
Twilio client is rewritten in the py3 branch. Im not going to work on the python2 branch anytime soon.
