### ISSUE TITLE
[APP SUBMITTED]: near "ALD": syntax error

### ISSUE THREAD

**Issue by arathas** [SickChill/SickChill#6607]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@c67114a85c9d911697376acec2d4c6dd9c902e54
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [HorribleSubs] :: [c67114a] Error while searching HorribleSubs, skipping: near "ALD": syntax error
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by arathas** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@c67114a85c9d911697376acec2d4c6dd9c902e54
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-DAILY-SEARCH :: [HorribleSubs] :: [c67114a] Fatal error executing query with db.mass_action in database C:\SickChill\Data\cache.db: near "ALD": syntax error
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Looks like your cache.db is corrupt. Stop SC and delete it and try again.
