### ISSUE TITLE
PY3 Q&A

### ISSUE THREAD

**Issue by DrDrewZA** [SickChill/SickChill#6613]
Hey guys - for those of us who are not developers, can I ask a few questions about getting my python upgraded from 2.7 to 3.x, just for the sake of clarity...

1)  Do I remove the old 2.7 installation first?
2)  Can I do this upgrade now already, or must I wait until the PY3-again branch is ready?

Im sure there are more questions out there from users - perhaps this can be the place to ask them.

TIA

**Comment by Tiwas** [comment]
Good thread. Wanted to know the same myself.

**Comment by DrDrewZA** [comment]
oh and before I forget - congrats on the birth bud!

**Comment by miigotu** [comment]
Thanks. He's a great baby 🥰

Anyways, you don't need to remove python 2 to install/use python3. You might even have other apps that still use python2

You just use your package manager and install python3 (preferably the latest version of python3, like 3.7 or 3.8)

**Comment by Tiwas** [comment]
@miigotu Great to hear being a dad works out 👍 

This might be a stupid question, but is there some way to change to the python 3 code now, or will there be news when it's available? The current version doesn't support python 3, it seems.

**Comment by miigotu** [comment]
The preferred way will be to backup from inside SC, shutdown/disable your old service, install python3.5+, which automatically installs pip, then pip3 install sickchill, edit your service to point to the new startup script (SickChill.py - it will be in your path) and restore your backup.

**Comment by miigotu** [comment]
Of course, running from a source archive or git clone will still work, but a pip install will help you keep your dependencies up to date.

**Comment by miigotu** [comment]
#6545 is where the discussion is btw, closing this so it isn't duplicate

![Screenshot_20200806-123259](https://user-images.githubusercontent.com/390379/89557907-86f46b00-d7e1-11ea-8cf1-131251a58b9f.png)

**Comment by miigotu** [comment]
@Tiwas it's still buggy and experimental. It is in the py3-again branch
