### ISSUE TITLE
Cannot Connect to SickChil Web UI from another system on the local network

### ISSUE THREAD

**Issue by sramacha2** [SickChill/SickChill#6614]
Branch/Commit: master  v2020.07.18-1 
OS: Centos 8 4.18.0-193.14.2.el8_2.x86_64
Browser: Firefox 68.10.0esr (64bit)

What you did: Tried to run firefox on a another system in the local network and tried to connect to http:<local_ip>:8081
I've checked 'netstat -tlpn' output and I see LISTEN on port 8081.
I also checked SickChill GitHub FAQ's and Fixes page but nothing relevant was found.

What happened: Firefox errors out with message "Unable to connect Cannot establish a connection to the server at <local_ip>:8081

What you expected: Firefox to be able to connect to SickChill web ui from another system on the local network and displays the SickChill home page.
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
make sure you are using http or https correctly

**Comment by sramacha2** [comment]
The URL I use is http://<sickchill_server_ip>:8081, both machines are on the same local network. SickChill is not exposed to the Internet.

**Comment by miigotu** [comment]
Same subnet?

**Comment by miigotu** [comment]
Possibly you have a firewall on the host, and are not allowing incoming connections to 8081. SC is working fine across a local network atm.

**Comment by miigotu** [comment]
Also make sure firefox or https-everywhere isnt changing your request to https

**Comment by sramacha2** [comment]
This was a brand new Centos 8 install and forgot that all ports are closed by default by the firewall. Opened them up and now I can connect from another system on the local network.
Appreciate steering me in the right direction :+1: 

Thanks.

**Comment by sramacha2** [comment]
Thanks for all your time and prompt responses!
