### ISSUE TITLE
Python 3 - Cannot import backup from version running on python 2.7

### ISSUE THREAD

**Issue by NunoHiggs** [SickChill/SickChill#6619]
Branch/Commit: master - installed via pip3 install sickchill -U sickchill
OS: linux
Browser: any
What you did: tried to restore zip form running version on py 2.7
What happened: restore failed. series loaded but only series. no configs, no search providers, etc
What you expected: restore to work.
Logs:
```
[sickchill@lxcVpar18 bin]$ ./SickChill.py
Restore: restoring DB and config.ini FAILED!
2020-08-08 22:43:08 WARNING :: MAIN :: Restore: settings.Unable to remove the cache/mako directory: [Errno 2] No such file or directory: '/home/sickchill/.local/lib/python3.7/site-packages/sickchill/gui/slick/cache/mako'
```

**Comment by miigotu** [comment]
Thanks. Fixed.

**Comment by NunoHiggs** [comment]
Hello,
Nope it isnt fixed. Just updated form the latest on pip, and the error remains, Is it still to be pushed to pip the correction?
Also found another bug regarding proxy usage. Will open a new bug report.

Thanks

**Comment by miigotu** [comment]
The cache/mako log line can be ignored, that's not a bug.

**Comment by NunoHiggs** [comment]
The issue still remains. Just pulled the latest form github, tree python3, and the issue remains.
The configs are there, form what i can see, all of the providers, but no shows.

If i do a drill down using curl i get:

curl -S http://lxcvpar18.net.xpto:8082/sickrage/api/XXXXXXXXXXXXXXXXX/?cmd=shows 

{"data": {"args": [], "error_msg": "a bytes-like object is required, not 'str'", "kwargs": {}}, "message": "SickChill encountered an internal error! Please report to the Devs", "result": "fatal"}

On the py2.7 i get a valid output.

**Comment by miigotu** [comment]
That's the API, check in the web UI. I will look at the API today.

**Comment by miigotu** [comment]
Also, what is shown in the log when you call the API?

**Comment by NunoHiggs** [comment]
Just updated from the latest source.
Now, after the restore, i still do not see any of my shows, but the output of the api is different:

{"data": {}, "message": "", "result": "success"}

But no show is displayed, either on the API, or web. No show is showned.
Looking at the logs:

2020-08-10 21:18:08 DEBUG :: WEBSERVER :: API :: 172.16.2.10 - gave correct API KEY. ACCESS GRANTED
2020-08-10 21:18:08 DEBUG :: WEBSERVER :: API :: all args: '()'
2020-08-10 21:18:08 DEBUG :: WEBSERVER :: API :: all kwargs: '{'cmd': b'shows'}'
2020-08-10 21:18:08 DEBUG :: WEBSERVER :: API :: shows: cur_kwargs {}
2020-08-10 21:20:47 DEBUG :: WEBSERVER :: API :: 172.16.2.10 - gave correct API KEY. ACCESS GRANTED
2020-08-10 21:20:47 DEBUG :: WEBSERVER :: API :: all args: '()'
2020-08-10 21:20:47 DEBUG :: WEBSERVER :: API :: all kwargs: '{'cmd': b'shows'}'
2020-08-10 21:20:47 DEBUG :: WEBSERVER :: API :: shows: cur_kwargs {}

No error, but no shows. 

Thanks for your help

**Comment by miigotu** [comment]
go to the Help&Info page and note the path your db is being loaded from, make sure your db is there and named sickchill.db

**Comment by NunoHiggs** [comment]
Hello,

That was the issue. There was an sickchill.db there (almost empty). Even when i did a restore, the original sickchill.db was not deleted, and sickbeard.db was placed along side it, not replacing it.
Once i stopped the app, deleted sickchill.db, the sickbeard.db file was automatically renamed and the shows were shown.

Thanks!!

**Comment by miigotu** [comment]
@NunoHiggs I fixed it so it doesnt happen to other people now. I appreciate you finding like 5 bugs for me so quick =P
This branch needs a lot of testing before it goes live.
https://github.com/SickChill/SickChill/pull/6625/commits
https://github.com/SickChill/SickChill/pull/6625/commits/dcafdc44dd2ea39ba1906c2f2fe51c72b3e6aeeb
https://github.com/SickChill/SickChill/pull/6625/commits/1f69a4db484a04c0f790492226aff76f1d7bc65d

**Comment by NunoHiggs** [comment]
I will continue testing and report as soon as i find more.
