### ISSUE TITLE
Mako Error on Preview Rename

### ISSUE THREAD

**Issue by crowaust** [SickChill/SickChill#6632]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

SickChill Info:
Branch: master
Commit: 99336df163c7e776c7931d864e84d1f0f83afe4d
Version: v2020.08.07-1
Database Version: 44.1
  Python Version:2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]
  SSL Version:OpenSSL 1.0.2t 10 Sep 2019
  OS:Windows-2008ServerR2-6.1.7601-SP1
  Locale:en_AU.cp1252

Browser:Google Chrome Version 84.0.4147.125 (Official Build) (64-bit)
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```
http://127.0.0.1:9094/home/testRename?show=305089

Mako Error
A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

File C:/SickChill/SickChill/gui/slick/views/testRename.mako:63, in render_content:
${('Season '+ str(current_season), 'Specials')[int(current_season) == 0]}

TypeError: int() argument must be a string or a number, not 'NoneType'
875 Shows (95 Active)  | 25330 +2718  Snatched / 38039 Episodes Downloaded (66.5%)  | Daily Search: 0:40:48 | Backlog Search: 11:20:43
Load time: 14.2090s | Mako: 14.2050s | Branch: master | Now: 12-08-2020 18:30

**Comment by miigotu** [comment]
I will fix this in the python3 branch later.
