### ISSUE TITLE
Filter out Rar compressed torrents? Not an issue.

### ISSUE THREAD

**Issue by JDubbedN** [SickChill/SickChill#6645]
I am not sure if this is the correct area to seek help. If it isn't please redirect me to the correct area. Maybe there is a community forum or a discord channel for general support I am not seeing.

Is there a way to filter out provider searches that contain compressed files aka rar?

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed) na

Branch/Commit: master
OS: Windows 10
Browser: FireFox
What you did: na
What happened: na
What you expected: na
Logs:
```
PASTE LOGS HERE
```

**Comment by RB14060** [comment]
SickChill itself doesn't have an option for that because it doesn't inspect the contents of the torrent files before it begins downloading them. If the uploaders on your provider are good about marking downloads as [NO RAR] or similar, you can go into Search Settings and make that a required phrase.

**Comment by miigotu** [comment]
Many providers won't allow rars/zips in video torrents.

I could parse a .torrent file if we have that and not just a magnet, but I'm not sure it's worth the time/effort to implement that?

**Comment by JDubbedN** [comment]
Miigotu you might be right that it may not be worth the time to implement if I am the only one having an issue with rars. Unfortunately the provider that I use doesn't appear to filter that stuff out or monitor it on their end. Uploaders don't have to label their files as such and they don't normally do so. If I could let me tell you my problem and maybe you have a solution.

I use Plex and I already have a folder system in place. I have SickChill setup using the black hole and my tor client watches the black hole folder for files. Once finished the file moves to the complete folder which SickChill watches and processes or "copies" to the respective tv show directory and named folder. For example "tv shows\show1". Problem is if I wanted to continue seeding, which I normally do for a long time, I now have duplicate files, one in the completed folder and one copied over using SickChill processing so that Plex can update it's library appropriately within it's folder structure.

Solution? Well since Plex doesn't read rar files I first need to filter out downloading rar files. Then, I would need to somehow have SickChill tell the tor client to download the files to the respective tv show directory rather then in the completed folder where it would wait for SickChill to process. I hope I am making sense. I am having trouble explaining in words what I am trying to accomplish.

I am just trying to avoid having two copies on my server, one for seeding and one for Plex.

Would you have any suggestions?

**Comment by RB14060** [comment]
Not sure if Windows supports it but hard links would be the way to
accomplish this. That way the file only physically exists on the disk once,
but it can appear to be in multiple folders at the same time. Deleting one
copy won't delete the file from disk unless it's the only one remaining.

**Comment by JDubbedN** [comment]
I'll look more into hard linking. That sounds like it could be part of the solution. However, if I cannot filter out torrents that contain rar's then it won't matter if I can hard link or not because Plex won't read rar's. What would be needed to tell SickChill to ignore torrents that contain rar files?

**Comment by RB14060** [comment]
Not sure why you'd need to, SickChill can automatically perform an unrar as
part of post processing, and some torrent clients are able to as well.

**Comment by JDubbedN** [comment]
Plex cannot read rar's. And if i want to seed a file that was downloaded as a rar then I have to leave the rar for seeding, then have SickChill unrar, then copy its contents to the Plex tv directory. Which hard link then wouldn't make sense and thus I would then have the rar and the unrared copies creating twice the space. Unless I am missing something. Would be better just to get rid of rar downloads if possible.

**Comment by JDubbedN** [comment]
I think if we can filter out rar files from downloading somehow then I could have SickChill process hard link from the completed downloads folder to the respected tv shows folder that Plex reads this way only having one copy of the media, if I understand hard linking correctly.

What I am wondering is this. Is my setup that unique? I do imagine other users having the same setup. What does it take for a user to continue to seed while keeping the Plex file structure? I guess another idea would be to have SickChill communicate with the tor client so that it adds the torrent file and saves the torrent location to the respective file structure rather then the black hole. This is how I do it manually to keep the file structure without having duplicates. Every time I download a torrent file I tell my tor client the exact location of where the tv show folder is which will be the same location it'll seed so it doesn't break the seed process and doesn't require moving or copying of the folders. Is this possible with SickChill?

**Comment by miigotu** [comment]
@JDubbedN does this provider give you torrent files or magnet links?

**Comment by JDubbedN** [comment]
I assume it is a torrent file. It is a physical file I download and then open in the tor client.

**Comment by miigotu** [comment]
This one is gonna be a pain in the ass to do, I might be able to do it sometime in the near future but no promises.
For now I would be looking for a more reliable provider who follows scene rules honestly, or just live with the extra disk space used by the seeding rars.

**Comment by JDubbedN** [comment]
I appreciate your time looking into this. I'll look and see if there is any other way to avoid SickChill downloading rar'd files maybe through the torrent website but I doubt there is an option to avoid rar torrents like there is with XXX torrents or the like. For the time being I'll just have two copies but instead of seeding for my usual 6 mo to 1 year time frame I'll have to settle for 1:1 so I can remove the duplicate files asap for obvious capacity reasons. Keep up the good work @miigotu .
