### ISSUE TITLE
API sb.searchtvdb or sb.searchindexers should return poster / banner informations

### ISSUE THREAD

**Issue by jaumard** [SickChill/SickChill#6654]
Would be nice to have the API to give poster and banner URLs, it will allow the web interface (or all other based on the API) to show the poster/banner and not only the name of the show. It will be easier to pick the right one.

Branch/Commit: master
OS: all
Browser: all
What you did: call APIBuilder with `cmd=sb.searchtvdb&lang=en&name=the 100`
What happened: Getting:
```
{
    "data": {
        "langid": 7,
        "results": [
            {
                "first_aired": "1991-3-31",
                "in_show_list": null,
                "indexer": 1,
                "name": "The 100 Lives of Black Jack Savage",
                "tvdbid": 76615
            },
            ///...
        ]
    },
    "message": "",
    "result": "success"
}
```
What you expected:
```
{
    "data": {
        "langid": 7,
        "results": [
            {
                "first_aired": "1991-3-31",
                "in_show_list": null,
                "indexer": 1,
                "name": "The 100 Lives of Black Jack Savage",
                "poster": "https://artworks.thetvdb.com/banners/posters/76615-1.jpg",
                "tvdbid": 76615
            },
            ///...
        ]
    },
    "message": "",
    "result": "success"
}
```

**Comment by miigotu** [comment]
Our web interface does show the banners and posters, and a poster/image selection feature is being implemented right now. We don't keep the URL's in the database, and we can't spam thetvdb every time someone hits the API endpoint.

**Comment by jaumard** [comment]
> Our web interface does show the banners and posters 

Not on search :) and I found it a bit painful to choose the right show when they have similar name.
<img width="721" alt="Capture d’écran 2020-08-16 à 17 28 43" src="https://user-images.githubusercontent.com/2970449/90337910-f2121e80-dfe5-11ea-86b2-93df05795bfa.png">

I'm currently making an mobile app that implement the sickchill API, and I want to offer poster/banner on show search to avoid opening thetvdb each time multiple show have similar names. 

> We don't keep the URL's in the database, and we can't spam thetvdb every time someone hits the API endpoint

I'm talking about the search API here. 
Totally agree that you shouldn't spam thetvdb, but here it's a thetvdb search anyway so you're calling them right ? Why not return poster/banner too in that case ? There is no DB involved normally.

**Comment by miigotu** [comment]
Our web interface does not use our web API, totally different.

We do have a mobile app though, maybe we can just update that.

Btw, you can also search tvdb yourself in the app and pass an indexerid to the add show search box.
