### ISSUE TITLE
Develop branch update shows very high commit count - 1161 commits but only 20 commits different

### ISSUE THREAD

**Issue by Parlane** [SickChill/SickChill#6657]
Branch/Commit: develop - 353dceb8e01a26aa899c93e74f38bada83fb24d3
OS: Docker under Debian 64 bit x64
Browser: Chrome
What you did: Opened sickchill home page
What happened: Update available notification appears but shows 1161 commits different
What you expected: Based on the "newer version available" link it should say:  There is a newer version available (you're 20 commits behind) — Update Now
Logs: Not relevant

The link is to: https://github.com/SickChill/SickChill/compare/353dceb8e01a26aa899c93e74f38bada83fb24d3...976a467387b97478454c68aeb2836341917d5f75

Which shows: 
![image](https://user-images.githubusercontent.com/86614/90441177-9aca9600-e12c-11ea-8993-250e59f48bd0.png)

![image](https://user-images.githubusercontent.com/86614/90440890-19730380-e12c-11ea-95ed-8013c048e85a.png)

Also there is no plural on the word "commit" as expected.

**Comment by miigotu** [comment]
How was your old setup ran? maybe you have a commit hash in your config.ini

**Comment by Parlane** [comment]
Would that not be reflected in the comparison link to github ?

**Comment by Parlane** [comment]
I checked my config.ini and the cur_commit_hash is 99336df163c7e776c7931d864e84d1f0f83afe4d

When I plug that in to the git diff URL I get 188 new commits

**Comment by Parlane** [comment]
Looks like an issue with the local git repo:

![image](https://user-images.githubusercontent.com/86614/90443238-0a8e5000-e130-11ea-8c02-a17596064d16.png)

**Comment by miigotu** [comment]
```
git fetch origin
git reset --hard origin/develop
ctrl+C
docker restart sickchill
```

**Comment by Parlane** [comment]
Yep done that, then I realised I had an issue with my debian not having chrony running so the clocks were out by 6 minutes so the imdb updates all failed.... SMH.

Upgrade worked eventually but now it is giving:

2020-08-18 09:00:14 INFO :: MAIN :: 337302: Unable to find IMDb show info in the database

One of those lines for every show, and very slowly :)
