### ISSUE TITLE
"Add Existing Shows" downloads episodes I already have

### ISSUE THREAD

**Issue by JDubbedN** [SickChill/SickChill#6659]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Windows 10 64bit
Browser: FireFox 79 64bit
What you did: Selected "Add Existing Shows". Selected correct TV show, select correct directory where TV show with episodes already exist which has season 1 and 2 already had all episodes.
What happened: All episodes were selected for downloading rather then the episodes I needed which was season 3 only.
What you expected: I expected for SickChill to see that season 1 and 2 were already there in the directory and to only download season 3. I did the same steps for another TV show and it worked as intended.
Logs:
```
I am having trouble finding the debug option. Can you please specify?

Thank you

```

**Comment by miigotu** [comment]
Likey you had the show set for one quality and the ones you already had were not that quality or had no quality tags in the file name. This causes it to have to download the episodes to make sure you have a quality you have set in preferred.

**Comment by JDubbedN** [comment]
Thanks for the reply @miigotu . So your saying I have to select the preferred quality in SickChill to the same quality episodes I already have? What if I have different quality's? Can SickChill not just see that the episodes are already there regardless of quality by using metadata already present? Like their names?

And what if I would like to download 720p quality instead of the 1080p that I already have downloaded for reasons like saving space? How could I accomplish this?

**Comment by miigotu** [comment]
If the quality is in the file names properly, it will recognize those episodes as that quality when adding existing. Then, you set the allowed qualities to include both qualities, and the preferred to what you want for future episodes and check the first match box.

**Comment by JDubbedN** [comment]
Thanks that seems to have fixed my problem.

**Comment by JDubbedN** [comment]
I didn't want to create another bug report and clutter things up. But I selected "delete rar contents" under settings but it doesn't appear to be working as I think it is supposed to. And under your online manual there is a "?" Under this feature so that doesn't help me understand what it does. What I think it is supposed to do is after the contents of a rar file is unpacked and copied over SickChill then deletes the contents that was unpacked from the rar. Am I understanding that correctly? If so, that is not the outcome. The contents of the rar stay. Any suggestions?
