### ISSUE TITLE
delete rar contents doesn't appear to do what I think it is supposed to do.

### ISSUE THREAD

**Issue by JDubbedN** [SickChill/SickChill#6664]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Windows 10 64bit
Browser: FireFox 79 64bit
What you did: Selected "delete rar contents" in settings
What happened: extracted content stays un-deleted so that the rar files downloaded from .torrent file plus un-rar'd contents take up space.
What you expected: I thought the rar'd contents, which is the contents that is un-rar'd gets deleted from SickChill after copying process has completed. But instead all contents, download rar files + extracted contents are kept.
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
If your process method is copy it doesn't work that way, only if it is move

**Comment by JDubbedN** [comment]
The wording is confusing then. In the SickChill settings it states...

"Delete RAR contents
delete content of RAR files, even if Process Method not set to move?
note: only working with RAR archive"

To me that says even if process is not set to move, which I have it to set copy, it will still delete rar contents. What am I missing?

**Comment by miigotu** [comment]
Idk why you would use copy at all. It uses double the drive space. If you use hard link (or reverse symlink when shows and downloads are on different drives) it just uses the space one time and you can keep seeding. For rars then it falls back to move.

**Comment by miigotu** [comment]
Anyways, I just made some changes to it because I think it is more complicated than it needs to be. No changes will be on master, we are strictly using python3 now and practically a million lines changed there in the develop branch.

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/commit/ba493e916381bc5184cc665c540e0dfc369e46ca

**Comment by JDubbedN** [comment]
Good question.

I looked into the reverse symlink and and hard link. The problem is that because there is no way to filter out compressed files downloads in SickChill besides the naming convention which my torrent source doesn't seem to follow, SickChill downloads torrent files with rar'd files. Thus I have to leave the rar'd files intact to keep the seeding going otherwise I am flagged with hit and runs. So I need to seed to at least 1:1. Problem is that Plex does not support reading from compressed files. So I have SickChill process and unpack the rar's, and copy the content to the Plex directory. This of course will leave 2 copies. One that is rar'd that will be seeding, and another copy in the Plex directory. No hard linking or reverse symlinking will save me space with this problem because I have two have the rar'd copy for seeding and the unpacked contents for Plex to be able to read the content.

Now. A solution I found is that I have added a physical HDD to my server to handle seeding and unpacking only. This HDD also contains the downloading/completed/torrent files/unpacking directories that utorrent and SickChill will use to watch and process its scripts. Then SickChill unpacks and copies the media content to the other HDD that contains the Plex server. This setup stills creates two copies, but the rar copy as well as the unpacked copy (that for some reason SickChill won't delete after copying over to the Plex server even though I have that option checkmarked) stay on the seed drive and won't take away from my actual active drive I use for my media. I also have all my downloads unpacked in a different directory so I can easily "flush" the unpacked folder every so often since for some reason SickChill isn't doing that(maybe I am misunderstanding that option).

Anyways, hope that makes sense. I guess my setup is a bit on the unusual side but I hope this information helps you make SickChill that much better.

**Comment by miigotu** [comment]
@JDubbedN with hardlink or symlink it will extract the file and MOVE the contents, then delete the files left in the extract folder, and leave the rar file for seeding.

**Comment by JDubbedN** [comment]
@miigotu Thank you for that clarification. I don't think hardlink will work because it doesn't support separate HDD's from what I've read. And I am using a separate HDD for seeding because I do not want rar's taking up space on my Plex server drive. Once SickChill can filter out rar's or my torrent source introduces a naming policy (doubtful) then I can go back to using a single drive drive I believe.

**Symlink seems to support 2 separate drives so I am going to test it and see how it works. Do I still need to checkmark the setting in SickChill "Delete RAR contents"?**

**Comment by miigotu** [comment]
Yes check the box, and then to keep the space used only on your downloads drive you use symlink. To mv it to the Plex drive and then create a symlink to it for your downloader to find it use reverse symlink.

Just depends where you want the space used and if your downloader follows symlinks.

Reverse is probably best, because it leaves rars on the download drive, regular files moved and symlinked back, and contents of rars moved to Plex drive. This way you split the space a little better

**Comment by miigotu** [comment]
@JDubbedN btw idk if you got this yet: https://discord.gg/U8WPBdf
