### ISSUE TITLE
Default 'Progress' sorting

### ISSUE THREAD

**Issue by vmdude** [SickChill/SickChill#6670]
Hi,

I'm using the 'Progress' sort-by option for the Shows view (with layout Poster), and some time ago the sorting used to work like:
- first displaying shows with missing (aka not yet downloaded) episodes, then displaying remaining shows based on their **title**

Some update ago this change to:
- first displaying shows with missing (aka not yet downloaded) episodes, then displaying remaining shows based on their **episodes count**

Is there any way to get a title-based sorting with missing episode shows put in front line (as before?)

**Comment by miigotu** [comment]
Click to sort any column header, then hold down the alt key and select a second column. Continue selecting columns as desired.

**Comment by vmdude** [comment]
I don't have any columns, I was talking about the main "Shows" view, not the singular show view:

![image](https://user-images.githubusercontent.com/1384259/91013816-926cd200-e5e8-11ea-8a37-a4bb1f08d50d.png)

**Comment by miigotu** [comment]
If you are sorting by progress, it sorts by the progress percentage. Meaning if a show has 100/100 it is 100%, 99/1000 is 0.99%, 99/100 is 99%
It never sorted by title, it always sorted by progress (percentage completed)

**Comment by vmdude** [comment]
Yes but the sorting of all the 100% shows (for instance starting in the 2nd row in my screenshot) was based on name some time ago, not episode count
