### ISSUE TITLE
Sickchill wont load - refuses connection

### ISSUE THREAD

**Issue by LordXLordX** [SickChill/SickChill#6674]
I was many commits behind, so I updated. As soon as it updated, I was not able to get back in. I can't get in at all, so I don't know how to pull logs if that is even possible now.

I tried the STOP, Git develop, Git pull, START that I read on the forums. Still connection refused after those steps completed.

It looked like the git pull command worked, as I saw it 'updating' in the CMD window.

My system: Windows 10 64, Chrome browser.

Is there something else I need now with these newer commits to get it to work? I would love not to lose my show database!

**Comment by miigotu** [comment]
#6230

However, in about a week you will be behind 256+ commits and need manual intervention, because we are moving to pure python3+movies

**Comment by LordXLordX** [comment]
What do I need to do manually?

**Comment by LordXLordX** [comment]
I followed the instructions in thread #6230 - it is still refusing connection

**Comment by LordXLordX** [comment]
Do I need python v3 installed?

**Comment by LordXLordX** [comment]
Uninstalled and reinstalled - web interface appears to be working - no pictures on thumbnals - but I dont mind that - as long as it grabs shows.
