### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: 'C:\\SickChill\\SickChill\\sickchill\\gui\\slick\\images\\network\\citv.png'

### ISSUE THREAD

**Issue by Yoshi900** [SickChill/SickChill#6683]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.14393-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@8d6cd262a47df380d48358a56c0ab0ebba54766f
No Log available with ERRORS:
### ERROR
```
Could not open static file %r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
This image is missing. You can add this image through PR or pass it to me here. The background should be transparent and it should be sized 64x32

**Comment by pnsbttl** [comment]
### INFO
Python Version: **2.7.18 (default, Apr 20 2020, 19:51:05) [GCC 9.2.0]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@99336df163c7e776c7931d864e84d1f0f83afe4d
Link to Log: https://gist.github.com/0a471ac62a2081b22aeca65e0a62bd4f
### ERROR
```
POSTPROCESSOR-MANUAL :: [99336df] Unable to run synoindex: error 2 : No such file or directory
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
@pnsbttl delete that gist, it has sensitive info. Also, fix your synoindex binary.

**Comment by pnsbttl** [comment]
Hi
Thank you for your fast answer.
What is gist and how to delete it?

Thank you in advance for your answer!

**Comment by miigotu** [comment]
https://gist.github.com/0a471ac62a2081b22aeca65e0a62bd4f
Go to that link and click the delete button on the top right
