### ISSUE TITLE
After change to PIP installed SickChill I get error 'Could not open static file'

### ISSUE THREAD

**Issue by bluezed** [SickChill/SickChill#6684]
Branch/Commit: PIP / sickchill 0.0.56 (master / c115315d5214cd6028051f7b69951df5174ef4d4)
OS: Ubuntu 20.04
Browser: Firefox 80

What you did: 
I installed SickChill using PIP and moved my config and db over to the new installation.

What happened:
It all seems to work ok but I get the error below in the log several times.

What you expected:
No error

Logs:
```
2020-09-06 13:32:09 ERROR :: WEBSERVER-HOME_0 :: Could not open static file '/home/xyz/.local/lib/python3.8/site-packages/sickchill/gui/slick/images/network/ctv drama (bravo).png'
```

**Comment by Nyaran** [comment]
That means the request network image doesn't exists. You can add the icon to this folder: https://github.com/SickChill/SickChill/tree/master/sickchill/gui/slick/images/network and create a PR with it

**Comment by bluezed** [comment]
@Nyaran Thanks but I don't actually have that icon and I don't know why it's asking for it. None of my shows are on that channel, as far as I know... And before the change over this message wasn't there...

**Comment by Nyaran** [comment]
Try to set the layout to "Simple" and, on "Network" column, filter with "CTV Drama"

SickChill gets the network info from TheTVDB, so maybe someone sets a series with a wrong network or something

**Comment by Nyaran** [comment]
Check the network logos rules: https://github.com/SickChill/SickChill/wiki/Network-logos
