### ISSUE TITLE
python3 debug logging requires a restart

### ISSUE THREAD

**Issue by thargan81** [SickChill/SickChill#6691]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/74d5f98ee
OS: Debian
Browser: Firefox
What you did: Enabled / Disabled debug logging
What happened: After turning on debug logging for raising #6690 nothing was written to the log until sickchill was restarted
What you expected: The logging level to change without a restart, as was previously the case.
Logs:
```

```

**Comment by miigotu** [comment]
It always has ^ but I can probably make that work without a restart

**Comment by miigotu** [comment]
Works fine here. You have to reload the logs page after saving advanced settings, and change the dropdown to debug

**Comment by thargan81** [comment]
That's not the issue. What's happening is I toggle debug logging, either on or off, and then nothing is written to the logs until I restart sickchill entirely.
