### ISSUE TITLE
Sickchill not starting after last update

### ISSUE THREAD

**Issue by YanPelletier** [SickChill/SickChill#6692]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: FreeNAS # FreeBSD
Browser: N/A
What you did: service sickchill start
What happened: Trace
What you expected: Starting sickchill
Logs:
```
Starting sickchill.
Traceback (most recent call last):
  File "/usr/local/sickchill/SickBeard.py", line 67, in <module>
    import sickbeard
  File "/usr/local/sickchill/sickbeard/__init__.py", line 41, in <module>
    import sickchill
  File "/usr/local/sickchill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/usr/local/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/usr/local/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/usr/local/sickchill/sickchill/logger.py", line 69
    msg = re.sub(fr'\b({item})\b', '*' * 8, msg)
                                ^
SyntaxError: invalid syntax
/usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill
```

**Comment by miigotu** [comment]
SickChill is python3 only now, you will need to back up your databases and config.ini and set the jail/package up again.
I have a PR up for an iocage: https://github.com/freenas/iocage-ix-plugins/pull/249

**Comment by stynoo** [comment]
fwiw it runs like a champ with python38/py38-sqlite3 installed.

**Comment by Raboo** [comment]
@miigotu what is the simplest way to revert sickchill to a python2 version until your PR has been fixed? afaik py3X-sqlite3 is not available in my my iocage 11.3 jail.

@stynoo How did you get py38-sqlite3 for your iocage jail?
```
root@freenas:~ # iocage upgrade -r 12.1-RELEASE sickchill

Host: 11.3-RELEASE is not greater than target: 12.1
This is unsupported.
```

**Comment by miigotu** [comment]
@Raboo you can use py36 or py37

**Comment by stynoo** [comment]
> @stynoo How did you get py38-sqlite3 for your iocage jail?
mhh, my iocage jails are running on 11.3-RELEASE-p9.

**Comment by AlanKellyEire** [comment]
@miigotu what is the last version/commit that supported python 2 so i can update to that until i have time to sort out a new jail

**Comment by miigotu** [comment]
> @miigotu what is the last version/commit that supported python 2 so i can update to that until i have time to sort out a new jail

The python2 branch

**Comment by miigotu** [comment]
The official iocage is live for TrueNAS CORE btw
