### ISSUE TITLE
Deluge labels not working

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#6693]
Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/64e55244d9bdc6d9012eaff214f3b254dc16df1f
OS: windows 10
Browser: chrome
What you did: nothing (also, when manually selecting a torrent/magnet from the awesome list you made! :D )
What happened: torrent/magnet added to deluge - no label set
What you expected:torrent/magnet added to deluge - label set

Nothing more to say, really. This started happening on the last update to the py2 version and I was hoping the new version would fix it. Please let me know if you need more info.

**Comment by miigotu** [comment]
Make sure your labels plugin is enabled:
![image](https://user-images.githubusercontent.com/390379/92422408-4a52c100-f14b-11ea-91d5-01dcc3512f9a.png)

It is working here:
![image](https://user-images.githubusercontent.com/390379/92422472-9140b680-f14b-11ea-83d4-6ebd62eb7a2d.png)
![image](https://user-images.githubusercontent.com/390379/92422518-b2a1a280-f14b-11ea-9438-0fac8af054a4.png)

**Comment by Tiwas** [comment]
@miigotu Thanks. I'm using the DelugeD option as my daemon is on a box. 
![image](https://user-images.githubusercontent.com/17053402/92434548-66348200-f1a0-11ea-8505-e6ab235f810b.png)
![image](https://user-images.githubusercontent.com/17053402/92434578-7a787f00-f1a0-11ea-9692-7e4174783cf5.png)

I'm not sure about the daemon version, but it should be the latest. My client is 1.3.15 (latest available for windows).

As you can see, labels are in use.
![image](https://user-images.githubusercontent.com/17053402/92434715-d8a56200-f1a0-11ea-8021-3344c3efe72a.png)


This used to work just a couple of weeks back.

**Comment by Tiwas** [comment]
Also, this was just tested on the latest version of SC
![image](https://user-images.githubusercontent.com/17053402/92434834-291cbf80-f1a1-11ea-9317-c88f4e9d2b16.png)

**Comment by miigotu** [comment]
And what about the debug logs?

**Comment by Tiwas** [comment]
Sorry.

![image](https://user-images.githubusercontent.com/17053402/92438639-77ce5780-f1a9-11ea-95c1-9e6acdfd858c.png)
The "unable to send torrent" kind of puzzles me as it will, indeed, end up in deluge.

**Comment by miigotu** [comment]
I'll have to figure out how to set up deluged, I was testing with regular deluge web client

**Comment by miigotu** [comment]
This is the log line I needed:
```bash
2020-09-08 14:06:55 DEBUG :: SEARCHQUEUE-MANUAL-376837 :: DelugeD: label plugin not detected
```

**Comment by Tiwas** [comment]
When manually selecting a version, label is not set. Do you need additional logs, or is it just the same typo in another function?

**Comment by miigotu** [comment]
Already know this. The result has no show when using manual selection yet so it cannot check of the show is anime or not.
