### ISSUE TITLE
New show folders and files are 'root' - Synology DSM

### ISSUE THREAD

**Issue by BKSteve** [SickChill/SickChill#6697]
SickChill Info: Branch: master
Commit: 64e55244d9bdc6d9012eaff214f3b254dc16df1f
Version: v2020.09.06-7
Database Version: 44.2
Python Version: 3.7.7 (default, Aug 18 2020, 20:42:48) [GCC 4.9.3 20150311 (prerelease)]
OS: Linux-4.4.59+-x86_64-with-glibc2.2.5

Folders and Files created by Sickchill on Synology NAS are created with permissions of owner 'root' user group 'root'

I added a new show in Sickchill and the expected the folder to be created with the owner of who ran Sickchill and the user group to be sc-download, user, sickchill, or with inherited permissions.

The image shows Prodigal Son and the log is Ratched both gave the same result.
Folder permissions contain user 'admin' and group 'administrators' as the only 2 entries. 

Logs don't really contain anything.
 ```
2020-09-07 20:30:30 INFO :: SHOWQUEUE-ADD :: Done cache check
2020-09-07 20:30:25 INFO :: SHOWQUEUE-ADD :: 364870: Updating NFOs for show with new indexer info
2020-09-07 20:30:08 INFO :: SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2020-09-07 20:30:07 INFO :: SHOWQUEUE-ADD :: Starting to add show by ShowDir: /volume1/Media/Series/Q-T/Ratched
2020-09-07 20:29:17 INFO :: SHOWQUEUE-REMOVE-SHOW :: Deleted show folder /volume1/Media/Series/A-D/Ratched
```
Debug logging gave less information than the above normal logging with debug set off.

![Sickchill-DMS-Folder](https://user-images.githubusercontent.com/10173496/92393070-79683300-f149-11ea-93be-7adea76aada7.png)

Edit: Having now collected new files and had them post processed by Sickchill their permissions are also root/root leaving them inaccessible to most users.

**Comment by miigotu** [comment]
@BenjV thoughts?

**Comment by BenjV** [comment]
Yes something when wrong when I created a Synology package for Python 3.
I removed that package from my github and will investigate and fix this as soon as possible.

**Comment by BenjV** [comment]
I rewrote the complete installation package for SickChill for Python 3 and posted it on this repositary.
You can find it here.
https://github.com/BenjV/SYNO-packages
Download the package to your PC for a manual install.
Make sure you installed Python 3 from the SynCommunity first.

If you already have a SickChill version running, please make a backup from within SickChill.
Then remove that package, manual install the new one, start it and restore the backup from within SickChiil.

Enjoy.
