### ISSUE TITLE
Need instructions to start SickChill as a service

### ISSUE THREAD

**Issue by modem** [SickChill/SickChill#6698]
Hi,

If SickChill is setup using the pip3 command, how could we setup the service to automatically start SickChill at boot time in a linux environment (I'm using Raspbian)?

Thanks!

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
I would do a `whereis SickChill.py` and use that path/with/SickChill.py in the service script, just the same as any other install.

**Comment by modem** [comment]
Well, my main difficulty is on how to create the service script... I will google it.
