### ISSUE TITLE
Issue: Py3 + adding movie causing DB key conflict error

### ISSUE THREAD

**Issue by heymoe** [SickChill/SickChill#6700]
Branch/Commit: PIP/2020.9.6.post7
OS: Linuxserver/SickChill docker (new Py3 version)
Browser: Any

**What you did**:
After upgrading to the Py3 version of SickChill I noticed a new "Movies" drop down and decided to try and see how it worked. I selected Movies->Add Movies, selected the "Popular on IMDB" tab and added a movie from the list. So far so good. Going to "Movies->Movie List" listed the one movie I just added. I then went to add a second movie using the same steps as above ...

**What happened**:
but this time I got a Mako Error screen and a "Show Hidden Error" button which I've cut-n-pasted below in the Logs section. This error page shows up every time I go to the "Movie List" page now. It doesn't show any of the movies I added. It looks like the second add DB transaction is stuck trying to add a conflicting key for the second movie I tried to add.

It looks like all the non-Movie stuff is still working. 

**What you expected**:
Seeing 2 movies in the "Movie List" and no errors. 

**Logs**:
```
Mako Error

A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.
--- Hidden Error Info ---
File /usr/lib/python3.8/site-packages/sqlalchemy/orm/session.py:289, in _assert_active:
   raise sa_exc.InvalidRequestError(
   InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new 
     transaction with this Session, first issue Session.rollback(). Original exception was: New instance  with identity key (, ('Sci-Fi',), 
     None) conflicts with persistent instance  (Background on this error at: http://sqlalche.me/e/13/7s2a)
```

**Comment by miigotu** [comment]
The movies section is not supposed to be seen by users yet. You have developer mode enabled lol

**Comment by miigotu** [comment]
Closing this because I knew it existed =P
