### ISSUE TITLE
Can't view log after update

### ISSUE THREAD

**Issue by explor202** [SickChill/SickChill#6705]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/d91d22fe3b2079a63001086c3323a9b0269fed70
OS: Windows 8.1
Browser: Chrome, FF
What you did: Tried to view log, error was generated. Tried to submit, but another error was generated
What happened: Log page is blank on host, on remote shows error "This page isn’t working, XX.X.X.XX is currently unable to handle this request.
What you expected: To see the log
Logs:
```
PASTE LOGS HERE
2020-09-07 18:23:36 Traceback (most recent call last):
File "C:\SickChill\SickChill\sickchill\logger.py", line 234, in submit_errors
__log_data = log_f.readlines()
File "C:\SickChill\Python3\lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1152: character maps to

2020-09-07 18:23:22 Uncaught exception %s
%r

**Comment by explor202** [comment]
I should note this is trying to use the "View Log" option in the UI.

**Comment by miigotu** [comment]
Stop sickchill and rename the Logs folder:
```bash
net stop sickchill
rename c:\SickChill\Data\Logs c:\SickChill\Data\old_logs
net start sickchill
```

**Comment by explor202** [comment]
I was able to stop the service but kept getting a "syntax of the command is incorrect" error message using CMD to rename the log folder. However manually renaming it worked, and now it seems fixed. Thanks!
