### ISSUE TITLE
error authenticating to qBittorrent

### ISSUE THREAD

**Issue by smilerz** [SickChill/SickChill#6706]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: v2020.09.08-1
Getting an error authenticating to qBittorrent - debug logs show no additional information.  Manually testing qbittorrent connection returns success
```
2020-09-08 14:38:16 WARNING :: SEARCHQUEUE-MANUAL-368643 :: qBittorrent: Authentication Failed
```

**Comment by smilerz** [comment]
this may be related to v2 of the qbittorrent API - older version of sickchill (IIRC) had a qbittorrent v2 configuation

**Comment by huhwhatwho** [comment]
Same problem here and in addition, black hole isn't working either.

**Comment by miigotu** [comment]
> this may be related to v2 of the qbittorrent API - older version of sickchill (IIRC) had a qbittorrent v2 configuation

This is the qbit V2 provider.

**Comment by miigotu** [comment]
> Same problem here and in addition, black hole isn't working either.

Ofc black hole is working. As is rtorrent, deluge, deluged, transmission. I personally verified all of those within the past 24 hours.

I will look into qbittorent, and emby (the only 2 known possibly broken things right now) - when I get up tomorrow.
