### ISSUE TITLE
404 not found when trying to use ipv6 transmission

### ISSUE THREAD

**Issue by pgmillon** [SickChill/SickChill#6707]
Branch/Commit: docker image from master (image sha1: aa06d354f449)/commit:d91d22fe3b2079a63001086c3323a9b0269fed70
OS: ArchLinux
Browser: FF79.0
What you did: Setup transmission URL to http://my.domain.resolving.ipv6:9091 + hit the test connection button
What happened: got a [Errno 404] Not Found in the UI and a single logline even with debug logs
What you expected: Connection successful
Logs:
```
INFO :: WEBSERVER-HOME_0 :: Request failed: [Errno 404] Not Found ()
```

**Comment by miigotu** [comment]
The machine SC is on has to be able to resolve ip6, aka an ip6 enabled dns, and SC might need bound to both ip4 and ip6.
This isn't a bug, but if you can provide more info on how to improve it I can help. For now I'm going to close this because I currently do not have ip6 set up and its a headache to even try when we arent even close to running out of ip4 yet =P

**Comment by pgmillon** [comment]
Hi,
SC is running on an ipv6-capable machine as docker container: DNS resolution & ping of the transmission host from the container works great:
```
/app/sickchill # ip a
...
39: eth0@if40: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:11:00:03 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.3/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2001:bc8:604:.../66 scope global flags 02 
       valid_lft forever preferred_lft forever
/app/sickchill # ping bt.***
PING bt.*** (2001:bc8:604:...): 56 data bytes
64 bytes from 2001:bc8:604:... seq=0 ttl=64 time=0.056 ms
64 bytes from 2001:bc8:604:... seq=1 ttl=64 time=0.061 ms
64 bytes from 2001:bc8:604:... seq=2 ttl=64 time=0.157 ms
```
Steps to reproduce:
- Get an ipv6 ubuntu development box from scaleway.com (0,01€/h)
- install transmission-daemon + docker
- enable ipv6 for docker:
```
/etc/docker/daemon.json 
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:bc8:604:1714:7000::/66"
}
```
- run SC container
```
docker run --rm --name sickchill \
  -p 127.0.0.1:8081:8081/tcp \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Paris \
  sickchill/sickchill
```
- setup SC to use host ipv6 as transmission host -> 404

**Comment by miigotu** [comment]
Did you try going to config/general and enabling `Listen on IPv6` and restarting?

**Comment by pgmillon** [comment]
Hi,
Yes it's enabled:
![image](https://user-images.githubusercontent.com/715479/92891036-eb759c00-f417-11ea-9945-92d409e3afd6.png)
