### ISSUE TITLE
Install Error: SickChill had a failure Exception: RuntimeError Message: Last 10 lines: fetch: 

### ISSUE THREAD

**Issue by Jared575** [SickChill/SickChill#6712]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 
OS: TrueNas 12 BETA 2.1
Browser: Chrome
What you did: installed sickchill using community plugins
What happened: install fails
What you expected: install to work
Logs:

"Install
Error: SickChill had a failure Exception: RuntimeError Message: Last 10 lines: fetch: https://github.com/SickChill/SickChill/archive/master.tar.gz: size of remote file is not known master.tar.gz 32 MB 1862 kBps 18s cp: /usr/local/sickchill/runscripts/init.freebsd: No such file or directory chmod: /usr/local/etc/rc.d/sickchill: No such file or directory Partial plugin destroyed"

Rolled back to a non beta freenas 11.3 however the issue persists. All my other plugins are working. Before the re-install an in plugin update was available and updating caused the browser to become inaccessible. Cleared out the plugin and storage and was attempting to re-install the plugin from new and run into this error.

**Comment by miigotu** [comment]
Make a new iocage
https://github.com/ix-plugin-hub/iocage-plugin-sickchill/pull/1
https://github.com/ix-plugin-hub/iocage-plugin-index/pull/106

**Comment by Jared575** [comment]
Thanks, I don't exactly know what you mean by "make a new iocage." I've followed the steps to make sure my truenas build is using the latest iocage repositories, it shows two 11.3 release and 12.1  release and all my plugins use the 12.2 except sickchill that despite upgrades before this would only use the 11.3 release.

**Comment by miigotu** [comment]
There is a new iocage, I need to make an adjustment to it but I'll post back here for the one you can use

**Comment by miigotu** [comment]
@Jared575  As soon as https://github.com/ix-plugin-hub/iocage-plugin-sickchill/pull/1 is merged everything should be copacetic, with the 12.1 release

**Comment by miigotu** [comment]
Or, for the time being, you could use this json:
```json
{
    "name": "SickChill",
    "plugin_schema": "2",
    "release": "12.1-RELEASE",
    "artifact": "https://github.com/sickchill/iocage-plugin-sickchill.git",
    "pkgs": [
        "git",
        "python3",
        "python37",
        "py37-pip",
        "py37-setuptools",
        "py37-sqlite3",
        "unrar",
        "ca_root_nss",
        "py37-pillow",
        "libmediainfo"
    ],
    "properties": {
        "nat": 1,
        "nat_forwards": "tcp(8081:8081)"
    },
    "packagesite": "http://pkg.FreeBSD.org/${ABI}/latest",
    "fingerprints": {
        "iocage-plugins": [
            {
                "function": "sha256",
                "fingerprint": "b0170035af3acc5f3f3ae1859dc717101b4e6c1d0a794ad554928ca0cbb2f438"
            }
        ]
    },
    "official": false,
    "revision": "0"
}
```

**Comment by Jared575** [comment]
Thanks! I have no idea what that JSON stuff was and what to do with it... Way above my pay grade of understanding. I'll let you do your update and let me know what to do when that's updated :) cheers

**Comment by miigotu** [comment]
I'm not sure how you update your plugin index, but the plugin for sickchill is live for freenas/trueos
Go with the 12.1-RELEASE version

**Comment by Jared575** [comment]
Funny I was just coming to see if anything was sent as this message popped up. I'm not sure how FreeNAS/TrueNAS community pulls work I just install plugins from the gui. I've tried in the past to install jails myself but they never work and never been able to figure out why haha. Thanks for the updates!

**Comment by Jared575** [comment]
I know by default the plugins update quarterly and I know how to, after they're installed, edit the configuration to update to latest instead of quarterly but unsure how or if it's possible to update plugins to latest that aren't already installed... Is that possible?

**Comment by miigotu** [comment]
I want to think that if you just uninstall the SickChill plugin from the gui and reinstall it that it will use the newer version

**Comment by Jared575** [comment]
Yeah I think the way FreeNAS and iocage plugin repositories are set up that there is a quarterly delay between the plugins being updated to the latest versions. Once a plugin is installed you can set it to do latest updates instead of quarterly or like SickChill updates can be made from inside the installed plugin... I'm not sure how or if it's possible to tell the plugin to pull the latest version to install... Guess I gotta figure out how to manually create and install a jail/plugin! Thanks for the updates 

Install
Error: Jail: SickChill has a missing configuration, please check that the dataset is mounted.

**Comment by miigotu** [comment]
@fireph do you know how to use the json to create jails?

**Comment by fireph** [comment]
It seems like if you have the plugin json file cached locally it will not download the new one. I wonder if the "revision" field needs to be incremented for FreeNAS to pull down the updated plugin json?

https://github.com/ix-plugin-hub/iocage-plugin-index/blob/master/sickchill.json#L32

**Comment by miigotu** [comment]
@fireph the updater has not been removed. Pip installs are better, but do not update themselves from inside SC, git and source installs still do.

**Comment by fireph** [comment]
@miigotu how do you use the updater now? The "Update now" link at the top of the web ui just takes me to https://pypi.org/project/sickchill/2020.9.10.post3/

**Comment by fireph** [comment]
@miigotu Ah I see the problem now. I have sickchill setup without pip in my FreeNAS jail, but I am using a config.ini/sickchill.db backup which at one point was running inside a pip sickchill install. It seems that it is permanently stuck thinking it is a pip install rather than a git/source install. Any way to force sickchill to recheck what kind of install it currently is?

**Comment by miigotu** [comment]
Stop the service and change git_branch to master in the ini

**Comment by fireph** [comment]
@miigotu It seems to revert back to "branch = pip" when the service is started. :(

**Comment by Jared575** [comment]
So I figured out how to pull an install into a plugin from the master branch:

"   iocage fetch -P sickchill -g https://github.com/ix-plugin-hub/iocage-plugin-index --branch 'master'    "

and everything goes smoothly but it keeps aborting at the end saying this:

 /usr/local/bin/python3: can't open file '/usr/local/sickchill/SickChill.py': [Errno 2] No such file or directory
Starting sickchill.
/usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill
Last 10 lines:
Cloning into '/usr/local/app/sickchill'...
mkdir: /usr/local/etc/rc.d: File exists
/usr/local/bin/python3: can't open file '/usr/local/sickchill/SickChill.py': [Errno 2] No such file or directory
/usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill
SickChill had a failure
Exception: SystemExit Message: 1
Partial plugin destroyed

**Comment by fireph** [comment]
ya https://github.com/SickChill/SickChill/blob/master/contrib/runscripts/init.freebsd needs to be updated to point at the right install location.

this line:
`: ${sickchill_dir:="/usr/local/sickchill"}`

needs to be changed to this:
`: ${sickchill_dir:="/usr/local/app/sickchill"}`

**Comment by Jared575** [comment]
SO IT'S NOT ME. Just when I thought I was finally wrapping my head around the shell that issue popped up and I was like WHAT DID I BREAK. Okay so just gotta wait for that or is there a way to change it for the install "manually?"

**Comment by miigotu** [comment]
Done in the master branch, try again (can't do my normal release process my laptop is doing an upgrade to focal rn)

**Comment by miigotu** [comment]
@fireph for the branch, you should `pip uninstall sickchill` if you aren't using the pip version.

**Comment by fireph** [comment]
Hmmmm, I did pip uninstall... I might have to recreate the jail entirely too make sure there are no sickchill pip remnants that are messing things up.

**Comment by Jared575** [comment]
THANK YOU, IT WORKS!!!!

**Comment by fireph** [comment]
oof, even after recreating the jail and doing everything the same as the plugin, it still reverts the branch back to pip every time the service is started.

how does the branch detection work currently? maybe I can fix how the detection code works so that this doesn't happen for others.

**Comment by miigotu** [comment]
@fireph it checks if it is installed here: https://github.com/SickChill/SickChill/blob/b9b47db27c9967dcc5f38155f71c61c02814ca08/sickchill/init_helpers.py#L32

**Comment by miigotu** [comment]
And sets the install type here: https://github.com/SickChill/SickChill/blob/b9b47db27c9967dcc5f38155f71c61c02814ca08/sickchill/update_manager/runner.py#L212

Go to the help&info page and make sure you are editing the correct config.ini, and make sure sickchill is completely stopped before editing the config.ini

**Comment by fireph** [comment]
@miigotu Ah I figured it out.
`sysconfig.get_paths().values()` returns `[ ... , "/usr/local" ]` which means that the install location of the jail `/usr/local/app/sickchill` will result in it thinking that it is installed using pip (I use `/usr/local/sickchill` but the same thing will happen in the plugin)

maybe there is a better way to get the location of pip plugins in python and check if it is installed in that directory?

**Comment by miigotu** [comment]
There likely is, but idk how right this second.
