### ISSUE TITLE
Manual post processed files are losing all permissions after being post processed

### ISSUE THREAD

**Issue by Ventje23** [SickChill/SickChill#6713]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / d91d22fe3b2079a63001086c3323a9b0269fed70
OS: Linux-4.4.59+-x86_64-with-glibc2.2.5
Browser: Chrome
What you did: I post processed three episodes of one and the same show
What happened: After being post processed the files lost all their permissions
What you expected: all files keeping their permissions
Logs: not available
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
I assume this is a synology and you installed benjv's package that made everything owned as root.
Thats a lot of assumptions, because nothing ever "loses permissions", they are just changed to something you do not expect. Try searching the open/closed issues for your specific device.

**Comment by Ventje23** [comment]
@miigotu ,

thanks for the feedback!
you made the correct assumptions. Probably best to wait till benjv released a new package and then check it again.

**Comment by miigotu** [comment]
Try this one
https://github.com/SickChill/SickChill/issues/6545#issuecomment-690941285
