### ISSUE TITLE
After reinstalling Windows 10 Sickchill won't run

### ISSUE THREAD

**Issue by Framston** [SickChill/SickChill#6714]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Windows 10
Browser: Chrome
What you did: Reinstalled Windows 10, reinstalled sickchill with the latest version
What happened: Sickchill won't run.  I get the site can't be reached screen.  When I try to stop sickchill, it tells me the service is not running.  When I try to start the service I get System error 5 has occurred. Access is denied.
When I try to start it from admin prompt  it says The Sickchill service could not be started.  A service specific error occurred: 3.
What you expected: I expected it to run like it did before the reinstalls.
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Admin prompt,
```bash
net start sickchill
```
What does it say?

**Comment by Framston** [comment]
C:\SickChill\SickChill>net start sickchill
The SickChill service is starting.
The SickChill service could not be started.

A service specific error occurred: 3.

More help is available by typing NET HELPMSG 3547.

**Comment by Framston** [comment]
C:\SickChill\SickChill>net helpmsg 3547

A service specific error occurred: ***.

**Comment by miigotu** [comment]
```bash
c:\sickchill\python3\python.exe c:\sickchill\sickchill\sickchill.py --datadir=c:\sickchill\data --port 8081
```

What's the output there? When did you last try to uninstall and reinstall? Several releases have come

**Comment by Framston** [comment]
When I tried your last script, I found that there was no python3 folder under sickchill. No idea why as this was an install of your latest install package for Windows, but I ran the python repair, and everything is back to the way it was before re-installing Windows plus the 5 updates.

Thanks so much, I wouldn't have figured it out without your help.
