### ISSUE TITLE
Problems with Qnap install

### ISSUE THREAD

**Issue by Dohnerd** [SickChill/SickChill#6720]
Im using QSickChill and get the famous "Local branch is ahead of master. Automatic update not possible."

The problem seems to be that QSickChill auto uses the system python standard, so even though I have python3 installed it still uses 2.7, as shown below:

[/share/CACHEDEV1_DATA/.qpkg/QSickRage] # which python
/opt/bin/python

[/share/CACHEDEV1_DATA/.qpkg/QSickRage] # python -V
Python 2.7.16

[/share/CACHEDEV1_DATA/.qpkg/QSickRage] # python3 -V
Python 3.8.0

[/share/CACHEDEV1_DATA/.qpkg/QSickRage] # ./QSickRage.sh start                
QSickRage prestartup checks...
 Checking for git...Git Found!
Looking for /usr/bin/python2.7
Looking for /usr/local/bin/python2.7
Looking for /opt/bin/python2.7
Looking for /Apps/opt/bin/python2.7
Looking for /opt/QPython2/bin/python2.7
Found Python Version 2.7.16 at /opt/bin/python2.7
Updating QSickRage
HEAD is now at 99336df1 Merge branch 'develop'
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
warning: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log.
Automatic cleanup will not be performed until the file is removed.

error: Could not read 23078bb65d88344335a2beea58c3632fefe641c6
fatal: Failed to traverse parents of commit dcb10ca58166f24a82ebe65fadb05185b7de8c0d
fatal: failed to run repack

HEEELLPP :)

**Comment by miigotu** [comment]
https://forum.qnap.com/viewtopic.php?t=132373 Use sherpa

**Comment by Dohnerd** [comment]
Wouldnt that erase my setup?

**Comment by miigotu** [comment]
just copy your db and config.ini out first, then after install stop the service and copy them where they go

**Comment by Dohnerd** [comment]
That just made it worse, not i dont even have a working SickChill anymore :/

[/share/CACHEDEV1_DATA/.qpkg/SickChill] # ./sickchill.sh start
daemon: NOT active
file (/opt/bin/git): exists
updating 'SickChill' from remote repository: OK
installed git branch: develop
file (/opt/bin/python3): exists
starting daemon: failed!
= ExecuteAndLog()
output: "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/locale
/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/locale
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/tv.py", line 21, in <module>
    import sickchill.oldbeard.providers
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/oldbeard/providers/__init__.py", line 4, in <module>
    import sickchill.oldbeard.helpers
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/oldbeard/helpers.py", line 2, in <module>
    import ctypes
  File "/opt/lib/python3.8/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.7: cannot open shared object file: No such file or directory"
result: [1]
[/share/CACHEDEV1_DATA/.qpkg/SickChill] #

**Comment by Dohnerd** [comment]
Fixed that one my self :D Just reinstalled entware..

**Comment by miigotu** [comment]
So... Ask in the sherpa thread? 😉
