### ISSUE TITLE
[APP SUBMITTED]: No episode url found for %s, season %d, episode %d

### ISSUE THREAD

**Issue by burtal** [SickChill/SickChill#6724]
### INFO
Python Version: **3.7.9 (default, Aug 18 2020, 04:02:05) [GCC 9.3.0]**
Operating System: **Linux-3.10.105-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7fb144dafa850792df46dd5a3ebdf113ba705cf1
Link to Log: https://gist.github.com/c12766533fb015c5f9dd3739e9433776
### ERROR
```
No episode url found for %s, season %d, episode %d
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
That is subliminal, not SC.

**Comment by burtal** [comment]
what is subliminal ?  how do i disable it ?

**Comment by miigotu** [comment]
subtitles, subtitulamos and tusubtitulo providers

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]**
Operating System: **Linux-5.4.51-v7+-armv7l-with-debian-10.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@fc91063a06dbf81d239f974d531a17f515f7853a
No Log available with ERRORS:
### ERROR
```
No episode url found for %s, season %d, episode %d
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
