### ISSUE TITLE
is it possible to download a whole show (released as one file)

### ISSUE THREAD

**Issue by Ventje23** [SickChill/SickChill#6725]
This is actually a feature request:

is it possible to enhance sickchill with a feature to download the whole season of a show. More and more whole seasons are released as one file sometimes even before the seperate episodes are released. Sometimes only just the whole season and not the seperate episodes. e.g. Julie.And.The.Phantoms.S01.WEBRip.x264-ION10.

would be nice if it is possible to catch this too.

**Comment by miigotu** [comment]
Yes, as long as your provider supports it. You set the default on the search settings to prefer episodes or seasons, and there is a checkbox for whether to allow falling back to the other option.
