### ISSUE TITLE
sickchill will not start

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6726]
Installed sickchill in a new folder using the windows installer
There were no errors during the install.
At the end it asks if you would like to start sickchill,  I get a browser window that "Problem Loading Page" , "Cannot Connect"
The port is correct on LocalHost
Check the service for sickchill it is not running, Try to start it I get an error 3

![image](https://user-images.githubusercontent.com/14140816/92936064-a8b3c400-f417-11ea-9560-78e59bb79ddc.png)

I have uninstalled it twice and reinstalled but hit the same road block each time.
I also tried deleting the sickchill folder, and removing the pyc files.

sickchill v0.5.7
Windows 7

**Comment by miigotu** [comment]
Start it from the command line and see what the issue is.

`c:\sickchill\python3\python.exe c:\sickchill\sickchill\sickchill.py --datadir c:\sickchill\data`

**Comment by kendog819** [comment]
Having this exact same problem. 

`C:\Users\ken>c:\sickchill\python3\python.exe c:\sickchill\sickchill\sickchill.py --datadir c:\sickchill\data
The system cannot find the path specified.`

Also in event viewer:
`Failed to start service SickChill.  Program C:\SickChill\Python3\python.exe couldn't be launched. CreateProcess() failed: The system cannot find the file specified.`

**Comment by miigotu** [comment]
Uninstall python3 and sickchill and reinstall.

**Comment by kendog819** [comment]
> Uninstall python3 and sickchill and reinstall.

Did that multiple times. The only way for me to get it running was to create a "Python3" folder within the SC directory, and install Python to it.

**Comment by nydave69** [comment]
Has this been fixed?

**Comment by miigotu** [comment]
Yes, unless I messed up on updating the installer lol, 0.58
