### ISSUE TITLE
Download Station: unable to send torrent with Sickchill BenjV package

### ISSUE THREAD

**Issue by dragonslore** [SickChill/SickChill#6730]
I used to have Sickchill on my Synology using the Sick-Beard package on 2.7 python version.
Since Sickchill moved to Python 3 I looked for a way to upgrade it, Sick-Beard package failed so I downloaded the package "Sickchill from BenjV" and it works fine. 
I use the option "Send Torrent to: download station" and authentication is fine but still I get the error "Download Station: unable to send torrent"
I assume there is some rights issues somewhere but can't figure out where...

Branch: master
Commit: b416a59dfa5fc806a95a1a398c647841ba59c377
Version: v2020.09.11-2
Database Version: 44.2
Version de Python:3.7.7 (default, Aug 18 2020, 20:42:48) [GCC 4.9.3 20150311 (prerelease)]
Version SSL:OpenSSL 1.0.2n 7 Dec 2017
OS:Linux-4.4.59+-x86_64-with-glibc2.2.5 - Synology DSM 6.2.3-25426 Update 2
Browser: 85.0.4183.102

Logs: I get many of these
AA IndexError: list index out of range
AA result = self._series(self.search(name, language)[0]['id'])
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 63, in get_series_by_name
AA result = self.indexers[i].get_series_by_name(n, indexerid, language)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/handler.py", line 114, in search_indexers_for_series_id
AA settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/oldbeard/helpers.py", line 947, in get_show

**Comment by miigotu** [comment]
Do not use the benjv package. (there is a reason it has been removed from everywhere)
Use the package here: https://github.com/SynoCommunity/spksrc/pull/4161
