### ISSUE TITLE
Change text in /config/search/ on 'Torrent Search' tab from 'label' to 'category' - cosmetic

### ISSUE THREAD

**Issue by Smokey23** [SickChill/SickChill#6731]
Branch/Commit: Master

Of course edit in master, not whatever branch is referenced below.
 
https://github.com/SickChill/SickChill/blob/71e93aa512dbdad04e1c0f31750cd8188e8d05a1/sickchill/gui/slick/views/config_search.mako#L1051

https://github.com/SickChill/SickChill/blob/71e93aa512dbdad04e1c0f31750cd8188e8d05a1/sickchill/gui/slick/views/config_search.mako#L1077

Replace "label" with "category" to be consistent with qBittorrent UI

Thanks!

Smokey

**Comment by miigotu** [comment]
We have half a dozen different client options and this text is universal across all of them. Changing this now will only confuse existing users.
