### ISSUE TITLE
Mass Update - Quality column does not sort correctly

### ISSUE THREAD

**Issue by Smokey23** [SickChill/SickChill#6732]
Branch/Commit:  Master
OS: Win10
Browser:  Chrome

Steps:
1. Open http://localhost/manage/
2. Have at least 2 different Quality types in the list of shows
3. Click the "Quality" header to sort it one direction.
4. Click the header again to reverse the sort order.

Expected Results:
Each time the "Quality" header is clicked, it should reverse whatever the sort order is.

Actual Results:
Clicking it once sets the sort order to match the "Show Name" column's default order.  Each additional click does not appear to change the sort order.

![Mass_Update](https://user-images.githubusercontent.com/36527588/92985676-babe5280-f469-11ea-90fb-af0e886621a0.png)

Logs:  N/A

**Comment by Nyaran** [comment]
Problem located, a fix is in progress.
