### ISSUE TITLE
Sickbeard.py missing

### ISSUE THREAD

**Issue by vslice24** [SickChill/SickChill#6734]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:Master
OS:Freenas 11.1
Browser:chrome
What you did: recently did big update through gui. it said abotu 200+ commits behind
What happened: didn't restart after update
What you expected: sickchill to restart after update
Logs:
```
when i log into termenal and enter service sickbeard start it says can't find sickbeard.py any longer
```

**Comment by miigotu** [comment]
Because the script is names SickChill.py and it requires python3.6+

Search the issues here...
