### ISSUE TITLE
The installation guide for Ubuntu is out of date

### ISSUE THREAD

**Issue by uhop** [SickChill/SickChill#6738]
The installation guide:

https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15

doesn't work anymore.

Running (as recommended):

```bash
curl https://raw.githubusercontent.com/SickChill/SickChill/master/contrib/debian-ubuntu-install.sh | sudo bash
```

immediately produces this screen:

![Screenshot from 2020-09-13 22-48-29](https://user-images.githubusercontent.com/37966/93041928-622ab900-f613-11ea-9305-d24898ef7659.png)

The computer in question has a vanilla Ubuntu 20.04 server installed:

```bash
$ python -V
Python 2.7.18rc1
$ python3 -V
Python 3.8.2
```

Additionally, it would be nice to have a small guide on the recommended way to update SickChill from `python2` to `python3` version.

**Comment by miigotu** [comment]
Considering that guide is for Ubuntu 15.04 that is expected.

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15#otherwise

**Comment by uhop** [comment]
Thank you for your prompt answer!

https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15#otherwise

Specifically, Step 4 copies `/opt/sickchill/runscripts/init.systemd`, which is not there.

**Comment by miigotu** [comment]
fixed
