### ISSUE TITLE
Sick Chill Failed to Run

### ISSUE THREAD

**Issue by demon8991** [SickChill/SickChill#6739]
Branch/Commit: sickchill_noarch-all_20200913-0.tar.gz
OS: Synology
Browser: Chrome

- I installed it, all went well and it worked.
- I restored my backup, all went well and it worked.
- I updated it from within the UI and now the package will not run when launched.

I tried uninstalling and reinstalling it, rebooted the server but I cannot get it to run.

I am a novice when it comes to SSH but would appreciate any support you can provide.

**Comment by consenti** [comment]
Same issue here. Worked fine until this evening's (for me) update.

**Comment by BKSteve** [comment]
I just uninstalled sickchill_noarch-all_20200911-0.spk and installed sickchill_noarch-all_20200913-0.spk and it fails to run.

This is what's in the /volume1/@appstore/sickchill/var/sickchill.log

> Mon Sep 14 11:33:42 WIB 2020
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python /volume1/@appstore/sickchill/var/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data 
/volume1/@appstore/sickchill/var/SickChill/sickchill/locale
/volume1/@appstore/sickchill/var/SickChill/sickchill/locale
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2n  7 Dec 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/var/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/volume1/@appstore/sickchill/var/SickChill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/volume1/@appstore/sickchill/var/SickChill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/volume1/@appstore/sickchill/var/SickChill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/volume1/@appstore/sickchill/var/SickChill/sickchill/tv.py", line 27, in <module>
    from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles
  File "/volume1/@appstore/sickchill/var/SickChill/sickchill/oldbeard/postProcessor.py", line 9, in <module>
    import sickchill.oldbeard.subtitles
  File "/volume1/@appstore/sickchill/var/SickChill/sickchill/oldbeard/subtitles.py", line 24, in <module>
    subliminal.provider_manager.register('legendastv = subliminal.providers.legendastv:LegendasTVProvider')
  File "/volume1/@appstore/sickchill/var/SickChill/lib3/subliminal/extensions.py", line 64, in register
    ext = self._load_one_plugin(ep, False, (), {}, False)
  File "/volume1/@appstore/sickchill/var/SickChill/lib3/stevedore/extension.py", line 253, in _load_one_plugin
    plugin = ep.resolve()
  File "/volume1/@appstore/sickchill/var/SickChill/lib3/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/volume1/@appstore/sickchill/var/SickChill/lib3/subliminal/providers/legendastv.py", line 29, in <module>
    language_converters.register('legendastv = subliminal.converters.legendastv:LegendasTVConverter')
  File "/volume1/@appstore/sickchill/var/SickChill/lib3/babelfish/converters/__init__.py", line 275, in register
    raise ValueError('Already registered')
ValueError: Already registered


I tried to go back to sickchill_noarch-all_20200911-0.spk which had been running properly before unistalling, but it also fails to run. With the same results in the log.
A DSM restart provided no joy in SickChill running again.

**Comment by publicarray** [comment]
I just want to explain why both spk files fail. It is probably becaurse they both install the git master branch of SickChill. So the version number of the spk only has something to do with the packageing and not SickChill directly.

**Comment by BKSteve** [comment]
@publicarray thanks for the note. 
I am (we are) waiting for the fixes to be propagated to master.

**Comment by McEnnes** [comment]
Same problem here, I have the same remarks as demon8991

**Comment by BKSteve** [comment]
> 
> 
> Same problem here, Using sickchill_noarch-all_20200913-0.spk on Synology DS 718+
> De-install and install again gave the same result

As publicarray pointed out this is not a problem with the spk it's a master branch code issue. 
Need to wait and then git pull once the fix is moved to master branch.

**Comment by McEnnes** [comment]
@BKSteve 
I do not now much about this, i am just a user. If i understand correctly the best i kan do is install sickchill_noarch-all_20200913-0.spk again and wait for news on this issue? Can you explain how to do this pull exactly bij then?

**Comment by miigotu** [comment]
there is an error in the code for subliminal -.-

**Comment by miigotu** [comment]
Try to reinstall the package again (copy out your data <db and config.ini> if you don't have it)
https://github.com/SickChill/SickChill/commit/9fcfbc8b554ec38ab45092007efc5cc998e04b49

**Comment by BKSteve** [comment]
> 
> 
> @BKSteve
> I do not now much about this, i am just a user. If i understand correctly the best i kan do is install sickchill_noarch-all_20200913-0.spk again and wait for news on this issue? Can you explain how to do this pull exactly bij then?

The git pull operation means you need to ssh into your device and do command line stuff.
As you define yourself as just a user leave it uninstalled until a fix is out and then install the package again.

**Comment by dracupg** [comment]
Just did the pull, but getting these error starting the service

Sep 14 17:31:26 server python[508]:   File "/opt/sickchill/lib3/stevedore/extension.py", line 207, in list_entry_points
Sep 14 17:31:26 server python[508]:     eps = list(_cache.get_group_all(self.namespace))
Sep 14 17:31:26 server python[508]:   File "/opt/sickchill/lib3/stevedore/_cache.py", line 171, in get_group_all
Sep 14 17:31:26 server python[508]:     data = self._get_data_for_path(path)
Sep 14 17:31:26 server python[508]:   File "/opt/sickchill/lib3/stevedore/_cache.py", line 155, in _get_data_for_path
Sep 14 17:31:26 server python[508]:     data = _build_cacheable_data(path)
Sep 14 17:31:26 server python[508]:   File "/opt/sickchill/lib3/stevedore/_cache.py", line 108, in _build_cacheable_data
Sep 14 17:31:26 server python[508]:     real_groups = importlib_metadata.entry_points()
Sep 14 17:31:26 server python[508]: AttributeError: module 'importlib_metadata' has no attribute 'entry_points'
Sep 14 17:31:26 server systemd[1]: sickchill.service: Control process exited, code=exited status=1
Sep 14 17:31:26 server systemd[1]: sickchill.service: Failed with result 'exit-code'.
Sep 14 17:31:26 server systemd[1]: Failed to start SickChill Daemon.
-- Subject: Unit sickchill.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit sickchill.service has failed.
-- 
-- The result is RESULT.

**Comment by McEnnes** [comment]
@BKSteve 
Thanks for the info. Does that mean i kan install  sickchill_noarch-all_20200913-0.spk again and then it will work?
Or do i have to do that Git pull? I do know how to ssh into my device and do stuff, i do not know the exact syntax for that, or the folder i have to do that from.

**Comment by BKSteve** [comment]
@McEnnes 
Yes, installinbg the spk will get the updated version automatically from git. No need to do a git pull.

@dracupg you may need to check permissions. git pull will have the user permissions from the logged in user when doing the pull. If your backup isn't old I'd do an uninstall reinstall.

**Comment by Pastagazok** [comment]
Hello, 

I did a "git pull" in sickchill directory on my raspbian distribution, which gave :

$ git pull
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 13 (delta 9), reused 13 (delta 9), pack-reused 0
Dépaquetage des objets: 100% (13/13), fait.
Depuis https://github.com/SickChill/SickChill
   a6403b90c..9fcfbc8b5  master        -> origin/master
 + 92938f208...5773c7d54 imdbpy        -> origin/imdbpy  (mise à jour forcée)
 * [nouvelle étiquette]  v2020.09.14-1 -> v2020.09.14-1
Mise à jour a6403b90c..9fcfbc8b5
Fast-forward
 lib3/subliminal/providers/addic7ed.py | 2 +-
 sickchill/oldbeard/subtitles.py       | 6 ++----

... but I can't restart SC after that.

**Comment by BKSteve** [comment]
@Pastagazok Did you check permissions. git pull will have the user permissions from the logged in user when doing the pull. If your backup isn't old I'd do an uninstall reinstall. 
You'll need to chown -R 'owner of sickchill in raspbian'

**Comment by Pastagazok** [comment]
> @Pastagazok Did you check permissions. git pull will have the user permissions from the logged in user when doing the pull. If your backup isn't old I'd do an uninstall reinstall.
> You'll need to chown -R 'owner of sickchill in raspbian' => Actually I have no idea about Raspbian ownerships so I put linux

Hello, Thank you for replying.
Yes I did that.
I want to try before reinstall, because I did a fresh one not so long ago, and it took time for me (many tv shows).

**Comment by dracupg** [comment]
@BKSteve Permissions look ok. Do I need to delete the python cached files *.pyc?

> @dracupg you may need to check permissions. git pull will have the user permissions from the logged in user when doing the pull. If your backup isn't old I'd do an uninstall reinstall. Otherwise chown -R sc-sickchill

**Comment by BKSteve** [comment]
@dracupg did you check this file  sickchill/oldbeard/subtitles.py and lib3/subliminal/providers/addic7ed.py 
These were the ones changed in the recent update.

@Pastagazok I don't know how up dated you were before but I'm way out of my skill level with Raspbian as never seen it.
Even so do you have a backup made in SickChill recently then the only thing that takes time to restore is the many images the functionality is there straight away.

**Comment by McEnnes** [comment]
@BKSteve Thanks for your help! Everything runs like a charm again.

**Comment by jangrewe** [comment]
My instance also died with a self-update. I did a manual pull, purged all `*.pyc` files, but it still doesn't start:
```
Sep 14 10:33:08 hades python3[3106]: Traceback (most recent call last):
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/stevedore/_cache.py", line 152, in _get_data_for_path
Sep 14 10:33:08 hades python3[3106]:     with open(filename, 'r') as f:
Sep 14 10:33:08 hades python3[3106]: FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/python-entrypoints/74c73e4c4b9ed6356e2b716f5358233c4a3619f122779e9310ae159172d001bf'
Sep 14 10:33:08 hades python3[3106]: During handling of the above exception, another exception occurred:
Sep 14 10:33:08 hades python3[3106]: Traceback (most recent call last):
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/SickChill.py", line 14, in <module>
Sep 14 10:33:08 hades python3[3106]:     import sickchill.start
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/sickchill/__init__.py", line 1, in <module>
Sep 14 10:33:08 hades python3[3106]:     from .show.indexers import indexer, ShowIndexer
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
Sep 14 10:33:08 hades python3[3106]:     from .handler import ShowIndexer
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
Sep 14 10:33:08 hades python3[3106]:     from sickchill.tv import Show, TVEpisode
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/sickchill/tv.py", line 27, in <module>
Sep 14 10:33:08 hades python3[3106]:     from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/sickchill/oldbeard/postProcessor.py", line 9, in <module>
Sep 14 10:33:08 hades python3[3106]:     import sickchill.oldbeard.subtitles
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/sickchill/oldbeard/subtitles.py", line 8, in <module>
Sep 14 10:33:08 hades python3[3106]:     import subliminal
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/subliminal/__init__.py", line 11, in <module>
Sep 14 10:33:08 hades python3[3106]:     from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/subliminal/core.py", line 16, in <module>
Sep 14 10:33:08 hades python3[3106]:     from .extensions import provider_manager, default_providers, refiner_manager
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/subliminal/extensions.py", line 99, in <module>
Sep 14 10:33:08 hades python3[3106]:     'tvsubtitles = subliminal.providers.tvsubtitles:TVsubtitlesProvider'
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/subliminal/extensions.py", line 30, in __init__
Sep 14 10:33:08 hades python3[3106]:     super(RegistrableExtensionManager, self).__init__(namespace, **kwargs)
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/stevedore/extension.py", line 136, in __init__
Sep 14 10:33:08 hades python3[3106]:     verify_requirements)
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/stevedore/extension.py", line 218, in _load_plugins
Sep 14 10:33:08 hades python3[3106]:     for ep in self.list_entry_points():
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/subliminal/extensions.py", line 34, in list_entry_points
Sep 14 10:33:08 hades python3[3106]:     eps = list(super(RegistrableExtensionManager, self).list_entry_points())
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/stevedore/extension.py", line 207, in list_entry_points
Sep 14 10:33:08 hades python3[3106]:     eps = list(_cache.get_group_all(self.namespace))
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/stevedore/_cache.py", line 171, in get_group_all
Sep 14 10:33:08 hades python3[3106]:     data = self._get_data_for_path(path)
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/stevedore/_cache.py", line 155, in _get_data_for_path
Sep 14 10:33:08 hades python3[3106]:     data = _build_cacheable_data(path)
Sep 14 10:33:08 hades python3[3106]:   File "/opt/sickchill/lib3/stevedore/_cache.py", line 108, in _build_cacheable_data
Sep 14 10:33:08 hades python3[3106]:     real_groups = importlib_metadata.entry_points()
Sep 14 10:33:08 hades python3[3106]: AttributeError: module 'importlib_metadata' has no attribute 'entry_points'
```

**Comment by speedfreak01** [comment]
I'm also getting a similar issue after the latest update 9fcfbc8b554ec38ab45092007efc5cc998e04b49

```
Traceback (most recent call last):
  File "/home/sickrage/SickChill/lib3/stevedore/_cache.py", line 152, in _get_data_for_path
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/python-entrypoints/97c841e40f69e0de2aea4890f47a4827d2782e258a972069c8c89556ae494323'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sickrage/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/home/sickrage/SickChill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/home/sickrage/SickChill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/home/sickrage/SickChill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/home/sickrage/SickChill/sickchill/tv.py", line 27, in <module>
    from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles
  File "/home/sickrage/SickChill/sickchill/oldbeard/postProcessor.py", line 9, in <module>
    import sickchill.oldbeard.subtitles
  File "/home/sickrage/SickChill/sickchill/oldbeard/subtitles.py", line 8, in <module>
    import subliminal
  File "/home/sickrage/SickChill/lib3/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/home/sickrage/SickChill/lib3/subliminal/core.py", line 16, in <module>
    from .extensions import provider_manager, default_providers, refiner_manager
  File "/home/sickrage/SickChill/lib3/subliminal/extensions.py", line 99, in <module>
    'tvsubtitles = subliminal.providers.tvsubtitles:TVsubtitlesProvider'
  File "/home/sickrage/SickChill/lib3/subliminal/extensions.py", line 30, in __init__
    super(RegistrableExtensionManager, self).__init__(namespace, **kwargs)
  File "/home/sickrage/SickChill/lib3/stevedore/extension.py", line 136, in __init__
    verify_requirements)
  File "/home/sickrage/SickChill/lib3/stevedore/extension.py", line 218, in _load_plugins
    for ep in self.list_entry_points():
  File "/home/sickrage/SickChill/lib3/subliminal/extensions.py", line 34, in list_entry_points
    eps = list(super(RegistrableExtensionManager, self).list_entry_points())
  File "/home/sickrage/SickChill/lib3/stevedore/extension.py", line 207, in list_entry_points
    eps = list(_cache.get_group_all(self.namespace))
  File "/home/sickrage/SickChill/lib3/stevedore/_cache.py", line 171, in get_group_all
    data = self._get_data_for_path(path)
  File "/home/sickrage/SickChill/lib3/stevedore/_cache.py", line 155, in _get_data_for_path
    data = _build_cacheable_data(path)
  File "/home/sickrage/SickChill/lib3/stevedore/_cache.py", line 108, in _build_cacheable_data
    real_groups = importlib_metadata.entry_points()
AttributeError: module 'importlib_metadata' has no attribute 'entry_points'
```

**Comment by hatemzidi** [comment]
same error for me too

> I'm also getting a similar issue after the latest update [9fcfbc8](https://github.com/SickChill/SickChill/commit/9fcfbc8b554ec38ab45092007efc5cc998e04b49)
> 
> ```
> Traceback (most recent call last):
>   File "/home/sickrage/SickChill/lib3/stevedore/_cache.py", line 152, in _get_data_for_path
>     with open(filename, 'r') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/python-entrypoints/97c841e40f69e0de2aea4890f47a4827d2782e258a972069c8c89556ae494323'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/sickrage/SickChill/SickChill.py", line 14, in <module>
>     import sickchill.start
>   File "/home/sickrage/SickChill/sickchill/__init__.py", line 1, in <module>
>     from .show.indexers import indexer, ShowIndexer
>   File "/home/sickrage/SickChill/sickchill/show/indexers/__init__.py", line 1, in <module>
>     from .handler import ShowIndexer
>   File "/home/sickrage/SickChill/sickchill/show/indexers/handler.py", line 5, in <module>
>     from sickchill.tv import Show, TVEpisode
>   File "/home/sickrage/SickChill/sickchill/tv.py", line 27, in <module>
>     from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles
>   File "/home/sickrage/SickChill/sickchill/oldbeard/postProcessor.py", line 9, in <module>
>     import sickchill.oldbeard.subtitles
>   File "/home/sickrage/SickChill/sickchill/oldbeard/subtitles.py", line 8, in <module>
>     import subliminal
>   File "/home/sickrage/SickChill/lib3/subliminal/__init__.py", line 11, in <module>
>     from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
>   File "/home/sickrage/SickChill/lib3/subliminal/core.py", line 16, in <module>
>     from .extensions import provider_manager, default_providers, refiner_manager
>   File "/home/sickrage/SickChill/lib3/subliminal/extensions.py", line 99, in <module>
>     'tvsubtitles = subliminal.providers.tvsubtitles:TVsubtitlesProvider'
>   File "/home/sickrage/SickChill/lib3/subliminal/extensions.py", line 30, in __init__
>     super(RegistrableExtensionManager, self).__init__(namespace, **kwargs)
>   File "/home/sickrage/SickChill/lib3/stevedore/extension.py", line 136, in __init__
>     verify_requirements)
>   File "/home/sickrage/SickChill/lib3/stevedore/extension.py", line 218, in _load_plugins
>     for ep in self.list_entry_points():
>   File "/home/sickrage/SickChill/lib3/subliminal/extensions.py", line 34, in list_entry_points
>     eps = list(super(RegistrableExtensionManager, self).list_entry_points())
>   File "/home/sickrage/SickChill/lib3/stevedore/extension.py", line 207, in list_entry_points
>     eps = list(_cache.get_group_all(self.namespace))
>   File "/home/sickrage/SickChill/lib3/stevedore/_cache.py", line 171, in get_group_all
>     data = self._get_data_for_path(path)
>   File "/home/sickrage/SickChill/lib3/stevedore/_cache.py", line 155, in _get_data_for_path
>     data = _build_cacheable_data(path)
>   File "/home/sickrage/SickChill/lib3/stevedore/_cache.py", line 108, in _build_cacheable_data
>     real_groups = importlib_metadata.entry_points()
> AttributeError: module 'importlib_metadata' has no attribute 'entry_points'
> ```

**Comment by overloadsix** [comment]
**For 18.04 I see this is importlib_metadata as bad module. I did a full delete of the /opt/sickchill directory and then when I try to start the daemon, I get the following:**

mario@anthem:~$ sudo service sickchill status
● sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-09-14 05:07:33 EDT; 13s ago
  Process: 4692 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=1/FAILURE)

Sep 14 05:07:33 anthem python3[4692]:   File "/opt/sickchill/lib3/stevedore/__init__.py", line 11, in <module>
Sep 14 05:07:33 anthem python3[4692]:     from .extension import ExtensionManager
Sep 14 05:07:33 anthem python3[4692]:   File "/opt/sickchill/lib3/stevedore/extension.py", line 19, in <module>
Sep 14 05:07:33 anthem python3[4692]:     from . import _cache
Sep 14 05:07:33 anthem python3[4692]:   File "/opt/sickchill/lib3/stevedore/_cache.py", line 31, in <module>
Sep 14 05:07:33 anthem python3[4692]:     import importlib_metadata
Sep 14 05:07:33 anthem python3[4692]: ModuleNotFoundError: No module named 'importlib_metadata'
Sep 14 05:07:33 anthem systemd[1]: sickchill.service: Control process exited, code=exited status=1
Sep 14 05:07:33 anthem systemd[1]: sickchill.service: Failed with result 'exit-code'.
Sep 14 05:07:33 anthem systemd[1]: Failed to start SickChill Daemon.

**I also went into the sickchill folder and tried to run sickchill.py directly:**

mario@anthem:/opt/sickchill$ sudo python ./SickChill.py
Traceback (most recent call last):
  File "./SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/opt/sickchill/sickchill/logger.py", line 72
    msg = re.sub(fr'\b({item})\b', '*' * 8, msg)
                                ^
SyntaxError: invalid syntax

Any advice? Maybe new Daemon needs built?

**Comment by jangrewe** [comment]
@overloadsix That later error is probably because you're running the script with `python` (= `python2`) instead of `python3`, as the systemd unit does.

**Comment by kyuuk** [comment]
actually even the Docker image not working 
```
    import sickchill.start,
  File "/app/sickchill/sickchill/__init__.py", line 1, in <module>,
    from .show.indexers import indexer, ShowIndexer,
  File "/app/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>,
    from .handler import ShowIndexer,
  File "/app/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>,
    from sickchill.tv import Show, TVEpisode,
  File "/app/sickchill/sickchill/tv.py", line 27, in <module>,
    from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles,
  File "/app/sickchill/sickchill/oldbeard/postProcessor.py", line 9, in <module>,
    import sickchill.oldbeard.subtitles,
  File "/app/sickchill/sickchill/oldbeard/subtitles.py", line 8, in <module>,
    import subliminal,
  File "/app/sickchill/lib3/subliminal/__init__.py", line 11, in <module>,
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,,
  File "/app/sickchill/lib3/subliminal/core.py", line 16, in <module>,
    from .extensions import provider_manager, default_providers, refiner_manager,
  File "/app/sickchill/lib3/subliminal/extensions.py", line 4, in <module>,
    from stevedore import ExtensionManager,
  File "/app/sickchill/lib3/stevedore/__init__.py", line 11, in <module>,
    from .extension import ExtensionManager,
  File "/app/sickchill/lib3/stevedore/extension.py", line 19, in <module>,
    from . import _cache,
  File "/app/sickchill/lib3/stevedore/_cache.py", line 31, in <module>,
    import importlib_metadata,
ModuleNotFoundError: No module named 'importlib_metadata',
/app/sickchill/sickchill/locale,
/app/sickchill/sickchill/locale,
Traceback (most recent call last):,
  File "/app/sickchill/lib3/stevedore/_cache.py", line 28, in <module>,
    import importlib.metadata as importlib_metadata,
ModuleNotFoundError: No module named 'importlib.metadata',
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "SickChill.py", line 14, in <module>,
    import sickchill.start,
  File "/app/sickchill/sickchill/__init__.py", line 1, in <module>,
    from .show.indexers import indexer, ShowIndexer,
  File "/app/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>,
    from .handler import ShowIndexer,
  File "/app/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>,
    from sickchill.tv import Show, TVEpisode,
  File "/app/sickchill/sickchill/tv.py", line 27, in <module>,
    from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles,
  File "/app/sickchill/sickchill/oldbeard/postProcessor.py", line 9, in <module>,
    import sickchill.oldbeard.subtitles,
  File "/app/sickchill/sickchill/oldbeard/subtitles.py", line 8, in <module>,
    import subliminal,
  File "/app/sickchill/lib3/subliminal/__init__.py", line 11, in <module>,
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,,
  File "/app/sickchill/lib3/subliminal/core.py", line 16, in <module>,
    from .extensions import provider_manager, default_providers, refiner_manager,
  File "/app/sickchill/lib3/subliminal/extensions.py", line 4, in <module>,
    from stevedore import ExtensionManager,
  File "/app/sickchill/lib3/stevedore/__init__.py", line 11, in <module>,
    from .extension import ExtensionManager,
  File "/app/sickchill/lib3/stevedore/extension.py", line 19, in <module>,
    from . import _cache,
  File "/app/sickchill/lib3/stevedore/_cache.py", line 31, in <module>,
    import importlib_metadata,
ModuleNotFoundError: No module named 'importlib_metadata',
Traceback (most recent call last):,
  File "/app/sickchill/lib3/stevedore/_cache.py", line 28, in <module>,
    import importlib.metadata as importlib_metadata,
ModuleNotFoundError: No module named 'importlib.metadata',
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "SickChill.py", line 14, in <module>,
    import sickchill.start,
  File "/app/sickchill/sickchill/__init__.py", line 1, in <module>,
    from .show.indexers import indexer, ShowIndexer,
  File "/app/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>,
    from .handler import ShowIndexer,
  File "/app/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>,
    from sickchill.tv import Show, TVEpisode,
  File "/app/sickchill/sickchill/tv.py", line 27, in <module>,
    from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles,
  File "/app/sickchill/sickchill/oldbeard/postProcessor.py", line 9, in <module>,
    import sickchill.oldbeard.subtitles,
  File "/app/sickchill/sickchill/oldbeard/subtitles.py", line 8, in <module>,
    import subliminal,
  File "/app/sickchill/lib3/subliminal/__init__.py", line 11, in <module>,
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,,
  File "/app/sickchill/lib3/subliminal/core.py", line 16, in <module>,
    from .extensions import provider_manager, default_providers, refiner_manager,
  File "/app/sickchill/lib3/subliminal/extensions.py", line 4, in <module>,
    from stevedore import ExtensionManager,
  File "/app/sickchill/lib3/stevedore/__init__.py", line 11, in <module>,
    from .extension import ExtensionManager,
  File "/app/sickchill/lib3/stevedore/extension.py", line 19, in <module>,
    from . import _cache,
  File "/app/sickchill/lib3/stevedore/_cache.py", line 31, in <module>,
    import importlib_metadata,
ModuleNotFoundError: No module named 'importlib_metadata',
/app/sickchill/sickchill/locale,
/app/sickchill/sickchill/locale,
```

**Comment by jangrewe** [comment]
Why should the Docker image still work if the code is broken?

**Comment by overloadsix** [comment]
> @overloadsix That later error is probably because you're running the script with `python` (= `python2`) instead of `python3`, as the systemd unit does.

mario@anthem:/opt/sickchill$ python3 ./SickChill.py
/opt/sickchill/sickchill/locale
/opt/sickchill/sickchill/locale
Traceback (most recent call last):
  File "/opt/sickchill/lib3/stevedore/_cache.py", line 28, in <module>
    import importlib.metadata as importlib_metadata
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/sickchill/sickchill/tv.py", line 27, in <module>
    from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles
  File "/opt/sickchill/sickchill/oldbeard/postProcessor.py", line 9, in <module>
    import sickchill.oldbeard.subtitles
  File "/opt/sickchill/sickchill/oldbeard/subtitles.py", line 8, in <module>
    import subliminal
  File "/opt/sickchill/lib3/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/opt/sickchill/lib3/subliminal/core.py", line 16, in <module>
    from .extensions import provider_manager, default_providers, refiner_manager
  File "/opt/sickchill/lib3/subliminal/extensions.py", line 4, in <module>
    from stevedore import ExtensionManager
  File "/opt/sickchill/lib3/stevedore/__init__.py", line 11, in <module>
    from .extension import ExtensionManager
  File "/opt/sickchill/lib3/stevedore/extension.py", line 19, in <module>
    from . import _cache
  File "/opt/sickchill/lib3/stevedore/_cache.py", line 31, in <module>
    import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'

**Comment by miigotu** [comment]
Figured it out, gimme a few and ill merge the next pr

**Comment by miigotu** [comment]
> Why should the Docker image still work if the code is broken?

Because the docker image uses python3.8 which has importlib.metadata in the stdlib

**Comment by miigotu** [comment]
SickChill/SickChill@v2020.09.14-2 should fix the issue.
Note to self: Never use python3.8 to bundle libs (it left out importlib_metadata and zipp which are needed for python 3.6 and 3.7)

**Comment by jangrewe** [comment]
Works fine now, thanks! 
(well, at least it starts again without issues ;-) )

**Comment by overloadsix** [comment]
Works again! 
btw, 
I am becoming intimately familiar with cron and rsync :) 👍

**Comment by LapinFou** [comment]
I didn't push the "_update_" button when I saw this bug report.
SickChill is running on a Synology DS916+. I've done the migration to Python3 yesterday by installation **sickchill_noarch-all_20200913-0.spk**.
Am I safe to launch the "update" process?  😃

**Comment by miigotu** [comment]
yes, it seems to be fixed

**Comment by LapinFou** [comment]
Success!
Pressing the **update** button does work on Synology. 👍 
Thanks for your hard work.

**Comment by Pastagazok** [comment]
Thank's @miigotu, and a kiss for baby.

**Comment by dabadgreek** [comment]
Sorry for the dumb question but where do I get the spk for sickchill is it in synocommunity now?

**Comment by MichelRabozee** [comment]
@dabadgreek : follow this thread on SynoCommunity to see progress and test the spk listed on the first post there : https://github.com/SynoCommunity/spksrc/pull/4161

**Comment by dracupg** [comment]
Looks good here. Thanks for all your work.

**Comment by demon8991** [comment]
Thanks for all the hard work, mine is working again too.
