### ISSUE TITLE
Scene exceptions problem

### ISSUE THREAD

**Issue by romainsi** [SickChill/SickChill#6743]
Branch/Commit:master/20d84f5288ec3e532b6dd46cdbe4b833fbef00fd
OS:Linux-4.19-std-centos-7
Browser:chrome
Version: v2020.09.14-2
Database Version: 44.5
Python Version:3.6.8 (default, Apr 2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

What you did:
Shows with years in parenthesis like : 'Family Business (2019)' was unable to find.
I've try to add a Scene exception at root shows (https://github.com/SickChill/SickChill/wiki/Scene-exceptions-and-numbering) :
![image](https://user-images.githubusercontent.com/30522413/93123174-fe15fc80-f6c7-11ea-89b6-4b2581868236.png)

What happened:
With my actuals Nzb Indexers with manual API query for this season i found correctly episodes without '(YEARS)' :

```
        <item>
            <title>Family.Business.S02E01.Straight.and.Narrow.1080p.NF.WEB-DL.DDP5.1.H.264-NTb</title>
            <guid isPermaLink="true">https://indexer1/details/0a13b0cf52b0067bbe8b0827381c5f25</guid>
            https://indexer2/getnzb/0a13b0cf52b0067bbe8b0827381c5f25.nzb&amp;i=281443&amp;r=****
            <comments>https://indexer1/details/0a13b0cf52b0067bbe8b0827381c5f25#comments</comments>
            <pubDate>Fri, 11 Sep 2020 18:03:05 +0200</pubDate>
            <category>TV &gt; HD</category>
            <description>Family.Business.S02E01.Straight.and.Narrow.1080p.NF.WEB-DL.DDP5.1.H.264-NTb</description>
            <enclosure url="https://indexer1/getnzb/0a13b0cf52b0067bbe8b0827381c5f25.nzb&amp;i=281443&amp;r=****" length="1246999875" type="application/x-nzb" />
            <newznab:attr name="category" value="5000" />
            <newznab:attr name="category" value="5040" />
            <newznab:attr name="size" value="1246999875" />
            <newznab:attr name="guid" value="0a13b0cf52b0067bbe8b0827381c5f25" />
```

What you expected:
That it works ^^ ;)

Logs Sickchill : 
SEARCHQUEUE-MANUAL-364468 :: Unable to find a download for: [Family Business (2019) - S02E01 - Straight and Narrow]
SEARCHQUEUE-MANUAL-364468 :: [Indexer2] :: Performing season pack search for Family Business (2019)
SEARCHQUEUE-MANUAL-364468 :: [Indexer2] :: Performing épisode search for Family Business (2019)
SEARCHQUEUE-MANUAL-364468 :: [Indexer1] :: Performing season pack search for Family Business (2019)
SEARCHQUEUE-MANUAL-364468 :: [Indexer1] :: Performing épisode search for Family Business (2019)
SEARCHQUEUE-MANUAL-364468 :: Beginning manual search for: [Family Business (2019) - S02E01 - Straight and Narrow]

**Comment by romainsi** [comment]
Ps : It also seems that after removing the scene exceptions and forcing the show update does not remove the exceptions that are already present.

![image](https://user-images.githubusercontent.com/30522413/93124753-66fe7400-f6ca-11ea-9073-9474688addbb.png)

![image](https://user-images.githubusercontent.com/30522413/93124771-71207280-f6ca-11ea-8a82-af681e0b99f2.png)

**Comment by miigotu** [comment]
@Nyaran maybe you can investigate why scene exceptions are not removed from the `exceptionsCache = {} or
exceptionsSeasonCache = {}` when `rebuild_exception_cache` is called? everything works it just doesn't remove the exception unless service is restarted (aka it is saved to the db but that is all)

**Comment by miigotu** [comment]
Very odd because I dont think we actually need both exceptionsCache and exceptionsSeasonCache, they both have the same layout afaik. Maybe this is a scene_seasons bug.

**Comment by Nyaran** [comment]
`exceptionsSeasonCache` contains just the seasons numbers per each show, it probably can be removed, just updating a couple of methods. Doing that, we can reduce the amount of DB calls, but, on large shows, if all the seasons have multiple names, the returned data could be heavy, but I can not think any show which can represents a problem (that could only happens with thousand and thousands of exceptions, and... that sounds really crazy)

**Comment by miigotu** [comment]
It is probably better to simplify that code as much as possible, it is very confusing as it sits.

**Comment by Nyaran** [comment]
I will try to work on it tomorrow, meanwhile that PR can be merged, to get fixed the issue with cache rebuild

**Comment by miigotu** [comment]
I refactored it and removed scene_season_exceptions list/cache =P
