### ISSUE TITLE
ignoring show defined required_words

### ISSUE THREAD

**Issue by digrouz** [SickChill/SickChill#6751]
### Before submitting your issue:

For few years, I've been using required_words inside sickchill to enforce getting french releases set globally. By that, I mean in the general config, not on every shows. For some specific shows like animes, I was redefining that required_words explicitly on each animes to enforce to get french subtitled animes. This way was working pretty good until last release where I  see in logs that he is ignoring files because they don't have the general required_words. 

Is this change of behavior wanted ? Or is it a bug ?

Branch/Commit: v2020.09.14-2 
OS: alpine
Browser: chrome
What you did: Redefinied required_words on specific shows
What happened: sickchill is using the required_words of the general config
What you expected:  sickchill use the required_words defined on shows if defined instead of the one defined in the general config.

**Comment by digrouz** [comment]
after some more test, sounds more like an issue on a specific file.
Here are the logs:


```
2020-09-16 00:56:37 INFO :: WEBSERVER-POSTPROCESS_0 :: Manual post processing task for /downloads completed
AA TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
AA '%0E': f'{int(self.episode):02d}',
AA File "/opt/sickchill/sickchill/tv.py", line 2057, in _replace_map
AA replace_map = self._replace_map()
AA File "/opt/sickchill/sickchill/tv.py", line 2115, in _format_pattern
AA return sanitize_filename(self._format_pattern(name_groups[-1], multi, anime_type))
AA File "/opt/sickchill/sickchill/tv.py", line 2319, in formatted_filename
AA result = self.formatted_filename(anime_type=anime_type)
AA File "/opt/sickchill/sickchill/tv.py", line 2264, in proper_path
AA proper_path = ep_obj.proper_path()
AA File "/opt/sickchill/sickchill/oldbeard/postProcessor.py", line 1081, in process
AA result.result = processor.process()
AA File "/opt/sickchill/sickchill/oldbeard/processTV.py", line 475, in process_media
AA process_media(current_directory, video_files, release_name, process_method, force, is_priority, result)
AA File "/opt/sickchill/sickchill/oldbeard/processTV.py", line 175, in process_dir
2020-09-16 00:56:37 WARNING :: WEBSERVER-POSTPROCESS_0 :: Couldn't find release in snatch history
2020-09-16 00:56:37 INFO :: WEBSERVER-POSTPROCESS_0 :: Release: downloads doesn't contain any of truefrench, vfq, fr, vfi, multi, vff, french, ignoring it
2020-09-16 00:56:37 INFO :: WEBSERVER-POSTPROCESS_0 :: Processing /downloads/The God of High School - 1x10 - 010 - french - 1080p.HDTV.mkv (None)
2020-09-16 00:56:37 INFO :: WEBSERVER-POSTPROCESS_0 :: Processing /downloads
2020-09-16 00:56:37 INFO :: WEBSERVER-POSTPROCESS_0 :: Beginning manual post processing task: /downloads
```

**Comment by digrouz** [comment]
Do you see what in this filename bugs the postprocessor ?

**Comment by miigotu** [comment]
yes, give me a bit ill fix it (my change expected a match there)

**Comment by digrouz** [comment]
That was fast, thanks a lot!
