### ISSUE TITLE
List index out of range and exception error during automatic refresh of shows

### ISSUE THREAD

**Issue by Ventje23** [SickChill/SickChill#6754]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: v2020.09.14-2
OS: 3.7.7 (default, Aug 18 2020, 20:42:48) [GCC 4.9.3 20150311 (prerelease)]
Browser: Chrome
What you did: Sickchill did an automatic refresh of shows
What happened: got some exception errors AND list index out of range
What you expected: no errors, maybe a warning that a banner could not be found
Logs:

2020-09-16 04:31:41 INFO :: SHOWQUEUE-FORCE-UPDATE :: Done cache check
2020-09-16 04:31:41 INFO :: SHOWQUEUE-FORCE-UPDATE :: Could not find any banner images on Fanart.tv for Monsterland
AA requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/385960/images/query?keyType=series
AA raise HTTPError(http_error_msg, response=self)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/requests/models.py", line 941, in raise_for_status
AA response.raise_for_status()
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 146, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 480, in _get_image_type
AA return self._get_image_type('series', language)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 403, in series
AA images = getattr(api_results, keyType)(lang or show.lang)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 168, in __call_images_api
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 21, in wrapper
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA Exception: No results for your query
AA raise Exception(response.json()['Error'])
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 144, in _request
2020-09-16 04:31:40 INFO :: SHOWQUEUE-FORCE-UPDATE :: Could not find any banner images on Fanart.tv for Monsterland
AA requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/385960/images/query?keyType=series
AA raise HTTPError(http_error_msg, response=self)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/requests/models.py", line 941, in raise_for_status
AA response.raise_for_status()
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 146, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 480, in _get_image_type
AA return self._get_image_type('series', language)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 403, in series
AA images = getattr(api_results, keyType)(lang or show.lang)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 168, in __call_images_api
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 21, in wrapper
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA Exception: No results for your query
AA raise Exception(response.json()['Error'])
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 144, in _request
2020-09-16 04:31:40 INFO :: SHOWQUEUE-FORCE-UPDATE :: 385960: Updating NFOs for show with new indexer info
2020-09-16 04:31:40 INFO :: SHOWQUEUE-FORCE-UPDATE :: Performing refresh on Monsterland

2020-09-16 04:30:03 INFO :: SHOWQUEUE-REFRESH :: Could not find any banner images on Fanart.tv for Sanctuary (2019)
AA requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/364491/images/query?keyType=series
AA raise HTTPError(http_error_msg, response=self)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/requests/models.py", line 941, in raise_for_status
AA response.raise_for_status()
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 146, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 480, in _get_image_type
AA return self._get_image_type('series', language)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 403, in series
AA images = getattr(api_results, keyType)(lang or show.lang)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 168, in __call_images_api
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 21, in wrapper
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA Exception: No results for your query
AA raise Exception(response.json()['Error'])
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 144, in _request
2020-09-16 04:30:02 INFO :: SHOWQUEUE-REFRESH :: Could not find any banner images on Fanart.tv for Sanctuary (2019)
AA requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/364491/images/query?keyType=series
AA raise HTTPError(http_error_msg, response=self)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/requests/models.py", line 941, in raise_for_status
AA response.raise_for_status()
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 146, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 480, in _get_image_type
AA return self._get_image_type('series', language)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 403, in series
AA images = getattr(api_results, keyType)(lang or show.lang)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 168, in __call_images_api
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 21, in wrapper
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA Exception: No results for your query
AA raise Exception(response.json()['Error'])
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 144, in _request
2020-09-16 04:30:02 INFO :: SHOWQUEUE-REFRESH :: Performing refresh on Sanctuary (2019)

2020-09-16 04:24:31 INFO :: SHOWQUEUE-REFRESH :: Performing refresh on White Lines
2020-09-16 04:24:27 INFO :: SHOWQUEUE-REFRESH :: Done cache check
2020-09-16 04:24:27 INFO :: SHOWQUEUE-REFRESH :: Could not find any banner images on Fanart.tv for Valeria
AA requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/379841/images/query?keyType=series
AA raise HTTPError(http_error_msg, response=self)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/requests/models.py", line 941, in raise_for_status
AA response.raise_for_status()
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 146, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 480, in _get_image_type
AA return self._get_image_type('series', language)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 403, in series
AA images = getattr(api_results, keyType)(lang or show.lang)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 168, in __call_images_api
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 21, in wrapper
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA Exception: No results for your query
AA raise Exception(response.json()['Error'])
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 144, in _request
2020-09-16 04:24:27 INFO :: SHOWQUEUE-REFRESH :: Could not find any banner images on Fanart.tv for Valeria
AA requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/379841/images/query?keyType=series
AA raise HTTPError(http_error_msg, response=self)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/requests/models.py", line 941, in raise_for_status
AA response.raise_for_status()
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 146, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 480, in _get_image_type
AA return self._get_image_type('series', language)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/series.py", line 403, in series
AA images = getattr(api_results, keyType)(lang or show.lang)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 168, in __call_images_api
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 21, in wrapper
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA Exception: No results for your query
AA raise Exception(response.json()['Error'])
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib3/tvdbsimple/base.py", line 144, in _request
2020-09-16 04:24:26 INFO :: SHOWQUEUE-REFRESH :: Performing refresh on Valeria

list index out of range:

2020-09-16 04:24:06 INFO :: SHOWQUEUE-REFRESH :: Performing refresh on One Day at a Time (2017)
AA IndexError: list index out of range
AA result = self._series(self.search(name, language)[0]['id'])
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 63, in get_series_by_name
AA result = self.indexers[i].get_series_by_name(n, indexerid, language)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/handler.py", line 114, in search_indexers_for_series_id
AA settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/oldbeard/helpers.py", line 957, in get_show
AA TypeError: expected string or bytes-like object
AA return _compile(pattern, flags).match(string)
AA File "/var/packages/python3/target/lib/python3.7/re.py", line 173, in match
AA if re.match(r'^t?t?\d{7,8}$', name) or re.match(r'^\d{6}$', name):
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 107, in search
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 21, in wrapper
AA IndexError: list index out of range
AA result = self._series(self.search(name, language)[0]['id'])
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 63, in get_series_by_name

**Comment by miigotu** [comment]
This is a debug traceback, ignore.

**Comment by Ventje23** [comment]
Ok thanks for the info. I will ignore this.
