### ISSUE TITLE
Won't start after latest pip update

### ISSUE THREAD

**Issue by josh-gaby** [SickChill/SickChill#6755]
Branch/Commit: PIP Latest 2020.9.16.post2
OS: Debian 9

Trying to start sickchill results in the following error:

```
Traceback (most recent call last):
  File "/*****/bin/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/*****/pip3/lib/python3.8/site-packages/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/*****/pip3/lib/python3.8/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/*****/pip3/lib/python3.8/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/*****/pip3/lib/python3.8/site-packages/sickchill/tv.py", line 15, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'
```

Rolling back to 2020.9.13.post1 fixes the issue 
`pip install -Iv sickchill==2020.9.13.post1`

**Comment by fl1ck3r** [comment]
Same issue here, tried fixing with
pip3 install imdbpy
new error:
`Sep 16 16:15:08 PI4 SickChill.py[5328]: /home/pi/virtualenv/SickChill/lib/python3.7/site-packages/sickchill/locale
Sep 16 16:15:08 PI4 SickChill.py[5328]: Traceback (most recent call last):
Sep 16 16:15:08 PI4 SickChill.py[5328]:   File "/home/pi/virtualenv/SickChill/bin/SickChill.py", line 40, in <module>
Sep 16 16:15:08 PI4 SickChill.py[5328]:     from sickchill.views.server_settings import SRWebServer
Sep 16 16:15:08 PI4 SickChill.py[5328]:   File "/home/pi/virtualenv/SickChill/lib/python3.7/site-packages/sickchill/views/__init__.py", line 15, in <module>
Sep 16 16:15:08 PI4 SickChill.py[5328]:     from .manage import AddShows, Manage, ManageSearches, PostProcess
Sep 16 16:15:08 PI4 SickChill.py[5328]:   File "/home/pi/virtualenv/SickChill/lib/python3.7/site-packages/sickchill/views/manage/__init__.py", line 1, in <module>
Sep 16 16:15:08 PI4 SickChill.py[5328]:     from .add_shows import AddShows
Sep 16 16:15:08 PI4 SickChill.py[5328]:   File "/home/pi/virtualenv/SickChill/lib/python3.7/site-packages/sickchill/views/manage/add_shows.py", line 21, in <module>
Sep 16 16:15:08 PI4 SickChill.py[5328]:     from sickchill.show.recommendations.imdb import imdb_popular
Sep 16 16:15:08 PI4 SickChill.py[5328]:   File "/home/pi/virtualenv/SickChill/lib/python3.7/site-packages/sickchill/show/recommendations/imdb.py", line 66, in <module>
Sep 16 16:15:08 PI4 SickChill.py[5328]:     imdb_popular = imdbPopular()
Sep 16 16:15:08 PI4 SickChill.py[5328]:   File "/home/pi/virtualenv/SickChill/lib/python3.7/site-packages/sickchill/show/recommendations/imdb.py", line 17, in __init__
Sep 16 16:15:08 PI4 SickChill.py[5328]:     self.imdb.topBottomProxy.tvmeter100_parser.rules[0].extractor.rules.append(
Sep 16 16:15:08 PI4 SickChill.py[5328]:   File "/home/pi/virtualenv/SickChill/lib/python3.7/site-packages/imdb/parser/http/__init__.py", line 90, in __getattr__
Sep 16 16:15:08 PI4 SickChill.py[5328]:     return getattr(_sm, name)
Sep 16 16:15:08 PI4 SickChill.py[5328]: AttributeError: module 'imdb.parser.http.topBottomParser' has no attribute 'tvmeter100_parser'
Sep 16 16:15:09 PI4 systemd[1]: sickchill.service: Control process exited, code=exited, status=1/FAILURE
`

**Comment by lobofoots** [comment]
Same here

**Comment by miigotu** [comment]
`pip install git+https://github.com/alberanid/imdbpy#egg=imdbpy` Not sure why that was not updated with the setup.py, maybe my requirements parser is lacking support for git+

**Comment by miigotu** [comment]
Lol it's totally my code

```python
with open(Path('requirements.txt').absolute()) as fp:
    info_dict['install_requires'] = [line for line in fp.readlines() if not line.startswith('#') and not line.startswith('git+')]
```

**Comment by lobofoots** [comment]
Starting correctly after 
pip install git+https://github.com/alberanid/imdbpy#egg=imdbpy
Thanks

**Comment by nopoz** [comment]
Temporary workaround is to roll back to the previous version.

Get interactive shell on docker container with bash (if you're using docker):

```
docker exec -t -i sickchill /bin/bash
```

Rollback to previous release using pip:

```
pip install --upgrade sickchill==2020.9.13.post1
```

**Comment by groebke** [comment]
Rolling back did not work:

  Downloading https://files.pythonhosted.org/packages/82/f7/e43cefbe88c5fd371f4c
f0cf5eb3feccd07515af9fd6cf7dbf1d1793a797/wrapt-1.12.1.tar.gz
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in c:\program f
iles (x86)\python37-32\lib\site-packages (from requests-oauthlib->python-twitter
->sickchill==2020.9.13.post1) (3.1.0)
Requirement already satisfied, skipping upgrade: pycparser in c:\program files (
x86)\python37-32\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.8->
pyOpenSSL->sickchill==2020.9.13.post1) (2.20)
Installing collected packages: tus.py, python3-fanart, PySocks, tvdbsimple, puti
o.py, pyjsparser, Js2Py, bencode.py, pyparsing, packaging, win-inet-pton, images
ize, pyaes, attrdict, qbittorrent-api, jsonrpclib-pelix, text-unidecode, python-
slugify, pyOpenSSL, tmdbsimple, wheel, diskcache, boto, attrs, trans, imdbpie, t
imeago, new-rtorrent-python, ifaddr, pynma, xmltodict, beekeeper, validators, wr
apt, deprecated, PyGithub, backports-abc, kodipydent, sickchill
  Running setup.py install for tus.py ... error
    ERROR: Command errored out with exit status 1:

**Comment by miigotu** [comment]
You don't need to roll back I released a version with the requirements fixed...

**Comment by groebke** [comment]
> 
> 
> You don't need to roll back I released a version with the requirements fixed...

Nice!!! Thanks for hanging in there. Can I bother you for the link?

Hope the smoke is not getting you.

**Comment by miigotu** [comment]
https://pypi.org/project/sickchill/

**Comment by groebke** [comment]
> 
> 
> https://pypi.org/project/sickchill/

Bummer, I must be having that day: 
"This is an old version of the SickChill installer"...

![image](https://user-images.githubusercontent.com/19145402/93419022-eb86f900-f868-11ea-81d5-ff65750a8cfe.png)

**Comment by groebke** [comment]
Fucking permissions...

**Comment by groebke** [comment]
Yeah, totally not working. Run as admin and all that. Thoughts?

**Comment by miigotu** [comment]
What does the windows installer have to do with a pip install ....

**Comment by groebke** [comment]
Apologies it is late, and I may have mixed up the threads. What do I need to do then to get Sickchill installed, as, clearly, I am muffing something up

**Comment by miigotu** [comment]
@groebke the windows installer has an update, I hope it works

**Comment by groebke** [comment]
> 
> 
> @groebke the windows installer has an update, I hope it works

Thanks! Yet, no dice:

![image](https://user-images.githubusercontent.com/19145402/93557547-7a167b80-f938-11ea-9d74-9a077b781d62.png)
Still shows the message that the installers is old.

Thoughts?

**Comment by miigotu** [comment]
You have to download the newest installer....
(currently 0.5.9) https://github.com/SickChill/windows-sickchill/releases/latest
