### ISSUE TITLE
New Synology package for Python 3

### ISSUE THREAD

**Issue by BenjV** [SickChill/SickChill#6758]
I rewrote the complete installation package for SickChill for Python 3 and posted it on this repositary.
You can find it here.
https://github.com/BenjV/SYNO-packages
Download the package to your PC for a manual install.
Make sure you installed Python 3 from the SynCommunity first.

If you already have a SickChill version running, please make a backup from within SickChill.
Then remove that package, manual install the new one, start it and restore the backup from within SickChiil.

Enjoy.

**Comment by miigotu** [comment]
We have on on synocommunity, you can make a pr to that one but we aren't going to be sharing packages anymore that we can't follow the code changes. If we had a git history of the changes to your package before we would have been able to update the package the same day the Python3 was required.

**Comment by spock99** [comment]
> 
> 
> I rewrote the complete installation package for SickChill for Python 3 and posted it on this repositary.
> You can find it here.
> https://github.com/BenjV/SYNO-packages
> Download the package to your PC for a manual install.
> Make sure you installed Python 3 from the SynCommunity first.
> 
> If you already have a SickChill version running, please make a backup from within SickChill.
> Then remove that package, manual install the new one, start it and restore the backup from within SickChiil.
> 
> Enjoy.

is version missing?
Under general info it not showing the version.

SickChill Configuration
  SickChill Info:
Branch: master
Commit: b89e9ccf406214f369ad6e74e7d0e77c9048cb33
Version: fatal: No names found, cannot describe anything.
Database Version: 44.5

  Python Version:
3.7.7 (default, Aug 18 2020, 20:42:48) [GCC 4.9.3 20150311 (prerelease)]

  SSL Version:
OpenSSL 1.0.2n 7 Dec 2017

  OS:
Linux-4.4.59+-x86_64-with-glibc2.2.5

  Locale:
en_US.UTF-8

**Comment by miigotu** [comment]
https://github.com/SynoCommunity/spksrc/pull/4161
