### ISSUE TITLE
Sickchill Manual Post Processing Not Working

### ISSUE THREAD

**Issue by potequity** [SickChill/SickChill#6759]
### Before submitting your issue:

Branch/Commit: master / b89e9ccf406214f369ad6e74e7d0e77c9048cb33 
OS: Centos 8 4.18.0-193.14.2.el8_2.x86_64
Browser: Firefox 68.11.0esr (64-bit)
What you did: Launched manual PP via UI
What happened: SC reports "No processable items found in folder" but folder contains the following dir and the dir contains multiple episode .mkv files:

Community.S01.1080p.BluRay.x264-YELLOWBiRD/
   -rw-r--r--. 1 sickchill sickchill 2337787796 Sep 16 17:40 Community.S01E01.1080p.BluRay.x264-YELLOWBiRD.mkv
-rw-r--r--. 1 sickchill sickchill 1555397215 Sep 16 17:40 Community.S01E02.1080p.BluRay.x264-YELLOWBiRD.mkv
-rw-r--r--. 1 sickchill sickchill 1555742573 Sep 16 17:40 Community.S01E03.1080p.BluRay.x264-YELLOWBiRD.mkv
-rw-r--r--. 1 sickchill sickchill 1555441302 Sep 16 17:38 Community.S01E04.1080p.BluRay.x264-YELLOWBiRD.mkv
-rw-r--r--. 1 sickchill sickchill 1554557197 Sep 16 17:38 Community.S01E05.1080p.BluRay.x264-YELLOWBiRD.mkv
-rw-r--r--. 1 sickchill sickchill 1554923679 Sep 16 17:38 Community.S01E06.1080p.BluRay.x264-YELLOWBiRD.mkv

What you expected: SC to move them into the Season_01 sub-dir under /mymedia/downloads/tv/Community/

Logs:
Output of PP from UI:
Postprocessing results
Processing in folder /mymedia/downloads/completed/Community.S01.1080p.BluRay.x264-YELLOWBiRD
Processing /mymedia/downloads/completed/Community.S01.1080p.BluRay.x264-YELLOWBiRD
Processing folder /mymedia/downloads/completed/Community.S01.1080p.BluRay.x264-YELLOWBiRD
/mymedia/downloads/completed/Community.S01.1080p.BluRay.x264-YELLOWBiRD : No processable items found in folder
Processing folder /mymedia/downloads/completed/Community.S01.1080p.BluRay.x264-YELLOWBiRD/Subs
/mymedia/downloads/completed/Community.S01.1080p.BluRay.x264-YELLOWBiRD/Subs : No processable items found in folder
Successfully processed

**Comment by josh-gaby** [comment]
Same issue here, on the latest PIP version 2020.9.16.post2 with the imdbpy installed as suggested here #6755

```
2020-09-17 01:04:41 INFO :: POSTPROCESSOR-AUTO :: Processing /*****/completed/tv
2020-09-17 01:04:41 DEBUG :: POSTPROCESSOR-AUTO :: Processing folder /*****/completed/tv
2020-09-17 01:04:41 DEBUG :: POSTPROCESSOR-AUTO :: Could not properly parse a show and episode from [Medium S03E11 1080p Amazon WEB-DL DD+ 5.1 H.264-TrollHD.mkv]: Unable to match Medium S03E11 1080p Amazon WEB-DL DD+ 5.1 H.264-TrollHD.mkv to a show in your database. Parser result: Medium - S03E11 [GROUP: TrollHD] [ABD: False] [ANIME: False] [whichReg: ['standard']] Score: 5
```

Rolled back to 2020.9.13.post1 and the matching is working again.

**Comment by miigotu** [comment]
Update and try again.

**Comment by josh-gaby** [comment]
Updated to 2020.9.16.post3 and the matching is working again.

**Comment by potequity** [comment]
Ran 'git pull' to apply updates and now manual PP works again! Thanks for taking the time to resolve this issue :+1:
