### ISSUE TITLE
Sickchill -Qbittorrent Python Installer Conflict (Windows)

### ISSUE THREAD

**Issue by Victorvdc** [SickChill/SickChill#6764]
Minor Problem
Probably not worth investigating but easy work around is shown below

I uninstalled SickChill
Reinstalled latest version with Python 3 using Windows Installer
Would not run

Uninstalled Sickchill & Python 3
Rebooted 
Qbittorrent requested Python 3 installation 
Python 3 installed by Qbittorrrent link
Installed SickChill using Windows Installer
Would not run

Uninstalled Sickchill & Python 3
Rebooted 
Qbittorrent requested Python 3 installation 
Deferred Python 3 Installation
Installed SickChill with Python 3 using Windows Installer
Sickchill and Qbittorrent both run OK

Probably not worth investigating but this information may be helpfull if others find the problem

**Comment by miigotu** [comment]
You you try installer version 0.58?

**Comment by miigotu** [comment]
Sec, it is still building and uploading ^^

**Comment by miigotu** [comment]
Ok I finally got it to build. I hate windows lol

**Comment by miigotu** [comment]
Fixed. Use the new installer and there is no longer a conflict.

Uninstall Python3 before uninstalling SickChill or you are stuck with a broken python3 that has to be repaired with a python3 installer exe before uninstalling install (this doesn't happen in the new installer)

**Comment by Victorvdc** [comment]
Fix Verified
Did a complete SickChill reinstall after Qbittorrent installed Python3 first and now  SickChill works fine

Thanks
