### ISSUE TITLE
logger.py syntax error (MacOS)

### ISSUE THREAD

**Issue by kaparmar** [SickChill/SickChill#6772]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: MASTER
OS: MACOS 10.11.6 El Capitan
Browser: n/a
What you did: git pull to update, then clean install
What happened: fail to start
What you expected: sickchill to start
Logs:
```
KMacmini:~ K$ cd '/Users/K/Desktop/SickChill-master/' && '/usr/local/bin/pythonw' -d  '/Users/K/Desktop/SickChill-master/SickChill.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/K/Desktop/SickChill-master/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/Users/K/Desktop/SickChill-master/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/Users/K/Desktop/SickChill-master/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/Users/K/Desktop/SickChill-master/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/Users/K/Desktop/SickChill-master/sickchill/logger.py", line 72
    msg = re.sub(fr'\b({item})\b', '*' * 8, msg)
                                ^
SyntaxError: invalid syntax
```
I have seen that someone else had this issues and it was due to Python support is now moved to Python 3. After finding that, I tried to run it using Python 3.8.2 but I get the same issue.

In fact, this issue started because my SickRage was telling me that auto update wasn't possible because my version was newer than the master? I tried to update by GIT PULL but got an error saying
"
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
"

This lead me to try a clean install, which lead to this issue with the syntax error. (I hope I have the right backup files to carry over to a clean install: cache.db, config.ini, failed.db, gui (folder), sickbeard.db)

Sorry if the solution is obvious, most of the time I'm sure I cause the problems because I'm trying to fix something that probably is not even broken =-/. Thanks in advance for all the help!

**Comment by miigotu** [comment]
There are a dozen closed and open issues about how to solve this. `git fetch origin && git reset --hard origin/master` and make sure it is python3 starting it.
