### ISSUE TITLE
FreeNas: Error on Install.

### ISSUE THREAD

**Issue by tapnikita** [SickChill/SickChill#6780]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 
OS: FreeNas
Browser: Using  Brave
What you did: Try to install
What happened: Failed to install
What you expected: Install
Logs:
```
Error: Sickchill had a failure Exception: RuntimeError Message: Last 10 lines: /root/post_install.sh: git: not found /root/post_install.sh: pip: not found chown: /usr/local/app/sickchill: No such file or directory cp: /usr/local/app/sickchill/contrib/runscripts/init.freebsd: No such file or directory chmod: /usr/local/etc/rc.d/sickchill: No such file or directory Partial plugin destroyed
```

When starting install on freenas, it goes though everything until it hits the Post install scripts, and then says it dont work and removes the VM/Jail. Here is the error:

Error: Sickchill had a failure Exception: RuntimeError Message: Last 10 lines: /root/post_install.sh: git: not found /root/post_install.sh: pip: not found chown: /usr/local/app/sickchill: No such file or directory cp: /usr/local/app/sickchill/contrib/runscripts/init.freebsd: No such file or directory chmod: /usr/local/etc/rc.d/sickchill: No such file or directory Partial plugin destroyed

**Comment by miigotu** [comment]
Not sure how you installed Python3, but pip comes with python3.

**Comment by tapnikita** [comment]
> Not sure how you installed Python3, but pip comes with python3.

This is all from the default installation, nothing modified, in freenas -> Plugins -> Community -> Sickchill -> Install.

Nothing modified. just base install.

**Comment by tapnikita** [comment]
I just did a "Fresh Install" With just Sickchill, Still gives me a error of :

'''Error: Sickchill had a failure Exception: RuntimeError Message: Last 10 lines: /root/post_install.sh: git: not found /root/post_install.sh: pip: not found chown: /usr/local/app/sickchill: No such file or directory cp: /usr/local/app/sickchill/contrib/runscripts/init.freebsd: No such file or directory chmod: /usr/local/etc/rc.d/sickchill: No such file or directory Partial plugin destroyed'''


Screenshot:
[https://prnt.sc/ukcgw2](url)

**Comment by miigotu** [comment]
What version of python? Because pip has been included since 3.4

**Comment by miigotu** [comment]
Lol also cp, chown, chmod not found? Your path is screwed up.

**Comment by tapnikita** [comment]
> Lol also cp, chown, chmod not found? Your path is screwed up.

The sickchill is right from "Freenas" fresh install.

**Comment by miigotu** [comment]
And you installed the python38 package?

**Comment by miigotu** [comment]
```bash
pkg install python38
```
Then:
```bash
pkg install py38-pip
```
Or 
```bash
python3.4 -m ensurepip

```

**Comment by aviv128** [comment]
Also have the same issue with upgrading and fresh install.

**Comment by miigotu** [comment]
`pkg add git`

**Comment by aviv128** [comment]
> `sudo pkg install git`

where did you use it? in the IOCAGE of sickchill or in the main FreeNAS terminal?

**Comment by tapnikita** [comment]
I actually had to update to Truenas destro, Freenas fresh install couldn't get it to work.

**Comment by aviv128** [comment]
@tapnikita  thank you, hope they will sort it out in sickchill community as well

**Comment by miigotu** [comment]
Your main freenas needs git

**Comment by aviv128** [comment]
> Your main freenas needs git

It does have git, as its a dedicated IOCAGE i assume the issue reside there.

**Comment by miigotu** [comment]
What release is your iocage on? 12.1-RELEASE is required.
https://github.com/ix-plugin-hub/iocage-plugin-index/blob/master/sickchill.json (git is specified there)
https://github.com/ix-plugin-hub/iocage-plugin-sickchill/blob/master/post_install.sh only uses packages specified in the json
You cannot upgrade an old python 2.7 jail for sickchill, it used 11.x-RELEASE

**Comment by aviv128** [comment]
@miigotu Thank you!!! my IOCAGE version is 11.3 so that explains it.
As I am always up to date with the STABLE train i did not even think in that direction. appreciate the help and patience and for keep updating sickchill to stay great. will try again when TrueNAS becomes STABLE version.
