### ISSUE TITLE
pip upgrade: No matching distribution found for imdbpy

### ISSUE THREAD

**Issue by lgordon** [SickChill/SickChill#6781]
Branch/Commit: pip
OS: Ubuntu 20.04
Browser: Chrome
What you did: pip3 install sickchill --upgrade
What happened: No matching distribution found for imdbpy

What you expected: update to the latest version per the update available notice which sent me to the pypi site instead of pulling the latest from github
Logs:

Sickchill log:
```
2020-09-20 10:39:33 WARNING :: CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version. Error: TypeError("object of type 'Version' has no len()")
2020-09-20 10:39:33 INFO :: CHECKVERSION :: New update found for SickChill, starting auto-updater ...
```

pip log:
```
Collecting sickchill
  Downloading sickchill-2020.9.20.post2-py3-none-any.whl (15.6 MB)
     |████████████████████████████████| 15.6 MB 3.9 MB/s 
Collecting tvdbsimple
  Downloading tvdbsimple-1.0.6.tar.gz (11 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.1-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 79.8 MB/s 
Collecting deluge-client
  Downloading deluge_client-1.9.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied, skipping upgrade: configobj in /usr/lib/python3/dist-packages (from sickchill) (5.0.6)
Collecting pynma
  Downloading PyNMA-1.0.tar.gz (2.4 kB)
Requirement already satisfied, skipping upgrade: pyOpenSSL in /usr/lib/python3/dist-packages (from sickchill) (19.0.0)
Collecting Mako
  Downloading Mako-1.1.3-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 9.9 MB/s 
Collecting sqlalchemy
  Downloading SQLAlchemy-1.3.19-cp38-cp38-manylinux2010_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 80.7 MB/s 
Collecting guessit
  Downloading guessit-3.1.1.tar.gz (147 kB)
     |████████████████████████████████| 147 kB 81.7 MB/s 
Collecting python-slugify
  Downloading python-slugify-4.0.1.tar.gz (11 kB)
Collecting gntp
  Downloading gntp-1.0.3-py3-none-any.whl (16 kB)
Collecting twilio
  Downloading twilio-6.45.2.tar.gz (454 kB)
     |████████████████████████████████| 454 kB 78.6 MB/s 
ERROR: Could not find a version that satisfies the requirement imdbpy==2020.09.29 (from sickchill) (from versions: 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 4.6, 4.7, 4.8, 4.8.1, 4.8.2, 4.9, 5.0, 5.1.1, 6.0, 6.2, 6.3, 6.4, 6.4.1, 6.5, 6.6, 6.7, 6.8)
ERROR: No matching distribution found for imdbpy==2020.09.29 (from sickchill)
```

**Comment by lgordon** [comment]
Looks like the data 2020.09.29 (in the future) was a typo in imdbpy and has since been fixed. See: https://github.com/alberanid/imdbpy/commit/bfdbdd085a551a4f355ff7557a364e27e8f892af#diff-91b7eb6773b179bcd6fb0d6b52854b38

Although, I'm not sure if pip will be able to use this date/version?

**Comment by lgordon** [comment]
Thanks! Athough this still doesn't seem to resolve the pip upgrade issue.
```
ERROR: Could not find a version that satisfies the requirement imdbpy==2020.09.29 (from sickchill) (from versions: 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 4.6, 4.7, 4.8, 4.8.1, 4.8.2, 4.9, 5.0, 5.1.1, 6.0, 6.2, 6.3, 6.4, 6.4.1, 6.5, 6.6, 6.7, 6.8)
ERROR: No matching distribution found for imdbpy==2020.09.29 (from sickchill)
```

**Comment by lgordon** [comment]
I'm still getting an error for imdbpy
`ERROR: Could not find a version that satisfies the requirement imdbpy==2020.09.20 (from sickchill) (from versions: 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 4.6, 4.7, 4.8, 4.8.1, 4.8.2, 4.9, 5.0, 5.1.1, 6.0, 6.2, 6.3, 6.4, 6.4.1, 6.5, 6.6, 6.7, 6.8)
ERROR: No matching distribution found for imdbpy==2020.09.20 (from sickchill)
`

**Comment by miigotu** [comment]
You likely have an upgrade for pip available.

**Comment by miigotu** [comment]
This would be solved if imdbpy would just make a release to pypi, even if it is a dev release.

**Comment by josh-gaby** [comment]
> I'm still getting an error for imdbpy
> `ERROR: Could not find a version that satisfies the requirement imdbpy==2020.09.20 (from sickchill) (from versions: 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 4.6, 4.7, 4.8, 4.8.1, 4.8.2, 4.9, 5.0, 5.1.1, 6.0, 6.2, 6.3, 6.4, 6.4.1, 6.5, 6.6, 6.7, 6.8) ERROR: No matching distribution found for imdbpy==2020.09.20 (from sickchill) `

I was getting the same error but pip was already up to date
` ~/pip3/bin/pip install --upgrade pip`
`Requirement already up-to-date: pip in ./pip3/lib/python3.8/site-packages (20.2.3)`

Fixed by manually upgrading imdbpy
` pip install --upgrade git+https://github.com/alberanid/imdbpy#egg=imdbpy`
