### ISSUE TITLE
[Feature Request] New Menu Item: "Jump to Show" drop-down list

### ISSUE THREAD

**Issue by jamver** [SickChill/SickChill#6783]
Feature Request:

Remove the "Change Show" drop-down list from "Show" pages.

Add "Jump to Show" drop-down to menu bar, centred between SickChill Banner icon and "Shows" menu item.

On any non-show page, insert 2 non-active entries to the list: "Jump to Show" (1st option / list title, default selected) and "---" (second option / spacer).

If we are currently on a "Show" page, show the current show as the selected option in the drop-down list and display the "Previous Show" and "Next Show" blue arrows on either side of the "All Shows" drop-down list.

i.e.

> SC banner <--> "Jump to Show" (drop-down list) <--> Shows (menu) || Schedule || History || Manage (menu) || Config (menu) || Tools (menu)

and

> SC banner <--> Previous Show/Left Arrow || "The SickChill Hour" (drop-down list) || Next Show/Right Arrow <--> Shows (menu) || Schedule || History || Manage (menu) || Config (menu) || Tools (menu)

**Comment by jamver** [comment]
This save time (possibly a minute or more) when navigating to a specific show, due to need to navigate to the "Show List" page and then searching for the desired show in the current design.

**Comment by miigotu** [comment]
Maybe a search box, a drop-down doesn't work because we also have movie support partially integrated.

**Comment by jamver** [comment]
Mixed-mode search/list to allow for both options?  Perhaps exclude all shows that are "Ended" and complete from the list?

**Comment by miigotu** [comment]
What you are asking for is unnecessary, it saves a grand total of 1 click (Home/main page) and the filter is on all layouts:
![image](https://user-images.githubusercontent.com/390379/94101913-daa52d00-fdfe-11ea-97d8-8d022b19791c.png)
![image](https://user-images.githubusercontent.com/390379/94101946-eee92a00-fdfe-11ea-86ba-98bd0f00ed29.png)
![image](https://user-images.githubusercontent.com/390379/94101976-058f8100-fdff-11ea-990d-29230ffffc97.png)
![image](https://user-images.githubusercontent.com/390379/94102001-13450680-fdff-11ea-8d75-ac38fd35cf46.png)

**Comment by jamver** [comment]
Probably because I never use the home/shows page, as it doesn't provide the information I usually want – I keep SickChill open on the Schedule page.  From the Schedule page, it is 2 clicks.

What I really want is the feature I requested on the Schedule page, but thought it might be more universally useful if it was in the title bar, rather than only shown on a specific show's page.

**Comment by miigotu** [comment]
We have to maintain the space in the title bar because of mobile layout, especially since I added movies to the menu bar.

**Comment by jamver** [comment]
I've never seen movies in SickChill, but I imagine you would have it auto-flow/hide (like Shows) and coalesce into the menu/burger button.

Alternatively, could you just add the "Change Show" as "Jump to Show" at the top of the Schedule page?

**Comment by miigotu** [comment]
It isnt public or completed yet:
![image](https://user-images.githubusercontent.com/390379/94105199-c6652e00-fe06-11ea-9a32-2a484c4d7c19.png)
![image](https://user-images.githubusercontent.com/390379/94105384-222fb700-fe07-11ea-9295-f005a1f2fafd.png)
![image](https://user-images.githubusercontent.com/390379/94105415-2f4ca600-fe07-11ea-87f8-f06bb62f0bdb.png)
![image](https://user-images.githubusercontent.com/390379/94105425-37a4e100-fe07-11ea-93e4-6f4e22b20285.png)

**Comment by miigotu** [comment]
![image](https://user-images.githubusercontent.com/390379/94105472-530fec00-fe07-11ea-8e70-14924ee03223.png)
