### ISSUE TITLE
Error after latest pip upgrade (2020.9.20.post7)

### ISSUE THREAD

**Issue by zeeter82** [SickChill/SickChill#6784]
ERROR: Could not find a version that satisfies the requirement imdbpy==2020.09.20 (from sickchill) (from versions: 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 4.6, 4.7, 4.8, 4.8.1, 4.8.2, 4.9, 5.0, 5.1.1, 6.0, 6.2, 6.3, 6.4, 6.4.1, 6.5, 6.6, 6.7, 6.8)
ERROR: No matching distribution found for imdbpy==2020.09.20 (from sickchill)

It appears I tried upgrading from "Version: 2020.9.10.post3"

Any ideas?

**Comment by miigotu** [comment]
Upgrade pip

**Comment by lobofoots** [comment]
Try this: pip install --use-feature=2020-resolver -U sickchill
it worked for me

**Comment by zeeter82** [comment]
That didn't work.  Seemed to make it worse because now my service won't even start.

That cmd did run and appeared to have good output, but still didn't upgrade my instance as expected.  Also I can still run: pip3 install -U sickchill

It still produces the error from above.

**Comment by josh-gaby** [comment]
I was getting the same error and pip was already up to date

Fixed it by manually upgrading imdbpy using 
`pip install --upgrade git+https://github.com/alberanid/imdbpy#egg=imdbpy`

**Comment by zeeter82** [comment]
Yep my pip is already showing up to date as well.  I'll try your suggestion Josh and report back.


Thanks!

**Comment by zeeter82** [comment]
_Successfully built imdbpy
Installing collected packages: imdbpy
  Attempting uninstall: imdbpy
    Found existing installation: IMDbPY 6.8
    Uninstalling IMDbPY-6.8:
      Successfully uninstalled IMDbPY-6.8
Successfully installed imdbpy-2020.9.20_

Success!  Up and running again :)

**Comment by einarsi** [comment]
Perhaps this can be fixed temporarily until imdbpy pushes a release by changing this line in requirements.txt:
```imdbpy==2020.09.20```
to
```git+https://github.com/alberanid/imdbpy```
?
I've done something similar to one of my projects before.

**Comment by DrDrewZA** [comment]
> I was getting the same error and pip was already up to date
> 
> Fixed it by manually upgrading imdbpy using
> `pip install --upgrade git+https://github.com/alberanid/imdbpy#egg=imdbpy`

so I am in the same situation where my sickchill isnt running after this upgrade.  I dont have git installed - is there another way to manually upgrade imdbpy to the correct version without going to all the trouble of installing git?

**Comment by einarsi** [comment]
> so I am in the same situation where my sickchill isnt running after this upgrade. I dont have git installed - is there another way to manually upgrade imdbpy to the correct version without going to all the trouble of installing git?

If you don’t want to run an ‘apt install git’ before pip installing git+https, then you can try to download/wget a tarball of imdbpy from github and install directly from it. My bet is it will be quicker to install and use git - no config should be necessary.

**Comment by miigotu** [comment]
I made a change to the dependency links to use a tar all instead. Maybe it fixes the issue maybe it doesn't.

Tested with pip 20.1.1 and 20.2.3 and it works here.

**Comment by miigotu** [comment]
And otherwise `pip install --upgrade git+https://github.com/alberanid/imdbpy#egg=imdbpy-2020.09.20`

**Comment by lgordon** [comment]
I manually installed imdbpy-2020.09.20 from git+https using pip 20.0.4 but I'm still getting the error that pip can't find the right version when I upgrade sickchill.

**Comment by miigotu** [comment]
Maybe pgrade your pip.
`pip install -U pip`
Pip current version is 20.2.3

**Comment by lgordon** [comment]
I was hesitant to install that since the previous version was in the ubuntu repositories but I just did and it works. Thanks.
