### ISSUE TITLE
pip upgrade error

### ISSUE THREAD

**Issue by DrDrewZA** [SickChill/SickChill#6785]
When running a pip upgrade command, which I do regularly, im now given an error message saying that one of the requirements cant be upgraded to the correct version - looks like sickchill is looking for a version that doesnt exist.

text reads: Could not find a version that satisfies the requirement imdbpy==2020.09.20 (from sickchill) (from versions: 2.9, 2.9 *every version up to 6.8 listed*

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by josh-gaby** [comment]
Duplicate of #6784

See my reply to the above issue

**Comment by DrDrewZA** [comment]
> Duplicate of #6784
> 
> See my reply to the above issue

100% - thanks Ive worked through that post and seem to have it sorted
