### ISSUE TITLE
has trouble getting episodes for most tv shows especially older ones

### ISSUE THREAD

**Issue by liam2003** [SickChill/SickChill#6793]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Fix the providers you are using. If you limit it to a site that has cloudflare and you are unable to pass cloudflare obviously it isn't going to get any episodes.
