### ISSUE TITLE
File scanning fails

### ISSUE THREAD

**Issue by armontero** [SickChill/SickChill#6797]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: FreeBSD
Browser: Chrome
What you did: Added existing show (all files downloaded already).  I then noticed that Sickchill was reporting only half or some small percentage of episodes downloaded. I then clicked "Rescan Files".
What happened:  The show downloaded metadata correctly, but only some downloaded files were appearing as downloaded.  There were lots of errors like the one below about the utf-8 encoding.
What you expected:  Expected the show to be added and all episodes to show already downloaded.
Logs:
```
PASTE LOGS HERE
Fatal error executing query with db.mass_action in database /usr/local/sickchill/sickchill.db: 'utf-8' codec can't encode characters in position 53-54: surrogates not allowed
(tons of these continue)
```

I had a running version of Sickchill prior to the Python 3 upgrade.  One time I clicked "update" in sickchill and then sickchill wouldn't restart.  Tried a couple of things others on this board recommended, but no luck.  Got tired and decided to do a fresh install.  I got the fresh install working and added my shows back.  That's when I noticed this problem.

**Comment by miigotu** [comment]
https://www.b1c1l1.com/blog/2011/05/09/using-utf-8-unicode-on-freebsd/
