### ISSUE TITLE
Smaller second sample video file replaces larger correct episode video file when processing directory

### ISSUE THREAD

**Issue by cgatesman** [SickChill/SickChill#6801]
Version: v2020.09.24-2 

I ran into a case where a sample video was chosen when processing an episode directory.  The files in the directory were:

Name | Size
---- | ----
abc.xyz.a46ed883f5b77c.nfo | 182 bytes
abc.xyz.232a6aedf1a66c.mkv | 3.18 GB
abc.xyz.7d5d8b7712c4c5.mkv | 66.1 MB

When I processed the directory, it first chose and moved the correct 3GB video, but then proceeded to replace it with the 66MB sample video (I have replaced directory and show names for privacy):

```
Processing in folder /NewMedia/New.Show.2020.S01E08
Processing /NewMedia/New.Show.2020.S01E08
Processing folder /NewMedia/New.Show.2020.S01E08
Processing /NewMedia/New.Show.2020.S01E08/abc.xyz.232a6aedf1a66c.mkv (None)
Retrieving episode object for 1x8
Snatch history had a quality in it, using that: 1080p WEB-DL
This was manually downloaded but it appears to be better quality than what we have so I'm marking it as priority
Is ep a priority download: True
There is no existing file so there's no worries about replacing it
This download is marked a priority download so I'm going to replace an existing file if I find one
Found release name New.Show.2020.S01E08
Destination folder for this episode: /TV/New Show (2020)/Season 01
Moving file from /NewMedia/New.Show.2020.S01E08/abc.xyz.232a6aedf1a66c.mkv to /TV/New Show (2020)/Season 01/New.Show.2020.S01E08.mkv
Processing succeeded for /NewMedia/New.Show.2020.S01E08/abc.xyz.232a6aedf1a66c.mkv
Processing /NewMedia/New.Show.2020.S01E08/abc.xyz.7d5d8b7712c4c5.mkv (None)
Retrieving episode object for 1x8
Snatch history had a quality in it, using that: 1080p WEB-DL
Is ep a priority download: False
File /TV/New Show (2020)/Season 01/New.Show.2020.S01E08.mkv is larger than /NewMedia/New.Show.2020.S01E08/abc.xyz.7d5d8b7712c4c5.mkv
No associated files for /TV/New Show (2020)/Season 01/New.Show.2020.S01E08.mkv were found during this pass
Deleting file /TV/New Show (2020)/Season 01/New.Show.2020.S01E08.mkv
Found release name New.Show.2020.S01E08
Destination folder for this episode: /TV/New Show (2020)/Season 01
Moving file from /NewMedia/New.Show.2020.S01E08/abc.xyz.7d5d8b7712c4c5.mkv to /TV/New Show (2020)/Season 01/New.Show.2020.S01E08.mkv
Processing succeeded for /NewMedia/New.Show.2020.S01E08/abc.xyz.7d5d8b7712c4c5.mkv
Found unwanted files: ['abc.xyz.232a6aedf1a66c.mkv', 'abc.xyz.7d5d8b7712c4c5.mkv']
Deleted folder: /NewMedia/New.Show.2020.S01E08
Successfully processed
```

I would think it should just select the largest video as the correct one.  Even if it does go through and try to process each video file, it should not replace a moved video file with a smaller sized video.

**Comment by Smokey23** [comment]
@cgatesman,
Usually Sample files contain the word sample in the file name.  Is that the case with the smaller files?

**Comment by cgatesman** [comment]
No.  I listed the file names in my description.  I don't think the file name should matter.  It's replacing a processed 3GB file with a 66MB file just because it doesn't have "sample" in the filename?

**Comment by miigotu** [comment]
File size has nothing to do with anything. A 1080p file with x265 is smaller than a 720p with x264.

The file names are not scene compliant, we have scene rules for a reason that all actual scene groups follow for a reason.

SickChill (and all forks of SickBeard) only operates well with scene compliant release names, and file names. We make some concessions to try and make non-compliant names work, but it is not perfect. Nor can it be.

**Comment by cgatesman** [comment]
I think it's safe to say there would not be multiple compressions of the same full episode under an episode directory which is being processed.  This isn't a matter of trying to compare an episode video being processed to one that is already added to SickChill.  It is processing an episode directory containing two video files.
