### ISSUE TITLE
SickChill does not start after fresh install on Windows using installer

### ISSUE THREAD

**Issue by exi2163** [SickChill/SickChill#6807]
SickChill does not start after a fresh install on Windows when using the installer.

Branch/Commit: master
OS: Windows
Browser: -
What you did: Install
What happened: Errors
What you expected: No errors
Logs:
...
  File "C:\Download\SickChill\SickChill\lib3\enzyme\parsers\ebml\__init__.py", l
ine 2, in <module>
    from .core import *
  File "C:\Download\SickChill\SickChill\lib3\enzyme\parsers\ebml\core.py", line
4, in <module>
    from pkg_resources import resource_stream  # @UnresolvedImport
  File "C:\Download\SickChill\SickChill\lib3\pkg_resources\__init__.py", line 32
, in <module>
    import plistlib
  File "<frozen zipimport>", line 259, in load_module
  File "plistlib.py", line 65, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "xml\parsers\expat.py", line 4, in <module>
ImportError: DLL load failed while importing pyexpat: Das angegebene Modul wurde
 nicht gefunden.

Reason: The installer does not check for the prerequisites of the included Python3.6. If a system lacks the Microsoft Visal C++ 2015 redistributables the above error will prevent SickChill from starting.
Installing https://www.microsoft.com/en-us/download/details.aspx?id=53587 resolved the issue.

**Comment by miigotu** [comment]
What windows version are you on?

**Comment by exi2163** [comment]
That system had windows 7. I just confirmed a similar problem on Windows Server 2012R2. 
The error on 2012R2 is a bit more helpful though is it states that "api-ms-win-crt-runtime-l1-1-0.dll" is missing.

**Comment by miigotu** [comment]
I'll try to make the installer check for it, but no promises. Technically those are installed automatically on vista and newer through windows update.
