### ISSUE TITLE
Scheme ignored in qBittorrent endpoint configuration

### ISSUE THREAD

**Issue by ti-mo** [SickChill/SickChill#6808]
Hi @miigotu! I've stumbled across a small bug in the qbittorrent search settings. This started showing up after merging the py3 branch.

When configuring an HTTPS endpoint in `Torrent host:port`, for example `https://qbt.example.com`, SickChill automatically assumes a default port of 8080. This leads to the following error when testing the connection:

```
Failed to authenticate with qBittorrent, Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='qbt.example.com', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused'))"))
```

When overriding the port to 443 by configuring an endpoint like `https://qbt.example.com:443`, a different error occurs:
`Failed to authenticate with qBittorrent, Client sent an HTTP request to an HTTPS server.`

I've had a similar issue with a SickChill version of a couple of days ago, where the error message would just display `'Failed to authenticate with qbittorrent,` with no further information. I tracked down the root cause to an interaction with `qbittorrent-api` [setting the `Origin` header](https://github.com/rmartin16/qbittorrent-api/blob/master/qbittorrentapi/request.py#L290) to eg. `qbt.example.com:443` where qBittorrent was expecting `https://qbt.example.com` instead. I temporarily worked around this by disabling CSRF protection in the qbt web UI. To me, this looks like a bug in `qbittorrent-api`, but it's triggered by an interaction with the port splitting logic in `qbittorrent.py` here in SickChill.

From what I can understand, these two issues look like they have the same root cause: wrongfully instantiating the qbt-api client with a `port` override. Perhaps the default port of 8080 should not be applied in case a scheme is specified in the connection string?

Cheers,

**Comment by miigotu** [comment]
Scheme is not ignored by anything, we split the host name and port and pass it just as you give it. If port is not supplied 8080 is the default (which can be an SSL port)
```python
import qbittorrentapi
VERIFY_WEBUI_CERTIFICATE=False
api = qbittorrentapi.Client('127.0.0.1', '8080', 'admin', 'adminadmin', VERIFY_WEBUI_CERTIFICATE=False)
api
<qbittorrentapi.client.Client object at 0x7f11ace0fe20>
api.auth_log_in()
api.is_logged_in
True
api.app_preferences().get('queueing_enabled')
False
api = qbittorrentapi.Client('https://127.0.0.1', '8080', 'admin', 'adminadmin', VERIFY_WEBUI_CERTIFICATE=False)
api.auth_log_in()
api.is_logged_in
True
api.host
'https://127.0.0.1'
api.app_preferences().get('queueing_enabled')
False
```

Your qbittorrent configuration is wrong

**Comment by miigotu** [comment]
Set your domains in the qbittorrent settings:
![image](https://user-images.githubusercontent.com/390379/94373227-f3993100-00d1-11eb-82ef-7cce3bd9d615.png)

**Comment by ti-mo** [comment]
Hi, not sure why this report was so quickly dismissed. My qbt is not misconfigured. I've disabled all checkboxes under 'Security', and 'server domains' is set to * (the default):
![image](https://user-images.githubusercontent.com/3214460/94375453-046a9680-0114-11eb-925a-97d9a3470a28.png)

In the snippet you pasted above, in both cases, you're establishing a connection to a plaintext HTTP endpoint (8080), so it just happens to work correctly.

qbittorrentapi seems to always establish plaintext HTTP connections when a port is given to `Client`'s constructor:
```
>>> import qbittorrentapi
>>> qbittorrentapi.Client(host='https://qbt.example.com', username='admin', password='adminadmin', port=443).auth_log_in()
Traceback (most recent call last):
<snip>
  File "qbittorrent-api/qbittorrentapi/request.py", line 327, in handle_error_responses
    raise InvalidRequest400Error(response.text)
qbittorrentapi.exceptions.InvalidRequest400Error: Client sent an HTTP request to an HTTPS server.

>>> qbittorrentapi.Client(host='https://qbt.example.com', username='admin', password='adminadmin').auth_log_in()
>>>
```

This is triggered by SickChill always providing a port (to default to 8080) in qbittorrent.py: `port=self.port or 8080,`.

---

The stuff I mentioned about the `Origin` header being generated incorrectly is adjacent to this issue, but would be fixed by only specifying a port to `Client()` if the user actually specifies a port in the connection string. It's still incorrect, though, and tripped the CSRF protector in my environment when I tested last week.

Would you like me to file an issue against qbt-api directly instead?

**Comment by lobofoots** [comment]
Had the same issue since a while back, after the python 3 change.
Had to change port in qbittorent to 8080 instead of 80 that I wanted to use.
My qbittorrent config is set to * in the security settings.
Will try with miigotu's settings.

**Comment by miigotu** [comment]
8080 is not an http endpoint. 8080 is https if you set qbittorent to run using https and do not change the port. CONVENTION says you should run https on another port than the standard 80 (public http) or 8080 (private http) conventional ports, but that doesn't stop you from putting an https server there.

**Comment by miigotu** [comment]
![image](https://user-images.githubusercontent.com/390379/94377010-2cde9a80-00ec-11eb-91e6-8cbdba3d1b1a.png)
![image](https://user-images.githubusercontent.com/390379/94377016-3bc54d00-00ec-11eb-9806-e697325ebd39.png)

**Comment by miigotu** [comment]
> 8080 is not an http endpoint. 8080 is https if you set qbittorent to run using https and do not change the port. CONVENTION says you should run https on another port than the standard 80 (public http) or 8080 (private http) conventional ports, but that doesn't stop you from putting an https server there.

You just needed to put 80 in the host field: `http://my.ip.or.domain:80` as long as it was available there.

**Comment by miigotu** [comment]
![image](https://user-images.githubusercontent.com/390379/94377209-898e8500-00ed-11eb-918f-943acf2b3c2a.png)
```python
api = qbittorrentapi.Client('https://127.0.0.1', '10443', 'admin', 'adminadmin', VERIFY_WEBUI_CERTIFICATE=False)
api.auth_log_in()
api._API_URL_BASE.geturl()
'https://127.0.0.1:10443'
api.is_logged_in
True
from qbittorrentapi.definitions import APINames
response = api._get(_name=APINames.Authorization, _method='logout')
response
<Response [200]>
response.request.url
'https://127.0.0.1:10443/api/v2/auth/logout'
response.url
'https://127.0.0.1:10443/api/v2/auth/logout'
response.headers
{'connection': 'keep-alive', 'content-length': '0', 'content-security-policy': "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self'; frame-ancestors 'self'; upgrade-insecure-requests;", 'content-type': 'text/plain', 'date': 'Sun, 27 Sep 2020 22:20:32 GMT', 'referrer-policy': 'same-origin', 'set-cookie': 'SID=; expires=Sat, 26-Sep-2020 22:20:32 GMT; path=/', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block'}
response.request.headers
{'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Referer': 'https://127.0.0.1:10443', 'Origin': 'https://127.0.0.1:10443', 'Cookie': 'SID=/vjZzDHvQADc2IWr/oXpEN7GShIFs5+C'}
```

Lets argue?

**Comment by miigotu** [comment]
If anything you need to open up an issue with the lib, to not supply the port to the URL and cors headers when the url is HTTP and port 80 or HTTPS and port 443.

**Comment by miigotu** [comment]
I apologize, I did not realize I didn't have to pass a port at all and I misread some parts of your posts.
> This is triggered by SickChill always providing a port (to default to 8080) in qbittorrent.py: port=self.port or 8080,
Indeed is the problem.
