### ISSUE TITLE
Show Customization Issues

### ISSUE THREAD

**Issue by Torhal** [SickChill/SickChill#6809]
I've set the Poster, Banner, and Background images for a few shows and have noticed some oddities:

1. From the image selection modal, nothing happens when selecting an image source (FanArt, TMDB, theTVDB); you must exit the modal and respawn it to trigger a change.
2. The poster selection works from the show view and the show list view, but doesn't apply to the schedule view - the original poster is shown there.
3. The background selection doesn't seem to do anything - the original background is shown when viewing the show.

Using Chrome, if that matters for the image selection issue.

**Comment by Nyaran** [comment]
> I've set the Poster, Banner, and Background images for a few shows and have noticed some oddities:
> 
>     1. From the image selection modal, nothing happens when selecting an image source (FanArt, TMDB, theTVDB); you must exit the modal and respawn it to trigger a change.

I was able to reproduce the problem. Investigating...

>     2. The poster selection works from the show view and the show list view, but doesn't apply to the schedule view - the original poster is shown there.

That is because the images cache on browser, just do a force reload (Control + F5 OR Control + R). Anyway, I'll try to fix it

>     3. The background selection doesn't seem to do anything - the original background is shown when viewing the show.
Same as above.

> Using Chrome, if that matters for the image selection issue.

**Comment by Torhal** [comment]
Ok - force-refresh did the trick (⌘-SHIFT-R on macOS) for posters and backgrounds. I didn't consider trying that because the banner and poster images didn't require it on the show view, just the background, and the poster image updated automatically on the show view, just not the schedule view. Thanks!
