### ISSUE TITLE
[APP SUBMITTED]: XML or text declaration not at start of entity: line 2, column 0

### ISSUE THREAD

**Issue by itsme9x** [SickChill/SickChill#6811]
### INFO
Python Version: **3.7.7 (default, Sep 19 2020, 16:20:47) [GCC 4.9.4 20150629 (prerelease)]**
Operating System: **Linux-4.4.59+-aarch64-with-glibc2.17**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@37657586de6ed01fbc3fddad92ede679aa44209f
Link to Log: https://gist.github.com/5bf120ac73ae5846f580aa5ba0386997
### ERROR
```
[BSPlayer] ERROR: XML or text declaration not at start of entity: line 2, column 0.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Nyaran** [comment]
BSPlayer servers returned an error, that usually happens when you perform multiple requests in a short time

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]**
Operating System: **Linux-5.4.51-v7+-armv7l-with-debian-10.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
[BSPlayer] ERROR: XML or text declaration not at start of entity: line 2, column 0.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.7.7 (default, Sep 19 2020, 16:20:47) [GCC 4.9.4 20150629 (prerelease)]**
Operating System: **Linux-4.4.59+-aarch64-with-glibc2.17**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
Link to Log: https://gist.github.com/5789f9f875ef52ed9cead8ef89835657
### ERROR
```
[BSPlayer] ERROR: XML or text declaration not at start of entity: line 2, column 0.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]**
Operating System: **Linux-5.4.51-v7+-armv7l-with-debian-10.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
[BSPlayer] ERROR: XML or text declaration not at start of entity: line 2, column 0.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.7.7 (default, Sep 27 2020, 05:32:30) [GCC 4.9.4 20150629 (prerelease)]**
Operating System: **Linux-4.4.59+-aarch64-with-glibc2.17**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
[BSPlayer] ERROR: XML or text declaration not at start of entity: line 2, column 0.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
