### ISSUE TITLE
Sickchill won't install with FreeNAS gui

### ISSUE THREAD

**Issue by jrvd007** [SickChill/SickChill#6814]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: FreeNAS
Browser: Chrome
What you did: I went in the FreeNAS plugins section and tried to install SickChill. I named the jail sickchill and did not change anything else to limit any potential problems.
What happened:
I got the following error:

"Error: sickchill had a failure Exception: RuntimeError Message: Last 10 lines: /root/post_install.sh: git: not found /root/post_install.sh: pip: not found chown: /usr/local/app/sickchill: No such file or directory cp: /usr/local/app/sickchill/contrib/runscripts/init.freebsd: No such file or directory chmod: /usr/local/etc/rc.d/sickchill: No such file or directory Partial plugin destroyed"

What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Requires TrueNAS CORE 12+, 11.3 does not have python3.6+
