### ISSUE TITLE
Question: Sickchill service won't start after OS upgrade, what to do?

### ISSUE THREAD

**Issue by knyllers** [SickChill/SickChill#6819]
Hi,

this is more of a question about what I need to do to get it working again after an OS upgrade than an issue with the sickchill software itself (I think).
So, I upgraded Ubuntu from 18.04 LTS to 20.04 LTS and after the fact sickchill won't start. See service status below.
Sickchill service points to python3.6 which is there, but command 'python3 --version' returns python 3.8.1, which is different.
According to doc sickchill should run on python 3.6+, so 3.8.1 should be ok? Could the problem be that sickchill is using the /usr/bin/python3.6 while system is on 3.8.1?

Any idea of what the best course of action would be? Any help is appreciated.

Thank you!
Kind regards,
knyllers

Branch/Commit: sickchill 2020.9.28.post2
OS: Ubuntu 20.04 LTS
Browser: Chrome
What you did: Upgraded from Ubuntu 18.04 LTS to Ubuntu 20.04
What happened: Sickchill service start fails
What you expected: Sickchill service start succeeds
Logs:
```
sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2020-09-29 20:03:18 CEST; 29min ago
    Process: 1149 ExecStart=/usr/bin/python3.6 /home/myuser/.local/bin/SickChill.py -q --daemon --nolaunch --datadir=/home/henrik/s>

Sep 29 20:03:18 localhost systemd[1]: Starting SickChill Daemon...
Sep 29 20:03:18 localhost  python3.6[1149]: Traceback (most recent call last):
Sep 29 20:03:18 localhost  python3.6[1149]:   File "/home/myuser/.local/bin/SickChill.py", line 6, in <module>
Sep 29 20:03:18 localhost  python3.6[1149]:     import shutil
Sep 29 20:03:18 localhost  python3.6[1149]: ModuleNotFoundError: No module named 'shutil'
Sep 29 20:03:18 localhost  systemd[1]: sickchill.service: Control process exited, code=exited, status=1/FAILURE
Sep 29 20:03:18 localhost  systemd[1]: sickchill.service: Failed with result 'exit-code'.
Sep 29 20:03:18 localhost  systemd[1]: Failed to start SickChill Daemon.
```

**Comment by miigotu** [comment]
I'm assuming you installed with pip? And with --user?
`pip3 install --user -U --force-reinstall sickchill`

**Comment by knyllers** [comment]
I did, still didn't work. But after some fiddling it seems there was some problem running both python3.6 and .3.8 at the same time. I did an 'apt-get autoremove' which removed the 3.6 version. Then changed the sickchill.service to point to /usr/bin/python3.8. Then it worked. Now I just need to get sabnzbplus working again, puh!
Thanks for the assist.
