### ISSUE TITLE
Mako error, can't view logs/search/download after fresh reinstall w/win installer

### ISSUE THREAD

**Issue by proctophage** [SickChill/SickChill#6821]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/7b98df06ad3357a377d64bf31e11db8d4e372f8f/v2020.09.28-2

OS: Windows 10 v 10.0.18363 N/A Build 18363

Browser: Chrome

What you did: 

Clicked "view log"
I also tried forcing generation of logs by doing manual updates/searches, restarting, etc. It doesn't seem to be able to find things with searches either, though I've confirmed connection & settings. I should note that I'm running the sickchill service as a user account because I'm using a network drive that SYSTEM can't see. This setup worked prior to the python3 update.

What happened: Logs did not display, manual searches can't find things I can manually confirm are available according to my search settings.

What you expected: Logs to display, searcher to search/download

Logs:

FixME

A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

Traceback (most recent call last):
File C:\SickChill\SickChill\sickchill\views\index.py:185, in async_call:
return function(**kwargs)
File C:\SickChill\SickChill\sickchill\views\logs.py:75, in viewlog:
data = sickchill.logger.log_data(min_level, log_filter, log_search, max_lines)
File C:\SickChill\SickChill\sickchill\logger.py:425, in log_data:
data += [line.strip() + '\n' for line in reversed(f.readlines()) if line.strip()]
File encodings\cp1252.py:23, in decode:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 226: character maps to

**Comment by miigotu** [comment]
Open an admin command prompt:
```bash
net stop sickchill
ren c:\sickchill\data\logs c:\sickchill\old_logs
net start sickchill
```

**Comment by proctophage** [comment]
Well I feel silly. You're doing the Lord's work miigotu, thank you!
