### ISSUE TITLE
Interface language issue

### ISSUE THREAD

**Issue by didli** [SickChill/SickChill#6823]
SickChill Info:
- Branch: master
- Commit: 7b98df06ad3357a377d64bf31e11db8d4e372f8f
- Database Version: 44.2
- Python Version:3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]

Not sure if it's an issue regarding sickchill or my browser (Brave x64 Linux), but the contextual menus from the interface that allows to change the status for a tv-show/anime (archived, skipped, ignored ... etc) shows up in french (which is registered as my locale, while I have no idea where to change this), while I want to the whole interface in english (Note : this issue showed up recently, didn't have this issue before). 
Any idea what I need to do please ?

**Comment by didli** [comment]
Took my hammer out and pummelled the FR locale folders in my sickchill path. That ... worked. 
Any non-brutish way to do the same thing ^^' ?

**Comment by miigotu** [comment]
Config->general->interface->interface language

**Comment by didli** [comment]
The problem is that English (US) is already setup there, and always had been, but I still see french for the contextual menus mentionned previously.
