### ISSUE TITLE
search order is newest first?

### ISSUE THREAD

**Issue by OneCDOnly** [SickChill/SickChill#6825]
Hi guys. :)

Did something change recently with regard to the order episodes are searched-for and grabbed? 

If I add a TV show with several seasons, my SickChill is searching for the episodes "newest first", whereas, I want the oldest episodes first, so I can begin watching the show. 

Can this be changed? Is there a setting somewhere already in SickChill I can change to set this? 

Thank you.

**Comment by OneCDOnly** [comment]
Some more behavior to note. 

The search order was newest-to-oldest when first adding a show and performing multiple season searches. 

I've just now tried a single season search on an existing show, and search order was oldest-to-newest. Weird.

**Comment by miigotu** [comment]
The search strings are sorted alphabetical

**Comment by OneCDOnly** [comment]
I've been testing the season packs settings in-case this was the cause, but nope. Still the same. 

Here's an example (ignore the first line, which is obviously a movie).

I've just set seasons 9 and 8 of this TV show to wanted in SickChill, and the order they were found (and passed to SABnzbd) is newest-episode to oldest-episode:

![](https://i.imgur.com/5p057pc.png)

This happens even when adding a single season.

**Comment by miigotu** [comment]
Those sure look like they were multipart nzbs, which get split and sent separately.

**Comment by OneCDOnly** [comment]
Here's my NZBHydra history: note the times
![](https://i.imgur.com/M4GATOz.png)

Then I turned off season packs and grabbed more seasons:
![](https://i.imgur.com/eMA4zPv.png)

The requests are coming from SickChill in newest-to-oldest order.

**Comment by miigotu** [comment]
Possibly the newest ones are found in the rss/daily search before string searches (backlog) are even used. We always do a daily search update first.
