### ISSUE TITLE
Sickchill post-processes files in subfolders within folders named with prefix _UNPACK_

### ISSUE THREAD

**Issue by Tensai75** [SickChill/SickChill#6828]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Install: pip
Version: v2020.09.28-2
Database Version: 44.5
Python-Version: 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
SSL-Version: OpenSSL 1.1.1g 21 Apr 2020
OS: Linux-4.15.0-99-generic-x86_64-with

What you did: Sickchill is set to monitor the folder "/downloads" for postprocessing. This is the folder where sabnzbd is saving the usenet downloads. sabnzbd does extract the downloaded files into a subfolder temporarily named with a prefix \_UNPACK\_ and after unpacking has been completed the folder is renamed to the final name removing the \_UNPACK\_ prefix.
What happened: Sickchill does postprocess files in subfolders within the folder named with the prefix \_UNPACK\_ 
What you expected: a folder named with a prefix \_UNPACK\_ should be completely excluded from postprocessing, including all  (nested) subfolders and files within.
Logs (censored/simplified for privacy reasons):
2020-10-05 12:51:47 INFO :: POSTPROCESSOR-AUTO :: Processing /downloads
2020-10-05 12:52:11 INFO :: POSTPROCESSOR-AUTO :: Processing /downloads/\_**UNPACK**\_censored/**subfolder**/censored.mkv (None)
2020-10-05 12:52:11 INFO :: POSTPROCESSOR-AUTO :: This download is marked a priority download so I'm going to replace an existing file if I find one
2020-10-05 13:02:45 INFO :: POSTPROCESSOR-AUTO :: Processing succeeded for /downloads/\_**UNPACK**\_censored/**subfolder**/censored.mkv
2020-10-05 13:02:45 INFO :: POSTPROCESSOR-AUTO :: Deleting folder: /downloads/\_**UNPACK**\_censored/**subfolder**

**Comment by Nyaran** [comment]
I recommend to you to avoid writing files on your "downloads" folders before the files is downloaded/unpacked. Check you sabnzbd options to save temp files in a different location and move it just when the files is really finished, unpacked and everything.

That's how I have configured my torrent client, and never have any problems.

I don't know about sabnzbd clients, but many torrent clients has an option to configure separated folders and also to run a script when the download is finished, so you can create a script to move it.

**Comment by Tensai75** [comment]
I don’t do torrents. Both, SABnzbd and NZBGet use this approach to add “_unpack” to the folder name where the files are currently extracted into. This is a unofficial standard which should signal the programs watching the folder not to process it.
Sickchill to my knowledge does adhere to this standard and files directly within a “_unpack” folder are not processed. But files located within a sub folder of the “_unpack” folder are process nevertheless, which IMHO is a bug.
