### ISSUE TITLE
Sickchill wont launch on readynas 102

### ISSUE THREAD

**Issue by kofu** [SickChill/SickChill#6829]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master (09/28)
OS: Readynas 6.10.3
Browser:
What you did: I clicked the update button
What happened: It did not restart
What you expected: To restart 

I restarted my nas nothing better.
I edited my fvapp service and noticed sickBeard.py changed to sickChill.py
Nothing better.
I tried to execute in shell this command :
python /apps/sickchill/SickChill.py --nolaunch --datadir=/apps/sickchill/app-config --config=/apps/sickchill/app-config/config.ini --port=6766

Here is what i got :
```
Traceback (most recent call last):
  File "/apps/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/apps/sickchill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/apps/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/apps/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/apps/sickchill/sickchill/logger.py", line 72
    msg = re.sub(fr'\b({item})\b', '*' * 8, msg)
                                ^
SyntaxError: invalid syntax

```

**Comment by kofu** [comment]
Can't edit and forgot to say "Hi" and "Thanks". Shame on me !

**Comment by miigotu** [comment]
requires python 3.6+

**Comment by miigotu** [comment]
`python3 /apps/sickchill/SickChill.py --nolaunch --datadir=/apps/sickchill/app-config --config=/apps/sickchill/app-config/config.ini --port=6766`

**Comment by kofu** [comment]
Readynas can't supply python version better than 3.4 even after apt-update...
I'll try to compile a 3.6 version on m'y own and let you know.

**Comment by fyrefive** [comment]
keep us posted kofu, sickchill isn't working on my readynas 204 either

**Comment by thul** [comment]
Same on Synology, i can't update past Python 3.5.1

**Comment by kofu** [comment]
I did not manage to get a correct compiled pyhon 3.6+ version on RN102, its ARM is so slow it takes hours to compile and finally get errors. I'm planning to update an old Raspeberry's raspbian and install SickChill on this piece of cheap hardware. :(

**Comment by kofu** [comment]
What we actually need is a better support of Python on our respective NAS's. It's not a SickChill issue.
To try (and fail) compiling my own P3.6,  I followed this guide : https://forums.sickrage.ca/t/how-to-install-on-readynas-and-python-3-6-9/275
I know it's SickChill's genesis' forum but can't get strong enough details from better sources such as Reddit or StackOverFlow :/

**Comment by kofu** [comment]
Hi, just to keep you in touch guys
Python 3.6.9 failed to compile because of NetGear Repo lack of support. 
It returns a 403 forbidden error while trying to fetch sqlite3 package. 

As Readynas gives me the option to factory reset with a single button, i'm taking some risks and did :
- edit /etc/apt/sources.list
- comment the readynas repo
- add a genuine Jessy mirror from a random country (deb http://ftp.au.debian.org/debian/ jessie main contrib non-free)
- apt-get update
- apt-get install sqlite3
So far so good, sqlite3 IS installed on my system.
Compiling Python 3.6.9 right now .. Fingers crossed ;)

**Comment by kofu** [comment]
SickChill is up and running. This was a real pain in the *** :/
All our issues guys are due to their lack of support and our lack of knowledge ;)

Here is a good summary of what we need to do if we want to keep our hardware up-to-date :
1. Learn how linux works. Get familiar to apt (aptitude), how to grab uptodate packages and where you get them from. Get familiar with sources wget, configure, make and make install (and be curious, check at least onscreen logs)
2. If your jailed repo is outdated, switch to an official repo (you need to discover which distro is running, and which version - in my case it is a Dabian Jessy but each case is unique ...) 
3. apt-get update / apt-upgrade / prey your best god not to break too many things
4. Install needed dependencies and compile missing ones
5. Enjoy your new superpowers :)

**Comment by kofu** [comment]
BTW, you need openssl 1.1.1 to be installed or you'll have issues with scrapers using CloufFlare. 

If your repo does not provide 1.1.1 (such as Jessie one), You should try this guide : https://askubuntu.com/questions/1126893/how-to-install-openssl-1-1-1-and-libssl-package
It will teach you how to download sources, compile, test ... 
And gives precious command lines teaching us how to find an earlier version of a package and how to deal with it when we download a out-of-repo one.

**Comment by theskillwithin** [comment]
maybe soething wrong with locale for me

```
➜  openssl-1.1.1g python3 /apps/sickchill/SickChill.py --nolaunch --datadir=/apps/sickchill/app-config --config=/apps/sickchill/app-config/config.ini --port=6766
/apps/sickchill/sickchill/locale
/apps/sickchill/sickchill/locale
Traceback (most recent call last):
  File "/apps/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/apps/sickchill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/apps/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/apps/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/apps/sickchill/sickchill/tv.py", line 20, in <module>
    import sickchill.oldbeard.providers
  File "/apps/sickchill/sickchill/oldbeard/providers/__init__.py", line 4, in <module>
    import sickchill.oldbeard.helpers
  File "/apps/sickchill/sickchill/oldbeard/helpers.py", line 12, in <module>
    import ssl
  File "/usr/local/lib/python3.9/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
```

**Comment by theskillwithin** [comment]
```
➜  Documents python3 /apps/sickchill/SickChill.py --nolaunch --datadir=/apps/sickchill/app-config --config=/apps/sickchill/app-config/config.ini --port=6766
Traceback (most recent call last):
  File "/apps/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/apps/sickchill/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/apps/sickchill/sickchill/show/indexers/__init__.py", line 22, in <module>
    from .handler import ShowIndexer
  File "/apps/sickchill/sickchill/show/indexers/handler.py", line 25, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by theskillwithin** [comment]
when doing`make test` on python 3.9 on readynas I get

```
======================================================================
FAIL: test_from_hex (test.test_float.HexFloatTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Python-3.9.0/Lib/test/test_float.py", line 1355, in test_from_hex
    self.identical(fromHex('0x0.ffffffffffffd6p-1022'), MIN-3*TINY)
  File "/root/Python-3.9.0/Lib/test/test_float.py", line 1066, in identical
    self.fail('%r not identical to %r' % (x, y))
AssertionError: 2.2250738585072e-308 not identical to 2.2250738585071984e-308

----------------------------------------------------------------------

Ran 48 tests in 0.898s

FAILED (failures=1, skipped=5)
test test_float failed
4 tests failed again:
    test_cmath test_float test_shutil test_socket

== Tests result: FAILURE then FAILURE ==

406 tests OK.

4 tests failed:
    test_cmath test_float test_shutil test_socket

1 test altered the execution environment:
    test_site

14 tests skipped:
    test_devpoll test_gdb test_ioctl test_kqueue test_msilib
    test_ossaudiodev test_startfile test_tix test_tk test_ttk_guionly
    test_winconsoleio test_winreg test_winsound test_zipfile64

4 re-run tests:
    test_cmath test_float test_shutil test_socket

Total duration: 26 min 19 sec
Tests result: FAILURE then FAILURE
Makefile:1198: recipe f
```
