### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Total Variety Network. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by mesa57** [SickChill/SickChill#6831]
### INFO
Python Version: **3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]**
Operating System: **Linux-4.9.103-odroidxu4-armv7l-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@99336df163c7e776c7931d864e84d1f0f83afe4d
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Total Variety Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Nyaran** [comment]
"Total Variety Network" is [tvN](https://www.thetvdb.com/networks/tvn-kr) on theTVDB, so your show data could be outdated or  has wrong information on the indexer. Check the show information on theTVDB and if there the information is ok, try a full update on the show.
