### ISSUE TITLE
[APP SUBMITTED]: [BSPlayer] ERROR: Too many tries (5)...

### ISSUE THREAD

**Issue by Zetsuo** [SickChill/SickChill#6843]
### INFO
Python Version: **3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]**
Operating System: **Linux-5.4.51-v7+-armv7l-with-debian-10.4**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7b98df06ad3357a377d64bf31e11db8d4e372f8f
No Log available with ERRORS:
### ERROR
```
[BSPlayer] ERROR: Too many tries (5)...
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by tvdias** [comment]
### INFO
Python Version: **3.8.8 (default, Feb 19 2021, 18:17:05) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.8.0-50-generic-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
Link to Log: https://gist.github.com/cb7016b475411560f5fa1f8af51098b1
### ERROR
```
[BSPlayer] ERROR: Too many tries (5)...
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by tvdias** [comment]
### INFO
Python Version: **3.8.8 (default, Feb 19 2021, 18:17:05) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.8.0-50-generic-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
No Log available with ERRORS:
### ERROR
```
[BSPlayer] ERROR: Too many tries (5)...
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itzbolsi** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2023.6.27**
No Log available with ERRORS:
### ERROR
```
[BSPlayer] ERROR: Too many tries (5)...
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
