### ISSUE TITLE
Runtime Error (at 126:640) using 0.5.9 Windows installer

### ISSUE THREAD

**Issue by onewinter** [SickChill/SickChill#6846]
OS: Server Core 2019

Trying to upgrade from the pre-Python3 branch.  Followed the instructions from other users here in the issue that was opened pertaining to that (#6681)

Backed up Sickchill folder
Uninstalled using uninstaller in Sickchill folder, said yes to keeping data
Rebooted
New installer downloads portable git and python3, then upon starting the install (Verifying dependency files for portablegit...) i get the following popup:

`Runtime Error (at 126:640)`
` `
`: `

I did have a version of Python 2.7 installed that I didn't need anymore, so I uninstalled that and rebooted to try again, but same result.

**Comment by miigotu** [comment]
Need Visual C++ Redistributable

**Comment by onewinter** [comment]
thanks, i actually was able to eventually figure that out with a ton of googling and installed it -- still the same error, though.  In the end I just ended up installing git portable, python 3 and pulling a copy of sickchill with git manually.  (took awhile, been a year or so since i've used git).  all up and running now, thanks
