### ISSUE TITLE
Mako Error : 'charmap' codec can't decode .....

### ISSUE THREAD

**Issue by Heidmall** [SickChill/SickChill#6847]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Wiundows 10
Browser: Chrome 86
What you did: View Log
What happened: Message FixMe a mako error has occured
What you expected: view my log
Logs:
```
Traceback (most recent call last):
File M:\SickChill\SickChill\sickchill\views\index.py:185, in async_call:
return function(**kwargs)
File M:\SickChill\SickChill\sickchill\views\logs.py:75, in viewlog:
data = sickchill.logger.log_data(min_level, log_filter, log_search, max_lines)
File M:\SickChill\SickChill\sickchill\logger.py:425, in log_data:
data += [line.strip() + '\n' for line in reversed(f.readlines()) if line.strip()]
File encodings\cp1252.py:23, in decode:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 7262: character maps to
```

Fresh install with just a config.ini (0 show ; just a preview config from last version on python 2.7)

**Comment by miigotu** [comment]
Stop SC and delete the c:\sickchill\data\logs folder.
