### ISSUE TITLE
bug: 'downloaded' text is unstyled

### ISSUE THREAD

**Issue by OneCDOnly** [SickChill/SickChill#6848]
Hey guys. :) 

Using SickChill cloned from GitHub source (`develop` branch) on Debian 10.5 with Python 3.7.3

Just noticed that episode 3 doesn't show `Downloaded` in the same style as episode 2:

![screenshot](https://i.imgur.com/RyLtvr9.png)

Is this because it was received in-advance of the airdate?

Thank you.

**Comment by OneCDOnly** [comment]
Update: after the airdate came-and-went, the styling for `Downloaded` didn't change. 😞

**Comment by miigotu** [comment]
Yeah it's a javascript error, purely cosmetic.

**Comment by OneCDOnly** [comment]
Okiedoke, thanks @miigotu 👍🏽
