### ISSUE TITLE
Bug: Scene Exception doesnt work, SC doesnt search for this.

### ISSUE THREAD

**Issue by gielie** [SickChill/SickChill#6849]
Branch/Commit: Master Version: v2020.09.28-2

When i put an extra name at the Scene Exception SC wont search for this alternative name.
Example The Haunting, season 2 has a different name "The Haunting of Bly Manor" and when i put the different name in the scene exception at the show or/and Season 2 SC wont search for this and wont find anything for this show.

**Comment by kyuuk** [comment]
i had a similar issue, and i had to delete cache.db file and restart sickchill

you can try this while waiting for a fix :)

**Comment by miigotu** [comment]
Enable backlog searching. That's the only time strings are used for search. Also, check your debug log.

**Comment by lobofoots** [comment]
I have kind of the same problem:

I tried:
Checking or unchecking 'restrict backlog searches to missing episodes only?'
Forcing a backlog search
Deleting Cache.DB, restarting Sickchill.
Unfortunately it doesn't solve it.
I added as a scene exception show name 2020, show name is already known by sickchill.
Set preferred and allowed quality as 4K UHD WEB-DL

Log say 
2020-11-23 22:31:58 DEBUG :: SEARCHQUEUE-BACKLOG-360295 :: [Rarbg] :: Ignoring Show.Name.2020.S02E03.Title.2160p.WEBRip.x265.10bit.HDR.HLG.DDP5.1-BL[rartv]
2020-11-23 22:31:58 DEBUG :: SEARCHQUEUE-BACKLOG-360295 :: [Rarbg] :: Don't want this quality, ignoring found result for Show Name S02E03 with quality N/A
2020-11-23 22:31:58 DEBUG :: SEARCHQUEUE-BACKLOG-360295 :: [Rarbg] :: Using cached parse result for: Show.Name.2020.S02E03.Title.2160p.WEBRip.x265.10bit.HDR.HLG.DDP5.1-BL[rartv]

**Comment by gielie** [comment]
I’d like to give this bug a bump up cause the scene exception still doesn’t work. Right now I can’t even fill in a scene exception(field stays empty). No error is given and nothing in the debug log.

**Comment by miigotu** [comment]
> I have kind of the same problem:
> 
> I tried:
> Checking or unchecking 'restrict backlog searches to missing episodes only?'
> Forcing a backlog search
> Deleting Cache.DB, restarting Sickchill.
> Unfortunately it doesn't solve it.
> I added as a scene exception show name 2020, show name is already known by sickchill.
> Set preferred and allowed quality as 4K UHD WEB-DL
> 
> Log say 
> 2020-11-23 22:31:58 DEBUG :: SEARCHQUEUE-BACKLOG-360295 :: [Rarbg] :: Ignoring Show.Name.2020.S02E03.Title.2160p.WEBRip.x265.10bit.HDR.HLG.DDP5.1-BL[rartv]
> 2020-11-23 22:31:58 DEBUG :: SEARCHQUEUE-BACKLOG-360295 :: [Rarbg] :: Don't want this quality, ignoring found result for Show Name S02E03 with quality N/A
> 2020-11-23 22:31:58 DEBUG :: SEARCHQUEUE-BACKLOG-360295 :: [Rarbg] :: Using cached parse result for: Show.Name.2020.S02E03.Title.2160p.WEBRip.x265.10bit.HDR.HLG.DDP5.1-BL[rartv]
> 
> 

This one you just need to enable HEVC support for x265/10bit. I think it is in search settings.

**Comment by miigotu** [comment]
In config/search
![Screenshot_20210607-190015.png](https://user-images.githubusercontent.com/390379/121097875-bc336600-c7c2-11eb-934c-2efb787e82c1.png)
