### ISSUE TITLE
Unaired episodes showing up as Downloaded (Unknown), overriding Wanted status

### ISSUE THREAD

**Issue by ronilaukkarinen** [SickChill/SickChill#6850]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/7b98df06a
OS: Fedora release 32 (Thirty Two) 
Browser: Google Chrome Version 86.0.4240.80 (Official Build) (x86_64)
What you did: Browsed to series /home/displayShow?show=355567
What happened: Seeing status Downloaded Unknown for every episode
What you expected: Seeing them wanted
Logs:
```
For privacy reasons I prefer not to.
```

Screenshot:
![Screenshot](https://i.imgur.com/SBxbpQV.png "Screenshot")

If I set up every single episode as "Wanted" manually, they are always "Downloaded (Unknown)" next time I go to check why I haven't got any dls... I have a pretty clean install.

**Comment by nhorvath** [comment]
If you mouse over the episode number does it show a filename? This usually happens when there are mismatches in episode numbering schemes.

**Comment by ronilaukkarinen** [comment]
Oh, didn't know that mouseover thingy. Yeah, it shows episodes from completely different series. It's not even remotely close to this series. The mouseover for next unaired episode is "Life (2007)/Life (2007) S02E09 Badge Bunny.m4v". I have one folder /mount/series that contains all the series and their episodes, could this be a reason? Do I have to readd the show or is it enough if I just edit the show details to its own subdirectory?

**Comment by nhorvath** [comment]
I'm not sure I fully understand your setup. Each show should be in it's own folder. After you clean it up you should be able to do a rescan from the buttons at the top of the show details.

**Comment by miigotu** [comment]
Each show has to have it's own show folder.

**Comment by ronilaukkarinen** [comment]
Yeah putting every show to their own folders seem to fix this. This also fixes the mystical seasons that don't exist for some shows. I don't know why/how it has happened that everyone were in the same directory. Thanks!
