### ISSUE TITLE
PUID / PGID ignored in docker-compose

### ISSUE THREAD

**Issue by lokipo** [SickChill/SickChill#6854]
Branch/Commit: latest
OS: linux-docker

When starting the latest docker-image using docker-compose and setting PUID=1000 / PGID=1000 sickchill is still ran as root, which makes all media that sickchill handles being owned by root.

**Comment by miigotu** [comment]
https://stackoverflow.com/a/56844765/1338570

**Comment by lokipo** [comment]
Hi,

this does not fix the initial problem of variables set properly according to documentation being ignored but adding:

User: "1000:1000" is of course a viable workaround.

**Comment by jonkristian** [comment]
Why is this closed? Defined env variables PUID/PGID is not working ...

**Comment by miigotu** [comment]
Because this is not linuxserver, use the user: keyword from docker-compose.
`user: yourusername` or `user: youruser:yourgroup`

**Comment by lokipo** [comment]
If you do not plan on fixing this, instead of just closing the issue you should maybe at least update the wiki to reflect this behaviour.

**Comment by jonkristian** [comment]
@miigotu Thanks for your reply. Obviously I was looking at the wiki for directions on how to set things up. I think I asked an honest question but I admit that I should have mentioned the wiki. Anyways, keep up the awesome work! Really loving this project <3
