### ISSUE TITLE
Cloudflare IUAM error (NOT running in blackhole)

### ISSUE THREAD

**Issue by Redostrike** [SickChill/SickChill#6856]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Docker (synology)
Browser: Chrome
What you did: Manual Search
What happened: Error Cloudflare
What you expected: No errors?
Logs:
```
2020-10-22 13:10:16 INFO :: SEARCHQUEUE-MANUAL-372787 :: [TorrentDay] :: Request failed: Cloudflare IUAM possibility malformed, issue extracing delay value. ()
2020-10-22 13:10:16 INFO :: SEARCHQUEUE-MANUAL-372787 :: [TorrentDay] :: Performing episode search for The Walking Dead: World Beyond
```

I'm not running in Blackhole, SC is connected and working (test connection) with transmission?

**Comment by Redostrike** [comment]
Well seems to only been the case for torrentday everything is working fine on eztv can't try on different private tracker though as i don't have any else. Is there something already in the works for this, or not possible or?

**Comment by jrmoede** [comment]
Have same issues it would appear:

Branch/Commit:Master
OS: TrueNAS/FreeBSD
Browser: Chrome
What you did: Manual Search

`2020-10-28 23:25:34 INFO :: SEARCHQUEUE-MANUAL-110381 :: [IPTorrents] :: Request failed: Cloudflare IUAM possibility malformed, issue extracing delay value. ()`

**Comment by papaxris** [comment]
I can confirm this issue exists with SPEED.

Error:
Request failed: Cloudflare IUAM possibility malformed, issue extracing delay value. ()

Also, the user and pass cookie info has been applied to the Provider Options
