### ISSUE TITLE
Make fatal errors more obvious in the UI

### ISSUE THREAD

**Issue by glenviewjeff** [SickChill/SickChill#6870]
Ends up the below problem is a side effect from the shows directory no longer granting write permission to the Sickchill service. It would be nice if there were pop-up errors for serious ones like this, or if the service would start in a state that made it very obvious something was wrong. I believe the only place that showed the error in any obvious sense was when I went to a specific show's details and noticed that the location was in red.

When I look at the poster view, I see the same order as the other views when sorting by next episode. The only four shows with a "next episode" listed are Last Week Tonight, Nova, SNL, and Doctor Who. Everything else shows "continuing," even shows which have ended, such as Beavis and Butt-Head. Many shows which have upcoming episodes even within the next week (both in reality and within the show page detail) are randomly sorted among those.

Looking at the details on the simple layout reveals the episode data is totally screwed up, and there must not be error checking within the code about this. For instance SNL shows a previous episode of 11/7/20, with a next episode of 10/31/20. Then as another example, Star Trek Discovery has a previous episode of 1/7/21, but no next episode in the simple list. Everything's correct on the individual show pages. 

The shows whose next episodes are missing in the show list are also not showing up in the schedule, and the schedule appears to be consistent with what's shown for the "next episode" shows.

**Comment by glenviewjeff** [comment]
It ends up is a side effect from the shows directory no longer granting write permission to the Sickchill service. It would be nice if there were pop-up errors for serious ones like this, or if the service would start in a state that made it very obvious something was wrong.

**Comment by glenviewjeff** [comment]
Why was this closed? Won't fix?

**Comment by miigotu** [comment]
You want me to make 1000 popups when there is user error? SC doesn't screw up the permissions.

**Comment by glenviewjeff** [comment]
I don't believe I suggested that. My advice would be that if Sickchill
detects a fatal error, such as inability to write to the shows folder, that
Sick Chill either not start and return an error, or issue a pop-up or
front-page message that something has gone very wrong and that the user
should check the logs.

**Comment by miigotu** [comment]
And what if you have 1000 shows, that would require 1000 warnings. Just don't mess with the permissions and check the logs.
