### ISSUE TITLE
Raspberry pi - SickChill - Not enough Disk Space

### ISSUE THREAD

**Issue by c1149** [SickChill/SickChill#6872]
Hi,

I have SickChill installed on my raspberry pi.
But now it isn't starting anymore and I get the message.
"Looks like we don't have enough disk space to render the page".

SickChill is taking up 28 gig? Is this normal? Or I have I a wrong set up?
I have an external hard disk connected to the raspberry pi.
This is were the files are downloaded to.

**Comment by nhorvath** [comment]
You would need to provide more information on what in sickchill is taking up 28 GB.

**Comment by miigotu** [comment]
Your permissions are wrong

**Comment by c1149** [comment]
> 
> 
> Your permissions are wrong

No because it has worked. But then I still had disk space. 
Now I have no space left.

**Comment by c1149** [comment]
> 
> 
> You would need to provide more information on what in sickchill is taking up 28 GB. For reference my sickchill directory is 2 GB and I have 27k episodes in the DB.

![afbeelding](https://user-images.githubusercontent.com/5947955/97217509-ae971600-17c7-11eb-83c6-649accc3028a.png)

Folder "SickChill/.git/objects" contains 20 gig. See 20 largest files in the folder (image above).
Just noticed most files are in "SickChill/.git/objects/pack".
Can I safely delete these files?

![afbeelding](https://user-images.githubusercontent.com/5947955/97217632-de461e00-17c7-11eb-81d6-7557d777748e.png)

**Comment by nhorvath** [comment]
Try git gc --aggressive --prune
