### ISSUE TITLE
Question - Manual Snatch

### ISSUE THREAD

**Issue by ulrick65** [SickChill/SickChill#6875]
I upgraded to Python 3. On Linux, used GIT then restored settings...no issues.

Now I see a new "plus sign" on the episodes that says Manual Snatch.  Shows me all the available episode listings...awesome!  But I am not sure how that is supposed to work...if I click on one, it says "snatched" like it should...but nothing happens.  According to the log it downloaded an NZB, but just puts it in my Sickchill install folder.

What am I missing with this feature?

Also, is there significance to color of "blue" around the word "Downloaded"?  Most have the blue, but some do not and I don't know why or what the difference is.

As always, thanks...great work!

**Comment by miigotu** [comment]
Seems like you don't have your nzb client connected. 

The blue/not-blue is just a javascript bug, ignore it for now.

**Comment by ulrick65** [comment]
I use Nzbget and everything else seems to be working fine.  It grabs episodes as normal, downloads and post processes fine, etc.
