### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: DreamWorks Animation. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by hubdows** [SickChill/SickChill#6877]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@fd546a06e190fa2de993e9197891de2a79f31f70
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: DreamWorks Animation. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hubdows** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@46a7f2a2304d6abbc6459820f88d830c57e89bcb
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: DreamWorks Animation. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by zobe123** [comment]
### INFO
Python Version: **3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]**
Operating System: **Linux-4.15.0-122-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@46a7f2a2304d6abbc6459820f88d830c57e89bcb
Link to Log: https://gist.github.com/b9e01ad722cbe6adf50032b52b2cb4c2
### ERROR
```
Missing time zone for network: DreamWorks Animation. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
