### ISSUE TITLE
Upgraded to 44.2 and now missing option to generate .tbn files

### ISSUE THREAD

**Issue by MartinHaimberger** [SickChill/SickChill#6878]
Hi, just upgraded to master (44.2) and now im missing the option to let .tbn (thumbnail files) be generated (I think this was in the Metadata PS3 generateor, but its not there anymore). Any help here ? ... also in the github.io page the TBN generation is mentioned. Is this support dropped ? 

Greetings, 
Martin

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by MartinHaimberger** [comment]
I lookup up the old config, and i was using KODI meta data type, but here seems to be the change, now the thumbnails are named 
Season##\filename-bumb.jpg. Before it was Season##\filename.tbn.

**Comment by miigotu** [comment]
What ancient hardware are you using tbn files for? They only were used for the original xbmc on the actual original box, they are not used for any other device.

**Comment by MartinHaimberger** [comment]
@miigotu Hi, u are right, its old. My Library was started then. Now im using Plex with the XBMCPlugin to scan my media. So Plex with the XBMCPlugin still uses this format.

**Comment by miigotu** [comment]
First, nothing that is up to date is still called xbmc.
There are kodi plugins for plex, but the plex scanner actually works best. Downloading images in the show for and then also having them cached for plex is a waste if space.

If you REALLY need them, the regular Kodi poster/banner jpg files will be picked up just fine. I won't be adding back tbn files that have been deprecated for nearly a decade and completely obsolete for over 5 years.

**Comment by MartinHaimberger** [comment]
@miigotu just for your information ... it is still out there and is being used

https://github.com/gboudreau/XBMCnfoMoviesImporter.bundle
https://github.com/gboudreau/XBMCnfoTVImporter.bundle

and caching the info and pictures one time has the advantage that imdb or the tvdb is only queried once. Also if the library has to been rebuild, there is no need for loading it all again. Its a waste of space, but think how big the info and the images are, in contrast to the video files.

**Comment by miigotu** [comment]
Both of those bundles will work just fine with jpg/png.
