### ISSUE TITLE
Filter in "manual snatch"

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#6879]
First of all - I love the manual snatch function! However, I would like to request (if possible) that is added a filtering option. Nothing fancy, but a regex filter of some kind. For me, writing something like "proper 265" to filter out anything except releases including these two words.

This is, of course, extremely urgent since I just noticed it would be a nice addition. (In case it's too early for irony - this was irony. I'd love to see it, but I completely understand if it's in the bottom of the pile.)

**Comment by Nyaran** [comment]
It was easy, so I did it. Just wait until @miigotu review it
