### ISSUE TITLE
Indexer request timeout when adding new show 

### ISSUE THREAD

**Issue by renatofsp** [SickChill/SickChill#6885]
Indexer request timeout when adding new show only two lines of code on the logs even in debug between the click on "add show" button and the timeout message see message on image bellow
![2020-11-03_15h27_38](https://user-images.githubusercontent.com/1664414/98005706-4361cb00-1de9-11eb-8ab4-4dbccf73126c.png)

Branch: master
Commit: fd546a06e190fa2de993e9197891de2a79f31f70
Version: v2020.10.22-2
Database Version: 44.2
Python Version:3.8.3 (default, Sep 13 2020, 17:47:24) [GCC 4.9.2]
SSL Version:OpenSSL 1.1.1g 21 Apr 2020
OS:Linux-4.9.35-v7+-armv7l-with-glibc2.17
Locale:en_GB.UTF-8
Browser: google chrome Version 86.0.4240.111
What you did: try to add a new show
What happened: indexer timeout request
What you expected: show information should have been found
Logs:
```
2020-11-03 15:05:45 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with searchterm(s): ['the undoing', 'undoing'] on Indexer: theTVDB
2020-11-03 15:05:01 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with searchterm(s): ['the undoing', 'undoing'] on Indexer: theTVDB
```

**Comment by renatofsp** [comment]
no one else has this issue

**Comment by kyuuk** [comment]
I don't have this issue, but maybe it's just a network problem, can tou try accessing this url https://api.thetvdb.com/api/
both from yout browser and from the system where Sickchill is intalled with a : `curl https://api.thetvdb.com/api/`

if the reponse is `{"Error":"Not authorized"}` then it is not a network problem

**Comment by renatofsp** [comment]
I get and {"Error":"Not authorized"} but i get it:

- on the browser windows machine with a vpn connection (tested different country connections)
- on the browser windows machine no vpn connection
- curl on windows machine with a vpn connection (tested different country connections)
- curl on windows windows machine no vpn connection
- curl on linux machine with a vpn connection (tested different country connections)
- curl on linux machine  no vpn connection
- thor browser
- curl and bowser outside my house so different isp 

all of those combinations gave the same {"Error":"Not authorized"} not sure how this is my network particularly the test using a diffrent isp

the linux machine is where I  have the sick running

**Comment by kyuuk** [comment]
yes it is Sickchill does all the necessary to be able to authentify to the tvdb api, this test was just to know if you can contact the tvdb api correctly, and it seems okay so must be something else 

sorry that i can't help you more

**Comment by renatofsp** [comment]
thank you nonetheless

**Comment by renatofsp** [comment]
I dig a bit more on this since I have access to the api discarding network issue I try sickchill on my windows machine and it was able to fetch series data from tvdb and I also tried the docker image of sickchill on my raspberry pi (where I have the sickchill server running with issue) and it also fetches the data my guess would be something related to openssl but I have a version from april 2020 as you can see in the first comment

Anyone has a recomended version of openssl to be used?

**Comment by renatofsp** [comment]
problem fixed looks like my little raspberry pi takes a bit longer to fetch data so I increased the timeout request to 30 seconds and it looks ok for now.

I try to change the proper variable settings.INDEXER_TIMEOUT at start.py but I'm still missing how to build up the code and update the js file namely core.js 

can someone give me a kick overview it would be nice for local issues like this I can even contribute if you need me to.
