### ISSUE TITLE
API Call to add new show not working for 'status=ignored'

### ISSUE THREAD

**Issue by himpich** [SickChill/SickChill#6892]
When I try to add a show via ombi, sickchill answeres with "Invalid Status"

Here is my Api Call from Ombi:
GET /api/REDACTED/?cmd=show.addnew&tvdbid=ALSOREDACTED&status=ignored&initial=hdtv HTTP/1.1
Result: `{"data": {}, "message": "Invalid Status", "result": "error"}`

When I change that call to "status=skipped", it works fine. Maybe the check for a valid status is broken? see
https://github.com/SickChill/SickChill/blob/fd546a06e190fa2de993e9197891de2a79f31f70/sickchill/views/api/webapi.py#L2180

**Comment by gsuave** [comment]
Same problem here this was working before... using latest stable docker containers for both apps.
