### ISSUE TITLE
RFS: Jackett RSS (backlog search)

### ISSUE THREAD

**Issue by rirofal** [SickChill/SickChill#6895]
Would really like to see a proper implementation av Jackett as a search provider.
Today you can use it as a RSS-feed but that doesn't work on backlog searches.

It's really easy to use the API, config needs a few things:
- Hostname & port (9117)
- API-Key

Then you can search via this URL:
http://somehost:9117/api/v2.0/indexers/all/results/torznab/api?apikey=secret&t=search&q=SomeSearchString

The big advantage of Jackett is that it caches everyting and you will have one single place to manage your trackers for all products you are using.

**Comment by miigotu** [comment]
This already exists. Add it as a custom newznab provider.

**Comment by rirofal** [comment]
Exists for NZB but not for torrents...

**Comment by miigotu** [comment]
> Exists for NZB but not for torrents...

Incorrect. You add jackett as a custom nzb provider. Jackett sends results as newznab data. SC WILL search backlog and download torrents from jackett.

**Comment by rirofal** [comment]
> > Exists for NZB but not for torrents...
> 
> Incorrect. You add jackett as a custom nzb provider. Jackett sends results as newznab data. SC WILL search backlog and download torrents from jackett.

Ah...  didnt know that... :)

Not really the most intuitive way to do it, but hey... if it works it works. 👍
