### ISSUE TITLE
Some popular TV shows on theTVDB not is search results

### ISSUE THREAD

**Issue by idkpmiller** [SickChill/SickChill#6897]
Hi,
I have been replacing my old python 2.7 version of SickChill and built a brand new version of python 3.x version and have not copied the db across, instead I did as recommended and took the opportunity to start again from scratch.
I am finding adding some of the existing shows that exist on my old version are not being found in the search of theTVDB on the new version. Going to the theTVdb web site they are certainly there alright.

Example shows:
The Flash
Killing Eve

There are around half a dozen in total so perhaps 10% of the show list.
Is this a bug? or am I likely mis-configured somewhere? I did check the wiki to see if there was any alternative indexers around and found nothing, there is mention in an a closed issue ticket that someone was adding new ones but that was over a year ago and have found nothing to see if it progressed.

Normally I would post such an item in a forum before coming here, but was not able to find a forum that seemed to deal with SickChill.

Many Thanks to those that offer assistance and point me the correct direction.

Thanks
Paul

**Comment by lobofoots** [comment]
Did you use something other than 'english' in the Metadata language search option?

**Comment by idkpmiller** [comment]
I have checklked the settings and I think the one you are referring to is 'Default Indexer Language' this is set to English, although the results being fed back are very suspect as if a different language or perhaps a match is trying to be met on a episode title not the show title?

For example if I add a new show 
Show Name: Flash
Metadata Language: English
Indexer: theTVDB

Results:

  | Show Name | Premiere | Indexer
-- | -- | -- | --
  | Last Stop Bay Bridge | null | theTVDB
  | last ship | null | theTVDB
  | Last Days on Earth | 2009-1-11 | theTVDB
  | Cable Girls | 2017-4-28 | theTVDB
  | Las canciones de la Granja | null | theTVDB
  | Las que faltaban | 2019-3-15 | theTVDB
  | LasseMajas Detektivbyrå | 2020-12-6 | theTVDB
  | Last Laugh | 2020-4-20 | theTVDB
  | L'Astucerie | null | theTVDB
  | Lass dich überwachen! Die Prism is a Dancer Show | 2018-11-2 | theTVDB
  | Last Rights (2005) | null | theTVDB
  | Láska v čase korony | 2020-5-4 | theTVDB
  | Lassie | 1943-10-7 | theTVDB
  | Lassie (1997) | 1997-3-2 | theTVDB
  | Last Dad Standing | 2020-8-13 | theTVDB
  | LaChaineDeJeremy | 2020-3-26 | theTVDB
  | Las 21 aventuras de Tintín | null | theTVDB
  | Las Uñas | 2018-6-19 | theTVDB
  | Last Man Standing | 2005-4-1 | theTVDB
  | Last Squad Standing | 2016-11-1 | theTVDB
  | Las Provincianas Podcast | null | theTVDB
  | Laser Fart | 2004-3-29 | theTVDB
  | Lah Ruk Sut Kob Fah | null | theTVDB
  | Lahore Law | 2002-1-1 | theTVDB
  | Last Idol ~LasAi, Yoroshiku!~ | 2017-8-13 | theTVDB
  | Lastman | 2016-11-22 | theTVDB
  | Last Madame | 2019-9-26 | theTVDB
  | Ladhood | 2019-11-24 | theTVDB
  | Last Commanders | 2018-1-29 | theTVDB
  | Las cerezas del cementerio | 1977-4-11 | theTVDB
  | Last Looks | 2020-10-12 | theTVDB
  | Las Vegas Academy | 2015-5-18 | theTVDB
  | Last Comic Standing | 1999-11-30 | theTVDB
  | Last One Standing | 2007-10-4 | theTVDB
  | Lassie's Rescue Rangers | 1972-11-11 | theTVDB
  | Lässugen | null | theTVDB
  | Last Man Standing (2007) | 2007-6-26 | theTVDB
  | Lachen Sie mit Stan & Ollie | 1975-1-21 | theTVDB
  | Last week I asked you (LWIAY) | 2017-6-22 | theTVDB
  | Las Últimas Horas De | 2018-1-9 | theTVDB
  | Last Chance Lawyer NYC | 2018-10-7 | theTVDB
  | Laish La? - ليش لا؟ | 2014-2-19 | theTVDB
  | The Two Sides of Ana | 2006-9-25 | theTVDB
  | Lachés Lousses | 2017-9-12 | theTVDB
  | Las Malcriadas | null | theTVDB
  | Las 13 esposas de Wilson Fernández (MX) | 2017-5-12 | theTVDB
  | Las Vegas | 2003-9-22 | theTVDB
  | Last Outpost | 2018-4-17 | theTVDB
  | Las Juanas | null | theTVDB
  | L'ascenceur | null | theTVDB
  | The Stars | 2017-5-29 | theTVDB
  | Lachy | null | theTVDB
  | Dumb Girls Don't Go to Heaven | 2008-2-11 | theTVDB
  | Last Fan Standing | null | theTVDB
  | Last Teenagers of the Apocalypse | 2016-3-21 | theTVDB
  | Last Kiss | 2015-10-16 | theTVDB
  | Taco Chronicles | 2019-7-12 | theTVDB
  | Lah | 2017-11-28 | theTVDB
  | Freefall | 2017-1-9 | theTVDB
  | Las mujeres que habitan en mí | null | theTVDB
  | Las Vegas Revealed | null | theTVDB
  | Last Call Honduras | 2019-4-8 | theTVDB
  | The news of guignol | 1995-9-5 | theTVDB
  | Last Marble Standing | 2020-6-1 | theTVDB
  | Last Chance to See | 2009-9-6 | theTVDB
  | Last Stop Garage | 2017-10-23 | theTVDB
  | Last Laugh in Vegas | 2018-4-3 | theTVDB
  | Last Days in Vietnam | 2015-4-20 | theTVDB
  | L.A.'s Finest | 2019-5-13 | theTVDB
  | Lasting Love Made Easy | null | theTVDB
  | Lush Life | 1996-9-9 | theTVDB
  | L'ascenseur | 2016-11-7 | theTVDB
  | Last Friends | 2008-4-10 | theTVDB
  | Last of the Summer Wine | 1973-1-4 | theTVDB
  | Last Chance High | 2017-8-8 | theTVDB
  | Las Buchonas | null | theTVDB
  | Last Minute Trips | 2017-2-24 | theTVDB
  | Las fuerzas del planeta | null | theTVDB
  | Las travesuras de los Picapiedra | null | theTVDB
  | Last Days | 2018-9-4 | theTVDB
  | Las Nuevas Aventuras De Federrico | null | theTVDB
  | Las Vegas Garden of Love | 2005-3-21 | theTVDB
  | Last Christmas | 2004-10-11 | theTVDB
  | Nowadays's girls | null | theTVDB
  | Last Train to Russia | 2018-3-22 | theTVDB
  | Lasse Åberg - En ängslig gosses memoarer | 2020-5-5 | theTVDB
  | Läskilinssi | null | theTVDB
  | Last Exile | 2003-4-7 | theTVDB
  | Last Call | null | theTVDB
  | Last Call with Carson Daly | 2002-1-10 | theTVDB
  | Last Alaskan Bob | null | theTVDB
  | Las Aventuras del Hada Rebeca | 1-1-1 | theTVDB
  | Last Ride: Post-Mortem | 2020-5-11 | theTVDB
  | Lashkara | 2018-4-3 | theTVDB
  | Lastman Kai | null | theTVDB
  | Last Period: the journey to the end of the despair | 2018-4-12 | theTVDB
  | Lasermannen | 2005-11-23 | theTVDB
  | Las Canciones del Zoo | null | theTVDB
  | Last Night's Late Night | null | theTVDB
  | Las Historias de Jesús | null | theTVDB


The returned results are mainly NOT english, long and not even close to being relevant to 'Flash'

Thanks
Paul

**Comment by idkpmiller** [comment]
I may have found the issue.
It seems capitalisation has an issue.

The Flash or Flash provides rubbish results, The glash gives the correct show result.
The second example Killing Eve gives rubbish results, but killing eve gives only one correct result.

This could be bug not me after all.

Thanks
Paul

**Comment by miigotu** [comment]
tvdb is going to be removed over the next few months anyway in favor or (probably) tvmaze

**Comment by swannie-eire** [comment]
@miigotu   is there an eta of when tvmaze will be added as an indexer?
