### ISSUE TITLE
[IPTORRENTS] Unable to find a download for 

### ISSUE THREAD

**Issue by piotr-siedlak** [SickChill/SickChill#6899]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Synology
Browser: Safari / Chrome /Firefox
What you did: Reinstall, restart
What happened: Unable to find a download [Iptorrents provider]
What you expected:
Logs:
AA AttributeError: 'NoneType' object has no attribute 'get' AA action = html.find('form', {'action': re.compile(r'.*login.*')}).get('action') AA File "/volume4/@appstore/sickchill/share/SickChill/sickchill/oldbeard/providers/iptorrents.py", line 66, in login AA if not self.login(): AA File "/volume4/@appstore/sickchill/share/SickChill/sickchill/oldbeard/providers/iptorrents.py", line 95, in search AA return {'entries': self.provider.search(self.search_params)} if self.search_params else None AA File "/volume4/@appstore/sickchill/share/SickChill/sickchill/oldbeard/tvcache.py", line 55, in _get_rss_data AA data = self._get_rss_data() AA File "/volume4/@appstore/sickchill/share/SickChill/sickchill/oldbeard/tvcache.py", line 66, in update_cache
2020-11-15 10:39:40 INFO :: SEARCHQUEUE-MANUAL-361753 :: Unable to find a download for: [The Mandalorian - S02E02 - Chapter 10 The Passenger] 2020-11-15 10:39:39 INFO :: SEARCHQUEUE-MANUAL-361753 :: [IPTorrents] :: Performing episode search for The Mandalorian 2020-11-15 10:39:38 INFO :: SEARCHQUEUE-MANUAL-361753 :: Beginning manual search for: [The Mandalorian - S02E02 - Chapter 10 The Passenger]

**Comment by piotr-siedlak** [comment]
Why you close this case?

**Comment by miigotu** [comment]
check the commit log 
![image](https://user-images.githubusercontent.com/390379/99264392-654a4d00-27ee-11eb-94fe-a656225d0e65.png)

**Comment by netvyper** [comment]
Something to do with Telegram has an effect on this issue? I must be missing something here, help me out please?

**Comment by miigotu** [comment]
It has been fixed for 10 days in develop. 229696a2bc573ce394efc601430e0ab922b1022b

**Comment by netvyper** [comment]
aha, gotcha.
Thanks @miigotu
