### ISSUE TITLE
Service Status Show Queue Alignment Error

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#6901]
I have noticed that when I go to server status and look at the queue there is often an alignment problem for the first entry.
There is no error in the logs that I can submit as such but I've noticed it a few times.

![image](https://user-images.githubusercontent.com/25068977/99187522-041f6c80-274f-11eb-9bcc-78467eb61b99.png)

Branch/Commit: v2020.10.22-2
OS: Synology / Windows 10
Browser: Firefox, Chrome,

**Comment by Tensai75** [comment]
I can confirm this issue.
It always happens when adding a new tv show while the Show Queue already has some tasks in in it. The add show task is then missaligned.
When adding the a new show wihle the Queue is empty, the add show task is shown correctly.
