### ISSUE TITLE
Episode airTime is not converted to local timezone in Docker Container

### ISSUE THREAD

**Issue by kyuuk** [SickChill/SickChill#6905]
Branch/Commit: Master/fd546a06e190fa2de993e9197891de2a79f31f70
OS: Docker on Debian 10 x64
Browser: Firefox
What you did: /
What happened: Episode AirTime not parsed to local timeZone
What you expected: AirTime to be of local timeZone

It seems that in the docker image the airTime is not converted to local 

- In the config Timezone is set to "local" 

- the Env var "TZ" is set to a correct TimeZone 

- sickchill shows the correct date & time in gui

I tried adding a field in the config.mako view to check what is the timeZone python is using with "time.tzname" & it seems correct
![image](https://user-images.githubusercontent.com/16566073/99587221-1288b500-29e9-11eb-8eea-b14195a04da6.png)

**Comment by miigotu** [comment]
You need to mount a volume: `/etc/localtime:/etc/localtime:ro`

**Comment by kyuuk** [comment]
@miigotu actually it is already mounted 
`"Mounts": [
            {
                "Type": "bind",
                "Source": "/home/user/downloads",
                "Destination": "/downloads",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/syno",
                "Destination": "/tv",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "sickchill_config",
                "Source": "/var/lib/docker/volumes/sickchill_config/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],`

**Comment by miigotu** [comment]
On syno im not sure if you need that, or if /etc/localtime is set.
On the syno you can try
`sudo timedatectl set-timezone your_time_zone`

**Comment by kyuuk** [comment]
Thanks @miigotu 
Sorry for the misslead. syno is just a folder mounted on a debian machine, i'm not running Sickchill into the NAS

I have done some testing, and the problem seems to be either the `dateutil.tz` or the OS or when they're together !

tried using `dateutil.zoneinfo.gettz` instead of `dateutil.tz.gettz` for the network timezone in `network_timezones.py` & it worked fine. 

The thing is that `dateutil.zoneinfo.gettz` is deprecated so its not a solution :/
