### ISSUE TITLE
Links to Trakt, IMDB, TVDB not working in mobile browser

### ISSUE THREAD

**Issue by bluezed** [SickChill/SickChill#6907]
Branch/Commit: pip /  v2020.11.16-1 38d52b6
OS: Ubuntu 20.04
Browser: Firefox for Android 82.1.3

What you did: 
Go to any show details page and press on any of the symbols for TVDB, IMDB, Trakt or whatever is present for this show.

What happened: 
Instead of opening the expected website it instead shows the show poster in full screen.

What you expected:
The respective website should be opened.

Note: On a PC browser this does not happen. The websites open fine there.

Here's a short video of the issue:
http://s000.tinyupload.com/index.php?file_id=46476646285577255164

**Comment by miigotu** [comment]
Fixed in develop branch
