### ISSUE TITLE
Error Log filled with  "[Errno 22] Invalid argument:"

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6908]
Every day I have hundreds of these in the log..
![image](https://user-images.githubusercontent.com/14140816/99877885-4fae9c00-2bcf-11eb-9052-1d8f9daee5af.png)

`2020-11-21 07:40:46 Unable to write image to M:\series\Mysteries at the Museum (2010)\Season 23\Mysteries at the Museum (2010) (S23E13) (2019-04-17) (1080p-h264 AAC-2ch) The Witch is Back, Edison's Little Monsters and I Love Toothy-thumb.jpg - are you sure the show folder is writable? [Errno 22] Invalid argument: "M:\\series\\Mysteries at the Museum (2010)\\Season 23\\Mysteries at the Museum (2010) (S23E13) (2019-04-17) (1080p-h264 AAC-2ch) The Witch is Back, Edison's Little Monsters and I Love Toothy-thumb.jpg"

2020-11-21 07:40:43 Unable to write image to M:\series\Mysteries at the Museum (2010)\Season 23\Mysteries at the Museum (2010) (S23E10) (2019-03-06) (1080p-h264 BluRay AAC-2ch) Hurricane Ghost, Deadly Christmas Gift and Roswell Alien-thumb.jpg - are you sure the show folder is writable? [Errno 22] Invalid argument: 'M:\\series\\Mysteries at the Museum (2010)\\Season 23\\Mysteries at the Museum (2010) (S23E10) (2019-03-06) (1080p-h264 BluRay AAC-2ch) Hurricane Ghost, Deadly Christmas Gift and Roswell Alien-thumb.jpg'`

`
SickChill Configuration
  SickChill Info:
Branch: master
Commit: 54162dfb5f95c68f8da55bbfd9efa97e1f1a7caa
Version: v2020.11.16-1
Database Version: 44.5

  Python Version:
3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]

  SSL Version:
OpenSSL 1.1.1g 21 Apr 2020

  OS:
Windows-7-6.1.7601-SP1

  Locale:
en_US.cp1252

It seems that when it writes the episode to the destination folder it writes everything else and these error out.
And it's only the -thumb,   the -poster -fanart both get written with out an error..  also if I manually copy the file that works fine.

I did search but couldn't find this reported...  this has been going on for well over a month.
I didn't submit this through the Sickchill, Last time I did that it created an issue for each error.
It maybe fixed so that doesn't happen but I didn't want to take the chance hat 272 issues would be created.

`

```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
File name is too long

**Comment by nydave69** [comment]
That's what I first thought,  It's not.. -thumb fails (5 char) and -fanart works (6 char)..

and there are much shorter names in the logs..
