### ISSUE TITLE
PIP Version does not contain latest Code

### ISSUE THREAD

**Issue by himpich** [SickChill/SickChill#6910]
The Code on the pip version does not match the latest master branch code. 

For example the latest version https://pypi.org/project/sickchill/2020.11.16.post1/#files does not have the fix for https://github.com/SickChill/SickChill/issues/6892

**Comment by miigotu** [comment]
Yes, it does.

**Comment by himpich** [comment]
https://github.com/SickChill/SickChill/blob/master/sickchill/locale/en_US/LC_MESSAGES/messages.json has 127053 bytes, whereby the messages.json from the pypip.org tar.gz has 127051 - https://files.pythonhosted.org/packages/74/74/b455064799f65b42c2667f6a3fb182a90acc5171b25b5ef8c74e31fbee05/sickchill-2020.11.16.post1.tar.gz

The pip version is missing the linebreak (no problem) and missing the 'd' from Ignored (which was patched with https://github.com/SickChill/SickChill/issues/6892 )

**Comment by miigotu** [comment]
released
