### ISSUE TITLE
Search by episode title only - sickchill currently only searches by episode number

### ISSUE THREAD

**Issue by starlingmi** [SickChill/SickChill#6914]
the bbc show storyville ( released as either bbc.storyville or bbc.storyville.global ) is released by year and Episode title only!

Because there are no episode numbers on any of the released episodes sickchill can't find them. below is a sample search on [rarbg ](https://rarbgproxied.org/torrents.php?search=%09BBC.Storyville)showing how the episodes are formatted and released.

BBC.Storyville.2020.The.Night.Notre-Dame.Burned.1080p.HDTV.x265.AAC.MVGroup.org.mkv
BBC.Storyville.2017.Notes.on.Blindness.1080p.HDTV.x265.AAC.MVGroup.org.mkv
BBC.Storyville.Global.2020.An.Army.of.Sons.1080p.HDTV.x265.AAC.MVGroup.org.mkv
BBC.Storyville.2020.Pepe.the.Frog.Feels.Good.Man.1080p.HDTV.x265.AAC.MVGroup.org.mkv
BBC.Storyville.2020.The.Mole.Infiltrating.North.Korea.1080p.HDTV.x265.AAC.MVGroup.org.mkv
BBC.Storyville.Global.2020.Undercover.in.the.Alt-Right.1080p.HDTV.x265.AAC.MVGroup.org.mkv
BBC.Storyville.Global.2020.Cuban.Dreams.1080p.HDTV.x265.AAC.MVGroup.org.mkv 
BBC.Storyville.2016.The.Toughest.Horse.Race.in.the.World.Palio.1080p.HDTV.x265.AAC.MVGroup.org.mkv BBC.Storyville.2012.The.Queen.of.Africa.The.Miriam.Makeba.Story.1080p.HDTV.x265.AAC.MVGroup.org.mkv BBC.Storyville.2008.Dolce.Vita.Africana.720p.HDTV.x265.AAC.MVGroup.org.mkv
BBC.Storyville.2020.Avicii.True.Stories.1080p.HDTV.x265.AAC.MVGroup.org.mkv
BBC.Storyville.2009.The.Trials.of.Oppenheimer.720p.HDTV.x265.AAC.MVGroup.org.mkv
BBC.Storyville.2019.The.Trial.of.Ratko.Mladic.1080p.HDTV.x265.AAC.MVGroup.org.mkv
BBC.Storyville.2020.United.Skates.1080p.HDTV.x265.AAC.MVGroup.org.mkv

**Comment by miigotu** [comment]
Not worth the effort to add a new show type for one show. Download them manually.
