### ISSUE TITLE
Series Seasons and Episodes not updating

### ISSUE THREAD

**Issue by Walfy21** [SickChill/SickChill#6917]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Windows 
Browser: Chrome
What you did: Nothing, it's on episode listings from TVDB
What happened: All most all show's are showing as continue, instead of updating with latest season and episodes, not downloading an example is Chicago Med & Bull 2016
What you expected: This to be resolved if possible and episode listings updating, there are a lot of series not working

- I've uninstalled and re-installed sick chill with no luck, checked for updates and all good. TVDB has updated episode listings, don't see any errors in log's but not done Debug mode - Can enable and let it run for a while and upload once done this afternoon.

![Capture](https://user-images.githubusercontent.com/21161164/100583856-34d0db80-32e3-11eb-8e82-76922df49232.PNG)
![Capture1](https://user-images.githubusercontent.com/21161164/100583861-36020880-32e3-11eb-859f-74adc7debcea.PNG)
![Capture2](https://user-images.githubusercontent.com/21161164/100583865-369a9f00-32e3-11eb-9070-9695ec898b67.PNG)

Logs:
```
PASTE LOGS HERE
```

**Comment by Walfy21** [comment]
Adding restart logs, will add more after it's run for the day
[sickchill.log](https://github.com/SickChill/SickChill/files/5614554/sickchill.log)

**Comment by kyuuk** [comment]
Can you try "force update" with debug logs enabled & paste logs here ?

**Comment by Walfy21** [comment]
Ahh never thought of the force update! Thank you looks to be sorted now appreciate it!
