### ISSUE TITLE
Adding an NZB and getting sickchill to post process it.

### ISSUE THREAD

**Issue by psyciknz** [SickChill/SickChill#6918]
Not an issue, but something I'm working on.  Its a script that will look for a show in thetvdb but the release names wont match particularly well (sport is wonderful).  So it's a bridge between them.   I'll do the newznab search and send the nzb to sabnzbd.

What I'm after is what I need to name teh NZB/download so that it will match what Sickchill expects to post process it and mark it as complete.

Can I add a tvid (similar to what you can do in couchpotato where if you add .cp(tt<imdb id>) it knows what it is.  OR do I just match the episode name that sickchil was looking for...in this case it Series Region (type) in brackets

**Comment by psyciknz** [comment]
I worked it out, yes if I use the Show name, and pretty much exact episode name and number as excpected by sickchill, it'll read it.

**Comment by miigotu** [comment]
Tvdb is probably getting removed from sickchill, because we ain't gonna be paying for api access for open source software.

**Comment by psyciknz** [comment]
Ok.  Since my show names, episode names are coming from sickchill, then they just need to be in sync.  I've got somethnbg working, published it today..
https://github.com/psyciknz/ScDownloader if curious.
