### ISSUE TITLE
SABNZB passes mapped drive through to SC via NZBtoMedia - SC fails postproc because it needs the UNC path to the data

### ISSUE THREAD

**Issue by Jonnehs** [SickChill/SickChill#6920]
Simple issue to diagnose really, the drive map path shows in the debug log of SickChill - referencing the mapped drive path that SAB uses to find the data. SAB does not support using UNC paths, and wont let you enter them for remote data.

Cant find anything in the documentation for any 3 of the softwares involved to overcome this. Anyone know how, or have I missed something obvious?

Thanks

**Comment by miigotu** [comment]
Edit the SC service to run as the user who mapped the drives.

**Comment by Jonnehs** [comment]
It already is, runs as the same user as SABNZBD, still doesn't see the drive
