### ISSUE TITLE
API with Param Status never work with value Ignored

### ISSUE THREAD

**Issue by kyuuk** [SickChill/SickChill#6929]
It seems that every API that has the param `Status ` won't work with value `ignored` 
it always end with an `Invalid Status`because of this :

![image](https://user-images.githubusercontent.com/16566073/102140684-eb929700-3e5f-11eb-93b9-b38dc36ec026.png)

i think the cause is that the string used for comparison is the translated one from `sickchill/locale/en_US/LC_MESSAGES/messages.po`
line 251-252
which is used in `sickchill/oldbeard/common.py` line 588

I'm not sure of the best way to fix this, so i'm opening the issue 😆

**Comment by TATUMTOT** [comment]
Having the same issue.

**Comment by perksie** [comment]
Having the same issue.

**Comment by TATUMTOT** [comment]
Should this be an issue on sickchill or ombi side?

**Comment by kyuuk** [comment]
@TATUMTOT 
i think it's a sickchill issue, the API documentation on sickchill show the possible values for the field status as 
`['wanted', 'skipped', 'ignored']`
and the value ignored does not work, i tried with the value in the translation file, and it's not accepted either.
I agree that ombi could use `skipped` and that would be a workaround, but it's still a bug in sickchill that you could never use the `ignored` status

**Comment by pcmerc** [comment]
Bump~ Same issue here.

**Comment by LlmDl** [comment]
Thanks @miigotu, very much appreciated.

**Comment by LlmDl** [comment]
It would appear that shows will now be added to SickChill when requested by Ombi, but the episodes which are requested are not switched from Ignored to Wanted. So there's been some progress but it might not be all the way functional yet. 

Do other ombi users see the same thing?

**Comment by TATUMTOT** [comment]
It seems to be working now for me.

**Comment by LlmDl** [comment]
After https://github.com/SickChill/SickChill/commit/8579864616b8a49d67c5e6e88f36c4755837808f it would appear that it is working better:

- request a single episode of a show via ombi.
- see show get added but the episode not set to wanted.
- request a second single episode of the same show.
- see that episode get set to wanted.

**Comment by TATUMTOT** [comment]
@LlmDl what version of ombi are you running.

**Comment by LlmDl** [comment]
> @LlmDl what version of ombi are you running.  

3.0.4892

This could be a factor. Did you test using single episode request?

**Comment by LlmDl** [comment]
Had my first TV request for a new show, it successfully added the show and set both seasons to Wanted. So that's is excellent, I'll test again using single-episode-requests.

**Comment by Nanganator** [comment]
How can I resolve this issue because I'm still seeing it.  The show gets added but every episode is set as ignored. Once it is added requesting any other season or episode in the show works fine.
Ombi: 4.0.1142.0
SickChill: v2021.03.07-2

**Comment by miigotu** [comment]
> How can I resolve this issue because I'm still seeing it.  The show gets added but every episode is set as ignored. Once it is added requesting any other season or episode in the show works fine.
> Ombi: 4.0.1142.0
> SickChill: v2021.03.07-2
> 

You maybe aren't sending a status and are using status_default.

**Comment by Nanganator** [comment]
I'm guessing it's an Ombi issue. I can see Ombi add's everything as ignored:

2021-03-16 22:16:22 DEBUG :: WEBSERVER :: Trying to find 71894 on theTVDB
2021-03-16 22:16:22 DEBUG :: WEBSERVER :: API :: show.addnew: cur_kwargs {'tvdbid': '71894', 'status': 'ignored'}
2021-03-16 22:16:22 DEBUG :: WEBSERVER :: API :: all kwargs: '{'cmd': 'show.addnew', 'tvdbid': '71894', 'status': 'ignored'}'
2021-03-16 22:16:22 DEBUG :: WEBSERVER :: API :: all args: '()'
2021-03-16 22:16:22 DEBUG :: WEBSERVER :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED

After that Ombi then appears to spam sickchill with additional request apparently to try fetch the episode.

2021-03-16 22:16:26 DEBUG :: WEBSERVER :: API :: show.seasons: cur_kwargs {'tvdbid': '71894', 'season': '1'}
2021-03-16 22:16:26 DEBUG :: WEBSERVER :: API :: all kwargs: '{'cmd': 'show.seasons', 'tvdbid': '71894', 'season': '1'}'
2021-03-16 22:16:26 DEBUG :: WEBSERVER :: API :: all args: '()'
2021-03-16 22:16:26 DEBUG :: WEBSERVER :: API :: 127.0.0.1 - gave correct API KEY. ACCESS GRANTED

Sickchill sets default ep status

2021-03-16 22:20:01 INFO :: SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5

And Sickchill then ignores all the files

2021-03-16 22:20:06 DEBUG :: SHOWQUEUE-ADD :: Episode has already aired, marking it Ignore
2021-03-16 22:20:05 DEBUG :: SHOWQUEUE-ADD :: 71894: Episode S01E01 not found in the database

**Comment by miigotu** [comment]
I'm set up now to be able to add ombi (as long as I don't run out of disk space x.X 98%) to test for sure. I'll try it myself in a few days.

**Comment by Nanganator** [comment]
I'm seeing same behaviour as @LlmDl. If I add EVERYTHING from a show it works fine. Requesting just 1 ep of a new show, or 1 season of a multi-season new show adds the show to SC but all eps as ignored. Any subsequent ep or season requests for that newly added show work fine.

**Comment by miigotu** [comment]
So ombi is setting them to ignored when it adds the show:
```
2021-03-16 22:16:22 DEBUG :: WEBSERVER :: API :: all kwargs: '{'cmd': 'show.addnew', 'tvdbid': '71894', 'status': 'ignored'}'
```
Then when it requests seasons, thats just to get a list of seasons
```
2021-03-16 22:16:26 DEBUG :: WEBSERVER :: API :: all kwargs: '{'cmd': 'show.seasons', 'tvdbid': '71894', 'season': '1'}'
```

After that if it is supposed to be changing a status for a single episode, it should call `episode.setstatus`
If it is just trying to search for a release for an episode, it would call `episode.search` which does not change the status (and is not supposed to)

Seeking as I dont have the complete log from the ombi calls and exactly what you are trying to do, there isnt anything I can do.
Ideally, ombi should also be setting future_status in the first api call as well.

**Comment by miigotu** [comment]
Are either of you running ombi in docker? If so, which tagged release are you using? Because `linuxserver/ombi:latest` is not the latest.

**Comment by TATUMTOT** [comment]
Windows for me.

**Comment by LlmDl** [comment]
Windows for me as well.

**Comment by Nanganator** [comment]
Ubuntu server 20.04.

**Comment by Nanganator** [comment]
Played around a bit and things got weirder.

If the defaults in SickChill are set
Quality: SD
Previous eps: skipped
Future Eps: Wanted
And in Ombi, under SickChill config you select default as the quality profile, everything is working fine! But who wants SD...

Tried setting the defaults in SC to 720p and 1080p with Ombi's SC config set to default and neither works. Same behavior as before

Set SC default back to SD and tried setting SC's config in Ombi to 720p and 1080p and neither works.
