### ISSUE TITLE
Ignored and Skipped status being ignored

### ISSUE THREAD

**Issue by brycelarge** [SickChill/SickChill#6933]
I have some series which are old and have many seasons. I want to change the preferred quality so I change the older episodes status to ignored and update the preferred quality but SickChill is not respecting the new ignored status and then all the old episodes are now being snatched and the status returns to downloaded/wanted/snatched. This is flooding transmission with many downloads.

I expected to be able to change the status of the older episodes to ignored or skipped so SickChill would stop adding them to the backlog queue or trying to get higher quality versions.

Is this normal behavior and if so how do I go about telling SickChill to chill and leave older episodes alone and only focus on newer episodes of a show?

Branch/Commit: master
OS: Arch Linux
Browser: Firefox latest
What you did: Updated shows with many seasons to ignored and or skipped so only new episodes are in wanted status
What happened: All episodes which are in ignored and or skipped status get changed back to wanted and floods transmission
What you expected: For all ignored and or skipped episodes to be ignored and stay in that status until I manually change the status again

**Comment by miigotu** [comment]
That was a bug that was fixed like the day after you posted this.
