### ISSUE TITLE
SickChill will not start

### ISSUE THREAD

**Issue by HPMSGEN8** [SickChill/SickChill#6935]
Good Day,

Please see the below issues i am having to get the service to start.

Branch/Commit: Master
OS: Synology
Browser: MS Edge
What you did: Tried to start sickchill even did the upgrade vai the FAQ
What happened: Failed to start package
What you expected: Services Start
Logs:
```
Starting sickbeard-custom command /volume1/@appstore/sickbeard-custom/env/bin/python /volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py --daemon --pidfile /volume1/@appstore/sickbeard-custom/var/sickbeard-custom.pid --config /volume1/@appstore/sickbeard-custom/var/config.ini --datadir /volume1/@appstore/sickbeard-custom/var/ 
/volume1/@appstore/sickbeard-custom/env/bin/python: can't open file '/volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py': [Errno 2] No such file or directory
```

Thanks.

**Comment by miigotu** [comment]
There is no SickBeard.py, only a SickChill.py, also you have to use python3

**Comment by HPMSGEN8** [comment]
Hi @miigotu 

I have Python 3 installed already and under /volume1/@appstore/sickbeard-custom/var/SickBeard/ there is only SickChill.py

Anything i need to change in the configs to solve this ?

**Comment by miigotu** [comment]
Sickbeard-custom is not the correct package. Check open PRs on synocommunity for the right package.

**Comment by HPMSGEN8** [comment]
Hi @miigotu 

I have always used this and added the URL from this Repo to install if this has changed where can i find it since there is no SickChill Package on the Repo for the Community or am i missing something ?

Thanks again

**Comment by miigotu** [comment]
That package no longer works.

https://github.com/SynoCommunity/spksrc/pull/4161

**Comment by HPMSGEN8** [comment]
Thanks alot :)

Happy Holidays

**Comment by mchirlin** [comment]
So what is the resolution here? Do we just need to wait until the new package is released? I am also unable to start SickChill which was using the Custom Sickbeard package.

Why did this just stop working without a replacement?
