### ISSUE TITLE
Migration From sickbeard-custom To SickChill New Install

### ISSUE THREAD

**Issue by HPMSGEN8** [SickChill/SickChill#6936]
Good Day.

Can someone please let me know how I can migrate my data from sickbeard-custom to the new SickChill on Synology.

I have the old files etc... but the new DB Name is different etc... 

Thanks in advanced.

**Comment by miigotu** [comment]
The db will rename on its own. Just restore your backup

**Comment by HPMSGEN8** [comment]
Hi @miigotu 

The issue seems to be it will not restore :(

**Comment by miigotu** [comment]
Go to the link I sent you in the other issue and read the comments.
