### ISSUE TITLE
[APP SUBMITTED]: Could not decode to UTF-8 column 'resource' with text 'H:\Tv-Shows-Compleet\Outlander S03E13 1080p AMZN WEBRip DDP5_1 x264 EN-NL subs\Outlander.S03E07.Creme.De.Menthe.1080p.AMZN.WEBRip.DDP5.1.x264-N

### ISSUE THREAD

**Issue by divx-guy** [SickChill/SickChill#6938]
### INFO
Python Version: **3.10.0a3 (tags/v3.10.0a3:8bae2a9, Dec  7 2020, 20:13:25) [MSC v.1927 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.21277-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@46a7f2a2304d6abbc6459820f88d830c57e89bcb
No Log available with ERRORS:
### ERROR
```
Fatal error executing query with db.action in database C:\WINDOWS\system32\config\systemprofile\sickchill\sickchill.db: Could not decode to UTF-8 column 'resource' with text 'H:\Tv-Shows-Compleet\Outlander S03E13 1080p AMZN WEBRip DDP5_1 x264 EN-NL subs\Outlander.S03E07.Creme.De.Menthe.1080p.AMZN.WEBRip.DDP5.1.x264-N
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation
