### ISSUE TITLE
[APP SUBMITTED]: no such column: sub_use_sr_metadata

### ISSUE THREAD

**Issue by mrlad967** [SickChill/SickChill#6939]
### INFO
Python Version: **3.7.7 (default, Oct 13 2020, 16:39:42) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-3.10.102-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@46a7f2a2304d6abbc6459820f88d830c57e89bcb
Link to Log: https://gist.github.com/599f61128195369c007f649b78bdcda2
### ERROR
```
Fatal error executing query with db.action in database /volume1/@appstore/sickchill/var/sickchill.db: no such column: sub_use_sr_metadata
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Looks like SC did not create your db?
