### ISSUE TITLE
Discord notifications fail due to AttributeError

### ISSUE THREAD

**Issue by offbyone** [SickChill/SickChill#6941]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
> Branch: master
> Commit: 46a7f2a2304d6abbc6459820f88d830c57e89bcb
> Version: v2020.11.24-1
> Database Version: 44.2
> Python Version:3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
> SSL Version:OpenSSL 1.1.1d 10 Sep 2019
> OS:Linux-5.4.72-v7l+-armv7l-with-debian-10.6
> Locale:en_US.UTF-8

Browser: Chrome on macOS

What you did:

Enabled Discord notifications, to a webhook at `https://discord.com/api/webhooks/<prefix elided>/<ID elided>`

What happened:

Testing resulted in "Discord message failed"

What you expected:

Something else :)

Logs:
```
AA AttributeError: 'NoneType' object has no attribute 'status_code'
AA if error.response.status_code != 429 or int(error.response.headers.get('X-RateLimit-Remaining')) != 0:
AA File "/opt/sickchill/sickchill/oldbeard/notifications_queue.py", line 145, in _send_discord
AA self.last_result = self._send_discord()
AA File "/opt/sickchill/sickchill/oldbeard/notifications_queue.py", line 110, in run
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
AA raise MissingSchema(error)
AA File "/opt/sickchill/lib3/requests/models.py", line 388, in prepare_url
AA self.prepare_url(url, params)
AA File "/opt/sickchill/lib3/requests/models.py", line 314, in prepare
AA hooks=merge_hooks(request.hooks, self.hooks),
AA File "/opt/sickchill/lib3/requests/sessions.py", line 459, in prepare_request
AA prep = self.prepare_request(req)
AA File "/opt/sickchill/lib3/requests/sessions.py", line 516, in request
AA return session.request(method=method, url=url, **kwargs)
AA File "/opt/sickchill/lib3/requests/api.py", line 61, in request
AA return request('post', url, data=data, json=json, **kwargs)
AA File "/opt/sickchill/lib3/requests/api.py", line 119, in post
AA headers=headers)
AA File "/opt/sickchill/sickchill/oldbeard/notifications_queue.py", line 142, in _send_discord
2021-01-01 08:36:16 INFO :: WEBSERVER-HOME_0 :: Sending discord message to url:
2021-01-01 08:36:16 INFO :: WEBSERVER-HOME_0 :: Sending discord message: This is a test notification from SickChill
```

**Comment by offbyone** [comment]
Screen shot of the settings
![image](https://user-images.githubusercontent.com/181693/103442678-589e7e80-4c0d-11eb-9819-ea54d1864197.png)

**Comment by tyzbit** [comment]
As a band-aid, if you shut SickChill down and manually edit config.ini, it works.  I haven't tested re-saving over it though, it might clobber the settings.

```
[Discord]
  use_discord = 1
  discord_notify_snatch = 0
  discord_notify_download = 1
  discord_webhook = "https://discord.com/api/webhooks/xxxx/yyyy"
```

**Comment by miigotu** [comment]
This has already been fixed, just make sure you have http/https in your url.

**Comment by tyzbit** [comment]
I copied the weblink straight from Discord (which definitely had 'https://') and pasted it into the settings and it didn't save.  I'm on `latest`.

**Comment by miigotu** [comment]
@tyzbit you need to click save before you click test
