### ISSUE TITLE
Raspbian : openssl strange issue with version

### ISSUE THREAD

**Issue by flapflap** [SickChill/SickChill#6946]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Raspbian 
Browser: Chrome
What you did: Fresh install from git
What happened:
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.1.0l  10 Sep 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order
What you expected:
Not this message :)

So when I'm launching directly via command line I don't have the complain about the openssl version
but when it's launched from systemd service I got it...

If I run 
python and then import ssl, ssl.OPENSSL_VERSION 
I got 
`'OpenSSL 1.1.1i  8 Dec 2020'`

So I don't get it :(

**Comment by miigotu** [comment]
It's not an error, and it comes from a 3rd party library. Ignore it.

**Comment by flapflap** [comment]
Ow. Ok! ¯\_(ツ)_/¯
