### ISSUE TITLE
Prefer x265/HEVC versions

### ISSUE THREAD

**Issue by stoniedk** [SickChill/SickChill#6954]
Hi

Feature request: Prefer x265/HEVC versions, because of the smaller filesize and better quality

**Comment by potestus** [comment]
Yes I would like this too.. I use a workaround at the moment to select t x265 and reject all x264 etc but it causes lots of unnecessary processing

**Comment by miigotu** [comment]
Feature requests stay closed, I can search back through the tagged issues for feature requests when it is time for features.
