### ISSUE TITLE
Browser GUI will not open. cant reach this page. localhost refused to connect.

### ISSUE THREAD

**Issue by mlwehk** [SickChill/SickChill#6960]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)
unable to enable - cant get to the gui.
Branch/Commit: unsure used SickChillInstaller.exe v0.5.9
OS: Win 10
Browser: Edge
What you did: Rebooted PC and 
What happened:  have not been able to open since
What you expected: I tried a current pull.
net stop sickchill
cd C:\SickChill\SickChill
C:\SickChill\Git\bin\git pull
net start sickchill
no luck
Then tried to re-install SickCHillInstaller.exe v0.5.9 - still will not open

Logs: this log appears to be before the issue. Issue was noticed on Jan 14, 2021
[sickchill.log](https://github.com/SickChill/SickChill/files/5821364/sickchill.log)

```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Make sure you have the newest installer
