### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by zobe123** [SickChill/SickChill#6963]
### INFO
Python Version: **3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]**
Operating System: **Linux-4.15.0-126-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f6daa75f6fe3af1f146f5948a838e33b74acec0c
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by zobe123** [comment]
### INFO
Python Version: **3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]**
Operating System: **Linux-4.15.0-126-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@07b71fe7076bf50be4c06f6d852a25b356ddaf5b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mufapu** [comment]
### INFO
Python Version: **3.9.1 (default, Jan  8 2021, 12:11:08) [Clang 12.0.0 (clang-1200.0.32.28)]**
Operating System: **macOS-11.1-arm64-arm-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@07b71fe7076bf50be4c06f6d852a25b356ddaf5b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **3.10.0a4 (tags/v3.10.0a4:445f7f5, Jan  4 2021, 19:55:53) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@07b71fe7076bf50be4c06f6d852a25b356ddaf5b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hieppo** [comment]
### INFO
Python Version: **3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]**
Operating System: **Linux-4.15.0-108-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DravenSA** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DravenSA** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hubdows** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by bwguy** [comment]
### INFO
Python Version: **3.8.3 (default, Jun 12 2020, 20:24:48) [GCC 8.4.0]**
Operating System: **Linux-4.14.24-qnap-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by m00n22** [comment]
### INFO
Python Version: **3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]**
Operating System: **Linux-4.4.180+-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@1e656000415b1e32dee9e04dabc53a3636045c02
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ebsmith** [comment]
### INFO
Python Version: **3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]**
Operating System: **Linux-5.4.0-64-generic-x86_64-with-glibc2.29**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@4cc6d62ea8a54cf0e04604b09a676b61a726556c
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hieppo** [comment]
### INFO
Python Version: **3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]**
Operating System: **Linux-4.15.0-108-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@4cc6d62ea8a54cf0e04604b09a676b61a726556c
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Prime Video. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by bjwest** [comment]
I'm getting this error on a few different networks as well as Amazon.  ITV1, Showcase, Spike, Dky1, YTV, TV2 and History.  This has been going on for quite some time now, is there any way to stop filling my logs with this error?  It obviously doesn't affect the operation.
