### ISSUE TITLE
SickChill checking for better quality copies of all episodes after update

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#6964]
Branch/Commit: Master/f6daa75f6fe3af1f146f5948a838e33b74acec0c 
OS: Windows 10
Browser: Firefox
What you did: upgrade to latest build
What happened: every episode seems to have gone into a backlog search for better quality copies - appx 1tb worth of episodes have been queued up and it's still going (now 1.4tb)
What you expected: Continued normal behaviour, shows to scan for missing episodes and download in the quality the show is set to. Even shows where the quality matches what I've set it to, SickChill is looking for a better quality. For example Big Bang Theory I set to HD for the quality and it triggered downloads for not only the early episodes I had in SD quality but is returning 1080p copies of the episodes I had in 720p quality.

Logs:  Searchqueue-daily-search Checking if we should stop searching for a better quality for for episode

I guess this could be user error but the only change I've made is to update my copy of SickChill.

**Comment by rutskiuk** [comment]
Looks like it's paused after getting to 1250 or 2.4tb worth of downloads.
From what I can see if I set a show to 720p quality it will search for a better 720p - ie replace TV or Web with BluRay
A 1080p will do the same, replace TV or Web with BluRay
A show marked as HD will replace all episodes with 1080p BluRay
As yet shows set as Any doesn't seem to be affected

**Comment by rutskiuk** [comment]
Looking at the changes I think this was caused by https://github.com/SickChill/SickChill/issues/6944
I have gone through the shows and it looks like it has affected all of those in HD/720p/1080p quality, Any and SD look like they are unaffected. It would be useful if shows could have a 'backlog quality' feature or something to prevent this kind of thing.
I've had a look through the settings and located the 'backlog missing episodes only' which I have now enabled.

**Comment by bigwavedave42** [comment]
I seem to have been hit by this too... I did the latest update, and shortly after noticed a ton of old shows were downloading.  It did seem to be related to the quality, or perceived quality anyways.  Thanks to @rutskiuk I found those settings and did a restart of SickChill.  Simply enabling the backlog features didn't seem to be enough.  (Can never remember which will be immediate and which require a restart).

**Comment by miigotu** [comment]
@Nyaran told ya 🤣🤷‍♂️

**Comment by miigotu** [comment]
Reverted

**Comment by hairyhippy** [comment]
Hi miigotu

All very well closing but what do you mean by it was reverted yesterday? Do we need to apply an update? What's the solution to stop this happening?

**Comment by rutskiuk** [comment]
Reverting means you need to update to roll back the change. that should stop it happening.

The challenge then is to restore your database which in my case the update ruined, I don't have the file quality in the name so I have to reinstate the quality of 1250 files and I don't have any backups from the last 6 months to restore from.
