### ISSUE TITLE
Shows redownloading

### ISSUE THREAD

**Issue by hairyhippy** [SickChill/SickChill#6969]
Branch/Commit: master/f6daa75f6fe3af1f146f5948a838e33b74acec0c
OS: DSM (Synology)
Browser: Chrome
What you did:  Nothing, no change to settings, etc,
What happened:  Shows already grabbed a long time ago have started to redownload, perhaps at a better quality than the original, yet I have not changed anything in settings or find a setting that would make this to happen.
What you expected:  I would expect shows to only be redownloaded if the original file was nuked or the user manually instructed.  What could have changed to suddenly make this happen?

**Comment by sorhol** [comment]
I have the same problem on Ubuntu 18.04 LT
Branch: master
Commit: 07b71fe7076bf50be4c06f6d852a25b356ddaf5b
Version: v2020.11.24-1
Database Version: 44.2

I can also mention: 
download of subtitles does not work
I get an error that Sickchill cannot move files to destination, but the file are actually moved

I had earlier downloaded show destroyed by this.

**Comment by miigotu** [comment]
Yeah, it was reverted yesterday. Check closed issues.

**Comment by hairyhippy** [comment]
Hi miigotu

All very well closing but what do you mean by it was reverted yesterday?  Do we need to apply an update?  What's the solution to stop this happening?
