### ISSUE TITLE
Manual Post Processing and files already in "series" folder

### ISSUE THREAD

**Issue by crzed1** [SickChill/SickChill#6974]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: [07b71fe7076bf50be4c06f6d852a25b356ddaf5b](http://dereferer.org/?https://github.com/SickChill/SickChill/commit/07b71fe7076bf50be4c06f6d852a25b356ddaf5b)
OS: Linux-2.6.32.12-armv5tel-with-glibc2.4 
Browser: Firefox
What you did: I manually post processed shows that were already in their series subfolder
What happened: I got a WARNING message saying an episode in it's show directory cannot be processed
What you expected: The episode being RENAMED into it's episodes preferred title
Logs:
```
2021-01-20 02:00:43 WARNING :: WEBSERVER-POSTPROCESS_0 :: Cannot process an episode that's already been moved to its show dir, skipping /volume3/series/XXX/Season 02/@eaDir/XXX - S02E01 - YYYYYYYY.mkv
```

This might not be an issue as well as a **Feature Enhancement Request**? 

1) Would it be possible to add the option of RENAME to the MANUAL POST PROCESSING option and do a rename of files in place?

or

2) When selecting one of the "**Show root directories**" during the MANUAL POST PROCESSING could it put out a warning saying it can't perform this action, in stead of going through the whole list of shows and failing on every single one of them?

_(other solutions might exist as well, I am just pointing out to the two solutions that seem to be the more obvious ones to me)_

**Comment by miigotu** [comment]
Go to the show page and click preview rename, you can rename them that way. But it is not advised to do it this way, you are trying to use the post processor whose whole job is to move the files from the download folder to the show folder.
