### ISSUE TITLE
"Manage torrent" Button in "Manage" menu disappears if "https" protocol set for "Torrent Search" Host

### ISSUE THREAD

**Issue by iseeweiner** [SickChill/SickChill#6984]
### Before submitting your issue:

# Some infos about my version

  SickChill Info:
Install: pip
Version: v2020.11.24-1
Database Version: 44.2

  Python Version:
3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

  SSL Version:
OpenSSL 1.1.1f 31 Mar 2020

  OS:
Linux-5.4.0-62-generic-x86_64-with-glibc2.29

  Locale:
fr_FR.UTF-8

# I noticed that if i set in "Search Settings" -> "Torrent Search" and https host for "Torrent host:port"

In the "Manage" Menu, the "Manage torrents" button disapears

Is it possible to modify you code so that, the button still remains even if "https" protocol is specified for :

"Torrent Search" -> "Torrent host:port"

Thanks in advance !

PS : Good job though, not kissing any butt but i really enjoy this app ;)

**Comment by miigotu** [comment]
No, this is intentional because the URL is passed with user:pass in the URL and is insecure. You need to use a local address to use the manage torrents button.
