### ISSUE TITLE
GoFundMe

### ISSUE THREAD

**Issue by miigotu** [SickChill/SickChill#6985]
So, my laptop is broken, and I have been unable to do anything for the project other than what I can do on the web interface on GitHub for the past several months, and I'm not sure when I might be able to fix that situation.

It was suggested that I create a GoFundMe (which I kind of detest when people do this) and someone told me it would be a good idea. 

There is more info about my situation on the GoFundMe, so if you are feeling generous or you can afford to help I appreciate it. If not, I appreciate you still. Thanks.

https://www.gofundme.com/laptop-for-open-source-developer-miigotu

**Comment by Smokey23** [comment]
Sent ya what I could.  Hope it helps!

**Comment by miigotu** [comment]
Thanks to anyone who donated or took the time to read about my situation. I'm so happy we have such a great community. Im going to close this because I did end up getting the laptop thanks to the fundraiser!
