### ISSUE TITLE
[APP SUBMITTED]: [Errno 1] Operation not permitted: '/media/Tvshows/Last Man Standing (2011)/Season 09/Last Man Standing (2011) - S09E05 - Outdoor Toddler.mp4'

### ISSUE THREAD

**Issue by graeme86** [SickChill/SickChill#6993]
### INFO
Python Version: **3.7.9 (default, Dec 12 2020, 01:25:17) [Clang 8.0.1 (tags/RELEASE_801/final 366581)]**
Operating System: **FreeBSD-12.2-RC3-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
Link to Log: https://gist.github.com/f2a34220b28df21583786c8d59f3c610
### ERROR
```
Unable to move file /media/Downloads/Complete/TVShows/Last.Man.Standing.S09E05.WEBRip.x264-ION10/8fc3008e35f148c69f540e64e7659c34.mp4 to /media/Tvshows/Last Man Standing (2011)/Season 09/Last Man Standing (2011) - S09E05 - Outdoor Toddler.mp4: [Errno 1] Operation not permitted: '/media/Tvshows/Last Man Standing (2011)/Season 09/Last Man Standing (2011) - S09E05 - Outdoor Toddler.mp4'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by graeme86** [comment]
It moves the file on the initial process but leaves the file in the to be process folder and doesn't delete it. It then tries to reprocess the file and I get this error. I don't believe I have made any changes sickchill settings or file permissions

**Comment by IxFail** [comment]
@graeme86 sounds like #6971
