### ISSUE TITLE
TLS Error when request is sent to NZBGet

### ISSUE THREAD

**Issue by ccwillia** [SickChill/SickChill#6995]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: DSM 2.4
Browser: Chrome
What you did: Initiated manual search 
What happened: Match was found and sent to NZBGet but then its unable to Fetch (TLS Error)
What you expected: The download to start.  I am using newnab custom provider.  I initially thought this was a provider issue but when testing the same provider from couchpotato the download begins immediately.  
Logs:
```
2021-01-29 16:11:35 INFO     SEARCHQUEUE-MANUAL- :: Beginning manual search for: [File]
2021-01-29 16:11:35 INFO     SEARCHQUEUE-MANUAL-253478 :: [NZBGeek] :: Performing episode search for File
2021-01-29 16:11:58 INFO     SEARCHQUEUE-MANUAL-253478 :: [NZBGeek] :: Quality of File is 1080p WEB-DL
2021-01-29 16:11:59 INFO     SEARCHQUEUE-MANUAL- :: Downloading File from NZBGeek
2021-01-29 16:11:59 INFO     SEARCHQUEUE-MANUAL- :: Sending NZB to NZBget
```

**Comment by miigotu** [comment]
Going to need a debug log and the tls error, I don't see the tls error in the info you provided.

**Comment by ccwillia** [comment]
The TLS error is not happening in SickChill.  It's happening in NZBGet.  The reason i think its related to SickChill is because the provider recently made updates so i had to replace my api-key in SickChill.  After replacing i no longer get api-key error but when SickChill sends the request to NZBGet i get this TLS error.  This is not happening when using the same provider from CouchPotato.  I am still using the older SickChill version that uses Python 2.  Sorry i know this is very vague, but i feel its something with the way the request is sent to NZBGet since CouchPotato is working.  When the request comes to NZBGet it says


FETCHING | File URL high priority
https://api.nzbgeek.info/api?t=get&id=51912bcb678323fe363d4f04625ceef6&apikey=***

Does SickChill actually send the NZB file to NZBGet or does it just send the API call required to get the NZB file?

**Comment by miigotu** [comment]
SickChill is just sending the link to nzbget, nzbget downloads the nzb. Python2 version is not supported anymore.

**Comment by ccwillia** [comment]
Thanks
