### ISSUE TITLE
Trakt Error msg

### ISSUE THREAD

**Issue by potestus** [SickChill/SickChill#6996]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
SickChill Info:
Branch: master
Commit: c6ee7aa889661dde40ea2240ecb5d88da776e039
Version: v2020.11.24-1
Database Version: 44.5

  Python Version:3.9.0 (default, Nov 30 2020, 13:01:15) [GCC 8.4.0]
  SSL Version:OpenSSL 1.1.1h 22 Sep 2020
  OS:Linux-3.4.6-armv5tel-with-glibc2.27
  Locale:en_US.UTF-8
OS:
Browser:
What you did:
Tested Trakt ok
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```2021-01-29 16:40:16 Unauthorized. Please check your Trakt settings

**Comment by miigotu** [comment]
Yeah, check your trakt settings. Either your authentication is wrong or you were banned or something.

**Comment by potestus** [comment]
As I said the trakt test works fine and this is an intermittent message.
Perhaps a timeout issue?

Terry

**Comment by mgaulton** [comment]
I seem to be having something like this. My logs are littered with that log line, though as recently as a couple weeks ago, show sync did work. Test button returns success.
