### ISSUE TITLE
Windows installer error - cannot download installer.ini

### ISSUE THREAD

**Issue by quickdry** [SickChill/SickChill#6998]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Windows Server 2012
Browser:
What you did: ran 0.5.9 windows installer 
What happened: error connecting to download installer.ini, same result when ran as administrator.
![image](https://user-images.githubusercontent.com/10321869/106401345-bd9cfc80-6477-11eb-9436-aed505d44fa5.png)

![image](https://user-images.githubusercontent.com/10321869/106401319-947c6c00-6477-11eb-8ce7-dd0baab3e405.png)

What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
You need internet access

**Comment by quickdry** [comment]
it has internet, that's how the installer was downloaded and run immediately after (it wasn't transferred over via sneakernet :p ). 

Same installer ran fine on a Win 10 VM running on that machine, so blew away everything on the 2k12 except the db, config and service and copied in the fresh files from the Win 10 install. Just needed to adjust the service launch settings using nssm, and updating some config.

Leaving that here in case anyone runs into same issue.

**Comment by miigotu** [comment]
Was probably a hosting issue on GitHub side 😉
