### ISSUE TITLE
Use parent folder names for post-processing

### ISSUE THREAD

**Issue by doublegalz** [SickChill/SickChill#7000]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Win 10 64 bit
Browser: Chrome
What you did: Post-process
What happened: 
[sickchill.log](https://github.com/SickChill/SickChill/files/5906332/sickchill.log)

What you expected: Process files based on name of folder if file name doesn't match.  This used to work.  If I have a fodler name called TV Show S01E01 then the file under that called abx.xyz.mp4, SickChill could process based on the folder name, not the file name.  But it is not doing that.  I thought there used to be an option, but I could be recalling wrong.
Logs:
```
PASTE LOGS HERE
```

**Comment by MichelRabozee** [comment]
Hello, my 2 cents here: the handling of the abc.xyz naming is already possible by enabling in the Sickchill post processing settings: activate "rename episode using the Episode Naming settings?" and set the name pattern you desire (personally, I set it to : "Saison %S/%S.N.S%0SE%0E.%RT.%SQ.N-%RG").

**Comment by doublegalz** [comment]
I already have that set.  But when the post-processing happens on the
folders that have the file names abc.xyz.mkv. underneath them....  in the
log it says that there are no processable files in the folder.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MichelRabozee** [comment]
Strange... It works here. I am using nzbToMedia with SABnzbd.

**Comment by nedillon** [comment]
I am having the same issue. 

This appears to be caused by [#6916](https://github.com/SickChill/SickChill/pull/6916), which made a change to specifically ignore mkv, mp4, and avi files named as "abc.xyz*". It looks like this was an attempt to avoid moving sample files instead of the actual file.

This is causing valid files named with "abc.xyx" to be ignored.

Here is a sample of my log:
```
2021-02-04 16:42:54 DEBUG :: POSTPROCESSOR-AUTO :: E:\Shared\Downloads\SickChill\The.Expanse.S05E10.Nemesis.Games.720p.REPACK.AMZN.WEBRip.DDP5.1.x264-NTb.mkv-xpost : No processable items found in folder
2021-02-04 16:42:53 DEBUG :: POSTPROCESSOR-AUTO :: Processing folder E:\Shared\Downloads\SickChill\The.Expanse.S05E10.Nemesis.Games.720p.REPACK.AMZN.WEBRip.DDP5.1.x264-NTb.mkv-xpost
2021-02-04 16:42:52 DEBUG :: POSTPROCESSOR-AUTO :: E:\Shared\Downloads\SickChill\The.Expanse.S05E07.Oyedeng.720p.REPACK.AMZN.WEBRip.DDP5.1.x264-NTb.mkv-xpost : No processable items found in folder
2021-02-04 16:42:52 DEBUG :: POSTPROCESSOR-AUTO :: Processing folder E:\Shared\Downloads\SickChill\The.Expanse.S05E07.Oyedeng.720p.REPACK.AMZN.WEBRip.DDP5.1.x264-NTb.mkv-xpost
2021-02-04 16:42:52 DEBUG :: POSTPROCESSOR-AUTO :: E:\Shared\Downloads\SickChill\Shameless.US.S11E05.Slaughter.720p.AMZN.WEBRip.DDP5.1.x264-NTb[TGx]-xpost : No processable items found in folder
2021-02-04 16:42:51 DEBUG :: POSTPROCESSOR-AUTO :: Processing folder E:\Shared\Downloads\SickChill\Shameless.US.S11E05.Slaughter.720p.AMZN.WEBRip.DDP5.1.x264-NTb[TGx]-xpost
```

The first listed has a (valid) file named "abc.xyz.9910d9e18b5c4a.mkv"
The second's file is named "abc.xyz.16197b07cf8048.mkv"
The third's is named "abc.xyz.mkv"

None of the folders actually have sample files. So it seems the assumption that all "abc.xyz" files are samples is incorrect.

In the meantime, you can just manually rename the file. Even something as simple as "a.mkv" will cause it to get picked up.

**Comment by MichelRabozee** [comment]
I now understand why it is working for me, I am still on the Python 2 Sickchill. Guess I will wait a bit longer to update :-(

**Comment by doublegalz** [comment]
That is exactly what I am seeing, thanks so much!  I have been using Bulk
Rename to rename the files, but probably easier just to name them manually
if all I have to do is change from abc to a.  Thanks so much for your help!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by miigotu** [comment]
Reverted 6916. This issue was not due to not honoring folder name.
