### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/home/grant/Downloads/complete/For.Life.S02E06.720p.WEB.H264-STRONTiUM.1/d67e7ac5c3104bea9e456a7f481578e4.mkv'

### ISSUE THREAD

**Issue by thisdjiknow** [SickChill/SickChill#7001]
### INFO
Python Version: **3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]**
Operating System: **Linux-5.8.0-41-generic-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
No Log available with ERRORS:
### ERROR
```
Unable to move file /home/********/Downloads/complete/For.Life.S02E06.720p.WEB.H264-STRONTiUM.1/d67e7ac5c3104bea9e456a7f481578e4.mkv to /media/TV3/For Life/For.Life.S02E06.354.mkv: [Errno 2] No such file or directory: '/home/********/Downloads/complete/For.Life.S02E06.720p.WEB.H264-STRONTiUM.1/d67e7ac5c3104bea9e456a7f481578e4.mkv'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by thisdjiknow** [comment]
Will do. This started after the last update (Version: v2020.11.24-1) my sickchill user and the user for the folder (/home/user/Downloads/complete) that sickchill sends new acquisitions to sabnzbd are the same. The externals are owned by root, but the group is the same user. I haven't changed _any_ settings that could have caused it to be wonky and it's worked for me since I've had sickchill/beard (at least 3-4 years)

**Comment by miigotu** [comment]
Check with the latest update, and make sure to supply a debug log from when it fails.
