### ISSUE TITLE
Problem with inaccurate Scene Exceptions

### ISSUE THREAD

**Issue by FurrTheBear** [SickChill/SickChill#7003]
My apologies if this is the incorrect place to put this, but it's where the configuration page in question sent me...

The UK show _QI_ has a standard and an extended-length version, and some how the scene exceptions for _QI_ now include _QI XL,_ which as you might imagine is causing havoc. I can't remove the incorrect entries myself and I haven't been able to figure out how to get RID of them. Any assistance - even telling me "not our issue, report it HERE" - would be appreciated.

I should point out that QI XL has its OWN TVDB ID - 369316. 

![QI-XL](https://user-images.githubusercontent.com/78501778/106793776-beb36280-660c-11eb-8792-0dd008750b6a.png)

**Comment by kyuuk** [comment]
Hello @FurrTheBear,
Actually the is a file [here ](https://github.com/SickChill/sickchill.github.io/blob/master/scene_exceptions/scene_exceptions.json) that contains all the scene exceptions you see there.
Maybe try a fixing it and submitting a pull request

**Comment by FurrTheBear** [comment]
> Hello @FurrTheBear,
> Actually the is a file [here ](https://github.com/SickChill/sickchill.github.io/blob/master/scene_exceptions/scene_exceptions.json) that contains all the scene exceptions you see there.
> Maybe try a fixing it and submitting a pull request

Fix it, I guess - but I have no idea how to do what you suggest. This is the problem entry - all three "XL" lines need to be removed.

```
        "72716": {
            "-1": [
                "QI XL",
                "BBC QI XL",
                "BBC QI XL (Quite Interesting)",
                "BBC QI",
                "BBC QI (Quite Interesting)"
            ]
        },

```

**Comment by poisonadder1** [comment]
Pull request submitted https://github.com/SickChill/sickchill.github.io/pull/42

**Comment by miigotu** [comment]
merged
