### ISSUE TITLE
[APP SUBMITTED]: get() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by turkeylegs1** [SickChill/SickChill#7006]
### INFO
Python Version: **3.6.8 (default, Feb 13 2019, 20:48:47) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@4cc6d62ea8a54cf0e04604b09a676b61a726556c
Link to Log: https://gist.github.com/db96b7c198024db5b97a80847da30bc3
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Delete that gist, it has your user/pass

**Comment by turkeylegs1** [comment]
Good lord. Thanks for catching that.
Smh that's what I get for just uploading direct.
