### ISSUE TITLE
Jellyfin library update not working

### ISSUE THREAD

**Issue by Ulrar** [SickChill/SickChill#7007]
Hi,

Jellyfin is an open source fork of Emby, which SickChill has a notification integration for.
Enabling the Emby one and pointing it at Jellyfin succeeds, at least on the test button, but in practice it seems like it does nothing - updating a show using that doesn't trigger an update on the Jellyfin side.
I can't see any errors in either logs.

Is this supposed to work, is the Emby integration compatible with Jellyfin, or is this a known incompatibility ? I know Emby clients usually work fine with Jellyfin so I would have expected this to work, but the issue might be something else entirely with my setup.
Thank you

**Comment by miigotu** [comment]
I just tested with https://docs.linuxserver.io/images/docker-jellyfin and it works fine

**Comment by Ulrar** [comment]
Hi,

Are you sure it worked using the notifcation, and not inotify ? Jellyfin uses that by default to monitor changes in the library, and that works fine if the library is local but really it's not being notified by sickchill.

**Comment by miigotu** [comment]
Testing with curl I get the expected response of 204
```bash
~/Docker/jellyfin via 🐍 v3.8.5 (venv)
❯ curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Emby-Token: 2a5d381ec0c74c298c2d3b0ad9716cf7" -X POST -d '{"Path":"/tvshows", "UpdateType":"Created"}' http://localhost:8096/emby/Library/Media/UpdatedHTTP/1.1 204 No Content
Date: Mon, 15 Feb 2021 11:28:41 GMT
Server: Kestrel
Content-Length: 0
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Cookie, Date, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-MediaBrowser-Token, X-Emby-Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
Access-Control-Allow-Origin: localhost:8096

~/Docker/jellyfin via 🐍 v3.8.5 (venv)
❯ curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Emby-Token: 2a5d381ec0c74c298c2d3b0ad9716cf7" -X POST -d '' http://localhost:8096/emby/Library/Refresh
HTTP/1.1 204 No Content
Date: Mon, 15 Feb 2021 11:28:57 GMT
Server: Kestrel
Content-Length: 0
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Cookie, Date, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-MediaBrowser-Token, X-Emby-Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
Access-Control-Allow-Origin: localhost:8096

~/Docker/jellyfin via 🐍 v3.8.5 (venv)
```

**Comment by Ulrar** [comment]
Might be a version thing, are you using Jellyfin 10.6 ?
Here is what I get on 10.7 in the sickchill logs

```
                        2021-02-15 11:56:34 EMBY: Warning: Could not contact Emby at http://10.0.10.18:8096/emby/Library/Media/Updated 400 Client Error: Bad Request for url: http://10.0.10.18:8096/emby/Library/Media/Updated
```

On 10.6 I don't get an error, but nothing happens on the Jellyfin side either.
My paths aren't the same in jellyfin and sickchill, that might be the cause. Radarr/Sonarr have mappings for that, which is handy.

I've fixed my inotify so I don't really need this to work, if it's just a me thing we can probably close this, but given the error above I wonder if the API might be changing in 10.7 ?

**Comment by miigotu** [comment]
The paths is likely the issue. We use the /Library/Refresh and /Library/Media endpoints and the one for a specific show uses the path sc knows.

There is a way to do it with tvdbid, which might be a way for me to fix it.

**Comment by kyuuk** [comment]
i tried a fix for this https://github.com/SickChill/SickChill/pull/7086, but if it's possible to update with tvdbid that would be better
