### ISSUE TITLE
CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version.

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#7017]
### Before submitting your issue:

Branch/Commit: origin/master
OS: windows 10
Browser: chrome x64
What you did: Nothing. I swear!
What happened: Nothing.
What you expected: New version with loads of cool stuff :D
Logs:
```
2021-02-17 06:44:20 WARNING :: CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version. Error: AttributeError("'NoneType' object has no attribute 'major'")
2021-02-17 06:44:20 INFO :: CHECKVERSION :: New update found for SickChill, starting auto-updater ...
```

I did search for a solution, closes I found was how to use git, but I got "fatal: bad config line 1 in file .git/config", so no use continuing with the possible solution in https://github.com/SickChill/SickChill/issues/6534#issuecomment-643940923

![image](https://user-images.githubusercontent.com/17053402/108161851-31800b80-70ec-11eb-84d1-d0e8186574e5.png)

I Here's my SickChill info:
![image](https://user-images.githubusercontent.com/17053402/108161969-6ab87b80-70ec-11eb-98ac-21b18f9a6a27.png)

(clicking the link in the "bad config" gives me a 404 error)

**Comment by miigotu** [comment]
1. Set an environment variable `PYTHONUTF8=1` (unrelated, but will fix foreign characters and your locale in SC)
2. Check the` c:\sickchill\sickchill\.git\config` file, it has been corrupted. It is a normal text file so maybe you can repair it.
Mine is like this:
```bash
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = git@github.com:SickChill/SickChill.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[branch "develop"]
        remote = origin
        merge = refs/heads/develop
```

Note: the url for the remote in there might need to be `https://github.com/SickChill/SickChill.git` for you.
