### ISSUE TITLE
Local branch is ahead of master. Automatic update not possible.

### ISSUE THREAD

**Issue by gabryk91** [SickChill/SickChill#7018]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: windows 10
Browser: chrome
What you did: nothing
What happened: notice appear on the top
What you expected: to do updates
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Back up, get new installer, install, restore.
