### ISSUE TITLE
Sort error on show list

### ISSUE THREAD

**Issue by rd1** [SickChill/SickChill#7019]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Branch: master
Commit: 34112a6279de83bb8671246dbf1b1f942d10915b
Version: v2021.02.17-1
Database Version: 44.5
  Python Version:3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
  SSL Version:OpenSSL 1.1.1g 21 Apr 2020
  OS:Windows-10-10.0.19041-SP0
  Locale:fr_CA.cp1252

Browser: CHROME

What you did: Started Sickchill. Noticed issue, tried reversing the sort order and back.

What happened: it loaded the shows then sorted them wrong in poster mode. reverse sort is good but ascending poster mode all catawampus! And ' Sort with "The", "A", "An" ' is checked but still does it if unchecked. 

What you expected: Sickchill to know the alphabet. see Screenshots.

![Sorting ascending](https://user-images.githubusercontent.com/1567489/108504518-00d2da00-7284-11eb-80c4-2c824ebab555.png)

![Sorting descending](https://user-images.githubusercontent.com/1567489/108504533-06c8bb00-7284-11eb-9933-db2d119cd041.png)

Logs: attached as zip
[Logs.zip](https://github.com/SickChill/SickChill/files/6009958/Logs.zip)

**Comment by ronrosenfeld** [comment]
Possibly related to #5944
