### ISSUE TITLE
Is there a way to find and list all the shows that are in DVD order

### ISSUE THREAD

**Issue by Ventje23** [SickChill/SickChill#7026]
Hi,

Still enjoying this program an dthanks for all the hard work you put in it.

So far I haven't been able to find the answer. But I have several shows that are sorted by DVD order. Now I want to find all the show that are sorted this way.
How can I do this with Sickchill? And if it's not possible yet, is there a way to add this as an option somewhere?

Kind regards

**Comment by miigotu** [comment]
Not sure if you can on the mass edit page?

**Comment by Ventje23** [comment]
No I haven't found it there. Would be a nice feature to have though....
