### ISSUE TITLE
Mass Update Does Nothing When Show Dir Doesn't Exist

### ISSUE THREAD

**Issue by Torhal** [SickChill/SickChill#7027]
The UI and logs both says it's being changed, but when I refresh the show page it hasn't.

```
2021-02-03 00:47:55 INFO :: WEBSERVER-MANAGE_0 :: For show Deadly Recall changing dir from /Volumes/Expansion/TV - REDACTED/Deadly Recall to /Volumes/Expansion/TV - REDACTED - Crime Documentaries/Deadly Recall 
```

So it "thinks" it's doing it, at least. There were actually no files nor a directory to be moved since all episodes had been watched and deleted. I’m guessing SC sees no show directory and, even though the log says otherwise, doesn’t update the root for the show itself.

```
miigotu 02/05/2021
I'm guessing you are right. This is a bug. It should change the root even if the show dir doesn't exist, but I could see how that would be an easy coding mistake to make
```

**Comment by miigotu** [comment]
Have you checked the debug logs, and do you get any errors in the gui notifications popup?
Are there any special characters in the new path?

What I was thinking might be wrong is not wrong, so we need to find out more information.
```python
location = os.path.normpath(xhtml_unescape(location))
            old_location = os.path.normpath(show_obj._location)
            # if we change location clear the db of episodes, change it, write to db, and rescan
            if old_location != location:
                logger.debug(old_location + " != " + location)
                if not (os.path.isdir(location) or settings.CREATE_MISSING_SHOW_DIRS or settings.ADD_SHOWS_WO_DIR):
                    errors.append(_("New location <tt>{location}</tt> does not exist").format(location=location))
                else:
                    # change it
                    try:
                        show_obj.location = location
```

**Comment by Torhal** [comment]
Here's what every log entry (on Debug) shows, though obviously with different dir names:

```
2021-02-24 06:13:14 INFO :: WEBSERVER-MANAGE_0 :: Updating scene exceptions
2021-02-24 06:13:14 DEBUG :: WEBSERVER-MANAGE_0 :: Updating show exceptions
2021-02-24 06:13:14 DEBUG :: WEBSERVER-MANAGE_0 :: 383491: Saving to database: Debris
2021-02-24 06:13:14 DEBUG :: WEBSERVER-MANAGE_0 :: Setter sets location to /Volumes/Vault/Shared/Shows/Debris
2021-02-24 06:13:14 DEBUG :: WEBSERVER-MANAGE_0 :: /Volumes/Expansion/TV Shows/Debris != /Volumes/Vault/Shared/Shows/Debris
2021-02-24 06:13:14 INFO :: WEBSERVER-MANAGE_0 :: For show Debris changing dir from /Volumes/Expansion/TV Shows/Debris to /Volumes/Vault/Shared/Shows/Debris
```

I'm not looking to have SC move the data, just change the show dir in the DB so once new episodes are processed they'll go to the new location.

In many cases there is no show dir because it was auto-deleted by Plex after deleting the last-watched episode of the show. If there is an existing show dir at the destination (because I moved it there ahead of the mass-update attempt) the DB update works as expected.

**Comment by miigotu** [comment]
Thats strange, `Setter sets location to` means its actually changing the location, that is the final debug before it changes.

```python
    def _setLocation(self, newLocation):
        logger.debug(f"Setter sets location to {newLocation}")
        # Don't validate dir if user wants to add shows without creating a dir
        if settings.ADD_SHOWS_WO_DIR or os.path.isdir(newLocation):
            if self._location != newLocation:
                self.dirty = True
            self._location = newLocation
        else:
            raise NoNFOException("Invalid folder for the show!")
```

Do you have the setting `Add shows without directory` enabled in postprocessing config?

**Comment by Torhal** [comment]
I actually do not have that set, since it says ```add shows without creating a directory (not recommended)``` but if that's what's causing this to not work, I'll enable it.

The wording makes it seem that this is just for adding new shows, not for moving their location, and both the UI and logs give no indication of a failure due to not having that set so... :)

**Comment by Torhal** [comment]
UPDATE: Turning that on solved the issue.

**Comment by miigotu** [comment]
I'll add more context to the setting info sometime.
