### ISSUE TITLE
Apache2 Reverse Proxy not working

### ISSUE THREAD

**Issue by blyb2592** [SickChill/SickChill#7028]
Hello,
I tried several configurations for Reverse Proxy in apache2, none work. Is there any way to configure it? 

Current configuration:
```
        <Location /sickchill>
               ProxyPass http://localhost:<port>/sickchill retry=0 timeout=5
               ProxyPassReverse http://localhost:<port>/sickchill
               AuthType Basic
               AuthName "Password Required"
               AuthBasicProvider file
               AuthUserFile <path>/.htpassword
               Require user <user>
               satisfy any
               deny from all
               Require ip <local ip>
        </Location>
```

**Comment by bigwavedave42** [comment]
My working config:
ProxyPass /sickrage https://192.168.1.10:8081/sickrage connectiontimeout=5 timeout=30
ProxyPassReverse /sickrage https://192.168.1.10:8081/sickrage
<Location /sickrage>
  Order allow,deny
  Allow from all
</Location>

192.168.1.10 is actually the local machine, but the route-able IP instead of localhost.  

The main issue of yours might be missing the "/sickrage" for the ProxyPassReverse line.

**Comment by blyb2592** [comment]
Hi,
Tried the config you use, and I'm getting an empty white page with no content.

I had to adjust it to fit my environment, so now I have:
```
#SickChill
              ProxyPass /sickchill http://192.168.1.1:8081/sickchill connectiontimeout=5 timeout=30
              ProxyPassReverse /sickchill http://192.168.1.1:8081/sickchill
        <Location /sickchill>
               Order allow,deny
               Allow from all
               AuthType Basic
               AuthName "Password Required"
               AuthBasicProvider file
               AuthUserFile /www/.htpassword
               Require user <name>
               satisfy any
               deny from all
               Require ip <local ip>
        </Location>
```

I had to remove the s from https, as I use redirection like this in the 000-default.conf file:
```
<VirtualHost *:80>
   RewriteEngine on
   RewriteCond %{HTTPS} !on
   RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
```

**Comment by miigotu** [comment]
You can't pass https to https, disable ssl in SC and just use your reverse proxy for handling https and block the sc port externally.

**Comment by blyb2592** [comment]
I dont understand why this is closed? I do not use https on SickChill side. https is enabled only on apache, so this is not the issue. The config I have is working on SABNzbd, SickBeard and other applications. There I do get an error, but the website is working fine. The issue is only on SickChill.

The error for SickBerd looks like this:
``
[Tue Mar 02 00:37:14.090669 2021] [access_compat:error] [pid 3961] [client <IP>:63421] AH01797: client denied by server configuration: proxy:http://localhost:8181/sickbeard/ui/get_messages/, referer: https://<FQDN>/sickbeard/home/
``

The difference between the error on SicBeard and SickChill is the ``referer: https://<FQDN>/sickbeard/home/`` part.

Could be I have something wrong in the config part that refers to authorization, but I can't figure how to set it properly.

**Comment by miigotu** [comment]
Not knowing how to do something and something being a bug are 2 different things. There is a discussion tab on the repo, use that.

You need to provide auth to SC to access it from outside your network, for one thing.
