### ISSUE TITLE
429 client error for rarbg (torrentapi.org) (possible fix in description ?)

### ISSUE THREAD

**Issue by salimimani** [SickChill/SickChill#7029]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: linux (ReadyNAS OS 6.10.4)
Browser: chrome (but doesn't matter)
What you did: launched a manual search for an episode using rarbg (only one episode, no backlog search running, no daily search running)
What happened: login api call (get_token) fails
What you expected: torrent would download normally
Logs:
```
2021-02-28 02:33:37 INFO :: SEARCHQUEUE-MANUAL-260189 :: [Rarbg] :: Request failed: 429 Client Error:  for url: http://torrentapi.org/pubapi_v2.php?get_token=get_token&format=json&app_id=sickchill (<class 'str'>)
2021-02-28 02:33:37 WARNING :: SEARCHQUEUE-MANUAL-260189 :: [Rarbg] :: Unable to connect to provider
```
Additional info :
It worked a few times this morning, but now it doesn't anymore. Nothing changed between this morning and now.
I added a few debug logs in "login" and "search" functions in rarbg.py to check how many times the api method is called.
==> I noticed it fails on the first try (and it only makes on attempt to call the api, in login function. doesn't even move on to search since login failed). So it doesn't seem to be triggered by flooding the rarbg api.
==> tried that full url in my PC browser. I noticed I get that same error code (429) only when i hit refresh very fast. I get it after approx. 3 refresh hits in one second. But then I wait one second and hit refresh, it works again.
==> i tried calling from my nas directly (curl in command line), in case it was something linked to the caller, by doing this :
for i in `seq 1 30`; do curl "http://torrentapi.org/pubapi_v2.php?get_token=get_token&format=json&app_id=sickchill"; done
==> it doesn't fail even once with curl from the NAS. I always get a token successfully. 30 successful responses.
==> also noticed calling with wget systematically gives a "403 unauthorized" response

Maybe there is some http info or header or anything, that is cached within sickchill that causes the api to always answer with 429 even on the first try ? maybe the response is cached because it's the same query url ? or something else ?

**Ok, just did an additional test right now before finishing this post !
1. restarting sickchill does not fix the problem, still 429
2. Deleting cache.db and cache folder and restarting sickchill fixes the issue !! it instantly starts answering correcly again !**

So there may be a fix in making sure the response is not cached if the url contains get_token and the http code is not 200 ?
Hope that helps

**Comment by miigotu** [comment]
The cached request expires on it's own, based on the etags that rarbg returns. We have to save that request, to respect rarbg and give it a timeout (not flood rarbg)

**Comment by salimimani** [comment]
I agree with the idea, but I'm wondering how long it takes for it to expire, because it's been over 24 hours (I reverted to the previous cache that i had backed up) and it still returns a 429 error. A full day seems a bit long to me ?

**Comment by salimimani** [comment]
Is there a way to manually clear the cached results when it has been too long ? or to fine tune the expiration time limit ? the strange part is that when i get the 429 error for the first time (after 1 or 2 successful torrent grabs), I make sure I wait a few minutes before triggering a manual search for a single episode.
I check the logs and I only see one attempt, instantly resulting in a 429 error code. It's as if there were multiple api calls that don't even appear. Rarbg normally doesn't deny you on the first try, so i'm wondering where the initial 429 comes from. I only see one attempt. Also tried monitoring network traffic, and I notice the first attempt fails, likely with no reason. It looks like I can only grab 1 or 2 torrents per day before being stuck in an infinite 429 "loop" (i say loop but it's not really a loop obviously, it's one manual attempt every 10 minutes or so to test, but it always returns 429)

**Comment by miigotu** [comment]
I use rarbg, and never have had a 429.

**Comment by Lanata07** [comment]
Also facing the same issue

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/issues/7769#issuecomment-1086767751_

**Comment by miigotu** [comment]
Don't put SC behind a VPN, just put your download client behind the VPN.
