### ISSUE TITLE
Fix the Search Strings Please!!

### ISSUE THREAD

**Issue by FabioFranconeri** [SickChill/SickChill#7030]
Branch/Commit:
OS: DSM 6.1
Browser: Chrome

When searching any show the search strings are such that nothing ever gets found.
For instance, searching for show WandaVision episode one produces the following search string:
[WandaVision - 2021 01 15 - Filmed Before a Live Studio Audience]
which clearly fails to find anything!!

How do I make SickChill search for : [WandaVision S01E01] instead?? Without the date or the episode title?!?

The same happens for every other show.

Please help!!

Logs:
INFO :: SEARCHQUEUE-MANUAL-362392 :: Unable to find a download for: [WandaVision - 2021 01 15 - Filmed Before a Live Studio Audience]

**Comment by miigotu** [comment]
That is not the search string. It is the episode information. Enable debug and you will see the actual search strong IS `WandaVision S01E01`.

**Comment by FabioFranconeri** [comment]
thank you miigotu.
I have enabled debug and the search string log now appears as : 
Beginning manual search for: [WandaVision - S01E08 - Previously On]
which still doesn't find anything.. how do I remove the '-' characters and the episode name?
Sorry to bother you with this but I can't find any documentation on how to fix the issue..

**Comment by FabioFranconeri** [comment]
Thank you for the quick reply miigotu.
I have taken a look at the actual search string that gets sent to my Jackett server and it looks like this:
"Torznab search in The Pirate Bay for WandaVision 2021 01 15"

Any idea why that might be the case?
