### ISSUE TITLE
Unable to find series. TVDB API issue?

### ISSUE THREAD

**Issue by swannie-eire** [SickChill/SickChill#7031]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Multiple

Branch: master
Commit: 34112a6279de83bb8671246dbf1b1f942d10915b
Version: v2021.02.17-1
Database Version: 44.2

Install: pip
Version: v2021.02.17-1
Database Version: 44.5

OS: docker container and freebsd jail
Browser: firefox mobile and firefox desktop and chrome
What you did: try to add a new TV show
What happened: got error "No results found, try a different search."
What you expected: it to find series matching the popular string "star trek"
Logs:
```
2021-03-01 20:34:29 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with searchterm(s): ['star trek'] on Indexer: theTVDB
2021-03-01 20:30:15 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with searchterm(s): ['star trek'] on Indexer: theTVDB
2021-03-01 20:30:07 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with searchterm(s): ['Snowfall'] on Indexer: theTVDB
2021-03-01 20:24:10 INFO :: MAIN :: Checking for XEM scene exception updates for theTVDB
```

There is not much info i can get from the logs. It looks like an issue with the Tvdb API.

Im seeing this on 1 docker container and a freebsd jail. I also spun up a clean SC in a docker container and the issue is the same. All these are were on different networks.

**Comment by miigotu** [comment]
https://twitter.com/thetvdb/status/1366428411304939523?s=19

**Comment by JarroVGIT** [comment]
@miigotu the issue persists while the maintenance was completed a couple of hours ago: https://twitter.com/thetvdb/status/1366463255510573058?s=19

**Comment by miigotu** [comment]
Try reading the comments on that latest tvdb twitter post where they asked people to report if they see any issues.

**Comment by swannie-eire** [comment]
> Try reading the comments on that latest tvdb twitter post where they asked people to report if they see any issues.

Thank you i search the TvDB site but didnt find anything. I know to check there twitter in future.

Maybe it would be worthwhile to add some logging about the TvDB responses or call.

e.g timeouts, rate limiting etc..
