### ISSUE TITLE
[APP SUBMITTED]: addExistingShows() missing 2 required positional arguments: 'shows_to_add' and 'promptForSettings'

### ISSUE THREAD

**Issue by divx-guy** [SickChill/SickChill#7032]
### INFO
Python Version: **3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@34112a6279de83bb8671246dbf1b1f942d10915b
Link to Log: https://gist.github.com/5f983001c8479a73156c17aaf9479db9
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Ombouwleusden** [comment]
### INFO
Python Version: **3.7.10 (default, Mar 14 2021, 11:04:23) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
Link to Log: https://gist.github.com/aaddce2179223cd727a334a61f28ae72
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
