### ISSUE TITLE
Feature Request: add subtitle provider legendasdivx.pt

### ISSUE THREAD

**Issue by TiagoDM** [SickChill/SickChill#7034]
Hi,

Would it be possible to add legendasdivx as a subtitle provider in SickChill? Theres a lot of excellent subtitles in portuguese there, normally you can find subs you cant with opensubtitles, so...

The website is https://www.legendasdivx.pt/ and im not sure about the API .... but it would be great!

**Comment by miigotu** [comment]
Asking on subliminal/subliminal would be your best bet
