### ISSUE TITLE
ReadyNas can't update. 

### ISSUE THREAD

**Issue by R0yalblo0d** [SickChill/SickChill#7038]
I install the version from the ReadyNas appstore. I try to run update from the browser gui for SC and it just shuts down and refuses to start up. I can't find any helpful information on this. Can someone direct me or help me?

**Comment by miigotu** [comment]
https://github.com/SickChill/readynas-sickchill/releases/tag/2021.02.04

**Comment by R0yalblo0d** [comment]
Hi. How do i install this build? When I manually upload. Says i can't install. Any guides or suggestions?

**Comment by miigotu** [comment]
ssh I guess, idk. Why does it say it can't install?

**Comment by R0yalblo0d** [comment]
Not sure why. Just refuses to upload this pckg. Through ssh is there a command i run to install this pkg? Sorry i am pretty noob at this

**Comment by R0yalblo0d** [comment]
Here is the log of me trying to install it via SSH

dpkg -i sickchill_2021.02.24_all.deb 
Selecting previously unselected package sickchill.
(Reading database ... 22646 files and directories currently installed.)
Preparing to unpack sickchill_2021.02.24_all.deb ...
/usr/local/bin/python3.6
Unpacking sickchill (2021.02.24) ...
dpkg: dependency problems prevent configuration of sickchill:
 sickchill depends on php5-sqlite; however:
  Package php5-sqlite is not installed.
 sickchill depends on python3 (>= 3.6); however:
  Package python3 is not installed.
 sickchill depends on git; however:
  Package git is not installed.

dpkg: error processing package sickchill (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 sickchill

**Comment by miigotu** [comment]
That is not the new version.

**Comment by miigotu** [comment]
I had the wrong link above, click again

**Comment by miigotu** [comment]
https://github.com/SickChill/readynas-sickchill/releases/tag/2021.03.09

**Comment by R0yalblo0d** [comment]
Thanks that seems to get rid of the python issue. However these dependencies are missing. Any suggestions?

The following packages have unmet dependencies:
 sickchill : Depends: php5-sqlite but it is not going to be installed
             Depends: git but it is not going to be installed

**Comment by R0yalblo0d** [comment]
Seems the directly uploading it to the readynas worked. Was able to update it as well. This can be closed. Thanks!

**Comment by miigotu** [comment]
Yeah, usually after you `dpkg -i` you then need to `apt-get -f install`.
