### ISSUE TITLE
Issue w/ SickChill and Synology Download Station

### ISSUE THREAD

**Issue by jtbreen** [SickChill/SickChill#7039]
Recently had to reinstall DSM on my Diskstation and lost Sickchill and all other packages. Reinstalled and now I'm unable to download torrents via SickChill and it looks like its because brackets "[]" are being converted to "%5B". It causes the download to hang. If I download the exact same torrent directly from the DS Get App, it downloads without issue. If I download from my laptop via the Synology extension it works fine. I was trying to upload a screen grab of the renamed torrent with the bracket issue but was unable to. Hopefully that makes sense. Bizarre issue to say the least! Thanks for the help all.

**Comment by miigotu** [comment]
Is that sent as a magnet link, a file link, or as a whole file? I need the api call info

**Comment by jtbreen** [comment]
> Is that sent as a magnet link, a file link, or as a whole file? I need the api call info

Thanks for the quick reply @miigotu 

I believe its coming as a magnet link. When I see the details of the download the URL is magnet:?xt=xxxxxxxxxxxx

Hopefully thats the info you needed?

**Comment by miigotu** [comment]
What's the whole magnet

**Comment by jtbreen** [comment]
> What's the whole magnet

magnet:?xt=urn:btih:b4c66c6a1fd8a3881de7f41df33c536442de58b8&dn=Shameless.US.S11E07.Two.at.a.Biker.Bar.One.in.the.Lake.1080p.AMZN.WEBRip.DDP5.1.x264-NTb%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2770&tr=udp%3A%2F%2F9.rarbg.to%3A2770

**Comment by miigotu** [comment]
Got it

**Comment by jtbreen** [comment]
> Got it

Awesome. Let me know if you need anything else. Hopefully its an easy fix! \
