### ISSUE TITLE
Timeout for Black Hole backend

### ISSUE THREAD

**Issue by hurricane-dorian** [SickChill/SickChill#7045]
Since there is no error-handling with the black hole backend it would be useful to be able to set a timeout, otherwise SickChill patiently waits for a bride that will never come.

**Comment by miigotu** [comment]
huh? If you want to know if a file was correctly sent to a client, do not use black hole. Connect directly to the client.

**Comment by hurricane-dorian** [comment]
The issue is that the client (https://github.com/piejanssens/premiumizer) doesn't have a function to report back to SickChill that the download failed. The timeout is to blacklist the torrent and try another.

**Comment by miigotu** [comment]
Re-read the first sentence of that comment again
