### ISSUE TITLE
Discord Name and Avatar URL not saving into config and reverting to defaults on restart

### ISSUE THREAD

**Issue by MattTheHuman** [SickChill/SickChill#7047]
So currently, everytime the service restarts, the **DISCORD_NAME** and **DISCORD_AVATAR_URL** will reset back to their defaults.
They are also not being saved into the config.ini when saving.

I tried looking into this a bit, but with this not being my coding language I've struggled a bit.
I tried adding the settings into the start.py but that just stopped the web part from loading (the service would still apparently start).

Its a small thing, but would be nice to fix 👍

**Comment by miigotu** [comment]
Fixed in develop, will merge to master as soon as I get a report back about cloudscraper changes
