### ISSUE TITLE
Cannot Update Synology Package

### ISSUE THREAD

**Issue by tcouey** [SickChill/SickChill#7063]
Branch/Commit: Synology package version 20210329-1.
OS: DSM 6.2.4-25556
Browser: Firefox
What you did: Attempted package update through Package Center
What happened: Received message "Current package version is v2020.09.28-2-1. You cannot roll back to the older version 20210329-1."
What you expected: Version update to 20210329-1.

Logs:
n/a (suspect synology package error)

![Capture](https://user-images.githubusercontent.com/5036697/113209764-294cdd00-920f-11eb-8604-87eceb8dcb6e.PNG)

**Comment by miigotu** [comment]
Back up inside SC, Uninstall the unofficial package, install from the package center.

**Comment by tcouey** [comment]
Sorry about that, I guess I didn't know (or more likely forgot) that I'd installed an unofficial package. I was wondering why the version date formats were different... Thanks.

**Comment by miigotu** [comment]
It was just the package from before we got it into the app store, there were some minor changes. Glad it worked out.

**Comment by imaukabuke** [comment]
The problem I have is I installed the official package via Package Center, then within the SC console, I’ve updated the app.  So I’m not sure why updating within the SC console would break the update from the Package Center.  I assume the updates are both from official channels.

**Comment by miigotu** [comment]
There's only one version in the package center.

**Comment by imaukabuke** [comment]
Within the SC console, I regularly get a notice that “you’re ## commits behind....install?”, I select install and and I assume it auto updates.  This package was installed originally via the App Package Center.  Like you said, It’s the only SC package in there.  Not too worried since a backup, remove, reinstall, restore will work.

**Comment by miigotu** [comment]
I will check if in-app updates work with the official synology package when I get back to my pc
