### ISSUE TITLE
Synology: Sickchill is not loading after restore

### ISSUE THREAD

**Issue by marfapeco** [SickChill/SickChill#7070]
Hello to all,
I start by saying that I am a complete novice. Sickchill won't start after updating it from Synology packaging update. I would like to include the debug loging but Sickchill is not loading and I do not know how to get it. 

I have done the following:

1.- I uninstalled it and reinstalled it from Synology. Result: it started. Then I restored a backup. Result: now it does not load.
2.- I uninstalled it again, downloaded this update:Build= sickchill_noarch-all_20210313-1.spk. I installed it and, perfect, it started. I restored a backup again. Result: again (although the app runs) it doesn't load as before.

What can I do to fix the problem?

Thanks for your help,
Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:SYNOLOGY
Browser: FIREFOX
What you did:Update Sickchill
What happened:not running
What you expected: Run
Logs:
```
PASTE LOGS HERE
```

**Comment by Ackman999** [comment]
i am having the same problem, any ideas?

**Comment by miigotu** [comment]
Check what port is set in the config.ini in your backup, it shoult be web_port=8081
I am going to work on that package some today.

**Comment by miigotu** [comment]
https://github.com/SynoCommunity/spksrc/pull/4538

**Comment by marfapeco** [comment]
Hi,
Thanks to all the ones helping me. It was really good. 
My previous posts and aswers from zyrill were:
Thanks zyrill. I'll try to install from scratch, so. One question: do you know why Synology did not create a shorcut for Sickchill? It did it always before but know I have to open it manually.

Zyrill answer: Check the port set in your SC config and app permissions in control panel for the other issue. Some old backups used different ports than 8081
My new questions now:
Ok. It was helpfull. I could restore it. The problem was the port, I had another one. What I do not know is where I have to chang the port in SC config and how.
And about the shortcut, I have given permissionn to SC in app permissionns but I do not know how to create now the shortcut.
Thanks again zyrill.

**Comment by marfapeco** [comment]
Update: I have gotten to change the port to 8081. Done.
The only one thing I do not know is how to create the shortcut to SC.

**Comment by DVDDLRW** [comment]
I had this problem too. My steps to fix it:

1: Reinstall SC
2: Update SC (commits)
3: On the General Configuration go to tab Interface
4: Scroll to the bottom and look for HTTP port.
5: Change it to the port you have been using. (look into your browsers history for previous port in address bar < No clue if thats the correct naming in english because i'm Dutch)
6: Restart SC
7: Connect via the webbrowser to your old IP + Port (look into your browsers history for previous port in address bar)
8: Restore the back-up you've made.

About the Shortcut, don't know. I've been using an shortcut on my desktop to the website. It's much easier.
Example: http://[your_ip_of_Synology]:[port_you_using]/home/

Hope it helps you!

**Comment by marfapeco** [comment]
Thanks DVDDLRW. 
Now, it is working perfectly.
About the shortcut, now it was automatically created. 
So, all of my problems were fixed.
Thanks to you and to all the community.

**Comment by miigotu** [comment]
This is a nightmare lol, I'm trying to get an xpenology vm set up today to prevent these issues, I also made a PR on synocommunity to force the port

**Comment by DVDDLRW** [comment]
> This is a nightmare lol, I'm trying to get an xpenology vm set up today to prevent these issues, I also made a PR on synocommunity to force the port

Maybe notify users when updating through Synology Package Center they have to look out for the port.
Is it normal that the update changes the port when updating? Maybe you could let that go?

**Comment by MichelRabozee** [comment]
Hello, I have a (maybe) stupid question. I do not have updated yet to the new Python 3 sick chill, but I read everything about the Synology package creation.
Currently, my SickChill runs on port 6114 (I have my reasons for that).
I read a lot of issues pointing to the fact that the port must now be 8081.
Does that mean that I cannot set it to 6114 anymore after migration to the "new" SickChill ?

Thank you !

**Comment by DVDDLRW** [comment]
No problem using your own port. I'm using port 8899.
Just remember you have to start from scratch with SC, as I remember correctly when upgrading to python 3 version. They even advice to start from scratch but you could try to use my steps, maybe it works.

This is the only help I can give you with my current knowledge (no programmer or coder, just a handy IT support guy)

**Comment by miigotu** [comment]
> > This is a nightmare lol, I'm trying to get an xpenology vm set up today to prevent these issues, I also made a PR on synocommunity to force the port
> 
> Maybe notify users when updating through Synology Package Center they have to look out for the port.
> Is it normal that the update changes the port when updating? Maybe you could let that go?

It just because old packages were forced to 8083, and 8081 is our port (8083 belongs to sickbeard)

**Comment by DVDDLRW** [comment]
> > > This is a nightmare lol, I'm trying to get an xpenology vm set up today to prevent these issues, I also made a PR on synocommunity to force the port
> > 
> > 
> > Maybe notify users when updating through Synology Package Center they have to look out for the port.
> > Is it normal that the update changes the port when updating? Maybe you could let that go?
> 
> It just because old packages were forced to 8083, and 8081 is our port (8083 belongs to sickbeard)

Clear! Thanks for the information.

**Comment by jonaspaulo** [comment]
Hi,

On my case a trying to apply the sick chill recent update on synology results in the following error:
[url=https://imgbb.com/][img]https://i.ibb.co/Qfr5j0j/sickchillsynology.png[/img][/url]
[https://i.ibb.co/Qfr5j0j/sickchillsynology.png](url)


Any tips? Usually I just upgrade sickchill via its web interface when the git message appears that I am X commits behind.

Thanks

**Comment by miigotu** [comment]
> Hi,
> 
> On my case a trying to apply the sick chill recent update on synology results in the following error:
> https://i.ibb.co/Qfr5j0j/sickchillsynology.png
> 
> 
> Any tips? Usually I just upgrade sickchill via its web interface when the git message appears that I am X commits behind.
> 
> Thanks

https://github.com/SickChill/SickChill/issues/7063#issuecomment-811505348

**Comment by jonaspaulo** [comment]
Thanks for the tip but I have the official package already. My issue seems to be as with https://github.com/SickChill/SickChill/issues/7063#issuecomment-816784643 . I always update inside the app when the notice X commits behind appear.

**Comment by miigotu** [comment]
Updating inside SC should work fine, but there is a PR open to improve the package.

**Comment by rodsombra** [comment]
Hi guys! 

I have just installed sick chill on a brand new synology using Nyaran’s PR (file sickchill_noarch-all_20210313-1.spk) I could install and setup without problems but synology didn’t create any shortcut for the app. I have to save the address as a bookmark to access, but it would be good to have the shortcut. Can you help me?

**Comment by miigotu** [comment]
> Hi guys! 
> 
> I have just installed sick chill on a brand new synology using Nyaran’s PR (file sickchill_noarch-all_20210313-1.spk) I could install and setup without problems but synology didn’t create any shortcut for the app. I have to save the address as a bookmark to access, but it would be good to have the shortcut. Can you help me?

There is an official package in synocommunity repo, no need to install a package manually.

**Comment by rodsombra** [comment]
> > Hi guys!
> > I have just installed sick chill on a brand new synology using Nyaran’s PR (file sickchill_noarch-all_20210313-1.spk) I could install and setup without problems but synology didn’t create any shortcut for the app. I have to save the address as a bookmark to access, but it would be good to have the shortcut. Can you help me?
> 
> There is an official package in synocommunity repo, no need to install a package manually.

Hi miigotu I have followed the instructions on the installation and configuration guides that there is an link to synology that send us to nyaran pr. Now that I have it installed what should I do? Thanks

**Comment by miigotu** [comment]
Use the package in the package center after you add synocommunity... Don't use the spk.

**Comment by rodsombra** [comment]
Hi miigotu, i have uninstalled the spk and installed Sickchill from
synocommunity.
But didn't create the shortcut on synology... any thoughts?

Thanks
