### ISSUE TITLE
Use trash on Linux

### ISSUE THREAD

**Issue by ErinVoid** [SickChill/SickChill#7071]
Branch/Commit: master (up to date)
OS: x86_64 Linux
Browser: FF 87
What you did: Auto Post Processing and non-Auto
What happened: Files Deleted
What you expected: Files to be sent to trash
Logs:
```
2021-04-03 11:05:24 INFO :: POSTPROCESSOR-AUTO :: Processing /my/folder with !/Name with !.mp4 (None)
2021-04-03 11:05:24 INFO :: POSTPROCESSOR-AUTO :: Processing succeeded for /my/folder with !/Name with !.mp4 (None)
2021-04-03 11:05:24 INFO :: POSTPROCESSOR-AUTO :: File exists and new file is same size, pretending we did something
```
So there may be a bug where files with a "!" in confused Sickchill as the files certainly do not exist but some were processed, others deleted.  

However, what would be amazing is if there is an option that anything Sickchill deletes for whatever reason can be sent to trash.  It would be perfect if the user can select what trash programme is being used and any options to pass to it.

I use "trash-cli" so would simply enter "/usr/bin/trash-put"

**Comment by miigotu** [comment]
You do know that SC is supposed to be its own download folder right? It should not be shared with your personal manual downloads or the downloads generated from another software.

**Comment by ErinVoid** [comment]
It has it's own separate folder. Everything is downloaded manually and SC only used for organising files. SC managed to loose 52 eps when renaming and now just deletes the missing files as per log in OP.

Having trash as an option would be a useful enhancement.

**Comment by miigotu** [comment]
Enable debug and get a proper log of it.

**Comment by miigotu** [comment]
Also, btdubbs, removing shows and rotating logs does use trash on linux if you have TRASH_REMOVE_SHOW or TRASH_ROTATE_LOGS set
