### ISSUE TITLE
/@eaDir : Hidden folder - how to configure generic ignore?

### ISSUE THREAD

**Issue by McMac** [SickChill/SickChill#7072]
I'm using the docker version of SickChill and run it on a Synology. Each directory has a @eaDir created within.

What is the proper way to exclude this from post-processing so I won't get loads of this messages:

```log
2021-04-04 08:53:07 INFO :: POSTPROCESSOR-AUTO :: /downloads/<someshow>/@eaDir : Hidden folder
```

Thinking to use same nomenclature as e.g. .gitignore so within top level I can specify **/@eadir to exclude it within the entire folder structure. 
Or extend/copy setting like file extensions so that I can exclude folders named @eadir.

Picked up from stale #4176 but also root cause for #6974

**Comment by miigotu** [comment]
Proper way is to disable debug.
