### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: '/media/series/Shaman King (2021)/Season 01/Shaman King (2021) - S01E02 - Another Shaman.mkv'

### ISSUE THREAD

**Issue by GeckoOBac** [SickChill/SickChill#7079]
### INFO
Python Version: **3.7.9 (default, Dec 15 2020, 01:20:10) [Clang 10.0.0 (git@github.com:llvm/llvm-project.git llvmorg-10.0.0-0-gd32170dbd**
Operating System: **FreeBSD-11.3-RELEASE-p14-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@4f6fcd742aebc68a75ee7b04c099b0d397cb522d
Link to Log: https://gist.github.com/b1f3735f33d452a41d23716c7e925aeb
### ERROR
```
Unable to move file from /media/downloads/[NetflixJail] Shaman King (2021) - 02 (1080p) [509BEA0A].mkv to /media/series/Shaman King (2021)/Season 01/Shaman King (2021) - S01E02 - Another Shaman.mkv: [Errno 13] Permission denied: '/media/series/Shaman King (2021)/Season 01/Shaman King (2021) - S01E02 - Another Shaman.mkv'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by GeckoOBac** [comment]
A clarification on the issue: the folder and file permissions are set correctly, however it seems Sickchill might have issues when moving files that have parenthesis in the series/season name. I've seen it happen with other series, Last one was "Attack on Titan (The final season)", where the file had parenthesis in the season name.

**Comment by miigotu** [comment]
What's the output of:
```bash
ls -ld /media/downloads
ls -la "/media/downloads/[NetflixJail] Shaman King (2021) - 02 (1080p) [509BEA0A].mkv"
ls -ld "/media/series/Shaman King/Season 01"
ls -la "/media/series/Shaman King (2021)/Season 01/Shaman King (2021) - S01E02 - Another Shaman.mkv"
```

Source permission and directory permissions matter too. File names are properly escaped in SC, parens are not an issue.

**Comment by GeckoOBac** [comment]
drwxr-xr-x  2 media  plex  3 Apr  4 00:07 /mnt/Volume1/series/Shaman King (2021)/Season 01/

downloads is not the problem as all series get put there and most work fine.

I guess the issue might be the group permissions?

**Comment by miigotu** [comment]
Group or even other, because I don't know his:gid and permissions for downloads idk.  Maybe some of shout show folders have different parent dir permissions.

**Comment by GeckoOBac** [comment]
No, user and group are media:plex all over the board. I've now set them to go+w and will attempt to process a similar file again, once I have a valid one.

**Comment by GeckoOBac** [comment]
Confirmed, it seems that group permissions were the problem.
