### ISSUE TITLE
[APP SUBMITTED]: WEBSERVER-ERRORLOGS :: [83e4393] git symbolic-ref -q HEAD returned : 

### ISSUE THREAD

**Issue by kkoutalis** [SickChill/SickChill#7083]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: ****
Commit: SickChill/SickChill@83e43932e0cbbf200472bb1a96f0580cddaf0e4c
Link to Log: https://gist.github.com/9776fff354d0426f507c427eb6f4023a
### ERROR
```
WEBSERVER-ERRORLOGS :: [83e4393] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kkoutalis** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: ****
Commit: SickChill/SickChill@83e43932e0cbbf200472bb1a96f0580cddaf0e4c
Link to Log: https://gist.github.com/7977bb4c01022727e552a485b577e881
### ERROR
```
WEBSERVER-HOME :: [83e4393] git symbolic-ref -q HEAD returned : 
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
SC does not support python 2.7, or cp1252.
