### ISSUE TITLE
Can't add shows since updating.

### ISSUE THREAD

**Issue by nekkidtruth** [SickChill/SickChill#7087]
Recently updated as it was telling me I was a few commits behind. Since I updated I cannot add any shows. It looks like TheTVDB is not functioning or not responding properly. I usually run updates whenever it says I'm behind in commits. Roughly every couple of weeks or so.

Branch/Commit: master
OS: Windows 7
Browser: Chrome
What you did: Tried to add a new show
What happened: Search times out and shows what's in the log
What you expected: The GUI to show the list of shows from the search
Logs:
```
2021-04-13 18:30:50 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with searchterm(s): ['red falcon'] on Indexer: theTVDB
2021-04-13 18:29:57 DEBUG :: CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2021-04-13 18:29:57 DEBUG :: CHECKVERSION :: cur_commit = <removed api for privacy>, newest_commit = <removed api for privacy>, num_commits_behind = 0, num_commits_ahead = 0
2021-04-13 18:29:57 DEBUG :: CHECKVERSION :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2021-04-13 18:29:57 DEBUG :: CHECKVERSION :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in C:\SickChill\SickChill\sickchill
2021-04-13 18:29:57 DEBUG :: CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2021-04-13 18:29:57 DEBUG :: CHECKVERSION :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in C:\SickChill\SickChill\sickchill
2021-04-13 18:29:57 DEBUG :: CHECKVERSION :: git branch --set-upstream-to origin/master : returned successful
2021-04-13 18:29:57 DEBUG :: CHECKVERSION :: Executing git branch --set-upstream-to origin/master with your shell in C:\SickChill\SickChill\sickchill
2021-04-13 18:29:57 DEBUG :: CHECKVERSION :: git fetch origin --prune : returned successful
```

**Comment by miigotu** [comment]
There's no red falcon on thetvdb.
https://www.thetvdb.com/search?query=Red+falcon

**Comment by miigotu** [comment]
Also, cur_commit and newest_commit are not api keys.

**Comment by quickdry** [comment]
I had issues with some shows, as test examples: "Home Economics", "Debris" and "The Falcon and the Winter soldier". It was finding them on the "Add Shows" page, but failed when adding the show. The storage directory is created, but it stayed at the "Loading" phase. Adding them again after a restart and using the "existing" also failed to progress beyond "Loading". I had to delete the show directory and then re-add them, after that they added.

(different issue since these all existed in TVDB, but logging here in case someone encounters this issue in future)

**Comment by nekkidtruth** [comment]
Red falcon was an example. This is happening regardless of the show. It's still downloading episodes fine for my current database of shows, but I can't add any new shows.

**Comment by miigotu** [comment]
Go to the server status page, make note of the cache folder, stop the service, delete cache/mako and cache.db and then restart the service. if that doesn't fix it make sure the cache dir is accessable and has the proper permissions and that you have internet access.

**Comment by nekkidtruth** [comment]
Cache and permissions are working fine. As mentioned already, it was working fine previous to the update I did and it's currently downloading items and procession them just fine. I just can't add a show

Anyway, removed cache.db and the mako directory. Still the same issue.

**Comment by miigotu** [comment]
I understood what you said, and I said that it is not broken in code. Something is messed up locally on your setup.
![Screenshot_20210414-202846.png](https://user-images.githubusercontent.com/390379/114796987-2a7a2000-9d60-11eb-8fc2-e7d27a7890f0.png)

**Comment by nekkidtruth** [comment]
I'm don't necessarily believe it's an issue with the code and could very well be an issue to me locally. I just find it odd that it was fine before updating and now there's an issue.

I uninstalled and reinstalled as well, without removing my data. The issue persists. I'd prefer not to have to start all over from scratch so that's why I came here first. I will say this will be the 4th or 5th time now I've had to start from scratch after an update which is obviously annoying.

Thanks for responding.

**Comment by nydave69** [comment]
I have reinstalled SickChill from scratch..

I can't get shows re-added back in like;
2021-04-20 18:21:43 INFO :: SHOWQUEUE-ADD :: Could not find show with id:43119 on theTVDB, skipping
2021-04-20 18:21:43 INFO :: SHOWQUEUE-ADD :: Starting to add show by ShowDir: O:\series temp\Star Trek Of Gods and Men (2007)

This is not just one show but hundreds..

if you do it manualy one show at a time,  it finds the show in the TVDB,  but you still get the error once you submit it.

**Comment by miigotu** [comment]
> I have reinstalled SickChill from scratch..
> 
> I can't get shows re-added back in like;
> 2021-04-20 18:21:43 INFO :: SHOWQUEUE-ADD :: Could not find show with id:43119 on theTVDB, skipping
> 2021-04-20 18:21:43 INFO :: SHOWQUEUE-ADD :: Starting to add show by ShowDir: O:\series temp\Star Trek Of Gods and Men (2007)
> 
> This is not just one show but hundreds..
> 
> if you do it manualy one show at a time,  it finds the show in the TVDB,  but you still get the error once you submit it.
> 
> 

Your tvshow.nfo/series.xml have the incorrect ids according to that log. "Star Trek of gods and men" is id 81460

**Comment by nydave69** [comment]
OK I see a problem...
Some of my other processes are adding the ID of other databases other then the TVDB since it will stop working shortly..

  <uniqueid default="true" type="tmdb">43119</uniqueid>

added in the NFO..

If I remove the NFO SickChill won't add it as an already existing show..



Just as a reference..  when I install sickchill from scratch and manually add one show at a time,  sometimes I can get ten shows added before I get that mako error trying to list the shows..  Usually it right after a the show is add..

**Comment by miigotu** [comment]
Tvdb isn't going to stop working, it's just going to limit queries and require a personal token.

I can filter the uniqueid though.

**Comment by nydave69** [comment]
I found a lot of shows don't have a TVDB ID..  mainly newer ones
my NFO,s are built using TMM and that includes all the ID's it can scrape.

I'm going to regret this;  
But how do I get the ones loaded that don't have a TVDB ID...     
And I will not do anything anymore with the TVDB sites..

Can you use another ID?

**Comment by miigotu** [comment]
This is an issue with your external nfo manager. Just let SC create them if you really need them or set tvdb as the default id. Show me one of these nfo files.  I know that kodi and plex do not need them anymore.

**Comment by nydave69** [comment]
Plex doesn't unless your adding your own poster, thumbs,  etc..  

[tvshow - Copy.nfo.txt](https://github.com/SickChill/SickChill/files/6392186/tvshow.-.Copy.nfo.txt)
Had to change the extension to txt,  wouldn't let me upload an NFO file here.

**Comment by miigotu** [comment]
You can add your own posters and thumbs and still not need the nfo

**Comment by nekkidtruth** [comment]
An update on my original post:

This was most definitely an issue with TVDB. It lasted at least a few days. Since previously added shows were still being downloaded, I ignored the issue for a week until I could decide what I wanted to do. I randomly tried to add a show again this morning and to my surprise, it worked.
