### ISSUE TITLE
version `OPENSSL_1_1_1' not found

### ISSUE THREAD

**Issue by PauloBarreiros** [SickChill/SickChill#7090]
Hi

I'm having an issue running sickchill on debian 9.
When i try to start the service with "systemctl start sickchill" i get the following error:
```
Job for sickchill.service failed because the control process exited with error code.
See "systemctl status sickchill.service" and "journalctl -xe" for details.
```
I then run "systemctl status sickchill.service" and i got the following error : 
```
● sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2021-04-18 14:36:53 WEST; 6min ago
  Process: 21594 ExecStart=/usr/local/bin/python3.8 /home/utilizador/SickChill/SickChill.py -q --daemon --nolaunch --datadir=/home/utilizador/.config/sickchill (code=e

Apr 18 14:36:53 lisboa python3.8[21594]:     import sickchill.oldbeard.helpers
Apr 18 14:36:53 lisboa python3.8[21594]:   File "/home/utilizador/SickChill/sickchill/oldbeard/helpers.py", line 12, in <module>
Apr 18 14:36:53 lisboa python3.8[21594]:     import ssl
Apr 18 14:36:53 lisboa python3.8[21594]:   File "/usr/local/lib/python3.8/ssl.py", line 98, in <module>
Apr 18 14:36:53 lisboa python3.8[21594]:     import _ssl             # if we can't import it, let the error propagate
Apr 18 14:36:53 lisboa  python3.8[21594]: ImportError: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/local/lib/python
Apr 18 14:36:53 lisboa systemd[1]: sickchill.service: Control process exited, code=exited status=1
Apr 18 14:36:53 lisboa systemd[1]: Failed to start SickChill Daemon.
Apr 18 14:36:53 lisboa systemd[1]: sickchill.service: Unit entered failed state.
Apr 18 14:36:53 lisboa systemd[1]: sickchill.service: Failed with result 'exit-code'.
```
I realize that the error is because of openssl not being 1.1.1... my openssl version is 1.1.01, but whenever i try to update it, it says that it is already the latest version.

Can someone please give me a little help ??

Thanks
Branch/Commit: Release 2021.4.10 / d76229c
OS: Debian 9
Browser: n/a
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
This is not a sickchill issue, it is your system. Try `sudo apt install build-essential openssl libssl-dev && sudo pip3 install --reinstall cryptography pyopenssl`

This looks like you built your own python? I suggest updating to buster and using bundled python3.8 or sticking to 3.7.

**Comment by PauloBarreiros** [comment]
Hi miigotu

Thanks for you answer.
I know it's not a sickchill issue, i was just trying to get some help.
Didn't work... thanks anyway.

**Comment by miigotu** [comment]
Deadsnakes ppa might be of help rather than building it yourself 😉
