### ISSUE TITLE
Addic7ed no longer in the list of Subtitles Pluggins

### ISSUE THREAD

**Issue by LucasAdam** [SickChill/SickChill#7099]
Branch/Commit: v2021.04.10
OS: Synology Docker
Browser:
What you did: 
Go into Subtitles Settings -> Subtitles Plugin
What happened: 
Addic7ed not in the list
What you expected:
Addic7ed in the list

<img width="835" alt="Screenshot 2021-04-23 at 13 58 57" src="https://user-images.githubusercontent.com/9447241/115869856-c67de880-a43e-11eb-9f95-7ed4296082d9.png">

**Comment by chewiiie** [comment]
Same here. Running 2021.04.10 with the docker version from linuxserver.io on an Asustor NAS.

**Comment by Ulrar** [comment]
Hi,

This was closed without an answer.
I hadn't realized it before but addic7ed did indeed disappear at some point, I suspect that's when my instance stopped finding any subtitles, only getting around to it now.

Is there any reason this was taken out ? Sadly it was the only one that kind of worked for me.
Thanks

**Comment by LucasAdam** [comment]
Yeah this is still an issue ... @miigotu 🙏🏼 ?

**Comment by TheQL** [comment]
Yes, this is indeed the case. 2 installations here, one on Synolgoy (plugin available), one on Mac, plugin gone.

**Comment by TheQL** [comment]
I tried to just re-add addic7ed to my config, but this caused a Mako error.

I feel like there are a lot of python packages missing in my Mac environment, for instance subliminal.

**Comment by TheQL** [comment]
Sorry @miigotu for opening a duplicate, but this didn't get any attention nevertheless.

**Comment by miigotu** [comment]
Maybe because it's not a priority? Just maybe there are other issues that are more pressing? Maybe I have 3 kids on different sports teams and this week is opening week for baseball, and also the playoffs for hockey? Maybe this is free software and you should chill?

**Comment by TheQL** [comment]
I'm not saying this needs to fixed asap, but how should anybody know a closed issue where there's no apparent reaction is going to be ever taken care of? I'm totally chill... it is low prio after all.

**Comment by LucasAdam** [comment]
Gotta agree with @TheQL here, this issue has been closed because it didn't get any answer in 3 months, from anyone. This clearly indicates it wasn't gonna get worked on, at least in my eyes.

Now I understand this is free software and everyone has priorities, but then let's at least keep the issue with a low prio

**Comment by miigotu** [comment]
You must be new. Most projects you don't get a reaction in 2 years.

Nevertheless, this isn't going to get a reaction.

**Comment by LucasAdam** [comment]
Lmao @miigotu ! You're also deleting comments you don't like now ? Wtf is wrong with you ? If anyone is new to software dev here it's you. You don't close issues just because you yourself don't have time to look into it. The issue is there ! Fix your software or let other poeple fix it (hello open source) while you go to the baseball games. Thank you

**Comment by miigotu** [comment]
If you look at the history, I didn't close it jackass. And if you want to fix it? Fork it. Now kindly fuck off.
