### ISSUE TITLE
Armv7 support to docker image

### ISSUE THREAD

**Issue by binbashblog** [SickChill/SickChill#7100]
I use the armv7 docker image located at: https://hub.docker.com/r/sickchill/sickchill

The latest image is only for amd64 and arm64. It seems armv7 support has been removed since the release tag 7048

**Comment by miigotu** [comment]
You can use the older docker image and update inside the app, upstream image dropped arm7

**Comment by binbashblog** [comment]
I tried that but nothing happens:

This is what it shows in the info:
Branch:
Commit: eef5379edb71f6554786574f91f65595ab9ec2a6
Version: fatal: No tags can describe 'eef5379edb71f6554786574f91f65595ab9ec2a6'. Try --always, or create some tags.

**Comment by binbashblog** [comment]
Nevermind, switched to a arm64 kernel instead on my raspberry pi k3s cluster!
