### ISSUE TITLE
Available subtitle download problem (Unable to set .episode from episode.episode attribute)

### ISSUE THREAD

**Issue by Pastagazok** [SickChill/SickChill#7102]
Branch/Commit: master
OS: Linux-5.10.17-v7l+-armv7l-with-debian-10.9
Browser: Chrome (Version 90.0.4430.85 (Build officiel) (64 bits))
What you did: Trying to download a subtitle on Addic7ed (wich is available on Addic7ed)
What happened: Subtitle won't download.
What you expected: Subtitle should download.
Logs:

Hi,

I have activated "debug mode" and I get that after trying to download an available subtitle for "The Handmaid's Tale S04E01" (fr) :

2021-04-28 14:29:10 DEBUG :: WEBSERVER-HOME_0 :: 321239: No subtitles downloaded for La Servante écarlate S04E01
2021-04-28 14:29:10 DEBUG :: WEBSERVER-HOME_0 :: No subtitles found for La Servante écarlate S04E01
2021-04-28 14:29:10 DEBUG :: WEBSERVER-HOME_0 :: Could not search in addic7ed provider. Discarding for now
2021-04-28 14:29:10 DEBUG :: WEBSERVER-HOME_0 :: Unable to set .episode from episode.episode attribute
2021-04-28 14:29:09 DEBUG :: WEBSERVER-HOME_0 :: Checking subtitle candidates for La Servante écarlate S04E01 (La_Servante_écarlate.S04E01.1080p.WEB.DL.mkv)

I haven't found anything about this message : "Unable to set .episode from episode.episode attribut", and maybe it's "the" problem. I don't know.

Could you help me, please ?

Thank you.

Guillaume.

**Comment by Pastagazok** [comment]
Hi,
I think the problem is in this code (but I don't know how to resolve it) :
https://github.com/SickChill/SickChill/blob/master/lib3/subliminal/providers/addic7ed.py
Could you help me, please ? :)
Have a nice day.
Guillaume.

**Comment by Pastagazok** [comment]
Is "subliminal" functional with supplier "addic7ed"?
I tried to use it separately, with a separate installation of "subliminal" on my raspberry (with Raspbian), but it doesn’t seem to use it properly.

**Comment by Pastagazok** [comment]
Am I the only one to have this problem ?

**Comment by Pastagazok** [comment]
Hello,
Is "subliminal" functional with supplier "addic7ed" as I asked before ?
Have a nice day.

**Comment by miigotu** [comment]
> Hello,
> Is "subliminal" functional with supplier "addic7ed" as I asked before ?
> Have a nice day.

No, addi7ed provider is broken in subliminal, at the very least it has an indent error.

**Comment by Pastagazok** [comment]
Thank you, Migotu.
