### ISSUE TITLE
Auto update stopped

### ISSUE THREAD

**Issue by BarryDup** [SickChill/SickChill#7106]
My SickChill is running on Win10,
It has been running 100% till a couple of months ago,  then it stopped new upgrades,
Can somebody help me with this please?
How can I manually upgrade without losing the history??

Thanks in advance

**Comment by n2burns** [comment]
I"ve been having a similar problem too for the last few days.
When I try to check for update, I get the warning message, "Unable to contact github, can't check for update"
I am running SIckChill on Linux Mint, Branch: master, Version: v2021.06.16-1

**Comment by miigotu** [comment]
> I"ve been having a similar problem too for the last few days.
> When I try to check for update, I get the warning message, "Unable to contact github, can't check for update"
> I am running SIckChill on Linux Mint, Branch: master, Version: v2021.06.16-1

Try restarting SC first.



> My SickChill is running on Win10,
> It has been running 100% till a couple of months ago, then it stopped new upgrades,
> Can somebody help me with this please?
> How can I manually upgrade without losing the history??
> 
> Thanks in advance

Create a backup from inside SC, copy that zip file somewhere safe, then make sure you have python3.6+ and do a git pull. Im sure someone in one of the many support chats can help.
