### ISSUE TITLE
Not starting after Pip3 update.

### ISSUE THREAD

**Issue by Dohnerd** [SickChill/SickChill#7123]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Qnap Linux
Browser:
What you did: Pip3 install -U sickchill
What happened: It updated and now not starting
What you expected: For it to start :D
Logs:
```
PASTE LOGS HERE
[/share/CACHEDEV1_DATA/.qpkg/SickChill] # ./sickchill.sh start
daemon: NOT active
file (/opt/bin/git): exists
updating 'SickChill' from remote repository: failed!
= ExecuteAndLog()
output: "HEAD is now at 921a727bc Bump qbittorrent-api from 2021.4.19 to 2021.4.20

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'admin@NASGATE.(none)')"
result: [128]
installed git branch: develop
file (/opt/bin/python3): exists
starting daemon: failed!
= ExecuteAndLog()
output: "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/locale
/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/locale
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/SickChill.py", line 17, in <module>
    from sickchill.movies import MovieList
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/movies.py", line 8, in <module>
    from imdb.parser.http.piculet import Path, Rule
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/__init__.py", line 40, in <module>
    from . import (
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/companyParser.py", line 32, in <module>
    from .piculet import Path, Rule, Rules
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: cannot import name 'etree' from 'lxml' (/opt/lib/python3.8/site-packages/lxml/__init__.py)"
./sickchill.sh: line 1187: echo: write error: No space left on device
result: [1]
./sickchill.sh: line 1187: echo: write error: No space left on device
[/share/CACHEDEV1_DATA/.qpkg/SickChill] # df -h
Filesystem                Size      Used Available Use% Mounted on
none                    200.0M    200.0M         0 100% /
devtmpfs                  1.5G      8.0K      1.5G   0% /dev
tmpfs                    64.0M      1.6M     62.4M   2% /tmp
tmpfs                     1.5G     24.0K      1.5G   0% /dev/shm
tmpfs                    16.0M      4.0K     16.0M   0% /share
/dev/md9                509.5M    148.7M    360.8M  29% /mnt/HDA_ROOT
cgroup_root               1.5G         0      1.5G   0% /sys/fs/cgroup
/dev/mapper/cachedev1
                         10.6T      5.3T      5.3T  50% /share/CACHEDEV1_DATA
/dev/md13               371.0M    341.3M     29.7M  92% /mnt/ext
tmpfs                    16.0M     44.0K     16.0M   0% /share/CACHEDEV1_DATA/.samba/lock/msg.lock
tmpfs                    16.0M         0     16.0M   0% /mnt/ext/opt/samba/private/msg.sock
tmpfs                     1.0M         0      1.0M   0% /mnt/rf/nd
tmpfs                    16.0M         0     16.0M   0% /share/NFSv=4
/dev/mapper/cachedev1
                         10.6T      5.3T      5.3T  50% /share/NFSv=4/Multimedia
/dev/mapper/cachedev1
                         10.6T      5.3T      5.3T  50% /share/NFSv=4/Openhab
/dev/mapper/cachedev1
                         10.6T      5.3T      5.3T  50% /share/NFSv=4/Public
/dev/mapper/cachedev1
                         10.6T      5.3T      5.3T  50% /share/NFSv=4/Recordings
[/share/CACHEDEV1_DATA/.qpkg/SickChill] #

**Comment by miigotu** [comment]
`pip3 install -U lxml`
Also, "No space left on device" for your root is bad.

**Comment by OneCDOnly** [comment]
Agree, no space on root is bad. :(

You should reboot to fix that first. 

The launcher text looks like you're using my QPKG available via sherpa. ;)

After rebooting, please try recloning the repo:
```
/etc/init.d/sickchill.sh clean
```
Your settings will be retained.

**Comment by Dohnerd** [comment]
None of the above helped unfortunatly...

@miigotu 
[/share/CACHEDEV1_DATA/.qpkg/SickChill] # pip3 install -U lxml
Requirement already satisfied: lxml in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.8/site-packages (4.6.3)
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
[/share/CACHEDEV1_DATA/.qpkg/SickChill] # 

@OneCDOnly after clean:
[/share/CACHEDEV1_DATA/.qpkg/SickChill] # /etc/init.d/sickchill.sh clean
daemon: NOT active
cleaning local repository: OK
[/share/CACHEDEV1_DATA/.qpkg/SickChill] # ./sickchill.sh start          
daemon: NOT active
file (/opt/bin/git): exists
cloning 'SickChill' from remote repository: OK
installed git branch: develop
file (/opt/bin/python3): exists
starting daemon: failed!
= ExecuteAndLog()
output: "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/locale
/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/locale
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/SickChill.py", line 17, in <module>
    from sickchill.movies import MovieList
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/movies.py", line 8, in <module>
    from imdb.parser.http.piculet import Path, Rule
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/__init__.py", line 40, in <module>
    from . import (
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/companyParser.py", line 32, in <module>
    from .piculet import Path, Rule, Rules
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: cannot import name 'etree' from 'lxml' (/opt/lib/python3.8/site-packages/lxml/__init__.py)"
result: [1]

**Comment by miigotu** [comment]
Did you fix the no space on root? Because lxml installs a c compiled shared object in /use/local/livlb iirc. Uninstall lxml after fixing that, and make sure you have the build depends for lxml

**Comment by miigotu** [comment]
Maybe make sure lxml is not in lib3, it might be not loading correctly

**Comment by Dohnerd** [comment]
> Did you fix the no space on root? Because lxml installs a c compiled shared object in /use/local/livlb iirc. Uninstall lxml after fixing that, and make sure you have the build depends for lxml

jups rebooted and its stopped saying it.... uninstalled and reinstalled lxml, didnt do any difference

**Comment by Dohnerd** [comment]
> Maybe make sure lxml is not in lib3, it might be not loading correctly

its in /share/CACHEDEV1_DATA/lib/lxml

**Comment by OneCDOnly** [comment]
@Dohnerd can you please reinstall your Entware? I can see you're on an older Python 3 version and with the installs you've tried in this topic, suspect you've confused the begeezus out of Entware. ;)
```
sherpa reinstall ew
```
Please note: your SickChill QPKG does not use SickChill installed via `pip`. 😉

**Comment by OneCDOnly** [comment]
Also, just did a quick test after noticing the `requirements.txt` file was recently updated. I haven't added anything new yet, and SickChill still starts fine:
```
[~] # /etc/init.d/sickchill.sh restart
daemon: IS active
daemon PID: 12666
stop daemon with SIGTERM: (no-more than 60 seconds): 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, OK
daemon: NOT active
disable QPKG icon: OK
file (/opt/bin/git): exists
update 'SickChill' from remote repository: OK
current git branch: master
file (/opt/bin/python3): exists
load UI ports from application: OK
start daemon: OK
file (/var/run/SickChill.pid): exists
daemon: IS active
daemon PID: 14496
daemon listening address: 0.0.0.0
check for UI port 7073 response: (no-more than 120 seconds): 2, 4, 6, 8, 10, OK
HTTP port 7073: OK
update QPKG icon with UI ports: OK
enable QPKG icon: OK
```
```
[~] # pip3 list
Package    Version
---------- -------
pip        21.1.1
setuptools 49.2.1
wheel      0.36.2
```
```
[~] # opkg list-installed
ar - 2.34-1
binutils - 2.34-1
ca-bundle - 20210119-1
ca-certificates - 20210119-1
entware-opt - 227000-3
entware-release - 1.0-2
entware-upgrade - 1.0-1
file - 5.40-2
findutils - 4.8.0-1
gcc - 7.4.0-6
git - 2.30.2-1
git-http - 2.30.2-1
grep - 3.6-1a
less - 563-1
libbfd - 2.34-1
libbz2 - 1.0.8-1
libc - 2.27-11
libctf - 2.34-1
libcurl - 7.76.0-2
libdb47 - 4.7.25.4.NC-7
libexpat - 2.2.10-1
libffi - 3.3-2
libgcc - 8.4.0-11
libgdbm - 1.19-1
libiconv-full - 1.16-1
libintl-full - 0.21-2
liblzma - 5.2.5-3
libmagic - 5.40-2
libncurses - 6.2-2
libncursesw - 6.2-2
libopcodes - 2.34-1
libopenssl - 1.1.1k-1
libpcre - 8.44-4
libpthread - 2.27-11
librt - 2.27-11
libsqlite3 - 3330000-2
libssp - 8.4.0-11
libstdcpp - 8.4.0-11
libtirpc - 1.3.1-1
libuuid - 2.36.1-2
locales - 2.27-9
nano - 5.6.1-1
objdump - 2.34-1
opkg - 2021-03-15-5936c4f9-1
python-pip-conf - 0.1-1
python3 - 3.9.4-1
python3-asyncio - 3.9.4-1
python3-base - 3.9.4-1
python3-cgi - 3.9.4-1
python3-cgitb - 3.9.4-1
python3-codecs - 3.9.4-1
python3-ctypes - 3.9.4-1
python3-dbm - 3.9.4-1
python3-decimal - 3.9.4-1
python3-dev - 3.9.4-1
python3-distutils - 3.9.4-1
python3-email - 3.9.4-1
python3-gdbm - 3.9.4-1
python3-lib2to3 - 3.9.4-1
python3-light - 3.9.4-1
python3-logging - 3.9.4-1
python3-lzma - 3.9.4-1
python3-multiprocessing - 3.9.4-1
python3-ncurses - 3.9.4-1
python3-openssl - 3.9.4-1
python3-pip - 20.2.3-1
python3-pkg-resources - 49.2.1-1
python3-pydoc - 3.9.4-1
python3-setuptools - 49.2.1-1
python3-sqlite3 - 3.9.4-1
python3-unittest - 3.9.4-1
python3-urllib - 3.9.4-1
python3-xml - 3.9.4-1
sed - 4.8-3
terminfo - 6.2-2
zlib - 1.2.11-3
zoneinfo-asia - 2021a-1
zoneinfo-europe - 2021a-1
```

**Comment by Dohnerd** [comment]
> @Dohnerd can you please reinstall your Entware? I can see you're on an older Python 3 version and with the various module installs you've tried in this topic, I suspect you've confused the begeezus out of Entware. ;)
> 
> ```
> sherpa reinstall ew
> ```
> 
> **Please note:** your SickChill QPKG does not use SickChill installed via `pip`. 😉

No I know... this install is really starting to creep me out... I uninstalled sickchill and would start a install via pip, but it puts everything into root dir and fills it up so its unable to install a new version. :(

**Comment by miigotu** [comment]
`pip install -t out_dir -U sickchill` will put it wherever you want, but it's better from git instead.

**Comment by Dohnerd** [comment]
> `pip install -t out_dir -U sickchill` will put it wherever you want, but it's better from git instead.

Ye ended up installing it via Sherpa and now its up and running again, I love these updates now and then that takes 5-6 hours of nerding to get working on Qnap :D
