### ISSUE TITLE
PIP install hangs indefinitely

### ISSUE THREAD

**Issue by willemw12** [SickChill/SickChill#7125]
PIP install never finishes.

Arch Linux. Python 3.9.4. Python-pip 20.3.1-1.

Installing the sickchill-git AUR package hangs (removed the --quiet options):

    ==> Starting build()...
    + virtualenv --quiet build
    + build/bin/pip install --isolated --no-warn-script-location --root=build --prefix=. sickchill
    Collecting sickchill
      Using cached sickchill-2021.5.6_1-py3-none-any.whl (14.7 MB)
    ....
      Using cached pytz-2013.7.zip (504 kB)
      Using cached pytz-2013.6.zip (504 kB)
      Using cached pytz-2013b.zip (535 kB)
      Using cached pytz-2012c.zip (520 kB)
    INFO: pip is looking at multiple versions of stevedore to determine which version is compatible with other requirements. This could take a while.
    INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
    INFO: pip is looking at multiple versions of pytz to determine which version is compatible with other requirements. This could take a while.
    INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
    INFO: pip is looking at multiple versions of pysrt to determine which version is compatible with other requirements. This could take a while.
    Collecting pysrt>=1.0.1
      Using cached pysrt-1.1.1.tar.gz (104 kB)
      Using cached pysrt-1.1.0.tar.gz (12 kB)
      Using cached pysrt-1.0.1.tar.gz (11 kB)

It hangs here, but after a long time there is a little bit more output:

    INFO: pip is looking at multiple versions of decorator to determine which version is compatible with other requirements. This could take a while.
    Collecting decorator>=4.0.0
      Using cached decorator-5.0.6-py3-none-any.whl (8.8 kB)
      Using cached decorator-5.0.5-py3-none-any.whl (8.8 kB)
      Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
      Using cached decorator-4.4.1-py2.py3-none-any.whl (9.2 kB)
      Using cached decorator-4.4.0-py2.py3-none-any.whl (8.3 kB)
      Using cached decorator-4.3.2-py2.py3-none-any.whl (9.1 kB)
      Using cached decorator-4.3.1-py2.py3-none-any.whl (8.8 kB)
      Using cached decorator-4.3.0-py2.py3-none-any.whl (9.2 kB)
      Using cached decorator-4.2.1-py2.py3-none-any.whl (9.3 kB)
      Using cached decorator-4.1.2-py2.py3-none-any.whl (9.1 kB)
      Using cached decorator-4.1.1-py2.py3-none-any.whl (9.0 kB)
      Using cached decorator-4.1.0-py2.py3-none-any.whl (9.0 kB)
      Using cached decorator-4.0.11-py2.py3-none-any.whl (8.9 kB)
      Using cached decorator-4.0.10-py2.py3-none-any.whl (9.2 kB)
      Using cached decorator-4.0.9-py2.py3-none-any.whl (22 kB)
      Using cached decorator-4.0.6-py2.py3-none-any.whl (21 kB)
      Using cached decorator-4.0.4-py2.py3-none-any.whl (8.7 kB)
      Using cached decorator-4.0.3-py2.py3-none-any.whl (8.5 kB)
      Using cached decorator-4.0.2-py2.py3-none-any.whl (8.5 kB)
      Using cached decorator-4.0.1-py2.py3-none-any.whl (8.5 kB)
      Using cached decorator-4.0.0-py2.py3-none-any.whl (8.6 kB)

It looks like that maybe the PIP website is rate-limiting network traffic.

Installing manually via PIP also seems to hang or takes a very long time:

    $ pip3 install -U sickchill
    ...
    Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from configobj<6.0.0,>=5.0.6->sickchill) (1.15.0)
    Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from configobj<6.0.0,>=5.0.6->sickchill) (1.15.0)
    Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from configobj<6.0.0,>=5.0.6->sickchill) (1.15.0)
    Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from configobj<6.0.0,>=5.0.6->sickchill) (1.15.0)
    Requirement already satisfied: requests<3.0.0,>=2.25.1 in /usr/lib/python3.9/site-packages (from sickchill) (2.25.1)
    Requirement already satisfied: requests<3.0.0,>=2.25.1 in /usr/lib/python3.9/site-packages (from sickchill) (2.25.1)
    Requirement already satisfied: requests<3.0.0,>=2.25.1 in /usr/lib/python3.9/site-packages (from sickchill) (2.25.1)
    Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from configobj<6.0.0,>=5.0.6->sickchill) (1.15.0)
    Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from configobj<6.0.0,>=5.0.6->sickchill) (1.15.0)
    Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from configobj<6.0.0,>=5.0.6->sickchill) (1.15.0)
    Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from configobj<6.0.0,>=5.0.6->sickchill) (1.15.0)
    ....

There is so much output installing like this, it is hard to tell what the progress is.

**Comment by miigotu** [comment]
Pypi was under attack the past few days, the web site was even down for awhile

**Comment by miigotu** [comment]
That is strange, those are deps for other packages, we dont even require them. I guess I could pin versions

**Comment by miigotu** [comment]
I expected some issues because I moved SC to a new dependancy management, but that one isnt because of me :)  ^

**Comment by miigotu** [comment]
Seems like a pip issue, current pip version is 21.1.1

**Comment by willemw12** [comment]
PIP issue [New resolver takes a very long time to complete](https://github.com/pypa/pip/issues/9187) maybe?

**Comment by miigotu** [comment]
Dropped twilio for now
https://github.com/SickChill/SickChill/commit/d589c2e64bb909eee26d1dfad28c9694de44a250

**Comment by willemw12** [comment]
Now it installs but does not start:

    /opt/sickchill/app/lib/python3.9/site-packages/sickchill/locale
    /opt/sickchill/app/lib/python3.9/site-packages/sickchill/locale
    Traceback (most recent call last):
      File "/opt/sickchill/app/bin/SickChill.py", line 14, in <module>
        import sickchill.start
      File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/__init__.py", line 1, in <module>
        from .show.indexers import indexer, ShowIndexer
      File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
        from .handler import ShowIndexer
      File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
        from sickchill.tv import Show, TVEpisode
      File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/tv.py", line 33, in <module>
        from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles
      File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/oldbeard/notifiers/__init__.py", line 3, in <module>
        from sickchill.oldbeard.notifiers import (
      File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/oldbeard/notifiers/twilio_notify.py", line 3, in <module>
        from twilio.rest import Client, TwilioException
    ModuleNotFoundError: No module named 'twilio'

**Comment by colaholiker** [comment]
for me it is working

**Comment by Ascalony** [comment]
I have the same issue, also on Arch
> Now it installs but does not start:
> 
> ```
> /opt/sickchill/app/lib/python3.9/site-packages/sickchill/locale
> /opt/sickchill/app/lib/python3.9/site-packages/sickchill/locale
> Traceback (most recent call last):
>   File "/opt/sickchill/app/bin/SickChill.py", line 14, in <module>
>     import sickchill.start
>   File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/__init__.py", line 1, in <module>
>     from .show.indexers import indexer, ShowIndexer
>   File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
>     from .handler import ShowIndexer
>   File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
>     from sickchill.tv import Show, TVEpisode
>   File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/tv.py", line 33, in <module>
>     from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles
>   File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/oldbeard/notifiers/__init__.py", line 3, in <module>
>     from sickchill.oldbeard.notifiers import (
>   File "/opt/sickchill/app/lib/python3.9/site-packages/sickchill/oldbeard/notifiers/twilio_notify.py", line 3, in <module>
>     from twilio.rest import Client, TwilioException
> ModuleNotFoundError: No module named 'twilio'
> ```

**Comment by willemw12** [comment]
It starts now without any issues. Thanks.
