### ISSUE TITLE
UNC related path for local mounts

### ISSUE THREAD

**Issue by buccinator** [SickChill/SickChill#7136]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: ubuntu
Browser:
What you did: "Update show in Emby"
What happened: local mount location sent to Windows Emby server
What you expected: Emby to accept refresh request

server 1:
Ubuntu sickchill mount path: /media/emby/E/Video/TV Shows/Show Name
Linux -> Windows mount: /media/emby/E -> \\server2\E$

server 2:
Windows Emby mount path: E:\Video\TV Shows\Show Name
Windows share: \\server2\E$

Emby has an option for the reverse scenario, where the local mounts (mapped drives) have a related UNC path ie. server1 has all the media files and not locally stored on server2

When using "Update show in Emby" on server1 where sickchill is located, it sends the "/media/emby/E/Video/TV Shows/Show Name" path to Emby on server2 which would expect either "E:\Video\TV Shows\Show Name" or "\\server2\E$\Video\TV Shows\Show Name"

I probably could also samba share /media/emby/E/ to be //server1/E and use \\server1\E on server2 as the optional UNC path, but thats going around the world and not an ideal solution.

Is there another way to solve this issue?

Will sickchill introduce an option (like Emby) to have a related UNC path for local mounts for external app usage such as this? Would it be better to associate with Emby via media item id instead and update that way, instead of sending a path?

Logs: N/A
```
PASTE LOGS HERE
```

**Comment by buccinator** [comment]
a discussion about this issue on Emby forums found here

https://emby.media/community/index.php?/topic/97969-embylibrarymediaupdated/

**Comment by miigotu** [comment]
There is an open issue about this already, I plan to use the tvdbid/imdbid to make the call. I just have too much on my plate right now so it might be a few more days.

**Comment by miigotu** [comment]
Of course the recommended way is to also run emby on Linux, or run both on windows. It makes no sense to run 2 separate servers and pass files back and forth over network or virtio. That adds extra overhead that is unnecessary and also makes it difficult to continue seeding. With them both on Linux you use hard links and you can continue to seed your whole library for as long as you want, and then delete the torrent and files whenever you want to quit seeding, without using double the drive space to do so.

**Comment by buccinator** [comment]
> Of course the recommended way is to also run emby on Linux, or run both on windows. It makes no sense to run 2 separate servers and pass files back and forth over network or virtio. That adds extra overhead that is unnecessary and also makes it difficult to continue seeding. With them both on Linux you use hard links and you can continue to seed your whole library for as long as you want, and then delete the torrent and files whenever you want to quit seeding, without using double the drive space to do so.

I'm not sure why you think files arent being passed back and forth at all? 

The torrent downloading service running could be on another server yet again. The files moved (or copied) from the downloader themselves could be stored on NAS, separated from both Emby and sickchill servers. 

Emby may be running lean on a server, setup purely for streaming and hardware transcoding with no other services to bog down its cpu/disk/network usage.

**Comment by miigotu** [comment]
The moving/copying of the files is the overhead. It takes 2x the disk space to keep seeding and time/bandwidth to copy/move files. It's simply inefficient, especially when SC can even run right on the Nas.

**Comment by miigotu** [comment]
SC can and will work with UNC paths directly. Just set them as the show dir.

**Comment by buccinator** [comment]
> The moving/copying of the files is the overhead. It takes 2x the disk space to keep seeding and time/bandwidth to copy/move files. It's simply inefficient, especially when SC can even run right on the Nas.

what does seeding have to do with this? 

SC, if it can run on any NAS, which im sure it couldnt, what happens when you have multiple? run multiple installations of SC on all your NAS boxen? or server acting as NAS? which is to my point anyway, SC wont always be living on the same server as Emby

**Comment by buccinator** [comment]
> SC can and will work with UNC paths directly. Just set them as the show dir.

If you can get linux to accept a UNC path youre a magician. 

i tried entering standard smb://name:pass@server/path or //name:pass@server/ into SC and it just reverts back to /
