### ISSUE TITLE
Unrar on ntfs mount in Ubuntu fails with [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by Nanganator** [SickChill/SickChill#7137]
Branch: master
Commit: d76229cd404a162a707d189302990d8911ffe77e
Version: v2021.04.10-1
OS: Ubuntu Server 20.04
Browser: Any
What you did: Running manual or auto post processing of rar archive to unpack directory located on NFTS Volume
What happened: Postprocessing successfully unpacks the archive into the unpack directory, but still generates the error "Failed to extract the archive name.of.the.archive.rar: [Errno 1] Operation not permitted: '/mnt/unrar/name.of.the.archive/name.of.the.archive.mkv', and does not post process the unpacked file.
Completed download is stored on same NTFS volume. Post Processing in this dir not requiring unrar works fine.
postprocessing to an unpack directory on an ext4 volume works fine.
Manually running unrar application to the NTFS volume works fine
NTFS volume mounted with rw,user,exec,umask=000
Same issue if using a symbolic link or not.
UNRAR 1:5.6.6-2build1 used.

**Comment by miigotu** [comment]
You need unrar-nonfree

**Comment by Nanganator** [comment]
That's the one installed:
Package: unrar
Version: 1:5.6.6-2build1
Priority: optional
Section: multiverse/utils
Source: unrar-nonfree

**Comment by miigotu** [comment]
I will have to make an ntfs partition and test this, all of my partitions are ext4, zfs, xfs, and btrfs

**Comment by miigotu** [comment]
It might be an erroneous log line, and the error is most likely on a chgrp or setting creation date of the file.

**Comment by Nanganator** [comment]
Ended up converting the drive to ext4 and now post processing works properly. Happy to close issue.
