### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: ITV Hub. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by cherjr** [SickChill/SickChill#7148]
### INFO
Python Version: **3.8.8 (default, Feb 19 2021, 18:19:15) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.17-v7l+-armv7l-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@771ea729fdae8606b6d41e3e66bb583323398014
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: ITV Hub. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cadmuslabslex** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@94f56b7e2c86655fc98d93e94be1a75e729d3969
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: ITV Hub. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
