### ISSUE TITLE
Pause button on log view screen does not work.

### ISSUE THREAD

**Issue by fyvekatz** [SickChill/SickChill#7151]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:  27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
OS:  Linux <name_redacted> 3.4.6 #1 SMP Wed Apr 8 05:46:23 CST 2020 x86_64 GNU/Linux
Browser:  Chrome - Version 90.0.4430.212 (Official Build) (x86_64)
What you did: Navigated to the logs page. Selected various log level filters. Tried to pause the autoupdate using the pause button.
What happened: The log continued to update and scroll.
What you expected: Expected that there would be no updates to the log on that page while the pause button was pushed.

The logs are not relevant here.

Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Works here in chrome and brave. Make sure you are allowing JavaScript?
