### ISSUE TITLE
cannot connect to github  Version check disabled

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#7165]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: abe2dd7c69d72f5adf8f2a9130d138eae3d4bedb
OS:  Synology/Docker
Browser: Edge
What you did: restart SC
What happened:  Error message as in the title and log
What you expected: Connect to github and check version
Logs:
```
2021-06-06 07:58:27 INFO :: MAIN :: Starting SickChill [master] using '/data/config.ini'
2021-06-06 07:58:27 INFO :: MAIN :: Forcing web server to port 8081
2021-06-06 07:58:27 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2021-06-06 08:00:27 INFO :: CHECKVERSION :: Request failed: HTTPSConnectionPool(host='sickchill.github.io', port=443): Max retries exceeded with url: /sickchill-news/news.md (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6f80b83090>, 'Connection to sickchill.github.io timed out. (connect timeout=30)')) (<class 'str'>)
```
As a further check, using Putty and SSHing to my NAS, I tried to do a docker/pull
```
root@DS718:~# docker pull sickchill/sickchill
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

FWIW, I have recently updated my GitHub token to their latest style, and it was working previously.

**Comment by ronrosenfeld** [comment]
This morning, after restarting SC, 
 - Version check in SC works OK
 - docker pull sickchill/sickchill does not work => same error response as above

**Comment by miigotu** [comment]
https://sickchill.github.io/sickchill-news/news.md" has nothing to do with checking the version, that's just the logger that checking for new news uses.

What this message means is that your connection to GitHub is interrupted, but it can be ignored.

**Comment by ronrosenfeld** [comment]
Thanks.
Sickchill is working so far as version checking is concerned.
docker pull still returns the same error message (obviously now not a SC problem and unlikely to be a network problem, as nothing else from the NAS is losing a network connection.)
Maybe it's a problem with Synology Docker <sigh>.

I'll have to research more the docker pull issue.   I've read to check the DNS server but it should be using the google servers via my router.
