### ISSUE TITLE
Search seems borked....

### ISSUE THREAD

**Issue by tjenvy** [SickChill/SickChill#7166]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:Master /  abe2dd7c69d72f5adf8f2a9130d138eae3d4bedb
OS: macOS El Capitan 
Browser: Safari
What you did: Searched for show title
What happened: Got 100 results that had nothing to do with it.
What you expected: to see shows with the same title or containing the same keywords
Logs:
```
Literally nothing in logs from before searching and after searching. 

2021-06-07 22:24:32 INFO :: POSTPROCESSOR :: Auto post processing task for /Volumes/Media RAID/completed was added to the queue 2021-06-07 22:19:32 INFO :: CHECKVERSION :: Checking for updates using SOURCE 2021-06-07 22:19:32 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/


```

<img width="1566" alt="Screen Shot 2021-06-07 at 10 26 18 PM" src="https://user-images.githubusercontent.com/11091359/121113078-6c16cc80-c7df-11eb-8484-36f78fa48527.png">

**Comment by tjenvy** [comment]
Not sure when this stopped working correctly as I have not aded a show in a while.  I updated to make sure and still same results.

**Comment by miigotu** [comment]
This is simply what they do returns, it isn't our code.

**Comment by tjenvy** [comment]
Well in thats the case, I guess does anyone have insight on what/how it changed?  Is there anything that can be done to limit the results?  I tested a quick medusa install and there is a limiter switch to "exact string". Maybe it could be implemented?  So instead of an issue, feature request?  LOL.

**Comment by miigotu** [comment]
I've made some tweaks in develop branch to filter out some of the junk, but even then they don't always return the same data smh. Can't wait to get everything don't I'm working on so I can remove tvdb entirely smh.
