### ISSUE TITLE
Sickchill package not starting on Synology after ed50be8

### ISSUE THREAD

**Issue by PluX-0** [SickChill/SickChill#7180]
The latest sickchill was plugging away nicely on my synology nas untill 14 hours ago when it installed commit ed50be8a.

 The sickchill syno package did not auto restart after installing the update and when trying to start manually it states "Failed to run the package service". 

I have tried the workaround in #7177 by editing parser.py and removing the ': TVShow' bit, but still synology fails to run.

Branch/Commit: 20210329-1
OS: Synology DSM 6.2.3-25426 update 2 
Browser: chrome/opera/adblock
What you did: let sickchill auto update to commit ed50be8
What happened: sickchill 'Failed to run the package service' after that.
What you expected: for sickchill to start
Logs: cant start sickchill to get to the logs and not sure where to find them from the CLI

```
PASTE LOGS HERE
```

**Comment by turkeylegs1** [comment]
he's not the only one -- I'm right here - been spending about 6 hours on it. Banging my head against a wall.

**Comment by Wismerhull** [comment]
Same here, getting a "Failed to run the package service"

**Comment by turkeylegs1** [comment]
I was thinking of checking for an update with a git pull, but I REALLY don't want to do that unless others have confidently done it with no problems.

**Comment by fadern** [comment]
`Thu Jun 17 12:30:58 CEST 2021
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --$
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/share/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/tv.py", line 19, in <module>
    import sickchill.oldbeard.providers
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/providers/__init__.py", line 6, in <module>
    from sickchill.oldbeard.providers import (
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/providers/abnormal.py", line 8, in <module>
    from sickchill.oldbeard import tvcache
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/tvcache.py", line 10, in <module>
    from . import db, show_name_helpers
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/show_name_helpers.py", line 10, in <module>
    from .name_parser.parser import InvalidNameException, InvalidShowException, NameParser
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/name_parser/parser.py", line 23, in <module>
    class NameParser(object):
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/name_parser/parser.py", line 28, in NameParser
    def __init__(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):
NameError: name 'TVShow' is not defined`

**Comment by BKSteve** [comment]
The work around #7177 didn't work for me, or I don't know where or how to do the restart or where / how to 'git pull'

**Comment by PluX-0** [comment]
I think i have managed to break it even further.

Doing a bit of digging i found some incorrect permissions were set on the data directory and the config.ini file within.

Sickchill start log showed:
_Thu Jun 17 11:28:36 CEST 2021
Starting sickchill command /volume2/@appstore/sickchill/env/bin/python3 /volume2/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume2/@appstore/sickchill/var/sickchill.pid --config /volume2/@appstore/sickchill/var/data/config.ini --datadir /volume2/@appstore/sickchill/var/data
/volume2/@appstore/sickchill/share/SickChill/sickchill/locale
/volume2/@appstore/sickchill/share/SickChill/sickchill/locale
/volume2/@appstore/sickchill/share/SickChill/sickchill/locale
Data directory must be writeable: /volume2/@appstore/sickchill/var/data
(... or:)
Config file must be writeable: /volume2/@appstore/sickchill/var/data/config.ini_

Tye following permissions were set on the directory and file:
_drwxr-xr-x 1 root         root            20 Jun 17 10:29 data
-rw-r--r-- 1 root root 151 Jun 17 10:29 config.ini_

So to fix this i tried:
_/volume2/@appstore/sickchill/var$ sudo chown sc-sickchill data

/volume2/@appstore/sickchill/var$ sudo chgrp sickchill data

/volume2/@appstore/sickchill/var$ sudo chmod sickchill data

/volume2/@appstore/sickchill/var$ cd data

/volume2/@appstore/sickchill/var/data$ sudo chown sc-sickchill config.ini

/volume2/@appstore/sickchill/var/data$ sudo chgrp sickchill config.ini_

And now sickchill will start again but not on port 8899 as expected but on port 8081.

**Comment by BKSteve** [comment]
All my .db file are 666  the .v44 is 644

**Comment by PluX-0** [comment]
Those files in volume2/@appstore/sickchill/var/data$ were auto generated after the first run after changing permissions on the data folder and config.ini. the actual db files are one branch up in volume2/@appstore/sickchill/var/ as far as i can tell

**Comment by BKSteve** [comment]
drwxrwxrwx 1 sc-sickchill sickchill      26 Jun 17 18:20 Logs
drwxrwxrwx 1 sc-sickchill sickchill      74 Jun 17 19:11 cache
drwxrwxrwx 1 sc-sickchill sickchill       0 Jun 17 18:21 cache-20210617_182114
-rw-rw-rw- 1 sc-sickchill sickchill  836608 Jun 17 18:47 cache.db
-rw-r--r-- 1 sc-sickchill sickchill  299008 Jun 17 18:20 cache.db.bak-20210617_182113
-rw-rw-rw- 1 sc-sickchill sickchill   36209 Jun 17 19:10 config.ini
-rw-r--r-- 1 sc-sickchill sickchill   28229 Jun 17 18:20 config.ini.bak-20210617_182113
-rw-rw-rw- 1 sc-sickchill sickchill   45056 Jun 17 18:32 failed.db
-rw-r--r-- 1 sc-sickchill sickchill   16384 Jun 17 18:20 failed.db.bak-20210617_182113
-rw-rw-rw- 1 sc-sickchill sickchill 6621184 Jun 17 19:10 sickchill.db
-rw-r--r-- 1 sc-sickchill sickchill   81920 Jun 17 18:20 sickchill.db.bak-20210617_182113
-rw-r--r-- 1 sc-sickchill sickchill   81920 Jun 17 18:20 sickchill.db.v44

**Comment by BKSteve** [comment]
After failing on the last develop update I uninstalled, reinstalled, restored my backup from 10 days ago.
Since restoring my backup I haven't updated I'm now 26 commits behind. (1 more update since 2 hours ago)

**Comment by PluX-0** [comment]
Hnm if those .db files belong in the data directory and not the upper var directory i may have worked around some holdover old settings or something at some point because my populated db files seem to be in the wrong place

**Comment by BKSteve** [comment]
/volume1/@appstore/sickchill/var$ ls -l
total 36
drwxr-xr-x 1 sc-sickchill sickchill   408 Jun 17 19:10 data
-rw-r--r-- 1 sc-sickchill sickchill   529 Jun 17 18:20 sickchill.log
-rw-r--r-- 1 sc-sickchill sickchill     5 Jun 17 19:11 sickchill.pid
-rw-r--r-- 1 sc-sickchill sickchill 26647 Jun 17 18:20 sickchill_install.log

**Comment by PluX-0** [comment]
Why that sure is curious :D. I have reinstalled the whole deal in january this year and kept it up to date the whole time.

**Comment by BKSteve** [comment]
Is SC running for you yet?
I used my old backup (only 10 days) and haven't updated yet. I will make a new backup before updating. So I'm effectively master after reinstall but with 26 differences to develop.
If you wanted to go clean make sure you have tvshow.nfo files for all shows you want back in SC then it's easier to rebuild when you do add existing shows.
You can also manual backup then restore manually 
[(https://github.com/SickChill/SickChill/wiki/FAQ%27s-and-Fixes#how-to-switch-to-the-new-repo)]

> make a backup from within SickChill, or manually backup config.ini & sickbeard.db

**Comment by scorpinus** [comment]
Confirming I have the same issue on my Synology. Same log output as fadern.

**Comment by zerosaber071** [comment]
Fix worked me!

I had to stop sickchill then start it up again using sudo python3 /opt/sickchill/Sickchill.py

**Comment by BKSteve** [comment]
> 
> 
> Fix worked me!
> 
> I had to stop sickchill then start it up again using sudo python3 /opt/sickchill/Sickchill.py

Did you do this on a Synology DSM? If so some more details on folder done in etc please.

**Comment by zerosaber071** [comment]
> > Fix worked me!
> > I had to stop sickchill then start it up again using sudo python3 /opt/sickchill/Sickchill.py
> 
> Did you do this on a Synology DSM? If so some more details on folder done in etc please.

Sorry, I should've specified that I did this in Ubuntu

**Comment by PluX-0** [comment]
Its still broken here. I have cloned the sickchill dir so i think im going to do a fresh install and cram my db and config files into it.

**Comment by fadern** [comment]
Im running sickchill on Synology DSM 6.
ive followed the #7177 and it worked.

1. go to /volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/name_parser
2. edit parser.py like this post. https://github.com/SickChill/SickChill/issues/7177#issuecomment-862803831
3. start sickchill from webgui.

**Comment by scorpinus** [comment]
Yeah what fadern posted also worked for me on Synology DSM 6.

**Comment by BKSteve** [comment]
1 and 2 - done.
3 doesn't start.
I'm on DSM 6.2.4 and sichchill won't start from package center (webgui)

**Comment by scorpinus** [comment]
@BKSteve what does your logfile say? I kept editing the wrong parser.py file :) apparently there are more then one in that sickchill folder :)

**Comment by BKSteve** [comment]
I edited the parser.py in /volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/name_parser/
or 
https://github.com/SickChill/SickChill/blob/develop/sickchill/oldbeard/name_parser/parser.py
lines checked. 
28 was changed in https://github.com/SickChill/SickChill/commit/4b2802e1b4cf06e239163151c14c9b2c88f6bb83 to 29
so i only changed the other line.
from self.showObj: TVShow = showObj
to     self.showObj = showObj

The SC log /volume1/@appstore/sickchill/var/sickchill.log last line shows this.
```
  File "/volume1/@appstore/sickchill/share/SickChill/lib3/nacl/bindings/crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named 'nacl._sodium'
```

**Comment by BKSteve** [comment]
So one more question are you using master or develop? I would guess master as,
The parser.py change was propagated to both streams but nacl only exists in develop.

So looks like an issue with develop.

**Comment by scorpinus** [comment]
Yeah i'm on master

**Comment by BKSteve** [comment]
Looks like i'm reinstalling, restoring, switch to master before updating.

**Comment by BKSteve** [comment]
Reinstalled, restored, restarted, switched from develop back to master, restarted, updated, no need to edit any files and running.
Issue is obviously with 'nacl._sodium' in develop branch.

**Comment by PluX-0** [comment]
Okay, so since my install was appearantly off when the breaking update hit, and the synology pkg updater may have dumped a wrong version on top of that i will have to roll back to my last backup from january 8 :/.

I did clone my broken sickchill dir and my db files seemed untouched and still populated with all my data.

When i roll back to jan 8, which files to i have to overwrite to get all my data and settings back? Is it just the sickchill.db or is there any show or setting info stored in other files?

**Comment by PluX-0** [comment]
Allright i fixed it, even with my messy install with db and config files all over the place. 

- first i cloned sickchills entire dir to /tmp
- then i manually reverted to an old backup as to get it running again
- then i dug up the backup from the cloned dir in sickchills backup directory that was made while installing the broken update on the 16th and restored that from within sickchill
- when starting sickchill it went straight for the corrected update and seems to be operating normally again with all my settings and tweaks.

Even if it makes me feel incompetent at times when the thing blows up and i have to do some digging to get it up again, i still love sickchill for keeping me on my toes :)

**Comment by BKSteve** [comment]
Port numbers are always interesting - SickBeard custom (early days) used 8083, whilst in SickRage on DSM it became 8899, now under SickChill py3 it's 8081.
The port number is in the config.ini > web_port = 8081 or settings webinterface 
So if you restore from an older version just edit the config.ini in the zip before restore or just log in with the other port and change it to whatever you want. 8081 in DSM is the one set by the package and linked with the package icon.

**Comment by miigotu** [comment]
sodium issue will be fixed as soon as #7187 is finished.

**Comment by miigotu** [comment]
Try the develop branch

**Comment by Meertman** [comment]
@miigotu, sorry for asking, but how do I use the develop branch? I've had the same problem that after an update sickchill is no longer working on my Synology NAS (and for some reason, it always automatically updates :( )

I've looked in all my log files, but I can't see anything wrong... it just does not seem to start after updating to the latest version...

**Comment by BKSteve** [comment]
See #7316 it has the most up to date info on Syno NAS reinstall using 20210329 SynoComm package and then getting to 2021.7.23-1

**Comment by Meertman** [comment]
@BKSteve , thanks, will look into that one now as well, as that seems exactly like my issue :)
