### ISSUE TITLE
SEARCHQUEUE-DAILY-SEARCH / Dailysearcher doesn't seem to be running correctly

### ISSUE THREAD

**Issue by Yoshi900** [SickChill/SickChill#7186]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: v2021.06.16-1
OS: windows
Browser: chrome
What you did: did a manual search
What happened: found an episode to download
What you expected: the "searchqueue-daily-search" to find the episode. e.g. why did it not find it doing the auto search 

below is the logs. I was seeing that a show wasn't downloaded (it was wanted and had been released yesterday (21 hours ago)) so I did a manual search after the auto search could not find anything. The manual search found the ep right away.
The Auto search is setup to search every 10 minutes. 

![image](https://user-images.githubusercontent.com/12824013/122627368-40a2b480-d0f2-11eb-934e-12d3cbccc7e6.png)
as you can see this was released  21 hours ago

![image](https://user-images.githubusercontent.com/12824013/122627407-7b0c5180-d0f2-11eb-9050-df7a45f4e2c2.png)

**Comment by miigotu** [comment]
Daily search is not a string search. It parses rss/latest/top torrents from a provider's feed. Problem is, they set a very high etag for the rss, so likely this torrent falls off the latest torrents by the time the request cache expires and allows another request.

Manual search uses backlog, which is a string search like in a search engine, and will always find what is available.
You have two options, add an rss feed to SC from your ipt user profile, or use a better provider that doesnt hate its users.
