### ISSUE TITLE
[APP SUBMITTED]: theTVDB timed out, unable to create the episode

### ISSUE THREAD

**Issue by turkeylegs1** [SickChill/SickChill#7204]
### INFO
Python Version: **3.7.10 (default, Mar 14 2021, 11:04:23) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
Link to Log: https://gist.github.com/2aa42c5fa2834d0c502cd13eb281f2b6
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by freeextreme** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@46a7f2a2304d6abbc6459820f88d830c57e89bcb
No Log available with ERRORS:
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by midnightx12** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hubdows** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.2.20
No Log available with ERRORS:
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by nydave69** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.2.20
No Log available with ERRORS:
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.2.20
Link to Log: https://gist.github.com/2595d854a054922a1fa8f5086960c282
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by midnightx12** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2023.1.2**
No Log available with ERRORS:
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by bluezed** [comment]
### INFO
Python Version: **3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]**
Operating System: **Linux-5.4.0-148-generic-x86_64-with-glibc2.29**
Locale: UTF-8
Version: **2023.1.2**
Link to Log: https://gist.github.com/bluezed/3b3d99a492163f49542fc6f5a3775642
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by autronix** [comment]
### INFO
Python Version: **3.10.10 (main, Feb 28 2023, 12:54:52) [GCC 8.5.0]**
Operating System: **Linux-3.10.108-x86_64-with-glibc2.26**
Locale: None
Version: **2023.1.2**
No Log available with ERRORS:
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by midnightx12** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2023.1.2**
No Log available with ERRORS:
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by dd30fragbait** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2023.1.2**
No Log available with ERRORS:
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.10.11 (main, May 13 2023, 17:53:56) [GCC 8.5.0]**
Operating System: **Linux-4.4.180+-aarch64-with-glibc2.26**
Locale: None
Version: **2023.1.2**
No Log available with ERRORS:
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by offbyone** [comment]
### INFO
Python Version: **3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]**
Operating System: **Linux-5.10.103-v7l+-armv7l-with-glibc2.36**
Locale: UTF-8
Version: **2023.6.27**
Link to Log: https://gist.github.com/offbyone/5dbe3ebc422dda8145a2891514be0494
### ERROR
```
theTVDB timed out, unable to create the episode
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
