### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by turkeylegs1** [SickChill/SickChill#7206]
### INFO
Python Version: **3.7.10 (default, Mar 14 2021, 11:04:23) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cherjr** [comment]
### INFO
Python Version: **3.8.8 (default, Feb 19 2021, 18:19:15) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.17-v7l+-armv7l-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kretzu77** [comment]
### INFO
Python Version: **3.7.10 (default, Mar 14 2021, 11:04:23) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by swhgraham** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 14 2019, 20:00:08) [GCC 4.9.2]**
Operating System: **Linux-4.4.218.x86_64.1-x86_64-with-debian-8.11**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@fd546a06e190fa2de993e9197891de2a79f31f70
No Log available with ERRORS:
### ERROR
```
WEBSERVER-HOME :: Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by turkeylegs1** [comment]
### INFO
Python Version: **3.7.10 (default, Mar 14 2021, 11:04:23) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by MahtavaDraig** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@bfc6fdb9347d326da6c3f26f8653eeaf9e2d18c6
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DravenSA** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by tommyv** [comment]
### INFO
Python Version: **3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]**
Operating System: **Linux-5.4.124-1-pve-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Sickchilldavid** [comment]
### INFO
Python Version: **3.7.10 (default, Mar 14 2021, 11:04:23) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by toxicneo** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@cc6b290153a4734cee277fa0e4cf636328a06b01
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e1e91c3ec3c90479b556e7e78b48dc3bb81ead01
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by zobe123** [comment]
### INFO
Python Version: **3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]**
Operating System: **Linux-4.15.0-147-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@e493682cb01d790f1fe25188d1aa0794d79717c5
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BabaIsYou** [comment]
### INFO
Python Version: **3.7.10 (default, Mar 14 2021, 10:13:48) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by edwinroos** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by identd113** [comment]
### INFO
Python Version: **3.9.6 (default, Jun 29 2021, 06:20:32) [Clang 12.0.0 (clang-1200.0.32.29)]**
Operating System: **macOS-10.15.7-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@794f94bdbe8b3d4c871ea4d6184a945f4354d35a
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DravenSA** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@1807f4d919f2b887b9b41db3ed10ab1acb1c7f02
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chris41g** [comment]
### INFO
Python Version: **3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]**
Operating System: **Linux-5.11.0-25-generic-x86_64-with-glibc2.33**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by glancy** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.28-Unraid-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@0306ded8f236585531276bc4cc1db9303f26bfce
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hubdows** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Hisha** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by nncrypted** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.4.124-1-pve-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mesa57** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-4.9.103-odroidxu4-armv7l-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@99336df163c7e776c7931d864e84d1f0f83afe4d
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by NilsNojje** [comment]
### INFO
Python Version: **3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]**
Operating System: **Linux-5.4.0-80-generic-x86_64-with-glibc2.29**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by turkeylegs1** [comment]
I'm guessing that this is a known issue still?
i keep getting emails for it, but i wanted to ask what  / how we can get this resolved or ignore it?

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cadmuslabslex** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cherjr** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.32-1-osmc-aarch64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by turkeylegs1** [comment]
### INFO
Python Version: **3.8.6 (default, Jan  4 2021, 16:11:49) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by turkeylegs1** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-4.4.180+-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22463-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by st3rv1s** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by tiny1mil** [comment]
### INFO
Python Version: **3.9.7 (default, Sep 24 2021, 09:43:00) [GCC 10.3.0]**
Operating System: **Linux-5.10.0-8-amd64-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@46455f17ef5e14a3b2581a522081cf1c33f4a0d8
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by stevezebrowski** [comment]
### INFO
Python Version: **3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]**
Operating System: **Linux-4.15.0-161-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@46455f17ef5e14a3b2581a522081cf1c33f4a0d8
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by RakeZim** [comment]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-17-amd64-x86_64-with-debian-10.10**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@94f56b7e2c86655fc98d93e94be1a75e729d3969
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cdjazman** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: ****
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
