### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Oprah Winfrey Network. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by turkeylegs1** [SickChill/SickChill#7207]
### INFO
Python Version: **3.7.10 (default, Mar 14 2021, 11:04:23) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Oprah Winfrey Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chris41g** [comment]
### INFO
Python Version: **3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]**
Operating System: **Linux-5.11.0-25-generic-x86_64-with-glibc2.33**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Oprah Winfrey Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hubdows** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Oprah Winfrey Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LordDeimos666** [comment]
### INFO
Python Version: **3.7.11 (default, Jun 29 2021, 20:40:03) [GCC 8.3.0]**
Operating System: **Linux-3.10.105-x86_64-with-debian-10.10**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Oprah Winfrey Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by tiny1mil** [comment]
### INFO
Python Version: **3.9.7 (default, Sep 24 2021, 09:43:00) [GCC 10.3.0]**
Operating System: **Linux-5.10.0-8-amd64-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@46455f17ef5e14a3b2581a522081cf1c33f4a0d8
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Oprah Winfrey Network. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
