### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: City. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by divx-guy** [SickChill/SickChill#7211]
### INFO
Python Version: **3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: City. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cherjr** [comment]
### INFO
Python Version: **3.8.8 (default, Feb 19 2021, 18:19:15) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.17-v7l+-armv7l-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: City. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: City. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by glancy** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.28-Unraid-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@0306ded8f236585531276bc4cc1db9303f26bfce
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: City. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mesa57** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-4.9.103-odroidxu4-armv7l-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@99336df163c7e776c7931d864e84d1f0f83afe4d
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: City. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cadmuslabslex** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: City. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cherjr** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.32-1-osmc-aarch64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: City. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22463-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: City. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by tiny1mil** [comment]
### INFO
Python Version: **3.9.7 (default, Sep 24 2021, 09:43:00) [GCC 10.3.0]**
Operating System: **Linux-5.10.0-8-amd64-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@46455f17ef5e14a3b2581a522081cf1c33f4a0d8
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: City. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
