### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by divx-guy** [SickChill/SickChill#7212]
### INFO
Python Version: **3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by RakeZim** [comment]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-17-amd64-x86_64-with-debian-10.10**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@94f56b7e2c86655fc98d93e94be1a75e729d3969
Link to Log: https://gist.github.com/06a165af93778c10576a7ff24e6651e5
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DravenSA** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by divx-guy** [comment]
### INFO
Python Version: **3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Sickchilldavid** [comment]
### INFO
Python Version: **3.7.10 (default, Mar 14 2021, 11:04:23) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e1e91c3ec3c90479b556e7e78b48dc3bb81ead01
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by DravenSA** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@1807f4d919f2b887b9b41db3ed10ab1acb1c7f02
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chris41g** [comment]
### INFO
Python Version: **3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]**
Operating System: **Linux-5.11.0-25-generic-x86_64-with-glibc2.33**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hubdows** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by RakeZim** [comment]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-17-amd64-x86_64-with-debian-10.10**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@94f56b7e2c86655fc98d93e94be1a75e729d3969
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: History (CA). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
