### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by itsme9x** [SickChill/SickChill#7215]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
how do we fix this then?

The tvdb page of this serie is: https://www.thetvdb.com/series/het-a-woord
Under network there is listed: NPO1, wich is a valid network.

But in sickbeard it is still listed as Nederlands Publieke Omroep 1, so the fault is in sickbeard not the TVDB.

**Comment by miigotu** [comment]
Also, if you update the show it should get "NPO 1" as the network for that show, and "NPO  1" IS in network timezones.

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19042-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@7f07d61b0a8fb34a9d14748829aacd9f9cf90220
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Nederlandse Publieke Omroep 1. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
