### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by cherjr** [SickChill/SickChill#7218]
### INFO
Python Version: **3.8.8 (default, Feb 19 2021, 18:19:15) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.17-v7l+-armv7l-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by swhgraham** [comment]
### INFO
Python Version: **2.7.9 (default, Sep 14 2019, 20:00:08) [GCC 4.9.2]**
Operating System: **Linux-4.4.218.x86_64.1-x86_64-with-debian-8.11**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@fd546a06e190fa2de993e9197891de2a79f31f70
No Log available with ERRORS:
### ERROR
```
WEBSERVER-HOME :: Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e1e91c3ec3c90479b556e7e78b48dc3bb81ead01
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@1807f4d919f2b887b9b41db3ed10ab1acb1c7f02
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by juancitotrucupe** [comment]
### INFO
Python Version: **3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]**
Operating System: **Linux-5.4.0-66-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by glancy** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.28-Unraid-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@0306ded8f236585531276bc4cc1db9303f26bfce
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cherjr** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.32-1-osmc-aarch64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by repmeer** [comment]
### INFO
Python Version: **3.7.11 (default, Aug 31 2021, 18:25:01) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-3.2.40-i686-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cdjazman** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: ****
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cdjazman** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: ****
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cdjazman** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: ****
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Channel 5 (UK). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
