### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Sony Crackle. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by cherjr** [SickChill/SickChill#7220]
### INFO
Python Version: **3.8.8 (default, Feb 19 2021, 18:19:15) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.17-v7l+-armv7l-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Sony Crackle. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by glancy** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.28-Unraid-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@0306ded8f236585531276bc4cc1db9303f26bfce
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Sony Crackle. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hubdows** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Sony Crackle. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Hisha** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Sony Crackle. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cherjr** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.32-1-osmc-aarch64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Sony Crackle. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
