### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: TV3 (NZ). Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by RakeZim** [SickChill/SickChill#7230]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-17-amd64-x86_64-with-debian-10.10**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@94f56b7e2c86655fc98d93e94be1a75e729d3969
Link to Log: https://gist.github.com/c5e8b861780c64e055348e11011734b6
### ERROR
```
Missing time zone for network: TV3 (NZ). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by MahtavaDraig** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@bfc6fdb9347d326da6c3f26f8653eeaf9e2d18c6
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: TV3 (NZ). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by RakeZim** [comment]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-17-amd64-x86_64-with-debian-10.10**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@94f56b7e2c86655fc98d93e94be1a75e729d3969
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: TV3 (NZ). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
