### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Nat Geo Wild. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by Dobbs84** [SickChill/SickChill#7241]
### INFO
Python Version: **3.7.9 (default, Oct 15 2020, 01:11:01) [Clang 10.0.0 (git@github.com:llvm/llvm-project.git llvmorg-10.0.0-0-gd32170dbd**
Operating System: **FreeBSD-12.2-RELEASE-p2-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f42794fb5d8746eeb7fa7462fd3aead87a2b780b
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Nat Geo Wild. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by zobe123** [comment]
### INFO
Python Version: **3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]**
Operating System: **Linux-4.15.0-147-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **develop**
Commit: SickChill/SickChill@e493682cb01d790f1fe25188d1aa0794d79717c5
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Nat Geo Wild. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
