### ISSUE TITLE
ModuleNotFoundError: No module named 'imdb'

### ISSUE THREAD

**Issue by UmRAtEJvgLtH** [SickChill/SickChill#7250]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Unkown
OS: Raspbian GNU/Linux 10 (buster)"
What you did: auto-update sickchill probably
What happened: Sickchill no longer starts
What you expected: Sickchill starts
Logs:
```
Jul 12 11:08:48 Nemesis-Pi4 sickchill[25818]:   File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
Jul 12 11:08:48 Nemesis-Pi4 sickchill[25818]:     from .handler import ShowIndexer
Jul 12 11:08:48 Nemesis-Pi4 sickchill[25818]:   File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
Jul 12 11:08:48 Nemesis-Pi4 sickchill[25818]:     from sickchill.tv import Show, TVEpisode
Jul 12 11:08:48 Nemesis-Pi4 sickchill[25818]:   File "/opt/sickchill/sickchill/tv.py", line 14, in <module>
Jul 12 11:08:48 Nemesis-Pi4 sickchill[25818]:     import imdb
Jul 12 11:08:48 Nemesis-Pi4 sickchill[25818]: ModuleNotFoundError: No module named 'imdb'
Jul 12 11:08:48 Nemesis-Pi4 systemd[1]: sickchill.service: Control process exited, code=exited, status=1/FAILURE
Jul 12 11:08:48 Nemesis-Pi4 systemd[1]: sickchill.service: Failed with result 'exit-code'.
Jul 12 11:08:48 Nemesis-Pi4 systemd[1]: Failed to start LSB: starts instance of SickChill.

```

**Comment by miigotu** [comment]
Try a git pull, we dont distribute libs anymore with SC, it installs them for you.

**Comment by UmRAtEJvgLtH** [comment]
I just did a git pull and tried service sickchill start. I'm still getting the same error

**Comment by miigotu** [comment]
Try it again, there isnt really a way to get to an import error like that right now, we kick out and stop everything if we cant install to a venv.

**Comment by Tiwas** [comment]
Got the same error. Things were working great, then it updated to cc6b290153a4734cee277fa0e4cf636328a06b01 and it stopped working.

**Comment by Tiwas** [comment]
Here's mine

> C:\SickChill>SickChill.py
> sickchill found: True
> Traceback (most recent call last):
>   File "C:\SickChill\SickChill.py", line 14, in <module>
>     import sickchill.start
>   File "C:\SickChill\sickchill\__init__.py", line 5, in <module>
>     from .show.indexers import indexer, ShowIndexer
>   File "C:\SickChill\sickchill\show\indexers\__init__.py", line 1, in <module>
>     from .handler import ShowIndexer
>   File "C:\SickChill\sickchill\show\indexers\handler.py", line 5, in <module>
>     from sickchill.tv import Show, TVEpisode
>   File "C:\SickChill\sickchill\tv.py", line 14, in <module>
>     import imdb
> ModuleNotFoundError: No module named 'imdb'
> 
> C:\SickChill>git pull
> remote: Enumerating objects: 69, done.
> remote: Counting objects: 100% (69/69), done.
> remote: Compressing objects: 100% (32/32), done.
> remote: Total 69 (delta 46), reused 51 (delta 32), pack-reused 0
> Unpacking objects: 100% (69/69), done.
> From https://github.com/SickChill/SickChill
>    cc6b29015..5195bac47  master     -> origin/master
>    cc6b29015..565f92563  develop    -> origin/develop
>  + 7ee10bc11...f472bd984 tvmaze     -> origin/tvmaze  (forced update)
>  * [new tag]             v2021.07.12-3 -> v2021.07.12-3
>  * [new tag]             v2021.07.12-4 -> v2021.07.12-4
> Updating cc6b29015..5195bac47
> Fast-forward
>  pyproject.toml                  |  2 +-
>  sickchill/init_helpers.py       | 66 ++++++++++++++++++++++++++++++++++++-----
>  sickchill/update_manager/git.py |  1 +
>  sickchill/version.py            |  2 +-
>  4 files changed, 62 insertions(+), 9 deletions(-)
> 
> C:\SickChill>SickChill.py
> sickchill found: True
> Traceback (most recent call last):
>   File "C:\SickChill\SickChill.py", line 14, in <module>
>     import sickchill.start
>   File "C:\SickChill\sickchill\__init__.py", line 5, in <module>
>     from .show.indexers import indexer, ShowIndexer
>   File "C:\SickChill\sickchill\show\indexers\__init__.py", line 1, in <module>
>     from .handler import ShowIndexer
>   File "C:\SickChill\sickchill\show\indexers\handler.py", line 5, in <module>
>     from sickchill.tv import Show, TVEpisode
>   File "C:\SickChill\sickchill\tv.py", line 14, in <module>
>     import imdb
> ModuleNotFoundError: No module named 'imdb'

**Comment by miigotu** [comment]
@Tiwas For windows, reinstall with the new installer: https://github.com/SickChill/windows-sickchill/releases/tag/v0.6.0

**Comment by miigotu** [comment]
@UmRAtEJvgLtH Start SC from the command line, you will get the output that is before the logger starts, about the virtualenv. Post that.

**Comment by Tiwas** [comment]
> @Tiwas For windows, reinstall with the new installer: https://github.com/SickChill/windows-sickchill/releases/tag/v0.6.0

Any way to tell the installer to install over the old version? I'm told to uninstall first.

**Comment by miigotu** [comment]
@Tiwas uninstalling the old uninstaller has the option to keep your db and config, just leave it

**Comment by Tiwas** [comment]
> @Tiwas uninstalling the old uninstaller has the option to keep your db and config, just leave it

Thanks. Will need to dig into the registry, it seems. It's telling me the uninstall file is missing...

**Comment by Tiwas** [comment]
> @Tiwas uninstalling the old uninstaller has the option to keep your db and config, just leave it

Ok, so that was a little painful. Got it running, though. Seems it will only run properly through the service the installer creates...

**Comment by UmRAtEJvgLtH** [comment]
> 
> 
> @UmRAtEJvgLtH Start SC from the command line, you will get the output that is before the logger starts, about the virtualenv. Post that.

You mean like this?

```
pi@Nemesis-Pi4:/opt/sickchill $ python SickChill.py
sickchill found: True
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.10) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/sickchill/sickchill/tv.py", line 14, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'
```

**Comment by miigotu** [comment]
> > @Tiwas uninstalling the old uninstaller has the option to keep your db and config, just leave it
> 
> Ok, so that was a little painful. Got it running, though. Seems it will only run properly through the service the installer creates...

No, the patch just changed now. `C:\sickchill\python3\tools\python.exe C:\sickchill\python3\tools\scripts\sickchill.py` should run perfectly fine.

**Comment by miigotu** [comment]
> > 
> > 
> > @UmRAtEJvgLtH Start SC from the command line, you will get the output that is before the logger starts, about the virtualenv. Post that.
> 
> You mean like this?
> 
> ```
> pi@Nemesis-Pi4:/opt/sickchill $ python SickChill.py
> sickchill found: True
> /usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.10) or chardet (3.0.4) doesn't match a supported version!
>   RequestsDependencyWarning)
> Traceback (most recent call last):
>   File "SickChill.py", line 14, in <module>
>     import sickchill.start
>   File "/opt/sickchill/sickchill/__init__.py", line 5, in <module>
>     from .show.indexers import indexer, ShowIndexer
>   File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
>     from .handler import ShowIndexer
>   File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
>     from sickchill.tv import Show, TVEpisode
>   File "/opt/sickchill/sickchill/tv.py", line 14, in <module>
>     import imdb
> ModuleNotFoundError: No module named 'imdb'
> ```

You seem to have SickChill installed by git and also in pip site-packages. If you are running from git and want to do it that way, pip uninstall sickchill and just use the git source. Git source starts up slower though, so you might want to run it from installing pip and running the script for that install instead.

Bottom line, use one or the other. Your one in site-packages (that was installed with pip) is out of date.

**Comment by Tiwas** [comment]
> > > @Tiwas uninstalling the old uninstaller has the option to keep your db and config, just leave it
> > 
> > 
> > Ok, so that was a little painful. Got it running, though. Seems it will only run properly through the service the installer creates...
> 
> No, the path just changed now. `C:\sickchill\python3\tools\python.exe C:\sickchill\python3\tools\scripts\sickchill.py` should run perfectly fine.

Thanks for your patience :)
