### ISSUE TITLE
code=exited status=126

### ISSUE THREAD

**Issue by fvolpe83** [SickChill/SickChill#7252]
Branch/Commit: latest - couldn't check version because happened during an update
OS: Ubuntu 18.04.5 LTS
Browser: firefox
What you did: update sickchill from the in-page prompt
What happened: hung at restarting sickchill, checked systemctl and it won't start, gives the error below
What you expected: sickchill to restart
Logs:
```
● sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-07-12 16:41:49 CEST; 4min 36s ago
  Process: 3597 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (

sickchill.service: Control process exited, code=exited status=126
sickchill.service: Failed with result 'exit-code'.
Failed to start SickChill Daemon.
```

**Comment by DavidPinilo** [comment]
I'm getting a similar error, but for me after trying to reinstall it won't start the service:
 sickchill.service - SickChill Daemon
   Loaded: loaded (/lib/systemd/system/sickchill.service; disabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Mon 2021-07-12 18:29:42 BST; 1min 47s ago
  Process: 3137 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/si

Jul 12 18:28:11 raspberrypi systemd[1]: Starting SickChill Daemon...
Jul 12 18:29:41 raspberrypi systemd[1]: sickchill.service: Start operation timed out. Terminating.
Jul 12 18:29:41 raspberrypi systemd[1]: sickchill.service: Control process exited, code=killed, status=15/TERM
Jul 12 18:29:42 raspberrypi systemd[1]: sickchill.service: Failed with result 'timeout'.
Jul 12 18:29:42 raspberrypi systemd[1]: Failed to start SickChill Daemon.
...skipping...
● sickchill.service - SickChill Daemon
   Loaded: loaded (/lib/systemd/system/sickchill.service; disabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Mon 2021-07-12 18:29:42 BST; 1min 47s ago
  Process: 3137 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/si

Jul 12 18:28:11 raspberrypi systemd[1]: Starting SickChill Daemon...
Jul 12 18:29:41 raspberrypi systemd[1]: sickchill.service: Start operation timed out. Terminating.
Jul 12 18:29:41 raspberrypi systemd[1]: sickchill.service: Control process exited, code=killed, status=15/TERM
Jul 12 18:29:42 raspberrypi systemd[1]: sickchill.service: Failed with result 'timeout'.
Jul 12 18:29:42 raspberrypi systemd[1]: Failed to start SickChill Daemon.

**Comment by fvolpe83** [comment]
> I'm getting a similar error, but for me after trying to reinstall it won't start the service:

didn't try a reinstall myself in fear of not working..renamed

**Comment by fvolpe83** [comment]
> I'm getting a similar error, but for me after trying to reinstall it won't start the service:

didn't reinstall myself in fear of not working.
did you get the error right after updating today?

**Comment by DavidPinilo** [comment]
It failed when I tried to update it. It just froze and it wouldn't start again, so I tried to reinstall I get the error I posted before

**Comment by davidlinke** [comment]
It won't start for me now either after updating. I am seeing this error on MacOS:

```
Traceback (most recent call last):
  File "/Applications/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/Applications/SickChill/sickchill/__init__.py", line 3, in <module>
    poetry_install()
  File "/Applications/SickChill/sickchill/init_helpers.py", line 55, in poetry_install
    pip_install("poetry")
  File "/Applications/SickChill/sickchill/init_helpers.py", line 43, in pip_install
    subprocess.check_call(args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pip'
```

**Comment by KevSex** [comment]
Receiving similar error on CentOS 7 after upgrading. When attempting to run via CLI, I get the following:

```
root@app01 ~ # /bin/python3 /opt/SickChill/SickChill.py --daemon --nolaunch --datadir=/opt/SickChill/data
sickchill found: False
We always run from virtualenv when running from source
Because of the above errors, we will try creating a new virtualenvironment in /opt/SickChill/.venv
virtualenv found: True
Using /usr/libexec/platform-python3.6 as base interpreter
Unable to run command: __init__() got an unexpected keyword argument 'text'
Due to the above error, we cannot continue! Exiting
root@app01 ~ #
```

**Comment by miigotu** [comment]
> I'm getting a similar error, but for me after trying to reinstall it won't start the service:
>  sickchill.service - SickChill Daemon
>    Loaded: loaded (/lib/systemd/system/sickchill.service; disabled; vendor preset: enabled)
>    Active: failed (Result: timeout) since Mon 2021-07-12 18:29:42 BST; 1min 47s ago
>   Process: 3137 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/si
> 
> Jul 12 18:28:11 raspberrypi systemd[1]: Starting SickChill Daemon...
> Jul 12 18:29:41 raspberrypi systemd[1]: sickchill.service: Start operation timed out. Terminating.
> Jul 12 18:29:41 raspberrypi systemd[1]: sickchill.service: Control process exited, code=killed, status=15/TERM
> Jul 12 18:29:42 raspberrypi systemd[1]: sickchill.service: Failed with result 'timeout'.
> Jul 12 18:29:42 raspberrypi systemd[1]: Failed to start SickChill Daemon.
> ...skipping...
> ● sickchill.service - SickChill Daemon
>    Loaded: loaded (/lib/systemd/system/sickchill.service; disabled; vendor preset: enabled)
>    Active: failed (Result: timeout) since Mon 2021-07-12 18:29:42 BST; 1min 47s ago
>   Process: 3137 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/si
> 
> Jul 12 18:28:11 raspberrypi systemd[1]: Starting SickChill Daemon...
> Jul 12 18:29:41 raspberrypi systemd[1]: sickchill.service: Start operation timed out. Terminating.
> Jul 12 18:29:41 raspberrypi systemd[1]: sickchill.service: Control process exited, code=killed, status=15/TERM
> Jul 12 18:29:42 raspberrypi systemd[1]: sickchill.service: Failed with result 'timeout'.
> Jul 12 18:29:42 raspberrypi systemd[1]: Failed to start SickChill Daemon.
> 

Try starting it manually, `/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchilll`

**Comment by miigotu** [comment]
> It won't start for me now either after updating. I am seeing this error on MacOS:
> 
> ```
> Traceback (most recent call last):
>   File "/Applications/SickChill/SickChill.py", line 14, in <module>
>     import sickchill.start
>   File "/Applications/SickChill/sickchill/__init__.py", line 3, in <module>
>     poetry_install()
>   File "/Applications/SickChill/sickchill/init_helpers.py", line 55, in poetry_install
>     pip_install("poetry")
>   File "/Applications/SickChill/sickchill/init_helpers.py", line 43, in pip_install
>     subprocess.check_call(args)
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 359, in check_call
>     retcode = call(*popenargs, **kwargs)
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
>     with Popen(*popenargs, **kwargs) as p:
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'pip'
> ```

I think you aren't fully updated, last few commits it checks if pip exists, and would print that it doesn't exist.

**Comment by miigotu** [comment]
> Receiving similar error on CentOS 7 after upgrading. When attempting to run via CLI, I get the following:
> 
> ```
> root@app01 ~ # /bin/python3 /opt/SickChill/SickChill.py --daemon --nolaunch --datadir=/opt/SickChill/data
> sickchill found: False
> We always run from virtualenv when running from source
> Because of the above errors, we will try creating a new virtualenvironment in /opt/SickChill/.venv
> virtualenv found: True
> Using /usr/libexec/platform-python3.6 as base interpreter
> Unable to run command: __init__() got an unexpected keyword argument 'text'
> Due to the above error, we cannot continue! Exiting
> root@app01 ~ #
> ```

This i think is my fault, I will check my code against subprocess.Popen

**Comment by miigotu** [comment]
@KevSex git pull should take care of it. I fixed that error with GitHub web editor lol (not at my pc, I'm in my phone RN)
3f0ec61e1ecb6451e47eb0c8a2cb956344e62027

**Comment by davidlinke** [comment]
It's working for me now when launching via terminal, but no longer working when launching via launchd :/ It says error 1, which is very generic. I can't seem to find any more detail logs of what the issue is.

**Comment by miigotu** [comment]
> It's working for me now when launching via terminal, but no longer working when launching via launchd :/ It says error 1, which is very generic. I can't seem to find any more detail logs of what the issue is.

Edit the launchd script to use the new virtual environment at `.venv/bin/python`

**Comment by kurt2x** [comment]
for ubuntu 20.04 you may not have pipenv installed, you'll likely have to execute this:
```
su - sickchill
cd /opt/sickchill
git pull
exit
apt install pipenv
systemctl start service.sickchill
```

**Comment by miigotu** [comment]
@kurt2x it is not using pipenv, just `pip install virtualenv`

**Comment by kurt2x** [comment]
oh yeah that's right, I just checked my apt history and indeed installing pipenv installed virtualenv:
```
Start-Date: 2021-07-12  19:33:26
Commandline: apt install pipenv
Install: python3-dev:amd64 (3.8.2-0ubuntu2, automatic), python3-distutils:amd64 (3.8.10-0ubuntu1~20.04, automatic), python3-virtualenv-clone:amd64 (0.3.0-2, automatic), libpython3.8-dev:amd64 (3.8.10-0ubuntu1~20.04, automatic), libexpat1-dev:amd64 (2.2.9-1build1, automatic), python3-filelock:amd64 (3.0.12-2, automatic), python3-pip:amd64 (20.0.2-5ubuntu1.5, automatic), python3-wheel:amd64 (0.34.2-1, automatic), zlib1g-dev:amd64 (1:1.2.11.dfsg-2ubuntu1.2, automatic), python3-appdirs:amd64 (1.4.3-2.1, automatic), python3-distlib:amd64 (0.3.0-1, automatic), python3-importlib-metadata:amd64 (1.5.0-1, automatic), python3-zipp:amd64 (1.0.0-1, automatic), python3-more-itertools:amd64 (4.2.0-1build1, automatic), pipenv:amd64 (11.9.0-1), python3.8-dev:amd64 (3.8.10-0ubuntu1~20.04, automatic), libpython3-dev:amd64 (3.8.2-0ubuntu2, automatic), python-pip-whl:amd64 (20.0.2-5ubuntu1.5, automatic), python3-virtualenv:amd64 (20.0.17-1ubuntu0.4, automatic), python3-setuptools:amd64 (45.2.0-1, automatic)
```

**Comment by fvolpe83** [comment]
this happened today after a git pull, started normally right after , marking as solved

`remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 27 (delta 16), reused 19 (delta 12), pack-reused 0
Unpacking objects: 100% (27/27), done.
From https://github.com/SickChill/SickChill
   5195bac47..7f07d61b0  master     -> origin/master
   565f92563..a0717b2a3  develop    -> origin/develop
Updating 5195bac47..7f07d61b0
Fast-forward
 SickChill.py                             |  2 +-
 sickchill/init_helpers.py                |  2 +-
 sickchill/oldbeard/common.py             |  2 +-
 sickchill/oldbeard/network_timezones.py  |  2 +-
 sickchill/oldbeard/notifiers/pushover.py |  2 +-
 sickchill/oldbeard/sbdatetime.py         |  6 +++---
 sickchill/oldbeard/search.py             |  2 +-
 sickchill/update_manager/source.py       | 22 +++++++++++-----------
 sickchill/views/api/webapi.py            |  2 +-
 tests/test_api_v1.py                     |  2 +-
 10 files changed, 22 insertions(+), 22 deletions(-) `

**Comment by KevSex** [comment]
> @KevSex git pull should take care of it. I fixed that error with GitHub web editor lol (not at my pc, I'm on my phone RN)
> [3f0ec61](https://github.com/SickChill/SickChill/commit/3f0ec61e1ecb6451e47eb0c8a2cb956344e62027)

I'm now getting a new error when attempting to start

```
root@app01 opt # /bin/python3 /opt/SickChill/SickChill.py --daemon --nolaunch --datadir=/opt/SickChill/data
sickchill found: False
We always run from virtualenv when running from source
Something weird happend when creating the virtualenv, /opt/SickChill/.venv/libexec/platform-python3.6 does not exist. Exiting
```

Seems like someone else has this error too as per [#7258](https://github.com/SickChill/SickChill/issues/7258)
