### ISSUE TITLE
Docker image : please publish latest modification in docker hub (with latest tag)

### ISSUE THREAD

**Issue by lcworld** [SickChill/SickChill#7254]
I'm using the docker image from dockerhub sickchill/sickchill.
docker pull sickchill/sickchill download the image tagged latest.

This tag is 4 month old, and during this period you switched from alpine to debian (buster)

So please update the docker image so it match the latest content of master branch.

Further details :
* Today Sickchill indicate lots of updates.
https://github.com/SickChill/SickChill/compare/f42794fb5d8746eeb7fa7462fd3aead87a2b780b...5195bac47b393b9edc718405fa58858421391c1d
So I update it from the link "update now", which usually works.
But today it's not working.

I checked the log and last issue was gcc was missing.
I try to installed it but I found that the image is based on alpine not on debian ...

I checked on docker hub, and so image tagged latest was 4 month old, which was on alpine.

I switched to image tagged develop (1 month old), and sickchill also offers to update the version.
I have done it, sickchill is working again ... but on develop branch.

So between june 17th and now, you made a change that breaks alpine image.

Branch/Commit: master   
     initial commit f42794fb5d8746eeb7fa7462fd3aead87a2b780b 
     destination commit 5195bac47b393b9edc718405fa58858421391c1d
OS: docker image  tagged latest
Browser: chrome
What you did: Update to latest commit on master branch via "update" link in Sickchill
What happened: Sickchill not working anymore, latest issue was gcc missing
What you expected: Sickchill to be updated and running

**Comment by ebaydan777** [comment]
Same. Sickchill no longer worker on Docker/Synology NAS after recent 91 commits update. Can't access at all.

**Comment by miigotu** [comment]
@ebaydan777 you need to back up your sickchill.db and config.ini, and reinstall. It works now.

For docker, im working on that tonight.

**Comment by ebaydan777** [comment]
> @ebaydan777 you need to back up your sickchill.db and config.ini, and reinstall. It works now.
> 
> For docker, im working on that tonight.

I am using docker, so I imagine I need to wait until that's fixed since I can't reinstall any other way. (sorry meant to say docker on my synology nas)

**Comment by ebaydan777** [comment]
Is docker version fixed? I just did 'docker pull sickchill/sickchill' but it says latest, doesn't turn on when I try to access the local url for sickchill from my synology nas.

**Comment by miigotu** [comment]
@ebaydan777 sickchill/sickchill:latest has not changed in 4 months. sickchill/sickchill:develop was just updated
linuxserver image is not mine.

Once https://github.com/SickChill/SickChill/actions/runs/1029269882 completes, sickchill/sickchill:master will be updated
And then when I merge develop to master latest will biuld.

**Comment by ebaydan777** [comment]
> @ebaydan777 sickchill/sickchill:latest has not changed in 4 months. sickchill/sickchill:develop was just updated
> linuxserver image is not mine.
> 
> Once https://github.com/SickChill/SickChill/actions/runs/1029269882 completes, sickchill/sickchill:master will be updated
> And then when I merge develop to master latest will biuld.

ok, sorry I am new to this. I just need to know what to do on docker on synology nas to get it working once complete. If there's any steps you can provide that would be very helpful! thanks! :)

**Comment by MrCee** [comment]
@ebaydan777  on Synology DSM my docker-compose line is ` image: sickchill/sickchill:develop`
Any other download is going to result in a 240+ commit update and it's not going to work.
If you do update at any stage run a permission fix on your docker folders involved (most important)

**Comment by ebaydan777** [comment]
> @ebaydan777 on Synology DSM my docker-compose line is ` image: sickchill/sickchill:develop`
> Any other download is going to result in a 240+ commit update and it's not going to work.
> If you do update at any stage run a permission fix on your docker folders involved (most important)

Sorry again I am very new so I am unsure what any of that even means. I have terminal up to access via SSH into my NAS and get into docker but if anyone can provide specific lines to copy paste into terminal that would be great. Thanks

**Comment by MrCee** [comment]
Use the Docker App to do the following:

- delete the sickchill/sickchill:latest container
- delete the sickchill/sickchill:latest image
- Search the registry for sickchill/sickchill
- When you download the sickchill/sickchill image in the docker app, instead of selecting the tag 'Latest', scroll down and select the tag 'Develop' and use this image to install.
- If you still have issues loading you may need to fix permissions on your NAS e.g.. `chmod -R 777 /volume1/docker/sickchill` and work out better permissions after everything runs.

**Comment by ebaydan777** [comment]
So this kinda screwed it up. When i got back on the webpage nothing was there and I had to restore my last backup which was 09/2020. I figured it would pick up the last position it was in before sickchill went down? Not sure what to do now..

**Comment by kyuuk** [comment]
I don't use docker on Synology but i'm using the docker image, so i would advice to use the `master` instead of `develop` because develop branch may not be stable
(try to backup before you change the anything, just in case)

**Comment by MrCee** [comment]
@kyuuk Actually yes, that's better than running develop. So currently using the tag 'latest' is 4 months old, but using tag 'master' shows Version: 2021.07.14-6 and it's working well.
@ebaydan777 unless the path/to/data changed you still should have your config.ini and sickchill.db in e.g. `/volume1/docker/sickchill/data`.  Maybe it's the way I update my containers, I always pick up where I left off when a new image/container is installed, the files in the path/to/data are not overwritten. I use a docker-compose file which I have tweaked over time but started out with whats on the wiki., and just now changed the image line to `  image: sickchill/sickchill:master`

**Comment by lcworld** [comment]
The job  https://github.com/SickChill/SickChill/actions/runs/1029269882  was finished with success, and new image "sickchill/sickchill:master" was uploaded to docker hub (2 days ago).

I installed it with success.
So my issue is solved.

I don't know about kyuuk and ebaydan777 issues.

**Comment by lcworld** [comment]
Sorry to fast ... the new image sickchill/sickchill:master is working.
But the image sickchill/sickchill:latest has not been updated.

@miigotu Please tag the image sickchill/sickchill:master from 2 days ago as latest.

**Comment by miigotu** [comment]
Already did
