### ISSUE TITLE
not work after update - File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain

### ISSUE THREAD

**Issue by tiagofcn** [SickChill/SickChill#7256]
OS: ubuntu 18.04

sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-07-12 15:22:56 -03; 1h 29min ago
  Process: 481 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, s

jul 12 15:22:56 Server python3[481]:   File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
jul 12 15:22:56 Server python3[481]:     result = func(*args)
jul 12 15:22:56 Server python3[481]:   File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
jul 12 15:22:56 Server python3[481]:     context=self._context, check_hostname=self._check_hostname)
jul 12 15:22:56 Server python3[481]:   File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
jul 12 15:22:56 Server python3[481]:     raise URLError(err)
jul 12 15:22:56 Server python3[481]: urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
jul 12 15:22:56 Server systemd[1]: sickchill.service: Control process exited, code=exited status=1
jul 12 15:22:56 Server systemd[1]: sickchill.service: Failed with result 'exit-code'.
jul 12 15:22:56 Server systemd[1]: Failed to start SickChill Daemon.

Help!!

**Comment by ghbaud** [comment]
SickChill service status is paused, and it will not start.

**Comment by tiagofcn** [comment]
> SickChill service status is paused, and it will not start.


Already tried to restart the service but always return the same error.

**Comment by ghbaud** [comment]
Sorry, wasn't offering advice, just chiming in that mine wasn't working either.

**Comment by Schoepp23** [comment]
Same here :(

**Comment by miigotu** [comment]
If you said the service is paused, that means you need to reinstall with the new windows SickChill installer, v0.6.0

Failure in name resolution, restart your box and make sure it has internet access. You cannot start SickChill without a working network.

**Comment by Schoepp23** [comment]
Just went thru the fresh install.  That did in fact fix my issue but I'm not sure why all of a sudden it would not load after the update.  I was impacted by the MAKO error so I needed to update.  @miigotu thanks for all your hard work.  For those who are confused, uninstall SickChill from your PC but leave the config folder, go to [here](https://github.com/SickChill/windows-sickchill/releases/tag/v0.6.0) and reinstall, this will take a few minutes, then you should be good to go.

**Comment by ghbaud** [comment]
> If you said the service is paused, that means you need to reinstall with the new windows SickChill installer, v0.6.0

That works for me. Thanks very much. Just curious, is there somewhere that this change was announced and I just missed it?

**Comment by miigotu** [comment]
> > If you said the service is paused, that means you need to reinstall with the new windows SickChill installer, v0.6.0
> 
> That worked for me. Thanks very much. Just curious, is there somewhere that this change was announced and I just missed it?

This level of mayhem was not expected. I wrote like 1000 lines of code and tested it for weeks in the develop branch. Shit happens, but this change is for the better in the long term since you will always have updated and proper dependencies. This is for security and stability, so the hassle getting it working now is well worth it for all SickChillers.

**Comment by tiagofcn** [comment]
After installing it started working again.
Thanks!
