### ISSUE TITLE
SickChill Not Starting on Centos 8

### ISSUE THREAD

**Issue by potequity** [SickChill/SickChill#7258]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Centos 8 (kernel: 4.18.0-305.7.1.el8_4.x86_64 )
Browser: Firefox
What you did: Downloaded SickChill-master.zip,unzipped and ran the following to start:

/usr/bin/env python3.6 /home/SickChill/SickChill.py -q --daemon --nolaunch --datadir /home/SickChill/sickchill

What happened:
sickchill found: False
Current environment is not writable!
Because of the above errors, we will try creating a new virtualenvironment in /home/SickChill/.venv
virtualenv found: True
Using /usr/libexec/platform-python3.6 as base interpreter
Command result: created virtual environment CPython3.6.8.final.0-64 in 567ms
  creator CPython3Posix(dest=/home/SickChill/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/SickChill/.local/share/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Created new virtualenvironment in /home/SickChill/.venv
Something weird happend when creating the virtualenv, /home/SickChill/.venv/libexec/platform-python3.6 does not exist. Exiting

What you expected:
Logs:
```
PASTE LOGS HERE

[sickchill@linux01 ~]$ /usr/bin/env python3.6 /home/SickChill/SickChill.py -q --daemon --nolaunch --datadir /home/SickChill/sickchill
sickchill found: False
Current environment is not writable!
Because of the above errors, we will try creating a new virtualenvironment in /home/SickChill/.venv
virtualenv found: True
Using /usr/libexec/platform-python3.6 as base interpreter
Command result: created virtual environment CPython3.6.8.final.0-64 in 567ms
  creator CPython3Posix(dest=/home/SickChill/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/SickChill/.local/share/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Created new virtualenvironment in /home/SickChill/.venv
Something weird happend when creating the virtualenv, /home/SickChill/.venv/libexec/platform-python3.6 does not exist. Exiting
[sickchill@linux01 ~]$ 

```
Any help would be greatly appreciated!

-SR

**Comment by buccinator** [comment]
$ git reset --hard
$ git reset --hard master@{"7 day ago"}

only way i could fix it, pulling brand new master had exactly the same error

**Comment by potequity** [comment]
@buccinator  No luck!

[sickchill@linux01 ~]$ git reset --hard
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[sickchill@linux01 ~]$ git reset --hard master@{"7 day ago"}
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[sickchill@linux01 ~]$ pwd
/home/SickChill
[sickchill@linux01 ~]$ cd sickchill/
[sickchill@linux01 sickchill]$ git reset --hard
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[sickchill@linux01 sickchill]$ git reset --hard master@{"7 day ago"}
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[sickchill@linux01 sickchill]$

**Comment by buccinator** [comment]
how/where did you install it? git pull?

why is it in the /home/ dir like a user? i git pulled mine into /opt/SickChill

**Comment by potequity** [comment]
Downloaded SickChill-master.zip from https://github.com/SickChill/SickChill and unzipped it in /home. The only customization I made was rename Sickchill-master dir to Sickchill.

**Comment by miigotu** [comment]
@potequity what is the output of `ls -R /home/SickChill/.venv/{libexec,bin,tools}`

**Comment by potequity** [comment]
@miigotu here's the output:

ls -al /home/SickChill/.venv/{libexec,bin,tools}
ls: cannot access '/home/SickChill/.venv/libexec': No such file or directory
ls: cannot access '/home/SickChill/.venv/bin': No such file or directory
ls: cannot access '/home/SickChill/.venv/tools': No such file or directory
[root@linux01 ~]# 

-PE

**Comment by miigotu** [comment]
@potequity thanks, I will fix this later today.

**Comment by potequity** [comment]
@miigotu ok, thanks.

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/commit/f96786115ad62a497a87f92e7eb5ebcd45dce314#diff-a3622ad2c46432097a26538f4b8df0cfedef2d8324e5a31ce680fc0f83b2ba70L198-R201

**Comment by potequity** [comment]
Sorry, should I just do a 'git pull' and install it? Or should I download the master zip file?

**Comment by KevSex** [comment]
After doing a `git pull`, I am now receiving the following error:

```
root@app01 SickChill # /bin/python3 /opt/SickChill/SickChill.py --daemon --nolaunch --datadir=/opt/SickChill/data
sickchill found: False
We always run from virtualenv when running from source
Restarting SickChill with ['/opt/SickChill/.venv/bin/platform-python3.6', '/opt/SickChill/SickChill.py', '--daemon', '--nolaunch', '--datadir=/opt/SickChill/data']
sickchill found: False
pip found: False
Installing pip
Traceback (most recent call last):
  File "/opt/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/SickChill/sickchill/__init__.py", line 3, in <module>
    poetry_install()
  File "/opt/SickChill/sickchill/init_helpers.py", line 223, in poetry_install
    check_and_install_pip()
  File "/opt/SickChill/sickchill/init_helpers.py", line 130, in check_and_install_pip
    tfd = download_to_temp_file("https://bootstrap.pypa.io/get-pip.py", suffix=".py", prefix="get-pip")
TypeError: download_to_temp_file() got an unexpected keyword argument 'suffix'
```
