### ISSUE TITLE
SickChill not starting on Qnap

### ISSUE THREAD

**Issue by HazMatt69** [SickChill/SickChill#7259]
[~] # sherpa reinstall SickChill
sherpa 210708 • a mini-package-manager for QNAP NAS

done: installed 1 PIP group                                            
fail: 'SickChill' service operation failed. Check (/var/log/SickChill.log) for more information 
done: reinstalled 1 dependent QPKG                                            
                                                           
[~] # cd /var/log/
[/var/log] # vi SickChill.log 

>>>>>>>>>> datetime:'Tue Jul 13 09:05:04 CEST 2021',request:'start',QPKG:'201130',app:'2021.7.12-6' <<<<<<<<<<
daemon: NOT active
file (/opt/bin/git): exists
update 'SickChill' from remote repository: OK
current git branch: master
file (/opt/bin/python3): exists
load UI ports from application: OK
start daemon: failed!
= ExecuteAndLog()
output: "sickchill found: False
pip found: True
pip args: /share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qqU setuptools poetry --pre
poetry found: True

**Comment by HazMatt69** [comment]
>>>>>>>>>> datetime:'Tue Jul 13 20:24:32 CEST 2021',request:'starting',QPKG:'210713',app:'2021.7.12-6' <<<<<<<<<<
daemon: NOT active
file (/opt/bin/git): exists
workaround (https://github.com/SickChill/SickChill/issues/7249): failed!
= ExecuteAndLog()
output: "fatal: ambiguous argument 'dec999c': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'"
result: [128]
current git branch: master
file (/opt/bin/python3): exists
load UI ports from application: OK
start daemon: failed!
= ExecuteAndLog()
output: "sickchill found: False
pip found: True
pip args: /share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=p >
poetry found: True
pip args: /share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=p >
Traceback (most recent call last):
  File "/share/ZFS3_DATA/.qpkg/SickChill/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/lib/python3.9/site-packages/github/__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/lib/python3.9/site-packages/github/MainClass.py", line 59, in <module>
    import github.Event
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/lib/python3.9/site-packages/github/Event.py", line 32, in <module>
    import github.NamedUser
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/lib/python3.9/site-packages/github/NamedUser.py", line 44, in <module>
    import github.Organization
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/lib/python3.9/site-packages/github/Organization.py", line 50, in <module>
    import github.Repository
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/lib/python3.9/site-packages/github/Repository.py", line 125, in <module>
    import github.PublicKey
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/lib/python3.9/site-packages/github/PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/lib/python3.9/site-packages/nacl/public.py", line 17, in <module>
    import nacl.bindings
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/lib/python3.9/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_aead import (
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/.venv/lib/python3.9/site-packages/nacl/bindings/crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'"
result: [1]

**Comment by Dohnerd** [comment]
Same here...

daemon: NOT active
wait for (/opt/bin/git) to appear: visible in 31 seconds
file (/opt/bin/git): exists
update 'SickChill' from remote repository: OK
current git branch: master
file (/opt/bin/python3): exists
load UI ports from application: OK
start daemon: failed!
= ExecuteAndLog()
output: "sickchill found: False
pip found: True
pip args: /share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qqU setuptools poetry --pre
poetry found: True

**Comment by Dohnerd** [comment]
at start:

daemon: NOT active
file (/opt/bin/git): exists
update 'SickChill' from remote repository: OK
current git branch: master
file (/opt/bin/python3): exists
load UI ports from application: OK
start daemon: OK
file (/var/run/SickChill.pid): exists
daemon: IS active
daemon PID: 10872
daemon listening address: 0.0.0.0
check for UI port 7073 response: (no-more than 120 seconds): 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, failed!
no response on configured port(s)!

**Comment by miigotu** [comment]
`check for UI port 7073 response: (no-more than 120 seconds)` whoever did that failed.

**Comment by OneCDOnly** [comment]
@HazMatt69 & @Dohnerd : I released an updated SickChill QPKG earlier today that reverts the most recent commits. It actually reverts right back to April - as this resulted in a working SiCkChill. The new QPKG version is 210714. To install it:
```
sherpa clean
sherpa upgrade sc restart sc
```
I don't have time right-now to try and get @miigotu's latest efforts to work as these were included in the master branch without any warning. Using `virtualenv` with Entware is not a simple matter in QTS. 😞

**Comment by miigotu** [comment]
@OneCDOnly just make it so they use a pip installed sickchill and done. No need for a venv. I have been saying for 5 years now that libs would be going away. Every time I make an update to them I'm fighting obscure bugs that are not reproducible because those libs are supposed to be compiled on each individual architecture, os, and libc/muscl combination. It just is not sustainable now that it is nearly impossible to provide a set of packages that work on anything other than x86_64 and arm64 using libc only.

A month would have been enough warning. 5 years was more.

**Comment by OneCDOnly** [comment]
@miigotu I have previously tried the pip install - it didn't go well. SickChill required so many other modules that it caused the other Python projects I run from source to break. 

I'm not-at-all happy you pushed these major changes into master without checking what the result would be on installations that get their commits from the master branch. I'm finding it difficult to continue supporting SickChill if this is how you're going to run things. :(

**Comment by miigotu** [comment]
You think you are some kind of authority figure here or something? not-at-all-happy...pfft The shit was tested for two whole months in develop. In that time you didn't bother to check how develop was going. It is not ME who is supposed to check it is going to work on every edge case platform on the planet with users I could count on my fingers and toes. I just try my best to make it universal and leave ample opportunity for people to test out the development branch ahead of time. It is on the maintainer of the package for that endpoint to keep up with whats going on upstream.

Imagine if you had thousands of people spamming you that something fucked up and I came at you talking shit. Trust, it's 10,000 times more a pain in the ass for me dealing with it than it is for you.

**Comment by OneCDOnly** [comment]
> Imagine if you had thousands of people spamming you that something fucked up and I came at you talking shit. Trust, it's 10,000 times more a pain in the ass for me dealing with it than it is for you.

Why do you think those thousands are spamming you? Because you tested for 2 whole months? Sheez. 

I think that concludes this discussion. You clearly can't accept criticism and think everyone else should be just fine with how you're doing things. Good luck with that.

**Comment by miigotu** [comment]
Ive had pretty good luck the last 8 years maintaining this project. But thanks. If you think I have dozens of random 10 year old nas devices laying around here you're on crack. SickChill has not worked correctly for the past 2 years or so on qnap anyway, because the libs needed compiled extensions to work properly. Which is why it was time to rip the bandaid off, because too many packages finally had shared objects and compiled extensions that made it IMPOSSIBLE to keep libs in the project. But you know, tell me how it is.

**Comment by OneCDOnly** [comment]
> Ive had pretty good luck the last 8 years maintaining this project. But thanks. 

Yes, I was there when you started. Clearly you've forgotten this. 

> If you think I have dozens of random 10 year old nas devices laying around here you're on crack. 

That's why volunteers like me have been maintaining packages suited to NAS, so that people like you don't need to. Only, you don't appreciate it. Sheez again.  

> SickChill has not worked correctly for the past 2 years or so on qnap anyway, because the libs needed compiled extensions to work properly. 

Tell that to all the QNAP users who are running SickChill thanks to me. They only had problems with SC when you decided to fsck with things. Which I then had to fix. You're welcome. 

> Which is why it was time to rip the bandaid off, because too many packages finally had shared objects and compiled extensions that made it IMPOSSIBLE to keep libs in the project. But you know, tell me how it is.

Oh, what a load of complete bullshit. You have no idea what you're talking about. You really do need someone to tell you how it is. 

If you had at least half-a-brain you'd understand how to work with others. I now see what created the SickChill fork all those years ago: it's your inability to work with a group. 

So tell me kid, if you're so talented and know what you're doing, why are so many complaining their installations are no longer working?

**Comment by Dohnerd** [comment]
Correct PIP install is sh*t .. but if I understand this right, its time to switch to sonar? Sounds like SC working on NAS is about to be a nightmare.

**Comment by HazMatt69** [comment]
@OneCDOnly I still get errors:

>>>>>>>>>> datetime:'Wed Jul 14 15:56:28 CEST 2021',request:'starting',QPKG:'210714',app:'2021.4.10' <<<<<<<<<<
daemon: NOT active
file (/opt/bin/git): exists
update 'SickChill' from remote repository: OK
workaround (https://github.com/SickChill/SickChill/issues/7249): OK
disable auto-update: OK
current git branch: master
file (/opt/bin/python3): exists
load UI ports from application: OK
start daemon: failed!
= ExecuteAndLog()
output: "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/sickchill/locale
/share/ZFS530_DATA/.qpkg/SickChill/SickChill/sickchill/locale
Traceback (most recent call last):
  File "/share/ZFS3_DATA/.qpkg/SickChill/SickChill/SickChill.py", line 17, in <module>
    from sickchill.movies import MovieList
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/sickchill/movies.py", line 8, in <module>
    from imdb.parser.http.piculet import Path, Rule
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/__init__.py", line 40, in <module>
    from . import (
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/companyParser.py", line 32, in <module>
    from .piculet import Path, Rule, Rules
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: cannot import name 'etree' from 'lxml' (/opt/lib/python3.9/site-packages/lxml/__init__.py)"
result: [1]

**Comment by miigotu** [comment]
@OneCDOnly the 1 day block is over. If you want to be positive and try to help the situation that's fine. But if you want to talk trash and make things worse by piling on shit and kicking it in my face when I'm down keep it to yourself.

**Comment by OneCDOnly** [comment]
@miigotu that's the worst apology I've ever seen. Try again. 

If you can't, then you may as well make the block permanent, as you're not someone I want to collaborate with. Just like you, I've withdrawn SickChill support on QNAP. I'm still trying to fix the damage your pip installer does to pre-established Python environments. 🙄
