### ISSUE TITLE
Windows temp folder filling up with .pyz files

### ISSUE THREAD

**Issue by anahka2309** [SickChill/SickChill#7265]
More of an FYI as I ended up completely uninstalling and reinstalling which fixed the issue. 

Since yesterday or today my Windows %TEMP% folder was filling up with .pyz files all about 9MB in size. Almost 200GB's worth which filled up the drive. The files were constantly being created but stopped the second I stopped the Sickchill service. Uninstalled and reinstalled and it now seems fine. 

I don't know which version I was on but auto update was enabled so it can't have been too far behind. I assume the auto-update grabbed a version that seems to have issues.

**Comment by miigotu** [comment]
Yeah that's the portable virtualenv, it should not be left behind, so I'll look into it.

**Comment by basj** [comment]
This is also happening on my Synology nas. SC wouldn't restart this morning. I have deinstalled and reinstalled using Synology package manager, but the problem remains. SC won't restart at all and makes lots of these pip files in my /tmp until space runs out. If you need info from a synology user, let me know.

**Comment by miigotu** [comment]
f96786115ad62a497a87f92e7eb5ebcd45dce314
