### ISSUE TITLE
Unable to start on Raspbian since last update

### ISSUE THREAD

**Issue by dporem** [SickChill/SickChill#7267]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: raspbian
Browser:
What you did: updated to the last version
What happened: when I try to start, the process times out
What you expected: when I try to start, the process starts
Logs:
```
xpto@raspberrypi:~/.sickchill $ sudo systemctl status sickchill.service
● sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Tue 2021-07-13 15:56:54 BST; 2min 46s ago
  Process: 9013 ExecStart=/usr/bin/python3 /home/pi/.sickchill/SickChill.py -q --daemon --nolaunch --datadir=/home/pi/.sickchill (code=killed,
    Tasks: 0 (limit: 2200)
   Memory: 96.6M
   CGroup: /system.slice/sickchill.service

Jul 13 15:55:24 raspberrypi systemd[1]: Starting SickChill Daemon...
Jul 13 15:56:54 raspberrypi systemd[1]: sickchill.service: Start operation timed out. Terminating.
Jul 13 15:56:54 raspberrypi systemd[1]: sickchill.service: Control process exited, code=killed, status=15/TERM
Jul 13 15:56:54 raspberrypi systemd[1]: sickchill.service: Failed with result 'timeout'.
Jul 13 15:56:54 raspberrypi systemd[1]: Failed to start SickChill Daemon.
```

**Comment by jbalicki10** [comment]
Can you run:
/home/pi/.sickchill/SickChill.py --daemon --nolaunch --datadir=/home/pi/.sickchill

This will give us verbose output

**Comment by dporem** [comment]
pi@raspberrypi:~/.sickchill $ /home/pi/.sickchill/SickChill.py --daemon --nolaunch --datadir=/home/pi/.sickchill
sickchill found: False
Current environment is not writable!
Restarting SickChill with ['/home/pi/.sickchill/.venv/bin/python3.7', '/home/pi/.sickchill/SickChill.py', '--daemon', '--nolaunch', '--datadir=/home/pi/.sickchill']
sickchill found: False
pip found: True
pip args: /home/pi/.sickchill/.venv/bin/python3.7 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qqU setuptools poetry --pre
poetry found: True
pip args: /home/pi/.sickchill/.venv/bin/python3.7 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qqU appdirs==1.4.4 babelfish==0.5.5 beautifulsoup4==4.9.3 beekeeper==0.9.2 bencode.py==4.0.0 cachecontrol==0.12.6; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") certifi==2021.5.30; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" cffi==1.14.6; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" or python_full_version >= "3.5.0" and python_version >= "3.6" chardet==4.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") click==8.0.1; python_version >= "3.6" cloudscraper==1.2.58 colorama==0.4.4; python_version >= "3.6" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.6" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==3.4.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" decorator==5.0.9; python_version >= "3.5" deluge-client==1.9.0 deprecated==1.2.12; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.3; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.8; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.0; python_version >= "3" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3" guessit==3.3.1 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.19.1 idna==2.10; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" ifaddr==0.1.7 imagesize==1.2.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2021.4.18 importlib-metadata==1.7.0; python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_version < "3.8" and python_version >= "3.6" and python_full_version >= "3.5.0" or python_version >= "2.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.2 kodipydent==0.3.1 lxml==4.6.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.1.4; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") markdown2==2.4.0; python_version >= "3.5" and python_version < "4" markupsafe==2.0.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" msgpack==1.0.2; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" new-rtorrent-python==1.0.1a0 oauthlib==3.1.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==20.9; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pbr==5.6.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.20; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.1.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.4.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pynma==1.0 pyopenssl==20.0.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") pyparsing==2.4.7; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" or python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==5.0.2; python_version >= "3.6" python-twitter==3.5 python3-fanart==2.0.0 pytz==2021.1 qbittorrent-api==2021.5.22 rarfile==4.0 rebulk==3.0.1 requests-oauthlib==1.3.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests-toolbelt==0.9.1 requests==2.25.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") send2trash==1.7.1 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" or python_full_version >= "3.5.0" or python_version >= "3.4" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" and python_version >= "3.4" or python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" soupsieve==2.2.1; python_version >= "3.6" sqlalchemy==1.4.20; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.3.0; python_version >= "3.6" subliminal==2.1.0 temp-babelfish==0.5.6.dev0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") text-unidecode==1.3; python_version >= "3.6" timeago==1.0.15 tmdbsimple==2.8.0 tornado==6.1; python_version >= "3.5" tus.py==1.3.4 tvdbsimple==1.0.6 tzlocal==2.1 unidecode==1.2.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") urllib3==1.26.6; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version < "4" validators==0.18.2; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.12.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" xmltodict==0.10.1 zipp==3.5.0; python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_version < "3.8" and python_version >= "3.6" and python_full_version >= "3.5.0"
sickchill found: False

**Comment by tmdelia** [comment]
I'm having a similar issue since update. I tried this:

sudo git reset --hard origin/master
sudo git pull https://github.com/SickChill/SickChill.git

It still won't load:

 sickchill.service - LSB: starts instance of SickChill
   Loaded: loaded (/etc/init.d/sickchill; generated)
   Active: active (exited) since Tue 2021-07-13 16:23:35 CDT; 6s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1661 ExecStart=/etc/init.d/sickchill start (code=exited, status=0/SUCCESS)

Jul 13 16:23:35 mediapi systemd[1]: Starting LSB: starts instance of SickChill...
Jul 13 16:23:35 mediapi sickchill[1661]: Starting SickChill
Jul 13 16:23:35 mediapi systemd[1]: Started LSB: starts instance of SickChill.
Jul 13 16:23:35 mediapi sickchill[1661]: Writing PID: 1668 to /home/pi/.sickchill.pid

**Comment by miigotu** [comment]
> pi@raspberrypi:~/.sickchill $ /home/pi/.sickchill/SickChill.py --daemon --nolaunch --datadir=/home/pi/.sickchill
> sickchill found: False
> Current environment is not writable!
> Restarting SickChill with ['/home/pi/.sickchill/.venv/bin/python3.7', '/home/pi/.sickchill/SickChill.py', '--daemon', '--nolaunch', '--datadir=/home/pi/.sickchill']
> sickchill found: False
> pip found: True
> pip args: /home/pi/.sickchill/.venv/bin/python3.7 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qqU setuptools poetry --pre
> poetry found: True
> pip args: /home/pi/.sickchill/.venv/bin/python3.7 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qqU appdirs==1.4.4 babelfish==0.5.5 beautifulsoup4==4.9.3 beekeeper==0.9.2 bencode.py==4.0.0 cachecontrol==0.12.6; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") certifi==2021.5.30; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" cffi==1.14.6; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" or python_full_version >= "3.5.0" and python_version >= "3.6" chardet==4.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") click==8.0.1; python_version >= "3.6" cloudscraper==1.2.58 colorama==0.4.4; python_version >= "3.6" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.6" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==3.4.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" decorator==5.0.9; python_version >= "3.5" deluge-client==1.9.0 deprecated==1.2.12; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.3; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.8; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.0; python_version >= "3" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3" guessit==3.3.1 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.19.1 idna==2.10; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" ifaddr==0.1.7 imagesize==1.2.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2021.4.18 importlib-metadata==1.7.0; python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_version < "3.8" and python_version >= "3.6" and python_full_version >= "3.5.0" or python_version >= "2.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.2 kodipydent==0.3.1 lxml==4.6.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.1.4; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") markdown2==2.4.0; python_version >= "3.5" and python_version < "4" markupsafe==2.0.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" msgpack==1.0.2; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" new-rtorrent-python==1.0.1a0 oauthlib==3.1.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==20.9; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pbr==5.6.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.20; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.1.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.4.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pynma==1.0 pyopenssl==20.0.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") pyparsing==2.4.7; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" or python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==5.0.2; python_version >= "3.6" python-twitter==3.5 python3-fanart==2.0.0 pytz==2021.1 qbittorrent-api==2021.5.22 rarfile==4.0 rebulk==3.0.1 requests-oauthlib==1.3.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests-toolbelt==0.9.1 requests==2.25.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") send2trash==1.7.1 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" or python_full_version >= "3.5.0" or python_version >= "3.4" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" and python_version >= "3.4" or python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" soupsieve==2.2.1; python_version >= "3.6" sqlalchemy==1.4.20; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.3.0; python_version >= "3.6" subliminal==2.1.0 temp-babelfish==0.5.6.dev0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") text-unidecode==1.3; python_version >= "3.6" timeago==1.0.15 tmdbsimple==2.8.0 tornado==6.1; python_version >= "3.5" tus.py==1.3.4 tvdbsimple==1.0.6 tzlocal==2.1 unidecode==1.2.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") urllib3==1.26.6; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version < "4" validators==0.18.2; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.12.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" xmltodict==0.10.1 zipp==3.5.0; python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_version < "3.8" and python_version >= "3.6" and python_full_version >= "3.5.0"
> sickchill found: False

This is exactly what it is suppose to do, leave it running.

**Comment by miigotu** [comment]
> I'm having a similar issue since update. I tried this:
> 
> sudo git reset --hard origin/master
> sudo git pull https://github.com/SickChill/SickChill.git
> 
> It still won't load:
> 
> sickchill.service - LSB: starts instance of SickChill
> Loaded: loaded (/etc/init.d/sickchill; generated)
> Active: active (exited) since Tue 2021-07-13 16:23:35 CDT; 6s ago
> Docs: man:systemd-sysv-generator(8)
> Process: 1661 ExecStart=/etc/init.d/sickchill start (code=exited, status=0/SUCCESS)
> 
> Jul 13 16:23:35 mediapi systemd[1]: Starting LSB: starts instance of SickChill...
> Jul 13 16:23:35 mediapi sickchill[1661]: Starting SickChill
> Jul 13 16:23:35 mediapi systemd[1]: Started LSB: starts instance of SickChill.
> Jul 13 16:23:35 mediapi sickchill[1661]: Writing PID: 1668 to /home/pi/.sickchill.pid

That is loaded.... it wrote the pid file and forked.

**Comment by dporem** [comment]
> > pi@raspberrypi:~/.sickchill $ /home/pi/.sickchill/SickChill.py --daemon --nolaunch --datadir=/home/pi/.sickchill
> > sickchill found: False
> > Current environment is not writable!
> > Restarting SickChill with ['/home/pi/.sickchill/.venv/bin/python3.7', '/home/pi/.sickchill/SickChill.py', '--daemon', '--nolaunch', '--datadir=/home/pi/.sickchill']
> > sickchill found: False
> > pip found: True
> > pip args: /home/pi/.sickchill/.venv/bin/python3.7 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qqU setuptools poetry --pre
> > poetry found: True
> > pip args: /home/pi/.sickchill/.venv/bin/python3.7 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qqU appdirs==1.4.4 babelfish==0.5.5 beautifulsoup4==4.9.3 beekeeper==0.9.2 bencode.py==4.0.0 cachecontrol==0.12.6; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") certifi==2021.5.30; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" cffi==1.14.6; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" or python_full_version >= "3.5.0" and python_version >= "3.6" chardet==4.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") click==8.0.1; python_version >= "3.6" cloudscraper==1.2.58 colorama==0.4.4; python_version >= "3.6" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.6" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==3.4.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" decorator==5.0.9; python_version >= "3.5" deluge-client==1.9.0 deprecated==1.2.12; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.3; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.8; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.0; python_version >= "3" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3" guessit==3.3.1 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.19.1 idna==2.10; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" ifaddr==0.1.7 imagesize==1.2.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2021.4.18 importlib-metadata==1.7.0; python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_version < "3.8" and python_version >= "3.6" and python_full_version >= "3.5.0" or python_version >= "2.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.2 kodipydent==0.3.1 lxml==4.6.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.1.4; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") markdown2==2.4.0; python_version >= "3.5" and python_version < "4" markupsafe==2.0.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" msgpack==1.0.2; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" new-rtorrent-python==1.0.1a0 oauthlib==3.1.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==20.9; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pbr==5.6.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.20; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.1.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.4.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pynma==1.0 pyopenssl==20.0.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") pyparsing==2.4.7; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" or python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==5.0.2; python_version >= "3.6" python-twitter==3.5 python3-fanart==2.0.0 pytz==2021.1 qbittorrent-api==2021.5.22 rarfile==4.0 rebulk==3.0.1 requests-oauthlib==1.3.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests-toolbelt==0.9.1 requests==2.25.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") send2trash==1.7.1 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" or python_full_version >= "3.5.0" or python_version >= "3.4" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" and python_version >= "3.4" or python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" soupsieve==2.2.1; python_version >= "3.6" sqlalchemy==1.4.20; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.3.0; python_version >= "3.6" subliminal==2.1.0 temp-babelfish==0.5.6.dev0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") text-unidecode==1.3; python_version >= "3.6" timeago==1.0.15 tmdbsimple==2.8.0 tornado==6.1; python_version >= "3.5" tus.py==1.3.4 tvdbsimple==1.0.6 tzlocal==2.1 unidecode==1.2.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") urllib3==1.26.6; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version < "4" validators==0.18.2; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.12.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" xmltodict==0.10.1 zipp==3.5.0; python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_version < "3.8" and python_version >= "3.6" and python_full_version >= "3.5.0"
> > sickchill found: False
> 
> This is exactly what it is suppose to do, leave it running.

The service doesn't start, timesout (like you can see on my first post) and I cannot access it on the browser due to that.

**Comment by miigotu** [comment]
@dporem I dont need hundreds of lines of logs, just around the error unless I ask for it, and wrap the logs with \`\`\` on the line before the log and \`\`\` on the line after the log.

**Comment by miigotu** [comment]
@dporem that log you showed me is not a timed out service. If it forked, it is running.

**Comment by miigotu** [comment]
I think some people confuse the `sickchill found: False` as sickchill not being found at all. Thats just saying it isnt installed with pip.

**Comment by miigotu** [comment]
@dporem also, yours is not updated to the latest code.

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/commit/6898f93be7fd1b79f0283298de2470f07478ca77

**Comment by dporem** [comment]
> @dporem that log you showed me is not a timed out service. If it wrote the pid file, it is running.

just noticed now, you are right, I can now access it, I guess my "normal" startservice command doesn't work anymore ?
@miigotu thanks for your help and yes the "sickchill found: False" doesn't help :)

**Comment by tmdelia** [comment]
> > I'm having a similar issue since update. I tried this:
> > sudo git reset --hard origin/master
> > sudo git pull https://github.com/SickChill/SickChill.git
> > It still won't load:
> > sickchill.service - LSB: starts instance of SickChill
> > Loaded: loaded (/etc/init.d/sickchill; generated)
> > Active: active (exited) since Tue 2021-07-13 16:23:35 CDT; 6s ago
> > Docs: man:systemd-sysv-generator(8)
> > Process: 1661 ExecStart=/etc/init.d/sickchill start (code=exited, status=0/SUCCESS)
> > Jul 13 16:23:35 mediapi systemd[1]: Starting LSB: starts instance of SickChill...
> > Jul 13 16:23:35 mediapi sickchill[1661]: Starting SickChill
> > Jul 13 16:23:35 mediapi systemd[1]: Started LSB: starts instance of SickChill.
> > Jul 13 16:23:35 mediapi sickchill[1661]: Writing PID: 1668 to /home/pi/.sickchill.pid
> 
> That is loaded.... it wrote the pid file and forked. It is running.

Yes, it wrote the .pid file, but it refuses to connect to the service.
![Capture](https://user-images.githubusercontent.com/19365008/125529681-10b971b8-fdba-4b12-b70c-d413b430eb49.JPG)

**Comment by miigotu** [comment]
@tmdelia you have to let it go for a few minutes and then try the browser. There is a delay between started and web ui accessible.

**Comment by tmdelia** [comment]
@miigotu It's been hours:

● sickchill.service - LSB: starts instance of SickChill
   Loaded: loaded (/etc/init.d/sickchill; generated)
   Active: active (exited) since Tue 2021-07-13 17:23:15 CDT; 6h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 449 ExecStart=/etc/init.d/sickchill start (code=exited, status=0/SUCCESS)

Jul 13 17:23:13 mediapi systemd[1]: Starting LSB: starts instance of SickChill...
Jul 13 17:23:13 mediapi sickchill[449]: Starting SickChill
Jul 13 17:23:15 mediapi systemd[1]: Started LSB: starts instance of SickChill.
Jul 13 17:23:15 mediapi sickchill[449]: Writing PID: 526 to /home/pi/.sickchill.pid

It's now 23:26.

**Comment by miigotu** [comment]
I think there has been quite a few commits since the last few hours. Anyways, you should git pull and also do this:
https://github.com/SickChill/SickChill/discussions/7281
