### ISSUE TITLE
AttributeError: module 'site' has no attribute 'getsitepackages'

### ISSUE THREAD

**Issue by egrueda** [SickChill/SickChill#7268]
Raspbian OS 10.10, up to date to master branch

Module "site" fails when running from virtualenv
When run "SickChill.py"

Logs:
```
$ ./SickChill.py 
sickchill found: False
We always run from virtualenv when running from source
Restarting SickChill with ['/opt/sc/.venv/bin/python3.7', './SickChill.py']
sickchill found: False
Traceback (most recent call last):
  File "./SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sc/sickchill/__init__.py", line 3, in <module>
    poetry_install()
  File "/opt/sc/sickchill/init_helpers.py", line 214, in poetry_install
    if not check_env_writable():
  File "/opt/sc/sickchill/init_helpers.py", line 110, in check_env_writable
    locations = [site.getsitepackages()[0]]
AttributeError: module 'site' has no attribute 'getsitepackages'
```

**Comment by egrueda** [comment]
Inside directory .venv/lib/python3.7 I can see all links to python libs but one.
Only file which is not a symlink is site.py

**Comment by miigotu** [comment]
@egrueda your virtualenv package is out of date, im trying to figure out another clean way of getting sitepackages

**Comment by paulz-gh** [comment]
Same problem here on FreeBSD 13.0 using python 3.8 after a git pull a few minutes ago.
(commit 1e89497f482e817e1ed757b7f45e16309614738b (HEAD -> master, tag: v2021.07.13-1, origin/master, origin/develop, origin/HEAD))

```
$ sudo service sickchill start
Starting sickchill.
sickchill found: False
Current environment is not writable!
Because of the above errors, we will try creating a new virtualenvironment in /opt/SickChill-py3/SickChill/.venv
virtualenv found: True
Command result: Already using interpreter /usr/local/bin/python3.8
Using base prefix '/usr/local'
New python executable in /opt/SickChill-py3/SickChill/.venv/bin/python3.8
Also creating executable in /opt/SickChill-py3/SickChill/.venv/bin/python
Installing setuptools, pip, wheel...
done.

Created new virtualenvironment in /opt/SickChill-py3/SickChill/.venv
Restarting SickChill with ['/opt/SickChill-py3/SickChill/.venv/bin/python3.8', '/opt/SickChill-py3/SickChill/SickChill.py', '--datadir', '/var/db/sickchill', '-d', '--pidfile', '/var/run/sickchill/sickchill.pid', '-q', '--nolaunch']
sickchill found: False
Traceback (most recent call last):
  File "/opt/SickChill-py3/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/SickChill-py3/SickChill/sickchill/__init__.py", line 3, in <module>
    poetry_install()
  File "/opt/SickChill-py3/SickChill/sickchill/init_helpers.py", line 211, in poetry_install
    if not check_env_writable():
  File "/opt/SickChill-py3/SickChill/sickchill/init_helpers.py", line 108, in check_env_writable
    locations = [site.getsitepackages()[0]]
AttributeError: module 'site' has no attribute 'getsitepackages'
/usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill
```

**Comment by egrueda** [comment]
> @egrueda delete the .venv dir and start again

Already did it. Same result.
Even with a fresh installation

**Comment by miigotu** [comment]
> Same problem here on FreeBSD 13.0 using python 3.8 after a git pull a few minutes ago.
> (commit [1e89497](https://github.com/SickChill/SickChill/commit/1e89497f482e817e1ed757b7f45e16309614738b) (HEAD -> master, tag: v2021.07.13-1, origin/master, origin/develop, origin/HEAD))
> 
> ```
> $ sudo service sickchill start
> Starting sickchill.
> sickchill found: False
> Current environment is not writable!
> Because of the above errors, we will try creating a new virtualenvironment in /opt/SickChill-py3/SickChill/.venv
> virtualenv found: True
> Command result: Already using interpreter /usr/local/bin/python3.8
> Using base prefix '/usr/local'
> New python executable in /opt/SickChill-py3/SickChill/.venv/bin/python3.8
> Also creating executable in /opt/SickChill-py3/SickChill/.venv/bin/python
> Installing setuptools, pip, wheel...
> done.
> 
> Created new virtualenvironment in /opt/SickChill-py3/SickChill/.venv
> Restarting SickChill with ['/opt/SickChill-py3/SickChill/.venv/bin/python3.8', '/opt/SickChill-py3/SickChill/SickChill.py', '--datadir', '/var/db/sickchill', '-d', '--pidfile', '/var/run/sickchill/sickchill.pid', '-q', '--nolaunch']
> sickchill found: False
> Traceback (most recent call last):
>   File "/opt/SickChill-py3/SickChill/SickChill.py", line 14, in <module>
>     import sickchill.start
>   File "/opt/SickChill-py3/SickChill/sickchill/__init__.py", line 3, in <module>
>     poetry_install()
>   File "/opt/SickChill-py3/SickChill/sickchill/init_helpers.py", line 211, in poetry_install
>     if not check_env_writable():
>   File "/opt/SickChill-py3/SickChill/sickchill/init_helpers.py", line 108, in check_env_writable
>     locations = [site.getsitepackages()[0]]
> AttributeError: module 'site' has no attribute 'getsitepackages'
> /usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill
> ```

https://github.com/SickChill/SickChill/issues/7268#issuecomment-879240229

**Comment by miigotu** [comment]
fixed.
