### ISSUE TITLE
SickChill Still Not Starting on Centos 8

### ISSUE THREAD

**Issue by potequity** [SickChill/SickChill#7270]
@miigotu It still fails to start. The original issue was closed so I had to open a new one, sorry about that.

Branch/Commit:
OS: Centos 8
Browser: Firefox
What you did: 

Ran usr/bin/env python3.6 /home/SickChill/SickChill.py -q --daemon --nolaunch --datadir /home/SickChill/sickchill

What happened:

sickchill@linux01 sickchill]$ /usr/bin/env python3.6 /home/SickChill/SickChill.py -q --daemon --nolaunch --datadir /home/SickChill/sickchill
sickchill found: False
Current environment is not writable!
Because of the above errors, we will try creating a new virtualenvironment in /home/SickChill/.venv
virtualenv found: True
Command result: created virtual environment CPython3.6.8.final.0-64 in 512ms
  creator CPython3Posix(dest=/home/SickChill/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/SickChill/.local/share/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Created new virtualenvironment in /home/SickChill/.venv
Restarting SickChill with ['/home/SickChill/.venv/bin/python3.6', '/home/SickChill/SickChill.py', '-q', '--daemon', '--nolaunch', '--datadir', '/home/SickChill/sickchill']
sickchill found: False
pip found: False
Installing pip
Traceback (most recent call last):
  File "/home/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/home/SickChill/sickchill/__init__.py", line 3, in <module>
    poetry_install()
  File "/home/SickChill/sickchill/init_helpers.py", line 222, in poetry_install
    check_and_install_pip()
  File "/home/SickChill/sickchill/init_helpers.py", line 129, in check_and_install_pip
    tfd = download_to_temp_file("https://bootstrap.pypa.io/get-pip.py", suffix=".py", prefix="get-pip")
TypeError: download_to_temp_file() got an unexpected keyword argument 'suffix'
[sickchill@linux01 sickchill]$

What you expected:
Logs:
```
[sickchill@linux01 sickchill]$ /usr/bin/env python3.6 /home/SickChill/sickchill/SickChill.py -q --daemon --nolaunch --datadir /home/SickChill/sickchill
python3.6: can't open file '/home/SickChill/sickchill/SickChill.py': [Errno 2] No such file or directory
[sickchill@linux01 sickchill]$ /usr/bin/env python3.6 /home/SickChill/SickChill.py -q --daemon --nolaunch --datadir /home/SickChill/sickchill
sickchill found: False
Current environment is not writable!
Because of the above errors, we will try creating a new virtualenvironment in /home/SickChill/.venv
virtualenv found: True
Command result: created virtual environment CPython3.6.8.final.0-64 in 512ms
  creator CPython3Posix(dest=/home/SickChill/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/SickChill/.local/share/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Created new virtualenvironment in /home/SickChill/.venv
Restarting SickChill with ['/home/SickChill/.venv/bin/python3.6', '/home/SickChill/SickChill.py', '-q', '--daemon', '--nolaunch', '--datadir', '/home/SickChill/sickchill']
sickchill found: False
pip found: False
Installing pip
Traceback (most recent call last):
  File "/home/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/home/SickChill/sickchill/__init__.py", line 3, in <module>
    poetry_install()
  File "/home/SickChill/sickchill/init_helpers.py", line 222, in poetry_install
    check_and_install_pip()
  File "/home/SickChill/sickchill/init_helpers.py", line 129, in check_and_install_pip
    tfd = download_to_temp_file("https://bootstrap.pypa.io/get-pip.py", suffix=".py", prefix="get-pip")
TypeError: download_to_temp_file() got an unexpected keyword argument 'suffix'
[sickchill@linux01 sickchill]$

```

-PE

**Comment by potequity** [comment]
@miigotu in case you need it....

[sickchill@linux01 ~]$ ls -al /home/SickChill/.venv/{libexec,bin,tools}
ls: cannot access '/home/SickChill/.venv/libexec': No such file or directory
ls: cannot access '/home/SickChill/.venv/tools': No such file or directory
/home/SickChill/.venv/bin:
total 60
drwxrwxr-x. 2 sickchill sickchill 4096 Jul 13 12:55 .
drwxrwxr-x. 5 sickchill sickchill   77 Jul 13 12:55 ..
-rw-rw-r--. 1 sickchill sickchill 2137 Jul 13 12:55 activate
-rw-rw-r--. 1 sickchill sickchill 1429 Jul 13 12:55 activate.csh
-rw-rw-r--. 1 sickchill sickchill 3060 Jul 13 12:55 activate.fish
-rw-rw-r--. 1 sickchill sickchill 1751 Jul 13 12:55 activate.ps1
-rw-rw-r--. 1 sickchill sickchill 1232 Jul 13 12:55 activate_this.py
-rw-rw-r--. 1 sickchill sickchill 1151 Jul 13 12:55 activate.xsh
-rwxrwxr-x. 1 sickchill sickchill  237 Jul 13 12:55 pip
-rwxrwxr-x. 1 sickchill sickchill  237 Jul 13 12:55 pip3
-rwxrwxr-x. 1 sickchill sickchill  237 Jul 13 12:55 pip-3.6
-rwxrwxr-x. 1 sickchill sickchill  237 Jul 13 12:55 pip3.6
lrwxrwxrwx. 1 sickchill sickchill   18 Jul 13 12:55 python -> /usr/bin/python3.6
lrwxrwxrwx. 1 sickchill sickchill    6 Jul 13 12:55 python3 -> python
lrwxrwxrwx. 1 sickchill sickchill    6 Jul 13 12:55 python3.6 -> python
-rwxrwxr-x. 1 sickchill sickchill  224 Jul 13 12:55 wheel
-rwxrwxr-x. 1 sickchill sickchill  224 Jul 13 12:55 wheel3
-rwxrwxr-x. 1 sickchill sickchill  224 Jul 13 12:55 wheel-3.6
-rwxrwxr-x. 1 sickchill sickchill  224 Jul 13 12:55 wheel3.6
[sickchill@linux01 ~]$

**Comment by miigotu** [comment]
Different error, already fixed. https://github.com/SickChill/SickChill/commit/3ea8b7975a17c73575b0dccd41dc99b0b46daf3c

**Comment by potequity** [comment]
@miigotu You're AWESOME! That did the trick and the service starts/stops through systemctl. Again, thank you for taking the time to help with this issue and the quick turnaround!! I can't begin to imagine how many issues you have to deal with on a daily basis. If you ever need to test stuff on a Centos platform, just ping me and I'd be more than happy to test it for you.

Thanks a million!

-PE
