### ISSUE TITLE
Unable to Start on macOS

### ISSUE THREAD

**Issue by Torhal** [SickChill/SickChill#7276]
After updating to `sickchill-2021.7.13.post4` SickChill will not start, instead giving the following error:

Checking poetry
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/SickChill.py", line 16, in <module>
    from sickchill.init_helpers import check_installed, setup_gettext, setup_lib_path
ImportError: cannot import name 'setup_lib_path' from 'sickchill.init_helpers' (/Users/redacted/Library/Python/3.8/lib/python/site-packages/sickchill/init_helpers.py)

**Comment by miigotu** [comment]
You arent starting the correct SickChill.py, because `setup_lib_path` does not exist anymore.

**Comment by Torhal** [comment]
Interesting. I updated as I regularly do, then used my shell's history to re-run the SickChill per normal. I'll have to look in the path to see where the new one was installed.

Thanks!

**Comment by miigotu** [comment]
Likely `/Users/redacted/Library/Python/3.8/lib/python/bin/SickChill.py`

**Comment by Torhal** [comment]
That fixed it. Thanks again!
