### ISSUE TITLE
MAKO error when trying to update

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#7287]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

 SickChill Info:
Install: pip
Version: v2021.07.12-6
Database Version: 44.2

  Python Version:3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
  SSL Version:OpenSSL 1.1.1k 25 Mar 2021
  OS:Windows-10-10.0.19042-SP0
  Locale:en_US.cp1252

Browser: Microsoft Edge or Google Chrome
What you did: Tried to update by clicking "Update Now"
What happened: 

![image](https://user-images.githubusercontent.com/18516066/125604499-6975112f-3de1-4d4d-bd3a-c0b1641a9b7c.png)

What you expected: Normal update

Logs:  *from the above page*
```
Traceback (most recent call last):
File C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py:188, in async_call:
return function(**kwargs)
File C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\home.py:687, in update:
if updater.update():
File C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\runner.py:308, in update:
return self.updater.update()
File C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\pip.py:79, in update:
settings.CUR_COMMIT_HASH = self._newest_version
AttributeError: 'PipUpdateManager' object has no attribute '_newest_commit_hash'
```

Logs:  *from log*
```
2021-07-14 06:07:12 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: 'PipUpdateManager' object has no attribute '_newest_commit_hash'
```

By entering `localhost:8081` in the browser URL line, SC restarts (but still needing the update)

And I am using the 6.0 installer and downloaded a new install of SC yesterday.

**Comment by miigotu** [comment]
Back up inside SC, reinstall again, restore. The commit you are on existed for like 10 minutes lol.

**Comment by ronrosenfeld** [comment]
Thanks for the prompt response.  

But this seems odd:  I had to reboot my computer to do some other unrelated stuff.  When I came back to SC to do this re-install, there was no prompt for an update and it was running `Version: v2021.07.14-1`

Seems that rebooting the OS took care of whatever was causing the MAKO error.  Does that make sense?

**Comment by miigotu** [comment]
If you have auto update on, yes.

**Comment by ronrosenfeld** [comment]
@miigotu  Auto update (in SC) is not enabled.
