### ISSUE TITLE
Some good news....   My show listing is now working after installing from scratch the recommended download.

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#7291]
Some good news....   My show listing is now working after installing from scratch the recommended download.
Made no system changes or system updates.  It also used my database and config file without issue.
What a wonderful sight...

![image](https://user-images.githubusercontent.com/14140816/125617055-29e43bee-488a-45d4-a9ba-98e12d9b4b2a.png)

![image](https://user-images.githubusercontent.com/14140816/125616852-3be8c258-e21e-4075-a71b-0a76ec00e008.png)

Now it shows an update is waiting to get installed....

Should I take it,  I really don't want to loose whats working now......

**Comment by peppermintesse** [comment]
I'm glad for you (I had to restore from a Time Machine backup to get my setup working again). However, this probably belongs in Discussions, not Issues, FWIW.
