### ISSUE TITLE
Issues starting on synology after update

### ISSUE THREAD

**Issue by spudsrus** [SickChill/SickChill#7293]
(Base install from SynoCommmunity package)
Branch/Commit: Master/9890d406bd9e84d945a6beddfbd80b9d30f26bd3
OS: DSM 6.2.4-25556
Browser: N/A
What you did: Updated SickChill to latest commit and waited for it to restart.
What happened: It did not restart after the update.
If I run it from package center it hangs then doesn't load with a generic 'failed to run the package service' error.
Uninstalled the package and reinstalled from synocommunity, started fine though was of course missing config.
Went to attempt an update before restoring config from latest backup and had the same behaviour.

What you expected: Expected it to run after the update.
Logs:
```
/volume1/@appstore/sickchill/var/sickchill.log

Wed Jul 14 21:19:56 CST 2021
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data
Writing PID: 30528 to /volume1/@appstore/sickchill/var/sickchill.pid
```
Not sure if it's supposed to be created but I don't see any /volume1/@appstore/sickchill/var/sickchill.pid file.
extracts from the install logs:
```
===> Step postinst. USER=sickchill GROUP=sc-download SHARE_PATH=
Installing service configuration /var/packages/sickchill/conf/sickchill.sc
Adding 'sc-sickchill' to 'sc-download'
Group Name: [sc-download]
Group Type: [AUTH_LOCAL]
Group ID:   [65537]
Group Members:
0:[couchpotatoserver]
1:[sc-couchpotatoserver-custom]
2:[spuddles]
3:[sc-sickbeard-custom]
4:[sc-sickchill]
Invoke service_postinst
created virtual environment CPython3.7.10.final.0-64 in 262ms
  creator CPython3Posix(dest=/volume1/@appstore/sickchill/env, clear=False, global=True)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Looking in links: /volume1/@appstore/sickchill/share/wheelhouse
```
And 
```
Installing collected packages: CacheControl, Deprecated, IMDbPY, Js2Py, Mako, MarkupSafe, PyGithub, PyJWT, PyNMA, PySocks, SQLAlchemy, Send2Trash, Unidecode, appdirs, attrdict, babelfish, beautifulsoup4, bencode.py, certifi, chardet, click, cloudscraper, configobj, decorator, deluge-client, dogpile.cache, enzyme, feedparser, future, gntp, guessit, html5lib, httplib2, idna, ifaddr, imagesize, ipaddress, jsonrpclib-pelix, markdown2, msgpack, new-rtorrent-python, oauthlib, packaging, pbr, profilehooks, putio.py, pyOpenSSL, pyaes, pycparser, pyjsparser, pymediainfo, pyparsing, pysrt, python3-fanart, python-dateutil, python-slugify, python-twitter, pytz, qbittorrent-api, rarfile, rebulk, requests, requests-oauthlib, requests-toolbelt, sgmllib3k, six, soupsieve, stevedore, subliminal, text-unidecode, timeago, tmdbsimple, tornado, tus.py, tvdbsimple, twilio, tzlocal, urllib3, validators, webencodings, win-inet-pton, wrapt, xmltodict
  Attempting uninstall: MarkupSafe
    Found existing installation: MarkupSafe 1.1.1
    Not uninstalling markupsafe at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/sickchill/env
    Can't uninstall 'MarkupSafe'. No files were found to uninstall.
  Attempting uninstall: SQLAlchemy
    Found existing installation: SQLAlchemy 1.3.13
    Not uninstalling sqlalchemy at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/sickchill/env
    Can't uninstall 'SQLAlchemy'. No files were found to uninstall.
  Attempting uninstall: appdirs
    Found existing installation: appdirs 1.4.3
    Not uninstalling appdirs at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/sickchill/env
    Can't uninstall 'appdirs'. No files were found to uninstall.
  Attempting uninstall: idna
    Found existing installation: idna 2.9
    Not uninstalling idna at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/sickchill/env
    Can't uninstall 'idna'. No files were found to uninstall.
  Attempting uninstall: ipaddress
    Found existing installation: ipaddress 1.0.23
    Not uninstalling ipaddress at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/sickchill/env
    Can't uninstall 'ipaddress'. No files were found to uninstall.
  Attempting uninstall: pyOpenSSL
    Found existing installation: pyOpenSSL 19.1.0
    Not uninstalling pyopenssl at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/sickchill/env
    Can't uninstall 'pyOpenSSL'. No files were found to uninstall.
  Attempting uninstall: pycparser
    Found existing installation: pycparser 2.19
    Not uninstalling pycparser at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/sickchill/env
    Can't uninstall 'pycparser'. No files were found to uninstall.
  Attempting uninstall: six
    Found existing installation: six 1.14.0
    Not uninstalling six at /volume1/@appstore/python3/lib/python3.7/site-packages, outside environment /volume1/@appstore/sickchill/env
    Can't uninstall 'six'. No files were found to uninstall.
Successfully installed CacheControl-0.12.6 Deprecated-1.2.10 IMDbPY-2020.9.25 Js2Py-0.70 Mako-1.1.3 MarkupSafe-1.1.1 PyGithub-1.53 PyJWT-1.7.1 PyNMA-1.0 PySocks-1.7.1 SQLAlchemy-1.3.20 Send2Trash-1.5.0 Unidecode-1.1.1 appdirs-1.4.4 attrdict-2.0.1 babelfish-0.5.5 beautifulsoup4-4.9.3 bencode.py-4.0.0 certifi-2020.11.8 chardet-3.0.4 click-7.1.2 cloudscraper-1.2.48 configobj-5.0.6 decorator-4.4.2 deluge-client-1.9.0 dogpile.cache-1.0.2 enzyme-0.4.1 feedparser-6.0.2 future-0.18.2 gntp-1.0.3 guessit-3.1.1 html5lib-1.1 httplib2-0.18.1 idna-2.10 ifaddr-0.1.7 imagesize-1.2.0 ipaddress-1.0.23 jsonrpclib-pelix-0.4.2 markdown2-2.3.10 msgpack-1.0.0 new-rtorrent-python-1.0.1a0 oauthlib-3.1.0 packaging-20.4 pbr-5.5.1 profilehooks-1.12.0 putio.py-8.7.0 pyOpenSSL-19.1.0 pyaes-1.6.1 pycparser-2.20 pyjsparser-2.7.1 pymediainfo-4.3 pyparsing-2.4.7 pysrt-1.1.2 python-dateutil-2.8.1 python-slugify-4.0.1 python-twitter-3.5 python3-fanart-2.0.0 pytz-2020.4 qbittorrent-api-2020.10.11 rarfile-4.0 rebulk-2.0.1 requests-2.24.0 requests-oauthlib-1.3.0 requests-toolbelt-0.9.1 sgmllib3k-1.0.0 six-1.15.0 soupsieve-2.0.1 stevedore-3.2.2 subliminal-2.1.0 text-unidecode-1.3 timeago-1.0.14 tmdbsimple-2.6.6 tornado-6.1 tus.py-1.3.4 tvdbsimple-1.0.6 twilio-6.47.0 tzlocal-2.1 urllib3-1.26.0 validators-0.18.1 webencodings-0.5.1 win-inet-pton-1.1.0 wrapt-1.12.1 xmltodict-0.10.1

```

Sorry if this is something stupid that I've done or if I should be waiting on a branch update.

**Comment by thatcow** [comment]
I've got the same issue with mine. The original installation commit runs fine but bringing it up to latest breaks it.

**Comment by thatcow** [comment]
As was hinted in another thread here. Cleaning up bad wheels seems to have resolved this for me.

Based on this thread: #7281 

`Log in as root and run "python3 -m pip cache dir | xargs rm -rf"`

**Comment by BKSteve** [comment]
The issue is with the env folder rights 

sudo chown -R sc-sickchill:sickchill /volume1/@appstore/sickchill/env

Works too

**Comment by spudsrus** [comment]
Many thanks guys. 
I used the chown fix which worked for me.

**Comment by BKSteve** [comment]
To be clear to anybody coming in to read this.
Solution to #7279 is also #7281 
I haven't gone through a full reinstall test and will remove this line later if #7281 works with 
`sudo python3 -m pip cache dir | xargs rm -rf`

**Comment by Smiggel** [comment]
@BKSteve Did you do anything else? I re-installed Sickchill using the Synology package. It starts. I then executed the chmod command and ran the update. The package start shortly and then stops running.

The python3 command can't be executed. I get a command unknown in python3, even though the package is installed.

**Comment by miigotu** [comment]
Maybe xargs is not installed? Just run `python3 -m pip cache dir` to get the die that you need to delete, and then sudo rm it.

**Comment by Smiggel** [comment]
Python3 command is not found on my NAS. Even Python 3 package is installed.

**Comment by miigotu** [comment]
@Smiggel it's just not on the path. `/usr/local/python3/bin python -m pip cache dir`

**Comment by miigotu** [comment]
I'm going to try and make a PR to the syno repo later. Or I'll put it in SickChill/synology-sickchill for now

**Comment by tinyhands01** [comment]
I've done both the chown and rm.  Package now starts, but does not appear to be working correctly.
Top shows the daemon running, but nmap from my desktop does not show it responding to any port, let alone default 8081

**Comment by basj** [comment]
> /usr/local/python3/bin python -m pip cache dir

I think you omitted a / and some more there. Should be /usr/local/python3/bin/python3 -m pip cache dir
But that just gives me:
admin@merbasj-nas:/volume1/@appstore/sickchill$ /usr/local/python3/bin/python3 -m pip cache dir
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/python3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/services/homes/admin/.local/lib/python3.7/site-packages/pip/__main__.py", line 9, in <module>
    if sys.path[0] in ("", os.getcwd()):
FileNotFoundError: [Errno 2] No such file or directory

**Comment by kretzu77** [comment]
the same here (synology + sickchill Nyaran v20210329-1) :(

**Comment by BKSteve** [comment]
When I enter
`/var/packages/sickchill/target/env/bin python -m pip cache dir | sudo xargs rm -rf` or
`/var/packages/sickchill/target/env/bin python -m pip cache dir`
This is the response:
`-sh: /var/packages/sickchill/target/env/bin: Is a directory`
similarly
`/usr/local/python3/bin python -m pip cache dir`
`-sh: /usr/local/python3/bin: Is a directory`

This I guess is because the pip version of the 3.7.10 isn't up to the task.

So I installed the 3.8.8 SygnoCommunity package.
`/var/packages/python38/target/bin/python3 -m pip cache dir`
`/volume1/homes/<username>/.cache/pip` this is the username under which I normally run SC.
logged in as root
`/root/.cache/pip`

in both these folders there are also http, selfcheck and wheels folders.
So `/var/packages/python38/target/bin/python3 -m pip cache dir | sudo xargs rm -rf` as both root and <username>

installed SC from SynoCommunity, updated. Still doesn't run. `chown -R` /env and it will run.

**Comment by Smiggel** [comment]
> When I enter
> `/var/packages/sickchill/target/env/bin python -m pip cache dir | sudo xargs rm -rf` or
> `/var/packages/sickchill/target/env/bin python -m pip cache dir`
> This is the response:
> `-sh: /var/packages/sickchill/target/env/bin: Is a directory`
> similarly
> `/usr/local/python3/bin python -m pip cache dir`
> `-sh: /usr/local/python3/bin: Is a directory`
> 
> This I guess is because the pip version of the 3.7.10 isn't up to the task.
> 
> So I installed the 3.8.8 SygnoCommunity package.
> `/var/packages/python38/target/bin/python3 -m pip cache dir`
> `/volume1/homes/<username>/.cache/pip` this is the username under which I normally run SC.
> logged in as root
> `/root/.cache/pip`
> 
> in both these folders there are also http, selfcheck and wheels folders.
> So `/var/packages/python38/target/bin/python3 -m pip cache dir | sudo xargs rm -rf` as both root and
> 
> installed SC from SynoCommunity, updated. Still doesn't run. `chown -R` /env and it will run.

Tried the above, no luck. Package runs, but SC is not reachable in the browser. After a few minutes the packages stops running. :-(

What params do you use for the `chown -R /env` command? When only using this, I got `chown: missing operand after ‘/env’`. And did you execute it as root?

**Comment by BKSteve** [comment]
Sorry, use the full command
`sudo chown -R sc-sickchill:sickchill /volume1/@appstore/sickchill/env`

**Comment by BKSteve** [comment]
Sorry that last one line might be a little unclear, use the full command
`sudo chown -R sc-sickchill:sickchill /volume1/@appstore/sickchill/env`

Then when you restart in package center it will take some time before able to access in the browser. It has to pull all the updates.

**Comment by Smiggel** [comment]
> Sorry that last one line might be a little unclear, use the full command
> `sudo chown -R sc-sickchill:sickchill /volume1/@appstore/sickchill/env`
> 
> Then when you restart in package center it will take some time before able to access in the browser. It has to pull all the updates.

Ok, thanks. Will give it a try later on. Perhaps restoring my backup too early is the problem for me. Will try the above again first, before trying to do a restore.

**Comment by basj** [comment]
> /var/packages/sickchill/target/env/bin python -m pip cache dir | sudo xargs rm -rf

I think it's because a '/' seems to be omited between bin and python. The line should be:
`/var/packages/sickchill/target/env/bin/python -m pip cache dir`

and in the case of python 3.8 it should be something like this:
`/volume1/@appstore/python38/bin/python3.8 -m pip cache dir`

which in my case returns  `/volume1/homes/admin/.cache/pip` when logged in as admin.
But the .cache directory lists as emtpy.

There is a .cache directory in  '/volume1/@appstore/sickchill' which contains:
`drwxrwxrwx 4 sc-sickchill sickchill 4096 Jul 15 23:15 pip
drwxr-xr-x 2 sc-sickchill sickchill 4096 Jul 15 22:56 python-entrypoints`

I did the chown to the env folder too but regardless sickchill not start. 
Or it will start but then after a back restore or hitting update it needs to restart, and it never does.

**Comment by BKSteve** [comment]
Restoring the backup shouldn't be the issue. It's when updating.
Also if you're backup is made under the latest version after restore it won't recognize it actually needs and update.
I'm on DS1019+ and did a reinstall, chown, then update, restore. This means on latest master.
All running.

@basj the advice was remove SC then rm the pip cache folders. So no '/volume1/@appstore/sickchill' once removed.
That said I did not try deleting this .cache in the testing above when trying to start without chown the env folder.

**Comment by BKSteve** [comment]
If you restore a backup that was done with the latest release then the config.ini matches the check and you won't get an update.
To trick an update, shutdown, edit config.ini and set the `cur_commit_hash =` back a version based on master or develop.
I did this once before (develop) changed latest `e1e91c3ec3c90479b556e7e78b48dc3bb81ead01` to `3538c49d69a45f0fa28e13b1728d47b104d52e25` saved and restarted. One update, which grabs the whole tar and updates everything.

**Comment by basj** [comment]
@BKSteve I have done it in the exact order: uninstall, cleaned the pip cache, reinstalled SC, chown the env dir, started SC from package centre, then updated through SC (815 commits behind) after which SC restarts by itself...then SC stops running. I did even get to a  backup restore.

The only difference I see is that I have SC configured to use the master instead of developer.

**Comment by Smiggel** [comment]
Done all the steps above again, with a clean install of the package. No back restore, etc. Still not working. Package runs a few minutes, but the interface never loads and the package stops after a while.

Checking out Medusa and Sonarr now as alternative, until there is a good fix for this issue.

**Comment by BKSteve** [comment]
@Smiggel what is the `uname -a` system mine is  x86_64, what's yours?

**Comment by Smiggel** [comment]
> @Smiggel @basj what is the `uname -a` system mine is x86_64, what's yours?

I have: synology_armadaxp_ds214+

**Comment by basj** [comment]
> > @Smiggel @basj what is the `uname -a` system mine is x86_64, what's yours?
> 
> I have: synology_armadaxp_ds214+

armv5tel GNU/Linux synology_88f6282_213air 
This is my old DS213 running the latest SDM 6

I have another DS720+ with SDM 7 but do not use it for SC.

**Comment by miigotu** [comment]
SynoCommunity/spksrc#4743 might be the fix

**Comment by Smiggel** [comment]
> [SynoCommunity/spksrc#4743](https://github.com/SynoCommunity/spksrc/pull/4743) might be the fix

That would be great! :-)

**Comment by kungktd** [comment]
> To be clear to anybody coming in to read this.
> Solution to #7279 is also #7281
> I haven't gone through a full reinstall test and will remove this line later if #7281 works with
> `sudo python3 -m pip cache dir | xargs rm -rf`
> 
> EDIT: Failed to achieve a start with #7281 only the chown so far on DSM6.

Thank you so much for this solution. Worked great!
