### ISSUE TITLE
Parsing error on series title that includes numbers

### ISSUE THREAD

**Issue by GeckoOBac** [SickChill/SickChill#7296]
It seems that some series with number in the title experience parsing problems that cause the episodes to not be correctly recognized as the number may be picked up by the parses as the episode number.

Example:
Series name: "Night Head 2041"

Result with scene numbering ACTIVE:
`Unable to match [SubsPlease].Night.Head.2041.-.01.(720p).[C69ED2CD].mkv to a show in your database. Parser result: Night Head - [ABS: [2041]] [ANIME VER: 1] [GROUP: SubsPlease] [ABD: False] [ANIME: True] [whichReg: ['anime_ultimate']] Score: 3`
Note: as it can be seen, "2041" has been interpreted as the episode's absolute number.

Result with scene numbering NOT active (indexer numbering):
`The result [SubsPlease].Night.Head.2041.-.01.(1080p).[CE052C62].mkv doesn't seem to match an episode that we are currently trying to snatch, skipping it`

I've also tried adding a scene exception for "Night Head", which also failed similarly.

After every configuration change I made sure to restart SickChill to prevent the issues delineated in https://github.com/SickChill/SickChill/issues/7089.

Show has also been newly added (first episode just aired).

I haven't tried manually downloading the file to check if the post processor recognizes it correctly, however I know for sure that for other series with similar names (e.g. "Shaman King (2021)") the post processing seems to work, however the parentheses may play a role in that, or perhaps the bug is limited just to the search results parser.

**Comment by GeckoOBac** [comment]
I can confirm that the issue seems to be just in the search results parser as the manually downloaded file was correctly recognized and moved into place.

**Comment by GeckoOBac** [comment]
The problem still presents itself and hasn't been solved.

**Comment by nydave69** [comment]
Is this being looked into?
