### ISSUE TITLE
Docker on Synology NAS - Sickchil not opening

### ISSUE THREAD

**Issue by ebaydan777** [SickChill/SickChill#7297]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
Can't access branch/commit but sickchill has been down since the 91 commits the other day on docker for synology NAS. Not sure how to update this to make it work if it's been fixed but I cannot access local url for sickchill since it went down.

What you expected:
Logs:
```

```

**Comment by jpmurray** [comment]
I've been seeing something like this for the past 2 days, but I'm running the SynoCommunity package (not on docker). SickChill _refuses_ to start, but somehow could make it run _once_, and promptly made a backup before starting the latest upgrades from commit, and now it won't start again.

**Comment by lintman** [comment]
> I've been seeing something like this for the past 2 days, but I'm running the SynoCommunity package (not on docker). SickChill _refuses_ to start, but somehow could make it run _once_, and promptly made a backup before starting the latest upgrades from commit, and now it won't start again.

I had the same running the SynoCommunity package; it just stopped and wouldn't run again. I reinstalled the package from https://synocommunity.com/package/sickchill and it works again. No need to uninstall first, do a Manual Install over the top. Make sure you don't click Upgrade Now when you log in as it will break it again.

**Comment by Smiggel** [comment]
Yeah, can confirm it's still broken on a Synology NAS with DSM 6 and without docker. Tried to update agin today, after seeing a lot of new commit. Same problem as before. Package restarts, but never actually starts anymore. :-(

**Comment by basj** [comment]
I have tried it on DSM 6 without docker and on DSM 7 with docker. Same problem. It installs, but once you restore a backup and it need to shutdown and restart or you update to the latest commits and it need to restart, it will not restart.

**Comment by jpmurray** [comment]
> > I've been seeing something like this for the past 2 days, but I'm running the SynoCommunity package (not on docker). SickChill _refuses_ to start, but somehow could make it run _once_, and promptly made a backup before starting the latest upgrades from commit, and now it won't start again.
> 
> I had the same running the SynoCommunity package; it just stopped and wouldn't run again. I reinstalled the package from https://synocommunity.com/package/sickchill and it works again. No need to uninstall first, do a Manual Install over the top. Make sure you don't click Upgrade Now when you log in as it will break it again.

Personally, I decided I was done with the Synology install, and proceeded to get it via Docker on my Raspi Homelab (my NAS doesn't support Docker, sadly).

**Comment by BKSteve** [comment]
DSM has access rights issues caused by the SynoCommunity package, the main /env folder. See #7293

**Comment by Smiggel** [comment]
> DSM has access rights issues caused by the SynoCommunity package, the main /env folder. See #7293
> The chown makes it work 'non docker' DSM6.

Tried it, but not working here. I installed the package from Sycommunity; App starts. I stopped the app, did the chmod command and started the package. Updated Sickchill and then the package stops working. Tried the chmod command again, but no luck. Still broken.

**Comment by arondurkin** [comment]
Same, DSM 6, no docker, synocommunity package, updated to latest sickchill, fine, saw DSM wanted to update Git, did that, sickchill no longer runs.

**Comment by tinyhands01** [comment]
Broken here too.  DSM 6, no Docker, with Git 2.32.0-18.  Sickchill crashed after update, would not start.  Chowned env director then Sickchill process runs for a few minutes but does not bring up listener on port 8081 and eventually exits.  Uninstalled, reinstalled from Synocommunity, and chowned env directory. Currently running, but 815 commits behind.

**Comment by miigotu** [comment]
Docker and synocommunity are not the same.

**Comment by tinyhands01** [comment]
@miigotu To whom are you speaking?  Presumably the non-Docker people posting on a Docker thread?  Maybe it's because, despite the thread title, Docker has nothing to do with the problem.

**Comment by miigotu** [comment]
#7249
