### ISSUE TITLE
ModuleNotFoundError: No module named 'imdb'

### ISSUE THREAD

**Issue by Glider3** [SickChill/SickChill#7300]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 
On branch master. 
Your branch is up-to-date with 'origin/master'.

OS:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

What you did:
Update sickchill (from the GUI) to the latest version

What happened:
The release broke

What you expected:
An updated version

Logs:
```# /usr/bin/python3 /opt/sickchill/SickChill.py --datadir=/opt/sickchill
Checking poetry
Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/sickchill/sickchill/tv.py", line 14, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'
```

So I tried a clean install, same result:
```
# curl https://raw.githubusercontent.com/SickChill/SickChill/master/contrib/debian-ubuntu-install.sh | sudo bash
...
done
Removing Old SickChill Folder And Creating New SickChill Folder
Git Cloning In Progress
Copying Startup Script To systemd
Starting SickChill
# service sickchill status
● sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2021-07-15 12:37:53 CEST; 42s ago
  Process: 4401 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=0/SUCCESS)

Jul 15 12:37:52 nano4 systemd[1]: Starting SickChill Daemon...
Jul 15 12:37:52 nano4 systemd[1]: Started SickChill Daemon.
```

**Comment by miigotu** [comment]
Edit your service and remove --daemon and see what's going on. Probably need to `python3 -m pip install virtualenv`

**Comment by Glider3** [comment]
> Edit your service and remove --daemon and see what's going on. 

Look at the first line in the bugreport after "Logs". I ran the service command manually without the --daemon and -q. But I reran it for you again...

# /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill
Checking poetry
Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/sickchill/sickchill/tv.py", line 14, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'

> Probably need to `python3 -m pip install virtualenv`

# python3 -m pip install virtualenv
Requirement already satisfied: virtualenv in /usr/local/lib/python3.6/dist-packages

Already up to date,


I tried reverting back to the previous git tag, all worked again
# git checkout f42794fb5d8746eeb7fa7462fd3aead87a2b780b
Checking out files: 100% (4206/4206), done.
Note: checking out 'f42794fb5d8746eeb7fa7462fd3aead87a2b780b'.
...
HEAD is now at f42794fb5 HOTFIX: Logging errors calls to logging.exception were not being handled, which caused many users head scratching and confusion as to why thing were not working when they were not working.

And all works fine again... So there was a push between then and master that broke something

**Comment by miigotu** [comment]
Sorry, can't read logs you don't have wrapped in \`\`\` and \`\`\` or are struck through crossed out.

**Comment by miigotu** [comment]
Edit SickChill/sickchill/init_helpers.py at the top change logging.INFO to logging.DEBUG and you will get more info.

**Comment by Glider3** [comment]
> Sorry, can't read logs you don't have wrapped in ``` and ``` or are struck through crossed out.

I edited the inital report to take out the '~', that caused the strikethrough, sorry for that.

> Edit SickChill/sickchill/init_helpers.py at the top change logging.INFO to logging.DEBUG and you will get more info.

\# vi sickchill/init_helpers.py
\# /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill
Checking poetry
sickchill found: True
Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/sickchill/sickchill/tv.py", line 14, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'

**Comment by miigotu** [comment]
`pip uninstall sickchill -y`

You should not have sickchill installed via pip if you are going to run it from git source. Pick one or the other

**Comment by Glider3** [comment]
You should really learn how to read. Installed it via the provided install script.

**Comment by miigotu** [comment]
And you should learn how to talk to people who are fucking helping you for free, with software they gave you for free and didn't ask you for shit or hold a gun to your head to use.

**Comment by miigotu** [comment]
`sickchill found: True` means it found sickchill INSTALLED VIA PIP in the virtualenv.
