### ISSUE TITLE
Network paths not accessible after update

### ISSUE THREAD

**Issue by nedillon** [SickChill/SickChill#7306]
I am using network shares to store my show data. These are accessed by IP address. Up until this week, this has worked fine. Now, post processing is failing with the error "[WinError 58] The specified server cannot perform the requested operation: ...". There are episodes in the post processing folder that are never moved (they aren't for the show listed in the log either). 

It seems to be a an issue with accessing the share in general, as I can't browse that path when editing a show's location either. The Server Status page also lists "Missing" as the root directory free space. I have tried changing it to a UNC path instead of IP with no success. There is no username or password requirements for accessing this share and I am not using mapped drives.

Any idea why this would suddenly start happening?

I have also tried rolling back to a previous version but the v0.5.11 installer is failing with "Error parsing dependency information for Git.x64".

Branch/Commit: v2021.07.14-1 
OS: Windows-10-10.0.19042-SP0 
Browser: Firefox 89.0.2

Logs:
```
2021-07-15 16:36:53 INFO :: POSTPROCESSOR-AUTO :: Auto post processing task for E:\Downloads\SickChill completed
AA OSError: [WinError 58] The specified server cannot perform the requested operation: '\\\\192.168.1.200\\Shows\\Outlander'
AA path = _getfinalpathname(path)
AA File "C:\SickChill\Python3\tools\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
AA path = _getfinalpathname_nonstrict(path)
AA File "C:\SickChill\Python3\tools\lib\ntpath.py", line 651, in realpath
AA process_path.lower().startswith(os.path.realpath(sqlShow["location"]).lower() + os.sep)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\processTV.py", line 281, in validate_dir
AA if not validate_dir(current_directory, release_name, failed, result):
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\processTV.py", line 177, in process_dir
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA OSError: [WinError 58] The specified server cannot perform the requested operation: '\\\\192.168.1.200\\Shows\\Outlander'
AA path = _getfinalpathname(path)
AA File "C:\SickChill\Python3\tools\lib\ntpath.py", line 647, in realpath
2021-07-15 16:36:52 INFO :: POSTPROCESSOR-AUTO :: Processing E:\Downloads\SickChill
```

**Comment by miigotu** [comment]
The newest installer is 0.6.0

**Comment by nedillon** [comment]
Right, but I'm trying to revert back to an older version because the latest has the issue I have described.

**Comment by miigotu** [comment]
Installer versions and SickChill version are not the same. The old installer will never work again. Use the new installer, and then edit the service to run as your user.

**Comment by nedillon** [comment]
That took care of it, thanks for your help.
