### ISSUE TITLE
Unable to update from v2021.07.13-3

### ISSUE THREAD

**Issue by nekkidtruth** [SickChill/SickChill#7307]
Branch/Commit: v2021.07.13-3
OS: Windows 7
Browser: Chrome
What you did: Clicked "Update Now"
What happened: Page refreshes and gives a 500 error. SickChill is still running though. If I hit back, I can navigate to the log. Pasted below.
What you expected: For SickChill to update and restart.
Logs:
```
AA TypeError: update() missing 1 required positional argument: 'pid'
AA return function()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "C:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA results = yield self.async_call(method)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info) # type: ignore
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: can only concatenate str (not "Version") to str
AA self._notify_pht(update_text + new_version, title)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\plex.py", line 71, in notify_git_update
AA n.notify_git_update(new_version)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\__init__.py", line 115, in notify_git_update
AA notifiers.notify_git_update(settings.CUR_COMMIT_HASH or "")
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\pip.py", line 80, in update
AA return self.updater.update()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\runner.py", line 308, in update
AA if updater.update():
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\home.py", line 687, in update
AA return function(**kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='192.168.1.71:8081', method='GET', uri='/home/update/?pid=224148', version='HTTP/1.1', remote_ip='192.168.1.2')
2021-07-15 18:24:59 ERROR :: WEBSERVER :: Uncaught exception GET /home/update/?pid=224148 (192.168.1.2)
AA mako.exceptions.TopLevelLookupException: Cant locate template for uri 'viewlogs.mako'
AA raise exceptions.TopLevelLookupException(
AA File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 262, in get_template
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\common.py", line 36, in __init__
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\logs.py", line 83, in viewlog
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "C:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info) # type: ignore
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA KeyError: 'viewlogs.mako'
AA return self._check(uri, self._collection[uri])
AA File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 249, in get_template
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: viewlog() got an unexpected keyword argument 'min_level'
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='192.168.1.71:8081', method='POST', uri='/errorlogs/viewlog/', version='HTTP/1.1', remote_ip='192.168.1.2')
2021-07-15 18:24:53 ERROR :: WEBSERVER :: Uncaught exception POST /errorlogs/viewlog/ (192.168.1.2)
AA mako.exceptions.TopLevelLookupException: Cant locate template for uri 'viewlogs.mako'
AA raise exceptions.TopLevelLookupException(
AA File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 262, in get_template
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\common.py", line 36, in __init__
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\logs.py", line 83, in viewlog
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "C:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info) # type: ignore
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA KeyError: 'viewlogs.mako'
AA return self._check(uri, self._collection[uri])
AA File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 249, in get_template
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: viewlog() got an unexpected keyword argument 'min_level'
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='192.168.1.71:8081', method='POST', uri='/errorlogs/viewlog/', version='HTTP/1.1', remote_ip='192.168.1.2')
2021-07-15 18:24:52 ERROR :: WEBSERVER :: Uncaught exception POST /errorlogs/viewlog/ (192.168.1.2)
AA mako.exceptions.TopLevelLookupException: Cant locate template for uri 'viewlogs.mako'
AA raise exceptions.TopLevelLookupException(
AA File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 262, in get_template
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\common.py", line 36, in __init__
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\logs.py", line 83, in viewlog
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "C:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info) # type: ignore
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA KeyError: 'viewlogs.mako'
AA return self._check(uri, self._collection[uri])
AA File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 249, in get_template
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: viewlog() got an unexpected keyword argument 'min_level'
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='192.168.1.71:8081', method='POST', uri='/errorlogs/viewlog/', version='HTTP/1.1', remote_ip='192.168.1.2')
2021-07-15 18:24:52 ERROR :: WEBSERVER :: Uncaught exception POST /errorlogs/viewlog/ (192.168.1.2)
AA mako.exceptions.TemplateLookupException: Cant locate template for uri 'viewlogs.mako'
AA raise exceptions.TemplateLookupException(
AA File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 352, in _check
AA return self._check(uri, self._collection[uri])
AA File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 249, in get_template
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\common.py", line 36, in __init__
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\logs.py", line 83, in viewlog
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "C:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info) # type: ignore
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/SickChill/Python3/tools/lib/site-packages/sickchill/gui/slick/views/viewlogs.mako'
AA template_stat = os.stat(template.filename)
AA File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 344, in _check
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: viewlog() got an unexpected keyword argument 'min_level'
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='192.168.1.71:8081', method='POST', uri='/errorlogs/viewlog/', version='HTTP/1.1', remote_ip='192.168.1.2')
2021-07-15 18:24:51 ERROR :: WEBSERVER :: Uncaught exception POST /errorlogs/viewlog/ (192.168.1.2)
```

**Comment by tjenvy** [comment]
+1 here.  

`2021-07-17 16:44:00 ERROR :: WEBSERVER :: Uncaught exception GET /home/update/?pid=1 (172.17.0.1)

HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/home/update/?pid=1', version='HTTP/1.1', remote_ip='172.17.0.1')

Traceback (most recent call last):

File "/app/sickchill/sickchill/views/index.py", line 185, in async_call

kwargs[arg] = [xhtml_escape(v) for v in value]

File "/app/sickchill/sickchill/views/home.py", line 669, in update

pid = self.get_query_argument("pid")

File "/app/sickchill/sickchill/update_manager/runner.py", line 313, in update

File "/app/sickchill/sickchill/update_manager/git.py", line 302, in update

if self.branch == self._find_installed_branch():

File "/app/sickchill/sickchill/oldbeard/notifiers/__init__.py", line 91, in notify_git_update

def notify_download(ep_name):

File "/app/sickchill/sickchill/oldbeard/notifiers/plex.py", line 69, in notify_git_update

title = common.notifyStrings[common.NOTIFY_GIT_UPDATE]

File "/app/sickchill/sickchill/oldbeard/notifiers/plex.py", line 46, in _notify_pht

return sickchill.oldbeard.notifiers.kodi_notifier._notify_kodi(

TypeError: _notify_kodi() got an unexpected keyword argument 'host'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "/app/sickchill/lib3/tornado/web.py", line 1703, in _execute

File "/app/sickchill/lib3/tornado/gen.py", line 742, in run

File "/app/sickchill/sickchill/views/index.py", line 161, in get

route = route.strip("/").replace(".", "_").replace("-", "_") or "index"

File "/app/sickchill/lib3/tornado/gen.py", line 735, in run

File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run

result = self.fn(*self.args, **self.kwargs)

File "/app/sickchill/sickchill/views/index.py", line 187, in async_call

raise Exception

TypeError: update() missing 1 required positional argument: 'pid'


2021-07-17 16:44:28 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: [Errno 2] No such file or directory: '/app/sickchill/lib3/cloudscraper/user_agent/browsers.json'`

**Comment by miigotu** [comment]
> +1 here.  
> Running in docker 
> 
> `2021-07-17 16:44:00 ERROR :: WEBSERVER :: Uncaught exception GET /home/update/?pid=1 (172.17.0.1)
> 
> HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/home/update/?pid=1', version='HTTP/1.1', remote_ip='172.17.0.1')
> 
> Traceback (most recent call last):
> 
> File "/app/sickchill/sickchill/views/index.py", line 185, in async_call
> 
> kwargs[arg] = [xhtml_escape(v) for v in value]
> 
> File "/app/sickchill/sickchill/views/home.py", line 669, in update
> 
> pid = self.get_query_argument("pid")
> 
> File "/app/sickchill/sickchill/update_manager/runner.py", line 313, in update
> 
> File "/app/sickchill/sickchill/update_manager/git.py", line 302, in update
> 
> if self.branch == self._find_installed_branch():
> 
> File "/app/sickchill/sickchill/oldbeard/notifiers/__init__.py", line 91, in notify_git_update
> 
> def notify_download(ep_name):
> 
> File "/app/sickchill/sickchill/oldbeard/notifiers/plex.py", line 69, in notify_git_update
> 
> title = common.notifyStrings[common.NOTIFY_GIT_UPDATE]
> 
> File "/app/sickchill/sickchill/oldbeard/notifiers/plex.py", line 46, in _notify_pht
> 
> return sickchill.oldbeard.notifiers.kodi_notifier._notify_kodi(
> 
> TypeError: _notify_kodi() got an unexpected keyword argument 'host'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> Traceback (most recent call last):
> 
> File "/app/sickchill/lib3/tornado/web.py", line 1703, in _execute
> 
> File "/app/sickchill/lib3/tornado/gen.py", line 742, in run
> 
> File "/app/sickchill/sickchill/views/index.py", line 161, in get
> 
> route = route.strip("/").replace(".", "_").replace("-", "_") or "index"
> 
> File "/app/sickchill/lib3/tornado/gen.py", line 735, in run
> 
> File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
> 
> result = self.fn(*self.args, **self.kwargs)
> 
> File "/app/sickchill/sickchill/views/index.py", line 187, in async_call
> 
> raise Exception
> 
> TypeError: update() missing 1 required positional argument: 'pid'
> 
> 
> 2021-07-17 16:44:28 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: [Errno 2] No such file or directory: '/app/sickchill/lib3/cloudscraper/user_agent/browsers.json'`

There is no lib3 anymore.

**Comment by tjenvy** [comment]
> > +1 here.
> > Running in docker
> > `2021-07-17 16:44:00 ERROR :: WEBSERVER :: Uncaught exception GET /home/update/?pid=1 (172.17.0.1)
> > HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/home/update/?pid=1', version='HTTP/1.1', remote_ip='172.17.0.1')
> > Traceback (most recent call last):
> > File "/app/sickchill/sickchill/views/index.py", line 185, in async_call
> > kwargs[arg] = [xhtml_escape(v) for v in value]
> > File "/app/sickchill/sickchill/views/home.py", line 669, in update
> > pid = self.get_query_argument("pid")
> > File "/app/sickchill/sickchill/update_manager/runner.py", line 313, in update
> > File "/app/sickchill/sickchill/update_manager/git.py", line 302, in update
> > if self.branch == self._find_installed_branch():
> > File "/app/sickchill/sickchill/oldbeard/notifiers/**init**.py", line 91, in notify_git_update
> > def notify_download(ep_name):
> > File "/app/sickchill/sickchill/oldbeard/notifiers/plex.py", line 69, in notify_git_update
> > title = common.notifyStrings[common.NOTIFY_GIT_UPDATE]
> > File "/app/sickchill/sickchill/oldbeard/notifiers/plex.py", line 46, in _notify_pht
> > return sickchill.oldbeard.notifiers.kodi_notifier._notify_kodi(
> > TypeError: _notify_kodi() got an unexpected keyword argument 'host'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/app/sickchill/lib3/tornado/web.py", line 1703, in _execute
> > File "/app/sickchill/lib3/tornado/gen.py", line 742, in run
> > File "/app/sickchill/sickchill/views/index.py", line 161, in get
> > route = route.strip("/").replace(".", "_").replace("-", "_") or "index"
> > File "/app/sickchill/lib3/tornado/gen.py", line 735, in run
> > File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
> > result = self.fn(*self.args, **self.kwargs)
> > File "/app/sickchill/sickchill/views/index.py", line 187, in async_call
> > raise Exception
> > TypeError: update() missing 1 required positional argument: 'pid'
> > 2021-07-17 16:44:28 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: [Errno 2] No such file or directory: '/app/sickchill/lib3/cloudscraper/user_agent/browsers.json'`
> 
> There is no lib3 anymore.

Well that’s expected stating “no such file or directory” but since I didn’t write the code I am not able to fix the codes error. But thank you for the reply.

**Comment by miigotu** [comment]
Try clearing the browser cache.

**Comment by nekkidtruth** [comment]
Clearing cache does not resolve my issue.

**Comment by Minxster** [comment]
Same for me, I had to do a re-install when the Windows version was changed to v0.6.0. I had to manually re-install again for v0.6.1, so I'm now running v 2021.07.14-b on Windows Server 2019. But when I click on the upgrade button I get a HTTP 500 error message.

The error log itself, not just main log, shows:
`2021-07-23 13:28:38 Uncaught exception %s
%r`

`AA TypeError: update() missing 1 required positional argument: 'pid'
AA return function()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "C:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA results = yield self.async_call(method)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info) # type: ignore
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: can only concatenate str (not "Version") to str
AA self._notify_pht(update_text + new_version, title)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\plex.py", line 71, in notify_git_update
AA n.notify_git_update(new_version)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\__init__.py", line 115, in notify_git_update
AA notifiers.notify_git_update(settings.CUR_COMMIT_HASH or "")
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\pip.py", line 80, in update
AA return self.updater.update()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\runner.py", line 308, in update
AA if updater.update():
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\home.py", line 687, in update
AA return function(**kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='sickchill:8081', method='GET', uri='/home/update/?pid=2964', version='HTTP/1.1', remote_ip='192.168.1.83')
2021-07-23 13:28:38 ERROR :: WEBSERVER :: Uncaught exception GET /home/update/?pid=2964 (192.168.1.83)
AA TypeError: update() missing 1 required positional argument: 'pid'
AA return function()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "C:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA results = yield self.async_call(method)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info) # type: ignore
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: can only concatenate str (not "Version") to str
AA self._notify_pht(update_text + new_version, title)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\plex.py", line 71, in notify_git_update
AA n.notify_git_update(new_version)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\__init__.py", line 115, in notify_git_update
AA notifiers.notify_git_update(settings.CUR_COMMIT_HASH or "")
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\pip.py", line 80, in update
AA return self.updater.update()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\runner.py", line 308, in update
AA if updater.update():
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\home.py", line 687, in update
AA return function(**kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='sickchill:8081', method='GET', uri='/home/update/?pid=2964', version='HTTP/1.1', remote_ip='192.168.1.83')
2021-07-23 13:28:37 ERROR :: WEBSERVER :: Uncaught exception GET /home/update/?pid=2964 (192.168.1.83)`

**Comment by Teamshake** [comment]
i get the same error also.  running windows 10.  just reinstalled yesterday using newest windows installer.

AA TypeError: update() missing 1 required positional argument: 'pid'
AA return function()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "C:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA results = yield self.async_call(method)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info) # type: ignore
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: can only concatenate str (not "Version") to str
AA self._notify_pht(update_text + new_version, title)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\plex.py", line 71, in notify_git_update
AA n.notify_git_update(new_version)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\__init__.py", line 115, in notify_git_update
AA notifiers.notify_git_update(settings.CUR_COMMIT_HASH or "")
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\pip.py", line 80, in update
AA return self.updater.update()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\runner.py", line 308, in update
AA if updater.update():
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\home.py", line 687, in update
AA return function(**kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/home/update/?pid=20260', version='HTTP/1.1', remote_ip='127.0.0.1')
2021-07-23 18:36:37 ERROR :: WEBSERVER :: Uncaught exception GET /home/update/?pid=20260 (127.0.0.1)

**Comment by telsum** [comment]
I had the same issue with my Windows install. 
Re-installing from the current windows installer solved this, however I do notice in sickchill my git status can't seem to get the branch version. 
![image](https://user-images.githubusercontent.com/60305073/126857637-5083247f-d3cd-462c-9116-f481334ec6f6.png)
I have checked the config.ini and one thing interests me
  branch = pip
  git_remote = origin
  git_remote_url = https://github.com/SickChill/SickChill.git
  cur_commit_hash = 2021.7.14.post1
  cur_commit_branch = ""
  config_version = 8

Is the branch in there meant to be pip?

**Comment by davidreverett** [comment]
Also seeing the same behavior on my setup.

**Comment by miigotu** [comment]
> I had the same issue with my Windows install. 
> Re-installing from the current windows installer solved this, however I do notice in sickchill my git status can't seem to get the branch version. 
> ![image](https://user-images.githubusercontent.com/60305073/126857637-5083247f-d3cd-462c-9116-f481334ec6f6.png)
> I have checked the config.ini and one thing interests me
>   branch = pip
>   git_remote = origin
>   git_remote_url = https://github.com/SickChill/SickChill.git
>   cur_commit_hash = 2021.7.14.post1
>   cur_commit_branch = ""
>   config_version = 8
> 
> Is the branch in there meant to be pip? 

Yes, the windows installer installs using pip now, not git. You'll notice you have not git folder in C:\SickChill anymore either.
