### ISSUE TITLE
releases/tags names

### ISSUE THREAD

**Issue by digrouz** [SickChill/SickChill#7309]
Hello,

I'm trying to automate my own container building for sickchill and I realize that release names sometimes starts by a "v", sometimes not. Is there a particular meaning to this ?

Kind Regards

**Comment by miigotu** [comment]
vXXXX.XX.XX-X is the older style version numbers, it is no different now just dropped the v because it conflicts with a lot of packaging systems (pip for one)

**Comment by digrouz** [comment]
@miigotu the issue is that https://api.github.com/repos/sickchill/sickchill/tags lists still the last "vXXXX.XX.XX-X" as the last one :/. 

![image](https://user-images.githubusercontent.com/548498/126745726-6b45c114-e068-4854-b24c-16fbd1038bd7.png)

**Comment by miigotu** [comment]
Yes, that has nothing to do with the question you asked here.

The tag and version are out of sync. I need to fix a plugin.
