### ISSUE TITLE
Missing params, no Indexer ID or folder: None and None/None

### ISSUE THREAD

**Issue by brianjmurrell** [SickChill/SickChill#7313]
### Before submitting your issue:

Branch/Commit: 
Branch: master
Commit: e1e91c3ec3c90479b556e7e78b48dc3bb81ead01
Version: 2021.07.14-6
Database Version: 44.2
OS: Linux
Browser: Chrome
What you did: Searched for a show, then set past episodes and future episodes to Wanted, set the directory to save to and then clicked Add Show.
What happened: Got an error: `Missing params, no Indexer ID or folder: None and None/None`
What you expected: Show should be added
Logs: Nothing new appears in the log

**Comment by warrenawa** [comment]
I had the same behavior when I ticked the "exact string search" but adding a show went smoothly when I left the box unticked.

Behavior was the same for old episodes wanted and old episodes skipped.
