### ISSUE TITLE
unable to update to from v2021.07.14-8 to v2021.07.22-8

### ISSUE THREAD

**Issue by UmRAtEJvgLtH** [SickChill/SickChill#7342]
Install: pip
Version: v2021.07.14-8
Database Version: 44.2
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
OS: Linux-5.10.17-v7l+-armv7l-with-debian-10.10
Problem: Can't update to latest commit. Manual update:
Update Failed
Update wasn't successful, not restarting. Check your log for more information. 

Logs:
```
2021-07-22 12:43:56 INFO :: CHECKVERSION :: Request failed: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/SickChill/SickChill/v2021.07.22-8/sickchill/oldbeard/databases/main.py ()
```

**Comment by miigotu** [comment]
Yep, tags are out of sync with the pypi release. I need to fix my poetry date version plugin.

**Comment by miigotu** [comment]
You can just do `pip install -U sickchill`

**Comment by DravenSA** [comment]
> You can just do `pip install -U sickchill`

call me stupid but how do i do that?

**Comment by miigotu** [comment]
@DravenSA if you had installed via pip, you would know. If you did not, you should not do that.

Either way, a new version is published with makes it work from inside SC, nothing special to do.

Fixed.
