### ISSUE TITLE
Synology - Unable to retrieve new version from https://github.com/SickChill/SickChill/tarball/master, can't update

### ISSUE THREAD

**Issue by toryn74** [SickChill/SickChill#7345]
Branch/Commit: 	Branch: master
Commit: 1e89497f482e817e1ed757b7f45e16309614738b
Database Version: 44.2
Running version 	2021.7.12-6
OS:                       	Synology NAS
Browser:               	Chrome
What you did:      	clicked "Update now"
What happened:  	Receive Error message - Update Failed
                             	Update wasn't successful, not restarting. Check your log for more information.

Commit: 1e89497f482e817e1ed757b7f45e16309614738b
Database Version: 44.2

Attempted before when it said I was 24 commits behind, and same issue as now when I am listed at 48 commits behind.  I shut down and restarted SC and get the same results.  
I checked with a friend who is also on Synology platform (Commit: 1e89497f482e817e1ed757b7f45e16309614738b; Database Version: 44.5) and he said he is getting the same error.

PASTE LOGS HERE
```

2021-07-22 11:54:27 INFO :: WEBSERVER-HOME_0 :: Clearing out update folder /volume1/@appstore/sickchill/var/data/sc-update before extracting
2021-07-22 11:54:27 INFO :: WEBSERVER-HOME_0 :: Creating update folder /volume1/@appstore/sickchill/var/data/sc-update before extracting
2021-07-22 11:54:27 INFO :: WEBSERVER-HOME_0 :: Downloading update from https://github.com/SickChill/SickChill/tarball/master
2021-07-22 11:54:27 ERROR :: WEBSERVER-HOME_0 :: Request failed: 'PosixPath' object has no attribute 'endswith' (<class 'str'>)
2021-07-22 11:54:27 WARNING :: WEBSERVER-HOME_0 :: Unable to retrieve new version from https://github.com/SickChill/SickChill/tarball/master, can't update

**Comment by FaiqH** [comment]
Glad I am not the only one. I uninstalled SC,GIT,PY3 and reinstalled from the community that has nyaran fork and it worked but then I was 800+ versions behind and the backup would not restore. I try updating, fails to run. Tried this twice.

**Comment by toryn74** [comment]
Woof!   Sorry to hear about your struggles.    Based on your feedback, I'm going to hold tight before experimenting with anything aggressive.  I may be 48 commits behind, but at least it is working at the moment.

**Comment by miigotu** [comment]
Fixed

**Comment by toryn74** [comment]
Sorry miigotu. . .  edit what line?

**Comment by toryn74** [comment]
stabbing in the dark, perhaps this. . .

/volume1/@appstore/sickchill/share/SickChill/sickchill/update_manager#

source.py:        tar_download_url = f"https://github.com/{settings.GIT_ORG}/{settings.GIT_REPO}/tarball/{self.branch}"

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/commit/6d462e2167b2689ab7f94c9791de4562c59d492c
https://github.com/SickChill/SickChill/commit/eeded6729fdee99d0adbbd1b6a699fb9a403db18#diff-c5df4caa7ca21f4a558895923ffd6bf27ccd9683cc9739469fc0b10bbe6c6527

And
            https://github.com/SickChill/SickChill/commit/7dcca27570e32c94d0703a5869e2e66b7cc6eb84#diff-c5df4caa7ca21f4a558895923ffd6bf27ccd9683cc9739469fc0b10bbe6c6527

**Comment by toryn74** [comment]
You sir are a gentleman and a scholar!

Followed the steps, and
root@T_Syn_1019:/volume1/@appstore/sickchill/share/SickChill/sickchill# cat version.py 
__version__ = "2021.7.23-1"

. . .  not bad for a network guy!   :-)


Please accept my paltry Sponsoring. . .  cause I'm a network guy with 4 kids.
