### ISSUE TITLE
Truenas installation not working

### ISSUE THREAD

**Issue by Ilocans** [SickChill/SickChill#7348]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:  TrueNAS-12.0-U3.1
Browser: Chrome/Brave
What you did: Install/Reinstall
What happened: This site can’t be reached
What you expected:
Problem: I use to have an installation of Sickchill working fine for the last few weeks but now when I try to connect to the webpage I have the error: the site cannot be reach.
I disabled my current installation and try to create a new one from the Truenas plugin page. Everything works fine for the installation. When I click on manage to access to the sickchill webpage I have the same error.
The only thing I did recently on my truenas was to replace my HDD but I don't think it should have impact.
Logs:
```
I don't have access to the UI and I did not find any logs in my new installation
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
Try again, make sure you have the newest iocage definitions

**Comment by Ilocans** [comment]
How can I make sure it is the newest definition ?

**Comment by miigotu** [comment]
https://github.com/ix-plugin-hub/iocage-plugin-index/blob/master/sickchill.json

https://github.com/ix-plugin-hub/iocage-plugin-sickchill

**Comment by miigotu** [comment]
I am not sure the cammanda for iocage, but pretty sure something with iocage fetch --update or something like that.

**Comment by sphinxlady** [comment]
Pkg update and pkg upgrade from inside the shell for sickchill

**Comment by Ilocans** [comment]
pkg update and pkg upgrade did nothing, everything is up to date.
I tried manually the iocage fetch -P sickchill -g https://github.com/ix-plugin-hub/iocage-plugin-index --branch 'master' :
it create a new jails with the plugin installed but I have the same result: a page with the message This site can’t be reached
I already tried the post_install.sh script but it has the same result.

Is there some logs somewhere that could help to know what's happening ? The plugin seems to start with no error or I don't know where to find what's wrong.

Thanks

**Comment by miigotu** [comment]
@fireph might know more, I don't use freenas/truenas and never have.

**Comment by sphinxlady** [comment]
Unfortunately at this point sickchill isn't working under truenas. It installs fine but will remain unreachable when you try to get to the ui.

**Comment by Ilocans** [comment]
Thanks @sphinxlady for the information.
I still have a jail created a few months ago which seems to work fine until recently. Do you know or anyone else know if it is for the same reason it is not working anymore ?

**Comment by sphinxlady** [comment]
Recent updates in sichchill  broke it for truenas. Older versions of sickchill may remain working if you avoid updating.

At this point it's up to the creator or some of the people helping to see if they can find the issue.

You can use sonarr for now to get around the problem it's recently been updated although it's not without it's issues.

**Comment by miigotu** [comment]
The jail for SC was updated to work with the latest changes of SC.

**Comment by sphinxlady** [comment]
Is this a recent update?
The present available download still remains nonworking.

**Comment by miigotu** [comment]
Yes, they were updated on the 12th.

**Comment by miigotu** [comment]
They don't get published on the index immediately, you have to manually pull the json.

**Comment by sphinxlady** [comment]
> 
> 
> pkg update and pkg upgrade did nothing, everything is up to date.
> I tried manually the iocage fetch -P sickchill -g https://github.com/ix-plugin-hub/iocage-plugin-index --branch 'master' :
> it create a new jails with the plugin installed but I have the same result: a page with the message This site can’t be reached
> I already tried the post_install.sh script but it has the same result.
> 
> Is there some logs somewhere that could help to know what's happening ? The plugin seems to start with no error or I don't know where to find what's wrong.
> 
> Thanks

I believe that's because it just grabbing the p9 release rather then the fixed p13 release.

**Comment by miigotu** [comment]
Exactly, I think there is a --pull parameter to add to the fetch, or you can wget/curl the json and use that locally

**Comment by miigotu** [comment]
'iocage fetch -P -n sickchill.json ip4_addr="em0|192.168.0.220/24"

**Comment by sphinxlady** [comment]
Truenass has been informed they need to update the downloaded version .

They dont do it often because it auto updates after install and not one they normally have to port the updates for.

**Comment by Bmiest** [comment]
What's the best way to fix my broken install? I took a backup of the appfolder after it stopped working (I saw about 150 commits behind and clicked update, after that it went fubar). Can I still fix my current jail in some way or do I have to install a new jail and try to restore the data/config?

**Comment by Toolazy2work** [comment]
Any Updates to this issue?  ive updated my Jail to 12.1-RELEASE-p13, done a fresh pull and still wont launch.  Is there any way to see what is crashing at startup?

**Comment by Tiladen** [comment]
Hi, I've also been trying to get this working on TrueNAS and just tried downloading the json file and running the iocage fetch command above to create a new plugin/jail. Same result - sickchill doesn't start up.

Have tried running the following in the jails(I've had several over the last few days) but it just exits without doing or logging anything useful:
`root@SickChill:/usr/local/app/sickchill # service sickchill start
Removing stale pidfile.
Starting sickchill.
root@SickChill:/usr/local/app/sickchill # Writing PID: 59837 to /var/run/sickchill/sickchill.pid
`
Using ps -auwwx I cant find any PID 56837, and running the command again gives the same result with a different PID.

One thing I did discover is that if I remove the '-d' from the command_args in the file /usr/local/etc/rc.d/sickchill and rerun the above command it looks like it works - I get a lot of logging and can, after it finishes, access the web interface. However I'm not sure this is a good fix as I never get my prompt back and I'm concerned it'll hang my jail starting up.

Logging from starting up without -d in command args:
`root@SickChill:/usr/local/app/sickchill # service sickchill start
Starting sickchill.
Checking poetry
sickchill found: False
Can write to /usr/local/lib/python3.8/site-packages: False
Can write to /.local/lib/python3.8/site-packages: False
Current environment is not writable!
Restarting SickChill with ['/usr/local/app/sickchill/.venv/bin/python3', '/usr/local/app/sickchill/SickChill.py', '--datadir', '/usr/local/app/sickchill/DB', '--pidfile', '/var/run/sickchill/sickchill.pid', '--quiet', '--nolaunch']
Checking poetry
sickchill found: False
Can write to /.local/lib/python3.8/site-packages: False
Can write to /usr/local/app/sickchill/.venv/lib/python3.8/site-packages: True
pip found: True
pip args: /usr/local/app/sickchill/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry poetry-date-version-plugin wheel --pre
poetry found: True
pip args: /usr/local/app/sickchill/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU appdirs==1.4.4 babelfish==0.6.0b1; python_version >= "3.6" and python_version < "4.0" beautifulsoup4==4.9.3 beekeeper-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" bencode.py==4.0.0 cachecontrol==0.12.6; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") certifi==2021.5.30; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" cffi==1.14.6; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" or python_full_version >= "3.5.0" and python_version >= "3.6" chardet==4.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") charset-normalizer==2.0.3; python_full_version >= "3.6.0" and python_version >= "3" click==8.0.1; python_version >= "3.6" cloudscraper==1.2.58 colorama==0.4.4; python_version >= "3.6" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.6" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==3.4.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" decorator==5.0.9; python_version >= "3.5" deluge-client==1.9.0 deprecated==1.2.12; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.3; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.8; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.0; python_version >= "3" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3" guessit==3.3.1 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.19.1 idna==3.2; python_version >= "3.5" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.5" ifaddr==0.1.7 imagesize==1.2.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2021.4.18 importlib-metadata==1.7.0; python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_version < "3.8" and python_version >= "3.6" and python_full_version >= "3.5.0" or python_version >= "2.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.2 kodipydent-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" lxml==4.6.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.1.4; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") markdown2==2.4.0; python_version >= "3.5" and python_version < "4" markupsafe==2.0.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" msgpack==1.0.2; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" new-rtorrent-python==1.0.1a0 oauthlib==3.1.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==20.9; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pbr==5.6.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.20; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.1.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.4.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pynma==1.0 pyopenssl==20.0.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") pyparsing==2.4.7; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" or python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==5.0.2; python_version >= "3.6" python-twitter==3.5 python3-fanart==2.0.0 pytz==2021.1 qbittorrent-api==2021.5.22 rarfile==4.0 rebulk==3.0.1 requests-oauthlib==1.3.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests-toolbelt==0.9.1 requests==2.26.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") send2trash==1.7.1 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" or python_full_version >= "3.5.0" or python_version >= "3.4" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" and python_version >= "3.4" or python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" soupsieve==2.2.1; python_version >= "3.6" sqlalchemy==1.4.22; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.3.0; python_version >= "3.6" subliminal==2.1.0 text-unidecode==1.3; python_version >= "3.6" timeago==1.0.15 tmdbsimple==2.8.0 tornado==6.1; python_version >= "3.5" tus.py==1.3.4 tvdbsimple==1.0.6 tzlocal==2.1 unidecode==1.2.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") urllib3==1.26.6; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version < "4" or python_full_version >= "3.6.0" and python_version < "4" validators==0.18.2; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.12.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" xmltodict==0.12.0; python_full_version >= "3.6.2" and python_version < "4" zipp==3.5.0; python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_version < "3.8" and python_version >= "3.6" and python_full_version >= "3.5.0"
sickchill found: False
`

Also if, after doing this, I stop SickChill and revert the file I end up back where I started.
`root@SickChill:/usr/local/app/sickchill # service sickchill start
Starting sickchill.
root@SickChill:/usr/local/app/sickchill # Writing PID: 12468 to /var/run/sickchill/sickchill.pid


root@SickChill:/usr/local/app/sickchill # ps auwwx
USER   PID %CPU %MEM   VSZ  RSS TT  STAT STARTED    TIME COMMAND
root 59094  0.0  0.0 11428 2804  -  SsJ  23:03   0:00.00 /usr/sbin/syslogd -c -ss
root 59159  0.0  0.0 11248 2600  -  IsJ  23:03   0:00.01 /usr/sbin/cron -J 15 -s
root 12479  0.0  0.0 11940 3136  8  R+J  23:45   0:00.00 ps auwwx
root 59564  0.0  0.0 13884 4352  8  SJ   23:14   0:00.06 /bin/csh -i
root 59378  0.0  0.0 12180 3132  9  IJ   23:06   0:00.01 login [pam] (login)
root 59379  0.0  0.0 13372 4012  9  I+J  23:06   0:00.02 -csh (csh)
`
Based on the above tests it looks like something breaks when running SickChill in daemon mode (-d) - is there anyway to get more detail on what this is as it's not outputting anything to the logs or anywhere that I could find. 

Happy to help in anyway I can, have a good tech background but don't know much Python so not sure where to start looking in the source code for clues.

**Comment by Tiladen** [comment]
OK, I think I may have worked out what is happening, not sure what to do about it tho.

I edited the sickchill/init_helpers.py file and commented out the lines redirecting stdin/stdout when running SickChill as a daemon. 

When I run the service sickchill start command I'm now getting an error:
```root@SickChill:/usr/local/app/sickchill # service sickchill start
Removing stale pidfile.
Starting sickchill.
root@SickChill:/usr/local/app/sickchill # Writing PID: 12956 to /var/run/sickchill/sickchill.pid

Checking poetry
sickchill found: False
Can write to /usr/local/lib/python3.8/site-packages: False
Can write to /.local/lib/python3.8/site-packages: False
Current environment is not writable!
Restarting SickChill with ['/usr/local/app/sickchill/.venv/bin/python3', '/usr/local/app/sickchill/SickChill.py', '--datadir', '/usr/local/app/sickchill/DB', '-d', '--pidfile', '/var/run/sickchill/sickchill.pid', '--debug', '--nolaunch']
PID file: /var/run/sickchill/sickchill.pid already exists. Exiting.
```
So it looks like when it's restarting SickChill it's trying to use the same PID file and failing because it already exists. 

Would it be safe and/or make sense to remove the pid file before restarting SickChill so the new instance can reuse the same PID file?

**Comment by sphinxlady** [comment]
The truenas people are presently  grabbing the working p13 version rather then the broken p9 versions so soon you can install a working version again.

**Comment by Tiladen** [comment]
I ran the iocage fetch command provided by miigotu - wouldn't this have installed the latest version? How can I confirm if it's p9 or p13 ?

**Comment by Toolazy2work** [comment]
@tiladen look at your release number for the jail.  It will say “12.1-RELEASE-p??”  The ?? Is the number either 9 or 14

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Toolazy2work** [comment]
13*

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tiladen** [comment]
OK, thanks for clarifying that. I can see that I am indeed running p9. 

I hadn't realised we were talking about the version of the jail and still don't understand how changing to a newer version of the OS will fix what to me seems to be an issue in the SickChill code. 

However am happy to take your word for it as I'm not familiar with how these things work.

Will wait for p13 to become available and reinstall again. Hopefully wont take too long as I'm missing my SickChill install already :)

**Comment by Toolazy2work** [comment]
> OK, thanks for clarifying that. I can see that I am indeed running p9.
> 
> I hadn't realised we were talking about the version of the jail and still don't understand how changing to a newer version of the OS will fix what to me seems to be an issue in the SickChill code.
> 
> However am happy to take your word for it as I'm not familiar with how these things work.
> 
> Will wait for p13 to become available and reinstall again. Hopefully wont take too long as I'm missing my SickChill install already :)

You can get it now by opening the shell and doing "iocage upgrade <nameOfSickChillJail>"

**Comment by Tiladen** [comment]
OK, I opened the shell and run `iocage upgrade SickChill` and it ran through the upgrade process and reported it was successfully upgraded. But still cant open the web interface for SickChill.

In addition, TrueNAS is still showing `12.2-RELEASE-p9` in the Jail page in the GUI. When I open a shell on the Jail however the first line is reporting that I'm logging in to 'FreeBSD 12.2-RELEASE-p6 df578562304(HEAD) TRUENAS` so not sure which to believe or if this matters at all.

I also see this p6 release when opening Shell for the NAS itself and I'm not sure how/if it relates to the Release shown on the Jail page.

OK, just realised that I'm running 12.2 but the previous posts where actually referring to 12.1... do I now need to work out how to deploy this plugin into an older version of the jail?

**Comment by Toolazy2work** [comment]
I THINK 12.2 is the newest release, but from what I’ve seen / read / heard, it’s still broken.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sphinxlady** [comment]
The truenas people are presently  grabbing the working p13 version rather then the broken p9 versions so soon you can install a working version again.

**Comment by sphinxlady** [comment]
The next update for truenass is aug 3 so it would have been pulled shortly anyway.

**Comment by jrvd007** [comment]
I've updated the jail. It is now 12.1-RELEASE-p13. However, sickchill still does not open. 

When I run the following command inside the jail : `service sickchill start`

I get this output:

```Starting sickchill.  
sickchill found: False  
Current environment is not writable!
Because of the above errors, we will try creating a new virtualenvironment in /usr/local/app/sickchill/.venv
virtualenv found: False
virtualenv module not found, cannot create virtualenv
/usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill

**Comment by sphinxlady** [comment]
The huge issue with plugins and truenas/freenas is they treat plugins as a after thought that they may remember to update after a truenas release.
They sell there products with supported plugins meaning they should have that part of the product built into there office workflow.
This means you can have breaking issues or security holes that sit there for months before they remember to do something.

Is it any wonder other competitors who treat this as any other part of their business sell more and have a better reputation.

The fix for sickchill has been sitting here for weeks but because of how truenas treats plugins on even the products they sell it left unfixed.
A bad business workflow and bad business model.

**Comment by miigotu** [comment]
> I've updated the jail. It is now 12.1-RELEASE-p13. However, sickchill still does not open. 
> 
> When I run the following command inside the jail : `service sickchill start`
> 
> I get this output:
> 
> ```Starting sickchill.  
> sickchill found: False  
> Current environment is not writable!
> Because of the above errors, we will try creating a new virtualenvironment in /usr/local/app/sickchill/.venv
> virtualenv found: False
> virtualenv module not found, cannot create virtualenv
> /usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill

Updating the jail, without recreating it, does not fix the permissions of the SickChill folder. Just `chown -R userthatrunssickchill:groupforuser /usr/local/app/sickchill`

**Comment by sphinxlady** [comment]
The real problem is truenas behaviour towards plugins. Even the ones that have so called support from them don't see any support until a release of truenas happens. This means security holes or plugin breaking bugs are left sitting unfixed for a month or months at a time.
Instead of treating it like part of the workflow like everything else it's left as a after thought even though they sell products advertising support for plugins.

Poor business practice and one that turns people away from the product even though it has great zfs support.

**Comment by Bmiest** [comment]
> The next update for truenass is aug 3 so it would have been pulled shortly anyway.

So tommorow I can update my existing jail and it will pull the correct version? I am having issues getting it up with manual json file. Getting VNET errors atm. 

```
root@jabba[~/jailz]# iocage fetch -P sickchill.json ip4_addr="lagg0|1x.x.x.x"
Plugin: SickChill
  Official Plugin: False
  Using RELEASE: 12.2-RELEASE
  Using Branch: 12.2-RELEASE
  Post-install Artifact: https://github.com/ix-plugin-hub/iocage-plugin-sickchill.git
  These pkgs will be installed:
    - git
    - python3
    - python38
    - py38-pip
    - py38-setuptools
    - py38-sqlite3
    - py38-pillow
    - py38-virtualenv
    - unrar
    - ca_root_nss
    - libmediainfo
    - libxslt
    - libxml2
    - rust

Stopped SickChill due to VNET failure
SickChill had a failure
Exception: SystemExit Message: 1
Partial plugin destroyed
```

**Comment by sphinxlady** [comment]
> 
> 
> > The next update for truenass is aug 3 so it would have been pulled shortly anyway.
> 
> So tommorow I can update my existing jail and it will pull the correct version? I am having issues getting it up with manual json file. Getting VNET errors atm.
> 
> ```
> root@jabba[~/jailz]# iocage fetch -P sickchill.json ip4_addr="lagg0|1x.x.x.x"
> Plugin: SickChill
>   Official Plugin: False
>   Using RELEASE: 12.2-RELEASE
>   Using Branch: 12.2-RELEASE
>   Post-install Artifact: https://github.com/ix-plugin-hub/iocage-plugin-sickchill.git
>   These pkgs will be installed:
>     - git
>     - python3
>     - python38
>     - py38-pip
>     - py38-setuptools
>     - py38-sqlite3
>     - py38-pillow
>     - py38-virtualenv
>     - unrar
>     - ca_root_nss
>     - libmediainfo
>     - libxslt
>     - libxml2
>     - rust
> 
> Stopped SickChill due to VNET failure
> SickChill had a failure
> Exception: SystemExit Message: 1
> Partial plugin destroyed
> ```

Maybe

Plugin support in Truenas for plugins is a bit of a joke.
The official supported plugins and the unsupported community plugins in truth get the same exact type of support.
They get updated when there a Truenss  update if they remember.

Not so great when your selling products you advertise support but you go a month to months without doing so.

**Comment by Bmiest** [comment]
> > > The next update for truenass is aug 3 so it would have been pulled shortly anyway.
> > 
> > 
> > So tommorow I can update my existing jail and it will pull the correct version? I am having issues getting it up with manual json file. Getting VNET errors atm.
> > ```
> > root@jabba[~/jailz]# iocage fetch -P sickchill.json ip4_addr="lagg0|1x.x.x.x"
> > Plugin: SickChill
> >   Official Plugin: False
> >   Using RELEASE: 12.2-RELEASE
> >   Using Branch: 12.2-RELEASE
> >   Post-install Artifact: https://github.com/ix-plugin-hub/iocage-plugin-sickchill.git
> >   These pkgs will be installed:
> >     - git
> >     - python3
> >     - python38
> >     - py38-pip
> >     - py38-setuptools
> >     - py38-sqlite3
> >     - py38-pillow
> >     - py38-virtualenv
> >     - unrar
> >     - ca_root_nss
> >     - libmediainfo
> >     - libxslt
> >     - libxml2
> >     - rust
> > 
> > Stopped SickChill due to VNET failure
> > SickChill had a failure
> > Exception: SystemExit Message: 1
> > Partial plugin destroyed
> > ```
> 
> Maybe
> 
> Plugin support in Truenas for plugins is a bit of a joke.
> The official supported plugins and the unsupported community plugins in truth get the same exact type of support.
> They get updated when there a Truenss update if they remember.
> 
> Not so great when your selling products you advertise support but you go a month to months without doing so.

I understand, however I can't find a way to manually update an existing jail with a local json file. So I either keep debugging my VNET issues to create a new one or wait till the update might work again. Shame but so far nothing.

**Comment by sphinxlady** [comment]
Sadly this is the state of things.

Unfortunately it seems they didn't feel like updating any plugins which shows their attitude toward even supported ones.

Moving the software away from the nas and leaving it as just storage is the way to go as support is just too much of a joke and causes too many headaches.

**Comment by phoenix7700** [comment]
I update sickchill very infrequently and was around 200 commits behind. After trying to update the WebGUI broke for me same as most people above. None of the fixes in this thread are working for me. Also Im Updating to 12.2-RELEASE-p8 which is different than what most people are mentioning. Tried new install and getting same issues.

**Comment by fxxer** [comment]
My only workaround was to rollback SickChill jail to 12.1-RELEASE-p12 snapshot, that I have from last jail upgrade.

**Comment by sphinxlady** [comment]
Truenas is aware of the issue they just don't care.
Even their so called supported plugins are treated as a joke with updates only happening once a month to once ever three depending on the  freenas/truenas update cycle.

There a fair chance this wont get updated unless people start pestering the hell out of them.

**Comment by sphinxlady** [comment]
At this point i wouldn't go expecting a update from truenas.

There basically just ignoring the community and doing whatever they want.
The business end has now killed most of the free end support.

The company seems to have forgotten how it became popular in the first place.

**Comment by turboture** [comment]
Is there anyone in the community that know how to fix it?

**Comment by Toolazy2work** [comment]
After 3 months of being down, I moved to anothrr product.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Bmiest** [comment]
> Is there anyone in the community that know how to fix it? @fulder? You helped me last time.

I moved it to a docker container on my docker host. After setting An NFS share and a bit of fiddling with the rights I am back up and running after a few short hours now. My backup was from 2020 so it's catching up right now. I am keeping as far as possible from running anything in a jail that isn't Plex.

**Comment by sphinxlady** [comment]
I think at this point he fed up. When you have to fight the bugs and then deal with the developers of truenas treating plugins as a after thought it becomes too much. With a family he got better things to do then get stressed out with this. As mentioned there work arounds but it anyone guess on how development going to go.

**Comment by fulder** [comment]
> Is there anyone in the community that know how to fix it? @fulder? You helped me last time.

Hi, sorry I don't follow this specific repository, use this software or am the creator of the SickChill plugin for TrueNAS. But can try to help out here as best as I can.

 I just tried a fast installation of the plugin and can verify (like the rest of you) that it seems broken. Browsing through other comments in this issue and the creation date of it I'm guessing either there was another bug at the creation time or there currently is a new bug and the reason why the plugin is not working. 

Looking into more details why the service doesn't seem to start (with the previously mentioned tip to remove the deamon flag) I noticed the `pygithub`  package was not properly installed during the package installation inside the venv and a quick search in this repo pointed me to this issue: https://github.com/SickChill/SickChill/issues/7489. Fetching the dev version of the `init_helpers.py` file and replacing the iocage version of it + restarting SickChill made startup take a while (I think it's compiling a lot of e.g. crypto packages from scratch using rust etc. would probably be better to just include some of the required packages as the prebuilt freebsd using `pkg` to speed this up, but that's outside of this issue) and finally it managed to install and startup SickChill properly after that making the UI reachable as well.

@Tiladen finding:
>So it looks like when it's restarting SickChill it's trying to use the same PID file and failing because it already exists.
Would it be safe and/or make sense to remove the pid file before restarting SickChill so the new instance can reuse the same PID file?

Seems to be correct and these PID issues are still there. Although I'm guessing that's more a SickChill bug which shouldn't have much to do with FreeBSD. 

The only way I managed to get SickChill running with the deamon flag is to remove the `--pidfile` flag from the startup command as well. Then the restart seems to work fine, but that's probably not a very "good" fix for this issue.

Summarized, I think there are a few bugs which need to be addressed on SickChill level rather than trying to quickfix them on TN plugin level.

**Comment by turboture** [comment]
@fulder Thank you for the time you have put in to helping us with this plugin.

**Comment by Toolazy2work** [comment]
Is this issue resolved or are people just no longer reporting?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by turboture** [comment]
Where is this file located where we should delete the --pidfile to get sickchill to start working again?

I found an init.freebds file under /local/app/sickchill/contrib/runscripts where there was a line with --pidfile (--pidfile ${pidfile} --quiet --nolaunch. Is it that line I should remove? The whole line or just the end?

**Comment by turboture** [comment]
Cant get it to work. Can anyone point me to a webpage that shows how to get sickchill to run under truenas TrueNAS-12.0-U6? Where step by step is posted. I have googled a tried everything I have found but cant get it to work. It's getting frustrating and since my knowlege in truenas/freebds i limited I need help. Anyone?
You who follow this thread. What have you done?

**Comment by turboture** [comment]
Thank you. Worked perfect.  If anyone else finds this thread and want to follw this excellent guide, the file @Ellimist1106 is refering to is misslabeled/missplaced. 

![image](https://user-images.githubusercontent.com/14950060/139526347-11d5f238-6a99-4d91-be13-4f5ccfa0a7db.png)

**Comment by odedia** [comment]
Thanks for this! Do you know if it is possible to disable automatic updates of SickChill? 
This caused my existing setup to break after few weeks.

**Comment by Ellimist1106** [comment]
> Thanks for this! Do you know if it is possible to disable automatic updates of SickChill? This caused my existing setup to break after few weeks.

Settings -> General -> Automatically Update

Its right at the bottom of that general page.

**Comment by Vivan** [comment]
Is there any plan to fix this issue or is TrueNAS just not supported any more?

**Comment by turboture** [comment]
Good question. There should be a filter in TrueNAS that disables plugins that doesent work.

**Comment by danielmarkavis** [comment]
My solution was this...

Create the jail with the broken plugin, then shell into it.

$ rm -R /usr/local/app/sickchill
$ git clone https://github.com/SickChill/SickChill.git /usr/local/app/sickchill
$ pkg install python
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python get-pip.py
$ chown -R sickchill:sickchill /usr/local/app/sickchill
$ cd /usr/local/app/sickchill
$ pip install -U sickchill
$ service sickchill start

The service may hang, but just cancel it, however the service has started.

**Comment by miigotu** [comment]
> My solution was this, using TrueNAS v12...
> 
> Create the jail with the broken plugin, then shell into it.
> 
> $ rm -R /usr/local/app/sickchill $ git clone https://github.com/SickChill/SickChill.git /usr/local/app/sickchill $ pkg install python $ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py $ python get-pip.py $ chown -R sickchill:sickchill /usr/local/app/sickchill $ cd /usr/local/app/sickchill $ pip install -U sickchill $ service sickchill start
> 
> The service may hang, but just cancel it, however the service has started.

This is a weird process.

There is no reason to both clone and pip install, either you install with pip or git. I think what you are doing here is installing SC dependencies with the pip install, and using the service file from the package, and the code from git. It's strange lol.

```bash
rm -R /usr/local/app/sickchill
pkg install python3
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
pip install -U sickchill
(change the service file to run sickchill directly)
```

The package should be updated to use a pip install properly.
