### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Viceland (US). Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by identd113** [SickChill/SickChill#7351]
### INFO
Python Version: **3.9.6 (default, Jun 29 2021, 06:20:32) [Clang 12.0.0 (clang-1200.0.32.29)]**
Operating System: **macOS-10.15.7-x86_64-i386-64bit**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@794f94bdbe8b3d4c871ea4d6184a945f4354d35a
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Viceland (US). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by chris41g** [comment]
### INFO
Python Version: **3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]**
Operating System: **Linux-5.11.0-25-generic-x86_64-with-glibc2.33**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Viceland (US). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
#7231

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Viceland (US). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
