### ISSUE TITLE
Folder switches to read only

### ISSUE THREAD

**Issue by c1149** [SickChill/SickChill#7362]
Branch/Commit: Latest version
OS: Raspbian
Browser: Chrome edge
What you did: new installation

I'm using Sickchill on a raspberry pi. Os is rasbian. Everything seems to work. I see my overview of series. Connection with transmission is ok. Then downloads automatically start but after a few mb in the download. The download stops. In transmission I get read only file system error.

I know, it could be a problem with transmission. But when I manually start a download through transmission, there is no problem.

After the download (manual), files aren't processed. This is because my mounted external hard drive turns to read only mode I assume. 

I can change is to write mode. But always after sickchill is running and I starts a download or post processing starts, the external hard drive turns to read only mode again.

Any ideas?

Thanks in advance

**Comment by kyuuk** [comment]
can you give us more details, how is your external drive mounted (fstab, manually, Script ?), is it mounted on boot ?

**Comment by c1149** [comment]
> can you give us more details, how is your external drive mounted (fstab, manually, Script ?), is it mounted on boot ?

 lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda           8:0    0  2,7T  0 disk 
└─sda1        8:1    0  2,7T  0 part /mnt/seagateHD
mmcblk0     179:0    0 29,5G  0 disk 
├─mmcblk0p1 179:1    0  256M  0 part /boot
└─mmcblk0p2 179:2    0 29,3G  0 part /

fstab
proc            /proc           proc    defaults          0       0
PARTUUID=1fa7135e-01  /boot           vfat    defaults          0       2
PARTUUID=1fa7135e-02  /               ext4    defaults,noatime  0       1
# a swapfile is not a swap partition, no line here
#   use  dphys-swapfile swap[on|off]  for that
UUID=cf76d97e-9546-462c-92db-bc80291e72ad /mnt/seagateHD ext4 defaults,auto,users,rw,nofail,noatime 0 0

If it's in fstab, it's mounted on boot I think right?
But sometimes I mount it with a manual command.

If you need to know anything else, please let me know.
Sickchill used to work before but it's currently useless because I can't download or post process anything.

**Comment by kyuuk** [comment]
not really , it's the option `auto` that make it mount on boot 
try changing your mount options to :
`defaults,user,nofail,noatime`  -> notice the missing "s" on user 

Also do you connect your drive to a windows machine ?

**Comment by c1149** [comment]
What do you mean with the windows machine?
It's only connected to the raspberry pi.

I have attached it to a Windows machine in the past.
Also to try and remove the read only mode through windows.

I'll try to change the settings.
WIll it take affect immediately?

**Comment by kyuuk** [comment]
Actually there is a bug where if you attach an external drive to a windows machine and don't eject it properly before unplugging  it causes this behaviour, so you may need to try connecting it to a windows machine and safely eject it before unplugging,

for the setting you will need to umount and remount your drive, or just reboot 😄

**Comment by miigotu** [comment]
Is it a powered hdd or is the power coming from the usb?

**Comment by c1149** [comment]
It is powered hdd.

Update:
It seems to have worked for a while. (one day :))
I had a download that could finish. But I noticed files weren't processed.

I tried a manual post processing. 
That worked for 1 of the downloads, the other failed but could have had a different reason.
System was still Read-Write.

Now I downloaded something else. Again no automatic post processing, so I checked the option:
_"create missing show directories when they get deleted"_

It can be a coincidence, but I checked this option this morning.
I'm checking a few hours later and the system is Read Only again.

Processing method is Move btw. Don't know if that can be an issue.

**Comment by kyuuk** [comment]
Maybe it is your drive that is failing, 

next time it happens try running a `dmesg -T` maybe you will find some error logs that may help, 
and get the output of  `mount | grep /mnt`  

also try running an fsck on your drive to search for filesystem errors.

**Comment by c1149** [comment]
``I'm seeing errors when I run dmesg -T

This is a part of it.
```
`EXT4-fs (sda1): I/O error while writing superblock
[wo jul 28 05:19:43 2021] EXT4-fs error (device sda1): ext4_journal_check_start:83: Detected aborted journal
[wo jul 28 05:19:43 2021] EXT4-fs (sda1): Remounting filesystem read-only
[wo jul 28 05:19:47 2021] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08 cmd_age=3s
[wo jul 28 05:19:47 2021] sd 0:0:0:0: [sda] tag#0 Sense Key : 0x3 [current] 
[wo jul 28 05:19:47 2021] sd 0:0:0:0: [sda] tag#0 ASC=0x11 ASCQ=0x0 
[wo jul 28 05:19:47 2021] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 26 21 0e 71 00 00 01 00
[wo jul 28 05:19:47 2021] blk_update_request: critical medium error, dev sda, sector 5117604744 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[wo jul 28 05:19:49 2021] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08 cmd_age=2s
[wo jul 28 05:19:49 2021] sd 0:0:0:0: [sda] tag#0 Sense Key : 0x3 [current] 
[wo jul 28 05:19:49 2021] sd 0:0:0:0: [sda] tag#0 ASC=0x11 ASCQ=0x0 
[wo jul 28 05:19:49 2021] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 26 21 0e 71 00 00 01 00
[wo jul 28 05:19:49 2021] blk_update_request: critical medium error, dev sda, sector 5117604744 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[wo jul 28 05:19:59 2021] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08 cmd_age=3s
[wo jul 28 05:19:59 2021] sd 0:0:0:0: [sda] tag#0 Sense Key : 0x3 [current] 
[wo jul 28 05:19:59 2021] sd 0:0:0:0: [sda] tag#0 ASC=0x11 ASCQ=0x0 
[wo jul 28 05:19:59 2021] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 26 21 0e 6f 00 00 01 00
[wo jul 28 05:19:59 2021] blk_update_request: critical medium error, dev sda, sector 5117604728 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[wo jul 28 05:20:02 2021] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08 cmd_age=3s
[wo jul 28 05:20:02 2021] sd 0:0:0:0: [sda] tag#0 Sense Key : 0x3 [current] 
[wo jul 28 05:20:02 2021] sd 0:0:0:0: [sda] tag#0 ASC=0x11 ASCQ=0x0 
[wo jul 28 05:20:02 2021] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 26 21 0e 6e 00 00 01 00
[wo jul 28 05:20:02 2021] blk_update_request: critical medium error, dev sda, sector 5117604720 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[wo jul 28 05:20:05 2021] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08 cmd_age=3s
[wo jul 28 05:20:05 2021] sd 0:0:0:0: [sda] tag#0 Sense Key : 0x3 [current] 
[wo jul 28 05:20:05 2021] sd 0:0:0:0: [sda] tag#0 ASC=0x11 ASCQ=0x0 
[wo jul 28 05:20:05 2021] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 26 21 0e 71 00 00 01 00
[wo jul 28 05:20:05 2021] blk_update_request: critical medium error, dev sda, sector 5117604744 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[wo jul 28 05:20:08 2021] sd 0:0:0:0: [sda] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08 cmd_age=2s
[wo jul 28 05:20:08 2021] sd 0:0:0:0: [sda] tag#0 Sense Key : 0x3 [current] 
[wo jul 28 05:20:08 2021] sd 0:0:0:0: [sda] tag#0 ASC=0x11 ASCQ=0x0 
[wo jul 28 05:20:08 2021] sd 0:0:0:0: [sda] tag#0 CDB: opcode=0x28 28 00 26 21 0e 70 00 00 01 00
[wo jul 28 05:20:08 2021] blk_update_request: critical medium error, dev sda, sector 5117604736 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[wo jul 28 13:57:18 2021] EXT4-fs (sda1): error count since last fsck: 12
[wo jul 28 13:57:18 2021] EXT4-fs (sda1): initial error at time 1626152733: ext4_journal_check_start:83
[wo jul 28 13:57:18 2021] EXT4-fs (sda1): last error at time 1627442023: ext4_journal_check_start:83
```

Mount | grep /mnt gives:
`/dev/sda1 on /mnt/seagateHD type ext4 (ro,nosuid,nodev,noexec,noatime,user)
`

I just don't understand why it's working at first but after a while, when SickChill is trying to move / download files, it goes to Read Only.

Formatting the External Hard Drive would fix the issue?
Any suggestions how I can safely copy my +- 2 TB of data?
I don't have other Hard drive of that size with enough free space.

Or how can I safely fix the errors without removing the data on the External Hard Drive?

Thanks

**Comment by kyuuk** [comment]
Sorry to say this, but it seems your drive is failing because it have corrupted blocks and your system is remounting it as read-only, i am no hard drive expert but i would advice you to get a new one and copy your data before loosing everything.
```
`EXT4-fs (sda1): I/O error while writing superblock
[wo jul 28 05:19:43 2021] EXT4-fs error (device sda1): ext4_journal_check_start:83: Detected aborted journal
[wo jul 28 05:19:43 2021] EXT4-fs (sda1): Remounting filesystem read-only
```
you could try an `fsck -fp /dev/sda1` to try a repair of the filesystem, and see if it happens again.


So i would say that this is a hard drive problem & not a Sickchill issue, thank you for closing the issue 😄

**Comment by c1149** [comment]
I ordered a new hard drive. 
I will try to format the old hd. 
 
Issue isn't related to Sickchill

**Comment by miigotu** [comment]
@c1149 sorry we couldn't help much. At least you can catch some of the data off of there before it dies. If it is a platter issue, you might be able to do something with marking bad sectors/badblocks.
