### ISSUE TITLE
is Docker image up to date?

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#7376]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: e1e91c3ec3c90479b556e7e78b48dc3bb81ead01
Version: 2021.07.14-6
Database Version: 44.5
  Python Version:3.7.11 (default, Jun 29 2021, 20:40:03) [GCC 8.3.0]
Browser: Edge

What you did:  Saw message `31 commits behind. New version available`
     logged in to NAS via Putty:
```
     docker pull sickchill/sickchill
````
What happened:
   ````
   Using default tag: latest
   latest: Pulling from sickchill/sickchill
   Digest: sha256:bdace97c0b8491139d49d5e343f0f5d3412bf24ba23452df5f5435fb20ee82fe
   Status: Image is up to date for sickchill/sickchill:latest
````

What you expected:  
    New version to be downloaded

Is the docker version not yet updated?
Should I be downloading in some other manner?

**Comment by kyuuk** [comment]
Hello @ronrosenfeld there are some issues with the docker image publishing, so it's not up to date with the latest version of sickchill, we hope it will be fixed soon, but we need to be patient 😄

**Comment by ronrosenfeld** [comment]
Any idea when it will be fixed?  A year or so ago, I switched from linuxserver/sickchill to sickchill/sickchill because the former wasn't updating (and some other reasons also).  But I see as of today that the situation has reversed.

**Comment by miigotu** [comment]
The latest tag on docker hub is like a week or so old. It is not even with master (and should not be, it is supposed to be a stable commit.)

When master hits another stable commit that actually has any changes that are necessary to fix something for docker users, it will be tagged again. For now, just update from inside the container.
