### ISSUE TITLE
Parmount+ image not found

### ISSUE THREAD

**Issue by gastonfama** [SickChill/SickChill#7380]
Branch: master
Commit: 5f63ed027cd80bd85604885d67d3fef3e40f42c9
Version: 2021.07.29
Database Version: 44.5

Browser: Chrome
The `Paramount+` icon is missing.

![image](https://user-images.githubusercontent.com/73205187/127745074-73c7bde4-8027-4b27-a446-256b923a5ef1.png)

There is a 404 not found error when trying to find the image located at /images/network/paramount+.png

Please, let me know if I can post some other information or anything else I can help with.

Thank you.

Regards.

**Comment by gastonfama** [comment]
I have been loking in the repo and the file name is different.

https://github.com/SickChill/SickChill/tree/master/sickchill/gui/slick/images/network

The system is looking for `paramount+.png` but the files related are `paramount network.png` and `paramount-network.png`.

I don't know what is easy or best.  
To add a copy of the image with the  `paramount+.png` name or change the code to point to the already existing image.

Thank you

Regards.

**Comment by miigotu** [comment]
The current way is you have to copy and rename the image to the name it is looking for. PR is welcome, I'm super busy this week.
