### ISSUE TITLE
Sickchill (on win 10) can't find shares (on NAS)

### ISSUE THREAD

**Issue by sanomi78** [SickChill/SickChill#7381]
Branch/Commit: pip
OS: Windows 10
Browser: Edge
What you did: Try to do a manual post processing
What happened: couldn't find location to post process
What you expected: being able to browse to the NAS (via IP Address) as before

Logs:
```
Nothing specific to be found in logs since no map shows up
```

I had to recently re-install Sickchill on my Win 10 machine because an update broke it. After the update i can't access my remote NAS anymore (on a local network, with the IP address). I tried everything i could find on Github and other google sources, but i can't get the GUI to browse to the correct location anymore.

I am on a Live account. I also tried adding a local account but to no avail. I included some screenshots.
![Schermafbeelding 2021-07-31 191825](https://user-images.githubusercontent.com/1458322/127747881-b3e6d75b-ef0c-4a6e-8dde-4207689002d9.jpg)
![Schermafbeelding 2021-07-31 191947](https://user-images.githubusercontent.com/1458322/127747882-14d266d9-c632-4a66-abad-fe75205a074b.jpg)

**Comment by miigotu** [comment]
Edit the SickChill service and set it to run as your user, not "local system"

**Comment by miigotu** [comment]
Not a sickchill issue btw, it is a windows issue.

**Comment by sanomi78** [comment]
> Edit the SickChill service and set it to run as your user, not "local system"

I did try that, but then the service refuses to start anymore

**Comment by nydave69** [comment]
can you map the NAS as a drive and see if SickChil can use the drive letter.
The is a long standing bug in the windows installer that creates a service with local service privileges.

**Comment by sanomi78** [comment]
> can you map the NAS as a drive and see if SickChil can use the drive letter.
> There is a long standing bug in the windows installer that creates a service with local service privileges and not the user privileges.

I mapped the map to Z and i still cannot access it

**Comment by nydave69** [comment]
You have to either set the privileges for that service to administrator.
Or run the application from your user account and disable the service.

**Comment by sanomi78** [comment]
> You have to either set the privileges for that service to administrator.
> Or run the application from your user account and disable the service.

It is now set to run as the Administrator account, but i still cannot access.

Disabling the service? Why would one do that? Won't that disable the whole program?

**Comment by davidreverett** [comment]
Mapped drives and shares are not accessible when SC runs as a system service. This is due to how Windows 10 works. You'll have to run SC service in services.msc as a domain user on that machine for this to work. I have the same setup, SC lives on my Plex server and runs as the same service account as Plex. Has access to all the shares and mapped drives.

**Comment by nydave69** [comment]
after you set it to administrator with the password did you stop and restart the service.

**Comment by davidreverett** [comment]
Yes

**Comment by nydave69** [comment]
Well I run it as a regular user account. and map the drives from the NAS units..

**Comment by sanomi78** [comment]
> Mapped drives and shares are not accessible when SC runs as a system service. This is due to how Windows 10 works. You'll have to run SC service in services.msc as a domain user on that machine for this to work. I have the same setup, SC lives on my Plex server and runs as the same service account as Plex. Has access to all the shares and mapped drives.

Sorry but i am getting rather confused now. This is how i've setup the service now and it does start:

![Schermafbeelding 2021-07-31 214002](https://user-images.githubusercontent.com/1458322/127750760-e14c08dc-6b30-4536-bb87-9bf6a88408c9.jpg)

But i still cannot access the IP address

**Comment by sanomi78** [comment]
the saddest thing is that i used to run it from my QNAP TS-410 NAS and it went brilliantly altho a bit slow. But since they decided to not support it anymore i'm stuck with running it on my Windows PC.

**Comment by nydave69** [comment]
You could try to run it under you user,
Stop and disable the service for SickChill.
Create a desktop shortcut. it must use the built in python from within sickchill.
I'm using windows 7 for my servers. The command line in mine is;

`C:\SickChill\Python3\tools\python.exe C:\SickChill\Python3\tools\Scripts\SickChill.py --nolaunch --port 8081 --datadir C:\\SickChill\\Data`

Mine should be close to what you need to use.

**Comment by sanomi78** [comment]
> @sanomi78
> You could try to run it under you user,
> Stop and disable the service for SickChill.
> Create a desktop shortcut. it must use the built in python from within sickchill.
> I'm using windows 7 for my servers. The command line in mine is;
> 
> `C:\SickChill\Python3\tools\python.exe C:\SickChill\Python3\tools\Scripts\SickChill.py --nolaunch --port 8081 --datadir C:\\SickChill\\Data`
> 
> Mine should be close to what you need to use.
> 
> edit: When I did the install I told it to install SickChill to C:\SickChill you'rs may be different.

Ok, this seems to work. I'll keep you posted

**Comment by miigotu** [comment]
> can you map the NAS as a drive and see if SickChil can use the drive letter.
> There is a long standing bug in the windows installer that creates a service with local service privileges and not the user privileges.
> 
> 

It's not a bug, innosetup does not have the capability to get user name or password, the only option is to ask the user in the installer pages. Adding that page to the installer is an enhancement, the lack of it is not a bug. Ideally a user running SC should be leaving the machine running SC on 24/7, which means it is much more energy efficient and cost effective, and has much higher performance to simply add the storage to the same machine.

**Comment by sanomi78** [comment]
> > can you map the NAS as a drive and see if SickChil can use the drive letter.
> > There is a long standing bug in the windows installer that creates a service with local service privileges and not the user privileges.
> 
> It's not a bug, innosetup does not have the capability to get user name or password, the only option is to ask the user in the installer pages. Adding that page to the installer is an enhancement, the lack of it is not a bug. Ideally a user running SC should be leaving the machine running SC on 24/7, which means it is much more energy efficient and cost effective, and has much higher performance to simply add the storage to the same machine.

Which of course was the case until "they" decided to not support my NAS anymore

**Comment by miigotu** [comment]
> > Mapped drives and shares are not accessible when SC runs as a system service. This is due to how Windows 10 works. You'll have to run SC service in services.msc as a domain user on that machine for this to work. I have the same setup, SC lives on my Plex server and runs as the same service account as Plex. Has access to all the shares and mapped drives.
> 
> Sorry but i am getting rather confused now. This is how i've setup the service now and it does start:
> 
> ![Schermafbeelding 2021-07-31 214002](https://user-images.githubusercontent.com/1458322/127750760-e14c08dc-6b30-4536-bb87-9bf6a88408c9.jpg)
> 
> But i still cannot access the IP address

./administrator does not have permissions for network shares by default. Create a new user, set SC to run as that user, give the shares everyone permissions, and use the `///server_name/share_name/folder` path. The shows dir or the downloads dir cannot be the root of the share, you have to have a share like `///server/sharename` and set `///server/sharename/downloads` and `///server/sharename/shows`

**Comment by sanomi78** [comment]
@nydave69 @miigotu both solutions worked. I've gone with the second solution (altho i am using the IP address which is fixed anyway and how i prefer it). Thanks for all the help from everyone, you too @davidreverett
