### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Amazon Studios. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by glancy** [SickChill/SickChill#7383]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.10.28-Unraid-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@0306ded8f236585531276bc4cc1db9303f26bfce
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Amazon Studios. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
#7231
