### ISSUE TITLE
SickChill on Windows won't start

### ISSUE THREAD

**Issue by vlastaw** [SickChill/SickChill#7384]
Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)
Enabled. Won't start, so no log. In log last shutdown was after I updated from the webui on July 23, hasn't started again. I noticed today.

Attempts to fix:
Manually updated by overwriting SickChill folder, Python3 folder (with Python 3.8.10 embeddable). Then reverted Sickchill folder and git pulled it. No success.

Branch/Commit:
OS: Windows 10 21H1 build 19043.1110
Browser: Independent
What you did: Tried to launch service via NSSM or Windows GUI.
What happened: Launched and Paused immediately.
What you expected: Launched.
Logs: None. Won't start.

What you did: Tried to launch via commandline.
What happened: Errored.
What you expected: Launched.
Logs:
C:\SickChill\Python3>python
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
>>> "C:\SickChill\SickChill\SickChill.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data"
  File "<stdin>", line 1
SyntaxError: cannot assign to operator

**Comment by miigotu** [comment]
Back up, through the gui if you can, and copy c:\sickchill\data to another place outside of c:\sickchill. Uninstall and select the option to keep your config and database. Use the newest sickchill installer.
