### ISSUE TITLE
Can't set archived to wanted

### ISSUE THREAD

**Issue by jeroenst** [SickChill/SickChill#7397]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 
OS: Linux-3.2.40-armv7l-with-glibc2.4
Browser: Chrome
What you did: Selected a archived episode, and changed to wanted (also tried manual search and manual snatch)
What happened: Episode stays archived (when I refresh the status is wanted for a few seconds and then changes to archived again)
What you expected: Episode becomes wanted
Logs:
```
Will add later, sickchill is now very busy, generating a huge amount of logging
```

**Comment by jeroenst** [comment]
Hi Bot,
I already did a search, but couldn't find anything about this.

**Comment by miigotu** [comment]
Set from archived to skipped or ignored, then to wanted.
