### ISSUE TITLE
Cant run sickchill on startup (timeout fail / problem with PID file)

### ISSUE THREAD

**Issue by BUZZ2K** [SickChill/SickChill#7401]
Branch/Commit: Main
OS: Debian Buster
Browser: Chrome
What you did: Fresh Install of Sickchill with PIP and systemd to run on startup
What happened: Sickchill run on startup but timeout a few minutes later
What you expected: Sickchill running for life

Hi, 

I was originally speaking on another thread when it was impossible for me to get sickchill started but now the issue is different, i think it would be easier to get a specific topic. If not, feel free to erase it and i would continue on the other thread.

So, after an update, Sickchill went broken. I used to do a fresh install (old way) and got the same issue so i installed it like suggested by miigotu : with pip

>
>sudo apt install python3.8
>python3.8 -m venv /opt/sickchill-env
>
>/opt/sickchill-env/bin/pip install sickchill
>

Then, i created a systemd service file sickchill.service like this in /etc/systemd/system : 

>
>[Unit]
>Description=SickChill Daemon
>
>[Service]
>Type=forking
>User=sickchill
>Group=sickchill
>
>PIDFile=/run/sickchill/sickchill.pid
>ExecStart=/opt/sickchill-env/bin/python /opt/sickchill-env/bin/SickChill.py -q --daemon
>ExecReload=/bin/sh -c "/bin/kill -s HUP $(/bin/cat /run/sickchill/sickchill.pid)"
>ExecStop=/bin/sh -c "/bin/kill -s TERM $(/bin/cat /run/sickchill/sickchill.pid)"
>
>[Install]
>WantedBy=multi-user.target
>

enabled the file, and tried to launch it : sudo systemctl start sickchill
Sickchill start but stop a few minutes later : 

>● sickchill.service - SickChill Daemon
>   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
>   Active: failed (Result: timeout) since Thu 2021-08-05 08:08:49 UTC; 5min ago
>  Process: 15469 ExecStart=/opt/sickchill-env/bin/python /opt/sickchill-env/bin/SickChill.py -q --daemon (code=exited, >status=0/SUCCESS)
>
>Aug 05 08:07:09 vps-5e21893a systemd[1]: Starting SickChill Daemon...
>Aug 05 08:07:09 vps-5e21893a systemd[1]: sickchill.service: Can't open PID file /run/sickchill/sickchill.pid (yet?) after start: No >such file or directory
>Aug 05 08:08:39 vps-5e21893a systemd[1]: sickchill.service: Start operation timed out. Terminating.
>Aug 05 08:08:49 vps-5e21893a systemd[1]: sickchill.service: Failed with result 'timeout'.
>Aug 05 08:08:49 vps-5e21893a systemd[1]: Failed to start SickChill Daemon.
>

As suggested by Leeporte, created a file located at /usr/lib/tmpfiles.d/sickchill.conf

>
>d /run/sickchill 0755 sickchill sickchill -
>

But i got the same result.

I searched a lot but dont find any other tutorial to install sickchill with pip and setup a systemd file to get it run on startup. I'm lost now and would be glad if anyone can help.

Thanks in advance.

**Comment by kyuuk** [comment]
Hello, i'm not sure about this, but try adding a longer timeout after `ExecStop` line 
`TimeoutSec=300`

maybe it's just sickchill taking a little too long to start with poetry dependencies check and systemd is killing it !

**Comment by BUZZ2K** [comment]
Hi,
Thanks for the help.
I've tried adding the timeout, enabled the service and started it. Unfortunately, the issue is the same.
I think i may be experiencing a right issue ?
Thanks in advance.

**Comment by kyuuk** [comment]
Maybe try adding `--pidfile=/run/sickchill/sickchill.pid` argument to the `ExecStart`

Also where did you find this service file ? if you did write it yourself you should take a look here 
https://github.com/SickChill/SickChill/blob/a8e5d00f02e5d27719409bb9d7d733042b294b82/contrib/runscripts/init.systemd

**Comment by kyuuk** [comment]
You are welcome @BUZZ2K.
Actually the problem is that you were telling systemd that he will find the pid file at that location but you were not telling sickchill to create it xD
