### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: CTV Drama (Bravo). Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by hubdows** [SickChill/SickChill#7404]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@5f63ed027cd80bd85604885d67d3fef3e40f42c9
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: CTV Drama (Bravo). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by AP-Engineering** [comment]
https://github.com/SickChill/SickChill/issues/7231

**Comment by cadmuslabslex** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: CTV Drama (Bravo). Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
