### ISSUE TITLE
Synology - Install fails with "Invalid file format. Please contact the package developer"

### ISSUE THREAD

**Issue by Hemie143** [SickChill/SickChill#7411]
Downloaded from SynoCommunity on 7th August 2021. The package is downloaded and immediately fails with the message "SickChill: Invalid file format. Please contact the package developer".

**Comment by Hemie143** [comment]
The Synology model is a DS920+, with an Intel Celeron J4125, running DSM 7.0-41890.

**Comment by JacquesSparro** [comment]
Hi, i have the same problem since i migrate from DSM6 to DSM 7.0-41890. My model is DS216+II.
And same message if i try to reinstall the package  "The package is downloaded and immediately fails with the message "SickChill: Invalid file format. Please contact the package developer".

**Comment by BKSteve** [comment]
DSM 7 package doesn't currently exist and is under development. [https://github.com/SynoCommunity/spksrc/pull/4743](https://github.com/SynoCommunity/spksrc/pull/4743)

**Comment by bfasan** [comment]
I have same problem python install which is an automatic dependency install when installing sickbeard give invalid file format, please contact developer. error

**Comment by BKSteve** [comment]
Here on SickChill we don't support Sickbeard or Sickbeard-custom.

Latest **SickChill** v20211110-4 is on SynoCommunity, but if not available in your DSM package center you can be manually downloaded [here](https://synocommunity.com/package/sickchill) for both DSM6 and DSM7 and requires Python 3.8.12-6
