### ISSUE TITLE
Sickchill Service Does Not Start After a New Install on Lubuntu 21.04 

### ISSUE THREAD

**Issue by potequity** [SickChill/SickChill#7413]
# Before submitting your issue:

Followed installation instructions at https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15

Branch/Commit:
OS: Ubuntu 21.04
Browser: Firefox 90.0.2
What you did: Installed sickchill on a new machine and tried to start the service in 2 scenarios:

Scenario 1:
su - sickchill
$ service sickchill start
Failed to start sickchill.service: Access denied
See system logs and 'systemctl status sickchill.service' for details.

Scenario 2:

Started sickchill service as root, the service starts but dies after a few seconds.

What you expected:
Logs:
```
I don't see any sickchill related error messages in /var/log/syslog other than this:

Aug  8 14:29:35 linux02 systemd[1]: Starting SickChill Daemon...
Aug  8 14:29:36 linux02 systemd[1]: Started SickChill Daemon.
Aug  8 14:29:42 linux02 systemd[1]: sickchill.service: Succeeded.

Please let me know what other information would help you in troubleshooting this issue.

Thanks in advance!

-PE

**Comment by miigotu** [comment]
#7412
