### ISSUE TITLE
Sickchill package not  working on DSM 7

### ISSUE THREAD

**Issue by KittyBB** [SickChill/SickChill#7430]
Hello,

Allow me to change this discussion into an issue. 

I'd like to know if there are any plans to make a new package that would be compatible on Synology DSM7

Thank you! 

### Discussed in https://github.com/SickChill/SickChill/discussions/7403

<div type='discussions-op-text'>

<sup>Originally posted by **KittyBB** August  5, 2021</sup>
Hello all,

I just upgraded Sickchill to DSM7 and apparently too many things changed. 

I'd like to know if there's  a package I can install for it to work again? 
For now, it displays that the package needs to be repaired and then I get this message -> 
"Invalid File format Please contact the package developer"

Thanks! </div>

**Comment by BKSteve** [comment]
#7411

**Comment by BKSteve** [comment]
DSM7 pre-release package.
[https://github.com/SickChill/SickChill/discussions/7403#discussioncomment-1311731](https://github.com/SickChill/SickChill/discussions/7403#discussioncomment-1311731)
