### ISSUE TITLE
Synology vDSM 6.2.4.25556 - Fresh Install Works; Then when updating it fails to restart

### ISSUE THREAD

**Issue by WaffleTortoiseCat** [SickChill/SickChill#7432]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 
OS: Synology Virtual DSM 6.2.4.25556
Browser: Brave
What you did: Installed SickChill and Updated via the web interface
What happened: it broke. This is a fresh install of vDSM and SickChill. I installed the package from SynoCommunity and it ran fine. It reported 800+ commits and said I should update. I clicked; it updated; and promptly stopped working. I do not have technical prowess to delve beyond the GUI on the Synology to provide any error output.
What you expected: for it to update and restart. It in fact does not.
Logs:
I'm investigating how to find logging resources on my Synology to assist with information at this time.  I can recreate it by uninstalling and reinstalling from synocommunity but the ensuing update repeats and breaks. 
PASTE LOGS HERE
As above.

**Comment by WaffleTortoiseCat** [comment]
Addendum: I did read the Wiki as well as the Install instructions from another Git repository. No changes were able to change the behaviour.

**Comment by BKSteve** [comment]
#7364
