### ISSUE TITLE
pip miss last version

### ISSUE THREAD

**Issue by digrouz** [SickChill/SickChill#7439]
Hello,

I'm using pip to generate my docker container, but it seems that last version there is: 2021.07.23-1 (https://pypi.org/project/sickchill/#history) and not 2021.07.29 as stated here, any idea why ?

Kind Regards

**Comment by digrouz** [comment]
In the meanwhile, I found how to use github as provider for pip:

    pip3 --no-cache-dir install --upgrade git+https://github.com/SickChill/SickChill.git@${SICKCHILL_VERSION} 

Still it would be convenient to just sync releases at pypi.org :)

**Comment by miigotu** [comment]
The last version just hasn't been published to pypi, there are a lot of issues still.

**Comment by digrouz** [comment]
oh ok that's why. Would you recommend to stay on previous one ?

**Comment by miigotu** [comment]
Both of them have issues right now, I don't get much help and I'm irritated with the issues right now so changes are slow atm. Good luck with either of them honestly.

**Comment by digrouz** [comment]
:( any way I can help ?
