### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Crunchyroll. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by Zetsuo** [SickChill/SickChill#7445]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-5.10.52-v7+-armv7l-with-debian-10.10**
Locale: UTF-8
Branch: **pip**
Commit: SickChill/SickChill@1ab5cd772328140c49813ca683de00f5bfa2997f
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Crunchyroll. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Zetsuo** [comment]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-5.10.60-v7+-armv7l-with-debian-10.10**
Locale: UTF-8
Branch: **pip**
Commit: SickChill/SickChill@1ab5cd772328140c49813ca683de00f5bfa2997f
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Crunchyroll. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ceesvanegmond** [comment]
Same error over here.

**Comment by ceesvanegmond** [comment]
@miigotu Why cloing this issue? Not relevant anymore?

**Comment by n2burns** [comment]
> @miigotu Why cloing this issue? Not relevant anymore?

@ceesvanegmond See [this issue](https://github.com/SickChill/SickChill/issues/7231) for an explanation.

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Crunchyroll. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
