### ISSUE TITLE
Fresh installed on TrueNAS 12.0 U4 doesn't start (work around included)

### ISSUE THREAD

**Issue by Dobbs84** [SickChill/SickChill#7452]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / `a8e5d00f02e5d27719409bb9d7d733042b294b82`
OS: TrueNAS 12.0 U4
Browser: Chrome
What you did: Fresh install on TrueNAS with the following command to ensure I pulled the latest (same issue if I installed through GUI)
`iocage fetch -P sickchill -g https://github.com/ix-plugin-hub/iocage-plugin-index --branch 'master' ip4_addr="vnet0|192.168.2.4/24"`
What happened: SC (sickchill) does not load on startup or by running `service sickchill start`
What you expected: SC to run 
Work around: I was able to get SC to run by manually running `SickChill.py` with `nohup /usr/local/app/sickchill/SickChill.py &`

Notes: The install completed with no issues. When trying to start SC with the service command, it just hangs, but if I go check that PID, it's not running.
```
root@SickChill:/ # service sickchill start
Removing stale pidfile.
Starting sickchill.
root@SickChill:/ # Writing PID: 60613 to /var/run/sickchill/sickchill.pid


```

**Comment by Dobbs84** [comment]
@miigotu I thought you would be all over this asking questions. I'm here to provide any output or results you ask for

**Comment by miigotu** [comment]
Likely because this is a duplicate, and you should search before opening an issue.

**Comment by Dobbs84** [comment]
What's the ticket number?

**Comment by miigotu** [comment]
#7348
#7252
#7249
Many more.

**Comment by Dobbs84** [comment]
So pulling directly from CLI is not grabbing the latest build?

**Comment by miigotu** [comment]
No. But don't make duplicate issues and split the conversation into separate places. You aren't making the situation better by doing that. Use the other issues.
