### ISSUE TITLE
Preview Rename -> Select all season button doesn't work

### ISSUE THREAD

**Issue by benyjr** [SickChill/SickChill#7456]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master / a8e5d00f02e5d27719409bb9d7d733042b294b82
OS: Linux-5.4.0-80-generic-x86_64-with-glibc2.29
Browser: Chrome
What you did: In Preview Rename I checked the select all for a specific season.
What happened: Nothing.  None of the episodes for renaming in the specific season were selected for remaining.
What you expected: I expected that the episodes that were eligible for renaming in that season should all be selected.

Checking All Seasons select all works as expect.

Please see the attached photographs.

![Screenshot_20210815-223827](https://user-images.githubusercontent.com/14084052/130492763-eb2267e3-d5ee-4e5d-955e-7457cc64f31a.png)
![Screenshot_20210815-223850](https://user-images.githubusercontent.com/14084052/130492774-f48b68f0-5364-43de-9e37-7d00e6f42afb.png)
![Screenshot_20210815-223905](https://user-images.githubusercontent.com/14084052/130492776-8a903bb5-e3a7-4e79-804a-10acbb7430fb.png)

**Comment by miigotu** [comment]
#7305
