### ISSUE TITLE
Trying to add Star Trek Science vs. Fiction

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#7476]
### Before submitting your issue:
When I try to add **Star Trek Science vs. Fiction**  it adds the folder with nothing in it and this is the only message I can find;

2021-08-30 14:52:19 Show in O:\series temp\Star Trek Science vs. Fiction has no name on theTVDB, probably searched with the wrong language. Delete .nfo and add manually in the correct language.

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
  SickChill Info:
Install: pip
Version: v2021.07.23-1
Database Version: 44.5
  Python Version:3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
  SSL Version:OpenSSL 1.1.1k 25 Mar 2021
  OS:Windows-7-6.1.7601-SP1
  Locale:en_US.cp1252

What you did:  add **Star Trek Science vs. Fiction**
What happened: doesn't add the show but does create the folder with nothing in it.
What you expected:  for it to add the show.
Logs:
```
2021-08-30 14:52:19 Show in O:\series temp\Star Trek Science vs. Fiction has no name on theTVDB, probably searched with the wrong language. Delete .nfo and add manually in the correct language.
```

**Comment by BKSteve** [comment]
Seems the search functionality is unable to find shows with a colon in their name without the colon being in the string searched for.
```
9-1-1: Lone Star
Star Trek: Piccard
Star Wars: The Clone Wars
Star Wars: Visions 
```
Exhibit the same issue of not being found in the search.

Full log of adding same show.
```
2021-08-31 14:01:59 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with search term(s): ['Star Trek: Science vs. Fiction'] on Indexer: theTVDB (exact: 0)
2021-08-31 14:02:00 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Filtering and sorting out excess results because exact match was checked
2021-08-31 14:02:19 INFO :: SHOWQUEUE-ADD :: Starting to add show by ShowDir: /volume1/Media/Series/A-D/Star Trek Science vs. Fiction
2021-08-31 14:02:19 WARNING :: SHOWQUEUE-ADD :: Show in /volume1/Media/Series/A-D/Star Trek Science vs. Fiction has no name on theTVDB, probably searched with the wrong language. Delete .nfo and add manually in the correct language.
```

**Comment by nydave69** [comment]
Any update as to when this will be fixed..   

would like to get the shows added..  

Any work around????

**Comment by BKSteve** [comment]
More details on shows throwing the NFO error please.

I'm not seeing these errors in develop so want to double check so we can try to resolve these issues. I'm a little freer whilst SynoCommunity are fixing Python38 issues.
Are you updated to 20210729 or still on 20210723-1 ?

**Comment by nydave69** [comment]
I tried the manual upgrade;   it reported that pip needed to be updated, I did that
but;

`Requirement already satisfied: wrapt<2,>=1.10 in c:\sickchill\python3\tools\lib\site-packages (from deprecated->PyGithub<2.0.0,>=1.54.1->sickchill) (1
.13.2)
Requirement already satisfied: oauthlib>=3.0.0 in c:\sickchill\python3\tools\lib\site-packages (from requests-oauthlib->python-twitter<4.0,>=3.5->sickchill) (3.1.1)
WARNING: You are using pip version 21.1.1; however, version 21.3 is available.
You should consider upgrading via the 'C:\SickChill\Python3\tools\python.exe -m pip install --upgrade pip' command.

C:\SickChill>C:\SickChill\Python3\tools\python -m pip install --upgrade pip
Requirement already satisfied: pip in c:\sickchill\python3\tools\lib\site-packages (21.1.1)
Collecting pip
  Downloading pip-21.3-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 3.3 MB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.1
    Uninstalling pip-21.1.1:
      Successfully uninstalled pip-21.1.1
  WARNING: The scripts pip.exe, pip3.8.exe and pip3.exe are installed in 'C:\SickChill\Python3\tools\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-21.3

C:\SickChill>C:\SickChill\Python3\tools\python -m pip install -U sickchill
Requirement already satisfied: sickchill in c:\sickchill\python3\tools\lib\site-packages (2021.7.23-1)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.3 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (4.10.0)
Requirement already satisfied: bencode.py<5.0.0,>=4.0.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (4.0.0)
Requirement already satisfied: packaging<21.0,>=20.9 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (20.9)
Requirement already satisfied: jsonrpclib-pelix<0.5.0,>=0.4.2 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.4.3.1)
Requirement already satisfied: Send2Trash<2.0.0,>=1.5.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.8.0)
Requirement already satisfied: Mako<2.0.0,>=1.1.4 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.1.5)
Requirement already satisfied: CacheControl<0.13.0,>=0.12.6 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.12.6)
Requirement already satisfied: PySocks<2.0.0,>=1.7.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.7.1)
Requirement already satisfied: timeago<2.0.0,>=1.0.15 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0.15)
Requirement already satisfied: new-rtorrent-python<2.0.0,>=1.0.1-alpha.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0.1a0)
Requirement already satisfied: babelfish>=0.6.0b1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.6.0)
Requirement already satisfied: pymediainfo<6.0.0,>=5.0.3 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (5.1.0)
Requirement already satisfied: python-slugify<6.0.0,>=4.0.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (5.0.2)
Requirement already satisfied: PyGithub<2.0.0,>=1.54.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.55)
Requirement already satisfied: httplib2<0.20.0,>=0.19.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.19.1)
Requirement already satisfied: markdown2<3.0.0,>=2.4.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.4.1)
Requirement already satisfied: profilehooks<2.0.0,>=1.12.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.12.0)
Requirement already satisfied: deluge-client<2.0.0,>=1.9.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.9.0)
Requirement already satisfied: feedparser<7.0.0,>=6.0.2 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (6.0.8)
Requirement already satisfied: chardet<5.0.0,>=4.0.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (4.0.0)
Requirement already satisfied: kodipydent-alt<2022.0.0,>=2021.7.16 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2021.7.16)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.8.2)
Requirement already satisfied: SQLAlchemy<2.0.0,>=1.4.3 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.4.25)
Requirement already satisfied: PyNMA<2.0,>=1.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0)
Requirement already satisfied: ipaddress<2.0.0,>=1.0.23 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0.23)
Requirement already satisfied: pyOpenSSL<21.0.0,>=20.0.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (20.0.1)
Requirement already satisfied: Unidecode<2.0.0,>=1.2.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.3.2)
Requirement already satisfied: imagesize<2.0.0,>=1.2.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.2.0)
Requirement already satisfied: qbittorrent-api<2022.0.0,>=2021.3.18 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2021.8.23)
Requirement already satisfied: enzyme<0.5.0,>=0.4.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.4.1)
Requirement already satisfied: IMDbPY>=2020.09.25 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2021.4.18)
Requirement already satisfied: win-inet-pton<2.0.0,>=1.1.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.1.0)
Requirement already satisfied: requests<3.0.0,>=2.25.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.26.0)
Requirement already satisfied: tvdbsimple<2.0.0,>=1.0.6 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0.6)
Requirement already satisfied: tornado<7.0,>=6.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (6.1)
Requirement already satisfied: validators<0.19.0,>=0.18.2 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.18.2)
Requirement already satisfied: python3-fanart<3.0.0,>=2.0.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.0.0)
Requirement already satisfied: beekeeper-alt<2022.0.0,>=2021.7.16 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2021.7.16)
Requirement already satisfied: subliminal<3.0.0,>=2.1.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.1.0)
Requirement already satisfied: gntp<2.0.0,>=1.0.3 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0.3)
Requirement already satisfied: putio.py<9.0.0,>=8.7.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (8.7.0)
Requirement already satisfied: rarfile<5.0,>=4.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (4.0)
Requirement already satisfied: pyaes<2.0.0,>=1.6.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.6.1)
Requirement already satisfied: python-twitter<4.0,>=3.5 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (3.5)
Requirement already satisfied: guessit<4.0.0,>=3.3.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (3.3.1)
Requirement already satisfied: tmdbsimple<3.0.0,>=2.8.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.8.0)
Requirement already satisfied: cloudscraper<2.0.0,>=1.2.56 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.2.58)
Requirement already satisfied: Js2Py<0.72,>=0.70 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.71)
Requirement already satisfied: ifaddr<0.2.0,>=0.1.7 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.1.7)
Requirement already satisfied: configobj<6.0.0,>=5.0.6 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (5.0.6)
Requirement already satisfied: html5lib<2.0,>=1.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.1)
Requirement already satisfied: tus.py<2.0.0,>=1.3.4 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.3.4)
Requirement already satisfied: soupsieve>1.2 in c:\sickchill\python3\tools\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.3->sickchill) (2.2.1)
Requirement already satisfied: xmltodict>=0.9.2 in c:\sickchill\python3\tools\lib\site-packages (from beekeeper-alt<2022.0.0,>=2021.7.16->sickchill) (
0.12.0)
Requirement already satisfied: msgpack>=0.5.2 in c:\sickchill\python3\tools\lib\site-packages (from CacheControl<0.13.0,>=0.12.6->sickchill) (1.0.2)
Requirement already satisfied: requests-toolbelt>=0.9.1 in c:\sickchill\python3\tools\lib\site-packages (from cloudscraper<2.0.0,>=1.2.56->sickchill)
(0.9.1)
Requirement already satisfied: pyparsing>=2.4.7 in c:\sickchill\python3\tools\lib\site-packages (from cloudscraper<2.0.0,>=1.2.56->sickchill) (2.4.7)
Requirement already satisfied: six in c:\sickchill\python3\tools\lib\site-packages (from configobj<6.0.0,>=5.0.6->sickchill) (1.16.0)
Requirement already satisfied: sgmllib3k in c:\sickchill\python3\tools\lib\site-packages (from feedparser<7.0.0,>=6.0.2->sickchill) (1.0.0)
Requirement already satisfied: rebulk>=3 in c:\sickchill\python3\tools\lib\site-packages (from guessit<4.0.0,>=3.3.1->sickchill) (3.0.1)
Requirement already satisfied: webencodings in c:\sickchill\python3\tools\lib\site-packages (from html5lib<2.0,>=1.1->sickchill) (0.5.1)
Requirement already satisfied: lxml in c:\sickchill\python3\tools\lib\site-packages (from IMDbPY>=2020.09.25->sickchill) (4.6.3)
Requirement already satisfied: pyjsparser>=2.5.1 in c:\sickchill\python3\tools\lib\site-packages (from Js2Py<0.72,>=0.70->sickchill) (2.7.1)
Requirement already satisfied: tzlocal>=1.2 in c:\sickchill\python3\tools\lib\site-packages (from Js2Py<0.72,>=0.70->sickchill) (3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\sickchill\python3\tools\lib\site-packages (from Mako<2.0.0,>=1.1.4->sickchill) (2.0.1)
Requirement already satisfied: pynacl>=1.4.0 in c:\sickchill\python3\tools\lib\site-packages (from PyGithub<2.0.0,>=1.54.1->sickchill) (1.4.0)
Requirement already satisfied: pyjwt>=2.0 in c:\sickchill\python3\tools\lib\site-packages (from PyGithub<2.0.0,>=1.54.1->sickchill) (2.2.0)
Requirement already satisfied: deprecated in c:\sickchill\python3\tools\lib\site-packages (from PyGithub<2.0.0,>=1.54.1->sickchill) (1.2.13)
Requirement already satisfied: cryptography>=3.2 in c:\sickchill\python3\tools\lib\site-packages (from pyOpenSSL<21.0.0,>=20.0.1->sickchill) (35.0.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\sickchill\python3\tools\lib\site-packages (from python-slugify<6.0.0,>=4.0.1->sickchill) (1.3
)
Requirement already satisfied: future in c:\sickchill\python3\tools\lib\site-packages (from python-twitter<4.0,>=3.5->sickchill) (0.18.2)
Requirement already satisfied: requests-oauthlib in c:\sickchill\python3\tools\lib\site-packages (from python-twitter<4.0,>=3.5->sickchill) (1.3.0)
Requirement already satisfied: urllib3>=1.24.2 in c:\sickchill\python3\tools\lib\site-packages (from qbittorrent-api<2022.0.0,>=2021.3.18->sickchill)
(1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\sickchill\python3\tools\lib\site-packages (from requests<3.0.0,>=2.25.1->sickchill) (2.
0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\sickchill\python3\tools\lib\site-packages (from requests<3.0.0,>=2.25.1->sickchill) (2021.10.8
)
Requirement already satisfied: idna<4,>=2.5 in c:\sickchill\python3\tools\lib\site-packages (from requests<3.0.0,>=2.25.1->sickchill) (3.3)
Requirement already satisfied: greenlet!=0.4.17 in c:\sickchill\python3\tools\lib\site-packages (from SQLAlchemy<2.0.0,>=1.4.3->sickchill) (1.1.2)
Requirement already satisfied: stevedore>=1.20.0 in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (3.4.0)
Requirement already satisfied: pytz>=2012c in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (2021.3)
Requirement already satisfied: click>=4.0 in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (8.0.3)
Requirement already satisfied: dogpile.cache>=0.6.0 in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (1.1.4)

Requirement already satisfied: pysrt>=1.0.1 in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (1.1.2)
Requirement already satisfied: appdirs>=1.3 in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (1.4.4)
Requirement already satisfied: decorator>=3.4.0 in c:\sickchill\python3\tools\lib\site-packages (from validators<0.19.0,>=0.18.2->sickchill) (5.1.0)
Requirement already satisfied: colorama in c:\sickchill\python3\tools\lib\site-packages (from click>=4.0->subliminal<3.0.0,>=2.1.0->sickchill) (0.4.4)

Requirement already satisfied: cffi>=1.12 in c:\sickchill\python3\tools\lib\site-packages (from cryptography>=3.2->pyOpenSSL<21.0.0,>=20.0.1->sickchil
l) (1.15.0)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in c:\sickchill\python3\tools\lib\site-packages (from stevedore>=1.20.0->subliminal<3.0.0,>=2.1.0->s
ickchill) (5.6.0)
Requirement already satisfied: tzdata in c:\sickchill\python3\tools\lib\site-packages (from tzlocal>=1.2->Js2Py<0.72,>=0.70->sickchill) (2021.2.post0)

Requirement already satisfied: backports.zoneinfo in c:\sickchill\python3\tools\lib\site-packages (from tzlocal>=1.2->Js2Py<0.72,>=0.70->sickchill) (0
.2.1)
Requirement already satisfied: wrapt<2,>=1.10 in c:\sickchill\python3\tools\lib\site-packages (from deprecated->PyGithub<2.0.0,>=1.54.1->sickchill) (1
.13.2)
Requirement already satisfied: oauthlib>=3.0.0 in c:\sickchill\python3\tools\lib\site-packages (from requests-oauthlib->python-twitter<4.0,>=3.5->sick
chill) (3.1.1)
Requirement already satisfied: pycparser in c:\sickchill\python3\tools\lib\site-packages (from cffi>=1.12->cryptography>=3.2->pyOpenSSL<21.0.0,>=20.0.
1->sickchill) (2.20)

C:\SickChill>
`
So nothing has changed..   any other advice?

**Comment by BKSteve** [comment]
The issue here seems to be Language, by selecting the shows language of the .nfo as in theTVDB

![image](https://user-images.githubusercontent.com/10173496/139523786-7aa2fc7a-ae5a-4068-8b4f-d136a3ed97fe.png)

The show added no issue with `Deutsch` selected.

For clarity testing was done using current develop

**Comment by nydave69** [comment]
> The issue here seems to be Language, by selecting the shows language of the .nfo as in theTVDB
> 
> ![image](https://user-images.githubusercontent.com/10173496/139523786-7aa2fc7a-ae5a-4068-8b4f-d136a3ed97fe.png)
> 
> The show added no issue with `Deutsch` selected.
> 
> For clarity testing was done using current develop

It's not just this one Show

It's most of the Star Trek shows and any others that have a special character in the title,
It all so affects episode titles...

**Comment by nydave69** [comment]
> Try setting the global environment variable PYTHONIOENCODING=UTF-8 and reboot

I am not a programmer,  how where do I set this variable?

**Comment by BKSteve** [comment]
Before marking this as closed I double checked all of these.
```
9-1-1: Lone Star
Star Trek: Piccard
Star Wars: The Clone Wars
Star Wars: Visions 
```
Plus `Star Trek: Science vs. Fiction` using German, all loaded without issue using the current develop branch.
![image](https://user-images.githubusercontent.com/10173496/139683304-5a78d1ef-b96a-42bd-ba26-810ca83e3e5e.png)

Here's the log for adding `Star Wars: Visions`
```
2021-11-01 21:02:23 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with search term(s): ['Star Wars: Visions'] on Indexer: theTVDB (exact: 0)
2021-11-01 21:02:30 INFO :: WEBSERVER-ADDSHOWS_0 :: addNewShow module theTVDB|1|https://thetvdb.com/?tab=series&amp;id=|393190|Star Wars: Visions|2021-09-22|false, dir /volume1/RStation1/DumpZone path None
2021-11-01 21:02:35 INFO :: SHOWQUEUE-ADD :: Starting to add show by ShowDir: /volume1/RStation1/DumpZone/Star Wars Visions
2021-11-01 21:02:35 DEBUG :: SHOWQUEUE-ADD :: 393190: Loading show info from theTVDB
2021-11-01 21:02:36 DEBUG :: SHOWQUEUE-ADD :: Setter sets location to /volume1/RStation1/DumpZone/Star Wars Visions
2021-11-01 21:02:36 INFO :: SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2021-11-01 21:02:36 DEBUG :: SHOWQUEUE-ADD :: 393190: Loading show info from IMDb
2021-11-01 21:02:39 DEBUG :: SHOWQUEUE-ADD :: 393190: Obtained info from IMDb ->{'indexer_id': 393190, 'imdb_id': '13622982', 'title': 'Star Wars: Visions', 'year': 2021, 'akas': 'Звёздные войны: Видения (Russia)|Зоряні війни: Видіння (Ukraine)', 'runtimes': '14', 'genres': 'Animation|Action|Adventure|Fantasy|Sci-Fi', 'countries': 'Japan|United States', 'country_codes': 'jp|us', 'certificates': 'Argentina:Atp|Australia:PG::(self-applied)|Brazil:Livre::(self-applied)|Canada:TV-PG::(self-applied)|France:9+::(self-applied)|Germany:12::(self-applied)|India:UA 7+::(self-applied)|Indonesia:PG::(self-applied)|Italy:T::(self-applied)|Japan:G::(self-applied)|Mexico:9+|Netherlands:6::(self-applied)|Poland:7|Singapore:PG|Spain:9+|Sweden:9::(self-applied)|United Kingdom:9+|United States:TV-PG', 'rating': '7.2', 'votes': '10298', 'last_update': 738095}
2021-11-01 21:02:39 DEBUG :: SHOWQUEUE-ADD :: 393190: Saving to database: Star Wars: Visions
2021-11-01 21:02:39 DEBUG :: SHOWQUEUE-ADD :: 393190: Loading all episodes from theTVDB...
...
2021-11-01 21:02:43 DEBUG :: SHOWQUEUE-ADD :: Building internal name cache for Star Wars: Visions
2021-11-01 21:02:43 DEBUG :: SHOWQUEUE-ADD :: get_all_scene_exceptions: {-1: [{'show_name': 'star wars visions', 'custom': False}]}
2021-11-01 21:02:43 DEBUG :: SHOWQUEUE-ADD :: exceptions_cache for 393190: {-1: ['star wars visions']}
2021-11-01 21:02:43 DEBUG :: SHOWQUEUE-ADD :: Internal name cache for Star Wars: Visions set to: [ star wars visions ]
2021-11-01 21:02:43 DEBUG :: SHOWQUEUE-ADD :: 393190: Loading all episodes from the show directory /volume1/RStation1/DumpZone/Star Wars Visions
2021-11-01 21:02:43 DEBUG :: SHOWQUEUE-ADD :: 393190: Writing NFOs for show
2021-11-01 21:02:43 DEBUG :: SHOWQUEUE-ADD :: Checking if /volume1/RStation1/DumpZone/Star Wars Visions/tvshow.nfo exists: False
2021-11-01 21:02:43 DEBUG :: SHOWQUEUE-ADD :: Metadata provider KODI creating show metadata for Star Wars: Visions
```

Branch: develop
Commit: a39a6298db7c2977c8f962bced95445bf257b48a
Database Version: 44.2

My device is a Linux based NAS, so don't know how to assist with PYTHONIOENCODING
