### ISSUE TITLE
Upgraded Synology Sickchill official package and can't run it now

### ISSUE THREAD

**Issue by jonaspaulo** [SickChill/SickChill#7503]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Latest
OS: Synology DSM6
Browser: Chrome
What you did: Upgrade the official Synology package to the latest version (20210729-2) (which also seemed to install python 3.8)
What happened: Package stopped and if I click "Run" after a while it stops again
What you expected: Package run sucessfully 
Logs:
/volume1/@appstore/sickchill/var/sickhill.log

Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data
Writing PID: 9180 to /volume1/@appstore/sickchill/var/sickchill.pid

Thanks

**Comment by jonaspaulo** [comment]
Btw the issue is the same as mentioned on : https://github.com/SickChill/SickChill/discussions/7364
But i have followed the work around with no success:

Add 2021.09.10

For those updating to the 20210729-2 SynoCommunity package it has a little bug and here's the work around:

install this 20210729-2 version and uncheck the run after installation box.
Once installed.
ssh to DSM
cd /volume1/@appstore/sickchill/share/SickChill/sickchill/ (assuming volume1)
sudo curl -O https://raw.githubusercontent.com/SickChill/SickChill/develop/sickchill/init_helpers.py
or
5. rm init_helpers.py
6. wget https://raw.githubusercontent.com/SickChill/SickChill/develop/sickchill/init_helpers.py
7. chown sc-sickchill:sickchill init_helpers.py
start SC from package center
wait for SC to load everything and start 5+++ minutes

**Comment by 4MOTION1977** [comment]
> Btw the issue is the same as mentioned on : #7364
> But i have followed the work around with no success:
> 
> Add 2021.09.10
> 
> For those updating to the 20210729-2 SynoCommunity package it has a little bug and here's the work around:
> 
> install this 20210729-2 version and uncheck the run after installation box.
> Once installed.
> ssh to DSM
> cd /volume1/@appstore/sickchill/share/SickChill/sickchill/ (assuming volume1)
> sudo curl -O https://raw.githubusercontent.com/SickChill/SickChill/develop/sickchill/init_helpers.py
> or
> 5. rm init_helpers.py
> 6. wget https://raw.githubusercontent.com/SickChill/SickChill/develop/sickchill/init_helpers.py
> 7. chown sc-sickchill:sickchill init_helpers.py
> start SC from package center
> wait for SC to load everything and start 5+++ minutes

Worked like a charm for me.

Thnx

**Comment by jonaspaulo** [comment]
Hi, After a few more "start" tries it worked ty
