### ISSUE TITLE
[APP SUBMITTED]: ('Connection aborted.', OSError(22, 'Invalid argument'))

### ISSUE THREAD

**Issue by turkeylegs1** [SickChill/SickChill#7521]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-4.4.180+-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', OSError(22, 'Invalid argument'))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by turkeylegs1** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-4.4.180+-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', OSError(22, 'Invalid argument'))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by turkeylegs1** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-4.4.180+-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', OSError(22, 'Invalid argument'))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by turkeylegs1** [comment]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-4.4.180+-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', OSError(22, 'Invalid argument'))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by aktur** [comment]
### INFO
Python Version: **3.9.15 (main, Nov 10 2022, 13:00:13) [GCC 10.3.1 20211027]**
Operating System: **Linux-3.10.105-x86_64-with**
Locale: None
Version: **2022.10.13**
Link to Log: https://gist.github.com/1da2949a506c0241c170cb89d5c85790
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', OSError(22, 'Invalid argument'))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
