### ISSUE TITLE
Feature Request: for Preferred Quality, could there be options like SDR, HDR, DV, etc. for 4K releases?

### ISSUE THREAD

**Issue by bouwew** [SickChill/SickChill#7525]
Now that 4K/2160p becomes more and more common, I have a need for more filtering: on encoding.

Some releases are available in various encoding formats.

**Comment by quickdry** [comment]
A way to give an order of preferences would be great. I'm not so worried about getting 4k - but if a 720p h265 is same size or smaller than the corresponding h264 then I'd want that. Even just a way to prefer 265 over 264 if available.

**Comment by miigotu** [comment]
You can add things like `x265` to `preferred words` and they will take precedence over x264
