### ISSUE TITLE
[APP SUBMITTED]: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

### ISSUE THREAD

**Issue by snapperhead** [SickChill/SickChill#7607]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
Link to Log: https://gist.github.com/0c1f48af300e7d84e3e71299eb62163d
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by st3rv1s** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.11.10
Link to Log: https://gist.github.com/7c4a9a4701e6172a410827f71284b4b6
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by POgli** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19044-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.11.7
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by st3rv1s** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.11.10
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by st3rv1s** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.11.10
Link to Log: https://gist.github.com/3298fea625fa751902011123f3a07e61
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.11.10
Link to Log: https://gist.github.com/b46e89186379eb604a506add575fd737
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by st3rv1s** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.2.20
Link to Log: https://gist.github.com/3b81f544336a35def195a584d31c4c7f
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
