### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Sky Max. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by tiny1mil** [SickChill/SickChill#7615]
### INFO
Python Version: **3.9.7 (default, Sep 24 2021, 09:43:00) [GCC 10.3.0]**
Operating System: **Linux-5.10.0-8-amd64-x86_64-with-glibc2.32**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@46455f17ef5e14a3b2581a522081cf1c33f4a0d8
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Sky Max. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
#7231

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.7.23.post1
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Sky Max. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cdjazman** [comment]
### INFO
Python Version: **3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19041-SP0**
Locale: cp1252
Branch: ****
Commit: SickChill/SickChill@c6ee7aa889661dde40ea2240ecb5d88da776e039
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Sky Max. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
