### ISSUE TITLE
Missing time zone for network

### ISSUE THREAD

**Issue by gits68** [SickChill/SickChill#7627]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: v2021.07.14-3
OS: Docker image
Browser: FF 94.0.1 
What you did:
What happened: /errorlogs/ messages
What you expected:
Logs:
```
Missing time zone for network: **КиноПоиск HD.** Check valid network is set in indexer (theTVDB) before filing issue.
```

list of other broken networks :
> History (CA)
> Polynésie La 1re
> Sony Crackle
> SVT1
> KBS TV2
> Play4
> Sky1
> NRK
> קשת 12
> BYU Television
> Channel 5 (UK)
> Showcase (CA)
> Spike
> 13 רשת
> Первый канал
> City
> ITV1
> CBC (CA)
> TV4 (SE)
> Amazon
> HBO Europe

see [TheTVDB ticket](https://support.thetvdb.com/tickets.php?id=8914) for details
it seems [network_timezones.txt](https://sickchill.github.io/sb_network_timezones/network_timezones.txt) isn't upto date.

Regards

**Comment by miigotu** [comment]
We include every network tvdb exposes on their "companies" pages. All of the missing networks are because they use aliases which are not listed anywhere other than a show's page, so we have no way to pre-scrape them programmatically. They should either use the actual network name and I'd on the show page, expose it over the public (free) api, or provide a public web page listing the aliases and their linked network.

https://github.com/SickChill/SickChill/issues/7231

**Comment by gits68** [comment]
well, in fact, it seems the missing networks have been renamed, will see w/ TheTVDB...

КиноПоиск HD:Europe/Moscow (aka KinoPoisk)
History (CA):America/St_Johns (aka History Canada)
Polynésie La 1re:Pacific/Tahiti (aka Polynésie 1ère)
SVT1:Europe/Stockholm (aka SVT 1)
KBS TV2:Asia/Seoul (aka KBS 2)
Play4:Europe/Brussels (aka Play More?)
Sky1:Europe/Brussels (there is no Sky* in belgium in network_timezones.txt)
NRK:Europe/Oslo (aka NRK1?)
קשת 12:Israel (aka Keshet 12)
BYU Television:America/Denver (aka BYUtv)
Channel 5 (UK):US/London (aka Channel 5)
Showcase (CA):America/St_Johns (aka Showcase?)
Spike:America/New_York (aka Spike TV)
13 רשת::Israel (aka Keshet? there is no Keshet 13 in network_timezones.txt)
Первый канал:Europe/Kaliningrad (aka Channel One)
City:America/St_Johns (aka CityTV)
ITV1:US/London (aka ITV? there is no ITV*1 in network_timezones.txt)
CBC (CA):America/St_Johns (aka CBC)
TV4 (SE):Europe/Stockholm (aka TV4)
Amazon:America/Los_Angeles (the is no Amazon* in network_timezones.txt)
HBO Europe:Europe/Stockholm (aka HBO Nordic? or HBO España?)

**Comment by gits68** [comment]
forget about searching for existing ticket, sorry.
[TheTVDB ticket](https://support.thetvdb.com/tickets.php?id=8914) updated

**Comment by gits68** [comment]
Hi, answer from TheTVDB team
![image](https://user-images.githubusercontent.com/7086920/141605515-81d15f31-68d5-4f5f-889c-906b438fb1bf.png)
