### ISSUE TITLE
last update to sick chill v20210729-3 on Synology wont let it start again

### ISSUE THREAD

**Issue by liam8888999** [SickChill/SickChill#7628]
as the title says

**Comment by 4MOTION1977** [comment]
Same issue after the update.

DSM version:  6.2.3-25426 Update3
Python version: 3.8.6-0154

No errors in de sickchill log files.

When you start the package, it runs for about 15 seconds and then stops.
You cant acces sickchill in that time.

**Comment by liam8888999** [comment]
just change callable back to reference on line 40 of pyproject.toml located at /volume1/@appstore/sickchill/share/SickChill. you will need to use vim to edit

**Comment by BKSteve** [comment]
This issue is not a Synology only issue. Pull #7630 and same as #7629. 

So closing this one as the 7629 has more relevant name.

**Comment by 4MOTION1977** [comment]
Changing the code in pyproject.toml
from:
`[tool.poetry.scripts]
SickChill = {reference = "SickChill.py", type = "file"}`
to:
`[tool.poetry.scripts]
SickChill = {callable = "SickChill.py", type = "file", extras = ["cli"]}`

Gives me a runtime error.

**Comment by BKSteve** [comment]
This [https://github.com/SickChill/SickChill/pull/7630/commits/93671f60da6cb7e9ee2f46c332aca3546eadf9ea](https://github.com/SickChill/SickChill/pull/7630/commits/93671f60da6cb7e9ee2f46c332aca3546eadf9ea)
is to change back the 3 hours ago one.
[https://github.com/SickChill/SickChill/commit/3b6aa227204d107ce78ef46f96cdde940e69984d](https://github.com/SickChill/SickChill/commit/3b6aa227204d107ce78ef46f96cdde940e69984d)
