### ISSUE TITLE
RuntimeError after update

### ISSUE THREAD

**Issue by alexsalex** [SickChill/SickChill#7629]
```
WARNING: Ignoring invalid distribution -br (/opt/SickChillServer/.venv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -br (/opt/SickChillServer/.venv/lib/python3.8/site-packages)

poetry installed: True

  RuntimeError

  The Poetry configuration is invalid:
    - [scripts.SickChill] {'callable': 'SickChill.py', 'type': 'file', 'extras': ['cli']} is not valid under any of the given schemas


  at .venv/lib/python3.8/site-packages/poetry/core/factory.py:45 in create_poetry
       41│             message = ""
       42│             for error in check_result["errors"]:
       43│                 message += "  - {}\n".format(error)
       44│
    →  45│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       46│
       47│         # Load package
       48│         name = local_config["name"]
       49│         version = local_config["version"]
Unable to install to the existing virtual environment located at /opt/SickChillServer/.venv
Please check the permissions, and that it does not include global site packages
```

**Comment by thargan81** [comment]
I've just had the same under Debian 10. Managed to fix it by uninstalling poetry and letting the startup process install it again. This did result in a version change to poetry, removing version 1.2.0a2 and then installing 1.1.11

`tanelorn:~/Apps/SickChill$ SickChill/.venv/bin/python3.7 -m pip uninstall poetry`

Sickchill then started using my standard unit file.

**Comment by BKSteve** [comment]
See #7630

**Comment by BKSteve** [comment]
if editing isn't your thing.
cd to the `../sickchill/share/SickChill/` folder where pyproject.toml is

In my case on my SynoDSM
`cd /volume1/@appstore/sickchill/share/SickChill/`

Then you can curl the edit version from #7630 
`sudo curl -O https://raw.githubusercontent.com/SickChill/SickChill/93671f60da6cb7e9ee2f46c332aca3546eadf9ea/pyproject.toml`

**Comment by fonzy69** [comment]
for me too the windows service stay paused after update.
tried to uninstall / reinstall with last windows installer without success
i don't find the pyproject.toml file in windows, 
Nothing appear in sickchill\data\logs\sickchill.log
What can i do for help?

**Comment by JustSomeGuyNZ** [comment]
> for me too the windows service stay paused after update. tried to uninstall / reinstall with last windows installer without success i don't find the pyproject.toml file in windows, Nothing appear in sickchill\data\logs\sickchill.log What can i do for help?

If you open a command window and run sickchill "direct" it seems to work (you need to leave the window open thou)

Something like this:
C:\pathtopython\python.exe "C:\pathtosickchill\SickChill\SickChill.py" --nolaunch --port=8081 --datadir="C:\pathtosickchill\Data"

**Comment by Djskynet9** [comment]
Any idea how to fix this when running SC in a docker

**Comment by miigotu** [comment]
The fix cannot be to revert the fix. poetry 1.2.0a2 is scrapped, and is superceded by poetry 1.1.10 (and some others)

**Comment by alexsalex** [comment]
> I've just had the same under Debian 10. Managed to fix it by uninstalling poetry and letting the startup process install it again. This did result in a version change to poetry, removing version 1.2.0a2 and then installing 1.1.11
> 
> 
> 
> `tanelorn:~/Apps/SickChill$ .venv/bin/python3.7 -m pip uninstall poetry`
> 
> 
> 
> Sickchill then started using my standard unit file.

Fixed for me.

**Comment by bjwest** [comment]
> if editing isn't your thing. cd to the `../sickchill/share/SickChill/` folder where your `pyproject.toml` is
> 
> In my case on my SynoDSM `cd /volume1/@appstore/sickchill/share/SickChill/`
> 
> Then you can curl the edit version from #7630 `sudo curl -O https://raw.githubusercontent.com/SickChill/SickChill/93671f60da6cb7e9ee2f46c332aca3546eadf9ea/pyproject.toml`

This worked for me on Ubuntu Server 20.04.3 LTS.

**Comment by fonzy69** [comment]
yes it works if i launch it manually
i seek that the service try to launch sickchill.py from "SickChill\Python3\tools\Scripts\SickChill.py" but the file is in "SickChill\Python3\tools\Lib\site-packages\"
if i modify the path in registry according to this, service launch flawlessly

**Comment by fireph** [comment]
I can get it to launch manually but cannot get it to work in a FreeBSD jail when running as a service 😭

**Comment by explor202** [comment]
> 
> 
> > for me too the windows service stay paused after update. tried to uninstall / reinstall with last windows installer without success i don't find the pyproject.toml file in windows, Nothing appear in sickchill\data\logs\sickchill.log What can i do for help?
> 
> If you open a command window and run sickchill "direct" it seems to work (you need to leave the window open thou)
> 
> Something like this: C:\pathtopython\python.exe "C:\pathtosickchill\SickChill\SickChill.py" --nolaunch --port=8081 --datadir="C:\pathtosickchill\Data"

@JustSomeGuyNZ Thanks for this, it helped me get SC running again after a failed update.

**Comment by explor202** [comment]
> 
> 
> yes it works if i launch it manually i seek that the service try to launch sickchill.py from "SickChill\Python3\tools\Scripts\SickChill.py" but the file is in "SickChill\Python3\tools\Lib\site-packages" if i modify the path in registry according to this, service launch flawlessly

@fonzy69 Can you provide a general path to where to edit this?

**Comment by fonzy69** [comment]
For me it is in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SickChill\Parameters
The key to edit is "AppParameters"
I hope it help

**Comment by dracupg** [comment]
> > if editing isn't your thing. cd to the `../sickchill/share/SickChill/` folder where your `pyproject.toml` is
> > In my case on my SynoDSM `cd /volume1/@appstore/sickchill/share/SickChill/`
> > Then you can curl the edit version from #7630 `sudo curl -O https://raw.githubusercontent.com/SickChill/SickChill/93671f60da6cb7e9ee2f46c332aca3546eadf9ea/pyproject.toml`
> 
> This worked for me on Ubuntu Server 20.04.3 LTS.

Worked for me too on Ubuntu Server 18.04.6 LTS (I really should upgrade lol)

**Comment by explor202** [comment]
> 
> 
> For me it is in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SickChill\Parameters The key to edit is "AppParameters" I hope it help

@fonzy69 Thanks, that's where I found it too.

**Comment by brianjmurrell** [comment]
Also just got this after an update on Linux:

```
$ python3 SickChill.py
Checking poetry
Can write to /home/brian/.local/lib/python3.9/site-packages: True
Can write to /usr/local/lib64/python3.9/site-packages: False
We always run from virtualenv when running from source
Restarting SickChill with ['/net/server/src/SickChill/.venv/bin/python3.9', 'SickChill.py']
Checking poetry
Can write to /net/server/src/SickChill/.venv/lib64/python3.9/site-packages: True
Can write to /home/brian/.local/lib/python3.9/site-packages: True
pip installed: True
pip args: /net/server/src/SickChill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
poetry installed: True

  RuntimeError

  The Poetry configuration is invalid:
    - [scripts.SickChill] {'reference': 'SickChill.py', 'callable': 'SickChill.py', 'type': 'file', 'extras': ['cli']} is not valid under any of the given schemas
  

  at .venv/lib/python3.9/site-packages/poetry/core/factory.py:45 in create_poetry
       41│             message = ""
       42│             for error in check_result["errors"]:
       43│                 message += "  - {}\n".format(error)
       44│ 
    →  45│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       46│ 
       47│         # Load package
       48│         name = local_config["name"]
       49│         version = local_config["version"]
Unable to install to the existing virtual environment located at /net/server/src/SickChill/.venv
Please check the permissions, and that it does not include global site packages
```

Perhaps updating should be blocked until this is fixed so that one after another, every SickChill user doesn't break their installation?

**Comment by BKSteve** [comment]
Line 40 
`SickChill = {reference = "SickChill.py", callable = "SickChill.py", type = "file", extras = ["cli"]}`
remove `callable = "SickChill.py", ` to give you
`SickChill = {reference = "SickChill.py", type = "file", extras = ["cli"]}`
Should then run.

**Comment by LapinFou** [comment]
> 
> 
> if editing isn't your thing. cd to the `../sickchill/share/SickChill/` folder where your `pyproject.toml` is
> 
> In my case on my SynoDSM `cd /volume1/@appstore/sickchill/share/SickChill/`
> 
> Then you can curl the edit version from #7630 `sudo curl -O https://raw.githubusercontent.com/SickChill/SickChill/93671f60da6cb7e9ee2f46c332aca3546eadf9ea/pyproject.toml`

Thanks!!! 😍

This did fix my SickChill not starting after update.
Synology DS916+ / 8Go
DSM version 6.2.4-25556 Update 2

**Comment by kungktd** [comment]
> if editing isn't your thing. cd to the `../sickchill/share/SickChill/` folder where your `pyproject.toml` is
> 
> In my case on my SynoDSM `cd /volume1/@appstore/sickchill/share/SickChill/`
> 
> Then you can curl the edit version from #7630 `sudo curl -O https://raw.githubusercontent.com/SickChill/SickChill/93671f60da6cb7e9ee2f46c332aca3546eadf9ea/pyproject.toml`

Thank you very much! Worked for my Synology installation.

**Comment by repmeer** [comment]
This didn't fixed it for me. I ran 97 updates today on sickchill. Than sickchill didn't started anymore. I that deleted the package from my synology NAS DSM DSM 6.2.4-25556 Update 2.
I installed the latest version of Sickchill. Sickchill started but after a while sickchill stopped. Loading the webpage didn't work.

**Comment by spock99** [comment]
So I did not do the update after the fix reloaded my backup and all was fine and I was on the current synology release 20210729-3 as seen in package Center. again Key was I restore a backup reboot after I rebooted it did not show any upgrade needed. My case I was using x64 and was running 7.x but based on other threads I see people have been able to get 20210729-3 to run with same change on the 6.2 version.

**Comment by gits68** [comment]
to fix docker startup, I use :

`docker exec -i -t --privileged=true sickchill /bin/bash -c "sed -i 's|callable = .SickChill.py., ||' pyproject.toml"`

then wait for a couple of minutes (~10min) to access the /errorlogs/viewlog/

starting sickchill manually gives me the following errors, but starts :

`Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.2.0a2 requires importlib-metadata<2.0.0,>=1.6.0; python_version < "3.8", but you have importlib-metadata 4.8.1 which is incompatible.
poetry 1.2.0a2 requires packaging<21.0,>=20.4, but you have packaging 21.2 which is incompatible.`

**Comment by skydiverscott** [comment]
> > I've just had the same under Debian 10. Managed to fix it by uninstalling poetry and letting the startup process install it again. This did result in a version change to poetry, removing version 1.2.0a2 and then installing 1.1.11
> > `tanelorn:~/Apps/SickChill$ .venv/bin/python3.7 -m pip uninstall poetry`
> > Sickchill then started using my standard unit file.
> 
> Fixed for me.

How do you uninstall poetry?  I am running on windows from source with python 3.8 installed

**Comment by explor202** [comment]
> How do you uninstall poetry? I am running on windows from source with python 3.8 installed

Grab the latest Windows installer for SC released a few days ago. It fixed everything for me.
