### ISSUE TITLE
Windows service will not start after update

### ISSUE THREAD

**Issue by Yoshi900** [SickChill/SickChill#7631]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Install: pip
Version: v2021.07.23-1

Clicking the update button made the Sickchill service paused. 
There wasn't anything I could do to get it started. 
Tired uninstall and do a new install from the new windows setup which didn't fix the issue. 

I also tried using the pip command from a CMD once it was working but that didn't help. 

Only thing that saved me was a backup from windows backup the pervious night.

**Comment by BKSteve** [comment]
Read #7629

**Comment by BKSteve** [comment]
No logs or usable info so closing
