### ISSUE TITLE
Latest python package (2021.11.7) install errors 

### ISSUE THREAD

**Issue by aptalca** [SickChill/SickChill#7632]
Branch/Commit: pip stable
OS: Alpine linux
Browser: N/A
What you did: `pip install sickchill`
What happened: Exits with errors
What you expected: Successful install
Logs:
```
ERROR: For req: sickchill==2021.11.7. Invalid script entry point: <ExportEntry SickChill = SickChill.py:None ['cli']> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
```
Full build log with the errors: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-sickchill/detail/master/504/pipeline

And here's the dockerfile used: https://github.com/linuxserver/docker-sickchill/blob/master/Dockerfile#L41-L43

Thanks

**Comment by BKSteve** [comment]
Read #7629

**Comment by aptalca** [comment]
Can this be reopened? I noticed that a new commit was pushed to fix this, but the package on pypi.org has not been updated and it still has the issue as of more than 3 hours after the push. Here's a recent build: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-sickchill/detail/master/511/pipeline

Thanks

**Comment by BKSteve** [comment]
Sure, I can reopen but this is the same error as 7629 based on the pyproject.toml kicking at the `callable`
There's some more testing that is happening and as you note the recent change is to roll back an edit from a few hours before which killed SC from starting after an update. 
This is being looked into as it's affecting all, but will ultimately make thing much better and faster as the code moves forward.
