### ISSUE TITLE
Error on clean install of Sickchill V0.6.1

### ISSUE THREAD

**Issue by anuccite** [SickChill/SickChill#7642]
When my update failed and didn't work...  I spun up a fresh 2019 Server build to run a new install....

1st errors I saw while python was installing complained about python not being in path....  I updated that,  completely uninstalled, rebooted, re-installed
`Added to Path
C:\SickChill\Python3\tools\Scripts`

Then I get an error and the python scrip closes...  and sickchill does not install

ERROR: for req: sickchill. Invalid script entry point: <exportEntry Sickchill - sickchill.py:none ['cli']> - A callable suffix is required.  cf https://packaging.python.org/specifications/entry-points/#use-for scripts for more information

![Screenshot_2021-11-08 13-14-29](https://user-images.githubusercontent.com/72975698/140812070-fe5d22f7-9e6b-4e54-959e-21ed2f193a17.jpg)

**Comment by knapekt** [comment]
I have the same issue.  It originally cropped up when I upgraded when prompted, but a clean install also resulted in the same error message.  I also have the red text at the end of the install like the previous poster.

**Comment by cabersc** [comment]
Ditto.  When the upgrade failed, I tried a clean re-install, and nothing.  So now I wait for a fix...

**Comment by miigotu** [comment]
The problem is that poetry 1.2.0a2 is still installed for many people and that release was scrapped. 1.1.11 is the newest release as far as I know. I can remove callable, but then it fails to build into a package here.

**Comment by anuccite** [comment]
> 
> 
> The problem is that poetry 1.2.0a2 is still installed for many people and that release was scrapped. 1.1.11 is the newest release as far as I know. I can remove callable, but then it fails to build into a package here.

Can you Just remove the force look to see if we are installing the latest version?   I can't back level either

**Comment by Victorvdc** [comment]
THis problem has been reported many time by multiple users.
Something is broken in the manual and auto install. Or maybe it is the build itself
