### ISSUE TITLE
Windows 10 Update - failing with Critical Error

### ISSUE THREAD

**Issue by mwhitmel** [SickChill/SickChill#7644]
Trying to update my windows 10 install.. Not a python guy so really struggling to debug. seems to be throwing a lot of errors in the log

Install: pip
Version: v2021.07.23-1
Database Version: 44.5
  Python Version:3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
  SSL Version:OpenSSL 1.1.1k 25 Mar 2021
  OS:Windows-10-10.0.19043-SP0
  Locale:en_AU.cp1252

  User:SickChill
  Program Folder:F:\SickChill\Python3\tools\lib\site-packages\sickchill
  Config File:F:\SickChill\Data\config.ini
  Database File:F:\SickChill\Data\sickchill.db
  Cache Folder:F:\SickChill\Data\cache
  Log Folder:F:\SickChill\Data\Logs
  Executable:F:\SickChill\Python3\tools\python.exe
  Main Script:F:\SickChill\Python3\tools\Scripts\SickChill.py
  Arguments:--nolaunch --port=8081 --datadir=F:\SickChill\Data
Browser: - Chrome
What you did:   Clicked Updated now
What happened:  2021-11-09 10:42:11 Uncaught exception %s
%r
What you expected:
Logs: Attached
```
PASTE LOGS HERE
```
[sickchill.log.1.txt](https://github.com/SickChill/SickChill/files/7501528/sickchill.log.1.txt)

AA TypeError: update() missing 1 required positional argument: 'pid'
AA return function()
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "F:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "F:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA results = yield self.async_call(method)
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info) # type: ignore
AA File "F:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "F:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: can only concatenate str (not "Version") to str
AA self._notify_pht(update_text + new_version, title)
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\plex.py", line 71, in notify_git_update
AA n.notify_git_update(new_version)
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\__init__.py", line 115, in notify_git_update
AA notifiers.notify_git_update(settings.CUR_COMMIT_HASH or "")
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\pip.py", line 80, in update
AA return self.updater.update()
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\runner.py", line 308, in update
AA if updater.update():
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\views\home.py", line 687, in update
AA return function(**kwargs)
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/home/update/?pid=7064', version='HTTP/1.1', remote_ip='127.0.0.1')
2021-11-09 10:42:11 ERROR :: WEBSERVER :: Uncaught exception GET /home/update/?pid=7064 (127.0.0.1)
AA TypeError: update() missing 1 required positional argument: 'pid'
AA return function()
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "F:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "F:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA results = yield self.async_call(method)
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info) # type: ignore
AA File "F:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "F:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: can only concatenate str (not "Version") to str
AA self._notify_pht(update_text + new_version, title)
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\plex.py", line 71, in notify_git_update
AA n.notify_git_update(new_version)
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\__init__.py", line 115, in notify_git_update
AA notifiers.notify_git_update(settings.CUR_COMMIT_HASH or "")
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\pip.py", line 80, in update
AA return self.updater.update()
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\runner.py", line 308, in update
AA if updater.update():
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\views\home.py", line 687, in update
AA return function(**kwargs)
AA File "F:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/home/update/?pid=7064', version='HTTP/1.1', remote_ip='127.0.0.1')
2021-11-09 10:42:04 ERROR :: WEBSERVER :: Uncaught exception GET /home/update/?pid=7064 (127.0.0.1)

**Comment by Victorvdc** [comment]
I am having a similar problem.  Last night (Nov7) the update ran and today when I tried to access with Chrome I go a "Site Can not be reached" error.
1- Uninstalled and reinstalled (using windows installer) was success full but the same problem "Site Can not be reached" error.
2 Tried system restore ,reloading chrome . not the problem
3 Copied the C:\sickchill folder from my backup image . Old version now works fine
4 Tried manual update but it failed to execute.
5 Uninstalled Sickchill and reinstalled . Problem with new build still there
6 Copy back old image . Old version works fine
7 Turned off automatic updates for now
I can reproduce the poblem . Let me know how to capture logs if you need them

**Comment by ComicsCon** [comment]
When is it expected to be a windows installer that works? Not everyone is well versed in coding, scripts and so on. Many just use the software as it is.
No matter how many comments you read, it's hard to get a clear answer on exactly what it is you need to do to make it work after the failed update on a Windows 10/11.
