### ISSUE TITLE
Cpasbien new URL

### ISSUE THREAD

**Issue by gits68** [SickChill/SickChill#7646]
### Before submitting your issue:

Branch/Commit: 45567ca2301751b09a690672a640e28df60d931d
OS: docker image

[cpasbien](https://www.cpasbien.ac)

**Comment by gits68** [comment]
also, replace **/view_cat.php?categorie=series&trie=date-d** by **torrents/series** and delete **.replace(".", "-").replace(" ", "-") + ".html,trie-seeds-d"** in file **/app/sickchill/sickchill/oldbeard/providers/cpasbien.py**

`sed 's,/view_cat.php?categorie=series\&trie=date-d,torrents/series,;/recherche/s/.replace.*//' /app/sickchill/sickchill/oldbeard/providers/cpasbien.py`

**Comment by BKSteve** [comment]
fork / branch / edit / pull to develop

**Comment by miigotu** [comment]
Thanks!
