### ISSUE TITLE
update breaks sickchill service

### ISSUE THREAD

**Issue by FGOD1983** [SickChill/SickChill#7648]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/46455f17ef5e14a3b2581a522081cf1c33f4a0d8
OS: Ubuntu 20.04
Browser: Chrome
What you did: update to the newest master commits
What happened: sickchill service is dead and I can't get it started anymore
What you expected: service just starting after the update and sickchill just working
Logs:
```

```

**Comment by M-arc-O** [comment]
Same happend to me, When I run sickchill.py I get the following error
Restarting SickChill with ['/share/CACHEDEV1_DATA/.qpkg/QSickChill3/SickChill/.venv/bin/python3.7', 'SickChill.py']
/share/CACHEDEV1_DATA/.qpkg/QSickChill3/SickChill/.venv/bin/python3.7: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

**Comment by FGOD1983** [comment]
ah didn't notice that yet. I was more looking into journalctl and syslog, but couldn't find anything

**Comment by Victorvdc** [comment]
Same problem.  
I reinstalled backup C:\sickchill folder from image and it works again.
I disabled auto updates for now but they just stopped working too.

**Comment by FGOD1983** [comment]
Seems that if you delete the .venv folder after the update, it will start again, but it needs a bit of time to start up again

**Comment by DrDrewZA** [comment]
update broke my windows install too

**Comment by midnightx12** [comment]
looks like after the update and reinstalling sickchill, i am still unable to access. localhost refuses connection. However, was working prior.

**Comment by euphuzadan** [comment]
on my windows install i was having issues after the update as well so i went into the Edit Sickchill service NSSM service editor and noticed that the path for the sickchill.py was incorrect so updated the Arguments to "C:\SickChill\Python3\tools\Lib\site-packages\SickChill.py" and the back running again.

**Comment by rd1** [comment]
> on my windows install i was having issues after the update as well so i went into the Edit Sickchill service NSSM service editor and noticed that the path for the sickchill.py was incorrect so updated the Arguments to "C:\SickChill\Python3\tools\Lib\site-packages\SickChill.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data" and its back running again.

i concur, rewriting the service's parameter got Sickchill working again !

Thank you euphuzadan

**Comment by euphuzadan** [comment]
> > on my windows install i was having issues after the update as well so i went into the Edit Sickchill service NSSM service editor and noticed that the path for the sickchill.py was incorrect so updated the Arguments to "C:\SickChill\Python3\tools\Lib\site-packages\SickChill.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data" and its back running again.
> 
> i concur, rewriting the service's parameter got Sickchill working again !
> 
> Thank you euphuzadan
> 
> Edit: well, that was a short lived re-activation of the service! now sickchill can't go 2 clicks without throwing a 404 error.

Weird mine is still working fine.

**Comment by DrDrewZA** [comment]
> on my windows install i was having issues after the update as well so i went into the Edit Sickchill service NSSM service editor and noticed that the path for the sickchill.py was incorrect so updated the Arguments to "C:\SickChill\Python3\tools\Lib\site-packages\SickChill.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data" and its back running again.

Yup - this got me sorted too - thank you

**Comment by miigotu** [comment]
Fixed, a reinstall with windows installer might be necessary. No manual editing on a local install should be done unless you are working on a pull request, it just makes it harder to get the update when it is fixed.

**Comment by miigotu** [comment]
https://github.com/SickChill/windows-sickchill/releases/download/v0.6.2/SickChillInstaller.exe for windows, I had to fix the console script extension from .py to .exe

**Comment by nydave69** [comment]
> Fixed, a reinstall with windows installer might be necessary. No manual editing on a local install should be done unless you are working on a pull request, it just makes it harder to get the update when it is fixed.

could we get an option to not install as a service..
