### ISSUE TITLE
Synology upgrade / install broken

### ISSUE THREAD

**Issue by tinyhands01** [SickChill/SickChill#7653]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master, no idea what commit
OS: DSM 6.2.4-25556 Update 2
Browser: Chrome
What you did: Updated, updated, uninstalled, installed
What happened: Failed to keep 'running'
What you expected: Expected it to update and keep running
Logs:
```
Log?  What log?
```
2 days ago, DSM told me I had no updates waiting.
SickChill GUI told me there was an update, so I made a backup and then clicked the update link.
That killed it, so I went into DSM.
DSM now tells me to update Python3, Python3.8, and SickChill, so I updated from DSM in that order.
Pythons updated fine, SickChill will not stay running.
Uninstalled SickChill from DSM & reinstalled.
SickChill will not stay running.

**Comment by wasyl00** [comment]
I have the same problem. Running fresh install from app store. App is running for a while but stops after a while. Gui is not working during that time.

**Comment by BKSteve** [comment]
Please provide further information.
DSM model, did you install v 20210729-3 from SynoComm?
Before uninstalling did you see $7629 or many other issues listed on start failures after update. (pyproject.toml)?
Did you look at #7504, #7364 for some details on where to get logs and how to bash start as sc-sickchill to get more info?

NB. DSM model is important as there's a little problem with some cpu models and installing v-3.

**Comment by tinyhands01** [comment]
`DSM model, did you install v 20210729-3 from SynoComm?`
Yes

`Before uninstalling did you see $7629 or many other issues listed on start failures after update. (pyproject.toml)?`
Yes, but I didn't see anything specific in this thread that helped.  One suggestion was to delete the .venv directory, but it was never created. You suggested navigating to a directory and doing 'sudo curl' but that just dumps a bunch of stuff to console with no instruction what to do next.  You suggested editing line 40 in pyproject.toml qto remove 'callable' but didn't indicate whether I should insert 'extras' which isn't there.  Then miigotu closed the thread.

`Did you look at #7504, #7364 for some details on where to get logs and how to bash start as sc-sickchill to get more info?`
No, I've never seen these threads before.  Could they be stickied or copied into a wiki?
The log currently in /var/log/packages just shows the start command & pidfile.  It does not contain any other useful info.

Trying the bash start ...

`uname -a`
Linux diskstation 3.2.40 #25556 Thu Jul 1 14:30:20 CST 2021 armv7l GNU/Linux synology_armada370_213j

**Comment by BKSteve** [comment]
Sticky or Wiki. Yes, I asked miigotu for rights to edit the wiki just yesterday as there is a real need for some actual documentation and guidance on what to do when the brown stuff hits the fan.

So did the v-3 actually install for you or not?
If not go to #7504 we are testing v-3.10 which is 20211107 with the pyproject.toml fix and it's worked for others with armv7-6.1 config or use -22 which is confirmed working and a fallback.

**Comment by tinyhands01** [comment]
> So did the v-3 actually install for you or not?
Yes it installs, it just doesn't run.  As far as I can tell from what was output to console when I tried the bash start, several packages fail to build, couldn't find the Rust complier, couldn't find a module ...  I'll try to paste into next message.

> BKSteve closed this
Please don't close issues until they're resolved.  If I can figure out how to install either of the test versions you suggested, then I'll be back up and running, but it doesn't really resolve the problem that the Synocomm package doesn't install.  Thanks.

**Comment by BKSteve** [comment]
I closed because you are moving to #7504 this is a clear duplicate and I'm not going to support on 2 or more threads.

Also use \``` on line above and below when pasting large logs.
