### ISSUE TITLE
Torrent9 search URL have changed

### ISSUE THREAD

**Issue by gits68** [SickChill/SickChill#7654]
Branch/Commit: 45567ca2301751b09a690672a640e28df60d931d
OS: docker image

replace **torrents_series.html** by **torrents/series** in file **/app/sickchill/sickchill/oldbeard/providers/torrent9.py**

`sed -i s,torrents_series.html,torrents/series, /app/sickchill/sickchill/oldbeard/providers/torrent9.py`

**Comment by BKSteve** [comment]
Change torrent9.one to torrent.pw too?

**Comment by miigotu** [comment]
Fixes in #7661

**Comment by gits68** [comment]
hi, sorry for the late answer, no, https://www.torrent9.one should stay as is, it forward to the last good domain, .pw for instance.
