### ISSUE TITLE
[APP SUBMITTED]: Incorrect padding

### ISSUE THREAD

**Issue by snapperhead** [SickChill/SickChill#7667]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.11.10
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
during search for rarbg or?

**Comment by nedillon** [comment]
I have this same error in my log. It happened after clicking "Update Now". The update didn't actually do anything, just went to a blank page (/home/update/?pid=8500).

Here's my debug log:
`AA TypeError: update() missing 1 required positional argument: 'pid'
AA return function()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 190, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "C:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
AA value = future.result()
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
AA results = yield self.async_call(method)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 164, in get
AA yielded = self.gen.throw(*exc_info)  # type: ignore
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
AA result = await result
AA File "C:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA TypeError: can only concatenate str (not "Version") to str
AA self._notify_pht(update_text + new_version, title)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\plex.py", line 71, in notify_git_update
AA n.notify_git_update(new_version)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifiers\__init__.py", line 115, in notify_git_update
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\pip.py", line 80, in update
AA return self.updater.update()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\update_manager\runner.py", line 308, in update
AA if updater.update():
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\home.py", line 687, in update
AA return function(**kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 188, in async_call
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='localhost:8082', method='GET', uri='/home/update/?pid=8500', version='HTTP/1.1', remote_ip='127.0.0.1')`

**Comment by miigotu** [comment]
Try searching for the same issue with updates. Uninstall and reinstall using https://github.com/SickChill/windows-sickchill/releases/tag/v0.6.2 or pip update sickchill manually.

**Comment by snapperhead** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22000-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.11.10
No Log available with ERRORS:
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
