### ISSUE TITLE
SC Syno DSM uname to help SynoComm, Py310, new wheel testing

### ISSUE THREAD

**Issue by BKSteve** [SickChill/SickChill#7672]
### Amended as adding test package links for those interested in assisting SynoComm improvements.
Latest packages are under [th0ma7 github and is 20211110-5](https://github.com/th0ma7/synology/tree/master/packages/python310)

---
Not an issue or error as such, but SynoComm asking for 
`uname -a && uname -m` to help fix their build process and python38.

All DSM all models, this is to improve the SynoComm build and quality of software. 

Thanks to @xleaalex for being the first.

> Linux DiskStation 3.2.101 #42214 SMP PREEMPT Sat Aug 28 02:37:40 CST 2021 i686 GNU/Linux synology_evansport_214play
> i686

**Comment by mediafreakch** [comment]
I don't have DSM 7 installed, but cannot hurt: 

```
Linux SCHWYZ 2.6.32.12 #25556 Thu Jul 1 14:25:48 CST 2021 armv5tel GNU/Linux synology_88f6282_213air
armv5tel
```

**Comment by th0ma7** [comment]
Thnx @mediafreakch , that's one I much needed :)

**Comment by MichelRabozee** [comment]
In the previous thread, that info was requested for non x64 models. This thread does not seem to have that limitation, so here it is:
```
Linux Rabozee-Syno 4.4.59+ #25556 SMP PREEMPT Sat Aug 28 02:17:25 CST 2021 x86_64 GNU/Linux synology_geminilake_1520+
x86_64
```
If I am wrong, feel free to ignore.

**Comment by twinden** [comment]
$uname -a
Linux DiskStation 3.2.40 #25556 SMP PREEMPT Thu Jul 1 14:28:54 CST 2021 i686 GNU/Linux synology_evansport_214play
$uname -m
i686
slightly different than above, so i'm posting.

**Comment by BKSteve** [comment]
> slightly different than above, so i'm posting.

more than slightly, you're running DSM6 (\#255556) and the other is DSM7 (\#422214)

**Comment by TheQL** [comment]
DS215j (recent builds are working though)
# uname -a && uname -m
Linux 3.2.40 #25556 SMP Thu Jul 1 14:30:22 CST 2021 armv7l GNU/Linux synology_armada375_ds215j
armv7l

**Comment by twinden** [comment]
> > slightly different than above, so i'm posting.
> 
> more than slightly, you're running DSM6 (3.2.40 #255556) and the other is DSM7 (3.2.101 #42214)

Ah now i understand.
But isn't `**more /etc.defaults/VERSION**` a better way to dwetermine the DSM version ?

$more /etc.defaults/VERSION
majorversion="**6**"
minorversion="**2**"
major="6"
minor="2"
micro="4"
productversion="6.2.4"
buildphase="GM"
buildnumber="25556"
smallfixnumber="2"
nano="0"
base="25556"
builddate="2021/08/28"
buildtime="19:18:12"
adam@diskstation_t:/$

**Comment by twinden** [comment]
anyone ?

**Comment by th0ma7** [comment]
@twinden we are not trying to figure out the version but rather how the Linux kernel matches the machine hardware name (e.g. architecture found with `unmae -m`).

**Comment by MichelRabozee** [comment]
I have a second Synology as well (but not used for SickChill), I put the result of the commands:
Linux Rabozee-Syno2 3.10.105 #25556 SMP Sat Aug 28 02:15:59 CST 2021 x86_64 GNU/Linux synology_avoton_1515+
x86_64

**Comment by BKSteve** [comment]
from @basj 
Linux merbasj-nas 2.6.32.12 #25556 Thu Jul 1 14:25:48 CST 2021 armv5tel GNU/Linux synology_88f6282_213air
and
Linux basj-nas 4.4.180+ #42218 SMP Fri Sep 24 02:41:48 CST 2021 x86_64 GNU/Linux synology_geminilake_720+

**Comment by aurelien-joly** [comment]
`root@DiskStation:~# uname -a && uname -m
Linux DiskStation 3.2.101 #41890 SMP PREEMPT Fri Jun 25 02:38:42 CST 2021 i686 GNU/Linux synology_evansport_415play
i686
`

**Comment by miigotu** [comment]
They probably should use config.guess to get arch when building ^

**Comment by bneser** [comment]
$ uname -a
Linux DS216play 3.10.108 #42218 SMP Mon Oct 18 19:15:02 CST 2021 armv7l GNU/Linux synology_monaco_ds216play
$ uname -m
armv7l

**Comment by Thullie** [comment]
Linux NAS 3.2.101 #42218 SMP Mon Oct 18 19:14:51 CST 2021 armv7l GNU/Linux synology_armadaxp_ds414
armv7l

**Comment by BKSteve** [comment]
Latest packages for testing built by SynoComm are under [th0ma7 github and is 20211110-5](https://github.com/th0ma7/synology/tree/master/packages/python310)
th0ma7 is doing lots of work on the build package system for DSM `https://github.com/SynoCommunity/spksrc/pull/4951`

**Comment by th0ma7** [comment]
Wait for a bit before using those as I am building what I hope to be the last version before publishing.  Updated packages should be online shortly.

**Comment by th0ma7** [comment]
I had to clean-up my repository but its now completed.
Packaged uploading as I write under: https://github.com/th0ma7/synology/tree/master/packages/python310
I was able to test x86_64, but really what is missing are  `armv5tel`, `armv7`, `armv7l` ...

**Comment by mediafreakch** [comment]
Install of python 3.10 worked on `armv5tel`. However install of sickchill seems to have failed according to logs: https://pastebin.com/YN787hW5 . Can't say for sure until about 30' after install, that's the time sickchill usually needs to start. package is still shown as "running". Will update here later.

Due to the last message in the install log, I also attach my disk space log here:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       2.4G  1.1G  1.3G  46% /
none            118M  4.0K  118M   1% /dev
/tmp            122M   11M  112M   9% /tmp
/run            122M  2.7M  120M   3% /run
/dev/shm        122M  4.0K  122M   1% /dev/shm
/dev/vg1000/lv  1.8T  1.6T  220G  89% /volume1
```

**Comment by th0ma7** [comment]
@mediafreakch I've uploaded an updated python310 package including cython for you to test.
Can you uninstall python310 + sickchill then reinstall and see if it solved your issue?

**Comment by mediafreakch** [comment]
I used `python310_88f6281-6.1_3.10.0-3.spk` and it still failed: https://pastebin.com/pwmZWqtY

**Comment by th0ma7** [comment]
I saw tow errors it the logs that make me dubious: 
1. the first `Building without Cython`
2. and the lack of space:
```
ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device
```

So I wonder
1. could you doublecheck the md5sum/sha256sum of the python310 package you downloaded to make sure you are not use the previous version I had originally uploaded?
2. ensure to clean-up your `/tmp` directory.  I'm not sure but if I recall correctly Synology cleans it up at reboot time.

@BKSteve : my PR was merged yesterday.  To get `sickchill` to work on arm you may to revisit that part.  Interestingly all the requirements are already in `python310` so sickchill shouldn't bother with that at all in the first place.  You might need to re-introduce:
```
BUILD_DEPENDS += cross/libxml2
BUILD_DEPENDS += cross/libxslt
```
And locally add in your `requirements-crossenv.txt` the `lxml==4.6.3` to rebuild it locally for your environment.  But again, its already included in python310 so there shouldn't be a need for it (perhaps due to how the `pip` call is done in `service-setup.sh`)?

Wish I had kept my old armv5 nas...

**Comment by mediafreakch** [comment]
@th0ma7 

1. Checksum is `e263ff636804220e1e66f69d6626d51e`
2. Will try this evening, however I doubt this has an impact. As you can see from my previous post the disk occupation after the install was 11M / 122M for `/tmp`.

**Comment by mediafreakch** [comment]
@th0ma7 I know now why Cython isn't used during sickchill install. From the python 3.10 install logs:

> ERROR: Cython-0.29.24-cp310-cp310-arm_marvell_linux_armv5tel.whl is not a supported wheel on this platform.

No further details...

**Comment by spock99** [comment]
> I have an old 411slim I used for backup of my 918+ I think it v5arm if you want me to test a load on it I can.
It on 6.x code.
Thanks
Dan

**Comment by th0ma7** [comment]
> > I have an old 411slim I used for backup of my 918+ I think it v5arm if you want me to test a load on it I can.
> > It on 6.x code.
> > Thanks
> > Dan

That would be great!  411slim is armv5 indeed (and I'm trying to find a used one for me to test things up as well...)

**Comment by th0ma7** [comment]
> > ERROR: Cython-0.29.24-cp310-cp310-arm_marvell_linux_armv5tel.whl is not a supported wheel on this platform.

@mediafreakch that is of particular interest to me.  Can you provide the full logs for both python310 and sickchill?

**Comment by mediafreakch** [comment]
@th0ma7 Python 3.10 install log: https://pastebin.com/p0Neff0P . I did not attempt another sickchill install.

**Comment by spock99** [comment]
Well it looks like the 411slim just not up to it CPU been more then 97% for the last hour or so.
sc-sick+ 11740  0.0  0.6  21264  1528 ?        S    13:45   0:00 /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data
sc-sick+ 11751  6.8  5.1  48680 12768 ?        S    13:45   2:41 /volume1/@appstore/sickchill/env/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU -f/volume1/@appstore/sickchill/share/wheelhouse setuptools poetry wheel
sc-sick+ 13523 45.8  9.6  45620 24164 ?        S    14:22   1:16 /volume1/@appstore/sickchill/env/bin/python3 /tmp/pip-standalone-pip-ze8ly451/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-aoea4dfk/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --find-links /volume1/@appstore/sickchill/share/wheelhouse -- setuptools>=40.6.0 wheel cffi>=1.12; platform_python_implementation != 'PyPy' setuptools-rust>=0.11.4
sc-sick+ 15503 21.1  3.3  15628  8248 ?        R    14:24   0:01 /volume1/@appstore/sickchill/env/bin/python3 -u -c import io, os, sys, setuptools, tokenize; sys.argv[0] = '/tmp/pip-install-zgs7fv7w/cffi_09be4296a03d432d966538e5b5910c0f/setup.py'; __file__='/tmp/pip-install-zgs7fv7w/cffi_09be4296a03d432d966538e5b5910c0f/setup.py';f = getattr(tokenize, 'open', open)(__file__) if os.path.exists(__file__) else io.StringIO('from setuptools import setup; setup()');code = f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec')) bdist_wheel -d /tmp/pip-wheel-y6mr0vnd
admin    15584  0.0  0.3   4756   996 pts/6    S+   14:24   0:00 grep --color=auto sick


I wait to later tonight to see if sickchil is reachable or not but this CPU is very loaded.

![image](https://user-images.githubusercontent.com/2895145/143659040-9ed95a04-e351-4df6-be63-4e3134cfc361.png)

admin@Spock2:~$ uname -a && uname -m
Linux Spock2 2.6.32.12 #25556 Thu Jul 1 14:25:48 CST 2021 armv5tel GNU/Linux synology_88f6282_411slim
armv5tel

**Comment by spock99** [comment]
After two hours or so it stopped do you want the logs it really does not look to be functional on this box if so let me know what you need.

**Comment by BKSteve** [comment]
@th0ma7 I saw the merge
> PR was merged yesterday.

The original build depends with `lxml` previously brought the two others with it. 
I'll take a look when I have the chance. 
Will also look to see if can add Python wheels path to SickChill pip call.

Will also look at the other logs. 
For those posting logs if bash fails we need the SickChill.log file too.

**Comment by th0ma7** [comment]
@BKSteve I believe the underlying issue really is with the file naming under `armv5tel`.  I've opened an issue to find a proper for that specifically, worst case is to return to previous behavior of renaming as `none-any` for that specific platform so it installs all right.

As for `lxml` the issue is the same, the wheel name `lxml-4.6.3-cp310-cp310-arm_marvell_linux_armv5tel.whl` is not being recognized by `pip` when installing, as such it doesn't become available into default python310 for that platform.  In turns then sickchill tries to install it because it can't find it, and fails miserably as it doesn't have the dependency libraries packaged with it anymore (as it is expected to be provided by python310 in the first place...).

So all in all, its exactly the same issue.

**Comment by th0ma7** [comment]
@mediafreakch and @spock99 would you mind providing the "python" platform name on your device?
Using a shell on your NAS (e.g. connecting with ssh) do the following:
```
$ /var/packages/python310/target/bin/python3
>>> from sysconfig import get_platform
>>> print(get_platform())
>>> quit()
```

**Comment by spock99** [comment]
admin@Spock2:~$ /var/packages/python310/target/bin/python3
Python 3.10.0 (default, Nov 25 2021, 21:33:21) [GCC 4.6.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by mediafreakch** [comment]
```
linux-armv5tel
Linux-2.6.32.12-armv5tel-with-glibc2.4
armv5tel
SCHWYZ
Linux
uname_result(system='Linux', node='SCHWYZ', release='2.6.32.12', version='#25556 Thu Jul 1 14:25:48 CST 2021', machine='armv5tel', processor='')
```

**Comment by spock99** [comment]
>>> print(get_platform())
linux-armv5tel
>>> import platform
>>> print(platform.platform())
Linux-2.6.32.12-armv5tel-with-glibc2.15
>>> print(platform.machine())
armv5tel
>>> print(platform.node())
Spock2
>>> print(platform.system())
Linux
>>> print(platform.uname())
uname_result(system='Linux', node='Spock2', release='2.6.32.12', version='#25556 Thu Jul 1 14:25:48 CST 2021', machine='armv5tel')
>>> quit()

**Comment by hgy59** [comment]
> I saw tow errors it the logs that make me dubious:
> 
>     1. the first `Building without Cython`
> 
>     2. and the lack of space:
> 

@th0ma7 to solve the `/tmp folder out of space` you can define `USE_ALTERNATE_TMPDIR = 1` in the spk Makefile.

**Comment by th0ma7** [comment]
@mediafreakch I've uploaded new python310 packages for testing (`-4`).  Can you give that a try?

**Comment by basj** [comment]
I installed your python 3.10 and then latest SC for x64 on my 720+. It ran without a problem, installed backup from from 213Air and restarted. Worked perfectly.

**Comment by th0ma7** [comment]
> I installed your python 3.10 and then latest SC for x64 on my 720+. It ran without a problem, installed backup from from 213Air and restarted. Worked perfectly.

I was expecting x64 to run out great.  Can you give it a shot on your 213air?  that's an armv5 and really is one of the CPU type I`d like to get positive results from.  thnx in advance.

**Comment by mediafreakch** [comment]
Installed python-310-4, seems to have worked fine. Here are the logs: https://pastebin.com/2Ym3G7Yk 
Commencing with sickchill install now. Will update with the logs later here.

**Comment by spock99** [comment]
No change it loaded python310_88f6281-6.1_3.10.0-4.spk then once that was done took 30 minutes I loaded sickchill_88f6281-6.1_20211110-5.spk it stop 45- 1hour later never get access to the interface to configure.
Same thing tried prior with released 3.8 and 20211110-4 load slow again but it does run and provide access to the web interface to configure.

**Comment by th0ma7** [comment]
@mediafreakch and @spock99 I've uploaded a new version that now includes lxml wheel.  Feel free to give it a shot.  Note that python installation now looked good from @mediafreakch logs so only sickchill needs uninstall/reinstall.

**Comment by spock99** [comment]
sickchill_88f6281-6.1_20211110-6.spk stopped just like prior build -5
admin@Spock2:/volume1/@appstore/sickchill/var$ cat sickchill.log
Sun Nov 28 13:03:48 PST 2021
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstor                             e/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data
Writing PID: 20473 to /volume1/@appstore/sickchill/var/sickchill.pid

admin@Spock2:/volume1/@appstore/sickchill/var$

**Comment by spock99** [comment]
[python310.log](https://github.com/SickChill/SickChill/files/7614544/python310.log)
python log

**Comment by mediafreakch** [comment]
Looks like `20211110-6.spk` also fails. Here are the logs: https://pastebin.com/LsVTpexj

**Comment by th0ma7** [comment]
Thnx to both of you @spock99 and @mediafreakch .  I've tried figuring out reasons of the failures and have come up with a few fixes all running well on x86_64 but the tricky part here really is armv5.  As a side note I also found 2x second hand armv7 and armv8 NAS currently in shipping on my way, sadly no armv5 yet.

I would much appreciate if you could give it a shot at the new python & sickchill packages I've uploaded on my github.  You'll have first to fully uninstall previous versions before installing newer ones.  Note that the package version wasn't re-numbered.

**Comment by spock99** [comment]
I load tomorrow am

**Comment by spock99** [comment]
Still sickchill  stops
![image](https://user-images.githubusercontent.com/2895145/144452628-40bbe0a7-6788-474d-93be-a14e3570c090.png)

**Comment by th0ma7** [comment]
@spock99 thnx so much for testing.  Can you provide the full `/var/log/packages` for sickchill and python310?

**Comment by spock99** [comment]
Sure

[sickchill.log](https://github.com/SickChill/SickChill/files/7644418/sickchill.log)
[python310.log](https://github.com/SickChill/SickChill/files/7644419/python310.log)

pointing problem maybe here:
2021/12/02 06:26:13	    ERROR: Command errored out with exit status 1:
2021/12/02 06:26:13	     command: /volume1/@appstore/sickchill/env/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gandtpk_/cffi_48a28954b9a8456aa8ae99c4f6585d7d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gandtpk_/cffi_48a28954b9a8456aa8ae99c4f6585d7d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'
'"'"', '"'"'
'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-9pwvk0ml
2021/12/02 06:26:13	         cwd: /tmp/pip-install-gandtpk_/cffi_48a28954b9a8456aa8ae99c4f6585d7d/
2021/12/02 06:26:13	    Complete output (25 lines):

**Comment by hgy59** [comment]
> Sure
> 
> [sickchill.log](https://github.com/SickChill/SickChill/files/7644418/sickchill.log) [python310.log](https://github.com/SickChill/SickChill/files/7644419/python310.log)
> 

Error from `sickchill.log`
`2021/12/02 06:26:32	ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device`

@th0ma7 didn't you define `USE_ALTERNATE_TMPDIR = 1` in spk/Makefile?

**Comment by spock99** [comment]
To confirm hardware testing on
Linux Spock2 2.6.32.12 #25556 Thu Jul 1 14:25:48 CST 2021 armv5tel GNU/Linux synology_88f6282_411slim
armv5tel

other system not testing currently as it has no issues and is on 7.x

Linux Spock 4.4.180+ #42218 SMP Fri Sep 24 02:41:40 CST 2021 x86_64 GNU/Linux synology_apollolake_918+
x86_64

**Comment by th0ma7** [comment]
> Error from `sickchill.log` `2021/12/02 06:26:32 ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device`
> 
> @th0ma7 didn't you define `USE_ALTERNATE_TMPDIR = 1` in spk/Makefile?

@hgy59 no I didn't, can it be set only for armv5 using `ifdef` in `spk/Makefile` ?

And issue is a little frustrating as there is this sort of an imbalance of much to put in vs out on armv5 platform in particular.  I just got my armv7 and armv8 boxes, now pending reception my hard drives.  Hopefully I'll be able to find that right balance while juggling with cross & arch approaches not that I'll have more platforms to play with.

**Comment by th0ma7** [comment]
@spock99 and @mediafreakch Ok, got a new version to test-bed.  Quite confident that this should make a lot more mileage than previous versions.

**Comment by spock99** [comment]
That fixed it sickchill run and I can configure it!

**Comment by th0ma7** [comment]
Awesome!  I've finally found the right "imbalance" to get things working on non x64 platforms.
Would you mind posting the logs so I can check nothing got missed in background (python310 & sickchill)?
And of course, thnx very much, your help was really appreciated!

**Comment by spock99** [comment]
[python310.log](https://github.com/SickChill/SickChill/files/7650154/python310.log
[sickchill.log](https://github.com/SickChill/SickChill/files/7650156/sickchill.log)
)
