### ISSUE TITLE
Latest update breaks virtual environment

### ISSUE THREAD

**Issue by DBMandrake** [SickChill/SickChill#7673]
Is there any way to configure Sickchill NOT to use virtual environments ?

Ever since it started using virtual environments I'm frequently having updates break Sickchill and having to manually fix it. Sometimes deleting .venv fixes it, sometimes like this time it does not. This is getting frustrating to say the least.

I'm using Python 3.7.3 on a Debian buster based system. After deleting the .venv folder and allowing it to rebuild I'm getting:

```
Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.11 requires importlib-metadata<2.0.0,>=1.6.0; python_version < "3.8", but you have importlib-metadata 4.8.1 which is incompatible.
poetry 1.1.11 requires packaging<21.0,>=20.4, but you have packaging 21.2 which is incompatible.
poetry-core 1.0.7 requires importlib-metadata<2.0.0,>=1.7.0; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.5" and python_version < "3.8", but you have importlib-metadata 4.8.1 which is incompatible.
```

Not a clue how to resolve this to be honest hence posting here. Nothing has changed with python on the system as far as I can tell - I've been using Python 3.7.3 for about a year now.

Any suggestions anyone ?

**Comment by DBMandrake** [comment]
I see people having a similar issue over here:

https://github.com/SickChill/SickChill/issues/7629

However I have done a git pull --rebase to update sickchill to the latest version which supposedly includes a fix for this, deleted the .venv directory, then run sickchill again to rebuild the virtual environment unfortunately I'm still getting the same errors.

**Comment by miigotu** [comment]
poetry had a development release that is revoked. `pip uninstall -y poetry poetry-core cleo && ./SickChill.py`

**Comment by DBMandrake** [comment]
Sorry but this doesn't fix the issue as poetry is not installed in the python 3 system environment :

```
pip3 uninstall -y poetry poetry-core cleo
Skipping poetry as it is not installed.
Skipping poetry-core as it is not installed.
Skipping cleo as it is not installed.
```

The virtual environment tries to install poetry 1.1.11 and the problem remains.

This looks to be some dependency issue with python versions <3.8 that is affecting the debin supplied Python 3.7.3.

I'm building Python 3.9.8 from source as an alt install to see if this fixes the issue.

**Comment by DBMandrake** [comment]
Ok Python 3.9.8 is coming closer to working and doesn't have an issue with the version of importlib-metadata but it is still unhappy about the version of the packaging module:

```
Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.11 requires packaging<21.0,>=20.4, but you have packaging 21.2 which is incompatible.
```

Should Python 3.9.8 work ? This is a completely fresh installation of 3.9.8. If not, what is the recommended version of Python to use - if I'm compiling from source I can choose whatever version I like - I just picked 3.9.8 on a whim as a more recent version than the system installed version 3.7.3.
