### ISSUE TITLE
Update broke SickChill starting

### ISSUE THREAD

**Issue by skydiverscott** [SickChill/SickChill#7674]
The latest SC update broke running on Windows Server 2016

OS: WinServer 2016
Browser: NA
Running SickChill via NSSM service using command line:
D:\SickChill\sickchill>D:\SickChill\SickChill\Python3\tools\python.exe "D:\SickChill\SickChill\Python3\tools\Scripts\SickChill.py" --nolaunch --port=8083 --datadir="D:\SickChill\SickChill\Data"

When running this command line from an elevate CMD prompt, I get the error below:
```
Traceback (most recent call last):
  File "D:\SickChill\SickChill\Python3\tools\Scripts\SickChill.py", line 14, in <module>
    import sickchill.start
  File "D:\SickChill\SickChill\Python3\tools\Scripts\sickchill.py", line 14, in <module>
    import sickchill.start
ModuleNotFoundError: No module named 'sickchill.start'; 'sickchill' is not a package
```
None of the suggestions in https://github.com/SickChill/SickChill/issues/7629 resolved the issue

**Comment by miigotu** [comment]
https://github.com/SickChill/windows-sickchill/releases/tag/v0.6.2
