### ISSUE TITLE
Dependency issues with packaging and/or importlib-metadata since update

### ISSUE THREAD

**Issue by DBMandrake** [SickChill/SickChill#7676]
This is a continuation of ticket #7673 which got closed without any resolution to the problem.

Since the latest update there are python dependencies that can't be resolved no matter what version of python I try.

Sickchill was originally using Python 3.7.3 provided by apt on Debian Buster which had been working fine for over a year, however since the Sickchill update and subsequent fixes the virtual environment will not create with the following error:

```
Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.11 requires importlib-metadata<2.0.0,>=1.6.0; python_version < "3.8", but you have importlib-metadata 4.8.2 which is incompatible.
poetry 1.1.11 requires packaging<21.0,>=20.4, but you have packaging 21.2 which is incompatible.
poetry-core 1.0.7 requires importlib-metadata<2.0.0,>=1.7.0; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.5" and python_version < "3.8", but you have importlib-metadata 4.8.2 which is incompatible.
```

There is an issue both with versions of "importlib-metadata" and "packaging", including during a fresh installation of Sickchill with the latest git master version.

I have tried building several different versions of python from source and while the exact errors vary, there is always at least one problem that prevents the virtual environment from being correctly installed.

The most compatible version I've tried seems to be Python 3.9.8 but this still returns an error about the version of "packaging" being requested by Sickchill:

```
Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.11 requires packaging<21.0,>=20.4, but you have packaging 21.2 which is incompatible.
```

I have also tried Python 3.10.0 and 3.8.12 - on both of those the cryptography module fails to build due to "no rust compiler" even though I have a compatible version of the rust compiler installed.

Does anyone have any ideas ? There seems to be something really messed up with the virtual environment creation in the latest version of Sickchill as it will simply not complete successfully with any version of Python I have tried.

What version of Python are people using to run Sickchill successfully now ?

**Comment by DBMandrake** [comment]
I've been going back to older commits to try to find where it broke and I've realised that the dependency warnings are actually a red herring to the actual problem.

I've tried the following versions of Sickchill using Python 3.7.3:

Sep 9th - 376e73403105879d691657d9445bc49067757e7a - works OK, no errors or problems.

Sep 25th - fc116668867d71964b6144cf7218b4a648350a01 - dependency errors/warnings but sickchill still works:

```
Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.11 requires importlib-metadata<2.0.0,>=1.6.0; python_version < "3.8", but you have importlib-metadata 4.8.1 which is incompatible.
poetry-core 1.0.7 requires importlib-metadata<2.0.0,>=1.7.0; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.5" and python_version < "3.8", but you have importlib-metadata 4.8.1 which is incompatible.
```

October 27th - a39a6298db7c2977c8f962bced95445bf257b48a - crashes with illegal instruction.

```
Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.11 requires importlib-metadata<2.0.0,>=1.6.0; python_version < "3.8", but you have importlib-metadata 4.8.1 which is incompatible.
poetry-core 1.0.7 requires importlib-metadata<2.0.0,>=1.7.0; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.5" and python_version < "3.8", but you have importlib-metadata 4.8.1 which is incompatible.

Illegal instruction
```

This version and all later versions crash with an Illegal instruction with all versions of Python I've tested. As I'm running on an arm based system (using Debian hardfloat) I'm wondering if a dependency is somehow pulling in x86 code or other code for the wrong architecture ?

Not sure how to troubleshoot this Illegal instruction error so I guess I'm going back to an old version for now and disabling automatic updating.

**Comment by miigotu** [comment]
Sickchill works fine. Your environment has the wrong version of poetry. If you need to build cryptography, search that. Start off by `sudo apt install python3-venv`.

This issue tracker is not intended to teach you how to solve installation questions.

**Comment by DBMandrake** [comment]
You guys really don't have a clue how to test updates before release do you, or take user feedback for that matter.

You keep introducing massive breaking changes to Sickchill then try to blame users for the fallout. At least 4 times in the last year one of your updates has hosed people's systems due to lack of testing before pushing an update and I've personally spent many hours on multiple occasions trying to untangle and fix the mess caused by these buggy updates.

As for this most recent issue - how does my environment have the "wrong" version of poetry ? Poetry is not even installed in the system wide python environment, it is only being installed in the sickchill virtual environment by YOUR script so if the wrong version is being installed your script is at fault. What is the "right" version of poetry anyway ? It might help if you would actually tell me what version it should be instead of just vaguely saying I have the wrong version...

python3-venv is already installed.

Issues building cryptography is only a problem on one specific version of Python that I've tried to compile from source - and the only reason I'm doing that in the first place is because Sickchill has broken on version 3.7.3. In any case it turns out that whatever issue has been introduced by update a39a629 affects ALL versions of Python I've tested, so the cryptography issue is irrelevant as I have a working cryptography module on Python 3.7.3 and 3.9.8. So forget about cryptography.

As for not intended to "teach you how to solve installation questions" that's pretty rich mate - I'm not trying to install it, I have an existing installation that has been working for over 2 years now which has been broken by your update, yet again. I'm trying to help you find out whats wrong with YOUR update. If an update has new system requirements that must manually be resolved you should clearly state what these changed requirements are. If there are new system requirements in the update a39a629 what are they ??

I didn't just post on here after giving up after 5 minutes, I've spent many, many hours troubleshooting this over several days, going way beyond what would normally be expected, compiling and testing different python versions, tediously bysecting your git commits to find out where the trouble started etc and you're completely uninstereted in any feedback with a single line response which claims to fix the problem but DOESN'T HELP followed by closing two tickets in a row before I can even respond to your non-help.

That's pretty shit mate. I've even asked you specifically in the previous ticket which Python version you recommend me to use and I get no response. How can I troubleshoot this issue when I don't even know what the system requirements are and no-one will give that information ?

You guys really need to get a grip of your update practices and regression testing, if I was to release updates that broke the installation like this on any projects I contribute to I'd get my arse kicked, especially if I did it multiple times.

If you're just going to blame users for your bad updates and keep closing ticketes of someone who has spent days trying to diagnose what the hell is going on with this update then I think it's time for me to ditch this thing and switch to one of the alternatives as I just don't have the time to spend days trying to fix this after an update.

**Comment by MinusZero30** [comment]
I fully agree with @DBMandrake on all points.
The update was pushed and with no warning it was installed by a lot of people. The result was not pretty but no real solution was given by you guys. I didn't have time to search what went wrong with the update.
Saying that the fault is on our installation is just a joke. Cuz if you mess up like that with an update you shoudl at least make a warning and give a clear solution to revert to an operational state.

This post was a great help as I wasn't gonna spend as much time as @DBMandrake to find the good commit to rollback.

So thank you DB and not thx to @miigotu

**Comment by miigotu** [comment]
It wasn't my fucking update, mate. I don't even install poetry. Poetry had a release that was yanked (1.2.0a2 or some shit, 1.1.11 is the latest afaik.)

Delete the virtual env like 10 other issues say and fuckin git pull or pip install -U and start it back up. The bug isn't with SC, it's a dependency problem on your system.

Coming and opening issues without searching, about an issue that was fixed long ago it annoying af.

Don't like the software? Don't use it. Don't like updates? Turn the fucking updater off.

**Comment by miigotu** [comment]
And talking shit about a random commit that supposedly breaks something is stupid af when that commit only modifies a node package that isn't used by SC, only by the tests for code formatting on GitHub. Jfc. That commit didnt even change any python code.
