### ISSUE TITLE
[APP SUBMITTED]: ThreadPoolExecutor-0_1 :: [f638d1b] Missing time zone for network: Sat.1 Emotions. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by rkorn86** [SickChill/SickChill#7677]
### INFO
Python Version: **2.7.18 (default, May  3 2020, 20:31:45) [GCC 9.2.0]**
Operating System: **Linux-5.13.6-arch1-1-x86_64-with**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f638d1bca3b3db45b9d5c7da021b07c8c2030ca2
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [f638d1b] Missing time zone for network: Sat.1 Emotions. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Come on now. Sickchill doesn't even run on python2 for like 2 years now.

**Comment by rkorn86** [comment]
As long, as Sickchill is not offering a native way to use german airdates 
or a fully compatible tvdb alternative like glotz.info I will stick on a 
docker image of https://github.com/avpnusr/sickchill which is based on 
v2019.09.02-1.
Network timezones should be detached from a specific sickchill version. So 
I am using the in-app feature of reporting missing timezones, to help you 
to complete the database.

Adding own timezones for these networks would be in fact much more easier.

Am 16. November 2021 07:02:30 schrieb miigotu ***@***.***>:

**Comment by miigotu** [comment]
That's not an in app way of reporting anything in latest versions, because there is no database to complete. We use the networks from thetvdb directly. 

Do not spam the issue tracker with bug reports from outdated versions of Sickchill. It doesn't even allow that without first updating, for a reason.
