### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by krash1220** [SickChill/SickChill#7679]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:Linux Mint 20.2
Browser:Chrome
What you did: docker pull sickchill/sickchill
What happened: Error response from daemon: manifest for sickchill/sickchill:latest not found: manifest unknown: manifest unknown
What you did: docker pull sickchill/sickchill:master
What happened: http://localhost:8081/home/ won't run. localhost refused to connect.
What you expected
Logs:
```
PASTE LOGS HERE
```

**Comment by tomm1ed** [comment]
Same issue here on Ubuntu 20.04

ERROR: for sickchill  manifest for sickchill/sickchill:latest not found: manifest unknown: manifest unknown
ERROR: manifest for sickchill/sickchill:latest not found: manifest unknown: manifest unknown

**Comment by miigotu** [comment]
Because latest isnt a tag, use develop or master tag. sickchill/sickchill:master

**Comment by krash1220** [comment]
In my post I said I tried sickchill/sickchill:master but sickchill will not start after that.

**Comment by miigotu** [comment]
Let's not open duplicate issues, whether they are closed or not doesn't prevent discussion.

https://github.com/SickChill/SickChill/issues/7688#issuecomment-971059375

**Comment by utdrmac** [comment]
> Because latest isnt a tag, use develop or master tag. sickchill/sickchill:master

@miigotu, the provided docker-compose, https://github.com/SickChill/SickChill/blob/master/docker-compose.yaml, literally uses :latest tag. If it isn't a tag, please correct the file.

**Comment by miigotu** [comment]
The latest tag USED to exist, but it was not updated since the build process with builds was failing, so it was like 7 months old when there were new releases. It might come back, but it was always the same as master.

**Comment by pakraticus** [comment]
Please update the overview at https://hub.docker.com/r/sickchill/sickchill in the meantime.
