### ISSUE TITLE
Iptorrents cookie

### ISSUE THREAD

**Issue by S7icky** [SickChill/SickChill#7685]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:ubuntu 20.04
Browser: Chrome
What you did: Trying to get iptorrents working correctly 
What happened:  
What you expected:
Logs:
```
2021-11-16 11:01:57 INFO :: SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Cookie is not correctly formatted: cf_clearance=zJgG2v.y6mDJb2bH2kZSzK11qJsDZ5jpvRny4wAluwk-1637077498-0-150; cf_chl_prog=F9; cf_chl_rc_ni=4; uid=******; pass=************
```

**Comment by miigotu** [comment]
It isn't going to work even if you get the cookie right, because they are on a newer version of cloudfare and there is no library that can handle it.

**Comment by S7icky** [comment]
Why does the cookie work on Jackett then?

**Comment by miigotu** [comment]
Because jackett is written in a different language which does have a 3rd party library to bypass cloudfare.

**Comment by S7icky** [comment]
ahhh gotcha. Thanks.
