### ISSUE TITLE
Can't change email from Show notification list & email not sent for these addresses

### ISSUE THREAD

**Issue by kretzu77** [SickChill/SickChill#7686]
Hi,

Branch: master
Commit: 01020f3636d01535f60b83464d8127ea0efabfc7
OS: Synology DSM
Browser: Chrome
What you did: change/delete show email list from http://config/notifications/#social (+"save for this show")
What happened: 
- page refreshed, but show email list was the same after refresh; only for shows with blank show email list the email are saved
- email is not sent to addresses in this field 
What you expected: 
- to change the old show email list with the new one or to be able to delete email list for some shows
- to send emails for this list
Logs: this operation don't appear in logs, not even with debug
```

```

Please advise.
Thank you

**Comment by miigotu** [comment]
You'll have to debug this a bit and try to find the issue. Maybe open the chrome developer console and check console for errors in JavaScript. I have no way to test this or debug it.

**Comment by BKSteve** [comment]
can you also clarify if you are DSM 6 or 7, and whether this is similar to #7694

**Comment by kretzu77** [comment]
DSM 7

email list for shows is not saved in config folder (/data)

**Comment by BKSteve** [comment]
I've fired up my DSM7 image and found that for me the email SMTP, To, and port configurations are saved to config.ini but the individual shows and email for each show do not save in the config.ini file.
That the `Show notification list` and the save button
```
  $.post(scRoot + "/home/saveShowNotifyList", {
    show: $("#email_show").val(),
    emails: $("#email_show_list").val()
```
I'm wondering whether this is because SC `data` folder is now under `/volume1/@appdata/sickchill/` where as before it was under `/volume1/@appstore/sickchill/var/`

I have never used this function before so not sure where it saved the data before.

**Comment by kretzu77** [comment]
> @BKSteve the list is stored in the database, in the show table. Probably need to add some logger debug lines in `def saveShowNotifyList` and see what data is received from the jQuery call.

Hi,

The list is stored only 1st time (from blank).
If I try to delete the email list or to change the emails from that list, the info isn't stored anymore.

**Comment by BKSteve** [comment]
Yes, coding issues in that module. The fix #7700 resolves this, just waiting for my code changes to be cleared into develop.

**Comment by kretzu77** [comment]
Hi,

Any news?

Thanks'

**Comment by BKSteve** [comment]
If you want to test it just curl it from my branch

```
cd /volume1/@appstore/sickchill/share/SickChill/sickchill/views (assuming volume1)
sudo curl -O https://github.com/BKSteve/SickChill/blob/EmailNotification/sickchill/views/home.py
```

**Comment by kretzu77** [comment]
sickchill not starting anymore (stops after click on run) :(
any chance to rollback curl?

**Comment by BKSteve** [comment]
So @kretzu77 did that work for you?
Is the test file working and did it fix the email issue?

**Comment by kretzu77** [comment]
Hi,
Nope

1. what is working: 
- if a show has empty email list, I can add an email list
2. what is not working:
- if a show already has an email list I can't delete it (the empty field is not saved and on next show selection appear the old one again)
- if a show already has an email list I can't I can't change it (the new email list is not saved and on next show selection appear the old one again)

I'll wait for next prost processing task to see if send the email for 1. case

**Comment by BKSteve** [comment]
Did you curl the test file and restart SC?
The test file works for me and resolves the issues. And if you don't restart it didn't load the changes.

**Comment by kretzu77** [comment]
Yes, I restarted SC. Even the NAS. :(

**Comment by kretzu77** [comment]
Hi,

SC doesn't sent email to Show notification list for the show.

Only to Global email list

**Comment by BKSteve** [comment]
So the first part is fixed and email address per show can be input.
Now to trace and make sure the correct email list is used when sending the notification.

**Comment by BKSteve** [comment]
@kretzu77 
I just tested this with several scenarios and don't get your result of only global email list working. To me this is fully functional.

I'd need you to provide the debug log lines with `Notification recipients: ` string and those around it.

Here are my test logs, email addresses changed from 'real' to 'someone'

Snatch sending to both global and show specific, successful:
```2021-12-26 13:34:56 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: Notification recipients: {'someone@hotmail.com', 'someone-else@yahoo.com'}
2021-12-26 13:34:56 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: HOST: smtp.live.com; PORT: 587; FROM: someone@hotmail.com, TLS: True, USER: someone@hotmail.com, PWD: HotDynamic28sh!t, TO: {'someone@hotmail.com', 'someone-else@yahoo.com'}
2021-12-26 13:34:57 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: Sending initial EHLO command!
2021-12-26 13:34:57 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: Sending STARTTLS command!
2021-12-26 13:34:57 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: Sending LOGIN command!
2021-12-26 13:34:58 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: Snatch notification sent to [{'someone@hotmail.com', 'someone-else@yahoo.com'}] for "Cowboy Bebop (2021) - 1x02 - TBA - 1080p HDTV from MyProvider"
```
Sending to show specific, one address, success too.
```
2021-12-26 13:45:12 DEBUG :: SEARCHQUEUE-MANUAL-370312 :: Notification recipients: {'someone-else@yahoo.com'}
2021-12-26 13:45:12 DEBUG :: SEARCHQUEUE-MANUAL-370312 :: HOST: smtp.live.com; PORT: 587; FROM: someone@hotmail.com, TLS: True, USER: someone@hotmail.com, PWD: HotDynamic28sh!t, TO: {'someone-else@yahoo.com'}
2021-12-26 13:45:13 DEBUG :: SEARCHQUEUE-MANUAL-370312 :: Sending initial EHLO command!
2021-12-26 13:45:13 DEBUG :: SEARCHQUEUE-MANUAL-370312 :: Sending STARTTLS command!
2021-12-26 13:45:13 DEBUG :: SEARCHQUEUE-MANUAL-370312 :: Sending LOGIN command!
2021-12-26 13:45:14 DEBUG :: SEARCHQUEUE-MANUAL-370312 :: Snatch notification sent to [{'someone-else@yahoo.com'}] for "Alex Rider - 2x01 - Surf - 1080p HDTV from MyProvider"
```

With 2 addresses in the show specific box and no global address it also works. (only comma between the two, no space)
```
2021-12-26 13:50:03 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: Notification recipients: {'someone@hotmail.com', ' someone-else@yahoo.com'}
2021-12-26 13:50:03 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: HOST: smtp.live.com; PORT: 587; FROM: someone@hotmail.com, TLS: True, USER: someone@hotmail.com, PWD: HotDynamic28sh!t, TO: {'someone@hotmail.com', ' someone-else@yahoo.com'}
2021-12-26 13:50:03 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: Sending initial EHLO command!
2021-12-26 13:50:03 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: Sending STARTTLS command!
2021-12-26 13:50:03 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: Sending LOGIN command!
2021-12-26 13:50:05 DEBUG :: SEARCHQUEUE-MANUAL-367234 :: Snatch notification sent to [{'someone@hotmail.com', 'someone-else@yahoo.com'}] for "Cowboy Bebop (2021) - 1x03 - TBA - 1080p HDTV from MyProvider"
```

**Comment by kretzu77** [comment]
I activated debug log and I'll wait until postprocessing.

For me, notifications are only on postprocess:

Notify on postprocesssend  => send a notification when a postprocessing finishes?

**Comment by BKSteve** [comment]
I tested all 3 functions and easier to test a response with snatch as you can manually search and it pushes an email almost instantly. The others all take longer. 

Did you test your non global email address using the test function?

Don't forget to restart after setting debug logging.

**Comment by kretzu77** [comment]
Hi,

Emails are send only to global email list (test function is ok).
Not to Show notification list of the show.
This means that I receive the email in global email list account but NOT in Show notification list accounts.

The log lines are attached.

[debug.txt](https://github.com/SickChill/SickChill/files/7792150/debug.txt)

**Comment by kretzu77** [comment]
Hi,

Emails are send only to global email list (test function is ok).
Not to Show notification list of the show.
This means that I receive the email in global email list account but NOT in Show notification list accounts.

The log lines are attached.
[debug.txt](https://github.com/SickChill/SickChill/files/7792175/debug.txt)

**Comment by BKSteve** [comment]
It works fully for me. So I don't know what's wrong with yours. Here's my screen shot. Both valid addresses and worked as above logs.

![image](https://user-images.githubusercontent.com/10173496/147810800-845aa874-1a24-47d3-a2a5-a01348ed4172.png)

I'm assuming you edited the log and put `'global email list'` instead of valid email.
And you've clicked `'Save for this show'` for the one in question, and there are not odd characters, extra spaces infront or ctl characters in the email address line you saved?

**Comment by kretzu77** [comment]
Hi,

Replaced emails, yes. And saved show after every show (+ the other 2 save buttons on the page also).

After longer testing:
Some shows work and some not. ALL have the same values in field "show notification list". In .db all have the same values on that field.

Some voodoo? I don't have another explanation. =))

**Comment by BKSteve** [comment]
Some bad history???
Remove them to clear and save first, perhaps?
I had no shows with notification emails so it was clean at the beginning and worked. 
Leave it with you.

**Comment by kretzu77** [comment]
I tried clear+save+set again and nothing.
I'll try clear+save+restart sickchill on next try. Next Delete show (without files) + restart + add again.

**Comment by BKSteve** [comment]
That's why I put please test tag so others might consider having a go too. Hopefully one of the people following me will have a go and cross check to see if the mod is working.

I have 2 devices I've tested this on and both work correctly with the modified `views/home.py` file.
The quickest way to test is with the `snatch` selected. Then you can manual in SC snatch the same file over and over and can trigger the emailing function quickly.
Did you clear the `Global email list` and try with only the show email?

In my sickchill.db file here's the individual show notification list image.
![image](https://user-images.githubusercontent.com/10173496/148323806-a7a41b22-4057-4866-8dda-85c93e97c1fb.png)
Each contains 2 parameters `emails` and `prowlAPIs`

> {'emails': 'someone-else@yahoo.com', 'prowlAPIs': ''}

**Comment by kretzu77** [comment]
Strange.
I deleted email lists, saved, restarted.
I reintroduced them.
For some shows works, for some not. Always works for new added shows.

We can do more than that. The only solution is to delete all database and readd all shows probably. Not in my plans :)

Thank you very much for support man.

**Comment by BKSteve** [comment]
> We can do more than that. The only solution is to delete all database and readd all shows probably. Not in my plans :)

If your shows all have `tvshow.nfo` in their folder then rebuilding the database by starting fresh and bulk `add existing` is pretty easy. The `tvshow.nfo` provides all the data for it to collect and add to the database.

If the don't have `tvshow.nfo` then [https://github.com/SickChill/SickChill/issues/7316#issuecomment-882032483](https://github.com/SickChill/SickChill/issues/7316#issuecomment-882032483)

**Comment by BKSteve** [comment]
I know i closed this but can you grab out of the database the string for one that works and one that doesn't work. I can then put in my database. 
Want to see what's stored for the one that doesn't work and see if there's a code tweak that'll fix it.

**Comment by kretzu77** [comment]
This is the copy paste from sickchill.db

The Book of Boba Fett works
New Amsterdam (2018) doesn't work.

![Screenshot 2022-01-16 141759](https://user-images.githubusercontent.com/30404637/149659599-1efda297-0423-4f0f-8e81-b366c90a6008.jpg)

**Comment by BKSteve** [comment]
In regard the email they look both the same `{'emails': 'email.address@mail.com', 'prowlAPIs': ''}` as the code does an sql call only on the `notify_list` as per the image posted above.

**Comment by kretzu77** [comment]
Same emails on both shows, indeed.

**Comment by BKSteve** [comment]
If you're on windows copy your sickchill.db file and open it with something like 'DB Browser (SQLite)' that might help you identify what's in the database that's wrong. Or DM the file to me to take a look.

**Comment by kretzu77** [comment]
both shows have the same value in dedicated field.

The Book Of Boba Fett works, but New Amsterdam NOT.

Karma much? :))))

![image](https://user-images.githubusercontent.com/30404637/150397471-09f8e47b-ef5c-4735-ad3d-42e79ef57e86.png)

**Comment by BKSteve** [comment]
Now in develop with major edit to the code from miigotu. So switch to `develop` or `curl` this file from develop.

```
cd /volume1/@appstore/sickchill/share/SickChill/sickchill/views  
sudo curl -O https://raw.githubusercontent.com/SickChill/SickChill/develop/sickchill/views/home.py
```

**Comment by BKSteve** [comment]
In `develop` see #7700

**Comment by kretzu77** [comment]
I have to wait until the update is merged in master or I have to change branch to develop?

Thanks'

**Comment by BKSteve** [comment]
The edited fix doesn't fully work in my opinion. So stay with the curl you took. I've left comment on 7700

**Comment by kretzu77** [comment]
ok
thanks' a lot man
