### ISSUE TITLE
Update to v2021.11.10 fails

### ISSUE THREAD

**Issue by bouwew** [SickChill/SickChill#7687]
After installing (using -U and --force-reinstall) and starting sickchill, it fails.
There should be a file called Sickchill.py in `~/.local/bin`, it's not there. Instead there is a file called Sickchill with the contents:
![image](https://user-images.githubusercontent.com/11290930/142046762-13875a50-a075-4a9b-8379-117368115898.png)

When I reinstall v2021.7.23-1 everything works fine.

System: Debian 10 LC in Proxmox 7.

**Comment by miigotu** [comment]
No, there shouldn't. It was an improper entry point previously. The file is either `$SCDIR/.venv/bin/SickChill` or `~/.local/bin/SickChill`

**Comment by miigotu** [comment]
Edit your service file to call the correct file.

**Comment by bouwew** [comment]
Thanks for the pointer! It's working now :)
