### ISSUE TITLE
Docker image still not working

### ISSUE THREAD

**Issue by krash1220** [SickChill/SickChill#7688]
I stated in my first post that I tried docker pull sickchill/sickchill:master 
This is what I've been doing ever since I started using this docker image.

docker pull sickchill/sickchill
docker run -dit --user 1000:1000 --name sickchill --restart=always \
-v /TV/SickChill/Data:/config \
-v /TV/SickChill/Data:/data \
-v /TV/SickChill/TVShows:/tvshows \
-v /TV/SickChill/Downloads/Complete:/complete \
-v /TV/SickChill/Downloads/Torrents:/torrents \
-v /etc/localtime:/etc/localtime:ro \
-p 8081:8081 sickchill/sickchill
If I already have an image and I do docker pull sickchill/sickchill:master it updates my image and works fine.
If I try to do a new image

docker pull sickchill/sickchill:master
docker run -dit --user 1000:1000 --name sickchill --restart=always \
-v /TV/SickChill/Data:/config \
-v /TV/SickChill/Data:/data \
-v /TV/SickChill/TVShows:/tvshows \
-v /TV/SickChill/Downloads/Complete:/complete \
-v /TV/SickChill/Downloads/Torrents:/torrents \
-v /etc/localtime:/etc/localtime:ro \
-p 8081:8081 sickchill/sickchill:master

Sickchill will NOT load.

![Screenshot](https://user-images.githubusercontent.com/10324887/142066223-ec07e235-58df-4189-beb7-c4f12b99442c.png)

Can you explain to me what I am doing wrong? I've tried deleting the data folder and not deleting the data folder.
This is the log from the image. I don't understand any of it but this is why it's not starting?
Checking poetry
Can write to /.local/lib/python3.9/site-packages: False
Can write to /app/sickchill/.venv/lib/python3.9/site-packages: False
Current environment is not writable!
Unable to install to the existing virtual environment located at /app/sickchill/.venv
Please check the permissions, and that it does not include global site packages
Checking poetry
Can write to /app/sickchill/.venv/lib/python3.9/site-packages: False
Can write to /.local/lib/python3.9/site-packages: False
Current environment is not writable!
Unable to install to the existing virtual environment located at /app/sickchill/.venv
Please check the permissions, and that it does not include global site packages
Checking poetry
Can write to /app/sickchill/.venv/lib/python3.9/site-packages: False
Can write to /.local/lib/python3.9/site-packages: False
Current environment is not writable!
Unable to install to the existing virtual environment located at /app/sickchill/.venv
Please check the permissions, and that it does not include global site packages
Checking poetry
Can write to /app/sickchill/.venv/lib/python3.9/site-packages: False
Can write to /.local/lib/python3.9/site-packages: False
Current environment is not writable!
Unable to install to the existing virtual environment located at /app/sickchill/.venv
Please check the permissions, and that it does not include global site packages

**Comment by kyuuk** [comment]
hello @krash1220, it's the `--user` option that is causing this problem. if you remove it from the command it should work, but i think that it will also create all the files outside the container as root,

i will try to look further into this issue 👍

**Comment by krash1220** [comment]
OMG, you are correct. Thank you so much. I just don't understand why it was working before but not now. It doesn't matter, really, as long as it's working. I really appreciate your help.

**Comment by miigotu** [comment]
--user is not supported, never has been for SC.
```
PUID=1000 PGID=1000 docker run -dit --name sickchill --restart=always
-v /TV/SickChill/Data:/config
-v /TV/SickChill/Data:/data
-v /TV/SickChill/TVShows:/tvshows
-v /TV/SickChill/Downloads/Complete:/complete
-v /TV/SickChill/Downloads/Torrents:/torrents
-v /etc/localtime:/etc/localtime:ro
-p 8081:8081 sickchill/sickchill:master
```

**Comment by kyuuk** [comment]
@krash1220 you are welcome mate, 

i guess miigotu is right about that, the `-e PUID=1000 -e PGID=1000` should be the right way to run it and have all the right permissions

**Comment by krash1220** [comment]
Well, that's funny because I got that command from the docker image page.

https://hub.docker.com/r/sickchill/

docker run -dit --user 1000:1000 --name sickchill --restart=always \
-v /path/to/shows:/path/to/shows \
-v /path/to/downloads:/path/to/downloads \
-v /path/to/data:/data \
-v /path/to/data/cache/gui:/app/sickchill/gui/slick/cache \
-v /etc/localtime:/etc/localtime:ro \
-p 8081:8081 sickchill/sickchill

**Comment by kyuuk** [comment]
yup the documentation seem a little outdated :/

**Comment by pakraticus** [comment]
With -e PUID=1000 -e PGID=1000 it still writes as root.  It appears to be a quirk of linuxserver.io, which the current Dockerfile does not use. https://docs.linuxserver.io/general/understanding-puid-and-pgid

I can consistently see the misbehavior with 
rm -rf /tmp/sc; docker run --rm -i -t -e PUID=1000 -e PGID=1000 -v /tmp/sc/data:/data -v /tmp/sc/tv:/tv -p 8081:8081 sickchill/sickchill:master
Then I add a TV show and add the /tv directory for the tv show and it's owned by root:root
$ find /tmp/sc/tv -ls
    62672      0 drwxr-xr-x   3 root     root           60 Nov 26 09:06 /tmp/sc/tv
    62757      0 drwxr-xr-x   2 root     root           40 Nov 26 09:06 /tmp/sc/tv/Law\ &\ Order\ True\ Crime

**Comment by pakraticus** [comment]
RUN chmod -R a+w /app/sickchill/.venv
VOLUME /app/sickchill/.venv
appears to fix it in a Dockerfile that works from sickchill/sickchill:master
Validating against a complete docker build and will submit pull request.
