### ISSUE TITLE
Sickchill path should follow the xdg specification

### ISSUE THREAD

**Issue by jlneder** [SickChill/SickChill#7691]
Currently the profile path is set to "$HOME/sickchill".
To follow the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) the correct path should be "$XDG_CONFIG_HOME/sickchill"(default to $HOME/.config) or "$XDG_DATA_HOME/sickchill"(default to $HOME/.local/share).
I made the change myself on the code, but i guess the changes should be different to contemplate for non-linux hosts.

**Comment by miigotu** [comment]
XDG is a Linux only specification, and the dir that is used can be set with command line arguments. Sorry but this isn't going to change any time soon and break everyone's install again.
