### ISSUE TITLE
Update DSM7 not functional

### ISSUE THREAD

**Issue by itsme9x** [SickChill/SickChill#7693]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Branch: pip
OS: DSM 7
Browser: Chrome
What you did: install the new sickchill_aarch64-7.0_20211110-4.spk on DSM7 (DS118), got promted with the message Unknown current version number: If you've never used the SickChill upgrade system before then current version is not set. — Update Now
What happened: Error while updating
What you expected: That the update url works.
Logs:
```
2021-11-17 20:10:17 WARNING :: WEBSERVER-HOME_0 :: Unable to retrieve new version from https://github.com/SickChill/SickChill/tarball/pip, can't update
2021-11-17 20:10:17 INFO :: WEBSERVER-HOME_0 :: Request failed: 404 Client Error: Not Found for url: https://codeload.github.com/SickChill/SickChill/legacy.tar.gz/pip ()
2021-11-17 20:10:16 INFO :: WEBSERVER-HOME_0 :: Downloading update from https://github.com/SickChill/SickChill/tarball/pip
2021-11-17 20:10:16 INFO :: WEBSERVER-HOME_0 :: Creating update folder /volume1/@appdata/sickchill/data/sc-update before extracting
```

**Comment by BKSteve** [comment]
The `https://github.com/SickChill/SickChill/tarball/pip` is not usual.
Did you ever have SC installed before? Did you upgrade to DSM7 from DSM6 when it was installed? 

Did you try uninstall and reinstall.

Please share `/var/log/packages/sichchill.log` if uninstall reinstall didn't resolve this error.

**Comment by itsme9x** [comment]
Yes sickchill was installed before, also while still at DSM6.

After the upgrade it was broken and I removed it, since then I was using a windows version of sickchill until I could install sickchill again on my Synology DS118 with DSM7

**Comment by BKSteve** [comment]
Uninstall and then check to make sure SickChill folder isn't in the `/volumeX/@appstore` folder. Clean it all out and make sure there's no junk left from upgrading to 7. 
Probably best to uninstall Python 3.8 too. 
Then install Python 3.8.12-6 and then SickChill 20211110-4 both from Package Center. 
Start it and make sure SickChill runs. 
Update or restore one at a time. Don't update and restore at the same time.

**Comment by miigotu** [comment]
Your config.ini has branch pip in it, change the branch to master either by stopping SC and editing the ini, or try changing it in the GUI.

**Comment by itsme9x** [comment]
hmm, when I goto cogwheel --> , i get:

FixME
A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

I think somehow my config file (coming from windows 10) is breaking thing, ill do a clean install and reconfig all by hand and see how that goes later.

**Comment by itsme9x** [comment]
> Your config.ini has branch pip in it, change the branch to master either by stopping SC and editing the ini, or try changing it in the GUI.

Gogwheel --> General --> Advanced Settings --> Branch version to master --> Save and restart solved it.

Now had 185 new commits, updated it and works fine now!
