### ISSUE TITLE
synodsmnotify not working in sickchill with DSM7

### ISSUE THREAD

**Issue by spock99** [SickChill/SickChill#7694]
Describe the bug
No notification sent to host system when download shows

To Reproduce
Download any show after turning synology notifier on

Expected behavior
I would expect it to sent notification anytime it grab file none seen
Work fine in DSM6.x Know change to synodsmnotify in DSM7

Screenshots
Nothing to show

SickChill Info:
Branch: master
Commit: 01020f3636d01535f60b83464d8127ea0efabfc7
Database Version: 44.5

  Python Version:
3.8.12 (default, Oct 22 2021, 21:05:38) [GCC 7.5.0]

  SSL Version:
OpenSSL 1.1.1l 24 Aug 2021

  OS:
Linux-4.4.180+-x86_64-with-glibc2.2.5

Additional context
Is there any way to test and trace this?
DS918+
synodsmnotify was changed in DSM7

Below is example from another project that was looking at this.
https://community.synology.com/enu/forum/36/post/140600

Failure in Sickchill is same issue the related to synodsmnotify and i18n under DSM-7
This command can also be run from command-line 

Hope this helps

**Comment by spock99** [comment]
Be aware this not related to mail. It is Synology notification this sent to the web interface. Reproduction can be done on cli on 6.x but 7.x changed text format so need to support new format.

**Comment by BKSteve** [comment]
This is a pain in the A.. i18n no ability to seemingly input text directly. Everything pre assembled.
[https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/7.0/enu/DSM_Developer_Guide_7_0_Beta.pdf](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Firmware/DSM/7.0/enu/DSM_Developer_Guide_7_0_Beta.pdf)
```
Application InternationalizationThe desktop application can have i18n text referenced by config, help, etc.
ui (specified by dsmuidir in INFO)
└── texts   
├── enu   
│    └── strings
└── cht
     └── strings
You have to create directories according to supported languages then create a file named strings inside each language directory.
[dsmuidir]/texts/enu/strings
    [app_tree]
    index_title="This is a title"  
    node_1="This is node1"  
    [app_tab]  
    tab1="This is tab1"  
    tab2="This is tab2"

[dsmuidir] /texts/cht/strings
    [app_tree]  
    index_title=""  
    node_1="1"  
    [app_tab]  
    tab1="1"  
    tab2="2"
    
When you want to use these texts, just reference them in `section:key` format (one value can only be one i18n string)
    "title": "app_tree:node_1"
```
typical lack of clarity from Synology.
So have raised a ticket with them for advice on using `synodsmnotify`
Even tried adding the strings file which fixed the i18n error but still `is not mail string key`

**Comment by miigotu** [comment]
Need to set `DSM_UI_DIR = ui` in makefile
create `src/ui/texts/enu/strings` with some strings we want to use
Add `src/ui/config` https://github.com/SynoCommunity/spksrc/blob/66b4dbc55981d3d47c6e6b766cccb401f0703461/spk/dnscrypt-proxy/src/ui/config

`src/ui/application.cfg`
https://github.com/SynoCommunity/spksrc/blob/66b4dbc55981d3d47c6e6b766cccb401f0703461/spk/dnscrypt-proxy/src/ui/application.cfg

And some other things i'm sure, and then call it like `/usr/syno/bin/synodsmnotify -c SYNO.SDS.SickChill.Application  admin SickChill:app_tree:index_title SickChill:app_tree:node_1`

https://github.com/SynoCommunity/spksrc/tree/66b4dbc55981d3d47c6e6b766cccb401f0703461/spk/dnscrypt-proxy/src/ui

I'm not 100% sure but that's what I have found so far. Just create an english one for now and people can add translated ones if they wish later. The notifier will need to be adjusted inside SC also.

@publicarray might be able to tell you if you miss something.

**Comment by miigotu** [comment]
btw, adding back appconfig will add SC back to the synology menu https://github.com/SynoCommunity/spksrc/blob/0b23159006a5b2b6e25624726828c0826dc92ec6/spk/sickbeard-custom/src/app/config

**Comment by BKSteve** [comment]
We already have dsmuidir = "app" in the INFO file and I created the file `strings` there `/volume1/@appstore/sickchill/app/text/enu/strings` as the dsmuidir is used for logo images too. (doing this file creation got rid of i18n error but not the other `mail string key` error.
```
[app_tree]
title="SickChill"
strtdl="Start Download"
```
I then use this command `/usr/syno/bin/synodsmnotify -c com.synocommunity.packages.sickchill @administrators sickchill:app_tree:title` and some other combinations of caps. 
`com.synocommunity.packages.sickchill` is also from the INFO file like they say "SYNO.SDS..." but will give this a try just to see what happens.
On discord publicarray pointed me to the same links above.
Will wait for Synology to respond further, as eventually we got updated info to fix the DownloadStation issue before.

**Comment by BKSteve** [comment]
@spock99 so they dumped you on medusa with this issue then?

**Comment by spock99** [comment]
Yes correct I am very happy with how this team responds and is open to addressing and improving product. I not programmer but I was a test engineer for network/storage product so I have tweak tcl and expect script so I understand all the hard work you guys are doing.
Again thanks

**Comment by BKSteve** [comment]
Well Synology gave me a RTFM reply with no additional information today. I've already responded to that with IRTFM and resovled i18n but not the other mail key error.

**Comment by BKSteve** [comment]
Well it's kind of working.
`/usr/syno/bin/synodsmnotify @administrators sickchill:appsc:apptitle sickchill:appsc:action`
It does send messages to the notifications however it's not resolving the i18n strings to text.
As in the message ends up with 

> Category: sickchill:appsc:apptitle
Event: sickchill:appsc:action
Time: (when message sent)

When I expected to see
> Category: SickChill
Event: Action
Time: (when message sent)

Which is what's in the file.

**Comment by BKSteve** [comment]
The reason the messages weren't resolving has been identified.
The INFO file `/var/packages/sickchill/INFO` contains `dsmappname="com.synocommunity.sickchill"`
BUT
The config file which is in `/volume1/@appstore/sickchill/app/` contains `com.synocommunity.packages.sickchill`
So they don't match!!
So DSM7 notifications doesn't work until they line up. Oh and you restart your DSM.

In the end either INFO has to change or config has to change.

**Comment by BKSteve** [comment]
> btw, adding back appconfig will add SC shortcut back to the synology menu https://github.com/SynoCommunity/spksrc/blob/0b23159006a5b2b6e25624726828c0826dc92ec6/spk/sickbeard-custom/src/app/config

This gets fixed when the INFO and config files are aligned.

**Comment by spock99** [comment]
Making progress I see 🖖

**Comment by BKSteve** [comment]
I got the following from Synology
```
1. Please note, Passing a variable to an i18n string is currently not supported. 
```
Thus if `fixed` strings is all we want we can use synodsmnotify. But that's quite useless.

So I asked how `Download Station` does it.
```
As we reported in the last ticket "Download Station is using another internal string system, but this system is not possible to publish now"

So we may not able to provide detailed information about it now, I'm very sorry for all the inconvenience this has caused.
```
Oh, they sent me the inquiry reference number but it's not available yet, but they refer to it in this message.

An unpublished system. WTF Synology!!

**Comment by spock99** [comment]
Hmm so sad 😭 Synology make this change then does not support it.

**Comment by miigotu** [comment]
> > btw, adding back appconfig will add SC shortcut back to the synology menu
> 
> This gets fixed when the INFO and config files are aligned.
> So @miigotu ok to stay with the fact `config` has by default gone to `dsmuidir="app"` that I add the files there rather than moving all to a new `ui` folder?
> The icon files are also needed to be in the same `dsmuidir` folder. 

Sorry I never saw this mention for some reason.

Good work fixing this in
https://github.com/SynoCommunity/spksrc/pull/4993
