### ISSUE TITLE
Looney Tunes Golden Collection

### ISSUE THREAD

**Issue by MSP85D** [SickChill/SickChill#7712]
I have downloaded this 6 box set and would like to add them to sickchill but the set does not exist in IMDB or TheTVDB.

Is there, or will there ever be, an option to create your own show?

**Comment by mavack** [comment]
The solution to this is to create the set on tvdb, its an open database with some rules etc and generally if it doesnt exist you can create it.

**Comment by TheExpertNoob** [comment]
This may help
https://github.com/TheExpertNoob/PlexClassicCartoons
