### ISSUE TITLE
Clean up leftover/associated files

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#7716]
Is it possible to add a function to clean up leftover files? If a mkv is deleted, it would be nice if the associated files could be removed at some point.

**Comment by twinden** [comment]
and the dir.
same for queue and nzb dirs after x number of days.

**Comment by BKSteve** [comment]
You need to detail what conditions you want this to function under and why SC should handle it for you. 
So please explain what deletes the mkv and what you expect the function to be.
The current remove and delete show clears whole folders and cleans up.

**Comment by Tiwas** [comment]
@BKSteve  This would be under the same function that marks a show as archived when an episode has been deleted manually. There is some kind of maintenance functionality run every x hours checking if an episode was removed in order to update the database, and I was hoping this could also remove residual files.

Example: SC downloads an episode of some show, you watch it in plex and decides to delete it. As plex will only delete the show itself and not any of the other files, there will be a lot of left over junk files. When SC scans the files, it could delete the *.nfo, *.srt etc at the same time the show is marked as archived.
