### ISSUE TITLE
show info url in “add show” tru blankrefer.com does not work anymore.

### ISSUE THREAD

**Issue by twinden** [SickChill/SickChill#7718]
after searching a new show in “add show” the info url by clicking the title does not work anymore.
for example https://blankrefer.com/?https://thetvdb.com/?tab=series&id=308178&lid=7 is opened.

I believe the site blankrefer.com is gone . . .

**Comment by MichelRabozee** [comment]
As far as I know, and if I am not mistaken, redirecting via blankrefeer.com is a kind of artefact of a malware ( cf https://malwaretips.com/blogs/remove-blankrefer-com/ ). Therefore, blankrefer.com has been shutdown and you should clean up your computer.

**Comment by pakraticus** [comment]
It's here https://github.com/SickChill/SickChill/blob/master/sickchill/settings.py#L66
Was introduced Jun 28 in commit 7e98f518bb0be71097d5a96a94c53e3cce0e415e
https://github.com/SickChill/SickChill/issues/4104

**Comment by twinden** [comment]
> As far as I know, and if I am not mistaken, redirecting via blankrefer.com is a kind of artefact of a malware ( cf https://malwaretips.com/blogs/remove-blankrefer-com/ ). Therefore, blankrefer.com has been shutdown and you should clean up your computer.

it’s in SickChill don’t you think ?!

**Comment by twinden** [comment]
> It's here https://github.com/SickChill/SickChill/blob/master/sickchill/settings.py#L66
> Was introduced Jun 28 in commit [7e98f51](https://github.com/SickChill/SickChill/commit/7e98f518bb0be71097d5a96a94c53e3cce0e415e)
> #4104

Changing the url in Settings / General / Advanced to https://dereferer.me/ ?
as mentioned in #4104 worked !
