### ISSUE TITLE
Update Fail : 404 Client Error

### ISSUE THREAD

**Issue by BUZZ2K** [SickChill/SickChill#7720]
Image of the config :
[https://ibb.co/Xpnn56T](url)

Branch/Commit: master
OS: debian
Browser: chrome
What you did: clicked on the link "update now" on sickchill
What happened: Got an error message : "La mise à jour a échoué : La mise à jour n'a pas été appliquée, il n'y a pas eu de redémarrage. Consultez votre journal des événements pour plus d'informations."
What you expected: Sickchill to be updated
Logs:
```
2021-11-29 14:31:48 INFO :: CHECKVERSION :: Update failed!
2021-11-29 14:31:45 INFO :: CHECKVERSION :: Config backup successful, updating...
2021-11-29 14:31:43 INFO :: CHECKVERSION :: Config backup in progress...
2021-11-29 14:31:43 INFO :: CHECKVERSION :: Request failed: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/SickChill/SickChill/v2021.11.10-None/sickchill/oldbeard/databases/main.py ()
2021-11-29 14:31:43 INFO :: CHECKVERSION :: New update found for SickChill, starting auto-updater ...
```

**Comment by BUZZ2K** [comment]
Hi, 
Am i the only one with the issue ?
For info, the install have been made with pip.
Thanks for any help.

**Comment by BKSteve** [comment]
You haven't provided any info on your current installed version.
Branch, commit, ... see image
![image](https://user-images.githubusercontent.com/10173496/150754795-9ecc0bfa-e296-476b-9cb1-075dbf657e69.png)


The error is clear `https://raw.githubusercontent.com/SickChill/SickChill/v2021.11.10-None/sickchill/oldbeard/databases/main.py` doesn't exist.

First step to fix, 1. Backup, 2. Uninstall, 3. Reinstall using latest, 4. Restore backup.

**Comment by BUZZ2K** [comment]
Hi,
Thanks for the reply.

I've updatted the first post with the image of the config that can be seen here [https://ibb.co/Xpnn56T](url)

The error mention a file that does not exist but, as you will see in the config, it is absolutely not the folder sickchill is running...

**Comment by BKSteve** [comment]
Your one 2021-07-23-1 which I think was one of those version where the install system of SC was updated.

How'd you install SC originally? 
Perhaps `pip install -U sickchill` after shutting down SC will work for you?
Or do the 4 steps as identified above. I'm no expert on debian install so these are only suggestions.

**Comment by BUZZ2K** [comment]
Hi, 
thanks for your help. You'r right, i used the pip install.

I stopped sickchill service and then run "sudo pip install -U sickchill" and i got : 

debian@vps-xxxxxxxx:~$ sudo pip install -U sickchill
Collecting sickchill
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement sickchill (from versions: )
No matching distribution found for sickchill

i did an apt-get update and upgrade and retried and then got : 

debian@vps-xxxxxxxx:~$ sudo pip install -U sickchill
Collecting sickchill
  Could not find a version that satisfies the requirement sickchill (from versions: )
No matching distribution found for sickchill

**Comment by BUZZ2K** [comment]
I've seen in another post that with this error i should upgrade pip.

I did.

Now, if i try pip install -U sickchill, i got an error because of my python version.

pip uses python 2.7.16 even if i have 3.7.3 installed also.

I remember a function to force pip to use a specific version of python. I'll try to find this and retry

**Comment by BUZZ2K** [comment]
updated python
updated pip

install of sickchill launched and end as a success but as i started sickchill service again, it seems to have launched the old version of sickchill

**Comment by BUZZ2K** [comment]
I have found an old issue where i reinstalled sickchill : https://github.com/SickChill/SickChill/issues/7401

I this issue i used : 

```
sudo apt install python3.8
python3.8 -m venv /opt/sickchill-env

/opt/sickchill-env/bin/pip install sickchill
```

And here is the content of my service file : 

```
[Unit]
Description=SickChill Daemon
Wants=network-online.target
After=network-online.target

[Service]
Type=forking
User=debian
Group=debian

GuessMainPID=no
#PIDFile=/run/sickchill/sickchill.pid
ExecStart=/opt/sickchill-env/bin/python /opt/sickchill-env/bin/SickChill.py -q --daemon --nolaunch --datadir=/home/debian/sickchill
#ExecReload=/bin/sh -c "/bin/kill -s HUP $(/bin/cat /run/sickchill/sickchill.pid)"
#ExecStop=/bin/sh -c "/bin/kill -s TERM $(/bin/cat /run/sickchill/sickchill.pid)"
#TimeoutSec=300

[Install]
WantedBy=multi-user.target
```

i see that i have specified a datadir. Which could explain why when i reinstall, it doesnt load the "good" sickchill.

When i use pip install -U sickchill, where does it install sickchill ? i didn't found

**Comment by BKSteve** [comment]
I'd suggest uninstall, go track down any folders and clean out all SickChill or predecessors and make sure you pip3 if you have Python2.

**Comment by miigotu** [comment]
`pip3 install -U sickchill`

**Comment by sgerlach** [comment]
Hi. I'm running into this same issue with PIP install for the last few releases. I currently have installed
` SickChill Info:
Install: pip
Version: v2022.08.15
Database Version: 44.2
`
After doing a `service sickchill stop; pip install -U sickchill; service sickchill start`, I always get a 404 in the log looking for the database migration util (I'm assuming)

> 2022-08-24 09:40:09 INFO :: CHECKVERSION :: Request failed: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/SickChill/SickChill/v2022.08.22-None/sickchill/oldbeard/databases/main.py (HTTPError)

My work around has been

1. backup config
2. stop service
3. pip uninstall sickchill
4. rm -rf {the data dir}
5. pip install sickchill
6. service start sickchill
7. restore config

this has previously work until today.

Is that database file supposed to be on github and if not, why is the update routine trying to fetch it, especially when it's installed...?
`/usr/local/lib/python3.8/site-packages/sickchill/oldbeard/databases # ls -la
total 76
-rw-r--r--  1 root  wheel     47 Aug 24 09:33 __init__.py
drwxr-xr-x  2 root  wheel      7 Aug 24 09:33 __pycache__
drwxr-xr-x  3 root  wheel      8 Aug 24 09:33 .
drwxr-xr-x  9 root  wheel     53 Aug 24 09:33 ..
-rw-r--r--  1 root  wheel   3599 Aug 24 09:33 cache.py
-rw-r--r--  1 root  wheel    939 Aug 24 09:33 failed.py
-rw-r--r--  1 root  wheel  16594 Aug 24 09:33 main.py
-rw-r--r--  1 root  wheel   6306 Aug 24 09:33 movie.py`

**Comment by BKSteve** [comment]
First thing to consider is your system, do you have Python 2 installed? 
If so you should probably use `pip3 install -U sickchill` as pip3 will force Python 3 use.

There's something messy with your installation and configuration as the `main.py` is accessible from https://raw.githubusercontent.com/SickChill/SickChill/2022.8.22/sickchill/oldbeard/databases/main.py 

Q. after the uninstall and `rm -rf` what's left in the `/usr/local/lib/python3.8/site-packages/sickchill` folder?
Maybe you also need to totally wipe sickchill folder with an `rm -rf /usr/local/lib/python3.8/site-packages/sickchill` before `pip3 ...`

**Comment by miigotu** [comment]
The pip updater is still in it's infancy. Just turn off auto updates if you want to avoid a log line, or ignore the error, and `pip3 install -U sickchill` to do the update. 

The bug is the updater is expecting a patch level when constructing the path to the database upgrade check file on GitHub, and when it is None it should be leaving that -None out of the string. We have to check the new version before upgrade to make sure it's not going to break your database, in which case we defer the update and require you to do it manually so you can avoid a broken system.
