### ISSUE TITLE
Fails to start if O/S python is upgraded newer than .venv

### ISSUE THREAD

**Issue by brianjmurrell** [SickChill/SickChill#7721]
Branch/Commit: 01020f3636d01535f60b83464d8127ea0efabfc7
OS: Fedora 35
Browser: N/A
What you did: Upgraded from Fedora 34
What happened: SickChill fails to start
What you expected: SickChill should start
Logs: N/A

When an existing installation of SickChill, complete with a `.venv` that was created on a previous version of an O/S is run on an upgraded version, it fails to start.  That is because the `.venv`'s `bin/python` symlink(s) points at the O/S provided python binary from before the upgrade.

```
$ ls -l .venv/bin/python*
lrwxrwxrwx. 1 brian brian    18 Jul 12 19:44 .venv/bin/python -> /usr/bin/python3.9
lrwxrwxrwx. 1 brian brian     6 Jul 12 19:44 .venv/bin/python3 -> python
lrwxrwxrwx. 1 brian brian     6 Jul 12 19:44 .venv/bin/python3.9 -> python

$ ls -l /usr/bin/python*
lrwxrwxrwx. 1 root  root      9 Oct  4 18:36 /usr/bin/python -> ./python3
lrwxrwxrwx. 1 root  root     10 Oct  4 18:10 /usr/bin/python3 -> python3.10
-rwxr-xr-x. 1 root  root  15944 Oct  4 18:10 /usr/bin/python3.10
-rwxr-xr-x. 1 root  root     62 Oct  4 18:10 /usr/bin/python3.10-config
-rwxr-xr-x. 1 root  root  15944 Oct  4 18:10 /usr/bin/python3.10d
-rwxr-xr-x. 1 root  root     63 Oct  4 18:10 /usr/bin/python3.10d-config
-rwxr-xr-x. 1 root  root   3588 Oct  4 17:59 /usr/bin/python3.10d-x86_64-config
-rwxr-xr-x. 1 root  root   3595 Oct  4 18:02 /usr/bin/python3.10-x86_64-config
lrwxrwxrwx. 1 root  root     17 Oct  4 18:10 /usr/bin/python3-config -> python3.10-config
lrwxrwxrwx. 1 root  root     20 Oct  4 18:10 /usr/bin/python3-debug -> /usr/bin/python3.10d
lrwxrwxrwx. 1 root  root     16 Oct  4 18:10 /usr/bin/python-config -> ./python3-config
lrwxrwxrwx. 1 root  root     15 Oct  4 18:10 /usr/bin/python-debug -> ./python3-debug
```

Trying to run with the python outside of the `.venv` doesn't even work:

```
$ python3 SickChill.py
Checking poetry
Can write to /home/brian/.local/lib/python3.10/site-packages: False
Can write to /usr/local/lib64/python3.10/site-packages: False
Current environment is not writable!
locations_to_check: [PosixPath('/net/server/src/SickChill/.venv/bin/python3.10'), PosixPath('/net/server/src/SickChill/.venv/bin/python3.10'), PosixPath('/net/server/src/SickChill/.venv/Scripts/python3.10')]
Something weird happend when creating the virtualenv, Could not find the bin dir or executable in /net/server/src/SickChill/.venv. Exiting
```

because as you can see `make_virtualenv_and_rerunmake_virtualenv_and_rerun()` is trying to also find the new version of python based on https://github.com/SickChill/SickChill/blob/01020f3636d01535f60b83464d8127ea0efabfc7/sickchill/init_helpers.py#L356 I would guess.

Ultimately, the `.venv` is no longer valid/current and needs to be updated.  SickChill should probably be trying to do this in `make_virtualenv_and_rerun()`, yes?

**Comment by brianjmurrell** [comment]
NOT STALE

**Comment by brianjmurrell** [comment]
Not stale.

**Comment by miigotu** [comment]
Run it with the full path to the bin. BTW, just because you have python 3.11 doesn't mean you should remove python3.10 for example, because of exactly these kind of issues. SC can't control if you remove a base interpreter, so you could dnf install python3.10 and fix this issue. Not all python3 versions are compatible, and assuming a python3.10 venv would work if you just used the 3.11 executable is incorrect. The libraries and byte code are compiled for that minor version of the interpretor. Sort of like trying to run something that depends on libc with a different version of libc.

Sorry, but there is nothing I can do about this. In debian/Ubuntu I would `apt-mark manual python3.10` so updates to the OS would not remove my dependency.
