### ISSUE TITLE
Question, not a bug

### ISSUE THREAD

**Issue by LapinFou** [SickChill/SickChill#7723]
Sorry to ask the question on GitHub.
SickChill is running on my Synology NAS (916+, DSM6).

I'm bit lost; some issue occurred with latest updates.
With the latest SickChill package (Synocommunity), everything seems stable again.
Thanks to all contributors.
However, my SickChill seems to be stick to the version _v2021.07.14-3_
When I click the update button, I got a message saying everything is up-to-date.
However on the Git, it seems latest stable version are _2021.11.xx_

So, my question, _v2021.07.14-3_ on NAS Synology is the correct version? Or something went wrong and I need to do something to upgrade to the latest current version?

**Comment by BKSteve** [comment]
No. You should be at v2021.11.10 should be the one on your DSM.
What information is shown in `Package Centre` for SickChill?
Here's what mine shows,
![image](https://user-images.githubusercontent.com/10173496/144212663-d34c2498-c5b6-4c4d-bcf7-2f03727c5665.png)

You may need to make a backup, uninstall and install new download from SynoCommunity or manually see #7364 first post link.

**Comment by LapinFou** [comment]
@BKSteve 
Thanks again for helping Syno users. 👍

Here is the version installed (DSM6):
![image](https://user-images.githubusercontent.com/1685030/144221900-2afce902-1afd-4237-8a3a-8e757e82af43.png) ![image](https://user-images.githubusercontent.com/1685030/144222520-ba812935-ab77-46d4-93d4-ca93e446b654.png)

In SickChill, here are the information available from the _Changelog_ tab:
![image](https://user-images.githubusercontent.com/1685030/144222236-9f8a8212-5714-4a40-b62e-8f3e67355237.png)

I will try to backup/uninstall/reinstall SickChill when back home tonight.

**Comment by LapinFou** [comment]
Here are the information from the _Help & Info_ 

![image](https://user-images.githubusercontent.com/1685030/144223476-b6fb6d1b-dd0e-4d49-9fae-e9cffc9e0d85.png)

**Comment by BKSteve** [comment]
Hash 01020f3636d01535f60b83464d8127ea0efabfc7
Is correct as current master

**Comment by LapinFou** [comment]
Hooooo, I see 😂
I didn't think to check that → https://github.com/SickChill/SickChill/commit/01020f3636d01535f60b83464d8127ea0efabfc7
Thanks a lot for your help! 🤩
