### ISSUE TITLE
blankrefer redirection is broken

### ISSUE THREAD

**Issue by LapinFou** [SickChill/SickChill#7726]
In the **http://SICKCHILL_IP:Port/config/** page (_Help & Info_), all links pointing to GitHub are broken.
There is a redirection through _blankrefer.com_ which doesn't exist anymore.

**Comment by BKSteve** [comment]
backlink protection via anonymizer service, must end in "?" (default: https://blankrefer.com/? )

This can be controlled by you in `Settings > General Configuration > Advanced Settings > Anonymous redirect`
So change it to something else to resolve your issue. 

The fix in `develop` changes it to `https://anonym.to/?`
#7690 #7678

**Comment by LapinFou** [comment]
Oups.... 😮
I should have use the search button before opening a ticket.
Sorry for that.. 😓
