### ISSUE TITLE
sickchill freezes on loading the Formula 1 as a series because of the amount of seasons/episodes

### ISSUE THREAD

**Issue by FGOD1983** [SickChill/SickChill#7744]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master/01020f3636d01535f60b83464d8127ea0efabfc7
OS: Ubuntu 20.04
Browser: Chrome
What you did: Open the Formula 1 page
What happened: freezes due to having to load too much at once (too many seasons/episodes to load data for)
What you expected: smooth navigations on the website, maybe use pagination when there are soo many episodes/seasons to load
Logs:

**Comment by BKSteve** [comment]
The initial load of all the episodes takes theTVDB a long time to feed them to SC through their API. (about 16 minutes)
Once these are all loaded and set in the database the show displays relatively quickly.
![image](https://user-images.githubusercontent.com/10173496/145674464-32b8fa9a-835a-4135-8e7d-03db67078d05.png)

**Comment by FGOD1983** [comment]
So I have to leave it open for 20 minutes and then relax the page to see what happens?

**Comment by BKSteve** [comment]
SC should load each and every episode. But it takes time, then refresh the page. 
If you run debug logging on save and restart then you can follow the progress in the log viewer on debugging selection. 
But that said SC should load all these episodes in the background and set their status as it gets each episode info from theTVDB. But the API doesn't always play nice and May take longer

**Comment by FGOD1983** [comment]
even after a refresh in the mass update settings it is still massively slow to the point I can't click anything and Chrome is giving me a wait/termintate page error...
