### ISSUE TITLE
[APP SUBMITTED]: Could not find table of torrents

### ISSUE THREAD

**Issue by POgli** [SickChill/SickChill#7746]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19044-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2021.11.7
No Log available with ERRORS:
### ERROR
```
Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kurt2x** [comment]
### INFO
Python Version: **3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]**
Operating System: **Linux-5.15.0-41-generic-x86_64-with-glibc2.29**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5
Link to Log: https://gist.github.com/997e3d5a5c8ded87b3394b8b7e404d7b
### ERROR
```
Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kurt2x** [comment]
### INFO
Python Version: **3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]**
Operating System: **Linux-5.15.0-41-generic-x86_64-with-glibc2.29**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5
Link to Log: https://gist.github.com/9ea981d6ca52c584df714bcd371c567c
### ERROR
```
Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ServalNator** [comment]
### INFO
Python Version: **3.11.5 (main, Sep  7 2023, 00:07:27) [GCC 8.5.0]**
Operating System: **Linux-4.4.180+-x86_64-with-glibc2.26**
Locale: None
Version: **2023.6.27**
Link to Log: https://gist.github.com/ServalNator/49bfcd8632e2d8526eb5e288da26ec9b
### ERROR
```
Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ServalNator** [comment]
### INFO
Python Version: **3.11.5 (main, Sep  7 2023, 00:07:27) [GCC 8.5.0]**
Operating System: **Linux-4.4.180+-x86_64-with-glibc2.26**
Locale: None
Version: **2023.6.27**
Link to Log: https://gist.github.com/ServalNator/19fd9ba7fe4b6a9854f707397125e6a9
### ERROR
```
Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ServalNator** [comment]
### INFO
Python Version: **3.11.5 (main, Sep  7 2023, 00:07:27) [GCC 8.5.0]**
Operating System: **Linux-4.4.180+-x86_64-with-glibc2.26**
Locale: None
Version: **2023.6.27**
Link to Log: https://gist.github.com/ServalNator/1858108a9f143ae524d6be0010337b39
### ERROR
```
Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by canepan** [comment]
### INFO
Python Version: **3.11.5 (main, Sep  6 2023, 23:39:45) [GCC 8.5.0]**
Operating System: **Linux-3.2.101-i686-with-glibc2.26**
Locale: None
Version: **2023.6.27**
No Log available with ERRORS:
### ERROR
```
Could not find table of torrents
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
