### ISSUE TITLE
failing to start, opensuse tumbleweed

### ISSUE THREAD

**Issue by mgaulton** [SickChill/SickChill#7762]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: github master fresh pull
OS: OpenSuse Tumbleweed
Browser: n/a
What you did: noted that software wasn't starting, deleted .venv and started
 python 3.8 and 3.9, neither worked.
What happened: Fails to start with errors
What you expected: Software to rebuild .venv and start
Logs:
```
hecking poetry
Can write to /usr/lib64/python3.8/site-packages: True
Can write to /root/.local/lib/python3.8/site-packages: True
We always run from virtualenv when running from source
Because of the above errors, we will try creating a new virtualenvironment in /opt/SickBeard-tvrage/.venv
Created new virtualenvironment in /opt/SickBeard-tvrage/.venv using venv module!
Restarting SickChill with ['/opt/SickBeard-tvrage/.venv/bin/python3', './SickChill.py']
Checking poetry
Can write to /root/.local/lib/python3.8/site-packages: True
Can write to /opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages: True
pip installed: True
pip args: /opt/SickBeard-tvrage/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
poetry installed: True
/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/setuptools/_distutils/util.py", line 258, in subst_vars
    return _subst_compat(s).format_map(lookup)
KeyError: 'platsubdir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/poetry/__main__.py", line 5, in <module>
    from .console import main
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/poetry/repositories/pypi_repository.py", line 33, in <module>
    from ..inspection.info import PackageInfo
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/poetry/inspection/info.py", line 25, in <module>
    from poetry.utils.env import EnvCommandError
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/poetry/utils/env.py", line 23, in <module>
    import virtualenv
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/virtualenv/run/__init__.py", line 14, in <module>
    from .plugin.creators import CreatorSelector
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/virtualenv/run/plugin/creators.py", line 6, in <module>
    from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>
    from virtualenv.create.creator import Creator
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/virtualenv/create/creator.py", line 15, in <module>
    from virtualenv.discovery.cached_py_info import LogCmd
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/virtualenv/discovery/cached_py_info.py", line 23, in <module>
    _CACHE[Path(sys.executable)] = PythonInfo()
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/virtualenv/discovery/py_info.py", line 86, in __init__
    self.distutils_install = {u(k): u(v) for k, v in self._distutils_install().items()}
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/virtualenv/discovery/py_info.py", line 157, in _distutils_install
    i.finalize_options()
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/setuptools/command/install.py", line 45, in finalize_options
    orig.install.finalize_options(self)
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/setuptools/_distutils/command/install.py", line 422, in finalize_options
    self.expand_dirs()
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/setuptools/_distutils/command/install.py", line 582, in expand_dirs
    self._expand_attrs(['install_purelib', 'install_platlib',
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/setuptools/_distutils/command/install.py", line 572, in _expand_attrs
    val = subst_vars(val, self.config_vars)
  File "/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/setuptools/_distutils/util.py", line 260, in subst_vars
    raise ValueError(f"invalid variable {var}")
ValueError: invalid variable 'platsubdir'
Unable to install to the existing virtual environment located at /opt/SickBeard-tvrage/.venv
Please check the permissions, and that it does not include global site packages
```

**Comment by mgaulton** [comment]
reattempt this morning looks different.

`vpnuser@server6:/opt/SickBeard-tvrage> rm -rf .venv
vpnuser@server6:/opt/SickBeard-tvrage> python3 SickChill.py --data=/opt/SBconfig
Checking poetry
Can write to /home/vpnuser/.local/lib/python3.8/site-packages: True
Can write to /usr/lib64/python3.8/site-packages: False
We always run from virtualenv when running from source
Because of the above errors, we will try creating a new virtualenvironment in /opt/SickBeard-tvrage/.venv
Created new virtualenvironment in /opt/SickBeard-tvrage/.venv using venv module!
Restarting SickChill with ['/opt/SickBeard-tvrage/.venv/bin/python3', 'SickChill.py', '--data=/opt/SBconfig']
Checking poetry
Can write to /opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages: True
Can write to /home/vpnuser/.local/lib/python3.8/site-packages: True
pip installed: True
pip args: /opt/SickBeard-tvrage/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
poetry installed: True
pip args: /opt/SickBeard-tvrage/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU appdirs==1.4.4 babelfish==0.6.0; python_version >= "3.6" and python_version < "4.0" backports.zoneinfo==0.2.1; python_version < "3.9" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") beautifulsoup4==4.10.0; python_full_version > "3.0.0" beekeeper-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" bencode.py==4.0.0 cachecontrol==0.12.10; python_version >= "3.6" certifi==2021.10.8; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" cffi==1.15.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" chardet==4.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") charset-normalizer==2.0.7; python_full_version >= "3.6.0" and python_version >= "3.6" click==8.0.3; python_version >= "3.6" cloudscraper==1.2.58 colorama==0.4.4; python_version >= "3.6" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.6" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==35.0.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" decorator==5.1.0; python_version >= "3.6" deluge-client==1.9.0 deprecated==1.2.13; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.4; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.8; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.2; python_version >= "3" and python_full_version < "3.0.0" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") or python_version >= "3" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") and python_full_version >= "3.5.0" guessit==3.4.2 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.20.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") idna==3.3; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" ifaddr==0.1.7 imagesize==1.3.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2021.4.18 importlib-metadata==4.8.2; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") importlib-resources==5.4.0; python_version >= "3.6" and python_version < "3.7" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.3.1 kodipydent-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" lxml==4.6.4; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.1.5; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") markdown2==2.4.1; python_version >= "3.5" and python_version < "4" markupsafe==2.0.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" msgpack==1.0.2; python_version >= "3.6" new-rtorrent-python==1.0.1a0 oauthlib==3.1.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==21.2; python_version >= "3.6" pbr==5.7.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.21; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.3.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.4.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pynma==1.0 pyopenssl==21.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") pyparsing==2.4.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==5.0.2; python_version >= "3.6" python-twitter==3.5 python3-fanart==2.0.0 pytz-deprecation-shim==0.1.0.post0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" pytz==2021.3 qbittorrent-api==2021.8.23 rarfile==4.0 rebulk==3.1.0 requests-oauthlib==1.3.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests-toolbelt==0.9.1 requests==2.26.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") send2trash==1.8.0 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" soupsieve==2.3; python_version >= "3.6" and python_full_version > "3.0.0" sqlalchemy==1.4.26; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.5.0; python_version >= "3.6" subliminal==2.1.0 text-unidecode==1.3; python_version >= "3.6" timeago==1.0.15 tmdbsimple==2.8.0 tornado==6.1; python_version >= "3.5" tus.py==1.3.4 tvdbsimple==1.0.6 typing-extensions==3.10.0.2; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") tzdata==2021.5; platform_system == "Windows" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") tzlocal==4.1; python_version >= "3.6" unidecode==1.3.2; python_version >= "3.5" urllib3==1.26.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version < "4" and python_version >= "3.6" validators==0.18.2; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.13.3; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" xmltodict==0.12.0; python_full_version >= "3.6.2" and python_version < "4" zipp==3.6.0; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") /opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecation   warnings.warn(
Command result: ERROR: Invalid requirement: '/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecation'
Hint: It looks like a path. File '/opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecation' does not exist.

Trying user site-packages
Command result: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

Traceback (most recent call last):
  File "SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/SickBeard-tvrage/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/SickBeard-tvrage/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/SickBeard-tvrage/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/opt/SickBeard-tvrage/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
ModuleNotFoundError: No module named 'github'
`

**Comment by BKSteve** [comment]
> /opt/SickBeard-tvrage/.venv/lib64/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecation warnings.warn(

Look at #7767 it's probably same issue

**Comment by mgaulton** [comment]
Apologies, I message up the code quoting.
I ended up working around it using pipx, sorry for the lack of reply.
