### ISSUE TITLE
[YggTorrent] :: Unable to connect to provider

### ISSUE THREAD

**Issue by dokho1984** [SickChill/SickChill#7765]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/01020f3636d01535f60b83464d8127ea0efabfc7
OS: Debian 11
Browser: Chrome
What you did: nothing
What happened: cannot connect to yggtorrent
What you expected: SichChill can connect to yggtorrent and search for new shows.
Logs:
```
2021-12-27 03:20:12 WARNING :: SEARCHQUEUE-BACKLOG-361315 :: [YggTorrent] :: Unable to connect to provider
2021-12-27 03:20:12 INFO :: SEARCHQUEUE-BACKLOG-361315 :: [YggTorrent] :: Request failed: Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version. ()
```

**Comment by dokho1984** [comment]
Hello,
Thanks in advance for your help on this issue.
Regards,
Julien.

**Comment by dokho1984** [comment]
I tried to create a RSS search provider but the rss website use cloudflare too.

**Comment by BKSteve** [comment]
refer #7264 
miigotu comment [https://github.com/SickChill/SickChill/issues/7264#issuecomment-879145520](https://github.com/SickChill/SickChill/issues/7264#issuecomment-879145520)
