### ISSUE TITLE
Sickchill exits with "install.py:34: SetuptoolsDeprecation' does not exist."

### ISSUE THREAD

**Issue by cyphher** [SickChill/SickChill#7767]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master / latest

OS: Linux  on Raspberry Pi (Linux raspberrypi 5.10.63-v8+ #1488 SMP PREEMPT Thu Nov 18 16:16:16 GMT 2021 aarch64 GNU/Linux)

Browser: NA
What you did: Fresh install of Bullseye 64bits raspi os
What happened: After a fresh install Sickchill extis with an error "SetuptoolsDeprecation' does not exist."
What you expected: Sickchill to start
Logs:
```
Checking poetry
Can write to /usr/local/lib/python3.9/dist-packages: False
Can write to /home/pi/.local/lib/python3.9/site-packages: True
We always run from virtualenv when running from source
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.9', './SickChill.py']
Checking poetry
Can write to /opt/sickchill/.venv/lib/python3.9/site-packages: True
Can write to /home/pi/.local/lib/python3.9/site-packages: True
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
poetry installed: True
pip args: /opt/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU /opt/sickchill/.venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecation   warnings.warn( appdirs==1.4.4 babelfish==0.6.0; 

<SNIP>

Command result: ERROR: Invalid requirement: '/opt/sickchill/.venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecation'
Hint: It looks like a path. File '/opt/sickchill/.venv/lib/python3.9/site-packages/setuptools/command/install.py:34: 

Trying user site-packages
Command result: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

Traceback (most recent call last):
  File "/opt/sickchill/./SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/opt/sickchill/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
ModuleNotFoundError: No module named 'github'
```
I've tried a fix I've used before with the 32bit OS:

".venv/bin/python3 -m poetry lock --no-update -vvv"

But this gives almost the same error:

/opt/sickchill/.venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Using virtualenv: /opt/sickchill/.venv

**Comment by BKSteve** [comment]
This is 2 parts.
1.
What version is your setuptools? latest 60.1.1?
This might be the reason [https://github.com/pypa/setuptools/issues/2979](https://github.com/pypa/setuptools/issues/2979)
[https://setuptools.pypa.io/en/latest/history.html#v58-0-0](https://setuptools.pypa.io/en/latest/history.html#v58-0-0)

2.
Can you put back the `<SNIP>` part so I can see the full line. As once before there was a similar issue #7451 

The `init_helpers.py` is the code calling the installation and update of site packages and uses `pip` and `poetry` 

>398 result, output = subprocess.getstatusoutput(
>399 f"cd {pyproject_path.parent} && {sys.executable} -m **poetry** export -f requirements.txt --without-hashes"
>400 )
>401 if result == 0:  # Ok
>402 pip_install(output)

**Comment by cyphher** [comment]
> /opt/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU poetry
> /opt/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools
> /opt/sickchill/.venv/bin/python3.9 -m poetry export -f requirements.txt --without-hashes
> 
> /opt/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU appdirs==1.4.4

I've issued these commands and the full output starting sickchill is:

Checking poetry
Can write to /home/pi/.local/lib/python3.9/site-packages: True
Can write to /usr/local/lib/python3.9/dist-packages: False
We always run from virtualenv when running from source
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.9', './SickChill.py']
Checking poetry
Can write to /home/pi/.local/lib/python3.9/site-packages: True
Can write to /opt/sickchill/.venv/lib/python3.9/site-packages: True
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
poetry installed: True
pip args: /opt/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU /opt/sickchill/.venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecation   warnings.warn( appdirs==1.4.4 babelfish==0.6.0; python_version >= "3.6" and python_version < "4.0" backports.zoneinfo==0.2.1; python_version < "3.9" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") beautifulsoup4==4.10.0; python_full_version > "3.0.0" beekeeper-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" bencode.py==4.0.0 cachecontrol==0.12.10; python_version >= "3.6" certifi==2021.10.8; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" cffi==1.15.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" chardet==4.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") charset-normalizer==2.0.7; python_full_version >= "3.6.0" and python_version >= "3.6" click==8.0.3; python_version >= "3.6" cloudscraper==1.2.58 colorama==0.4.4; python_version >= "3.6" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.6" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==35.0.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" decorator==5.1.0; python_version >= "3.6" deluge-client==1.9.0 deprecated==1.2.13; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.4; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.8; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.2; python_version >= "3" and python_full_version < "3.0.0" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") or python_version >= "3" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") and python_full_version >= "3.5.0" guessit==3.4.2 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.20.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") idna==3.3; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" ifaddr==0.1.7 imagesize==1.3.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2021.4.18 importlib-metadata==4.8.2; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") importlib-resources==5.4.0; python_version >= "3.6" and python_version < "3.7" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.3.1 kodipydent-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" lxml==4.6.4; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.1.5; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") markdown2==2.4.1; python_version >= "3.5" and python_version < "4" markupsafe==2.0.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" msgpack==1.0.2; python_version >= "3.6" new-rtorrent-python==1.0.1a0 oauthlib==3.1.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==21.2; python_version >= "3.6" pbr==5.7.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.21; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.3.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.4.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pynma==1.0 pyopenssl==21.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") pyparsing==2.4.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==5.0.2; python_version >= "3.6" python-twitter==3.5 python3-fanart==2.0.0 pytz-deprecation-shim==0.1.0.post0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" pytz==2021.3 qbittorrent-api==2021.8.23 rarfile==4.0 rebulk==3.1.0 requests-oauthlib==1.3.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests-toolbelt==0.9.1 requests==2.26.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") send2trash==1.8.0 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" soupsieve==2.3; python_version >= "3.6" and python_full_version > "3.0.0" sqlalchemy==1.4.26; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.5.0; python_version >= "3.6" subliminal==2.1.0 text-unidecode==1.3; python_version >= "3.6" timeago==1.0.15 tmdbsimple==2.8.0 tornado==6.1; python_version >= "3.5" tus.py==1.3.4 tvdbsimple==1.0.6 typing-extensions==3.10.0.2; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") tzdata==2021.5; platform_system == "Windows" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") tzlocal==4.1; python_version >= "3.6" unidecode==1.3.2; python_version >= "3.5" urllib3==1.26.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version < "4" and python_version >= "3.6" validators==0.18.2; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.13.3; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" xmltodict==0.12.0; python_full_version >= "3.6.2" and python_version < "4" zipp==3.6.0; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6")
Command result: ERROR: Invalid requirement: '/opt/sickchill/.venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecation'
Hint: It looks like a path. File '/opt/sickchill/.venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecation' does not exist.

Trying user site-packages
Command result: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

Traceback (most recent call last):
  File "/opt/sickchill/./SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/opt/sickchill/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
ModuleNotFoundError: No module named 'github'

**Comment by BKSteve** [comment]
Whilst you tested that, I did a test with my DSM system.
It still runs but it kicks the same error.

```
 /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data
Checking poetry
Can write to /volume1/@appstore/sickchill/env/lib/python3.8/site-packages: True
Can write to /var/packages/sickchill/target/.local/lib/python3.8/site-packages: False
pip installed: True
Found wheelhouse dir at /volume1/@appstore/sickchill/share/wheelhouse
pip args: /volume1/@appstore/sickchill/env/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU -f/volume1/@appstore/sickchill/share/wheelhouse setuptools poetry wheel
poetry installed: True
check installed poetry
Found wheelhouse dir at /volume1/@appstore/sickchill/share/wheelhouse
pip args: /volume1/@appstore/sickchill/env/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU -f/volume1/@appstore/sickchill/share/wheelhouse importlib-metadata==4.8.2; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") packaging==21.2; python_version >= "3.6" typing-extensions==3.10.0.2; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") /volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.   warnings.warn(
Command result: ERROR: Invalid requirement: '/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.'
Hint: It looks like a path. File '/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.' does not exist.

Trying user site-packages
Command result: ERROR: Invalid requirement: '/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.'
Hint: It looks like a path. File '/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.' does not exist.
```

This looks like something is wrong with `setuptools` as when I do 
`/volume1/@appstore/sickchill/env/bin/python -m poetry export -f requirements.txt --without-hashes`
The first line is 
```
/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
```

**Comment by BKSteve** [comment]
I was working on something else in regard to loading packages and added some additional filter lines to clear these errors so it should load if you try the below.

1. cd to where init_helpers.py is `/opt/sickchill/sickchill/` ??
2. copy init_helpers.py to somewhere for safety.
3. `sudo curl -O https://raw.githubusercontent.com/BKSteve/SickChill/packages-update/sickchill/init_helpers.py`
4. start SC as normal.

**Comment by cyphher** [comment]
> I was working on something else in regard to loading packages and added some additional filter lines to clear these errors so it should load if you try the below.
> 
>     1. cd to where init_helpers.py is `/opt/sickchill/sickchill/` ??
> 
>     2. copy init_helpers.py to somewhere for safety.
> 
>     3. `sudo curl -O https://raw.githubusercontent.com/BKSteve/SickChill/packages-update/sickchill/init_helpers.py`
> 
>     4. start SC as normal.
> 
> 
> PS. This is definitely a `setuptools` >=60.0.0 problem and not SC but it can be worked around in SC.

Well, this does seem to do the trick! However, I guess once a new commit/upgrade is performed this problem will resurface again?

**Comment by BKSteve** [comment]
They should hopefully have fixed setuptools by then. I did add to one of their open issues

**Comment by BKSteve** [comment]
Issue closed as proper fix pull request.
New curl line in line with master rather than other coding I was doing.
`cd to where init_hlepers.py is`  
`sudo curl -O https://raw.githubusercontent.com/BKSteve/SickChill/poetry-export/sickchill/init_helpers.py`
