### ISSUE TITLE
All shows stuck with "This show is queued and awaiting an update.".

### ISSUE THREAD

**Issue by michaelosten** [SickChill/SickChill#7771]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 01020f3636d01535f60b83464d8127ea0efabfc7
Version: 2021.11.10
Database Version: 44.2
  Python Version:3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  SSL Version:OpenSSL 1.1.1f 31 Mar 2020
  OS:Linux-5.4.0-91-generic-x86_64-with-glibc2.29
  Locale:en_US.UTF-8

What happened: All shows display "This show is queued and awaiting an update.".
What you expected: Shows to be updated

**Comment by BKSteve** [comment]
These are all theTVDB and their API response related.
Restarting SC can often seem to resolve.
