### ISSUE TITLE
Long Delay Between Snatched & Downloaded

### ISSUE THREAD

**Issue by adit-s** [SickChill/SickChill#7782]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: v2021.07.14-3
OS: Docker Container
Browser: Not relavent, but Firefox
What you did: N/A
What happened: There is a long delay (approximately 4 hours) between an episode being snatched and post-processed to become downloaded even the file is in the Post Processing Dir. The post-processing interval is set to 10 min. I can see from the logs post-processing does run every 10 minutes, but for some reason, it doesn't process the downloaded file until later.
What you expected: Expect the post processing process to pick up and process the file as soon as it's available in the Post Processing Dir.
For the most recent event, the episode was snatched 1:01:46AM and successfully post-processesd at 5:05:55AM.
There were 24 post processing runs before the file was post processed. 
In the runs where it wasn't picked up, the logs simply show per the screen shots.

Logs:
```
PASTE LOGS HERE
```
![Screenshot_20220107_101714](https://user-images.githubusercontent.com/8761424/148565051-c4e36cf1-7e3a-4905-93c8-321d474f5f17.png)
![Screenshot_20220107_101839](https://user-images.githubusercontent.com/8761424/148565100-d4d43677-af5d-4116-a89d-7d018413a7a6.png)
![Screenshot_20220107_100512](https://user-images.githubusercontent.com/8761424/148565139-714327fa-0339-4271-a73b-4b0d0dab9a19.png)

**Comment by adit-s** [comment]
Update: I marked the episode as wanted and the same thing happened. The episode was snatched, the file was downloaded to the post process dir, but on the first run (when the file was already there) it did NOT post process it for some reason.
I then ran a manual post process and it did not pick up the file either.
I'll leave it and see when it is successfully post processed.

Very confusing. Why doesn't it pick it up and then at some later time (~4 hours later does)..
![Screenshot_20220107_104014](https://user-images.githubusercontent.com/8761424/148568364-049d71ba-5e39-49d4-9dc8-3bab2989eb89.png)
.

**Comment by adit-s** [comment]
Update: I'm running in Docker from image linuxserver/sickchill. 
So it looks like the mapping to /downloads is NOT refreshed after the file is downloaded. The /downloads directory still shows as empty. 
If I restart the container, the /downloads directory is updated and it works as it should. 
So the issue seems to be with the changes to the host /downloads directy not properly reflecting to the container /downloads directory.
Any ideas or suggestions? (or should this be raised with the container maintainer - linuxserver/sickchill?)

**Comment by kyuuk** [comment]
I guess that's more of a docker problem, i think you should see with the image maintainer

**Comment by adit-s** [comment]
So it looks like restarting the container "fixed" the issue. Any new downloaded files seem to be properly propogated to the container's /downloads directory - and as a result, post processed correctly.
