### ISSUE TITLE
Added show stuck in loading mode

### ISSUE THREAD

**Issue by mhoban** [SickChill/SickChill#7785]
Branch/Commit: master, 01020f3636d01535f60b83464d8127ea0efabfc7 
OS: Debian 9.13
Browser: Firefox 95
What you did: 
I added a show (Yellowjackets)

What happened: 
The show never fully added. It stayed stuck with the loading screen and never updated. I have the same error repeated over and over in the log (see below).

In addition, I'm experiencing the same issue as posted [here](https://github.com/SickChill/SickChill/issues/7771), although some of them also say "This show is queued to be refreshed"

What you expected:
The show to be added. 

The log section I pasted below repeats over and over.
Logs:
```
AA AttributeError: 'NoneType' object has no attribute 'id'
AA showObj = Show.find(settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "/media/sdz1/deadbilly/SickChill/sickchill/oldbeard/helpers.py", line 977, in get_show
AA TypeError: expected string or bytes-like object
AA return _compile(pattern, flags).match(string)
AA File "/media/sdz1/deadbilly/miniconda3/lib/python3.9/re.py", line 191, in match
AA if re.match(r"^t?t?\d{7,8}$", name) or re.match(r"^\d{6}$", name):
AA File "/media/sdz1/deadbilly/SickChill/sickchill/show/indexers/tvdb.py", line 110, in search
AA result = target(*args, **kwargs)
AA File "/media/sdz1/deadbilly/SickChill/sickchill/show/indexers/wrappers.py", line 25, in wrapper
```

**Comment by mhoban** [comment]
Well, I restarted the server and after some fussing around with "existing" shows, it seems to work now. Though this isn't the first time I've encountered a problem like this so it may still be worth leaving up here.

**Comment by BKSteve** [comment]
These are all theTVDB and their API response related.
Restarting can often seem to resolve.

**Comment by mhoban** [comment]
It seems like if this is a known issue, it might be useful to put more descriptive messaging in the log files.

**Comment by BKSteve** [comment]
No real point modifying code as expecting to move to a different indexer
