### ISSUE TITLE
Questions re Sickchill on synology

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#7788]
Hi,
I tried asking this question to the people making the synology package, but as I haven't gotten any response I'll try here.

I installed SC on my NAS, but I'm unable to log on. The default u/p doesn't work, and neither does any of the passwords I can think of that I might have used if I tried installing it before. I would prefer not to have to ssh into it, so...

Does anyone know which directories on the synology a previous SC installation might have left? Before I try the ssh approach (I'd need to know the dirs anyway to do that) I'd like to try to uninstall the service, delete any remnants, and then reinstalling it. If that doesn't work I can try the ssh approach.

Thanks!

**Comment by BKSteve** [comment]
You don't provide enough information. 
What DSM version?
What version of SC did you install? Latest 20211110-4?
Take a look in `discussions` section, most folders are listed under the Synology labeled items.

**Comment by Tiwas** [comment]
> You don't provide enough information. What DSM version? What version of SC did you install? Latest 20211110-4? Take a look in `discussions` section, most folders are listed under the Synology labeled items.
> 
> Uninstall first then a new install should allow you to set the user and password. If not then uninstall and ssh remove `/var/packages/sickchill`

Thanks. I didn't think the DSM version would be relevant, but...
DSM 6.2.4-25556 Update 2
SickChill: 20211110-4

I'll try to ssh into it and remove the folder. When I did the last install (there was no sickchill installed at the moment, but I cannot guarantee I haven't installed it at some point) I was unable to login, so didn't get a chance to set password.

**Comment by Tiwas** [comment]
@BKSteve Uninstalling, removing the directory and reinstalling seems to have fixed any issues. Thanks :)
