### ISSUE TITLE
Dereferer.org not working anymore - rendering all links on Sickchill useless.

### ISSUE THREAD

**Issue by ofirbb** [SickChill/SickChill#7794]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: cddc3c8c60f3f588ea56326a42727ffb12149428
OS: Windows
Browser: Chrome
What you did: Clicked any link in sickchill
What happened: Went to the default homepage of dereferer
What you expected: to get to the referenced URL
Logs:
```
PASTE LOGS HERE
```

**Comment by BKSteve** [comment]
https://github.com/SickChill/SickChill/issues/7718#issuecomment-980801393
