### ISSUE TITLE
Show List shows some shows after Ended instead of in dated order for Sort Next Episode

### ISSUE THREAD

**Issue by BCITMike** [SickChill/SickChill#7797]
Branch/Commit: pip/latest
OS: Alma Linux
What happened: Some new shows that start 01/20 or later are displayed after shows that have already ended.
What you expected: In Sort, Next Episode, ascending order display, I expect shows to be shown in order of next episode, followed by "Continuing", "Ended" and finally with "Upcoming". However, some shows are being displayed after the Ended shows instead of in dated order.

Example:
Top row of shows have next episode dates of 01/16 - 01/21 and continue for 3.5 rows in dated order until 04/17/22 and then shows "Continuing" for 7 rows followed by a single "Paused" show and then five "Ended". Here, I expect the end of the list, except there are 21 more shows starting from 01/18-02/21 and then lastly "Upcoming" shows.

Changing ascending/descending and layouts do not resort them back into ordered date.

**Comment by BKSteve** [comment]
Maybe some screen shots? I'm not deciphering what you've written.

**Comment by BCITMike** [comment]
> 
Top and bottom.

![image](https://user-images.githubusercontent.com/8147716/150280596-e71d2844-119c-4033-8992-de6f69d01677.png)
![image](https://user-images.githubusercontent.com/8147716/150280197-23099fdf-a14c-4821-bb7a-4edf57e24b07.png)

Just now, when I added "Children Ruin Everything", it initially appeared (without the poster) before "Single Drunk Female" and when refreshed (with poster loaded) it correctly appeared in the order for 1/26. So it's not every show that this happens to. /shrug

**Comment by BCITMike** [comment]
And now, without doing anything, Single Drunk Female is now showing in the correct location by sorted date:
![image](https://user-images.githubusercontent.com/8147716/150457281-d7d42b27-6aea-4b3d-9436-a8b242f5d97a.png)

**Comment by BKSteve** [comment]
Close? 
Did you have a restart in between?

**Comment by BCITMike** [comment]
> Close?
> Did you have a restart in between?

Well, its unknown why it gets added out of order. I don't know if the next show I'll add will get added to the top or bottom out of order. Presumably, the rest of the shows still our of order will show up at the top by March 31 based on their new episodes appearing. 

No restart that I can recall in recent memory but my history does show restarting sickchill several times.

**Comment by BKSteve** [comment]
A Glitch in the Matrix. I just had a look at mine in Poster and Next Episode order and also had a 31 Jan before 28 Jan show.

**Comment by BKSteve** [comment]
`Back Burner` minor inconsistency in only `Poster` view.

**Comment by miigotu** [comment]
Ended shows should be put at the end for sure. Ones that are just added will appear in an undetermined location until they are fully added on the backend (we don't know the dates yet at that point)

This is fixable in JS.
