### ISSUE TITLE
Episode naming not by year first released?

### ISSUE THREAD

**Issue by Manfred73** [SickChill/SickChill#7807]
Setting name pattern to "Season %0S/%S.N.(%Y).s%0Se%0E.%E.N" resulting in something like "Season 02/Show.Name.(2010).s02e03-04.Ep.Name.and.Ep.Name.2.ext"

I was hoping that %Y would be the year the show was first released (I also created the main folder of the show like this, e.g. "Lost in Space  (2021)".

But %Y is the year when the episode was aired.

I guess %CY is the year when postprocessing took place?

Is there also something which I can use in the episode naming to use the year of first release of the show?

**Comment by BKSteve** [comment]
These are the names in the `naming legend`
<html><body>


Show Name: | %SN | Show Name
-- | -- | --
  | %S.N | Show.Name
  | %S_N | Show_Name
Season Number: | %S | 2
  | %0S | 02
XEM Season Number: | %XS | 2
  | %0XS | 02
Episode Number: | %E | 3
  | %0E | 03
XEM Episode Number: | %XE | 3
  | %0XE | 03
Episode Name: | %EN | Episode Name
  | %E.N | Episode.Name
  | %E_N | Episode_Name
Air Date: | %M | 1
  | %D | 23
  | %Y | 2022
Post-Processing Date: | %CM | 1
  | %CD | 23
  | %CY | 2022
Quality: | %QN | 720p BluRay
  | %Q.N | 720p.BluRay
  | %Q_N | 720p_BluRay
Scene Quality: | %SQN | 720p HDTV x264
  | %SQ.N | 720p.HDTV.x264
  | %SQ_N | 720p_HDTV_x264
Release Name: | %RN | Show.Name.S02E03.HDTV.XviD-RLSGROUP
Release Group: | %RG | RLSGROUP
Release Type: | %RT | PROPER


</body>
</html>

**Comment by Manfred73** [comment]
So no option to set the year when it was first released then I guess?
