### ISSUE TITLE
Windows Post Processing fails with long path names

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#7809]
SickChill Info:
Install: pip
Version: v2021.11.10
Database Version: 44.2
  Python Version:3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
  SSL Version:OpenSSL 1.1.1k 25 Mar 2021
  OS:Windows-10-10.0.19042-SP0

Browser: Edge
What you did: Post-process manually
What happened:failed
What you expected:success

In NzbGet, the failure message indicated "could not find file"  (but the file existed).

In SC manual processing, merely returned a failure message.

But, the full pathname of the show was 290 characters.  When I shortened the pathname (by changing the name of the folder containing the show), SC manual post-processing then succeeded.

Is this behavior expected with long file paths?
Can it be mitigated by enabling Win32 long paths?

**Comment by miigotu** [comment]
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by ronrosenfeld** [comment]
@miigotu   Thanks. That's what I thought but wanted to check here first.
