### ISSUE TITLE
Information needed about "Unable to connect to provider"

### ISSUE THREAD

**Issue by rd1** [SickChill/SickChill#7811]
Branch/Commit: v2021.07.14-3
OS: Win10 x64
Browser: edge

What happened:  Everyday "Unable to connect to provider" 

What you expected: Which provider? there's no name.

Can't fix the problem if i don't know which provider!

SC used to show the name but an update changed that, over a year ago.

**Comment by BKSteve** [comment]
debug logging `on`? If debug is on it should be identified.

**Comment by FaiqH** [comment]
Odd that i get this as well and I am on version 20230627-8. It shows up when trying to connect to imdb.

**Comment by miigotu** [comment]
> Odd that i get this as well and I am on version 20230627-8. It shows up when trying to connect to imdb.

The lib that gets data from IMDb has been broken since March.
