### ISSUE TITLE
SickChill keeps messing up completed Cartoons

### ISSUE THREAD

**Issue by Schoepp23** [SickChill/SickChill#7833]
I have been having an issue for awhile and it's starting to get past the last nerve of my last nerve.  I have lot's of old cartoons and it's always the same ones generally, but something is going in and updating the show and jacking up the episodes naming convention.  It's shows like the following:

Hey Arnold!
Fairly Odd PArents
Voltron
The Adventures of Gummi Bears

In my case, every blue moon I believe that I have SickChill updating all shows, lets say it's 90 days.  At that point it breaks Cartoons and renames episodes, even tho I have started them from the beginning and made sure that they are the right episode.  I have the "pause this show (SickChill will not download episodes)", but that doesn't stop SickChill from updating and messing up the show.  Do we have a setting that can IGNORE any update or change to a show so that i can exclude these shows from being touched unless a manual update is selected?  Any assistance would be more than amazing!

Everything is updated to the most recent version

**Comment by Schoepp23** [comment]
![TV Show Mess Up](https://user-images.githubusercontent.com/15948053/151811822-ed6c3000-9920-4bc4-950e-167105111bb0.png)

Here is what is jut did over the weekend.  All of these shows were 100% downloaded and named correctly on Friday.

**Comment by miigotu** [comment]
Remove them from SC, there's no reason to have them in there if they are completed and never going to get an update. Cartoons didn't used to follow proper release standards.

**Comment by Schoepp23** [comment]
I can do that and that is completely fine.  I do want to ask just so I am covering my base.  Their is no setting that says "DO NOT TOUCH" this show right?  If not, that would be an awesome add on!
