### ISSUE TITLE
Update Error : Unable to retrieve new version 

### ISSUE THREAD

**Issue by KittyBB** [SickChill/SickChill#7847]
Hello 

I've been running SickChill in a container for a while now after the Synology DSM 7 update. 

I tried to install the new package available directly on my NAS and restored a backup from the container. 
Everything seems to be working fine except when I try to update sickchill

I get the following error 

_`2022-02-08 20:11:07 WARNING :: WEBSERVER-HOME_0 :: Unable to retrieve new version from https://github.com/SickChill/SickChill/tarball/pip, can't update 2022-02-08 20:11:07 INFO :: WEBSERVER-HOME_0 :: Request failed: 404 Client Error: Not Found for url: https://codeload.github.com/SickChill/SickChill/legacy.tar.gz/pip () 2022-02-08 20:11:06 INFO :: WEBSERVER-HOME_0 :: Downloading update from https://github.com/SickChill/SickChill/tarball/pip 2022-02-08 20:11:06 INFO :: WEBSERVER-HOME_0 :: Creating update folder /volume1/@appdata/sickchill/data/sc-update before extracting 2022-02-08 20:11:06 INFO :: WEBSERVER-HOME_0 :: Clearing out update folder /volume1/@appdata/sickchill/data/sc-update before extracting`_ 

Below the version on my container (the one the backup is from) 

**SickChill Info:**
Install: [pip](https://blankrefer.com/?https://pypi.org/project/sickchill/)
Version: [v2021.07.23-1](https://blankrefer.com/?https://github.com/SickChill/SickChill/releases/tag/v2021.07.23-1)
Database Version: 44.2
  **Python Version:** 3.8.10 (default, May 6 2021, 00:05:59) [GCC 10.2.1 20201203]
  SSL Version: OpenSSL 1.1.1k 25 Mar 2021
  OS: Linux-3.10.108-x86_64-with
  Locale: None.None

I tried to get the same information from the NAS Sickchill but I get a "fix me"  error : 

`Traceback (most recent call last): File /volume1/@appstore/sickchill/share/SickChill/sickchill/views/index.py:188, in async_call: return function(**kwargs) File /volume1/@appstore/sickchill/env/lib/python3.8/site-packages/tornado/web.py:1905, in wrapper: return method(self, *args, **kwargs) File /volume1/@appstore/sickchill/share/SickChill/sickchill/views/config/index.py:61, in index: sc_version = updater.updater.get_clean_version() AttributeError: 'SourceUpdateManager' object has no attribute 'get_clean_version'`

Thanks for your help

**Comment by miigotu** [comment]
Stop your sickchill (or the container) and edit config.ini, change `branch=pip` to `branch=master`. This is an artifact of moving from a pip install to non-pip install, and in the future i will check and fix this automatically in code.
