### ISSUE TITLE
[APP SUBMITTED]: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by StanESmith** [SickChill/SickChill#7848]
### INFO
Python Version: **3.8.10 (default, May  6 2021, 00:05:59) [GCC 10.2.1 20201203]**
Operating System: **Linux-5.13.19-3-pve-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@01020f3636d01535f60b83464d8127ea0efabfc7
Link to Log: https://gist.github.com/7a0e80730fa1237cb6b8b4f334428731
### ERROR
```
Exception while searching Speedcd. Error: object of type 'NoneType' has no len()
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Ataelos** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2023.6.27**
Link to Log: https://gist.github.com/Ataelos/93e800d03c0f8fac2414bff39cb0ddec
### ERROR
```
Exception while searching Speedcd. Error: object of type 'NoneType' has no len()
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
