### ISSUE TITLE
2160P formats not recognized as 4K.

### ISSUE THREAD

**Issue by crookedview** [SickChill/SickChill#7849]
Enable HEVC support in `settings->search settings` by checking `Allow downloading HEVC x265 releases`

_Originally posted by @miigotu in https://github.com/SickChill/SickChill/issues/5924#issuecomment-578458727_

Unfortunately the "Allow downloading HEVC x265 releases" option doesn't resolve the problem.

**Comment by miigotu** [comment]
It does. But do not open different issues for comments. Closed does not mean you can't comment on the original issue. Enable the debug log and you will see why it was ignored, or it does not match a proper release name. Series, season, episode, resolution, and codec are all required in the release name. Showname.S02E02.2160p.mkv for example is not enough information it would have to be "Showname.S02E02.2160p.h265.mkv" or similar to be valid.
