### ISSUE TITLE
[APP SUBMITTED]: Missing time zone for network: Sky Comedy. Check valid network is set in indexer (theTVDB) before filing issue.

### ISSUE THREAD

**Issue by RakeZim** [SickChill/SickChill#7856]
### INFO
Python Version: **3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]**
Operating System: **Linux-4.19.0-17-amd64-x86_64-with-debian-10.10**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@94f56b7e2c86655fc98d93e94be1a75e729d3969
No Log available with ERRORS:
### ERROR
```
Missing time zone for network: Sky Comedy. Check valid network is set in indexer (theTVDB) before filing issue.
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
#7231
