### ISSUE TITLE
Search result freeze

### ISSUE THREAD

**Issue by Navino16** [SickChill/SickChill#7861]
Branch/Commit: latest
OS: Linux/Docker (linuxserver)
Browser: Chrome
What you did: Search an existing show using search bar
What happened: The search append almost immediately but then during 20/30s I can't click on anything
What you expected: Being able to click on any result almost immediately
Logs:
```
Nothing relevant in logs even in browser logs (only some 404 about some networks images)
```

**Comment by Navino16** [comment]
Note that I have almost 700 shows in sickchill if it's an usefull information

**Comment by BKSteve** [comment]
Poster layout seems to have a couple of items not working properly #7797 too.

**Comment by miigotu** [comment]
I don't understand what you mean you can't click anything. It's a web page, in a browser.... We don't control the browser and clicking something in the browser should make a new request to the application.

**Comment by Navino16** [comment]
After enterring my search string, the result is displayed but after that if I click on a result or any other link, nothing append. I have to wait 20/30s before clicking on anything.
And during this "freeze", only sickchill doesn't work, any other web page are working perfectly.

**Comment by miigotu** [comment]
Because it's searching your providers... That's how manual search works.

**Comment by Navino16** [comment]
What do you mean by "It's searching your providers" ?
I'm talking about this search :
![image](https://user-images.githubusercontent.com/22234867/155533198-73f52b85-3f98-4c4f-8b14-e076562bfa78.png)

**Comment by miigotu** [comment]
In that case it's going to take a few seconds to query SC about 700 shows, access the name of each show, sort the results, and send a huge response back to the browser which does its own sorting and then updating the page via js.

**Comment by Navino16** [comment]
Okay thanks for your answer.
