### ISSUE TITLE
Problems restoring backup to synology nas

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#7882]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:latest
OS:synology DSM 6
Browser:
What you did:installed the package, updated to latest commit, imported my backup
What happened:Nothing. Seems to hang.
What you expected:
Logs:
```
tail -f sickchill.log
Fri Feb 18 20:23:04 CET 2022
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data
Writing PID: 15955 to /volume1/@appstore/sickchill/var/sickchill.pid
```
Nothing happens after this. Are there any troubleshooting steps I can try? I've checked the config.ini and it seems to have been imported fine, and debug=1. 

Seems the folder and children are owned by user sc-sickchill and group sickchill, but these are not present in the users or groups tables. Could this be the problem? 

Checking the process with ps -aux gives me the following
`sc-sick+  6697  7.2 12.5 1331780 127332 ?      Sl   20:43   0:20 /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data
`

I'm at a loss here and would greatly appreciate any help.

**Comment by BKSteve** [comment]
Did you try to update SC and restore at same time?

Do each separately. 
Update SC to latest. Restart. 
Restore backup. 
Don't try both at same time

**Comment by Tiwas** [comment]
> Did you try to update SC and restore at same time?
> 
> Do each separately. Update SC to latest. Restart. Restore backup. Don't try both at same time.
> 
> See discussion for ssh start strings

Thanks. I didn't update and restore at the same time, but https://github.com/SickChill/SickChill/discussions/7364 gave a workable solution :)
