### ISSUE TITLE
Should version match release?

### ISSUE THREAD

**Issue by BCITMike** [SickChill/SickChill#7892]
I just noticed that today, on Feb 20, 2022, there is a release `Release 2022.02.22` and when looking at the code changes, the version is `version = "2022.02.20"`.

Should the release have been 2022.02.20 to match the version or they are unrelated and just coincidental?  Doesn't seem intuitive to have them different, IMO.  My guess is a "too many 2's" typo.

**Comment by miigotu** [comment]
It's intended to be the same, but our release process currently is fragmented and a pain in the ass to keep it synced. There is already a project in process to improve that, but it is simply cosmetic.

**Comment by BCITMike** [comment]
What makes it a pain? I'd think 'the day of' is pretty straight forward with the only limitation being no multiple releases on the same day. And even then, I don't know if it would be a problem to add a 'b' to the end.

**Comment by miigotu** [comment]
It isn't just as simple as changing the version in code.... It's 6 different commands, 2 files manually edited, pushing to gh and pypi, manually making a release on gh, pypi, and dockerhub and some other shit. If one step is not done exactly right it gets out of sync. Like I said, if it's ever out of sync it is simply cosmetic, and we are working on code to handle the whole process in one step to avoid mistakes in the future.
