### ISSUE TITLE
Backlog Overview ... second page of result and further incorrectly formatted.

### ISSUE THREAD

**Issue by MicanopyNorth** [SickChill/SickChill#7894]
Verified on Firefox and Chrome

  SickChill Info:
Install: pip
Version: v2022.02.20
Database Version: 44.2

  Python Version:
3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

  SSL Version:
OpenSSL 1.1.1k 25 Mar 2021

  OS:
Windows-10-10.0.19043-SP0

  Locale:
en_US.cp1252

**Comment by miigotu** [comment]
You'll need to provide screenshots of what you mean. There is no paging on backlog overview, it's just one page.

**Comment by MicanopyNorth** [comment]
I thought that I had ... I'll try again
![Screenshot 2022-02-21 093613](https://user-images.githubusercontent.com/14912569/155415493-43a53308-ecf0-4b15-bf45-dd4f0f73189d.png)
.

**Comment by MicanopyNorth** [comment]
![Screenshot 2022-02-23 165814](https://user-images.githubusercontent.com/14912569/155415752-98cac199-5a26-40cd-9863-84f873b46d80.jpg)

**Comment by MicanopyNorth** [comment]
I also get a Mako error when I try to view the wonky show "At Last the 1948 Show", so that specific show might be corrupted.  Forcing a full update to see if that cleans anything up.

**Comment by miigotu** [comment]
View source of that page and send the html. Also, what mako error when clicking that show?

**Comment by MicanopyNorth** [comment]
[html source.txt](https://github.com/SickChill/SickChill/files/8156265/html.source.txt)

**Comment by MicanopyNorth** [comment]
A mako error has occurred.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

                Traceback (most recent call last):
                    File C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\common.py:86, in render:
                        return self.template.render_unicode(*args, **context)
                    File C:\SickChill\Python3\tools\lib\site-packages\mako\template.py:478, in render_unicode:
                        return runtime._render(
                    File C:\SickChill\Python3\tools\lib\site-packages\mako\runtime.py:878, in _render:
                        _render_context(
                    File C:\SickChill\Python3\tools\lib\site-packages\mako\runtime.py:920, in _render_context:
                        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
                    File C:\SickChill\Python3\tools\lib\site-packages\mako\runtime.py:947, in _exec_template:
                        callable_(context, *args, **kwargs)
                    File C:/SickChill/Python3/tools/lib/site-packages/sickchill/gui/slick/views/layouts/main.mako:325, in render_body:
                        

File C:/SickChill/Python3/tools/lib/site-packages/sickchill/gui/slick/views/displayShow.mako:540, in render_content: ${sbdatetime.sbdatetime.sbfdatetime(airDate)} File C:\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py:222, in utcoffset: if self._isdst(dt): File C:\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py:291, in _isdst: dstval = self._naive_is_dst(dt) File C:\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py:260, in _naive_is_dst: return time.localtime(timestamp + time.timezone).tm_isdst OSError: [Errno 22] Invalid argument

**Comment by miigotu** [comment]
You should probably update sickchill then.

**Comment by MicanopyNorth** [comment]
Did an uninstall, and re-install using SickChillInstaller.exe.  Identical error behaviors.

**Comment by MicanopyNorth** [comment]
Deleting the show that got the Mako error resolved the display issue with the Backlog.
