### ISSUE TITLE
Error in show exceptions, how to fix

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#7896]
![image](https://user-images.githubusercontent.com/14140816/155029340-e9f86acd-c2f9-4d4f-a882-8b3dc728b1ef.png)

How does one fix the last entry it's grayed out ?

**Comment by BKSteve** [comment]
It can't as it comes from theTVDB or Xem and thus only fixed on their side.

**Comment by miigotu** [comment]
There is no way to change the data that comes from other sites in SC, you have to find which site it comes from and change it there.
