### ISSUE TITLE
addic7ed subtitle plugin not available

### ISSUE THREAD

**Issue by TheQL** [SickChill/SickChill#7923]
Branch/Commit: master/b8d6186701250c8b3305f12bb87e7cce5bfa0267
OS: macOS 11.6.5
Browser: Safari
What you did: opened subtitle plugin settings
What happened: addic7ed was not there
What you expected: addic7ed to be there

This issue is a duplicate of #7099 which was closed without a resolution.

Everything ok on Synology for me, but not on my Mac. I am unsure if all requirements are met.
I searched for addic7ed on my NAS and found mentions in the subliminal package which is not available on my Mac environment.

**Comment by miigotu** [comment]
#7099 (duplicate) Please don't open duplicates, a closed issue is still ok to use.
