### ISSUE TITLE
Postprocessing issue

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#7924]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

SickChill Configuration
  SickChill Info:
Install: [pip](https://pypi.org/project/sickchill/)
Version: [v2022.02.20](https://github.com/SickChill/SickChill/releases/tag/v2022.02.20)
Database Version: 44.5
  Python Version:3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
  SSL Version:OpenSSL 1.1.1k 25 Mar 2021
  OS:Windows-7-6.1.7601-SP1
  Locale:en_US.cp1252

What you did: Manually post processed 2 files
What happened: 
One it just skipped, It's not in the list (it actually is and usually does process correctly) and 
the other Nova it processed it as a different episode.
What you expected:  that it would  have processed both files correctly
Logs:
```

Postprocessing results
Processing in folder \\IP-Address\media\utorrent\completedDownload\SC
Processing \\IP-Address\media\utorrent\completedDownload\SC
Processing folder \\IP-Address\media\utorrent\completedDownload\SC
Processing \\IP-Address\media\utorrent\completedDownload\SC\NOVA (1974) (S49E01) (2022-1-5) (1080p WEB h264 BluRay).mkv (None)
Retrieving episode object for 49x5
Snatch history had a quality in it, using that: 1080p BluRay
Is ep a priority download: False
File N:\series\NOVA (1974)\Season 49\NOVA (1974) (S49E05) (2022-02-02) (1080p BluRay h264 BluRay) Arctic Sinkholes.mkv is the same size as \\IP-Address\media\utorrent\completedDownload\SC\NOVA (1974) (S49E01) (2022-1-5) (1080p WEB h264 BluRay).mkv
File exists and new file is same size, pretending we did something
Processing succeeded for \\192.168.29.52\media\utorrent\completedDownload\SC\NOVA (1974) (S49E01) (2022-1-5) (1080p WEB h264 BluRay).mkv
Processing \\IP-Address\media\utorrent\completedDownload\SC\Grey's Anatomy (2005) (S18E09) (2022-2-24) (1080p WEB h264 BluRay).mkv (None)
This show isn't in your list, you need to add it to SC before post-processing an episode
Processing failed for \\IP-Address\media\utorrent\completedDownload\SC\Grey's Anatomy (2005) (S18E09) (2022-2-24) (1080p WEB h264 BluRay).mkv:
Processing Failed
Some items were not processed.
\\IP-Address\media\utorrent\completedDownload\SC\Grey's Anatomy (2005) (S18E09) (2022-2-24) (1080p WEB h264 BluRay).mkv : Processing failed:

```

I've seen this with the auto post processing also..
Not sure why it skipped Grey's Anatomy   NOTE: the highlighted entry is one that SickChill added and can't be removed
![image](https://user-images.githubusercontent.com/14140816/159120822-b4feedf3-ef45-43da-b111-8f556fd13887.png)

Nova 49x1 was downloaded and it tried to process it as 49x5

**Comment by BKSteve** [comment]
This looks like 2 issues which are quite different.

The NOVA will need to be looked at as the `NOVA (1974) (S49E01) (2022-1-5) (1080p WEB h264 BluRay).mkv` may be being interpreted and filtered incorrectly. If you rename it to `NOVA (1974) (S49E01) (1080p WEB h264 BluRay).mkv` without the date string does it process properly?

The Grey's one is different. Can you 1) Try a `Force Full Update` to see if that resolves the many strings, if not you may need to 2) remove and add existing.
Grey's on my machine looks like this with only 2 scene exceptions both auto added so greyed out in Edit>Advanced.
![image](https://user-images.githubusercontent.com/10173496/160235270-1caff281-8229-425d-9e27-18a51feeab3d.png)
![image](https://user-images.githubusercontent.com/10173496/160235358-f7b42bf9-5e8c-4515-8e55-e40cb12a515b.png)
