### ISSUE TITLE
[APP SUBMITTED]: 420 Client Error:  for url: https://api-v2launch.trakt.tv/sync/watchlist

### ISSUE THREAD

**Issue by mwhitmel** [SickChill/SickChill#8003]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.2.20
No Log available with ERRORS:
### ERROR
```
Could not connect to Trakt. Code error: 420
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
Need more info. Trakt is working.
Debug logs?
If worked then please close

**Comment by rd1** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19044-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.7.20
Link to Log: https://gist.github.com/b9824717de214a3c974c671b94d79df2
### ERROR
```
API :: 4
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mwhitmel** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.8.15
Link to Log: https://gist.github.com/68913e0a8038283f5b48885dc7bcad78
### ERROR
```
Could not connect to Trakt. Code error: 420
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
