### ISSUE TITLE
pip3 install -U sickchill Warning when running

### ISSUE THREAD

**Issue by Yoshi900** [SickChill/SickChill#8004]
when I run pip3 install -U sickchill 
I get "WARNING: There was an error checking the latest version of pip."

below is the full log... it there an issue or is there just no update?

Requirement already satisfied: sickchill in c:\sickchill\python3\tools\lib\site-packages (2022.2.20)
Requirement already satisfied: deluge-client<2.0.0,>=1.9.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.9.0)
Requirement already satisfied: win-inet-pton<2.0.0,>=1.1.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.1.0)
Requirement already satisfied: guessit<4.0.0,>=3.3.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (3.4.1)
Requirement already satisfied: bencode.py<5.0.0,>=4.0.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (4.0.0)
Requirement already satisfied: profilehooks<2.0.0,>=1.12.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.12.0)
Requirement already satisfied: python-slugify<7.0.0,>=4.0.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (5.0.2)
Requirement already satisfied: cloudscraper<2.0.0,>=1.2.56 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.2.58)
Requirement already satisfied: Mako<2.0.0,>=1.1.4 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.1.5)
Requirement already satisfied: qbittorrent-api<2023.0.0,>=2021.3.18 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2021.8.23)
Requirement already satisfied: PyNMA<2.0,>=1.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0)
Requirement already satisfied: jsonrpclib-pelix<0.5.0,>=0.4.2 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.4.3.1)
Requirement already satisfied: CacheControl<0.13.0,>=0.12.6 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.12.10)
Requirement already satisfied: feedparser<7.0.0,>=6.0.2 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (6.0.8)
Requirement already satisfied: rarfile<5.0,>=4.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (4.0)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.3 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (4.10.0)
Requirement already satisfied: tmdbsimple<3.0.0,>=2.8.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.8.0)
Requirement already satisfied: tus.py<2.0.0,>=1.3.4 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.3.4)
Requirement already satisfied: python-twitter<4.0,>=3.5 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (3.5)
Requirement already satisfied: validators<0.19.0,>=0.18.2 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.18.2)
Requirement already satisfied: html5lib<2.0,>=1.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.8.2)
Requirement already satisfied: timeago<2.0.0,>=1.0.15 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0.15)
Requirement already satisfied: PySocks<2.0.0,>=1.7.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.7.1)
Requirement already satisfied: IMDbPY>=2020.09.25 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2021.4.18)
Requirement already satisfied: Js2Py<0.72,>=0.70 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.71)
Requirement already satisfied: pyOpenSSL<23.0.0,>=20.0.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (21.0.0)
Requirement already satisfied: httplib2<0.21,>=0.19 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.20.2)
Requirement already satisfied: gntp<2.0.0,>=1.0.3 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0.3)
Requirement already satisfied: markdown2<3.0.0,>=2.4.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.4.1)
Requirement already satisfied: beekeeper-alt<2022.0.0,>=2021.7.16 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2021.7.16)
Requirement already satisfied: pymediainfo<6.0.0,>=5.0.3 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (5.1.0)
Requirement already satisfied: imagesize<2.0.0,>=1.2.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.2.0)
Requirement already satisfied: enzyme<0.5.0,>=0.4.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.4.1)
Requirement already satisfied: putio.py<9.0.0,>=8.7.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (8.7.0)
Requirement already satisfied: python3-fanart<3.0.0,>=2.0.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.0.0)
Requirement already satisfied: kodipydent-alt<2022.0.0,>=2021.7.16 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2021.7.16)
Requirement already satisfied: tvdbsimple<2.0.0,>=1.0.6 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0.6)
Requirement already satisfied: requests<3.0.0,>=2.25.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.26.0)
Requirement already satisfied: babelfish>=0.6.0b1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.6.0)
Requirement already satisfied: SQLAlchemy<2.0.0,>=1.4.3 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.4.26)
Requirement already satisfied: subliminal<3.0.0,>=2.1.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (2.1.0)
Requirement already satisfied: ipaddress<2.0.0,>=1.0.23 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0.23)
Requirement already satisfied: new-rtorrent-python<2.0.0,>=1.0.1-alpha.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.0.1a0)
Requirement already satisfied: ifaddr<0.2.0,>=0.1.7 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (0.1.7)
Requirement already satisfied: packaging<22.0,>=20.9 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (21.2)
Requirement already satisfied: configobj<6.0.0,>=5.0.6 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (5.0.6)
Requirement already satisfied: Unidecode<2.0.0,>=1.2.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.3.2)
Requirement already satisfied: pyaes<2.0.0,>=1.6.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.6.1)
Requirement already satisfied: chardet<5.0.0,>=4.0.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (4.0.0)
Requirement already satisfied: Send2Trash<2.0.0,>=1.5.0 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.8.0)
Requirement already satisfied: tornado<7.0,>=6.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (6.1)
Requirement already satisfied: PyGithub<2.0.0,>=1.54.1 in c:\sickchill\python3\tools\lib\site-packages (from sickchill) (1.55)
Requirement already satisfied: soupsieve>1.2 in c:\sickchill\python3\tools\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.3->sickchill) (2.3)
Requirement already satisfied: xmltodict>=0.9.2 in c:\sickchill\python3\tools\lib\site-packages (from beekeeper-alt<2022.0.0,>=2021.7.16->sickchill) (0.12.0)
Requirement already satisfied: msgpack>=0.5.2 in c:\sickchill\python3\tools\lib\site-packages (from CacheControl<0.13.0,>=0.12.6->sickchill) (1.0.2)
Requirement already satisfied: pyparsing>=2.4.7 in c:\sickchill\python3\tools\lib\site-packages (from cloudscraper<2.0.0,>=1.2.56->sickchill) (2.4.7)
Requirement already satisfied: requests-toolbelt>=0.9.1 in c:\sickchill\python3\tools\lib\site-packages (from cloudscraper<2.0.0,>=1.2.56->sickchill) (0.9.1)
Requirement already satisfied: six in c:\sickchill\python3\tools\lib\site-packages (from configobj<6.0.0,>=5.0.6->sickchill) (1.16.0)
Requirement already satisfied: sgmllib3k in c:\sickchill\python3\tools\lib\site-packages (from feedparser<7.0.0,>=6.0.2->sickchill) (1.0.0)
Requirement already satisfied: rebulk>=3.1.0 in c:\sickchill\python3\tools\lib\site-packages (from guessit<4.0.0,>=3.3.1->sickchill) (3.1.0)
Requirement already satisfied: webencodings in c:\sickchill\python3\tools\lib\site-packages (from html5lib<2.0,>=1.1->sickchill) (0.5.1)
Requirement already satisfied: lxml in c:\sickchill\python3\tools\lib\site-packages (from IMDbPY>=2020.09.25->sickchill) (4.6.4)
Requirement already satisfied: pyjsparser>=2.5.1 in c:\sickchill\python3\tools\lib\site-packages (from Js2Py<0.72,>=0.70->sickchill) (2.7.1)
Requirement already satisfied: tzlocal>=1.2 in c:\sickchill\python3\tools\lib\site-packages (from Js2Py<0.72,>=0.70->sickchill) (4.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\sickchill\python3\tools\lib\site-packages (from Mako<2.0.0,>=1.1.4->sickchill) (2.0.1)
Requirement already satisfied: pynacl>=1.4.0 in c:\sickchill\python3\tools\lib\site-packages (from PyGithub<2.0.0,>=1.54.1->sickchill) (1.4.0)
Requirement already satisfied: pyjwt>=2.0 in c:\sickchill\python3\tools\lib\site-packages (from PyGithub<2.0.0,>=1.54.1->sickchill) (2.3.0)
Requirement already satisfied: deprecated in c:\sickchill\python3\tools\lib\site-packages (from PyGithub<2.0.0,>=1.54.1->sickchill) (1.2.13)
Requirement already satisfied: cryptography>=3.3 in c:\sickchill\python3\tools\lib\site-packages (from pyOpenSSL<23.0.0,>=20.0.1->sickchill) (35.0.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\sickchill\python3\tools\lib\site-packages (from python-slugify<7.0.0,>=4.0.1->sickchill) (1.3)
Requirement already satisfied: future in c:\sickchill\python3\tools\lib\site-packages (from python-twitter<4.0,>=3.5->sickchill) (0.18.2)
Requirement already satisfied: requests-oauthlib in c:\sickchill\python3\tools\lib\site-packages (from python-twitter<4.0,>=3.5->sickchill) (1.3.0)
Requirement already satisfied: urllib3>=1.24.2 in c:\sickchill\python3\tools\lib\site-packages (from qbittorrent-api<2023.0.0,>=2021.3.18->sickchill) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in c:\sickchill\python3\tools\lib\site-packages (from requests<3.0.0,>=2.25.1->sickchill) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\sickchill\python3\tools\lib\site-packages (from requests<3.0.0,>=2.25.1->sickchill) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\sickchill\python3\tools\lib\site-packages (from requests<3.0.0,>=2.25.1->sickchill) (2.0.7)
Requirement already satisfied: greenlet!=0.4.17 in c:\sickchill\python3\tools\lib\site-packages (from SQLAlchemy<2.0.0,>=1.4.3->sickchill) (1.1.2)
Requirement already satisfied: pytz>=2012c in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (2021.3)
Requirement already satisfied: stevedore>=1.20.0 in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (3.5.0)
Requirement already satisfied: appdirs>=1.3 in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (1.4.4)
Requirement already satisfied: dogpile.cache>=0.6.0 in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (1.1.4)
Requirement already satisfied: click>=4.0 in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (8.0.3)
Requirement already satisfied: pysrt>=1.0.1 in c:\sickchill\python3\tools\lib\site-packages (from subliminal<3.0.0,>=2.1.0->sickchill) (1.1.2)
Requirement already satisfied: decorator>=3.4.0 in c:\sickchill\python3\tools\lib\site-packages (from validators<0.19.0,>=0.18.2->sickchill) (5.1.0)
Requirement already satisfied: colorama in c:\sickchill\python3\tools\lib\site-packages (from click>=4.0->subliminal<3.0.0,>=2.1.0->sickchill) (0.4.4)
Requirement already satisfied: cffi>=1.12 in c:\sickchill\python3\tools\lib\site-packages (from cryptography>=3.3->pyOpenSSL<23.0.0,>=20.0.1->sickchill) (1.15.0)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in c:\sickchill\python3\tools\lib\site-packages (from stevedore>=1.20.0->subliminal<3.0.0,>=2.1.0->sickchill) (5.7.0)
Requirement already satisfied: pytz-deprecation-shim in c:\sickchill\python3\tools\lib\site-packages (from tzlocal>=1.2->Js2Py<0.72,>=0.70->sickchill) (0.1.0.post0)
Requirement already satisfied: tzdata in c:\sickchill\python3\tools\lib\site-packages (from tzlocal>=1.2->Js2Py<0.72,>=0.70->sickchill) (2021.5)
Requirement already satisfied: backports.zoneinfo in c:\sickchill\python3\tools\lib\site-packages (from tzlocal>=1.2->Js2Py<0.72,>=0.70->sickchill) (0.2.1)
Requirement already satisfied: wrapt<2,>=1.10 in c:\sickchill\python3\tools\lib\site-packages (from deprecated->PyGithub<2.0.0,>=1.54.1->sickchill) (1.13.3)
Requirement already satisfied: oauthlib>=3.0.0 in c:\sickchill\python3\tools\lib\site-packages (from requests-oauthlib->python-twitter<4.0,>=3.5->sickchill) (3.1.1)
Requirement already satisfied: pycparser in c:\sickchill\python3\tools\lib\site-packages (from cffi>=1.12->cryptography>=3.3->pyOpenSSL<23.0.0,>=20.0.1->sickchill) (2.21)

**Comment by BKSteve** [comment]
2022.02.20 is the most up to date `master` release with 3 minor updates checksum `364a62e89dc80591e3f367dae9ad2162334924d3`

**Comment by miigotu** [comment]
Before you pip install, create a virtual environment.

```bash
pip3 -m venv ~/sickchill.venv
source ~/sickchill.venv/bin/activate 
pip install -u sickchill
~/sickchill.venv/bin/SickChill
```

**Comment by Yoshi900** [comment]
ah so, 
the warning is just basically saying "nothing new to update"? 

if this is the case maybe it can go into a wiki.... e.g. 

When checking for an update on windows using 
pip3 install -U sickchill
and this is displayed "WARNING: There was an error checking the latest version of pip."
this means that there is no update to be found. 

If I am correct than this issue can be closed too :) thanks for the information back too.

**Comment by BKSteve** [comment]
Your log you posted doesn't actually have a warning message, unless you missed it. 

You should also put 3\` on a line before and after your log so it's easier to read
