### ISSUE TITLE
Connecting to unknown IP

### ISSUE THREAD

**Issue by msurg** [SickChill/SickChill#8011]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: PIP
OS: Centos 8
Browser: Firefox latest
What you did: 
![capture](https://user-images.githubusercontent.com/1208773/177481949-f46c8d0a-9c5d-4a93-9721-de0c49c08d46.JPG)

Sickchill is connecting to IP (188.114.97.7) port 80 and stays connected. Reverse IP lookup provides names below
ghatatnews.ir
livemlbstreams.club
mmalivestreaming.club
service.efcoin.org
themtm.freenamesystem.net

Edit:

Below are other IPs with port 443 Sickchill establishes connections

185.199.108.153
151.101.64.223
140.82.121.6

What happened: When I kill Sickchill the connection dies, too
What you expected: No connection to an unknown IP. eg. Sickgear does not establish such a connection.
Logs:
```
PASTE LOGS HERE
```

**Comment by BKSteve** [comment]
SC doesn't establish such connections and would point to system or installation corruption.
What's the info page give for 
```
Branch: 
Commit: 
Database Version: 
```

**Comment by msurg** [comment]
I am pretty sure that it is SickChill. As soon as I start SickChill the connections below are established.

`tcp        0      0 192.168.80.5:42298      185.199.111.153:443     ESTABLISHED 3794680/python3.9

tcp        0      0 192.168.80.5:52488      151.101.128.223:443     ESTABLISHED 3794680/python3.9

tcp        0      0 192.168.80.5:46444      140.82.121.6:443        ESTABLISHED 3794680/python3.9  `

And when I kill SickChill connections disappear. 

On Info page I get

`SickChill Info:
Install: pip
Version: v2022.02.20

Database Version: 44.2

Python Version:
3.9.6 (default, Aug 25 2021, 16:22:38) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]

SSL Version:
OpenSSL 1.1.1k FIPS 25 Mar 2021

OS:
Linux-4.18.0-348.7.1.el8_5.x86_64-x86_64-with-glibc2.28

Locale:
en_US.UTF-8`
