### ISSUE TITLE
Docker container keeps crashing after update

### ISSUE THREAD

**Issue by UmRAtEJvgLtH** [SickChill/SickChill#8018]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Unknown
OS: Docker container on Synology Nas running sickchill/sickchill:master

Logs:
The screenshot shows the logs
![Untitled](https://user-images.githubusercontent.com/87305485/179940021-afd9eda0-39c8-49b5-a15a-2a4675423bb6.png)

**Comment by salmon85** [comment]
@speedfreak01 
this worked for me to fix

/opt/SickChill/.venv/bin/python3.8 -m pip install --force-reinstall IMDbPY

replace /opt/SickChill/.venv/bin/python3.8 with whatever is shown in pip args:
for me it was 
pip args: /opt/SickChill/.venv/bin/python3.8 -m pip install

**Comment by speedfreak01** [comment]
That seems to have done the trick! Thanks for the reply 👍

**Comment by FGOD1983** [comment]
worked like a charm, thx @salmon85 !

**Comment by UmRAtEJvgLtH** [comment]
> I'm assuming people who use containers know how to apply the fix.. Docker baffles the hell out of me :)

Sadly, I have no idea how to fix this in my Docker Container.

**Comment by Cy63rPunk** [comment]
I have the same problem on synology with synocommunity package version 20211110-4
After Update the this morning the package stops after a few minutes.
Tried to install IMDbPY and get the error:

ERROR: Will not install to the user site because it will lack sys.path precedence to IMDbPY in /volume1/@appstore/sickchill/env/lib/python3.8/site-packages

**Comment by desmoloch** [comment]
same problem with synology here. Seems like my whole var directory is deleted (config.ini, sickchill,db, etc...).
I cant start it and there is no log written.

**Comment by speedfreak01** [comment]
@UmRAtEJvgLtH For sickchill using docker on synology,. the following worked for me (just did this as a test)

Open the synology web interface
Open docker app.
Go to containers page. 
Select the sickchill container, and click details. 
Ensure the container is started, then click the terminal tab at the top. 
Click the drop down arrow next to create, and then select 'launch with command', and enter "/app/sickchill/.venv/bin/python3 -m pip install --force-reinstall IMDbPY" (without quotes)

Once it completes, you may need to restart the container... or if like me you have a really old synology nas that takes forever to start the container in the first place... sickchill eventually started and was working on latest version.

**Comment by miigotu** [comment]
Aaaaaand we see why I don't do updates much anymore 😂

**Comment by miigotu** [comment]
I believe if you just delete poetry.lock and restart the process it will run. Can someone try that?

**Comment by desmoloch** [comment]
i'm running your package via synocommunity package. Seems like updating

**Comment by desmoloch** [comment]
ok i can´t get it running via --daemon... and i have no log :(

**Comment by BKSteve** [comment]
@desmoloch 
if you update or run SC items you need to make sure the permission are correct.
`sc-sickchill sickchill` owner and group.
So check the site-packages folder and fix any that aren't.

So after ssh you `sudo -u sc-sickchill /bin/bash` that way you install and run as sc-sickchill as it runs from package center properly.

@UmRAtEJvgLtH  sorry for hijacking your docker thread.

**Comment by UmRAtEJvgLtH** [comment]
> 

Before it starts downloading the Docker crashes. I'm to be completely honest a total n00b when it comes to Docker and Containers.
Is there anyway to start the container from Synology without it executing the code to install so it won't crash?

**Comment by BKSteve** [comment]
Sorry not familiar enough with Docker on Synology. I use the SynoCommunity package directly.

They discuss docker on SynoCommunity Discord Support some times.
https://discord.com/channels/732558169863225384/732559466721181738

here's one of the links recommended
https://trash-guides.info/Hardlinks/How-to-setup-for/Synology/

**Comment by desmoloch** [comment]
@BKSteve : I never changed permissions manually. If i try to run it via user sc-sickchill i get this error:
[code]Poetry installed packages checker completed
["/volume1/@appstore/sickchill/share/SickChill/.venv/bin/python3: No module named poetry.__main__; 'poetry' is a package and cannot be directly executed"]
Unable to install to the existing virtual environment located at /volume1/@appstore/sickchill/share/SickChill/.venv
Please check the permissions, and that it does not include global site packages
[/code]

**Comment by UmRAtEJvgLtH** [comment]
> Sorry not familiar enough with Docker on Synology. I use the SynoCommunity package directly.
> 
> They discuss docker on SynoCommunity Discord Support some times. https://discord.com/channels/732558169863225384/732559466721181738
> 
> here's one of the links recommended https://trash-guides.info/Hardlinks/How-to-setup-for/Synology/

I started using this one too. Luckily I make nightly backups of my SickChill configuration. The SynoCommunity works like a charm so far

**Comment by miigotu** [comment]
The docker container is rebuilding a new image now.

**Comment by SimonHova** [comment]
> I believe if you just delete poetry.lock and restart the process it will run. Can someone try that?

No, I tried that several times and it didn't work.

**Comment by SimonHova** [comment]
I also get a pip error

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sickchill 2022.2.20 requires packaging<22.0,>=20.9, but you have packaging 20.4 which is incompatible.`

**Comment by miigotu** [comment]
> I also get a pip error
> 
> `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> sickchill 2022.2.20 requires packaging<22.0,>=20.9, but you have packaging 20.4 which is incompatible.`

The docker image was updated 8 hours ago, do a docker pull.

**Comment by Stormtrooper666** [comment]
I was running a normal Windows installation, so no docker etc. Also crashed after updating. Removed my sickchill-master folder and build up a new one. Also crashed. Now downloaded the SickChill-2022.02.20 file, extracted that, started it and than updated. Seems to work now.

**Comment by rEes9P** [comment]
Not working on macOS for me either with similar error messages

**Comment by miigotu** [comment]
> I was running a normal Windows installation, so no docker etc. Also crashed after updating. Removed my sickchill-master folder and build up a new one. Also crashed. Now downloaded the SickChill-2022.02.20 file, extracted that, started it and than updated. Seems to work now.

The windows installer doesn't install a git clone.

Have you tried master since the build was fixed?

**Comment by miigotu** [comment]
> Not working on macOS for me either with similar error messages

Kill the .venv folder and try it again?

**Comment by rEes9P** [comment]
> Kill the .venv folder and try it again?

I can't seem to locate it. Could you please tell me how to go about it?

**Comment by miigotu** [comment]
> > Kill the .venv folder and try it again?
> 
> I can't seem to locate it. Could you please tell me how to go about it?

In the SickChill folder, `rm -rf .venv`

**Comment by miigotu** [comment]
> subtitles is also broken
> 2022-07-21 21:18:12 Traceback (most recent call last):
> File "/opt/sickchill/sickchill/oldbeard/subtitles.py", line 257, in download_subtitles
> f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
> TypeError: tuple indices must be integers or slices, not str

Irrelevant to this issue. Please open a separate issue for that error.

**Comment by rEes9P** [comment]
> In the SickChill folder, `rm -rf .venv`

Back up and running now. Thanks!

**Comment by wallacebrf** [comment]
i can confirm the issue was fixed for me on a synology DSM7 docker container as detailed by user speedfreak01

Open the synology web interface
Open docker app.
Go to containers page.
Select the sickchill container, and click details.
Ensure the container is started, then click the terminal tab at the top.
Click the drop down arrow next to create, and then select 'launch with command', and enter "/app/sickchill/.venv/bin/python3 -m pip install --force-reinstall IMDbPY" (without quotes)
