### ISSUE TITLE
Show List: Sort by Downloads - no longer sorting in order

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#8019]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:

Install: pip
Version: v2022.07.20
Database Version: 44.2

OS: Windows 10
Browser: Firefox
What you did: installed latest SickChill update
What happened: TV show list order became random when sorted by downloads
What you expected: to see the shows in the order of the proportion of episodes downloaded
Logs:
```
n/a
```

**Comment by rutskiuk** [comment]
![random](https://user-images.githubusercontent.com/25068977/180043328-594dc2fd-f9ef-4957-8ff5-3450c32fc051.JPG)

**Comment by DravenSA** [comment]
I agree, I used to be able to sort by download, and anything that missing or snached would go to the top of the list, before 0/0 of upcoming shows, or shows that only had like 6/6 episodes. Now I can see easily if something didnt download like 168+1/169 or 168/169, this was the way to see that everything was order, or if I had to manually go find some things, Now i'll have to look through a massive list to find whats missing.

**Comment by DravenSA** [comment]
After a minute or 2 of investigation, the correct way to get the listing in the order you are looking for is to set the view to poster and sort by PROGRESS, the order you get there, is the way the DOWNLOADS used to work. So maybe this will be an easy fix, to get it to do a PROGRESS Sort in the over View types. Poster View is NOT for me, for YEARS i have been using Small Poster and i see the OP is using Simple layout, as i am sue so many others are too.
