### ISSUE TITLE
Sickchill hangs installing poetry

### ISSUE THREAD

**Issue by bsteph** [SickChill/SickChill#8024]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Linux
Browser: Chrome
What you did: Tried starting sickchill after a recent update.  Also tried a git pull to ensure I had the latest copy

What happened: SickChill hangs trying to do the pip install
What you expected: I expected the package installed successfully and sickrage start up
Logs:
```
 ./SickChill.py --debug
Checking poetry
Can write to /home/bsteph/.local/lib/python3.8/site-packages: True
Can write to /usr/local/lib/python3.8/dist-packages: False
We always run from virtualenv when running from source
Restarting SickChill with ['/home/bsteph/git/SickChill/.venv/bin/python3.8', './SickChill.py', '--debug']
Checking poetry
Can write to /home/bsteph/git/SickChill/.venv/lib/python3.8/site-packages: True
Can write to /home/bsteph/.local/lib/python3.8/site-packages: True
pip installed: True
pip args: /home/bsteph/git/SickChill/.venv/bin/python3.8 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
```

**Comment by bsteph** [comment]
I deleted the .venv and now it's starting fine.

**Comment by MLQ-BA** [comment]
Semes like same issue as in Nov

https://github.com/SickChill/SickChill/issues/7673

Solution that worked for me

1. close sickchill
2. delete .venv
3. run a git update

- git remote set-url origin https://github.com/SickChill/SickChill.git;
- git fetch origin;
- git reset --hard origin/master;

6. restart sickhill or whole server
