### ISSUE TITLE
Subtile does not work anymore in latest release

### ISSUE THREAD

**Issue by Netfreak100** [SickChill/SickChill#8026]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: ubuntu focal in al VM

PASTE LOGS HERE
2022-07-21 21:18:12 Traceback (most recent call last):
File "/opt/sickchill/sickchill/oldbeard/subtitles.py", line 257, in download_subtitles
f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
TypeError: tuple indices must be integers or slices, not str

**Comment by UmRAtEJvgLtH** [comment]
I have the same problem running the SynoCommunity package:
  SickChill Info:
Branch: master
Commit: e943e010b959ffcc412ab098a332233ffd55350b
Database Version: 44.2

  Python Version:
3.8.13 (default, Jul 10 2022, 21:07:01) [GCC 7.5.0]

  SSL Version:
OpenSSL 1.1.1q 5 Jul 2022

  OS:
Linux-4.4.180+-x86_64-with-glibc2.2.5
