### ISSUE TITLE
720p HEVC gets marked as unknown

### ISSUE THREAD

**Issue by bluezed** [SickChill/SickChill#8029]
Branch/Commit: pip/ v2022.07.20 
OS: Ubuntu 20.04.4
Browser: Firefox

What you did:
I have set all 720p qualities as preferred for all shows. 

What happened:
If the file is 720p HEVC it's marked as unkonwn.

What you expected:
I would expect any file with 720p in the filename to be marked as 720p.
Is there any way to include those HEVC files in the 720p qualities so they get marked correctly?

Logs:
```
2022-07-22 12:50:56 INFO :: SEARCHQUEUE-RETRY-356202 :: [SomeProvider] :: Quality of SHOWNAME.S01E01.720p.HEVC.x265 is Unknown
```

**Comment by miigotu** [comment]
You have to enable HEVC in settings most likely.

**Comment by bluezed** [comment]
Oh wow, I never knew that setting exists.
Yes, it works now.
Thank you very much!
