### ISSUE TITLE
[APP SUBMITTED]: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by AllUsernamesWereUnavailable** [SickChill/SickChill#8030]
### INFO
Python Version: **3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]**
Operating System: **Linux-5.15.32-v7+-armv7l-with-glibc2.31**
Locale: UTF-8
Branch: **pip**
Commit: SickChill/SickChill@
Link to Log: https://gist.github.com/e7647db79d2970ead55a13f1a717f643
### ERROR
```
Unable to find subtitles for Ted Lasso S01E05. Error: tuple indices must be integers or slices, not str
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
This is already fixed, update

**Comment by gielie** [comment]
### INFO
Python Version: **3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]**
Operating System: **Linux-4.4.180+-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@
Link to Log: https://gist.github.com/9ae084887bcd6aedcf9f23a7e3c25805
### ERROR
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sickchill/oldbeard/subtitles.py", line 257, in download_subtitles
    f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
TypeError: tuple indices must be integers or slices, not str

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Magiske** [comment]
### INFO
Python Version: **3.9.13 (main, Jul 26 2022, 13:12:30) [GCC 10.3.1 20211027]**
Operating System: **Linux-4.4.59+-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@a8e5d00f02e5d27719409bb9d7d733042b294b82
Link to Log: https://gist.github.com/63f374da2f384d5c4c8b7309f6b30950
### ERROR
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sickchill/oldbeard/subtitles.py", line 257, in download_subtitles
    f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
TypeError: tuple indices must be integers or slices, not str

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by viperhansa** [comment]
### INFO
Python Version: **3.9.13 (main, Jul 26 2022, 13:12:30) [GCC 10.3.1 20211027]**
Operating System:  Linux-5.15.46-Unraid-x86_64-with
Locale: None
Branch: **pip**
Version: [v2022.07.20](SickChill/releases/tag/v2022.07.20)
Database Version: 44.2

### ERROR
```
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/sickchill/oldbeard/subtitles.py", line 257, in download_subtitles
f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
TypeError: tuple indices must be integers or slices, not str
```

**Comment by gielie** [comment]
### INFO
Python Version: **3.9.13 (main, Jul 26 2022, 13:12:30) [GCC 10.3.1 20211027]**
Operating System: **Linux-4.4.180+-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@
Link to Log: https://gist.github.com/bc90682817709d69d5ee23a2316e9e68
### ERROR
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sickchill/oldbeard/subtitles.py", line 257, in download_subtitles
    f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
TypeError: tuple indices must be integers or slices, not str

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by edwinroos** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.7.20
Link to Log: https://gist.github.com/ff3c2a6838b1727a8338f71a0f29c833
### ERROR
```
Traceback (most recent call last):
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\subtitles.py", line 257, in download_subtitles
    f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
TypeError: tuple indices must be integers or slices, not str

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by tanjd** [comment]
### INFO
Python Version: **3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19044-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.7.20
No Log available with ERRORS:
### ERROR
```
Traceback (most recent call last):
  File "C:\Windows\system32\config\systemprofile\AppData\Roaming\Python\Python39\site-packages\sickchill\oldbeard\subtitles.py", line 257, in download_subtitles
    f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
TypeError: tuple indices must be integers or slices, not str

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
And if you are installed with pip, check this comment: https://github.com/SickChill/SickChill/issues/8051#issuecomment-1204589643
