### ISSUE TITLE
SickChill do not work after fresh install

### ISSUE THREAD

**Issue by Criptogalinha** [SickChill/SickChill#8036]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Server Armbian // Client Debian
Browser: Server Lynx // Client Firefox & Chrome
What you did: Fresh install in a fresh environment, IpTables all ports open
What happened: No error reported during the install, the service is running with out any errors, but i cannot access Sickchill at port 8081
What you expected: 
Logs: Not much ;

```
systemctl status sickchill
● sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-07-24 09:51:00 CEST; 12min ago
    Process: 4466 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=0/SUCCESS)
      Tasks: 7 (limit: 4441)
     Memory: 261.3M
        CPU: 11min 10.007s
     CGroup: /system.slice/sickchill.service
             ├─4481 /opt/sickchill/.venv/bin/python3.10 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill
             ├─4503 /bin/sh -c "cd /opt/sickchill && /opt/sickchill/.venv/bin/python3.10 -m poetry export -f requirements.txt --without-hashes"
             ├─4504 /opt/sickchill/.venv/bin/python3.10 -m poetry export -f requirements.txt --without-hashes
             ├─4955 /tmp/tmpd70yw5jg/.venv/bin/python -
             └─4958 /tmp/tmpd70yw5jg/.venv/bin/python -m pip install --ignore-installed --prefix /tmp/pep517-build-env-lgrte06i setuptools wheel

Jul 24 09:51:00 odroidxu4 systemd[1]: Starting SickChill Daemon...
Jul 24 09:51:00 odroidxu4 systemd[1]: Started SickChill Daemon.

```

I do not know where to find SickChill logs or to verify if the correct port is 8081

**Comment by BKSteve** [comment]
First guess on where to look for logs would be
`/opt/sickchill/var/data/logs`. 
However you give no information on how you installed on Ambian and you log shows Python running from `tmp` folder

**Comment by Criptogalinha** [comment]
I installed on Armbian using your guide / more specific "Our guide"
I also have Python 3.10 installed
After running the command netstat /I do not have any port been listen by sickchill
# netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:39795           0.0.0.0:*               LISTEN      1267/rpc.mountd     
tcp        0      0 0.0.0.0:51413           0.0.0.0:*               LISTEN      1269/transmission-d 
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      673/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1346/sshd: /usr/sbi 
tcp        0      0 0.0.0.0:46199           0.0.0.0:*               LISTEN      1267/rpc.mountd     
tcp        0      0 0.0.0.0:53847           0.0.0.0:*               LISTEN      1267/rpc.mountd     
tcp        0      0 0.0.0.0:42875           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:2049            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:9091            0.0.0.0:*               LISTEN      1269/transmission-d 
tcp        0      0 0.0.0.0:43625           0.0.0.0:*               LISTEN      1266/rpc.statd      
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/init              
 
No logs what so ever ! I check :
/opt/sickchill  (the is no ./var )
/var/log
/var/lib/sickchill

and when I enable sickchill I have two process running
# ps -e | grep pyth
 7176 ?        00:00:00 python3.10
 7186 ?        00:00:14 python3.10

Thank you and let me know what do you need to help

**Comment by miigotu** [comment]
You can't find the logs in systemd logging because you have -q. Your sickchill.log would be in `/opt/sickchill/Logs/sickchill.log`

You can stop that service and run:
`/opt/sickchill/.venv/bin/python3.10 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill`

You might need sudo if it fails to a permissions error (if you didn't set a proper user to use in your service file)

This will show you whatever error it is, probably some compilation error because wheels are not available for every platform, or because your glib is a strange version.

**Comment by Criptogalinha** [comment]
Thanks

I ran : sudo -u sickchill /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill

No Logs but the output was :
Checking poetry
Can write to /usr/local/lib/python3.10/dist-packages: False
Can write to /var/lib/sickchill/.local/lib/python3.10/site-packages: False
Current environment is not writable!
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.10', '/opt/sickchill/SickChill.py', '--nolaunch', '--datadir=/opt/sickchill']
Checking poetry
Can write to /var/lib/sickchill/.local/lib/python3.10/site-packages: False
Can write to /opt/sickchill/.venv/lib/python3.10/site-packages: True
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.10 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed
pip args: /opt/sickchill/.venv/bin/python3.10 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ appdirs==1.4.4 babelfish==0.6.0; python_version >= "3.6" and python_version < "4.0" backports.zoneinfo==0.2.1; python_version < "3.9" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") beautifulsoup4==4.11.1; python_full_version >= "3.6.0" beekeeper-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" bencode.py==4.0.0 cachecontrol==0.12.11; python_version >= "3.6" certifi==2022.6.15; python_version >= "3.7" and python_version < "4" cffi==1.15.1; python_version >= "3.6" chardet==5.0.0; python_version >= "3.6" charset-normalizer==2.1.0; python_version >= "3.7" and python_version < "4" and python_full_version >= "3.6.0" cinemagoer==2022.2.11 click==8.1.3; python_version >= "3.7" colorama==0.4.5; python_version >= "3.7" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.7" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==37.0.4; python_version >= "3.6" decorator==5.1.1; python_version >= "3.6" deluge-client==1.9.0 deprecated==1.2.13; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.8; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.10; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.2; python_version >= "3" and python_full_version < "3.0.0" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") or python_version >= "3" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") and python_full_version >= "3.5.0" guessit==3.4.3 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.20.4; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") idna==3.3; python_version >= "3.7" and python_version < "4" ifaddr==0.2.0 imagesize==1.4.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2022.7.9 importlib-metadata==4.12.0; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7") importlib-resources==5.9.0; python_version >= "3.7" and python_version < "3.9" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.3.2 kodipydent-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" lxml==4.9.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.2.1; python_version >= "3.7" markdown2==2.4.3; python_version >= "3.5" and python_version < "4" markupsafe==2.1.1; python_version >= "3.7" msgpack==1.0.4; python_version >= "3.6" new-rtorrent-python==1.0.1a0 oauthlib==3.2.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==21.3; python_version >= "3.6" pbr==5.9.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.21; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.4.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.5.0; python_version >= "3.6" pynma==1.0 pyopenssl==22.0.0; python_version >= "3.6" pyparsing==3.0.9; python_full_version >= "3.6.8" and python_version >= "3.6" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==6.1.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") python-twitter==3.5 python3-fanart==2.0.0 pytz-deprecation-shim==0.1.0.post0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" pytz==2022.1 qbittorrent-api==2022.5.32 rarfile==4.0 rebulk==3.1.0 requests-oauthlib==1.3.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests==2.28.1; python_version >= "3.7" and python_version < "4" send2trash==1.8.0 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" soupsieve==2.3.2.post1; python_version >= "3.6" and python_full_version >= "3.6.0" sqlalchemy==1.4.39; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.5.0; python_version >= "3.6" subliminal==2.1.0 text-unidecode==1.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" timeago==1.0.15 tmdbsimple==2.9.1 tornado==6.2; python_version >= "3.7" tus.py==1.3.4 tvdbsimple==1.0.6 typing-extensions==4.3.0; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7") tzdata==2022.1; platform_system == "Windows" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") tzlocal==4.2; python_version >= "3.6" unidecode==1.3.4; python_version >= "3.5" urllib3==1.26.10; python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "4" or python_full_version >= "3.6.0" and python_version < "4" and python_version >= "3.7" validators==0.20.0; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.14.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" xmltodict==0.13.0; python_full_version >= "3.6.2" and python_version < "4" and python_version >= "3.4" zipp==3.8.1; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7")
Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.14 requires packaging<21.0,>=20.4, but you have packaging 21.3 which is incompatible.

Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 18, in <module>
    from sickchill.movies import MovieList
  File "/opt/sickchill/sickchill/movies.py", line 8, in <module>
    from imdb.parser.http.piculet import Path, Rule
  File "/opt/sickchill/.venv/lib/python3.10/site-packages/imdb/parser/http/__init__.py", line 40, in <module>
    from . import (
  File "/opt/sickchill/.venv/lib/python3.10/site-packages/imdb/parser/http/companyParser.py", line 32, in <module>
    from .piculet import Path, Rule, Rules
  File "/opt/sickchill/.venv/lib/python3.10/site-packages/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

i had two errors :

Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.14 requires packaging<21.0,>=20.4, but you have packaging 21.3 which is incompatible.
 
And

ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

also I deleted .venv and ran the command again as suggested,  

the header was a litle bit different : 

Checking poetry
Can write to /usr/local/lib/python3.10/dist-packages: False
Can write to /var/lib/sickchill/.local/lib/python3.10/site-packages: False
Current environment is not writable!
Because of the above errors, we will try creating a new virtualenvironment in /opt/sickchill/.venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/opt/sickchill/.venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

virtualenv installed: False
virtualenv module not found, getting a portable one to use temporarily
Command result: created virtual environment CPython3.10.4.final.0-32 in 1099ms
  creator CPython3Posix(dest=/opt/sickchill/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/var/lib/sickchill/.local/share/virtualenv)
    added seed packages: pip==22.1.2, setuptools==62.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Created new virtualenvironment in /opt/sickchill/.venv
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.10', '/opt/sickchill/SickChill.py', '--nolaunch', '--datadir=/opt/sickchill']
Checking poetry
Can write to /opt/sickchill/.venv/lib/python3.10/site-packages: True
Can write to /var/lib/sickchill/.local/lib/python3.10/site-packages: False
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.10 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed

Additional question : do I need to install apt install python3.10-venv ?

**Comment by Criptogalinha** [comment]
Thanks

I ran : sudo -u sickchill /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill

No Logs but the output was :
Checking poetry
Can write to /usr/local/lib/python3.10/dist-packages: False
Can write to /var/lib/sickchill/.local/lib/python3.10/site-packages: False
Current environment is not writable!
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.10', '/opt/sickchill/SickChill.py', '--nolaunch', '--datadir=/opt/sickchill']
Checking poetry
Can write to /var/lib/sickchill/.local/lib/python3.10/site-packages: False
Can write to /opt/sickchill/.venv/lib/python3.10/site-packages: True
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.10 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed
pip args: /opt/sickchill/.venv/bin/python3.10 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ appdirs==1.4.4 babelfish==0.6.0; python_version >= "3.6" and python_version < "4.0" backports.zoneinfo==0.2.1; python_version < "3.9" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") beautifulsoup4==4.11.1; python_full_version >= "3.6.0" beekeeper-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" bencode.py==4.0.0 cachecontrol==0.12.11; python_version >= "3.6" certifi==2022.6.15; python_version >= "3.7" and python_version < "4" cffi==1.15.1; python_version >= "3.6" chardet==5.0.0; python_version >= "3.6" charset-normalizer==2.1.0; python_version >= "3.7" and python_version < "4" and python_full_version >= "3.6.0" cinemagoer==2022.2.11 click==8.1.3; python_version >= "3.7" colorama==0.4.5; python_version >= "3.7" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.7" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==37.0.4; python_version >= "3.6" decorator==5.1.1; python_version >= "3.6" deluge-client==1.9.0 deprecated==1.2.13; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.8; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.10; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.2; python_version >= "3" and python_full_version < "3.0.0" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") or python_version >= "3" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") and python_full_version >= "3.5.0" guessit==3.4.3 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.20.4; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") idna==3.3; python_version >= "3.7" and python_version < "4" ifaddr==0.2.0 imagesize==1.4.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2022.7.9 importlib-metadata==4.12.0; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7") importlib-resources==5.9.0; python_version >= "3.7" and python_version < "3.9" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.3.2 kodipydent-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" lxml==4.9.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.2.1; python_version >= "3.7" markdown2==2.4.3; python_version >= "3.5" and python_version < "4" markupsafe==2.1.1; python_version >= "3.7" msgpack==1.0.4; python_version >= "3.6" new-rtorrent-python==1.0.1a0 oauthlib==3.2.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==21.3; python_version >= "3.6" pbr==5.9.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.21; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.4.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.5.0; python_version >= "3.6" pynma==1.0 pyopenssl==22.0.0; python_version >= "3.6" pyparsing==3.0.9; python_full_version >= "3.6.8" and python_version >= "3.6" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==6.1.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") python-twitter==3.5 python3-fanart==2.0.0 pytz-deprecation-shim==0.1.0.post0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" pytz==2022.1 qbittorrent-api==2022.5.32 rarfile==4.0 rebulk==3.1.0 requests-oauthlib==1.3.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests==2.28.1; python_version >= "3.7" and python_version < "4" send2trash==1.8.0 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" soupsieve==2.3.2.post1; python_version >= "3.6" and python_full_version >= "3.6.0" sqlalchemy==1.4.39; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.5.0; python_version >= "3.6" subliminal==2.1.0 text-unidecode==1.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" timeago==1.0.15 tmdbsimple==2.9.1 tornado==6.2; python_version >= "3.7" tus.py==1.3.4 tvdbsimple==1.0.6 typing-extensions==4.3.0; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7") tzdata==2022.1; platform_system == "Windows" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") tzlocal==4.2; python_version >= "3.6" unidecode==1.3.4; python_version >= "3.5" urllib3==1.26.10; python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "4" or python_full_version >= "3.6.0" and python_version < "4" and python_version >= "3.7" validators==0.20.0; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.14.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" xmltodict==0.13.0; python_full_version >= "3.6.2" and python_version < "4" and python_version >= "3.4" zipp==3.8.1; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7")
Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.14 requires packaging<21.0,>=20.4, but you have packaging 21.3 which is incompatible.

Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 18, in <module>
    from sickchill.movies import MovieList
  File "/opt/sickchill/sickchill/movies.py", line 8, in <module>
    from imdb.parser.http.piculet import Path, Rule
  File "/opt/sickchill/.venv/lib/python3.10/site-packages/imdb/parser/http/__init__.py", line 40, in <module>
    from . import (
  File "/opt/sickchill/.venv/lib/python3.10/site-packages/imdb/parser/http/companyParser.py", line 32, in <module>
    from .piculet import Path, Rule, Rules
  File "/opt/sickchill/.venv/lib/python3.10/site-packages/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

i had two errors :

Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.14 requires packaging<21.0,>=20.4, but you have packaging 21.3 which is incompatible.
 
And

ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

also I deleted .venv and ran the command again as suggested,  

the header was a litle bit different : 

Checking poetry
Can write to /usr/local/lib/python3.10/dist-packages: False
Can write to /var/lib/sickchill/.local/lib/python3.10/site-packages: False
Current environment is not writable!
Because of the above errors, we will try creating a new virtualenvironment in /opt/sickchill/.venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/opt/sickchill/.venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

virtualenv installed: False
virtualenv module not found, getting a portable one to use temporarily
Command result: created virtual environment CPython3.10.4.final.0-32 in 1099ms
  creator CPython3Posix(dest=/opt/sickchill/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/var/lib/sickchill/.local/share/virtualenv)
    added seed packages: pip==22.1.2, setuptools==62.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Created new virtualenvironment in /opt/sickchill/.venv
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.10', '/opt/sickchill/SickChill.py', '--nolaunch', '--datadir=/opt/sickchill']
Checking poetry
Can write to /opt/sickchill/.venv/lib/python3.10/site-packages: True
Can write to /var/lib/sickchill/.local/lib/python3.10/site-packages: False
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.10 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed

Additional question : do I need to install apt install python3.10-venv ?

**Comment by miigotu** [comment]
So you need to `sudo apt install libxslt-bin` or something similar.

`sudo apt search libxslt` to find the link you need to install.

**Comment by Criptogalinha** [comment]
The problem was solved,

Thank youi

**Comment by BKSteve** [comment]
@Criptogalinha Could you make a note of what solved this for you so if somebody else comes looking it may help them resolve for themselves quickly.
Thanks.

**Comment by miigotu** [comment]
@BKSteve probably did `sudo apt install libxml2-dev libxslt1-dev`
https://github.com/SickChill/SickChill/blob/master/Dockerfile#L25
