### ISSUE TITLE
SickChill Stops adding Shows from existing folders

### ISSUE THREAD

**Issue by josurr** [SickChill/SickChill#8039]
### Before submitting your issue:

Enable debug logging in SickChill settings, and reproduce the error (be sure to disable it after the bug is fixed)

Branch/Commit: master
OS: Docker container (sickchill/sickchill) on UnraidOS
Browser: Chrome
What you did: Added shows from existing folders (approximately 525 or so in total)
What happened: Show count has stalled at 217 and no updates since, even after restarting. Did not see anything in the debug logs
What you expected: Add all of the existing shows from the folders into the SickChill database
Logs:
```
I checked the archive and current log files and there is nothing that could explain why the adding of shows stopped.
```

**Comment by miigotu** [comment]
So start adding again. It will add the ones that aren't added yet

**Comment by miigotu** [comment]
Also, 500+ shows is ridiculous. The idea is not to see how much you can possibly pirate. Just get enough to watch and be humble about it. Just my opinion.

**Comment by josurr** [comment]
I have tried re-added them multiple times, it never increases the count.

Yes, I know it is an excessive number, but I have a lot of people that use my Plex setup and some of the shows I have you can't find on physical media or even streaming services anymore.

**Comment by josurr** [comment]
I think this may be the issue?

`2022-07-26 19:00:36 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with search term(s): ['Conviction'] on Indexer: theTVDB (exact: 0)
2022-07-26 19:00:32 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with search term(s): ['Constantine'] on Indexer: theTVDB (exact: 0)
2022-07-26 19:00:25 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with search term(s): ['Community'] on Indexer: theTVDB (exact: 0)
2022-07-26 19:00:20 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with search term(s): ['Cobra Kai'] on Indexer: theTVDB (exact: 0)
2022-07-26 19:00:13 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with search term(s): ['Class'] on Indexer: theTVDB (exact: 0)
2022-07-26 19:00:08 DEBUG :: WEBSERVER-ADDSHOWS_0 :: Searching for Show with search term(s): ['Chicago Med'] on Indexer: theTVDB (exact: 0)`

**Comment by miigotu** [comment]
If the shows are not available anywhere else, and you have all of the episodes, you dont need them in SC anymore, just in your library on plex.

That is not an error, it just says what is being searched on tvdb.

**Comment by josurr** [comment]
Ah, gotcha. Some of the shows that haven't been added are still airing.

With the API limit information, I will start going through the remaining ones that haven't been added to SC and only try to add the ones that are still airing.

Thanks!

Keep up the awesome work!

Side note: the latest docker container shows an update/commit available within the web interface, but I haven't applied it as I recall hearing that doing so will not keep the commit/update in place should the container have to be restarted, is that still the case and I should ignore that message for now?

**Comment by miigotu** [comment]
Updates will remain if the container is restarted, just not if it is recreated.

**Comment by josurr** [comment]
Ah, gotcha. Thanks!
