### ISSUE TITLE
Documentation / git / config mismatch 

### ISSUE THREAD

**Issue by brunis** [SickChill/SickChill#8049]
I think most of the installers like this one refers to /opt/sickchill non-capitalized, but cloning git gives you /opt/SickChill
https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15

And the /etc/systemd/system/sickchill.service also refers to /opt/sickchill in ExecStart:
ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill

**Comment by miigotu** [comment]
That installation guide you referenced has this line:
`sudo -u sickchill git clone https://github.com/SickChill/SickChill.git /opt/sickchill`

Which puts it in /opt/sickchill, not /opt/SickChill

**Comment by miigotu** [comment]
As does the automated script:
https://github.com/SickChill/SickChill/blob/master/contrib/debian-ubuntu-install.sh#L78
https://github.com/SickChill/SickChill/blob/master/contrib/debian-ubuntu-install.sh#L86

**Comment by miigotu** [comment]
If you are cloning instead of using an installer, or following a guide, you should know the difference right off the bat. If you are following a guide, correctly, you end up with the right directories. `contrib` btw is reference files, almost all of them need customized for each user's use case.

**Comment by brunis** [comment]
Ouch yes.. i had manually just cloned github/SickChill ..  which was the mistake that lead to the rest of my issues! Sorry for wasting your time.
