### ISSUE TITLE
Mako Error after adding a few shows

### ISSUE THREAD

**Issue by brunis** [SickChill/SickChill#8050]
Branch/Commit: d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5
OS: Debian
Browser: Firefox
What you did: Added shows (reached maybe 6 out of 10 total)
What happened: Mako error
What you expected: Shows added
Logs:
```
From filesystem log:
2022-08-02 18:27:07 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: local variable 'cur_airs_prev' referenced before assignment
2022-08-02 18:27:19 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: local variable 'cur_airs_prev' referenced before assignment

Mako error page log:
Traceback (most recent call last):
                    File /opt/SickChill/sickchill/views/common.py:86, in render:
                        return self.template.render_unicode(*args, **context)
                    File /usr/local/lib/python3.9/dist-packages/mako/template.py:444, in render_unicode:
                        return runtime._render(
                    File /usr/local/lib/python3.9/dist-packages/mako/runtime.py:874, in _render:
                        _render_context(
                    File /usr/local/lib/python3.9/dist-packages/mako/runtime.py:916, in _render_context:
                        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
                    File /usr/local/lib/python3.9/dist-packages/mako/runtime.py:943, in _exec_template:
                        callable_(context, *args, **kwargs)
                    File /opt/SickChill/sickchill/gui/slick/views/layouts/main.mako:325, in render_body:

File /opt/SickChill/sickchill/gui/slick/views/home.mako:64, in render_content: <%include file="/inc_home_show_list.mako" args="curListType=curShowlist[0], myShowList=curShowlist[1]"/> File /usr/local/lib/python3.9/dist-packages/mako/runtime.py:793, in _include_file: callable_(ctx, **kwargs) File /opt/SickChill/sickchill/gui/slick/views/inc_home_show_list.mako:17, in render_body: <%include file="/inc_home_show_list_poster.mako" args="curListType=curListType, myShowList=myShowList"/> File /usr/local/lib/python3.9/dist-packages/mako/runtime.py:793, in _include_file: callable_(ctx, **kwargs) File /opt/SickChill/sickchill/gui/slick/views/inc_home_show_list_poster.mako:127, in render_body: % if cur_airs_next or cur_airs_prev: UnboundLocalError: local variable 'cur_airs_prev' referenced before assignment

```

**Comment by BKSteve** [comment]
Adding individually or `add existing` mass adding?
What is your display and `layout` when this occurs? was it `show list` just after adding? What `layout` is selected?
Try the same thing with a different layout.
Turn on `debug logging` and restart SC. Then reproduce and put the `debug` data from the log.

**Comment by brunis** [comment]
> Adding individually or `add existing` mass adding? 
Mass add existing, was starting fresh.

> What is your display and `layout` when this occurs? was it `show list` just after adding?
Yes, Show list in Poster layout.

> What `layout` is selected? Try the same thing with a different layout. Turn on `debug logging` and restart SC. Then reproduce and put the `debug` data from the log.
I *did* turn on debugging before copy/pasting those logs.

It seems it was just a matter of waiting for the show details to be scraped, now that the posters and metadata is fetched it's displaying properly. But it only managed to add 3 shows out of the total 20..

But adding all the remaining the 2nd time around didn't cause any issues.

**Comment by BKSteve** [comment]
Sometimes `theTVDB` is the cause of these with many hits from same ip or when it's busy.
