### ISSUE TITLE
TrueNAS Plugin Doesn't Work

### ISSUE THREAD

**Issue by jasker5183** [SickChill/SickChill#8057]
First off install instructions for TrueNAS do not work, branch master uses release 12.2 which doesn't have python38 so it fails. Branch 12.3-RELEASE also doesn't work as the repo's do not have python38. The pip instructions some what work in that it will install the program but will be executed by command line meaning it will run as root without a service file.

I'm trying to get the plugins working on 13.1 [here](https://github.com/ix-plugin-hub/iocage-plugin-index/pull/322), I thought the reason I couldn't get it going was because of a missing dependency but that apparently is not the case. If I use the updated .json with the 13.1-RELEASE and python39 it will install but will not be running. If I shell into the jail and run `pip install sickchill` then start the sickchill service it will start, but I don't think that's the right way to fix it plus normal users are not going to know how to do this.

Any idea of what to do to fix this?

**Comment by BKSteve** [comment]
mIght be related to release and update
2022.-7.20 hash `a1cf98ae68ebd4475e82f8b0d11ae851eba37827` which didn't run and with a few fixes done quickly with latest hash `d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5` working.
The `pip install` I believe gets the latest from github where as the pypi one may not be fully updated. (assumption)

**Comment by jasker5183** [comment]
As far as I can tell the plugin by default is installing git and pulling directly from the repo so it should be up to date master. The service file that it's using is executing `/usr/local/app/sickchill/SickChill.py` which will not work until Sickchill is installed with pip, under help and about it shows that Sickchill is running from `/usr/local/app/sickchill` and not `/usr/local/lib/python3.9/site-packages/sickchill`. Which still makes me think that there is a missing dependency, but pip should just grab anything it's missing. 

I tried to run the program as root and poetry wanted to do checks then I think pip downloaded all the dependencies but it took 5-8 minutes. Maybe it just takes too long and the service file times out? Wish there was a log to check. Is there any way to debug this? Not too familiar with FreeBSD.

**Comment by miigotu** [comment]
It may just be that the interface is not ready right away on first start, because it is installing dependencies. Check the init script for the command that is run by it, and run that in the jail manually without the -d (--daemon) or -q (--quiet) and you will see what is going on.

pip install always comes from pypi unless you do something like an editable install or add the git+git:// url for the repo instead of sickchill on the pip install line.

**Comment by miigotu** [comment]
@jasker5183 imo the plugin should be reworked to install from pip rather than git.

**Comment by jasker5183** [comment]
I could try running it manually again but the problem with that is that it'll be running as root as the sickchill user was created with /nologin. [Here](https://github.com/SickChill/SickChill/blob/master/contrib/runscripts/init.freebsd) is the init script for reference. 

Might be an idea to switch from git to pip version, attempted at one point to figure this out but couldn't locate the service file to run it as it doesn't seem to be in the `/usr/local/lib/python3.9/site-packages/sickchill` directory. Also installing the pip version doesn't copy an init file to `/usr/local//etc/rc.d`, but I guess you could pull that file using git if you had to. 

If the TrueNAS community is interested in keeping this plugin going they can maintain it because I'm not interested, I just wanted to see if I could fix it.

**Comment by jasker5183** [comment]
For a `post_install.sh`:
```
#!/bin/sh

echo "Create data location for sickchill"
mkdir -p /sickchill_data

echo "Updating dependencies"
pip install --upgrade pip
pip install --upgrade virtualenv
pip install --upgrade sickchill

echo "Create sickchill user"
pw user add sickchill -c "Sickchill" -d /nonexistent -s /usr/bin/nologin -w no
chown -R sickchill:sickchill /sickchill_data

echo "Executing SickChill service"
chmod u+x /usr/local/etc/rc.d/sickchill
sysrc "sickchill_enable=YES"
service sickchill start
```
For `overlay/usr/local/etc/rc.d/sickchill`:
```
#!/bin/sh
#
# PROVIDE: sickchill
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# sickchill_enable (bool):  Set to NO by default.
#      Set it to YES to enable it.
# sickchill_user:  The user account SickChill daemon runs as what
#      you want it to be. It uses 'sickchill' user by
#      default. Do not sets it as empty or it will run
#      as root.
# sickchill_group:  The group account SickChill daemon runs as what
#      you want it to be. It uses 'sickchill' group by
#      default. Do not sets it as empty or it will run
#      as wheel.
# sickchill_dir:  Directory where SickChill lives.
#      Default: /usr/local/app/sickchill
# sickchill_datadir:  Data directory for SickChill (DB, Logs, config)
#      Default is same as sickchill_dir

. /etc/rc.subr

name="sickchill"
rcvar=${name}_enable

load_rc_config ${name}

: ${sickchill_enable:="NO"}
: ${sickchill_user:="sickchill"}
: ${sickchill_group:="sickchill"}
: ${sickchill_dir:="/usr/local/app/sickchill"}
: ${sickchill_datadir:="/sickchill_data"}

pidfile="/var/run/sickchill/sickchill.pid"
command="/usr/local/bin/python3"
command_args="/usr/local/bin/SickChill  --datadir ${sickchill_datadir} -d --pidfile ${pidfile} --quiet --nolaunch"

start_precmd="sickchill_prestart"
sickchill_prestart() {
  if [ -f ${pidfile} ]; then
    rm -f ${pidfile}
    echo "Removing stale pidfile."
  elif [ ! -d ${pidfile%/*} ]; then
    install -d -o ${sickchill_user} -g ${sickchill_group} ${pidfile%/*}
  fi

  if [ ! -d ${sickchill_datadir} ]; then
    install -d -o ${sickchill_user} -g ${sickchill_group} ${sickchill_datadir}
  fi
}

run_rc_command "$1"
```

Not sure what to do about updates, maybe a `post_update.sh` file containing `pip install --upgrade sickchill`?

**Comment by jasker5183** [comment]
For reference this is what I get when I try to run Sickchill as root:

<details>
<summary> ./SickChill.py </summary>
root@sickchill:/usr/local/app/sickchill # ./SickChill.py 

Checking poetry
Can write to /root/.local/lib/python3.9/site-packages: False
Can write to /usr/local/lib/python3.9/site-packages: True
We always run from virtualenv when running from source
Restarting SickChill with ['/usr/local/app/sickchill/.venv/bin/python3.9', './SickChill.py']
Checking poetry
Can write to /root/.local/lib/python3.9/site-packages: False
Can write to /usr/local/app/sickchill/.venv/lib/python3.9/site-packages: True
pip installed: True
pip args: /usr/local/app/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed
pip args: /usr/local/app/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU appdirs==1.4.4 babelfish==0.6.0; python_version >= "3.6" and python_version < "4.0" backports.zoneinfo==0.2.1; python_version < "3.9" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") beautifulsoup4==4.11.1; python_full_version >= "3.6.0" beekeeper-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" bencode.py==4.0.0 cachecontrol==0.12.11; python_version >= "3.6" certifi==2022.6.15; python_version >= "3.7" and python_version < "4" cffi==1.15.1; python_version >= "3.6" chardet==5.0.0; python_version >= "3.6" charset-normalizer==2.1.0; python_version >= "3.7" and python_version < "4" and python_full_version >= "3.6.0" cinemagoer==2022.2.11 click==8.1.3; python_version >= "3.7" colorama==0.4.5; python_version >= "3.7" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.7" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==37.0.4; python_version >= "3.6" decorator==5.1.1; python_version >= "3.6" deluge-client==1.9.0 deprecated==1.2.13; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.8; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.10; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.2; python_version >= "3" and python_full_version < "3.0.0" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") or python_version >= "3" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") and python_full_version >= "3.5.0" guessit==3.4.3 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.20.4; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") idna==3.3; python_version >= "3.7" and python_version < "4" ifaddr==0.2.0 imagesize==1.4.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2022.7.9 importlib-metadata==4.12.0; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7") importlib-resources==5.9.0; python_version >= "3.7" and python_version < "3.9" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.3.2 kodipydent-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" lxml==4.9.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.2.1; python_version >= "3.7" markdown2==2.4.3; python_version >= "3.5" and python_version < "4" markupsafe==2.1.1; python_version >= "3.7" msgpack==1.0.4; python_version >= "3.6" new-rtorrent-python==1.0.1a0 oauthlib==3.2.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==21.3; python_version >= "3.6" pbr==5.10.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.21; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.4.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.5.0; python_version >= "3.6" pynma==1.0 pyopenssl==22.0.0; python_version >= "3.6" pyparsing==3.0.9; python_full_version >= "3.6.8" and python_version >= "3.6" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==6.1.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") python-twitter==3.5 python3-fanart==2.0.0 pytz-deprecation-shim==0.1.0.post0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" pytz==2022.2 qbittorrent-api==2022.8.34 rarfile==4.0 rebulk==3.1.0 requests-oauthlib==1.3.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests==2.28.1; python_version >= "3.7" and python_version < "4" send2trash==1.8.0 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" soupsieve==2.3.2.post1; python_version >= "3.6" and python_full_version >= "3.6.0" sqlalchemy==1.4.40; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.5.0; python_version >= "3.6" subliminal==2.1.0 text-unidecode==1.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" timeago==1.0.15 tmdbsimple==2.9.1 tornado==6.2; python_version >= "3.7" tus.py==1.3.4 tvdbsimple==1.0.6 typing-extensions==4.3.0; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7") tzdata==2022.1; platform_system == "Windows" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") tzlocal==4.2; python_version >= "3.6" unidecode==1.3.4; python_version >= "3.5" urllib3==1.26.11; python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "4" or python_full_version >= "3.6.0" and python_version < "4" and python_version >= "3.7" validators==0.20.0; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.14.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" xmltodict==0.13.0; python_full_version >= "3.6.2" and python_version < "4" and python_version >= "3.4" zipp==3.8.1; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7")
Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.14 requires packaging<21.0,>=20.4, but you have packaging 21.3 which is incompatible.

Unable to find /root/.config/sickchill/config.ini, all settings will be default!
2022-08-12 08:23:32 INFO :: MAIN :: Backing up database before upgrade
2022-08-12 08:23:32 INFO :: MAIN :: Proceeding with upgrade
2022-08-12 08:23:32 INFO :: MAIN :: Adding column rls_prefer_words to tvshows
2022-08-12 08:23:32 INFO :: MAIN :: Updated to: 44.4
2022-08-12 08:23:32 INFO :: MAIN :: Backing up database before upgrade
2022-08-12 08:23:32 INFO :: MAIN :: Proceeding with upgrade
2022-08-12 08:23:32 INFO :: MAIN :: Adding column custom_name to tvshows
2022-08-12 08:23:32 INFO :: MAIN :: Updated to: 44.5
2022-08-12 08:23:32 INFO :: MAIN :: Starting SickChill [master] using '/root/.config/sickchill/config.ini'
2022-08-12 08:23:32 INFO :: MAIN :: Generating New API key
2022-08-12 08:23:32 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2022-08-12 08:23:32 INFO :: CHECKVERSION :: Checking for updates using GIT
2022-08-12 08:23:32 INFO :: MAIN :: Checking for scene exception updates from https://sickchill.github.io/scene_exceptions/scene_exceptions.json
2022-08-12 08:23:33 INFO :: MAIN :: Checking for XEM scene exception updates for theTVDB
2022-08-12 08:23:34 INFO :: MAIN :: Checking for scene exception updates for AniDB
</details>

It takes about 10 minutes to start but it does work, but it's running as root. What I would really like to know is why when I `pip install sickchill` it works but when I `pip uninstall sickchill` it does not?

**Comment by miigotu** [comment]
When sickchill is installed via pip, it doesn't install any dependencies because pip has already installed them. So there is no delay on the first startup when you install with pip.

**Comment by miigotu** [comment]
When sickchill is installed via pip, it doesn't install any dependencies because pip has already installed them. So there is no delay on the first startup when you install with pip. 

I would not recommend releasing it that way though, because the updater will never tell the user to pip install -U sickchill when the git version gets updates. Either rework the whole package to pip install, or leave it at the other method and have your script wait longer before timing out. Possibly the init script for freebsd need updated, but those are maintained by contributors (contrib) as I can't test on all platforms or package for all of them.

**Comment by jasker5183** [comment]
I just wanted to leave users install the way it was meaning they are running the git master version and will continue to update through git. It's possible that the freebsd init script is taking too long and it errors out but I haven't seen any evidence of this. At one point I even tried removing some of the options like --quiet and --nolaunch but it still gives me no idea of what it's doing before it quits without error.

Like I mentioned above the init script is running sickchill from `/usr/local/app/sickchill/SickChill.py`, where pip installs sickchill to `/usr/local/lib/python3.9/site-packages/sickchill` putting a binary in `/usr/local/bin/SickChill`. But for some reason if I install sickchill via pip the program will work using git master, then if I remove it (pip uninstall sickchill) it will no longer works at all. As far as I can tell it's not removing any dependencies either. If you want to run the pip version all you have to do is run `Sickchill` or put `/usr/local/bin/SickChill` in the `/usr/local/etc/rc.d/sickchill` init script. 

The goal might be to fix the init script but that is beyond my capabilities and this method fixes it now.

**Comment by jasker5183** [comment]
For the sake of argument if you are dead set on switching this plugin from git to pip would the plugin need some kind of post_upgrade.sh script? As far as I can tell when SickChill tries to update itself using pip, if it uses the `--user` option since sickchill has no home directory there are going to be problems.

**Comment by jasker5183** [comment]
Not too sure if I should just close this as TrueNAS plugins are not Sickchill proper's fault, but bumping issue to get the attention of whomever is running https://github.com/ix-plugin-hub/iocage-plugin-sickchill as this plugin has been broken for quite some time.

**Comment by miigotu** [comment]
I created the iocage to get it started, but I don't have a Nas or any way to even both with any of that. Whoever wants it to work will need to contribute some of their time/code to make it work. The iocage mess to me is silly anyway, rather just use docker/docker-compose or just use pip.

All I can be responsible for is SC itself. There are so many different packages created to make it easy to install SC on random edge case systems but nobody wants to help maintain them. So they will either fix them or the plugins will die 🤷
