### ISSUE TITLE
Sort Order Broken - No Update With Fix

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#8063]
Unable to check for updates since issue 8019 was closed
https://github.com/SickChill/SickChill/issues/8019
The issue has apparently been resolved but I cannot search for updates to apply the fix.
I have looked at the GitHub Branch Version and is shows: error: No branches found
I presume this is the reason that each time I scan for an update I see none found:

2022-08-03 17:46:29 DEBUG :: WEBSERVER-HOME_0 :: check_for_new_news: Checking GitHub for latest news.
2022-08-03 17:46:29 INFO :: WEBSERVER-HOME_0 :: No update needed
2022-08-03 17:46:29 INFO :: WEBSERVER-HOME_0 :: Checking for updates using PIP
2022-08-03 17:42:48 INFO :: SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found

The git reset only works if this was installed through git, my install was done through the windows installer, I cannot install using git.

Install: exe
Version: v2022.07.20
Database Version: 44.2

OS: Windows 10
Browser: Firefox
What you did: checked for latest update after sort order issue was fixed
What happened: No updates available
What you expected: To see the update that fixes the issue, my sort order is still broken

**Comment by miigotu** [comment]
It is fixed. It is in the develop branch and will be released in the next release. Please do not open random duplicate issues. A closed status does not mean you cant comment there.
