### ISSUE TITLE
Update Failed. Unable to start

### ISSUE THREAD

**Issue by optio50** [SickChill/SickChill#8067]
Today I used the "Update now" link from within Sickchill.
and instantly received this message.

Error !
AttributeError: module 'sickchill.settings' has no attribute 'NO_LGMARGIN'
% endif </div> <div class="row"> % if settings.NO_LGMARGIN: <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"> % else: <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12"> % endif <%block name="content" />
/home/myusername/.sickchill/sickchill/gui/slick/views/layouts/main.mako, line 326:
% if settings.NO_LGMARGIN:
/home/myusername/.sickchill/.venv/lib/python3.9/site-packages/mako/runtime.py, line 936:
callable_(context, *args, **kwargs)

I am unable to reload sickchill to provide any further info.

**Comment by didli** [comment]
Same here with same error in Fedora 36 xfce.

**Comment by demon8991** [comment]
Same issue for me.

**Comment by optio50** [comment]
> 

No home page to go to. The sickchill service is not started.

**Comment by demon8991** [comment]
Unfortunately, this doesn't work as the package will not start.

I had to uninstall and reinstall and restore my backup, will have to stay on the current version until a fix is issued.

**Comment by miigotu** [comment]
> % if settings.NO_LGMARGIN:

Errors in templates do not stop the python code from running, and the variables are there.

**Comment by optio50** [comment]
Any other suggestions?
I am unable to reload sickchill to provide any further info.
This is twice in a week after many years of updating that the update has broke the service.

**Comment by miigotu** [comment]
If you are worried about a couple hiccups in software you get for free, you should either not update ever (there's always bugs in every software) or find a paid solution. Otherwise, try and be a little more forgiving.

Without the thousands of updates SC gets in almost every release, it would stop working VERY quickly.

I have no information about how you are installed, how you run it, or anything. So unless sickchill/settings.py is not getting updated with your package the new code is there. You can check the source code for yourself.

**Comment by optio50** [comment]
Uh....I was asking for help....But OK. I guess I was worried and had hiccups.

**Comment by mortael** [comment]
I had the same message after pressing 'Update Now'.
After that my SickChill didn't start either.

For me, this is what helped to get it working again: https://github.com/SickChill/SickChill/issues/8068#issuecomment-1214715102

**Comment by nydave69** [comment]
Got this when I clicked on update....

Error !
AttributeError: module 'sickchill.settings' has no attribute 'NO_LGMARGIN'
% endif </div> <div class="row"> % if settings.NO_LGMARGIN: <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"> % else: <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12"> % endif <%block name="content" />
C:/SickChill_2000/sickchill/gui/slick/views/layouts/main.mako, line 326:
% if settings.NO_LGMARGIN:
C:\SickChill_2000\.venv\lib\site-packages\mako\runtime.py, line 940:
callable_(context, *args, **kwargs)


I watched the command window that it runs in...
Looks like this error caused a restart of the process..


SickChill Configuration
  SickChill Info:
Branch: master
Commit: a369538827c08c1fb28c638bf877ff2b884176eb
Database Version: 44.5

  Python Version:
3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]

  SSL Version:
OpenSSL 1.1.1d 10 Sep 2019

  OS:
Windows-10-10.0.22000-SP0

  Locale:
en_US.cp65001


  User:
plex

  Program Folder:
C:\SickChill_2000\sickchill

  Config File:
C:\SickChill_2000\Data\config.ini

  Database Files:
C:\SickChill_2000\Data\sickchill.db
C:\SickChill_2000\Data\cache.db
C:\SickChill_2000\Data\failed.db

  Cache Folder:
C:\SickChill_2000\Data\cache

  Log Folder:
C:\SickChill_2000\Data\Logs

  Executable:
C:\SickChill_2000\.venv\Scripts\python.exe

  Main Script:
C:\SickChill_2000\SickChill.py

  Arguments:
--nolaunch --port 8086 --datadir C:\SickChill_2000\Data


after the restart it no longer show that I need the update

**Comment by didli** [comment]
> I had the same message after pressing 'Update Now'. After that my SickChill didn't start either.
> 
> For me, this is what helped to get it working again: [#8068 (comment)](https://github.com/SickChill/SickChill/issues/8068#issuecomment-1214715102)

Worked for me. Thanks.

**Comment by optio50** [comment]
Also for me. :-)
Thanks for curing my hiccups. Apparently, I have a problem.

**Comment by calibra1996** [comment]
ssl_verify worked for me, thxs
