### ISSUE TITLE
Sick Chill not starting because of SSL Error

### ISSUE THREAD

**Issue by bsteph** [SickChill/SickChill#8070]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS:Linux
Browser:Chrome
What you did: Tried to start sickchill 
What happened: sickchill failed to start
What you expected:
Logs:
```
  context.verify_mode = ssl.CERT_REQUIRED if verify else ssl.CERT_NONE
  File "/usr/lib/python3.8/ssl.py", line 720, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.
```
I tried creating a check_hostname entry in the config.ini and setting it to false, and tried 0, but still getting the same result.

**Comment by mortael** [comment]
Try this: https://github.com/SickChill/SickChill/issues/8068#issuecomment-1214715102

**Comment by bsteph** [comment]
That fixed it for me.  Thanks!!!

**Comment by bsteph** [comment]
Followed steps here: https://github.com/SickChill/SickChill/issues/8068#issuecomment-1214715102
