### ISSUE TITLE
[APP SUBMITTED]: __init__() got an unexpected keyword argument 'language'

### ISSUE THREAD

**Issue by mwhitmel** [SickChill/SickChill#8076]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.8.15
No Log available with ERRORS:
### ERROR
```
Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "F:\\SickChill\\Python3\\tools\\lib\\site-packages\\sickchill\\oldbeard\\providers\\limetorrents.py", line 55, in search\n    data = BeautifulSoup(data, language="xml")\n  File "F:\\SickChill\\Python3\\tools\\lib\\site-packages\\bs4\\__init__.py", line 254, in __init__\n    builder = builder_class(**kwargs)\n  File "F:\\SickChill\\Python3\\tools\\lib\\site-packages\\bs4\\builder\\_lxml.py", line 128, in __init__\n    super(LXMLTreeBuilderForXML, self).__init__(**kwargs)\nTypeError: __init__() got an unexpected keyword argument \'language\'\n'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mwhitmel** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19043-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.8.15
Link to Log: https://gist.github.com/6b791fee9edb1e55b7fb5d77b6bc2d21
### ERROR
```
Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "F:\\SickChill\\Python3\\tools\\lib\\site-packages\\sickchill\\oldbeard\\providers\\limetorrents.py", line 55, in search\n    data = BeautifulSoup(data, language="xml")\n  File "F:\\SickChill\\Python3\\tools\\lib\\site-packages\\bs4\\__init__.py", line 254, in __init__\n    builder = builder_class(**kwargs)\n  File "F:\\SickChill\\Python3\\tools\\lib\\site-packages\\bs4\\builder\\_lxml.py", line 128, in __init__\n    super(LXMLTreeBuilderForXML, self).__init__(**kwargs)\nTypeError: __init__() got an unexpected keyword argument \'language\'\n'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by edwinroos** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.8.15
No Log available with ERRORS:
### ERROR
```
Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "C:\\SickChill\\Python3\\tools\\lib\\site-packages\\sickchill\\oldbeard\\providers\\limetorrents.py", line 55, in search\n    data = BeautifulSoup(data, language="xml")\n  File "C:\\SickChill\\Python3\\tools\\lib\\site-packages\\bs4\\__init__.py", line 254, in __init__\n    builder = builder_class(**kwargs)\n  File "C:\\SickChill\\Python3\\tools\\lib\\site-packages\\bs4\\builder\\_lxml.py", line 128, in __init__\n    super(LXMLTreeBuilderForXML, self).__init__(**kwargs)\nTypeError: __init__() got an unexpected keyword argument \'language\'\n'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
pull request should resolve

**Comment by tmdelia** [comment]
pull did not solve this issue. 

sudo git pull https://github.com/SickChill/SickChill.git
From https://github.com/SickChill/SickChill
 * branch                HEAD       -> FETCH_HEAD
Already up to date.

**Comment by BKSteve** [comment]
It's a branch pull request to add to `develop` and then ` master`
Manual edit file to test or you'll just have to wait

**Comment by mwhitmel** [comment]
Sorry I dont understand. How do I perform a Pull request ? and add develop and master ? Or what I am waiting for ? These are cryptic to end users

**Comment by BKSteve** [comment]
I've done the pull request to fix this but I'm not there one who can authorise an update to `master`

To fix it for yourself now you must edit the code yourself on your system. 
1. Shutdown SC 
2. Go to `~/sickchill/oldbeard/providers/`
3. Edit `limetorrents.py` line 55 and remove ` language =`
4. Save
5. Start SC

**Comment by Sandrus** [comment]
### INFO
Python Version: **3.9.13 (main, Jul 26 2022, 13:12:30) [GCC 10.3.1 20211027]**
Operating System: **Linux-5.15.46-Unraid-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@2022.8.15
Link to Log: https://gist.github.com/5c05ac6359eae4bb7e7f147ffcbecfdc
### ERROR
```
Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/config/.local/lib/python3.9/site-packages/sickchill/oldbeard/providers/limetorrents.py", line 55, in search\n    data = BeautifulSoup(data, language="xml")\n  File "/usr/lib/python3.9/site-packages/bs4/__init__.py", line 257, in __init__\n    builder = builder_class(**kwargs)\n  File "/usr/lib/python3.9/site-packages/bs4/builder/_lxml.py", line 139, in __init__\n    super(LXMLTreeBuilderForXML, self).__init__(**kwargs)\nTypeError: __init__() got an unexpected keyword argument \'language\'\n'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mwhitmel** [comment]
Thanks BKSteve

I appreciate your help !

Matt

**Comment by bluezed** [comment]
### INFO
Python Version: **3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]**
Operating System: **Linux-5.4.0-124-generic-x86_64-with-glibc2.29**
Locale: UTF-8
Branch: **pip**
Commit: SickChill/SickChill@2022.8.15
Link to Log: https://gist.github.com/0cb7eb6d3b8c2e82322f3ec99e0738d8
### ERROR
```
Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/tv/.local/lib/python3.8/site-packages/sickchill/oldbeard/providers/limetorrents.py", line 55, in search\n    data = BeautifulSoup(data, language="xml")\n  File "/home/tv/.local/lib/python3.8/site-packages/bs4/__init__.py", line 252, in __init__\n    builder = builder_class(**kwargs)\n  File "/home/tv/.local/lib/python3.8/site-packages/bs4/builder/_lxml.py", line 128, in __init__\n    super(LXMLTreeBuilderForXML, self).__init__(**kwargs)\nTypeError: __init__() got an unexpected keyword argument \'language\'\n'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
@bluezed yes known issue, see solution above.
