### ISSUE TITLE
post process adds additional " . " to reference file

### ISSUE THREAD

**Issue by herbi3** [SickChill/SickChill#8093]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: latest 2022.08.15
OS:
Browser:
What you did: auto or manual post-processing
What happened: executed python command referencing the moved and renamed file, but had an extra DOT " . " in the extension file name. the post-processor couldn't find the file because it was given "..mkv" instead of just ".mkv"
What you expected: to post process the file after renaming

other programs continue to work well with the post-processor, except for sick chill since latest updates

Logs:
post processor

`2022-08-19 20:21:14 - resources.mediaprocessor - INFO - File M:\Media\TV Shows\Westworld\Season 4\Westworld - S4 E6 - Fidelity..mkv is not valid'

**Comment by herbi3** [comment]
> 2022-08-20 12:51:01 INFO :: POSTPROCESSOR-MANUAL :: Successfully processed 2022-08-20 12:51:01 INFO :: POSTPROCESSOR-MANUAL :: Processing succeeded for M:\Downloads\Downloaded\SickBeard\In the Dark (2019) - S4 E8 - Tequila Mockingbird.mkv AA 2022-08-20 12:51:01 - resources.mediaprocessor - INFO - File M:\Media\TV Shows\In the Dark (2019)\Season 4\In the Dark (2019) - S4 E8 - Tequila Mockingbird..mkv is not valid AA 2022-08-20 12:51:01 - resources.readsettings - WARNING - Force-convert is true, so process-same-extensions is being overridden to true as well AA 2022-08-20 12:51:01 - resources.readsettings - INFO - Loading config file C:\Users\admin\AppData\MP4_Automator\config\autoProcess.ini. AA 2022-08-20 12:51:01 - resources.readsettings - INFO - C:\Python39\python.exe 2022-08-20 12:51:00 INFO :: POSTPROCESSOR-MANUAL :: Executing command: ['C:\\Python39\\python.exe', 'C:\\Users\\Admin\\AppData\\MP4_Automator\\postSickbeard.py', 'M:\\Media\\TV Shows\\In the Dark (2019)\\Season 4\\In the Dark (2019) - S4 E8 - Tequila Mockingbird..mkv', 'M:\\Downloads\\Downloaded\\SickBeard\\In the Dark (2019) - S4 E8 - Tequila Mockingbird.mkv', '347645', '4', '8', '2022-08-01'] 2022-08-20 12:51:00 WARNING :: POSTPROCESSOR-MANUAL :: 347645: Failed to modify date of 'In the Dark (2019) - S4 E8 - Tequila Mockingbird..mkv' 2022-08-20 12:50:59 INFO :: POSTPROCESSOR-MANUAL :: Trying to clean any empty folders under M:\Media\TV Shows\In the Dark (2019)\Season 4 2022-08-20 12:50:59 INFO :: POSTPROCESSOR-MANUAL :: Process method is 'move' and src and destination are on the same device, skipping free space check 2022-08-20 12:50:59 INFO :: POSTPROCESSOR-MANUAL :: This download is marked a priority download so I'm going to replace an existing file if I find one 2022-08-20 12:50:59 INFO :: POSTPROCESSOR-MANUAL :: Processing M:\Downloads\Downloaded\SickBeard\In the Dark (2019) - S4 E8 - Tequila Mockingbird.mkv (None)

**Comment by BKSteve** [comment]
Fixed in develop #8079

**Comment by herbi3** [comment]
seems to still be an issue in develop

**Comment by BKSteve** [comment]
Read #8074
Need to rescan to update database file name references. 
The double is in the database but files are named correctly.
