### ISSUE TITLE
Sickchill service seems to be exiting repeatedly after update

### ISSUE THREAD

**Issue by DrDrewZA** [SickChill/SickChill#8103]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: was up to date - tried to update to latest commit
OS: Wini11
Browser: Edge
What you did: Was working fine, notified me there was an update, so I clicked update in browser instead of using command line
What happened: it killed it 
What you expected:  to update
Logs: - none available - cant get into sickchill to get them

Event viewer shows service exits after starting with event description:
 Program C:\SickChill\Python3\tools\python.exe for service SickChill exited with return code 1.

```
PASTE LOGS HERE
```

**Comment by kyuuk** [comment]
Look at this #8101, you might have the same issue as me

**Comment by DrDrewZA** [comment]
> Look at this #8101, you might have the same issue as me

100% - Im sorted thank you for the assist :)
