### ISSUE TITLE
Update failed ( last 20 commits)

### ISSUE THREAD

**Issue by twinden** [SickChill/SickChill#8105]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Synology DSM 6.2.4-25556 Update 6  (no docker)
Browser: IOS Safari
What you did: Automatic update inside SC, most recent 20 commits.
What happened: Message that SC couldn’t restart after update, and msg to check logs.
What you expected: Update to most recent 20 commits.
There is a [newer version available]  (you're 20 commits behind) — [Update Now]
Logs:
```
WARNING log
 2022-08-23 20:35:48 Unable to open /volume1/NetBackup: PermissionError(13, 'Permission denied') / [Errno 13] Permission denied: '/volume1/NetBackup'

ERROR log
 2022-08-23 23:11:20 Error while trying to update: [Errno 39] Directory not empty: 'network'

```
SickChill Configuration
SickChill Info:
Branch: [master]
Commit: cc9de09d40de432d8d86cd896ec424ab6af0d78d
Database Version: 44.5

  Python Version: 3.8.13 (default, Jul 10 2022, 19:18:08) [GCC 4.9.3 20150311 (prerelease)]

  SSL Version: OpenSSL 1.1.1q 5 Jul 2022

  OS: Linux-3.2.40-i686-with-glibc2.0

**Comment by twinden** [comment]
After a manual restart of Synology, SC doesn’t show “ (you're 20 commits behind) — [Update Now]” anymore.
Neither does “check for updates”.
Is commit: [cc9de09d40de432d8d86cd896ec424ab6af0d78d](https://dereferer.me/?https://github.com/SickChill/SickChill/commit/cc9de09d40de432d8d86cd896ec424ab6af0d78d)
the latest !?

**Comment by twinden** [comment]
If I don’t follow up in a week, and no one else does, please close.

**Comment by Wally73** [comment]
yes that is the latest commit on master (you can check that easily yourself here on github)
