### ISSUE TITLE
Sickchill displaying random 'continuing' dates on older shows

### ISSUE THREAD

**Issue by DrDrewZA** [SickChill/SickChill#8107]
Not sure if its related to the recent update or not, but just noticed that shows (That I think should just say 'continuing') have that, but also a random looking date far back.

Not affecting function afaik - just weird

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
Browser:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by pigsyn** [comment]
I think it's mostly show without upcoming episodes on thetvdb.com, so the last aired  episode date is kept

**Comment by miigotu** [comment]
A show can be continuing, without new episode dates set yet. For example many shows went on a hiatus during COVID, but are not ended or cancelled yet. So they are still continuing, we just don't know when the next season will be.

**Comment by trick77** [comment]
I've noticed this as well. While earlier, the shows just showed up as continuing (which of course is a useful info) without a date in the past, they now also show a date in the past which is a bit misleading. Imagine my surprise noticing a continuation date on one of my favourite shows just to notice later on that the date is actually February 2022, not February 2023. I might submit a PR if I find out why it's happening.

**Comment by trick77** [comment]
Btw. I didn't find out why it was happening but it's been fixed!

**Comment by BKSteve** [comment]
#8275 was almost same issue and #8281 adjusted the sorting logic
