### ISSUE TITLE
Main web page fails to load (blank page) after upgrading Linux to Ubuntu 22.04 (from 20.04)

### ISSUE THREAD

**Issue by knyllers** [SickChill/SickChill#8119]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: tag 2022.7.20
OS: Ubuntu 22.04
Browser: Firefox
What you did: Upgraded Ubuntu 20.04 to 22.04 (with it python from 3.8 to 3.10)
What happened: Sickchill starts, but when browsing to localhost:8081 ablank page is shown and error in log
What you expected: Main sickchill web page to display as usual
Logs:
```
2022-08-28 22:44:01 ERROR :: WEBSERVER :: Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='knyllers-media:8081', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/henrik/.local/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/henrik/.local/lib/python3.10/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/henrik/.local/lib/python3.10/site-packages/sickchill/views/index.py", line 161, in get
    results = yield self.async_call(method)
  File "/home/henrik/.local/lib/python3.10/site-packages/tornado/concurrent.py", line 122, in wrapper
    conc_future = getattr(self, executor).submit(fn, self, *args, **kwargs)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

```

**Comment by pigsyn** [comment]
Is it installed like this ? https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15
If yes you could try:
https://github.com/SickChill/SickChill/discussions/8089

**Comment by knyllers** [comment]
I installed it using: pip3 install -U sickchill==2022.7.20 (Latest release failed to start, possibly due to [https://github.com/SickChill/SickChill/discussions/8089]), so I reverted back to the last working release)
As far as I can see sickchill service starts ok. sudo systemctl status sickchill gives a green light, I can also see that it's checking things in the background, it's seems it's just the web-ui that fails. I can't check it now since I'm at work, I'll provide some more info when home.

**Comment by BKSteve** [comment]
If SC installed before update of Linux then shutdown SC delete venv and restart. Python version changed with Linux update and that's likely the problem.

**Comment by knyllers** [comment]
What is venv and where can I find it?
I did change a path in some file (can't remember which) from python3.8 to python3.10 to get SC to start at all.

Thanks!

**Comment by BKSteve** [comment]
Sorry previous answer from mobile. 
Per @pigsyn mention https://github.com/SickChill/SickChill/discussions/8089#discussioncomment-3422706 

It should be `/opt/sickchill/.venv/` 

If it's not there try to find `find / -type d -name '.venv'` as it's a hidden folder.

**Comment by knyllers** [comment]
Hmm....running `find / -type d -name '.venv'` doesn't find anything on my system...
I have my SC installation in my user.home, not that I think it should matter.

SC is doing background tasks...from the log.

2022-08-29 16:43:55 DEBUG :: FINDPROPERS :: Setting the last Proper search in the DB to 738396
2022-08-29 16:43:55 INFO :: FINDPROPERS :: Completed the search for new propers, next check in approx. 1h, 29m
2022-08-29 16:49:54 DEBUG :: POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2022-08-29 16:49:54 INFO :: POSTPROCESSOR :: Auto post processing task for /home/henrik/Incoming/complete was added to the queue
2022-08-29 16:49:55 INFO :: POSTPROCESSOR-AUTO :: Beginning auto post processing task: /home/henrik/Incoming/complete

status output

henrik@knyllers-media:~$ systemctl status sickchill.service
● sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-08-28 22:43:43 CEST; 18h ago
    Process: 9289 ExecStart=/usr/bin/python3.10 /home/henrik/.local/bin/SickChill.py -q --daemon --nolaunch --datadir=/home/henrik/>
      Tasks: 15 (limit: 9300)
     Memory: 144.7M
        CPU: 5min 41.145s
     CGroup: /system.slice/sickchill.service
             └─9291 /usr/bin/python3.10 /home/henrik/.local/bin/SickChill.py -q --daemon --nolaunch --datadir=/home/henrik/sickchill

Aug 28 22:43:43 knyllers-media systemd[1]: Starting SickChill Daemon...
Aug 28 22:43:43 knyllers-media systemd[1]: Started SickChill Daemon.


So it seems to be running ok, just not the web-ui

**Comment by BKSteve** [comment]
How about `sudo find / -name ".venv"` ?
the .venv could be env or venv too.

You have `/usr/bin/python3.10` but do you have an old `/usr/bin/python3.8` with SC lurking there?

or 
remove SC totally, hunt down all sickchill with `sudo find / -name "sickchill"` and remove them, reinstall, restore back (assume you have one)

**Comment by pigsyn** [comment]
I think SickChill.py in your systemctl unit is from an old installation, entrypoint should be `SickChill` imho

```bash
ls -lh /home/henrik/.local/bin/SickChill*
```
Should only report 1 file

I made a pip install like yours moving from Ubuntu 20.04 to 22.04 breaks it but you just have to reinstall with `pip3 install -U sickchill`A

```
sudo systemctl stop sickchill
vim /etc/systemd/system/sickchill.service
# replace 
ExecStart=/usr/bin/python3.10 /home/henrik/.local/bin/SickChill.py 
# with 
ExecStart=/usr/bin/python3.10 /home/henrik/.local/bin/SickChill
sudo systemctl daemon-reload
sudo systemctl restart sickchill
```

You should consider removing .local and reinstall sickchill with pip (if you don't  have any other personal libs installed there).
You'll need to edit systemctl unit because of the entrypoint change

**Comment by BKSteve** [comment]
Why not update to the latest with `pip3 install -U sickchill` instead of doing `pip3 install -U sickchill==2022.7.20`
Latest version is `2022.8.22.74751`

**Comment by knyllers** [comment]
This is what I get when looking for venv.

henrik@knyllers-media:~$ sudo find / -name "venv"
[sudo] password for henrik: 
find: ‘/run/user/1000/gvfs’: Permission denied
find: ‘/run/user/1000/doc’: Permission denied
/timeshift/snapshots/2022-08-26_14-48-37/localhost/usr/lib/python3.8/venv
/timeshift/snapshots/2022-08-26_14-52-20/localhost/usr/lib/python3.8/venv
/usr/lib/python3.10/venv
/snap/gnome-3-34-1804/77/usr/lib/python3.6/venv
/snap/gnome-3-34-1804/72/usr/lib/python3.6/venv
/snap/core20/1611/usr/lib/python3.8/venv
/snap/core20/1593/usr/lib/python3.8/venv
/snap/gnome-3-28-1804/161/usr/lib/python3.6/venv
/snap/gnome-3-28-1804/145/usr/lib/python3.6/venv
/snap/core18/2409/usr/lib/python3.6/venv
/snap/core18/2538/usr/lib/python3.6/venv
/snap/core/13308/usr/lib/python3.5/venv
/snap/core/13425/usr/lib/python3.5/venv

I removed the ~/.local/bin/SickChill.py and changed the sickchill.service to point to ~/.local/binSickChill
Also removed some old python 3.6 and 3.8 dir in .local.

I've searched for sickchill and it looks ok, just some backup dir I created.
sudo find / -name "sickchill"
find: ‘/run/user/1000/gvfs’: Permission denied
find: ‘/run/user/1000/doc’: Permission denied
/backup/sickchill
/backup/.local/lib/python3.6/site-packages/sickchill
/backup/.local/lib/python3.8/site-packages/sickchill
/home/henrik/sickchill
/home/henrik/.local/lib/python3.10/site-packages/sickchill

I did a new pip3 install -U sickshill. Now it doesn't start at all...:(

henrik@knyllers-media:~$ systemctl status sickchill.service
○ sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Mon 2022-08-29 21:58:43 CEST; 5min ago
    Process: 4853 ExecStart=/usr/bin/python3.10 /home/henrik/.local/bin/SickChill -q --daemon --nolaunch --datadir=/home/henrik/sic>
        CPU: 1.464s

Aug 29 21:58:42 knyllers-media systemd[1]: Starting SickChill Daemon...
Aug 29 21:58:42 knyllers-media systemd[1]: Started SickChill Daemon.
Aug 29 21:58:43 knyllers-media systemd[1]: sickchill.service: Deactivated successfully.
Aug 29 21:58:43 knyllers-media systemd[1]: sickchill.service: Consumed 1.464s CPU time.

This is what the sickchill.service look like, perhaps something funky in there?

[Unit]
Description=SickChill Daemon
Wants=network-online.target
After=network-online.target

[Service]
User=henrik
Group=henrik

Type=forking
GuessMainPID=no
ExecStart=/usr/bin/python3.10 /home/henrik/.local/bin/SickChill -q --daemon --nolaunch --datadir=/home/henrik/sickchill

[Install]
WantedBy=multi-user.target

**Comment by knyllers** [comment]
I removed the data directory /home/henrik/sickchill. Now it starts. So I tried to restore from backup I made before upgrade to ubuntu 22.04. Restore is successful, but restarting fails.

From log:
2022-08-29 22:13:01 INFO :: EVENT-QUEUE :: Restarting SickChill with ['/usr/bin/python3.10', '/home/henrik/.local/lib/python3.10/site-packages/SickChill.py', '-q', '--daemon', '--nolaunch', '--datadir=/home/henrik/sickchill']
2022-08-29 22:13:02 INFO :: MAIN :: Restore: restoring cache successful
2022-08-29 22:13:02 INFO :: MAIN :: Restore: Unable to remove the cache/mako directory: [Errno 2] No such file or directory: '/home/henrik/sickchill/cache/mako'

**Comment by knyllers** [comment]
data directory looks like:

henrik@knyllers-media:~$ ll sickchill/
total 4880
drwxr--r--  5 henrik henrik    4096 Aug 29 22:13 ./
drwxr-xr-x 28 henrik henrik    4096 Aug 29 22:15 ../
drwxrwxrwx  3 henrik henrik    4096 Aug 29 22:12 cache/
drwxrwxrwx  2 henrik henrik    4096 Aug 29 22:13 cache-20220829_221302/
-rw-rw-rw-  1 henrik henrik 1426432 Aug 29 22:12 cache.db
-rw-r--r--  1 henrik henrik  294912 Aug 29 22:11 cache.db.bak-20220829_221302
-rw-rw-rw-  1 henrik henrik   34948 Aug 29 22:12 config.ini
-rw-rw-rw-  1 henrik henrik   27948 Aug 29 22:12 config.ini.bak-20220829_221302
-rw-rw-rw-  1 henrik henrik   21504 Aug 29 22:12 failed.db
-rw-r--r--  1 henrik henrik   16384 Aug 29 22:11 failed.db.bak-20220829_221302
drwxrwxrwx  2 henrik henrik    4096 Aug 29 22:11 Logs/
-rw-rw-rw-  1 henrik henrik 2890752 Aug 29 22:12 sickchill.db
-rw-r--r--  1 henrik henrik   81920 Aug 29 22:11 sickchill.db.bak-20220829_221302
-rw-r--r--  1 henrik henrik   81920 Aug 29 22:11 sickchill.db.v44.3
-rw-r--r--  1 henrik henrik   81920 Aug 29 22:11 sickchill.db.v44.4

**Comment by miigotu** [comment]
Any time there is an error, it's best to try starting SC without --quiet, -q, --daemon, or -d, directly in shell so you can see exactly what is happening.

What is the output from this? (Also, make sure to temporarily change ssl_verify=0 to ssl_verify=1 in your config.ini, that's potentially why you are failing to start?)

```bash
cp -R /home/henrik/sickchill /home/henrik/sickchill_backup
python3.10 /home/henrik/.local/lib/python3.10/site-packages/SickChill.py --datadir=/home/henrik/sickchill
```

**Comment by miigotu** [comment]
@BKSteve when installed with pip there is no venv created, because we don't need to poetry install dependencies when they are already installed when they did pip install.

**Comment by knyllers** [comment]
> Any time there is an error, it's best to try starting SC without --quiet, -q, --daemon, or -d, directly in shell so you can see exactly what is happening.
> 
> What is the output from this? (Also, make sure to temporarily change ssl_verify=0 to ssl_verify=1 in your config.ini, that's potentially why you are failing to start)
> 
> ```shell
> cp -R /home/henrik/sickchill /home/henrik/sickchill_backup
> python3.10 /home/henrik/.local/lib/python3.10/site-packages/SickChill.py --datadir=/home/henrik/sickchill
> ```

I'll assume I can use 'python3.10 /home/henrik/.local/lib/python3.10/site-packages/SickChill' instead of the '.py' file, since I deleted that...:)

Will try it this evening...thanks a bunch!

**Comment by knyllers** [comment]
> 

This sorted it...now it starts and restored backup works. So, thank you very much for your help. Much appreciated.
Starting with ssl_verify caused this:
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.

Setting ssl_verify = 1 starts successfully.

You said to temporarily set ssl_verify = 1. So what to do now? just setting it back to 0 will just fail the startup again...

Cheers!
/Henrik

**Comment by miigotu** [comment]
> > 
> 
> This sorted it...now it starts and restored backup works. So, thank you very much for your help. Much appreciated. Starting with ssl_verify caused this: ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.
> 
> Setting ssl_verify = 1 starts successfully.
> 
> You said to temporarily set ssl_verify = 1. So what to do now? Setting it back to 0 will just fail the startup again...
> 
> Cheers! /Henrik

If you are on master or develop or the tests branch and fully updated it works with ssl_verify=0 too. 

It took me 3 different fixes to get it actually fixed because of the strange way urllib does it's check. It was fixed 17 hours ago, just not tagged as a release yet:

https://github.com/SickChill/SickChill/commit/d7a607d07bf6fced98b705216e8a810e98e76d49
