### ISSUE TITLE
Schedule does not show in local time

### ISSUE THREAD

**Issue by Yoshi900** [SickChill/SickChill#8128]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: v2022.08.29
OS: server 2016
Browser: Chrome
What you did: change the interface to "local" for timezone
What happened: time is still in network 
What you expected: the time to be in my local time so I know when to search for episode. 
Logs:
```
PASTE LOGS HERE
```

**Comment by kyuuk** [comment]
Hello @Yoshi900, can you show me where you did the change.

and also, is the date/time at the bottom of the page in SC right ?

**Comment by Yoshi900** [comment]
the time is the local time for me 
![image](https://user-images.githubusercontent.com/12824013/188593434-3988eacc-254c-4631-9522-1956bcdc6411.png)

![image](https://user-images.githubusercontent.com/12824013/188593742-7fcd4718-28e0-4711-9b99-72ceb9fccd65.png)

General > interface 
![image](https://user-images.githubusercontent.com/12824013/188593923-34882485-0e5d-47ad-b33b-6ff8897952f8.png)


it used to be that these episodes would be around the local time of 10:00am or towards midday rather than at the 8-10pm timezones. 

I am in GMT + 10

does that help?

**Comment by kyuuk** [comment]
can you give an example of a show that does not have the right time, i will try it.

**Comment by Yoshi900** [comment]
Yeah sure. 
Here are 3 from a screenshot
![Screenshot_20220907-072656](https://user-images.githubusercontent.com/12824013/188743466-e683bd7f-2e94-46ba-a49c-0ead4eeffbbb.png)

**Comment by mrc013** [comment]
I am also having this issue but OS: Server 2022

**Comment by miigotu** [comment]
The only thing I can think of is that if there is an exception when converting the time, we fall back to the original time.

**Comment by pigsyn** [comment]
It's not giving correct localtime with SIckChill Installer or a pip install for win11 or Server 2022
Works with a local python 3.9 install and poetry run.

Even works with nssm

**Comment by miigotu** [comment]
> It's not giving correct localtime with SIckChill Installer or a pip install for win11 or Server 2022
> Works with a local python 3.9 install and poetry run on develop, master is also not giving correct localtime
> 

Then it is a bug in dateutil

**Comment by miigotu** [comment]
Our whole timezones parsing junk needs ripped out and rewritten.

**Comment by Yoshi900** [comment]
good so i am not going insane :) I will wait for the update then :) 

thanks.

**Comment by pigsyn** [comment]
Is windows package out yet ? Should be resolved in 2022.9.14

**Comment by miigotu** [comment]
Pip install -U works on windows, or reinstall with the installer, or use the built in updater

**Comment by pigsyn** [comment]
@Yoshi900 what's up in GMT +10 ? 😆

**Comment by Yoshi900** [comment]
Hi, 
After freaking out and having to use my backup I have upgraded to the newest version (using windows installer rather than "pip -m install -U Sickchill" (for some reason it didnt find an update but I am sure that @miigotu will fix it one day after his urgent issues are sorted out) 

![image](https://user-images.githubusercontent.com/12824013/190531224-2324e259-cfad-4c98-bb3e-1184bb509a50.png)

![image](https://user-images.githubusercontent.com/12824013/190531269-6e4dd16f-4dd2-4113-81f8-44f6baaec7ab.png)


so looking like this is working as expected now :) thanks. this issue can be closed.
