### ISSUE TITLE
building 'dulwich._objects' extension ends with "error: Microsoft Visual C++ 14.0 or greater is required."

### ISSUE THREAD

**Issue by MrHappy** [SickChill/SickChill#8133]
When I try to start sickchill (latest version) it crashed with the error in the log.
I installed the latest version from the link mentioned in the log.

Branch/Commit: commit b2b09e3720a5e1b4af3d88a165fa8f97d0a44593 (HEAD -> master, tag: 2022.8.30, origin/master, origin/HEAD)
OS: Windows 10
Browser: -
What you did: (re)started sickchill
What happened: it didn't start
What you expected: it to start
Logs:
```
  building 'dulwich._objects' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

**Comment by miigotu** [comment]
Looks like you aren't using the windows installer, which means you should know how to install dependencies (even SC is going to stop installing its own dependencies,, you should learn how to do this now before develop is merged)

You can download and install the dulwich wheel from here https://www.lfd.uci.edu/~gohlke/pythonlibs/#dulwich

**Comment by MrHappy** [comment]
Installed the whl from there, but I still get the same error.

**Comment by Xx-Ness-xX** [comment]
> Installed the whl from there, but I still get the same error. However running: `pip3 install -U sickchill `fixed it 👍

Running `pip3 install -U sickchill` fixed for me as well
Thank you ❤️
