### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/sickchill/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014B41CC5070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

### ISSUE THREAD

**Issue by tanjd** [SickChill/SickChill#8134]
### INFO
Python Version: **3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19044-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.8.29
Link to Log: https://gist.github.com/d3963d6a3fa238d774605d31153b5683
### ERROR
```
Exception generated in thread CHECKVERSION: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/sickchill/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014B41CC5070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by kyuuk** [comment]
seems like a DNS problem, 

do you have this log every time you check for update @tanjd ?

**Comment by BKSteve** [comment]
Check your firewall/s and allow `pypi` through
