### ISSUE TITLE
Sickchill start with command line but not in Synology package center

### ISSUE THREAD

**Issue by Lifferman** [SickChill/SickChill#8140]
Hi,
I'm on DSM 7.1-42661 Update 4, i got some problem with sickchill so i decided to reinstall.

When i install from Package center, it say launched, then, after 1 min, say it's stopped.
But i can launch it by doing:
`sudo -u sc-sickchill /bin/bash`
`/volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --config /volume1/@appdata/sickchill/data/config.ini --datadir /volume1/@appdata/sickchill/data
`

I don't have logs in  /var/logs/packages/sichchill.log
and in  /volume1/@appdata/sickchill/data/Logs/sickchill.log i only have those when i use command line, even in debug mode

I don't know if it's related to the problem that prompted me to reinstall: when the search for the desired episode started, sickchill crashed without logs, even in debug...

thanks

**Comment by kyuuk** [comment]
might be the same as here https://github.com/SickChill/SickChill/issues/8126

**Comment by BKSteve** [comment]
If you have the logs of when you ran the ssh start please post.

tracing why DSM and SC kicks to and creates `.venv` when it should try again with `env` which was writable.

**Comment by Lifferman** [comment]
No sorry, i don't saved it...

**Comment by BKSteve** [comment]
#8160  is work around for synology.

**Comment by caramdache** [comment]
> #8160 is work around for synology.

Where is #8160?

**Comment by caramdache** [comment]
> might be the same as here https://github.com/SickChill/SickChill/issues/8126

#8126 has been deleted.

**Comment by miigotu** [comment]
This thread is not how to do it. There are packages built now that work

https://github.com/SickChill/sickchill/discussions/8247
