### ISSUE TITLE
SickChill won't start after Ubuntu Updates

### ISSUE THREAD

**Issue by asbestinuS** [SickChill/SickChill#8146]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)
I cant because SickChill won't start again. Where might I find the latest logs? The last entries under /sickchill/Logs are:

_22-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the REFRESH thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR-AUTO thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the NOTIFICATIONS thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2022-09-06 00:30:24 INFO :: EVENT-QUEUE :: Saving all shows to the database
2022-09-06 00:30:25 INFO :: EVENT-QUEUE :: Saving config file to disk
2022-09-06 00:30:26 INFO :: EVENT-QUEUE :: Shutting down Tornado_

Branch/Commit: latest stable (how can I find out which one excatly if SickChill won't start?)
OS: Ubuntu Server 22.04.1 LTS (GNU/Linux 5.15.0-47-generic x86_64)
Browser: Any
What you did: updated the os with apt update && apt upgrade -y and let it run. Ubuntu asked to restart certain services which I did. After that I restarted the machine because a newer kernel was installed and it told me I should consider a reboot. Which I did.
What happened: After the reboot, SickChill didn't start, so I tried manually starting it with _systemctl start sickchill_. It started but it immediately "deactivated" itself again.
What you expected: SickChill surviving Linux Updates
Logs:
```
○ sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor pre>
     Active: inactive (dead) since Tue 2022-09-06 14:55:28 UTC; 3s ago
    Process: 4826 ExecStart=/usr/bin/python3.10 /storage/sickchill/SickChill.py>
        CPU: 3.314s

Sep 06 14:55:24 download systemd[1]: Starting SickChill Daemon...
Sep 06 14:55:24 download systemd[1]: Started SickChill Daemon.
Sep 06 14:55:28 download systemd[1]: sickchill.service: Deactivated successfull>
Sep 06 14:55:28 download systemd[1]: sickchill.service: Consumed 3.314s CPU tim>
```
Can someone help me? I more or less followed these install instructions here a few months ago: https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15
and it worked pretty well until the recent os updates.

Edit:
I found the possible issue. But how might I be able to fix it? I checked what updates actually did install in /var/log/apt/history.log

Start-Date: 2022-09-06  00:20:34
Commandline: apt upgrade
Requested-By: max (1000)
Upgrade: libglx-mesa0:amd64 (22.0.1-1ubuntu2.1, 22.0.5-0ubuntu0.1), python3-distupgrade:amd64 (1:22.04.11, 1:22.04.13), apt:amd64 (2.4.6, 2>
End-Date: 2022-09-06  00:29:17

I think the python3-distupgrade might be responsible for the problem. How can I rollback the python version?

Thank you

**Comment by pigsyn** [comment]
Don't rollback python3-distupgrade it's for system updates.

Could you confirm what user and parameters you are using in /etc/systemd/system/sickchill.service ?
If you are running with user sickchill you could run sickchill manually to check for errors:

```
sudo su - sickchill -s /bin/bash
cd /storage/sickchill
# set datadir to your current configuration
/usr/bin/python3.10 /storage/sickchill/SickChill.py --datadir=/path/to/your/datadir
```
And report errors.

Could be a venv issue.
https://github.com/SickChill/SickChill/discussions/8089

**Comment by asbestinuS** [comment]
Hello pigsyn, thank you for your reply.
These are the settings in /etc/systemd/system/sickchill.service
```
[Unit]
Description=SickChill Daemon
Wants=network-online.target
After=network-online.target

[Service]
User=sickchill
Group=gr_download

Type=forking
GuessMainPID=no
ExecStart=/usr/bin/python3.10 /storage/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/storage/sickchill

[Install]
WantedBy=multi-user.target
```
And the following is the output of your code:
```
max@download:/storage/sickchill$ sudo su - sickchill -s /bin/bash
sickchill@download:~$ cd /storage/sickchill
sickchill@download:/storage/sickchill$ /usr/bin/python3.10 /storage/sickchill/SickChill.py --datadir=/storage/sickchill
Checking poetry
Can write to /var/lib/sickchill/.local/lib/python3.10/site-packages: False
Can write to /usr/local/lib/python3.10/dist-packages: False
Current environment is not writable!
Restarting SickChill with ['/storage/sickchill/.venv/bin/python3.10', '/storage/sickchill/SickChill.py', '--datadir=/storage/sickchill']
Checking poetry
Can write to /var/lib/sickchill/.local/lib/python3.10/site-packages: False
Can write to /storage/sickchill/.venv/lib/python3.10/site-packages: True
pip installed: True
pip args: /storage/sickchill/.venv/bin/python3.10 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed
["No module named 'poetry_date_version_plugin'"]
Unable to install to the existing virtual environment located at /storage/sickch                                                                        ill/.venv
Please check the permissions, and that it does not include global site packages
sickchill@download:/storage/sickchill$

```
Definitely looks like the issue you mentioned. Should I try your proposed solution?
```
sudo rm -rf /opt/sickchill/.venv/
sudo chown -R sickchill:sickchill /opt/sickchill/
sudo systemctl restart sickchill
sudo systemctl status sickchill
```
(using my gr_download group instead of the sickchill group)

Thank you!

**Comment by pigsyn** [comment]
sudo apt install python3-pip should solve this.

Previous error is a poetry 1.2.0 issue but I can't reproduce on linux only on windows 🤔

**Comment by asbestinuS** [comment]
Yes! That did it! At least the manual start is fine now.
But..sadly, I I run it again as a service it's again not working. I also restarted the service twice.

```
2022-09-06 17:43:19 INFO :: EVENT-QUEUE :: Shutting down Tornado
sickchill@download:/storage/sickchill$ exit
logout
max@download:/storage/sickchill$ sudo systemctl restart sickchill
max@download:/storage/sickchill$ sudo systemctl status sickchill
○ sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2022-09-06 17:45:19 UTC; 11s ago
    Process: 6550 ExecStart=/usr/bin/python3.10 /storage/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/storage/sickchill (code=exited, status=0/SUCCESS)
        CPU: 3.183s

Sep 06 17:45:15 download systemd[1]: Starting SickChill Daemon...
Sep 06 17:45:15 download systemd[1]: Started SickChill Daemon.
Sep 06 17:45:19 download systemd[1]: sickchill.service: Deactivated successfully.
Sep 06 17:45:19 download systemd[1]: sickchill.service: Consumed 3.183s CPU time.
max@download:/storage/sickchill$ sudo systemctl status sickchill
○ sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2022-09-06 17:45:19 UTC; 1min 10s ago
    Process: 6550 ExecStart=/usr/bin/python3.10 /storage/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/storage/sickchill (code=exited, status=0/SUCCESS)
        CPU: 3.183s

Sep 06 17:45:15 download systemd[1]: Starting SickChill Daemon...
Sep 06 17:45:15 download systemd[1]: Started SickChill Daemon.
Sep 06 17:45:19 download systemd[1]: sickchill.service: Deactivated successfully.
Sep 06 17:45:19 download systemd[1]: sickchill.service: Consumed 3.183s CPU time.
max@download:/storage/sickchill$ sudo systemctl restart sickchill
max@download:/storage/sickchill$ sudo systemctl status sickchill
○ sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2022-09-06 17:46:36 UTC; 13s ago
    Process: 6576 ExecStart=/usr/bin/python3.10 /storage/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/storage/sickchill (code=exited, status=0/SUCCESS)
        CPU: 3.299s

Sep 06 17:46:32 download systemd[1]: Starting SickChill Daemon...
Sep 06 17:46:32 download systemd[1]: Started SickChill Daemon.
Sep 06 17:46:36 download systemd[1]: sickchill.service: Deactivated successfully.
Sep 06 17:46:36 download systemd[1]: sickchill.service: Consumed 3.299s CPU time.
max@download:/storage/sickchill$
```
Is there anything else I could try? Thanks again for your help so far.

**Comment by pigsyn** [comment]
Given the mess with the previous error with pip not installed I would remove the .venv directory again

**Comment by asbestinuS** [comment]
Hello,
I don't get it. After I did the env deletion again, everything seemed to be working.
```
max@download:/storage/sickchill$ sudo systemctl status sickchill
● sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-09-06 18:02:51 UTC; 4min 59s ago
    Process: 6627 ExecStart=/usr/bin/python3.10 /storage/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/storage/sickchill (code=exited, status=0/SUCCESS)
      Tasks: 16 (limit: 19068)
     Memory: 460.2M
        CPU: 43.452s
     CGroup: /system.slice/sickchill.service
             └─6639 /storage/sickchill/.venv/bin/python3.10 /storage/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/storage/sickchill

Sep 06 18:02:51 download systemd[1]: Starting SickChill Daemon...
Sep 06 18:02:51 download systemd[1]: Started SickChill Daemon.
```
The service ran about 5 minutes without issue and I could access the web interface again.

Then I orderly shut down sickchill with `sudo systemctl status sickchill` and deleted the vm snapshot I created prior to all the tinkering.
And after the snapshot was deleted the bloody service wont start up again.

```
max@download:/storage/sickchill$ sudo systemctl stop sickchill
max@download:/storage/sickchill$ sudo systemctl status sickchill
○ sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2022-09-06 18:08:08 UTC; 3s ago
    Process: 6627 ExecStart=/usr/bin/python3.10 /storage/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/storage/sickchill (code=exited, status=0/SUCCESS)
        CPU: 43.509s

Sep 06 18:02:51 download systemd[1]: Starting SickChill Daemon...
Sep 06 18:02:51 download systemd[1]: Started SickChill Daemon.
Sep 06 18:07:57 download systemd[1]: Stopping SickChill Daemon...
Sep 06 18:08:08 download systemd[1]: sickchill.service: Deactivated successfully.
Sep 06 18:08:08 download systemd[1]: Stopped SickChill Daemon.
Sep 06 18:08:08 download systemd[1]: sickchill.service: Consumed 43.509s CPU time.
max@download:/storage/sickchill$ sudo systemctl start sickchill
max@download:/storage/sickchill$ sudo systemctl status sickchill
○ sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2022-09-06 18:10:54 UTC; 27s ago
    Process: 6799 ExecStart=/usr/bin/python3.10 /storage/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/storage/sickchill (code=exited, status=0/SUCCESS)
        CPU: 3.304s

Sep 06 18:10:51 download systemd[1]: Starting SickChill Daemon...
Sep 06 18:10:51 download systemd[1]: Started SickChill Daemon.
Sep 06 18:10:54 download systemd[1]: sickchill.service: Deactivated successfully.
Sep 06 18:10:54 download systemd[1]: sickchill.service: Consumed 3.304s CPU time.
```
What is happening? I'm going to retrace/redo the steps I did already again, hopefully it will work again then.

Thank you again so far

**Comment by pigsyn** [comment]
> I don't get it. After I did the env deletion again, everything seemed to be working.

That's nice

> Then I orderly shut down sickchill with `sudo systemctl status sickchill` and deleted the vm snapshot I created prior to all the tinkering.
Yeah but does that include installing python3-pip and removing /storage/sickchill/.venv ?

**Comment by asbestinuS** [comment]
> Yeah but does that include installing python3-pip and removing /storage/sickchill/.venv ?

It should...deleting the snapshot will make the current state the de-facto state. But I will recheck. I had 2 snapshots, maybe I deleted the wrong one firsdt or something. Thanks ;D

**Comment by asbestinuS** [comment]
Okay, I rechecked everything. I think I had to re-delete .venv , because python3-pip was still installed.
Now it appreas to be working again without issue!

Thank you very much, kind sir. In the future I will never update my vms without doing a snapshot beforehand :)
The Issue is resolved.

The only thing that may be interesintg is what caused this issue. I'm kind of uncertain if I want to update SickChill right now. I'm glad it's working again ;)
Apparently I'm 104 commits behind. So just for completion's sake I'm currently running:

Branch: master
Commit: d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5
Version: 2022.07.20
Database Version: 44.5

**Comment by pigsyn** [comment]
It's complicated, git installs with virtual python environments gets broken when python versions are upgraded (from 3.8 or 9 to 3.10) when upgrading distros from Ubuntu 20.04 LTS to 22.04 LTS for example.

Or when python3-pip is not in prerequisite from a 7 year old install guide.
Or when users are running stuff with root

I do a lot of OSINT stuff with python tools, it's not specific to SickChill, when you use virtual environments and a core component gets upgraded like python itself, everything breaks and you have to manually fix it.

That's why **git installs** are not recommended I guess, going forward maybe poetry will be more reliable ? 
(should be in next release, but needs to be documented)
Because it's easier to specify a previous version of a pip package or a docker image than fixing a broken virtual environment.

> Apparently I'm 104 commits behind. So just for completion's sake I'm currently running:

That's not good there are big issues on master with Nyaa and custom rss providers, but there is also a log of bugs fixed in between. It's also hard to track "current issues" on github.
https://github.com/SickChill/SickChill/compare/d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5..master
