### ISSUE TITLE
Pip update to latest version

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#8148]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:Install: pip
Version: v2022.08.29
OS: Windows 10
Browser: Edge
What you did: Noted a later version on the Code tab V2022.08.30. Selected "Check for Update"
What happened: "No update needed" message returned
What you expected: Prompt to update to later version

I have been following with interest the thread regarding the problem with not being able to obtain latest versions of shows as a problem which has been fixed. [#8132](https://github.com/SickChill/SickChill/issues/8132#issue-1358807686)

Since this fix does not yet seem to be available to me, do I have any options other than to continue with manually downloading the NZB files?

Thank you

**Comment by miigotu** [comment]
That fix is not in a released version, it is only on the develop branch because there are a lot of other updates that are going to break people's install. We need to complete guides and wikis and information about it before we make a release, and push a release that disables to automatic updater before that release (to avoid breaking people's install without them being forewarned)

**Comment by DravenSA** [comment]
Maybe I am just stupid and dumb here, but the snatching of episodes is like the entire point of sickchill, And I am seeing several comments and then then closed issues with it claiming to be "Fixed" , Yet how many people are still not able to snatch NZB files.

This problem was fixed a few weeks ago, then it broke again and hasn't worked since. So although i appreciate that it is all to do with coding, surely taking a step backward might just be the way forward?
"We need to complete guides and wikis and information about it before we make a release"

Surely this is just delaying the fix, and i am sure it is upsetting a lot of people, and I think i can talk for just about everyone on pip version when i say "we appreciate all your work, but it is getting confusing for all the different "branches" "Forks", versions etc etc"

I see there are a lot of other issues opened too, but like i said in the beginning, snatching is the primary reason for sickchiil, so should that not be the main priority? or is pip just not that important?, Can windows users install something else like Master Branch or whatever thing makes Sickchill snatch. 

Less Rage More Chill?, not right now it seems.

Not having a go... just pointing out some feelings.

**Comment by DravenSA** [comment]
> ### Before submitting your issue:
> Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)
> 
> Branch/Commit:Install: pip Version: v2022.08.29 OS: Windows 10 Browser: Edge What you did: Noted a later version on the Code tab V2022.08.30. Selected "Check for Update" What happened: "No update needed" message returned What you expected: Prompt to update to later version
> 
> I have been following with interest the thread regarding the problem with not being able to obtain latest versions of shows as a problem which has been fixed. [#8132](https://github.com/SickChill/SickChill/issues/8132#issue-1358807686)
> 
> Since this fix does not yet seem to be available to me, do I have any options other than to continue with manually downloading the NZB files?
> 
> Thank you

So this might not be the right way to fo this but, this is how i got my NZB's to be snatched automatically again.

I found the sickchill folder in the python3 folder, my path was
C:\SickChill\Python3\tools\Lib\site-packages\sickchill
I backed up the contents of the folder
I then downloaded the contents of
https://github.com/SickChill/SickChill
on that page go to Code and select Download Zip
in the zip file look for SickChill-master\sickchill
you will need the contents of the sickchill folder
Stopped Sickchill running on pc
deleted the contents of C:\SickChill\Python3\tools\Lib\site-packages\sickchill
replaced with the contents from the SickChill-master\sickchill that was in the zip file you downloaded
rebooted the pc 

and low and behold, it snatched NZBs again

Might not work for everyone, but it worked for me until the fix can be properly applied to windows pip version.

**Comment by miigotu** [comment]
> > ### Before submitting your issue:
> > Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)
> > 
> > Branch/Commit:Install: pip Version: v2022.08.29 OS: Windows 10 Browser: Edge What you did: Noted a later version on the Code tab V2022.08.30. Selected "Check for Update" What happened: "No update needed" message returned What you expected: Prompt to update to later version
> > 
> > I have been following with interest the thread regarding the problem with not being able to obtain latest versions of shows as a problem which has been fixed. [#8132](https://github.com/SickChill/SickChill/issues/8132#issue-1358807686)
> > 
> > Since this fix does not yet seem to be available to me, do I have any options other than to continue with manually downloading the NZB files?
> > 
> > Thank you
> 
> So this might not be the right way to fo this but, this is how i got my NZB's to be snatched automatically again.
> 
> I found the sickchill folder in the python3 folder, my path was
> C:\SickChill\Python3\tools\Lib\site-packages\sickchill
> I backed up the contents of the folder
> I then downloaded the contents of
> https://github.com/SickChill/SickChill
> on that page go to Code and select Download Zip
> in the zip file look for SickChill-master\sickchill
> you will need the contents of the sickchill folder
> Stopped Sickchill running on pc
> deleted the contents of C:\SickChill\Python3\tools\Lib\site-packages\sickchill
> replaced with the contents from the SickChill-master\sickchill that was in the zip file you downloaded
> rebooted the pc 
> 
> and low and behold, it snatched NZBs again
> 
> Might not work for everyone, but it worked for me until the fix can be properly applied to windows pip version.

Please don't do that. It's not going to fix the issue. Master is broken. Windows installer uses pip, not git.

**Comment by miigotu** [comment]
Also, there is one fork https://github.com/SickChill/SickChill, and two main branches master and develop.

**Comment by skydiverscott** [comment]
@miigotu What many of us need is guidance on how to use the fork to fix our Windows Installer installations

**Comment by miigotu** [comment]
There is no fork. And there is nothing for you to do until the next release. If it needs to be that much faster you guys could contribute some pull requests or something, because I don't have 12 hours a day to spend on this like I used to.

**Comment by nydave69** [comment]
I spent the last 4 days and cannot get SickChill to run on windows no matter what I try...
and that's for both master or develop...

I'm not a programmer,  did my best effort...

**Comment by miigotu** [comment]
> I spent the last 4 days and cannot get SickChill to run on windows no matter what I try...
> and that's for both master or develop...
> 
> I'm not a programmer,  did my best effort...
>  

Which is why we said to wait. It should be done in a few days.

**Comment by daksteter** [comment]
> > I spent the last 4 days and cannot get SickChill to run on windows no matter what I try...
> > and that's for both master or develop...
> > I'm not a programmer,  did my best effort...
> 
> Which is why we said to wait. It should be done in a few days.

Thank you for your efforts, people just need to be patient, they can manually do something for a couple days it won't kill them lol.  I would do some PRs but I'm a C# person not a Python guy--I will however sign up for the Patreon if that helps at all?

**Comment by miigotu** [comment]
Always helps, thanks.

**Comment by pigsyn** [comment]
2022.9.14 is out

**Comment by DravenSA** [comment]
Sorry to say, the issue has not been fixed. I updated, and it it wouldn't snatch, so i have downgraded back to my little hack, that I was told not to do, but it works for me, 2022.9.14 I was hoping would be the light at the end of the tunnel, but it is not. I see there is another opened issue, where i belive it is the same problem #8169
