### ISSUE TITLE
Starts and stops - synology sickchill 20211110-4

### ISSUE THREAD

**Issue by FaiqH** [SickChill/SickChill#8150]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 20211110-4
OS: DSM 7.1.1-42962
Browser: Chorme
What you did: --
What happened:--
What you expected:
Logs:
```
Thu Sep  8 10:09:01 MDT 2022
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appdata/sickchill/sickchill.pid --config /volume1/@appdata/sickchill/data/config.ini --datadir /volume1/@appdata/sickchill/data
Writing PID: 31934 to /volume1/@appdata/sickchill/sickchill.pid

```

I am new to this so I apologize in advance.
I updated SC via the web interface.
SC would start and then stop. Nothing in the logs execept that is started then stopped.
I removed it all and reinstalled. Same issue.
I updated my DSM from 6.4 to 7.1
installed it again. Same issue.
I looked at the issues and followed them, even using SSH and installing manually, even using pip. Same issue.
The service starts then stops.
It's been over 13 hours and I am at wits end drawing at straws.

**Comment by FaiqH** [comment]
I give up.
It is similar to bug 8090 but even a clean install does not work.
I don't even see logs.

**Comment by BKSteve** [comment]
Hopefully when you ssh you follow the wiki guide so it didn't mess up the ownership of files. https://github.com/SickChill/SickChill/wiki/Synology

Look at #8126 first as it's probably that but also #8143

**Comment by FaiqH** [comment]
I did do it like the wiki instructed. And read your comment on how to nuke all SC before reinstalling. No success.

I had those issue before and remember discovering with everyone the permissions.
I thought it was resolved with this build.
Anyways I tried doing the permissions again and same result. 

For some reason SC does not want to stay running, it loads and then stops. Random intervals. No logs. I originally thought it was a python issue or even the fact that I am now on DSM 7.

I will try cleaning up all of SC and trying via SSH. I usually do it as admin.

Thanks.

**Comment by Thullie** [comment]
I have the same problem with sc after i installed the sc last updates.  Worked fine before the updates
**`There is a newer version available (you're xx commits behind) — Update Now**

can start sc but after like 5 min it stops on my  synology ( DSM 7 )
Only see a start and stop msg in my log file

**Comment by BKSteve** [comment]
If you run SC as sudo on DSM you can also damage the Python install

**Comment by Apfelstruhdl** [comment]
I have a similar problem. It was running fine for some time now and stopped working end of August. I run it on a DS414 with DSM 7.0.1-42218 Update 5. I reinstalled python 3.8 and sickchill.

If I ssh to the NAS and run sickchill as describd in the wiki, I get the following output. I think it hints at problems with packages to be installed and compiled?
https://pastebin.com/TfTtsedc

**Comment by BKSteve** [comment]
Current develop kicks at ` "/volume1/@appstore/sickchill/share/SickChill/sickchill/init_helpers.py", line 156, in get_current_version
    result = subprocess.run(["poetry", "version", "-s"], capture_output=True, text=True)`

As there is a way to get past `cleo` and `poetry_date_version_plugin` and that can leave you running at the old 20211110-4 installed version.

**Comment by Apfelstruhdl** [comment]
@BKSteve, sorry, I didn't get your suggestion, if it was directed to me.

**Comment by BKSteve** [comment]
Sorry, not a suggestion. A comments so that people know this is being worked on. Double checking a step by step procedure (a little complex) to get things up and running on develop from a new install. 
People can then choose to try some reduced set to see if they can get going from where they are but a full procedure from a fresh install will be usable for all.

**Comment by miigotu** [comment]
> Current develop kicks at ` "/volume1/@appstore/sickchill/share/SickChill/sickchill/init_helpers.py", line 156, in get_current_version
>     result = subprocess.run(["poetry", "version", "-s"], capture_output=True, text=True)`
> 
> As there is a way to get past `cleo` and `poetry_date_version_plugin` and that can leave you running at the old 20211110-4 installed version.

Yeah that will be removed. Shouldn't be calling poetry from inside SC at all.

**Comment by FaiqH** [comment]
updating poetry as instructed in the other issue resulted in a fail, here are the logs:
`
2022/09/08 14:09:24 upgrade sickchill 20211110-4 Begin start-stop-status stop
2022/09/08 14:09:24 upgrade sickchill 20211110-4 End start-stop-status stop ret=[0]
2022/09/08 14:09:26 upgrade sickchill 20211110-4 Begin preupgrade
2022/09/08 14:09:26 Begin reload_inst_variables
2022/09/08 14:09:27 End reload_inst_variables
2022/09/08 14:09:27 Begin initialize_variables
2022/09/08 14:09:27 End initialize_variables
2022/09/08 14:09:27 ===> Step preupgrade. USER=sc-sickchill GROUP=sc-download SHARE_PATH=
2022/09/08 14:09:27 Begin service_preupgrade
2022/09/08 14:09:27 End service_preupgrade
2022/09/08 14:09:27 upgrade sickchill 20211110-4 End preupgrade ret=[0]
2022/09/08 14:09:27 upgrade sickchill 20211110-4 Begin preuninst
2022/09/08 14:09:27 Begin reload_inst_variables
2022/09/08 14:09:27 End reload_inst_variables
2022/09/08 14:09:27 Begin initialize_variables
2022/09/08 14:09:27 End initialize_variables
2022/09/08 14:09:27 ===> Step preuninst. USER=sc-sickchill GROUP=sc-download SHARE_PATH=
2022/09/08 14:09:27 upgrade sickchill 20211110-4 End preuninst ret=[0]
2022/09/08 14:09:28 upgrade sickchill 20211110-4 Begin /bin/rm -rf /volume1/@appstore/sickchill
2022/09/08 14:10:02 upgrade sickchill 20211110-4 End /bin/rm -rf /volume1/@appstore/sickchill ret=[0]
2022/09/08 14:10:02 upgrade sickchill 20211110-4 Begin /bin/rm -rf /volume1/@apptemp/sickchill
2022/09/08 14:10:02 upgrade sickchill 20211110-4 End /bin/rm -rf /volume1/@apptemp/sickchill ret=[0]
2022/09/08 14:10:02 upgrade sickchill 20211110-4 Begin postuninst
2022/09/08 14:10:03 Begin reload_inst_variables
2022/09/08 14:10:03 End reload_inst_variables
2022/09/08 14:10:03 Begin initialize_variables
2022/09/08 14:10:03 End initialize_variables
2022/09/08 14:10:03 ===> Step postuninst. USER=sc-sickchill GROUP=sc-download SHARE_PATH=
2022/09/08 14:10:03 upgrade sickchill 20211110-4 End postuninst ret=[0]
2022/09/08 14:10:04 upgrade sickchill 20211110-4 Begin preinst
2022/09/08 14:10:05 Begin reload_inst_variables
2022/09/08 14:10:05 End reload_inst_variables
2022/09/08 14:10:05 Begin initialize_variables
2022/09/08 14:10:05 End initialize_variables
2022/09/08 14:10:05 ===> Step preinst. USER=sc-sickchill GROUP=sc-download SHARE_PATH=
2022/09/08 14:10:05 upgrade sickchill 20211110-4 End preinst ret=[0]
2022/09/08 14:10:05 upgrade sickchill 20211110-4 Begin /bin/mkdir -p /volume1/@appstore/sickchill -m 755
2022/09/08 14:10:05 upgrade sickchill 20211110-4 End /bin/mkdir -p /volume1/@appstore/sickchill -m 755 ret=[0]
2022/09/08 14:10:05 upgrade sickchill 20211110-4 Begin /bin/rm -rf /volume1/@appstore/sickchill
2022/09/08 14:10:05 upgrade sickchill 20211110-4 End /bin/rm -rf /volume1/@appstore/sickchill ret=[0]
2022/09/08 14:10:05 upgrade sickchill 20211110-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.BVgmKi/package /volume1/@appstore/sickchill
2022/09/08 14:10:05 upgrade sickchill 20211110-4 End /bin/mv -f /volume1/@tmp/synopkg/install.BVgmKi/package /volume1/@appstore/sickchill ret=[0]
2022/09/08 14:10:05 upgrade sickchill 20211110-4 Begin /bin/rm -rf /var/packages/sickchill
2022/09/08 14:10:05 upgrade sickchill 20211110-4 End /bin/rm -rf /var/packages/sickchill ret=[0]
2022/09/08 14:10:05 upgrade sickchill 20211110-4 Begin /bin/mkdir -p /var/packages/sickchill -m 755
2022/09/08 14:10:05 upgrade sickchill 20211110-4 End /bin/mkdir -p /var/packages/sickchill -m 755 ret=[0]
2022/09/08 14:10:05 upgrade sickchill 20211110-4 Begin /bin/touch /var/packages/sickchill/installing
2022/09/08 14:10:05 upgrade sickchill 20211110-4 End /bin/touch /var/packages/sickchill/installing ret=[0]
2022/09/08 14:10:05 upgrade sickchill 20211110-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.BVgmKi/INFO /var/packages/sickchill/INFO
2022/09/08 14:10:05 upgrade sickchill 20211110-4 End /bin/mv -f /volume1/@tmp/synopkg/install.BVgmKi/INFO /var/packages/sickchill/INFO ret=[0]
2022/09/08 14:10:05 upgrade sickchill 20211110-4 Begin /bin/rm -rf /var/packages/sickchill/scripts
2022/09/08 14:10:05 upgrade sickchill 20211110-4 End /bin/rm -rf /var/packages/sickchill/scripts ret=[0]
2022/09/08 14:10:05 upgrade sickchill 20211110-4 Begin /bin/mv -f /volume1/@tmp/synopkg/install.BVgmKi/scripts /var/packages/sickchill/scripts
2022/09/08 14:10:05 upgrade sickchill 20211110-4 End /bin/mv -f /volume1/@tmp/synopkg/install.BVgmKi/scripts /var/packages/sickchill/scripts ret=[0]
2022/09/08 14:10:05 upgrade sickchill 20211110-4 Begin /bin/rm -rf /var/packages/sickchill/WIZARD_UIFILES
2022/09/08 14:10:05 upgrade sickchill 20211110-4 End /bin/rm -rf /var/packages/sickchill/WIZARD_UIFILES ret=[0]
`

**Comment by BKSteve** [comment]
What were you doing? 
The log doesn't explain too much either. It's just the update log.
There isn't any `poetry` referenced in the log.

Anyway will have a step by step to get 20211110-04 up and running. Soon as doing final testing and needs a little code fix.

**Comment by BKSteve** [comment]
#8160
discussion item

**Comment by BKSteve** [comment]
closing as work around available.
