### ISSUE TITLE
Blankreferrer doesn't work

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#8152]
When adding a show, I can click the show name to get information. This leads me to the following page:
![image](https://user-images.githubusercontent.com/17053402/189351427-f10782fe-34e7-41fc-86ce-cdb3285919e3.png)

**Comment by Wally73** [comment]
just change to https://dereferer.me/?

**Comment by Tiwas** [comment]
> just change to https://dereferer.me/?

Sure, but figured it would be nice to change it for new installations - or possibly change it in existing installations, too :)

**Comment by pigsyn** [comment]
@Tiwas Default is: `https://anonym.to/?`, like suggested in settings -> General -> Advanced Settings -> Anonymous redirect

https://github.com/SickChill/SickChill/blob/305c06f4a6010567d0bdcdafeb04b73ab783946a/sickchill/settings.py#L66

```
Only  http://dereferer.org/? is blacklisted in code, not https://blankrefer.com/?, so it won't be removed
```
