### ISSUE TITLE
Venv crash

### ISSUE THREAD

**Issue by ncl2fth** [SickChill/SickChill#8153]
Need some help here

Branch/Commit: Master
OS: Linux docker 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Browser: Microsoft Edge
What you did: fresh rebuild of docker image, start image, try a manual search
What happened: it starts the search then suddenly goes into peotry update mode and crashes
What you expected: not to crash
Logs:
```
sickchill    | 2022-09-09 17:05:00 DEBUG :: MAIN :: get_all_scene_exceptions: {-1: [{'show_name': 'X', 'custom': False}]}
sickchill    | 2022-09-09 17:05:00 DEBUG :: MAIN :: exceptions_cache for 203411: {-1: ['X']}
sickchill    | 2022-09-09 17:05:00 DEBUG :: MAIN :: Internal name cache for Xset to: [ X ]
sickchill    | 2022-09-09 17:05:11 DEBUG :: SEARCHQUEUE-MANUAL-367506 :: formatting pattern: %SN - S%0SE%0E - %EN -> X
sickchill    | 2022-09-09 17:05:11 INFO :: SEARCHQUEUE-MANUAL-367506 :: Beginning manual search for: X
sickchill    | 2022-09-09 17:05:11 DEBUG :: SEARCHQUEUE-MANUAL-367506 :: Building internal name cache for X
sickchill    | 2022-09-09 17:05:11 DEBUG :: SEARCHQUEUE-MANUAL-367506 :: get_all_scene_exceptions: {-1: [{'show_name': 'X', 'custom': False}]}
sickchill    | 2022-09-09 17:05:11 DEBUG :: SEARCHQUEUE-MANUAL-367506 :: exceptions_cache for 367506: {-1: ['X']}
sickchill    | 2022-09-09 17:05:11 DEBUG :: SEARCHQUEUE-MANUAL-367506 :: Internal name cache for X
sickchill    | 2022-09-09 17:05:11 DEBUG :: SEARCHQUEUE-MANUAL-367506 :: [DOGnzb] :: Checking database structure...cache.db
sickchill    | 2022-09-09 17:05:11 DEBUG :: SEARCHQUEUE-MANUAL-367506 :: [DOGnzb] :: Last update was too soon, using old cache: 2022-09-09 16:44:22. Updated less then 30 minutes ago
sickchill    | 2022-09-09 17:05:11 DEBUG :: SEARCHQUEUE-MANUAL-367506 :: [OMGWTFNZBs] :: GET URL: https://rss.omgwtfnzbs.me/rss-download.php?user=ncl2fth&api=907298d08b59e3045e9ed88daddfcd69&eng=1&catid=19%2C20%2C30 [Status: 200]
sickchill    | Checking poetry
sickchill    | Can write to /root/.local/lib/python3.9/site-packages: False
sickchill    | Can write to /app/sickchill/.venv/lib/python3.9/site-packages: True
sickchill    | pip installed: True
sickchill    | pip args: /app/sickchill/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
sickchill    | poetry installed: True
sickchill    | Poetry installed packages checker started
sickchill    | Poetry installed packages checker completed
sickchill    | ["No module named 'poetry_date_version_plugin'"]
sickchill    | Unable to install to the existing virtual environment located at /app/sickchill/.venv
sickchill    | Please check the permissions, and that it does not include global site packages

crashes  here

**Comment by pigsyn** [comment]
> sickchill    | 2022-09-09 17:05:11 DEBUG :: SEARCHQUEUE-MANUAL-367506 :: [OMGWTFNZBs] :: GET URL: https://rss.omgwtfnzbs.me/rss-download.php?user=ncl2fth&api=907298d08b59e3045e9ed88daddfcd69&eng=1&catid=19%2C20%2C30 [Status: 200]

There is a bug with rss providers on master.
It is fixed on develop, pull sickchill/sickchill:develop

https://github.com/SickChill/SickChill/issues/8132#issuecomment-1236201490

**Comment by ncl2fth** [comment]
Thank you

**Comment by disl-pdavid** [comment]
> > sickchill    | 2022-09-09 17:05:11 DEBUG :: SEARCHQUEUE-MANUAL-367506 :: [OMGWTFNZBs] :: GET URL: https://rss.omgwtfnzbs.me/rss-download.php? [Status: 200]
> 
> There is a bug with rss providers on master. It is fixed on develop, pull sickchill/sickchill:develop
> 
> [#8132 (comment)](https://github.com/SickChill/SickChill/issues/8132#issuecomment-1236201490)

Should I just wait for `master` to get the fix if I don't want to run develop?

**Comment by pigsyn** [comment]
> Should I just wait for `master` to get the fix if I don't want to run develop from now on (or is develop stable enough to run as a daily driver)?

Good question I was about to comment on pulling develop blindly without checking what has changed. 😄 

I have been running it for 3 days on docker, with a few torrent providers and 75 shows, it's seems ok. I didn't test NZB.
Custom rss doesn't crash sickchill anymore.

If you are not using docker, it might break systemctl service and it needs documentation.

What is true today might not be true tomorrow, so I did a backup from backup & restore menu.

**Comment by miigotu** [comment]
Just update, I have released develop now. But I would suggest switching to a pip based install, because it will no longer update with a git install or a source install anymore.

**Comment by FooBarTrixibell** [comment]
I had this issue too, I didn't really like the idea of running the development version.

I did a roll backwards rather than forwards, perhaps a few tags too many but it seems to be back working.

`git checkout 2022.7.0`

**Comment by disl-pdavid** [comment]
> Just update, I have released develop now. But I would suggest switching to a pip based install, because it will no longer update with a git install or a source install anymore.

This shouldn't effect docker users, shoudl it?

**Comment by miigotu** [comment]
Docker already uses a pip install
