### ISSUE TITLE
EZTV ReadTimeout 

### ISSUE THREAD

**Issue by bluezed** [SickChill/SickChill#8163]
Branch/Commit: pip / v2022.08.29
OS: Ubuntu 20.04.5
Browser: Firefox 104

What happened:
For several days now I find EZTV ReadTimeout errors in the log every time there's an episode search being performed. The EZTV site is reachable through the browser though and other providers appear to work fine.

What you expected:
No connection error.

Logs:
```
2022-09-13 08:37:49 INFO :: SEARCHQUEUE-MANUAL-297369 :: [EZTV] :: Request failed: HTTPSConnectionPool(host='eztv.re', port=443): Read timed out. (read timeout=30) (ReadTimeout)
```

Has EZTV maybe changed their API?

**Comment by pigsyn** [comment]
EZTV works fine for me (pip install + develop), but I think they had a downtime this morning, had a cloudflare error 503 while testing / browsing.
It's more a stability issue on their end.

**Comment by bluezed** [comment]
Think you're right. Can't connect now either.
Guess they must have had issues quite frequently recently then.

Guess we can close this issue again...
