### ISSUE TITLE
Msg after updating: SickChill no longer is supported unless installed with pip or poetry. Source and git installs are for experienced users only

### ISSUE THREAD

**Issue by twinden** [SickChill/SickChill#8174]
Msg after updating: SickChill no longer is supported unless installed with pip or poetry. Source and git installs are for experienced users only

I’m on latest SC on Synology with pip and poetry being added by sc @ runtime.
This is somewhere in the latest 22 updates.

**Comment by miigotu** [comment]
https://github.com/SynoCommunity/spksrc/pull/5431

Wait until the new syno package is finished. It will work fine until then.
