### ISSUE TITLE
Update Failure - Both Manual Update and Automatic Update Fail

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#8179]
I have been unable to run the updater in order to get the latest version installed
Pretty sure this one isn't user error but I'd never rule myself out as the cause!
I have automatic update enabled so was surprised to see that an update was available, the automatic update should have covered it
When I clicked to update it instantly failed, the logs show "no matching distribution found for s"

   SickChill Info:
Install: pip
Version: 2022.9.14
Database Version: 44.2

  Python Version:
3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

  SSL Version:
OpenSSL 1.1.1k 25 Mar 2021

  OS:
Windows-10-10.0.19044-SP0

  Locale:
en_GB.cp1252

Browser: Firefox / Chrome / Edge
What you did: Clicked update / enabled autoupdate
What happened: update instantly failed, error saying the updated wasn't successful
What you expected: Update to complete (currently affected by the NZBHydra issue which this update should fix)
Logs:
```
2022-09-17 11:54:14 INFO :: CHECKVERSION :: Update failed!
AA ERROR: No matching distribution found for s
2022-09-17 11:54:14 INFO :: CHECKVERSION :: Command result: ERROR: Could not find a version that satisfies the requirement s (from versions: none)
2022-09-17 11:54:13 INFO :: CHECKVERSION :: Trying user site-packages
```

**Comment by pigsyn** [comment]
https://github.com/SickChill/SickChill/issues/8178

**Comment by rutskiuk** [comment]
I tried shutting down SC and running the update 

pip3 install -U sickchill

Frustratingly, even thought the interface had stopped the windows service was still running and the autoupdater jumped in.
The autoupdater failed, I switched it off and retried running the pip update again. This time I just get a long string of messages saying "requirement already satisfied" and if I run SickChill after that I am notified that an update is still available.

**Comment by miigotu** [comment]
Inside SickChill, check which python is used in help & info. Stop SickChill`net stop sickchill`, then use that python to do the update. `/path/to/python3 -m pip install -U sickchill `

**Comment by rutskiuk** [comment]
The above didn't initially work initially however I used nssm edit sickchill and found the python used by the service was actually from the tools folder of Sickchill so put that in the above instead and voila! 

Sickchill updated 👍 

Aaand it was only after that when I realised you were referring to the path to the executable from Help and Info rather than the python version. I got there in the end, my brain just took the scenic route 🤣 

This one can be closed off 😃

**Comment by miigotu** [comment]
> The above didn't initially work initially however I used nssm edit sickchill and found the python used by the service was actually from the tools folder of Sickchill so put that in the above instead and voila! 
> 
> Sickchill updated 👍 
> 
> Aaand it was only after that when I realised you were referring to the path to the executable from Help and Info rather than the python version. I got there in the end, my brain just took the scenic route 🤣 
> 
> This one can be closed off 😃 

Ideally you should edit the nssm service to use the other python3 instead of the other way around. C:\SickChill\tools shouldn't even exist with the newer installer afaik.

**Comment by rutskiuk** [comment]
Thanks, I've done that right away, running smoothly
