### ISSUE TITLE
ImportError: cannot import name 'InputFileContent' from 'github' or cannot import name 'Github' from 'github'

### ISSUE THREAD

**Issue by adrhc** [SickChill/SickChill#8184]
**Version**: current master branch
**OS**: Ubuntu 22.04.1 LTS
**What you did**:
`sudo -u sickchill /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill --port 8061`
**Logs**:
```
Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/opt/sickchill/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
ImportError: cannot import name 'InputFileContent' from 'github' (/usr/local/lib/python3.10/dist-packages/github/__init__.py)
```
```
sudo -u sickchill /usr/bin/python3 --version
Python 3.10.4
```
Indeed, `InputFileContent` is missing but it doesn't show up when executing `sudo pip install --force-reinstall github`. On the other hand `/opt/sickchill/.venv/lib/python3.10/site-packages/github/InputFileContent.py` exists.
```
ll /usr/local/lib/python3.10/dist-packages/github/
drwxr-xr-x 2 root root 4.0K Sep 17 21:05 __pycache__
-rw-r--r-- 1 root root 2.0K Sep 17 21:05 cache.py
-rw-r--r-- 1 root root  13K Sep 17 21:05 client.py
-rw-r--r-- 1 root root 4.6K Sep 17 21:05 exceptions.py
-rw-r--r-- 1 root root  13K Sep 17 21:05 http.py
-rw-r--r-- 1 root root  16K Sep 17 21:05 objects.py
-rw-r--r-- 1 root root  949 Sep 17 21:05 urls.py
-rw-r--r-- 1 root root  311 Sep 17 21:05 __init__.py
```
How can solve this issue?

**Comment by pigsyn** [comment]
There's a couple of guides to migrate from git installs to poetry or pip.

Reasons
https://github.com/SickChill/SickChill/wiki/Poetry-and-the-history-of-dependencies-in-SickChill

Quick Guides (from ubuntu 15):
https://github.com/SickChill/SickChill/discussions/categories/ubuntu-debian

**Comment by adrhc** [comment]
The issue seems related to:
[Fresh install of SickChill will not start](https://github.com/SickChill/SickChill/issues/7391)
[Ubuntu 18.04 to 20.04 upgrade. Python 3.6 sickchill reference](https://github.com/SickChill/SickChill/issues/7766)
but the solutions there don't work for me.

When switching to `/opt/sickchill/.venv` I get:
```
sudo -u sickchill /opt/sickchill/.venv/bin/python /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill --port 8061
Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/opt/sickchill/sickchill/logger.py", line 15, in <module>
    from sickchill import settings
  File "/opt/sickchill/sickchill/settings.py", line 7, in <module>
    from sickchill.oldbeard.common import SD
  File "/opt/sickchill/sickchill/oldbeard/common.py", line 9, in <module>
    from sickchill.helper import video_screen_size
  File "/opt/sickchill/sickchill/helper/__init__.py", line 1, in <module>
    from .common import episode_num, HTTP_STATUS_CODES, MEDIA_EXTENSIONS, pretty_file_size, sanitize_filename, setup_github, SUBTITLE_EXTENSIONS, try_int
  File "/opt/sickchill/sickchill/helper/common.py", line 9, in <module>
    from github import Github
ImportError: cannot import name 'Github' from 'github' (/opt/sickchill/.venv/lib/python3.10/site-packages/github/__init__.py)
```

**Comment by pigsyn** [comment]
SickChill no longer is supported unless installed with pip or poetry https://github.com/SickChill/SickChill/discussions/8167

Git install -> you are responsible to install and manage dependencies with poetry
Pip -> packaging does it for you

https://github.com/SickChill/SickChill/issues/8184#issuecomment-1250124280

> sudo cp -v /opt/sickchill/.venv/lib/python3.10/site-packages/github/* /usr/local/lib/python3.10/dist-packages/github/

Don't do this.

Take 5m to migrate and add `--port 8061` to your specific configuration

**Comment by adrhc** [comment]
> There's a couple of guides to migrate from git installs to poetry or pip.
> 
> Reasons https://github.com/SickChill/SickChill/wiki/Poetry-and-the-history-of-dependencies-in-SickChill
> 
> Quick Guides (from ubuntu 15): https://github.com/SickChill/SickChill/discussions/categories/ubuntu-debian

I tried [migrating to poetry from Ubuntu 15 guide](https://github.com/SickChill/SickChill/discussions/8155); first I had to `pip install github` to solve `ModuleNotFoundError: No module named 'github'` error and then I stumbled on the below error:
```
(.venv) sickchill@adrhc:/opt/sickchill$ poetry run python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill --port 8061
Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/opt/sickchill/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
ImportError: cannot import name 'InputFileContent' from 'github' (/opt/sickchill/.venv/lib/python3.10/site-packages/github/__init__.py)
```

**Comment by pigsyn** [comment]
You need to follow every step in the guides, including prerequisite and the disclaimer.
The only package you should have to install in the virtual environment with pip is html5lib. (small issue with poetry in venv)

poetry lock before poetry install should fix your issue.

You can always go with a pip install, now or after fixing your git install.

Please do not force reinstall pip packages as root.

**Comment by adrhc** [comment]
> Please, for your own sake, do not force reinstall pip packages as root.

Well, I hope you read my entire post but not only the last question related to `github`. If it is so, than please notice `(.venv) sickchill@adrhc:/opt/sickchill$` which means I'm not using root or another but I'm sticking to [migrating to poetry from Ubuntu 15 guide](https://github.com/SickChill/SickChill/discussions/8155).

**Comment by miigotu** [comment]
@adrhc you should not use poetry or git at all. back up your database and config.ini, and install with pip into a virtualenv or pipx.

You will need to update your service file to run it from the virtualenv then, but we do not have documentation for that currently I dont think.

```bash
sudo mv /opt/sickchill /opt/sickchill_obsolete
sudo -u sickchill /usr/bin/python3 -m venv /opt/sickchill
sudo -u sickchill /opt/sickchill/bin/pip install sickchill
sudo -u sickchill /opt/sickchill/bin/SickChill  --nolaunch --datadir=/opt/sickchill --port 8061
```

**Comment by adrhc** [comment]
> @adrhc you should not use poetry or git at all
Well, according to [migrating to poetry from Ubuntu 15 guide](https://github.com/SickChill/SickChill/discussions/8155) you pointed I do have to install poetry.

**Comment by adrhc** [comment]
> There's a couple of guides to migrate from git installs to poetry or pip.
> 
> Reasons https://github.com/SickChill/SickChill/wiki/Poetry-and-the-history-of-dependencies-in-SickChill
> 
> Quick Guides (from ubuntu 15): https://github.com/SickChill/SickChill/discussions/categories/ubuntu-debian

just a reminder to you about the documentation you pointed

**Comment by miigotu** [comment]
> > @adrhc you should not use poetry or git at all
> > Well, according to [migrating to poetry from Ubuntu 15 guide](https://github.com/SickChill/SickChill/discussions/8155) you pointed I do have to install poetry.

Not me. But those guides are a __reference__ ... there is no such thing as a one size fits all...yet.

We are still working on the documentation. Feel free to let us know what you figure out and share your working service once you get it working.

```bash
sudo mv /opt/sickchill /opt/sickchill_obsolete
sudo -u sickchill /usr/bin/python3 -m venv /opt/sickchill
sudo -u sickchill /opt/sickchill/bin/pip install sickchill
sudo -u sickchill /opt/sickchill/bin/SickChill  --nolaunch --datadir=/opt/sickchill --port 8061
```

# /etc/systemd/system/sickchill.conf - edit the ExecStart, there is probably more to do but I haven't messed with it yet.
```
ExecStart=/opt/sickchill/bin/SickChill  --nolaunch --datadir=/opt/sickchill --port 8061
```

**Comment by adrhc** [comment]
Well, you last instructions look similar to [migrating to pip from Ubuntu 15 guide](https://github.com/SickChill/SickChill/discussions/8154) which is the guide that works.

**Comment by adrhc** [comment]
> ```
> ExecStart=/opt/sickchill/bin/SickChill  --nolaunch --datadir=/opt/sickchill --port 8061
> ```

Are you sure that I have to use `--datadir=/opt/sickchill`?

**Comment by pigsyn** [comment]
> Are you sure that I have to use `--datadir=/opt/sickchill`?

If you used the pip guide, **followed every step**,  and everything is working, `--datadir=/path/to/conf` is optional and your config is now in `/var/lib/sickchill/.config/sickchill/` by default. 

You can check with `sudo ls -lh /var/lib/sickchill/.config/sickchill/`

```
pigsyn@ubuntu:~$ sudo ls -lh /var/lib/sickchill/.config/sickchill/
total 420K
drwxrwxr-x 2 sickchill sickchill 4,0K sept. 17 12:59 cache
-rw-r--r-- 1 sickchill sickchill 288K sept. 17 10:52 cache.db
-rw-rw-r-- 1 sickchill sickchill  28K sept. 17 21:45 config.ini
-rw-r--r-- 1 sickchill sickchill  16K sept. 17 10:52 failed.db
drwxrwxr-x 2 sickchill sickchill 4,0K sept. 17 10:53 Logs
-rw-r--r-- 1 sickchill sickchill  80K sept. 17 10:52 sickchill.db
```

If you followed @miigotu instructions, (not using the pip survival guide), then your config and database are still in `/opt/sickchill`
Use backup & restore in sickchill to save your configuration somewhere safe just in case.

**Comment by miigotu** [comment]
Where you create the virtualenv and/or store your config and db is a user choice. There is no decent way to convey that in a wiki page. Everyone wants to put their things organized in a different way, and every distro has a different guidance on where to put things like 3rd party software or configurations.

**Comment by fbossy** [comment]
Hi!

I have the same issue on Mac.
How to install with pip and launch on startup?

I can’t find any tutorials out there for Mac/pip.

**Comment by pigsyn** [comment]
> Hi!
> 
> I have the same issue on Mac. How to install with pip and launch on startup?
> 
> I can’t find any tutorials out there for Mac/pip.

@fbossy Move to https://github.com/SickChill/SickChill/discussions/8173
Confirm that your config and database are in `/Users/<username>/Library/Application Support/sickchill` and current content of your service (it might be ~/Library/LaunchAgents/SickChill.plist)

**Comment by fbossy** [comment]
I think I figured it out.

I’ll post how I did it when on my computer.
Maybe it can help some other users. 😊
