### ISSUE TITLE
Refactor tv.py

### ISSUE THREAD

**Issue by miigotu** [SickChill/SickChill#8185]
I've selected [**tv.py**](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L1-L0) for refactoring, which is a module that has **13** instance(s) of code in comments ([1](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L241-L241), [2](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L562-L562), [3](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L712-L712), [4](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L720-L720), [5](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L1117-L1117), [6](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L1538-L1538), [7](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L1560-L1560), [8](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2001-L2001), [9](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2027-L2027), [10](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2136-L2136), [11](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2145-L2145), [12](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2299-L2299), [13](https://github.com/SickChill/SickChill/blob/c7e8a6c39d52d65457b6a9f44f9bad8f35c97fbe/sickchill/tv.py#L2406-L2406)).  Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Clean Code** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Apply The Boy Scout Rule and fix "code smells" in the codebase.
- **Why**❓ 
Clean code is maintainable code.
- **How** 🔧 
Remove useless comments, commented code blocks, and dead code. Refactor poorly handled exceptions, magic constants, and poorly named units or variables.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by pigsyn** [comment]
Need to recheck a couple of logger.debug strings that I enabled, to see if they are helpful or not, some are spammy and don't provide much information.

https://github.com/SickChill/SickChill/compare/develop..code_cleanup/tv

https://bettercodehub.com/results/SickChill/SickChill/eeaecd8452353cc7473c935b86f671d25e4f4531

**Comment by miigotu** [comment]
I opened a PR for it, easier to review and check tests for me

**Comment by miigotu** [comment]
This is the next thing that is going to prevent help a lot of issues
![Screenshot_20220920-163031.png](https://user-images.githubusercontent.com/390379/191358527-cc692e5f-6418-4b39-a7a1-ef3b75563d4f.png)
