### ISSUE TITLE
Pip install failing

### ISSUE THREAD

**Issue by markasammut** [SickChill/SickChill#8187]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version:
OS: Linux-4.19.122-2-osmc-armv7l-with-glibc2.31
Browser:
What you did:

What happened:

I used to use the git version of Sickchill, but after the warning to switch to pip/docker came up at some point it started failing to start, so I decided to attempt the pip install. I moved away the old directory, and attempted the below:

```
osmc@osmc:/opt/sickchill$ sudo su - sickchill -s /bin/bash
$ python3 -m venv /opt/sickchill
$ source /opt/sickchill/bin/activate
(sickchill) $ /opt/sickchill/bin/pip install -U sickchill
```

This returned  the below error:
    AttributeError: 'HTMLParser' object has no attribute 'unescape'

After some googling, I upgraded pip, setuptools and distlib, but cryptography kept failing to install (issue with Rust compiler). Logs below.

```
(sickchill) $ pip install --upgrade pip
(sickchill) $ pip install --upgrade distlib setuptools
(sickchill) $ /opt/sickchill/bin/pip install -U sickchill
```

Have also tried to install this on the main system, outside of the virtual environment, but kept getting the same issue.

What you expected:
Logs:
```

      writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
      /tmp/pip-build-env-4lgbp7sa/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'cryptography.hazmat.bindings._rust' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'cryptography.hazmat.bindings._rust' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'cryptography.hazmat.bindings._rust' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'cryptography.hazmat.bindings._rust' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      copying src/cryptography/py.typed -> build/lib.linux-armv7l-cpython-39/cryptography
      copying src/cryptography/hazmat/bindings/_openssl.pyi -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings
      creating build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-armv7l-cpython-39/cryptography/hazmat/bindings/_rust
      running build_ext
      running build_rust

          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Read https://cryptography.io/en/latest/installation/ for specific
             instructions for your platform.
          3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq/
          4) Ensure you have a recent Rust toolchain installed:
             https://cryptography.io/en/latest/installation/#rust

          Python: 3.9.2
          platform: Linux-4.19.122-2-osmc-armv7l-with-glibc2.31
          pip: n/a
          setuptools: 65.3.0
          setuptools_rust: 1.5.2
          rustc: n/a
          =============================DEBUG ASSISTANCE=============================

      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.

      This package requires Rust >=1.48.0.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
  Building wheel for msgpack (pyproject.toml) ... done
  Created wheel for msgpack: filename=msgpack-1.0.4-cp39-cp39-linux_armv7l.whl size=280367 sha256=27756ddd0e5730cccaed0603bccc62a5291ba4da253beb4a20ec139e661d9604
  Stored in directory: /opt/sickchill/.cache/pip/wheels/09/45/cc/6414f98c3c831980e8a50311be260886f3fbfae1028d4c8f7f
  Building wheel for pynacl (pyproject.toml) ... done
  Created wheel for pynacl: filename=PyNaCl-1.5.0-cp39-cp39-linux_armv7l.whl size=600831 sha256=32f7b559db215b0fb20bc390b70d7e1ac91699704f66ffb6f749920b1c30d104
  Stored in directory: /opt/sickchill/.cache/pip/wheels/b2/1a/3d/bc1564bd01d06e7071dd466d477d42523dc1405c04c668dfd0
Successfully built tornado msgpack pynacl
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
```

**Comment by Pastagazok** [comment]
Hello,

=> "error: can't find Rust compiler"

As it is said in your log, you need RUST, and have to do this before your Sickchill installation : 

`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

Best regards,
Guillaume.

**Comment by miigotu** [comment]
For raspberry pi follow the instructions on the front page of https://www.piwheels.org/

Or call pip with this flag:
`pip install -U sickchill --extra-index-url=https://www.piwheels.org/simple`

Crypto doesn't build a version from armv7,l by default, but piwheels does.

**Comment by markasammut** [comment]
Thank you. Two questions:

- Is it suggested to use a virtual env for this?
- Should I use pip or pip3?

**Comment by Pastagazok** [comment]
> For raspberry pi follow the instructions on the front page of https://www.piwheels.org/
> 
> Or call pip with this flag: `pip install -U sickchill --extra-index-url=https://www.piwheels.org/simple`
> 
> Cryptography doesn't build a version from armv7,l by default, but piwheels does.

Hi Migotu,
For my installation, do you advise me to apply your method instead of mine? 
Thank you.
May the force be with you.

**Comment by miigotu** [comment]
> Thank you. Two questions:
> 
> - Is it suggested to use a virtual env for this?
> - Should I use pip or pip3?

I would use a virtualenv like you did in the original post, just add the extra-index-url
In your virtualenv pip and pip3 point to the same pip.

**Comment by miigotu** [comment]
> > For raspberry pi follow the instructions on the front page of https://www.piwheels.org/
> > 
> > Or call pip with this flag: `pip install -U sickchill --extra-index-url=https://www.piwheels.org/simple`
> > 
> > Cryptography doesn't build a version from armv7,l by default, but piwheels does.
> 
> Hi Migotu,
> For my installation, do you advise me to apply your method instead of mine? 
> Thank you.
> May the force be with you. 

If you are on a raspberry pi then yes, do it this way.

**Comment by Pastagazok** [comment]
> > > For raspberry pi follow the instructions on the front page of https://www.piwheels.org/
> > > Or call pip with this flag: `pip install -U sickchill --extra-index-url=https://www.piwheels.org/simple`
> > > Cryptography doesn't build a version from armv7,l by default, but piwheels does.
> > 
> > 
> > Hi Migotu,
> > For my installation, do you advise me to apply your method instead of mine?
> > Thank you.
> > May the force be with you.
> 
> If you are on a raspberry pi then yes, do it this way.
> 
> You can install a rust compiler if you run across a wheel they don't have built, but probably won't run into that. We don't use many dependencies that have rust or c extensions.

OK, thank you. 👌🙂

**Comment by miigotu** [comment]
> Would be helpful if this wiki (https://github.com/SickChill/SickChill/wiki/Pip) is updated to run sudo systemctl daemon-reexec after the daemon-reload :)
> 
> All went fine, installed and everything back up :) Thanks all for your help!

daemon-reexec is only necessary if you change the settings or configuration of systems ITSELF, which you do not do in order to run SickChill.

daemon-reload reloads service unit files, which is what we are editing.

This, all that is needed is:
```bash
systemctl stop sickchill
systemctl edit sickchill 
systemctl daemon-reload
systemctl start sickchill 
```

It would be nice if people would stop making rude comments about what would be nice that the documentation did when they can't suggest correct information, let alone making a pull request to the wiki repo or SickChill.
