### ISSUE TITLE
Exception generated in thread CHECKVERSION

### ISSUE THREAD

**Issue by egrueda** [SickChill/SickChill#8193]
Got this message eveery few hours in error logs:

`Exception generated in thread CHECKVERSION: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/sickchill/json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known'))`

It's happening since I moved from git to pip install, yesterday.
Any clues?

SickChill Info:
Install: [pip](http://www.lolinez.com/?https://pypi.org/project/sickchill/)
Version: [2022.9.17](http://www.lolinez.com/?https://github.com/SickChill/SickChill/releases/tag/2022.9.17)
Database Version: 44.5
  Python Version:3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  SSL Version:OpenSSL 1.1.1n 15 Mar 2022
  OS:Linux-5.10.78-7-osmc-aarch64-with-glibc2.31

**Comment by rd1** [comment]
SAME HERE!

SickChill Info:
Install: [pip](https://pypi.org/project/sickchill/) (windows installer v0.62)

Version: [2023.1.2](https://github.com/SickChill/SickChill/releases/tag/2023.1.2)

Database Version: 44.5
Python:3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
SSL:OpenSSL 1.1.1k 25 Mar 2021
OS:Windows-10-10.0.19044-SP0
