### ISSUE TITLE
module 'rarfile' has no attribute 'UNAR_TOOL'

### ISSUE THREAD

**Issue by citroboy** [SickChill/SickChill#8201]
Version: 2022.9.22
OS: Debian Bullseye
Browser: N/A
What you did: Installed from git and tried to run
What happened: Fails with error
What you expected: Success!
Logs:
```
File "/home/martin/SickChill/sickchill/settings.py", line 500, in <module>
    UNAR_TOOL = rarfile.UNAR_TOOL
AttributeError: module 'rarfile' has no attribute 'UNAR_TOOL'
```
Python Version: 3.9.2
Installed python3-rarfile 3.1-1 from Debian repo. Is there another version I should be using? If I try to remove it apt wants to remove python3-subliminal too.

**Comment by miigotu** [comment]
See the pinned post, SickChill does not install directly from git anymore. Use pip.
