### ISSUE TITLE
Sickchill  start and stop on synology Dsm 6

### ISSUE THREAD

**Issue by xmenxmen** [SickChill/SickChill#8202]
### Before submitting your issue:

Sickchill  version 20211110-4 start  and stop after install on Synology Dsm 6

synology DS1819+
DSM-version  6.2.4-25556

**Comment by miigotu** [comment]
https://github.com/SynoCommunity/spksrc/issues/4524

https://github.com/SickChill/SickChill/discussions/8160

**Comment by xmenxmen** [comment]
How do i  install pypi based wheel, on synology dsm 6

**Comment by miigotu** [comment]
If you read the link I posted, you would see the PR I made that we are trying to get working on dsm.
