### ISSUE TITLE
Large number of errors in the log Since Reinstall

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#8203]
Version: Master
OS: Windows 10
Browser: Firefox
What you did: Reinstalled SickChill, restored from an old backup, submitted a refresh of the shows and saw after the process seemed to stop after 5 hours noticed the log was full of the same error many times. Interestingly, the interface used to highlight errors (I get many as a number of shows added to my database no longer exist on TheTVDB) and those no longer show.

What happened: Sickchill runs but the log is full of the errors as below, the interface has slowed down 

What you expected: Smooth user experience
Logs:
```
AA TypeError: expected string or bytes-like object
AA return _compile(pattern, flags).match(string)
AA File "C:\SickChill\Python3\tools\lib\re.py", line 191, in match
AA if re.match(r"^t?t?\d{7,8}$", name) or re.match(r"^\d{6}$", name):
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\show\indexers\tvdb.py", line 113, in search
AA result = target(*args, **kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\show\indexers\wrappers.py", line 25, in wrapper
```
Is there something I can do to work around or fix these persistent errors?
I saw reference to a workaround but the issue that included the detail no longer exists.

**Comment by miigotu** [comment]
Its not necessarily an error, it can be ignored. Also, if you update to 2022.9.22 it isn't an error anymore, it's a debug line.
