### ISSUE TITLE
config.ini isn't created, I can't launch SickChill

### ISSUE THREAD

**Issue by ElrondVardamir** [SickChill/SickChill#8207]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: latest
OS: Ubuntu 22.04.1
Browser: Firefox, Safari, Google Chrome, etc...
What you did: just install SickChill

Hello,

I tried to install SickChill on my server but there is a problem : after installed the last version (by using this guides : https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15) I'm blocked.

My server show me "502 Bad Gateway", but the most weird for me is that the file "config.ini" don't even created.

I tried to reboot server, delete and reinstall sickchill but same problem.

Do you already seen this problem .

Thank you

**Comment by miigotu** [comment]
That guide is outdated, I just added a deprecated tag to it. Most of the wiki is outdated and anything that involves git or a clone is not to be used.

Either you can do what is in contrib/debian-ubuntu-install.sh manuall or do this:

```bash
sudo deluser sickchill 2>/dev/null
sudo delgroup sickchill 2>/dev/null
sudo mv /etc/systemd/system/sickchill.service sickchill.service_old 2>/dev/null

curl https://raw.githubusercontent.com/SickChill/SickChill/master/contrib/debian-ubuntu-install.sh | sudo bash --
```
