### ISSUE TITLE
Docker image errors "/bin/sh: SickChill: not found"

### ISSUE THREAD

**Issue by disl-pdavid** [SickChill/sickchill#8210]
Using docker image pulled from "Latest" tag:

https://hub.docker.com/layers/sickchill/sickchill/latest/images/sha256-fd6f79a22dced8cb7199a506ece3e5c905320dc7ab763fa8c71ac3cbf92cacd2

Everything was running fine.  I attempted to update by issuing `docker-compose pull` and `docker-compose up -d`.

The new container fails with this output:

```
❯ docker-compose up
sickchill is up-to-date
Attaching to sickchill
sickchill    | /bin/sh: 1: SickChill: not found
sickchill    | /bin/sh: 1: SickChill: not found
...
```

**Comment by patdavid** [comment]
Sorry, wrong account when I posted the issue.  Commenting here to watch replies with the correct one.

**Comment by miigotu** [comment]
Yep, still working on docker issues. arm/v7 and arm/v6 are causing issues. I'll probably disable those platforms again for now to get arm64 and amd64 images built at least.

**Comment by miigotu** [comment]
When this build finishes, try the edge tag or develop tag
https://github.com/SickChill/sickchill/actions/runs/3129977420

**Comment by miigotu** [comment]
@disl-pdavid working on it, should have a working image for you tonight. I overlooked something in the image that made it not found.

**Comment by patdavid** [comment]
Awesome, y'all *rock*! :+1: Thank you!

**Comment by JEDIBC** [comment]
Hi,

I've just tested the last docker image and still have the problem.

```
Creating network "sickchill_default" with the default driver
Pulling sickchill (sickchill/sickchill:latest)...
latest: Pulling from sickchill/sickchill
31b3f1ad4ce1: Pull complete
f335cc1597f2: Pull complete
0375df124bb5: Pull complete
90a356bcda5b: Pull complete
c82e0170c13b: Pull complete
5143f3fc6943: Pull complete
df572db65bae: Pull complete
1cd1eb4619f5: Pull complete
c889ea2d146e: Pull complete
be1483f6c02b: Pull complete
Digest: sha256:318781ae7f194debb623827995c51c2608ce4c5f57ffdece0cb8eea113428c79
Status: Downloaded newer image for sickchill/sickchill:latest
Creating sickchill ... done
Attaching to sickchill
sickchill    | /bin/sh: 1: sickchill: not found
sickchill exited with code 127
```

**Comment by jkoelker** [comment]
The issue is the `PATH` env setup is not done after the last `FROM` so the `PATH` in the container does not contain the `/.venv/bin` where the script is installed (its getting wiped out and reset through the base layers). As a workaround, just use the full path as the `CMD` when starting, ala:

```
podman run .... sickchill/sickchill:master /.venv/bin/sickchill --nolaunch --datadir=/data --port 8081
```

**Comment by JEDIBC** [comment]
Thanks @jkoelker , I added `command: "/.venv/bin/sickchill --nolaunch --datadir=/data --port 8081"` in my docker-compose and it start correctly :+1:

**Comment by miigotu** [comment]
I moved the PATH out of builder and into base in develop, I'll merge that to master later today and it will get rebuilt.

**Comment by turkeylegs1** [comment]
how can i change my docker config in syno to redo this to set it to work like yours?

**Comment by binbashblog** [comment]
+1 Running kubernetes on RPI4 (ARM64 - Ubuntu 22.04), both develop and master tags still give the error: "/bin/sh: 1: SickChill: not found"

**Comment by miigotu** [comment]
Docker hasnt been built, because there are errors with dependencies. When the issues get worked out, youll get a new image.
For now, you can pull the repo and docker build.

**Comment by miigotu** [comment]
Or when you docker run, you can specify the command

`docker run -it sickchill:develop "/.venv/bin/sickchill --nolaunch --datadir=/data --port 8081"`

Or use docker compose.

**Comment by turkeylegs1** [comment]
can i install manually straightup from ssh on synology 1821+ its got x64 architecture -- im tired of docker.
i cant install the spk package on community -- just fails. I've had this box with data on it since 2015. so i konw there are bound to be some leftovers, though i have ensured any old sickchill/sickrage dirs on the host are deleted or moved. and the /docker/sickchill remains untouched.

do you know how to do a docker pull on synology ( even if its on portainer)

**Comment by miigotu** [comment]
@BKSteve has working x64 builds, and synocommunity just solved the cross compilation error so I expect that to be done soon

**Comment by turkeylegs1** [comment]
When I get this working with Synology natively without docker, I’d like to
have a way to donate to you and others that have made huge contributions.
Thank you for putting up with all of us.

**Comment by miigotu** [comment]
Thanks in advance. Hope you get it working. Definitely at a rocky point with 3rd party packages and dependencies not working well lately.

**Comment by BKSteve** [comment]
> synology 1821+ its got x64 architecture

See #8160 for link

**Comment by miigotu** [comment]
Looks like the docker image built successfully for amd64 (x86_64), arm64/aarch64, arm32v7 and arm32v6.

You can pull sickchill/sickchill:develop now of you want, and try that out for me before I make a release to master.

**Comment by turkeylegs1** [comment]
@BKSteve  did this but it errored out and now as an spk i have no way to find errors.. removed package and will try to redo and stop right at the pip part you indicated. i was able to execute from bash as you indicated with commands and ran all 4 commands. no joy.

**Comment by turkeylegs1** [comment]
@BKSteve did that -- 
![image](https://user-images.githubusercontent.com/44487990/193467037-e1636826-6054-4b2f-b3b2-f0b4a2dd35ea.png)

I killed it quickly as soon as it validated as you specified - chris@Overlord:~$ sudo -u sc-sickchill /bin/bash
Password:
bash-4.4$ /volume1/@appstore/sickchill/share/SickChill/.venv/bin/python3 /volume1/@appstore/sickchill/share/S                                                                                                                                ickChill/SickChill.py --config /volume1/@appdata/sickchill/data/config.ini --datadir /volume1/@appdata/sickch                                                                                                                                ill/data
Checking poetry
Can write to /volume1/@appstore/sickchill/share/SickChill/.venv/lib/python3.8/site-packages: True
Can write to /var/packages/sickchill/home/.local/lib/python3.8/site-packages: False
pip installed: True
Found wheelhouse dir at /volume1/@appstore/sickchill/share/wheelhouse
pip args: /volume1/@appstore/sickchill/share/SickChill/.venv/bin/python3 -m pip install --no-input --disable-                                                                                                                                pip-version-check --no-python-version-warning --no-color -qU -f/volume1/@appstore/sickchill/share/wheelhouse                                                                                                                                 setuptools poetry wheel
poetry installed: True
Found wheelhouse dir at /volume1/@appstore/sickchill/share/wheelhouse
pip args: /volume1/@appstore/sickchill/share/SickChill/.venv/bin/python3 -m pip install --no-input --disable-                                                                                                                                pip-version-check --no-python-version-warning --no-color -qU -f/volume1/@appstore/sickchill/share/wheelhouse                                                                                                                                 appdirs==1.4.4 ; python_full_version >= "3.6.2" and python_version < "4" babelfish==0.6.0 ; python_full_versi                                                                                                                                on >= "3.6.2" and python_version < "4.0" backports-zoneinfo==0.2.1 ; python_full_version >= "3.6.2" and pytho                                                                                                                                n_version < "3.9" beautifulsoup4==4.10.0 ; python_full_version >= "3.6.2" and python_version < "4" beekeeper-                                                                                                                                alt==2021.7.16 ; python_full_version >= "3.6.2" and python_version < "4" bencode-py==4.0.0 ; python_full_vers                                                                                                                                ion >= "3.6.2" and python_version < "4" cachecontrol==0.12.10 ; python_full_version >= "3.6.2" and python_ver                                                                                                                                sion < "4" certifi==2021.10.8 ; python_full_version >= "3.6.2" and python_version < "4" cffi==1.15.0 ; python                                                                                                                                _full_version >= "3.6.2" and python_version < "4" chardet==4.0.0 ; python_full_version >= "3.6.2" and python_                                                                                                                                version < "4" charset-normalizer==2.0.7 ; python_full_version >= "3.6.2" and python_version < "4" click==8.0.                                                                                                                                3 ; python_full_version >= "3.6.2" and python_version < "4" cloudscraper==1.2.58 ; python_full_version >= "3.                                                                                                                                6.2" and python_version < "4" colorama==0.4.4 ; python_full_version >= "3.6.2" and python_version < "4" and p                                                                                                                                latform_system == "Windows" configobj==5.0.6 ; python_full_version >= "3.6.2" and python_version < "4" crypto                                                                                                                                graphy==35.0.0 ; python_full_version >= "3.6.2" and python_version < "4" decorator==5.1.0 ; python_full_versi                                                                                                                                on >= "3.6.2" and python_version < "4" deluge-client==1.9.0 ; python_full_version >= "3.6.2" and python_versi                                                                                                                                on < "4" deprecated==1.2.13 ; python_full_version >= "3.6.2" and python_version < "4" dogpile-cache==1.1.4 ;                                                                                                                                 python_full_version >= "3.6.2" and python_version < "4" enzyme==0.4.1 ; python_full_version >= "3.6.2" and py                                                                                                                                thon_version < "4" feedparser==6.0.8 ; python_full_version >= "3.6.2" and python_version < "4" future==0.18.2                                                                                                                                 ; python_full_version >= "3.6.2" and python_version < "4" gntp==1.0.3 ; python_full_version >= "3.6.2" and p                                                                                                                                ython_version < "4" greenlet==1.1.2 ; python_full_version >= "3.6.2" and (platform_machine == "aarch64" or pl                                                                                                                                atform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machin                                                                                                                                e == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and python_version < "4" guessit=                                                                                                                                =3.4.2 ; python_full_version >= "3.6.2" and python_version < "4" html5lib==1.1 ; python_full_version >= "3.6.                                                                                                                                2" and python_version < "4" httplib2==0.20.2 ; python_full_version >= "3.6.2" and python_version < "4" idna==                                                                                                                                3.3 ; python_full_version >= "3.6.2" and python_version < "4" ifaddr==0.1.7 ; python_full_version >= "3.6.2"                                                                                                                                 and python_version < "4" imagesize==1.3.0 ; python_full_version >= "3.6.2" and python_version < "4" imdbpy==2                                                                                                                                021.4.18 ; python_full_version >= "3.6.2" and python_version < "4" importlib-metadata==4.8.2 ; python_full_ve                                                                                                                                rsion >= "3.6.2" and python_version < "3.8" importlib-resources==5.4.0 ; python_full_version >= "3.6.2" and p                                                                                                                                ython_version < "3.9" ipaddress==1.0.23 ; python_full_version >= "3.6.2" and python_version < "4" js2py==0.71                                                                                                                                 ; python_full_version >= "3.6.2" and python_version < "4" jsonrpclib-pelix==0.4.3.1 ; python_full_version >=                                                                                                                                 "3.6.2" and python_version < "4" kodipydent-alt==2021.7.16 ; python_full_version >= "3.6.2" and python_versi                                                                                                                                on < "4" lxml==4.6.4 ; python_full_version >= "3.6.2" and python_version < "4" mako==1.1.5 ; python_full_vers                                                                                                                                ion >= "3.6.2" and python_version < "4" markdown2==2.4.1 ; python_full_version >= "3.6.2" and python_version                                                                                                                                 < "4" markupsafe==2.0.1 ; python_full_version >= "3.6.2" and python_version < "4" msgpack==1.0.2 ; python_ful                                                                                                                                l_version >= "3.6.2" and python_version < "4" new-rtorrent-python==1.0.1a0 ; python_full_version >= "3.6.2" a                                                                                                                                nd python_version < "4" oauthlib==3.1.1 ; python_full_version >= "3.6.2" and python_version < "4" packaging==                                                                                                                                21.2 ; python_full_version >= "3.6.2" and python_version < "4" pbr==5.7.0 ; python_full_version >= "3.6.2" an                                                                                                                                d python_version < "4" profilehooks==1.12.0 ; python_full_version >= "3.6.2" and python_version < "4" putio-p                                                                                                                                y==8.7.0 ; python_full_version >= "3.6.2" and python_version < "4" pyaes==1.6.1 ; python_full_version >= "3.6                                                                                                                                .2" and python_version < "4" pycparser==2.21 ; python_full_version >= "3.6.2" and python_version < "4" pygith                                                                                                                                ub==1.55 ; python_full_version >= "3.6.2" and python_version < "4" pyjsparser==2.7.1 ; python_full_version >=                                                                                                                                 "3.6.2" and python_version < "4" pyjwt==2.3.0 ; python_full_version >= "3.6.2" and python_version < "4" pyme                                                                                                                                diainfo==5.1.0 ; python_full_version >= "3.6.2" and python_version < "4" pynacl==1.4.0 ; python_full_version                                                                                                                                 >= "3.6.2" and python_version < "4" pynma==1.0 ; python_full_version >= "3.6.2" and python_version < "4" pyop                                                                                                                                enssl==21.0.0 ; python_full_version >= "3.6.2" and python_version < "4" pyparsing==2.4.7 ; python_full_versio                                                                                                                                n >= "3.6.2" and python_version < "4" pysocks==1.7.1 ; python_full_version >= "3.6.2" and python_version < "4                                                                                                                                " pysrt==1.1.2 ; python_full_version >= "3.6.2" and python_version < "4" python-dateutil==2.8.2 ; python_full                                                                                                                                _version >= "3.6.2" and python_version < "4" python-slugify==5.0.2 ; python_full_version >= "3.6.2" and pytho                                                                                                                                n_version < "4" python-twitter==3.5 ; python_full_version >= "3.6.2" and python_version < "4" python3-fanart=                                                                                                                                =2.0.0 ; python_full_version >= "3.6.2" and python_version < "4" pytz-deprecation-shim==0.1.0.post0 ; python_                                                                                                                                full_version >= "3.6.2" and python_version < "4" pytz==2021.3 ; python_full_version >= "3.6.2" and python_ver                                                                                                                                sion < "4" qbittorrent-api==2021.8.23 ; python_full_version >= "3.6.2" and python_version < "4" rarfile==4.0                                                                                                                                 ; python_full_version >= "3.6.2" and python_version < "4" rebulk==3.1.0 ; python_full_version >= "3.6.2" and                                                                                                                                 python_version < "4" requests-oauthlib==1.3.0 ; python_full_version >= "3.6.2" and python_version < "4" reque                                                                                                                                sts-toolbelt==0.9.1 ; python_full_version >= "3.6.2" and python_version < "4" requests==2.26.0 ; python_full_                                                                                                                                version >= "3.6.2" and python_version < "4" send2trash==1.8.0 ; python_full_version >= "3.6.2" and python_ver                                                                                                                                sion < "4" sgmllib3k==1.0.0 ; python_full_version >= "3.6.2" and python_version < "4" six==1.16.0 ; python_fu                                                                                                                                ll_version >= "3.6.2" and python_version < "4" soupsieve==2.3 ; python_full_version >= "3.6.2" and python_ver                                                                                                                                sion < "4" sqlalchemy==1.4.26 ; python_full_version >= "3.6.2" and python_version < "4" stevedore==3.5.0 ; py                                                                                                                                thon_full_version >= "3.6.2" and python_version < "4" subliminal==2.1.0 ; python_full_version >= "3.6.2" and                                                                                                                                 python_version < "4" text-unidecode==1.3 ; python_full_version >= "3.6.2" and python_version < "4" timeago==1                                                                                                                                .0.15 ; python_full_version >= "3.6.2" and python_version < "4" tmdbsimple==2.8.0 ; python_full_version >= "3                                                                                                                                .6.2" and python_version < "4" tornado==6.1 ; python_full_version >= "3.6.2" and python_version < "4" tus-py=                                                                                                                                =1.3.4 ; python_full_version >= "3.6.2" and python_version < "4" tvdbsimple==1.0.6 ; python_full_version >= "                                                                                                                                3.6.2" and python_version < "4" typing-extensions==3.10.0.2 ; python_full_version >= "3.6.2" and python_versi                                                                                                                                on < "3.8" tzdata==2021.5 ; python_full_version >= "3.6.2" and python_version < "4" tzlocal==4.1 ; python_ful                                                                                                                                l_version >= "3.6.2" and python_version < "4" unidecode==1.3.2 ; python_full_version >= "3.6.2" and python_ve                                                                                                                                rsion < "4" urllib3==1.26.7 ; python_full_version >= "3.6.2" and python_version < "4" validators==0.18.2 ; py                                                                                                                                thon_full_version >= "3.6.2" and python_version < "4" webencodings==0.5.1 ; python_full_version >= "3.6.2" an                                                                                                                                d python_version < "4" win-inet-pton==1.1.0 ; python_full_version >= "3.6.2" and python_version < "4" wrapt==                                                                                                                                1.13.3 ; python_full_version >= "3.6.2" and python_version < "4" xmltodict==0.12.0 ; python_full_version >= "                                                                                                                                3.6.2" and python_version < "4" zipp==3.6.0 ; python_full_version >= "3.6.2" and python_version < "3.9"
^CTraceback (most recent call last):
  File "/volume1/@appstore/sickchill/share/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/__init__.py", line 4, in <module>
    poetry_install()
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/init_helpers.py", line 402, in poetry_install
    pip_install(output)
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/init_helpers.py", line 225, in pip_install
    result = subprocess_call(cmd)
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/init_helpers.py", line 163, in subprocess_call
    stdout, stderr = process.communicate()
  File "/var/packages/python38/target/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/var/packages/python38/target/lib/python3.8/subprocess.py", line 1868, in _communicate
    ready = selector.select(timeout)
  File "/var/packages/python38/target/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

**Comment by turkeylegs1** [comment]
followed your further  DSM 7.1+ instructions on #8160  to the letter, but pkg still stops. syno 1821+ spk pkg.

**Comment by binbashblog** [comment]
I can confirm the develop docker image works now

**Comment by BKSteve** [comment]
@turkeylegs1 I think you misunderstood.
https://github.com/SickChill/sickchill/discussions/8160#discussioncomment-3659351
go to the google drive link and get build `sickchill_x64-7.0_20220928-6-Py310-07.spk`

**Comment by miigotu** [comment]
> I can confirm the develop docker image works now

I got rpi builds working too, just trying to get them to build from cryptography sources now for other architecture =P

**Comment by turkeylegs1** [comment]
> @turkeylegs1 I think you misunderstood. [#8160 (comment)](https://github.com/SickChill/sickchill/discussions/8160#discussioncomment-3659351) go to the google drive link and get build `sickchill_x64-7.0_20220928-6-Py310-07.spk`

@BKSteve put comment in #8160 - got link and installed proper spk -- (THANK YOU btw!) take a look at your convenience (and DM me way to donate to you and @miigotu pls).

**Comment by BKSteve** [comment]
https://github.com/SickChill/SickChill/wiki/Donations

**Comment by turkeylegs1** [comment]
> @turkeylegs1 https://github.com/SickChill/SickChill/wiki/Donations

got you. done.

**Comment by miigotu** [comment]
Docker image fixed as soon as master get built successfully
