### ISSUE TITLE
can't start with autoexec after moving to pip

### ISSUE THREAD

**Issue by fvolpe83** [SickChill/sickchill#8213]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: latest
OS: ubuntu 22.04
Browser: firefox
What you did: moved the installation to pip and changed the config files
What happened: sickchill doesn't start with systemctl start sickchill.service
What you expected: for sickchill to start

so this is what my sickchill.service looks like:

` ### Configuration

[Unit]
Description=SickChill Daemon
Wants=network-online.target
After=network-online.target

[Service]
User=microserver
Group=microserver

Type=forking
GuessMainPID=no
ExecStart=/usr/bin/python3 /opt/sickchill/bin/SickChill -q --daemon --nolaunch --datadir=/opt/sickchill

[Install]
WantedBy=multi-user.target`

but systemctl start sickchill returns the error:

`microserver@microserver:~$ sudo systemctl status sickchill
× sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-09-28 09:19:36 UTC; 3s ago
    Process: 2331 ExecStart=/usr/bin/python3 /opt/sickchill/bin/SickChill -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=1/FAILURE)
        CPU: 159ms

Sep 28 09:19:35 microserver systemd[1]: Starting SickChill Daemon...
Sep 28 09:19:36 microserver python3[2331]: Traceback (most recent call last):
Sep 28 09:19:36 microserver python3[2331]:   File "/opt/sickchill/bin/SickChill", line 5, in <module>
Sep 28 09:19:36 microserver python3[2331]:     from SickChill import main
Sep 28 09:19:36 microserver python3[2331]: ModuleNotFoundError: No module named 'SickChill'
Sep 28 09:19:36 microserver systemd[1]: sickchill.service: Control process exited, code=exited, status=1/FAILURE
Sep 28 09:19:36 microserver systemd[1]: sickchill.service: Failed with result 'exit-code'.
Sep 28 09:19:36 microserver systemd[1]: Failed to start SickChill Daemon. `

while launching from the console as:

` opt/sickchill/bin/SickChill --datadir /opt/sickchill `

returns no errors and sickchill starts normally

**Comment by kyuuk** [comment]
Hello @fvolpe83

Your execStart seems wrong 
it should look like this 
https://github.com/SickChill/sickchill/blob/78b659be2b9a6fe9045cfd8012465235f6a2d4a1/contrib/runscripts/init.systemd#L58

**Comment by miigotu** [comment]
> Hello @fvolpe83
> 
> Your execStart seems wrong it should look like this
> 
> https://github.com/SickChill/sickchill/blob/78b659be2b9a6fe9045cfd8012465235f6a2d4a1/contrib/runscripts/init.systemd#L58

Just fyi, for current and future releases sickchill and SickChill entrypoints are both made so there is no case issues 👍

Definitely is just using the system python instead of the venv python (the entrypoint knows to use the venv)

**Comment by fvolpe83** [comment]
solved, thanks for the inputs
I was using the same sickchill.service I've copied from the previous installation which had the "ExecStart=/usr/bin/python3" line
