### ISSUE TITLE
RSS Feeds are broken since tvcache.py was refactored

### ISSUE THREAD

**Issue by wyrickre** [SickChill/sickchill#8217]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: 2022.9.28
OS: Linux
Browser: Chrome
What you did: Upgraded to new version of SickChill.  It had been a while.
What happened: RSS Feeds stopped working.
What you expected: RSS Feeds should continue working.
Logs:
```
2022-09-29 14:53:44 DEBUG :: SEARCHQUEUE-DAILY-SEARCH :: [custom] :: Did not find size|seeders|leechers: None, 0, 0
```

The above message shows up for pretty much everything in the feed.... I went digging and found that https://github.com/SickChill/sickchill/pull/8124 had made a subtle change to how item_size gets computed.  The old code essentially always defaulted to -1 (even though that's not obvious).

**Comment by wyrickre** [comment]
To clarify.  If an RSS feed (or provider that was based on RSS like shazbat) did not have sizes in the feed.  They just stopped working.

**Comment by miigotu** [comment]
Fixed
