### ISSUE TITLE
Sickchill hasn't found any episodes for 2 weeks now

### ISSUE THREAD

**Issue by aurelien-joly** [SickChill/sickchill#8229]
Seems like the 2022.09.14 version broke something with nzb search, my sickchill hasn't found anything in 2 weeks. I've seen in the closed issue there was an issue that was fixed in the next release, but since i'm on synology it seems i'm stuck on this version until synocommunity can adapt the package to the mandatory pip install ?

Is there a way for me to force an update or am i stuck for the foreseable future ?

Version: 2022.09.14
OS: synology
Browser: chrome
What you did: started a manual search, but nothing has been found/downloaded since the 2022.09.14 version
What happened: nothing
What you expected: an episode to be found

**Comment by BKSteve** [comment]
Fixed in 20220928

**Comment by BKSteve** [comment]
If your DSM is x64 then updated SPK test package available under #8160.

**Comment by thatcow** [comment]
Any idea when 20220928 will be released on synocommunity?

**Comment by BKSteve** [comment]
Hopefully soon non x64 devices will have an SPK the SynoComm team are actively working on the cryptography build issue.

**Comment by miigotu** [comment]
@BKSteve this next release I think cryptography < 35 will work for SC, so we need to update the spk PR to just have SC in the requirements.txt

We need to remove more of the old code, and clean up. 

Even cryptography > 35 should be able to be built soon (I have a working workflow that builds wheels, need to fix some things with it and add auditwheel to make it portable)

**Comment by BKSteve** [comment]
@miigotu ready once the new SC with older cryptography (3.3.2) is. 
I'm also following SynoComm 5435 in regard wheels, that will bring an update python38 310 too.
