### ISSUE TITLE
Sickchill up.. but not up? (I don't know how to better else describe it)

### ISSUE THREAD

**Issue by zerosaber071** [SickChill/sickchill#8230]
Good day,

I recently had a power outage and when my server reboot, I tried accessing SickChill. after trying to to run they SickChill.py script, I get the notes below

Version: 22.04.1 LTS (GNU/Linux 5.15.0-48-generic x86_64)
OS: Ubuntu
Browser: Chrome
What you did: Power went out in my building
What happened: Server reboot, says sickchill is already running but can't view web page
What you expected: access to the sickchill webpage
Logs:
```
PASTE LOGS HERE
```
2022-10-03 17:22:17 INFO :: MAIN :: 397424: Unable to find IMDb show info in the database
2022-10-03 17:22:17 INFO :: MAIN :: Starting SickChill [2022.9.17] using '/opt/sickchill/config.ini'
2022-10-03 17:22:17 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2022-10-03 17:22:17 INFO :: WEBSERVER :: Could not start webserver on port 8081: already in use!

**Comment by miigotu** [comment]
`Could not start webserver on port 8081: already in use!`

Kill, stop, and uninstall anything using port 8081.

**Comment by miigotu** [comment]
Also, do not run SickChill.py, run SickChill (no py extension).

SickChill has to be installed with pip and run the installed entrypoint (`$VENV/local/bin/SickChill` or `$VENV/bin/SickChill`

**Comment by zerosaber071** [comment]
> Also, do not run SickChill.py, run SickChill (no py extension).
> 
> SickChill has to be installed with pip and run the installed entrypoint (`$VENV/local/bin/SickChill` or `$VENV/bin/SickChill`

Dumb question, how do I "run" SickChill without the py extension? Is just as simple as a service?

Sorry for for the dumb question, I am a bit rusty of ubuntu and I am also tired ha ha

**Comment by zerosaber071** [comment]
> Also, do not run SickChill.py, run SickChill (no py extension).
> 
> SickChill has to be installed with pip and run the installed entrypoint (`$VENV/local/bin/SickChill` or `$VENV/bin/SickChill`

Alright, it looks like it's back.

I followed this guide: https://github.com/SickChill/sickchill/discussions/8154

Thanks!
