### ISSUE TITLE
[APP SUBMITTED]: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by turkeylegs1** [SickChill/sickchill#8237]
### INFO
Python Version: **3.10.6 (main, Aug 28 2022, 13:50:45) [GCC 7.5.0]**
Operating System: **Linux-4.4.180+-x86_64-with-glibc2.26**
Locale: None
Version: **2022.9.28**
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Both pypi and GitHub were having issues this morning.

**Comment by turkeylegs1** [comment]
### INFO
Python Version: **3.10.6 (main, Aug 28 2022, 13:50:45) [GCC 7.5.0]**
Operating System: **Linux-4.4.180+-x86_64-with-glibc2.26**
Locale: None
Version: **2022.10.8**
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.11.4 (main, Jul 22 2023, 17:57:40) [GCC 8.5.0]**
Operating System: **Linux-4.4.302+-aarch64-with-glibc2.36**
Locale: None
Version: **2023.6.27**
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
