### ISSUE TITLE
Downloaded episode notification not working since 2022.10.8

### ISSUE THREAD

**Issue by binbashblog** [SickChill/sickchill#8258]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: 2022.10.08
OS: Ubuntu 22.04 (Kubernetes)

What happened: Snatched email notifications are being sent, however the downloaded notification no longer works. Test notifications get sent successfully. The 'notify on download' option is selected.
What you expected: Downloaded notifications to be sent to my email.

**Comment by miigotu** [comment]
Yes. Read the first line of the first post in this thread lol.

**Comment by BKSteve** [comment]
Just tested. Got [SN], [DL] and [PP] emails as expected.
The [DL] and [PP] emails come pretty much at the same time as SC only really knows it's downloaded when it's found in the folder when doing its Post Processing task.

**Comment by binbashblog** [comment]
> Yes. Read the first line of the first post in this thread lol.

I already did, thanks. Debug logging is enabled, found no entries about generating emails, do you have an example log entry when an email is generated so I can search for it?

Generating a test email from SickChill works, snatched emails are received, as they have been for the last 6 years.

PostProcessing works as expected, the 'DL' or 'PP' email just doesn't get sent. I receive the snatched email. Has been working for 6 years up until build 2022.10.8 (worked 2022.9.17 and below)

Config.ini shows notifications are enabled.

  email_notify_onsnatch = 1
  email_notify_ondownload = 1
  email_notify_onpostprocess = 1
