### ISSUE TITLE
Container no longer starting, poetry not found

### ISSUE THREAD

**Issue by seanmccabe** [SickChill/sickchill#8265]
Version: sickchill/sickchill:master
OS: Docker on Debian
Browser: N/A
What you did: Update to the latest master on Docker
What happened: Container will no longer start
What you expected: Container to start.
Logs:
```
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
/bin/sh: 1: poetry: not found
```

**Comment by miigotu** [comment]
Don't update inside the container. Pull the new container tag.

https://containrrr.dev/watchtower/ is what you need

**Comment by seanmccabe** [comment]
I didn't, pulled the new image and that was the issue I got.

Managed to resolve it by clearing out all the env variables and re-pulling.

**Comment by miigotu** [comment]
I believe you have to recreate (`docker-compose down` first, not just `docker-compose pull` and `docker-compose up`.

This is because the CMD instruction has changed, and just a pull and up keeps the old CMD.
