### ISSUE TITLE
[feature] Enable push notifications on logged errors

### ISSUE THREAD

**Issue by offbyone** [SickChill/sickchill#8270]
I would like to receive push notifications when there is an error logged in SickChill, at least the first time the error appears in the log. I generally try not to look at the system too much when it's working, but if I experience authentication failures to a search provider, I definitely want early notification of that.

How much work would it be to wire in the notification system to the error log filter? I'm happy to look into doing this myself, too, if that's the best way to achieve it.

**Comment by miigotu** [comment]
I imagine it could be done with a few lines in logger.py where it checks severity, adding a notifier method to each notifier, and some code in the web server and html to be able to change and save the settings for it.

**Comment by BKSteve** [comment]
https://github.com/SickChill/sickchill/discussions/8034

**Comment by offbyone** [comment]
Heh... that was also me :D
