### ISSUE TITLE
Poster order does not match sort criteria

### ISSUE THREAD

**Issue by oliv3r** [SickChill/sickchill#8275]
Version: 2022.10.13 (docker)
OS: Linux
Browser: Firefox
What you did: Sort posters by 'next episode'
What happened: Dates from the tiles do not match the order
What you expected: Posters sorted by dates

![image](https://user-images.githubusercontent.com/1245341/197612668-4443fa6c-85d3-4849-9001-42466d9b033f.png)
![image](https://user-images.githubusercontent.com/1245341/197612830-3b23f8fb-eb99-4593-b2bb-8b40f7b83c78.png)
![image](https://user-images.githubusercontent.com/1245341/197613357-4294ae4a-51b9-433f-9f0d-c9c08d9b986a.png)
I just noticed that ironically this paste, it actually was correct, but more then not this is not the case, see the second (which is my second) line as well.

I also realize, that half comes from bad data, but some shows really are weird. Some shows use the final expected episode date for sorting, some the last aired time, it's really quite messy ...

**Comment by BKSteve** [comment]
I've looked at this and every show that has a `next episode` poster is in the correct order, then after that where the `next episode` is blank it shows the `previous episode date` in the next episode position with the posters sorted in show alphabetical order.
You could confirm this by having the shows screen on 2 pages. Simple sort by Next Episode on one and Posts by Next Episode on the other.
This will need a little code examination and editing.

**Comment by oliv3r** [comment]
The show about handmaids is also interesting, if we look for example here http://rarbggo.org/tv/tt5834204/ we can see that the next episode is nov 2nd; whereas the last one nov 11th, and sickchill uses the final date, instead of the upcomming one?

**Comment by BKSteve** [comment]
Your system was still pending a refresh of handmaids as mine shows it with 2 Nov as next ep before Andor on 2 Nov as the time of release is also taken into account 11:55 and 14:41 my time respectively.
SC is very much dependent on theTVDB API and what's available from them through the API isn't always as up to date as their site.

**Comment by BKSteve** [comment]
Fix on develop branch
