### ISSUE TITLE
Encoding apostrophe on newznab api break query

### ISSUE THREAD

**Issue by mesa57** [SickChill/sickchill#8287]
Version: latest
OS: docker
Browser: firefox
What you did: show manuel search episode via indexer
What happened: could not find
What you expected: show is presen
Logs:
```
PASTE LOGS HERE
```

The call to the newznab indexer is broken by use of a apostrophe in showname exceptions.
In het log if following call : (showname is handmaid's tale)

`http://spotweb.xxxx.nl/api?t=tvsearch&limit=100&offset=0&cat=5000,5020,5030,5040,5050&maxage=500&apikey=&season=5&ep=8&q=the+handmaid&#39;s+tale+(2022)+S05E08
`
The apostrophe is encoded as htlm entity &39# 
As such is disrupts the parameters of the api en never reaches the target as expected. 
Please do not encode apostrophes on newznab api calls.

**Comment by miigotu** [comment]
You are incorrect. You used the wrong quote in a scene exception for the handmaid's tale.

```python
import urllib.parse
print(urllib.parse.quote_plus("the handmaid's tale"))
```

Correct result 
```bash
the+handmaid%27s+tale
```

Quotes MUST be encoded to send them as a query parameter. 

Correct the quote in the title of the show. If it comes from thetvdb, fix it there. If it comes from you setting a custom show name or a scene exception with the incorrect quote, fix it there.

**Comment by mesa57** [comment]
As I use docker i have no influence over imports.
As a said, the name come's from show's exceptions list.
It is just entered as the handmaid's 
But the call sickchill does is encoded with an html entity &#39;
How can i prevent this then ?

**Comment by miigotu** [comment]
Using docker makes no difference as to whether you can change exceptions. Docker behaves 100% the same as if you ran it in a venv or installed it directly into the system python environment. 

It's possible that it is double encoded, because it's coming from JavaScript then to python.

I will take a look, but it would have to fail for a regular search also if it is from a external indexer

**Comment by miigotu** [comment]
Looks like we need an `html.unescape` call.
Next time, unless you have a fix don't tell me what we are doing wrong, because you were wrong.

**Comment by mesa57** [comment]
Thank you for putting the blame on me. I would gladly accept that if i knew what i am doing wrong ?

**Comment by BKSteve** [comment]
The default name in SC is ‘the handmaids tale’ without #39

**Comment by mesa57** [comment]
I know that's the default, but I added an exception name.
But i never used &#39; 
That's encoded by sickchill on the call to the newznab indexer.

**Comment by mesa57** [comment]
I editted the exception in cache.db manually with sqlite db editor and changed &#39;  into ' (apostrophe).
This time the call to the newznab provider was better encoded : 

`http://spotweb.xxxxx.nl/api?t=tvsearch&limit=100&offset=0&cat=5000%2C5020%2C5030%2C5040%2C5050&maxage=500&apikey=xxxxx&season=5&ep=8&q=the+handmaid**%27**s+tale+%282022%29+S05E08 [Status: 200]`

and the episode was found.

**Comment by mesa57** [comment]
I hardly see editing a database manually as a solution.
