### ISSUE TITLE
No longer know how to start sickchill

### ISSUE THREAD

**Issue by pjrettin** [SickChill/sickchill#8291]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version:latest
OS: Ubuntu 22.04

Before I updated to the latest version, I used to start sickchill using this command:
pjrettin@nas:~$ sudo python3 /opt/sickrage/SickChill.py -d

When I updated last, sickchill took care of restarting itself (after the update - and I haven't had to start it manually again since today.

When I use the same command now I get:

pjrettin@nas:~$ sudo python3 /opt/sickrage/SickChill.py -d
Traceback (most recent call last):
  File "/opt/sickrage/sickchill/init_helpers.py", line 11, in <module>
    from importlib.metadata import Distribution, PackageNotFoundError  # noqa
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sickrage/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickrage/sickchill/__init__.py", line 1, in <module>
    from sickchill.init_helpers import maybe_daemonize
  File "/opt/sickrage/sickchill/init_helpers.py", line 13, in <module>
    from importlib_metadata import Distribution, PackageNotFoundError  # noqa
ModuleNotFoundError: No module named 'importlib_metadata'

This may no longer be the correct way to start sickchill.  I've tried to follow numerous guides online for starting using systemctl but without success.

I just need to know how to start it lol.

**Comment by miigotu** [comment]
SickChill has to be installed now, so you probably have a virtualenv in /opt/SickChill, see if this file exists: `/opt/SickChill/.venv/bin/sickchill` . If not, back up your config.ini and sickchill.db and do a reinstall with the debian/Ubuntu installer in the contrib folder or follow the wiki guide for Ubuntu 14/15+

Your service file should never call SickChill.py anymore, it has to use the file in the bin folder of the virtualenv.

**Comment by pjrettin** [comment]
I'm not sure I understand... sickchill was working, up and running.  I had a power outage, so I needed to restart it.. isn't there a way to start it the way it was started when it restarted itself after the upgrade?

**Comment by miigotu** [comment]
Negative. SC cannot update itself to the newest version because the install method has changed months ago. backup your config.ini and sickchill.db and follow this guide:
https://github.com/SickChill/SickChill/wiki/SickChill-installation-Debian-Ubuntu-14-15-16
Or
https://github.com/SickChill/SickChill/wiki/Pip#ubuntudebian

**Comment by pjrettin** [comment]
This worked thanks.  After installing I had an issue with permissions with post-processing.  I tried fixing by adding the sickchill user to the same group that had correct permissions, but this didn't work - so I ended up changing the user sickchill runs with.

Thanks for your help and time.
