### ISSUE TITLE
 Cant Install On Raspberry Pi

### ISSUE THREAD

**Issue by tomkinane** [SickChill/sickchill#8303]
Version:
OS: Raspberry Pi
What you did: Followed the HTPC Guides (Install SickRage Raspberry Pi for Usenet Torrent TV)
What happened: Cant install I think the guides are outdated

**Comment by miigotu** [comment]
SickChill is not SuckRage. That guide hasn't been updated in like 6 years iirc.

Check our wiki here on GitHub for the raspberry pi. There is even a script in the contrib folder that's for debian/Ubuntu based OS, you just run it with sudo and it will set SC up and install a service for it.

**Comment by miigotu** [comment]
SickChill is not SuckRage. That guide hasn't been updated in like 6 years iirc.

Check our wiki here on GitHub for the raspberry pi. There is even a script in the contrib folder that's for debian/Ubuntu based OS, you just run it with sudo and it will set SC up and install a service for it. 

```bash
wget https://raw.githubusercontent.com/SickChill/sickchill/master/contrib/debian-ubuntu-install.sh

chmod +x debian-ubuntu-install.sh
./debian-ubuntu-install.sh
#follow in screen instruy
```

**Comment by miigotu** [comment]
SickChill is not SuckRage. That guide hasn't been updated in like 6 years iirc. We don't have control of 3rd party sites like htpcguides, but we would gladly work with them to get the guide updated. 

Check our wiki here on GitHub for the raspberry pi. There is even a script in the contrib folder that's for debian/Ubuntu based OS, you just run it with sudo and it will set SC up and install a service for it. 

```bash
wget https://raw.githubusercontent.com/SickChill/sickchill/master/contrib/debian-ubuntu-install.sh

chmod +x debian-ubuntu-install.sh
./debian-ubuntu-install.sh
#follow in screen instruy
```
