### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/sickchill/json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

### ISSUE THREAD

**Issue by itsme9x** [SickChill/sickchill#8306]
### INFO
Python Version: **3.10.8 (main, Oct 12 2022, 23:40:30) [GCC 7.5.0]**
Operating System: **Linux-4.4.180+-aarch64-with-glibc2.26**
Locale: None
Version: **2022.10.13**
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/sickchill/json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.10.10 (main, Feb 28 2023, 12:20:17) [GCC 8.5.0]**
Operating System: **Linux-4.4.180+-aarch64-with-glibc2.26**
Locale: None
Version: **2023.1.2**
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/sickchill/json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
More details. 
Device and OS. 

Have you done anything recently? Upgraded something?
