### ISSUE TITLE
Infinite update loop

### ISSUE THREAD

**Issue by Telecart** [SickChill/sickchill#8332]
Version: 2022.10.13
OS: MacOS
Browser: Whatever
What you did: Turned off auto-update for now.
What happened: Auto-update is stuck in a loop, it keeps installing and relaunching and finding that it's the same version it was before, and installing again.
What you expected: for it to update normally to 2023.1.2
Logs: I turned on debug logging but it's just a long list of stuff looking like this, there's no discernible error.
```
2023-01-02 20:25:03 INFO :: CHECKVERSION :: Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=3.2->pyOpenSSL<24.0.0,>=20.0.1->sickchill) (2.20)
```

**Comment by miigotu** [comment]
What happens if you update it yourself manually? Enter the sickchill virtualenv if you are using one, and `python3.10 -m pip install -U sickchill` or whichever python your sickchill uses.

**Comment by Telecart** [comment]
Same thing; long list of "Requirement already satisfied, skipping upgrade", then I run sickchill.py again and it loads 2022.10.13.

**Comment by miigotu** [comment]
sickchill.py isn't supposed to be ran, the `/bin/sickchill` script is.

**Comment by andreofgyn** [comment]
I resolved that same issue by manually deleting the older sickchill folder inside site-packages, eg: sickchill-2022.9.28.dist-info and then:

`python -m pip install -U sickchill`

I also updated my pip before doing that:

`python -m pip install --upgrade pip`

**Comment by Telecart** [comment]
> sickchill.py isn't supposed to be ran, the /bin/sickchill script is.

I've never ran it from there before, but I gave it a try, it spat this back:
ImportError: cannot import name 'setup_lib_path' from 'sickchill.init_helpers' (/Users/telecart/Library/Python/3.8/lib/python/site-packages/sickchill/init_helpers.py)



> I resolved that same issue by manually deleting the older sickchill folder inside site-packages, eg: sickchill-2022.9.28.dist-info and then:
> 
> `python -m pip install -U sickchill`
> 
> I also updated my pip before doing that:
> 
> `python -m pip install --upgrade pip`

Yesss this worked! 
I tried it and at first, it reverted to an even older version! I then pursued to delete _all_ the outside folders and it decided to finally load 2023.1. Huzzah! Thanks for the help.

**Comment by davidreverett** [comment]
@andreofgyn provided solution worked for me as well. Same exact thing happened. May want to pin this for the Windows installs.

**Comment by miigotu** [comment]
Prior to the 2022.10.2 (I think that's the date) release the updater was broken, and was a known issue that required a manual update if you search the issues. I believe the solution is pinned already. Once on the newer versions (2022.10.28+ I think) the issue is gone and shouldn't happen anymore.

**Comment by Telecart** [comment]
just as an FYI, hasn't happened in a while but happened again with 5.30.2023 update, same solve worked to fix it, deleted the outside folder and it updated fine.

**Comment by miigotu** [comment]
We don't use GitHub for issues anymore. Reinstall with the latest updater.

https://discord.com/channels/502612977271439372/1112387941755539546
