### ISSUE TITLE
Episode names that start with number marked as missing even when present

### ISSUE THREAD

**Issue by jonthewise** [SickChill/sickchill#8334]
Version: 2022.10.13 
OS: CentOS Linux release 7.9.2009 (Core)
Browser: Safari
What you did: Force Full update
What happened: Episodes whose names start with numbers are marked as wanted even when they exist
What you expected: Episodes that exist being marked as present
Logs:
No logs for this, and I work around the issue by marking the episode as ignored so it stops trying to get it again, but it's been around for a while. Just thought to report it today after noticing it on both my Family Guy and Simpsons shows after a force full update that I ran because my VPN connection was down for 3 weeks and I didn't notice that episode information had gone stale. Probably should have just waited for it to refresh on it's own, but I was being impatient.

**Comment by miigotu** [comment]
What are the episode names? Likely it's your naming pattern that presents this issue, so what's your naming pattern as well?

**Comment by jonthewise** [comment]
Naming pattern: 

%S.N_Season-%0S/%S.N-S%0SE%0E-%E.N_%Q.N

These are the episodes that I currently see the issue occurring on:

Family.Guy-S11E16-12.and.a.Half.Angry.Men_720p.HDTV.mkv
Family.Guy-S12E13-3.Acts.of.God_720p.HDTV.mkv

Robot.Chicken-S02E06-1987_SD.DVD.mp4

The.Simpsons-S30E15-101.Mitigations_1080p.WEB.DL.mkv

**Comment by BKSteve** [comment]
My naming pattern is not much different, using . instead of - but also no season folder, I just keep everything flat.
`%S.N.S%0SE%0E.%E.N.%SQ.N`

And these are snatched, force update and files rescanned without issue. Nothing gets set back to wanted.
`Robot.Chicken.S09E06.3.2.1.2.3.3.3,.2.2.2,.3...6.6.HDTV.x264.mkv`
`Robot.Chicken.S02E06.1987.720p.HDTV.mp4`
Did this test on my Synology pip Version: 2023.1.2

Then did test using the `%S.N_Season-%0S/%S.N-S%0SE%0E-%E.N_%Q.N` on my develop machine.
Copied the 2 files and post processed them in. Named and sub-folders created.
Force full update, no issues the 2 files weren't reverted to wanted or archived.

**Comment by BKSteve** [comment]
Seeing that `%S.N.S%0SE%0E.%E.N.%SQ.N` results in `standard` regex and `%S.N-S%0SE%0E-%E.N_%Q.N` does not.
The regex below `# linking e/- char` is probably the reason `standard` and others are not met and it goes into `season only` regex and fails to match.

```
        "standard",
        # Show.Name.S01E02.Source.Quality.Etc-Group
        # Show Name - S01E02 - My Ep Name
        # Show.Name.S01.E03.My.Ep.Name
        # Show.Name.S01E02E03.Source.Quality.Etc-Group
        # Show Name - S01E02-03 - My Ep Name
        # Show.Name.S01.E02.E03
        r"""
     ^((?P<series_name>.+?)[. _-]+)?             # Show_Name and separator
     \(?s(?P<season_num>\d+)[. _-]*              # S01 and optional separator
     e(?P<ep_num>\d+)\)?                         # E02 and separator
     (([. _-]*e|-)                               # linking e/- char
     (?P<extra_ep_num>(?!(1080|720|480)[pi])\d+)(\))?)*   # additional E03/etc
     ([. _,-]+((?P<extra_info>.+?)                 # Source_Quality_Etc-
     ((?<![. _-])(?<!WEB)                        # Make sure this is really the release group
     -(?P<release_group>[^ -]+([. _-]\[.*\])?))?)?)?$              # Group
     """,
```

Work around would be use different `naming pattern` separator character.
