### ISSUE TITLE
SC suddenly downloading old episodes

### ISSUE THREAD

**Issue by Tiwas** [SickChill/sickchill#8338]
I've had this happening on a few occasions before, but the last three days I've awakened to a lot of old episodes being downloaded. It's just an annoyance, but maybe something that should be looked into? The only thing in common (as far as I can see) is that the episodes are marked as archived, the files are deleted from the filesystem, and the quality is either set as preferred or unknown.

It would be nice if this could be resolved, but I guess it's not one of the most pressing concerns :)

I'm on the latest synology build.

**Comment by BKSteve** [comment]
#7390
