### ISSUE TITLE
[APP SUBMITTED]: 400 Client Error: Bad Request for url: https://discordapp.com/api/webhooks/1068009960052641914/Kihl0heVZLpweqsJ1zzr_MvZCCrXE5BOr274uwEtl6wsq1C4P76VqL2kk2CcsoXi-wvT

### ISSUE THREAD

**Issue by midnightx12** [SickChill/sickchill#8350]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19044-SP0**
Locale: cp1252
Version: **2023.1.2**
Link to Log: https://gist.github.com/f4e550038c9209e6d9dac52450271f00
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
#8351
