### ISSUE TITLE
[APP SUBMITTED]: 400 Client Error: Bad Request for url: https://discordapp.com/api/webhooks/1068013057617432597/wrI0sloLyEVD2YPSbr2WFf5o23C1hHeds-eEu-YzYlt-ZwvlrOH22LJ8g6pMMWT0Fs7k

### ISSUE THREAD

**Issue by midnightx12** [SickChill/sickchill#8351]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19044-SP0**
Locale: cp1252
Version: **2023.1.2**
Link to Log: https://gist.github.com/4d1548dbece0ac565efbea3558bc169a
### ERROR
```
Uncaught exception %s
%r
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Wally73** [comment]
#8339
