### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: 'Star.Wars.The.Bad.Batch.S02E05.Entombed.2160p.WEB-DL.DDP5.1.H.265-NTb[eztv.re].mkv.torrent'

### ISSUE THREAD

**Issue by mrspidey** [SickChill/sickchill#8353]
### INFO
Python Version: **3.8.5 (default, Oct  1 2020, 11:57:13) [GCC 4.9.2]**
Operating System: **Linux-5.10.60-qnap-x86_64-with-glibc2.2.5**
Locale: UTF-8
Version: **2023.1.2**
Link to Log: https://gist.github.com/4ed24537bcc0d610b78b34f091a8a79c
### ERROR
```
put.io: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Guessing your put.io ran out of space or the account wasn't paid? Check the account status. Ping me back here if I'm wrong and I'll reopen this.

**Comment by mrspidey** [comment]
Hi thanks for the quick reply back. Unfortunately, it seems to be happening again. I made sure I had enough space and my account is active. Not quite sure what's going on as it was working, and then suddenly the error happened.

**Comment by miigotu** [comment]
I would check if your jackett was just recently updated, because there have been a few different reports about issues for people using jackett, and sickchill hasn't changed for a long time now.

**Comment by mrspidey** [comment]
I can't tell if it did or didn't tbh, but I did just force an update. Would that update somehow affect put.io uploads?

**Comment by Sickchilldavid** [comment]
### INFO
Python Version: **3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22621-SP0**
Locale: cp1252
Version: **2023.6.27**
No Log available with ERRORS:
### ERROR
```
There was a problem copying a file from \\10.23.0.6\Torrents\Invasion.2021.S02E05.MULTI.1080p.WEB.H264-HiggsBoson\invasion.2021.s02e05.multi.1080p.web.h264-higgsboson\invasion.2021.s02e05.multi.1080p.web.h264-higgsboson.mkv to V:\TV Shows\Invasion (2021)\Invasion (2021).S02E05.A Voice From the Other Side.mkv. Error: [Errno 2] No such file or directory
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Sickchilldavid** [comment]
### INFO
Python Version: **3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22621-SP0**
Locale: cp1252
Version: **2023.6.27**
No Log available with ERRORS:
### ERROR
```
Unable to copy file from \\10.23.0.6\Torrents\Invasion.2021.S02E05.MULTI.1080p.WEB.H264-HiggsBoson\invasion.2021.s02e05.multi.1080p.web.h264-higgsboson\invasion.2021.s02e05.multi.1080p.web.h264-higgsboson.mkv to V:\TV Shows\Invasion (2021)\Invasion (2021).S02E05.A Voice From the Other Side.mkv: [Errno 2] No such file or directory
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
