### ISSUE TITLE
2023.1.2 tag missing in docker hub

### ISSUE THREAD

**Issue by binbashblog** [SickChill/sickchill#8360]
Has the workflow changed as releases used to be tagged, but only Master seems to point to 2023.1.2.

**Comment by miigotu** [comment]
No, for some reason the workflow was cancelled.
https://github.com/SickChill/sickchill/actions/runs/3826052725

I will re-run it now and that will push to docker.

**Comment by miigotu** [comment]
Actually, it won't let me re-run it, you can just use the latest docker tag and it will update itself inside the container.

I will have to re-tag it on my PC sometime soon to have it built and pushed.

**Comment by miigotu** [comment]
Should be up now
