### ISSUE TITLE
Episodes that had been downloaded and are still present, are now in various archived states1

### ISSUE THREAD

**Issue by richardlnd** [SickChill/sickchill#8362]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: 2023.1.2
OS: Win7
Browser: Chrome/Edge

What you did: Apparently some issues happened with the some of the drive enclosures on the main server which at some point degraded and took storage spaces of the series media offline. This was then fixed and restored with same share and drive/volume designations.

What happened: I noticed that some of the series, including active ones listed downloaded episodes as archived, The active ones however happily added new episodes in the same file structure and marked them correctly. I tried to mass update scan in order for the software to recognise the files again, but this did not happen.
Manual status update management only seemed to work (i think ) for some of the entries marked archived. - i noticed log entries like this: Refusing to change status of 1x1 to DOWNLOADED because it's not SNATCHED/DOWNLOADED

What you expected: I was expecting the episode statusses to be marked back to downloaded either through the scanning process or the status update process

Some incident research:
https://github.com/SickChill/sickchill/issues/6407
- May look the same if the files were still present, it does not seem to say in the incident. If they were setting t ignore might not be the desired result.
https://github.com/SickChill/sickchill/issues/5569
- Similar issue, but with difference that file system designations did not change. The expectation would be that the system would recognise the files if in the same place.
https://github.com/SickChill/sickchill/issues/5194
- Related but not the same. More of a bump as it is a little annoying to find and fix each version of archived.

Logs: Unsure what to log exactly, could you maybe first look at providing some advise. If it is tough luck you won't get this into downloaded that would save us both some time.
```
PASTE LOGS HERE
```

**Comment by BKSteve** [comment]
Did you try `rescan files` or once the drive was available again setting them to ` downloaded x-format`?

**Comment by miigotu** [comment]
Your share was offline, and the default status for files that were there and no longer are is archived when the show refresh/update thread runs on each show. The only thing you can do is remove and add-existing for the show, or just leave them as archived. Archived is the best state for all episodes once you have the quality you want for them, because the providers wont be spammed for them anymore.
