### ISSUE TITLE
AA OverflowError: mktime argument out of range

### ISSUE THREAD

**Issue by binbashblog** [SickChill/sickchill#8373]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: 2023.1.2
OS: Ubuntu 22.04 - rpi4 arm64 running k3s & containerd
Browser:
What you did: manual postprocessing
What happened: postprocessing failed
What you expected: postprocessing succeed
Logs:
```
AA OverflowError: mktime argument out of range
AA if helpers.touchFile(self.location, time.mktime(airdatetime)):
AA File "/.venv/lib/python3.10/site-packages/sickchill/tv.py", line 2537, in airdateModifyStamp
AA ep_obj.airdateModifyStamp()
AA File "/.venv/lib/python3.10/site-packages/sickchill/oldbeard/postProcessor.py", line 1173, in process
AA result.result = processor.process()
AA File "/.venv/lib/python3.10/site-packages/sickchill/oldbeard/processTV.py", line 493, in process_media
AA process_media(current_directory, video_files, release_name, process_method, force, is_priority, result)
AA File "/.venv/lib/python3.10/site-packages/sickchill/oldbeard/processTV.py", line 191, in process_dir
```

I get the above repeatedly, some shows succeed whereas some don't.

**Comment by miigotu** [comment]
Disable the post process setting "modify timestamps", we don't control the dates that thetvdb gives us for the airdate of the episodes.
