### ISSUE TITLE
docker hub image not found

### ISSUE THREAD

**Issue by gits68** [SickChill/sickchill#8386]
query : https://hub.docker.com/search?q=sickshill

answer :
No results
There are no results for sickshill in Docker Hub.

**Comment by gits68** [comment]
didn't understand, it works using docker-compose !
```
# docker-compose config
services:
  sickchill:
    container_name: sickchill
    image: sickchill/sickchill:latest
...

# docker-compose pull
Pulling sickchill ... done
```

**Comment by BKSteve** [comment]
Check your spelling. 
SickChill 
Not sickshill. No shills here
