### ISSUE TITLE
[APP SUBMITTED]: Unable to create the folder \\F35-NAS\KODI\TV_SHOWS\Dr. Stone, can't add the show

### ISSUE THREAD

**Issue by Fhayat** [SickChill/sickchill#8420]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22621-SP0**
Locale: cp1252
Version: **2023.1.2**
No Log available with ERRORS:
### ERROR
```
Unable to create the folder \\F35-NAS\KODI\TV_SHOWS\Dr. Stone, can't add the show
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
Usually folder permissions
