### ISSUE TITLE
Request failed: Missing dependencies for SOCKS support. (InvalidSchema)

### ISSUE THREAD

**Issue by muresan** [SickChill/sickchill#8421]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: 2023.1.2
OS: Linux
Browser: Chrome
What you did: Set proxy to socks5://IP:port/
What happened: Connectivity errors
What you expected: requests to work
Logs:
```
sickchill  | 2023-04-18 19:29:41 DEBUG :: MAIN :: Using global proxy: socks5://192.168.0.45:1080
sickchill  | 2023-04-18 19:29:41 INFO :: MAIN :: Request failed: Missing dependencies for SOCKS support. (InvalidSchema)
```
I've installed the package `pysocks` (`pip3 install pysocks`) and stopped/started the process, it works after that.
I assume `pysocks` should be added to the dependencies list for the main package unless there is another option.

Thanks.

**Comment by miigotu** [comment]
When a person sets up a socks proxy usually they would install that dependency themselves. However, I can add it to a special group in poetry and document it, or installed it automatically if someone tried to use a socks proxy.

**Comment by miigotu** [comment]
If you need further support, all support and bug reports and everything other than code/releases has been moved to discord. https://discord.gg/7yebVwpntc
