### ISSUE TITLE
NAS as download folder in Windows

### ISSUE THREAD

**Issue by Zetsuo** [SickChill/sickchill#8426]
I already map the drive. But I dont have it as a option for storage in Sickchill for windows. Can you help me?

Already edit the service with nssm and windows service app to change the log on to my user. It Didn't work

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version:
OS: windows 11 
Browser:
What you did: look out for the mapped nas 
What happened: didn't find it 
What you expected: find it 
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
https://github.com/SickChill/windows-sickchill/issues/41

**Comment by Smokey23** [comment]
You can also do it by adding a symlink in a folder on your HDD to the directory on the NAS share.  So in Sickchill, you would put the location on your HDD (C:\whatever in the example below) and it would think it was looking at your HDD when it would really be browsing the folder on the NAS.

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink

mklink /d C:\whatever \\nas\share

**Comment by miigotu** [comment]
If you need further support, all support and bug reports and everything other than code/releases has been moved to discord. https://discord.gg/7yebVwpntc
