### ISSUE TITLE
Sickchill proxy issues

### ISSUE THREAD

**Issue by valheru** [SickChill/sickchill#8430]
Version: 
- Install: pip
- Version: 2023.1.2
- Database Version: 44.5

OS: Ubuntu 22.04 Kernel 5.15.0.56
Browser: Firefox 102.10.0esr and Chrome 113.0.5672.63
What you did: Run sickchill behind an apache proxy
What happened: Page loaded, then dissapeared and got replaced with a lot of 'Undefined' messages
What you expected: No undefined messages
Logs:
```
2023-05-04 11:20:23 INFO :: WEBSERVER-UI_0 :: A mako error occurred: HTTP 400: Bad Request (Missing argument level)
2023-05-04 11:21:33 INFO :: WEBSERVER :: User logged into the SickChill web interface
2023-05-04 11:21:51 INFO :: WEBSERVER-UI_0 :: A mako error occurred: HTTP 400: Bad Request (Missing argument level)
2023-05-04 11:22:22 DEBUG :: POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2023-05-04 11:22:22 INFO :: POSTPROCESSOR :: Auto post processing task for /data/Downloads/TV was added to the queue
2023-05-04 11:22:23 INFO :: POSTPROCESSOR-AUTO :: Beginning auto post processing task: /data/Downloads/TV
2023-05-04 11:22:23 DEBUG :: POSTPROCESSOR-AUTO :: Processing in folder /data/Downloads/TV
2023-05-04 11:22:23 INFO :: POSTPROCESSOR-AUTO :: Processing /data/Downloads/TV
2023-05-04 11:22:23 DEBUG :: POSTPROCESSOR-AUTO :: Processing folder /data/Downloads/TV
2023-05-04 11:22:23 DEBUG :: POSTPROCESSOR-AUTO :: /data/Downloads/TV : No processable items found in folder
2023-05-04 11:22:23 INFO :: POSTPROCESSOR-AUTO :: Successfully processed
2023-05-04 11:22:23 INFO :: POSTPROCESSOR-AUTO :: Auto post processing task for /data/Downloads/TV completed
2023-05-04 11:22:46 INFO :: WEBSERVER-UI_0 :: A mako error occurred: HTTP 400: Bad Request (Missing argument level)
2023-05-04 11:23:17 INFO :: WEBSERVER-UI_0 :: A mako error occurred: HTTP 400: Bad Request (Missing argument level)
2023-05-04 11:23:42 INFO :: WEBSERVER-UI_0 :: A mako error occurred: HTTP 400: Bad Request (Missing argument level)
```

I have a perfect working SichChill install when I'm on my own network, however I wanted to be able to access it from a few other places as well so I setup an apache proxy, this worked fine for a while until recently I got `Undefined ` messages in my screen.
I tried several things with the proxy but I couldn't get it to work again.
I ran the webdeveloper tools and noticed a few things:

1. A loop of 26314 times this html:
```
<div class="alert alert-undefined upgrade-notification hidden-print" id="site-message-99" role="alert"><span>undefined</span><span class="glyphicon glyphicon-check site-message-dismiss pull-right" data-id="99"></span></div>
```

2. An error about endpoint not connected on the second line of this function:
```
async function CheckIfURLShouldBeBlocked() {
  const siteList = await browser.runtime.sendMessage({
    message: "what-sites-are-added"
  });
```

My proxy config (anonymized and auth hash changed):

```
<VirtualHost *:443>
    ServerName <external.url>

    ServerAdmin <email>
    DocumentRoot /var/www/html

    SSLEngine on
    SSLCertificateFile          /etc/letsencrypt/live/<hostname>/cert.pem
    SSLCertificateKeyFile       /etc/letsencrypt/live/<hostname>/privkey.pem
    SSLCertificateChainFile     /etc/letsencrypt/live/<hostname>/fullchain.pem

    RewriteEngine On
    RewriteCond %{REQUEST_URI} ^\/(home|css|js|images|ui|fonts|cache|login).*$
    RewriteRule (.*) https://<external.url>/sickchill%{REQUEST_URI} [R=301,L]

    <Location /sickchill/>
        ProxyPass http://10.0.1.1:8081/
        ProxyPassReverse http://10.0.1.1:8081/

        AuthType Basic
        AuthUserFile /etc/apache2/munin-htpasswd
        AuthName "Protected Area"

        <RequireAny>
            Require local
            Require ip <several dedicated ips>
            Require valid-user
        </RequireAny>

        RequestHeader set Authorization: "Basic <authhash>"
    </Location>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

If I acces SickChill directly from my lan it works fine so there is an issue with the proxy config.
Of course I have set the handle reverse proxy to 1 in the config and set a username and password, I do get a correct login prompt, can login, I see the overview of shows loading and then it gets replaced by this:

![image](https://user-images.githubusercontent.com/1986012/236170071-0af31af4-e5a1-40f0-abe3-e32269900394.png)

Please help me figuring out what the problem is, I know this worked fine a few weeks ago..

**Comment by kyuuk** [comment]
Hello, 

this might be your apache configuration that is doing this (you are making url rewrites !), you might want to check your network log on your browser (prerry sure there will be some 404)

i personally have pretty much the same setup except that i'm using Nginx and not doing rewrites, 

instead i configured Sickchill webroot to be `/sickchill` you can do this be editing your config.ini in the General section at the key `web_root`
![image](https://user-images.githubusercontent.com/16566073/236649015-959dc0f3-cd97-4edb-a706-00e2f1f6bd65.png)

with this i think you can remove these two lines 
```
    RewriteCond %{REQUEST_URI} ^\/(home|css|js|images|ui|fonts|cache|login).*$
    RewriteRule (.*) https://<external.url>/sickchill%{REQUEST_URI} [R=301,L]
```

and everything should work

**Comment by valheru** [comment]
Thank you for your response, I will try your suggestion tomorrow. 
I ended up with the rewrites since my SickChill install was way before I started using apache and I also rewrite several other things in the same way (munin, .well-known for letsencrypt, etc) but your suggestion seems a way better way to handle things.

**Comment by valheru** [comment]
It took a little longer to test but your  your solution worked.
I do wonder why my proxy config used to work and stopped working suddenly but hey, if it ain't broke don't try to fix it ;)

Thank you for your help.

**Comment by kyuuk** [comment]
Happy to read that 😄
