### ISSUE TITLE
tvdb episode parsing issue

### ISSUE THREAD

**Issue by vtol79** [SickChill/sickchill#8438]
Version: [2023.1.2]
OS: lscr.io/linuxserver/sickchill:latest (Linux-5.10.0-18-amd64-x86_64-with) (same issue with older releases)
Browser: 
What you did: addings tvshow from tvdb e.g. Series #260845
What happened: theTVDB timed out, unable to create the episode
What you expected: no error :)

Looks like an tvdbsimple issue. API change?!

Logs:
```
2023-05-12 21:53:38 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Could not find item on the indexer: (Indexer probably does not have this item) ['NoneType' object is not iterable]
2023-05-12 21:53:38 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
    result = target(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
    result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
  File "/usr/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
    episodes.extend(self.page(i))
TypeError: 'NoneType' object is not iterable

2023-05-12 21:53:38 ERROR :: SHOWQUEUE-FORCE-UPDATE :: theTVDB timed out, unable to create the episode
```

**Comment by vtol79** [comment]
Getting the data via tvdbsimple seems to work fine.

```
import tvdbsimple as tvdb
tvdb.KEYS.API_KEY = '6aa6e4ecae5b56e9644f6a303c0739b6'
show = tvdb.Series(260845)
episodes = show.Episodes.all()
for i in episodes:
    print(i.get('episodeName'))
```

**Comment by ejc1967** [comment]
Version: [2023.1.2]
OS: Linux-3.10.108-x86_64-with-glibc2.26 (Synology DS3615xs DSM 7.1.1-42962 Update 5
What you did: Force Full Update
What happened: Episodes got removed from database also got an airdate of 'never'

Looks like I had a similar issue.
Did the Force Full Update after finding that some Episodes had already been removed automatically.

Logs:

2023-05-12 20:00:28 INFO :: SHOWQUEUE-FORCE-UPDATE :: 337907: Updating NFOs for show with new indexer info
AA 2023-05-12 20:00:27 DEBUG :: SHOWQUEUE-FORCE-UPDATE ::
AA 2023-05-12 20:00:27 DEBUG :: SHOWQUEUE-FORCE-UPDATE ::
...
...
AA 2023-05-12 20:00:19 DEBUG :: SHOWQUEUE-FORCE-UPDATE ::
AA 2023-05-12 20:00:19 DEBUG :: SHOWQUEUE-FORCE-UPDATE ::
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Performing refresh on 9-1-1
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E03 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E05 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E06 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E09 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E18 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E12 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E11 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E17 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E14 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E08 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E07 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E04 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E02 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E01 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E15 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E16 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E10 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 02E13 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E09 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E06 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E05 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E03 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E01 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E02 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E04 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E07 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E08 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E10 from the database
2023-05-12 20:00:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 03E10 from the database
2023-05-12 20:00:18 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 03E08 from the database
2023-05-12 20:00:18 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 03E02 from the database
2023-05-12 20:00:18 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 03E01 from the database
2023-05-12 20:00:18 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 03E07 from the database
2023-05-12 20:00:18 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 03E04 from the database
2023-05-12 20:00:18 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 03E11 from the database
2023-05-12 20:00:18 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 03E05 from the database
2023-05-12 20:00:18 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 03E06 from the database
2023-05-12 20:00:18 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 03E03 from the database
2023-05-12 20:00:18 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 03E09 from the database
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 92, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
2023-05-12 19:59:58 INFO :: SHOWQUEUE-FORCE-UPDATE :: Could not get IMDB info: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt7235466/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': }
2023-05-12 19:59:58 INFO :: SHOWQUEUE-FORCE-UPDATE :: using lxml html builder
2023-05-12 19:59:58 INFO :: SHOWQUEUE-FORCE-UPDATE :: using lxml html builder

**Comment by vtol79** [comment]
The tvdbsimple page function within the Series_Episodes class does not return data for specific episodes.

E.g.:

Adding a print statement to tvdbsimple series.py:
```
--- ../python3.9/site-packages/tvdbsimple/series.py	2023-05-12 23:32:19.929200968 +0200
+++ ../python3.9/site-packages/tvdbsimple/series2.py 2023-05-12 23:31:45.036945899 +0200
@@ -242,6 +242,7 @@
         filters = self._FILTERS.copy()
         filters['page'] = page
         response = self._GET(path, params=filters, cleanJson=False)
+        print(response)
 
         if 'links' in response and 'last' in response['links']:
             self._PAGES = response['links']['last']
```


Getting episode 5:
```
import tvdbsimple as tvdb
tvdb.KEYS.API_KEY = '6aa6e4ecae5b56e9644f6a303c0739b6'
showeps = tvdb.Series_Episodes(260845, airedSeason=2, airedEpisode=5)
response = showeps.all()
for i in response:
    print(i.get('episodeName'))
```

```
{'links': {'first': 1, 'last': 1, 'next': None, 'prev': None}, 'data': None}
```
And yes None is not iterable

**Comment by vtol79** [comment]
Just a guess... 3 months ago they did set the page default to 0 in the official python lib for the get_series_episodes function.
Maybe there was a API change?!

https://github.com/thetvdb/tvdb-v4-python/blob/bd63a9176d8eb5d794920fb39cd79da5419c1349/tvdb_v4_official.py#L196

```
    def get_series_episodes(
        self,
        id: int,
        season_type: str = "default",
        page: int = 0, #<-----
        lang: str = None,
        meta=None,
```

This "fixes" my test issue! ( DO NOT USE IT... WILL MOST LIKELY BREAK THINGS )

```
--- series.py	2023-05-13 00:35:53.312773612 +0200
+++ series.py2y	2023-05-13 00:37:16.441341768 +0200
@@ -240,6 +240,7 @@
             path = self._get_id_path('episodes')
 
         filters = self._FILTERS.copy()
+        page=0
         filters['page'] = page
         response = self._GET(path, params=filters, cleanJson=False)
```

tvdbsimple is outdated?!

**Comment by vtol79** [comment]
I did notice that tvdbsimple is still using the v2 api, has only support for python3.8 (but runs with python3.10) and the last release is from 2019.

**Comment by fanmovies999** [comment]
This issue generates lots of problems.
#7390 
#6933

**Comment by vtol79** [comment]
tvdb will shutdown the legacy APIs mid-late 2023 according to there website anyhow.
If i get it right, the whole thing will completely stop working soon or later.

**Comment by Ventje23** [comment]
Got similar issues. Lot's of show got statuses changed: from e.g. being download in a specific format to unknown. When I delete that show (e.g. Supernatural) and re-add it again a lot of show information is missing that I had before and I got a lot of time-outs from thetvdb. Als when I do a forced full update messages like mentioned above: deleting episodes from db, some episodes get re-added some not and lot's of time-outs from thetvdb again. Looks like when you get time-outs show info is missing.

**Comment by BKSteve** [comment]
same old tvdb bs #7390

**Comment by hvitbardur** [comment]
I'm also having the aforementioned issues with tvdb, which makes me wonder if perhaps there is an alternative to tvdb.

**Comment by vtol79** [comment]
(just my personal opinion)
tvdb is not the issue here, its the dependency to tvdbsimple which is dead since 4 years and reflects the overall code quality.
I switched to sonarr ...

**Comment by xmenxmen** [comment]
Hi.
Synology DSM 7.1
Version: 2023.1.2
Database Version: 44.5
3.10.10 (main, Feb 28 2023, 12:54:52) [GCC 8.5.0]
OpenSSL 1.1.1t 7 Feb 2023
Linux-3.10.108-x86_64-with-glibc2.26

Got the same problem (theTVDB timed out, unable to create the episode)

**Comment by HenriMatthijssen** [comment]
Same problem here. Episodes which were already downloaded (and marked as 'Archived') are randomly set to 'Wanted' and then downloaded again.

**Comment by jrc27** [comment]
It's getting ridiculous on my end....Every morning I wake up with a backlog with well over 100 episodes.  Archiving them hasn't worked, now I'm trying setting them to skipped.  I'm starting to get nasty copyright emails from Verizon 😂

**Comment by LlmDl** [comment]
My two cents:

Shows (I found it was larger shows with 20+ seasons) which have a default episode status of Wanted get updated, causing some of their earlier seasons disappear from the show. The show updates again and the forgotten seasons/episodes re-appear and get set to their default status of wanted, causing them to be re-downloaded.

**Comment by BKSteve** [comment]
tvdbsimple is getting the 1st page of a shows episode data but failing on 2nd page call.

**Comment by DragonEmbers** [comment]
> tvdbsimple is getting the 1st page of a shows episode data but failing on 2nd page call.


It's pretty inconsistent for me. I managed to get the entirity of One Piece (all 1000+ episodes) without a problem then a few minutes after failed to load any of a 12 episode series. One Piece having dropped a whole load of episode details yesterday. It's pretty sparodic so for now I've disabled episode updates until I see some more stability.  FWIW I think with the instability coming from TVDB, (timeouts, connection errors, incomplete/invalid results returned) the behaviour seen matches [LlmDl](https://github.com/LlmDl)'s theory pretty well.

**Comment by DragonEmbers** [comment]
There may be scope in this for SickChill to better handle empty result returns (i.e. don't do anything, just queue it for a later retry). After all, it's highly unlikely anyone is ever going to add a show with ZERO episodes... right???

**Comment by tinyhands01** [comment]
> There may be scope in this for SickChill to better handle empty result returns (i.e. don't do anything, just queue it for a later retry). After all, it's highly unlikely anyone is ever going to add a show with ZERO episodes... right???

Yes and no.  I add "upcoming" shows to my SC list even though nothing beyond the name is yet populated in TVDB.

**Comment by jdstone** [comment]
> There may be scope in this for SickChill to better handle empty result returns (i.e. don't do anything, just queue it for a later retry). After all, it's highly unlikely anyone is ever going to add a show with ZERO episodes... right???

@DragonEmbers, it's possible and probably even likely that someone may add an upcoming show, but the episodes aren't known yet, so it has zero episodes.

**Comment by DragonEmbers** [comment]
Congratulations on the ninja @tinyhands01. I stand corrected, in that case I guess rather than remove known episodes if an empty result set is returned, just silently drop the result set until the next scheduled scrape. I'm not sure how episodes being removed (with valid reason) could be handled though (soft delete followed by a hard delete?).

**Comment by tinyhands01** [comment]
I'm just thinking out loud, but what if updates were handled in a way similar to how Word handles document revision with 'Track Changes' turned on?  Nightly updates from tvdb, rather than being immediately accepted, would go into a queue where the user could accept or reject the update.  Major coding effort?

**Comment by blindman2k** [comment]
It's nice to find a community full of people suffering with the exact same issues as me ... logs full of exceptions, backlogs of old shows filling my download queue in the morning ... etc.

**Comment by miigotu** [comment]
https://discordapp.com/channels/502612977271439372/1108387756880699412
