### ISSUE TITLE
[APP SUBMITTED]: 400 Client Error: Bad Request for url: https://trakt.tv/oauth/token

### ISSUE THREAD

**Issue by linuxbuilds** [SickChill/sickchill#8442]
### INFO
Python Version: **3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]**
Operating System: **Linux-5.15.0-1029-raspi-aarch64-with-glibc2.35**
Locale: UTF-8
Version: **2023.1.2**
No Log available with ERRORS:
### ERROR
```
Could not connect to Trakt. Code error: 400
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by modem** [comment]
You need to re-authorize. I submitted a feature request long ago. See here: https://github.com/SickChill/sickchill/discussions/8245 it contains instructions to force re-authorization manually.

**Comment by miigotu** [comment]
If you need further support, all support and big reports and everything other than code/releases has been moved to discord. https://discord.gg/7yebVwpntc

Please re-add this there in the #bug-reports channel there.
