### ISSUE TITLE
2023.5.24 upgrade failed

### ISSUE THREAD

**Issue by Telecart** [SickChill/sickchill#8449]
Just tried to install Version 2023.5.24 on my Mac mini to attempt to resolve #7390 . Used the updater in the UI, it failed, then tried pip install -U route, and I get this error:
 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/SickChill.py", line 24, in <module>
    from sickchill.movies import MovieList
  File "/usr/local/lib/python3.8/site-packages/sickchill/movies.py", line 14, in <module>
    from .oldbeard.databases import movie
  File "/usr/local/lib/python3.8/site-packages/sickchill/oldbeard/databases/movie.py", line 10, in <module>
    from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship, sessionmaker
ImportError: cannot import name 'DeclarativeBase' from 'sqlalchemy.orm' (/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/__init__.py)
```

Never seen this one before, help?

**Comment by Telecart** [comment]
meanwhile I rolled back sqlalchemy and sickchill to previous versions and loads fine.

**Comment by Telecart** [comment]
Time machine, I just restored sickchill.py, and the two respective folders in /usr/local/lib/python3.8/site-packages/

**Comment by corzocone** [comment]
> meanwhile I rolled back sqlalchemy and sickchill to previous versions and loads fine.

How do I do this? I have sickchill installed via docker/portainer. Thank you!

**Comment by miigotu** [comment]
Using the python sickchill is running with, `pip install -U sqlalchemy`

https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#step-one-orm-declarative-base-is-superseded-by-orm-declarativebase

DeclarativeBase was changed in january, before the last sickchill update. 
https://docs.sqlalchemy.org/en/20/changelog/changelog_20.html#change-2.0.0

**Comment by miigotu** [comment]
> Using the python sickchill is running with, `pip install -U sqlalchemy`
> 
> https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#step-one-orm-declarative-base-is-superseded-by-orm-declarativebase
> 
> DeclarativeBase was changed in january, before the last sickchill update which was in february, which has nothing to do with this week's release. https://docs.sqlalchemy.org/en/20/changelog/changelog_20.html#change-2.0.0

As a matter of fact, sqlalchemy is pinned to SQLAlchemy = ">=2.0.0,<3.0.0" which means you didn't install sickchill at all, or you didn't switch your service to stop using SickChill.py

`File "/usr/local/lib/python3.8/site-packages/SickChill.py",` shows me you are running it incorrectly. 
In that case you should be running `sickchill`, just try running that in your terminal.

**Comment by Telecart** [comment]
I ended up having to switch macs so just finished reinstalling Sickchill under python 3.10 in a new apple silicon mac and so far so good, think we can close this out.

**Comment by rEes9P** [comment]
Hi @miigotu. I ran the command `/usr/local/bin/python3.8 -c 'import site; from pathlib import Path; location = Path(site.USER_BASE) / "bin" / "sickchill"; print(f"Found sickchill at {location}") if location.exists() else print("sickchill not found")'` but got `zsh: no such file or directory: /usr/local/bin/python3.8`

`which python` gives me `/usr/local/opt/python/libexec/bin/python`

So then I tried `/usr/local/opt/python/libexec/bin/python -c 'import site; from pathlib import Path; location = Path(site.USER_BASE) / "bin" / "sickchill"; print(f"Found sickchill at {location}") if location.exists() else print("sickchill not found")'`which resulted in `sickchill not found`

My sickchill install is at _/Users/john_doe/Library/Application Support/sickchill_. I have installed Python via Homebrew on my Mac and `python --version` gives me `Python 3.11.3`.

Could you please tell me how I can proceed?

Also, you mention "updat[ing] your service to call that (lowercase, no .py extension) instead of SickChill.py." I've been running sickchill by simply typing sickchill in Terminal on my Mac ever since the move to the pip install.

**Comment by miigotu** [comment]
Yes all support is now done on discord , including issue reports and everything other than code and releases. https://discord.gg/7yebVwpntc

**Comment by miigotu** [comment]
> **EDIT:** Sorry, just saw that this issue has been closed. I haven't been able to respond earlier and thought it might be better to respond here than to open a new issue and so am leaving the comment here.
> 
> ______________
> 
> Hi @miigotu. I ran the command `/usr/local/bin/python3.8 -c 'import site; from pathlib import Path; location = Path(site.USER_BASE) / "bin" / "sickchill"; print(f"Found sickchill at {location}") if location.exists() else print("sickchill not found")'` but got `zsh: no such file or directory: /usr/local/bin/python3.8`
> 
> `which python` gives me `/usr/local/opt/python/libexec/bin/python`
> 
> So then I tried `/usr/local/opt/python/libexec/bin/python -c 'import site; from pathlib import Path; location = Path(site.USER_BASE) / "bin" / "sickchill"; print(f"Found sickchill at {location}") if location.exists() else print("sickchill not found")'`which resulted in `sickchill not found`
> 
> My sickchill install is at _/Users/john_doe/Library/Application Support/sickchill_. I have installed Python via Homebrew on my Mac and `python --version` gives me `Python 3.11.3`.
> 
> Could you please tell me how I can proceed?
> 
> Also, you mention "updat[ing] your service to call that (lowercase, no .py extension) instead of SickChill.py." I've been running sickchill by simply typing sickchill in Terminal on my Mac ever since the move to the pip install.

You can then `which sickchill` to show sickchill's location, and edit your service script to point there. We can continue on discord to try and solve it.

**Comment by rEes9P** [comment]
> > **EDIT:** Sorry, just saw that this issue has been closed. I haven't been able to respond earlier and thought it might be better to respond here than to open a new issue and so am leaving the comment here.
> > 
> > Hi @miigotu. I ran the command `/usr/local/bin/python3.8 -c 'import site; from pathlib import Path; location = Path(site.USER_BASE) / "bin" / "sickchill"; print(f"Found sickchill at {location}") if location.exists() else print("sickchill not found")'` but got `zsh: no such file or directory: /usr/local/bin/python3.8`
> > `which python` gives me `/usr/local/opt/python/libexec/bin/python`
> > So then I tried `/usr/local/opt/python/libexec/bin/python -c 'import site; from pathlib import Path; location = Path(site.USER_BASE) / "bin" / "sickchill"; print(f"Found sickchill at {location}") if location.exists() else print("sickchill not found")'`which resulted in `sickchill not found`
> > My sickchill install is at _/Users/john_doe/Library/Application Support/sickchill_. I have installed Python via Homebrew on my Mac and `python --version` gives me `Python 3.11.3`.
> > Could you please tell me how I can proceed?
> > Also, you mention "updat[ing] your service to call that (lowercase, no .py extension) instead of SickChill.py." I've been running sickchill by simply typing sickchill in Terminal on my Mac ever since the move to the pip install.
> 
> You can then `which sickchill` to show sickchill's location, and edit your service script to point there. We can continue on discord to try and solve it.

Thanks @miigotu. I've opened a thread on the Discord forum about this.
