### ISSUE TITLE
MTV setup fails

### ISSUE THREAD

**Issue by wokka1** [SickChill/sickchill#8452]
### Discussed in https://github.com/SickChill/sickchill/discussions/8448

<div type='discussions-op-text'>

<sup>Originally posted by **wokka1** May 24, 2023</sup>
morethantv.me has config built into Sickchill, but it's not functioning.  I asked for help on their forums, but no one seems to be actively using it over there (or not reading the forums) and the people who are using other apps than sickchill, indicate we need to use their API to connect.  They do have directions on setting up autodl via RSS, which I've tried, but I'm getting an error from Sickchill and it won't let me save the settings : 
Error when trying to load RSS: a bytes-like object is required, not 'NoneType'

The RSS URL they are having me use has my username/pw encoded into it, but it works properly when I put it into an incognito window and I see the torrents listed.  

I'll attach a screenshot of the XML (no personal data will be shown).

I didn't raise this as an issue, because I don't know if it's a config problem on my end or just an incompatible provider after they've updated things.

![Screen Shot 2023-05-24 at 4 19 38 PM](https://github.com/SickChill/sickchill/assets/1001878/d86212b5-90b2-4e4a-8290-211c107d08e5)
</div>

**Comment by miigotu** [comment]
I literally answered you about this in the discussions thread though

**Comment by wokka1** [comment]
Sorry, I assumed (badly it seems) that you'd want it here for tracking.   Close it out if you prefer or I can.  Thanks!

**Comment by miigotu** [comment]
I just made some changed to make the new mtv api work. It is only in the develop branch for now but once it is in the next release you will do this:

1. Go to https://www.morethantv.me/user/security
2. Generate an api key
3. Go to http://localhost:8081/config/search/ in sickchill (using your domain)
4. Enable NZB support, click save
5. Go to http://localhost:8081/config/providers/ and click the `Configure custom newznab providers` tab
6. Add a new provider with the name morethantv, url https://www.morethantv.me/api/torznab and the api key you generated

Doc: 
https://www.morethantv.me/wiki.php?action=article&id=131
