### ISSUE TITLE
Multiple TV Shows - Mako Error

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/sickchill#8467]
I have noticed that while updating the resolution of TV shows in my library that multiple shows return a mako error when I select them.

I have removed and re-added the shows but the error persists. 
I have forced an update of the shows from mass update but again, no change.
I have enabled debug logging but the corresponding log entry shows little more than mako error. 

I read [elsewhere ](https://github.com/SickChill/sickchill/issues/6304)that this was likely due to a database corruption and that I will likely need to recreated from scratch. I truly hope that this is not the case as I have 1149 shows and in the past I manually verified the quality of each of the episodes.

The shows in question which I have identified so far are: 71324 (Do Not Adjust Your Set) and 76799 (Hammer House of Horror). Both of these exist in the path defined and are accessible in the file system.
Sadly, I've no idea when the corruption was introduced, it could have been during a power cut but I have no was to know when it occurred.

Do you have any recommendation beyond recreating the entire database for how I can reinstate these shows correctly?

Version: latest (installed and updated via pip but doesn't seem to have updated the version number in help & info)
OS: Windows 10
Browser: Any (typically Firefox)
What you did: Selected a TV show
What happened: mako Error
What you expected: To see the TV show
Logs:
```
2023-06-11 14:36:18 INFO :: WEBSERVER-HOME_0 :: A mako error occurred: [Errno 22] Invalid argument
Traceback (most recent call last):
                    File C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\common.py:86, in render:
                        return self.template.render_unicode(*args, **context)
                    File C:\SickChill\Python3\tools\lib\site-packages\mako\template.py:444, in render_unicode:
                        return runtime._render(
                    File C:\SickChill\Python3\tools\lib\site-packages\mako\runtime.py:874, in _render:
                        _render_context(
                    File C:\SickChill\Python3\tools\lib\site-packages\mako\runtime.py:916, in _render_context:
                        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
                    File C:\SickChill\Python3\tools\lib\site-packages\mako\runtime.py:943, in _exec_template:
                        callable_(context, *args, **kwargs)
                    File C:/SickChill/Python3/tools/lib/site-packages/sickchill/gui/slick/views/layouts/main.mako:333, in render_body:
                        <%block name="content" />
                    File C:/SickChill/Python3/tools/lib/site-packages/sickchill/gui/slick/views/displayShow.mako:540, in render_content:
                        ${sbdatetime.sbdatetime.sbfdatetime(airDate)}
                    File C:\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py:222, in utcoffset:
                        if self._isdst(dt):
                    File C:\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py:291, in _isdst:
                        dstval = self._naive_is_dst(dt)
                    File C:\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py:260, in _naive_is_dst:
                        return time.localtime(timestamp + time.timezone).tm_isdst
                OSError: [Errno 22] Invalid argument
```

**Comment by BKSteve** [comment]
**Notice:**
The issue tracker, wiki,and discussions tab on GitHub is going to be archived/disabled in the near future for SickChill. All issues, discussions, support, guides, feature requests, and communication will be handled on discord. Please consider raising your issue there instead.
---

You don't state SC installed version.

**Comment by BKSteve** [comment]
https://discord.com/channels/502612977271439372/502612977803984898/1117661328107126917
Follow the update for windows item. Make a copy of config.ini and *.db for safety if you haven't got a backup. This is a just in case you need to restore but should be ok.
