### ISSUE TITLE
Green announcement message won't go away !

### ISSUE THREAD

**Issue by rd1** [SickChill/sickchill#8468]
fresh windows 10 home x64 (2 weeks ago)
fresh SC installation (with installer)

Using m$ Edge, pure, no extensions

The green message box at the top of SC announcing the Discord news, just won't stay hidden when message [checkbox] is clicked.

it comes back at every page load, page refresh, any button press.

What to do ?

**Comment by BKSteve** [comment]
1. read the banner message and follow the link.
2. read there under `bug reports`

https://discord.com/channels/502612977271439372/1114414269451210762/1114429570381250570
