### ISSUE TITLE
[APP SUBMITTED]: invalid bencoded value (data after valid prefix)

### ISSUE THREAD

**Issue by squozeneu** [SickChill/sickchill#8471]
### INFO
Python Version: **3.10.11 (main, Apr  6 2023, 01:16:54) [GCC 12.2.1 20220924]**
Operating System: **Linux-4.4.249-1.el7.elrepo.x86_64-x86_64-with**
Locale: None
Version: **2023.5.30**
Link to Log: https://gist.github.com/squozeneu/00ebc66b3ebfdc410c36148748e75c27
### ERROR
```
rTorrent: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by squozeneu** [comment]
### INFO
Python Version: **3.10.11 (main, Apr  6 2023, 01:16:54) [GCC 12.2.1 20220924]**
Operating System: **Linux-4.4.249-1.el7.elrepo.x86_64-x86_64-with**
Locale: None
Version: **2023.5.30**
Link to Log: https://gist.github.com/squozeneu/d549e3f2d951cc929edf95a8c29dc1e0
### ERROR
```
Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by truckz** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2023.5.30**
Link to Log: https://gist.github.com/truckz/294fd2fc179f5d7eba1e895b91943e7c
### ERROR
```
Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by truckz** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2023.5.30**
Link to Log: https://gist.github.com/truckz/5a3965a2dea7da4c42b7b55ad4999c17
### ERROR
```
qBittorrent: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Shammy01011101** [comment]
### INFO
Python Version: **3.8.13 (default, Jul 10 2022, 21:54:50) [GCC 7.5.0]**
Operating System: **Linux-3.10.108-armv7l-with-glibc2.4**
Locale: None
Version: **2022.9.28**
No Log available with ERRORS:
### ERROR
```
Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Shammy01011101** [comment]
### INFO
Python Version: **3.8.13 (default, Jul 10 2022, 21:54:50) [GCC 7.5.0]**
Operating System: **Linux-3.10.108-armv7l-with-glibc2.4**
Locale: None
Version: **2022.9.28**
No Log available with ERRORS:
### ERROR
```
DownloadStation: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
https://discord.com/channels/502612977271439372/1119595411422859264/1119724178111742043

**Comment by BKSteve** [comment]
Pleases look on [Discord](https://discord.gg/FXre9qkHwE)

**Comment by pfrenard** [comment]
### INFO
Python Version: **3.10.11 (main, May 23 2023, 09:27:52) [GCC 10.2.1 20210110]**
Operating System: **Linux-6.2.9-200.fc37.aarch64-aarch64-with-glibc2.31**
Locale: UTF-8
Version: **2023.5.30**
Link to Log: https://gist.github.com/pfrenard/466e1caf2e32772fcabb59775dbd29ec
### ERROR
```
Unable to bdecode torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by pfrenard** [comment]
### INFO
Python Version: **3.10.11 (main, May 23 2023, 09:27:52) [GCC 10.2.1 20210110]**
Operating System: **Linux-6.2.9-200.fc37.aarch64-aarch64-with-glibc2.31**
Locale: UTF-8
Version: **2023.5.30**
Link to Log: https://gist.github.com/pfrenard/5866c49e36e665834d961ead1796318d
### ERROR
```
Deluge: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
