### ISSUE TITLE
[APP SUBMITTED]: 'list' object has no attribute 'status'

### ISSUE THREAD

**Issue by offbyone** [SickChill/sickchill#8511]
### INFO
Python Version: **3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]**
Operating System: **Linux-5.10.103-v7l+-armv7l-with-glibc2.36**
Locale: UTF-8
Version: **2023.6.27**
Link to Log: https://gist.github.com/offbyone/01b907db845a248cdeba551f86e0a573
### ERROR
```
Exception generated in thread FINDPROPERS: 'list' object has no attribute 'status'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
Has this resolved itself?
The log provided does not include any lines after the `Exception` were there any?
