### ISSUE TITLE
Updated Ubuntu installation instructions

### ISSUE THREAD

**Issue by SCastleman** [SickChill/sickchill#8543]
Following on from my Discord thread regarding the Ubuntu installation guide being outdated, I've updated it with the steps I followed to resolve the issue. Most of these are just adapted from the install script, with the addition of a couple extra packages declared at step 1, so it should all be OK, but if anyone more familiar with Debian and Python would like to correct anything please do. This all worked on Ubuntu 22.04.3 using Systemd, and should be fine on other LTS versions and for init/upstart variants, but I can't confirm.
As an aside, the remaining Debian/Ubuntu guides should be removed from the wiki - they're all severely outdated and/or deprecated, and just add confusion when trying to find up-to-date steps.

----

The following instructions are for installing SickChill on Ubuntu 14.x 15.x 16.x 18.x 20.x 22.x

The installation is applicable to up to and including Ubuntu 22.04 LTS, The provided script can distinguish the difference between systemd/init/upstart for you.

The installation assumes that you're not using the root user to install/run sickchill - the entries for **user:group** throughout the document will be set as sickchill:sickchill and you will
 have to modify if if you want it to match your user configuration.

If you trust us and would like us to just do it for you just paste this:

```shell
curl https://raw.githubusercontent.com/SickChill/SickChill/master/contrib/debian-ubuntu-install.sh | sudo bash
```

Otherwise:

1. Update repositories and install SickChill dependencies
  This will give you unrar-free (guess) and git to pull the repo, as well as any other requirements for building the package. The name of the `python3-venv` package you need to install may be different to what is listed here - in this case you will be prompted with the updated version at a later step.
  
  ```shell
  sudo apt-get update && sudo apt-get install unrar-free git-core openssl libssl-dev python3 python3-pip python3.10-venv
  ```
  
2. Create sickchill user and group
  This makes sure that sickchill is isolated and is best practice for security
  
  ```shell
  sudo addgroup --system sickchillsudo adduser --disabled-password --system --home /var/lib/sickchill --gecos "SickChill" --ingroup sickchill sickchill
  ```
  
3. Clone SickChill git repo
  
  ```shell
  sudo mkdir /opt/sickchill && sudo chown sickchill:sickchill /opt/sickchillsudo -u sickchill git clone https://github.com/SickChill/SickChill.git /opt/sickchill
  ```
  
4. Set up a Python virtual environment
  
  ```shell
  sudo -u sickchill -g sickchill python3 -m venv /opt/sickchill
  ```
  
5. Install the required dependencies with pip
  
  ```shell
  sudo -u sickchill -g sickchill /opt/sickchill/bin/pip install -U pip setuptools wheel
  ```
  
6. Install SickChill
  
  ```shell
  sudo -u sickchill -g sickchill /opt/sickchill/bin/pip install -U sickchill
  ```
  

For Init Systems

7. Copy init.d service
  
  ```shell
  sudo cp -v /opt/sickchill/runscripts/init.ubuntu /etc/init.d/sickchill
  ```
  
8. Make sure your new service has correct permissions
  
  ```shell
  sudo chown root:root /etc/init.d/sickchillsudo chmod 644 /etc/init.d/sickchill
  ```
  
9. Update and start your new service
  
  ```shell
  sudo update-rc.d sickchill defaultssudo service sickchill start
  ```
  

For Upstart Systems

7. Copy init.d service
  
  ```shell
  sudo cp -v /opt/sickchill/runscripts/init.upstart /etc/init/sickchill.conf
  ```
  
8. Make sure your new service has correct permissions
  
  ```shell
  sudo chown root:root /etc/init/sickchill.confsudo chmod 644 /etc/init/sickchill.conf
  ```
  
9. Update and start your new service
  
  ```shell
  sudo service sickchill start
  ```
  

For Systemd Systems

7. Copy systemd service
  
  ```shell
  sudo cp -v /opt/sickchill/runscripts/init.systemd /etc/systemd/system/sickchill.service
  ```
  
8. Make sure your new service has correct permissions
  
  ```shell
  sudo chown root:root /etc/systemd/system/sickchill.servicesudo chmod 644 /etc/systemd/system/sickchill.service
  ```
  
9. Enable, start, and then check the status of your new service
  
  ```shell
  sudo systemctl enable sickchillsudo systemctl start sickchillsudo systemctl status sickchill
  ```
  

All done, verify that SickChill is accessible at: [http://localhost:8081/](http://localhost:8081)

**Comment by miigotu** [comment]
No need to clone anything, sickchill is installed from pypi with pip. Just create a user for sickchill, change to that user, create a venv, pip install into the venv, create a service definition and set that user and venv/bin/sickchill as the executable.

**Comment by BKSteve** [comment]
see

https://github.com/SickChill/SickChill.WikiTemp/blob/main/SickChill-installation-Debian-Ubuntu-14-15-16.md

**Comment by miigotu** [comment]
Wikitemp has been synced to main wiki now 👍🏼
