### ISSUE TITLE
SickChill Systemd Not Working

### ISSUE THREAD

**Issue by tmdelia** [SickChill/sickchill#8623]
## Notice:
The issue tracker, wiki,and discussions tab on GitHub is going to be archived/disabled in the near future for SickChill. All issues, discussions, support, guides, feature requests, and communication will be handled on [discord](https://discord.gg/FXre9qkHwE). Please consider raising your issue there instead. 

## Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: 2023.6.27
OS: Raspberry Pi 5 - Bookworm
Browser: n/a
What you did: Ran sudo systemctl start sickchill
What happened: Errored out. See log below.
What you expected: Sickchill to start
Logs:
```
No associated log

```
When i try to start Sickchill using systemd nothing happens. This is the systemd sickchill.service file (user and group x'd out for security, but they are correct:

[Unit]
Description=SickChill Daemon
Wants=network-online.target
After=network-online.target

[Service]
User=XXX
Group=XXX

Type=forking
GuessMainPID=no
ExecStart=/opt/sickchill/bin/SickChill --datadir /opt/sickchill --daemon

[Install]
WantedBy=multi-user.target

**Comment by kyuuk** [comment]
did you try running the command `/opt/sickchill/bin/SickChill --datadir /opt/sickchill --daemon` directly using the user configured is the service file ? it might give you a hint for why it's not working

**Comment by tmdelia** [comment]
Thanks for the reply. Same thing happens when I run that command directly as when I try and run it from the systemd - absolutely nothing.

**Comment by miigotu** [comment]
> Thanks for the reply. Same thing happens when I run that command directly as when I try and run it from the systemd - absolutely nothing.

Stop SC and then run that command without the --daemon, there is no cli output when --daemon is passed.

**Comment by tmdelia** [comment]
Thanks for your reply. Worked perfectly when I ran it directly without --daemon, but failed when I tried to run it using systemd without the --daemon using sudo systemctl start sickchill:

Job for sickchill.service failed because the control process exited with error code.
See "systemctl status sickchill.service" and "journalctl -xeu sickchill.service" for details.

**Comment by miigotu** [comment]
In the service file if you remove --daemon you have to change the service type to simple, not forking. 

You also did reload the systemd daemon right?

What's the output of 
"systemctl status sickchill.service" and "journalctl -xe sickchill.service"

**Comment by tmdelia** [comment]
> In the service file if you remove --daemon you have to change the service type to simple, not forking.
> 
> You also did reload the systemd daemon right?
> 
> What's the output of "systemctl status sickchill.service" and "journalctl -xe sickchill.service"

I did reload the systemd daemon by using "systemctl daemon-reload".

systemctl status sickchill.service (as you can see, millisecond safter it starts it stops}:

Nov 16 17:38:26 mediapi systemd[1]: Starting sickchill.service - SickChill Daemon...
Nov 16 17:38:26 mediapi systemd[1]: Started sickchill.service - SickChill Daemon.
Nov 16 17:38:28 mediapi systemd[1]: sickchill.service: Deactivated successfully.
Nov 16 17:38:28 mediapi systemd[1]: sickchill.service: Consumed 1.829s CPU time.

journalctl -xe sickchill.service

Failed to add match 'sickchill.service': Invalid argument
