### ISSUE TITLE
Titles of seasons in search go to spam sites

### ISSUE THREAD

**Issue by cdnninja** [SickChill/sickchill#8625]
When you add a show and click the titles of the options next to the radio button the redirect now takes you to a spam website. This is using the default https://anonym.to/

Example bad URL generated by sickchill. https://anonym.to/?https://thetvdb.com/?tab=series&id=424437&lid=7

**Comment by cdnninja** [comment]
Shouldn't the default be removed as the default is no longer a valid option?

**Comment by BKSteve** [comment]
Having an alternate rather than blank. 

`http://savanttools.com/anon/?`
Or some other?
