### ISSUE TITLE
[APP SUBMITTED]: Resulting JSON from provider is not correct, not parsing it

### ISSUE THREAD

**Issue by itzbolsi** [SickChill/sickchill#8646]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2023.6.27**
Link to Log: https://gist.github.com/itzbolsi/be0e0a2914c3c5ba27084aca5856f526
### ERROR
```
Resulting JSON from provider is not correct, not parsing it
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itzbolsi** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2023.6.27**
No Log available with ERRORS:
### ERROR
```
Resulting JSON from provider is not correct, not parsing it
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itzbolsi** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2024.1.8.post3**
Link to Log: https://gist.github.com/itzbolsi/d04cc9b0b85cca9a4186917ec7b52372
### ERROR
```
Resulting JSON from provider is not correct, not parsing it
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
Line 5
`2024-01-13 19:39:23 INFO :: SEARCHQUEUE-DAILY-SEARCH :: [SceneTime] :: Request failed: 403 Client Error: Forbidden for url: https://www.scenetime.com/browse.php (HTTPError)
`
