### ISSUE TITLE
[APP SUBMITTED]: 'mappingproxy' object does not support item assignment

### ISSUE THREAD

**Issue by hubdows** [SickChill/sickchill#8679]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2024.1.8.post1**
Link to Log: https://gist.github.com/hubdows/dbe6c7e8294100342bf51d5c1d29e197
### ERROR
```
%s: caught exception postprocessing data
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by count00zero** [comment]
This seems closed but I still have the same existing error (python3.11 as well as python3.12):

`2024-01-10 08:21:45,823 ERROR [imdbpy.parser.http.domparser] /home/user/.local/lib/python3.11/site-packages/imdb/parser/http/utils.py:438: DOMHTMLSearchMovieAdvancedParser: caught exception postprocessing data
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/imdb/parser/http/utils.py", line 436, in parse
    data = self.postprocess_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/imdb/parser/http/searchMovieAdvancedParser.py", line 207, in postprocess_data
    data['data'] = []
    ~~~~^^^^^^^^
TypeError: 'mappingproxy' object does not support item assignment
2024-01-10 08:21:45 ERROR :: MAIN :: DOMHTMLSearchMovieAdvancedParser: caught exception postprocessing data
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/imdb/parser/http/utils.py", line 436, in parse
    data = self.postprocess_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/imdb/parser/http/searchMovieAdvancedParser.py", line 207, in postprocess_data
    data['data'] = []
    ~~~~^^^^^^^^
TypeError: 'mappingproxy' object does not support item assignment
2024-01-10 08:21:45 ERROR :: MAIN :: DOMHTMLSearchMovieAdvancedParser: caught exception postprocessing data
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/imdb/parser/http/utils.py", line 436, in parse
    data = self.postprocess_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/imdb/parser/http/searchMovieAdvancedParser.py", line 207, in postprocess_data
    data['data'] = []
    ~~~~^^^^^^^^
TypeError: 'mappingproxy' object does not support item assignment`

**Comment by ServalNator** [comment]
### INFO
Python Version: **3.11.5 (main, Sep  7 2023, 00:07:27) [GCC 8.5.0]**
Operating System: **Linux-4.4.180+-x86_64-with-glibc2.26**
Locale: None
Version: **2024.1.8.post3**
Link to Log: https://gist.github.com/ServalNator/bbd1bf6b89675633d53c1ccbe434b1cc
### ERROR
```
%s: caught exception postprocessing data
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.11.5 (main, Sep  6 2023, 23:34:24) [GCC 8.5.0]**
Operating System: **Linux-4.4.302+-aarch64-with-glibc2.36**
Locale: None
Version: **2024.1.8.post3**
Link to Log: https://gist.github.com/itsme9x/a02feffaaf4a32ab867a4cb6f92eb5f7
### ERROR
```
%s: caught exception postprocessing data
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
### INFO
Python Version: **3.11.5 (main, Sep  6 2023, 23:34:24) [GCC 8.5.0]**
Operating System: **Linux-4.4.302+-aarch64-with-glibc2.36**
Locale: None
Version: **2024.1.8.post3**
No Log available with ERRORS:
### ERROR
```
%s: caught exception postprocessing data
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
@itsme9x please **STOP** pressing the submit button, just **clear** the error message!

**Comment by Cy63rPunk** [comment]
### INFO
Python Version: **3.11.5 (main, Sep  7 2023, 00:07:50) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-3.10.105-x86_64-with-glibc2.20-2014.11**
Locale: None
Version: **2024.1.8.post3**
Link to Log: https://gist.github.com/Cy63rPunk/c0476e921bbf2d882a7e08726d402608
### ERROR
```
%s: caught exception postprocessing data
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by itsme9x** [comment]
> @itsme9x please **STOP** pressing the submit button, just **clear** the error message!

Okey Dokey

**Comment by tvblock** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2024.1.8.post3**
No Log available with ERRORS:
### ERROR
```
%s: caught exception postprocessing data
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by tvblock** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2024.1.31**
No Log available with ERRORS:
### ERROR
```
%s: caught exception postprocessing data
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cjwillis** [comment]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2024.2.2**
Link to Log: https://gist.github.com/cjwillis/ecf6507e30490391cf09ae031dbf353c
### ERROR
```
%s: caught exception postprocessing data
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
Per the log `INFO :: MAIN :: 321541: Unable to find IMDb show info in the database`
Remove show 321541 `The Mask Singer` and add it back again.

**Comment by Sickchilldavid** [comment]
### INFO
Python Version: **3.11.5 (main, Sep  7 2023, 00:07:27) [GCC 8.5.0]**
Operating System: **Linux-4.4.302+-x86_64-with-glibc2.36**
Locale: None
Version: **2024.2.2**
Link to Log: https://gist.github.com/Sickchilldavid/f0210b27e4ea7dbbd48ebe0e10d32db0
### ERROR
```
%s: caught exception postprocessing data
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
