### ISSUE TITLE
Fix for formatting issue on Status page when Added show is present

### ISSUE THREAD

**Issue by crowaust** [SickChill/sickchill#8682]
There has been a formatting bug for a while when you have a recently added show, the Show Queue table would have 7 cells on the added show lines and 6 on the rest of the table. (extra blank cell at the beginning of the row)

I've attached a copy of the original mako file from the distribution and a copy of a version that appears to fix the issue for me. Not sure if this is the best version of a fix though.

Version:
SickChill Info:
Install: [pip](https://dereferer.me/?https://pypi.org/project/sickchill/)
Version: [2024.1.8.post3](https://dereferer.me/?https://github.com/SickChill/SickChill/releases/tag/2024.1.8.post3)
Database Version: 44.2
  Python Version:3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
  OS:Windows-10-10.0.19045-SP0

Browser: Chrome
What you did: 
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

[status - fixed.mako.txt](https://github.com/SickChill/sickchill/files/13887547/status.-.fixed.mako.txt)
[status. original.mako.txt](https://github.com/SickChill/sickchill/files/13887548/status.original.mako.txt)

**Comment by BKSteve** [comment]
Thanks for the input, will tag as low priority as it doesn't cause any actual issues.

**Comment by miigotu** [comment]
@crowaust a diff would be easier for us to see what the issue is
