### ISSUE TITLE
Add show from Most Anticipated Shows

### ISSUE THREAD

**Issue by nickichi84** [SickChill/sickchill#8684]
Version: Latest Version: [2024.1.8.post3]

Database Version: 44.5
Python Version:3.11.6 (main, Oct 4 2023, 06:22:18) [GCC 12.2.1 20220924]
SSL Version:OpenSSL 3.1.4 24 Oct 2023
OS:Linux-5.15.0-91-generic-x86_64-with

OS: Ubuntu Docker 22.04
Browser: Chrome / Chromebook

Logs:  Set to debug but nothing was logged 

When i try to add a new show via the Trackt list webpage, clicking on add show button doesn't send anything to sickchill. If I add it manually via add new show webpage, it will search tvdb as expected and load it into sickchill

**Comment by BKSteve** [comment]
Gets through to render under newShow but fails to perform the add. 
No errors or mako failures probably in the core.js

**Comment by BKSteve** [comment]
The fix is in #8706
