### ISSUE TITLE
[APP SUBMITTED]: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by nazofm** [SickChill/sickchill#8685]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22631-SP0**
Locale: cp1252
Version: **2024.1.8.post3**
Link to Log: https://gist.github.com/nazofm/5814c3b934b60d9f31a6e7f30e9a8526
### ERROR
```
API :: 'list' object has no attribute 'keys'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by nazofm** [comment]
Hey guys, this we caused by trying to use the Sickchill connect  chrome extension to access my sickchill instance. prior to the upgrade it was working fine. Now it does not load any data in the extension

**Comment by 03397** [comment]
I have the exact same issue.
I do not know how this appears.

SickChill Info:
Install: [pip](https://pypi.org/project/sickchill/)
Version: [2024.1.8.post3](https://github.com/SickChill/SickChill/releases/tag/2024.1.8.post3)
Database Version: 44.2
  Python Version:3.10.13 (main, Dec 19 2023, 03:53:10) [GCC 10.2.1 20210110]
  SSL Version:OpenSSL 1.1.1w 11 Sep 2023
  OS:Linux-5.10.60-qnap-x86_64-with-glibc2.31
  Locale:en_US.UTF-8

**Comment by miigotu** [comment]
The coming episodes page is broken

**Comment by BKSteve** [comment]
#8691
