### ISSUE TITLE
[APP SUBMITTED]: could not convert string to float: ''

### ISSUE THREAD

**Issue by itzbolsi** [SickChill/sickchill#8686]
### INFO
Python Version: **3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19045-SP0**
Locale: cp1252
Version: **2024.1.8.post3**
Link to Log: https://gist.github.com/itzbolsi/12729df3bb24bb4b0693e3a040ae7984
### ERROR
```
qBittorrent: Failed Sending Torrent
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
https://discord.com/channels/502612977271439372/1194310821568860170/1194310821568860170

**Comment by itzbolsi** [comment]
@BKSteve link not working. Do i have to join the channel first? If so, which channel?
