### ISSUE TITLE
Zamunda Provider not working

### ISSUE THREAD

**Issue by joncevski** [SickChill/sickchill#8688]
2024-01-14 19:22:24 INFO :: SEARCHQUEUE-BACKLOG-366924 :: [Zamunda] :: No NZB/Torrent providers found or enabled in the sickchill config for backlog searches. Please check your settings.
AA TypeError: Provider.search() got an unexpected keyword argument 'episode_object'
AA ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AA items_list += self.search(search_string, episode_object=episode)
AA File "/opt/sickchill/lib/python3.11/site-packages/sickchill/providers/GenericProvider.py", line 162, in find_search_results
AA ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AA search_results = curProvider.find_search_results(show, episodes, search_mode, manual, downCurQuality)
AA File "/opt/sickchill/lib/python3.11/site-packages/sickchill/oldbeard/search.py", line 459, in search_providers
2024-01-14 19:22:24 ERROR :: SEARCHQUEUE-BACKLOG-366924 :: [Zamunda] :: Exception while searching Zamunda. Error: Provider.search() got an unexpected keyword argument 'episode_object'

**Comment by BKSteve** [comment]
Start with rectifying this
`No NZB/Torrent providers found or enabled in the sickchill config for backlog searches. Please check your settings.`

**Comment by miigotu** [comment]
It's saying none are enabled because that one errored out, I missed removing something in a refactor

**Comment by miigotu** [comment]
@BKSteve sickchill/providers/GenericProvider.py", line 162, remove the episode_object parameter and this one is fixed
