### ISSUE TITLE
[APP SUBMITTED]: [Errno 13] Permission denied: 'V:\\TV Shows\\seaQuest DSV\\seaQuest DSV.S01E04.Treasures of the Mind.mkv'

### ISSUE THREAD

**Issue by Sickchilldavid** [SickChill/sickchill#8690]
### INFO
Python Version: **3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22621-SP0**
Locale: cp1252
Version: **2024.1.8.post3**
Link to Log: https://gist.github.com/Sickchilldavid/80e53625cb6ca2347d8402134419df83
### ERROR
```
There was a problem copying a file from \\10.23.0.6\Torrents\Seaquest.DSV.S01-S03.720p.BluRay.DD5.1.x264-Scene [NO RAR]\Seaquest.DSV.S01.720p.BluRay.DD5.1.x264-Scene\pfa-sq.dsv.s01e04.720p.mkv to V:\TV Shows\seaQuest DSV\seaQuest DSV.S01E04.Treasures of the Mind.mkv. Error: [Errno 13] Permission denied: 'V:\\TV Shows\\seaQuest DSV\\seaQuest DSV.S01E04.Treasures of the Mind.mkv'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Sickchilldavid** [comment]
### INFO
Python Version: **3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.22621-SP0**
Locale: cp1252
Version: **2024.1.8.post3**
Link to Log: https://gist.github.com/Sickchilldavid/ff7fba4436a1e45ecde63dab61e5670d
### ERROR
```
Unable to copy file from \\10.23.0.6\Torrents\Seaquest.DSV.S01-S03.720p.BluRay.DD5.1.x264-Scene [NO RAR]\Seaquest.DSV.S01.720p.BluRay.DD5.1.x264-Scene\pfa-sq.dsv.s01e04.720p.mkv to V:\TV Shows\seaQuest DSV\seaQuest DSV.S01E04.Treasures of the Mind.mkv: [Errno 13] Permission denied: 'V:\\TV Shows\\seaQuest DSV\\seaQuest DSV.S01E04.Treasures of the Mind.mkv'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by BKSteve** [comment]
The user SC is running as doesn't have `Permission` for the folder `V:\\TV Shows\\` per the log.
