### ISSUE TITLE
Episode Status Management not working

### ISSUE THREAD

**Issue by cmdzod** [SickChill/sickchill#8697]
## Notice:
The issue tracker, wiki,and discussions tab on GitHub is going to be archived/disabled in the near future for SickChill. All issues, discussions, support, guides, feature requests, and communication will be handled on [discord](https://discord.gg/FXre9qkHwE). Please consider raising your issue there instead. 

## Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version:  2024.1.8.post3
OS: Windows 10
Browser: Firefox
What you did: Open menu Manage/Episode Status Management => click Manage button
What happened: NOTHING
What you expected: List of episodes Skipped/Wanted/etc
Logs:
```
PASTE LOGS HERE
```

**Comment by BKSteve** [comment]
https://discord.com/channels/502612977271439372/1194668724591017984

Please check Discord before posting
