### ISSUE TITLE
Episode Status Management No Longer Working

### ISSUE THREAD

**Issue by austinstevenson** [SickChill/sickchill#8701]
Version: 2024.1.8.post3
OS: Ubuntu 22.04.3 LTS
Browser: Chrome
What you did: visit /manage/episodeStatuses/ and select any option and click manage
What happened: No results appear
What you expected: Specifically for the Status of Snatched, expected results, especially given the footer says "157  Snatched" 
Logs:
Debug logging did not log anything during recreation.
DB logs show endlessly repeating:
2024-01-29 13:18:50 DB :: WEBSERVER-ERRORLOGS_0 :: sickchill.db: SELECT airdate, status FROM tv_episodes WHERE season > 0 AND episode > 0 AND airdate > 1

**Comment by BKSteve** [comment]
#8697
