### ISSUE TITLE
Trakt API Setting points to deprecated Trakt endpoint

### ISSUE THREAD

**Issue by IRQs** [SickChill/sickchill#8703]
As of today, the old Trakt endpoint http://api-v2launch.trakt.tv is no longer available and has been removed. Trakt advises to use http://api.trakt.tv instead (refer to their official [Tweet](https://twitter.com/traktapi/status/1753116197229670524)).

As far as I can tell, Sickchill still points to the old endpoint. As a result, Trakt notifications no longer work. I assume that in order to fix this issue, the TRAKT_API_URL setting in [settings.py](https://github.com/SickChill/sickchill/blob/f51bc819f79cb5f2194fad2060bbfce8aa91c4ef/sickchill/settings.py#L483) should be adapted accordingly.

**Comment by BKSteve** [comment]
#8705

**Comment by billbo99** [comment]
I think more is needed that just updating the URL to the API,  got these errors after updating to the latest version


AA TypeError: _is_in_show_watchlist() takes 3 positional arguments but 5 were given
AA if not self._is_in_show_watchlist(show.idxr.slug, str(show.indexerid), "0", "0"):
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\traktChecker.py", line 293, in _add_shows_to_trakt_watchlist
AA self._add_shows_to_trakt_watchlist()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\traktChecker.py", line 196, in _sync_watchlists
AA self._sync_watchlists()
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\traktChecker.py", line 35, in run

**Comment by BKSteve** [comment]
https://discord.com/channels/502612977271439372/1207096559049642095
